Repository OpenLiberty/open-liberty, pull requests merged in 2018-09, with the labels that each got.

#4931 Cap unit tests to JDK 8 which rely on legacy cglib ClassImposteriser
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/AttributeToSubjectTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/TAIEncryptionUtilsTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4938 Refactor javac.args.release values
  dev/com.ibm.ws.injection_fat/bnd.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4704 Ignore some FFDCs in Fault Tolerance Async
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/async/QueuedFuture.java
Labels: CLA Signed

#4904 Avoid TCKs creating a top level failure
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#4869 Add optional javax.jws dependency for jaxwsClient-2.2
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxwsClient-2.2.feature
Labels: CLA Signed, in:Web Services, team:Zombie Apocalypse

#4925 Handle TCKs which use JUnit in the same way as those that use TestNG
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics_fat_tck/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.openapi_fat_tck/fat/src/org/eclipse/microprofile/openapi/fat/tck/OpenAPITckTest.java
  dev/com.ibm.ws.microprofile.openapi_fat_tck/fat/src/org/eclipse/microprofile/openapi/fat/tck/ResultsUtil.java
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#4928 Enhance social login code with more OIDC client config options
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/GithubLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/GoogleLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/ClientConstants.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/OAuthLoginFlowTest.java
Labels: CLA Signed, ID reviewed, team:Security SSO

#4807 remove jaxb from testpath of kernel and install project
  dev/com.ibm.ws.install/bnd.bnd
Labels: CLA Signed

#4943 Handle TCKs which use RepeatTests
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#4942 Upgrade ASM api from ASM5 to ASM7_EXPERIMENTAL
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoVisitor.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoVisitor_Annotation.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsVisitor.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/ByteCodeMetaData.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.1.cdi/.project
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/MonitoringProxyActivator.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ClassAvailableHookClassAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ProbeInjectionClassAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ProbeMethodAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/remap/AddVersionFieldClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/CheckInstrumentableClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/DeferConstructorProcessingMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/RasMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/FFDCIgnoreAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/InjectedTraceAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigClassVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigPackageVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceObjectFieldAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceOptionsAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
  dev/com.ibm.ws.request.probes/src/com/ibm/ws/request/probe/bci/internal/RequestProbeClassVisitor.java
Labels: CLA Signed, team:Zombie Apocalypse

#4916 Increased the StringBuffer capacity to 2048 from 512 fror JSON Loggin…
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
Labels: CLA Signed

#4930 Add missing doPriv in unwrap path
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcWrapper.java
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: team:Zombie Apocalypse

#4952 Add optional dependency on javax.activation API for JavaMail features
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.5/com.ibm.websphere.appserver.javaMail-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.6/com.ibm.websphere.appserver.javaMail-1.6.feature
Labels: in:Java EE Platform, team:Zombie Apocalypse

#4933 JSR375: Support Everyone Role
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiRequest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecAnnotatedBasicAuthServlet.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
Labels: CLA Signed, in:Security, release bug, team:Core Security

#4900 Exercised the Http2 Code with increased parallel stream and connection
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/connection/H2Connection.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameData.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/MultiSessionTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Utils.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2TestModule.war/src/http2/test/war/servlets/H2MultiDataFrame.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed

#4937 update oidc common code to use client config when creating the oidccode cookie
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
Labels: CLA Signed

#4961 Upgrading to Johnzon 1.1.8 and giving it full permission in this FAT.
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.packageJsonBWithFeature/server.xml
Labels: in:JAX-RS, team:Wendigo West, test bug

#4951 Add doPriv around call to close socket output stream.
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4886 Add first test in Cloud TX Testsuite
  dev/com.ibm.ws.transaction.cloudsim_fat/.classpath
  dev/com.ibm.ws.transaction.cloudsim_fat/.project
  dev/com.ibm.ws.transaction.cloudsim_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloudsim_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloudsim_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloudsim_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloudsim_fat/bnd.bnd
  dev/com.ibm.ws.transaction.cloudsim_fat/build.gradle
  dev/com.ibm.ws.transaction.cloudsim_fat/com.ibm.ws.transactions.fat.utils.bnd
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/features/txfat-1.0.mf
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD001/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD002/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_FSCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/resources/index.jsp
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/SimpleFS2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/AbortableXAResourceImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/StateKeeper.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/TxTestUtils.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceFactoryImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceFactoryService.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceInfoFactory.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceInfoImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XID.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/package-info.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/ws/cloudtx/ut/util/LastingXAResourceImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/ws/cloudtx/ut/util/TxTestUtils.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/txfat/src/com/ibm/ws/cloudtx/ut/util/package-info.java
  dev/com.ibm.ws.transaction.cloudsim_fat/transaction_fat.bnd
Labels: CLA Signed, noproductcode

#4963 Add internal dependency on JAXB for jsf-2.3 feature for JDK 9+
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
Labels: CLA Signed, team:Zombie Apocalypse

#4947 Create optional JAX-B 2.2 feature which exposes JAX-B API to app classloader
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.1/com.ibm.websphere.appserver.jpaContainer-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.2/com.ibm.websphere.appserver.jpaContainer-2.2.feature
Labels: CLA Signed, team:Zombie Apocalypse

#4919 MYFACES-3629 web fragment fix for jsf-2.2
  dev/com.ibm.ws.jsf.2.2/src/com/ibm/ws/jsf/ext/LibertyWebConfigProvider.java
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/ee6/MyFacesContainerInitializer.java
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/webapp/AbstractFacesInitializer.java
Labels: CLA Signed, in:Web Components, team:Sirius

#4948 Check for ibm.tolerates versions when required feature is not found
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/adaptor/ESAAdaptor.java
Labels: CLA Signed

#4962 Cleanup eclipse settings
  dev/com.ibm.websphere.appserver.features/.classpath
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.cdi.api_fat/.classpath
  dev/com.ibm.ws.clientcontainer.8.0_fat/bnd.bnd
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/.classpath
  dev/com.ibm.ws.config_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.tx_fat/bnd.bnd
  dev/com.ibm.ws.install.map/.classpath
  dev/com.ibm.ws.jbatch.cdi_fat/.classpath
  dev/com.ibm.ws.jbatch.misc_fat/.classpath
  dev/com.ibm.ws.jsf.2.3_fat/.classpath
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsonp_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config_fat/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.1.1.cdi/.project
  dev/com.ibm.ws.threading_policy_fat/.classpath
  dev/com.ibm.ws.webserver.plugin.utility/bnd.bnd
Labels: CLA Signed

#4954 beginRequest and endRequest when aborted from same thread
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/LocalTransactionWrapper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbSpiLocalTransactionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcPreparedStatement.java
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/AbortedException.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/ClosedException.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43Handler.java
Labels: CLA Signed, team:Zombie Apocalypse

#4984 Issue #4983: update JSF 2.3 test class copyright
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23Spec1433.jar/src/com/ibm/ws/jsf23/fat/spec1433/TestBean.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#4979 remove extra debug statement in writeTo() method causing excess cpu usage
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonPProvider.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4988 Issue #4987: Enable jsf 2.3 container ViewHandler test
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
Labels: in:Web Components, team:Sirius

#4986 Add jaxws feature to test servers using javax.xml.ws packages.
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientInvocationTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientSyncInvokerTest/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4780 Fix issue #4414 for feature resolver false conflicts
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverTest.java
  dev/com.ibm.ws.kernel.feature/test/resolverData/lib/features/t7.auto.6-1.0.mf
Labels: CLA Signed

#4924 CWSID0046E error seen after migrating to V9
  dev/com.ibm.ws.messaging.common/resources/com/ibm/ws/sib/processor/CWSIPMessages.nlsprops
  dev/com.ibm.ws.messaging.common/src/com/ibm/websphere/sib/SIRCConstants.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/msgstore/AbstractItem.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/msgstore/MessageStoreConstants.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/cache/links/AbstractItemLink.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/deliverydelay/DeliveryDelayManager.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/deliverydelay/DeliveryDelayable.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/Persistable.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/impl/CachedPersistableImpl.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/objectManager/PersistableImpl.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/objectManager/PersistableMetaData.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/items/MessageItem.java
Labels: CLA Signed, ID reviewed

#5003 Fix com.ibm.ws.transport.http test copyrights
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/dispatcher/internal/HttpDispatcherTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLinkTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/HostAliasTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/HttpEndpointImplTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/HttpProxyRedirectTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/VirtualHostImplTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/VirtualHostMapTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/transport/http2_test/frames/FrameTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/transport/http2_test/headers/HeaderTest.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#4967 close zip file when reacquire fails
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
Labels: CLA Signed, release bug

#4976 Parse java.spec.version as float instead of int
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4994 Disable LDAP endpoint identification for Sun JNDI impl
  dev/fattest.simplicity/src/componenttest/topology/ldap/LocalLDAPServerSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5006 Enabled MicroProfile FAT and renamed related files from version 1.3 t…
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATSuite.java
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/MicroProfile14NoTracer.java
  dev/com.ibm.ws.opentracing.1.1_fat/publish/servers/opentracingFATServer4/server.xml
Labels: CLA Signed, noproductcode

#4957 Issue #4846: Async EJB methods fire during shutdown
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/AsyncMethodWrapper.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/AbstractEJBRuntime.java
  dev/com.ibm.ws.ejbcontainer.session.async_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.session.async_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.session.async_fat/fat/src/com/ibm/ws/ejbcontainer/session/async/fat/AsyncWarnTest.java
  dev/com.ibm.ws.ejbcontainer.session.async_fat/test-applications/AsyncWarnTest.war/src/com/ibm/ws/ejbcontainer/session/async/warn/web/AsyncWarnServlet.java
  dev/com.ibm.ws.ejbcontainer.session.async_fat/test-applications/AsyncWarnTestBean.jar/src/com/ibm/ws/ejbcontainer/session/async/warn/ejb/InitRecoveryLogBean.java
Labels: CLA Signed, in:EJB Container

#4824 assertion moved to before class
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/ServerConfigUpdateTest.java
Labels: CLA Signed, noproductcode

#4841 Modify test code to avoid concurrentModificationException
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Sirius

#5014 Add javax.activation APIs to list of exposed APIs in JAXB optional fe…
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
Labels: CLA Signed, team:Zombie Apocalypse

#5007 4871 4872 fix metrics monitor fat
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#5038 Updates to LibertyServer in FAT framework
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LogMonitor.java
Labels: CLA Signed, team:Security SSO

#5040 copy SSL properties before the get modified
  dev/com.ibm.ws.jaxws.security/src/com/ibm/ws/jaxws/security/internal/JaxWsSSLManager.java
Labels: CLA Signed, team:Core Security

#5013 List convenience features as singletons
  dev/com.ibm.websphere.appserver.features/visibility/public/javaee-7.0/com.ibm.websphere.appserver.javaee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaee-8.0/com.ibm.websphere.appserver.javaee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-7.0/com.ibm.websphere.appserver.javaeeClient-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-8.0/com.ibm.websphere.appserver.javaeeClient-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.0/com.ibm.websphere.appserver.microProfile-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.2/com.ibm.websphere.appserver.microProfile-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.3/com.ibm.websphere.appserver.microProfile-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/com.ibm.websphere.appserver.microProfile-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/com.ibm.websphere.appserver.microProfile-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-7.0/com.ibm.websphere.appserver.webProfile-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-8.0/com.ibm.websphere.appserver.webProfile-8.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#4995 make XADataSource default for jdbc-4.3 feature and above
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#5012 data source wrapper for jdbc 4.3
  dev/com.ibm.ws.jdbc.4.0.feature/src/com/ibm/ws/jdbc/osgi/v40/JDBC40Runtime.java
  dev/com.ibm.ws.jdbc.4.1.feature/src/com/ibm/ws/jdbc/osgi/v41/JDBC41Runtime.java
  dev/com.ibm.ws.jdbc.4.2.feature/src/com/ibm/ws/jdbc/osgi/v42/JDBC42Runtime.java
  dev/com.ibm.ws.jdbc.4.3.feature/src/com/ibm/ws/jdbc/osgi/v43/JDBC43Runtime.java
  dev/com.ibm.ws.jdbc.4.3/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43DataSource.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/osgi/JDBCRuntimeVersion.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.java
Labels: CLA Signed, team:Zombie Apocalypse

#5052 Change DHE repository to new URL
  dev/settings.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#5057 Fix the top-level help message for securityUtility.
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
Labels: CLA Signed

#5015 Issue4990 fix ffdc in long stress runs
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
Labels: CLA Signed

#5061 Add New Swid Tag for OpenLiberty
  dev/build.image/build.gradle
  dev/build.image/publish/openliberty.io_OpenLiberty-@VERSION@.swidtag
Labels: CLA Signed

#5044 Create runtime update fat in open liberty
  dev/com.ibm.ws.runtime.update_fat/.classpath
  dev/com.ibm.ws.runtime.update_fat/.gitignore
  dev/com.ibm.ws.runtime.update_fat/.project
  dev/com.ibm.ws.runtime.update_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.runtime.update_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.runtime.update_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.runtime.update_fat/bnd.bnd
  dev/com.ibm.ws.runtime.update_fat/build.gradle
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/ConfigUpdateDeliveryTest.java
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/FATSuite.java
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/RuntimeQuiesceTest.java
  dev/com.ibm.ws.runtime.update_fat/publish/features/quiescelistener-1.0.mf
  dev/com.ibm.ws.runtime.update_fat/publish/files/bad-quiesce-listener.server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/local-connector-server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/longrunning-quiesce-listener.server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/no-quiesce-listener.server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/quiesce-listener.server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/user-quiesce-listener.server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/servers/com.ibm.ws.runtime.quiesce.fat/bootstrap.properties
  dev/com.ibm.ws.runtime.update_fat/publish/servers/com.ibm.ws.runtime.quiesce.fat/server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/servers/com.ibm.ws.runtime.update.fat/bootstrap.properties
  dev/com.ibm.ws.runtime.update_fat/publish/servers/com.ibm.ws.runtime.update.fat/server.xml
  dev/com.ibm.ws.runtime.update_fat/runtime.update.fat.bnd
  dev/com.ibm.ws.runtime.update_fat/test-applications/mbean/resources/META-INF/permissions.xml
  dev/com.ibm.ws.runtime.update_fat/test-applications/mbean/resources/WEB-INF/web.xml
  dev/com.ibm.ws.runtime.update_fat/test-applications/mbean/src/web/MBeanServlet.java
  dev/com.ibm.ws.runtime.update_fat/test-bundles/test.server.quiesce/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.runtime.update_fat/test-bundles/test.server.quiesce/src/test/server/quiesce/TestQuiesceListener.java
  dev/com.ibm.ws.runtime.update_fat/test.server.quiesce.bnd
Labels: CLA Signed, noproductcode

#5059 Timed removal of EarlyMessageQueue and EarlyTraceQueue from BaseTraceService
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#5073 Update eclipse settings for new components
  dev/com.ibm.ws.runtime.update_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social_fat/.project
  dev/com.ibm.ws.security.social_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#5063 Added a recursion counter for the trace writer, when trace is written…
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#5067 Update old DSA signed certs to use RSA algorithm
  dev/build.sharedResources/usrShared/resources/security/key.jks
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClientSecurity/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.clientcert.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.anno.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authalias.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authdata.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.nouser.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.shortname.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.immediate.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ejb.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.jaxrs.fat/resources/security/key.jks
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5083 Revert "Add New Swid Tag for OpenLiberty "
  dev/build.image/build.gradle
  dev/build.image/publish/openliberty.io_OpenLiberty-@VERSION@.swidtag
Labels: CLA Signed

#5084 Revert "Update ClassLoadingService to depend on PermissionManager instead of the other way around for issue #1438"
  dev/com.ibm.ws.classloading/bnd.bnd
  dev/com.ibm.ws.classloading/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading_test/bnd.bnd
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/TestUtil.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/security/PermissionsCombiner.java
  dev/com.ibm.ws.security.java2sec/bnd.bnd
  dev/com.ibm.ws.security.java2sec/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.security.java2sec/src/com/ibm/ws/security/java2sec/JavaPermissionsConfiguration.java
  dev/com.ibm.ws.security.java2sec/src/com/ibm/ws/security/java2sec/PermissionManager.java
  dev/com.ibm.ws.security.java2sec/test/com/ibm/ws/security/java2sec/PermissionManagerTest.java
Labels: CLA Signed

#4929 Throw RepositoryArchiveException on NoSuchFileException
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/ParserBase.java
Labels: CLA Signed, team:Zombie Apocalypse

#5041 Add Saaj-impl and mimepull to jaxws when running on java 9+
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.classpath
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.project
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.settings/bndtools.core.prefs
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/bnd.bnd
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/bnd.overrides
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/build.gradle
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/com.ibm.ws.org.jvnet.mimepull/.classpath
  dev/com.ibm.ws.org.jvnet.mimepull/.project
  dev/com.ibm.ws.org.jvnet.mimepull/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.jvnet.mimepull/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.jvnet.mimepull/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.jvnet.mimepull/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.jvnet.mimepull/bnd.bnd
  dev/com.ibm.ws.org.jvnet.mimepull/bnd.overrides
  dev/com.ibm.ws.org.jvnet.mimepull/build.gradle
Labels: CLA Signed, team:Zombie Apocalypse

#4972 MP Rest Client 1.1 TCK default test to EE7, but still test with EE8
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/servers/FATServer/server.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#5086 Add JAX-B API and Impl as a dependency for opentracing FATs
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATOpentracing.java
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATSuite.java
  dev/com.ibm.ws.opentracing.1.1_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATOpentracing.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATSuite.java
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
Labels: noproductcode, team:Zombie Apocalypse

#5093 Removed special characters from comments
  dev/com.ibm.ws.security.social/src/com/ibm/websphere/security/social/UserProfile.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Needed, CLA trivial

#5090 Disable ldap endpoint identificiation for JDK 10+
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/jvm.options
Labels: CLA Signed, in:Security, noproductcode, team:Zombie Apocalypse

#5091 Remove JAX-B dependency in http2_fat
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Zombie Apocalypse

#5095 create connection builders for mock JDBC 4.3 driver
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43CommonDataSource.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43ConnectionBuilder.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43ConnectionPoolDataSource.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43DataSource.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43Driver.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43Handler.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43PooledConnectionBuilder.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43ShardingKey.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43ShardingKeyBuilder.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43XAConnectionBuilder.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43XADataSource.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5081 Fix NPE in JWKRetriever
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
Labels: CLA Signed, team:Security SSO

#5096 Fix NPE in servlet cleanup for WebSocket request
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#5062 pull request to update trace in OidcClientHttpUtil
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
Labels: CLA Signed, team:Security SSO

#5066 Capture global shared library contents in CLS dump introspector
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/ClassLoaderConfigHelper.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#5037 Removed Work Around from Security FVT Servers
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#5030 New test for plain socket timeout (not using JAX-RS client)
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5115 abort method must guarantee state transition
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyTaskFutureImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#5101 Remove DataTypeConverter refs in http2_fat
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5097 Add jaxb and activation apis to rest client tck fats
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5113 Add JAX-B to JSF Container Servers
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.beanval/server.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.cdi/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#4981 Add oidc client userinfo endpoint support
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/common/Constants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelperTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/websphere/security/social/UserProfile.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAISubjectUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/UserProfileTest.java
Labels: CLA Signed, ID reviewed

#5107 Add JAX-B to Metrics 1.1 TCK FATS
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5098 Update Saaj config policy
  dev/com.ibm.ws.com.sun.xml.messaging.saaj/bnd.overrides
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5112 Remove CORBA dependency from com.ibm.ws.install
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/FeatureDependencyChecker.java
Labels: CLA Signed, team:Zombie Apocalypse

#5010 Issue #4882 - update release version to 18.0.0.4
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#5111 cache contenttype
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: CLA Signed

#5108 Update security FAT infra to allow immediate expectations
  dev/com.ibm.ws.security.fat.common/keystores/rsa_key.jks
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonSecurityFat.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectations.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ServerMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/validation/TestValidationUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonSpecificExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ServerMessageExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/validation/TestValidationUtilsTest.java
Labels: CLA Signed, team:Security SSO

#5122 Write fail.log in well-known location to match non-TCK FAT behavior
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: in:Test Infrastructure, team:Zombie Apocalypse, test bug

#5129 Remove OnlyRunInJava7Rule and related rules
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuiteCDI12WithJava7.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/AutoApplySessionTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/ProgrammaticTest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/AlwaysPassesTest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/NoOpTestForOldJava7.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/OnlyRunInIBMJava7ForMultitenancyRule.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/OnlyRunInJava7Rule.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#4971 Issue #4970: Remove serverTTLAttribute from ldapRegistry-3.0
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ConfigConstants.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATTestAD.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATTestIDS_allIbmGroups.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/InputOutputMappingTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPReferralTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryContextPoolNoConfigTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryDynamicUpdateTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryNoCustomContext.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/SearchPagingTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_RealmPropertyMappingTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/AttributesCache.java
Labels: CLA Signed, team:Wendigo East

#5118 Ensure firstTimeout for Persistent Calendar timer is rounded to seconds
  dev/com.ibm.ws.ejbcontainer.timer.persistent/src/com/ibm/ws/ejbcontainer/timer/persistent/osgi/internal/PersistentTimerTaskHandlerImpl.java
Labels: CLA Signed

#5130 Issue 5076: null check on aclStore
  dev/com.ibm.ws.classloading/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#5142 remove erroneous assertion from testActionlessFutureWithSpecifiedExecutor
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5138 update constants
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ClientConstants.java
Labels: CLA Signed

#5137 Create two jwks by default
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKProviderTest.java
Labels: CLA Signed

#5151 Fix copyrights
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/ConfigUpdateDeliveryTest.java
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/FATSuite.java
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/RuntimeQuiesceTest.java
  dev/com.ibm.ws.runtime.update_fat/test-applications/mbean/src/web/MBeanServlet.java
  dev/com.ibm.ws.runtime.update_fat/test-bundles/test.server.quiesce/src/test/server/quiesce/TestQuiesceListener.java
Labels: CLA Signed, noproductcode

#5120 Update JWK code to support getting key by use entry
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtilTest.java
Labels: CLA Signed, team:Security SSO

#5139 use builders to create connections with sharding keys
  dev/com.ibm.ws.jdbc.4.0.feature/src/com/ibm/ws/jdbc/osgi/v40/JDBC40Runtime.java
  dev/com.ibm.ws.jdbc.4.1.feature/src/com/ibm/ws/jdbc/osgi/v41/JDBC41Runtime.java
  dev/com.ibm.ws.jdbc.4.2.feature/src/com/ibm/ws/jdbc/osgi/v42/JDBC42Runtime.java
  dev/com.ibm.ws.jdbc.4.3.feature/src/com/ibm/ws/jdbc/osgi/v43/JDBC43Runtime.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43DataSource.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/osgi/JDBCRuntimeVersion.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSConnectionRequestInfoImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43Handler.java
Labels: CLA Signed, team:Zombie Apocalypse

#5150 Add testPingFrameBadFlags to the full tracing bucket to get more debug
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
Labels: CLA Signed, noproductcode, team:Sirius

#5147 Issue #5136: Avoid Loading CORBA classes if remote EJB is not enabled
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
Labels: CLA Signed

#5005 Run jaxrs-2.0 CDI and Client tests with the jaxrs-2.1 feature
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/CheckCDIFeature.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuiteCDI12WithJava7.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuiteLite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/AbstractTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRSLtpaServerTest/server.xml
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/service/ServerEndpointControlMBeanTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPITestUtil.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigActuatorXMLOverrideTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigServerXMLOverrideTests.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpEndpoint.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfigurationFactory.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5133 Rework JPA Diagnostic Dump
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAApplInfo.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAIntrospection.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPxmlInfo.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAScopeInfo.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/JPAORMDiagnostics.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/ormparser/EntityMappingsDefinition.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/ormparser/EntityMappingsFactory.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/puscanner/PersistenceUnitScanner2.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/puscanner/PersistenceUnitScannerResults2.java
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
Labels: CLA Signed, in:JPA, priority/medium, team:Blizzard

#4552 Dynamic Update for File Refresh Command
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/FileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.config/bnd.bnd
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigFileMonitor.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/FileMonitor.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/FileNotification.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/FileNotificationMBean.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/FileNotificationImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/MonitorHolder.java
  dev/com.ibm.ws.kernel.filemonitor/test/com/ibm/ws/kernel/filemonitor/internal/MonitorHolderTestParent.java
Labels: CLA Needed

#5165 connection builder cannot allow sharding key when backed by java.sql.Driver
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43ConnectionBuilder.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43DataSource.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#5170 Update eclipse settings for .classpath
  dev/com.ibm.ws.app.manager_fat/.classpath
  dev/com.ibm.ws.security.fat.common.social/.classpath
Labels: CLA Signed, noproductcode

#5155 Clear queued actions when an app is removed
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
Labels: CLA Signed

#5173 Add Java permissions for test using plain Java sockets to connect.
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/publish/servers/jaxrs20.cxfClientProps/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5152 Support zip files in BOOT-INF/lib regardless of the extension
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/LibIndexCache.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/EmbeddedContainerTest.java
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/LibIndexCreateTest.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NonZipExtensionFilesInBootInfLibTests.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/tasks/ThinAppTaskTest.java
Labels: CLA Signed

#5171 Add additional OIDC certification tests for social login feature
  dev/com.ibm.ws.security.fat.common.social/src/com/ibm/ws/security/fat/common/social/MessageConstants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/MessageConstants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtilsTest.java
  dev/com.ibm.ws.security.social_fat.oidcCertification/fat/src/com/ibm/ws/security/social/fat/oidc/certification/Constants.java
  dev/com.ibm.ws.security.social_fat.oidcCertification/fat/src/com/ibm/ws/security/social/fat/oidc/certification/OidcCertificationRPBasicProfileTests.java
  dev/com.ibm.ws.security.social_fat.oidcCertification/publish/shared/config/oidcCertification_oidcLoginConfigs.xml
Labels: CLA Signed, team:Security SSO

#5174 Throws WIMSystemException when userfilter does not have %v
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
Labels: CLA Signed, team:Wendigo East

#5163 moved resetHandlerInfo
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
  dev/com.ibm.ws.security.authorization.jacc.ejb/src/com/ibm/ws/security/authorization/jacc/ejb/impl/EJBSecurityValidatorImpl.java
Labels: CLA Signed, release bug

#5191 Update local build instructions
  README.md
Labels: CLA Signed, team:Zombie Apocalypse

#5182 Issue #5181 - disable testBulkheadQueReplacesDueToClassRetryFailures
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#5127 Tolerate PRIORITY frames received in any stream state and better handle flow control problems
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/FrameReadProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/priority/Tree.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http2/upgrade/H2Exception.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/FileServletWrapper.java
Labels: CLA Signed, in:Transport, team:Sirius

#5176 suppress begin/endRequest when invoked by application or external connection manager
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43Connection.java
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/AdapterUtil.java
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/JDBC43Test.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#5190 DelayInvalidationAlarmDuringServerStartup default to 5 seconds
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
Labels: CLA Signed

#5175 Upgrade to arquillian-liberty-managed v1.0.3
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing.1.1_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#5192 Add removed JDK dependencies to jaxwsClient-2.2 feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxwsClient-2.2.feature
Labels: CLA Signed, in:Web Services, team:Zombie Apocalypse

#5200 Tolerate missing binary warning
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
Labels: CLA Signed, noproductcode

#5185 changed to allow for japanese locoale to not be truncated
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/writer/PrometheusMetricWriter.java
Labels: CLA Signed

#5179 remove hardcoded port in mpjwt 1.1 tck fat
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_noenv.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_noenv2.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#4977 Externalize multiple http/tcp option documentation
  dev/com.ibm.ws.channelfw/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.channelfw/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/TCPChannelConfiguration.java
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
Labels: ID Required, ID reviewed, release bug

#5204 increase problamatic jaxrs timeouts from 100ms to 1000ms
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLProxyAuthTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5187 Added Java permissions
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin_SBInFilter/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/server.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#5167 Fix AfterTypeDiscoveryTest and EnablingBeansXmlValidationTest
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AfterTypeDiscoveryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/BuildShrinkWrap.java
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/ShrinkWrapSharedServer.java
Labels: CLA Signed, noproductcode, team:MicroProfileUK

#5159 4688 provide optional
  dev/com.ibm.ws.microprofile.config.cdi/src/com/ibm/ws/microprofile/config/cdi/ConfigCDIExtension.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/suite/SharedShrinkWrapApps.java
  dev/com.ibm.ws.microprofile.config_fat/test-applications/cdiConfig.jar/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.microprofile.config_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/beans/ConfigPropertyBean.java
  dev/com.ibm.ws.microprofile.config_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/ConfigPropertyTestServlet.java
Labels: CLA Signed

#5219 Revert "Shutdown improvements"
  dev/com.ibm.ws.channelfw/src/com/ibm/websphere/channelfw/ChannelUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/channelfw/internal/UtilsChainListener.java
  dev/com.ibm.ws.concurrency.policy/bnd.bnd
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/MonitorHolder.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/scan/ScanningCoreServiceImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
  dev/com.ibm.ws.runtime.update/bnd.bnd
  dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/PauseableComponentQuiesceListener.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
  dev/com.ibm.ws.runtime.update_fat/fat/src/com/ibm/ws/runtime/update/fat/RuntimeQuiesceTest.java
  dev/com.ibm.ws.runtime.update_fat/publish/files/longrunning-threads-server.xml
  dev/com.ibm.ws.runtime.update_fat/publish/files/non-blocking-threads-server.xml
  dev/com.ibm.ws.runtime.update_fat/test-bundles/test.server.quiesce/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.runtime.update_fat/test-bundles/test.server.quiesce/src/test/server/quiesce/TestQuiesceListener.java
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutorProvider.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ThreadQuiesce.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/bnd.bnd
Labels: CLA Signed

#5208 Ph03014 cxfupdate
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
Labels: CLA Signed

#5203 Issue #5202 - reduce MBean client timeout
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#5211 Exclude tools.jar as a maven dependency for JDK 9+
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5178 4135 MyFaces 2.3.2 update
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/build.xml
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/bean/package-info.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIWebsocket.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UIWebsocket.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/behavior/FacesBehavior.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/search/SearchExpressionContextFactory.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/FacesValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/FaceletCache.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/FaceletContext.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ConverterValidatorBehaviorInjectionTarget.war/resources/JSFArtifactsInjection.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ConverterValidatorBehaviorInjectionTarget.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ConverterValidatorBehaviorInjectionTarget.war/src/com/ibm/ws/jsf23/fat/converter/validator/behavior/injection/beans/JSFArtifactsInjectionBean.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ConverterValidatorBehaviorInjectionTarget/resources/JSFArtifactsInjection.xhtml
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ConverterValidatorBehaviorInjectionTarget/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ConverterValidatorBehaviorInjectionTarget/src/com/ibm/ws/jsf23/fat/converter_validator/beans/JSFArtifactsInjectionBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ApplicationImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/model/DataModelBuilderProxy.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/component/search/SearchExpressionContextFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/push/WebsocketComponentRenderer.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/renderkit/html/HtmlLabelRenderer.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/HtmlGroupRendererBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/HtmlResponseWriterImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/util/HTMLEncoder.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/resource/ResourceValidationUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/util/FastWriter.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/util/CDataEndEscapeFilterWriter.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/compiler/CheckDuplicateIdFaceletUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/util/FastWriter.java
Labels: CLA Signed, in:Web Components, team:Sirius

#5226 test connection sharing according to MatchCurrentState with sharding
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/JDBC43Test.java
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5225 Issue #4135: enable testSpecIssue790Test1
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#5223 Common security FAT: Implement JsonObjectExpectation
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/validation/TestValidationUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonExpectationTestClass.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectationTest.java
Labels: CLA Signed, team:Security SSO

#5224 Issue-4681-RemoveJaxbFromSpringBootFeatures
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.springBootHandler-1.0.feature
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/AuthData.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/ConfigElement.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/ConfigMonitorElement.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/ConnectionManager.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/File.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/Fileset.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/Folder.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/HttpEndpoint.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/HttpOptions.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/HttpSession.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/JspEngineElement.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/KeyEntry.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/KeyStore.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/Logging.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/OutboundConnection.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/SSLConfig.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/ServerConfiguration.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/SslOptions.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/TcpOptions.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/Variable.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/VirtualHost.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/WebContainerElement.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/ServerConfigurationWriter.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
Labels: CLA Signed, in:SpringBoot, team:OSGi Infrastructure

#4000 Remove version from artifact path in stub .classpath files
  dev/cnf/build.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#5232 Delay Invalidation Alarm During Server Startup and update failure test
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
Labels: CLA Signed

#5195 refactor usage of set/getSourceType to set/getSourceName
  dev/com.ibm.ws.collector.manager/src/com/ibm/ws/logging/ffdc/source/FFDCSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/source/AccessLogSource.java
Labels: CLA Signed

#5236 Use more performant regex to search logs for errors and warnings
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse
