Repository OpenLiberty/open-liberty, pull requests merged in 2018-02, with the labels that each got.

#1990 Issue #1936 - delete com.ibm.ws.com.netflix.archaius
  dev/com.ibm.ws.com.netflix.archaius/.classpath
  dev/com.ibm.ws.com.netflix.archaius/.gitignore
  dev/com.ibm.ws.com.netflix.archaius/.project
  dev/com.ibm.ws.com.netflix.archaius/.settings/bndtools.core.prefs
  dev/com.ibm.ws.com.netflix.archaius/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.com.netflix.archaius/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.com.netflix.archaius/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.com.netflix.archaius/bnd.bnd
  dev/com.ibm.ws.com.netflix.archaius/bnd.overrides
Labels: CLA Signed

#2072 mpOpenAPI validation and Reader fixes
  dev/com.ibm.ws.microprofile.openapi/resources/com/ibm/ws/microprofile/openapi/impl/validation/resources/ValidationMessages.nlsprops
  dev/com.ibm.ws.microprofile.openapi/resources/com/ibm/ws/microprofile/openapi/resources/OpenAPI.nlsprops
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ApplicationProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ConfigProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OpenAPIServlet.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/core/jackson/ModelResolver.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/core/util/AnnotationsUtils.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/Reader.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/util/ReaderUtils.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/SchemaImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/parser/util/OpenAPIDeserializer.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/PathItemValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/ValidatorUtils.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/OpenAPIModelWalker.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/ProxySupportUtil.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/ServerInfo.java
  dev/com.ibm.ws.microprofile.openapi_test/test/com/ibm/ws/microprofile/openapi/validation/test/CallbacksValidatorTest.java
Labels: CLA Signed, ID reviewed

#2088 test cache entry per session property
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/CacheEntryPerSessionPropertyTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/CacheEntryPerSessionTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/MultiServerCacheEntryPerSessionPropertyTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/MultiServerCacheEntryPerSessionTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServer/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2097 Throw IllegalStateException when SseEventSink is closed (per Javadoc).
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#2115 Improve build times with publishFeatureResources
  dev/cnf/gradle/scripts/tasks.gradle
Labels: team:Continuous Delivery

#2078 Do not instrument repository client project
  dev/com.ibm.ws.repository/bnd.bnd
Labels: CLA Signed

#2061 Allow the SingleFileClient to accept and discard attachments
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/SingleFileClient.java
Labels: CLA Signed

#2049 fix FlowScopeBeanHolder serialization compatibility
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/flow/cdi/FlowScopeBeanHolder.java
Labels: CLA Signed

#2117 PR for issue 2116: Pull MYFACES4197 and MYFACES4198
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/util/ClassUtils.java
Labels: CLA Signed

#2133 Revert "Improve build times with publishFeatureResources (#2115)"
  dev/cnf/gradle/scripts/tasks.gradle
Labels: CLA Signed, noproductcode

#2121 Re-enable 'name' attr in @BatchProperty qualifier
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/src/app/beans/AbstractBean.java
Labels: CLA Signed, noproductcode

#2137 Update new components to have the right settings for eclipse.
  dev/com.ibm.ws.ejbcontainer.cdi_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.cdi_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.install.utility.installUtility/.classpath
  dev/com.ibm.ws.install.utility.installUtility/.classpath.gradle
  dev/com.ibm.ws.install.utility.installUtility/.settings/bndtools.core.prefs
  dev/com.ibm.ws.install.utility.installUtility/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.install/.classpath
  dev/com.ibm.ws.install/.classpath.gradle
  dev/com.ibm.ws.install/.settings/bndtools.core.prefs
  dev/com.ibm.ws.install/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#2138 Reapply improve build times with publishFeatureResources
  dev/build.image/build.gradle
  dev/cnf/gradle/scripts/tasks.gradle
Labels: team:Continuous Delivery

#2129 Incorporate improvements to CWPKI0817A
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
Labels: CLA Signed, ID reviewed, in:Security, in:Transport

#2136 update test case to cover getAttributeNames
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2058 JSR375:removing unused HAMs
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtensionTest.java
Labels: CLA Signed, in:Security, team:Core Security

#2142 nlsprops files for Jandex
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages.nlsprops
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.app.manager/resources/com/ibm/ws/app/manager/internal/resources/AppManagerMessages.nlsprops
Labels: CLA Signed, ID reviewed

#1998 http2 bugfixes
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLAlpnNegotiatorJdk8.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameHeaders.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePriority.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/hpack/H2Headers.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/hpack/HpackConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: CLA Signed

#2141 Only enable java security if server is not exempt
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode

#2123 Move to use jaxb-2.2 feature instead of JRE JAXB to bypass j2sec failure
  dev/com.ibm.ws.jbatch.cdi_fat/publish/servers/CDIBatch/server.xml
Labels: CLA Signed, noproductcode

#2150 Close sink on exception
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
Labels: in:JAX-RS, team:Wendigo West

#2094 Early implementation of CXF PR https://github.com/apache/cxf/pull/379
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ConfigurationImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientConfigurableImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#2143 Fix batch runtime table version determination
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
Labels: CLA Signed

#2166 Move MP openapi_test into the MP openapi component
  dev/com.ibm.ws.microprofile.openapi/.classpath
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/test/utils/TestValidationContextHelper.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/test/utils/TestValidationHelper.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/CallbacksValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ComponentsValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ContactValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/DiscriminatorValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ExampleValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ExtensionValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ExternalDocumentationValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/HeaderValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/InfoValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/LicenseValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/MediaTypeValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OAuthFlowValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OAuthFlowsValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OpenAPIRuntimeExpressionTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OpenAPIValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OperationValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ParameterValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/PathsValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ReferenceValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/RequestBodyValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ResponseValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ResponsesValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/SchemaValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/SecurityRequirementValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/SecuritySchemeValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ServerValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ServerVariableValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ServerVariablesValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/TagValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi_test/.classpath
  dev/com.ibm.ws.microprofile.openapi_test/.project
  dev/com.ibm.ws.microprofile.openapi_test/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.openapi_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.openapi_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.openapi_test/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.openapi_test/bnd.bnd
Labels: CLA Signed

#2175 Fix ConcurrentModificationException during app startup
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
Labels: CLA Signed

#2120 Handle re-usable field for MicroProfile Metrics
  dev/com.ibm.ws.microprofile.metrics.1.1.cdi/src/com/ibm/ws/microprofile/metrics11/cdi/MetricResolver11.java
  dev/com.ibm.ws.microprofile.metrics.cdi/src/io/astefanutti/metrics/cdi/MetricResolver.java
  dev/com.ibm.ws.microprofile.metrics.cdi/src/io/astefanutti/metrics/cdi/MetricsExtension.java
  dev/com.ibm.ws.microprofile.metrics.cdi/src/io/astefanutti/metrics/cdi/MetricsInterceptor.java
Labels: in:MicroProfile/Metrics, team:Lumberjack

#2189 CDI2.0 asynv event tests increase timeout values
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/asyncEventsApp/src/asyncEventsApp/web/AsyncEventsServlet.java
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/secureAsyncEventsApp/src/secureAsyncEventsApp/web/SecureApprenticeChef.java
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/secureAsyncEventsApp/src/secureAsyncEventsApp/web/SecureAsyncEventsServlet.java
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/secureAsyncEventsApp/src/secureAsyncEventsApp/web/SecureMasterChef.java
Labels: CLA Signed, in:CDI/2.0, noproductcode, team:MicroProfileUK

#2174 http/2 redirect and error handling fixes
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
Labels: CLA Signed

#2152 Initial version of jCacheContainer-1.1 feature
  dev/com.ibm.websphere.appserver.jCacheContainer-1.1/.classpath
  dev/com.ibm.websphere.appserver.jCacheContainer-1.1/.project
  dev/com.ibm.websphere.appserver.jCacheContainer-1.1/bnd.bnd
  dev/com.ibm.websphere.appserver.jCacheContainer-1.1/com.ibm.websphere.appserver.jCacheContainer-1.1.feature
  dev/com.ibm.websphere.appserver.jCacheContainer-1.1/resources/l10n/com.ibm.websphere.appserver.jCacheContainer-1.1.properties
  dev/com.ibm.websphere.appserver.sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
Labels: CLA Signed, ID review not needed, team:Zombie Apocalypse

#2167 #1441 Merge JTS into BTS and format events at handlers
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/CollectorManagerPipelineConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/MessageRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TraceRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging.osgi/test/com/ibm/ws/logging/internal/osgi/WsMessageRouterImplTest.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/LogFieldConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/LogTraceData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.logging_fat/test-bundles/trace.source.handler/src/trace/source/handler/TraceHandlerImpl.java
Labels: CLA Signed

#2206 Update Message in InstallKernel.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
Labels: CLA Signed

#1925 Commit for 1877-sslHostNameVerify
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/LibertyConstants.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed

#1890 WI#1296: Rename JPA 2.2 Container + CDI 2.0 Autofeature and remove ve…
  dev/com.ibm.websphere.appserver.jpaContainer-cdi/.classpath
  dev/com.ibm.websphere.appserver.jpaContainer-cdi/.gitignore
  dev/com.ibm.websphere.appserver.jpaContainer-cdi/.project
  dev/com.ibm.websphere.appserver.jpaContainer-cdi/bnd.bnd
  dev/com.ibm.websphere.appserver.jpaContainer-cdi/com.ibm.websphere.appserver.jpaContainer-cdi.feature
Labels: CLA Signed, in:CDI, in:JPA, priority/medium, team:Blizzard

#2186 Remove unnecessary eclipselink 2.2 container integration bundle.
  dev/com.ibm.websphere.appserver.jpa-2.2/com.ibm.websphere.appserver.jpa-2.2.feature
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/.classpath
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/.project
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/bnd.bnd
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/Consts.java
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/EclipseLinkJPAProvider.java
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/logging/EclipseLinkLogger.java
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/logging/LogChannel.java
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/logging/package-info.java
  dev/com.ibm.ws.jpa.container.eclipselink.2.7/src/com/ibm/ws/jpa/container/eclipselink/package-info.java
Labels: in:JPA, priority/medium, team:Blizzard, tech debt

#2231 Revert "WI#1296: Rename JPA 2.2 Container + CDI 2.0 Autofeature and remove ve…"
  dev/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2/.classpath
  dev/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2/.gitignore
  dev/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2/.project
  dev/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2/bnd.bnd
  dev/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2/com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2.feature
Labels: CLA Signed

#2098 OpenTracing: Fix OutOfMemoryError with leaked ActiveSpans
  dev/com.ibm.ws.opentracing.cdi/src/com/ibm/ws/opentracing/cdi/TracedInterceptor.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingClientFilter.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingService.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATOpentracing.java
  dev/com.ibm.ws.opentracing_fat/test-applications/serviceApp/src/com/ibm/ws/testing/opentracing/service/FATOpentracingService.java
  dev/com.ibm.ws.opentracing_fat/test-bundles/opentracing.mock/src/com/ibm/ws/opentracing/mock/OpentracingMockTracer.java
Labels: CLA Signed

#1908 Issue #1865: Do not wrap Http2PushException and rethrow
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilderTest.java
Labels: CLA Signed

#2176 switching to no version bundle
  dev/com.ibm.websphere.appserver.servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.ws.rest.handler/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer/bnd.bnd
Labels: CLA Signed

#2208 Issue 2207: Pull in MYFACES-4202 to JSF 2.3
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/application/FacesServletMappingUtils.java
Labels: CLA Signed

#2250 Revert "Fix ConcurrentModificationException during app startup"
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
Labels: CLA Signed

#2236 Set log mark before deploying CDI extension app
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppExtensionTest.java
Labels: CLA Signed, noproductcode

#2164 Issue #2160 - add permissions.xml files to test wars
  dev/com.ibm.ws.cdi.api_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.cdi.api_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.api_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AlterableContextTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.cdi.beansxml_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.beansxml_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AfterTypeDiscoveryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ClassExclusionTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/classExclusion.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanEJB.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanFourWhichIsEJB.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanOne.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanThree.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanTwo.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/Iface.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/MyForthQualifier.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/MyQualifier.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/MySecondQualifier.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/MyThirdQualifier.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/Servlet.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/StaticState.java
  dev/com.ibm.ws.cdi.jndi_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.cdi.jndi_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.jndi_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanManagerLookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/JNDILookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/jndiLookup.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.lifecycle_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.cdi.lifecycle_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.lifecycle_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanLifecycleTest.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EventMetaDataTest.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ObservesInitializedTest.java
Labels: CLA Signed, noproductcode

#2247 Fix test failure caused by changing exception message text
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
Labels: CLA Signed

#2180 Update to 3.12.100.v20180210-1608 for org.eclipse.osgi
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
Labels: CLA Signed

#2254 Updated Sun providers according to the algorithm
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#2279 Revert "Updated Sun providers according to the algorithm"
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#2280 Revert "CWWKS4106E: LTPA CONFIGURATION ERROR IN LIBERTY when using PKCS11Impl provider "
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPADigSignature.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#2282 Revert "#1441 Merge JTS into BTS and format events at handlers"
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/CollectorManagerPipelineConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/MessageRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TraceRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging.osgi/test/com/ibm/ws/logging/internal/osgi/WsMessageRouterImplTest.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/LogFieldConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/LogTraceData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.logging_fat/test-bundles/trace.source.handler/src/trace/source/handler/TraceHandlerImpl.java
Labels: CLA Signed

#2252 Do not display info for products that are replaced
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ProductFeatureTest.java
Labels: CLA Signed

#2289 Issue #2288 - reenable all Config 1.2 TCK tests
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#2083 remove allow http config attribute for token requests
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/JwtConfig.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtComponent.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/web/JwtEndpointServices.java
Labels: CLA Signed, ID review not needed

#2341 Remove logservice=all from default FAT trace spec
  dev/fattest.simplicity/autoFVT-defaults/testports.properties
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2274 Upgrade to mp rest client api101
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.rest.client.1.0/bnd.bnd
  dev/com.ibm.websphere.org.eclipse.microprofile.rest.client.1.0/resources/OSGI-INF/permissions.perm
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/providers/jsonp/JsonPProvider.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBean.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/JAXRSClientFactoryBean.java
Labels: CLA Signed, in:JAX-RS, in:MicroProfile, team:Wendigo West

#2293 Issue #2022: Support multi-value attributes for LDAP registry.
  dev/com.ibm.websphere.appserver.federatedRegistry-1.0/com.ibm.websphere.appserver.federatedRegistry-1.0.feature
  dev/com.ibm.websphere.appserver.spi.federatedRepository/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Container.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Country.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Entity.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/GeographicLocation.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Group.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Locality.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/LoginAccount.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/OrgContainer.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/PartyRole.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Person.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/PersonAccount.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/RolePlayer.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/package-info.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/websphere/security/wim/ras/BankInfo.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/websphere/security/wim/ras/Customer.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/websphere/security/wim/ras/Geography.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/websphere/security/wim/ras/PhoneInfo.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/websphere/security/wim/ras/WIMTraceHelperTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/ContainerTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/CountryTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/EntityTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/GeographicLocationTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/GroupTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/LocalityTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/LoginAccountTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/OrgContainerTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/PartyRoleTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/PartyTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/PersonAccountTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/PersonTest.java
  dev/com.ibm.websphere.security.wim.base/test/com/ibm/wsspi/security/wim/model/RolePlayerTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
Labels: CLA Signed, team:Wendigo East

#2270 issue warning message when it is determined security not present
  dev/com.ibm.jbatch.container/bnd.bnd
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
Labels: CLA Signed

#2312 251601 chk additiona sql ex
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
Labels: CLA Signed

#2296 Adding Metrics Global Tags
  dev/com.ibm.websphere.appserver.mpMetrics-1.1/bnd.bnd
  dev/com.ibm.websphere.appserver.mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.ws.microprofile.metrics.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1/src/com/ibm/ws/microprofile/metrics11/impl/MetricRegistry11Impl.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
Labels: CLA Signed

#2326 Add Microprofile Metrics TCK 1.0 #2322
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics_fat_tck/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics_fat_tck/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArchiveProcessor.java
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode, team:Lumberjack

#2285 Updated the java vendor logic following the way Liberty Kernel does
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPADigSignature.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#2246 Make com.ibm.ws.cdi.visibility_fat pass java 2 security testing
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/VisTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/permissions.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12SharedLibraryServer/bootstrap.properties
Labels: CLA Signed, noproductcode

#2333 Disable http/2 for 18001 release
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed

#2330 Reduce FAT tracing
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.cdi/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.multi.client.cdi/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.remoteServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.tolerateEE8/bootstrap.properties
Labels: CLA Signed, in:JAX-RS, in:MicroProfile, noproductcode, team:Wendigo West

#2286 fix update of consecutiveEmptyQueueCount
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed

#2340 Fix Json out put of json console (remove duplicate basic messages and abide by consoleloglevel)
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
Labels: CLA Signed

#2343 Stop publishing EJb test manifest
  dev/com.ibm.ws.ejbcontainer.fat_tools/build.gradle
Labels: CLA Signed, noproductcode

#2362 Fixes config for JSON Logging
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
Labels: CLA Signed

#2363 Fix cdi fat app deployments
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/implicit/ImplicitBeanArchiveTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/implicit/ImplicitEJBTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/implicit/ImplicitWarLibJarsTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/implicit/ImplicitWarTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AroundConstructTestBase.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppExtensionTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi12/fat/tests/SimpleJSPTest.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/NonContextualInjectionPointTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/JarInRarTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/PackagePrivateAccessTest.java
Labels: CLA Signed, noproductcode

#2355 Update to in-memory Derby where possible
  dev/com.ibm.ws.cdi.lifecycle_fat/publish/servers/cdi12PassivationServer/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_demo/publish/servers/com.ibm.ws.concurrent.persistent.fat.demo/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_locking/publish/servers/com.ibm.ws.concurrent.persistent.fat.locking/server.xml
  dev/com.ibm.ws.config_fat/publish/files/featureRemove/serverRemoveJDBC.xml
  dev/com.ibm.ws.config_fat/publish/files/featureRemove/serverRemoveOpenID.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.features/server.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.invalidJDBCoption/server.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.invalidOptionalInclude/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2212 Don't wait for a feature update
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/service/ServerEndpointControlMBeanTest.java
Labels: CLA Signed, noproductcode

#2305 2234 update mp config version
  dev/com.ibm.websphere.appserver.mpConfig-1.2/bnd.bnd
  dev/com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.2/bnd.bnd
  dev/com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.2/com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.2.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
Labels: CLA Signed

#2342 Audit fix by explicitly creating bufferManagerImpl with ringbuffer form the beginning
  dev/com.ibm.ws.collector.manager/src/com/ibm/ws/collector/manager/internal/SourceManager.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
Labels: CLA Signed

#2336 Fix ConcurrentModifcationException during app startup
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
Labels: CLA Signed

#2367 Reduce trace in javaeesec fat bucket
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBAuthAliasTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBNoUserTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBShortNameTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authalias.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.nouser.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.shortname.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ejb.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.jaxrs.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ldapidstore.deferred.fat/bootstrap.properties
Labels: CLA Signed, noproductcode, team:Wendigo East

#2369 Added mpMetrics 1.1 fat tck project.
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArchiveProcessor.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode

#2368 Reduce trace in CDI, mpConfig and mpFaultTolerance
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20AsyncEventsServer/server.xml
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20BasicServer/server.xml
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20BuiltinAnnoServer/server.xml
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20ConfigServer/server.xml
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20SecureAsyncEventsServer/server.xml
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12BeanDiscoveryModeNoneServer/bootstrap.properties
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12BeanDiscoveryModeNoneServer/server.xml
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12UserSAXParserFactory/bootstrap.properties
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12UserSAXParserFactory/server.xml
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12WarLibsAccessWarServer/bootstrap.properties
  dev/com.ibm.ws.cdi.beansxml_fat/publish/servers/cdi12WarLibsAccessWarServer/server.xml
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12EJB32Server/bootstrap.properties
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12EjbConstructorInjectionServer/bootstrap.properties
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12ManagedBeanTestServer/bootstrap.properties
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12StatefulSessionBeanServer/bootstrap.properties
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12StatefulSessionBeanServer/server.xml
  dev/com.ibm.ws.cdi.extension_fat/publish/servers/cdi12AppExtensionServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12JarInRar/bootstrap.properties
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12SharedLibraryServer/bootstrap.properties
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12WarLibsAccessWarServer/bootstrap.properties
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12WarLibsAccessWarServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat/publish/servers/ConverterServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/CDIConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/ClassLoadersServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/ConverterServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/ConvertersServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/CustomSourcesServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/OrdForDefaultsServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/SharedLibUserServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/SimpleConfigSourcesServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/StressServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/TypesServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/brokenCDIConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/CDIFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/FaultToleranceMultiModule/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetrics/server.xml
Labels: CLA Signed, noproductcode

#2242 Removing versioned bundle refs
  dev/com.ibm.websphere.appserver.kernel-1.0/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-3.1/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.servlet-4.0/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.ws.org.apache.commons.io/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
  dev/com.ibm.ws.persistence_fat/bnd.bnd
  dev/com.ibm.ws.security.utility.securityutil/bnd.bnd
  dev/com.ibm.ws.security.utility/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.utility/bnd.bnd
Labels: CLA Signed

#2380 Change coordinates for arquillian plugin
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
Labels: in:JAX-RS, in:MicroProfile, team:Wendigo West

#2392 MP OpenAPI 1.0 Validator fixes, update feature to use MP Config 1.2
  dev/com.ibm.websphere.appserver.mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/CustomCSSProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/ComponentsImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/ExternalDocumentationImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/OpenAPIImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/OperationImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/PathItemImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/PathsImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/callbacks/CallbackImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/examples/ExampleImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/headers/HeaderImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/info/ContactImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/info/InfoImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/info/LicenseImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/links/LinkImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/ContentImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/DiscriminatorImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/EncodingImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/MediaTypeImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/SchemaImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/media/XMLImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/parameters/ParameterImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/parameters/RequestBodyImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/responses/APIResponseImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/responses/APIResponsesImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/security/OAuthFlowImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/security/OAuthFlowsImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/security/ScopesImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/security/SecurityRequirementImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/security/SecuritySchemeImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/servers/ServerImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/servers/ServerVariableImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/servers/ServerVariablesImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/model/tags/TagImpl.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/CallbackValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/ContactValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/ExternalDocumentationValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/InfoValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/LicenseValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/OAuthFlowValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/PathItemValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/ReferenceValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/SecuritySchemeValidator.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/ValidatorUtils.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/OpenAPIUtils.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/CallbacksValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ContactValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/ExternalDocumentationValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/InfoValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/LicenseValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/OAuthFlowValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/PathItemValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/SecuritySchemeValidatorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/UICustomizationTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFour.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestTwo.java
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/dropins/openapi_validation.war
Labels: CLA Signed

#2335 use cache entry per session property approach
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMapMR.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheSession.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStore.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SessionData.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/CacheEntryPerSessionPropertyTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/MultiServerCacheEntryPerSessionPropertyTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServer/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheEntryPerPropServerB/server.xml
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMapMR.java
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseSession.java
  dev/com.ibm.ws.session.store/src/com/ibm/ws/session/store/common/BackedSession.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/store/memory/MemorySession.java
Labels: CLA Signed, team:Zombie Apocalypse

#2253 update test case to recognize Java 9 CompletableFuture
  dev/com.ibm.websphere.appserver.concurrentRX-1.0/com.ibm.websphere.appserver.concurrentRX-1.0.feature
  dev/com.ibm.ws.concurrent.rx/src/com/ibm/websphere/concurrent/rx/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#2262 Avoid NPE on shutdown
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigRefresher.java
Labels: CLA Signed

#2269 Add another package exclusion
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerClasspathTest.java
Labels: CLA Signed, noproductcode

#2298 Add the HttpServletMapping related attributes to the request
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebAppDispatcherContext40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletRequest40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/webapp/WebAppRequestDispatcher40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/webapp/package-info.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WebContainerConstants.java
Labels: CLA Signed

#2151 Clean up internal CDI api usage
  dev/com.ibm.ws.beanvalidation.v20.cdi/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20.cdi/src/com/ibm/ws/beanvalidation/v20/cdi/internal/BvalManagedObjectBuilderImpl.java
  dev/com.ibm.ws.beanvalidation.v20.cdi/src/com/ibm/ws/beanvalidation/v20/cdi/internal/LibertyHibernateValidatorExtension.java
Labels: CLA Signed, in:Bean Validation, team:Zombie Apocalypse

#2375 Squelch exception from DS
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TrLogServiceImpl.java
Labels: CLA Signed

#1630 Work around file system issue
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/wsspi/kernel/embeddable/EmbeddedServerMergeProductExtensionTest.java
Labels: CLA Signed, noproductcode

#1986 1560 shrinkwrap helper should not default to overwiting when exporting artifacts to the server
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
Labels: CLA Signed, noproductcode

#2182 add permission.xml
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/BuiltinAnnoLiteralsTest.java
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/builtinAnnoLiteralsApp/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode

#2204 Issue #2203 - add permissions.xml to Extension Test
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDI12ExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/test-applications/helloWorldExtensionTest.war/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode

#2303 Fulfil issue #2202: only repeat security tests
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/FATSuite.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/SecureAsyncEventsAS20Test.java
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20as20SecureAsyncEventsServer/.gitignore
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20as20SecureAsyncEventsServer/bootstrap.properties
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20as20SecureAsyncEventsServer/server.xml
Labels: CLA Signed, noproductcode

#2059 Test combination of fault tolerance with @Transactional
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/TxRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/TxFaultTolerance/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/TxFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/RetryServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/beans/FTTransactional.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/beans/Required.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/beans/RetryBeanA.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/beans/RetryBeanB.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/TxFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/tx/beans/RetryBeanB2.java
Labels: CLA Signed, noproductcode

#2244 Issue #2243: Remove test dir from servlet 4 FAT
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test/configuration.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test/logging.properties
Labels: CLA Signed, noproductcode

#2188 fix incorrect mp-jwt message
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
Labels: CLA Signed, ID reviewed

#2346 Set qualifiers to timestamps and upload a zip artifact of .feature files
  dev/cnf/build.gradle
  dev/settings.gradle
Labels: team:Continuous Delivery

#2287 Create private feature for servlet SPI to decouple servlet-3.0 dependency
  dev/com.ibm.websphere.appserver.servlet-3.1/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.servlet-4.0/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.websphere.appserver.servlet-servletSpi1.0/.classpath
  dev/com.ibm.websphere.appserver.servlet-servletSpi1.0/.gitignore
  dev/com.ibm.websphere.appserver.servlet-servletSpi1.0/.project
  dev/com.ibm.websphere.appserver.servlet-servletSpi1.0/bnd.bnd
  dev/com.ibm.websphere.appserver.servlet-servletSpi1.0/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
Labels: CLA Signed

#2364 refactor interface, reduce trace
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/config/JwtSsoConfig.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MicroProfileJwtConfig.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/publish/servers/mpjwt_roles/server.xml
Labels: CLA Signed

#2103 Initial prototype of jcache vendor property config for sessionCache
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#2135 EJBxCDI ee8 Tests & RepeatTest Servlet Injection Fix
  dev/com.ibm.ws.ejbcontainer.cdi_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.cdi_fat/fat/src/com/ibm/ws/ejbcontainer/cdi/fat/EJBxCDITest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, noproductcode

#2301 Mechanism to fail a FAT that generates more than X MB of trace while running
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/LogPolice.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#2411 Revert "Updated the java vendor logic following the way Liberty Kerne…
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPADigSignature.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#2239 Issue 2235: Fix ClassCastException when changing servlet feature from…
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpResponseImpl.java
Labels: CLA Signed

#2429 Revert "1560 shrinkwrap helper should not default to overwiting when exporting artifacts to the server"
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
Labels: CLA Signed, noproductcode

#2295 Initial copy of SecureAction utility class
  dev/com.ibm.ws.adaptable.module/src/com/ibm/ws/adaptable/module/internal/AdapterFactoryServiceImpl.java
  dev/com.ibm.ws.beanvalidation.core/src/com/ibm/ws/beanvalidation/config/ValidationConfigurator.java
  dev/com.ibm.ws.beanvalidation/src/com/ibm/ws/beanvalidation/OSGiBeanValidationImpl.java
  dev/com.ibm.ws.beanvalidation/src/com/ibm/ws/beanvalidation/accessor/BeanValidationAccessor.java
  dev/com.ibm.ws.concurrent.persistent/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/TaskStatusImpl.java
  dev/com.ibm.ws.javaee.platform.defaultresource/src/com/ibm/ws/javaee/platform/defaultresource/internal/DefaultResourceJavaColonNamingHelper.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/component/injection/ContextObjectFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/component/injection/QueryParamObjectFactory.java
  dev/com.ibm.ws.jca.1.7/src/com/ibm/ws/jca17/processor/service/AdministeredObjectResourceFactoryBuilder.java
  dev/com.ibm.ws.jca.1.7/src/com/ibm/ws/jca17/processor/service/ConnectionFactoryResourceBuilder.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/BootstrapContextImpl.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ConnectorModuleMetaDataImpl.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ConnectorModuleMetatypeAdapter.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ConnectorModuleMetatypeBundleImpl.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ConnectorModuleRuntimeContainer.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ResourceAdapterService.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/Utils.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/service/ConnectionFactoryService.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/service/EndpointActivationService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/exceptions/DataStoreAdapterException.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/SerializedDataSourceWrapper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcTracer.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcWrapper.java
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/PrivHelper.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/SecureAction.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ws/sib/utils/RuntimeInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/component/injection/ContextObjectFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/component/injection/QueryParamObjectFactory.java
Labels: CLA Signed, team:Zombie Apocalypse

#2398 Added case 18 to handle InvokeDynamic for lambda expressions.
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/utils/SDEInstaller.java
Labels: CLA Signed

#2432 More eclipse updates
  dev/com.ibm.websphere.appserver.kernel-1.0/bnd.bnd
  dev/com.ibm.websphere.appserver.mpMetrics-1.1/.classpath
  dev/com.ibm.websphere.appserver.mpMetrics-1.1/.project
  dev/com.ibm.websphere.appserver.mpMetrics1.1-cdi1.2/.classpath
  dev/com.ibm.websphere.appserver.mpMetrics1.1-cdi1.2/.project
  dev/com.ibm.websphere.appserver.mpMetrics1.1-cdi1.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-1.1/.classpath
  dev/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-1.1/.project
  dev/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-1.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.beansxml_fat/.classpath
  dev/com.ibm.ws.microprofile.openapi.ui/build.gradle
  dev/com.ibm.ws.microprofile.openapi_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.openapi_fat_tck/.project
  dev/com.ibm.ws.microprofile.openapi_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.openapi_fat_tck/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.microprofile.openapi_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.openapi_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/build.gradle
  dev/com.ibm.ws.repository.test.utils/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.repository_fat_shared/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed

#2154 Issue 1766: Custom Hash fix and tests for DatabaseIdentityStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
  dev/com.ibm.ws.security.javaeesec_fat/.classpath
  dev/com.ibm.ws.security.javaeesec_fat/bnd.bnd
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FATSuite.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashBeanTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashNoConfigTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/Constants.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/WCApplicationHelper.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/apps/.gitignore
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/resources/security/ltpa.keys
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/apps/.gitignore
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/resources/security/ltpa.keys
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/CustomPasswordHash.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/CustomPasswordHash.jar/src/com/ibm/ws/security/pwdhash/test/TestHash.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/CustomPasswordHashBean.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/CustomPasswordHashBean.jar/resources/META-INF/beans.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/CustomPasswordHashBean.jar/src/com/ibm/ws/security/pwdhash/bean/test/TestHash.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHash.war/src/web/war/hash/db/DatabaseAnnotatedCustomHashServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedCustomHashBean.war/src/web/war/hash/db/bean/DatabaseAnnotatedCustomHashServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/dbfatCustomHash.war/src/web/war/db/CustomHashDatabaseServlet.java
Labels: CLA Signed, team:Wendigo East

#2281 pull in new version of apache.aries.jndi.core with fix to issue #2223
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.bnd
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.overrides
Labels: CLA Signed

#2198 update to latest felix scr (2.0.14)
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#2337 Same changes as in PI92182
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/ConnectionWriteCompletedCallback.java
Labels: CLA Signed

#2438 Revert "Same changes as in PI92182"
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/ConnectionWriteCompletedCallback.java
Labels: CLA Signed

#2220 Update Bean Validation 2.0 API and impl and JSON-B 1.0 impl
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.beanValidation-2.0/com.ibm.websphere.appserver.beanValidation-2.0.feature
  dev/com.ibm.websphere.appserver.beanValidationCDI-2.0/bnd.bnd
  dev/com.ibm.websphere.appserver.beanValidationCDI-2.0/com.ibm.websphere.appserver.beanValidationCDI-2.0.feature
  dev/com.ibm.websphere.javaee.validation.2.0/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20.cdi/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20/bnd.bnd
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
  dev/com.ibm.ws.clientcontainer.json_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PackageJsonBTestNoFeature.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PackageJsonBTestWithFeature.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.packageJsonBNoFeature/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.packageJsonBWithFeature/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbapp/src/jaxrs21/fat/jsonb/MyJsonBProvider.java
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONBInAppTest.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JsonUserFeatureTest.java
  dev/com.ibm.ws.jsonb_fat/publish/servers/com.ibm.ws.jsonb.inapp/server.xml
  dev/com.ibm.ws.jsonb_fat/publish/servers/com.ibm.ws.jsonp.container.userfeature.fat/server.xml
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.bnd
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_de.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_fr.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_uk.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_zh_CN.properties
Labels: CLA Signed, in:Bean Validation, in:JSONP/JSONB, team:Zombie Apocalypse

#2406 Issue #2404: Revert zipreaper keep tests
  dev/com.ibm.ws.artifact.zip/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingProperties.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingService.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipFileHandle.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/CacheHashMap.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingServiceImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/package-info.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ContainerFactoryHolder.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/FileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/SystemUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/Utils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntryIterator.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileNestedDirContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/package-info.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/ArtifactAPIServlet.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/notification/JarArtifactNotificationTest.java
Labels: CLA Signed

#2452 test HttpSessionListener
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionListener1.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionListener2.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2457 vary which apps use HttpSessionListener and use different types for session attributes
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/listener1/SessionListener.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/listener2/SessionListener.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2460 fix SessionInfo so that it does deep clone
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SessionInfo.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
Labels: team:Zombie Apocalypse

#2466 Issue #2165: fixing listener count
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: team:Zombie Apocalypse
