Repository OpenLiberty/open-liberty, pull requests merged in 2018-07, with the labels that each got.

#4156 FAT test for FT metrics being removed
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/MetricListServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/RemovalBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/RemovalServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/permissions.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetricsRemoval/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetricsRemoval/server.xml
Labels: CLA Signed, noproductcode

#4160 Squelch DS lock error, even when wrapped
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TrLogServiceImpl.java
Labels: CLA Signed

#4139 Remove commons-lang3 v3.5 bundle
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.classpath
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.project
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.lang3.3.5/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#4179 fix timing issue in testRefreshInvalidation
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4175 Fix trace check in DatabaseIdentityStoreImmediateSettingsTest Test
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreImmediateSettingsTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#4024 Issue 4023: Update EclipseLink 2.6_WAS to support Java 11
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed

#4184 Issue #4183 - update the beta version to 2018.7.0.0
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#4162 Remove PrivHelper class from kernel.service bundle
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/exceptions/DataStoreAdapterException.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcTracer.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcWrapper.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/PrivHelper.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/package-info.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ws/sib/utils/RuntimeInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/component/injection/ContextObjectFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/component/injection/QueryParamObjectFactory.java
Labels: CLA Signed, in:Kernel/Bootstrap, team:Zombie Apocalypse

#4182 4181 injection point pmr
  dev/com.ibm.ws.cdi.api_fat/bnd.bnd
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi12/fat/tests/InjectInjectionPointAsParamTest.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12InjectInjectionPointParamServer/.gitignore
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12InjectInjectionPointParamServer/bootstrap.properties
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12InjectInjectionPointParamServer/server.xml
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12InjectInjectionPointServer/jvm.options
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointAsParam.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointAsParam.war/src/com/ibm/ws/fat/cdi/injectInjectionPointParam/InjectInjectionPointServlet.java
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointAsParam.war/src/com/ibm/ws/fat/cdi/injectInjectionPointParam/TestBean.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionObjectFactory.java
Labels: CLA Signed

#4185 Misc build changes working toward Java 11 support
  dev/cnf/oss_dependencies.maven
  dev/cnf/resources/bin/tool
  dev/cnf/resources/bin/tool.bat
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
  dev/com.ibm.ws.kernel.cmdline/bnd.bnd
  dev/com.ibm.ws.kernel.cmdline/build.gradle
  dev/com.ibm.ws.kernel.cmdline/test/com/ibm/ws/kernel/boot/cmdline/PackageDelegateClassLoaderTest.java
  dev/com.ibm.ws.product.utility/bnd.bnd
  dev/com.ibm.ws.product.utility/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
Labels: CLA Signed, in:Build, team:Zombie Apocalypse

#4167 When FFDC checking is disabled for one server, continue checking other servers
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode

#4190 Ignore SSLError on FAT that purposely misconfigures SSL
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests20.java
Labels: CLA Signed, noproductcode

#4198 Also handle UnsupportedOperationException in getCompatibleUpdateCount
  dev/com.ibm.ws.jdbc.4.2/src/com/ibm/ws/rsadapter/jdbc/v42/WSJdbc42PreparedStatement.java
Labels: CLA Signed, in:JDBC/JCA, release bug, team:Zombie Apocalypse

#4195 Exclude FT 1.1 timing sensitive tests
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#4174 Add retry logic for file deletes
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/notification/JarArtifactNotificationTest.java
Labels: CLA Signed, noproductcode

#4187 4186 improve config dropins
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java
Labels: CLA Signed

#4212 Issue 4211: Add doPriv around conn.setSSLSocketFactory
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4043 server xml variable and app property config support
  dev/com.ibm.ws.microprofile.config.1.3/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.microprofile.config.1.3/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/interfaces/Config13Constants.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/AppPropertyConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/Config13DefaultSources.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/ServerXMLVariableConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/.classpath
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/refreshAppProperties/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/refreshVariables/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/server.env
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/mapEnvVarApp/src/com/ibm/ws/microprofile/config13/mapEnvVar/web/MapEnvVarServlet.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/variableServerXMLApp/src/com/ibm/ws/microprofile/config13/variableServerXML/web/VariableServerXMLBean.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/variableServerXMLApp/src/com/ibm/ws/microprofile/config13/variableServerXML/web/VariableServerXMLServlet.java
Labels: CLA Signed, ID reviewed

#4201 Incremental changes for Java 11 support
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/.classpath
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/bnd.bnd
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/build.gradle
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/src/org/omg/stub/javax/management/j2ee/_ManagementHome_Stub.java
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/src/org/omg/stub/javax/management/j2ee/_Management_Stub.java
  dev/com.ibm.websphere.javaee.management.j2ee.1.1/test/javax/management/j2ee/EJBStubModificationCheck.java
  dev/com.ibm.ws.install/test/com/ibm/ws/install/JarAssetTest.java
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#4215 Add individual waits for file updates
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/DropinsTest.java
Labels: CLA Signed, noproductcode

#4224 Revert "server xml variable and app property config support"
  dev/com.ibm.ws.microprofile.config.1.3/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.microprofile.config.1.3/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/interfaces/Config13Constants.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/AppPropertyConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/Config13DefaultSources.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/ServerXMLVariableConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/.classpath
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/refreshAppProperties/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/refreshVariables/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/server.env
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLVariableServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/mapEnvVarApp/src/com/ibm/ws/microprofile/config13/mapEnvVar/web/MapEnvVarServlet.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/variableServerXMLApp/src/com/ibm/ws/microprofile/config13/variableServerXML/web/VariableServerXMLBean.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/variableServerXMLApp/src/com/ibm/ws/microprofile/config13/variableServerXML/web/VariableServerXMLServlet.java
Labels: CLA Signed

#4217 Issue #3987 : common jwk implementation
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/com.ibm.websphere.appserver.jwt-1.0.feature
  dev/com.ibm.ws.security.common.jsonwebkey/.classpath
  dev/com.ibm.ws.security.common.jsonwebkey/.gitignore
  dev/com.ibm.ws.security.common.jsonwebkey/.project
  dev/com.ibm.ws.security.common.jsonwebkey/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.common.jsonwebkey/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.common.jsonwebkey/bnd.bnd
  dev/com.ibm.ws.security.common.jsonwebkey/build.gradle
  dev/com.ibm.ws.security.common.jsonwebkey/build.xml
  dev/com.ibm.ws.security.common.jsonwebkey/findbugs.exclude.xml
  dev/com.ibm.ws.security.common.jsonwebkey/resources/com/ibm/ws/security/common/jwk/internal/resources/JWKCommonMessages.nlsprops
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/constants/TraceConstants.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/constants/package-info.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKImpl.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jEllipticCurveJWK.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWK.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/package-info.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/interfaces/JSONWebKey.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/interfaces/JWK.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/interfaces/package-info.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/internal/JwkConstants.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/internal/package-info.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/config/CommonConfigUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/http/HttpUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKProviderTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWKTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/jwk_test.json
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/random/RandomUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/web/JavaScriptUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/web/WebUtilsTest.java
Labels: CLA Signed

#4176 Perf improvements in webcontainer and JSF functions
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/WASApplicationImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/GenericUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/KeyMatcher.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/BufferedWriter.java
Labels: CLA Signed

#4194 Falling back to SimpleDateFormat if format is invalid
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/BurstDateFormat.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/collector/BurstDateFormatterTest.java
Labels: CLA Signed, team:Lumberjack

#4216 copy method for managed completable future
  dev/com.ibm.ws.concurrent.rx/bnd.bnd
  dev/com.ibm.ws.concurrent.rx/src/com/ibm/websphere/concurrent/rx/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#3952 Add global error when user registry is not found
  dev/com.ibm.websphere.appserver.spi.federatedRepository/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/NoUserRepositoriesFoundException.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/package-info.java
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/NoRegistryConfiguredTest.java
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/bootstrap.properties
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/server.xml
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/WIMUserRegistry.java
Labels: CLA Signed, ID reviewed, release bug, team:Wendigo East

#4146 Add trace for Read_Write_listener
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/AsyncReadCallback.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/AsyncWriteCallback.java
Labels: CLA Signed, in:Web Components

#4228 Eclipselink: Bug 536853: MapsID processing sets up to fail validation…
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed, in:JPA, priority/medium, team:Blizzard

#3854 Better repository resolution
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.repository.resolver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.repository.resolver/bnd.bnd
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/ProductRequirementInformation.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolutionException.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/FixFeatureComparator.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/RepositoryResolveContext.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/ResolutionFilter.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/StopAutoFeaturesInstallingTheirRequiredCapabilities.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRepository.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRequirement.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/namespace/InstallableEntityIdentityConstants.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/namespace/ProductNamespace.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/CapabilityImpl.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/FeatureResource.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/GenericMetadataRequirement.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/IFixResource.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/InstallableEntityCapability.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/InstallableEntityRequirement.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/LpmResource.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/ProductCapability.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/ProductRequirement.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/ProductResource.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/RequirementImpl.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/ResourceHolder.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/ResourceImpl.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/resource/SampleResource.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/DummyRepositoryConnection.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/RepositoryResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/ResolutionTests.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/ResolverTestUtils.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/FixFeatureComparatorTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/RepositoryResolveContextUnitTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/StopAutoFeaturesInstallingTheirRequiredCapabilitiesTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResourceMatcher.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsaMatcher.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsaTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRepositoryTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverResultMatcher.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/FeatureResourceTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/GenericMetadataRequirementTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/IFixResourceTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/LpmResourceTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/ProductRequirementTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/ProductResourceTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/RequirementImplTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/ResourceImplTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/resource/SampleResourceTest.java
Labels: CLA Signed

#4243 Revert "Add global error when user registry is not found"
  dev/com.ibm.websphere.appserver.spi.federatedRepository/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/NoUserRepositoriesFoundException.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/package-info.java
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/NoRegistryConfiguredTest.java
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/bootstrap.properties
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/server.xml
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/WIMUserRegistry.java
Labels: CLA Signed, ID review not needed

#4204 Issue #4203: Avoid IllegalArgumentException when maxParamPerRequest i…
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/RequestUtils.java
Labels: CLA Signed, in:Web Components

#4235 completedStage, failedFuture, and failedStage
  dev/com.ibm.ws.concurrent.rx/src/com/ibm/websphere/concurrent/rx/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4242 Enable overriding install map jar
  dev/com.ibm.ws.install.map/src/com/ibm/ws/install/map/InstallMap.java
Labels: CLA Signed

#4161 Port com.ibm.ws.webserver.plugin.utility FAT bucket and unit tests
  dev/com.ibm.ws.webserver.plugin.utility/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.utility/test/src/com/ibm/ws/webserver/plugin/utility/WebServerPluginUtilityTest.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/.classpath
  dev/com.ibm.ws.webserver.plugin.utility_fat/.functional_area
  dev/com.ibm.ws.webserver.plugin.utility_fat/.project
  dev/com.ibm.ws.webserver.plugin.utility_fat/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.webserver.plugin.utility_fat/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.utility_fat/build.gradle
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/FATSuite.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityGenerateTest.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityMergeTest.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/plugin-cfg1.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/plugin-cfg2.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/defaultServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/defaultServer/server.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/.gitignore
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/local/.gitkeep
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/server.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/.gitignore
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/remote/.gitkeep
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/resources/security/sslOptions.jks
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/resources/security/trust.jks
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode

#4244 Add global error when user registry is not found
  dev/com.ibm.websphere.appserver.features/visibility/public/federatedRegistry-1.0/com.ibm.websphere.appserver.federatedRegistry-1.0.feature
  dev/com.ibm.websphere.appserver.spi.federatedRepository/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/NoUserRepositoriesFoundException.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/exception/package-info.java
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/NoRegistryConfiguredTest.java
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/bootstrap.properties
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.noreg/server.xml
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/WIMUserRegistry.java
Labels: CLA Signed, ID reviewed, release bug, team:Wendigo East

#4240 completeAsync methods
  dev/com.ibm.ws.concurrent.rx/src/com/ibm/websphere/concurrent/rx/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4270 Update eclipse settings for new projects
  dev/com.ibm.ws.security.common.jsonwebkey/.classpath
  dev/com.ibm.ws.webserver.plugin.utility/.classpath
  dev/com.ibm.ws.webserver.plugin.utility_fat/.project
  dev/com.ibm.ws.webserver.plugin.utility_fat/.settings/bndtools.core.prefs
Labels: CLA Signed, noproductcode

#4283 Add xml-apis to -testpath
  dev/com.ibm.ws.security.fat.common/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#4268 Transfer jaxrs.2.1_fat_executor tests from commercial Liberty to open
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.gitignore
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.project
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/fat/src/com/ibm/ws/jaxrs/executor/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/fat/src/com/ibm/ws/jaxrs/executor/fat/JAXRSExecutorTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/publish/servers/com.ibm.ws.jaxrs.2.1.fat.executor/.gitignore
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/publish/servers/com.ibm.ws.jaxrs.2.1.fat.executor/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/publish/servers/com.ibm.ws.jaxrs.2.1.fat.executor/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/test-applications/jaxrsapp/src/web/jaxrstest/JAXRSExecutorTestApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/test-applications/jaxrsapp/src/web/jaxrstest/JAXRSExecutorTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#4262 Added methods to allow for array of product ids to be passed in
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#4273 provie a more useful error message if the restart fails
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDIManagedBeanInterceptorTest.java
Labels: CLA Signed, noproductcode

#4290 Revert "Added methods to allow for array of product ids to be passed in"
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#4280 Issue4277-updateWebContainerCodeToEmitOnlyOneAuthzAuditRecordForUnpro…
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
Labels: CLA Signed

#4234 Add API to allow ESA's to specify unspecified License type
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/EsaParser.java
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/ParserBase.java
Labels: CLA Signed

#4099 update weld to 3.0.4
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-1.2/com.ibm.websphere.appserver.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.jsf/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.web/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
  dev/com.ibm.ws.org.jboss.classfilewriter/bnd.bnd
  dev/com.ibm.ws.org.jboss.classfilewriter/bnd.overrides
  dev/com.ibm.ws.org.jboss.classfilewriter/build.xml
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
Labels: CLA Signed

#4276 Add heuristic knowledge of H2 JDBC driver
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
Labels: CLA Signed, in:JDBC/JCA, team:Zombie Apocalypse

#4281 Consider a Connection aged out if tDiff >= timout
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
Labels: CLA Signed, in:JDBC/JCA, team:Zombie Apocalypse

#4285 JDK9 ALPN support
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/AlpnSupportUtils.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLAlpnNegotiator.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannel.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLConnectionLink.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: CLA Signed, in:Transport, team:Sirius

#4255 Issue #3987 : Continue the work of common JWK implementation for all sso features
  dev/com.ibm.ws.security.common.jsonwebkey/.classpath
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/config/CommonConfigUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/http/HttpUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/random/RandomUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/web/JavaScriptUtilsTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/web/WebUtilsTest.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/JWKImpl.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/Jose4jEllipticCurveJWK.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWK.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/package-info.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/interfaces/JSONWebKey.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/interfaces/JWK.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/interfaces/package-info.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/internal/JwkConstants.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/internal/package-info.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/jwk/impl/JWKProviderTest.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWKTest.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/jwk/impl/jwk_test.json
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwKRetriever.java
  dev/com.ibm.ws.security.jwtsso/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
Labels: CLA Signed, team:Security SSO

#4293 Issue4292-CorrectMissingJMSRoles
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/authorization/internal/MessagingAuthorizationServiceImpl.java
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/internal/MessagingSecurityServiceImpl.java
Labels: CLA Signed

#4316 completeOnTimeout, orTimeout, and delayedExecutor
  dev/com.ibm.ws.concurrent.rx/src/com/ibm/websphere/concurrent/rx/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4258 adding support for directory-Based Repositories
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#4313 Fix NPE when checking for skipping
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingClientFilter.java
Labels: CLA Signed, team:Lumberjack

#4315 support ignoreCase for getUsers method
  dev/com.ibm.ws.security.registry.basic/src/com/ibm/ws/security/registry/basic/internal/BasicRegistry.java
  dev/com.ibm.ws.security.registry.basic/test/com/ibm/ws/security/registry/basic/internal/BasicRegistryTest.java
Labels: CLA Signed, in:Security, team:Core Security

#4257 Updating OpenTracing to 1.0.1
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.opentracing.1.0/bnd.bnd
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, team:Lumberjack

#4333 Fix message number and add carriage returns
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages.nlsprops
Labels: CLA Signed

#4318 Enable Gradle daemon by default
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#4331 fix validator in FeatureTest of com.ibm.ws.security.javaeesec_fat
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FeatureTest.java
Labels: CLA Signed, in:Security, noproductcode, team:Core Security, test bug

#4323 Issue4322-RefactorJMSAuditFieldNames
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
Labels: CLA Signed

#4324 Port jdbc_bvt test bucket to Open Liberty
  dev/com.ibm.ws.jdbc_fat_driver/.classpath
  dev/com.ibm.ws.jdbc_fat_driver/.project
  dev/com.ibm.ws.jdbc_fat_driver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat_driver/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_driver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_driver/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_driver/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_driver/build.gradle
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3861 Fix to remove early messages and early traces from BaseTraceService
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#4325 prepare for driver class instead of data source class
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iNativeHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iToolboxHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/SybaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#4337 Revert "update weld to 3.0.4"
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-1.2/com.ibm.websphere.appserver.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.jsf/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.web/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
  dev/com.ibm.ws.org.jboss.classfilewriter/bnd.bnd
  dev/com.ibm.ws.org.jboss.classfilewriter/bnd.overrides
  dev/com.ibm.ws.org.jboss.classfilewriter/build.xml
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
Labels: CLA Signed

#4222 Issue #4221 - update release versions
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#3085 Refactored bufferManagerImpl to allow hard referenced early buffer
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/SimpleRotatingQueue.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/SimpleRotatingSoftQueue.java
  dev/com.ibm.ws.logging_test/bnd.bnd
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/collector/manager/buffer/SimpleRotatingQueueTest.java
Labels: CLA Signed

#4339 use driver package to identify known data source class
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
Labels: CLA Signed, team:Zombie Apocalypse

#4347 Added doPriv for InetAddress related activity in messaging
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/comms/client/ClientSideConnection.java
Labels: CLA Signed, release bug

#4348 Added doPriv for InetAddress related activity in IIOP
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/css/CSSCompoundSecMechConfig.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/yoko/helper/SocketFactoryHelper.java
Labels: CLA Signed, release bug

#4321 Update eclipse settings for the com.ibm.ws.jaxrs.2.1_fat_executor proj
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#4352 Revert "Fix to remove early messages and early traces from BaseTraceService"
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#4349 Add FAT JDBC driver
  dev/com.ibm.ws.jdbc_fat_driver/.classpath
  dev/com.ibm.ws.jdbc_fat_driver/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDriver.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4297 Fix FaultToleranceCDIExtension and downgrade warning
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/FTGlobalConfig.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableClient.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableTest.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, ID review not needed

#4267 fix max connection when thread is interrupted
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
Labels: CLA Signed, team:Zombie Apocalypse

#4342 Issue #4341: Fix case where if PageControl's 'startIndex' is >0 and '…
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
Labels: CLA Signed, team:Wendigo East

#4344 use driver class name to guess data source class names
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
Labels: CLA Signed, team:Zombie Apocalypse

#4338 Added new methods to allow for a list of product ids to be passed
  dev/com.ibm.ws.install/src/com/ibm/ws/install/InstallKernel.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#4357 test for inferring data source class from driver class
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4361 test for discovering datasource class from JAR
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/xa/FAT2PCDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3978 Add product version to openliberty zip file names
  dev/build.image/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#4144 Provide link to plugin properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans.properties
Labels: CLA Signed, ID reviewed

#4374 Removed getIBMApplicationSession from Javadoc of IBMSession
  dev/com.ibm.ws.session/src/com/ibm/websphere/servlet/session/IBMSession.java
Labels: CLA Signed

#4372 Update for next beta version
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#4343 reverting all the changes made in PR3907
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Clock.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/ExpDecayingReservoir.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Histogram.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/HistogramImpl.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdder.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdderAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdderProxy.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Snapshot.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/StatisticsMeter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Striped64.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/TimeWeightedMeter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/WeightedSnapshot.java
  dev/com.ibm.ws.monitor/test/com/ibm/websphere/monitor/meters/StatisticsMeterTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/websphere/webcontainer/ServletStatsMXBean.java
Labels: CLA Signed

#4379 Add units for bulkhead.waiting.duration metric
  dev/com.ibm.ws.microprofile.faulttolerance.metrics/src/com/ibm/ws/microprofile/faulttolerance/metrics/integration/MetricRecorderImpl.java
Labels: CLA Signed

#4241 Add option for disabling generation of default keystore password
  dev/com.ibm.ws.appclient.boot.core/src/com/ibm/ws/appclient/boot/ClientBootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerHelpActions.java
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/CreateCommandTest.java
Labels: CLA Signed, in:Kernel/Bootstrap, team:Zombie Apocalypse

#4381 Issue #4254 : add auth filter support to mpjwt
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.0/com.ibm.websphere.appserver.mpJwt-1.0.feature
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MicroProfileJwtConfig.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
Labels: CLA Signed, team:Security SSO

#4239 release some more buffers to the buffer pools rather than have them get
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2MuxTCPReadCallback.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed

#4360 Fix logic regarding what goes into JSON formatting mode... e.g. Trace…
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
Labels: CLA Signed

#4370 Issue #4368 Avoid ConcurrentModificationException when sorting media types.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
Labels: CLA Signed

#3423 3422-Add warning for invalid config override
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/TypeBuilder.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/MergedConfigTests.java
Labels: CLA Signed, ID reviewed

#4385 Remove Java 6 toleration code that isn't needed. We support Java 7 +
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/ExponentiallyDecayingReservoir.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/ThreadLocalRandom.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/ThreadLocalRandomProxy.java
Labels: CLA Signed

#4384 move jdbc init code towards tolerance of driver class
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#4299 JPA 22 FAT: Initial drop of multi-db support (updated Callback bucket)
  dev/com.ibm.ws.jpa_22_fat/.classpath
  dev/com.ibm.ws.jpa_22_fat/bnd.bnd
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/DatabaseVendor.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa10/CallbackTest.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/helpers/DatabaseManagement/resources/databasemanagement.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_22_fat/test-applications/helpers/DatabaseManagement/src/jpahelper/databasemanagement/DatabaseManagementServlet.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/callback.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_HSQL.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_INFORMIX.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_ORACLE.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_CREATE_SYBASE.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_DB2.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_HSQL.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_INFORMIX.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_MYSQL.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/resources/ddl/WEB-INF/classes/JPA10_CALLBACK_DROP_SYBASE.ddl
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/src/jpa10callback/web/CallbackOrderOfInvocationTestServlet.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/src/jpa10callback/web/CallbackRuntimeExceptionTestServlet.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/src/jpa10callback/web/CallbackTestServlet.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/src/jpa10callback/web/DefaultListenerCallbackRuntimeExceptionTestServlet.java
  dev/com.ibm.ws.jpa_22_fat/test-applications/jpa10/callback/src/jpa10callback/web/DefaultListenerCallbackTestServlet.java
Labels: CLA Signed, in:JPA, noproductcode, priority/low, team:Blizzard

#4401 move built-in driver to end of list
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDriver.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4354 Include audit source into JSON Logging.
  dev/com.ibm.ws.collector.manager/src/com/ibm/ws/collector/manager/internal/CollectorManagerImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
Labels: CLA Signed
