Repository OpenLiberty/open-liberty, pull requests merged in 2018-03, with the labels that each got.

#2467 Deliver sessionCache-1.0 progress as of Feb 28th
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SessionInfo.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/listener1/SessionListener.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/listener2/SessionListener.java
Labels: CLA Signed, team:Zombie Apocalypse

#2469 test writeContents behaviors
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: team:Zombie Apocalypse

#2472 Support for session expiring via timeout
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SessionInfo.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: team:Zombie Apocalypse

#2475 Update sessionCache-1.0 to require a min of Java SE 8
  dev/com.ibm.websphere.appserver.sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.ws.session.cache/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/build.gradle
Labels: team:Zombie Apocalypse

#2479 test creationTime and lastAccessedTime
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: team:Zombie Apocalypse

#2271 Ensure providers in server are not constrained to the client.
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/ResourceUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#2463 PR for issue 2291: Fix class loader issue to get the default resource in the…
  dev/com.ibm.ws.jsf.shared/src/com/ibm/ws/jsf/shared/util/WSFacesUtil.java
Labels: CLA Signed

#2503 test concurrent putAttribute for new session attributes
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: team:Zombie Apocalypse

#2440 Microprofile Bulkhead: fix waitingTaskQueue default
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/policy/BulkheadPolicyImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/BulkheadTest.java
Labels: CLA Signed

#2454 Issue #2453 - use a common wlp managed container for tck
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#2100 Issue #1870 - disable implicit bean archive scanning
  dev/com.ibm.ws.cdi.1.2.weld/bnd.bnd
  dev/com.ibm.ws.cdi.1.2.weld/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.cdi.2.0.weld/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.cdi.2.0.weld/src/com/ibm/ws/cdi/config/liberty/CDI20ContainerConfig.java
  dev/com.ibm.ws.cdi.2.0_fat/publish/servers/cdi20ConfigServer/server.xml
  dev/com.ibm.ws.cdi.weld/bnd.bnd
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/config/liberty/CDI12ContainerConfig.java
Labels: CLA Signed, ID reviewed

#2410 Add support for future IBM JSSE ALPN
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLAlpnNegotiatorJdk8.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLConnectionContextImpl.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/srt/SRTConnectionContext31.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed

#2455 Fix MicroProfile FATs which repeat tests at the class level
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/ImplicitConverterTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIBuiltInConverterTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIConfigPropertyTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIFieldInjectionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIXtorInjectionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ConvertersTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DynamicSourcesTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIAsyncTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIFallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDITimeoutTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/validation/AppValidator.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/validation/ValidationTest.java
Labels: CLA Signed, noproductcode

#2470 Add FFDCIgnore to updateNonRecurseFileMonitorService to match other methods
  dev/com.ibm.ws.artifact.loose/src/com/ibm/ws/artifact/loose/internal/LooseArtifactNotifier.java
Labels: CLA Signed

#2494 Issue 2235: Change the useEE7Streams to use the declarative service v…
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpResponseImpl.java
Labels: CLA Signed

#2491 Update name of jcacheContainer-1.1 feature.
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/.classpath
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/.project
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/bnd.bnd
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/resources/l10n/com.ibm.websphere.appserver.jcacheContainer-1.1.properties
  dev/com.ibm.websphere.appserver.sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
Labels: team:Zombie Apocalypse

#2488 Make the timeout more lenient on FT testTimeout
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/TimeoutServlet.java
Labels: CLA Signed, noproductcode

#2512 Add test case for refreshing the session access time
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: team:Zombie Apocalypse

#2462 Handle EJContainer disabled during stopModule
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/StatefulBeanReaper.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
Labels: CLA Signed

#2376 encodePassword update
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapHelper.java
Labels: CLA Signed

#2504 Defer decoding until after FormUtils map is populated
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: in:JAX-RS, team:Wendigo West

#2496 #2497 JSONLogging Changed copy in read to copy on write for BufferManagerImpl
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
Labels: CLA Signed

#2493 Disabling time sensitive MP Metrics tests
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/Metrics, noproductcode, team:Lumberjack

#2501 Added back mpMetrics 1.1 fat tck project
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArchiveProcessor.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, in:MicroProfile/Metrics, noproductcode, team:Lumberjack

#2521 Update session cache metatype to sentence case
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
Labels: ID required, ID reviewed, team:Zombie Apocalypse

#2447 Initial commit: WebContainer now sets the remote user on the channel
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogRemoteUser.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/outstream/HttpOutputStreamConnectWeb.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: CLA Signed

#2523 Ensure preShutdown invokes preShutdown of LibertyApplicationBusListeners
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/bus/LibertyApplicationBusFactory.java
Labels: CLA Signed, in:Web Services, team:Wendigo West

#2519 Fix issue #2517: Adding an @FFDCIgnore for an InstanceNotFoundException.
  dev/com.ibm.ws.jmx/src/com/ibm/ws/jmx/internal/DelayedMBeanActivatorHelper.java
Labels: CLA Signed

#2500 Issue 2499: Double check DB file props for EL FAT test
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseIdstoreDeferred.war/src/web/war/database/deferred/DatabaseSettingsBean.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#2522 Avoid leaking Bus objects in the busSet
  dev/com.ibm.ws.jaxws.wsat/src/com/ibm/ws/jaxws/wsat/WSATFeatureBusListener.java
Labels: in:Transactions, in:Web Services, team:Wendigo West

#2540 More eclipse cleanup
  dev/com.ibm.websphere.appserver.jpa-2.2/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed

#2448 Refactor RememberMe interceptor for CTS issue #2338
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/RememberMeInterceptor.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/RememberMeInterceptorTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/RememberMeTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextJaxRSTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/rememberMe.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/mechanisms/BaseAuthMech.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/mechanisms/rememberme/DefaultRememberMeAuthMech.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/mechanisms/rememberme/secureonlyfalse/SecureOnlyFalseHttpOnlyFalseRememberMeAuthMech.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/servlets/unprotected/rememberme/UnprotectedServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecBase.jar/src/web/jar/base/FlexibleBaseServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/SecureOnlyFalseHttpOnlyFalseRememberMe.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/SecureOnlyFalseHttpOnlyFalseRememberMe.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/UnprotectedRememberMe.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/UnprotectedRememberMe.war/resources/WEB-INF/web.xml
Labels: CLA Signed

#2509 Remove exception message check from test
  dev/com.ibm.ws.repository_fat/fat/src/com/ibm/ws/repository/transport/client/test/InvalidZipClientTest.java
Labels: CLA Signed, noproductcode

#2516 test for SessionScoped
  dev/com.ibm.ws.session.cache_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/cdi/SessionScopedBean1.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/cdi/SessionScopedBean2.java
Labels: CLA Signed, ID review not needed, team:Zombie Apocalypse

#2266 Initial commit: flipping behavior of httpOption throwIOExceptionForInboundConnections to default true.
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/HttpDispatcher.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpTransportBehavior.java
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
Labels: CLA Signed

#2316 Copy the input stream sent to providers to avoid premature close
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentDeserializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/DataSourceProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#2534 Move sessionCache-1.0 and jcacheContainer-1.1 into beta
  dev/com.ibm.websphere.appserver.jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
  dev/com.ibm.websphere.appserver.sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#2545 Extend FAT timeout to 5 hours
  dev/com.ibm.ws.kernel.feature_fat/build-test.xml
Labels: CLA Signed, noproductcode

#2541 Port PR #2404 to integration branch
  dev/com.ibm.ws.artifact.zip/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingProperties.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingService.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipFileHandle.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/CacheHashMap.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingServiceImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/package-info.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ContainerFactoryHolder.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/FileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/SystemUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/Utils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntryIterator.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileNestedDirContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/package-info.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/ArtifactAPIServlet.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/notification/JarArtifactNotificationTest.java
Labels: CLA Signed

#2551 Move javax.cdi-2.0 feature from 'noship' to 'beta'
  dev/com.ibm.websphere.appserver.javax.cdi-2.0/com.ibm.websphere.appserver.javax.cdi-2.0.feature
Labels: CLA Signed

#2526 add hs256
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
Labels: CLA Signed

#2549 Use an info message for configuration conflicts
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigValidator.java
Labels: CLA Signed

#1886 generate resolution report after feature manager provision
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.service/bnd.bnd
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ResolutionReportHelper.java
Labels: CLA Signed

#2553 Test that maxInactiveInterval is properly used for invalidation
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2576 Revert "Use an info message for configuration conflicts"
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigValidator.java
Labels: CLA Signed

#2525 Issue #2498 Removed static lock from buffermanager impl
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerEMQHelper.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
Labels: CLA Signed

#2530 Update microProfile1 server template to use microProfile-1.3
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile1/server.xml
Labels: CLA Signed

#2585 Fix build break caused by PR #2525
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/EMQSychronousHandlerTest.java
Labels: CLA Signed, noproductcode

#2586 Revert "Fix build break caused by PR #2525"
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/EMQSychronousHandlerTest.java
Labels: CLA Signed, noproductcode

#2587 Revert "Issue #2498 Removed static lock from buffermanager impl"
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerEMQHelper.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
Labels: CLA Signed

#2575 Issue #2571 - add permissions.xml to fix J2S issue
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientSecurityTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/test-applications/appClientSecurity.ear/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode

#2533 Replace Weld 3.0.2 with 3.0.3
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.jsf/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.web/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld.3.0/bnd.overrides
Labels: CLA Signed

#2560 Issue 2165: Removing invalid use of MemorySessions
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#2595 2255 master cache common fields for json logging
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
Labels: CLA Signed

#2596 test cache contents after multithreaded usage
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#2593 eclipse and bnd updates for new springboot components.
  dev/com.ibm.ws.app.manager.springboot/bnd.bnd
  dev/com.ibm.ws.springboot.support.shutdown/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version20.test.app/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.springboot.support.version20.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.web.server.version15/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server.version20/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server/bnd.bnd
Labels: CLA Signed

#1995 useGroupAsRole only for app
  dev/com.ibm.ws.security.authorization.builtin/src/com/ibm/ws/security/authorization/builtin/internal/BuiltinAuthorizationService.java
  dev/com.ibm.ws.security.authorization.builtin/test/com/ibm/ws/security/authorization/builtin/internal/BuiltinAuthorizationServiceTest.java
Labels: CLA Signed

#2079 return 401 instead of 403
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashNoConfigTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBNoUserTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplCustomTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreBasicTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_singleIS/BasicAuthenticationMechanismSingleISTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/ChallengeReply.java
Labels: CLA Signed

#2492 check for all SqlSyntaxErrorException classes when creating PSU
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
Labels: CLA Signed

#2555 cache json message into generic data object
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
Labels: CLA Signed

#2588 Revert 2587 revert 2525 json remove static lock
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerEMQHelper.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/EMQSychronousHandlerTest.java
Labels: CLA Signed

#2619 MicroProfile 1.3 toleration of EE8 features
  dev/com.ibm.websphere.appserver.microProfile-1.3/com.ibm.websphere.appserver.microProfile-1.3.feature
  dev/com.ibm.websphere.appserver.mpOpenTracing-1.0/com.ibm.websphere.appserver.mpOpenTracing-1.0.feature
Labels: CLA Signed, in:MicroProfile, team:Zombie Apocalypse

#2608 Add com.ibm.ws.repository.generator project
  dev/com.ibm.ws.repository.generator/.classpath
  dev/com.ibm.ws.repository.generator/.project
  dev/com.ibm.ws.repository.generator/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.repository.generator/bnd.bnd
  dev/com.ibm.ws.repository.generator/build.gradle
  dev/com.ibm.ws.repository.generator/src/com/ibm/ws/repository/generator/SingleJsonRepositoryGenerator.java
  dev/com.ibm.ws.repository.generator/src/com/ibm/ws/repository/generator/default.properties
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/RepositoryResourceImpl.java
Labels: CLA Signed

#2616 Clean up test file before+after tests for windows on Oracle JDK
  dev/com.ibm.ws.repository/test/com/ibm/ws/repository/connections/test/SingleFileRepositoryConnectionTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2520 PR for Issue 2170: Create common security FAT infrastructure project
  dev/com.ibm.ws.security.fat.common/.classpath
  dev/com.ibm.ws.security.fat.common/.gitignore
  dev/com.ibm.ws.security.fat.common/.project
  dev/com.ibm.ws.security.fat.common/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectations.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/package-info.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/package-info.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonExpectationTestClass.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationsTest.java
Labels: CLA Signed, team:Security SSO

#2527 add message for error condition
  dev/com.ibm.ws.security.mp.jwt.cdi/resources/com/ibm/ws/security/mp/jwt/cdi/resources/JwtCDI.nlsprops
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/JsonWebTokenBean.java
Labels: CLA Signed, ID reviewed

#2623 More eclipse and build cleanup
  dev/com.ibm.ws.install/.classpath
  dev/com.ibm.ws.repository.generator/.settings/bndtools.core.prefs
  dev/com.ibm.ws.repository.generator/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version20.test.app/.settings/bndtools.core.prefs
Labels: CLA Signed, noproductcode

#2621 Change the lib-index-cache to preserve original jar names inside a di…
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/LibIndexCache.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
Labels: CLA Signed

#2622 Move artifact_test tests under their appropriate source component.
  dev/com.ibm.ws.adaptable.module/.classpath
  dev/com.ibm.ws.adaptable.module/bnd.bnd
  dev/com.ibm.ws.adaptable.module/test/com/ibm/ws/adaptable/module/internal/InterpretedNotifierTest.java
  dev/com.ibm.ws.artifact.loose/.classpath
  dev/com.ibm.ws.artifact.loose/bnd.bnd
  dev/com.ibm.ws.artifact.loose/test/InvalidXml.xml
  dev/com.ibm.ws.artifact.loose/test/com/ibm/ws/archive/LooseConfigTest.java
  dev/com.ibm.ws.artifact.url/.classpath
  dev/com.ibm.ws.artifact.url/bnd.bnd
  dev/com.ibm.ws.artifact.url/test/com/ibm/ws/artifact/zip/internal/ZipFileContainerTest.java
  dev/com.ibm.ws.artifact_test/.classpath
  dev/com.ibm.ws.artifact_test/.gitignore
  dev/com.ibm.ws.artifact_test/.project
  dev/com.ibm.ws.artifact_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.artifact_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.artifact_test/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.artifact_test/bnd.bnd
  dev/com.ibm.ws.artifact_test/publish/features/artifactapilibertyinternals-1.0.mf
Labels: CLA Signed

#2583 Publish a beta features list
  dev/cnf/build.gradle
Labels: CLA Signed, noproductcode

#2606 add missing numeric char to messages
  dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops
Labels: CLA Signed

#2377 JSR375:Fix ClassCastException when SecurityContext is used in an EJB
  dev/com.ibm.ws.security.javaeesec.cdi/resources/com/ibm/ws/security/javaeesec/cdi/internal/resources/JavaEESecMessages.nlsprops
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/LoginToContinueInterceptor.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/Utils.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/SecurityContextImpl.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/JavaEESecConstants.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtils.java
  dev/com.ibm.ws.security.javaeesec/test/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtilsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/securityContextHamApp.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/util/MetaDataThreadContext.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/util/WebConfigUtils.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/util/WebConfigUtilsTest.java
Labels: in:Security, team:Core Security

#2573 Fix issue #2572: rename and add permissions
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/test-applications/CDIFaultToleranceMetrics.war/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode, team:MicroProfileUK

#2635 disallow advanced session manager properties and use default values
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#2636 Use version qualifier for zip output for consistency with bundles
  dev/build.image/build.gradle
Labels: CLA Signed

#2628 Add OpenTracing TCK FAT
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATSuite.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncher.java
  dev/com.ibm.ws.opentracing_fat/publish/servers/OpentracingTCKServer/apps/.gitignore
  dev/com.ibm.ws.opentracing_fat/publish/servers/OpentracingTCKServer/bootstrap.properties
  dev/com.ibm.ws.opentracing_fat/publish/servers/OpentracingTCKServer/jvm.options
  dev/com.ibm.ws.opentracing_fat/publish/servers/OpentracingTCKServer/server.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/pom.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/.gitignore
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#2594 update CXF binaries
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.jaxws.wsat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-api.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-core.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-transports-http.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-ws-policy.bnd
Labels: CLA Signed

#2648 Update new http2 projects to build in eclipse correctly.
  dev/com.ibm.ws.http2.client/.classpath
  dev/com.ibm.ws.http2.client/.project
  dev/com.ibm.ws.http2.client/.settings/bndtools.core.prefs
  dev/com.ibm.ws.http2.client/bnd.bnd
  dev/com.ibm.ws.transport.http2_fat/.classpath
  dev/com.ibm.ws.transport.http2_fat/.project
  dev/com.ibm.ws.transport.http2_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transport.http2_fat/build.gradle
Labels: CLA Signed

#2654 Extend CDI package import range to include CDI 2.0
  dev/com.ibm.ws.microprofile.opentracing/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#2660 Revert "Extend CDI package import range to include CDI 2.0"
  dev/com.ibm.ws.microprofile.opentracing/bnd.bnd
Labels: CLA Signed

#2661 Import CDI packages with range [1.1,2.1)
  dev/com.ibm.ws.microprofile.opentracing/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#2603 2365 improve tck stdout
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#2650 Manage writable Spring lib.index.cache under the server workarea
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/LibIndexCache.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringConstants.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/PreThinnedSpringBootTests.java
Labels: CLA Signed

#2649 fix user name in generated token
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/TokenBuilder.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/utils/TokenBuilderTest.java
Labels: CLA Signed

#2640 Stop SourceManger from removing the BufferManager from LogSource or TraceSource
  dev/com.ibm.ws.collector.manager/src/com/ibm/ws/collector/manager/internal/SourceManager.java
Labels: CLA Signed, team:Lumberjack

#2554 Issue #1767 Fixed and re-enabled broken disabled logging FAT tests
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/AbstractStackTraceFilteringTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/FATSuite.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForBadlyWrittenThrowableTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForIBMFeatureExceptionTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForLoggedExceptionParametersTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForLoggedExceptionWithACauseParametersTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForNoClassDefFoundErrorTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForPrintedExceptionTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForPrintedExceptionWithIBMCodeAtTopTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForSpecificationClassesExceptionTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceFilteringForUserFeatureExceptionTest.java
  dev/com.ibm.ws.logging_fat/test.configuration.fallalloverthefloor.userfeature.bnd
Labels: CLA Signed, noproductcode

#2542 Issue #2418 Not printing extensions if none exist
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
Labels: CLA Signed

#2670 Use unique hazelcast cluster names in session.cache_fat
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#2664 quarantine HTTP/2 FATs while debugging timing issues
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
Labels: CLA Signed, noproductcode

#2669 Increase MP Metrics undeploy timeout to 20s
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, in:MicroProfile/Metrics, noproductcode, team:Lumberjack

#2655 fix HTTP/2 authority header processing
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
Labels: CLA Signed

#2667 Only attempt to load .properties files when validating product matche…
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractor.java
Labels: CLA Signed, team:Zombie Apocalypse

#2647 don't convert numbers to Strings in GenericData.addPair
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueIntegerPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueLongPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValuePair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValuePairList.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueStringPair.java
  dev/com.ibm.ws.logging_fat/test-bundles/trace.source.handler/src/trace/source/handler/TraceHandlerImpl.java
Labels: CLA Signed

#1861 Initial code pass of configured H2 enablement
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannel.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannelConstants.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/websphere/channelfw/osgi/CHFWBundle.java
  dev/com.ibm.ws.channelfw/src/com/ibm/wsspi/channelfw/HttpProtocolBehavior.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpChain.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpEndpointImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee8/Http2InboundConnection.java
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/upgrade/H2HandlerImpl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd
Labels: CLA Signed

#2679 Uninstall leftover app configurations on restart
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootHandler.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/WarmStartTests.java
Labels: CLA Signed, springboot

#2690 springboot support: missed codepath in earlier fix to store boot-inf/…
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/LibIndexCreateTest.java
  dev/com.ibm.ws.app.manager.springboot/test/readme
Labels: CLA Signed, springboot

#2673 2284 make incomplete config source work
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/CompositeConfig.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/AbstractConfig.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/AbstractConfigSource.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/TestUtils.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/basic/test/BasicConfigSource.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/basic/test/EmptyNullStringTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/basic/test/SourcedValueTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/basic/test/ValueOnlyConfigSource.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/basic/test/ValueOnlyTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/dynamic/test/DynamicSourceTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/extended/test/WebSphereConfigTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/loader/test/ConfigSourceServiceLoaderTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/statik/test/StaticSourceTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/xml/test/GenericXMLConfigSource.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/xml/test/HashMapConfigSource.java
  dev/com.ibm.ws.microprofile.config_fat/bnd.bnd
Labels: in:MicroProfile/Config, team:MicroProfileUK

#2699 Revert "2444 - fix user being unable to modify the EntityStream from a ClientRequestFilter"
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/spec/ClientRequestFilterInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/stream/ProxyOutputStream.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientRequestFilterInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/stream/ProxyOutputStream.java
Labels: CLA Signed

#2686 2632 allow multiple app properties
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/AppPropertyConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/serverXMLApp/src/com/ibm/ws/microprofile/config13/serverXML/web/ServerXMLBean.java
Labels: CLA Signed

#2653 test should poll cache instead of doing lengthy sleep
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheSession.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse, test bug

#2085 Issue #2055: Update README to include pause and resume
  dev/build.image/publish/README.TXT
Labels: bug, team:Zombie Apocalypse

#2697 Eclipse cleanup
  dev/com.ibm.ws.org.apache.cxf.3.2.jaxrs/.classpath
  dev/com.ibm.ws.org.apache.cxf.3.2.jaxrs/.gitignore
  dev/com.ibm.ws.org.apache.cxf.3.2.jaxrs/.project
  dev/com.ibm.ws.org.apache.cxf.3.2.jaxrs/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.3.2.jaxrs/build.xml
  dev/com.ibm.ws.org.apache.cxf.jaxrs/.classpath
  dev/com.ibm.ws.org.apache.cxf.jaxrs/.gitignore
  dev/com.ibm.ws.org.apache.cxf.jaxrs/.project
  dev/com.ibm.ws.org.apache.cxf.jaxrs/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.jaxrs/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxrs/build.xml
  dev/com.ibm.ws.springboot.support_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed

#2698 [2627] Push RestServlet init props to Bus
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsServerFactoryBean.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#2705 Direct stderr to the same output file when running Maven in the build
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#2703 Issue #2700 - turn faulttolerance trace back on to help with RTC 252617
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/RetryConfig.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/RetryImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTckLauncher.java
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/servers/FaultToleranceTCKServer/bootstrap.properties
Labels: CLA Signed

#2490 update micro version for next release
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#2720 disable portion of test with intermittent failure while being investigated
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2689 2359 reduce tracing volume for com ibm ws star trace
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging_fat/publish/servers/SampleSourceHandlerServer/bootstrap.properties
Labels: CLA Signed

#2723 fix bug in testActionlessFutureWithSpecifiedExecutor
  dev/com.ibm.ws.concurrent_fat_rx/test-applications/concurrentrxfat/src/web/ConcurrentRxTestServlet.java
Labels: team:Zombie Apocalypse

#2730 Find latest version in maven repo for replacements
  dev/cnf/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#2741 Revert "Issue1693 jmx audit"
  dev/com.ibm.websphere.security.audit/src/com/ibm/ws/security/audit/utils/SecurityUtils.java
  dev/com.ibm.websphere.security.audit/src/com/ibm/ws/security/audit/utils/package-info.java
  dev/com.ibm.websphere.security/bnd.bnd
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditConstants.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/utils/SecurityUtils.java
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/utils/package-info.java
  dev/com.ibm.ws.jmx/.classpath
  dev/com.ibm.ws.jmx/src/com/ibm/ws/jmx/internal/DelayedMBeanActivator.java
  dev/com.ibm.ws.jmx/src/com/ibm/ws/jmx/internal/DelayedMBeanActivatorHelper.java
  dev/com.ibm.ws.security.audit.utils/src/com/ibm/ws/security/audit/utils/AuditConstants.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/Audit.java
Labels: CLA Signed

#2728 Fix WLP-ServerVersion in WebContainer
  dev/com.ibm.ws.webcontainer/bnd.bnd
Labels: CLA Signed

#2734 simplicity objects for httpSessionCache
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpSessionCache.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpSessionCacheProperties.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: team:Zombie Apocalypse

#2738 Enable async fault tolerance tests
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/servers/FaultToleranceTCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#2677 HTTP/2 FAT fixes
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResultManager.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/connection/H2Connection.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/FrameReadProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.tracing/common.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.tracing/server.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat/common.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat/server.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/http2ClientRuntime.tracing/common.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/http2ClientRuntime.tracing/server.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/http2ClientRuntime/common.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/http2ClientRuntime/server.xml
Labels: CLA Signed

#2744 create fat bucket for config updates to httpSessionCcahe
  dev/com.ibm.ws.session.cache_fat_config/.classpath
  dev/com.ibm.ws.session.cache_fat_config/.project
  dev/com.ibm.ws.session.cache_fat_config/.settings/bndtools.core.prefs
  dev/com.ibm.ws.session.cache_fat_config/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.session.cache_fat_config/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.session.cache_fat_config/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.session.cache_fat_config/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config/build.gradle
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat_config/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: team:Zombie Apocalypse

#2736 Issue #2626 V2 changed values to constants
  dev/com.ibm.ws.collector.manager/src/com/ibm/ws/logging/ffdc/source/FFDCSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/LogFieldConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/source/AccessLogSource.java
Labels: CLA Signed

#2721 Check to see if the channel framework is stopped before calling connectAsynch
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/richclient/framework/impl/CFWNetworkConnection.java
Labels: CLA Signed

#2751 Call send listeners once writing thread has become idle.
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/ConnectionWriteCompletedCallback.java
Labels: CLA Signed

#2668 1784 pull in my faces230
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/build.xml
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIComponentBase.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIData.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIInput.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UISelectOne.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/convert/EnumConverter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/model/IterableDataModel.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/BeanValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/DoubleRangeValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/LengthValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/LongRangeValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/MethodExpressionValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/RegexValidator.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/NavigationHandlerImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ResourceHandlerImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/application/FacesServletMappingUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/HtmlSelectableRendererBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/util/ClassUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/component/UIRepeat.java
Labels: CLA Signed

#2431 Issue 2430: Make `@RegisterRestClient` a bean-defining annotation
  dev/com.ibm.ws.microprofile.rest.client.cdi/src/com/ibm/ws/microprofile/rest/client/cdi/LibertyRestClientExtension.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/BasicServiceClient.java
Labels: CLA Signed, in:CDI, in:MicroProfile, team:Wendigo West

#2754 PR for Issue 2753: Create JWT SSO FAT project
  dev/com.ibm.ws.security.jwtsso_fat/.classpath
  dev/com.ibm.ws.security.jwtsso_fat/.project
  dev/com.ibm.ws.security.jwtsso_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.jwtsso_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.jwtsso_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.jwtsso_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.jwtsso_fat/bnd.bnd
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/bootstrap.properties
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/server.xml
Labels: CLA Signed, noproductcode, team:Security SSO

#2607 Check SQLException error message for unsupported methods
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#2589 Entity casting in various Bridge classes
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPReferralTest.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/DisplayNameBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/MembershipBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SearchBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SecurityNameBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/UniqueIdBridge.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#2786 Issue 2785: Update the classpath in both MyFaces 2.3 IMPL and API to …
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.ws.org.apache.myfaces.2.3/.classpath
Labels: CLA Signed, noproductcode

#2729 2436 additional Json FAT Tests
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/FATSuite.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/TestUtils.java
  dev/com.ibm.ws.logging.json_fat/publish/files/basicConsoleBasicMessage.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/basicConsoleJsonMessage.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/basicConsoleJsonMessageMaxFileSize.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/basicConsoleJsonMessageTraceAccess.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/clearLoggingSources.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/consoleLogLevelError.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/consoleLogLevelInfoBasicConsole.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/consoleLogLevelWarning.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonConsoleJsonMessage.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonConsoleJsonMessageTraceEnabled.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonMessageSourceAccessLog.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonSourceMessageTraceAccess.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/traceConsoleAccessTraceMessage.xml
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.JsonConfigServer/bootstrap.properties
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.JsonConfigServer/server.xml
  dev/com.ibm.ws.logging.json_fat/test-applications/LogstashApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.logging.json_fat/test-applications/LogstashApp/src/com/ibm/logs/LogServlet.java
Labels: CLA Signed, noproductcode

#2680 Updated uid assertion logic for special UserRegistry implementation
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/jaas/modules/ServerCommonLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/CertificateLoginModule.java
Labels: CLA Signed

#2790 Fix for Issue #2766: fix URI_TEMPLATE_CACHE
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
Labels: CLA Signed, in:JAX-RS, priority/high, team:Wendigo West

#2784 Include path parameters in the parameter list maintained by the
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/HandshakeProcessor.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/external/HandshakeRequestExt.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/external/WsocHandlerImpl.java
Labels: CLA Signed

#2761 Pass null for caller DN on DatabaseIdentityStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
Labels: in:CTS, team:Wendigo East

#2760 Cache constructor parameters and annotations.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProvider.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
Labels: CLA Signed

#2313 Remove JaxRsModuleMetaData from overlay cache on app shutdown
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/component/JaxRsModuleMetaDataListener.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/component/JaxRsModuleMetaDataListener.java
Labels: in:JAX-RS, team:Wendigo West

#2795 2777 my faces4205
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/ExternalContext.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/StartupServletExternalContextImpl.java
Labels: CLA Signed

#2781 JSR375:Fix sec context issue by sec cookie
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/SecurityCookieImpl.java
Labels: CLA Signed

#2771 Issue #2767: Added copywrite header for EMQSychronousHandlerTest
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/DummyHandler.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/EMQSychronousHandlerTest.java
Labels: CLA Signed, noproductcode

#2829 Cleanup stuff
  dev/com.ibm.websphere.security.audit/src/com/ibm/ws/security/audit/utils/SecurityUtils.java
  dev/com.ibm.websphere.security.audit/src/com/ibm/ws/security/audit/utils/package-info.java
  dev/com.ibm.ws.jmx/.classpath
Labels: CLA Signed

#2750 update com.ibm.wsspi.http.ee8 version
  dev/com.ibm.websphere.appserver.httptransport-1.0/com.ibm.websphere.appserver.httptransport-1.0.feature
  dev/com.ibm.websphere.appserver.spi.httptransport/bnd.bnd
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee8/package-info.java
Labels: CLA Signed

#2762 test for config update to writeFrequency and writeInterval
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_config/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2820 JSR375:fix ModulePropertiesUtils and it's UT.
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtils.java
  dev/com.ibm.ws.security.javaeesec/test/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtilsTest.java
Labels: in:Security, team:Core Security

#2742 relax checks on adding ejb descriptor
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
Labels: CLA Signed

#2831 2800 myfaces4207
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/WebsocketEvent.java
Labels: CLA Signed

#2807 Add messaging FAT test framework and basic messaging tests
  dev/com.ibm.ws.messaging.open_fat/.classpath
  dev/com.ibm.ws.messaging.open_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.messaging.open_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.messaging.open_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_fat/build.gradle
  dev/com.ibm.ws.messaging.open_fat/fat/src/com/ibm/ws/messaging/open/FATSuite.java
  dev/com.ibm.ws.messaging.open_fat/fat/src/com/ibm/ws/messaging/open/TestLocal.java
  dev/com.ibm.ws.messaging.open_fat/fat/src/com/ibm/ws/messaging/open/TestRemote.java
  dev/com.ibm.ws.messaging.open_fat/publish/servers/FATJmsServer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_fat/publish/servers/FATJmsServer/server.xml
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/resources/index.jsp
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/JmsTests.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/TestLocalJmsServlet.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/TestRemoteJmsServlet.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/ConnectionFactoryType.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/JmsTestFramework.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/JmsTestsBase.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/JmsTestsImpl.java
Labels: CLA Signed, noproductcode

#2704 2646 fix duplicate wto message print
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/test/com/ibm/ws/logging/internal/osgi/WsMessageRouterImplTest.java
Labels: CLA Signed

#2671 update messages pulled from WS-CD
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_cs.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_de.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_es.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_fr.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_hu.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_it.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_ja.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_ko.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_pl.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_pt_BR.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_ro.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_ru.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_zh.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel_zh_TW.nlsprops
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/Repository_de.nlsprops
Labels: CLA Signed, ID reviewed

#2821 Remove sync block to improve concurrency in WebContainer
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/CacheServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/FileServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
Labels: CLA Signed

#2592 Synchronize the push_promise frames.
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/FrameTypes.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameHeaders.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePPHeaders.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/PushPromiseTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2TestModule.war/src/http2/test/war/servlets/H2PushPromise.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2TestModule.war/src/http2/test/war/servlets/PushBuilderAPIServlet.java
Labels: CLA Signed

#2794 JSR375:make sure that ValidationType objects are used as it is.
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/ELHelper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/IdentityStoreHandlerImpl.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseIdstoreDeferred.war/src/web/war/database/deferred/DatabaseSettingsBean.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecAnnotatedBasicAuthServletDeferred.war/src/web/war/annotatedbasic/deferred/LdapSettingsBean.java
Labels: in:Security, team:Core Security

#2838 JSR375:2837:Return 200 if target is unprotected even authentication failure happens.
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
Labels: CLA Signed, in:Security, team:Core Security

#2840 2832 myfaces4208
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/PartialViewContext.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/ResponseWriterWrapper.java
Labels: CLA Signed

#2836 Simplify clearQueue test implementation
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/JmsTestFramework.java
Labels: CLA Signed, noproductcode
