Repository OpenLiberty/open-liberty, pull requests merged in 2018-12, with the labels that each got.

#5894 test case is missing code to wait for termination before verifying the state
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5906 translatable messages for MP Concurrency
  dev/com.ibm.ws.concurrent.mp.1.0/resources/com/ibm/ws/concurrent/mp/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent/resources/com/ibm/ws/concurrent/resources/CWWKCMessages.nlsprops
Labels: CLA Signed, team:Zombie Apocalypse

#5902 change withCurrentContext completion stages to run on same thread, per spec
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/SameThreadExecutor.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextImpl.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed

#5859 Correct copyright statements
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/ConstructorInjectionServlet.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/EjbImpl.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/FirstManagedBeanInterface.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/ManagedSimpleBean.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/SecondManagedBeanInterface.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/test-applications/archiveWithNoBeansXML.war/src/com/ibm/ws/cdi12/test/ejbsNoBeansXml/SimpleServlet.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/WebListener.war/src/com/ibm/ws/cdi/test/session/destroy/InvalidateServlet.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/WebListener.war/src/com/ibm/ws/cdi/test/session/destroy/SimpleSessionBean.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/WebListener.war/src/com/ibm/ws/cdi/test/session/destroy/TimeoutServlet.java
Labels: CLA Signed, noproductcode

#5884 5883 managed object getbeans
  dev/com.ibm.ws.cdi.noncontextual_fat/bnd.bnd
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/VetoAndExtendTests.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/vetoAndExtendServer/.gitignore
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/vetoAndExtendServer/bootstrap.properties
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/vetoAndExtendServer/server.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/src/test/vetoandextend/MyBean.java
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/src/test/vetoandextend/MyServlet.java
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/src/test/vetoandextend/ServletExtension.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/AbstractManagedObjectFactory.java
Labels: CLA Signed

#5077 3645 sync user during login
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorFactory.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAuthenticatorFactoryImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/AuthenticateApiTest.java
Labels: release bug

#5501 Initial commit for Forwarding and X-Forwarded-* header support
  dev/com.ibm.ws.transport.http/bnd.bnd
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogRemoteHost.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogRemoteIP.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogRequestProtocol.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpChain.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpEndpointImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/HttpInboundConnection.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInboundConnectionExtended.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: CLA Signed, ID reviewed, in:Web Components, team:Sirius

#5797 Issue 5789 - use jar/wsjar protocol for root dirctory
  dev/com.ibm.ws.classloading/bnd.bnd
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoaderFactory.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ParentLastClassLoader.java
  dev/com.ibm.ws.classloading_test/bnd.bnd
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/LibertyClassLoaderTest.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/ProtectionDomainTest.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/TestUtil.java
  dev/com.ibm.ws.springboot.support.version20.test.war.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.war.app/module/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.war.app/module/src/main/java/com/ibm/ws/multimodule/module/ModuleBean.java
  dev/com.ibm.ws.springboot.support.version20.test.war.app/module/src/main/resources/application-context-module.xml
  dev/com.ibm.ws.springboot.support.version20.test.war.app/src/main/java/com/ibm/ws/springboot/support/version20/test/war/app/RootBean.java
  dev/com.ibm.ws.springboot.support.version20.test.war.app/src/main/java/com/ibm/ws/springboot/support/version20/test/war/app/TestJSPApplication.java
  dev/com.ibm.ws.springboot.support.version20.test.war.app/src/main/resources/application-context.xml
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MultiModuleProjectTests20.java
  dev/settings.gradle
Labels: CLA Signed

#5896 Increase timeout for slower test machines.
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/asyncApp/src/mpRestClient11/async/AsyncTestServlet.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#5897 Increase timeout for slow test machines.
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicClientApp/src/mpRestClient10/basic/BasicClientTestServlet.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#5891 Improved Uninstall Runtime Performance
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Engine.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/adaptor/ESAAdaptor.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/asset/UninstallAsset.java
  dev/com.ibm.ws.install/test/com/ibm/ws/install/CheckFileLockedTest.java
Labels: CLA Signed

#5911 Ignore svc ref warning for test svc component
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JsonUserFeatureTest.java
Labels: CLA Signed, noproductcode

#5925 Reordered the testInvalidPaddingValue test to put the expected frame in
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
Labels: CLA Signed, noproductcode

#5799 Separate Write and Read Continuation Frame tracking to fix a problem in
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed, in:Transport, team:Sirius

#5826 Set 400 SC for too many traversed parent URI
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed, in:Web Components, team:Sirius

#5879 FIX added a check to make sure jax-ws components are not tested with Java version above Java8
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter1.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter2.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter3.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter4.xml
Labels: CLA Signed, noproductcode

#5918 Issue #5917: Give x a value in test
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/src/com/ibm/ws/el30/fat/servlets/EL30OperatorPrecedenceServlet.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/src/com/ibm/ws/el30/fat/servlets/EL30OperatorsServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#5533 rename groupConfiguration to match xml element
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATTestIDS_allIbmGroups.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/GroupProperties.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#5944 Re-order dynamic config tests to end of bucket, and swap to FULL mode
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/JDBCDerbyTest.java
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/JDBCDynamicConfigTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5927 social oidc client messages updates for provider discovery
  dev/com.ibm.ws.security.common/resources/com/ibm/ws/security/common/internal/resources/SSOCommonMessages.nlsprops
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/config/DiscoveryConfigUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, team:Security SSO

#5939 Tolerate longer timeout delay in transactions test
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/SimpleServlet.java
Labels: CLA Signed, noproductcode

#5935 Improve FFDC handling in FATRunner
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode, team:Sirius, test bug

#5947 Increase the default TCCL lock acquisition timeout for FATs
  dev/fattest.simplicity/autoFVT-defaults/testports.properties
Labels: CLA Signed, noproductcode, team:Sirius, test bug

#5571 PR for issue 5206: Test X-Forwarded-* and Forwarded header support
  dev/com.ibm.ws.transport.http.remoteip_fat/.classpath
  dev/com.ibm.ws.transport.http.remoteip_fat/.project
  dev/com.ibm.ws.transport.http.remoteip_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transport.http.remoteip_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transport.http.remoteip_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transport.http.remoteip_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transport.http.remoteip_fat/bnd.bnd
  dev/com.ibm.ws.transport.http.remoteip_fat/build.gradle
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/FATSuite.java
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpXForwardedAndForwardedHeaderTests.java
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/IPv4IPv6RemoteIP-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/accessLogRemoteIP-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/defaultRemoteIP-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/defaultRemoteIPRef-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/disableAccessLogRemoteIPConfig-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/unknownAndObfuscatedIndetifierRemoteIP-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/test-applications/EndpointInformation/resources/WEB-INF/web.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/test-applications/EndpointInformation/src/com/ibm/ws/transport/http/servlets/EndpointInformationServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#5945 Handled invalid location scenario for featureManager
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/cmdline/ExeInstallAction.java
Labels: CLA Signed

#5930 use in mem derby for around_timeout test
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/publish/servers/com.ibm.ws.ejbcontainer.interceptor.fat.AroundTimeoutServer/server.xml
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#5926 EJB Add debug trace in interceptor method invoke during exception
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/interceptors/InterceptorProxy.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#5967 Update eclipse settings for new springboot multi module application.
  dev/com.ibm.ws.springboot.support.version20.test.war.app/.classpath
  dev/com.ibm.ws.springboot.support.version20.test.war.app/.gitignore
Labels: CLA Signed, noproductcode

#5965 Fix for Issue #5886: Additional cleanup to avoid quiesce errors
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BroadcasterApp/src/io/openliberty/sse/broadcaster/BroadcasterTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BroadcasterApp/src/io/openliberty/sse/broadcaster/ClientListener.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5961 social oidc discovery updates
  dev/com.ibm.ws.security.common/resources/com/ibm/ws/security/common/internal/resources/SSOCommonMessages.nlsprops
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/config/DiscoveryConfigUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, team:Security SSO

#5974 Fix for Issue #5405: Increase Margin for Sun
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5978 Add README for instructions on running the FAT locally
  dev/com.ibm.ws.concurrent.mp_fat_tck/README.md
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#5972 build jwk with kids even if they are created using the key information from the config
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWK.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwkKidBuilder.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtData.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/BuilderTests.java
Labels: CLA Signed, team:Security SSO

#5956 5955 test bulkhead method asynch future done without get slow macs
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#5899 session ignore CWWKG0033W
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: CLA Signed, noproductcode

#5982 Fix for Issue #5981: Verify the JAX-RS 2.1 DoPriv
  dev/com.ibm.ws.javaee.8.0_fat/publish/servers/javaee8.fat/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#4768 Print stack traces for CNFE from parent/follow-on classloaders
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/UnifiedClassLoader.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#5986 Fix issue where timeout.stop() can be called before timeout.start()
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/SyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/package-info.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/TimeoutState.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/DurationUtils.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/RetryStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateNullImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/DurationUtilsTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/RetryStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImplTest.java
Labels: CLA Signed

#5912 Update product and bundle version for release 19.0.0.1
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Continuous Delivery

#5989 Diagnostics for defect 249816 in the JDK
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityGenerateTest.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/defaultServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/defaultServer/jvm.options
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/localAccessServer/jvm.options
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/bootstrap.properties
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/jvm.options
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/servers/remoteAccessServer/server.xml
Labels: CLA Signed, in:JDK Infrastructure, noproductcode, team:Wendigo West

#5975 5536 metricstckfatjava11
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#5984 cleaning up old code
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorFactory.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAuthenticatorFactoryImpl.java
Labels: CLA Signed, release bug

#5962 Add post invoke delay before checking if timer is deleted in fat test
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/NoDBProgrammaticTimerEJB.jar/src/com/ibm/ws/ejbcontainer/timer/nodb/programmatic/ejb/ProgrammaticTimerBean.java
Labels: in:EJB Container, team:Blizzard, test bug

#5988 added trace specification
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsAuthenticationServer/server.xml
Labels: CLA Signed, noproductcode

#5966 Add unsafe method from Oracle 18c Driver
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcProxyMethod.java
Labels: CLA Signed, team:Zombie Apocalypse

#5985 Don't path normalize variables in JDBC/JCA annos
  dev/com.ibm.ws.jca.1.7/src/com/ibm/ws/jca17/processor/service/AdministeredObjectResourceFactoryBuilder.java
  dev/com.ibm.ws.jca.1.7/src/com/ibm/ws/jca17/processor/service/ConnectionFactoryResourceBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
Labels: CLA Signed, team:Zombie Apocalypse

#5998 Revert "Update product and bundle version for release 19.0.0.1"
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Continuous Delivery

#5921 Issue #5919:Fix typo
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/src/com/ibm/ws/el30/fat/servlets/EL30OperatorsServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#5283 Fix JarFile leak in JSF
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/view/facelets/util/Classpath.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/util/Classpath.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#5991 Fix a timing issue in testTrustedForwardedWithMultipleServerConfigura…
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpXForwardedAndForwardedHeaderTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#5973 Cancel lease timer at shutdown
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
Labels: CLA Signed

#6009 Issue 6008: Fix testValidateWholeBeanIllegalAccess test regex to be m…
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ClassLevelBeanValidationTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#6006 keystore/certificate updates
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser2.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser5.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/resources/security/DummyServerTrustFile.jks
Labels: CLA Signed, noproductcode

#6014 Fix for Issue #5405: Increase Margin for Java 11 Hotspot
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6007 testing fat syncing
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#5999 when adding destination wait for delete to finish
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/DestinationManager.java
Labels: CLA Signed

#5625 Longer timeout windows on attributeCache and searchCache
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/VMMAPIs_EmbeddedLdapTests.java
Labels: team:Wendigo East

#5994 Set Default Read Timeout to 1min
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/ReadTimeoutTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/ReadTimeoutTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.readtimeout/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.readtimeout/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
Labels: CLA Signed, team:Wendigo East

#6012 ft_fat smooth over outlier timing glitch
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/TimeoutServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/faulttolerance.jar/src/com/ibm/ws/microprofile/faulttolerance_fat/util/ConnectRuntimeException.java
Labels: CLA Signed, noproductcode

#5980 5979 lengthen arquillian deploy timeout
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#6033 Fix for Issue #6032: Add new JAX-RS tests to test async Timeouts
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/BookStore2.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6023 fixed fat extended timeout
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#5271 Update .classpath and bnd.bnd files to remove nonexistent source paths.
  dev/com.ibm.websphere.org.eclipse.microprofile.opentracing.1.0/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.opentracing.1.1/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.opentracing.1.2/.classpath
  dev/com.ibm.ws.app.manager_fat/.classpath
  dev/com.ibm.ws.app.manager_fat/bnd.bnd
  dev/com.ibm.ws.cdi.beansxml_fat/.classpath
  dev/com.ibm.ws.cdi.beansxml_fat/bnd.bnd
  dev/com.ibm.ws.cdi.jndi_fat/.classpath
  dev/com.ibm.ws.cdi.jndi_fat/bnd.bnd
  dev/com.ibm.ws.cdi.noncontextual_fat/.classpath
  dev/com.ibm.ws.cdi.noncontextual_fat/bnd.bnd
  dev/com.ibm.ws.cdi.visibility_fat/.classpath
  dev/com.ibm.ws.config_fat/.classpath
  dev/com.ibm.ws.javaee.persistence.api.2.1/.classpath
  dev/com.ibm.ws.javaee.persistence.api.2.2/.classpath
  dev/com.ibm.ws.javamail.config/.classpath
  dev/com.ibm.ws.jaxrs.2.0.client_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.config/.classpath
  dev/com.ibm.ws.kernel.boot_test/.classpath
  dev/com.ibm.ws.microprofile.config_fat/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.metrics/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi.ui/.classpath
  dev/com.ibm.ws.microprofile.openapi_fat/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.classpath
  dev/wlp-rasInstrumentation/.classpath
Labels: CLA Signed, noproductcode

#6037 Fix intermittent VirtualHostMapTest failure
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/VirtualHostMapTest.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#6029 6028 correct web container typos
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: CLA Signed, in:Web Components, team:Sirius

#6018 TokenLoginModule support hashtable userId only return from handleJwtSSO service
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/jaas/modules/ServerCommonLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/HashtableLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModule.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_mpJwt_mapToUserRegistry_true.xml
Labels: CLA Signed

#6048 Added testZeroLengthPadding to the trace bucket
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#6027 Ignore config elements that are beta if generating from a GA release
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
Labels: CLA Signed

#5901 remove unused attributes from threading metatype
  dev/com.ibm.ws.threading/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.threading/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
Labels: CLA Signed

#6030 Dump and restore output streams between unit tests
  dev/com.ibm.ws.junit.extensions/src/test/common/SharedOutputManager.java
Labels: CLA Signed, team:Continuous Delivery

#6066 Enable TCK test when running locally
  dev/com.ibm.ws.concurrent.mp_fat_tck/README.md
  dev/com.ibm.ws.concurrent.mp_fat_tck/fat/src/com/ibm/ws/concurrent/mp/fat/tck/MPConcurrencyTCKLauncher.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6062 Revert "Fix for Issue #6032: Add new JAX-RS tests to test async Timeouts"
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/BookStore2.java
Labels: CLA Signed, noproductcode

#6055 Use different trace method for SearchPagingTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/SearchPagingTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#6031 Publish version props to repository
  dev/cnf/build.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#6074 Ignore NPE and default version to null
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/DataModelSerializer.java
Labels: CLA Signed, team:Continuous Delivery

#6039 update libertyBetaVersion per beta driver build process
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Zombie Apocalypse

#6043 MP Concurrency impl should use translated messages
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/context/package-info.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/package-info.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#6056 cleared context improperly cloned
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/MicroProfileClearedContextSnapshot.java
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/bootstrap.properties
Labels: CLA Signed, team:Zombie Apocalypse

#6077 Rename file to match class name
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/metadata/internal/MethodMetaDataManager.java
Labels: CLA Signed, team:Zombie Apocalypse

#6016 Sync changes in fattest.simplicity
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigActuatorXMLOverrideTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigServerXMLOverrideTests20.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/JMSActivationSpec.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/JMSQueue.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MongoElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/OpenAPIElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/OutboundConnection.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ProductInsightsElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SSL.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SSLConfig.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SSLDefault.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
  dev/fattest.simplicity/src/componenttest/common/apiservices/cmdline/LocalProvider.java
  dev/fattest.simplicity/src/componenttest/common/apiservices/cmdline/StreamGobbler.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/LogPolice.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/TestNameFilter.java
  dev/fattest.simplicity/src/componenttest/depchain/FeatureDependencyProcessor.java
  dev/fattest.simplicity/src/componenttest/topology/database/CloudantDatabase.java
  dev/fattest.simplicity/src/componenttest/topology/database/OracleDatabase.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LogMonitor.java
  dev/fattest.simplicity/src/componenttest/topology/impl/PortDetectionUtil.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FATServletClient.java
  dev/fattest.simplicity/src/componenttest/topology/utils/HttpUtils.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6082 Allow for FFDC from intentional exception raised by test
  dev/com.ibm.ws.concurrent.mp_fat_tck/fat/src/com/ibm/ws/concurrent/mp/fat/tck/MPConcurrencyTCKLauncher.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6084 Fix for Issue #6032: Add new JAX-RS tests to test async Timeouts
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/BookStore2.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6021 Run tests on separate servers to prevent test failure
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/ConsoleFormatTest.java
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ConsoleFormatServer2/bootstrap.properties
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ConsoleFormatServer2/server.xml
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ConsoleFormatServer3/bootstrap.properties
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ConsoleFormatServer3/server.xml
Labels: CLA Signed, noproductcode

#6091 Revert "Dump and restore output streams between unit tests"
  dev/com.ibm.ws.junit.extensions/src/test/common/SharedOutputManager.java
Labels: CLA Signed, team:Continuous Delivery

#6080 Update product and bundle versions for 19.0.0.1
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Continuous Delivery
