Repository OpenLiberty/open-liberty, pull requests merged in 2018-08, with the labels that each got.

#4367 Use exact version 0.30.0
  dev/com.ibm.ws.io.opentracing.opentracing-api/bnd.bnd
  dev/com.ibm.ws.opentracing/bnd.bnd
  dev/com.ibm.ws.opentracing_fat/opentracing.mock.bnd
Labels: CLA Signed, in:MicroProfile/OpenTracing, team:Lumberjack

#4307 add server restart
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
Labels: CLA Signed, noproductcode

#4405 Add initial support for getting a connection using Driver
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/ConnectionResults.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4390 update jwk common code to support adding basic auth header to the jwk retrieve request
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
Labels: CLA Signed, team:Security SSO

#4412 Feature name cleanup
  dev/com.ibm.websphere.appserver.features/visibility/public/appClientSupport-1.0/com.ibm.websphere.appserver.appClientSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/bells-1.0/com.ibm.websphere.appserver.bells-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedMap-1.0/com.ibm.websphere.appserver.distributedMap-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/federatedRegistry-1.0/com.ibm.websphere.appserver.federatedRegistry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-7.0/com.ibm.websphere.appserver.javaeeClient-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-8.0/com.ibm.websphere.appserver.javaeeClient-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jcaInboundSecurity-1.0/com.ibm.websphere.appserver.jcaInboundSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jndi-1.0/com.ibm.websphere.appserver.jndi-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/json-1.0/com.ibm.websphere.appserver.json-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/com.ibm.websphere.appserver.jwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ldapRegistry-3.0/com.ibm.websphere.appserver.ldapRegistry-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/localConnector-1.0/com.ibm.websphere.appserver.localConnector-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.0/com.ibm.websphere.appserver.microProfile-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.2/com.ibm.websphere.appserver.microProfile-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.2/resources/l10n/com.ibm.websphere.appserver.microProfile-1.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.3/com.ibm.websphere.appserver.microProfile-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.3/resources/l10n/com.ibm.websphere.appserver.microProfile-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/monitor-1.0/com.ibm.websphere.appserver.monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.1/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.2/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.3/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.0/resources/l10n/com.ibm.websphere.appserver.mpFaultTolerance-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/resources/l10n/com.ibm.websphere.appserver.mpFaultTolerance-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/resources/l10n/com.ibm.websphere.appserver.mpHealth-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.0/com.ibm.websphere.appserver.mpJwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.0/resources/l10n/com.ibm.websphere.appserver.mpJwt-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.0/resources/l10n/com.ibm.websphere.appserver.mpMetrics-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/resources/l10n/com.ibm.websphere.appserver.mpMetrics-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/resources/l10n/com.ibm.websphere.appserver.mpOpenAPI-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/osgiConsole-1.0/com.ibm.websphere.appserver.osgiConsole-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.0/com.ibm.websphere.appserver.passwordUtilities-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-1.0/com.ibm.websphere.appserver.persistentExecutor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionDatabase-1.0/com.ibm.websphere.appserver.sessionDatabase-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/transportSecurity-1.0/com.ibm.websphere.appserver.transportSecurity-1.0.feature
Labels: CLA Signed, ID reviewed

#4415 avoid modifications to vendor properties so as to allow subsequent connections via Driver
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4421 Issue4409-RemoveOpenSourceScansOfFATs
  dev/build.example_fat/build.gradle
  dev/com.ibm.ws.beanvalidation.v11_fat/build.gradle
  dev/com.ibm.ws.cdi.2.0_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_demo/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_locking/build.gradle
  dev/com.ibm.ws.concurrent_fat/build.gradle
  dev/com.ibm.ws.concurrent_fat_config/build.gradle
  dev/com.ibm.ws.concurrent_fat_demo/build.gradle
  dev/com.ibm.ws.concurrent_fat_ejb/build.gradle
  dev/com.ibm.ws.concurrent_fat_policy/build.gradle
  dev/com.ibm.ws.config_fat/build.gradle
  dev/com.ibm.ws.context_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/build.gradle
  dev/com.ibm.ws.jbatch.cdi_fat/build.gradle
  dev/com.ibm.ws.jca_fat_derbyra/build.gradle
  dev/com.ibm.ws.jca_fat_example_anno/build.gradle
  dev/com.ibm.ws.jdbc_fat_driver/build.gradle
  dev/com.ibm.ws.jdbc_fat_loadfromapp/build.gradle
  dev/com.ibm.ws.jdbc_fat_v41/build.gradle
  dev/com.ibm.ws.jmx_fat/build.gradle
  dev/com.ibm.ws.jpa_22_fat/build.gradle
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.jsonp.1.1_fat/build.gradle
  dev/com.ibm.ws.jsonp_fat/build.gradle
  dev/com.ibm.ws.kernel.boot_fat/build.gradle
  dev/com.ibm.ws.kernel.feature_fat/build.gradle
  dev/com.ibm.ws.kernel.filemonitor_fat/build.gradle
  dev/com.ibm.ws.kernel.metatype.helper_fat/build.gradle
  dev/com.ibm.ws.logging.hpel_fat/build.gradle
  dev/com.ibm.ws.logging_fat/build.gradle
  dev/com.ibm.ws.microprofile.config_fat/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/build.gradle
  dev/com.ibm.ws.microprofile.health_fat/build.gradle
  dev/com.ibm.ws.opentracing_fat/build.gradle
  dev/com.ibm.ws.product.utility_fat/build.gradle
  dev/com.ibm.ws.runtime.update_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt_fat_tck/build.gradle
  dev/com.ibm.ws.security.utility_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.file_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.registry_fat/build.gradle
  dev/com.ibm.ws.threading_fat/build.gradle
  dev/com.ibm.ws.threading_policy_fat/build.gradle
  dev/wlp.lib.extract_fat/build.gradle
Labels: CLA Signed, noproductcode

#4422 Format spacing when traceFileName is stdout ( for BASIC, ADVANCED, and ENHANCED format)
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
Labels: CLA Signed

#4420 Modify the collectorjsonutils to accomodate the new threadid key value…
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
Labels: CLA Signed

#4431 Update build-text.xml for com.ibm.ws.kernel.feature_fat
  dev/com.ibm.ws.kernel.feature_fat/build-test.xml
Labels: CLA Needed, CLA Signed, noproductcode

#4433 Issue #4432 - don't use fatTestPorts.xml in client tests
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClient/client.xml
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClientAdvanced/client.xml
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClientSecurity/client.xml
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/servers/cdi12EmptyServer/server.xml
Labels: CLA Signed, noproductcode

#4448 Issue #4447 - Ensure WAB bundles are always unconfigured
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
Labels: CLA Signed

#4435 infer data source class for DataSourceDefinition
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4407 Remove dependency on internal JAX-B from wimcore-1.0
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wimcore-1.0.feature
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/.classpath
  dev/com.ibm.ws.jaxb_fat/.project
  dev/com.ibm.ws.jaxb_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxb_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxb_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxb_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxb_fat/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/build.gradle
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/FATSuite.java
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/ThirdPartyJAXBTest.java
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat.no-jaxb-feature/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat.no-jaxb-feature/server.xml
  dev/com.ibm.ws.jaxb_fat/test-applications/jaxbApp/src/jaxb/web/ObjectFactory.java
  dev/com.ibm.ws.jaxb_fat/test-applications/jaxbApp/src/jaxb/web/ThirdPartyJAXBTestServlet.java
Labels: CLA Signed, in:Java EE Platform, in:Security, team:Zombie Apocalypse

#4434 Revert StringBuilder changes for JSF Writer implementations.
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/shared/renderkit/html/HtmlResponseWriterImpl.java
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/util/CDataEndEscapeFilterWriter.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/HtmlResponseWriterImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/util/CDataEndEscapeFilterWriter.java
Labels: CLA Signed

#4452 Issue4439 audit for cloud sequence consistency
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
Labels: CLA Signed

#4454 Issue4409-AddBackMissingBuildGradle
  dev/com.ibm.ws.concurrent_fat_demo/build.gradle
Labels: CLA Signed, noproductcode

#4461 Issue 4373: Allow `@Inject` on JAX-RS resource constructors
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/ResourceUtils.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.project
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/AtInjectTest.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinject/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinject/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinject/server.xml
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AbstractInjectedObject.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AtInjectApp.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AtInjectDirectService.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AtInjectOnManagedObjectService.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AtInjectTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/ConstructorInjectedObject.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/FieldInjectedObject.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/MethodInjectedObject.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/MyManagedObject.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4466 Issue #4465: Fix EJB Timer Create Timing Issue
  dev/com.ibm.ws.ejbcontainer.timer.persistent/src/com/ibm/ws/ejbcontainer/timer/persistent/osgi/internal/PersistentTimerTaskHandlerImpl.java
Labels: CLA Signed

#4481 Update eclipse files for new component.
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#4483 Upgrade from ASM 6.1.1 to 6.2.1 for JDK 11 support
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#4491 Add derby-only bucket
  dev/com.ibm.ws.jdbc_fat_derby/.classpath
  dev/com.ibm.ws.jdbc_fat_derby/.project
  dev/com.ibm.ws.jdbc_fat_derby/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat_derby/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_derby/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_derby/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_derby/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_derby/build.gradle
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/JDBCDerbyTest.java
  dev/com.ibm.ws.jdbc_fat_derby/publish/servers/com.ibm.ws.jdbc.fat.derby/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_derby/publish/servers/com.ibm.ws.jdbc.fat.derby/server.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/src/jdbc/fat/derby/web/JDBCDerbyServlet.java
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/trandriver/src/jdbc/tran/none/driver/TranNoneConnection.java
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/trandriver/src/jdbc/tran/none/driver/TranNoneDataSource.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4446 Add required-osgi-ee bundle attribute to feature resolver
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wimcore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleList.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureResourceImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/FeatureResource.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRequirement.java
Labels: CLA Signed, team:Zombie Apocalypse

#4437 Update FeatureReplacementAction so ALL_SERVERS works at the test class level with injected servers
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AfterTypeDiscoveryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanDiscoveryModeNoneTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ClassExclusionTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CustomerProvidedXMLParserFactoryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/DisablingBeansXmlValidationTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EmptyCDITest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/MultipleBeansXmlTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/WebBeansBeansXmlInWeldTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EJB32Test.java
  dev/com.ibm.ws.cdi.extension_fat/hello_world_extension.bnd
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.helloworld.extension.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi12.internals-1.0.mf
  dev/com.ibm.ws.clientcontainer.cdi_fat/.classpath
  dev/com.ibm.ws.clientcontainer.cdi_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.clientcontainer.cdi_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.clientcontainer.cdi_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientAdvancedTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientSecurityTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/ClientOnly.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#4314 Tests for Batch array deserialize
  dev/com.ibm.ws.jbatch.misc_fat/.classpath
  dev/com.ibm.ws.jbatch.misc_fat/.project
  dev/com.ibm.ws.jbatch.misc_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jbatch.misc_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.misc_fat/build.gradle
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/ArrayDeserializeTest.java
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/.gitignore
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/bootstrap.properties
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/server.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayCheckpointDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayUserDataDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/index.jsp
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayCheckpointReader.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayDeserializeServlet.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionAnalyzer.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionCollector.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/NoOpItemWriter.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ReaderData.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/SimplePartitionMapper.java
  dev/com.ibm.ws.jbatch.misc_fat/util/src/fat/util/JobWaiter.java
Labels: CLA Signed, noproductcode

#3957 Issue #2416 moving computation for sequence and message id
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/LogTraceData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/SequenceNumber.java
Labels: CLA Signed

#4500 Add missing javaPermissions for jdbc_fat_v41
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41/server.xml
Labels: CLA Signed, in:JDBC/JCA, noproductcode, team:Zombie Apocalypse, test bug

#4498 Add recovery tests
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/RecoveryTest.java
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/RecoveryServlet.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/AbortableXAResourceImpl.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceFactoryImpl.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceFactoryService.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceInfoFactory.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceInfoImpl.java
Labels: CLA Signed, noproductcode, team:MicroProfileUK

#4503 Issue4502-ConsistentISO8601DateTimeFormat
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
Labels: CLA Signed

#4486 i4310-SpringBoot_app_fails_with_Json_CastExc_on_startup
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootModuleInfo.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBContainerImpl.java
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests20.java
  dev/com.ibm.ws.springboot.support_fat/publish/servers/com.ibm.ws.springboot.support.fat.SpringBootTests/server.xml
Labels: CLA Signed, in:SpringBoot, team:OSGi Infrastructure

#4511 null check before adding to ringBuffer
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
Labels: CLA Signed

#4516 Add provided scope to BOM
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
Labels: CLA Signed

#4524 Revert "Tests for Batch array deserialize"
  dev/com.ibm.ws.jbatch.misc_fat/.classpath
  dev/com.ibm.ws.jbatch.misc_fat/.project
  dev/com.ibm.ws.jbatch.misc_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jbatch.misc_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.misc_fat/build.gradle
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/ArrayDeserializeTest.java
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/.gitignore
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/bootstrap.properties
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/server.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayCheckpointDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayUserDataDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/index.jsp
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayCheckpointReader.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayDeserializeServlet.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionAnalyzer.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionCollector.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/NoOpItemWriter.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ReaderData.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/SimplePartitionMapper.java
  dev/com.ibm.ws.jbatch.misc_fat/util/src/fat/util/JobWaiter.java
Labels: CLA Signed, noproductcode

#4512 explicitly configure to use driver class
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, ID review not needed, team:Zombie Apocalypse

#4265 Allow extra messages in InfoStoreTest
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/cases/InfoStoreTest.java
Labels: CLA Signed, noproductcode

#4484 JDBC DataSource allows for IsolationLevel = TRAN_NONE
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/ResourceEnvRefInfo.java
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/AdapterUtil.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/JDBCDerbyTest.java
  dev/com.ibm.ws.jdbc_fat_derby/publish/servers/com.ibm.ws.jdbc.fat.derby/server.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/src/jdbc/fat/derby/web/JDBCDerbyServlet.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#4532 tests for driver not accessible to application classloader
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/proxy/driver/Handler.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/proxy/driver/ProxyDrivr.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/proxy/driver/ProxyPoolDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4501 Issue #4459: Fix quotation issue for GCData values
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
Labels: CLA Signed

#4506 More support for Driver
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#4520 4279 auto feature monitor to mp metrics
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics-monitor-1.0.feature
  dev/com.ibm.ws.microprofile.metrics.monitor/.classpath
  dev/com.ibm.ws.microprofile.metrics.monitor/.project
  dev/com.ibm.ws.microprofile.metrics.monitor/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorCounter.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorGauge.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetrics.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetricsHandler.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/package-info.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.classpath
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.project
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/build.gradle
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_microProfile13Monitor10.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitor.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter1.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter2.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter3.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorFilter4.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_monitorOnly.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_mpMetric10Monitor10.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_mpMetric11.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_noJDBC.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/MetricsMonitorServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/MetricsMonitorServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/MetricsMonitorServer/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/MetricsMonitorServer/serverJDBCConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/test-applications/testJDBCApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/test-applications/testJDBCApp/src/com/ibm/ws/microprofile/metrics/monitor_fat/jdbc/servlet/TestJDBCServlet.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/test-applications/testSessionApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/test-applications/testSessionApp/src/com/ibm/ws/microprofile/metrics/monitor_fat/session/servlet/TestSessionServlet.java
  dev/com.ibm.ws.microprofile.metrics/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
Labels: CLA Signed, ID reviewed

#4549 suppress error message when scheduled task cannot start due to server shutdown
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
Labels: CLA Signed, team:Zombie Apocalypse

#4558 mpJwt issuer is no longer required in server.xml
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#4561 Add new test to ensure response thread is from the specified ExecSvc
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/test-applications/jaxrsapp/src/web/jaxrstest/JAXRSExecutorTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#4557 Message Updates from serviceability review
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#4572 Update eclipse files for new components.
  dev/com.ibm.ws.microprofile.metrics.monitor/.project
  dev/com.ibm.ws.microprofile.metrics.monitor/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.project
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1.config/.classpath
  dev/com.ibm.ws.security.mp.jwt.1.1/.classpath
Labels: CLA Signed, noproductcode

#4496 EJB NPTimer scheduleNext after timer hits max retries
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/TimerNpRunnable.java
Labels: CLA Signed

#4559 test coverage for data source backed by java.sql.Driver in loadfromapp bucket
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDrivers.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/jdbc-drivers/mini/src/jdbc/driver/mini/MiniConnection.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/jdbc-drivers/mini/src/jdbc/driver/mini/jse/DriverImpl.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromAppServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4495 add + or - to api types for easier usage
  dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/classloader.properties
  dev/com.ibm.ws.classloading/resources/com/ibm/ws/classloading/internal/resources/ClassLoadingServiceMessages.nlsprops
  dev/com.ibm.ws.classloading/src/com/ibm/wsspi/classloading/ApiType.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/ApiTypeTest.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#4569 Mark getNumberOfRepositoriesVolatile as trivial
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
Labels: CLA Signed, team:Wendigo East

#4327 Updates to support URBridge audit testing
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/util/AuditConstants.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/util/package-info.java
Labels: CLA Signed, team:Wendigo East

#4582 remove nonship guards for datasource backed by driver feature
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#4467 Audit:JSR375:update audit entries
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/ProgrammaticTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/Constants.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/BasicAuthAuthenticator.java
Labels: CLA Signed, in:Security, team:Core Security

#4591 Update new MP components eclipse settings
  dev/com.ibm.ws.microprofile.metrics.1.0/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.private/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.private/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.public/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.public/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#4487 i4057-CreateServerTemplatesForSpringBoot-1-2
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot1/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot2/server.xml
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/TemplateTests.java
Labels: CLA Signed, in:SpringBoot, team:OSGi Infrastructure

#4553 add updates to jsonwebkey and jwt projects and see if it all still works
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
Labels: CLA Signed

#4523 Initial commit for flushCloseDown SSL Channel improvement
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
Labels: CLA Signed, release bug

#4570 Refactor features to avoid MP Rest API features depending on impls
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.1.feature
Labels: in:JAX-RS, in:MicroProfile, team:Wendigo West

#4551 Inject at startup issue
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuiteCDI12WithJava7.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/ResourceInfoAtStartupTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.resourceInfoAtStartup/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.resourceInfoAtStartup/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.resourceInfoAtStartup/server.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/App.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/ClientResource.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/Filter1.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/InjectableObject.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/Resource1.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/resourceInfoAtStartup/src/io/openliberty/resourceInfoAtStartup/test/StartupSingletonBean.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/InjectionRuntimeContextHelper.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/ProviderInfo.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/InjectionUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/InjectionRuntimeContextHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/model/ProviderInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/InjectionUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4614 Revert "PR for #4406 - Add ability to enable/disable authentication for the MicroProfile Metrics endpoint"
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.0/com.ibm.websphere.appserver.mpMetrics-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.ws.microprofile.metrics.1.0/.classpath
  dev/com.ibm.ws.microprofile.metrics.1.0/.project
  dev/com.ibm.ws.microprofile.metrics.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.0/resources/META-INF/NOTICE
  dev/com.ibm.ws.microprofile.metrics.1.0/src/com/ibm/ws/microprofile/metrics10/impl/SharedMetricRegistries10.java
  dev/com.ibm.ws.microprofile.metrics.1.0/src/com/ibm/ws/microprofile/metrics10/impl/package-info.java
  dev/com.ibm.ws.microprofile.metrics.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.metrics.private/.classpath
  dev/com.ibm.ws.microprofile.metrics.private/.project
  dev/com.ibm.ws.microprofile.metrics.private/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.private/build.gradle
  dev/com.ibm.ws.microprofile.metrics.private/findbugs.exclude.xml
  dev/com.ibm.ws.microprofile.metrics.private/src/com/ibm/ws/microprofile/metrics/privateapi/PrivateMetricsRESTHandler.java
  dev/com.ibm.ws.microprofile.metrics.private/src/com/ibm/ws/microprofile/metrics/privateapi/PrivateMetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics.private/src/com/ibm/ws/microprofile/metrics/privateapi/package-info.java
  dev/com.ibm.ws.microprofile.metrics.public/.classpath
  dev/com.ibm.ws.microprofile.metrics.public/.project
  dev/com.ibm.ws.microprofile.metrics.public/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.public/build.gradle
  dev/com.ibm.ws.microprofile.metrics.public/findbugs.exclude.xml
  dev/com.ibm.ws.microprofile.metrics.public/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.metrics.public/resources/com/ibm/ws/microprofile/metrics/publicapi/resources/ibm-web-ext.xml
  dev/com.ibm.ws.microprofile.metrics.public/src/com/ibm/ws/microprofile/metrics/publicapi/PublicMetricsRESTHandler.java
  dev/com.ibm.ws.microprofile.metrics.public/src/com/ibm/ws/microprofile/metrics/publicapi/PublicMetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics.public/src/com/ibm/ws/microprofile/metrics/publicapi/package-info.java
  dev/com.ibm.ws.microprofile.metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.microprofile.metrics/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.metrics/resources/com/ibm/ws/microprofile/metrics/resources/ibm-web-ext.xml
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/MetricsConfig.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/MetricsHandler.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/MetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/helper/PrometheusBuilder.java
Labels: CLA Signed, ID review not needed

#4597 address TODO comments around message parameters
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
Labels: CLA Signed, team:Zombie Apocalypse

#4601 Issue 4600: Remove inconsistent tests from ScanningCoreServiceImplTests
  dev/com.ibm.ws.kernel.filemonitor/test/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImplTestParent.java
Labels: CLA Signed, noproductcode

#4599 mpJwt11: update runtime code for the e2e scenario and add ut code.
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpJwtConfigProxy-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.1/com.ibm.websphere.appserver.mpJwt-1.1.feature
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.mp.jwt.1.1.config/.classpath
  dev/com.ibm.ws.security.mp.jwt.1.1.config/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.1.1.config/src/com/ibm/ws/security/mp/jwt/v11/config/impl/MpConfigProxyServiceImpl.java
  dev/com.ibm.ws.security.mp.jwt.1.1.config/test/com/ibm/ws/security/mp/jwt/v11/config/impl/MpConfigProxyServiceImplTest.java
  dev/com.ibm.ws.security.mp.jwt.1.1/.classpath
  dev/com.ibm.ws.security.mp.jwt.1.1/.project
  dev/com.ibm.ws.security.mp.jwt.1.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.1.1/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1/build.xml
  dev/com.ibm.ws.security.mp.jwt.1.1/findbugs.exclude.xml
  dev/com.ibm.ws.security.mp.jwt.1.1/resources/com/ibm/ws/security/mp/jwt/v11/resources/MpJwtMessages.nlsprops
  dev/com.ibm.ws.security.mp.jwt.1.1/src/com/ibm/ws/security/mp/jwt/v11/MpConfigProxyService.java
  dev/com.ibm.ws.security.mp.jwt.1.1/src/com/ibm/ws/security/mp/jwt/v11/TraceConstants.java
  dev/com.ibm.ws.security.mp.jwt.1.1/src/com/ibm/ws/security/mp/jwt/v11/impl/MpJwtExtensionServiceImpl.java
  dev/com.ibm.ws.security.mp.jwt.1.1/src/com/ibm/ws/security/mp/jwt/v11/impl/package-info.java
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MpConfigProxyService.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MpJwtExtensionService.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/test/com/ibm/ws/security/mp/jwt/config/MpConfigUtilTest.java
Labels: CLA Signed

#4592 Update arquillian container to 1.0.2
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing.1.1_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#4612 Adding feature translation files for OpenTracing.1.1
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/resources/l10n/com.ibm.websphere.appserver.opentracing-1.1_zh_TW.properties
Labels: CLA Signed, ID review not needed

#4589 Add MicroProfile 1.4 & 2.0 features
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/com.ibm.websphere.appserver.microProfile-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/resources/l10n/com.ibm.websphere.appserver.microProfile-1.4_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/com.ibm.websphere.appserver.microProfile-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/resources/l10n/com.ibm.websphere.appserver.microProfile-2.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.3/com.ibm.websphere.appserver.mpConfig-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.1/com.ibm.websphere.appserver.mpJwt-1.1.feature
Labels: CLA Signed, ID review not needed, ID reviewed

#4628 Allow base features to install in IBM Cloud
  dev/com.ibm.websphere.appserver.features/build.gradle
Labels: CLA Signed, noproductcode

#4546 Issue 4480: Allow user to specify root folder in package command
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommand.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessorUtils.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerHelpActions.java
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/server.xml
Labels: CLA Signed, ID reviewed

#4626 3917 Additional transaction none testing
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_derby/fat/src/com/ibm/ws/jdbc/fat/derby/JDBCDerbyTest.java
  dev/com.ibm.ws.jdbc_fat_derby/publish/servers/com.ibm.ws.jdbc.fat.derby/server.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/jdbcapp/src/jdbc/fat/derby/web/JDBCDerbyServlet.java
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/trandriver/src/jdbc/tran/none/driver/TranNoneConnection.java
  dev/com.ibm.ws.jdbc_fat_derby/test-applications/trandriver/src/jdbc/tran/none/driver/TranNoneDataSource.java
Labels: CLA Signed, team:Zombie Apocalypse

#4620 4619-PersonAccount's and Group's get(String), isSet(String), and unset(String) methods may throw NullPointerExceptions
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/Group.java
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/wsspi/security/wim/model/PersonAccount.java
  dev/com.ibm.ws.org.apache.directory.server/src/com/ibm/ws/apacheds/EmbeddedApacheDS.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
Labels: CLA Signed, team:Wendigo East

#4625 added scm, url, developer and name/descriptions to generatePOM methods
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Constants.java
Labels: CLA Signed

#4556 4455 product utility refactor
  dev/com.ibm.ws.product.utility/bnd.bnd
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/IFixUtils.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Applicability.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/BundleFile.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Bundles.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/FeatureManifestFile.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/FeatureManifests.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/IFixInfo.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Information.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/LibertyProfileMetadataFile.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Offering.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Problem.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Property.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Resolves.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/UpdatedFile.java
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/ifix/xml/Updates.java
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/IfixParser.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/RestClient.java
Labels: CLA Signed, team:Zombie Apocalypse

#4411 add null checks when adding to jeeComponentClass
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
Labels: CLA Signed

#4651 Update eclipse / bnd settings for new components.
  dev/com.ibm.websphere.javaee.activation.1.1/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.openidconnect.clients.common/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed

#4634 add socialLogin-1.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/com.ibm.websphere.appserver.socialLogin-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/resources/l10n/com.ibm.websphere.appserver.socialLogin-1.0_zh_TW.properties
Labels: CLA Signed

#4639 Update mpjwt runtime to handle default config
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
Labels: CLA Signed, team:Security SSO

#4618 Fix recorded bulkhead queue times
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/ExecutionContextImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/async/AsyncOuterExecutorImpl.java
Labels: CLA Signed

#4652 For issue #4504: mpMetrics FAT test cases for authetication config
  dev/com.ibm.ws.microprofile.metrics_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/fat/utils/MetricsAuthTestUtil.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/fat/utils/MetricsConnection.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsAuthenticationTest.java
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsAuthenticationServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsAuthenticationServer/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MPMetricsElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: CLA Signed, noproductcode

#4621 Set JCache related features to kind=noship
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi2.0-jcache1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
Labels: CLA Signed, team:Zombie Apocalypse

#4638 Run Fault Tolerance tests against 1.1
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/CDIFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/FTFallback/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/FaultToleranceMultiModule/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/TxFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/TxFaultToleranceReordered/server.xml
Labels: CLA Signed, noproductcode

#4627 Install Kernel exception fix for matching Feature shortnames
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Needed, CLA Signed

#4655 Update exception classes to pass cause by exception to super()
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/PasswordExpiredException.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/UserRevokedException.java
Labels: CLA Signed

#4649 Only skip dependency check if the subsystem entry is another feature
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/adaptor/ESAAdaptor.java
Labels: CLA Signed

#4653 4554 mp jwt config public key
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKSetTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/PemKeyUtilTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/rsa_key.pem
Labels: CLA Signed

#4335 Use managed executor service if concurrency is enabled
  dev/com.ibm.ws.cdi.weld/bnd.bnd
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIDeferredMetaDataFactoryImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/JndiHelperComponentMetaData.java
Labels: CLA Signed

#4199 Save security context for batch sync to OS thread
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/ContextBasedThreadPoolServiceImpl.java
Labels: CLA Signed

#4630 This updates Xalan from 2.7.0 to 2.7.2 to satisfy CVE-2014-0107.
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jsp/bnd.bnd
Labels: CLA Signed

#4678 Temporarily comment out a couple JWK-related unit tests
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/OidcLoginConfigImplTest.java
Labels: CLA Signed, noproductcode, team:Security SSO

#4664 Add com.ibm.websphere.appserver.api.social
  dev/com.ibm.websphere.appserver.api.social/.classpath
  dev/com.ibm.websphere.appserver.api.social/.gitignore
  dev/com.ibm.websphere.appserver.api.social/.project
  dev/com.ibm.websphere.appserver.api.social/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.api.social/bnd.bnd
  dev/com.ibm.websphere.appserver.api.social/build.gradle
  dev/com.ibm.websphere.appserver.api.social/com.ibm.websphere.appserver.api.social.pom
Labels: CLA Signed, team:Security SSO

#4608 Filter URL for tracing when using Driver
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/PropertyService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcTracer.java
  dev/com.ibm.ws.jdbc/test/com/ibm/ws/jdbc/internal/InternalTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#4689 Revert "4554 mp jwt config public key"
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKSetTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/PemKeyUtilTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/rsa_key.pem
Labels: CLA Signed

#4677 Update tests to use +third-party
  dev/com.ibm.ws.cdi.third.party_fat/publish/servers/cdi12DeltaSpikeServer/server.xml
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/mailSessionTestServer/server.xml
  dev/com.ibm.ws.opentracing_fat/publish/servers/opentracingFATServer3/server.xml
Labels: CLA Signed, noproductcode

#4694 Update security.social eclipse and bnd settings.
  dev/com.ibm.ws.security.social/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.social/bnd.bnd
Labels: CLA Signed

#4673 Disable JPA ORM Analyzer for 18.0.0.3 (#4605)
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/JPAORMDiagnostics.java
Labels: CLA Signed, in:JPA, priority/medium, target:3Q18, team:Blizzard

#4701 Revert "Update security.social eclipse and bnd settings."
  dev/com.ibm.ws.security.social/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.social/bnd.bnd
Labels: CLA Signed

#4629 Batch deserialize test
  dev/com.ibm.ws.jbatch.misc_fat/.classpath
  dev/com.ibm.ws.jbatch.misc_fat/.project
  dev/com.ibm.ws.jbatch.misc_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jbatch.misc_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jbatch.misc_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.misc_fat/build.gradle
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/ArrayDeserializeTest.java
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/.gitignore
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/bootstrap.properties
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/server.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayCheckpointDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayUserDataDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/index.jsp
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayCheckpointReader.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayDeserializeServlet.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionAnalyzer.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/DeserializePartitionCollector.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/NoOpItemWriter.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ReaderData.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/SimplePartitionMapper.java
  dev/com.ibm.ws.jbatch.misc_fat/util/src/fat/util/JobWaiter.java
Labels: CLA Signed, noproductcode

#4695 Add javax.annotation to testpath of security.mp.jwt
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#4693 Revert "Revert "4554 mp jwt config public key""
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKSetTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/PemKeyUtilTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/rsa_key.pem
Labels: CLA Signed

#4708 Redo PR #4694.
  dev/com.ibm.ws.security.social/.classpath
  dev/com.ibm.ws.security.social/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/AuthorizationCodeAuthenticatorTest.java
Labels: CLA Signed

#4702 Issue #4692 : add default mpjwt config if mpconfig for jwt exists
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
Labels: CLA Signed, team:Security SSO

#4707 Fix NPE in ConsumerUtil.validateClaims()
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
Labels: CLA Signed, team:Security SSO

#4696 Add option to ignore unittest failures
  dev/cnf/gradle/scripts/tasks.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4642 Add switching of virtual host for MP features
  dev/com.ibm.ws.app.manager.wab/bnd.bnd
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WAB.java
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABGroup.java
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
  dev/com.ibm.ws.jmx.connector.server.rest/bnd.bnd
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.private/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.public/bnd.bnd
  dev/com.ibm.ws.rest.handler/bnd.bnd
Labels: CLA Signed

#4710 Ensure mpRestClient-1.1 works with EE7/MP1.4 and EE8/MP2.0
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/AbstractClient.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiInEE8Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagationTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/MultiClientCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.async/server.xml
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/AbstractClient.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#4713 fix mp-jwt spec violation
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/DefaultJsonWebTokenImpl.java
Labels: CLA Signed

#4690 4661 princ bean
  dev/com.ibm.ws.security.mp.jwt.cdi/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/JsonWebTokenBean.java
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/JwtCDIExtension.java
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/principal/PrincipalBean.java
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/principal/package-info.java
Labels: CLA Signed

#4631 Shutdown improvements
  dev/com.ibm.ws.channelfw/src/com/ibm/websphere/channelfw/ChannelUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/channelfw/internal/UtilsChainListener.java
  dev/com.ibm.ws.concurrency.policy/bnd.bnd
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/MonitorHolder.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/scan/ScanningCoreServiceImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
  dev/com.ibm.ws.runtime.update/bnd.bnd
  dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/PauseableComponentQuiesceListener.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutorProvider.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ThreadQuiesce.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/bnd.bnd
Labels: CLA Signed, ID reviewed

#4588 Issue 4587: Update EclipseLink from 2.7.1 to 2.7.3 for JPA 2.2
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/BeanValidationExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/EclipseLinkLocalizationResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/ToStringLocalizationResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Labels: CLA Signed, ID reviewed, in:JPA, team:Blizzard

#4718 Issue #4717: update Yoko to favour CSI endpoints
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#4676 Remove com.google.guava dependency in socialLogin-1.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/com.ibm.websphere.appserver.socialLogin-1.0.feature
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/JsonTokenUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/token/JsonTokenUtilTest.java
Labels: CLA Signed, team:Security SSO

#4679 Update components to depend on internal copy of JAXB and CORBA
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.corba-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.managedBeansCore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.springBootHandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-1.0/com.ibm.websphere.appserver.batch-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-1.2/com.ibm.websphere.appserver.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-1.1/com.ibm.websphere.appserver.jaspic-1.1.feature
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/AutomaticTimerBean.java
  dev/com.ibm.ws.ejbcontainer/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#4547 PII 3Q18 Returns from Shipment 3
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_cs.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_de.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_es.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_fr.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_hu.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_it.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ja.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ko.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_pl.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_pt_BR.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ro.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ru.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_zh.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_zh_TW.nlsprops
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages_fr.nlsprops
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages_pl.nlsprops
  dev/com.ibm.ws.microprofile.config.1.3/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_cs.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_fr.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_hu.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_it.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_ja.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_ko.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_pt_BR.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_ru.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_zh.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages_zh_TW.nlsprops
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_cs.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_de.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_es.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_fr.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_hu.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_it.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_ja.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_ko.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_pl.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_pt_BR.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_ro.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_ru.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_zh.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans_zh_TW.properties
Labels: CLA Signed, ID review not needed

#4752 Revert "Shutdown improvements"
  dev/com.ibm.ws.channelfw/src/com/ibm/websphere/channelfw/ChannelUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/channelfw/internal/UtilsChainListener.java
  dev/com.ibm.ws.concurrency.policy/bnd.bnd
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/MonitorHolder.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/scan/ScanningCoreServiceImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
  dev/com.ibm.ws.runtime.update/bnd.bnd
  dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/PauseableComponentQuiesceListener.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutorProvider.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ThreadQuiesce.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/bnd.bnd
Labels: CLA Signed

#4748 resolve test failure for issue #4739
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
Labels: CLA Signed, in:Security, noproductcode, team:Security SSO, test bug

#4613 Performance Improvement
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: CLA Signed

#4733 Update date insert in OIDC client NLS message
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
Labels: CLA Signed, team:Security SSO

#4658 Prepend the fields of audit source when Jsonifying
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
Labels: CLA Signed

#4703 4590 update poms
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
Labels: CLA Signed

#4741 4715-OLStream1
  dev/com.ibm.ws.security.credentials.wscred/src/com/ibm/ws/security/credentials/wscred/internal/WSCredentialProvider.java
Labels: CLA Signed, release bug

#4672 tolerate pkcs#1 keys
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
Labels: CLA Signed

#4755 PII NLS 3Q18 Shipment 4 Returns
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_cs.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_de.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_es.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_fr.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_hu.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_it.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_ja.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_ko.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_pl.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_pt_BR.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_ro.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_ru.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_zh.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages_zh_TW.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_cs.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_de.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_es.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_fr.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_hu.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_it.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_ja.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_ko.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_pl.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_pt_BR.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_ro.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_ru.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_zh.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions_zh_TW.nlsprops
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_cs.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_de.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_es.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_fr.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_hu.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_it.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_ja.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_ko.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_pl.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_pt_BR.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_ro.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_ru.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_zh.nlsprops
  dev/com.ibm.ws.webserver.plugin.utility/resources/com/ibm/ws/webserver/plugin/utility/resources/UtilityMessages_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed

#4751 Issue #4750 - only depend on config 1.3
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/servers/FaultTolerance11TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIFallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/servers/FaultToleranceTCKServer/server.xml
Labels: CLA Signed

#4766 add doPriv
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/principal/PrincipalBean.java
Labels: CLA Signed

#4675 Fix for Issue #4647 Upgrade CXF to 3.1.16 for JAX-RS 2.0
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.0.beanvalidation/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/AbstractClient.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/MediaTypeHeaderProvider.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/RequestImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/interceptor/JAXRSInInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/FilterProviderInfo.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/ProviderInfo.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.jaxrs.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.managedbeans/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.server/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4757 Add Mapped Edition for packaging
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/AppliesToProcessor.java
Labels: CLA Signed

#4727 Upgrade SLF4J library
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
  dev/com.ibm.ws.clientcontainer.javamail_fat/bnd.bnd
  dev/com.ibm.ws.clientcontainer.javamail_fat/build.gradle
  dev/com.ibm.ws.com.lightbend.microprofile.reactive.streams.zerodep/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.streams.operators/bnd.bnd
  dev/com.ibm.ws.org.slf4j.api/bnd.bnd
  dev/com.ibm.ws.org.slf4j.jdk14/bnd.bnd
Labels: CLA Signed

#4726 Correct wait timing parameters; logging adjustments; remove zip notif…
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingProperties.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileData.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/notification/JarArtifactNotificationTest.java
Labels: CLA Signed

#4737 Update beanValidation, jaxrs, jca, and mpOpenAPI features to include JAXB
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jca-1.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-1.1/com.ibm.websphere.appserver.beanValidation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-2.0/com.ibm.websphere.appserver.beanValidation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
  dev/com.ibm.ws.beanvalidation.v11_fat/test-applications/DefaultBeanValidationCDI_11.war/src/defaultbeanvalidation/cdi/web/BValAtInjectionServlet.java
  dev/com.ibm.ws.beanvalidation.v20_fat/test-applications/bvalCDIApp/src/bval/v20/cdi/web/BeanValCDIServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#4769 Generate and use custom j2sec policy file for beanval.v11_fat
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/basic/BasicValidation11Test.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/basic/BasicValidation20Test.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/cdi/BeanValidation11CDITest.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/cdi/BeanValidation20CDITest.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/ejb/EJBModule11Test.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/ejb/EJBModule20Test.java
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation.cdi_1.1.fat/server.xml
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation.cdi_2.0.fat/server.xml
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation.ejb_1.1.fat/server.xml
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation.ejb_2.0.fat/server.xml
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation_1.1.fat/server.xml
  dev/com.ibm.ws.beanvalidation.v11_fat/publish/servers/com.ibm.ws.beanvalidation_2.0.fat/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/fattest.simplicity/src/componenttest/topology/utils/PrivHelper.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4779 Update NOTICES for release
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#4764 Issue #4761: Exclude openj9 packages in Test
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerClasspathTest.java
Labels: CLA Signed, noproductcode

#4736 Revert getLocation change - should only be non-null if explicitly set
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4802 Revert version upgrade
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
Labels: CLA Signed, noproductcode

#4697 Remove liberty change flags for function ported to the cxf community.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProvider.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/lifecycle/PerRequestResourceProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
Labels: CLA Signed

#4805 Revert "Upgrade SLF4J library"
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.clientcontainer.javamail_fat/bnd.bnd
  dev/com.ibm.ws.clientcontainer.javamail_fat/build.gradle
  dev/com.ibm.ws.com.lightbend.microprofile.reactive.streams.zerodep/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.streams.operators/bnd.bnd
  dev/com.ibm.ws.org.slf4j.api/bnd.bnd
  dev/com.ibm.ws.org.slf4j.jdk14/bnd.bnd
Labels: CLA Signed

#4786 Issue #4775 - minor updates to the mp reactive projects
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.streams.operators-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.reactivestreams-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-1.0/com.ibm.websphere.appserver.mpReactiveStreams-1.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/bnd.bnd
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/build.gradle
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionRunner.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/CompletionSubscriber.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/GraphAccessor.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/InternalStages.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/ProcessorBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/PublisherBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreams.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/ReactiveStreamsGraphBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/Reductions.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/SubscriberBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/package-info.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Graph.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/spi/ReactiveStreamsEngine.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/spi/Stage.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/spi/UnsupportedStageException.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/src/main/java/org/eclipse/microprofile/reactive/streams/spi/package-info.java
  dev/com.ibm.websphere.org.reactivestreams.reactive-streams.1.0/bnd.bnd
  dev/com.ibm.websphere.org.reactivestreams.reactive-streams.1.0/build.gradle
Labels: CLA Signed

#4778 Update CXF Transports-Http Binaries
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/src/com/ibm/ws/jaxws/client/LibertyProviderImpl.java
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-transports-http.bnd
  dev/com.ibm.ws.org.apache.xml.resolver/.classpath
Labels: CLA Signed

#4684 Issue 4682: Update EclipseLink to 2.6.7_WAS
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed, in:JPA, team:Blizzard

#4781 add first pass mpjwt 1.1 fat in quarantine
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/Readme.txt
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/DummyForQuarantine.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_env.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_noenv.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_noaud_env.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudEnv/bootstrap.properties
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudEnv/resources/security/key.jks
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudEnv/server.env
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudEnv/server.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudNoenv/bootstrap.properties
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudNoenv/resources/security/key.jks
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudNoenv/server.env
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckAudNoenv/server.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckNoaudEnv/bootstrap.properties
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckNoaudEnv/resources/security/key.jks
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckNoaudEnv/server.env
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/servers/tckNoaudEnv/server.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#4797 fixWebCollaborator
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecAnnotatedBasicAuthServlet.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
Labels: CLA Signed, in:Security, team:Core Security

#4746 Upgrade Hibernate Validator from 6.0.9 to 6.0.12
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.beanValidationCDI-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-2.0/com.ibm.websphere.appserver.beanValidation-2.0.feature
  dev/com.ibm.ws.beanvalidation.v20.cdi/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_de.properties
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages_nl.properties
  dev/com.ibm.ws.org.hibernate.validator/test/com/ibm/ws/org/hibernate/validator/HibernateValidatorMessageTest.java
Labels: CLA Signed, in:Java EE Platform, team:Zombie Apocalypse

#4795 4767 metrics monitor fat sun jdk
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/files/server_noJDBCMonitor.xml
Labels: CLA Signed, noproductcode

#4791 Allow stack products to force the replaced product into the log file
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/productinfo/ProductInfo.java
Labels: CLA Signed, target:3Q18

#4782 Add necessary import ranges for Guava
  dev/com.ibm.ws.cdi.weld/bnd.bnd
Labels: CLA Signed, team:Security SSO

#4813 Add null check to SystemConfigSource.getProperties
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/sources/SystemConfigSource.java
Labels: CLA Signed

#4793 Issue #4792: BundleContext no longer valid on server shutdown
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleInstallOriginBundleListener.java
Labels: CLA Signed, release bug

#4790 Generate and use custom j2sec policy file for JPA FAT
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/JPABootstrapTest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa10/CallbackTest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22BeanValidation.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22Injection.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22QueryTest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22TimeAPITest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPACDIIntegrationTest.java
Labels: CLA Signed, in:JPA, noproductcode, priority/medium, team:Blizzard

#4823 Allow JDBC 4.3 bundles to compile against JDBC 4.3 APIs
  dev/com.ibm.ws.jdbc.4.3.feature/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3.feature/src/com/ibm/ws/jdbc/osgi/v43/JDBC43Runtime.java
  dev/com.ibm.ws.jdbc.4.3/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3/lib/java.sql.4.3.jar
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43CallableStatement.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43Connection.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43DatabaseMetaData.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43PreparedStatement.java
  dev/com.ibm.ws.jdbc.4.3/src/com/ibm/ws/rsadapter/jdbc/v43/WSJdbc43Statement.java
  dev/com.ibm.ws.jdbc_fat_v43/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_v43/build.gradle
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: in:JDBC/JCA, team:Zombie Apocalypse

#4816 added new fat test package for no authentication metrics
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArchiveProcessor.java
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode, team:Lumberjack

#4686 Correct getServletPath for a default mapping case
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: CLA Signed, ID reviewed, release bug

#4817 Fix NPE when application builds a request to the targeted web resource
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/EndpointInfo.java
Labels: CLA Signed
