Repository OpenLiberty/open-liberty, pull requests merged in 2018-06, with the labels that each got.

#3815 Revert "2476 z fs log fails permanently"
  dev/com.ibm.ws.logging/resources/com/ibm/ws/logging/internal/resources/LoggingMessages.nlsprops
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/FileLogSet.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingFileUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/FileLogHolder.java
Labels: CLA Signed

#3813 Remove a couple CXF classes that we no longer need to override
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/ProxyOutputStream.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3792 expose HttpInboundConnection to upgrade logic
  dev/com.ibm.ws.webcontainer/src/com/ibm/websphere/servlet/request/IRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed

#3805 Change from the TwoTierObjectPool to a new ConcurrentObjectPool.
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/PooledWsByteBufferImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferPool.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferPoolManagerImpl.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ConcurrentObjectPool.java
Labels: CLA Signed

#3719 adding support for resolver jar override
  dev/com.ibm.ws.install.map/src/com/ibm/ws/install/map/InstallMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Engine.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/adaptor/ESAAdaptor.java
Labels: CLA Signed

#3822 Revert "Issue #3757 : update jwtsso default cookie name"
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/ConfigUtils.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
Labels: CLA Signed

#3820 Move getting InputStream to only happen if it is used.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed

#3817 3816 add intern to facelet context constant
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/FaceletContext.java
Labels: CLA Signed

#3811 Remove http2 stream close Timer tasks
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed

#3806 jcacheContainer-1.1 feature should be listed as non-ship
  dev/com.ibm.websphere.appserver.features/visibility/public/jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
Labels: CLA Signed, team:Zombie Apocalypse

#3827 Remove cts property
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStoreDefinitionWrapper.java
Labels: CLA Signed, team:Core Security

#3788 Add memory calculation for Linux containers with cgroup memory limitation
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/FileSystem.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformation.java
Labels: CLA Signed

#3841 Revert "Add memory calculation for Linux containers with cgroup memory limitation"
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/FileSystem.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformation.java
Labels: CLA Signed

#3791 Performance update for getting beanmanager.
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/model/DataModelBuilderProxy.java
Labels: CLA Signed

#3826 add getHttpInboundConnection() to IRequestExtended
  dev/com.ibm.ws.webcontainer/src/com/ibm/websphere/servlet/request/extended/IRequestExtended.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: CLA Signed

#3763 Enable users to configure KeepAlive setting in JAX-RS Clients
  dev/com.ibm.ws.jaxrs.2.0.client/resources/com/ibm/ws/jaxrs20/client/internal/resources/JAXRSClientMessages.nlsprops
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/configuration/LibertyJaxRsClientConfigInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/clientconfig/JAXRSClientConstants.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.classpath
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.project
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/fat/src/com/ibm/ws/jaxrs2x/clientProps/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/fat/src/com/ibm/ws/jaxrs2x/clientProps/fat/KeepAliveTest20.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/fat/src/com/ibm/ws/jaxrs2x/clientProps/fat/KeepAliveTest21.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/fat/src/com/ibm/ws/jaxrs2x/clientProps/fat/KeepAliveTestBase.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/publish/servers/jaxrs20.clientProps.fat.keepAlive/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/publish/servers/jaxrs20.clientProps.fat.keepAlive/server.xml
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/publish/servers/jaxrs21.clientProps.fat.keepAlive/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/publish/servers/jaxrs21.clientProps.fat.keepAlive/server.xml
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/keepAliveApp/src/jaxrs2x/clientProps/fat/keepAlive/KeepAliveHeaderCheckAppResource.java
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/keepAliveApp/src/jaxrs2x/clientProps/fat/keepAlive/KeepAliveTestServlet.java
Labels: in:JAX-RS, team:Wendigo West

#3838 Fix memory leak and more performance updates.
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/util/JaxRSClientUtil.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/ClientProviderFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/ClientProviderFactory.java
Labels: CLA Signed

#3736 Issue 1425: Suppress CWWKW1001W and CWWKW1002W msgs in JAX-RS 2.1
  dev/com.ibm.ws.jaxrs.2.0.cdi/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/CDITest.java
Labels: in:JAX-RS, team:Wendigo West

#3686 improve destination synchronization
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
Labels: CLA Signed

#3830 Issue #3819: Uninstall the application when an exception occurs after application is available
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootHandler.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ExceptionOccuredAfterAppIsAvailableTest15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed, in:SpringBoot

#3836 Reduce stream cleanup delay and improve close loop
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/priority/Node.java
Labels: CLA Signed

#3762 Fix message logic for Jandex enablement
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfig.java
Labels: CLA Signed

#3591 Issue #2224 Fixed stacktrace double append issue
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
Labels: CLA Signed, team:Lumberjack

#3735 #3579 Refactored code to use KeyValuePair instead of KeyValuePairList
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueBooleanPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueFloatPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueIntegerPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueLongPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValuePair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValuePairList.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/KeyValueStringPair.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging_fat/test-bundles/trace.source.handler/src/trace/source/handler/TraceHandlerImpl.java
Labels: CLA Signed

#3828 Issue #3757 : update jwtsso default cookie name
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/ConfigUtils.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
Labels: CLA Signed, team:Security SSO

#3509 Ensure mpRestClient-1.0 works with Filters in JAX-RS 2.1
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/FilterProviderInfo.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/BasicServiceClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/MyFilter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/MicroProfileClientFactoryBean.java
Labels: CLA Signed, in:JAX-RS, in:MicroProfile, team:Wendigo West

#3846 Fix server variables layout issue in OpenAPI UI
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui-bundle.js
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui.css
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui.js
Labels: CLA Signed

#3834 JSR375: Integrate jaspic session cookie to the existing sso cookie.
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/HashtableLoginModule.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/LoginToContinueInterceptor.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/Utils.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/LoginToContinueInterceptorTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/IdentityStoreHandlerServiceImplTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/AutoApplySessionTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreImmediateSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FormHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/ProgrammaticTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/Constants.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/form.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.anno.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.immediate.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ldapidstore.deferred.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/mechanisms/appllogintocontinue/redirect/LoginToContinueMechanism.java
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
Labels: in:Security, team:Core Security

#3823 Fix wildcard on group filter
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADWildCardTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.wild/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.wild/resources/security/ltpa.keys
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.wild/server.xml
Labels: CLA Signed, release bug, team:Wendigo East

#3856 Add thread safety to ParamConverter list.
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
Labels: CLA Signed

#3859 3814 integrate jaspic session to jwtSSOToken
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/HashtableLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModule.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelper.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenProxy.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.jwtsso.token/src/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImpl.java
  dev/com.ibm.ws.security.jwtsso.token/test/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImplTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
Labels: CLA Signed

#3631 PR for issue 3471: Fix PB cookie and url
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee8/Http2PushBuilder.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilder.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/SRTServletRequest40Test.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilderTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderSecurity.war/resources/WEB-INF/web.xml
Labels: CLA Signed

#3807 Revert "Enable jandex for cdi extenstion archives"
  .gitignore
  dev/com.ibm.ws.cdi.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/ExtensionArchiveImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/RuntimeFactory.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIRuntime.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/WebSphereCDIDeployment.java
  dev/com.ibm.ws.cdi.weld/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
Labels: CLA Signed

#3514 Include repository parsers in runtime
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
Labels: CLA Signed

#3867 3577 - refactor previous change to fix performance regression
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
Labels: in:JAX-RS, release bug, team:Wendigo West

#3812 2749:HTTPComponents4.3.1TempPackageForUpgrade
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.classpath
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.gitignore
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.project
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/bnd.bnd
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/bnd.overrides
Labels: CLA Signed

#3852 Issue 3851: Null check on reflective use of HTTP methods
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.patch/resources/security/key.jks
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.patch/resources/security/trust.jks
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.patch/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/patchapp/src/jaxrs21/fat/patch/PatchTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3878 Update use of z/OS settings to check if running on z/OS.
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutboundServiceContextImpl.java
Labels: CLA Signed

#3832 Consume new yoko; avoid security exceptions when loading classes acro…
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.clientcontainer.remote.common/src/com/ibm/ws/clientcontainer/remote/common/ClientSupportStubRegisterer.java
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SSLSubsystemFactory.java
  dev/com.ibm.ws.transport.iiop.transaction/src/com/ibm/ws/transport/iiop/transaction/TransactionSubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/WSClassRegistration.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/yoko/DefaultSocketFactorySubsystemFactory.java
Labels: CLA Signed

#3880 release buffers once done with them in magic path and error paths
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
Labels: CLA Signed

#2600 Improve Federated Repositories auditing and test coverage
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/context/AuditManager.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/context/AuditThreadContext.java
  dev/com.ibm.ws.org.apache.directory.server/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
  dev/com.ibm.ws.security.wim_test.servlet/src/com/ibm/ws/security/wim/test/VmmServiceServletConnection.java
  dev/com.ibm.ws.security.wim_test.servlet/test-applications/vmmService/src/web/VmmServiceServlet.java
Labels: team:Wendigo East

#3887 Remove bad time restriction from test
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
Labels: CLA Signed, noproductcode

#3839 Update CXF binaries to improve behavior when running JDKs past JDK8
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.jaxws.wsat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-api.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-bindings-soap.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-core.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-transports-http.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-ws-policy.bnd
Labels: CLA Signed

#3890 Validate archive paths
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/war/internal/ZipUtils.java
Labels: CLA Signed

#3866 Initial commit: added documentation for http/2 properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed

#3891 Skip the JAXB test when Java 2 security is enabled.
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseJaxbApp/src/jaxrs21sse/jaxb/SseJaxbTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#3895 Issue #3882: Add package-info.java to javax.faces.bean package
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/bean/package-info.java
Labels: CLA Signed

#3872 Parse singleton field from ESAs
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/EsaParser.java
  dev/com.ibm.ws.repository.test.utils/src/com/ibm/ws/lars/testutils/BasicChecks.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/EsaResource.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/writeable/EsaResourceWritable.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/WlpInformation.java
Labels: CLA Signed

#3896 Issue #3876 - minor post review updates
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectFactoryImpl.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectServiceImpl.java
Labels: CLA Signed

#3884 Issue #3883: Removed commons-collections3.2.1 package
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.classpath
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.gitignore
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.project
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/build.xml
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/build.xml.working
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
Labels: CLA Signed

#3874 JPA 2.2 Container Feature needs JNDI feature dependency
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.1/com.ibm.websphere.appserver.jpa-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.2/com.ibm.websphere.appserver.jpa-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.1/com.ibm.websphere.appserver.jpaContainer-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.2/com.ibm.websphere.appserver.jpaContainer-2.2.feature
Labels: bug, in:JPA, priority/high, team:Blizzard

#3905 Issue #2749: Missing Version in bnd.overrides
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/bnd.overrides
Labels: CLA Signed, noproductcode

#3914 Revert "Update CXF binaries to improve behavior when running JDKs past JDK8"
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.jaxws.wsat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-api.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-bindings-soap.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-core.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-transports-http.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-ws-policy.bnd
Labels: CLA Signed

#3908 Issue #3881: Increase login and transaction timeouts in DSD tests
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/fat/src/com/ibm/ws/ejbcontainer/interceptor/fat/AroundTimeoutTest.java
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/publish/files/jvm.options
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/publish/servers/com.ibm.ws.ejbcontainer.interceptor.fat.AroundTimeoutServer/server.xml
  dev/com.ibm.ws.injection_fat/publish/servers/com.ibm.ws.injection.fat.DSDServer/server.xml
  dev/com.ibm.ws.injection_fat/publish/servers/com.ibm.ws.injection.fat.RepeatableDSDServer/server.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDSingletonBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDStatefulBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnWeb.war/src/com/ibm/ws/injection/dsdann/web/BasicDSDAnnServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/src/com/ibm/ws/injection/dsdmix/ejb/DSDMixedBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixWeb.war/src/com/ibm/ws/injection/dsdmix/web/BasicDSDMixServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/src/com/ibm/ws/injection/dsdxml/ejb/DSDStatelessBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLWeb.war/src/com/ibm/ws/injection/dsdxml/web/BasicDSDXMLServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDAnnEJB.jar/src/com/ibm/ws/injection/repeatable/dsdann/ejb/RepeatableDSDStatefulBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDAnnWeb.war/src/com/ibm/ws/injection/repeatable/dsdann/web/BasicRepeatableDSDAnnServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDMixEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDMixEJB.jar/src/com/ibm/ws/injection/repeatable/dsdmix/ejb/RepeatableDSDMixedBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDMixWeb.war/src/com/ibm/ws/injection/repeatable/dsdmix/web/BasicRepeatableDSDMixServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDXMLEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDXMLEJB.jar/src/com/ibm/ws/injection/repeatable/dsdxml/ejb/RepeatableDSDStatelessBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDXMLWeb.war/src/com/ibm/ws/injection/repeatable/dsdxml/web/BasicRepeatableDSDXMLServlet.java
Labels: CLA Signed, noproductcode

#3864 change issuer url
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/IssuerUtil.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
Labels: CLA Signed

#3915 Adding Notices and License to zips
  dev/build.image/build.gradle
  dev/build.image/publish/LICENSE
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#3920 Resolve Batch deserialization of array types
  dev/com.ibm.jbatch.container/bnd.bnd
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/RuntimeStepExecution.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/CheckpointData.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/util/TCCLObjectInputStream.java
Labels: CLA Signed

#3901 Dont FFDC managed object exceptions
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ManagedBeanOBase.java
  dev/com.ibm.ws.injection.core/src/com/ibm/wsspi/injectionengine/InjectionTarget.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectFactoryImpl.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectImpl.java
Labels: CLA Signed

#3898 Issue #3897 : add custom auth provider claim to the jwtsso token and subject
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/TokenBuilder.java
  dev/com.ibm.ws.security.jwtsso/bnd.bnd
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/SubjectUtil.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIMappingHelper.java
Labels: CLA Signed

#3909 Parse IBM Install To Field in ESAs
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/EsaParser.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/EsaResource.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/writeable/EsaResourceWritable.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/WlpInformation.java
Labels: CLA Signed

#3406 Removed old bundles and refs
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/multiple_extensions/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/no_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/no_matching_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/one_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.classpath
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.gitignore
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.project
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/build.xml
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/findbugs.exclude.xml
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/src/org/apache/commons/fileupload/FileUploadBase.java
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/src/org/apache/commons/fileupload/MultipartStream.java
  dev/com.ibm.ws.org.apache.commons.io.1.4/.classpath
  dev/com.ibm.ws.org.apache.commons.io.1.4/.gitignore
  dev/com.ibm.ws.org.apache.commons.io.1.4/.project
  dev/com.ibm.ws.org.apache.commons.io.1.4/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.io.1.4/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.io.1.4/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.io.1.4/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.io.1.4/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io.1.4/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.io.1.4/build.xml
  dev/com.ibm.ws.org.apache.commons.io.2.4/.classpath
  dev/com.ibm.ws.org.apache.commons.io.2.4/.gitignore
  dev/com.ibm.ws.org.apache.commons.io.2.4/.project
  dev/com.ibm.ws.org.apache.commons.io.2.4/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.io.2.4/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.io.2.4/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.io.2.4/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.io.2.4/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io.2.4/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.io.2.4/build.xml
  dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
  dev/com.ibm.ws.persistence_fat/publish/features/com.ibm.ws.persistence.consumer-1.0.mf
Labels: CLA Signed

#3906 Revert "Issue #3467: Ensure proper handling of factory wrappers implementing the purge method"
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/config/FacesConfigurator.java
Labels: CLA Signed

#3907 initial commit of time weighted average for servlet response time, co…
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Clock.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/ExpDecayingReservoir.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Histogram.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/HistogramImpl.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdder.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdderAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/LongAdderProxy.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Snapshot.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/StatisticsMeter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/Striped64.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/TimeWeightedMeter.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/WeightedSnapshot.java
  dev/com.ibm.ws.monitor/test/com/ibm/websphere/monitor/meters/StatisticsMeterTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/websphere/webcontainer/ServletStatsMXBean.java
Labels: CLA Signed

#3924 Add recursion counters to avoid infinite loop in trace for hpelbts
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
Labels: CLA Signed

#3574 Fat test to check if app using metrics is held in memory after unloading said app
  dev/com.ibm.ws.microprofile.metrics_fat/.classpath
  dev/com.ibm.ws.microprofile.metrics_fat/.project
  dev/com.ibm.ws.microprofile.metrics_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/build.gradle
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsClassLoaderTest.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsClassLoaderTest_10.java
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsClassLoaderTest_11.java
  dev/com.ibm.ws.microprofile.metrics_fat/publish/files/server_disableMetricApp_10.xml
  dev/com.ibm.ws.microprofile.metrics_fat/publish/files/server_disableMetricApp_11.xml
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.0/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.0/server.env
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.0/server.xml
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.1/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.1/server.env
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.1/server.xml
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/checkerServlet/resources/.gitignore
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/checkerServlet/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/checkerServlet/src/com/ibm/ws/microprofile/metrics/fat/checker/servlet/CheckerServlet.java
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/classloaderUtil/src/com/ibm/ws/microprofile/metrics/classloader/utility/ClassLoaderUtils.java
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/metric-servlet/resources/.gitignore
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/metric-servlet/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/metric-servlet/src/com/ibm/ws/microprofile/metrics/fat/metric/servlet/MetricGenerator.java
  dev/com.ibm.ws.microprofile.metrics_fat/test-applications/metric-servlet/src/com/ibm/ws/microprofile/metrics/fat/metric/servlet/MetricServlet.java
Labels: CLA Signed, noproductcode

#3863 Change logic to route JUL logs directly to trace if it is a trace event
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
Labels: CLA Signed

#3928 ensure warning is printed
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3932 Remove references to generated jars. Just use bnd to find dependencies.
  dev/com.ibm.ws.microprofile.metrics_fat/.classpath
Labels: CLA Signed, noproductcode

#3926 JWKS containing a JWK with the x5c-attribute is now correctly parsed …
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWK.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWKTest.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/jwk/impl/jwk_test.json
Labels: CLA Signed, in:MicroProfile, in:Security

#3413 Issue #3335 - fix EEModuleDescriptor warnings
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BDAFactory.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereEEModuleDescriptor.java
Labels: CLA Signed

#3936 Update jaxws binaries
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.jaxws.wsat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-api.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-bindings-soap.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-core.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-transports-http.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-ws-policy.bnd
Labels: CLA Signed

#3934 Rearrange logging check in DBStore test
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#3942 PII NLS Returns from 2Q18 Shipment 8
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_cs.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_de.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_es.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_fr.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_hu.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_it.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_ja.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_ko.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_pl.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_pt_BR.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_ro.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_ru.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_zh.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages_zh_TW.nlsprops
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype_zh_TW.properties
Labels: CLA Signed, ID review not needed

#3951 Copy License and Notices to package staging dir
  dev/build.image/build.gradle
Labels: CLA Signed

#3941 Port MongoDB FAT to OpenLiberty
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.mongo_fat/.classpath
  dev/com.ibm.ws.mongo_fat/.project
  dev/com.ibm.ws.mongo_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.mongo_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.mongo_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.mongo_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.mongo_fat/bnd.bnd
  dev/com.ibm.ws.mongo_fat/build.gradle
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/AbstractMongoTestCase.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/FATSuite.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoServerSelector.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/TestMongoDb.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/TestMongoDbNoSSLFeature.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/TestMongoDbSSL.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/TestMongoDbSSLDefaultConfig.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/TestMongoDbWar.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/shared/MongoServletAction.java
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.no.ssl.feature/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.no.ssl.feature/server.xml
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.ssl.default.config/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.ssl.default.config/server.xml
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.ssl/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.ssl/resources/security/invalidCertAuthTrustStore.jks
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server.ssl/server.xml
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/com.ibm.ws.mongo.fat.server/server.xml
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/resources/META-INF/permissions.xml
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/resources/WEB-INF/web.xml
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/AbstractMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/DifferentSSLRefServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/InjectedMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/InvalidTruststoreMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/JNDIResourceEnvRef.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/MongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/NestedSSLServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/NoSSLFeatureServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/NoSSLRefMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthAliasNotInKeystoreServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthInvalidAliasServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthInvalidDriverLevelServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthInvalidScenarios.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthInvalidTrustServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthNoAliasButReqdServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthNoAliasReqdServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthNoSSLEnabledServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthParmsPasswordServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthParmsUseridServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthSSLEnabledFalseServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLCertAuthValidAliasServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLEnabledFalseMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLEnabledFalseSSLRefMongoServlet.java
  dev/com.ibm.ws.mongo_fat/test-applications/mongo/src/com/ibm/ws/mongo/servlet/SSLRefOnlyMongoServlet.java
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/ACEScanner.java
Labels: CLA Signed, noproductcode

#3953 Make test more tolerant to slow machines, also reduce test runtime
  dev/com.ibm.ws.monitor/test/com/ibm/websphere/monitor/meters/StatisticsMeterTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3659 Remove system.out.println
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/wsspi/kernel/embeddable/ServerBuilder.java
Labels: CLA Signed

#3855 Use OS Mbean instead of reflection and enhance Linux container memory calculation
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/FileSystem.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformation.java
  dev/com.ibm.ws.kernel.boot/bnd.bnd
Labels: CLA Signed

#3935 keep more careful track of FFDCs encountered in FATs
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode

#3900 Updated the test h2 test code to wait for a goaway frame if one is expected.
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResult.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResultManager.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
Labels: CLA Signed

#3946 Cleanup repo even if test fails
  dev/com.ibm.ws.repository.test.utils/src/com/ibm/ws/lars/testutils/fixtures/RepositoryFixture.java
Labels: CLA Signed

#3950 Fix caching servlet prematurely during serveServletsByClassName.
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/extension/InvokerExtensionProcessor.java
Labels: CLA Signed, release bug

#3837 Upgrade from ASM 6.0 to 6.1.1
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformation.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/BootstrapManifestTest.java
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
  dev/com.ibm.ws.request.probes/src/com/ibm/ws/request/probe/bci/internal/RequestProbeMethodAdapter.java
Labels: CLA Signed, team:Zombie Apocalypse

#3340 Issue 3070: update JCA code to apply protectionDomain to classpath for MQ
  dev/com.ibm.ws.jca.utils/resources/com/ibm/ws/jca/utils/internal/resources/JcaUtilsMessages.nlsprops
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/MetatypeGenerator.java
  dev/com.ibm.ws.jca/bnd.bnd
  dev/com.ibm.ws.jca/resources/com/ibm/ws/jca/internal/resources/J2CAMessages.nlsprops
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/BootstrapContextImpl.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ResourceAdapterService.java
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterSecurityTest.java
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.security/bootstrap.properties
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.security/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra/bootstrap.properties
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/test-resourceadapters/fvt-resourceadapter/resources/META-INF/permissions.xml
Labels: ID reviewed, team:Zombie Apocalypse

#3949 Cleanup duplicate security test apps
  dev/com.ibm.ws.security.fat.common/build.gradle
  dev/com.ibm.ws.security.fat.common/test-applications/formlogin/src/com/ibm/ws/security/fat/common/apps/formlogin/BaseServlet.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/apps/formlogin/FormLoginServletTest.java
  dev/com.ibm.ws.security.jwtsso_fat/.classpath
  dev/com.ibm.ws.security.jwtsso_fat/bnd.bnd
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/resources/login.jsp
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/resources/loginError.jsp
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/src/com/ibm/ws/security/fat/common/apps/formlogin/BaseServlet.java
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/src/com/ibm/ws/security/fat/common/apps/formlogin/FormLoginServlet.java
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/testmarker/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/testmarker/src/com/ibm/ws/security/fat/common/apps/testmarker/TestMarker.java
Labels: CLA Signed

#3970 Reduce expected time further to account for second fudging.
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
Labels: CLA Signed, noproductcode

#3985 added an image of open-liberty logo for ICP
  images/OpenLiberty-Logo.png
Labels: CLA Needed

#3991 Do not run the tx.jta_fat_hibernate bucket on JDK 7
  dev/com.ibm.ws.tx.jta_fat_hibernate/bnd.bnd
Labels: CLA Signed, in:Transactions, noproductcode, team:Zombie Apocalypse, test bug

#3989 Add testSettingFrameBadSize test to the trace bucket.
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
Labels: CLA Signed, noproductcode

#3794 Fix for Issue #3793: add IllegalArgumentException
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/BasicSseTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BasicSseApp/src/jaxrs21sse/basic/BasicSseResource.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BasicSseApp/src/jaxrs21sse/basic/BasicSseTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/src/org/apache/cxf/jaxrs/sse/NoSuitableMessageBodyWriterException.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/src/org/apache/cxf/jaxrs/sse/OutboundSseEventBodyWriter.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#4009 force the use of tls 1.2
  dev/gradle.properties
Labels: CLA Signed

#3998 Issue #3996 - allow metrics and openapi to tolerate config 1.3
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
Labels: CLA Signed

#4012 Issue 4006: Fix the CustomStateManagerInjection test by explicitly dr…
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/CDITestBase.java
Labels: CLA Signed, noproductcode

#4019 Add expected frames before upgrades in http/2 FATs
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/ContinuationFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/HttpMethodTests.java
Labels: CLA Signed, noproductcode

#4011 Fix packaging of security FAT test applications
  dev/com.ibm.ws.security.fat.common/build.gradle
Labels: CLA Signed, noproductcode, team:Security SSO

#4010 Add debug
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseResource.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
Labels: CLA Signed, noproductcode

#4025 Issue3980 additional trace for jms messaging
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/authorization/internal/MessagingAuthorizationServiceImpl.java
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/internal/MessagingSecurityServiceImpl.java
Labels: CLA Signed

#4003 Update base bundle to use new version and references to support
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.httpcommons-1.0.feature
  dev/com.ibm.websphere.filetransfer/bnd.bnd
  dev/com.ibm.websphere.security.impl/bnd.bnd
  dev/com.ibm.websphere.security/bnd.bnd
  dev/com.ibm.ws.org.apache.httpcomponents/bnd.bnd
  dev/com.ibm.ws.org.apache.httpcomponents/bnd.overrides
  dev/com.ibm.ws.security.javaeesec_fat/bnd.bnd
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
Labels: CLA Signed

#3972 Move MemoryInformation API to kernel.service
  dev/com.ibm.ws.kernel.boot.core/.classpath
  dev/com.ibm.ws.kernel.boot.core/bnd.bnd
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot/bnd.bnd
  dev/com.ibm.ws.kernel.service/.classpath
  dev/com.ibm.ws.kernel.service/bnd.bnd
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/service/utils/resources/ServiceMessages.nlsprops
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/FileSystem.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/MemoryInformation.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/MemoryInformationException.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/OperatingSystem.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/OperatingSystemException.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/OperatingSystemType.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/package-info.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/ws/kernel/service/test/MemoryInformationTests.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/ws/kernel/service/test/package-info.java
Labels: CLA Signed, ID reviewed

#4013 Change performance improvement to not use assignment in conditional.
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/application/ApplicationImpl.java
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/util/CDataEndEscapeFilterWriter.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ApplicationImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/util/CDataEndEscapeFilterWriter.java
Labels: CLA Signed

#4042 Updating CONTRIBUTING for CLA trivial
  CONTRIBUTING.md
Labels: CLA Signed

#4051 Move some code to reduce amount of code in sync block.
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
Labels: CLA Signed

#4049 Increase Gradle jvmargs -Xmx by 512MB and set -XX:+HeapDumpOnOutOfMem…
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#4018 Mark app start dependency to be ignored on quiesce
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfigurator.java
Labels: CLA Signed

#4045 Handle early startup failure and make sure failure logs are copied in…
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
Labels: CLA Signed

#4031 Use addAnnotatedType non-deprecated signature
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
Labels: CLA Signed

#4053 Make the RC for Starting Liberty as a Windows Service consistent with
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#4058 Update Gradle to version 4.8
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.httpcommons-1.0.feature
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#4055 testInvokeAnyTimedShutdownNowWhileEnqueued must allow for task rejected due to shutdown
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3840 Stop converting connection manager properties
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CGlobalConfigProperties.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/j2c/poolmanager/ConnectionPoolProperties.java
Labels: CLA Signed, team:Zombie Apocalypse

#4008 Changing bnd repo to artifactory
  dev/settings.gradle
Labels: CLA Signed, noproductcode

#4050 PR for Issue 3870: Add the authFilter-1.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.authFilter-1.0.feature
Labels: CLA Signed, team:Security SSO

#4059 Factor out function calls from buildscript
  dev/settings.gradle
Labels: CLA Signed, noproductcode

#4052 Update EclipseLink logging logic to avoid calling Map.get so often.
  dev/com.ibm.ws.jpa.container.eclipselink/src/com/ibm/ws/jpa/container/eclipselink/logging/EclipseLinkLogger.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/eclipselink/Log.java
Labels: CLA Signed

#3971 Zipreaper 3q
  dev/com.ibm.ws.artifact.zip/.classpath
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingProperties.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingService.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipFileHandle.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/CacheHashMap.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingServiceImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileData.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileDataStore.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/package-info.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/package-info.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ContainerFactoryHolder.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/FileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/SystemUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/Utils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntryIterator.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileNestedDirContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/package-info.java
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/ArtifactAPIServlet.java
  dev/com.ibm.ws.artifact_fat_bvt/test-applications/artifactapi.war/src/com/ibm/ws/artifact/fat_bvt/servlet/notification/JarArtifactNotificationTest.java
Labels: CLA Signed

#4063 Use incubating parallel builds
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#4041 Common security code updates for consolidation
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/package-info.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/WebUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/http/HttpUtilsTest.java
Labels: CLA Signed

#4110 Revert "Use incubating parallel builds"
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#4102 Fix to 2032
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DynamicSourcesTest.java
Labels: CLA Signed

#3999 Managed object factory updates
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/ManagedObjectService.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectFactoryImpl.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectImpl.java
  dev/com.ibm.ws.managedobject/src/com/ibm/ws/managedobject/internal/ManagedObjectServiceImpl.java
Labels: CLA Signed

#4065 Release recovery log lease earlier
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
Labels: CLA Signed

#3984 2476 z fs log fails permanently
  dev/com.ibm.ws.logging.hpel/test/com/ibm/ws/logging/internal/hpel/HpelBaseTraceServiceTest.java
  dev/com.ibm.ws.logging.hpel/test/com/ibm/ws/logging/internal/hpel/HpelLogProviderImplTest.java
  dev/com.ibm.ws.logging/resources/com/ibm/ws/logging/internal/resources/LoggingMessages.nlsprops
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/FileLogSet.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingFileUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/FileLogHolder.java
Labels: CLA Signed, ID review not needed

#4121 PR for Issue 3491: JWT SSO test without SSL port
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_noSslPort.xml
Labels: CLA Signed, noproductcode, team:Security SSO

#4125 3997 mpstartupconflict
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/interfaces/ConfigStartException.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/sources/InternalConfigSource.java
  dev/com.ibm.ws.microprofile.metrics.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1/src/com/ibm/ws/microprofile/metrics11/impl/MetricRegistry11Impl.java
  dev/com.ibm.ws.microprofile.metrics.1.1/src/com/ibm/ws/microprofile/metrics11/impl/SharedMetricRegistries11.java
Labels: CLA Signed

#4015 Change to use biz.aQute.bnd.* 4.0.0 dependencies instead of 3.5.0
  dev/cnf/build.gradle
  dev/cnf/gradle/scripts/anttaskdefs.bnd
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.ws.bnd.annotations/bnd.bnd
  dev/wlp-bndPlugins/bnd.bnd
  dev/wlp-featureTasks/bnd.bnd
Labels: CLA Signed

#4127 server dump tests broken when Windows path separator used
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4122 Fix bug which didn't allow for infinite conn timeout
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
Labels: CLA Signed, team:Zombie Apocalypse

#4109 Accepted inherited matches for user encoding parameters
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/LinkWrite.java
Labels: CLA Signed

#4131 Do not add bnd.gradle dependency since it isn't needed.
  dev/cnf/build.gradle
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, noproductcode

#4104 2725 config bean
  dev/com.ibm.ws.microprofile.config.cdi/src/com/ibm/ws/microprofile/config/cdi/ConfigBean.java
  dev/com.ibm.ws.microprofile.config_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/SimultaneousRequestsServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/SimultaneousRequestsServer/server.env
  dev/com.ibm.ws.microprofile.config_fat/publish/servers/SimultaneousRequestsServer/server.xml
  dev/com.ibm.ws.microprofile.config_fat/test-applications/simultaneousRequests.war/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.microprofile.config_fat/test-applications/simultaneousRequests.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.microprofile.config_fat/test-applications/simultaneousRequests.war/src/com/ibm/ws/microprofile/appConfig/simultaneousRequests/test/EmptyBean.java
  dev/com.ibm.ws.microprofile.config_fat/test-applications/simultaneousRequests.war/src/com/ibm/ws/microprofile/appConfig/simultaneousRequests/test/SimultaneousRequestsTestServlet.java
Labels: CLA Signed

#4119 Add a timeout to a close frame sync write path.
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/WsocConnLink.java
Labels: CLA Signed

#4129 Store weakref to classloader not config
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/AbstractProviderResolver.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/ConversionManager.java
Labels: CLA Signed

#4141 Use same iterator when checking/getting next element
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Zombie Apocalypse

#4118 Issue #3930: Removing Temp packages and references
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.httpcommons-1.0.feature
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.classpath
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.gitignore
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.project
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/bnd.bnd
  dev/com.ibm.ws.org.apache.httpcomponents.4.3.1/bnd.overrides
Labels: CLA Signed

#4149 Update eclipse / bnd settings for new components.
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.project
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#4130 Issue #4100 -- add logging to overQualLastAccessTimeUpdate
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
Labels: CLA Signed

#4151 testTransactionTimeoutAbort not waiting for transaction to time out
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/basicfat/src/jdbc/fat/v41/web/BasicTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4142 Minor doc improvements to JMS & server cmd
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
  dev/com.ibm.ws.messaging.jms.common/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID review not needed

#4021 MDB support for MDB request classification using WLM
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSContainer.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSDeployedSupport.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/MessageEndpointCollaborator.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/EJBRuntime.java
  dev/com.ibm.ws.ejbcontainer.mdb.core/src/com/ibm/ws/ejbcontainer/mdb/MessageEndpointBase.java
  dev/com.ibm.ws.ejbcontainer.mdb/src/com/ibm/ws/ejbcontainer/mdb/internal/MDBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/MDBRuntime.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
Labels: CLA Signed

#4022 Issue #4014: Add a FAT tool that will take a series of included serve…
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/CommonMergeTools.java
  dev/com.ibm.ws.security.fat.common/test-files/imports/.gitignore
  dev/com.ibm.ws.security.fat.common/test-files/imports/emptyFile.xml
  dev/com.ibm.ws.security.fat.common/test-files/imports/rootWithoutChildren.xml
  dev/com.ibm.ws.security.fat.common/test-files/imports/server-01.xml
  dev/com.ibm.ws.security.fat.common/test-files/imports/server-02.xml
  dev/com.ibm.ws.security.fat.common/test-files/imports/server-03.xml
  dev/com.ibm.ws.security.fat.common/test-files/imports/server-04.xml
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/utils/CommonMergeToolsTest.java
Labels: CLA Signed, team:Wendigo East

#4159 Rename fields to make it clear which Mongo API is accessed reflectively
  dev/com.ibm.ws.mongo/src/com/ibm/ws/mongo/internal/MongoService.java
  dev/com.ibm.ws.mongo/src/com/ibm/ws/mongo/internal/Utils.java
Labels: CLA Signed, team:Zombie Apocalypse
