Repository OpenLiberty/open-liberty, pull requests merged in 2018-05, with the labels that each got.

#3253 Optimize primitive object caching
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/BuiltinSerializationInfo.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SerializationInfoCache.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/TypeConversion.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#3362 Add ServerMessageExpectation class to security FAT infra
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ServerMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ServerMessageExpectationTest.java
Labels: CLA Signed, team:Security SSO

#3356 Add messages for invalid spring boot application
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/InvalidAppTests.java
Labels: CLA Signed

#3310 Moving to uplevel bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.persistence_fat/bnd.bnd
  dev/com.ibm.ws.persistence_fat/com.ibm.ws.persistence.consumer.testresource.bnd
  dev/com.ibm.ws.repository.test.utils/bnd.bnd
  dev/com.ibm.ws.rest.handler/bnd.bnd
  dev/com.ibm.ws.security.utility.securityutil/bnd.bnd
  dev/com.ibm.ws.security.utility/bnd.bnd
  dev/com.ibm.ws.springboot.utility.springbootutil/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.utility/bnd.bnd
Labels: CLA Signed

#3373 Issue #3372: Wait for user registry servlet to reload after swapping …
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryDynamicUpdateTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#3322 Replace the messageLogFormat second parameter with the appropriate value
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#3305 Fix NPEs for error path when sessionCache-1.0 has invalid config
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTRequestContext.java
  dev/com.ibm.ws.webserver.plugin.runtime/src/com/ibm/ws/webserver/plugin/runtime/listeners/GeneratePluginConfigListener.java
Labels: CLA Signed, team:Zombie Apocalypse

#3371 include session attribute names in session cache introspector
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#3377 Exclude testBulkheadClassAsynchFutureDoneWithoutGet OL#3376
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#3387 IllegalStateException from SessionCacheConfigUpdateTest
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2923 fix for issue 2877 - correct tag file errors in loose jars
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inputsource/JspURLConnection.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/utils/JspTranslatorUtil.java
Labels: CLA Signed

#3386 Update user action for invalid spring boot application
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
Labels: CLA Signed, ID reviewed

#3379 Delete redundant UTF8Encoder class
  dev/com.ibm.ws.messaging.jms.common/src/com/ibm/ws/sib/jms/util/UTF8Encoder.java
Labels: CLA Signed

#3368 Issue #3367: Remove ContextPoolOnLDAPFailureTest and replace with uni…
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/ContextPoolOnLDAPFailureTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.context.pool.on.ldap.fail/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.context.pool.on.ldap.fail/server.xml
Labels: CLA Signed, team:Wendigo East

#3057 Tolerate Java 9 multi-release JARs
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedContainer.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedDirectory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedJar.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedSimple.java
Labels: release bug

#3364 Issue3157 spring security
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/MvcConfig.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/WebSecurityConfig.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/templates/hello.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/templates/login.html
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SpringSecurityTests.java
Labels: CLA Signed

#3190 Fix tescase to remove arbitrary time factors resulting in intermitten…
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseResource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#3391 Custom login failure after JSR 375 authentication completed successfully
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/BridgeBuilderService.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiCallbackHandler.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/NonMappingCallbackHandler.java
  dev/com.ibm.ws.security.jaspic/test/com/ibm/ws/security/jaspi/JaspiCallbackHandlerTest.java
  dev/com.ibm.ws.security.jaspic/test/com/ibm/ws/security/jaspi/NonMappingCallbackHandlerTest.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/BridgeBuilderImpl.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.xml
Labels: CLA Signed

#3400 Issue #2935: Move DSDTest to injection_fat in open-liberty
  dev/com.ibm.ws.injection_fat/.classpath
  dev/com.ibm.ws.injection_fat/bnd.bnd
  dev/com.ibm.ws.injection_fat/build.gradle
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/DSDTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/FATSuite.java
  dev/com.ibm.ws.injection_fat/publish/servers/com.ibm.ws.injection.fat.DSDServer/.gitignore
  dev/com.ibm.ws.injection_fat/publish/servers/com.ibm.ws.injection.fat.DSDServer/bootstrap.properties
  dev/com.ibm.ws.injection_fat/publish/servers/com.ibm.ws.injection.fat.DSDServer/server.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDSingletonBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDStatefulBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnWeb.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnWeb.war/src/com/ibm/ws/injection/dsdann/web/BasicDSDAnnServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/src/com/ibm/ws/injection/dsdmix/ejb/DSDMixedBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixWeb.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixWeb.war/src/com/ibm/ws/injection/dsdmix/web/BasicDSDMixServlet.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/src/com/ibm/ws/injection/dsdxml/ejb/DSDStatelessBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLWeb.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLWeb.war/src/com/ibm/ws/injection/dsdxml/web/BasicDSDXMLServlet.java
Labels: CLA Signed, noproductcode, team:Blizzard

#3351 Create TestActions class for common security FAT infra
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/package-info.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/exceptions/TestActionException.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/actions/TestActionsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/exceptions/TestActionExceptionTest.java
  dev/com.ibm.ws.security.test.common/src/com/ibm/ws/security/test/common/CommonTestClass.java
Labels: CLA Signed, team:Security SSO

#3405 Issue3394 cdi
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CDITests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed

#3396 Issue 3067: Complete filtering of embedded servers
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/EmbeddedContainerTest.java
Labels: CLA Signed

#3393 Update KC the WC property servletDestroyWaitTime
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Signed, ID reviewed

#3418 Start the server with EE7 features
  dev/com.ibm.ws.cdi.extension_fat/publish/servers/observerServer/server.xml
Labels: CLA Signed, noproductcode

#3370 Bruce jwttsso more fats
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelper.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FeatureOnlyTest.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/bootstrap.properties
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/server_testlargecookies.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/formlogin/src/com/ibm/ws/security/fat/common/apps/formlogin/BaseServlet.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/LoggedOutJwtSsoCookieCache.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
Labels: CLA Signed

#3412 Issue #3411: Add certificate chain support to the internal com.ibm.ws…
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/CertificateLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/wsspi/security/common/auth/module/IdentityAssertionLoginModule.java
  dev/com.ibm.ws.security.quickstart/src/com/ibm/ws/security/quickstart/internal/QuickStartSecurityRegistry.java
  dev/com.ibm.ws.security.registry.basic/src/com/ibm/ws/security/registry/basic/internal/BasicRegistry.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/CustomCertificateMapperInBellTest.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/CustomCertificateMapperInFeatureTest.java
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/BasicUser3.jks
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/ca.pem
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/generateCertChain.sh
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.bell/server.xml
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.feature/server.xml
  dev/com.ibm.ws.security.registry.basic_fat/test-applications/certificateMappers/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.registry.basic_fat/test-applications/certificateMappers/META-INF/services/com.ibm.websphere.security.X509CertificateMapper
  dev/com.ibm.ws.security.registry.basic_fat/test-applications/certificateMappers/OSGI-INF/CertificateMapper4.xml
  dev/com.ibm.ws.security.registry.basic_fat/test-applications/certificateMappers/src/test/cert/mappers/CertificateMapper4.java
  dev/com.ibm.ws.security.registry/src/com/ibm/ws/security/registry/UserRegistry.java
  dev/com.ibm.ws.security.registry/src/com/ibm/ws/security/registry/internal/CustomUserRegistryWrapper.java
  dev/com.ibm.ws.security.registry/src/com/ibm/ws/security/registry/internal/UserRegistryProxy.java
  dev/com.ibm.ws.security.registry/src/com/ibm/ws/security/registry/internal/UserRegistryWrapper.java
  dev/com.ibm.ws.security.registry_test.servlet/src/com/ibm/ws/security/registry/test/UserRegistryServletConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/CustomCertificateMapperInBellTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/CustomCertificateMapperInFeatureTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/ca.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/generateCertChain.sh
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/test-applications/certificateMappers/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/test-applications/certificateMappers/META-INF/services/com.ibm.websphere.security.X509CertificateMapper
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/test-applications/certificateMappers/OSGI-INF/CertificateMapper6.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/test-applications/certificateMappers/src/test/cert/mappers/CertificateMapper6.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
  dev/com.ibm.ws.security.wim.core/test/com/ibm/ws/security/wim/adapter/urbridge/util/DummyRegistry.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/WIMUserRegistry.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/BridgeUtils.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/LoginBridge.java
Labels: CLA Signed, team:Wendigo East

#3433 Websocket and http2 configuration are not mutually exclusive.
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed

#3424 create autofeature for jcachecontainer and cdi
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi2.0-jcache1.1.feature
  dev/com.ibm.ws.jcache.cdi/.classpath
  dev/com.ibm.ws.jcache.cdi/.project
  dev/com.ibm.ws.jcache.cdi/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jcache.cdi/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jcache.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jcache.cdi/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jcache.cdi/bnd.bnd
  dev/com.ibm.ws.jcache.cdi/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/com.ibm.ws.jcache.cdi/src/com/ibm/ws/jcache/cdi/JCacheExtension.java
  dev/com.ibm.ws.jcache.cdi/src/com/ibm/ws/jcache/cdi/package-info.java
Labels: CLA Signed, team:Zombie Apocalypse

#3437 Issue #3435: Fix compilation errors in JUnit tests.
  dev/com.ibm.websphere.security.impl/test/com/ibm/ws/security/intfc/internal/UserRegistryWrapperTest.java
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/ws/security/authentication/jaas/modules/CertificateLoginModuleTest.java
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/wsspi/security/common/auth/module/IdentityAssertionLoginModuleTest.java
  dev/com.ibm.ws.security.quickstart/test/com/ibm/ws/security/quickstart/internal/QuickStartSecurityRegistryTest.java
  dev/com.ibm.ws.security.registry.basic/test/com/ibm/ws/security/registry/basic/internal/BasicRegistryTest.java
  dev/com.ibm.ws.security.registry/test/com/ibm/ws/security/registry/internal/CustomUserRegistryWrapperTest.java
  dev/com.ibm.ws.security.registry/test/com/ibm/ws/security/registry/internal/UserRegistryProxyTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#3381 More eclipse cleanup
  dev/com.ibm.ws.cdi.extension_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.config_fat/.classpath
  dev/com.ibm.ws.config_fat/bnd.bnd
  dev/com.ibm.ws.jcache.cdi/.classpath
  dev/com.ibm.ws.messaging.common/.classpath
  dev/com.ibm.ws.messaging.runtime/.classpath
  dev/com.ibm.ws.org.apache.commons.fileupload/.classpath
Labels: CLA Signed, noproductcode

#3374 generate bill of materials pom
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Constants.java
Labels: CLA Signed

#3309 Issue #3308: Add response cookie to push request cookie header
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilder.java
Labels: CLA Signed, in:Web Components

#3344 3089 default threadpool hang resolution
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed, release bug

#3451 Add FFDCIgnore for a InvalidRuntimeStateException in channel framework
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpChain.java
Labels: CLA Signed

#3421 Issue #3420 : update jwtsso features to include servlet 3.1
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jwtSsoToken-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
Labels: CLA Signed

#3409 Bruce jwtsso compare token exp times
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelper.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenProxy.java
  dev/com.ibm.ws.security.jwtsso.token/src/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImpl.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.webcontainer.security/resources/com/ibm/ws/webcontainer/security/resources/WebAppSecurityMessages.nlsprops
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
Labels: CLA Signed

#3408 Github#1296: Rename JPA-CDI autofeature to remove version from featur…
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jpaContainer-cdi.feature
Labels: CLA Signed, in:CDI, in:JPA, in:Java EE Platform, priority/medium, team:Blizzard

#3464 Issue3460 display jms roles for audit
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/authorization/internal/MessagingAuthorizationServiceImpl.java
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/internal/MessagingSecurityServiceImpl.java
Labels: CLA Signed

#3444 Re-cache the message InputStream to read FormParams
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentDeserializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3508 Update eclipse settings
  dev/com.ibm.ws.jsf.2.3_fat/.project
  dev/com.ibm.ws.jsf.2.3_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#3536 fix possible NPE caused by recent hang resolution changes
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed

#3480 testConcurrentSetGetAndRemove-key not found
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode

#3466 Issue3429 ssl error
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingSslFeatureTests.java
Labels: CLA Signed, ID reviewed, in:SpringBoot

#3544 Issue #3540: Add missing servelet-4.0 dependency to EJB FAT
  dev/com.ibm.ws.ejbcontainer.tx_fat/bnd.bnd
Labels: CLA Signed, noproductcode, test bug

#3521 Fix several JSR 375 issues
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-1.0/com.ibm.websphere.appserver.appSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-3.0/com.ibm.websphere.appserver.appSecurity-3.0.feature
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/form.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authalias.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.nouser.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.shortname.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ldapidstore.deferred.fat/server.xml
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#3600 Increased ulimate timeout for test
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
Labels: CLA Signed, noproductcode

#3586 Update to bndPlugin version 4.0.0
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#3616 Session cache changes
  dev/com.ibm.ws.session.cache/resources/com/ibm/ws/session/store/cache/resources/WASSessionCache.nlsprops
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SerializationInfoCache.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/TypeConversion.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: team:Zombie Apocalypse

#3622 3402 benjamin confino 109 microprofile config dsiable
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/FTGlobalConfig.java
Labels: CLA Signed

#3402 Allow disabling individual annotations
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/FTGlobalConfig.java
Labels: CLA Signed

#3623 3017 get failure for microprofile tck staging
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/ExecutionContextImpl.java
Labels: CLA Signed

#3549 create convenient runtime zips for javaee8 full profile and web profile
  dev/build.image/build.gradle
  dev/build.image/profiles/javaee8/features.xml
  dev/build.image/profiles/webProfile8/features.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/javaee8/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile8/server.xml
Labels: CLA Signed

#3458 Log warning if direct dependency not found when generating Maven artifacts
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/LibertyFeature.java
Labels: CLA Signed

#3625 Git fat to 11 no excludes plus cwmft5019 w
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceGitTckLauncher.java
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed

#3543 #3542 export javax.enterprise.inject.se
  dev/com.ibm.websphere.javaee.cdi.2.0/bnd.bnd
Labels: CLA Signed

#3442 recreate jwtSSOToken with custom stuffs
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/jaas/modules/ServerCommonLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/HashtableLoginModule.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModule.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/authentication/principals/WSPrincipal.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelper.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenProxy.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/TokenBuilder.java
  dev/com.ibm.ws.security.jwtsso.token/bnd.bnd
  dev/com.ibm.ws.security.jwtsso.token/src/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImpl.java
  dev/com.ibm.ws.security.jwtsso/bnd.bnd
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwtsso/resources/com/ibm/ws/security/jwtsso/internal/resources/JWTSSOMessages.nlsprops
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/config/JwtSsoBuilderConfig.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/config/JwtSsoConfig.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/Constants.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/IssuerUtil.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoConstants.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/MessageConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_testbadbuilder.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_testbadconsumer.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_testfallbacktoltpatrue.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_testgoodconsumer.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/JwtPrincipalMapping.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIJwtUtils.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIMappingHelper.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
Labels: CLA Signed

#3441 update basic annotations test to drive code path
  dev/com.ibm.ws.jcache_fat/bnd.bnd
  dev/com.ibm.ws.jcache_fat/publish/servers/jcacheContainerServer/bootstrap.properties
  dev/com.ibm.ws.jcache_fat/publish/servers/jcacheContainerServer/server.xml
  dev/com.ibm.ws.jcache_fat/publish/servers/jcacheContainerServerBell/server.xml
  dev/com.ibm.ws.jcache_fat/test-applications/jcacheApp/src/jcache/web/JCacheTestServlet.java
  dev/com.ibm.ws.jcache_fat/test-applications/jcacheApp/src/jcache/web/ZombiePod.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3450 only match CachingProvider instances from bells
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/DefaultCachingProviderSupport.java
Labels: team:Zombie Apocalypse

#3488 3476 disable serilize deserialize logging
  dev/com.ibm.ws.session.cache/resources/com/ibm/ws/session/store/cache/resources/WASSessionCache.nlsprops
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/SerializationInfoCache.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/TypeConversion.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: team:Zombie Apocalypse

#3438 Issue #3436: set referer header on init not push
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilder.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/SRTServletRequest40Test.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilderTest.java
Labels: CLA Signed

#3594 Add failover test for exercising HTTP session failover
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3555 Fix logic for minify,runnable
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
Labels: CLA Signed

#3585 Update Maven coordinates for j2ee management api
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.j2eeManagementClient-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/j2eeManagement-1.1/com.ibm.websphere.appserver.j2eeManagement-1.1.feature
Labels: CLA Signed

#3566 Sebratton/error pages
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/SpringBootConfig.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/SpringConfiguration.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/SpringErrorPageData.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/support/ContainerInstanceFactory.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version20.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/java/com/ibm/ws/springboot/support/version20/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/java/com/ibm/ws/springboot/support/version20/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.web.server.version15/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/osgi/SpringBoot20Support.java
  dev/com.ibm.ws.springboot.support.web.server/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstance.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstanceFactory.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPage15Test.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPage20Test.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPageBaseTest.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer/bnd.bnd
Labels: CLA Signed, in:SpringBoot

#3532 Fix leak of WABDeployedAppInfo when a wab is redeployed many times
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABGroup.java
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
Labels: CLA Signed

#3440 H2: Add code that allows for an inactivity to be set to close a
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2MuxTCPReadCallback.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed

#3607 fix checkpii errors
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_cs.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_de.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_es.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_fr.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_hu.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_it.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_ja.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_ko.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_pl.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_pt_BR.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_ro.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_ru.nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed

#3596 Issue2968 http2
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/HttpEndpoint.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/initializer/ServerConfigurationFactory.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpEndpoint.java
Labels: CLA Signed

#3415 Dont call toString on weld proxies for traces
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionBinding.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionObjectFactory.java
Labels: CLA Signed, release bug

#3571 work with ALPNJSSEExt on non-alpn connections
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLAlpnNegotiatorJdk8.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLConnectionLink.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
Labels: CLA Signed, in:Transport

#3527 Issue 3523: Add the Authorization header to the PushBuilder request a…
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilder.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/SRTServletRequest40Test.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilderTest.java
Labels: CLA Signed, in:Web Components

#3485 Generate Maven compile dependencies from manifests for Java specs
  dev/cnf/gradle/scripts/anttaskdefs.bnd
  dev/wlp-mavenRepoTasks/bnd.bnd
  dev/wlp-mavenRepoTasks/pom.xml
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/LibertyFeature.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/MavenCoordinates.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Constants.java
Labels: CLA Signed

#3633 NoSuchElementException on iterator.next
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: team:Zombie Apocalypse

#3511 impl missing for invalidateAll
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStore.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#3595 GA the sessionCache feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.sessionStore-1.0.0.JCache.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.javaee.jcache.1.1/bnd.bnd
  dev/com.ibm.ws.jcache_fat/fat/src/com/ibm/ws/jcache/fat/JCacheBellTest.java
  dev/com.ibm.ws.jcache_fat/fat/src/com/ibm/ws/jcache/fat/JCacheTest.java
  dev/com.ibm.ws.jcache_fat/test-applications/jcacheApp/src/jcache/web/JCacheTestServlet.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#3468 Allow h2c upgrade when servlet filters are active
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
Labels: CLA Signed, in:Web Components

#3619 Issue #3604: Fix MessageEndpointProxy with ME method overrides
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
Labels: CLA Signed

#3479 Pass future.get Timeouts to nested async
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ServerAsyncResult.java
Labels: CLA Signed

#3629 Issue #3613: Display an error message when websoket feature is not en…
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/ApplicationError.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.support.shutdown/src/com/ibm/ws/springboot/support/shutdown/FeatureAuditor.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingWebsocketFeatureTests15.java
Labels: CLA Signed, ID reviewed

#3634 Issue #3510 : ga jwt sso feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIMappingHelper.java
Labels: CLA Signed, team:Security SSO

#3494 PR for Issue 1422: Externalize ID attributes for JWT builder and consumer
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#3507 Improve calls to getInstalledFeatures so we aren't copying the Set.
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
Labels: CLA Signed

#3528 Remove some of the overhead in URITemplate
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/URITemplate.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/model/URITemplate.java
Labels: CLA Signed

#3517 Reduce calls to Subject.getPublicCredentials in security collaborator
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
Labels: CLA Signed

#3457 Upgrade from Hibernate Validator 6.0.7.Final to 6.0.9.Final
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.beanValidationCDI-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-2.0/com.ibm.websphere.appserver.beanValidation-2.0.feature
  dev/com.ibm.ws.beanvalidation.v20.cdi/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator/bnd.overrides
Labels: CLA Signed, in:Bean Validation, team:Zombie Apocalypse

#3640 Move to java7 line seperator idiom
  dev/com.ibm.ws.cdi.api_fat/test-applications/alterableContextApp.war/src/com/ibm/ws/cdi12/alterablecontext/test/AlterableContextTestServlet.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/afterTypeDiscoveryApp.war/src/com/ibm/ws/cdi12/aftertypediscovery/test/AfterTypeServlet.java
  dev/com.ibm.ws.cdi.beansxml_fat/test-applications/classExclusion.war/src/cdi12/classexclusion/test/TestServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/ejbConstructorInjection.war/src/com/ibm/ws/cdi/ejb/constructor/test/BeanEJB.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.war/src/cdi12/beanmanagerlookup/test/BeanManagerLookupServlet.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/ObservesInitializedInJars.war/src/cdi12/observersinjarsbeforebean/WarBeforeBeansObserver.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/ObservesInitializedInJarsSecondWar.war/src/cdi12/observersinjarssecondwar/WarBeforeBeansObserver.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/eventMetaData.war/src/com/ibm/ws/cdi12/test/MetaDataServlet.java
  dev/com.ibm.ws.cdi.lifecycle_fat/test-applications/scopeActivationDestructionTests.war/src/cdi12/resources/GlobalState.java
Labels: CLA Signed, noproductcode

#3537 add metatype attrib with one second granularity
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtComponent.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtCreator.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
Labels: CLA Signed, ID reviewed, team:Security SSO

#3486 push_promise frames require the http2 :authorize pseudo header
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: CLA Signed

#3475 Remove readOnly from DatabaseIdentityStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
Labels: team:Wendigo East

#3584 JAX-RS performance improvements
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/Servlet3ContinuationProvider.java
Labels: CLA Signed

#3558 Set default ID for keyStore element so configs merge properly
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: bug, in:Security, team:Zombie Apocalypse

#3447 Set SCC and AOT options regardless of JDK version
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: in:Kernel/Bootstrap, team:Zombie Apocalypse

#3541 Initial commit: Adding configurable options for HTTP/2, separating co…
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2ConnectionSettings.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameContinuation.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameData.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameHeaders.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePushPromise.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameSettings.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/hpack/H2Headers.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/transport/http2_test/frames/FrameTest.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/PushPromiseTests.java
Labels: CLA Signed

#3531 Add mechanism to opt-out of --release javac flag for JDK 9+ builds
  dev/build.gradle
  dev/cnf/build.bnd
  dev/com.ibm.ws.injection_fat/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#3365 mpOpenAPI extra tests and FAT fixes
  dev/com.ibm.ws.microprofile.openapi/resources/airlines_openapi.yaml
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/AnnotationScanner.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/Constants.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OpenAPIServlet.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/OperationParser.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/impl/parser/test/OpenAPIParserTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/JAXRSApp.java
Labels: CLA Signed

#3506 Creating a copy of commons-collections.3.2.1 to upgrade this package to 3.2.2.
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.classpath
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.gitignore
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.project
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/build.xml
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/build.xml.working
Labels: CLA Signed

#3609 Set id store id as the realm for custom HAMs when provided
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiCallbackHandler.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/NonMappingCallbackHandler.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/HttpMessageContextImpl.java
  dev/com.ibm.ws.security.javaeesec/test/com/ibm/ws/security/javaeesec/HttpMessageContextImplTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/commonServer.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/rememberMe.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/scoped.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAuthAliasBasicAuthServlet.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/identitystores/BaseIdentityStore.java
Labels: CLA Signed

#3493 Installing WL feature onto OL- include edition in error message
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#3453 Issue #3452: update MyFaces to 2.3.1
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/build.xml
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/annotation/FacesConfig.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/annotation/ManagedProperty.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/NavigationHandlerWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ViewHandler.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlCommandButton.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlCommandScript.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlInputFile.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlInputSecret.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlInputText.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlInputTextarea.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectBooleanCheckbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectManyCheckbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectManyListbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectManyMenu.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectOneListbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectOneMenu.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/HtmlSelectOneRadio.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_ChangeProperty.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlCommandButton.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlCommandScript.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlInputFile.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlInputSecret.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlInputText.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlInputTextarea.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectBooleanCheckbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectManyCheckbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectManyListbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectManyMenu.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectOneListbox.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectOneMenu.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_HtmlSelectOneRadio.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/html/_SelectProperty.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/visit/VisitContextFactory.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/visit/VisitContextWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/ExternalContext.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/ExternalContextWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/PartialViewContext.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/ResponseWriterWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/convert/DateTimeConverter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/WebsocketEvent.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23GeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ViewHandlerImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/JsfArtifactProducerExtension.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/StartupServletExternalContextImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/el/unified/ResolverBuilderBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/component/UIRepeat.java
Labels: CLA Signed

#3627 add metatype description
  dev/com.ibm.ws.management.security/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.management.security/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed

#3603 PR for Issue 3568: Update addAnnotatedType CDI invocations
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtension.java
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/JwtCDIExtension.java
Labels: team:Security SSO

#3519 Add request params to create custom extensions
  dev/com.ibm.ws.logging.json_fat/test-applications/LogstashApp/src/com/ibm/logs/ExtensionServlet.java
Labels: CLA Signed, noproductcode, team:Lumberjack

#3465 3462 jaxrs client bus
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3570 Installing OL feature to WL Core - Add proper error message to handle different products
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
Labels: CLA Signed, ID required

#3575 Issue #3477 Fixed 6 character issue
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
Labels: CLA Signed, team:Lumberjack

#3682 Revert "mpOpenAPI extra tests and FAT fixes"
  dev/com.ibm.ws.microprofile.openapi/resources/airlines_openapi.yaml
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/AnnotationScanner.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/Constants.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OpenAPIServlet.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/OperationParser.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/impl/parser/test/OpenAPIParserTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/JAXRSApp.java
Labels: CLA Signed

#3658 Issue#3649: Filter out the default netty server when deployed on libe…
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/EmbeddedContainerTest.java
Labels: in:SpringBoot

#3642 Move Spring Boot features to GA
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBoot15ServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBoot20ServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBootServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.springBootHandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-1.5/com.ibm.websphere.appserver.springBoot-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-2.0/com.ibm.websphere.appserver.springBoot-2.0.feature
Labels: CLA Signed, in:SpringBoot

#3670 Issue3654-webflux applications not supported
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/ApplicationError.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.support.shutdown/src/com/ibm/ws/springboot/support/shutdown/FeatureAuditor.java
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/.classpath
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/.gitignore
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/.project
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/src/main/java/com/ibm/ws/springboot/support/version20/test/webflux/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/WebFluxApplicationNotSupportedTest.java
Labels: CLA Signed, ID reviewed, in:SpringBoot

#3688 removing resolution from localEsaInstall
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#3513 After async complete is called, isAsyncStarted set to false upon exit…
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/async/AsyncContextImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
Labels: CLA Signed

#3685 Make logging safer
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionObjectFactory.java
Labels: CLA Signed

#3651 NullPointerException on value after cache modified during iteration
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: team:Zombie Apocalypse

#3678 3456 fix jaspic session default
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/form.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.xml
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
Labels: CLA Signed, ID reviewed

#3697 Issue #3683: Add app validation to exportDropins
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/DSDTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/RepeatableDSDTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
Labels: CLA Signed, noproductcode, team:Blizzard

#3701 JWT SSO FAT: Cookie manipulation and manually building JWT
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ServerMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/WebResponseUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/web/WebResponseUtilsTest.java
  dev/com.ibm.ws.security.jwtsso_fat/.classpath
  dev/com.ibm.ws.security.jwtsso_fat/bnd.bnd
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CommonJwtFat.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/CommonExpectations.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatActions.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/MessageConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_shortJwtLifetime.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_shortJwtLifetime_shortClockSkew.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_withBuilderApp.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/files/configs/server_withBuilderApp_consumerTrustsAllIssuers.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/separateKeyStore.jks
  dev/com.ibm.ws.security.jwtsso_fat/publish/shared/config/jwtbuilderApp.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/jwtbuilder/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/jwtbuilder/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/jwtbuilder/src/com/ibm/ws/security/fat/common/apps/jwtbuilder/JwtBuilderServlet.java
  dev/com.ibm.ws.security.jwtsso_fat/test-applications/jwtbuilder/src/com/ibm/ws/security/fat/common/apps/jwtbuilder/ProtectedServlet.java
Labels: CLA Signed, team:Security SSO

#3445 Remove jaxrs-2.1 dependency on json-1.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/websphere/jaxrs/providers/json4j/JSON4JArrayProvider.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/websphere/jaxrs/providers/json4j/JSON4JJAXBProvider.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/websphere/jaxrs/providers/json4j/JSON4JObjectProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.overrides
Labels: CLA Signed, in:JAX-RS, team:Zombie Apocalypse

#3698 JSR375:stopping a server without removing the application and features
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/AutoApplySessionTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/CustomIdentityStoreHandlerTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EAREJBModuleTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FormHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBAuthAliasTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBAuthDataTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LoginToContinueELTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplCustomTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplLoginToContinueTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreBasicTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleDBRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertFailOverTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleNoExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/NoIdentityStoreTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/NoJavaEESecFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/ProgrammaticTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/ScopedTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/multipleModuleDBBase.xml
Labels: CLA Signed, noproductcode

#3684 Reset httpclient between user checks
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#3689 MPOpenAPI UI update and SVT fixes
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/index.html
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/oauth2-redirect.html
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui-bundle.js
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui-standalone-preset.js
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui.css
  dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-CONTENT/swagger-ui.js
  dev/com.ibm.ws.microprofile.openapi/resources/airlines_openapi.yaml
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/AnnotationScanner.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/Constants.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OpenAPIServlet.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/OperationParser.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/impl/parser/test/OpenAPIParserTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/JAXRSApp.java
Labels: CLA Signed

#3674 convert default exp time to seconds
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
Labels: CLA Signed

#3597 3578 restrict jms consumed state transition
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/api/impl/JobOperatorImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/AbstractPersistenceManager.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/servicesmanager/ServicesManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/BatchStatusValidator.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSJobRepository.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
  dev/com.ibm.jbatch.container/test/com/ibm/jbatch/container/services/impl/AbstractPersistenceManagerTest.java
Labels: CLA Signed, in:Batch, release bug

#3707 Fix up eclipse files.
  dev/com.ibm.ws.cloudant/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cloudant/bnd.bnd
  dev/com.ibm.ws.cloudant/build.gradle
  dev/com.ibm.ws.couchdb/build.gradle
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/test-applications/AroundTimeoutAnnEJB.jar/src/com/ibm/ws/ejbcontainer/interceptor/aroundTimeout_ann/ejb/OverrideBase.java
  dev/com.ibm.ws.mongo/build.gradle
  dev/com.ibm.ws.org.apache.commons.collections.3.2.1/.project
Labels: CLA Signed

#3644 Fix http/2 NPE and improve SSL logging
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLWriteServiceContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: CLA Signed

#3699 add javaee 8 client.xml template
  dev/build.image/build.gradle
  dev/com.ibm.ws.appclient.boot/publish/templates/clients/javaeeClient7/client.xml
  dev/com.ibm.ws.appclient.boot/publish/templates/clients/javaeeClient8/client.xml
Labels: CLA Signed

#3667 Change wimcore-1.0 to use internal JAXB feature instead of exposing the API
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wimcore-1.0.feature
Labels: in:Security, team:Zombie Apocalypse

#3324 Add mapping of all JSP files in web module into the generated_web.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/tools/AbstractJspModC.java
Labels: CLA Signed

#3535 Fix for issue #3483: Refactor JAX-RS 2.1
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsAppSecurity-2.1.feature
  dev/com.ibm.ws.jaxrs.2.0.client/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.security/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/providers/security/SecurityAnnoProviderRegister.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3717 Issue #3715: Remove an unused MD5 certificate from the X.509 certific…
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/BasicUser3.jks
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/BasicUser3.pem
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/ca.pem
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/chain_ca.pem
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/chain_root.pem
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/clientcert/generateCertChain.sh
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.registry.basic_fat/test-applications/certificateMappers/src/test/cert/mappers/CertificateMapper4.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/ca.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_ca.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_root.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/generateCertChain.sh
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/test-applications/certificateMappers/src/test/cert/mappers/CertificateMapper6.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#3708 Issue3655 spring boot trace
  dev/com.ibm.ws.springboot.support.web.server/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/initializer/package-info.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed

#3648 Clean up http2 closed stream map
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/FrameReadProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed, in:Transport

#3720 JWT SSO FAT: Update to compile and run on Java 8
  dev/com.ibm.ws.security.jwtsso_fat/bnd.bnd
Labels: CLA Signed, noproductcode, team:Security SSO

#3714 #3542 - make cdi.se to be IBM-API
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
Labels: CLA Signed

#3388 Apply change recoomendations in review of PR #3092
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/CollectorManagerPipelineUtils.java
Labels: CLA Signed

#3562 Raise exception when properties are not passed to Gradle
  dev/build.image/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#3703 Tolerate JDBC 4.2 drivers not supporting Statement.getLargeUpdateCount() on cleanup code path
  dev/com.ibm.ws.jdbc.4.2/src/com/ibm/ws/rsadapter/jdbc/v42/WSJdbc42PreparedStatement.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
Labels: CLA Signed, in:JDBC/JCA, team:Zombie Apocalypse

#3704 Update liberty beta version to 2018.6.0.0
  dev/cnf/resources/bnd/liberty-release.props
Labels: in:Build, team:Zombie Apocalypse

#3721 Enforce test ordering in EMQSychronousHandlerTest
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/test/EMQSychronousHandlerTest.java
Labels: CLA Signed, noproductcode

#3710 Remove now-unused interface methods
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/BatchStatusValidator.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSJobRepository.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
Labels: CLA Signed

#3463 Issue #3467: Ensure proper handling of factory wrappers implementing the purge method
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/config/FacesConfigurator.java
Labels: in:Web Components, team:Wendigo West

#3726 Issue #3436: Use HttpServletRequest.getRequestURL() vs getRequestURI
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilder.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/SRTServletRequest40Test.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/test/com/ibm/ws/webcontainer40/srt/http/HttpPushBuilderTest.java
Labels: CLA Signed

#3733 PR for Issue 11779: Fix TAI cast in JWT SSO code
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
Labels: CLA Signed, team:Security SSO

#3728 H2 fix for concurrent modification when removing nodes from the priority
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/priority/Node.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/priority/Tree.java
Labels: CLA Signed

#3602 Issue2601-RemoveExtraAuditTrace
  dev/com.ibm.websphere.security/.classpath
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditAuthenticationResult.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/Audit.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/package-info.java
  dev/com.ibm.ws.webcontainer.security/.classpath
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticationResult.java
Labels: CLA Signed

#3738 remove un-necessary call when jwtSSO feature is not enabled
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/JwtSSOTokenBytesCacheKeyProvider.java
Labels: CLA Signed

#3709 Simplify Java 9 class detection
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedContainer.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedDirectory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedJar.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_MappedSimple.java
Labels: CLA Signed

#3576 Add MemoryInformation API to provide more accurate OS free memory statistics
  dev/com.ibm.ws.kernel.boot.core/.classpath
  dev/com.ibm.ws.kernel.boot.core/bnd.bnd
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/FileSystem.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformation.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/MemoryInformationException.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/OperatingSystem.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/OperatingSystemException.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/OperatingSystemType.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/util/package-info.java
  dev/com.ibm.ws.kernel.boot.core/test/com/ibm/ws/kernel/util/test/MemoryInformationTests.java
Labels: CLA Signed, ID required

#3747 Issue #3746 : jwtsso token unittests updates
  dev/com.ibm.ws.security.jwtsso.token/bnd.bnd
  dev/com.ibm.ws.security.jwtsso.token/src/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImpl.java
  dev/com.ibm.ws.security.jwtsso.token/test/com/ibm/ws/security/jwt/sso/token/JwtSSOTokenImplTest.java
  dev/com.ibm.ws.security.jwtsso.token/test/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImplTest.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
Labels: CLA Signed, team:Security SSO

#3635 Issue #3383: Add LDAP registry JNDI read timeout.
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ConfigConstants.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
Labels: CLA Signed, team:Wendigo East

#3730 Re-disabling part of testConcurrentSetGetAndRemove
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse
