Repository OpenLiberty/open-liberty, pull requests merged in 2018-04, with the labels that each got.

#2914 ready for build testing
  dev/wlp.lib.extract_fat/build-test.xml
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/ExternalDependencyDownloadTest.java
Labels: CLA Signed, noproductcode

#2857 Add changes and testcase to support SSE retry.
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/DelaySseTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/publish/servers/com.ibm.ws.jaxrs21.sse.delay/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/publish/servers/com.ibm.ws.jaxrs21.sse.delay/server.xml
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseResource.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/src/org/apache/cxf/jaxrs/sse/client/SseEventSourceImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
Labels: CLA Signed

#2893 Ensure that namespace URIs are interned when processing ra.xml
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/DeploymentDescriptorParser.java
Labels: bug, in:JDBC/JCA, team:Zombie Apocalypse

#2925 update existing test to use writeContents=GET_AND_SET_ATTRIBUTES
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2924 Use the String method instead of the byte[] method.
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: CLA Signed

#2921 Bruce mark jwtsso feature beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jwtSsoToken-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
Labels: CLA Signed

#2919 force sessionCache feature to use different CachingProviding instances than applications
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CachingProviderClassLoader.java
  dev/com.ibm.ws.session.cache_fat_config/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#2937 write tests for JCache MXBeans
  dev/com.ibm.ws.session.cache_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2839 update version from 18001 to 18002 for next release
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#2900 Update webcontainer formlogin app to support ShrinkWrap
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/apps/CommonFatApplications.java
  dev/com.ibm.ws.security.fat.common/test-applications/testmarker/src/com/ibm/ws/security/fat/common/apps/testmarker/TestMarker.java
  dev/com.ibm.ws.webcontainer.security_test.servlets/bnd.bnd
  dev/com.ibm.ws.webcontainer.security_test.servlets/common-classes/src/web/common/package-info.java
  dev/com.ibm.ws.webcontainer.security_test.servlets/test-applications/formlogin/src/web/formlogin/package-info.java
Labels: CLA Signed, team:Security SSO

#2892 #2360 Remove white space from entry/exit
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
Labels: CLA Signed

#2938 Do not load a Class on every REST request where an exception occurs.
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsInvoker.java
Labels: CLA Signed

#2830 Issue #660: Enable remote LDAP servers in FAT using Consul.
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/GetUserSecurityCustomLDAP.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.ad.ssl/trust.jks
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestService.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceFilter.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceFilterAlwaysMatched.java
  dev/fattest.simplicity/src/componenttest/topology/utils/HttpsRequest.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#2945 2920 myfaces4216
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ViewHandler.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ViewHandlerImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
Labels: CLA Signed

#2943 Issue 2942: Fix the setApplication method from WASApplicationFactoryI…
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/WASApplicationFactoryImpl.java
Labels: CLA Signed

#2949 Fixed extensions issue in CollectorJsonUtils
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
Labels: CLA Signed

#2922 Fix HttpServletMapping during NameDispatcher forward
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebAppDispatcherContext40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletRequest40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java
Labels: CLA Signed

#2950 2948 myfaces4217
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/annotation/ManagedProperty.java
Labels: CLA Signed

#2954 Update .classpath and bnd.bnd to include test directory
  dev/com.ibm.websphere.appserver.features/.classpath
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/.classpath
Labels: CLA Signed

#2898 Added code the throw a deployment exception if boolean was on the
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/AnnotatedEndpoint.java
Labels: CLA Signed

#2869 Add IdentityStore RuntimeException, add to DBIDStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStoreDefinitionWrapper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/IdentityStoreRuntimeException.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashNoConfigTest.java
Labels: CLA Signed, in:CTS, team:Wendigo East

#2908 Issue 2162: prevent sessionCache and sessionDatabase starting together.
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.sessionStore-1.0.0.Database.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.sessionStore-1.0.0.JCache.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionDatabase-1.0/com.ibm.websphere.appserver.sessionDatabase-1.0.feature
Labels: team:Zombie Apocalypse

#2873 1601 config git branch tck
  dev/cnf/gradle/scripts/fat.gradle
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.project
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.config_git_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.config_git_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.config_git_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.config_git_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/ConfigGitTckLauncher.java
  dev/com.ibm.ws.microprofile.config_git_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/servers/ConfigGitTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/servers/ConfigGitTCKServer/server.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/config/test/ArchiveProcessor.java
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/config/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#2967 Issue 2165: Adding Cache verification invalidation tests
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2971 updating monitoring detection for multiserver
  dev/com.ibm.ws.monitor/bnd.bnd
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#2957 management and statistics enablement based on monitoring enablement
  dev/com.ibm.ws.monitor/bnd.bnd
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: team:Zombie Apocalypse

#2959 Ensure that assembleBootstrap task re-runs if the JDK changes
  dev/fattest.simplicity/build.gradle
Labels: CLA Signed, noproductcode

#2953 Publish maven artifact
  dev/build.image/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/wlp-mavenRepoTasks/.classpath
  dev/wlp-mavenRepoTasks/.gitignore
  dev/wlp-mavenRepoTasks/.project
  dev/wlp-mavenRepoTasks/bnd.bnd
  dev/wlp-mavenRepoTasks/pom.xml
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/default.properties
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/LibertyFeature.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/MavenCoordinates.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/MavenRepoGeneratorException.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Constants.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Utils.java
Labels: CLA Signed

#2609 Formlogout ol
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/FormLogoutExtensionProcessor.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/FormLogoutExtensionProcessorTest.java
Labels: CLA Signed

#2985 update dependencies in pom file
  dev/wlp-mavenRepoTasks/pom.xml
Labels: CLA Signed

#2974 Issue #2972: rename ViewHandler DISABLE_FACELET_JSF_VIEWHANDLER property
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ViewHandler.java
Labels: CLA Signed

#2980 test case to add and remove the monitor feature
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Monitor.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#2975 Add FFDCIgnore to WebUtils.validateUriFormat
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/WebUtils.java
Labels: team:Security SSO

#2988 Determine API and SPI dependencies from ESAs
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/utils/Constants.java
Labels: CLA Signed

#2979 fix searchscopeexpression el
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/ELHelper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStoreDefinitionWrapper.java
Labels: CLA Signed

#2844 Add message to nlsprops
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages.nlsprops
Labels: CLA Signed, ID reviewed

#3002 Use platform separator in SpringBoot LibIndexCreateTest (broken on Windows)
  dev/com.ibm.ws.app.manager.springboot/test/com/ibm/ws/app/manager/springboot/util/LibIndexCreateTest.java
Labels: CLA Signed, noproductcode, springboot

#3003 JCASecurityContextService missing doPriv
  dev/com.ibm.ws.jca.inbound.security/src/com/ibm/ws/jca/inbound/security/JCASecurityContextService.java
Labels: CLA Signed, team:Zombie Apocalypse

#3007 Update readme to indicate extra task for building features
  README.md
Labels: CLA Signed, team:Zombie Apocalypse

#3006 Update eclipse settings to get things compiling
  dev/com.ibm.ws.cdi.jndi_fat/.classpath
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableTransactionWeb.war/src/com/ibm/ws/injection/repeatable/transaction/web/RepeatableTransactionTestHelper.java
  dev/wlp-mavenRepoTasks/.settings/bndtools.core.prefs
Labels: CLA Signed, noproductcode

#2998 Change interceptor api dependency to proper versions
  dev/wlp-mavenRepoTasks/pom.xml
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
Labels: CLA Signed

#3008 config update test for scheduled invalidation
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3000 2999 myfaces4221
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/annotation/FacesConfig.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/JsfArtifactProducerExtension.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/el/unified/ResolverBuilderBase.java
Labels: CLA Signed

#2976 Save datasource on DBIDStore when datasourceLookup is set
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStoreDefinitionWrapper.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBTest.java
Labels: CLA Signed, team:Wendigo East

#3005 Issue #3004: Update the com.ibm.ws.security.wim.adapter.urbridge.util…
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMDefaultMessage.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/utils/URBridgeXPathHelper.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/utils/package-info.java
  dev/com.ibm.ws.security.wim.repository_test.custom/src/com/myorg/SampleCustomRepository.java
Labels: CLA Signed, team:Wendigo East

#3013 Update OpenTracing CWMOT0008E Message
  dev/com.ibm.ws.opentracing/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
Labels: CLA Signed, ID reviewed

#3015 Support releaseVersion param. Warn if feature versions do not match.
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
Labels: CLA Signed

#3009 Change JsonPProvider to not use reflection
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/providers/jsonp/JsonPProvider.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
Labels: CLA Signed

#2557 Add sessionCache test for programmatic session timeout adjustment
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3011 remove conversion to null that changes error message
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionObjectFactory.java
Labels: CLA Signed

#3021 Issue #2982: Rename springBootApp config element
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootHandler.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigSpringBootApplicationTagTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/PreThinnedSpringBootTests.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SpringBootApplication.java
Labels: CLA Signed, springboot, team:OSGi Infrastructure

#3020 useInvalidatedId should not be configurable
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#3041 Add issue and pull request templates
  .github/issue_template.md
  .github/pull_request_template.md
Labels: CLA Signed

#3022 Issue 2773: Adding JCache bucket and basic test
  dev/com.ibm.ws.jcache_fat/.classpath
  dev/com.ibm.ws.jcache_fat/.project
  dev/com.ibm.ws.jcache_fat/bnd.bnd
  dev/com.ibm.ws.jcache_fat/build.gradle
  dev/com.ibm.ws.jcache_fat/fat/src/com/ibm/ws/jcache/fat/FATSuite.java
  dev/com.ibm.ws.jcache_fat/fat/src/com/ibm/ws/jcache/fat/JCacheTest.java
  dev/com.ibm.ws.jcache_fat/publish/servers/jcacheContainerServer/bootstrap.properties
  dev/com.ibm.ws.jcache_fat/publish/servers/jcacheContainerServer/server.xml
  dev/com.ibm.ws.jcache_fat/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.jcache_fat/test-applications/jcacheApp/src/jcache/web/JCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#3026 Fix ACE log not generated on j2sec error/warning from com.ibm.jbatch code
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/ACEScanner.java
Labels: CLA Signed, noproductcode

#2989 1507 sso for builtin mechanisms
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/Utils.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/IdentityStoreHandlerServiceImplTest.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStoreDefinitionWrapper.java
  dev/com.ibm.ws.security.javaeesec_fat/.classpath
  dev/com.ibm.ws.security.javaeesec_fat/bnd.bnd
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FormHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormForwardTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormRedirectTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/Constants.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_singleIS/BasicAuthenticationMechanismSingleISTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/form.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/securityContext.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authalias.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.nouser.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.shortname.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ldapidstore.deferred.fat/server.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/ApplicationScopedMechanismWithRequestScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/ApplicationScopedMechanismWithSessionScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/servlets/form/get/forward/FormServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/servlets/form/get/redirect/FormServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuth.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuth.war/resources/login.jsp
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuth.war/src/web/war/formlogin/JavaEEsecFormAuthServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuthRedirect.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuthRedirect.war/resources/login.jsp
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuthRedirect.war/src/web/war/redirectformlogin/JavaEEsecFormAuthRedirectServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/RequestScopedMechanismWithApplicationScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxyTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
Labels: CLA Signed, ID reviewed

#2997 Pull request to add methods to WebUtils
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/config/CommonConfigUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/WebUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/web/WebUtilsTest.java
Labels: CLA Signed

#3037 Pull request for update PostParameterHelper for post body less bytes than content
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/PostParameterHelper.java
Labels: team:Security SSO

#2995 Ensure LTPA operation to use IBMJCE so it won't fail in HWCrypto scenario (PKCS11 provider is configured with high priority)
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPADigSignature.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#3063 Update eclipse files for recent changes.
  dev/com.ibm.websphere.appserver.jwtSsoToken-1.0/.project
  dev/com.ibm.ws.cdi.jndi_fat/.classpath
  dev/com.ibm.ws.jcache_fat/.classpath
  dev/com.ibm.ws.jcache_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jcache_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.metrics/build.gradle
  dev/com.ibm.ws.org.jboss.jandex/build.gradle
  dev/wlp-generateChecksums/.settings/org.eclipse.jdt.core.prefs
  dev/wlp-generateRepositoryContent/.settings/org.eclipse.jdt.core.prefs
  dev/wlp-mavenRepoTasks/.settings/bndtools.core.prefs
  dev/wlp-metatypeValidator/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#3030 Correctly use the provided classloader when creating a Validator
  dev/com.ibm.ws.beanvalidation.v20/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20/src/com/ibm/ws/beanvalidation/v20/ValidatorFactoryBuilderImpl.java
  dev/com.ibm.ws.beanvalidation/src/com/ibm/ws/beanvalidation/OSGiBeanValidationImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#3034 Remove the empty package com.ibm.ws.http.logging.data from com.ibm.ws.logging
  dev/com.ibm.ws.logging/bnd.bnd
  dev/com.ibm.ws.logging/src/com/ibm/ws/http/logging/data/package-info.java
Labels: CLA Signed

#2993 Add common security FAT web response utils class
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/WebResponseUtils.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/package-info.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/web/WebResponseUtilsTest.java
Labels: CLA Signed, team:Security SSO

#3074 fix typo
  .github/pull_request_template.md
Labels: CLA Signed

#3060 add saml slo support
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/FormLogoutExtensionProcessor.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/FormLogoutExtensionProcessorTest.java
Labels: CLA Signed

#3062 Use system.lineSeperator
  dev/com.ibm.ws.cdi.annotations_fat/test-applications/DepProducerApp.war/src/com/ibm/ws/cdi/test/dependentscopedproducer/servlets/MyServlet.java
Labels: CLA Signed, noproductcode

#3054 workaround for session manager stop overlapping deactivate
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#2903 Spring command line
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.springBootHandler-1.0.feature
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringConstants.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootManifest.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityScriptUtils.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
  dev/com.ibm.ws.springboot.utility.springbootutil/.classpath
  dev/com.ibm.ws.springboot.utility.springbootutil/.gitignore
  dev/com.ibm.ws.springboot.utility.springbootutil/.project
  dev/com.ibm.ws.springboot.utility.springbootutil/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.utility.springbootutil/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.springboot.utility.springbootutil/bnd.bnd
  dev/com.ibm.ws.springboot.utility/.classpath
  dev/com.ibm.ws.springboot.utility/.gitignore
  dev/com.ibm.ws.springboot.utility/.project
  dev/com.ibm.ws.springboot.utility/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.utility/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.springboot.utility/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.utility/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.springboot.utility/README
  dev/com.ibm.ws.springboot.utility/bnd.bnd
  dev/com.ibm.ws.springboot.utility/resources/com/ibm/ws/springboot/utility/resources/UtilityMessages.nlsprops
  dev/com.ibm.ws.springboot.utility/resources/com/ibm/ws/springboot/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/IFileUtility.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/SpringBootUtility.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/SpringBootUtilityReturnCodes.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/SpringBootUtilityTask.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/tasks/BaseCommandTask.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/tasks/HelpTask.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/tasks/ThinAppTask.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/utils/CommandUtils.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/utils/ConsoleWrapper.java
  dev/com.ibm.ws.springboot.utility/src/com/ibm/ws/springboot/utility/utils/FileUtility.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/SpringBootUtilityReturnCodesTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/SpringBootUtilityTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/tasks/BaseCommandTaskTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/tasks/HelpTaskTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/tasks/ThinAppTaskTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/utils/ConsoleWrapperTest.java
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/utils/FileUtilityTest.java
Labels: CLA Signed, ID reviewed, springboot

#2813 Update to CXF 3.2.4
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/blueprint/Activator.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.cdi/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/ClientSideMBRW.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyHighPriorityParamConverterProvider.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyHighPriorityThrowableMapper.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyLowPriorityParamConverterProvider.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyObject.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyParam.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/MyParamConverter.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/ProviderPriorityTestApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/ProviderPriorityTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentDeserializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/blueprint/Activator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ConfigurationImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/RequestImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/UriBuilderImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/model/ProviderInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ServerConfigurableFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ExceptionUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/AbstractClient.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/ClientProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/ClientProxyImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientConfigurableImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/spec/ClientRequestFilterInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/MicroProfileClientConfigurableImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/Headers.java
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3077 Changes to get wlp-bndPlugins build to work with clean task
  dev/cnf/bnd.bnd
  dev/cnf/build.gradle
  dev/cnf/gradle/scripts/tasks.gradle
  dev/settings.gradle
  dev/wlp-bndPlugins/build.gradle
Labels: CLA Signed

#3053 Jandex FATs
  dev/com.ibm.ws.anno_fat/.project
  dev/com.ibm.ws.anno_fat/bnd.bnd
  dev/com.ibm.ws.anno_fat/build.gradle
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/FATSuite.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/JandexApplicationHelper.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppDefaultAppMgrDefaultTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppDefaultAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppFalseAppMgrFalseTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppFalseAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppTrueAppMgrFalseTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/jandex/tests/JandexAppTrueAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/publish/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrDefault_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrDefault_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrDefault_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrFalse_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrFalse_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrFalse_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrTrue_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrTrue_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppDefaultAppMgrTrue_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrFalse_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrFalse_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrFalse_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrTrue_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrTrue_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppFalseAppMgrTrue_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrFalse_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrFalse_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrFalse_server/server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrTrue_server/.gitignore
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrTrue_server/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/jandexAppTrueAppMgrTrue_server/server.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/resources/META-INF/jandex.idx
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/src/testservlet40/jar/servlets/ServletContainerInitializerImpl.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/src/testservlet40/jar/servlets/SimpleTestServlet.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/META-INF/jandex.idx
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WebErrorPage.html
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/src/testservlet40/war/servlets/MyServlet.java
Labels: CLA Signed, noproductcode

#3079 Revert "relax checks on adding ejb descriptor"
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
Labels: CLA Signed

#3090 restore bnd plugin to the release version
  dev/gradle.properties
Labels: CLA Signed

#2992 2946 myfaces4203
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/component/UIRepeat.java
Labels: CLA Signed

#3083 Issue #3080- Disable session configuration for spring boot applicatio…
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyServletContainer.java
Labels: CLA Signed, springboot

#3075 Issue #2486: [spring boot feature] Figure out the port for the virtual host
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server/bnd.bnd
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstance.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstanceFactory.java
Labels: CLA Signed, springboot

#3051 Bells config - replacing #3012
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
Labels: CLA Signed

#3072 Remove extra space from bnd symbolic name
  dev/com.ibm.ws.springboot.support.web.server.version15/bnd.bnd
Labels: CLA Signed

#3076 Upload modified feature list to Maven Repo
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
Labels: CLA Signed, noproductcode

#3040 Update the generic types cache to be simpler.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
Labels: CLA Signed

#3028 improve http2 flow control queueing
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2ConnectionSettings.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2MuxTCPWriteCallback.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2WriteTree.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameSettings.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
Labels: CLA Signed

#3097 Update eclipse settings for new components.
  dev/com.ibm.websphere.appserver.jsfContainer-2.3/.project
  dev/com.ibm.ws.anno_fat/.classpath
  dev/com.ibm.ws.anno_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.anno_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jsfContainer.classloading.2.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jsfContainer.classloading.2.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jsfContainer_fat_2.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
Labels: CLA Signed, noproductcode

#2842 2770 - @FormParam fields not being injected in @BeanParam annotated beans due to request body already being read
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#3107 Remove client from IBM-Process-Types for springBoot features
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-1.5/com.ibm.websphere.appserver.springBoot-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-2.0/com.ibm.websphere.appserver.springBoot-2.0.feature
Labels: CLA Signed, springboot, team:OSGi Infrastructure

#3118 config update test to remove sessionCache feature
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: team:Zombie Apocalypse

#3105 Init commit: logger will not delete backup files when 0 is set on max…
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/LoggerOffThread.java
Labels: CLA Signed

#3031 Bruce jwtsso cookie changes
  dev/com.ibm.ws.webcontainer.security/resources/com/ibm/ws/webcontainer/security/resources/WebAppSecurityMessages.nlsprops
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/LoggedOutJwtSsoCookieCache.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/SSOCookieHelperImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/LoggedOutJwtSsoCookieCacheTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/SSOAuthenticatorTest.java
Labels: CLA Signed, ID reviewed

#3109 Add com.ibm.websphere.kernel.server api to kernelCore-1.0.mf file
  dev/com.ibm.ws.kernel.boot/publish/platform/kernelCore-1.0.mf
Labels: CLA Signed, team:Zombie Apocalypse

#3115 Corrected Maven spec dependency versions
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
Labels: CLA Signed

#3119 test infrastructure to capture and read server dump
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: team:Zombie Apocalypse

#2969 return AuthResult.RETURN
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.jaspic/test/com/ibm/ws/security/jaspi/JaspiServiceImplTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/AuthModule.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/BasicAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/DatabaseIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/HttpAuthenticationMechanismDBHashNoConfigTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplCustomTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/ChallengeReply.java
Labels: CLA Signed

#3081 Additional performance improvements found in a few areas.
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed

#3124 Update liberty beta version to 2018.5.0.0
  dev/cnf/resources/bnd/liberty-release.props
Labels: in:Build, team:Zombie Apocalypse

#3135 Don't set app loaders PD from common libs
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/ClassLoaderConfigHelper.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#3143 Use correct array index
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionBinding.java
Labels: CLA Signed

#3114 updating resolver with logging messages
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#3130 Adding post install validate to localEsaInstall
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
Labels: CLA Signed

#3136 Add Extracted apps and loose application support
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/HttpEndpoint.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/KeyStore.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/SSLConfig.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/VirtualHost.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ExtractedAppTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityScriptUtils.java
Labels: CLA Signed, springboot, team:OSGi Infrastructure

#3068 Create CommonFatLoggingUtils class for common security FAT infrastructure
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtils.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/logging/package-info.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtilsTest.java
Labels: team:Security SSO

#3138 Improve parsing of query string performance.
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/RequestUtils.java
Labels: CLA Signed

#3153 Split jaxb-2.2 API+Impl out into a private/internal jaxb feature
  dev/com.ibm.websphere.appserver.features/.gitignore
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
Labels: CLA Signed, team:Zombie Apocalypse

#3148 Move failing test to trace bucket to get a trace the next time it fails.
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
Labels: CLA Signed, noproductcode

#3149 Issue2727 websocket
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/.classpath
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/.gitignore
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/.project
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/src/main/java/com/ibm/ws/springboot/support/version15/test/websocket/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/src/main/java/com/ibm/ws/springboot/support/version15/test/websocket/echo/ServerEchoWebSocketEndpoint.java
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ClientEchoWebSocketEndpoint.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/WebSocketTests15.java
Labels: CLA Signed, in:SpringBoot, team:OSGi Infrastructure

#3131 add basic introspector for session cache feature
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#3133 Ensure that com.ibm.websphere.kernel.server is listed as IBM-API
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appmanager-1.0.feature
Labels: CLA Signed, in:Application Services, team:Wendigo West

#2567 Update test for new message
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigValidator.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
Labels: CLA Signed, noproductcode

#3146 Add doPrivileged blocks in select locations for issue #3073
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/core/SecurityContext.java
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStoreDefinitionWrapper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/ELHelper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStoreDefinitionWrapper.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISCustomForm.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISCustomFormPost.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecUnprotected.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/UnprotectedRememberMe.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModule.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAs.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAsMixed.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAsMixedAppBndXml.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/securityContextHamApp.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionContextImpl.java
Labels: CLA Signed

#3165 Expose JCache API to bundle TCCL
  dev/com.ibm.websphere.javaee.jcache.1.1/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/build.gradle
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer-mphealth/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer-mphealth/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/com.ibm.ws.session.store/src/com/ibm/ws/session/store/common/BackedStore.java
Labels: CLA Signed, bug, team:Zombie Apocalypse

#3112 Issue 3110: Test the push method of PushBuilder from a secured and an…
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderSecurityTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_PushBuilderSecurity/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_PushBuilderSecurity/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderSecurity.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderSecurity.war/resources/images/logo_horizontal_light_navy.png
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderSecurity.war/src/testpushbuildersecurity/war/servlets/PushBuilderSecuredServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderSecurity.war/src/testpushbuildersecurity/war/servlets/PushBuilderUnsecuredServlet.java
Labels: CLA Signed, noproductcode

#3161 add feature manifest generation to assemble task
  dev/com.ibm.websphere.appserver.features/build.gradle
Labels: CLA Signed, noproductcode

#3108 3091 fix ACE in LdapIdentityStoreImpl
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStore.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/CustomIdentityStoreHandlerTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EAREJBModuleTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FormHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplCustomTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplLoginToContinueTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreBasicTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormForwardTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormRedirectTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormForwardTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormRedirectTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/ServerHelper.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/TestHelper.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/ApplicationScopedMechanismWithRequestScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/ApplicationScopedMechanismWithSessionScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/AuthMechs.jar/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseAnnotatedBasicAuthServlet.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/DatabaseIdstoreDeferred.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/IdentityStores.jar/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESec.war/src/web/war/identitystores/custom/grouponly/GroupOnlyIdentityStore200.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleIS.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISCustomForm.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISCustomFormPost.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISForm.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISForm2.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecMultipleISFormPost.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuth.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEEsecFormAuthRedirect.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/RequestScopedMechanismWithApplicationScopedStore.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModule.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModule2.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAs.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAsMixed.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModuleRunAsMixedAppBndXml.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/securitycontextejbinwar.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/securityejbinwar.ear/resources/META-INF/permissions.xml
Labels: CLA Signed, in:Security, team:Core Security

#3144 Exclude testBulkheadMethodAsynchronousRetry55Trip due to issue 2994
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#3166 Issue #2983: Eval config of SpringBootApplication
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigSpringBootApplicationClassloaderTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed, in:SpringBoot, team:OSGi Infrastructure

#3186 Issue 3154: Change FATs to use transportSecurity-1.0
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests20.java
Labels: CLA Signed, in:SpringBoot, noproductcode, team:OSGi Infrastructure

#3188 Revert "add feature manifest generation to assemble task"
  dev/com.ibm.websphere.appserver.features/build.gradle
Labels: CLA Signed, noproductcode

#3187 Cleanup to get eclipse to compile cleanly
  dev/com.ibm.ws.config_fat/.classpath
  dev/com.ibm.ws.javaee.7.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.javaee.7.0_fat/build.gradle
  dev/com.ibm.ws.javaee.7.0_fat/test-applications/simpleWar.war/src/testservlet31/war/servlets/SimpleClassesServlet.java
  dev/com.ibm.ws.javaee.8.0_fat/build.gradle
  dev/com.ibm.ws.javaee.8.0_fat/test-applications/simpleWar.war/src/testservlet40/war/servlets/SimpleClassesServlet.java
  dev/com.ibm.ws.springboot.support.version15.test.websocket.app/bnd.bnd
Labels: CLA Signed

#3092 Check in again JsonTraceService, BaseTraceService Merger + Fixes
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerImpl.java
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
  dev/com.ibm.ws.logging.hpel/test/com/ibm/ws/logging/internal/hpel/HpelLogProviderImplTest.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/CollectorManagerPipelineConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/MessageRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TraceRouterConfigurator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsMessageRouterImpl.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/WsTraceRouterImpl.java
  dev/com.ibm.ws.logging.osgi/test/com/ibm/ws/logging/internal/osgi/WsMessageRouterImplTest.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/LogFieldConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/LogTraceData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/MessageLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/LogSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/source/TraceSource.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/CollectorManagerPipelineUtils.java
  dev/com.ibm.ws.logging_fat/test-bundles/trace.source.handler/src/trace/source/handler/TraceHandlerImpl.java
Labels: CLA Signed

#3185 Update dependency for wmqJmsClient-1.1
  dev/wlp-mavenRepoTasks/resources/featureMavenDependency.xml
Labels: CLA Signed

#3159 Rearrange getCallerQuery on DatabaseIdentityStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
Labels: CLA Signed, team:Wendigo East

#3049 Enable jandex for cdi extension archives
  .gitignore
  dev/com.ibm.ws.cdi.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/ExtensionArchiveImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/RuntimeFactory.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIRuntime.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/WebSphereCDIDeployment.java
  dev/com.ibm.ws.cdi.weld/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
Labels: CLA Signed

#3203 Add hashtable before the setCredential call for CertificateLoginModule
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/CertificateLoginModule.java
Labels: CLA Signed

#3206 Fix for issue 3176 - mark Spring Boot features for beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBoot15ServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBoot20ServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.springBootServerSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.springBootHandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-1.5/com.ibm.websphere.appserver.springBoot-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-2.0/com.ibm.websphere.appserver.springBoot-2.0.feature
Labels: CLA Signed, in:SpringBoot

#3150 Move refs to legacy and upgrade
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.ws.org.apache.commons.fileupload.1.2.1/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.fileupload/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.fileupload/src/org/apache/commons/fileupload/FileUploadBase.java
  dev/com.ibm.ws.org.apache.commons.fileupload/src/org/apache/commons/fileupload/MultipartStream.java
  dev/com.ibm.ws.org.apache.commons.io.1.4/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io.2.4/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io/bnd.bnd
  dev/com.ibm.ws.persistence_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler/bnd.bnd
  dev/com.ibm.ws.security.utility.securityutil/bnd.bnd
  dev/com.ibm.ws.security.utility/bnd.bnd
  dev/com.ibm.ws.springboot.utility.springbootutil/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.utility/bnd.bnd
Labels: CLA Signed

#3182 config update to session cache fileset
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#3175 minimal set of changes from Andy's #2963 in order to enable lazy init of JCache provider and cache manager
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: team:Zombie Apocalypse

#3155 Create well-known Expectation classes for security FAT infra
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectation.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonExpectationTestClass.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonSpecificExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ExpectationsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtilsTest.java
Labels: CLA Signed

#3193 Use servlet-3.1 feature for tests
  dev/com.ibm.ws.messaging.open_fat/publish/servers/FATJmsServer/server.xml
Labels: CLA Signed, noproductcode

#3210 Separate Open and WebSphere Liberty maven zips
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java
  dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/model/LibertyFeature.java
Labels: CLA Signed

#3202 increase jwtsso logged out cookie cache size to 10000 and enable cache by default
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/LoggedOutJwtSsoCookieCache.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/LoggedOutJwtSsoCookieCacheTest.java
Labels: CLA Signed

#3217 Add TestValidationUtils class to common security FAT infra
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/validation/TestValidationUtils.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/validation/package-info.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/validation/TestValidationUtilsTest.java
Labels: team:Security SSO

#3191 Fixes issues 2826, 3168 and 3147
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/VirtualHost.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringConstants.java
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyServletContainer.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigSpringBootApplicationWithArgsTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ExtractedAppTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/WarmStartTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
  dev/com.ibm.ws.springboot.utility/resources/com/ibm/ws/springboot/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.springboot.utility/test/com/ibm/ws/springboot/utility/tasks/ThinAppTaskTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SpringBootApplication.java
Labels: CLA Signed, ID reviewed, in:SpringBoot

#3225 obtain info from cache mxbeans to use in introspector
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#3216 Add support for variable list expressions
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigConstants.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
Labels: CLA Signed

#3215 Add new edtion and product id for Open Liberty
  dev/cnf/resources/bnd/feature.props
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/ParserBase.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/AppliesToProcessor.java
  dev/com.ibm.ws.repository/test/com/ibm/ws/repository/resources/internal/test/AppliesToProcessorTest.java
Labels: CLA Signed

#3212 Don't run the asserts on an excpetion if we see WELD-001210
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EnablingBeansXmlValidationTest.java
Labels: CLA Signed, noproductcode

#3237 update testMXBeansEnabled so that it does not rely on immediate update of stats
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: team:Zombie Apocalypse

#3222 Implement validate methods in security FAT Expectation classes
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectation.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/WebResponseUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/CommonSpecificExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/JsonObjectExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseFullExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseHeaderExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseMessageExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseStatusExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseTitleExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectationTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/logging/CommonFatLoggingUtilsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/test/UnitTestUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/validation/TestValidationUtilsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/web/WebResponseUtilsTest.java
  dev/com.ibm.ws.security.test.common/src/com/ibm/ws/security/test/common/CommonTestClass.java
Labels: CLA Signed, team:Security SSO

#3239 Test that timed invokeAll does not run tasks on submitter's thread
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: team:Zombie Apocalypse

#3178 adding debug stacktrace info
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#3242 Issue 3241: Additional tests for the HttpServletMapping when using Se…
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCGetMappingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestGetMapping.war/src/testgetmapping/war/servlets/GetMappingNamedDispatcherFwdServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestGetMapping.war/src/testgetmapping/war/servlets/GetMappingNamedDispatcherIncServlet.java
Labels: CLA Signed, noproductcode

#3231 Issue #3226: Fix NullPointerException in EJSContainer when runUnderUOW
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSContainer.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSDeployedSupport.java
  dev/com.ibm.ws.ejbcontainer.tx_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.tx_fat/.gitignore
  dev/com.ibm.ws.ejbcontainer.tx_fat/.project
  dev/com.ibm.ws.ejbcontainer.tx_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.tx_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.ejbcontainer.tx_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ejbcontainer.tx_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.ejbcontainer.tx_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.tx_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.tx_fat/fat/src/com/ibm/ws/ejbcontainer/tx/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.tx_fat/fat/src/com/ibm/ws/ejbcontainer/tx/fat/RunUnderUOWTest.java
  dev/com.ibm.ws.ejbcontainer.tx_fat/publish/servers/com.ibm.ws.ejbcontainer.tx.fat.RunUnderUOWServer/.gitignore
  dev/com.ibm.ws.ejbcontainer.tx_fat/publish/servers/com.ibm.ws.ejbcontainer.tx.fat.RunUnderUOWServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.tx_fat/publish/servers/com.ibm.ws.ejbcontainer.tx.fat.RunUnderUOWServer/server.xml
  dev/com.ibm.ws.ejbcontainer.tx_fat/test-applications/RunUnderUOWBean.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.tx_fat/test-applications/RunUnderUOWBean.jar/src/com/ibm/ws/ejbcontainer/tx/rununderuow/ejb/RunUnderUOWBMTBean.java
  dev/com.ibm.ws.ejbcontainer.tx_fat/test-applications/RunUnderUOWBean.jar/src/com/ibm/ws/ejbcontainer/tx/rununderuow/ejb/RunUnderUOWCMTBean.java
  dev/com.ibm.ws.ejbcontainer.tx_fat/test-applications/RunUnderUOWWeb.war/src/com/ibm/ws/ejbcontainer/tx/rununderuow/web/RunUnderUOWServlet.java
Labels: CLA Signed

#3254 Changed WasLoggingUtil to LoggingUtil.
  dev/com.ibm.ws.session.store/src/com/ibm/ws/session/store/common/BackedStore.java
Labels: CLA Signed

#3234 Close Streams after reading and writing
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/SingleFileClient.java
Labels: CLA Signed

#3199 3198 avoid full deserialization in ObjectMessage.toString()
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsObjectMessageImpl.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/JmsObjectMessageTests.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/TestLocalJmsServlet.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/TestRemoteJmsServlet.java
  dev/com.ibm.ws.messaging.open_fat/test-applications/testjms/src/testjms/web/impl/JmsObjectMessageTestsImpl.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ws/sib/utils/SerializedObjectInfoHelper.java
Labels: CLA Signed

#3228 Issue3043-multiple spring boot apps
  dev/com.ibm.ws.app.manager.springboot/resources/com/ibm/ws/app/manager/springboot/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootHandler.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MultipleApplicationsNotSupported.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot15FeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot20FeatureTests.java
Labels: CLA Signed, ID reviewed

#3243 Create CommonSecurityFat class
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonSecurityFat.java
Labels: CLA Signed, team:Security SSO

#3249 Initial commit for Http/2 configuration tests
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2ConfigTests.java
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.off/.gitignore
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.off/bootstrap.properties
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.off/server.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.on/.gitignore
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.on/bootstrap.properties
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet31.h2.on/server.xml
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet40.h2.off/.gitignore
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet40.h2.off/bootstrap.properties
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.servlet40.h2.off/server.xml
Labels: CLA Signed, noproductcode

#3204 Updating MP Metrics from 1.1 to 1.1.1
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-1.1.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.gitignore
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.1.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/Metrics, team:Lumberjack

#3223 http2 frame buffer changes and flow control improvements
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/connection/H2Connection.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/frames/FrameSettingsClient.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/Frame.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameContinuation.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameData.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameGoAway.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameHeaders.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePing.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePriority.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FramePushPromise.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameRstStream.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameSettings.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameUnknown.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/frames/FrameWindowUpdate.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: CLA Signed

#3265 missing derby permissions for concurrent_fat_db
  dev/com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse
