Repository OpenLiberty/open-liberty, pull requests merged in 2019-01, with the labels that each got.

#6093 CompletableFuture unaware of executor shutdown and other abort paths
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletionStage.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyTaskFutureImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6096 Reapply "Dump and restore output streams between unit tests""
  dev/com.ibm.ws.junit.extensions/src/test/common/SharedOutputManager.java
Labels: CLA Signed, team:Continuous Delivery

#6072 Issue #6020 : fix win service description in server.bat
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed, release bug

#6099 Add cnf:checkForUpdates task to check for artifact updates on Maven Central
  dev/cnf/build.gradle
Labels: CLA Signed, in:Build, noproductcode, team:Zombie Apocalypse

#6107 Create FAT test case for jwtSso and mpJwt problem with subject creation
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
Labels: CLA Signed, noproductcode, team:Security SSO

#6101 Added timestampFormat to ldapRegistry
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed

#6117 create new test application/server instance for testing MP Config overrides of MP Concurrency
  dev/com.ibm.ws.concurrent.mp_fat/.classpath
  dev/com.ibm.ws.concurrent.mp_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentConfigTest.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentConfigTestServer/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentConfigTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/ConcurrencyBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/ConcurrencyConfigBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6035 Ensure dynamic source polling tasks are cleaned up
  dev/com.ibm.ws.microprofile.config/.classpath
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/AbstractProviderResolver.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/classloader/test/ConfigCacheTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/dynamic/test/DynamicSourceCleanupTest.java
  dev/com.ibm.ws.microprofile.config/test/src/com/ibm/ws/microprofile/config/dynamic/test/TestDynamicConfigSource.java
  dev/com.ibm.ws.microprofile.config_fat/test-applications/dynamicSources.war/src/com/ibm/ws/microprofile/appConfig/dynamicSources/test/DynamicSourcesTestServlet.java
  dev/com.ibm.ws.microprofile.config_fat/test-applications/dynamicSources.war/src/com/ibm/ws/microprofile/appConfig/dynamicSources/test/MySource.java
Labels: CLA Signed

#6112 Fix for Issue #6032: Add new JAX-RS tests to test async Timeouts with InvocationCallback
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6100 trackLoggedOutCookies setting cause multiple login failure
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
Labels: CLA Signed

#5983 5785-orbssltimeout2-commit1
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.iiop/resources/OSGI-INF/metatype/metatype.xml
Labels: release bug

#6111 Updated AttributeCache and SearchCache Times
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/VMMAPIs_EmbeddedLdapTests.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#5889 Test aggregator
  dev/build.gradle
Labels: CLA Signed, noproductcode

#6122 fix a Java 11 build break with the jaxb-2.3 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.3/com.ibm.websphere.appserver.jaxb-2.3.feature
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#5808 Updates to reduce CPU and memory during startup.
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/wsspi/channelfw/objectpool/LocalThreadObjectPool.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/MetaTypeRegistry.java
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/jacc/EJBJaccAuthorizationHelper.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapManifest.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/BootstrapChildFirstJarClassloader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/BootstrapChildFirstURLClassloader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/DirectoryResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarFileClassLoader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/ResourceEntry.java
  dev/com.ibm.ws.kernel.security.thread/src/com/ibm/ws/kernel/security/thread/ThreadIdentityManager.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/PathUtils.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/TimestampUtils.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/logging/hpel/LogRecordContext.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/TraceComponent.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/BurstDateFormat.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/DateFormatHelper.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpLocalFormat.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed

#6119 Add period to explanation messages
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages.nlsprops
Labels: CLA Signed

#6086 Filter out MP Rest Client interfaces from MP OpenAPI view
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/AnnotationScanner.java
Labels: CLA Signed, team:Zombie Apocalypse

#6085 Upgrade javaMail-1.5 to use API v1.5.6 and IMPL v.1.5.9
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.5/com.ibm.websphere.appserver.javaMail-1.5.feature
  dev/com.ibm.websphere.appserver.thirdparty.mail/bnd.bnd
  dev/com.ibm.websphere.javaee.mail.1.5/bnd.bnd
  dev/com.ibm.ws.clientcontainer.javamail_fat/bnd.bnd
  dev/com.ibm.ws.clientcontainer.javamail_fat/build.gradle
  dev/com.ibm.ws.com.sun.mail.javax.mail/bnd.bnd
  dev/com.ibm.ws.com.sun.mail.javax.mail/bnd.overrides
  dev/com.ibm.ws.javamail.1.6_fat/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
Labels: CLA Signed, team:Zombie Apocalypse

#6110 1. Sanitizing metric names to prevent illegal Prometheus characters s…
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetrics.java
Labels: CLA Signed

#6116 Update MP Concurrency impl to produce a unique ManagedExecutor per @Default injection point
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.concurrency.1.0/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyProviderImpl.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ManagedExecutorBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/ConcurrencyBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MyQualifier.java
Labels: CLA Signed, team:Zombie Apocalypse

#6103 PR to Pull MYFACES-4251
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/Application.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ApplicationWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ConfigurableNavigationHandlerWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/NavigationHandler.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIData.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIGraphic.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIImportConstants.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIViewAction.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIViewParameter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UISelectItem.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UISelectItems.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UIWebsocket.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/behavior/BehaviorBase.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/PartialResponseWriter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/convert/EnumConverter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/ComponentSystemEventListener.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/SystemEventListener.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/BeanValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/RequiredValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/DelegatingMetaTagHandler.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/Facelet.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/FaceletContext.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/webapp/AttributeTag.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/webapp/UIComponentELTag.java
Labels: CLA Signed, in:Web Components, team:Sirius

#5993 Add java vendor
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/LibertyProcessImpl.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/krb5/Krb5Common.java
Labels: CLA Signed

#6126 MicroProfile Config overrides int attribute of ManagedExecutorConfig
  dev/com.ibm.ws.concurrent.mp.cdi/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/MPConfigAccessor.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/MPConfigAccessorImpl.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ManagedExecutorBean.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentConfigTestServer/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/ConcurrencyConfigBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#6142 fix Java 11 build break in Jaxb-2.3 FAT
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.3/com.ibm.websphere.appserver.jaxb-2.3.feature
  dev/com.ibm.ws.jaxb_fat/test-applications/jaxbApp/src/jaxb/web/JAXBTestServlet.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#6151 Update LDAPUtils to never set null property values
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#6130 Add report for publish
  dev/build.gradle
  dev/build.image/build.gradle
Labels: CLA Signed

#6157 Allow MP Config to override ManagedExecutor injection points which are method parameters
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/ConcurrencyConfigBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#6162 Update Guava to 27.0.1-android for Java 7 support
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.com.google.guava.26.0/bnd.bnd
  dev/com.ibm.ws.com.google.guava.26.0/bnd.overrides
Labels: CLA Signed, team:Security SSO

#6124 issue #6073 : Fix ZipArchive and add new tests for loose app
  dev/com.ibm.ws.kernel.boot.archive/src/com/ibm/ws/kernel/boot/archive/internal/ZipArchive.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessorUtils.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/apps/AppsLooseWeb.war.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/earContent/META-INF/application.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testUtil/classes/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testUtil/classes/META-INF/MANIFEST.MF
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb0/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb0/WebContent/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb0/WebContent/META-INF/MANIFEST.MF
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb0/WebContent/index.jsp
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb1/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb1/WebContent/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb1/WebContent/META-INF/MANIFEST.MF
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/testWeb1/WebContent/index.jsp
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/utils/classes/.gitignore
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.root.fat/looseConfig/utils/classes/META-INF/MANIFEST.MF
Labels: CLA Signed, release bug

#6121 Update OIDC RP certification tests to run in full mode
  dev/com.ibm.ws.security.fat.common.social/src/com/ibm/ws/security/fat/common/social/oidc/certification/OidcCertificationRPBasicProfileTests.java
  dev/com.ibm.ws.security.social_fat.oidcCertification/fat/src/com/ibm/ws/security/social/fat/oidc/certification/SocialOidcCertificationRPBasicProfileTests.java
Labels: CLA Signed, team:Security SSO

#6163 Updating wiremock plugin version.
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#6149 FT 2.0 CompletionStage new semantics
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncCompletionStageExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageTest.java
Labels: CLA Signed

#6153 Propagate NamingException when enumerating through JNDI bindings
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/WSNamingEnumeration.java
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/WSContext.java
Labels: CLA Signed

#6166 Add fault tolerance 2.0 metrics
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics.feature
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncCompletionStageExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncFutureExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/ExecutorBuilderImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/SyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/FaultToleranceStateFactory.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/AsyncBulkheadStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/CircuitBreakerStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/RetryStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/SyncBulkheadStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/CircuitBreakerStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/RetryStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/SyncBulkheadStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImplTest.java
Labels: CLA Signed

#6169 avoid repeatedly resolving MPConfig
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/MPConfigAccessor.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/MPConfigAccessorImpl.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ManagedExecutorBean.java
Labels: CLA Signed, team:Zombie Apocalypse

#6171 Issue #6148 - use BSN where version contains special chars
  dev/com.ibm.websphere.javaee.jaxb.2.2/bnd.bnd
Labels: CLA Signed

#6177 add db applicsaion to the wait list
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleTestUnprotectedServlet.java
Labels: CLA Signed, in:Security, noproductcode, team:Core Security, test bug

#6170 Issue 6106 pt2: Improve logging performance
  dev/com.ibm.ws.jpa.container.eclipselink/src/com/ibm/ws/jpa/container/eclipselink/logging/EclipseLinkLogger.java
Labels: CLA Signed

#6184 Use in memory derby for injection_fat
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDSingletonBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDStatefulBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDMixEJB.jar/src/com/ibm/ws/injection/dsdmix/ejb/DSDMixedBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/DSDXMLEJB.jar/src/com/ibm/ws/injection/dsdxml/ejb/DSDStatelessBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDAnnEJB.jar/src/com/ibm/ws/injection/repeatable/dsdann/ejb/RepeatableDSDStatefulBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDMixEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDMixEJB.jar/src/com/ibm/ws/injection/repeatable/dsdmix/ejb/RepeatableDSDMixedBean.java
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDXMLEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.injection_fat/test-applications/RepeatableDSDXMLEJB.jar/src/com/ibm/ws/injection/repeatable/dsdxml/ejb/RepeatableDSDStatelessBean.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test debt

#6150 Update copyright year to 2019
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Continuous Delivery

#6202 Revert "5785-orbssltimeout2-commit1"
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.iiop/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#6109 minimum pool size 4
  dev/com.ibm.ws.threading/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
  dev/com.ibm.ws.threading/test/com/ibm/ws/threading/internal/PolicyExecutorTest.java
Labels: CLA Signed

#6132 Add trace to EmbeddedApacheDS class
  dev/com.ibm.ws.org.apache.directory.server/bnd.bnd
  dev/com.ibm.ws.org.apache.directory.server/src/com/ibm/ws/apacheds/EmbeddedApacheDS.java
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
Labels: CLA Signed, team:Wendigo East

#6208 increase timeout to allow for transaction recovery init
  dev/com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#6078 Issue 6075: Add new 'eclipselink.jdbc.force-bind-parameters' property
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
Labels: CLA Signed

#6156 Ignore config when using Oracle UCP
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/AbstractConnectionFactoryService.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/service/ConnectionFactoryService.java
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/DSConfig.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Zombie Apocalypse

#6213 Revert "Issue 6075: Add new 'eclipselink.jdbc.force-bind-parameters' property"
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
Labels: CLA Signed

#5288 Add zips to maven publish
  dev/build.image/build.gradle
Labels: CLA Signed

#6164 remove com.ibm.ws.cds
  dev/com.ibm.ws.cds/.classpath
  dev/com.ibm.ws.cds/.gitignore
  dev/com.ibm.ws.cds/.project
  dev/com.ibm.ws.cds/.settings/bndtools.core.prefs
  dev/com.ibm.ws.cds/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.cds/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cds/bnd.bnd
  dev/com.ibm.ws.cds/build.gradle
  dev/com.ibm.ws.cds/build.xml
  dev/com.ibm.ws.cds/lib/com.ibm.cds_3.0.1.201410101357.jar
  dev/com.ibm.ws.kernel.boot/publish/platform/kernelCore-1.0.mf
Labels: CLA Signed

#6172 More updates for social discovery, messages and configuration
  dev/com.ibm.ws.security.common/resources/com/ibm/ws/security/common/internal/resources/SSOCommonMessages.nlsprops
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/config/DiscoveryConfigUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/GoogleLoginConfigImplTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/OidcLoginConfigImplTest.java
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#6219 Notices Update for 19001
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#6218 Check for openJ9 to allow TLSv1.3
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/JavaInfo.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ids.ssl/jvm.options
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/jvm.options
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.ssl/jvm.options
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed

#6216 Move FireOnEventListenerVisitor classes inside a parent to help prevent compilation issues
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/FireOnEventListenerVisitors.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppEventSource.java
Labels: CLA Signed, team:MicroProfileUK

#6180 FT 2.0 set priority dynamically
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi2.0.feature
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.project
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/src/com/ibm/ws/microprofile/faulttolerance/cdi20/FaultToleranceCDI20Extension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/src/com/ibm/ws/microprofile/faulttolerance/cdi20/FaultToleranceCDI20Interceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi.2.0/src/com/ibm/ws/microprofile/faulttolerance/cdi20/package-info.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
Labels: CLA Signed

#6239 Only disable TLSv1.3 on Oracle
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed

#6160 Return more comprehensive error stack for timestamp
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
Labels: CLA Signed

#6243 jwtsso feature should expose mp jwt api
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
Labels: CLA Signed, team:Security SSO

#6240 Split com.ibm.ws.security.javaeesec_fat project.
  dev/com.ibm.ws.security.javaeesec_fat.2/.classpath
  dev/com.ibm.ws.security.javaeesec_fat.2/.gitignore
  dev/com.ibm.ws.security.javaeesec_fat.2/.project
  dev/com.ibm.ws.security.javaeesec_fat.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.javaeesec_fat.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.javaeesec_fat.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.javaeesec_fat.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.javaeesec_fat.2/bnd.bnd
  dev/com.ibm.ws.security.javaeesec_fat.2/build.gradle
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/CustomIdentityStoreHandlerTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleRealmTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/FATSuite.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleDBRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertFailOverTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/NoIdentityStoreTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/SSOTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/ScopedTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextEJBTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextJaxRSTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/readme.txt
  dev/com.ibm.ws.security.javaeesec_fat/build/features/jaspicUserTestFeature-1.0.mf
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleTestProtectedServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleTestUnprotectedServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FATSuite.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FeatureTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FormHttpAuthenticationMechanismTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplCustomTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreApplLoginToContinueTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreBasicTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreFormTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleNoExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/ServerHelper.java
Labels: CLA Signed, in:Security, noproductcode, team:Core Security, test bug

#6236 Issue #5472 - check OSGi Framework state
  dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/archaius/composite/PollingDynamicConfig.java
Labels: CLA Signed

#6215 Change expanded apps dir to be under wlp_output_dir
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/DeployedAppInfoFactoryBase.java
Labels: CLA Signed, release bug

#6235 Issue 6106: Fix EclipseLink null channel bug
  dev/com.ibm.ws.jpa.container.eclipselink/src/com/ibm/ws/jpa/container/eclipselink/logging/LogChannel.java
Labels: CLA Signed

#6257 PII NLS Returns from 19001 Shipment 2
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_cs.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_es.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_hu.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_it.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_ko.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_pl.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_pt_BR.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_ro.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_ru.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_zh.nlsprops
  dev/com.ibm.ws.logging.osgi/resources/com/ibm/ws/logging/internal/osgi/resources/OSGiMessages_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed

#6252 minor message update
  dev/com.ibm.ws.kernel.instrument.serialfilter.serverconfig/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, L2 ReviewNotRequiered, in:Security, team:Core Security

#6271 Move plugins to top of build.gradle
  dev/com.ibm.ws.kernel.instrument.serialfilter.premain/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/build.gradle
Labels: CLA Signed, noproductcode

#6253 Issue #6206: Update the getUsersForMaxSearchResultException test actu…
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADLDAPTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#6244 1. When setting level for TraceComponent, current implementation is n…
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/TraceComponent.java
  dev/com.ibm.ws.logging_test/test/com/ibm/websphere/ras/TraceComponentTest.java
Labels: release bug

#6290 Do not reference project in .classpath. Just rely on bnd to find it.
  dev/com.ibm.ws.security.javaeesec_fat.2/.classpath
Labels: CLA Signed, noproductcode

#6247 Disabled getUserRemoveAttributeTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/VMMAPIs_EmbeddedLdapTests.java
Labels: CLA Signed, noproductcode

#6277 clear cached classloaders when application is stopped
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyProviderImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6181 Add Java 11 to feature list
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
Labels: CLA Signed, team:Zombie Apocalypse

#6191 fix incomplete SRVE0279E message
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#6275 Fix for Issue #5405: increase margin of error
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6265 Fix for Issue #6264: JAXRS20ClientAsyncInvokerTest to ignore the javax.ws.rs.ProcessingException FFDC
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6210 test build break on mac
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/ELHelper.java
Labels: CLA Signed

#6289 Test that CDI Interceptors are invoked on JAX-RS resources and providers
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/InterceptorTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.interceptor/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.interceptor/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.interceptor/server.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/src/com/ibm/ws/jaxrs20/cdi12/fat/interceptor/App.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/src/com/ibm/ws/jaxrs20/cdi12/fat/interceptor/Filter.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/src/com/ibm/ws/jaxrs20/cdi12/fat/interceptor/Loggable.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/src/com/ibm/ws/jaxrs20/cdi12/fat/interceptor/LoggableInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/interceptor/src/com/ibm/ws/jaxrs20/cdi12/fat/interceptor/Resource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#5904 Issue 4975: Destroy of aborted connections and removal from the pool
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/LocalTransactionWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/XATransactionWrapper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/JDBC43Test.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/d43driver/src/org/test/d43/jdbc/D43Handler.java
Labels: CLA Signed, team:Zombie Apocalypse

#6296 Update WebContainer.getCacheManager() to avoid NullPointerException
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed

#6260 Only zip maven artifacts on release builds
  dev/build.image/build.gradle
Labels: CLA Signed

#6299 Correct the DHE maven repo location
  dev/cnf/build.bnd
Labels: CLA Signed

#6301 New jwtsso cookie name api
  dev/com.ibm.websphere.appserver.api.webcontainer.security.app/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.webAppSecurity-1.0.feature
  dev/com.ibm.ws.webcontainer.security.app/build-api-spi.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/WebSecurityHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/package-info.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/websphere/security/web/WebSecurityHelperTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelperTestHelper.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImplTest.java
Labels: CLA Signed, team:Security SSO

#6269 New implementation of AsyncBulkheadState
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncCompletionStageExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncFutureExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/ExecutorBuilderImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/AsyncBulkheadState.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/FaultToleranceStateFactory.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/AsyncBulkheadStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/AsyncBulkheadStateNullImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/AsyncBulkheadStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/MockRejectingExecutor.java
Labels: CLA Signed

#6259 Additional init trace for embedded ApacheDS
  dev/com.ibm.ws.org.apache.directory.server/src/com/ibm/ws/apacheds/EmbeddedApacheDS.java
Labels: team:Wendigo East

#6276 Issue 6273: Avoid clearing runtime contexts in client requests
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/ContextAndClientTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandclient/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandclient/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandclient/server.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandclient/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandclient/App.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandclient/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandclient/Client.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandclient/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandclient/LocalResource.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/ClientContextInjectionTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/clientcontextinjection/src/com/ibm/ws/jaxrs20/client/ClientContextInjectionTest/client/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/clientcontextinjection/src/com/ibm/ws/jaxrs20/client/ClientContextInjectionTest/service/Resource.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/HttpServletRequestInjectionProxy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#6308 Test 202 response
  dev/com.ibm.ws.jaxrs.2.0.client_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/HandleResponsesTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.HandleResponsesTest/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.HandleResponsesTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.HandleResponsesTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/handleresponses/src/com/ibm/ws/jaxrs20/client/HandleResponsesTest/client/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/handleresponses/src/com/ibm/ws/jaxrs20/client/HandleResponsesTest/service/Resource.java
  dev/com.ibm.ws.microprofile.rest.client_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.handleresponses/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.handleresponses/resources/security/key.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.handleresponses/resources/security/trust.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.handleresponses/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicRemoteApp/src/remoteApp/basic/BasicService.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/ClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/HandleResponsesClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/UnknownWidgetException.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/UnknownWidgetExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/Widget.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6311 implement toString for ManagedExecutor and ThreadContext
  dev/com.ibm.ws.concurrent.mp.1.0/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/service/ConcurrencyCDIHelper.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/service/package-info.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#5593 Increment bnd version to 4.1.0
  dev/cnf/build.gradle
  dev/cnf/gradle/scripts/anttaskdefs.bnd
  dev/cnf/oss_dependencies.maven
  dev/cnf/resources/bnd/app-resources.bnd
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.ws.bnd.annotations/bnd.bnd
  dev/com.ibm.ws.cdi.1.2.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.javamail.1.6/bnd.bnd
  dev/com.ibm.ws.javamail/bnd.bnd
  dev/com.ibm.ws.jaxb.tools.2.3/bnd.bnd
  dev/com.ibm.ws.jaxb.tools.2.3/jaxb-tools.bnd
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb-tools.bnd
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.jsonp_fat/custom.jsonp.bnd
  dev/com.ibm.ws.logging.hpel/bnd.bnd
  dev/com.ibm.ws.org.apache.bval.1.1.0/bnd.bnd
  dev/com.ibm.ws.org.apache.bval.1.1.0/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-rt-frontend-jaxws.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.wsoc/bnd.bnd
  dev/gradle.properties
  dev/wlp-bndPlugins/bnd.bnd
  dev/wlp-featureTasks/bnd.bnd
Labels: CLA Signed, team:Continuous Delivery

#6144 SAF Authentication Failure Auditing
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditConstants.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/Audit.java
Labels: CLA Signed

#6318 Increase the timeout of testMultiRequestBulkhead
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIBulkheadTest.java
Labels: CLA Signed, noproductcode

#6315 tests for security context
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentConfigTest.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentConfigTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/ConcurrencyConfigBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#4197 Allow setting JVM options on server start command
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartJVMOptionsTest.java
Labels: CLA Signed, in:Kernel/Bootstrap, team:Zombie Apocalypse

#5591 Move jdbc-4.3 feature from BETA to GA
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.3/com.ibm.websphere.appserver.jdbc-4.3.feature
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/EsaParser.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6294 withContextCapture must reject Async actions without an executor
  dev/com.ibm.ws.concurrent.mp.1.0/resources/com/ibm/ws/concurrent/mp/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/UnusableExecutor.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/context/TransactionContextProvider.java
  dev/com.ibm.ws.concurrent.mp.cdi/resources/com/ibm/ws/concurrent/mp/cdi/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ConcurrencyCDIExtension.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/package-info.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextProviderImpl.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Zombie Apocalypse

#6288 Add the missing default value of the remoteIp proxies attribute in th…
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, in:Web Components, team:Sirius

#6324 Changed cardinality of defaultParent
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#6320 re-enable archive weaving
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/reactive/streams/operators/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/reactive/streams/operators/test/ReactiveStreamsArchiveProcessor.java
Labels: CLA Signed, noproductcode

#6342 Updates to eclipse settings and copyrights.
  dev/com.ibm.ws.collector/.settings/bndtools.core.prefs
  dev/com.ibm.ws.collector/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.collector/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.request.probe.audit.servlet/.classpath
  dev/com.ibm.ws.request.probe.audit.servlet/.classpath.gradle
  dev/com.ibm.ws.request.probe.audit.servlet/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.file/.classpath
  dev/com.ibm.ws.security.audit.file/.classpath.gradle
  dev/com.ibm.ws.security.audit.file/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.file/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.audit.file/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.audit.reader.auditreader/.classpath
  dev/com.ibm.ws.security.audit.reader.auditreader/.classpath.gradle
  dev/com.ibm.ws.security.audit.reader.auditreader/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.reader.auditreader/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.audit.reader.auditreader/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.audit.reader/.classpath
  dev/com.ibm.ws.security.audit.reader/.classpath.gradle
  dev/com.ibm.ws.security.audit.reader/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.reader/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.audit.reader/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.audit.reader/bnd.bnd
  dev/com.ibm.ws.security.audit.source/.classpath
  dev/com.ibm.ws.security.audit.source/.classpath.gradle
  dev/com.ibm.ws.security.audit.source/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.source/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.audit.source/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/SimpleFS2PCCloudTest.java
Labels: CLA Signed

#6333 Reduce Page Size on Search Paging Test
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/SearchPagingTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#6330 Pull in Microprofile Fault Tolerance 2.0 API
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.0/com.ibm.websphere.appserver.mpFaultTolerance-2.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/.gitignore
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
Labels: CLA Signed

#6322 4946 tck repeat
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/config13/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FATSuite.java
Labels: CLA Signed, noproductcode

#6367 Correct comment
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/reactive/streams/operators/test/ReactiveStreamsArchiveProcessor.java
Labels: CLA Signed, noproductcode
