Repository OpenLiberty/open-liberty, pull requests merged in 2019-11, with the labels that each got.

#9586 Clean up MP Config when app fails to start
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractProviderResolver.java
Labels: CLA Signed

#9594 Increasing timeout for DB2 container
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9580 enable main test bucket for for Infinispan 10.0.0.Final
  dev/com.ibm.ws.session.cache_fat_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9562 Port com.ibm.ws.event.logging_fat to OL
  dev/com.ibm.ws.event.logging_fat/.classpath
  dev/com.ibm.ws.event.logging_fat/.project
  dev/com.ibm.ws.event.logging_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.event.logging_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.event.logging_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.event.logging_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.event.logging_fat/bnd.bnd
  dev/com.ibm.ws.event.logging_fat/build.gradle
  dev/com.ibm.ws.event.logging_fat/delivery.sets
  dev/com.ibm.ws.event.logging_fat/fat/src/com/ibm/ws/event/logging/FATTest.java
  dev/com.ibm.ws.event.logging_fat/publish/files/server_NOeventLogging.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_NoContextInfo.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_TrueContextInfo.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_eventLogging_original.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_eventTypes.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_eventTypes2.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_logModeEntry.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_logModeEntryExit.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_logModeExit.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_minDuration.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_minDuration2.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_minDuration3.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_removeElement.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_sampleRate.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_sampleRate0.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_sampleRate3.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_sampleRate4.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_sampleRatetemp.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_updateAll.xml
  dev/com.ibm.ws.event.logging_fat/publish/files/server_updateAllsample.xml
  dev/com.ibm.ws.event.logging_fat/publish/servers/EventLoggingServer/bootstrap.properties
  dev/com.ibm.ws.event.logging_fat/publish/servers/EventLoggingServer/server.xml
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/resources/.gitignore
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/src/com/ibm/ws/request/timing/Login1.java
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/src/com/ibm/ws/request/timing/Login2.java
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/src/com/ibm/ws/request/timing/Stock.java
  dev/com.ibm.ws.event.logging_fat/test-applications/jdbcTestPrj_1/src/com/ibm/ws/request/timing/TestJDBC.java
Labels: CLA Signed, noproductcode

#9464 9384 Adding processCpuTime metric to 2.0
  dev/com.ibm.ws.microprofile.metrics.2.0/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetrics.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#9539 OpenShift login: Initial NLS message drop
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#9604 Update featureverifier to build in eclipse
  dev/com.ibm.ws.featureverifier/bnd.bnd
Labels: CLA Signed, team:Performance

#9599 relax ffdc criteria, too many fvt false positives.
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ChannelSelector.java
Labels: in:Transport, team:Sirius

#9612 Fix event.logging_fat .project file
  dev/com.ibm.ws.event.logging_fat/.project
Labels: CLA Signed, noproductcode, team:Performance

#9577 Set globalID earlier
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceInfoImpl.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/RemoteTransactionControllerService.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
Labels: CLA Signed

#9541 Issue #9538: Remove mention of ANT
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIConfigByACPTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIInjectionTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#9569 Add message for missing Kafka Lib
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaAdapterException.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaAdapterFactory.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/package-info.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/AdapterFactoryImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/nolib/KafkaNoLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/nolib/NoLibMessagingBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/FATSuite.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#9623 Remove xtrace
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12CDICurrentServer/jvm.options
Labels: CLA Signed, noproductcode

#9591 Rename microProfile-3.1 to microProfile-3.2
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/com.ibm.websphere.appserver.microProfile-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/resources/l10n/com.ibm.websphere.appserver.microProfile-3.2_zh_TW.properties
  dev/com.ibm.ws.microprofile.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/SimpleJAXRSCDITest.java
Labels: CLA Signed, ID review not needed, in:MicroProfile, team:MicroProfileUK

#9558 Mp fault tolerance parallel ba
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance1.0-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance1.1-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-0.0.0.noImpl.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-1.0/com.ibm.websphere.appserver.concurrent-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.0/com.ibm.websphere.appserver.mpFaultTolerance-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.0/com.ibm.websphere.appserver.mpFaultTolerance-2.0.feature
Labels: CLA Signed

#9616 testTransactionTimeout does not wait long enough
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/PersistentErrorTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9598 Update OpenSAML coordinates to reflect DHE
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
Labels: CLA Signed, noproductcode, team:Security SSO

#9608 update config test bucket to Infinispan 10 final
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.classpath
  dev/com.ibm.ws.session.cache_fat_config_infinispan/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/server.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/jcacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/jcacheApp/src/test/cache/infinispan/web/JCacheConfigTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#9513 contextual proxy method exception logged to ffdc
  dev/com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ContextualInvocationHandler.java
  dev/com.ibm.ws.microprofile.health_fat/fat/src/com/ibm/ws/microprofile/health/fat/HealthCheckExceptionTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#9627 fix the NPE when the algorithm field is not provided in a Digest
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/security/auth/DigestUtils.java
Labels: CLA Signed

#9617 Enable SessionCacheTimeoutTests
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/files/infinispan/users.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/server.xml
Labels: team:Zombie Apocalypse

#8858 HTTP/2 malformed request streams should be reset
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/huffman/HuffmanDecoder.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpResponseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, team:Sirius

#9585 [9293] Log JAXRS exception handled by OT ExceptionMapper
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerConfigTest.java
  dev/com.ibm.ws.opentracing.1.1/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncher.java
  dev/com.ibm.ws.opentracing.1.2/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.2_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncher.java
  dev/com.ibm.ws.opentracing.1.3/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.3_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncher.java
  dev/com.ibm.ws.opentracing.1.3_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncherMicroProfile.java
  dev/com.ibm.ws.opentracing/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/OpentracingTCKLauncher.java
Labels: CLA Signed, ID reviewed, in:MicroProfile/OpenTracing, team:Wendigo West

#9556 switch the metatype attribute for infinispan support to beta
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Zombie Apocalypse

#9285 Add Capitalization for openldap Boolean
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
Labels: CLA Signed, team:Wendigo East

#9642 Add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other-issue.md
Labels: CLA Signed

#9640 Issue #9639: Remove Xfuture test on Windows envs due to dialog box
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: CLA Signed, noproductcode

#9614 Enable SessionCacheTwoServerTest
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/server.xml
Labels: team:Zombie Apocalypse

#9630 Enable SessionCacheTwoServerTimeoutTests
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/server.xml
Labels: team:Zombie Apocalypse

#9626 set tccl on recovery thread
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.transaction/bnd.bnd
Labels: CLA Signed

#9656 Revert "set tccl on recovery thread"
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.transaction/bnd.bnd
Labels: CLA Signed

#9153 ACME Fat test skeleton
  dev/com.ibm.ws.security.acme_fat/.classpath
  dev/com.ibm.ws.security.acme_fat/.project
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/FATSuite.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/SimpleTest.java
  dev/com.ibm.ws.security.acme_fat/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.security.acme_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.security.acme_fat/test-applications/app1/resources/index.jsp
  dev/com.ibm.ws.security.acme_fat/test-applications/app1/src/app1/web/TestServletA.java
Labels: CLA Signed, noproductcode

#9659 Revert "Revert "set tccl on recovery thread""
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.transaction/bnd.bnd
Labels: CLA Signed

#9649 Change the OSGI to liberty log mapping of log level detail.
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/LoggingConfigurationService.java
Labels: CLA Signed

#9674 issue-9673
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/SipServletResponseImpl.java
Labels: CLA Signed

#9652 add scope to app token
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/UIAccessTokenBuilder.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/UIAccessTokenBuilderTest.java
Labels: CLA Signed

#9653 Initial mpMetrics-2.2 implementation
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics-2.2-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics2.2-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/com.ibm.websphere.appserver.microProfile-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.2/com.ibm.websphere.appserver.mpMetrics-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.2/resources/l10n/com.ibm.websphere.appserver.mpMetrics-2.2.properties
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.2/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/.project
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_cs.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_de.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_es.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_fr.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_hu.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_it.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_ja.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_ko.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_pl.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_pt_BR.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_ro.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_ru.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_zh.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics_zh_TW.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/fat/resources/logging.properties
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/fat/src/com/ibm/ws/microprofile/metrics22/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/fat/src/com/ibm/ws/microprofile/metrics22/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/servers/MetricsTCKServer/jvm.options
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed

#9669 Resolving ispn021011 issue
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/files/infinispan/config.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9636 update json4j's Tokenizer.readNumber() to handle 0E-10
  dev/com.ibm.json4j/src/com/ibm/json/java/internal/Tokenizer.java
Labels: CLA Signed, in:JAX-RS, release bug, team:Wendigo West

#9677 Update application class load to not transform cached classes
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
Labels: CLA Signed, team:Performance

#9605 Social login with OpenShift: Metatype additions
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#9654 nonship config attribute for coordinating task ownership via a time-based claim
  dev/com.ibm.ws.concurrent.persistent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/Config.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
Labels: CLA Signed, team:Zombie Apocalypse

#9650 Modifying FAT test to stop liberty server after each test method
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/JSONFieldsTest.java
Labels: CLA Signed, noproductcode

#9551 incorrect use of phaser.arriveAndAwaitAdvance by testGroupedSubmits
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9667 Add a check to see if the executor has been shutdown
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaInput.java
Labels: CLA Signed, in:MicroProfile/Reactive, team:MicroProfileUK

#9689 Revert "Revert "Revert "set tccl on recovery thread"""
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.transaction/bnd.bnd
Labels: CLA Signed

#9705 Cleanup of eclipse / bnd settings
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/.classpath
  dev/com.ibm.ws.security.acme_fat/.settings/bndtools.core.prefs
Labels: CLA Signed, team:Performance

#9638 Fix null pointer when remove and iterator overlap in Infinispan
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: CLA Signed

#9699 Social login: Initial delivery of support for OpenShift
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/ClientConstants.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/AuthorizationCodeAuthenticator.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/test/CommonTestClass.java
Labels: CLA Signed, team:Security SSO

#9704 Add builderignore to avoid extra checking during builds
  dev/cnf/build.bnd
Labels: CLA Signed, team:Performance

#9702 Cleaning up infinispan_container test suite
  dev/com.ibm.ws.session.cache_fat_infinispan_container/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan_container/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/files/infinispan/config.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server.mphealth/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server.mphealth/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/AppObject.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean1.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean2.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener1/SessionListener.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener2/SessionListener.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9681 Issue #9675:Explicit FFDC for app ExecutionException
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfigurator.java
Labels: CLA Signed

#9637 Issue #9307: Error message in Open Tracing changes to Warning message
  dev/com.ibm.ws.opentracing.1.1/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing.1.2/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.2_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing.1.3/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.3_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
Labels: CLA Signed

#9629 Update testcontainers and explicitly terminate networks to prevent ha…
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.cloudant_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/build.gradle
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_db2/build.gradle
  dev/com.ibm.ws.jdbc_fat_postgresql/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/KafkaSaslPlainContainer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/KafkaTlsContainer.java
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan_container/build.gradle
  dev/fattest.simplicity/bnd.bnd
Labels: CLA Signed, noproductcode

#9721 Revert "Issue #9307: Error message in Open Tracing changes to Warning message"
  dev/com.ibm.ws.opentracing.1.1/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.1_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing.1.2/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.2_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing.1.3/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.3_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
Labels: CLA Signed

#9688 Switch from TCP to UDP, and cleanup transport stack name.
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/infinispan/infinispan-config-lacking-http-session-cache-name.xml
Labels: team:Zombie Apocalypse

#9634 Java2sec errors in jaxws-2.2
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/bus/LibertyApplicationBusFactory.java
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/metadata/JaxWsClientMetaData.java
  dev/com.ibm.ws.org.apache.cxf.jaxws/.gitignore
  dev/com.ibm.ws.org.apache.cxf.jaxws/.project
  dev/com.ibm.ws.org.apache.cxf.jaxws/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.jaxws/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.jaxws/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.jaxws/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4520.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4521.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4522.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4523.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4557.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4562.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4565.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4570.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4583.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4584.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4594.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4611.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4616.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4650.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4652.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4674.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4676.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4677.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4684.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4695.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4713.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4720.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4725.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4730.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4748.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4768.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4784.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4790.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4794.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4803.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4818.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4839.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4859.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4876.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4877.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4918.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4947-2.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/CXF-4947.diff
  dev/com.ibm.ws.org.apache.cxf.jaxws/archive/changes.txt
Labels: CLA Signed

#9678 Clean up http/2 test client code
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/CFWManager.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResult.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResultManager.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/connection/H2Connection.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/frames/FrameDataClient.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/frames/FrameHeadersClient.java
Labels: CLA Signed, in:Transport, team:Sirius

#9686 EJB SimpleBindingName xml Namespace Tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/SimpleBindingNameTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameWeb.war/src/com/ibm/ejb2x/jndiName/web/JNDINameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameEJB.jar/src/com/ibm/ejb3x/SimpleBindingName/ejb/SimpleBindingName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameEJB.jar/src/com/ibm/ejb3x/SimpleBindingName/ejb/SimpleBindingNameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameEJB.jar/src/com/ibm/ejb3x/SimpleBindingName/ejb/SimpleBindingNameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameWeb.war/src/com/ibm/ejb3x/SimpleBindingName/web/SimpleBindingNameTestServlet.java
Labels: CLA Signed, noproductcode

#9668 Tentative - remove processCpuTime metric
  dev/com.ibm.ws.microprofile.metrics.2.0/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetrics.java
Labels: CLA Signed

#9711 Change to use `@SchemaName` instead of `@Argument` or `@InputField`
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/query/AnnotatedArgumentBuilder.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/query/PublicResolverBuilder.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/AnnotationMappingUtils.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/InputFieldInfoGenerator.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/jsonb/JsonbValueMapper.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPDateTimeScalarMapperExtension.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicMutationApp/src/mpGraphQL10/basicMutation/GraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/defaultvalueApp/src/mpGraphQL10/defaultvalue/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/graphQLInterfaceApp/src/mpGraphQL10/graphQLInterface/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ifaceApp/src/mpGraphQL10/iface/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/InputFieldsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/Widget.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/WidgetClientObject.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/typesApp/src/mpGraphQL10/types/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9067 Remove the provider bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/spnego-1.0/com.ibm.websphere.appserver.spnego-1.0.feature
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/ws/security/auth/data/internal/AuthDataImpl.java
  dev/com.ibm.ws.security.oauth.jwt/bnd.bnd
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/UserAuthentication.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/UserAuthenticationTest.java
  dev/com.ibm.ws.security.openid/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.client/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.server/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.provider/.classpath
  dev/com.ibm.ws.webcontainer.security.provider/.project
  dev/com.ibm.ws.webcontainer.security.provider/.settings/bndtools.core.prefs
  dev/com.ibm.ws.webcontainer.security.provider/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.webcontainer.security.provider/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.webcontainer.security.provider/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.webcontainer.security.provider/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/AuthenticateApiExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/ReferrerURLCookieHandlerExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/SSOCookieHelperImplExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/WebAppSecurityConfigExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/WebAuthenticatorFactoryExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/WebAuthenticatorProxyExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/WebProviderAuthenticatorProxyExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/extended/package-info.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/internal/extended/WebAppSecurityConfigImplExtended.java
  dev/com.ibm.ws.webcontainer.security.provider/src/com/ibm/ws/webcontainer/security/internal/extended/WebAuthenticatorFactoryImplExtended.java
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ReferrerURLCookieHandler.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorFactory.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/OAuthChallengeReply.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAuthenticatorFactoryImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/oauth20/OAuth20Authenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/oauth20/OAuth20Service.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/oauth20/package-info.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openid20/OpenidClientService.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openid20/package-info.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcClient.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcServer.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcServerConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/package-info.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxyTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
Labels: CLA Signed

#9664 Default all Kafka test timeouts to 30s
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/common/KafkaTestConstants.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/ExtendedKafkaWriter.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/invalid/LibertyLoginModuleInvalidTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomKeySerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaKeySerializerTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaSerializerTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tls/KafkaTlsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tls/KafkaTlsTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/MissingGroupIDTest.java
Labels: CLA Signed, in:MicroProfile/Reactive, noproductcode, team:MicroProfileUK

#9730 intermittent failure in testCancelRunningTask when failover is enabled
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9693 Add initialization for failoverServers
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/FailoverServers.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#9726 Login integration latest changes
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/ClientConstants.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed, ID review not needed

#9738 externalize string for not found page for OL splash page
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/notFound/index.html
Labels: CLA Signed

#9728 Add integration between MP Fault Tolerance 2.0 and MP Metrics-2.2
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics2.0.feature
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/RepeatFaultTolerance.java
Labels: CLA Signed

#9720 construct default realm from token review ep for oauth proxy flow
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAISubjectUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
Labels: CLA Signed

#9747 Rename `@SchemaName` to `@Name` - as changed in the MP GraphQL spec
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/query/AnnotatedArgumentBuilder.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/AnnotationMappingUtils.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/InputFieldInfoGenerator.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/jsonb/JsonbValueMapper.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPOperationBuilder.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicMutationApp/src/mpGraphQL10/basicMutation/GraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/defaultvalueApp/src/mpGraphQL10/defaultvalue/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/graphQLInterfaceApp/src/mpGraphQL10/graphQLInterface/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ifaceApp/src/mpGraphQL10/iface/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/InputFieldsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/Widget.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/WidgetClientObject.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/typesApp/src/mpGraphQL10/types/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9743 Issue #9742: Update FVT TLS certificates for new / replaced Active Di…
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.ad.ssl/oldcerts/key.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.ad.ssl/oldcerts/trust.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.ad.ssl/trust.jks
Labels: CLA Signed, noproductcode, team:Wendigo East

#9756 Get things building in eclipse again
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/.classpath
  dev/com.ibm.ws.request.probe.jdbc_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.jdbc_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.probe.servlet_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.servlet_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.probe.servlet_fat/build.gradle
  dev/com.ibm.ws.request.probes_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probes_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.timing_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.timing_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#9719 update trace for REST request handler
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/internal/service/RESTHandlerContainerImpl.java
Labels: CLA Signed, team:Wendigo East

#9540 Remove EARLY_ACCESS test.
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/AnnotationsBetaHelper.java
Labels: CLA Signed

#9716 Temporarily re-enable Java 7 support
  dev/com.ibm.ws.jaxrs.2.0.tools/src/com/ibm/ws/kernel/boot/cmdline/Main.java
  dev/com.ibm.ws.kernel.boot.cmdline/src/com/ibm/ws/kernel/boot/cmdline/EnvCheck.java
  dev/com.ibm.ws.kernel.boot.cmdline/src/com/ibm/ws/kernel/boot/cmdline/Main.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/CreateCommandTest.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/BootstrapConfigTest.java
Labels: CLA Signed, ID reviewed

#9727 Changing default value of ModifyActiveCountOnInvalidatedSession to be…
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
Labels: CLA Signed

#9736 Fixes for com.ibm.ws.jaxws.2.3.common
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/policy/DynamicAttachmentProvider.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/support/LibertyHTTPConduit.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/support/LibertyHTTPTransportFactory.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/support/LibertyJaxWsServiceFactoryBean.java
Labels: CLA Signed

#9758 Change the JDBC call from executeBatch() API to executeUpdate() APIs
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMapMR.java
Labels: CLA Signed

#9740 Use TCCL in recovery
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.transaction/bnd.bnd
Labels: CLA Signed

#9768 Revert "Remove EARLY_ACCESS test."
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/AnnotationsBetaHelper.java
Labels: CLA Signed

#9763 fix how claim expiry is computed and enforce requirement for commit of in-progress timers that are canceled asynchronously
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/websphere/concurrent/persistent/TaskIdAccessor.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/websphere/concurrent/persistent/mbean/PersistentExecutorMBean.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/TaskStatusImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9706 url encode logout url
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/OAuth20EndpointServicesTest.java
Labels: CLA Signed

#9772 Notices for 19.0.0.12
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#9715 Clean up and consolidate some OpenShift social login code
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/AuthUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/TAIWebUtilsTest.java
Labels: CLA Signed, team:Security SSO

#9764 Add com.ibm.ws.jaxws.2.3.security to the jaxws-2.3 feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxwsSecurity-2.3.feature
  dev/com.ibm.ws.jaxws.2.3.security/.classpath
  dev/com.ibm.ws.jaxws.2.3.security/.gitignore
  dev/com.ibm.ws.jaxws.2.3.security/.project
  dev/com.ibm.ws.jaxws.2.3.security/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxws.2.3.security/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxws.2.3.security/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxws.2.3.security/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxws.2.3.security/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_cs.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_de.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_es.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_fr.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_hu.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_it.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_ja.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_ko.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_pl.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_pt_BR.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_ro.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_ru.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_zh.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/resources/com/ibm/ws/jaxws/security/internal/resources/JaxWsSecurityMessages_zh_TW.nlsprops
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/JaxWsProxySSLSocketFactory.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/JaxWsSSLManager.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/JaxWsSecurityConfigurationServiceImpl.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/JaxWsSecurityConstants.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/JaxWsWebAppSecurityConfigurator.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/SecurityJaxWsModuleInfoBuilderExtension.java
  dev/com.ibm.ws.jaxws.2.3.security/src/com/ibm/ws/jaxws/security/internal/package-info.java
Labels: CLA Signed

#9746 add additional information for conTimeout value for 0 and -1
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#9782 update fattest.simplicy to allow specifying multiple test classes/met…
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/TestNameFilter.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode

#9759 Add a warning for variables in ID fields
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
Labels: CLA Signed

#9748 Generate a server dump if the service fails to activate
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/fat/src/com/ibm/ws/concurrent/persistent/delayexec/DelayExecutionFATTest.java
Labels: CLA Signed, noproductcode

#9803 get correct token from the header
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/AuthUtils.java
Labels: CLA Signed

#9793 Login integration latest changes
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed

#9192 Issue #9179: Remove beta tag from reader-role so it can GA.
  dev/com.ibm.ws.management.security/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Wendigo East

#9193 Issue #9180: Update restConnector-2.0 description to mention reader a…
  dev/com.ibm.websphere.appserver.features/visibility/public/restConnector-2.0/resources/l10n/com.ibm.websphere.appserver.restConnector-2.0.properties
Labels: CLA Signed, L2 ReviewNotRequired, team:Wendigo East

#9785 Add apps to the server's startup verification list
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/BuildShrinkWrap.java
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/ShrinkWrapSharedServer.java
Labels: CLA Signed, noproductcode

#9781 metatype update
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#9745 Move Jaeger to GA
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/JaegerTracerFactory.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerConfigTest.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer1/server.env
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer2/server.env
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerInventory/server.env
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerSystem/server.env
Labels: CLA Signed

#9805 wait for security to start
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentConfigTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9791 GA microProfile-3.2
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics-2.2-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics2.2-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/com.ibm.websphere.appserver.microProfile-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.2/com.ibm.websphere.appserver.mpMetrics-2.2.feature
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile3/server.xml
Labels: CLA Signed, in:MicroProfile, team:MicroProfileUK

#9792 initial tests in failover timers bucket running with failover approach 2
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest2.java
Labels: CLA Signed, team:Zombie Apocalypse

#9762 Issue #9760: Add server.isStopped() check in ServerStartAsServericeTest
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartAsServiceTest.java
Labels: CLA Signed, noproductcode

#9665 add new oauth error message
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/internal/resources/OAuthMessages.nlsprops
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/TokenExchange.java
Labels: CLA Signed, ID reviewed

#9800 Use 3.1 instead of 4.0 for the test applications.
  dev/com.ibm.ws.anno_fat/bnd.bnd
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppDefaultAppMgrDefaultTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppDefaultAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppFalseAppMgrFalseTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppFalseAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppTrueAppMgrFalseTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/jandex/JandexAppTrueAppMgrTrueTest.java
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppDefaultAppMgrDefault_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppDefaultAppMgrFalse_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppDefaultAppMgrTrue_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppFalseAppMgrFalse_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppFalseAppMgrTrue_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppTrueAppMgrFalse_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexAppTrueAppMgrTrue_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/jandexDefaultsAutoExpandTrue_server.xml
  dev/com.ibm.ws.anno_fat/publish/servers/annoFat_server/config/looseConfig_server.xml
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet1.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet1.jar/src/looseservlet1/jar/listeners/Servlet_1_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet1.jar/src/looseservlet1/jar/servlets/ServletContainerInitializer_1.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet2.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet2.jar/src/looseservlet2/jar/listeners/Servlet_2_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet2.jar/src/looseservlet2/jar/servlets/ServletContainerInitializer_2.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet3.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet3.jar/src/looseservlet3/jar/listeners/Servlet_3_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/LooseServlet3.jar/src/looseservlet3/jar/servlets/ServletContainerInitializer_3.java
  dev/com.ibm.ws.anno_fat/test-applications/LooseConfig/earContent/META-INF/application.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.jar/src/testservlet40/jar/servlets/ServletContainerInitializerImpl.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-NOT-metadata-complete.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-absolute-ordering-a-b-c.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-absolute-ordering-a-b-others.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-absolute-ordering-a-b.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-absolute-ordering-c-d-a-b-others.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-metadata-complete-missing-servlets.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-metadata-complete.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web-original.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServlet40.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServletA.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServletA.jar/src/testservleta/jar/listeners/Servlet_A_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletA.jar/src/testservleta/jar/servlets/ServletContainerInitializer_A.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletB.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServletB.jar/src/testservletb/jar/listeners/Servlet_B_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletB.jar/src/testservletb/jar/servlets/ServletContainerInitializer_B.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletC.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServletC.jar/src/testservletc/jar/listeners/Servlet_C_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletC.jar/src/testservletc/jar/servlets/ServletContainerInitializer_C.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletD.jar/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.anno_fat/test-applications/TestServletD.jar/src/testservletd/jar/listeners/Servlet_D_Listener.java
  dev/com.ibm.ws.anno_fat/test-applications/TestServletD.jar/src/testservletd/jar/servlets/ServletContainerInitializer_D.java
Labels: CLA Signed, noproductcode

#9801 All wait for log to loose config test.
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/AnnoCachingTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/LooseConfigTest.java
Labels: CLA Signed, noproductcode

#9812 Clean up recovery director
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LibertyRecoveryDirectorImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorFactory.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
Labels: CLA Signed

#9822 Update the FT TCK trace spec
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/servers/FaultTolerance11TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/servers/FaultToleranceTCKServer/bootstrap.properties
Labels: CLA Signed, noproductcode

#9827 Prevent trace statement injection for most of JNDI literal parsing code
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/literals/LiteralParser.java
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/literals/LiteralType.java
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/literals/Patterns.java
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/literals/StringParser.java
Labels: CLA Signed

#8524 removing obsolete channelwritetype from metadata and webcontainer properties
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/config/WebContainerElement.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/WebContainerElement.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#9775 Wire anno caching into JAXWS 23; augment tracing.
  dev/com.ibm.ws.jaxws.2.3.web/src/com/ibm/ws/jaxws23/web/WebJaxWsModuleInfoBuilder.java
  dev/com.ibm.ws.jaxws.2.3.webcontainer/src/com/ibm/ws/jaxws23/webcontainer/JaxWsExtensionFactory.java
  dev/com.ibm.ws.jaxws.web/src/com/ibm/ws/jaxws/web/WebJaxWsModuleInfoBuilder.java
  dev/com.ibm.ws.jaxws.webcontainer/src/com/ibm/ws/jaxws/webcontainer/JaxWsExtensionFactory.java
Labels: CLA Signed

#8994 start of translation
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/api/error/OAuthException.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/api/error/OidcServerException.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/error/impl/BrowserAndServerLogMessage.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/exception/OAuth20BadParameterException.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientProvider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidator.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/custom/OauthClientStore.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProvider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/jose4j/JWTTokenException.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/AbstractOidcEndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/ClientAuthentication.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/CoverageMapEndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/TokenExchange.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/WebUtils.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/error/impl/BrowserAndServerLogMessageTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidatorTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/custom/OauthClientStoreCommon.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProviderTest.java
  dev/com.ibm.ws.security.test.common/src/com/ibm/ws/security/test/common/CommonTestClass.java
Labels: CLA Signed

#9817 9281-auditutility COMMIT1
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
Labels: CLA Signed, release bug

#9680 9679 - Message already sent ffdc
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: CLA Signed, in:Transport, team:Sirius

#9837 fix testcase errors
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FeatureTest.java
Labels: CLA Signed, in:Security, noproductcode, team:Core Security, test bug

#9843 edited tr from message to error
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
Labels: CLA Signed

#9840 Deliver acmeCA project for SEC-27
  dev/com.ibm.ws.security.acme/.classpath
  dev/com.ibm.ws.security.acme/.project
  dev/com.ibm.ws.security.acme/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/build.gradle
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-bnd.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-ext.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeService.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderServiceImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationProcessor.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/TraceConstants.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/package-info.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorization.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorizationServices.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeFilterImpl.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#9832 clarify CWOAU0073E message
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs.nlsprops
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/PublicFacingErrorServletTest.java
Labels: CLA Signed, release bug, team:Security SSO

#9859 Upgrade MP GraphQL TCK to get added diagnostics
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9796 update mpjwt utility to have additional checking done
  dev/com.ibm.ws.security.mp.jwt.proxy/src/com/ibm/ws/security/mp/jwt/proxy/MpJwtHelper.java
Labels: CLA Signed, release bug

#9853 ensure cache is used before shutdown in tests
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9723 Implement circuit breaker skip on 9628
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics2.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.1/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/CircuitBreakerStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/CircuitBreakerStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi.services/src/com/ibm/ws/micrprofile/faulttolerance21/cdi/services/AnnotationConfigFactoryComponent.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/AnnotationConfigFactoryImpl21.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/CircuitBreakerConfig21Impl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/package-info.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/test/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/CircuitBreakerConfig21Test.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck21Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/servers/FaultTolerance21TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/servers/FaultTolerance21TCKServer/jvm.options
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/servers/FaultTolerance21TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/faulttolerance/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite-metrics-only.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/AnnotationConfigFactory.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/CircuitBreakerConfig.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/AnnotationConfigFactoryImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/AnnotationConfigFactoryImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/CircuitBreakerConfigImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/CircuitBreakerPolicy.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/policy/CircuitBreakerPolicyImpl.java
Labels: CLA Needed

#9877 Update SmallRye bundles
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-1.0/com.ibm.websphere.appserver.mpReactiveStreams-1.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/bnd.bnd
  dev/com.ibm.ws.io.reactivex.rxjava.2.2/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.classpath
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.project
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.settings/bndtools.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.converters/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.classpath
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.gitignore
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.project
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.settings/bndtools.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/resources/META-INF/beans.xml
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/src/com/ibm/ws/microprofile/reactive/messaging/OLReactiveMessagingExtension.java
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.classpath
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.project
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.settings/bndtools.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/UPSTREAM_pom.xml
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.streams.operators.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.streams.operators/bnd.bnd
Labels: CLA Signed, in:MicroProfile/Reactive, team:MicroProfileUK

#9889 add retry logic, modify trace spec.
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleIdentityStoreCustomFormPostTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.custom.post.fat/apps/.gitignore
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.custom.post.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.custom.post.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.custom.post.fat/resources/security/ltpa.keys
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.custom.post.fat/server.xml
Labels: CLA Signed, in:Security, noproductcode, team:Core Security, test bug

#9882 Add runtime update trace by default
  dev/fattest.simplicity/autoFVT-defaults/testports.properties
Labels: CLA Signed, noproductcode

#9899 Removed unnecessary derby call
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9875 Adding test in Jaeger for packaging library war file
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerConfigTest.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer3/server.xml
Labels: CLA Signed, noproductcode

#9698 Fix Timeout issue
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LdapFailoverTest.java
Labels: CLA Signed, team:Wendigo East

#9891 Expand package import range to include JCA 1.6 packages
  dev/com.ibm.ws.rest.handler.validator.jca/bnd.bnd
Labels: team:Zombie Apocalypse

#9552 9392 batch remote partition recovery
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/JobExecutionHelper.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/RuntimePartitionExecution.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotablePartitionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotableSplitFlowEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/AbstractPersistenceManager.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSJobRepository.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSRemotablePartitionState.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSStartupRecoveryServiceImpl.java
  dev/com.ibm.jbatch.container/test/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImplTest.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/dispatcher/BatchJmsDispatcher.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/listener/BatchJmsEndpointListener.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobInstances.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
Labels: CLA Signed

#9776 Fix defaulting and reading of WLP_DEBUG_REMOTE env var
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#9912 Revert "9392 batch remote partition recovery"
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/JobExecutionHelper.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/RuntimePartitionExecution.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotablePartitionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotableSplitFlowEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/AbstractPersistenceManager.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/RemotablePartitionState.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSJobRepository.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSStartupRecoveryServiceImpl.java
  dev/com.ibm.jbatch.container/test/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImplTest.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/dispatcher/BatchJmsDispatcher.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/listener/BatchJmsEndpointListener.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobInstances.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
Labels: CLA Signed

#9849 Added the RA's CMD to the thread during configureResourceAdapter
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/BootstrapContextImpl.java
Labels: CLA Signed

#9831 OpenShift social login serviceability work
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/FacebookLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/GithubLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/LinkedinLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/TwitterLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/Oauth2LoginConfigImplTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/TAIWebUtilsTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/test/CommonTestClass.java
Labels: CLA Signed, team:Security SSO

#9927 Get things building in eclipse again
  dev/com.ibm.ws.jaxws.2.3.security/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/.project
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/.project
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/.project
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.opentracing.1.x_fat/.classpath
  dev/com.ibm.ws.opentracing.1.x_fat/.project
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, team:Performance

#9893 display generated infinispan config
  dev/com.ibm.ws.session.cache/resources/com/ibm/ws/session/store/cache/resources/WASSessionCache.nlsprops
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#9908 test where transaction blocks after cancelling task
  dev/com.ibm.ws.concurrent.persistent/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#9905 Ignore charset when deciding whether or not to process form parameters
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/FormUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/params/ParamsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/params/src/com/ibm/ws/jaxrs/fat/params/form/FormParamResource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/FormUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9894 EJB Custom Bindings binding-name element tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BindingNameTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/src/com/ibm/ejb3x/BindingName/ejb/BindingName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/src/com/ibm/ejb3x/BindingName/ejb/BindingNameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/src/com/ibm/ejb3x/BindingName/ejb/BindingNameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameEJB.jar/src/com/ibm/ejb3x/BindingName/ejb/BindingNameIntf.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameWeb.war/src/com/ibm/ejb3x/BindingName/web/BindingNameTestServlet.java
Labels: CLA Signed, noproductcode

#9911 Create microProfile-3.3 feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/com.ibm.websphere.appserver.microProfile-3.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/resources/l10n/com.ibm.websphere.appserver.microProfile-3.3_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.1/com.ibm.websphere.appserver.mpFaultTolerance-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.1/com.ibm.websphere.appserver.mpJwt-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.1/com.ibm.websphere.appserver.mpOpenAPI-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/com.ibm.websphere.appserver.mpOpenTracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.2/com.ibm.websphere.appserver.mpRestClient-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/com.ibm.websphere.appserver.mpRestClient-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.2/com.ibm.websphere.appserver.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
  dev/com.ibm.ws.microprofile.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/SimpleJAXRSCDITest.java
Labels: CLA Signed, ID review not needed, In Progress, in:MicroProfile, team:MicroProfileUK

#9959 9956 - testDataFrameAfterContinuationFrame to trace bucket
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#9962 add blocking tests for finder operations and more
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9958 Fix for Issue #9957: Handle quiesce operation did not complete errors for Load On Startup Test
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/LoadOnStartup12Test.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#9961 IllegalStateException handling for selfExtractUtils
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractUtils.java
Labels: CLA Signed

#9930 Social login: Kubernetes login code enhancements
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OAuthClientHttpUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OAuthClientUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAISubjectUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/AuthorizationCodeAuthenticatorTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/OAuthLoginFlowTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/TAISubjectUtilsTest.java
Labels: CLA Signed, team:Security SSO

#9964 Social login: Update how default metatype values are read
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
Labels: CLA Signed, team:Security SSO

#9896 Adding an Introspector for the Logging framework
  dev/com.ibm.ws.diagnostics/bnd.bnd
  dev/com.ibm.ws.diagnostics/src/com/ibm/ws/diagnostics/osgi/LoggingIntrospector.java
Labels: CLA Signed

#9820 added error handling to changelog creation
  dev/build.image/build.gradle
  dev/build.image/packaging/buildOsNativePackages.sh
  dev/build.image/packaging/buildRPM.sh
  dev/build.image/packaging/updateChangelogs.sh
Labels: CLA Signed

#9945 Adding back processCpuTime metric
  dev/com.ibm.ws.microprofile.metrics.2.0/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetrics.java
Labels: CLA Signed, ID reviewed

#9972 Introduce new tai to handle access token
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/Constants.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/OAuthLoginFlow.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginWithAccessToken.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIRequestHelper.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/test/CommonTestClass.java
Labels: CLA Signed

#9960 Openshift utils changes
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed

#9923 Correct error message
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed, ID review not needed, team:Security SSO

#9560 Initial drop for #9496 - Copy com.ibm.ws.messaging.comms_fat to open-liberty
  dev/com.ibm.ws.messaging.open_comms_fat/.gitignore
  dev/com.ibm.ws.messaging.open_comms_fat/.project
  dev/com.ibm.ws.messaging.open_comms_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_comms_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_comms_fat/common/src/com/ibm/ws/messaging/open_comms/fat/Util.java
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FATBase.java
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FeatureUpdate.java
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/WasJmsOutBoundTest.java
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/.gitignore
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/README
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/SecurityDisabledClient.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/SecurityDisabledServer.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/SecurityEnabledClient.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/SecurityEnabledServer.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/client.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/server.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/files/testjmsinternals-1.0.mf
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOClient/.gitignore
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOClient/bootstrap.properties
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOClient/resources/security/WJOClient.jks
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOClient/server.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOServer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOServer/resources/security/WJOServer.jks
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.WJOServer/server.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.client/.gitignore
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.client/bootstrap.properties
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.client/resources/security/client.jks
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.client/server.xml
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.server/bootstrap.properties
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.server/resources/security/server.jks
  dev/com.ibm.ws.messaging.open_comms_fat/publish/servers/com.ibm.ws.messaging.open_comms.server/server.xml
  dev/com.ibm.ws.messaging.open_comms_fat/test-applications/CommsLP/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_comms_fat/test-applications/CommsLP/src/com/ibm/ws/messaging/open_comms/fat/CommsLPServlet.java
Labels: CLA Signed, noproductcode
