Repository OpenLiberty/open-liberty, pull requests merged in 2019-07, with the labels that each got.

#8079 Add mpReactiveMessaging-1.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.messaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
Labels: CLA Signed

#7997 Support for WLP-Activation-Type feature header for parallel activation
  dev/com.ibm.ws.kernel.boot.nested/bnd.bnd
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/ProvisionerImpl.java
  dev/com.ibm.ws.kernel.boot_test/bnd.bnd
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/launch/internal/ProvisionerTest.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleList.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureResourceImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/KernelFeatureDefinitionImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/ActivationType.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/FeatureResource.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/ProvisioningFeatureDefinition.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureManagerTest.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ActivationTypeTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.activation.parallel.system-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.activation.parallel.user-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.activation.sequential.system-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.activation.sequential.user-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.activation.type/.gitignore
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.activation.type/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.activation.type/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.activation.type/src/test/activation/type/Activator.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.api/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.provisioner/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.service.consumer/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.service.provider/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.activation.type.parallel.system.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.activation.type.parallel.user.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.activation.type.sequential.system.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.activation.type.sequential.user.bnd
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRequirement.java
Labels: CLA Signed

#8080 move up isInitialDiscovery check
  dev/com.ibm.ws.microprofile.metrics.cdi.2.0/src/io/astefanutti/metrics/cdi/MetricResolver.java
Labels: CLA Signed

#8094 Revert "temporarily disable the PureCXFTest in com.ibm.ws.jaxws.2.2.webcontai…"
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#8066 Include default value in warning message
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
Labels: CLA Signed, ID review not needed, L2 Reviewed

#8011 remove erroneous override of library id
  dev/com.ibm.ws.classloading/resources/OSGI-INF/metatype/library.xml
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/providers/Providers.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/SharedLibraryImpl.java
Labels: CLA Signed, invalid, team:Zombie Apocalypse

#8102 Add null check for webAppNameSpaceCollab
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed, team:Performance

#8100 Fix MP Config classloader cache test
  dev/com.ibm.ws.microprofile.config.1.1_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.config.1.1_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoaderCacheTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/RemoteFile.java
Labels: CLA Signed, noproductcode

#7845 Ported the compat fat test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_compat/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_compat/.project
  dev/com.ibm.ws.concurrent.persistent_fat_compat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_compat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/PersistentExecutorCompatibilityTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/publish/servers/com.ibm.ws.concurrent.persistent.fat.compat/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_compat/publish/servers/com.ibm.ws.concurrent.persistent.fat.compat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/CallableTrigger-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/CallableWithTrigger-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/EJBTimer-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/FailingRunnable-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/FixedDelayTask-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/FixedRateTask-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/OneShotCallable-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/SkipRunFailure-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/SkippedCallable-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/TaskWithNonSerializableResult-8.5.5.6.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/ejb/MyTimerEJBInWAR.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/CounterCallable.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/CounterCallableTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/ExecTimeCallable.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/MapCounter.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/MapCounterRunnable.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/NonSerializableResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/PersistentExecCompatibilityTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/SkipFailingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/SkippingTwoTimeTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/TwoTimeTrigger.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7963 Porting database task store test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.project
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/db/CommonUtils.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/db/ExecEnabledDBStoreConfigUpdateTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/db/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/db/PersistentExecutionConfigUpdateDBStoreTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate.dbtaskstore/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate.dbtaskstore/derby.properties
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate.dbtaskstore/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/test-applications/persistcfgdbtest/src/web/AlternatingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/test-applications/persistcfgdbtest/src/web/CountingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/test-applications/persistcfgdbtest/src/web/ScheduleStartServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/test-applications/persistcfgdbtest/src/web/SimpleTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8111 Wrap JPA container call to ClassLoadingService.createThreadContextCla…
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
Labels: CLA Signed, bug, in:JPA, team:Blizzard

#8103 Prevent Batcher trying to commit batches after the app has closed
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/AckTracker.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/Batcher.java
Labels: CLA Signed

#8105 Fix test to work in non-English locales
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/wsspi/kernel/embeddable/EmbeddedServerDriver.java
Labels: CLA Signed, noproductcode

#8121 clean up logging in com.ibm.ws.jaxws.2.2.webcontainer_fat
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/util/ExplodedShrinkHelper.java
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#8110 Tolerate unexpected protocol messages
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
Labels: CLA Signed

#8097 remove PR7009
  dev/com.ibm.ws.security.authentication.tai/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/TAIConfig.java
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/TAIService.java
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/internal/TAIConfigImpl.java
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/internal/TAIServiceImpl.java
  dev/com.ibm.ws.security.authentication.tai/test/com/ibm/ws/security/authentication/tai/internal/TAIConfigImplTest.java
  dev/com.ibm.ws.security.authentication.tai/test/com/ibm/ws/security/authentication/tai/internal/TAIServiceImplTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebRequest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebRequestImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
Labels: CLA Signed, ID reviewed, in:Security, release bug, team:Core Security

#8010 fix StackOverflowException
  dev/com.ibm.ws.security.audit.source/.classpath
  dev/com.ibm.ws.security.audit.source/bnd.bnd
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/JMXMBeanAttributeEvent.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/JMXMBeanEvent.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/ParameterUtils.java
  dev/com.ibm.ws.security.audit.source/test/com/ibm/ws/security/audit/event/ParameterUtilsTest.java
Labels: CLA Signed, in:Security, release bug, team:Core Security

#8056 cleaning up impl bundles for OpenTracing 1.x
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/com.ibm.websphere.appserver.opentracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.2/com.ibm.websphere.appserver.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
  dev/com.ibm.websphere.appserver.thirdparty.opentracing.0.31.0/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.opentracing/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.2/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.3/bnd.bnd
  dev/com.ibm.ws.opentracing.1.1.cdi/bnd.bnd
  dev/com.ibm.ws.opentracing.1.1/bnd.bnd
  dev/com.ibm.ws.opentracing.1.2.cdi/bnd.bnd
  dev/com.ibm.ws.opentracing.1.2/bnd.bnd
  dev/com.ibm.ws.opentracing.1.3.cdi/bnd.bnd
  dev/com.ibm.ws.opentracing.1.3/bnd.bnd
  dev/com.ibm.ws.opentracing.cdi/bnd.bnd
  dev/com.ibm.ws.opentracing/bnd.bnd
Labels: CLA Signed

#8020 Porting error paths test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/.project
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/publish/servers/com.ibm.ws.concurrent.persistent.fat.errorpaths/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/publish/servers/com.ibm.ws.concurrent.persistent.fat.errorpaths/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/DerbyShutdownTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/ExtendedIllegalArgumentException.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/FailingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/ImmediateSkippingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/LoadClassTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/LookupTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/NextTenthOfSecondTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/NoExecutionsTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/NonSerializableTaskAndResult.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/PersistentErrorTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/ResultThatFailsSerialization.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/SharedCounterTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/SharedFailingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/SharedSkippingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/TaskThatFailsSerialization.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/TenSecondTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/TriggerThatFailsSerialization.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/TwoExecutionsTrigger.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8117 check for adress
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#8115 restore osgi.module.lock.timeout its default value prior to 4.11
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
Labels: CLA Signed

#8101 Change to cache BeanManager instead of looking it up always
  dev/com.ibm.ws.microprofile.health.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20Service.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/HealthCheck20CDIBeanInvoker.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/HealthCheck20Executor.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/impl/HealthCheck20CDIBeanInvokerImpl.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/impl/HealthCheck20ExecutorImpl.java
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTracker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckService.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckServiceImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/HealthCheckCDIBeanInvoker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/HealthExecutor.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/impl/HealthCheckCDIBeanInvokerImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/impl/HealthExecutorImpl.java
Labels: CLA Signed, team:Performance

#8132 Issue #8131: Use AllowedFFDC rather than ExpectedFFDC
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#8136 Change allows for custom schema and table names
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
Labels: CLA Signed

#8036 RealFlushServer: using older features to ensure java7 support
  dev/com.ibm.ws.logging_fat/publish/servers/RealFlushServer/server.xml
Labels: CLA Signed, noproductcode

#8134 Fix flag name
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.java
Labels: CLA Signed

#8142 Ensure tracked kafka partitions are cleaned up on shutdown
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/AckTracker.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaInput.java
Labels: CLA Signed

#8081 escape special characters from element name when used in OSGi filter
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/ConfigBasedRESTHandler.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#8126 Issue #8125: Update bnd.bnd to specify javac source and target
  dev/com.ibm.ws.el.3.0_fat/bnd.bnd
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#8143 Eclipse setting cleanup
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.reactive.messaging_fat_tck/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6/bnd.overrides
  dev/com.ibm.ws.security.audit.source/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#8124 8123 remove dummy tests
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSFDummyTest.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPDummyTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCDummyTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#8137 Clean FAT test to better wait for app stop
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/LifeCycle12Test.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West, test bug

#8145 Grant kafka test permission to connect to any hostname
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/apps/kafka/permissions.xml
Labels: CLA Signed, noproductcode

#8147 Pull in MP Rest Client 1.3.3 for latest TCK fixes
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#8149 update to MP Context Propagation 1.0
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.0.feature
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, team:Zombie Apocalypse

#8151 Enable App Manager and OSGi Console parallel activation
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.artifact-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.dynamicBundle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeedd-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appLifecycle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appmanager-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.classloading-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/osgiConsole-1.0/com.ibm.websphere.appserver.osgiConsole-1.0.feature
Labels: CLA Signed

#8153 Remove extra content from PostgreSQL server certificate to be compatible with IBM JCE impl
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/ssl-certs/server.crt
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#8160 Revert "Enable App Manager and OSGi Console parallel activation"
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.artifact-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.dynamicBundle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeedd-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appLifecycle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appmanager-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.classloading-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/osgiConsole-1.0/com.ibm.websphere.appserver.osgiConsole-1.0.feature
Labels: CLA Signed

#8109 GA microProfile-3.0
  dev/build.image/build.gradle
  dev/build.image/packaging/debuild/scripts/openliberty
  dev/build.image/packaging/rpmbuild/SOURCES/scripts/openliberty
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics-2.0-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics2.0-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/com.ibm.websphere.appserver.microProfile-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.0/com.ibm.websphere.appserver.mpMetrics-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/com.ibm.websphere.appserver.mpRestClient-1.3.feature
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed, DO NOT MERGE

#8161 Issue 8159: Added the deferServletLoad=false server property in the s…
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/servers/Health20TCKServer/server.xml
Labels: CLA Signed, noproductcode

#8168 Update Notices for 19.0.0.7
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#8163 Remove extra content from postgresql cert
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest-native/resources/security/server.crt
Labels: team:Zombie Apocalypse, test bug

#8135 Remove beta tag from <properties.postgresql> element to make it GA
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#8165 Enable javax.net.debug trace for testcontainers buckets
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/fat/src/com/ibm/ws/rest/handler/validator/cloudant/fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/topology/utils/JULPipe.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7883 Porting persistent_fat_compatibility test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/.project
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/fat/src/com/ibm/ws/concurrent/persistent/fat/compatibility/CommonUtils.java
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/fat/src/com/ibm/ws/concurrent/persistent/fat/compatibility/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/fat/src/com/ibm/ws/concurrent/persistent/fat/compatibility/FatTestConcurrentCompatible.java
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/publish/files/config/disableTaskExecuteServer.xml
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/publish/files/config/enableTaskExecuteServer.xml
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/publish/servers/com.ibm.ws.concurrent.persistent.fat.compatibility/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/publish/servers/com.ibm.ws.concurrent.persistent.fat.compatibility/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/test-applications/PersistentExecutor/src/com/ibm/test/servlet/LongRunningTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/test-applications/PersistentExecutor/src/com/ibm/test/servlet/ScheduleStartServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/test-applications/PersistentExecutor/src/com/ibm/test/servlet/SimpleTask.java
  dev/fattest.simplicity/src/componenttest/topology/database/DerbyEmbeddedUtilities.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8082 Porting execdisabled test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/.project
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/fat/src/com/ibm/ws/concurrent/persistent/fat/execdisabled/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/fat/src/com/ibm/ws/concurrent/persistent/fat/execdisabled/PersistentExecutorExecutionDisabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/publish/servers/com.ibm.ws.concurrent.persistent.fat.execdisabled/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/publish/servers/com.ibm.ws.concurrent.persistent.fat.execdisabled/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/test-applications/persistentnoexectest/src/web/HourlyTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/test-applications/persistentnoexectest/src/web/ImmediateTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/test-applications/persistentnoexectest/src/web/NamedTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/test-applications/persistentnoexectest/src/web/PersistentExecDisabledTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8170 Correct maven coordinates in feature file
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.3.feature
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#8174 Issue 8173: Update timeout on ContextManagerTest
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#8167 Rework console log test
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/LogLevelPropertyTest.java
Labels: CLA Signed, noproductcode, test bug

#8182 Add small wait to make sure server.xml change is recognized
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ActivationTypeTest.java
Labels: CLA Signed, noproductcode, test bug

#8178 test config & validation REST endpoints for app-defined connection factory from an embedded resource adapter
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/service/ConnectionFactoryService.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/publish/servers/com.ibm.ws.rest.handler.config.appdef.fat/server.xml
  dev/com.ibm.ws.rest.handler.config_fat/test-applications/AppDefResourcesApp/src/test/resthandler/config/appdef/ejb/AppDefinedResourcesBean.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8177 Update pii collection to match CL
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#8175 Porting persistant_feature test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_feature/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_feature/.project
  dev/com.ibm.ws.concurrent.persistent_fat_feature/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_feature/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_feature/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_feature/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_feature/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_feature/fat/src/com/ibm/ws/concurrent/persistent/feature/ConcurrentPersistentFeatureFATTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/fat/src/com/ibm/ws/concurrent/persistent/feature/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/persistent_fat_feature.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_feature/publish/files/features/persistentExecutorTestFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_feature/publish/files/features/testFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_feature/publish/servers/com.ibm.ws.concurrent.persistent.feature.fat/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_feature/publish/servers/com.ibm.ws.concurrent.persistent.feature.fat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-applications/CPFeatureApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-applications/CPFeatureApp/src/com/ibm/feature/ConcurrentPersistentFeatureServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-applications/CPFeatureApp/src/com/ibm/feature/NoDbOpTestTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-bundles/userFeature/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-bundles/userFeature/src/test/concurrent/persistent/feature/TaskStoreTester.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-bundles/userFeature/src/test/concurrent/persistent/feature/internal/ExecutorFactoryServiceImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_feature/userFeature.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8091 Porting initial pooling test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.project
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/fat/src/com/ibm/ws/concurrent/persistent/fat/initial/polling/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/fat/src/com/ibm/ws/concurrent/persistent/fat/initial/polling/InitialPollingTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/publish/servers/com.ibm.ws.concurrent.persistent.fat.polling/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/publish/servers/com.ibm.ws.concurrent.persistent.fat.polling/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/test-applications/initialpollingtest/src/web/ManagedCountingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/test-applications/initialpollingtest/src/web/PersistentExecutorsTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/test-applications/initialpollingtest/src/web/RepeatingTrigger.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8190 Set qualifier correctly for ifix builds
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#8051 Porting delayexec test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/.project
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/fat/src/com/ibm/ws/concurrent/persistent/delayexec/DelayExecutionFATTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/fat/src/com/ibm/ws/concurrent/persistent/delayexec/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/persistent_fat_delayexec.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/publish/files/features/testFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/publish/servers/com.ibm.ws.concurrent.persistent.delayexec.fat/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/publish/servers/com.ibm.ws.concurrent.persistent.delayexec.fat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test-applications/DelayExecution/src/web/NoDbOpTestTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test-applications/DelayExecution/src/web/PersistentExecutorsTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test-bundles/userFeature/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test-bundles/userFeature/src/test/concurrent/persistent/delayexec/internal/TestServiceImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test_feature.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7958 Adding a check for https security endpoint for each FAT Test
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
Labels: CLA Signed, noproductcode

#8065 Update felix scr
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#8200 Move com.ibm.websphere.appserver.api.security.spnego to Open Liberty
  dev/com.ibm.websphere.appserver.api.security.spnego/.classpath
  dev/com.ibm.websphere.appserver.api.security.spnego/.gitignore
  dev/com.ibm.websphere.appserver.api.security.spnego/.project
  dev/com.ibm.websphere.appserver.api.security.spnego/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.api.security.spnego/bnd.bnd
  dev/com.ibm.websphere.appserver.api.security.spnego/com.ibm.websphere.appserver.api.security.spnego.pom
Labels: CLA Signed, team:Continuous Delivery

#8188 FT 1.1: Do explicit counting of concurrent executions
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/async/AsyncOuterExecutorImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/async/QueuedFuture.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/QueuedFutureTest.java
Labels: CLA Signed

#8189 Fix timing issues in FutureShellTest
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/impl/FutureShellTest.java
Labels: CLA Signed

#8164 Update to MP Reactive Messaging 1.0 API and TCK
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#8186 Consume the Fault Tolerance 2.0.1 release
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#8112 Porting persistant_JCA test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_jca/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_jca/.project
  dev/com.ibm.ws.concurrent.persistent_fat_jca/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_jca/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_jca/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_jca/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_jca/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_jca/fat/src/fat/concurrent/persistent/jca/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/fat/src/fat/concurrent/persistent/jca/PersistRATest.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/publish/servers/com.ibm.ws.concurrent.persistent.fat.jca/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_jca/publish/servers/com.ibm.ws.concurrent.persistent.fat.jca/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-applications/fvtweb/src/web/PersistRAServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/PSETestResourceAdapter.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/RAResult.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/RASerializableTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/RASerializableTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/RATask.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/RATrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/package-info.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8193 MPContextPropagation 167 add tests to explore question that was raised about CDI context
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8156 Fix httpHostNameVerification attribute type
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#8199 Support putting encoded passwords in Oracle connectionProperties attr…
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/test/com/ibm/ws/jdbc/internal/InternalTest.java
Labels: CLA Signed

#8218 Fix server script missing ] message for debug launch
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#8191 Update org.eclipse.equinox.region from 1.4.300.v20181116-1551 to 1.4.500.v20190710-1831
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.eclipse.equinox.region/bnd.bnd
Labels: CLA Signed

#8224 Fix up eclipse settings after moving new projects to open liberty
  dev/com.ibm.ws.app.manager.sar/.settings/bndtools.core.prefs
  dev/com.ibm.ws.app.manager.sar/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6.2/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.core.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.jaxws/.project
  dev/com.ibm.ws.org.apache.cxf.ws.security/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.ws.security/build.gradle
  dev/com.ibm.ws.org.apache.ws.security.wss4j/build.gradle
  dev/com.ibm.ws.webcontainer.security.provider/.classpath
  dev/com.ibm.ws.webcontainer.security.provider/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.webcontainer.servlet.3.0.factories/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.wssecurity.saml/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.wssecurity/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.wssecurity/src/com/ibm/ws/wssecurity/cxf/interceptor/WSSecuritySamlTokenInterceptor.java
Labels: CLA Signed, team:Performance

#8237 BB 265329: Restrict fat_init_pooling to java 8+
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/bnd.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8210 Fix to allow CDI runtime extensions to be hot added
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/RuntimeFactory.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/AbstractCDIRuntime.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/.classpath
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/HotAddMPConfig.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/HotAddMPConfig/noApp/HotAddApp.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/HotAddMPConfig/noMPConfig/HotAddMPConfig.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/HotAddMPConfig/withApp/HotAddApp.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/HotAddMPConfig/withMPConfig/HotAddMPConfig.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/HotAddMPConfig/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/HotAddMPConfig/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/hotAddMPConfigApp/src/com/ibm/ws/microprofile/config/hotadd/HotAddMPConfigServlet.java
Labels: CLA Signed

#8202 Zip reaper fix.
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
Labels: CLA Signed

#5036 ServletContext.getRealPath() shouldn't return null for nonexistent files
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#8245 EJB Remote_FAT wait after restoring server config
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/RemoteTests.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#8090 Fix HttpServletMapping.getPattern for /* mapping
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletRequest40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/wsspi/webcontainer40/util/URIMatcher40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCGetMappingSlashStarTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestGetMappingSlashStar.war/src/testgetmappingslashstar/war/servlets/GetMappingServletSlashStar.java
Labels: CLA Signed, release bug

#8179 Porting persistant_mbean test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/.project
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/fat/src/com/ibm/ws/concurrent/persistent/fat/mbean/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/fat/src/com/ibm/ws/concurrent/persistent/fat/mbean/PersistentExecutorMBeanTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/files/server2.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/servers/com.ibm.ws.concurrent.persistent.fat.mbean/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/servers/com.ibm.ws.concurrent.persistent.fat.mbean/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/test-applications/persistentmbeantest/src/web/MBeanCounterCallable.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/test-applications/persistentmbeantest/src/web/PersistentExecMBeanTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8244 Fix BundleInstallOriginBundleListener
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleInstallOriginBundleListener.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureManagerTest.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/BundleOriginTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.origin.system-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.origin.user-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.origin.bundle/.gitignore
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.origin.bundle/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.origin.bundle/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.origin.bundle/src/test/origin/bundle/Activator.java
  dev/com.ibm.ws.kernel.feature_fat/test.origin.bundle.system.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.origin.bundle.user.bnd
Labels: CLA Signed

#8238 SCR does not handle when configurations are deleted while it is using them
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#8201 add ui hardening
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/internal/resources/OAuthMessages.nlsprops
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidator.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/EndpointUtils.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/TokenExchange.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/UIAccessTokenBuilder.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/EndpointUtilsTest.java
Labels: CLA Signed, L2 Reviewed

#8256 Add trace to kafka connector
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/ConsumerRebalanceListenerImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/ConsumerRecordsImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/KafkaConsumerImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/KafkaProducerImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/AdapterFactoryImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SimpleRxMessagingServer/bootstrap.properties
Labels: CLA Signed

#8257 Sort cnf/oss_dependencies.maven and remove duplicates
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, noproductcode, team:MicroProfileUK

#8241 better error msg
  dev/com.ibm.ws.security.spnego/resources/com/ibm/ws/security/spnego/internal/resources/SpnegoMessages.nlsprops
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/Krb5Util.java
Labels: CLA Signed, ID reviewed

#8267 Add a doPriv to AbstractJaxWsWebEndpoint
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/endpoint/AbstractJaxWsWebEndpoint.java
Labels: CLA Signed

#8258 Update org.eclipse.osgi version from 3.15.0.v20190618-1815 to 3.15.0.v20190715-1310
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/bnd.bnd
Labels: CLA Signed

#8227 Correctly sequence createJFAPChain
  dev/com.ibm.ws.messaging.comms.client/bnd.bnd
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/CommsOutboundChain.java
Labels: CLA Signed

#8209 RPM/DEB Updates to Building Os Native Packages for Open Liberty
  dev/build.image/build.gradle
  dev/build.image/packaging/.gitignore
  dev/build.image/packaging/buildOsNativePackages.sh.template
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed

#8235 Create MP RM message bundle
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/.classpath
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/Batcher.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaInput.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutgoingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutput.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/classloader/package-info.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/package-info.java
Labels: CLA Signed

#8265 Add adminCenter attributes to openidConnectServer feature
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
Labels: CLA Signed

#8106 Add WLP-Activation-Type header for parallel activation
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.artifact-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.channelfw-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.dynamicBundle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.httptransport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.injection-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeeCompatible-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeeCompatible-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeePlatform-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeePlatform-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeePlatform-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeedd-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeeddSchema-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.servlet-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.requestProbes-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appLifecycle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appmanager-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.classloading-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
Labels: CLA Signed

#8253 OL#8252: Eclipselink: Deliver bug 547173
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed, in:JPA, team:Blizzard

#8261 Add oidcServer dependency on com.ibm.ws.webcontainer.security.provider
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
Labels: CLA Signed, team:Continuous Delivery

#8247 Issue #8246: Minor JSP 2.3 FAT cleanup
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava8Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerHttpUnit.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#8129 Issue #8128: Minor cleanup of the code.
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/wsspi/webcontainer40/util/URIMatcher40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
Labels: CLA Signed, in:Web Components, team:Sirius

#7658 Issue #1770: Update missing translation key and add FAT
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContainerInitializerExceptionTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SCIExceptionTest.jar/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SCIExceptionTest.jar/src/com/ibm/ws/servlet40/exception/sci/OnStartupExceptionSCI.java
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed, ID Required, ID reviewed, L2 ReviewNotRequired, in:Web Components, noproductcode, release bug, team:Sirius

#8275 read during close timing issue
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/WsocConnLink.java
Labels: CLA Signed, in:Web Components, team:Sirius

#8292 Revert "Correctly sequence createJFAPChain"
  dev/com.ibm.ws.messaging.comms.client/bnd.bnd
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/CommsOutboundChain.java
Labels: CLA Signed

#8254 translatable messages for the config and validation endpoints
  dev/com.ibm.websphere.rest.handler/bnd.bnd
  dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/ConfigBasedRESTHandler.java
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/package-info.java
  dev/com.ibm.ws.rest.handler.config/resources/com/ibm/ws/rest/handler/config/resources/CWWKOMessages.nlsprops
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/ConfigRESTHandler.java
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/package-info.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/fat/src/com/ibm/ws/rest/handler/validator/cloudant/fat/ValidateCloudantTest.java
  dev/com.ibm.ws.rest.handler.validator.jca/resources/com/ibm/ws/rest/handler/validator/jca/resources/CWWKOMessages.nlsprops
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/package-info.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/DataSourceValidator.java
  dev/com.ibm.ws.rest.handler.validator/resources/com/ibm/ws/rest/handler/validator/resources/CWWKOMessages.nlsprops
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/package-info.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDataSourceTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#8283 Enable scr metadata cache support
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
  dev/com.ibm.ws.org.apache.felix.scr/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.org.apache.felix.scr/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed

#8248 Enable discovery of revocation endpoint (Issue 8250)
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OIDCConstants.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcDiscoveryProviderConfig.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
Labels: CLA Signed

#8130 Porting persistant_oneexec test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/.project
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/OneExecutorRunsAllTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/oneexec_persistent_fat.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/publish/files/features/singletonTestFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/publish/servers/com.ibm.ws.concurrent.persistent.fat.oneexec/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/publish/servers/com.ibm.ws.concurrent.persistent.fat.oneexec/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/singletonTestFeature.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/NamedTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/OneExecutorRunsAllTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/RepeatingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/RepeatingTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-bundles/singletonTestFeature/src/test/feature/ejb/singleton/SingletonTriggerTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8286 For non-english languages, merge with en message file
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/common/js/globalization.js
Labels: CLA Signed, team:Admin Center

#8310 Set HealthCheckService on AppTracker for mpHealth 1.0
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckServiceImpl.java
Labels: CLA Signed, team:Performance

#8278 Add Kafka test using a custom data type
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/AbstractKafkaTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/KafkaTestClient.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/SimpleKafkaReader.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/SimpleKafkaWriter.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaSerializerTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/MyData.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/MyDataDeserializer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/MyDataMessagingBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/MyDataSerializer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/FATSuite.java
Labels: CLA Signed, noproductcode

#8220 Porting persistant_simctrl test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/.project
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/controllerTestFeature.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/fat/src/com/ibm/ws/concurrent/persistent/fat/simctrl/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/fat/src/com/ibm/ws/concurrent/persistent/fat/simctrl/SimulatedControllerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/persistent_fat_simctrl.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/files/features/controllerTestFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/files/features/simulatedController-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/servers/com.ibm.ws.concurrent.persistent.fat.simctrl/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/servers/com.ibm.ws.concurrent.persistent.fat.simctrl/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-applications/persistctrltest/src/web/RepeatTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-applications/persistctrltest/src/web/RepeatTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-applications/persistctrltest/src/web/SimulatedControllerPXTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-bundles/simcontroller/src/test/concurrent/persistent/fat/simctrl/SimulatedController.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8259 Improve init_pooling test failure logic
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/test-applications/initialpollingtest/src/web/PersistentExecutorsTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8301 Increase wait time on jobwaiter
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayDeserializeServlet.java
Labels: CLA Signed, noproductcode, test bug

#8308 Allow registration update of public OAuth clients to use asterisk for client secret
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.java
Labels: CLA Signed, team:Security SSO

#8313 Disable Regenerate button on personalTokenManagement when flag not set
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/common/css/tool.css
Labels: CLA Signed

#7768 export jsf-2.3 impl classes as third-party
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jsfApiStub-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.websphere.appserver.jsfApiStub-2.3/.gitignore
  dev/com.ibm.websphere.appserver.jsfApiStub-2.3/.project
  dev/com.ibm.websphere.appserver.jsfApiStub-2.3/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPI.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/src/com/ibm/ws/jsf23/fat/thirdpartyapi/ThirdPartyBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#8041 export jsf-2.2 impl classes as third-party
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jsfApiStub-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.jsfApiStub-2.2/.project
  dev/com.ibm.websphere.appserver.jsfApiStub-2.2/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#8299 Fixup from review of pull request #8244
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleInstallOriginBundleListener.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.origin.bundle/src/test/origin/bundle/Activator.java
Labels: CLA Signed

#8287 Update the description for Oracle connectionProperties to indicate th…
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed

#8319 Pass userid for single token deletes in usersTokenManagement
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/apiUtils.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/table.js
Labels: CLA Signed, team:Admin Center

#8333 change http client construction
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
Labels: CLA Signed

#8320 Issue 8309: Update Ldap fats after LoginBridge fix
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPReferralTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_TDS_EmptyInputsTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#8326 Don't use translated label for values in selection lists or radio button groups.
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/clientInputDialog.js
Labels: CLA Signed, team:Admin Center

#8331 Add event var to each event handler
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/accountManager.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/clientAdmin.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/clientInputDialog.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/common/js/tableUtils.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/common/js/utils.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/tokenManager.js
Labels: CLA Signed, team:Admin Center

#8347 Reestablish key traversal after Regenerate
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/table.js
Labels: CLA Signed, team:Admin Center

#8351 Permit restricted PostgreSQL operations
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/PostgreSQLHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcProxyMethod.java
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLTestServlet.java
Labels: CLA Signed, in:JDBC/JCA, team:Zombie Apocalypse

#7899 Jpa extended bean manager
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.jpa.container.v21.cdi/bnd.bnd
  dev/com.ibm.ws.jpa.container.v21.cdi/src/com/ibm/ws/jpa/container/v21/cdi/internal/BeanManagerInvocationHandler.java
  dev/com.ibm.ws.jpa.container.v21.cdi/src/com/ibm/ws/jpa/container/v21/cdi/internal/CDIJPAEMFPropertyProviderImpl.java
  dev/com.ibm.ws.jpa.container.v21.cdi/src/com/ibm/ws/jpa/container/v21/cdi/internal/HibernateNotifier.java
  dev/com.ibm.ws.jpa.container.v21.cdi/src/com/ibm/ws/jpa/container/v21/cdi/internal/IBMHibernateExtendedBeanManager.java
  dev/com.ibm.ws.jpa.container.v21.cdi/src/com/ibm/ws/jpa/container/v21/cdi/internal/JPAContainerCDIExtension.java
Labels: CLA Signed

#8327 Add hash value to xml to avoid cached file re-hashing
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed

#8370 Remove oss_ibm.maven.orig
  dev/cnf/oss_ibm.maven.orig
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#8323 initial experimentation with jcache for coordination
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.project
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_cache/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_cache/fat/src/com/ibm/ws/concurrent/persistent/fat/cache/ControllerCacheTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/fat/src/com/ibm/ws/concurrent/persistent/fat/cache/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverA/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverA/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverB/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverB/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/src/test/controller/cache/web/ControllerCacheTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/src/test/controller/cache/web/TestCacheEntryCreatedOrExpiredListener.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8352 Removing jsonifyGCEvent that uses GenericData
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
Labels: CLA Signed

#8359 Add oidcClient dependency on com.ibm.ws.webcontainer.security.provider
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
Labels: CLA Signed, team:Continuous Delivery

#8222 add userinfo support to implicit and propagation flows
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
Labels: CLA Signed

#8348 Block contextual operations from lazily enlisting CDI beans
  dev/com.ibm.ws.cdi.mp.context/bnd.bnd
  dev/com.ibm.ws.cdi.mp.context/resources/com/ibm/ws/cdi/mp/context/resources/CDI_MP_CONTEXT.nlsprops
  dev/com.ibm.ws.cdi.mp.context/src/com/ibm/ws/cdi/mp/context/ContextualInstanceSnapshot.java
  dev/com.ibm.ws.cdi.mp.context/src/com/ibm/ws/cdi/mp/context/WeldContextSnapshot.java
  dev/com.ibm.ws.cdi.mp.context/src/com/ibm/ws/cdi/mp/context/package-info.java
  dev/com.ibm.ws.concurrent.mp.1.0/resources/com/ibm/ws/concurrent/mp/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualRunnable.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualSupplierAction.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentCDITest.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
Labels: CLA Signed, L2 Reviewed, team:Zombie Apocalypse

#8263 Traudit
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/DateFormatHelper.java
Labels: CLA Signed

#8138 Porting persistant_retry test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_retry/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_retry/.project
  dev/com.ibm.ws.concurrent.persistent_fat_retry/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_retry/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_retry/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_retry/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_retry/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_retry/fat/src/com/ibm/ws/concurrent/persistent/fat/retry/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/fat/src/com/ibm/ws/concurrent/persistent/fat/retry/FailureRetryTests.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/publish/servers/com.ibm.ws.concurrent.persistent.fat.retry/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_retry/publish/servers/com.ibm.ws.concurrent.persistent.fat.retry/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/src/web/PersistentRetryTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/src/web/ProgrammableTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/src/web/RetryCallable.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/src/web/UpdateDatabaseServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8341 jaasLoginContextEntryRef for connection factories
  dev/com.ibm.ws.jca.1.7/src/com/ibm/ws/jca17/processor/service/ConnectionFactoryResourceBuilder.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/AbstractConnectionFactoryService.java
  dev/com.ibm.ws.jca.resourcedefinition.jms.2.0/src/com/ibm/ws/jca/processor/jms/service/JMSConnectionFactoryResourceBuilder.java
  dev/com.ibm.ws.jca/bnd.bnd
  dev/com.ibm.ws.jca/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jca/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/DataSourceValidator.java
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDSCustomLoginModuleTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jca.fat/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/validator-customLoginModule-Server/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/adapter/ConnectionSpecImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/adapter/DataSourceImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/adapter/ManagedConnectionImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/JMSConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/JMSConnectionImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/ManagedJMSConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/ManagedJMSQueueConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/ManagedJMSTopicConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-resourceadapter/src/org/test/validator/jmsadapter/NoOpSessionImpl.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, team:Zombie Apocalypse

#8372 Issue 8236: Fixed the AppTracker class to use the ApplicationStateLis…
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTracker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerServletContextListener.java
Labels: CLA Signed

#8366 Ensure the non-deferrable scheduled executor is used
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/MonitorHolder.java
Labels: CLA Signed

#8195 com.ibm.ws.jaxws.clientcontainer access control issues
  dev/com.ibm.ws.jaxws.clientcontainer/src/com/ibm/ws/jaxws/support/LibertyHTTPConduit.java
  dev/com.ibm.ws.jaxws.clientcontainer/src/com/ibm/ws/jaxws/support/LibertyHTTPTransportFactory.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#8360 PR for OIDC provider may get exception using Oracle database
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/db/DetectDatabaseType.java
Labels: CLA Signed, release bug, team:Security SSO

#8368 changed error message for 1430-1432E
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/internal/resources/OAuthMessages.nlsprops
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#8374 Make TimeoutStateImplTest more reliable
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/AsyncBulkheadStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/CircuitBreakerStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/MockScheduledExecutorService.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/MockScheduledFuture.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/MockScheduledTask.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/MockScheduledTaskMatcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/RetryStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/SyncBulkheadStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/policy/CircuitBreakerPolicyImpl.java
Labels: CLA Signed

#8381 Add a test for providing the kafka jar in a shared library
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/SharedLibMessagingBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/PlaintextTests.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SharedLibRxMessagingServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SharedLibRxMessagingServer/server.xml
Labels: CLA Signed, noproductcode

#8383 Fix double byte character encoding for OAuth client metatype API
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20ClientMetatypeService.java
Labels: CLA Signed, team:Security SSO

#8376 Enable discovery of app pw and app tokens endpts
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OIDCConstants.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20Request.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcDiscoveryProviderConfig.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
Labels: CLA Signed

#8157 Add com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6 bundle
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.gitignore
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/com/ibm/ws/jaxws22/cxf/rt/bindings/soap/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/com/ibm/ws/jaxws22/cxf/rt/bindings/soap/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/Messages.properties
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/RPCOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/ReadHeadersInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/Soap11FaultInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/Soap11FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/Soap12FaultInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/Soap12FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/interceptor/SoapOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/saaj/SAAJInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/saaj/SAAJOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/saaj/SAAJStreamWriter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/saaj/SAAJUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/tcp/ChannelIdParser.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/tcp/ChannelService.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/src/org/apache/cxf/binding/soap/tcp/SoapTcpUtils.java
Labels: CLA Signed, ID review not needed, L2 Reviewed

#8116 create jaxwsweb-2.3 auto feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxwsejb-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxwsweb-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxws-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxws-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.3/com.ibm.websphere.appserver.jaxws-2.3.feature
  dev/com.ibm.websphere.javaee.jaxws.2.3/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.web/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.webcontainer/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2/bnd.overrides
Labels: CLA Signed, in:Web Services, team:Bobcats

#8148 zip file cache introspector w/ fat tests
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/ZipCachingProperties.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingIntrospector.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingServiceImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileData.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileDataStore.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
  dev/com.ibm.ws.artifact_fat/bnd.bnd
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/DumpArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperMultipleIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATSuite.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCachingIntrospectorOutput.java
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipDumps/.gitignore
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipDumps/bootstrap.properties
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipDumps/server.xml
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipIntrospections/.gitignore
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipIntrospections/bootstrap.properties
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.zipIntrospections/server.xml
  dev/com.ibm.ws.artifact_fat/test-applications/HoldingServlet/resources/WEB-INF/lib/TestJar.jar
  dev/com.ibm.ws.artifact_fat/test-applications/HoldingServlet/src/com/ibm/ws/artifact/fat/zip/HoldingServlet.java
  dev/com.ibm.ws.artifact_fat/test-applications/testServlet1/resources/WEB-INF/lib/TestJar.jar
  dev/com.ibm.ws.artifact_fat/test-applications/testServlet1/src/com/ibm/ws/artifact/fat/servlet/TestServlet1.java
  dev/com.ibm.ws.artifact_fat/test-applications/testServlet2/src/com/ibm/ws/artifact/fat/servlet/TestServlet2.java
Labels: CLA Signed

#8154 Issue #8150: Update RESTHandler implementations to allow non-default …
  dev/com.ibm.websphere.rest.handler/bnd.bnd
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/ConfigBasedRESTHandler.java
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/handler/RESTResponse.java
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/handler/package-info.java
  dev/com.ibm.ws.jmx.connector.server.rest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.metrics.private/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.private/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsAuthenticationTest.java
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsAuthenticationServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsAuthenticationServer/server.xml
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/ConfigRESTHandler.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.rest.handler.validator/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/helper/ServletRESTResponseImpl.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/helper/ServletRESTResponseWithWriter.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/internal/service/RESTHandlerContainerImpl.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/wsspi/rest/handler/helper/DefaultAuthorizationHelper.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/wsspi/rest/handler/helper/RESTHandlerForbiddenError.java
  dev/com.ibm.ws.rest.handler/src/com/ibm/wsspi/rest/handler/helper/package-info.java
  dev/com.ibm.ws.rest.handler/test/com/ibm/wsspi/rest/handler/helper/MockRESTResponse.java
Labels: CLA Signed, team:Wendigo East

#8053 HADB Locking Scheme
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/HADBLogAvailabilityManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LibertyRecoveryDirectorImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LivingRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryAgent.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/build.gradle
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicCoreTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicDBTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicFSTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/defaultAttributesServer1/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/longLocalStaleTimeServer1/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/longPeerStaleTimeServer2/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/originalServer1/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/originalServer2/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/peerLockingDisabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/peerLockingEnabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD001/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD002/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/Simple2PCCloudServlet.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#8413 Unzip to temp directory to avoid multiple updates
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
Labels: CLA Signed, noproductcode, test bug

#8396 PR to Update trace in OAuth20EndpointServices
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
Labels: CLA Signed, team:Security SSO

#8400 Display messages missing from UI
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/index.jsp
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/table.js
Labels: CLA Signed, team:Admin Center

#8364 Extra Server Fix + Dir Update to Align with WAD
  dev/build.image/build.gradle
  dev/build.image/packaging/buildOsNativePackages.sh.template
  dev/build.image/packaging/debuild/openliberty/debian/postinst
  dev/build.image/packaging/debuild/openliberty/debian/postrm
  dev/build.image/packaging/debuild/scripts/openliberty
  dev/build.image/packaging/debuild/scripts/openliberty@.service
  dev/build.image/packaging/openliberty.spec.template
  dev/build.image/packaging/rpmbuild/SOURCES/scripts/openliberty
  dev/build.image/packaging/rules.template
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed

#8373 Remove ZipReaper stall warning
  dev/com.ibm.ws.artifact.zip/resources/com/ibm/ws/artifact/zip/internal/resources/ZipArtifactMessages.nlsprops
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
Labels: CLA Signed, ID review not needed, L2 Reviewed
