Repository OpenLiberty/open-liberty, pull requests merged in 2019-06, with the labels that each got.

#7689 Update to call new message and add some tracing
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLInvalidTrustTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/OutboundSSLLDAPTest.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
Labels: CLA Signed

#7686 Add check for negotiate
  dev/com.ibm.ws.security/src/com/ibm/ws/security/krb5/SpnegoUtil.java
Labels: CLA Signed

#7672 rely on transaction manager for enforcement of serial usage of transactions
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentTxApp/src/concurrent/mp/fat/tx/web/MPConcurrentTxTestServlet.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/SerialTransactionContextImpl.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/SuspendCount.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextProviderImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#7628 Update org.osgi.service.http.whiteboard to 1.1
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.osgi.service.http.whiteboard/bnd.bnd
Labels: CLA Signed

#7698 7694 - Adjust test timeout value
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/utils.java
Labels: CLA Signed

#7699 Give more clear error message when attempting to unwrap to non-interface class
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcWrapper.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#7705 Revert "Backport CXF 3.2.X fix "Handle null contracts" and others"
  dev/com.ibm.ws.jaxrs.2.0.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.0.common/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ConfigurationImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
Labels: CLA Signed

#7692 add waiting for httpEndpoint to both tests of merged PR# 7587
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#7708 Update bnd files to compile with and require Java 8 for jaxws 2.3 comps
  dev/com.ibm.ws.jaxws.2.3.web/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.webcontainer/bnd.bnd
Labels: CLA Signed, team:Performance

#7671 stop the server while ignoring CWWKW1001W to avoid warning messages
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/RealFlushTest.java
Labels: CLA Signed, noproductcode

#7713 add new method signature
  dev/com.ibm.ws.security/src/com/ibm/ws/security/krb5/SpnegoUtil.java
Labels: CLA Signed

#7669 Run timing sensitve FT TCK tests in full mode only
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck11Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTckLauncher.java
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
Labels: CLA Signed, noproductcode

#7716 NLS review update number two.
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages.nlsprops
Labels: CLA Signed

#7704 Add runtime update logging
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.brokenserver/bootstrap.properties
Labels: CLA Signed, noproductcode

#7715 Add error messages, tests, and delete duplicate property files
  dev/com.ibm.ws.kernel.boot.cmdline/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot.core/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/ReturnCode.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/ServerCommand.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessControlHelper.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerCommandClient.java
  dev/com.ibm.ws.kernel.boot.nested/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot_test/bnd.bnd
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/commands/ServerCommandClientTest.java
Labels: CLA Signed, ID reviewed

#7727 Issue #7724: Update mongo_fat with new SSL error message
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLInvalidTrustTest.java
Labels: CLA Signed, noproductcode, team:Blizzard, test bug

#7654 Properly cancel timer
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTimeoutManager.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
Labels: CLA Signed

#7682 Allow internal ConfigSources to be provided using DS
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/impl/Config13BuilderImpl.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/impl/Config13ProviderResolverImpl.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14BuilderImpl.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14ProviderResolverImpl.java
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#7726 Disable all trace for MP Config Cache test server
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/ClassLoaderCacheServer/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/Config, noproductcode, team:MicroProfileUK

#7714 hide internal properties from config REST endpoint and remove TODO
  dev/com.ibm.ws.jca.resourcedefinition.jms.2.0/src/com/ibm/ws/jca/processor/jms/service/JMSConnectionFactoryResourceBuilder.java
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/ConfigRESTHandler.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#7662 implementing unit conversion for Timed metric in JSON
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/helper/Util.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/writer/JSONMetricWriter.java
Labels: CLA Signed

#7707 Lazily create Jsonb object when it is first needed.
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonBProvider.java
Labels: CLA Signed, team:Performance

#7684 Portation of com.ibm.ws.jaxws.2.3.ejb bundle and creation com.ibm.websphereappserver.jaxwsejb-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxwsejb-2.3.feature
  dev/com.ibm.ws.jaxws.2.3.ejb/.project
  dev/com.ibm.ws.jaxws.2.3.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.ejb/build.gradle
  dev/com.ibm.ws.jaxws.2.3.ejb/findbugs.exclude.xml
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_cs.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_de.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_es.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_fr.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_hu.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_it.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_ja.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_ko.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_pl.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_pt_BR.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_ro.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_ru.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_zh.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/resources/com/ibm/ws/jaxws/ejb/internal/resources/JaxWsEJBMessages_zh_TW.nlsprops
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBHandlerResolver.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBInWarJaxWsModuleInfoBuilderExtension.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBJaxWsModuleInfoBuilder.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBJaxWsModuleInfoBuilderHelper.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBJaxWsWebEndpoint.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBMethodInvoker.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBPostInvokeInterceptor.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/EJBPreInvokeInterceptor.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/JaxWsEJBEndpointConfigurator.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/internal/JaxWsEJBConstants.java
  dev/com.ibm.ws.jaxws.2.3.ejb/src/com/ibm/ws/jaxws/ejb/package-info.java
Labels: CLA Signed, ID review not needed, L2 Reviewed, in:Web Services, team:Bobcats

#7731 Fix ability to run FATs without executing all unit tests
  dev/gradle/java.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#7771 Revert 7705
  dev/com.ibm.ws.jaxrs.2.0.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.0.common/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ConfigurableImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ConfigurationImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#7494 Add comments and change how generated.properties is stored
  dev/build.gradle
  dev/build.image/build.gradle
  dev/com.ibm.ws.artifact_fat/build.gradle
  dev/com.ibm.ws.artifact_fat_bvt/build.gradle
  dev/com.ibm.ws.cdi.annotations_fat/build.gradle
  dev/com.ibm.ws.cdi.api_fat/build.gradle
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/build.gradle
  dev/com.ibm.ws.cdi.beansxml_fat/build.gradle
  dev/com.ibm.ws.cdi.ejb_fat/build.gradle
  dev/com.ibm.ws.cdi.extension_fat/build.gradle
  dev/com.ibm.ws.cdi.jee_fat/build.gradle
  dev/com.ibm.ws.cdi.jndi_fat/build.gradle
  dev/com.ibm.ws.cdi.lifecycle_fat/build.gradle
  dev/com.ibm.ws.cdi.noncontextual_fat/build.gradle
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
  dev/com.ibm.ws.cdi.visibility_fat/build.gradle
  dev/com.ibm.ws.clientcontainer.cdi_fat/build.gradle
  dev/com.ibm.ws.logging.json_fat/build.gradle
  dev/com.ibm.ws.messaging.open_fat/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.social/build.gradle
  dev/com.ibm.ws.security.fat.common/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt_fat/build.gradle
  dev/com.ibm.ws.security.social_fat.oidcCertification/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/gradle/biz.aQute.bnd.gradle
  dev/gradle/subprojects/publish.gradle
  dev/settings.gradle
  dev/wlp-gradle/.project
  dev/wlp-gradle/biz.aQute.bnd.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/buildCacheSettings.gradle
  dev/wlp-gradle/init-scripts/build-scan.init.gradle
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/propertiesSettings.gradle
  dev/wlp-gradle/subprojects/anttaskdefs.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/jacoco.gradle
  dev/wlp-gradle/subprojects/publish.gradle
  dev/wlp-gradle/subprojects/repos.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Continuous Delivery

#7721 Fix chkpii error in com.ibm.ws.security.audit.source
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#7720 Fix chkpii message errors in com.ibm.ws.anno
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#7719 Fix chkpii errors in ssl messages file
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#7734 Delete and expose dupped messages
  dev/com.ibm.ws.kernel.feature.core/bnd.bnd
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/resources/package-info.java
  dev/com.ibm.ws.kernel.feature/bnd.bnd
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_cs.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_de.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_es.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_fr.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_hu.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_it.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_ja.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_ko.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_pl.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_pt_BR.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_ro.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_ru.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_zh.nlsprops
  dev/com.ibm.ws.kernel.feature/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed

#7776 validation for app-defined JCA connection factories
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/publish/servers/com.ibm.ws.rest.handler.config.appdef.fat/server.xml
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ConnectionImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ConnectionSpecImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/DataSourceImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ManagedConnectionImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ManagedJDBCConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/adapter/ResourceAdapterMetaDataImpl.java
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
Labels: CLA Signed, team:Zombie Apocalypse

#7791 Revert "Re-deliver improved version of PR #7356"
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/server.xml
  dev/com.ibm.ws.jmx.connector.local/src/com/ibm/ws/jmx/connector/local/LocalConnectorActivator.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed

#7710 Stop writing plugin-cfg.xml on every startup
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed

#7678 Move long tests to full mode only
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIAnnotationsDisabledTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIBulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDICircuitBreakerTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIFallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDITimeoutTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/TxRetryReorderedTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/TxRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageServlet.java
Labels: CLA Signed, noproductcode

#7808 remove non static public field
  dev/com.ibm.ws.cdi.jee_fat/test-applications/jeeInjectionTargetTest.war/src/cdi12/helloworld/jeeResources/test/JEEResourceExtension.java
  dev/com.ibm.ws.cdi.jee_fat/test-applications/jeeInjectionTargetTest.war/src/cdi12/helloworld/jeeResources/test/LoggerServlet.java
Labels: CLA Signed, noproductcode

#7810 Avoid multiple bean validation when CDI and JAX-RS are both enabled
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.beanvalidation/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BeanValidationApplication.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/CheckForSingleValidationResource.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeObject.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeObjectValidator.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeReturnObject.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeReturnObjectValidator.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/ValidSomeReturnString.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/ValidSomeString.java
  dev/com.ibm.ws.jaxrs.2.0.server/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.server/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsInvoker.java
Labels: CLA Signed, in:JAX-RS, release bug, team:Wendigo West

#7765 Use read/write locks for synchronization
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStore.java
Labels: CLA Signed

#7690 Perf improvement during getLogger flow
  dev/com.ibm.ws.kernel.boot.logging/src/com/ibm/ws/kernel/boot/logging/WsLogManager.java
Labels: CLA Signed

#7794 first step toward using standard MPConfig property names
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#7805 validation for app-defined JMS connection factories
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
Labels: CLA Signed, team:Zombie Apocalypse

#7696 Fix network timeout when the JDBC driver has it's own default.
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSConnectionRequestInfoImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#7801 Issue #7800: Stabilize the couchdb-1.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/couchdb-1.0/resources/l10n/com.ibm.websphere.appserver.couchdb-1.0.properties
Labels: CLA Signed, team:Blizzard

#7687 Issue #6379: Ulimit boost change
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/UlimitTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.ulimit.fat/bootstrap.properties
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.ulimit.fat/server.xml
  dev/com.ibm.ws.kernel.boot_fat/test-applications/ulimitApp/src/com/ibm/ws/kernel/boot/ulimit/fat/uLimitAppServlet.java
Labels: CLA Signed

#7646 Increase wait time between file deletion retry
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode

#7807 Issue #7763: Improve JPA FAT application starts
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Callback_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Callback_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Inheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Inheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXMany_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXMany_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXOne_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXOne_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXMany_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXMany_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXOne_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXOne_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/publish/servers/JPA10Server/server.xml
  dev/com.ibm.ws.jpa_spec10_fat/test-applications/jpa10/callback/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec10_fat/test-applications/jpa10/callback/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec10_fat/test-applications/jpa10/callback/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec10_fat/test-applications/jpa10/inheritance/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec10_fat/test-applications/jpa10/inheritance/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_NoInheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_NoInheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_NoInheritance_WebLib.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_YesInheritance_DDOvrd_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_YesInheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_YesInheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dfi/JPA10Injection_DFI_YesInheritance_WebLib.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_NoInheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_NoInheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_NoInheritance_WebLib.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_YesInheritance_DDOvrd_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_YesInheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_YesInheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/dmi/JPA10Injection_DMI_YesInheritance_WebLib.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/jndi/JPA10Injection_JNDI_EJB.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/jndi/JPA10Injection_JNDI_Web.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/injection/jndi/JPA10Injection_JNDI_WebLib.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/publish/servers/JPAServer/server.xml
  dev/com.ibm.ws.jpa_spec10_injection_fat/publish/servers/JPAServerDFI/server.xml
  dev/com.ibm.ws.jpa_spec10_injection_fat/publish/servers/JPAServerDMI/server.xml
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPA20QueryLockMode_EJB.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPA20QueryLockMode_WEB.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20Server/server.xml
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard, test bug

#7785 Remove no verify option
  dev/fattest.simplicity/.settings/org.eclipse.jdt.core.prefs
  dev/fattest.simplicity/.settings/org.eclipse.jdt.ui.prefs
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: team:MicroProfileUK

#7799 Update to very latest version of SmallRye RM and MP api
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.messaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/bnd.bnd
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/Incoming.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/Outgoing.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/Connector.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/ConnectorFactory.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/ConnectorLiteral.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/IncomingConnectorFactory.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/OutgoingConnectorFactory.java
  dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/src/org/eclipse/microprofile/reactive/messaging/spi/package-info.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/com/ibm/ws/microprofile/reactive/messaging/OLReactiveMessagingExtension.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/AbstractMediator.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/ChannelRegistar.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/ChannelRegistry.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/Invoker.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/MediatorConfiguration.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/MediatorFactory.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/ProcessingException.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/ProcessorMediator.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/PublisherMediator.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/Shape.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/StreamTransformerMediator.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/SubscriberMediator.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/SubscriberWrapper.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/WeavingException.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/annotations/Broadcast.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/annotations/Emitter.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/annotations/Merge.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/annotations/Stream.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/CollectedMediatorMetadata.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/EmitterImpl.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/LazySource.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/MediatorManager.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/ReactiveMessagingExtension.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/extension/StreamProducer.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/impl/ConfiguredChannelFactory.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/impl/ConnectorConfig.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/impl/InternalChannelRegistry.java
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/impl/LegacyConfiguredChannelFactory.java
Labels: CLA Signed, in:MicroProfile/Reactive, team:MicroProfileUK

#7786 Revert "Update EclipseLink in OpenLiberty"
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed

#7819 Add JNDI trace
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.BadAppServer/bootstrap.properties
Labels: CLA Signed, noproductcode

#7691 Update second metatype.properties file
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#7804 Add debug for file monitor
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/DirectoryUpdateMonitor.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/FileUpdateMonitor.java
Labels: CLA Signed

#7820 validation REST endpoint for app-defined topicConnectionFactory
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJMSTest.java
  dev/com.ibm.ws.rest.handler.config_fat/test-applications/AppDefResourcesApp/src/test/resthandler/config/appdef/ejb/AppDefinedResourcesBean.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/jmsadapter/JMSTopicConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/jmsadapter/JMSTopicConnectionImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/jmsadapter/ManagedJMSTopicConnectionFactoryImpl.java
  dev/com.ibm.ws.rest.handler.config_fat/test-resourceadapter/src/org/test/config/jmsadapter/NoOpSessionImpl.java
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jms/JMSConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJMSTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#7837 start of yaml for validation endpoint
  dev/com.ibm.ws.rest.handler.validator_fat/.classpath
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.openapi.fat/bootstrap.properties
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.openapi.fat/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/src/web/ValidationOpenAPITestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7825 json unit conversion for Timed metric
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/helper/Util.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/writer/JSONMetricWriter.java
Labels: CLA Signed

#7838 PII NLS 19006 Emergency Shipment
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_cs.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_de.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_es.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_fr.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_hu.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_it.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ja.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ko.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_pl.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_pt_BR.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ru.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_zh.nlsprops
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_zh_TW.nlsprops
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages_es.nlsprops
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages_ja.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_es.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_ja.nlsprops
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_cs.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_de.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_es.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_fr.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_hu.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_it.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ja.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ko.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_pl.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_pt_BR.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ru.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_zh.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_zh_TW.nlsprops
Labels: CLA Signed, L2 Reviewed

#7795 Changed TBWSessionStorer to non-configurable 1 second
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionContext.java
Labels: CLA Signed

#7842 Create a new ApplicationInfo object if the Application was replaced.
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsServerFactoryBean.java
Labels: CLA Signed, team:Performance

#7769 catch block moved to prevent SOOB exception in jsf 2.2
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/view/facelets/util/Classpath.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#7841 fix trace agedtimeout adding mcwrapper id
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
Labels: CLA Signed, team:Zombie Apocalypse

#7821 Switching Metrics to use artifactory and removing source
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/bnd.bnd
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/ConcurrentGauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Counter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Counting.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/DefaultMetadata.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Gauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Histogram.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Metadata.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetadataBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Meter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Metered.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Metric.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetricFilter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetricID.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetricRegistry.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetricType.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/MetricUnits.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Sampling.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Snapshot.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Tag.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/Timer.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/ConcurrentGauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/Counted.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/Gauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/Metered.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/Metric.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/RegistryType.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/Timed.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/annotation/package-info.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/src/org/eclipse/microprofile/metrics/package-info.java
Labels: CLA Signed

#7857 Update smallrye code to work with bnd tools in eclipse.
  dev/com.ibm.ws.io.smallrye.reactive.messaging/src/io/smallrye/reactive/messaging/PublisherMediator.java
Labels: CLA Signed, team:Performance

#7858 include header and query parameters in the yaml for the validation REST endpoint
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7855 validation endpoint must avoid logging password to FFDC and trace
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/DataSourceValidator.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
Labels: CLA Signed, team:Zombie Apocalypse

#7633 Issue #7632: Add EclipseLink property to disable #7207 fix
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/AbstractJPAProviderIntegration.java
Labels: CLA Signed, priority/high

#7859 Add additional JPA trace
  dev/com.ibm.ws.jpa.container.eclipselink/src/com/ibm/ws/jpa/container/eclipselink/logging/LogChannel.java
Labels: CLA Signed

#7861 Update .classpath files to make things build in eclipse again.
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.0/.classpath
  dev/com.ibm.ws.microprofile.health.2.0/.classpath
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#7832 Fix IllegalStateException on ConfigurationStore
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStorageHelper.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStore.java
Labels: CLA Signed, bug, release bug

#7860 Do not use the 27.0.1-jre version of google guava.
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, noproductcode, team:Performance

#7847 Added wait statements to resolve server connection issues
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsAuthenticationTest.java
Labels: CLA Signed, noproductcode

#7872 dataSource validation result and example values
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7836 Upgrade to yasson-1.0.4
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.clientcontainer.json_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.bnd
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.overrides
  dev/com.ibm.ws.org.eclipse.yasson.1.0/resources/yasson-messages.properties
Labels: CLA Signed, team:Zombie Apocalypse

#7873 Add Trace in EJB Async FAT
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncRemoteServer/bootstrap.properties
Labels: CLA Signed, in:EJB Container, noproductcode

#7616 Make remove ALPN call on connection error. Also don't ALPN init until
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLAlpnNegotiator.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannel.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannelFactoryImpl.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLConnectionLink.java
Labels: CLA Signed

#7886 Revert "Avoid multiple bean validation when CDI and JAX-RS are both enabled"
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.beanvalidation/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BeanValidationApplication.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/CheckForSingleValidationResource.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeObject.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeObjectValidator.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeReturnObject.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/SomeReturnObjectValidator.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/ValidSomeReturnString.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/ValidSomeString.java
  dev/com.ibm.ws.jaxrs.2.0.server/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.server/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsInvoker.java
Labels: CLA Signed

#7890 Revert "Issue #6379: Ulimit boost change"
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/UlimitTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.ulimit.fat/bootstrap.properties
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.ulimit.fat/server.xml
  dev/com.ibm.ws.kernel.boot_fat/test-applications/ulimitApp/src/com/ibm/ws/kernel/boot/ulimit/fat/uLimitAppServlet.java
Labels: CLA Signed

#7756 update test JavaDoc that still refers to MP Concurrency
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/ConcurrencyConfigBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentTxApp/src/concurrent/mp/fat/tx/web/MPConcurrentTxTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7881 yaml for validation of multiple data sources and connection factory
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.openapi.fat/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7885 update to release candidate 3 of MP Context Propagation
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.0.feature
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextBuilderImpl.java
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, team:Zombie Apocalypse

#7877 Remove temporary method from cert utility
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/DefaultSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.java
Labels: CLA Signed

#7834 Specify hostname in server debug command
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#7884 Force jaxws to start late to allow proper parallel bundle processing
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
Labels: CLA Signed, team:Performance

#7852 Issue 7683: Update JPA feature descriptions
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.1/resources/l10n/com.ibm.websphere.appserver.jpa-2.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.2/resources/l10n/com.ibm.websphere.appserver.jpa-2.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.1/resources/l10n/com.ibm.websphere.appserver.jpaContainer-2.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.2/resources/l10n/com.ibm.websphere.appserver.jpaContainer-2.2.properties
Labels: CLA Signed, ID Required, ID reviewed

#7905 Issue #7904: Ignore Quiesce Errors in EJB Async FAT
  dev/com.ibm.ws.ejbcontainer.async_fat/fat/src/com/ibm/ws/ejbcontainer/async/fat/tests/AsyncRemoteTests.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard

#7802 Ported the configupdate test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.project
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/PersistentExecutorConfigUpdateTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/src/web/FixedDelayTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/src/web/PersistentExecutorConfigUpdateTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7903 Use JDK-only ping to determine Docker Host availability
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/topology/utils/HttpsRequest.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#7910 Ignore exception on unregister
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/WSContext.java
Labels: CLA Signed

#7907 Clear interruptible flag during recycle
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
Labels: CLA Signed

#7894 Fix false positive readiness check status before application starts up
  dev/com.ibm.ws.microprofile.health.2.0/resources/com/ibm/ws/microprofile/health20/resources/Health20.nlsprops
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20HttpResponseBuilder.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/.classpath
  dev/com.ibm.ws.microprofile.health.2.0_fat/.project
  dev/com.ibm.ws.microprofile.health.2.0_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.health.2.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.health.2.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.health.2.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/MultipleHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/.gitignore
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DelayedHealthCheck/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DelayedHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/MultipleHealthCheck/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/MultipleHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/src/com/ibm/ws/microprofile/health20/delayed/health/check/app/DelayedLivenessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/src/com/ibm/ws/microprofile/health20/delayed/health/check/app/DelayedReadinessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/src/com/ibm/ws/microprofile/health20/delayed/health/check/app/DelayedServlet.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/MultipleHealthCheckApp/src/com/ibm/ws/microprofile/health20/multiple/health/checks/app/TestLivenessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/MultipleHealthCheckApp/src/com/ibm/ws/microprofile/health20/multiple/health/checks/app/TestReadinessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/servers/Health20TCKServer/server.xml
  dev/com.ibm.ws.microprofile.health/.classpath
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTracker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckHttpResponseBuilder.java
Labels: CLA Signed, L2 Reviewed

#7944 Update eclipse settings to Java 7 to match bnd settings
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#7839 Use Xdump options on all versions of IBM JDK
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, test bug

#7934 Add log marks
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/DelayedVariableTests.java
Labels: CLA Signed, noproductcode, test bug

#7917 yaml for validation of JMS connection factories and cloudantDatabase
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.openapi.fat/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7965 Revert "Update eclipse settings to Java 7 to match bnd settings"
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode

#7966 Revert "Ported the configupdate test bucket to open liberty"
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.project
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/PersistentExecutorConfigUpdateTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/.gitignore
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/src/web/FixedDelayTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/test-applications/persistcfgtest/src/web/PersistentExecutorConfigUpdateTestServlet.java
Labels: CLA Signed, noproductcode

#7914 make appInfo appName same as J2eeName.application
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
Labels: CLA Signed

#7936 7935-Send Settings Frame from the client as one unit
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, noproductcode

#7932 setting cookie path
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ReferrerURLCookieHandler.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/ReferrerURLCookieHandlerTest.java
Labels: CLA Signed, release bug, team:Core Security

#7967 experiment with unicode chars in parameters
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jca.fat/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#7962 Apply changes requested in issue#7894
  dev/com.ibm.ws.microprofile.health.2.0/resources/com/ibm/ws/microprofile/health20/resources/Health20.nlsprops
Labels: CLA Signed, ID reviewed

#7912 Make mpjwt wait
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/MessageConstants.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/CommonMpJwtFat.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtApplicationAndSessionScopedClaimInjectionTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtBasicTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtConfigUsingBuilderTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MpJwtMessageConstants.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtLoginConfig_VariationTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtMPConfigTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtPropagationTests.java
Labels: CLA Signed, team:Security SSO, test bug

#7959 Fixed the version of saaj in test failure
  dev/com.ibm.ws.jaxws.ejb_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb_fat/build.gradle
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#7964 Modification needed in server.xml due to lack of java.net.URLPermission class for Java 7
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBInWarServiceTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBJndiTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSBasicTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSContextTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSInterceptorTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSLifeCycleTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBInWarService/java7_server.xml
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBJndi/java7_server.xml
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBWSBasic/java7_server.xml
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBWSContext/java7_server.xml
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBWSInterceptor/java7_server.xml
  dev/com.ibm.ws.jaxws.ejb_fat/publish/files/EJBWSLifeCycle/java7_server.xml
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#7915 MP GraphQL TCK FAT Project
  dev/com.ibm.ws.microprofile.graphql_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.graphql_fat_tck/.project
  dev/com.ibm.ws.microprofile.graphql_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.graphql_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.graphql_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/GraphQLTckPackageTest.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/.gitignore
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/graphql/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#7960 Set mark to end of log between server config update / restore
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/BadApplicationTests.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#7929 Check for null properties
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/protocol/LibertySSLSocketFactory.java
Labels: CLA Signed

#7930 Restrict REST config/validation endpoints to HTTP GET method
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/ConfigBasedRESTHandler.java
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/ConfigRESTHandler.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDSCustomLoginModuleTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDataSourceTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
  dev/fattest.simplicity/src/componenttest/topology/utils/HttpsRequest.java
Labels: CLA Signed, team:Zombie Apocalypse

#7968 Explicitly initialize PlatformMBeanServer prior to JVM self-attach
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/server.xml
  dev/com.ibm.ws.jmx.connector.local/src/com/ibm/ws/jmx/connector/local/LocalConnectorActivator.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, team:Zombie Apocalypse

#7983 initial yaml for config endpoint, plus improvements to yaml for login config properties
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7928 Add JDBC metatype and FAT tests for PostgreSQL with SSL
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/CustomPostgreSQLContainer.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/PostgreSQLSSLTest.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/ssl-certs/privkey.pem
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/ssl-certs/server.crt
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/ssl-certs/server.key
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/ssl-certs/server.req
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/postgresql-test-server/server.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest-native/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest-native/resources/security/outboundKeys.p12
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest-native/resources/security/server.crt
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest-native/server.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest/resources/security/outboundKeys.p12
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLSSLTest/server.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLNativeSSLTestServlet.java
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLSSLTestServlet.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#7982 Switched System.getProperty to server.getHttpDefaultPort to get the default ports
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsAuthenticationTest.java
Labels: CLA Signed, noproductcode

#7777 MicroProfile Metrics 2.0 FAT TCK
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/fat/resources/logging.properties
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/metrics20/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/metrics20/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/servers/MetricsTCKServer/jvm.options
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode

#7981 update framework to org.eclipse.osgi-3.15.0.v20190618-1815
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
Labels: CLA Signed

#7980 Session crossover debug requires the request call stack trace
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionContextImpl.java
Labels: CLA Signed

#7830 added missing synchronization in getoradd
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
Labels: CLA Signed

#7969 Create common bundle for mpMetrics so that they share metatype files
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.0/com.ibm.websphere.appserver.mpMetrics-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.0/com.ibm.websphere.appserver.mpMetrics-2.0.feature
  dev/com.ibm.ws.microprofile.metrics.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.cdi.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.common/.classpath
  dev/com.ibm.ws.microprofile.metrics.common/.project
  dev/com.ibm.ws.microprofile.metrics.common/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.common/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.common/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.common/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.common/findbugs.exclude.xml
  dev/com.ibm.ws.microprofile.metrics.common/resources/META-INF/NOTICE
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.microprofile.metrics.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.microprofile.metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.microprofile.metrics/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID review not needed

#7931 create a fat test based on a recent CTS regression when combining jax…
  dev/com.ibm.ws.jaxrs.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/managedbeans/ManagedBeansTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/JaxrsManagedBeansTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/JaxrsManagedBeansTestServer/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/testManagedBeans/src/com/ibm/ws/jaxrs/managedbeans/ApplicationHolderSingleton.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/testManagedBeans/src/com/ibm/ws/jaxrs/managedbeans/ManagedBeanApp.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/testManagedBeans/src/com/ibm/ws/jaxrs/managedbeans/ManagedBeanResource.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/testManagedBeans/src/com/ibm/ws/jaxrs/managedbeans/ManagedBeansTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#7988 add yaml for root config element and filtering by generic query params
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#7994 Wrong metricName value when creating MetricID in MpMetrics 2.0 Monitor (auto) feature
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetrics.java
Labels: CLA Signed

#7874 PII_19006 Shipment 2 NLS returns part 2
  dev/com.ibm.ws.anno/resources/com/ibm/ws/anno/resources/internal/AnnoMessages_ro.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/service/location/internal/resources/LocServiceMessages_de.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_es.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_fr.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_hu.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_ko.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_ro.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_ru.nlsprops
  dev/com.ibm.ws.microprofile.config.1.1/resources/com/ibm/ws/microprofile/config/resources/Config_zh_TW.nlsprops
  dev/com.ibm.ws.security.audit.source/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.security.wim.core/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ro.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#8000 Revert "Explicitly initialize PlatformMBeanServer prior to JVM self-attach"
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/servers/MPConcurrencyTCKServer/server.xml
  dev/com.ibm.ws.jmx.connector.local/src/com/ibm/ws/jmx/connector/local/LocalConnectorActivator.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed

#7992 update loginConfigProps impl per the yaml and re-enable tests
  dev/com.ibm.ws.rest.handler.validator.jca/src/com/ibm/ws/rest/handler/validator/jca/ConnectionFactoryValidator.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/DataSourceValidator.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/wsspi/validator/Validator.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDSCustomLoginModuleTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
Labels: CLA Signed, team:Zombie Apocalypse

#7822 Setting system prop in order to use localConnector-1.0 on zOS
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/OpentracingRestClientTCKServer/jvm.options
Labels: CLA Signed, noproductcode

#7985 Create ejbcontainer.bindings_fat and port default bindings test
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.gitignore
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.project
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/DefaultBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/.gitignore
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/resources/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/LocalBusiness.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/LocalComponentBusiness.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/LocalComponentEJB.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/LocalEJB.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/RemoteBusiness.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/RemoteComponentBusiness.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/RemoteComponentEJB.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/RemoteEJB.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestComponentBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestLocalComponentHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestLocalHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestRemoteComponentHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndBean.jar/src/com/ibm/ws/ejbcontainer/bindings/defbnd/ejb/TestRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultComponentBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultJavaColonBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/Helper.java
  dev/com.ibm.ws.ejbcontainer.fat_tools/src/com/ibm/websphere/ejbcontainer/test/tools/FATHelper.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#7656 Scrub error response for unwanted characters
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: CLA Signed, in:Transport, team:Sirius

#7952 Issue #7426: Make server stop take arguments
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/EmbeddedServerImpl.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/LauncherDelegate.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/LauncherDelegateImpl.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/wsspi/kernel/embeddable/EmbeddedServerDriver.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/wsspi/kernel/embeddable/EmbeddedServerTest.java
Labels: CLA Signed

#7978 Fix NPE and cleanup test for issue #7871
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
Labels: CLA Signed

#7926 Create microProfile-3.0 convenience feature
  dev/build.image/build.gradle
  dev/build.image/profiles/javaee8/features.xml
  dev/build.image/profiles/microProfile3/features.xml
  dev/build.image/profiles/webProfile8/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/com.ibm.websphere.appserver.microProfile-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/resources/l10n/com.ibm.websphere.appserver.microProfile-3.0_zh_TW.properties
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile3/server.xml
Labels: CLA Signed, ID review not needed, team:MicroProfileUK

#6414 Issue #6158: Pull in MyFaces 2.3.3
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.javaee.jsf.2.3/.classpath
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/Application.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ApplicationWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/ConfigurableNavigationHandlerWrapper.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/application/NavigationHandler.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIData.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIGraphic.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIImportConstants.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIViewAction.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/UIViewParameter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UISelectItem.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UISelectItems.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/_UIWebsocket.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/component/behavior/BehaviorBase.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/context/PartialResponseWriter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/convert/EnumConverter.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/ComponentSystemEventListener.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/event/SystemEventListener.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/BeanValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/validator/RequiredValidator.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/DelegatingMetaTagHandler.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/Facelet.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/view/facelets/FaceletContext.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/webapp/AttributeTag.java
  dev/com.ibm.websphere.javaee.jsf.2.3/src/javax/faces/webapp/UIComponentELTag.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/view/ViewScopeContextImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/FacesContextImplBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/application/FacesServletMappingUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/util/Classpath.java
Labels: CLA Signed, in:Web Components, team:Sirius

#7987 Update code to release memory when stopping applications
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationExtension.java
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationExtensionService.java
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationReleasableFactoryImpl.java
  dev/com.ibm.ws.beanvalidation/src/com/ibm/ws/beanvalidation/OSGiBeanValidationImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/ThreadBasedHashMap.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/component/JaxRsClientModuleMetaDataListener.java
  dev/com.ibm.ws.jaxrs.2.0.ejb/src/com/ibm/ws/jaxrs20/ejb/JaxRsFactoryBeanEJBCustomizer.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseFFDCService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ForwardIncident.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/IncidentImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/IncidentLogger.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/internal/impl/BasicFFDCServiceTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/srt/SRTConnectionContext31.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/webapp/WebApp31.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/SessionImpl.java
Labels: CLA Signed, team:Performance

#8003 Do not persist redelivery count if the message is deleted.
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/objectManager/PersistableImpl.java
Labels: CLA Signed

#8012 Fix for Issue #8007: Fix CL Issue #16484 NPE in ThreadLocalHttpServletRequest
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/InjectionRuntimeContextHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/InjectionRuntimeContextHelper.java
Labels: bug, in:JAX-RS, team:Wendigo West

#8019 Clean up eclipse artifacts
  dev/com.ibm.ws.microprofile.health.2.0_fat/.classpath
  dev/com.ibm.ws.microprofile.health/.classpath
  dev/gradle/.project
Labels: CLA Signed, noproductcode, team:Performance

#7977 Use correct system property for FAT server HTTP port
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicMutationApp/src/mpGraphQL10/basicMutation/BasicMutationTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicQueryApp/src/mpGraphQL10/basicQuery/BasicQueryTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/defaultvalueApp/src/mpGraphQL10/defaultvalue/DefaultValueTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/DeprecationTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ifaceApp/src/mpGraphQL10/iface/InterfaceTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/IgnoreTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/typesApp/src/mpGraphQL10/types/TypesTestServlet.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#7940 create the org.apache.cxf.cxf.rt.bindings.xml.2.6 bundle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.gitignore
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/src/ibm/ws/jaxws22/cxf/rt/bindings/xml/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/src/ibm/ws/jaxws22/cxf/rt/bindings/xml/package-info.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#7942 Create the org.apache.cxf.cxf.rt.ws.addr.2.6 bundle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.gitignore
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/src/com/ibm/ws/jaxws22/cxf/rt/ws/addr/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/src/com/ibm/ws/jaxws22/cxf/rt/ws/addr/package-info.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#7991 Issue #5337: Fix NPE in BridgeUtils.separateRealmAndID. Fix inconsist…
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/AbstractRepositoryWrapper.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ConfigManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryWrapper.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ServiceProvider.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/VMMService.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/WIMUserRegistry.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/BridgeUtils.java
  dev/com.ibm.ws.security.wim.registry/test/com/ibm/ws/security/wim/registry/util/BridgeUtilsTest.java
  dev/com.ibm.ws.security.wim.registry_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.registry_fat/build.gradle
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/WIMURRegressionTest.java
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.WIMURRegression/bootstrap.properties
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.WIMURRegression/server.xml
Labels: CLA Signed, team:Wendigo East

#7913 Adding mpRestClient.1.3 support in the OT auto feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpOpenTracing1.3-mpRestClient1.2.feature
Labels: CLA Signed

#8031 Modified TCP Channel wait statements to not include port number.
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsAuthenticationTest.java
Labels: CLA Signed, noproductcode

#8018 Shutdown Kafka connector gracefully
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/KafkaProducerImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaProducer.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutgoingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutput.java
Labels: CLA Signed

#8026 Update kafka client test dependency
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.org.apache.kafka.clients/.classpath
  dev/com.ibm.ws.org.apache.kafka.clients/.project
  dev/com.ibm.ws.org.apache.kafka.clients/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.kafka.clients/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.kafka.clients/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.kafka.clients/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.kafka.clients/bnd.bnd
  dev/com.ibm.ws.org.apache.kafka.clients/bnd.overrides
Labels: CLA Signed

#8009 add basic auth and error message
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
  dev/com.ibm.ws.rest.handler.validator_fat/test-applications/testOpenAPIApp/resources/META-INF/openapi.yaml
Labels: CLA Signed, team:Zombie Apocalypse

#7856 In jdk7, some of the static fields are not initialized before method …
  dev/com.ibm.ws.kernel.boot.logging/src/com/ibm/ws/kernel/boot/logging/WsLogManager.java
Labels: CLA Signed

#8054 Use print() function in both Python 2 and Python 3
  dev/com.ibm.ws.jmx.scripting.client/publish/clients/jython/restConnector.py
Labels: CLA trivial

#8058 Issue #8034: Fix NPE in UniqueNameHelper.getValidDN()
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATTestIDS_allIbmGroups.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/util/UniqueNameHelper.java
  dev/com.ibm.ws.security.wim.core/test/com/ibm/ws/security/wim/util/UniqueNameHelperTest.java
  dev/com.ibm.ws.security.wim.core_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/WimCoreRegressionTest.java
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.WimCoreRegression/bootstrap.properties
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.WimCoreRegression/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/GroupProperties.java
Labels: CLA Signed, team:Wendigo East

#8068 temporarily disable the PureCXFTest in com.ibm.ws.jaxws.2.2.webcontai…
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#8070 Fix up things so they build in eclipse.
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/src/com/ibm/ws/jaxws22/cxf/rt/bindings/xml/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/src/com/ibm/ws/jaxws22/cxf/rt/bindings/xml/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/.classpath
Labels: CLA Signed, team:Performance

#8038 Build packaging integration
  dev/build.image/build.gradle
  dev/build.image/packaging/buildOsNativePackages.sh.template
  dev/build.image/packaging/changelog.template
  dev/build.image/packaging/debuild/defaultServer.zip
  dev/build.image/packaging/debuild/openliberty/debian/compat
  dev/build.image/packaging/debuild/openliberty/debian/control
  dev/build.image/packaging/debuild/openliberty/debian/copyright
  dev/build.image/packaging/debuild/openliberty/debian/postinst
  dev/build.image/packaging/debuild/openliberty/debian/postrm
  dev/build.image/packaging/debuild/openliberty/debian/prerm
  dev/build.image/packaging/debuild/openliberty/debian/source/format
  dev/build.image/packaging/debuild/scripts/openliberty
  dev/build.image/packaging/debuild/scripts/openliberty@.service
  dev/build.image/packaging/openliberty.spec.template
  dev/build.image/packaging/rpmbuild/BUILD/.gitignore
  dev/build.image/packaging/rpmbuild/BUILDROOT/.gitignore
  dev/build.image/packaging/rpmbuild/RPMS/.gitignore
  dev/build.image/packaging/rpmbuild/SOURCES/defaultServer.zip
  dev/build.image/packaging/rpmbuild/SOURCES/scripts/openliberty
  dev/build.image/packaging/rpmbuild/SOURCES/scripts/openliberty@.service
  dev/build.image/packaging/rpmbuild/SPECS/.gitignore
  dev/build.image/packaging/rpmbuild/SRPMS/.gitignore
  dev/build.image/packaging/rules.template
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed

#8060 enable JAX-RS to create completable futures backed by any executor
  dev/com.ibm.ws.concurrent.mp.1.0/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/CompletionStageFactory.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/package-info.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#8042 Override Arquillian URIResourceProvider
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/health20/tck/Health20TCKLauncher.java
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/servers/Health20TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/servers/Health20TCKServer/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health20/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health20/test/URIProviderProducer.java
Labels: CLA Signed, noproductcode

#8050 Allow unexpected exceptions to propagate from testPersistenceFull
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/MessageStoreTestCase.java
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/persistence/objectManager/PersistenceFullTest.java
Labels: CLA Signed, noproductcode, test bug, test debt
