Repository OpenLiberty/open-liberty, pull requests merged in 2019-02, with the labels that each got.

#6092 Update connection wait timeout exception to include number of waiting requests and the total connection count
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
Labels: CLA Signed, team:Zombie Apocalypse

#6369 test case should not expect to be able to run task on unusable executor
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#6363 SAF Authz audit code from closed liberty
  dev/com.ibm.ws.request.probe.audit.servlet/src/com/ibm/ws/request/probe/audit/servlet/AuditPE.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/SAFAuthorizationDetailsEvent.java
Labels: CLA Signed

#6366 Check for conflict
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/OutboundSSLSelections.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
Labels: CLA Signed

#6383 Fix eclipse settings and Copyright headers.
  dev/com.ibm.ws.io.reactivex.rxjava.2.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.io.reactivex.rxjava.2.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ssl_fat_pkcs12/.classpath
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSDoesNotExistSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSExistsSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultPKCS12DoesNotExistSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultPKCS12ExistsSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/FATSuite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/FATSuiteLite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/NonDefaultJKSSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/NonDefaultPKCS12SSLTest.java
Labels: CLA Signed, noproductcode

#6345 beans for container-produced ThreadContext and ManagedExecutor must not have an EL name
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ManagedExecutorBean.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/ThreadContextBean.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentCDITestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
Labels: CLA Signed

#6334 Enable waitForRecovery test with transaction bundle set to CONTAINER_LATE
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.2.feature
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_waitForRecovery/server.xml
Labels: CLA Signed

#6359 Port dual peer recovery tests from Commercial Liberty
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/Simple2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/SimpleFS2PCCloudServlet.java
Labels: CLA Signed, noproductcode

#6382 Externalize enableLocalAuthentication attribute for socialLogin-1.0
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#6303 Add port config that references dynamic ports
  dev/com.ibm.ws.config_fat/publish/files/badconfig/goodConfig.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.bad/bootstrap.properties
Labels: CLA Signed, noproductcode

#5943 Add runtime udpate trace to config fat servers
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.childalias/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.commandLineVar/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.delayedVar/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.dropins/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.extensions/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.features/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.helper/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.import.error/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.import/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.invalidJDBCoption/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.merging/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.metatype.provider/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.product.extension/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.refresh/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.restart.var/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.restart/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.schemaGen.mbean/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.update.mbean/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.update/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.validate/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.validateConfig/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.validator/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.varmerging/bootstrap.properties
Labels: CLA Signed, noproductcode

#6357 Increase JobWaiter polling timeout to 30
  dev/com.ibm.ws.jbatch.cdi_fat/util/src/fat/util/JobWaiter.java
Labels: CLA Signed, noproductcode

#4278 don't eat exceptions
  dev/fattest.simplicity/src/componenttest/rules/AutoStopRule.java
Labels: CLA Signed, noproductcode

#6281 match repository for scim create when multiple are federated
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapHelper.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/util/UniqueNameHelper.java
Labels: CLA Signed, team:Wendigo East

#6327 6280 failover
  dev/com.ibm.ws.cdi.interfaces/bnd.bnd
  dev/com.ibm.ws.cdi.interfaces/src/com/ibm/ws/cdi/CDIServiceUtils.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/RuntimeFactory.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIUtils.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/OnDemandArchive.java
Labels: CLA Signed

#6372 Handle exception when aborting connection
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/adapter/WSManagedConnection.java
  dev/com.ibm.ws.jdbc.4.1/src/com/ibm/ws/rsadapter/jdbc/v41/WSJdbc41Connection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6393 Test fix: ensure builder timeout is reset after test that changes it.
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicClientApp/src/mpRestClient10/basic/BasicClientTestServlet.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West, test bug

#6307 Expand app start timeout in client container bean val fat
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.ApacheBvalConfig_11/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.BeanValidationCDI_11/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.BeanValidationCDI_20/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.DefaultBeanValidationCDI_11/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.DefaultBeanValidationCDI_20/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.beanvalidation_11/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.beanvalidation_20/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.defaultbeanvalidation_11/client.xml
  dev/com.ibm.ws.clientcontainer.beanvalidation_fat/publish/clients/com.ibm.ws.clientcontainer.beanvalidation.fat.defaultbeanvalidation_20/client.xml
Labels: CLA Signed, noproductcode

#6331 Better zip error checking
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
Labels: CLA Signed

#6261 quiet down routine jwtsso cookie expiration messages
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerImpl.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoTokenUtils.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIJwtUtils.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtConfigUsingBuilderTests.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/InvalidTokenTest.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
Labels: CLA Signed

#6346 Update the cxf-api jar with new version
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxws.clientcontainer.security/bnd.bnd
  dev/com.ibm.ws.jaxws.clientcontainer/bnd.bnd
  dev/com.ibm.ws.jaxws.common/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.security/bnd.bnd
  dev/com.ibm.ws.jaxws.web/bnd.bnd
  dev/com.ibm.ws.jaxws.wsat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.jaxws/cxf-api.bnd
Labels: CLA Needed, CLA Signed

#6398 Make RepeatTests handle exceptions better
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, noproductcode

#6388 Issue 6381 - Fixed the trace.log rotating issue on Windows
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/FileLogHolder.java
Labels: CLA Signed

#6418 fix incorrect JavaDoc in ThreadContextDescriptorImpl and remove unnecessary code
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextDescriptorImpl.java
Labels: CLA Signed, bug, team:Zombie Apocalypse

#6396 precontextualized tasks
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualBiConsumer.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualBiFunction.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualCallable.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualConsumer.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualFunction.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualRunnable.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualSupplier.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/ContextualAction.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/AbstractTask.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
  dev/com.ibm.ws.concurrent_fat/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#6399 Initial commit: tests will wait for app startup message
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpXForwardedAndForwardedHeaderTests.java
Labels: CLA Signed, noproductcode

#6405 Add trace message for use in tests
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/BundleProcessor.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/MetatypeProviderTest.java
Labels: CLA Signed

#6424 Increase file monitor interval to 1 second
  dev/com.ibm.ws.kernel.filemonitor/test/com/ibm/ws/kernel/filemonitor/internal/CoreServiceImplTestParent.java
Labels: CLA Signed, noproductcode

#6336 Update to handle invalid endpoints in rp flow
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/common/internal/resources/OidcCommonMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
Labels: CLA Signed, ID reviewed

#6421 Avoid warning when no providers are specified for MP Rest Client
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#6406 fix for connection wait timeout translation
  dev/com.ibm.ws.jca.cm/resources/com/ibm/ws/j2c/resources/J2CAMessages.nlsprops
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#6444 Fix Issue #6437: remove FFDC
  dev/com.ibm.ws.jaxrs.2.0.ejb/src/com/ibm/ws/jaxrs20/ejb/JaxRsFactoryBeanEJBCustomizer.java
Labels: CLA Signed, in:JAX-RS, release bug, team:Wendigo West

#6256 6165 transaction scoped
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContext.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContextExtension.java
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/TransactionScopedObserversTest.java
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/.gitignore
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/DestroyCallback.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequestScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequiredTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequiresNewTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopeObserver.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedBean2.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedTestServlet.java
Labels: CLA Signed

#6443 NullPointerException when backed by unmanaged executor
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: bug, team:Zombie Apocalypse

#6410 Issue #6407: Fix RC issue in server.bat for win service
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed, release bug

#6426 delete the build.xml files for the jaxrs projects
  dev/com.ibm.ws.jaxrs.2.0.beanvalidation/build.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi/build.xml
  dev/com.ibm.ws.jaxrs.2.0.client/build.xml
  dev/com.ibm.ws.jaxrs.2.0.common/build.xml
  dev/com.ibm.ws.jaxrs.2.0.ejb/build.xml
  dev/com.ibm.ws.jaxrs.2.0.managedbeans/build.xml
  dev/com.ibm.ws.jaxrs.2.0.security/build.xml
  dev/com.ibm.ws.jaxrs.2.0.server/build.xml
  dev/com.ibm.ws.jaxrs.2.0.tools.wadl2java/build.xml
  dev/com.ibm.ws.jaxrs.2.0.tools/build.xml
  dev/com.ibm.ws.jaxrs.2.0.web/build.xml
  dev/com.ibm.ws.jaxrs.2.1.common/build.xml
  dev/com.ibm.ws.jaxrs.2.x.concurrent/build.xml
  dev/com.ibm.ws.jaxrs.2.x.config/build.xml
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#6439 Issue #6435 - move config TCKs to FULL mode
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/fat/src/com/ibm/ws/microprofile/config12/tck/Config12TCKLauncher.java
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/fat/src/com/ibm/ws/microprofile/config12/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/config13/tck/Config13TCKLauncher.java
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/config13/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.config_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/ConfigTCKLauncher.java
  dev/com.ibm.ws.microprofile.config_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.config_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#6447 Use JWT SSO Cookie for unprotected resource if useAuthenticationDataForUnprotectedResource is enabled for issue #6246
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/CookieHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebRequestImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelperTestHelper.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/CookieHelperTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebRequestImplTest.java
Labels: CLA Signed

#6440 Add debug logging to jaxb_fat
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/JAXBToolsTest.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed, team:Zombie Apocalypse

#6394 add dependency on building userRegistry war
  dev/com.ibm.ws.security.registry.basic_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.file_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.registry_fat/build.gradle
  dev/com.ibm.ws.webcontainer.security_test.servlets/test-applications/basicauth/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#6468 remove lambda
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContextExtension.java
  dev/com.ibm.ws.transaction.core_fat/.classpath
Labels: CLA Signed

#6344 Fix the codesource for creating the application protection domain for issue #6129
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/DeployedAppInfoBase.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/java2sec/PermissionManagerTest.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ResourceAdapterService.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionServletWrapper.java
Labels: CLA Signed

#6462 5671 openapi
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/openapi/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/tck/TestLoggingObserverExtension.java
Labels: CLA Signed, noproductcode

#6453 Auth filter updates for request header and cookie support
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.authentication.filter/resources/com/ibm/ws/security/authentication/filter/internal/resources/FilterMessages_es.nlsprops
  dev/com.ibm.ws.security.authentication.filter/resources/com/ibm/ws/security/authentication/filter/internal/resources/FilterMessages_fr.nlsprops
  dev/com.ibm.ws.security.authentication.filter/resources/com/ibm/ws/security/authentication/filter/internal/resources/FilterMessages_ko.nlsprops
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/AuthenticationFilter.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/AuthFilterConfig.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/AuthenticationFilterImpl.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/CommonFilter.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/ContainsCondition.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/EqualCondition.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/GreaterCondition.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/ICondition.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/IPAddressRange.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/IPAddressRangeGroup.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/IRequestInfo.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/RealRequestInfo.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/TraceConstants.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/ValueAddressRange.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/internal/package-info.java
  dev/com.ibm.ws.security.authentication.filter/src/com/ibm/ws/security/authentication/filter/package-info.java
Labels: CLA Signed, ID review not needed, L2 Reviewed, team:Security SSO

#6441 added wait statement for entire test to finish
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#6456 UCP Config NLS updates
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequiered, team:Zombie Apocalypse

#6450 Issue6449-MoveAuditReaderToOpenLiberty
  dev/com.ibm.ws.security.audit.reader.auditreader/bnd.bnd
  dev/com.ibm.ws.security.audit.reader/.classpath
  dev/com.ibm.ws.security.audit.reader/bnd.bnd
Labels: CLA Signed

#6442 Update social metadata
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequiered, team:Security SSO

#6475 update com.ibm.ws.microprofile.metrics_fat_tck to use 1.0.2 metrics API
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#6463 Correct the mavenCoordinates for jaxb-api in the jaxb-2.2 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
Labels: CLA Signed, team:Zombie Apocalypse

#6174 Avoid NPE if no URL specified with DataSource type of java.sql.Driver
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Zombie Apocalypse

#6425 fix dynamic changing of connection timeout to 0
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CGlobalConfigProperties.java
Labels: CLA Signed, team:Zombie Apocalypse

#6451 fix showPoolContents waiting connection requests value
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6467 align with spec decision for context from executor parameter
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#6486 IllegalArgumentException when Runnable supplied to ContextualExecutor.execute already has context
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ContextualExecutor.java
Labels: CLA Signed, team:Zombie Apocalypse

#6472 Change to remove specific cached object from the configuration
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/KeyStoreManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/KeystoreConfigurationFactory.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
Labels: CLA Signed

#6249 Update QuickStartSecurity to support hashed passwords
  dev/com.ibm.ws.security.quickstart/src/com/ibm/ws/security/quickstart/internal/Password.java
  dev/com.ibm.ws.security.quickstart/src/com/ibm/ws/security/quickstart/internal/QuickStartSecurity.java
  dev/com.ibm.ws.security.quickstart/src/com/ibm/ws/security/quickstart/internal/QuickStartSecurityRegistry.java
  dev/com.ibm.ws.security.quickstart/test/com/ibm/ws/security/quickstart/internal/QuickStartSecurityRegistryIllegalArgumentTest.java
  dev/com.ibm.ws.security.quickstart/test/com/ibm/ws/security/quickstart/internal/QuickStartSecurityRegistryTest.java
  dev/com.ibm.ws.security.quickstart/test/com/ibm/ws/security/quickstart/internal/QuickStartSecurityTest.java
Labels: CLA Signed, team:Wendigo East

#6497 Revert 6256
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContext.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContextExtension.java
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/TransactionScopedObserversTest.java
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/.gitignore
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/DestroyCallback.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequestScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequiredTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/RequiresNewTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopeObserver.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedBean2.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/web/TransactionScopedTestServlet.java
Labels: CLA Signed

#6492 Publish runtime, javaee8, and webprofile8 images from release builds
  dev/build.image/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#6446 Add custom TestMode support for RepeatTests
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, noproductcode

#6488 Move mpConcurrency-1.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConcurrency-1.0/com.ibm.websphere.appserver.mpConcurrency-1.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#6487 Add a separate check for beta attributes to catch extended types that…
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
Labels: CLA Signed, release bug

#6495 Update JDBC 4.1 FAT Java Permissions
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6494 Don't run jaxb-2.3 FATs on Java 7 builds
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Wendigo West

#6508 Revert "Publish runtime, javaee8, and webprofile8 images from release builds"
  dev/build.image/build.gradle
Labels: CLA Signed

#6465 added wait statement for entire start sequence to finish
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#6434 Add Oracle UCP config
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequiered, in:JDBC/JCA, team:Zombie Apocalypse

#6484 Use -Xverify:all for Hotspot JDK 11
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6493 Add JPA 2.0 support to JPA Spec 1.0 Bucket
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/RepeatWithJPA20.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#6499 update org.eclipse.osgi to new i-build 3.13.300.v20190211-2137 and fix for com.ibm.ws.jsonb_fat
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/build.xml
Labels: CLA Signed

#6390 Check for link close before async write in SSLWriteServiceContext
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLWriteServiceContext.java
Labels: CLA Signed, in:Transport, release bug, team:Sirius

#6464 Issue 6435 - move more tests to FULL mode
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/ConverterPriorityTest.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/ImplicitConverterTest.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/TypeConverterTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/DuplicateInServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/MapEnvVarTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/VariableResolutionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIBrokenInjectionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIBuiltInConverterTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIConfigPropertyTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIFieldInjectionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CDIXtorInjectionTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoaderCacheTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoadersTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ConverterPriorityTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ConvertersTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/CustomSourcesTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DynamicSourcesTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/OrdinalsForDefaultsTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SharedLibTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimpleScopeTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/StressTest.java
  dev/com.ibm.ws.microprofile.config_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/TypesTest.java
  dev/com.ibm.ws.microprofile.config_repeat_tests/src/com/ibm/ws/microprofile/config/fat/repeat/RepeatConfigActions.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/TestModeFilter.java
Labels: CLA Signed, in:MicroProfile/Config, noproductcode, team:MicroProfileUK

#6507 PR #6497 reverted the some transaction scope changes but missed this one file
  dev/com.ibm.ws.transaction.core_fat/.classpath
Labels: team:MicroProfileUK

#6519 6518 redundant log files in workarea
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
Labels: CLA Signed

#6511 Don't perform server dump all the time in plugin.utility_fat
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityGenerateTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6522 Standardize UCP XA code path
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6520 Correctly handle case where we need to wait for multiple updates
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
Labels: CLA Signed, noproductcode

#6409 Security FAT infra update for TestActionExceptions
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/exceptions/TestActionException.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/exceptions/TestActionExceptionTest.java
Labels: CLA Signed, team:Security SSO

#6432 FT 2.0: Fix async fallback
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/BulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/util/AsyncTestFunction.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/ejb/AsyncEJBServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/ejb/AsyncEJBThreadContextBean.java
Labels: CLA Signed

#6459 FT 2.0: rename AsyncExecutor stages
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncCompletionStageExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutionContextImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncFutureExecutor.java
Labels: CLA Signed

#6491 timing window where submit can hang when delay after capturing nanoTime exceeds maxWaitForEnqueue
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6502 deprecate the old ThreadContextProvider interface
  dev/com.ibm.ws.context/src/com/ibm/wsspi/threadcontext/ThreadContextProvider.java
Labels: CLA Signed, team:Zombie Apocalypse

#6535 Revert "Add custom TestMode support for RepeatTests"
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, noproductcode

#6513 Enhance Spring boot features to support app configured port on default_host for cloud migration
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/container/SpringBootConfig.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/support/ContainerInstanceFactory.java
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyWebServer.java
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyWebServer.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/initializer/ServerConfigurationFactory.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstance.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15Servlet40.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests20Servlet40.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigActuatorXMLOverrideTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigServerXMLOverrideTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MultContextTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLCommonTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests20.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
Labels: CLA Signed

#6512 Disable dumps in JPA Spec10 Bucket
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22BeanValidation.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22Injection.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22QueryTest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPA22TimeAPITest.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/JPACDIIntegrationTest.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Callback_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Callback_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Inheritance_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Inheritance_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXMany_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXMany_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXOne_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_ManyXOne_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXMany_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXMany_Web.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXOne_EJB.java
  dev/com.ibm.ws.jpa_spec10_fat/fat/src/com/ibm/ws/jpa/spec10/Relationships_OneXOne_Web.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPA20QueryLockMode_EJB.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPA20QueryLockMode_WEB.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#6517 Move ApacheDS tests to FULL ldap bucket
  dev/com.ibm.ws.org.apache.directory.server/src/com/ibm/ws/apacheds/EmbeddedApacheDS.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPReferralTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/SearchPagingTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_RealmPropertyMappingTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#6528 Publish runtime, javaee8, and webProfile8 images to DHE
  dev/build.image/build.gradle
  dev/settings.gradle
Labels: CLA Signed, team:Continuous Delivery

#6565 NOTICES for 19002
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#6457 Reconsume weld 3.1 and only ues one digit in the weld version string
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.jsf/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.web/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld3/.classpath
  dev/com.ibm.ws.org.jboss.weld3/.gitignore
  dev/com.ibm.ws.org.jboss.weld3/.project
  dev/com.ibm.ws.org.jboss.weld3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.jboss.weld3/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.jboss.weld3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.jboss.weld3/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.jboss.weld3/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld3/src/org/jboss/weldx/transaction/package-info.java
Labels: CLA Signed

#6553 When ucp is specified with ConnectionPoolDataSource, do not search ba…
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
Labels: CLA Signed, team:Zombie Apocalypse

#6489 Create FT 2.0 TCK runner project
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.project
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/jvm.options
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/faulttolerance/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#5825 Improve variable server test
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/files/original/variableServerXMLApp.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode, team:MicroProfileUK

#6536 Fix pr 6446
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, noproductcode

#6316 Mp concurrency cdi context
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/.gitignore
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.ejb/.gitignore
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.jsf/.gitignore
  dev/com.ibm.ws.cdi.2.0.jsf/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.web/.gitignore
  dev/com.ibm.ws.cdi.2.0.web/bnd.bnd
  dev/com.ibm.ws.cdi.2.0.weld/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyManagerImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ConcurrencyProviderImpl.java
  dev/com.ibm.ws.concurrent.mp.cdi/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/context/WeldContextProvider.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/context/WeldContextSnapshot.java
  dev/com.ibm.ws.concurrent.mp.cdi/src/com/ibm/ws/concurrent/mp/cdi/context/package-info.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/AbstractBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/ConversationScopeBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/RequestScopedBean.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/SessionScopedBean.java
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#6576 Give stderr and stdout each a thread for copying output
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/JAXBToolsTest.java
Labels: CLA Signed, noproductcode, test bug

#6572 6360 filter out spring boot start21x deps
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.springboot.support.version21.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version21.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version21.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version21.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version21.test.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/CustomizationBean.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/MvcConfig.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/TestWebFilter.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/TestWebListener.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/TestWebServlet.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/java/com/ibm/ws/springboot/support/version21/test/app/WebSecurityConfig.java
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/public/file.weby
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/public/useJarUrlsTest.html
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/templates/hello.html
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/templates/login.html
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests21.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed

#6538 Fix permissions.xml in BasicAuth app
  dev/com.ibm.ws.webcontainer.security_test.servlets/test-applications/basicauth/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#6531 Fix ConcurrentModificationException in channelfw unit tests
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/bytebuffer/test/ByteBufferTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/bytebuffer/test/ByteBufferUtilsTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/CFEndPointTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChainDataTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChainEventListenerTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChainLifeCycleTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChannelDataTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChannelFactoryDataTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChannelFactoryLifeCycleTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/ChannelLifeCycleTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/DiscriminationTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/GroupDataTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/GroupLifeCycleTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/ws/channelfw/testsuite/junit/VirtualConnectionTest.java
  dev/com.ibm.ws.channelfw/test/com/ibm/wsspi/connmgmt/ConnectionHandleTest.java
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#6485 [Issue 5903] Enhance JsonBProvider to use ContextResolver<Jsonb>
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/JsonbContextResolverTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonbContextResolver/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonbContextResolver/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/JsonbContextResolver.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/JsonbContextResolverTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/Person.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/PrivateVisibilityStrategy.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/Resource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonBProvider.java
Labels: CLA Signed, enhancement, in:JAX-RS, team:Wendigo West

#6470 New test the CRLFs are preserved when using text/plain POST bodies
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/formApp/src/jaxrs21/fat/form/FormBehaviorTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/formApp/src/jaxrs21/fat/form/FormReaderInterceptor.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/formApp/src/jaxrs21/fat/form/FormResource.java
Labels: in:JAX-RS, team:Wendigo West

#6574 Beta Fault Tolerance 2.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.0/com.ibm.websphere.appserver.mpFaultTolerance-2.0.feature
Labels: CLA Signed

#6564 Issue 6521: Ensure we can send/receive generic'd collections
  dev/com.ibm.ws.microprofile.rest.client_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/build.gradle
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.collections/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.collections/resources/security/key.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.collections/resources/security/trust.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.collections/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.remoteServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicRemoteApp/src/remoteApp/basic/BasicService.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicRemoteApp/src/remoteApp/basic/WidgetListEntityProvider.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/CollectionsClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/CollectionsTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/DuplicateWidgetException.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/DuplicateWidgetExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/UnknownWidgetException.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/UnknownWidgetExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/collectionsApp/src/mpRestClient10/collections/Widget.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonBProvider.java
Labels: CLA Signed, in:JAX-RS, in:MicroProfile, release bug, team:Wendigo West

#6579 New FAT tests for invoking MP Rest Client in EJBs.
  dev/com.ibm.ws.microprofile.rest.client_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicEJBTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.ejb/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.ejb/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/BasicServiceClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/DuplicateWidgetException.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/DuplicateWidgetExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/MyEJB.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/MyFilter.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/UnknownWidgetException.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/UnknownWidgetExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/Widget.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#6584 create nonship configValidator feature, porting over the Config REST API handler first
  dev/com.ibm.websphere.appserver.features/visibility/public/configValidator-1.0/com.ibm.websphere.appserver.configValidator-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/configValidator-1.0/resources/l10n/com.ibm.websphere.appserver.configValidator-1.0.properties
  dev/com.ibm.ws.rest.handler.config/.classpath
  dev/com.ibm.ws.rest.handler.config/.project
  dev/com.ibm.ws.rest.handler.config/.settings/bndtools.core.prefs
  dev/com.ibm.ws.rest.handler.config/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.rest.handler.config/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.rest.handler.config/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.rest.handler.config/bnd.bnd
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/ConfigRESTHandler.java
  dev/com.ibm.ws.rest.handler.config/src/com/ibm/ws/rest/handler/config/internal/package-info.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/.classpath
  dev/com.ibm.ws.rest.handler.validator.jdbc/.project
  dev/com.ibm.ws.rest.handler.validator.jdbc/.settings/bndtools.core.prefs
  dev/com.ibm.ws.rest.handler.validator.jdbc/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.rest.handler.validator.jdbc/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.rest.handler.validator.jdbc/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.rest.handler.validator.jdbc/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/DataSourceValidator.java
  dev/com.ibm.ws.rest.handler.validator.jdbc/src/com/ibm/ws/rest/handler/validator/jdbc/package-info.java
  dev/com.ibm.ws.rest.handler.validator/.classpath
  dev/com.ibm.ws.rest.handler.validator/.project
  dev/com.ibm.ws.rest.handler.validator/.settings/bndtools.core.prefs
  dev/com.ibm.ws.rest.handler.validator/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.rest.handler.validator/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.rest.handler.validator/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.rest.handler.validator/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/ValidatorRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/ws/rest/handler/validator/internal/package-info.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/wsspi/validator/Validator.java
  dev/com.ibm.ws.rest.handler.validator/src/com/ibm/wsspi/validator/package-info.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequiered, team:Zombie Apocalypse

#6606 Add http2 testDataOnStreamZero to trace bucket
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
Labels: CLA Signed, noproductcode

#6458 Test for closed proxy connection in OrderingContext.
  dev/com.ibm.ws.messaging.common/src/com/ibm/wsspi/sib/core/OrderingContext.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/comms/client/OrderingContextProxy.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsConnectionImpl.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/OrderingContextImpl.java
Labels: CLA Signed

#6597 changed wait to later message in log
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
Labels: CLA Signed, noproductcode

#6611 Allow jceks type
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#6624 Updates to make new project work in eclipse.
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version21.test.app/.classpath
  dev/com.ibm.ws.springboot.support.version21.test.app/.project
  dev/com.ibm.ws.springboot.support.version21.test.app/bnd.bnd
Labels: CLA Signed

#6610 fix lambda bug and some minor changes.
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/LogLevelPropertyTest.java
  dev/com.ibm.ws.kernel.instrument.serialfilter.premain/src/com/ibm/ws/kernel/instrument/serialfilter/agent/PreMain.java
  dev/com.ibm.ws.kernel.instrument.serialfilter.serverconfig/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/agenthelper/PreMainUtil.java
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/config/Config.java
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/config/ConfigImpl.java
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/util/CallStackWalker.java
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/validators/ClassValidatorFactory.java
  dev/com.ibm.ws.kernel.instrument.serialfilter/src/com/ibm/ws/kernel/instrument/serialfilter/validators/DiscoveringClassValidator.java
  dev/com.ibm.ws.kernel.instrument.serialfilter_fat/fat/src/com/ibm/ws/kernel/instrument/serialfilter/fat/SerialFilterEnabledTest.java
  dev/com.ibm.ws.kernel.instrument.serialfilter_fat/test-applications/MethodIntfWeb.war/src/com/ibm/ws/ejbcontainer/tx/methodintf/web/SerialFilterEnabledServlet.java
Labels: CLA Signed, in:Security, team:Core Security

#6577 add required arguments for ZOS
  dev/com.ibm.ws.opentracing.1.1_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing.1.2_fat/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.opentracing_fat/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#6620 tolerate Java 12 CompletableFuture methods
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ManagedCompletableFuture.java
Labels: CLA Signed, team:Zombie Apocalypse

#6622 port tests for datasource validator REST API
  dev/com.ibm.websphere.appserver.features/visibility/public/configValidator-1.0/com.ibm.websphere.appserver.configValidator-1.0.feature
  dev/com.ibm.ws.rest.handler.validator_fat/.classpath
  dev/com.ibm.ws.rest.handler.validator_fat/.project
  dev/com.ibm.ws.rest.handler.validator_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.rest.handler.validator_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.rest.handler.validator_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.rest.handler.validator_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/build.gradle
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDataSourceTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jdbc.fat/bootstrap.properties
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jdbc.fat/server.xml
Labels: team:Zombie Apocalypse

#6612 avoid warning for feature version that does not exist in OpenLiberty
  dev/com.ibm.websphere.appserver.features/visibility/public/configValidator-1.0/com.ibm.websphere.appserver.configValidator-1.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#6615 update message file, comments only
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
Labels: CLA Signed

#6631 add trace to connection pool mbeans
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#6607 Login hint initial support
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/common/internal/resources/OidcCommonMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/common/ConfigUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/common/Constants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/common/ConfigUtilsTest.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, team:Security SSO

#6617 4493 Reactive Streams Unit Tests
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/AbstractReactiveUnitTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/CollectTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/ElementDroppingAndAddingTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/ErrorRecoveryTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/ExceptionalCompletionTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/RsoElementsTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/SetInstanceTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/UtSubscriber.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/WASReactiveStreamsEngineImplSubclass.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/WASReactiveStreamsFactoryImplSubclass.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators/test/src/com/ibm/ws/microprofile/reactive/streams/test/WASReactiveUT.java
Labels: CLA Signed

#6616 FT 2.0 FATs for CompletionStage and interceptor interactions
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/EarlyInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptionRecorder.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptorBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptorTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptorTestServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/LateInterceptor.java
Labels: CLA Signed, noproductcode

#6636 Add tests for FT 2.0 + JAX-RS
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/JaxRsClientProducer.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/JaxRsTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/JaxRsTestServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/TestApplication.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/TestClientBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/TestException.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/TestExceptionHandler.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/TestResource.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/JaxRsFaultTolerance/bootstrap.properties
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/JaxRsFaultTolerance/server.xml
Labels: CLA Signed, noproductcode

#6619 Make FaultTolerance 2.0 depend on CDI-2.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.0/com.ibm.websphere.appserver.mpFaultTolerance-2.0.feature
Labels: CLA Signed

#6638 plugin.utility_fat: wait for LTPA service start before testing remote server
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityGenerateTest.java
Labels: CLA Signed, noproductcode, team:Sirius, test bug

#6245 Fixed bug in merging paths
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/jaxrs2/util/ReaderUtils.java
Labels: CLA Signed

#6510 Shared class cache updates for kernel and application classloader
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileContainer.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/DirectoryBasedOverlayContainerImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/PooledWsByteBufferImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferPool.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/LibertyClassLoaderTest.java
  dev/com.ibm.ws.kernel.boot.common/src/com/ibm/ws/kernel/boot/classloader/SharedClassCacheHook.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/DirectoryResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarFileClassLoader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/ResourceEntry.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
Labels: CLA Signed

#6660 Additional cleanup not done in PR #6629.
  dev/com.ibm.ws.ssl_fat_pkcs12/.classpath
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSDoesNotExistSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSExistsSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultPKCS12DoesNotExistSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultPKCS12ExistsSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/FATSuite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/FATSuiteLite.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/NonDefaultJKSSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/NonDefaultPKCS12SSLTest.java
Labels: CLA Signed, noproductcode

#6587 Work around windows start command bug
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#6632 6628 keep all variables in server bat
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#6647 OIDC login hint: Changes from final WAD updates
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/common/internal/resources/OidcCommonMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/common/ConfigUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/common/ConfigUtilsTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#6644 test coverage for TransactionScoped bean
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/MPConcurrentCDITestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentCDIApp/src/concurrent/mp/fat/cdi/web/TransactionScopedBean.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6671 Update project name to match component name.
  dev/com.ibm.ws.jpa_spec10_injection_fat/.project
Labels: CLA Signed, noproductcode

#6657 Issue6656-EnsureJMXMBeanMessagesAreRecordsInAudit
  dev/com.ibm.ws.security.audit.source/bnd.bnd
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/pipeline/AuditJMXPipeline.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/source/AuditServiceImpl.java
Labels: CLA Signed

#6642 port userfeature for config REST API test
  dev/com.ibm.ws.rest.handler.config_fat/.classpath
  dev/com.ibm.ws.rest.handler.config_fat/.project
  dev/com.ibm.ws.rest.handler.config_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.rest.handler.config_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.rest.handler.config_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.rest.handler.config_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.rest.handler.config_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/build.gradle
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.config_fat/publish/files/features/nestedFlat-1.0.mf
  dev/com.ibm.ws.rest.handler.config_fat/publish/servers/com.ibm.ws.rest.handler.config.fat/bootstrap.properties
  dev/com.ibm.ws.rest.handler.config_fat/publish/servers/com.ibm.ws.rest.handler.config.fat/server.xml
  dev/com.ibm.ws.rest.handler.config_fat/rest.handler.config_fat.bnd
  dev/com.ibm.ws.rest.handler.config_fat/test-bundles/test.config.nested.flat/resources/metatype.xml
  dev/com.ibm.ws.rest.handler.config_fat/test.config.nested.flat.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#6515 Squashed commit of the following:
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/RemoteFile.java
  dev/fattest.simplicity/src/componenttest/common/apiservices/cmdline/LocalProvider.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyFileManager.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode

#6662 Update FaultTolerance interfaces
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/ExecutorBuilderImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/ProviderResolverImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/AsyncTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/BulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/CircuitBreakerTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/FallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/RetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/TimeoutTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/AggregatedFTPolicy.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/Executor.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/ExecutorBuilder.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/FaultToleranceProvider.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/FaultToleranceProviderResolver.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/ExecutorBuilderImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/ProviderResolverImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/AsyncTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/BulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/CircuitBreakerTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/FallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/RetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance/test/src/com/ibm/ws/microprofile/faulttolerance/test/TimeoutTest.java
Labels: CLA Signed

#6666 Increase servlet.4.0_fat app startup timeout
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/WCApplicationHelper.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCAddJspFileTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCContextRootPrecedence.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCEncodingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCGetMappingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderSecurityTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletClarificationTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletPathForDefaultMappingDefault.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletPathForDefaultMappingFalse.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTrailersTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius, test bug

#6702 Update minimum JDK for JPA Spec tests to 8 to satisfy JEE 8 minimum J…
  dev/com.ibm.ws.jpa_spec10_fat/.classpath
  dev/com.ibm.ws.jpa_spec10_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa_spec10_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_injection_fat/.classpath
  dev/com.ibm.ws.jpa_spec10_injection_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa_spec10_injection_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec20_fat/.classpath
  dev/com.ibm.ws.jpa_spec20_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa_spec20_fat/bnd.bnd
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#6718 Issue #6695: Update JSF23 JavaScript timeout to 5000ms
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#6704 Ignore testClientAuthNeedWithoutClientSideKeyStoreFor15 Beyond Java8
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
Labels: CLA Signed, in:SpringBoot, noproductcode, team:OSGi Infrastructure, test bug

#6640 Use privilaged block to access bundle
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ThreadContextClassLoader.java
Labels: CLA Signed

#6504 6165 transaction scoped
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContext.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContextExtension.java
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/TransactionScopedObserversTest.java
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/.gitignore
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction_cdi/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/DestroyCallback.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/RequestScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/RequiredTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/RequiresNewTransactionalHelperBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/TransactionScopeObserver.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/TransactionScopedBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/TransactionScopedBean2.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactionscoped/src/transactionscopedtest/TransactionScopedTestServlet.java
Labels: CLA Signed

#6596 Update LDAP FAT to assure membership attribute overrides iFilter
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun/server.xml
Labels: CLA Signed, noproductcode

#6623 Initial work to support env and default vars
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/SchemaData.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/ConfigVariables.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigVariable.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigVariableRegistry.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/EvaluationContext.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/StringUtils.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/VariableEvaluator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigurationTest.java
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.delayedVar/server.env
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.delayedVar/server.xml
  dev/com.ibm.ws.config_fat/test-applications/varmerge/src/test/config/merged/DelayedVariableTestServlet.java
  dev/com.ibm.ws.config_fat/test-bundles/test.config.variables/resources/OSGI-INF/metatype/metatype-variables.xml
  dev/com.ibm.ws.config_fat/test-bundles/test.config.variables/src/com/ibm/ws/config/variables/ConfigVariableComponent.java
  dev/com.ibm.ws.config_fat/test-bundles/test.config.variables/src/com/ibm/ws/config/variables/ServerXMLVariables.java
Labels: CLA Signed, L2 Reviewed

#6729 Revert "Shared class cache updates for kernel and application classloader"
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileContainer.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/DirectoryBasedOverlayContainerImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/PooledWsByteBufferImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/bytebuffer/internal/WsByteBufferPool.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/LibertyClassLoaderTest.java
  dev/com.ibm.ws.kernel.boot.common/src/com/ibm/ws/kernel/boot/classloader/SharedClassCacheHook.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/DirectoryResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarFileClassLoader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarResourceEntry.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/ResourceEntry.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/GenericData.java
Labels: CLA Signed

#6626 Add hashing information to KC for quickStartSecurity
  dev/com.ibm.ws.security.quickstart/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, L2 ReviewNotRequiered, team:Wendigo East

#6698 Issue 6697: MP Rest Client 1.2 CDI Interceptor/MP FT support
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.project
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/RetryTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/TimeoutTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.retry/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.retry/resources/security/key.jks
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.retry/resources/security/trust.jks
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.retry/server.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.timeout/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.timeout/resources/security/key.jks
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.timeout/resources/security/trust.jks
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.timeout/server.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/App.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/Driver.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/ISExceptionMapper.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/InAppConfigSource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/Loggable.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/LoggableInterceptor.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryClient.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryRemoteResource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/App.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/InAppConfigSource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/TimeoutClient.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/TimeoutRemoteResource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/TimeoutTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/com/ibm/ws/microprofile/rest/client/component/LibertyFTTimeoutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/com/ibm/ws/microprofile/rest/client/component/LibertyRestClientConfigListener.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/cdi/CDIInterceptorWrapperImpl.java
Labels: in:MicroProfile, team:Wendigo West

#6395 Add connection information to TCPChannel thrown exceptions
  dev/com.ibm.ws.channelfw/resources/com/ibm/ws/tcpchannel/internal/resources/TCPChannelMessages.nlsprops
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ConnectChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ConnectionManager.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/NBAcceptChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/NioTCPReadRequestContextImpl.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/SocketIOChannel.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/SocketRWChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/TCPPort.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/WorkQueueManager.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/util/Utils.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#6727 JSP slash slash comment fix
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/visitor/generator/ExpressionGenerator.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#6734 Updates to build files
  dev/com.ibm.ws.org.jose4j.0.5.1/build.gradle
  dev/com.ibm.ws.transaction.core_fat/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#6700 Avoid warning when no providers are specified for MP Rest Client 1.2
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West
