Repository OpenLiberty/open-liberty, pull requests merged in 2019-12, with the labels that each got.

#9932 Fix for Issue #9931: Ignore already closed exception during close for SSE Broadcast Tests
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BroadcasterApp/src/io/openliberty/sse/broadcaster/BroadcasterTestServlet.java
Labels: CLA Signed, noproductcode

#9963 fixed length for nonPersistentContextServiceRef for NP EJB Timer
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed

#9834 default SAN and multiple extInfo flags
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/DefaultSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolCommand.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/test/com/ibm/ws/crypto/certificateutil/keytool/KeytoolCommandTest.java
  dev/com.ibm.ws.crypto.certificateutil/test/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreatorTest.java
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTaskTest.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed, ID reviewed

#9974 Remove reinstateHADBLock optimisation
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
Labels: CLA Signed

#9901 Issue 9856: Add acmeCA as a no ship feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/resources/l10n/com.ibm.websphere.appserver.acmeCA-2.0.properties
Labels: CLA Signed, team:Core Security, team:Wendigo East

#9895 [9879] "setX" to "X" conversion for Mutations
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/query/PropertyOperationNameGenerator.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPDefaultInclusionStrategy.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicMutationApp/src/mpGraphQL10/basicMutation/BasicMutationTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/basicMutationApp/src/mpGraphQL10/basicMutation/GraphQLEndpoint.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9814 Issues: 9739 8302 - Remove attributes when get the sso cookie from sso token
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModuleTest.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenService.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/UserData.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenManager.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenService.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/TokenManagerImpl.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/ltpa/TokenFactory.java
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/TokenManagerImplTest.java
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/WebSecurityHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/LoggedOutTokenCacheImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImpl.java
Labels: CLA Signed

#9750 Issue #9307: Changing error message in Open Tracing to Warning message
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerConfigTest.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerTraceTest.java
  dev/com.ibm.ws.opentracing.1.1/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.2/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.3/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing.1.x_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
  dev/com.ibm.ws.opentracing/resources/com/ibm/ws/opentracing/resources/Opentracing.nlsprops
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingUserFeatureAccessService.java
  dev/com.ibm.ws.opentracing_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATTestBase.java
Labels: CLA Signed

#9924 Upgrade to latest version of Apache HTTP Client
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.httpcomponents/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10003 Get messaging.open_comms_fat building in eclipse
  dev/com.ibm.ws.messaging.open_comms_fat/.classpath
  dev/com.ibm.ws.messaging.open_comms_fat/.project
  dev/com.ibm.ws.messaging.open_comms_fat/.settings/bndtools.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#9982 Upgrade to Gradle 6.0.1
  dev/.gradle-wrapper/gradle-wrapper.properties
Labels: in:Build, noproductcode, team:Zombie Apocalypse

#9655 Batch collector properties, zero-partition partitioned step, status passed to reducer - fixes #9645, #9707, #9708
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/ExecutionElementControllerFactory.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/impl/ParallelStepBuilder.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/jsl/CloneUtility.java
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATTest.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ArrayUserDataDeserialize.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/CollectorPropertiesMapper.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/CollectorPropertiesPlan.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/resources/ZeroPartitionPlan.xml
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/deserialize/ArrayDeserializeServlet.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/app/misc1/Artifacts.java
  dev/com.ibm.ws.jbatch.misc_fat/test-applications/implicit/src/web/BatchFATServlet.java
  dev/com.ibm.ws.jbatch.misc_fat/util/src/fat/util/JobWaiter.java
Labels: CLA Signed

#9868 add state retry for oauth auth code flow
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
Labels: CLA Signed

#9998 Issue 9861: Add unit test infrastructure to acme project
  dev/com.ibm.ws.security.acme/.classpath
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/AcmeProviderServiceImplTest.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#9977 Fallback apply on and skip on 9671
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.1/src/org/eclipse/microprofile/faulttolerance/Fallback.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/AsyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/impl/SyncExecutor.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/FallbackState.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/FaultToleranceStateFactory.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/FallbackStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/FallbackStateNullImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/test/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/FallbackStateImplTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/AnnotationConfigFactoryImpl21.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/FallbackConfig21Impl.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1.cdi/test/src/com/ibm/ws/microprofile/faulttolerance21/cdi/config/impl/FallbackConfig21Test.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FallbackFunction.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/AnnotationConfigFactory.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/FallbackConfig.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/AnnotationConfigFactoryImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/AnnotationConfigFactoryImpl20.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/config/impl/FallbackConfigImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/FallbackPolicy.java
  dev/com.ibm.ws.microprofile.faulttolerance/src/com/ibm/ws/microprofile/faulttolerance/impl/policy/FallbackPolicyImpl.java
Labels: CLA Signed

#9338 Add diagnostics to print out where duplicated app path URLs are located
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/metadata/EndpointInfo.java
  dev/com.ibm.ws.jaxrs.2.0.server/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/component/JaxRsWebModuleInfoBuilder.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10001 [9878] Handle `@Id` on entity fields
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/OperationMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/type/DefaultTypeInfoGenerator.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/defaultvalueApp/src/mpGraphQL10/defaultvalue/WidgetInput.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ifaceApp/src/mpGraphQL10/iface/WidgetInput.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/typesApp/src/mpGraphQL10/types/WidgetInput.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9994 Map the Spring Boot application's context root to the application's welcome page(index)
  dev/com.ibm.ws.springboot.support.version20.test.war.app/src/main/java/com/ibm/ws/springboot/support/version20/test/war/app/JSPTestController.java
  dev/com.ibm.ws.springboot.support.version20.test.war.app/src/main/webapp/WEB-INF/jsp/index.jsp
  dev/com.ibm.ws.springboot.support.web.server.version15/resources/container/META-INF/spring.factories
  dev/com.ibm.ws.springboot.support.web.server.version15/src/com/ibm/ws/springboot/support/web/server/version15/container/LibertyJspTemplateProvider.java
  dev/com.ibm.ws.springboot.support.web.server.version20/resources/container/META-INF/spring.factories
  dev/com.ibm.ws.springboot.support.web.server.version20/src/com/ibm/ws/springboot/support/web/server/version20/container/LibertyJspTemplateProvider.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JSPTests20.java
Labels: CLA Signed

#10024 Revert "Issues: 9739 8302 - Remove attributes when get the sso cookie from sso token"
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModuleTest.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenService.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/UserData.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenManager.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenService.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/TokenManagerImpl.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/ltpa/TokenFactory.java
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/TokenManagerImplTest.java
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/WebSecurityHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/LoggedOutTokenCacheImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImpl.java
Labels: CLA Signed

#10009 service.ranking can be removed from com.ibm.ws.persistence defaultIns…
  dev/com.ibm.ws.persistence/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed, in:JPA, team:Blizzard

#9032 Enable featureUtility to install features for Open Liberty
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.install.featureUtility.featureutil/.classpath
  dev/com.ibm.ws.install.featureUtility.featureutil/.project
  dev/com.ibm.ws.install.featureUtility.featureutil/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.install.featureUtility.featureutil/.settings/org.eclipse.wst.common.project.facet.core.xml
  dev/com.ibm.ws.install.featureUtility.featureutil/bnd.bnd
  dev/com.ibm.ws.install.featureUtility/.classpath
  dev/com.ibm.ws.install.featureUtility/.project
  dev/com.ibm.ws.install.featureUtility/bnd.bnd
  dev/com.ibm.ws.install.featureUtility/resources/com/ibm/ws/install/featureUtility/internal/resources/FeatureUtilityToolOptions.nlsprops
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtilityExecutor.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureHelpAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallFeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallServerAction.java
  dev/com.ibm.ws.install.featureUtility_fat/.classpath
  dev/com.ibm.ws.install.featureUtility_fat/.project
  dev/com.ibm.ws.install.featureUtility_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.install.featureUtility_fat/.settings/org.eclipse.wst.common.project.facet.core.xml
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FATSuite.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/test/utils/TestUtils.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/servers/com.ibm.ws.install.featureUtility_fat/bootstrap.properties
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/autoFeatureServerXml/server.xml
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/noFeaturesServerXml/server.xml
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/serverX.zip
  dev/com.ibm.ws.install/.classpath
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallLogUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ProgressBar.java
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
Labels: CLA Signed, ID reviewed

#10034 nested transaction FFDC after rollback missed on error path
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
Labels: CLA Signed, team:Zombie Apocalypse

#10035 Get featureUtility projects building in eclipse
  dev/com.ibm.ws.install.featureUtility.featureutil/.classpath
  dev/com.ibm.ws.install.featureUtility.featureutil/.project
  dev/com.ibm.ws.install.featureUtility.featureutil/.settings/bndtools.core.prefs
  dev/com.ibm.ws.install.featureUtility/.classpath
  dev/com.ibm.ws.install.featureUtility/.project
  dev/com.ibm.ws.install.featureUtility/.settings/bndtools.core.prefs
  dev/com.ibm.ws.install.featureUtility_fat/.classpath
  dev/com.ibm.ws.install.featureUtility_fat/.project
  dev/com.ibm.ws.install.featureUtility_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.acme/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#10032 EJB Bindings Home Binding Name Tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/HomeBindingNameTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameEJB.jar/src/com/ibm/ejb3x/HomeBindingName/ejb/LocalHomeBindingName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameEJB.jar/src/com/ibm/ejb3x/HomeBindingName/ejb/LocalHomeBindingNameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameEJB.jar/src/com/ibm/ejb3x/HomeBindingName/ejb/LocalHomeBindingNameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameWeb.war/src/com/ibm/ejb3x/HomeBindingName/web/HomeBindingNameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameWeb.war/src/com/ibm/ejb3x/SimpleBindingName/web/SimpleBindingNameTestServlet.java
Labels: CLA Signed, noproductcode

#9935 OAuth ROPC flow should prefer user security name if different than supplied name
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20ComponentImpl.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20Constants.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/granttype/impl/OAuth20GrantTypeHandlerResourceOwnerCredentialsImpl.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/api/OAuth20Provider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/internal/LibertyOAuth20Provider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/ClientAuthentication.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/oauth/core/internal/oauth20/OAuth20ComponentImplTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/internal/LibertyOAuth20ProviderTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/ClientAuthenticationTest.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
Labels: CLA Signed, ID reviewed, team:Security SSO

#10015 Detect when unit testing
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
Labels: CLA Signed

#9682 Splash page
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/fonts/BunueloCleanPro-Light.woff
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/fonts/BunueloCleanPro-SemiBold.woff
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/fonts/IBMPlexSans-Regular.woff
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/hero-bg.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/beam.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/clouds.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/footer-img.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/github_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/gitter_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/groups_io_logo.jpeg
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/jakarta_ee_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/microprofile_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/open_liberty_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/open_liberty_title.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/stack_overflow_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/twitter_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/js/banner.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/js/externalize-string.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/welcome-message.png
Labels: CLA Signed

#10038 Enable Parallel Bundle Activation for some MP features
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi1.2-jndi1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi1.2-servlet3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi1.2-transaction1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrscdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpReactiveStreams1.0-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeeCompatible-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence.base-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.validation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.graphql-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.openapi-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.openapi-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.opentracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.opentracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.opentracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.messaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.streams.operators-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.wsspi.appserver.webBundle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-1.2/com.ibm.websphere.appserver.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.0/com.ibm.websphere.appserver.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.0/com.ibm.websphere.appserver.jaxrsClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/json-1.0/com.ibm.websphere.appserver.json-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonb-1.0/com.ibm.websphere.appserver.jsonb-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonp-1.0/com.ibm.websphere.appserver.jsonp-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.1/com.ibm.websphere.appserver.mpOpenAPI-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/com.ibm.websphere.appserver.mpOpenTracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/com.ibm.websphere.appserver.mpOpenTracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/com.ibm.websphere.appserver.mpOpenTracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/com.ibm.websphere.appserver.mpOpenTracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-1.0/com.ibm.websphere.appserver.mpReactiveStreams-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.0/com.ibm.websphere.appserver.mpRestClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.1/com.ibm.websphere.appserver.mpRestClient-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.2/com.ibm.websphere.appserver.mpRestClient-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/com.ibm.websphere.appserver.mpRestClient-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.0/com.ibm.websphere.appserver.opentracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/com.ibm.websphere.appserver.opentracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.2/com.ibm.websphere.appserver.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
Labels: CLA Signed

#10049 Get wsat building in eclipse
  dev/com.ibm.websphere.appserver.spi.wsat/build.gradle
  dev/com.ibm.ws.wsat.common/build.gradle
  dev/com.ibm.ws.wsat.webclient/build.gradle
  dev/com.ibm.ws.wsat.webservice/.classpath
  dev/com.ibm.ws.wsat.webservice/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.webservice/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.webservice/build.gradle
  dev/com.ibm.ws.wsat.webservice/build.xml
  dev/com.ibm.ws.wsat_fat/.classpath
  dev/com.ibm.ws.wsat_fat/.project
  dev/com.ibm.ws.wsat_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat_fat/bnd.bnd
  dev/com.ibm.ws.wsat_fat/build-test.xml
Labels: CLA Signed, team:Performance

#10008 Issue #10007: Fix test case to ensure app running before execution
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/MultiReleaseJarTest.java
Labels: CLA Signed, noproductcode

#10026 warnings in testMultipleInstancesCompeteToRunManyLateTasks
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest2.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10042 execdisabled bucket with failover enabled
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/fat/src/com/ibm/ws/concurrent/persistent/fat/execdisabled/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/fat/src/com/ibm/ws/concurrent/persistent/fat/execdisabled/PersistentExecutorExecutionDisabledTestWithFailoverEnabled.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10048 New public API to remove attrs from ltpa token
  dev/com.ibm.websphere.appserver.api.webcontainer.security.app/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.webAppSecurity-1.0.feature
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/ws/security/authentication/jaas/modules/TokenLoginModuleTest.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenService.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/UserData.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenManager.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/TokenService.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/TokenManagerImpl.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/ltpa/TokenFactory.java
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/TokenManagerImplTest.java
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/WebSecurityHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/package-info.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/LoggedOutTokenCacheImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImpl.java
Labels: CLA Signed

#10027 fix pacakge version and kept an old method
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/WebSecurityHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/websphere/security/web/package-info.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebSecurityHelperImpl.java
Labels: CLA Signed

#9968 Create more test cases for different error paths for the FAT
  dev/com.ibm.ws.install.featureUtility/resources/com/ibm/ws/install/featureUtility/internal/resources/FeatureUtilityToolOptions.nlsprops
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallFeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallServerAction.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FATSuite.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/test/utils/TestUtils.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/plainServerXml/server.xml
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/usrFeaturesServerXml/server.xml
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ProgressBar.java
Labels: CLA Signed, ID reviewed

#10060 Auto version update 20191120 2129
  dev/cnf/resources/bnd/liberty-release.props
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
Labels: CLA Signed

#9933 Update SQLServer Image
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/container-license-acceptance.txt
Labels: noproductcode, team:Zombie Apocalypse

#10036 Add ssl recovery test
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.transaction.db_fat/.classpath
  dev/com.ibm.ws.transaction.db_fat/.project
  dev/com.ibm.ws.transaction.db_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.db_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.db_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.db_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.db_fat/bnd.bnd
  dev/com.ibm.ws.transaction.db_fat/build.gradle
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/CustomPostgreSQLContainer.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/com.ibm.ws.transaction.db_fat/publish/files/ssl-certs/privkey.pem
  dev/com.ibm.ws.transaction.db_fat/publish/files/ssl-certs/server.crt
  dev/com.ibm.ws.transaction.db_fat/publish/files/ssl-certs/server.key
  dev/com.ibm.ws.transaction.db_fat/publish/files/ssl-certs/server.req
  dev/com.ibm.ws.transaction.db_fat/publish/servers/ssl-recovery/bootstrap.properties
  dev/com.ibm.ws.transaction.db_fat/publish/servers/ssl-recovery/resources/security/outboundKeys.p12
  dev/com.ibm.ws.transaction.db_fat/publish/servers/ssl-recovery/server.xml
  dev/com.ibm.ws.transaction.db_fat/test-applications/sslRecovery/src/com/ibm/ws/transaction/web/SSLRecoveryServlet.java
Labels: CLA Signed

#10053 tolerate 4 minute delay in infrastructure
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/test-applications/DelayExecution/src/web/PersistentExecutorsTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9991 Port oracle jdbc
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_oracle/.classpath
  dev/com.ibm.ws.jdbc_fat_oracle/.project
  dev/com.ibm.ws.jdbc_fat_oracle/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_oracle/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/build.gradle
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleUCPTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ucp/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ucp/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracleucpfat/src/ucp/web/OracleUCPTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10072 reduce the length of classpath for windows.
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, noproductcode, test bug

#10012 Change test to wait for LTPA service to start before running tests
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagation12Test.java
Labels: CLA Signed, in:MicroProfile, in:Security, noproductcode, team:Wendigo West

#10071 Revert "Revert "9392 batch remote partition recovery""
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/JobExecutionHelper.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/execution/impl/RuntimePartitionExecution.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntityV3.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotablePartitionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/RemotableSplitFlowEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityExtractor.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadExecutionEntityV2.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/StepThreadInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/TopLevelStepInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/AbstractPersistenceManager.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSJobRepository.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/WSRemotablePartitionState.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSJobRepositoryImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/ws/impl/WSStartupRecoveryServiceImpl.java
  dev/com.ibm.jbatch.container/test/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImplTest.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/dispatcher/BatchJmsDispatcher.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/listener/BatchJmsEndpointListener.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobInstances.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
Labels: CLA Signed

#9844 Initial drop for #9661- Copy com.ibm.ws.messaging.clientcontainer_fat to open-liberty
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/.classpath
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/.project
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/BasicCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/ClientMain.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/CompletionListenerBase.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/FATBase.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/MessageOrderCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/clientcontainer/fat/Util.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/clientcontainer/fat/ClientIDTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/clientcontainer/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/clientcontainer/fat/JMS1AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/clientcontainer/fat/JMS2AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/clientcontainer/fat/MessageListenerTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.ClientIDContainer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.ClientIDContainer/client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.JMS1Container/bootstrap.properties
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.JMS1Container/client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.JMS2Container/bootstrap.properties
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.JMS2Container/client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.MessageListenerContainer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.MessageListenerContainer/client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/servers/com.ibm.ws.open_clientcontainer.fat.Server/bootstrap.properties
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/servers/com.ibm.ws.open_clientcontainer.fat.Server/server.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientID.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientID.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientIDClient.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientIDClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientIDClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/ClientID.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSend.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSend.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/JMS1AsyncSend.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/SessionCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSend.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSend.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/ContextCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/JMS2AsyncSend.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListener.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListener.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/MessageListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/MessageListenerConnection.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/MessageListenerContext.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/clientcontainer/fat/MessageListenerSession.java
Labels: CLA Signed, noproductcode

#10083 Update FT 2.0 TCK to 2.0.3-RC1
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#9942 Kernel fixes for Maintenance
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/provisioning/AbstractResourceRepository.java
  dev/wlp-gradle/subprojects/assemble.gradle
Labels: CLA Signed

#10097 expected PersistenceException FFDC from failover test
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest2.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10082 errorpaths tests with failover enabled
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverAndPollingEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverEnabledNoPolling.java
Labels: CLA Signed, team:Zombie Apocalypse

#10045 Don't send same authcode twice
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs.nlsprops
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/PublicFacingErrorServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandlerTest.java
Labels: CLA Signed, ID reviewed

#9916 Mark start time when session is created instead of when first read.
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10079 Fix cleanup issues for feature utility fat
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/test/utils/TestUtils.java
Labels: CLA Signed, noproductcode

#10057 10030: On connection errors, free up the awaiting thread
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed

#10106 Add tx trace
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/publish/servers/com.ibm.ws.concurrent.persistent.fat.errorpaths/bootstrap.properties
Labels: CLA Signed, noproductcode

#10064 Fixed Infinispan session cache FAT tests for Windows
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10085 expected CWWKC1503W from testProgrammaticTimerFailsOverWhenTimerFailsOnOneServer
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest2.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10059 Improve equinox trace enablement
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/Activator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/LoggingConfigurationService.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/TrOSGiLogForwarder.java
Labels: CLA Signed, team:Performance

#10077 Use AccessController to get bundle context
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
Labels: CLA Signed

#10065 Parallelize features appClientSupport-1.0, batch-1.0, jdbc-4.1
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.iioptransport.transaction-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jndi1.0-iiop1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appclient.appClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appclient.client-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.clientContainerRemoteSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.clientContainerRemoteSupportCommon-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.iiopclient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.iiopcommon-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.iioptransport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-2.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.ws.persistence-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appClientSupport-1.0/com.ibm.websphere.appserver.appClientSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-1.0/com.ibm.websphere.appserver.batch-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.1/com.ibm.websphere.appserver.jdbc-4.1.feature
Labels: CLA Signed

#10103 More eclipse cleanup
  dev/com.ibm.ws.artifact_fat/.classpath
  dev/com.ibm.ws.cdi.noncontextual_fat/.classpath
  dev/com.ibm.ws.install.featureUtility.featureutil/.settings/org.eclipse.wst.common.project.facet.core.xml
  dev/com.ibm.ws.install.featureUtility_fat/.settings/org.eclipse.wst.common.project.facet.core.xml
  dev/com.ibm.ws.install/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jsf.2.2_fat/.classpath
  dev/com.ibm.ws.kernel.boot_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/.classpath
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/BasicCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientMain.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/CompletionListenerBase.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/FATBase.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageOrderCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/Util.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientIDTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS1AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListenerTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientIDClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientID.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS1AsyncSend.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/SessionCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/ContextCompletionListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSend.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListener.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListenerConnection.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListenerContext.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/MessageListenerClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListenerSession.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor_fat/.classpath
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/.classpath
  dev/com.ibm.ws.org.apache.cxf.ws.mex/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.audit.source/.classpath
Labels: CLA Signed, team:Performance

#10074 Strengthen lock on PersistableMetadata.
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/objectManager/PersistableImpl.java
Labels: CLA Signed

#10124 Revert "reduce the length of classpath for windows."
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, noproductcode

#10101 social login tai updates to construct default realm
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAISubjectUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/tai/TAISubjectUtilsTest.java
Labels: CLA Signed

#10054 Strip out async update and re-implement caching
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.4/src/org/eclipse/microprofile/config/spi/ConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/archaius/composite/CompositeConfig.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractConfig.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractConfigBuilder.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/ConfigBuilderImpl.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/ConfigImpl.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/SortedSourcesImpl.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/SourcedValueImpl.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/interfaces/SortedSources.java
  dev/com.ibm.ws.microprofile.config.1.1/test/src/com/ibm/ws/microprofile/config/internals/test/SortedSourcesTest.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/impl/Config13BuilderImpl.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14BuilderImpl.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14Impl.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/TypeCache.java
  dev/com.ibm.ws.microprofile.config.1.4/test/src/com/ibm/ws/microprofile/config14/test/ConversionTest.java
  dev/com.ibm.ws.microprofile.config.1.4/test/src/com/ibm/ws/microprofile/config14/test/TestType.java
  dev/com.ibm.ws.microprofile.config.1.4/test/src/com/ibm/ws/microprofile/config14/test/TestTypeConverter.java
Labels: CLA Signed

#9780 Revert "Revert "Remove EARLY_ACCESS test.""
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/AnnotationsBetaHelper.java
Labels: CLA Signed

#10119 Add permissions for db test
  dev/com.ibm.ws.transaction.db_fat/publish/servers/ssl-recovery/server.xml
Labels: CLA Signed, noproductcode

#10136 Fix for Issue #10135: Handle Connection refused exception in JAXRSWebContainerTest
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/webcontainer/JAXRSWebContainerTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#10116 Fix for Issue #10115: Improve Serviceability of JaxRsFactoryImplicitBeanCDICustomizer
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/CDITest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/RetryTest.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10095 Issue 10087: Fix merging of JVM options.
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/jvm.options
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9735 Helper methods for poolManagerMbean
  dev/com.ibm.websphere.appserver.api.connectionmanager/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.connectionManagement-1.0.feature
  dev/com.ibm.ws.jca.cm/bnd.bnd
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/mbean/ConnectionManagerMBean.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/mbean/package-info.java
Labels: CLA Signed

#9643 9602 - H2 Synchronization
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResult.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, team:Sirius

#10129 Redo of reducing the length of classpath for windows.
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, noproductcode

#9952 Access-Control-Allow-Max-Age is actually Access-Control-Max-Age
  dev/com.ibm.ws.webcontainer.cors/src/com/ibm/ws/webcontainer/cors/CorsHelper.java
  dev/com.ibm.ws.webcontainer.cors/test/com/ibm/ws/webcontainer/cors/CorsHelperTest.java
Labels: CLA Needed, CLA Signed

#10127 EJB Timer Service needs a way to check if fail over is enabled
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/ejb/TimersPersistentExecutor.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/OneExecutorRunsAllTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/OneExecutorRunsAllWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/OneExecutorRunsAllTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#10146 Handle forthcoming package rename of MetricRegistryFactory
  dev/com.ibm.ws.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/GraphQLExtension.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/MetricsInterceptor.java
Labels: CLA Signed, in:MicroProfile, in:MicroProfile/Metrics, team:Wendigo West

#10117 Uninstall features prior to installation in feature utility fat
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
Labels: CLA Signed, noproductcode

#10111 Don't always enable j2sec for com.ibm.ws.ejbcontainer.session.async.fat.AsyncWarnServer server
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/EJBTrace.properties
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/MetaDataTrace.properties
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/default.properties
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/servers/com.ibm.ws.ejbcontainer.session.async.fat.AsyncWarnServer/bootstrap.properties
Labels: noproductcode, test bug

#10112 Only reference ACE-report in error message if it will be created
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: in:Test Infrastructure, noproductcode, test bug

#10147 Correct processing of specific annotations.
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/classsource/internal/ClassSourceImpl_MappedContainer.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsScannerBaseImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsScannerOverallImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsScannerSpecificImpl.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/internal/SpecificAnnotationsImpl.java
Labels: CLA Signed

#10063 Add tests for unwrap to JDBC vendor specific API
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATJDBCSpecialOps.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/driver/derby/FATVendorSpecificSomething.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10132 10062 H2 test framework sendBytes() synchronization
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/connection/H2Connection.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, team:Sirius

#10160 Fix for Issue #10159: Handle quiesce operation did not complete errors for SSE Test
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/BasicSseTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#10161 Servicablity enhancement for handling NullPointerException from Infinispan session caching file name
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#10162 choose fail over approach with time-based claim
  dev/com.ibm.ws.concurrent.persistent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/Config.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/PartitionRecord.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/PersistentExecutorCompatibilityWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverAndPollingEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverEnabledNoPolling.java
  dev/com.ibm.ws.concurrent.persistent_fat_execdisabled/fat/src/com/ibm/ws/concurrent/persistent/fat/execdisabled/PersistentExecutorExecutionDisabledTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest2.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/publish/servers/com.ibm.ws.concurrent.persistent.fat.failover1serv/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/test-applications/failover1servApp/src/failover1serv/web/Failover1ServerTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest2.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/OneExecutorRunsAllWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_retry/fat/src/com/ibm/ws/concurrent/persistent/fat/retry/FailureRetryTests.java
Labels: CLA Signed, team:Zombie Apocalypse

#10143 Allow for server error messages to be shown
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/accountManager.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/clientAdmin.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/clientInputDialog.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/table.js
Labels: CLA Signed, team:Admin Center

#10166 Tolerate PostgreSQL connection failure
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
Labels: CLA Signed, noproductcode

#10152 remove temporary method
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/DefaultSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.java
Labels: CLA Signed

#10182 deadlock on maxPoolSize of 2
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverAndPollingEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/fat/src/com/ibm/ws/concurrent/persistent/fat/errorpaths/PersistentExecutorErrorPathsTestWithFailoverEnabledNoPolling.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10188 expected CWWCK1511W for CancellationException
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTestWithFailoverEnabled.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9944 Enable databse roation testing for locking tests
  dev/com.ibm.ws.concurrent.persistent_fat_locking/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_locking/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_locking/publish/servers/com.ibm.ws.concurrent.persistent.fat.locking/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9993 Moving JDBC FAT to OL
  dev/com.ibm.ws.jdbc_fat/.classpath
  dev/com.ibm.ws.jdbc_fat/.project
  dev/com.ibm.ws.jdbc_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/FATSuite.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceJaasTest.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceTest.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/TestGSSCredential.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/TestGSSLoginModule.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/TestGSSName.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/TestLoginModule.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/.gitignore
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/.gitignore
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/.gitignore
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/TestXAResource.java
  dev/com.ibm.ws.jdbc_fat/test-applications/dsdfat/resources/.gitignore
  dev/com.ibm.ws.jdbc_fat/test-applications/dsdfat/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/dsdfat/src/dsdfat/DSDTestServlet.java
  dev/com.ibm.ws.jdbc_fat/test-applications/dsdfat_global_lib/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/dsdfat_global_lib/src/dsdfat_global_lib/DSDGlobalLibTestServlet.java
  dev/com.ibm.ws.jdbc_fat/test-applications/jdbcapp/.gitignore
  dev/com.ibm.ws.jdbc_fat/test-applications/jdbcapp/resources/META-INF/application.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/setupfat/resources/.gitignore
  dev/com.ibm.ws.jdbc_fat/test-applications/setupfat/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/setupfat/src/setupfat/CheckSetupTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10149 Update code that determines token type
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
Labels: CLA Signed, release bug, team:Security SSO

#10173 Update Mongo FAT for IBMCertPathBuilderException FFDC
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLInvalidTrustTest.java
Labels: CLA Signed, noproductcode, team:Security SSO

#10177 Clean up reference non existent build/classes directory in bnd files
  dev/com.ibm.ws.jaxb.tools.2.3/jaxb-tools.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb-tools.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools.wadl2java/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools/wadl2java.bnd
Labels: CLA Signed, team:Performance

#10192 tolerate infrastructure slowness by waiting for recovery message
  dev/com.ibm.ws.concurrent.persistent_fat_retry/fat/src/com/ibm/ws/concurrent/persistent/fat/retry/FailureRetryTests.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10197 tolerate errors from transaction across server stop
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10175 Fault Tolerance 1.x timing fixes
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck11Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-10-subset.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-11-subset.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/AsyncBulkheadServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/beans/AsyncBulkheadBean.java
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTckLauncher.java
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, noproductcode

#10131 query and lock timeout on various databases
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcResultSet.java
Labels: CLA Signed, team:Zombie Apocalypse

#10206 restrict mbean test to public API to determine if the mbean is usable in Liberty
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/fat/src/com/ibm/ws/concurrent/persistent/fat/mbean/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/fat/src/com/ibm/ws/concurrent/persistent/fat/mbean/PersistentExecutorMBeanTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/files/server2.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/servers/com.ibm.ws.concurrent.persistent.fat.mbean/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/test-applications/persistentmbeantest/src/web/PersistentExecMBeanTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10213 test must wait for task to become successful
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/PersistentErrorTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10145 Issue 10144: Add range check on main Ldap search path
  dev/com.ibm.ws.security.wim.adapter.ldap/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/ADNestedGroupsWithRange.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.range/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.range/resources/security/ltpa.keys
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ad.range/server.xml
Labels: CLA Signed, team:Wendigo East

#10061 Issue #9246: Setup testing infrastructure for Pebble ACME CA.
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeCertificate.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/CSROptions.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/AcmeClientTest.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/AcmeProviderServiceImplTest.java
  dev/com.ibm.ws.security.acme_fat/.classpath
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/FATSuite.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/SimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/ChalltestsrvContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/PebbleContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/HttpChallengeServer.java
  dev/com.ibm.ws.security.acme_fat/publish/files/pebble-config.json
  dev/com.ibm.ws.security.acme_fat/publish/files/pebble.minica.pem
  dev/com.ibm.ws.security.acme_fat/test-applications/app1/src/app1/web/TestServletA.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Wendigo East

#10198 Wait for server config update to finish before continuing
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java
Labels: CLA Signed, noproductcode

#10190 Update server config before start of each test
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/HungRequestTiming.java
Labels: CLA Signed, noproductcode

#10199 Fix invalid delimiter in acmeCA-2.0 feature and move to full edition
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
Labels: CLA Signed

#7392 Compression of Response via Accept-Encoding Header
  dev/com.ibm.ws.transport.http.compression_fat/.classpath
  dev/com.ibm.ws.transport.http.compression_fat/.project
  dev/com.ibm.ws.transport.http.compression_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transport.http.compression_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transport.http.compression_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transport.http.compression_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transport.http.compression_fat/bnd.bnd
  dev/com.ibm.ws.transport.http.compression_fat/build.gradle
  dev/com.ibm.ws.transport.http.compression_fat/fat/src/com/ibm/ws/transport/http/FATSuite.java
  dev/com.ibm.ws.transport.http.compression_fat/fat/src/com/ibm/ws/transport/http/HttpCompressionTests.java
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compression-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionCommonConfig-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithPreferredAlgo-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithPreferredAlgoMisconfiguration-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithTypeAddRemoveDuplicate-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithTypeDuplicate-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithTypeDuplicateRemoval-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithTypeOverwriteAndAdd-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compressionWithTypes-server.xml
  dev/com.ibm.ws.transport.http.compression_fat/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.transport.http.compression_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.transport.http.compression_fat/test-applications/EndpointInformation/resources/WEB-INF/web.xml
  dev/com.ibm.ws.transport.http.compression_fat/test-applications/EndpointInformation/src/com/ibm/ws/transport/http/servlets/EndpointInformationServlet.java
  dev/com.ibm.ws.transport.http/bnd.bnd
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpChain.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpEndpointImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/compression/DeflateOutputHandler.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/compression/GzipOutputHandler.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, in:Transport, team:Sirius

#10194 Introduce startup script for sql server
  dev/fattest.databases/bnd.bnd
  dev/fattest.databases/resources/init-sqlserver.sql
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerUtil.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10043 Issue #8563:Update MyFaces to 2.3.6
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
Labels: CLA Signed, in:Web Components, team:Sirius

#10200 Close URLClassLoader to fix resource leak
  dev/com.ibm.ws.install.map/src/com/ibm/ws/install/map/InstallMap.java
Labels: CLA Signed

#10193 Fix Fault Tolerance messages
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
Labels: CLA Signed

#10223 remove inaccessible mbean and controller operations
  dev/com.ibm.ws.concurrent.persistent/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/websphere/concurrent/persistent/mbean/PersistentExecutorMBean.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/controller/Controller.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/controller/package-info.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/ControllerAutoSchedule.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorMBeanImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/src/web/MultiplePersistentExecutorsTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/fat/src/com/ibm/ws/concurrent/persistent/fat/oneexec/OneExecutorRunsAllTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_oneexec/test-applications/persistoneexectest/src/web/OneExecutorRunsAllTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/fat/src/com/ibm/ws/concurrent/persistent/fat/simctrl/SimulatedControllerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-applications/persistctrltest/src/web/SimulatedControllerPXTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/test-bundles/simcontroller/src/test/concurrent/persistent/fat/simctrl/SimulatedController.java
Labels: CLA Signed, team:Zombie Apocalypse

#10176 removing duplicate dbroation code
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat/publish/servers/com.ibm.ws.concurrent.persistent.fat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_locking/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_locking/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/com/ibm/ws/concurrent/persistent/fat/locking/PXLockTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_locking/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/publish/servers/com.ibm.ws.concurrent.persistent.fat.multiple/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerType.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10241 Migrate JPA Cache tests to Open Liberty
  dev/com.ibm.ws.jpa_spec20_fat/.classpath
  dev/com.ibm.ws.jpa_spec20_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPA20Cache_WEB.java
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20CacheServer/bootstrap.properties
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20CacheServer/database.xml
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20CacheServer/server.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_HSQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_Informix.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_MySQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_Postgres.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_SQLServer.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_CREATE_Sybase.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_DB2.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_DERBY.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_HSQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_Informix.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_MySQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_Postgres.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_SQLServer.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DELETE_Sybase.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_DB2.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_HSQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_Informix.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_MySQL.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_Postgres.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_SQLServer.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/ddl/WEB-INF/classes/JPA_CACHE_DROP_Sybase.ddl
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/CacheEntityCacheable.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/CacheEntityCacheableNot.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/CacheEntityCollection.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/CacheEntitySimple1.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/CacheEntitySimple2.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/Employee.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/JPA20EMEntityA.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/JPA20EMEntityB.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/model/JPA20EMEntityC.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/web/CacheTestServlet.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/web/FindCacheTestServlet.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/web/RefreshCacheTestServlet.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/src/com/ibm/ws/jpa/cache/web/UpdateEntityTask.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/META-INF/application.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/cacheWeb.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/cacheWeb.war/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/cacheWeb.war/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/cache/web/cacheWeb.war/WEB-INF/web.xml
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#10250 Update eclipse settings to match bnd settings
  dev/com.ibm.ws.concurrent.persistent_fat_locking/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_locking/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.acme_fat/.classpath
  dev/com.ibm.ws.security.acme_fat/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#10222 Synchronize use of shared SimpleDateFormat.
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_Utils.java
Labels: CLA Signed

#10252 Update edition of noship feature to be full
  dev/com.ibm.websphere.appserver.features/visibility/public/scim-2.0/com.ibm.websphere.appserver.scim-2.0.feature
Labels: CLA Signed, team:Performance

#10218 clarify message
  dev/com.ibm.ws.security.mp.jwt/resources/com/ibm/ws/security/mp/jwt/resources/MicroProfileJwtMessages.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#10255 update to MP Context Propagation 1.0.2 for TCK dependency on Jakarta EE 8
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.1.feature
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, team:Zombie Apocalypse

#10205 Disable featureUtility script generation
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
Labels: CLA Signed

#10231 Improve server update performance
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerUtil.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10233 Issue 10232: Add acme feature to acme_fat for Auto Fat Test Gen
  dev/com.ibm.ws.security.acme_fat/publish/servers/FATServer/server.xml
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#10220 Moving loginmodule to separate package
  dev/com.ibm.ws.jdbc_fat/.classpath
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/FATSuite.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/test-resource/loginmodule/src/loginmodule/TestGSSCredential.java
  dev/com.ibm.ws.jdbc_fat/test-resource/loginmodule/src/loginmodule/TestGSSLoginModule.java
  dev/com.ibm.ws.jdbc_fat/test-resource/loginmodule/src/loginmodule/TestGSSName.java
  dev/com.ibm.ws.jdbc_fat/test-resource/loginmodule/src/loginmodule/TestLoginModule.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10257 Add wsat.common translation from NLS PII Shipment 20001
  dev/com.ibm.ws.wsat.common/resources/com/ibm/ws/wsat/resources/WSAT_ko.nlsprops
  dev/com.ibm.ws.wsat.common/resources/com/ibm/ws/wsat/resources/WSAT_pt_BR.nlsprops
  dev/com.ibm.ws.wsat.common/resources/com/ibm/ws/wsat/resources/WSAT_ru.nlsprops
  dev/com.ibm.ws.wsat.common/resources/com/ibm/ws/wsat/resources/WSAT_zh.nlsprops
  dev/com.ibm.ws.wsat.common/resources/com/ibm/ws/wsat/resources/WSAT_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#10226 Add gzip support to CXF
  dev/com.ibm.ws.jaxws.wsat/src/com/ibm/ws/jaxws/wsat/WSATFeatureBusListener.java
Labels: CLA Signed

#10251 Add a test to ensure FT 1.x messages are produced
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIBulkheadTest.java
Labels: CLA Signed, noproductcode

#10219 Add exit trace points; fix-up trace messages
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/CommsOutboundChain.java
  dev/com.ibm.ws.messaging.comms.server/src/com/ibm/ws/jfap/inbound/channel/CommsInboundChain.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogFileHandle.java
Labels: CLA Signed

#10259 test failure com.ibm.ws.messaging.jms20.fat.mdb.jmsmdb test.test queue mdb
  dev/com.ibm.ws.messaging.security/bnd.bnd
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/internal/MessagingSecurityServiceImpl.java
Labels: CLA Signed

#10207 Add wsat recovery tests
  dev/com.ibm.ws.wsat.recovery_fat/.classpath
  dev/com.ibm.ws.wsat.recovery_fat/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat/.project
  dev/com.ibm.ws.wsat.recovery_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat/fat/src/com/ibm/ws/wsat/fat/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat/fat/src/com/ibm/ws/wsat/fat/SingleRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat/publish/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat/publish/features/wsatfat-1.0.mf
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/dynamicallyRemoveWSAT/serverWithWSAT.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/dynamicallyRemoveWSAT/serverWithoutWSAT.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/proxy/server_client.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/proxy/server_server1.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/proxy/server_server2.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_NNC.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_NYC.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YNC.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YSC.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YYCWithoutKeystore.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YYCdsslRef.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YYCnsslRef.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YYCssslRef.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_YYN.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_client.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_server1.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/files/ssl/server_server2.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery1/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery1/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery2/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery2/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATRecovery2/server.xml
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATSingleRecovery/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATSingleRecovery/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat/publish/servers/WSATSingleRecovery/server.xml
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/resources/WEB-INF/wsdl/RecoveryService.wsdl
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/Invoke.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/InvokeResponse.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/MultiRecoverySetupServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/ObjectFactory.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/Recovery.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/RecoveryCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/RecoveryService.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/RecoverySetupServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/SuicideServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryClient.war/src/com/ibm/ws/wsat/fat/client/recovery/package-info.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryServer.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryServer.war/resources/WEB-INF/wsdl/RecoveryService.wsdl
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryServer.war/src/com/ibm/ws/wsat/fat/server/MultiRecoveryCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryServer.war/src/com/ibm/ws/wsat/fat/server/Recovery.java
  dev/com.ibm.ws.wsat.recovery_fat/test-applications/recoveryServer.war/src/com/ibm/ws/wsat/fat/server/SuicideServlet.java
  dev/com.ibm.ws.wsat.recovery_fat/wsat.recovery_fat.bnd
Labels: CLA Signed, noproductcode

#10263 Migrate JPA 2.1 CDI FAT to Open Liberty.
  dev/com.ibm.ws.jpa_spec21_fat/.classpath
  dev/com.ibm.ws.jpa_spec21_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec21_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec21_fat/fat/src/com/ibm/ws/jpa/TestCDI.java
  dev/com.ibm.ws.jpa_spec21_fat/fat/src/com/ibm/ws/jpa/TestCDILib.java
  dev/com.ibm.ws.jpa_spec21_fat/publish/servers/JPA21CDIServer/bootstrap.properties
  dev/com.ibm.ws.jpa_spec21_fat/publish/servers/JPA21CDIServer/database.xml
  dev/com.ibm.ws.jpa_spec21_fat/publish/servers/JPA21CDIServer/server.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimple.ear/META-INF/application.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimple.ear/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimple.ear/TestCDISimple.war/WEB-INF/beans.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimple.ear/TestCDISimple.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimple.ear/TestCDISimple.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/META-INF/application.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/TestCDISimpleEJB.jar/META-INF/beans.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/TestCDISimpleEJB.jar/META-INF/ejb-jar.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/TestCDISimpleEJB.jar/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDISimpleEJB.ear/TestCDISimpleEJB.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/META-INF/application.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/TestCDIWithJPALib.war/WEB-INF/beans.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/TestCDIWithJPALib.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/lib/jpamodel.jar/META-INF/beans.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALib.ear/lib/jpamodel.jar/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/META-INF/application.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/TestCDIWithJPALibEJB.jar/META-INF/beans.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/TestCDIWithJPALibEJB.jar/META-INF/ejb-jar.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/TestCDIWithJPALibEJB.jar/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/apps/TestCDIWithJPALibEJB.ear/TestCDIWithJPALibEJB.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/ddl/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/ddl/WEB-INF/classes/JPA_CDI_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/ddl/WEB-INF/classes/JPA_CDI_DELETE_DERBY.ddl
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/ddl/WEB-INF/classes/JPA_CDI_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/CDIJPALibTestLogic.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/CDITestComponent.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/ejb/JPACDIWithJPALibSFEJB.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/ejb/JPACDIWithJPALibSFLocal.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/ejb/JPACDIWithJPALibSLEJB.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/ejb/JPACDIWithJPALibSLLocal.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/ejb/web/JPACDIWithJPALibEJBServlet.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/model/LoggingService.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/model/LoggingServiceImpl.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/model/Widget.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/model/WidgetEntityListener.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/jpalib/web/JPACDIJPALibServlet.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/CDISimpleTestLogic.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/CDITestComponent.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/ejb/JPACDISimpleSFEJB.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/ejb/JPACDISimpleSFLocal.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/ejb/JPACDISimpleSLEJB.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/ejb/JPACDISimpleSLLocal.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/ejb/web/JPACDISimpleEJBServlet.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/model/LoggingService.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/model/LoggingServiceImpl.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/model/Widget.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/model/WidgetEntityListener.java
  dev/com.ibm.ws.jpa_spec21_fat/test-applications/CDI/src/com/ibm/ws/jpa/fvt/cdi/simple/web/JPACDISimpleServlet.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard
