Repository OpenLiberty/open-liberty, pull requests merged in 2019-10, with the labels that each got.

#9144 Update to MP Context Propagation 1.0.1
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.1.feature
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
Labels: team:Zombie Apocalypse

#9120 basic test case where automatic persistent timer fails over to another server
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/ejb/autotimer/AutoCountingTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/web/FailoverTimersTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9095 Reduce runtime of ZipFileReaperTest
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9148 Update eclipse settings to get things building in eclipse again.
  dev/com.ibm.ws.microprofile.metrics.2.1.monitor_fat/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.2.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.http/.classpath
  dev/com.ibm.ws.request.probe.http/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.http/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.probe.http/build.gradle
  dev/com.ibm.ws.request.probe.jdbc/.classpath
  dev/com.ibm.ws.request.probe.jdbc/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.jdbc/build.gradle
  dev/com.ibm.ws.request.probe.servlet/.classpath
  dev/com.ibm.ws.request.probe.servlet/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.probe.servlet/build.gradle
  dev/com.ibm.ws.request.timing.jdbc/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.timing.jdbc/build.gradle
  dev/com.ibm.ws.request.timing.servlet/.classpath
  dev/com.ibm.ws.request.timing.servlet/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.timing.servlet/build.gradle
  dev/com.ibm.ws.request.timing/.classpath
  dev/com.ibm.ws.request.timing/bnd.bnd
Labels: CLA Signed, team:Performance

#9123 Issue #9122: Remove extra ;
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: CLA Signed, in:Web Components, team:Sirius

#9101 Add oracle jdbc maven dependency
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_timers/build.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9159 rename to missedTaskThreshold
  dev/com.ibm.ws.concurrent.persistent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/Config.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/publish/servers/com.ibm.ws.concurrent.persistent.fat.failover1serv/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverA/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#9125 Build fat test integration passing
  dev/build.image/packaging/.gitignore
  dev/build.image/packaging/debuild/openliberty/debian/postinst
  dev/build.image/packaging/debuild/openliberty/debian/postrm
  dev/build.image/packaging/openliberty.spec.template
  dev/com.ibm.ws.os.packaging_fat/.classpath
  dev/com.ibm.ws.os.packaging_fat/.project
  dev/com.ibm.ws.os.packaging_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.os.packaging_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.os.packaging_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.os.packaging_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.os.packaging_fat/bnd.bnd
  dev/com.ibm.ws.os.packaging_fat/build.gradle
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/FATSuite.java
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/InstallRhelTest.java
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/InstallUbuntuTest.java
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/InstallUtilityToolTest.java
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/SimpleTest.java
  dev/com.ibm.ws.os.packaging_fat/publish/servers/com.ibm.ws.os.packaging_fat/bootstrap.properties
  dev/com.ibm.ws.os.packaging_fat/publish/servers/com.ibm.ws.os.packaging_fat/server.xml
Labels: CLA Signed

#9134 JSON-B integration for property names, date format, etc.
  dev/build.image/scripts/Liberty- server remote debug.launch
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/GraphQLSchemaGenerator.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/ScalarMapperExtension.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/common/ArrayAdapter.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/common/ScalarMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/strategy/AbstractInputHandler.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/strategy/AutoScanAbstractInputHandler.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/TypedElement.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/jackson/JacksonValueMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/jsonb/JsonbValueMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/value/jsonb/JsonbValueMapperFactory.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/util/Defaults.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/util/Scalars.java
  dev/com.ibm.ws.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/DataFetcherResultOutputConverter.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/GraphQLExtension.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPDateTimeScalarMapperExtension.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPDefaultInclusionStrategy.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPOperationBuilder.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MethodUtils.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/.classpath
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/InputFieldsTest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/OutputFieldsTest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.inputFields/bootstrap.properties
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.inputFields/jvm.options
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.inputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.outputFields/bootstrap.properties
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.outputFields/jvm.options
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.outputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/resources/graphiql.html
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/AllWidgetData.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/GraphQLClient.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/GraphQLOperation.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/InputFieldsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/LoggingFilter.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/Widget.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/WidgetQueryResponse.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/resources/graphiql.html
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/AllWidgetData.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/GraphQLClient.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/GraphQLOperation.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/LoggingFilter.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/OutputFieldsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/Widget.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/WidgetQueryResponse.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/bootstrap.properties
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9171 Update JSP 404 msg
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPErrorReport.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#9037 configure uri on httpSessionCache for a bell
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9175 Issue 9174: Address review comments on CachedDBOidcClientProviderTest
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProviderTest.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#9173 Update ResponseUrlExpectationTest for different JDK behavior
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/expectations/ResponseUrlExpectationTest.java
Labels: CLA Signed, noproductcode, team:Security SSO

#8196 7234-TRACENPE COMMIT1
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSGSSExportedNameConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSGeneralNameConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSSASMechConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSServiceConfigurationConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSUnknownServiceConfigurationConfig.java
Labels: CLA Signed, release bug

#8197 7238 cs iv2 extractssl
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/css/CSSCompoundSecMechConfig.java
Labels: CLA Signed, release bug

#9103 PR to Change SAML20UnsloictedState in Constants
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/Constants.java
Labels: CLA Signed, release bug, team:Security SSO

#8270 Porting persistant_fat test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat/.project
  dev/com.ibm.ws.concurrent.persistent_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DDLGenScriptHelper.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/SchedulerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat/persistent_fat.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/publish/files/features/timerInterfacesTestFeature-1.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat/publish/servers/com.ibm.ws.concurrent.persistent.fat/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat/publish/servers/com.ibm.ws.concurrent.persistent.fat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/CancelableTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/CancelingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/CustomResult.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/DBIncrementTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/FixedRepeatTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/ManagedTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/ResultBasedTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SelfCancelingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SelfRemovingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SharedRollbackTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/TriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/VaryingRepeatTrigger.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-bundles/timerInterfacesTestFeature/src/test/feature/sim/ejb/timer/TimerTriggerTask.java
  dev/com.ibm.ws.concurrent.persistent_fat/timerInterfacesTestFeature.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9154 Upgrade to ASM 7.2 for Java 14 support
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#9191 Remove bus extensions that will never be loadable.
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/resources/META-INF/cxf/bus-extensions.txt
Labels: CLA Signed, focalApproved:performance, performance

#9189 AdminPermission granted to test app in wrong location
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9194 initial tests of failover when app stops
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/InvokerTask.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverA/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/configDropins/overrides/fatSecondaryPorts.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/ejb/autotimer/AutoCountingSingletonTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/ejb/stateless/StatelessTxSuspendedBean.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/web/FailoverTimersTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9060 Clean up build/libs for FATs on automated builds to conserve disk space
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#9163 Issue #8899: Federated repositories is using non-participating base e…
  dev/com.ibm.ws.security.wim.adapter.file_fat/fat/src/com/ibm/ws/security/wim/adapter/file/fat/BasicTests.java
  dev/com.ibm.ws.security.wim.adapter.file_fat/fat/src/com/ibm/ws/security/wim/adapter/file/fat/WithRepoConfiguredWithoutIDTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADLDAP_NoIdTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADLDAP_SSLTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_CustomLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_Federation_2LDAPsTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAP_DefaultConfigTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAP_SSLTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_TDSLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_TDSLDAP_FailoverTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_TDSLDAP_SSLTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/server.xml
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ConfigManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core/test/com/ibm/ws/security/wim/ProfileManagerUpdateTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/InvalidBaseEntryInRealmTest.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/BridgeUtils.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/DisplayNameBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/MembershipBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SearchBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SecurityNameBridge.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/UniqueIdBridge.java
  dev/com.ibm.ws.security.wim.registry/test/com/ibm/ws/security/wim/ProfileManagerInvalidRealmTest.java
  dev/com.ibm.ws.security.wim.registry/test/com/ibm/ws/security/wim/ProfileManagerUpdateTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/WIMURRegressionTest.java
Labels: CLA Signed, team:Wendigo East

#9198 Revert "7234-TRACENPE COMMIT1"
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSGSSExportedNameConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSGeneralNameConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSSASMechConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSServiceConfigurationConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/tss/TSSUnknownServiceConfigurationConfig.java
Labels: CLA Signed

#8434 Issue #7701: Pull in MyFaces 2.3.4
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/FacesContextImplBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/application/FacesServletMappingUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared_impl/webapp/webxml/WebXml.java
Labels: CLA Signed, in:Web Components, team:Sirius

#9150 Fix for Issue #9139: Don't use Liberty thread pool for SSE when running Java 8
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9170 add missedTaskThreshold in simplicity and update tests
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/PersistentExecutor.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9182 Issue 9178: Add eyecatcher on remote ldap failure/zOS run
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#9224 allow a hiccup during the config file parse
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/MessageConstants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/servers/ServerTracker.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/servers/ServerTrackerTest.java
Labels: CLA Signed, in:Test Infrastructure, team:Security SSO

#9168 Check for race condition when getting services
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
Labels: CLA Signed

#9149 Build a new MP Config instance each time and close when done
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ApplicationProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ConfigProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/CustomCSSProcessor.java
Labels: CLA Signed

#9176 Update createProperty logic
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat/test-applications/schedtest/src/web/SchedulerFATServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9216 clean up various TODOs
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/sessionCacheConfigApp/src/session/cache/infinispan/web/SessionCacheConfigTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server.mphealth/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server.mphealth/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9213 Create microProfile-3.1 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/com.ibm.websphere.appserver.microProfile-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.1/resources/l10n/com.ibm.websphere.appserver.microProfile-3.1_zh_TW.properties
Labels: CLA Signed, ID review not needed

#9233 Update cnf oss maven files
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
Labels: CLA Signed, noproductcode, team:Performance

#9218 Remove `@Deprecated` references and tests
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/common/EnumMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/strategy/query/AnnotatedResolverBuilder.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/deprecationApp/src/mpGraphQL10/deprecation/Widget.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/MyGraphQLEndpoint.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/outputFieldsApp/src/mpGraphQL10/outputFields/MyGraphQLEndpoint.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9185 Issue9169-KeystoreLoadError
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#9229 Performance improvement for local builds
  dev/build.image/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat/build.gradle
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Continuous Delivery

#9237 unnecessary failover attempt results in too much locking
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/ejb/stateless/StatelessProgrammaticTimersBean.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/web/FailoverTimersTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9211 Add senderConfig to reporterConfig
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/JaegerTracerFactory.java
Labels: CLA Signed

#9223 Fixes 261572, checks if session is valid before invalidating
  dev/com.ibm.ws.session/src/com/ibm/ws/session/store/memory/MemorySession.java
Labels: CLA Signed

#9167 initial code drop for cacerts in config drop
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.spi.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/core/WSX509TrustManagerTest.java
Labels: CLA Signed, ID reviewed, team:Core Security

#9066 Update Commons BeanUtils to 1.9.4
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.beanValidationCore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.org.apache.commons.beanutils/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.beanutils/bnd.overrides
Labels: CLA Signed, in:Web Components, team:Sirius

#9222 remove obsolete tests that were used to explore a potential design for which product function was never added
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.project
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_cache/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_cache/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_cache/fat/src/com/ibm/ws/concurrent/persistent/fat/cache/ControllerCacheTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/fat/src/com/ibm/ws/concurrent/persistent/fat/cache/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverA/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverA/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverB/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/servers/serverB/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/src/test/controller/cache/web/ControllerCacheTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_cache/test-applications/controllerCacheApp/src/test/controller/cache/web/TestCacheEntryCreatedOrExpiredListener.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9113 lengthen lease timeout parameters
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD001/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD002/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
Labels: CLA Signed, noproductcode

#9261 Fix threading issue in BaseCache
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/BaseCache.java
Labels: CLA Signed, bug, team:Security SSO

#9274 Revert "Performance improvement for local builds"
  dev/build.image/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat/build.gradle
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#9253 Add RESTHandler Auditing
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditConstants.java
  dev/com.ibm.ws.request.probe.audit.servlet/src/com/ibm/ws/request/probe/audit/servlet/AuditPE.java
  dev/com.ibm.ws.rest.handler/bnd.bnd
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/internal/service/RESTHandlerContainerImpl.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/RESTAuthorizationEvent.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/Audit.java
Labels: CLA Signed, team:Wendigo East

#9235 Do not cache Exchange properties in MessageImpl
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
Labels: CLA Signed, performance, team:Performance

#9302 Revert "initial code drop for cacerts in config drop"
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.spi.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/core/WSX509TrustManagerTest.java
Labels: CLA Signed

#9244 Eclipse settings cleanup for anno_fat
  dev/com.ibm.ws.anno_fat/.classpath
  dev/com.ibm.ws.anno_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jbatch.jms/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.audit.source/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#9278 Adding cert from the environment
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/CertificateEnvHelper.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed, team:Core Security

#9297 Never set MaxPermSize and remove generation of WLP_SKIP_MAXPERMSIZE
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/CreateCommandTest.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/BootstrapConfigTest.java
Labels: CLA Signed, in:JDK Infrastructure, in:Kernel/Bootstrap, team:Zombie Apocalypse

#9295 Move mpGraphQL-1.0 feature to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.graphql-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9312 Update eclipse settings for transaction.test.util
  dev/com.ibm.ws.transaction.test.util/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.test.util/bnd.bnd
Labels: CLA Signed, team:Performance

#9092 EJBCustomBindings: Initial Implementation of ejblocal: namespace
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbliteJNDI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.spi.containerServices/bnd.bnd
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/EJBLocalNamingHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/LocalColonEJBNamingHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/package-info.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/DefaultBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.noInterface.fat.server/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.noInterface.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingAbstractServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingSingletonServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingStatefulServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingStatelessServlet.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/BindingsHelper.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/NameSpaceBinder.java
  dev/com.ibm.ws.ejbcontainer/bnd.bnd
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/SystemNameSpaceBinderImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBJavaColonNamingHelper.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBLocalNamingHelperImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBNamingInstancer.java
  dev/com.ibm.ws.ejbcontainer_test/test/com/ibm/ws/ejbcontainer/mock/MockEJBJavaColonNamingHelper.java
  dev/com.ibm.ws.jndi.ejb/.classpath
  dev/com.ibm.ws.jndi.ejb/.gitignore
  dev/com.ibm.ws.jndi.ejb/.project
  dev/com.ibm.ws.jndi.ejb/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jndi.ejb/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jndi.ejb/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jndi.ejb/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jndi.ejb/bnd.bnd
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/EJBLocalURLContext.java
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/EJBLocalURLContextFactory.java
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/EJBNamingEnumeration.java
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/ResourceConstants.java
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/package-info.java
Labels: CLA Signed

#9306 Re-deliver initial code drop for cacerts in config drop
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.spi.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/core/WSX509TrustManagerTest.java
Labels: CLA Signed

#9304 Revert "Revert "initial code drop for cacerts in config drop""
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.spi.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/core/WSX509TrustManagerTest.java
Labels: CLA Signed

#9314 internal attribute to gate experimentation with infinispan config
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#9264 persist information about which instances repeatedly poll and detect missed tasks
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/Partition.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/PartitionRecord.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#9286 Update JQuery to 3.4.1
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/common/lib/jquery/jquery.min.js
Labels: CLA Signed

#9311 JSP FAT update for expected warnings
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#9118 Add session cache tests for Infinispan in a container
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.classpath
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.project
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.settings/bndtools.core.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan_container/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan_container/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan_container/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/files/infinispan/config.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/files/infinispan/users.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server.mphealth/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server.mphealth/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/shared/resources/infinispan/infinispan.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/AppObject.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean1.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean2.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener1/SessionListener.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener2/SessionListener.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9287 GPG key Logic
  dev/build.image/build.gradle
  dev/build.image/packaging/buildOsNativePackages.sh.template
  dev/build.image/packaging/buildOsNativePackagesGPGKey.sh
  dev/build.image/packaging/buildOsNativePackagesNoGPGKey.sh
  dev/build.image/packaging/debBuild.expect
  dev/build.image/packaging/rpmBuild.expect
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed

#9082 Fix chkpii errors in NLS files
  dev/com.ibm.ws.security.registry_test.custom/resources/OSGI-INF/l10n/metatype.properties
Labels: ID review not needed, L2 ReviewNotRequired

#9250 Fix issues with FAT JsonConfigTest to check correct lines
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigTest.java
Labels: CLA Signed, noproductcode

#9271 Merge jaeger-1.0 into mpOpenTracing-1.3
  dev/com.ibm.websphere.appserver.features/visibility/public/jaeger-1.0/com.ibm.websphere.appserver.jaeger-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaeger-1.0/resources/l10n/com.ibm.websphere.appserver.jaeger-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
  dev/com.ibm.ws.microprofile.opentracing.jaeger/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/JaegerTracerFactory.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/fat/src/com/ibm/ws/microprofile/opentracing/jaeger_fat/JaegerConfigTest.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer1/server.env
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer1/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer2/server.env
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer2/server.xml
  dev/com.ibm.ws.opentracing.1.3/bnd.bnd
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
Labels: CLA Signed

#9318 Add jakartaee-8.0 to javaee8 profile zip
  dev/build.image/profiles/javaee8/features.xml
Labels: CLA Signed, team:Zombie Apocalypse

#9326 experiment with temporary files for infinispan config
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9337 expected errors after transaction abort
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/PostgreSQLTest.java
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9331 Add check on filebased path
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#9325 Add com.ibm.ws.org.apache.commons.httpclient
  dev/com.ibm.ws.org.apache.commons.httpclient/.classpath
  dev/com.ibm.ws.org.apache.commons.httpclient/.gitignore
  dev/com.ibm.ws.org.apache.commons.httpclient/.project
  dev/com.ibm.ws.org.apache.commons.httpclient/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.httpclient/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.httpclient/bnd.overrides
Labels: CLA Signed, team:Security SSO

#9320 Adjust retry on RemoteFile
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/RemoteFile.java
Labels: CLA Signed, noproductcode

#9289 Add missing dsannotation line
  dev/com.ibm.ws.artifact.overlay/bnd.bnd
Labels: CLA Signed

#9280 manually updated rpm/deb changelogs
  dev/build.image/packaging/changelog.template
  dev/build.image/packaging/openliberty.spec.template
Labels: CLA Signed, in:Install

#9361 Revert "GPG key Logic "
  dev/build.image/build.gradle
  dev/build.image/packaging/buildOsNativePackages.sh.template
  dev/build.image/packaging/buildOsNativePackagesGPGKey.sh
  dev/build.image/packaging/buildOsNativePackagesNoGPGKey.sh
  dev/build.image/packaging/debBuild.expect
  dev/build.image/packaging/rpmBuild.expect
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed

#9330 Update yoko for issues #8539 and #6831
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#9290 MicroProfile HelloWorld test
  dev/com.ibm.ws.microprofile.1.0_fat/.classpath
  dev/com.ibm.ws.microprofile.1.0_fat/.project
  dev/com.ibm.ws.microprofile.1.0_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.1.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.1.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.1.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/tests/helloworld/HelloWorldApplication.java
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/tests/helloworld/HelloWorldBean.java
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/tests/helloworld/HelloWorldResource.java
  dev/com.ibm.ws.microprofile.1.0_fat/publish/servers/MPServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.1.0_fat/publish/servers/MPServer/server.xml
  dev/com.ibm.ws.microprofile.1.2_fat/.classpath
  dev/com.ibm.ws.microprofile.1.2_fat/.project
  dev/com.ibm.ws.microprofile.1.2_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.1.2_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.1.2_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.1.2_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/tests/helloworld/HelloWorldApplication.java
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/tests/helloworld/HelloWorldBean.java
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/tests/helloworld/HelloWorldResource.java
  dev/com.ibm.ws.microprofile.1.2_fat/publish/servers/MPServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.1.2_fat/publish/servers/MPServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/invalid/LibertyLoginModuleInvalidTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tls/KafkaTlsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/ConnectorProperties.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/MissingGroupIDTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/PropertiesAsset.java
Labels: CLA Signed, noproductcode

#9208 Set TCCL before calling OASFilter
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ApplicationProcessor.java
  dev/com.ibm.ws.microprofile.openapi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/complete-flow/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/complete-flow/src/app/web/complete/flow/filter/OASFilterImpl.java
Labels: CLA Signed

#9355 Update openapi projects to build in eclipse
  dev/com.ibm.websphere.appserver.spi.openapi.3.1/.project
  dev/com.ibm.websphere.appserver.spi.openapi.3.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.spi.openapi.3.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.spi.openapi.3.1/bnd.bnd
  dev/com.ibm.websphere.openapi.3.1/.classpath
  dev/com.ibm.websphere.openapi.3.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.openapi.3.1/bnd.bnd
  dev/com.ibm.ws.openapi.3.1.private/.classpath
  dev/com.ibm.ws.openapi.3.1.private/.settings/bndtools.core.prefs
  dev/com.ibm.ws.openapi.3.1.private/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.openapi.3.1.private/bnd.bnd
  dev/com.ibm.ws.openapi.3.1.public/.classpath
  dev/com.ibm.ws.openapi.3.1.public/.settings/bndtools.core.prefs
  dev/com.ibm.ws.openapi.3.1.public/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.openapi.3.1.public/bnd.bnd
  dev/com.ibm.ws.openapi.3.1/.classpath
  dev/com.ibm.ws.openapi.3.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.openapi.3.1/bnd.bnd
  dev/com.ibm.ws.openapi.ui.private/.classpath
  dev/com.ibm.ws.openapi.ui.private/.project
  dev/com.ibm.ws.openapi.ui.private/.settings/bndtools.core.prefs
  dev/com.ibm.ws.openapi.ui.private/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.openapi.ui.private/bnd.bnd
  dev/com.ibm.ws.openapi.ui.private/build.gradle
  dev/com.ibm.ws.openapi.ui/.classpath
  dev/com.ibm.ws.openapi.ui/.settings/bndtools.core.prefs
  dev/com.ibm.ws.openapi.ui/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, team:Performance

#9360 Add com.ibm.ws.security.oauth.jwt unit tests
  dev/com.ibm.ws.security.oauth.jwt/.classpath
  dev/com.ibm.ws.security.oauth.jwt/bnd.bnd
  dev/com.ibm.ws.security.oauth.jwt/test/com/ibm/ws/security/oauth20/jwt/GrantTypeCustomizeHandlerJwtImplTest.java
  dev/com.ibm.ws.security.oauth.jwt/test/com/ibm/ws/security/oauth20/jwt/JwtGrantTypeHandlerConfigTest.java
Labels: CLA Signed, team:Security SSO

#9352 Update server.xml with network permissions
  dev/com.ibm.ws.messaging.open_fat/publish/servers/FATJmsServer/server.xml
Labels: CLA Signed, noproductcode

#9340 Java 13 fat test update
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileContainer.java
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/FATSuite.java
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/Java13Test.java
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/MultiReleaseJarTest.java
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java13-server/apps/java13-app.war
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java13-server/bootstrap.properties
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java13-server/server.xml
  dev/com.ibm.ws.java11_fat/publish/servers/server_MultiReleaseJarTest/lib/multiRelease.jar
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/jar/MRClass_RequireJava13.java
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/jar/MRClass_RequireJava14.java
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/jar/MRClass_RequireJava15.java
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/jar/MRClass_RequireJava16.java
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/jar/MRClass_RequireJava17.java
  dev/com.ibm.ws.java11_fat/test-applications/multiReleaseApp/src/java11/multirelease/web/MultiReleaseJarTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9131 BNFHeader find header ignore case
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
Labels: CLA Signed

#9327 Added the mpHealth-1.0 TCKs to OL FAT
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.project
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/fat/src/com/ibm/ws/microprofile/health/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/fat/src/com/ibm/ws/microprofile/health/tck/HealthTCKLauncher.java
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/servers/HealthTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/servers/HealthTCKServer/jvm.options
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/servers/HealthTCKServer/server.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/.gitignore
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health/test/URIProviderProducer.java
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#9104 Issue #8824 : fix defaultServer create on start with minus sign in se…
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/StartCommandTest.java
Labels: CLA Signed, release bug

#9367 PR for Issue 8860: Update JwkRetriever to avoid getting SSL factory for HTTP calls
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
Labels: CLA Signed, team:Security SSO

#9371 moved testDataFrameAfterContinuationFrame to Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#9372 9366: Disable new H2 stress tests
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
Labels: CLA Signed, noproductcode, team:Sirius, test bug

#9363 Enable discovery of PKCE code challenge methods
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OIDCConstants.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/DiscoveryTest.java
Labels: CLA Signed

#9389 Convert identity sets to equality sets for public returns.
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsImpl_Targets.java
Labels: CLA Signed

#9359 default server file updates
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/defaultServer/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/javaee7/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/javaee8/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile1/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile2/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile3/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot1/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot2/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile7/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile8/server.xml
Labels: CLA Signed

#9374 Cache OSGi Services, add more shutdown checks and a couple of performance tweaks
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/AppPropertyConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/OSGiConfigUtils.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/ServerXMLDefaultVariableConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/sources/ServerXMLVariableConfigSource.java
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#9301 Issues with Javamail test failures
  dev/com.ibm.ws.javamail.1.6/src/com/ibm/ws/javamail/internal/injection/MailSessionDefinitionInjectionBinding.java
  dev/com.ibm.ws.javamail.1.6/src/com/ibm/ws/javamail/internal/injection/MailSessionResourceFactoryBuilder.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/fvtweb/src/fvtweb/web/JavamailFATServlet.java
Labels: CLA Signed

#9351 Add test utilities
  dev/com.ibm.ws.transaction.test.util/publish/features/txtest-1.0.mf
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/ws/cloudtx/ut/util/CloudTestServletBase.java
Labels: CLA Signed

#9394 Remove com.ibm.ws.kernel.service.location project
  dev/com.ibm.ws.kernel.service.location/.classpath
  dev/com.ibm.ws.kernel.service.location/.gitignore
  dev/com.ibm.ws.kernel.service.location/.project
  dev/com.ibm.ws.kernel.service.location/.settings/bndtools.core.prefs
  dev/com.ibm.ws.kernel.service.location/bnd.bnd
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/pseudo/internal/PseudoContext.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/pseudo/internal/PseudoContextFactory.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/pseudo/internal/package-info.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/Activator.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/FileLocator.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/InternalLocationConstants.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/InternalWsResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/LocalDirectoryResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/LocalFileResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/RemoteResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/ResourceIterators.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/ResourceUtils.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/SymbolRegistry.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/SymbolicRootResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/UndeletableFile.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/VariableRegistryHelper.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/VirtualRootResource.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/WsLocationAdminImpl.java
  dev/com.ibm.ws.kernel.service.location/src/com/ibm/ws/kernel/service/location/internal/package-info.java
Labels: CLA Signed

#9357 add heart beats per the heartbeatInterval
  dev/com.ibm.ws.concurrent.persistent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/Config.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/publish/servers/com.ibm.ws.concurrent.persistent.fat.failover1serv/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#9396 Add artifact downloader and progress bar
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ProgressBar.java
Labels: CLA Signed

#9376 update yoko to deliver yoko ACEs fix
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#9418 Notices for 19.0.0.11
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#8964 Make primaryServerQuery public
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LdapFailoverTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/ReadTimeoutTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.return.to.primary/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.return.to.primary/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
Labels: CLA Signed, ID Required, ID reviewed, L2 ReviewNotRequired, team:Wendigo East

#9401 Issue #9397: injection_fat fails with NameNotFoundException
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/OSGiInjectionScopeData.java
  dev/com.ibm.ws.injection/test/com/ibm/ws/injection/JndiHelperUnitTest.java
  dev/com.ibm.ws.injection/test/com/ibm/ws/injection/OSGiInjectionScopeDataTest.java
  dev/com.ibm.ws.injection/test/com/ibm/ws/injection/mock/MockInjectionJavaColonHelper.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnEJB.jar/src/com/ibm/ws/injection/dsdann/ejb/DSDSingletonBean.java
  dev/com.ibm.ws.injection_fat/test-applications/DSDAnnWeb.war/src/com/ibm/ws/injection/dsdann/web/BasicDSDAnnServlet.java
Labels: CLA Signed, team:Blizzard

#9410 Revert "default server file updates"
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/defaultServer/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/javaee7/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/javaee8/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile1/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile2/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile3/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot1/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/springBoot2/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile7/server.xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile8/server.xml
Labels: CLA Signed

#9434 9433 Update H2 test expectations
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#9429 lower case cert
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#9240 Update OpenSAML to version 2.6.6
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
  dev/com.ibm.ws.org.opensaml.opensaml/bnd.bnd
  dev/com.ibm.ws.org.opensaml.opensaml/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml/build.gradle
Labels: CLA Signed, team:Security SSO

#9369 Fix determine token type
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
Labels: CLA Signed, release bug, team:Security SSO

#9435 Fix Java 2 security issue with getting thread context classloader
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
Labels: CLA Signed, in:MicroProfile/Metrics, team:Wendigo West

#9425 ignore ssl errors
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/CloudantTestOutboundSSL.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius, test bug

#9377 tolerate intermittent benign message
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_env.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_noenv.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_noenv2.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_noaud_env.java
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_noaud_noenv.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/ClaimValueInjectionTest.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/JsonValueInjectionTest.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/ProviderInjectionTest.java
Labels: CLA Signed, noproductcode

#9470 Revert "Update OpenSAML to version 2.6.6"
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
  dev/com.ibm.ws.org.opensaml.opensaml/bnd.bnd
  dev/com.ibm.ws.org.opensaml.opensaml/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml/build.gradle
Labels: CLA Signed

#9460 increase message range for social login
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
Labels: CLA Signed, ID reviewed

#9388 3925 Propagate utility workarea to location service
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/location/internal/WsLocationAdminImpl.java
Labels: CLA Signed

#9454 Infinispan JARs from previous test can interfere with subsequent Infinispan buckets
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9466 Fix for Issue #9465: Change mockserver to use -keysize of 2048
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#9452 Fix Intermittent NullPointerException on TCP trace during shutdown
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/SocketRWChannelSelector.java
Labels: CLA Signed, in:Transport, team:Sirius

#5526 Fixes #4387 ignore wlp user dir for runnable
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/cmdline/Utils.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractRun.java
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed

#9439 Update CXF API
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/src/org/apache/cxf/resource/ExtendedURIResolver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/src/org/apache/cxf/transport/TransportURIResolver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/src/org/apache/cxf/wsdl/EndpointReferenceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6.2/src/org/apache/cxf/ws/policy/PolicyAnnotationListener.java
Labels: CLA Signed

#9348 Update org.eclipse.equinox.metatype version to 1.5.200.v20191008-0645
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.eclipse.equinox.metatype/bnd.bnd
Labels: CLA Signed

#9350 For Oracle DB, increases storage size for medium column row with Mult…
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
Labels: CLA Signed

#9299 Re-apply performance improvement for local builds
  dev/build.image/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Continuous Delivery

#9430 Infinispan NullPointerException due to overlap of remove and iterator
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: CLA Signed, team:Zombie Apocalypse

#9475 Fix for Issue #9474: Synchronized ArrayList in BasicSseResource to prevent loss of test data
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BasicSseApp/src/jaxrs21sse/basic/BasicSseResource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#9415 Change baseAuthz for security service from OPTIONAL to MANDATORY
  dev/com.ibm.ws.security.authorization.builtin/src/com/ibm/ws/security/authorization/builtin/BaseAuthorizationTableService.java
Labels: CLA Signed, bug, team:Core Security

#9477 partition info restored when missing
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/test-applications/failover1servApp/src/failover1serv/web/Failover1ServerTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#9481 Clean up and fix System property
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/CertificateEnvHelper.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
Labels: CLA Signed

#9459 Issue 9458: Add a silent delete on InMemoryLdapServer for FAT tests
  dev/com.ibm.ws.com.unboundid/src/com/ibm/ws/com/unboundid/InMemoryLDAPServer.java
Labels: CLA Signed, team:Wendigo East

#9476 Enable Opentracing trace logs for further analysis
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/OpentracingRestClientTCKServer/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/OpentracingTCKServer/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/OpentracingTCKServerMicroProfile/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/opentracingFATServer1/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/opentracingFATServer2/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/opentracingFATServer3/server.xml
  dev/com.ibm.ws.opentracing.1.3_fat/publish/servers/opentracingFATServer4/server.xml
Labels: CLA Signed, noproductcode

#9408 Updates for new components
  dev/com.ibm.ws.featureverifier/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxws.2.3.clientcontainer/bnd.bnd
  dev/com.ibm.ws.logstash.collector.1.0/.settings/bndtools.core.prefs
  dev/com.ibm.ws.logstash.collector/.settings/bndtools.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#9431 Move JSF third party API tests to jsf.2.2_fat bucket
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22ThirdPartyAPIServer/.gitignore
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22ThirdPartyAPIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22ThirdPartyAPIServer/server.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ThirdPartyApi.war/resources/JSF22ThirdPartyAPI.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ThirdPartyApi.war/resources/JSF22ThirdPartyAPIFailure.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ThirdPartyApi.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ThirdPartyApi.war/src/com/ibm/ws/jsf22/fat/thirdpartyapi/ThirdPartyBean.java
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius, test debt

#9469 Update keystores to be valid till 2069 and compatible for java 8 and above
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support.version20.test.actuator.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version20.test.actuator.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version20.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version21.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support_fat/publish/servers/com.ibm.ws.springboot.support.fat.SpringBootTests/client-keystore.jks
  dev/com.ibm.ws.springboot.support_fat/publish/servers/com.ibm.ws.springboot.support.fat.SpringBootTests/client-truststore.jks
  dev/com.ibm.ws.springboot.support_fat/publish/servers/com.ibm.ws.springboot.support.fat.SpringBootTests/resources/security/override-keystore.jks
  dev/com.ibm.ws.springboot.support_fat/publish/servers/com.ibm.ws.springboot.support.fat.SpringBootTests/resources/security/override-truststore.jks
Labels: CLA Signed

#9490 Update jaxws.2.3.clientcontainer to build in eclipse.
  dev/com.ibm.ws.jaxws.2.3.clientcontainer/bnd.bnd
Labels: CLA Signed, team:Performance

#9381 Catch illegal state exception on RESTHandler exception when calling g…
  dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/internal/service/RESTHandlerContainerImpl.java
Labels: CLA Signed

#9447 Delivery of EJB jndiName xmi element tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/JNDINameTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameEJB.jar/src/com/ibm/ejb2x/jndiName/ejb/JNDIName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameEJB.jar/src/com/ibm/ejb2x/jndiName/ejb/JNDINameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameEJB.jar/src/com/ibm/ejb2x/jndiName/ejb/JNDINameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameWeb.war/src/com/ibm/ejb2x/jndiName/web/JNDINameTestServlet.java
Labels: CLA Signed, noproductcode

#9263 Replace file.renameTo() method to Files.move() for platform compatibilty
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NonZipExtensionFilesInBootInfLibTests20.java
Labels: CLA Signed, noproductcode

#9491 enable and add new tests for heartbeats
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/test-applications/failover1servApp/src/failover1serv/web/Failover1ServerTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9467 Issue #9436: Fix LdapHelper.replaceRDC(...) so that it only considers…
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapHelper.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/LdapHelperTest.java
Labels: CLA Signed, team:Wendigo East

#9160 Issue 9108: Add no- ship acme feature skeleton project
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.acme-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acme-1.0/com.ibm.websphere.appserver.acme-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acme-1.0/resources/l10n/com.ibm.websphere.appserver.acme-1.0.properties
  dev/com.ibm.ws.security.acme/.classpath
  dev/com.ibm.ws.security.acme/.project
  dev/com.ibm.ws.security.acme/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/build.gradle
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-bnd.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-ext.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeService.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderServiceImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationProcessor.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/TraceConstants.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/package-info.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorization.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorizationServices.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeFilterImpl.java
Labels: CLA Signed, ID review not needed, L2 Reviewed, team:Core Security, team:Wendigo East

#9493 [9492] Synchronize access to beanManagers map
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9370 Support for OPENJ9_JAVA_OPTIONS
  dev/cnf/resources/bin/tool
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartJavaEnvironmentVariablesTest.java
Labels: CLA Signed

#9478 Adding metatype documentation to protocolVersion
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, in:Transport, team:Sirius

#9402 Adding trace for serviceability
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/PasswordNullifier.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
Labels: CLA Signed

#9509 add http session cache name if absent from infinispan config
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/infinispan/infinispan-config-lacking-http-session-cache-name.xml
Labels: CLA Signed, team:Zombie Apocalypse

#8818 zWLM Classification for EJB Timers
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/TimerNpImpl.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/TimerNpRunnable.java
  dev/com.ibm.ws.ejbcontainer.timer/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ejbcontainer.timer/src/com/ibm/ws/ejbcontainer/timer/osgi/internal/EJBTimerRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer.timer/src/com/ibm/ws/ejbcontainer/timer/osgi/internal/TimerNpSERunnable.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#9533 Revert "Issue 9108: Add no- ship acme feature skeleton project"
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.acme-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acme-1.0/com.ibm.websphere.appserver.acme-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acme-1.0/resources/l10n/com.ibm.websphere.appserver.acme-1.0.properties
  dev/com.ibm.ws.security.acme/.classpath
  dev/com.ibm.ws.security.acme/.project
  dev/com.ibm.ws.security.acme/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.acme/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/build.gradle
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-bnd.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/ibm-web-ext.xmi
  dev/com.ibm.ws.security.acme/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/config/AcmeService.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderServiceImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/ApplicationProcessor.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/TraceConstants.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/package-info.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorization.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeAuthorizationServices.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/web/AcmeFilterImpl.java
Labels: CLA Signed

#9518 Use userProps instead of generated.properties
  dev/com.ibm.ws.cdi.third.party_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat/build.gradle
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#9519 don't add cert to read only keystore
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#9542 Revert "Adding trace for serviceability"
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/PasswordNullifier.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
Labels: CLA Signed

#9521 Allow default context root for servlet caching
  dev/com.ibm.ws.dynacache.web/src/com/ibm/ws/cache/servlet/ServletCacheEngine.java
Labels: CLA Signed

#9515 19.0.0.11 Emergency Translation Returns
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_cs.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_de.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_es.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_fr.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_hu.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_it.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ja.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ko.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_pl.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_pt_BR.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ro.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_ru.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_zh.nlsprops
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl_zh_TW.nlsprops
Labels: CLA Signed
