Repository OpenLiberty/open-liberty, pull requests merged in 2019-09, with the labels that each got.

#8817 Update jsonFields in metatype.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#8810 Clean up Kafka test containers properly
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/KafkaSaslPlainContainer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/KafkaTlsContainer.java
Labels: CLA Signed, noproductcode

#8819 Upgrade commons compress to 1.19
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.cloudant_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/build.gradle
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.kernel.boot.archive/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/build.gradle
  dev/com.ibm.ws.logging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.org.apache.commons.compress/bnd.bnd
Labels: CLA Signed

#8803 Throw exception with only specific invalid features instead of all features
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#8739 Issue 8736: Removed the line of code that nulls out the SQL, when the…
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcPreparedStatement.java
Labels: CLA Signed

#8821 NLS returns from 19009 TVT Pass 2
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/nls/it/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/nls/cs/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/nls/it/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/nls/pl/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/nls/cs/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/nls/it/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/nls/pl/messages.js
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#8825 Add trace for debug
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.callback/bootstrap.properties
Labels: CLA Signed, noproductcode

#8762 Make GraphQL TCK port and server name dynamic
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West, test bug

#8710 create the org.apache.cxf.cxf.rt.transports.http.2.6 bundle to move t…
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.gitignore
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/CXFAuthenticator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/Headers.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/Messages.properties
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/TrustDecisionUtil.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/osgi/HTTPTransportActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/http/policy/impl/ClientPolicyCalculator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/https/CertificateHostnameVerifier.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/servlet/BaseUrlHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/servlet/servicelist/FormattedServiceListWriter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transport/servlet/servicelist/ServiceListGeneratorServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/ConnectionType.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/HTTPClientPolicy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/HTTPServerPolicy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/ObjectFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/ProxyServerType.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/src/org/apache/cxf/transports/http/configuration/package-info.java
Labels: CLA Signed, ID review not needed, in:Web Services, team:Bobcats

#8805 Ignore fields based on `@Ignore` and/or `@JsonbTransient` annotations
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.ws.microprofile.graphql.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/component/GraphQLExtension.java
  dev/com.ibm.ws.microprofile.graphql.1.0/src/com/ibm/ws/microprofile/graphql/internal/MPDefaultInclusionStrategy.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/IgnoreTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ignoreApp/src/mpGraphQL10/ignore/Widget.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#8140 Reorder command-line building in server.bat debug
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#8834 create nonship mpContextPropagation-1.1 feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-1.0/com.ibm.websphere.appserver.concurrent-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.1/com.ibm.websphere.appserver.jaxrsClient-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.1/com.ibm.websphere.appserver.mpContextPropagation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.1/resources/l10n/com.ibm.websphere.appserver.mpContextPropagation-1.1.properties
Labels: CLA Signed, team:Zombie Apocalypse

#8841 Issue 8840: Adjust property for DN on getGroups search
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_TDSLDAPTest.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SearchBridge.java
Labels: release bug, team:Wendigo East

#8829 Update TransactionContext processing
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContext.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/TransactionContextExtension.java
Labels: CLA Signed, team:Performance

#8847 remove dead catch block
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
Labels: CLA Signed

#8846 Issue #8842: Upgrade Apache Commons Daemon to 1.2.0
  dev/com.ibm.ws.org.apache.commons.daemon/lib/commons-daemon-1.0.15-bin-windows-signed.jar
  dev/com.ibm.ws.org.apache.commons.daemon/lib/commons-daemon-1.2.0-bin-windows-signed.jar
  dev/com.ibm.ws.org.apache.commons.daemon/publish/bin/tools/win/prunsrv.exe
Labels: CLA Signed, release bug

#8768 Fix to handle whitespace in tokens
  dev/settings.gradle
  dev/wlp-gradle/bndSettings.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#8849 copy main Hazelcast sessions bucket and first test using Infinispan
  dev/com.ibm.ws.session.cache_fat_infinispan/.classpath
  dev/com.ibm.ws.session.cache_fat_infinispan/.project
  dev/com.ibm.ws.session.cache_fat_infinispan/.settings/bndtools.core.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.session.cache_fat_infinispan/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheApp.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server.mphealth/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server.mphealth/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/derby.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/AppObject.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean1.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionScopedBean2.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener1/SessionListener.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/listener2/SessionListener.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8809 Create jaxws.2.3.cdi bundle and jaxwscdi-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxwscdi-2.3.feature
  dev/com.ibm.ws.jaxws.2.3.cdi/.classpath
  dev/com.ibm.ws.jaxws.2.3.cdi/.gitignore
  dev/com.ibm.ws.jaxws.2.3.cdi/.project
  dev/com.ibm.ws.jaxws.2.3.cdi/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxws.2.3.cdi/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxws.2.3.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxws.2.3.cdi/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxws.2.3.cdi/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.cdi/findbugs.exclude.xml
  dev/com.ibm.ws.jaxws.2.3.cdi/src/com/ibm/ws/jaxrws/cdi/JAXWSCDIConstants.java
  dev/com.ibm.ws.jaxws.2.3.cdi/src/com/ibm/ws/jaxws/cdi/component/JAXWSCDIServiceImplByJndi.java
  dev/com.ibm.ws.jaxws.2.3.cdi/src/com/ibm/ws/jaxws/cdi/component/JaxWsImplBeanCDICustomizer.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#8823 Update jsonFields to jsonFieldMappings and LoggingMessages.nlsprops
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonConfigFieldExt.xml
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/resources/com/ibm/ws/logging/internal/resources/LoggingMessages.nlsprops
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConstants.java
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.fieldnamebootstrap/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.fieldnamebootstrap/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.fieldnameenv/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.fieldnamexml/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.fieldnamexml/server.env
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Logging.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#8612 export jsf-2.3 impl classes as third-party
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPI.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPIFailure.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/src/com/ibm/ws/jsf23/fat/thirdpartyapi/ThirdPartyBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#8614 export jsf-2.2 impl classes as third-party
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#8869 remaining tests in SessionCacheTimeoutTest
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8867 modify imports/exports of the new cxf 2.6 bundles so that a server st…
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.core.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/com/ibm/ws/cxf/rt/frontend/jaxws/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/com/ibm/ws/cxf/rt/frontend/jaxws/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6/src/com/ibm/ws/cxf/rt/frontend/simple/NoOpActivator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6/src/com/ibm/ws/cxf/rt/frontend/simple/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.2.6/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6/bnd.bnd
Labels: CLA Signed, in:Web Services, team:Bobcats

#8870 Add missing bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/spnego-1.0/com.ibm.websphere.appserver.spnego-1.0.feature
Labels: CLA Signed

#8838 Change mvn install plugin and install utility to use new resolve as se…
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#8880 Revert "export jsf-2.3 impl classes as third-party"
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPI.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPIFailure.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/src/com/ibm/ws/jsf23/fat/thirdpartyapi/ThirdPartyBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
Labels: CLA Signed

#8882 Revert "export jsf-2.2 impl classes as third-party"
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
Labels: CLA Signed

#8707 OIDC: Remove possible space from ID of buttons on clientManagement table.
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/js/table.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/js/table.js
Labels: CLA Signed, team:Admin Center

#8889 Revert "Fix to handle whitespace in tokens"
  dev/settings.gradle
  dev/wlp-gradle/bndSettings.gradle
Labels: CLA Signed, noproductcode

#8851 synchronize checkPeerServers
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LibertyRecoveryDirectorImpl.java
Labels: CLA Signed

#8853 cancel HADBLogAvailabilityManager alarm on server stop
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
Labels: CLA Signed

#8875 copy from hazelcast session config bucket to create one for Infinispan
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.classpath
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.project
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.settings/bndtools.core.prefs
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.session.cache_fat_config_infinispan/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.session.cache_fat_config_infinispan/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/server.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/jcacheApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/jcacheApp/src/test/cache/infinispan/web/JCacheConfigTestServlet.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/sessionCacheConfigApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/sessionCacheConfigApp/src/session/cache/infinispan/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8896 Avoid JVM delays caused by random number gen
  dev/wlp-gradle/java.gradle
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#8878 Upgrade to yasson-1.0.5
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.clientcontainer.json_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/BasicSseTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/BroadcasterTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/DelaySseTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/SseClientBehaviorTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/SseJaxbTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/SseJsonbTest.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseJsonbApp/src/jaxrs21sse/jsonb/JsonbObject.java
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.bnd
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.overrides
  dev/com.ibm.ws.org.eclipse.yasson.1.0/resources/yasson-messages.properties
Labels: CLA Signed, team:Zombie Apocalypse

#8804 7491 Add workarea for embedded servers launched by liberty utils
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/asset/ServerAsset.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/EmbeddedServerImpl.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/FileUtils.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommand.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/BootstrapConfigTest.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/SharedBootstrapConfig.java
Labels: CLA Signed, in:Kernel/Bootstrap, team:OSGi Infrastructure

#8723 H2: GoAway and close connections on write IOExceptions
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2MuxTCPWriteCallback.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2WriteQEntry.java
Labels: CLA Signed, in:Transport, team:Sirius

#8900 test case for updating configuration of infinispan library
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8906 Update settings to match between eclipse and bnd
  dev/com.ibm.ws.jaxws.2.3.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.metrics.1.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance.metrics.2.0/.settings/bndtools.core.prefs
Labels: CLA Signed, team:Performance

#8848 Initial checkin of Jaeger adapter
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/jaeger-1.0/com.ibm.websphere.appserver.jaeger-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaeger-1.0/resources/l10n/com.ibm.websphere.appserver.jaeger-1.0.properties
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/.project
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/AbstractJaegerAdapter.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/CodecConfigurationImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/ConfigurationImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/ReporterConfigurationImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/SamplerConfigurationImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/SenderConfigurationImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/impl/package-info.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/.project
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/AppLibraryClassLoader.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/Configuration.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/JaegerAdapter.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/JaegerAdapterException.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/JaegerAdapterFactory.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/src/com/ibm/ws/microprofile/opentracing/jaeger/adapter/package-info.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger/.project
  dev/com.ibm.ws.microprofile.opentracing.jaeger/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger/resources/com.ibm.ws.microprofile.opentracing.jaeger.resources/JaegerMessages.nlsprops
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/AdapterFactoryImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/JaegerTracerFactory.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/package-info.java
Labels: CLA Signed, ID reviewed

#8680 Print elapsed time message on completion of SlowRequest in com.ibm.ws.request.timing
  dev/com.ibm.ws.request.probes/src/com/ibm/wsspi/requestContext/RequestContext.java
  dev/com.ibm.ws.request.timing/resources/com/ibm/ws/request/timing/internal/resources/LoggingMessages.nlsprops
  dev/com.ibm.ws.request.timing/src/com/ibm/ws/request/timing/manager/SlowRequestManager.java
  dev/com.ibm.ws.request.timing/src/com/ibm/ws/request/timing/probeExtensionImpl/SlowRequestProbeExtension.java
Labels: CLA Needed, ID reviewed, L2 Reviewed

#8837 Change cache names from . to %2F
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed

#8909 Issue #8908: Port couchdb FAT to OpenLiberty using testcontainers
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.couchdb_fat/.classpath
  dev/com.ibm.ws.couchdb_fat/.project
  dev/com.ibm.ws.couchdb_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.couchdb_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.couchdb_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.couchdb_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.couchdb_fat/fat/src/com/ibm/ws/couchdb/fat/FATSuite.java
  dev/com.ibm.ws.couchdb_fat/fat/src/com/ibm/ws/couchdb/fat/tests/CouchDBContainer.java
  dev/com.ibm.ws.couchdb_fat/fat/src/com/ibm/ws/couchdb/fat/tests/TestCouchDbWar.java
  dev/com.ibm.ws.couchdb_fat/publish/files/couchdb-config/testcontainers_config.ini
  dev/com.ibm.ws.couchdb_fat/publish/files/ssl-certs/couchdb.pem
  dev/com.ibm.ws.couchdb_fat/publish/files/ssl-certs/privkey.pem
  dev/com.ibm.ws.couchdb_fat/publish/files/ssl-certs/server.req
  dev/com.ibm.ws.couchdb_fat/publish/servers/com.ibm.ws.couchdb.fat.server/bootstrap.properties
  dev/com.ibm.ws.couchdb_fat/publish/servers/com.ibm.ws.couchdb.fat.server/server.xml
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/resources/META-INF/permissions.xml
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/AbstractCouchDbServlet.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/CouchDocument.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/InjectedCouchDbServlet.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/InjectedURLCouchDbServlet.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/JNDIDirectLookupServlet.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/JNDIResourceEnvRefServlet.java
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/src/com/ibm/ws/couchdb/fat/web/StateDocument.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/CouchDBElement.java
Labels: CLA Signed, noproductcode, team:Blizzard

#8907 test where application closes Infinspan Caching Provider
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/jcacheApp/src/test/cache/infinispan/web/JCacheConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8925 Eclipse updates to get things building again
  dev/com.ibm.ws.jsf.2.2_fat/.classpath
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.opentracing.jaeger/.settings/bndtools.core.prefs
Labels: team:Performance

#8874 Issue 8873: Add XOR and Hash tests for Database Store
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/custom/OauthClientStoreCommon.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProviderHashTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProviderTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProviderXORTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/db/InitialContextFactoryMock.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#8921 Fix for Issue #8037: Use MP CompletionStageFactory to enable JAX-RS to run on the Liberty Thread Pool
  dev/com.ibm.ws.concurrent.mp.1.0/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/CompletionStageFactory.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/test-applications/jaxrsapp/src/web/jaxrstest/JAXRSExecutorTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/com/ibm/ws/jaxrs21/clientconfig/JAXRSClientCompletionStageFactoryConfig.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/CompletionStageRxInvokerImpl.java
Labels: in:JAX-RS, team:Wendigo West

#8931 Add a more specific message when Jaeger libraries are not found
  dev/com.ibm.ws.microprofile.opentracing.jaeger/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger/resources/com.ibm.ws.microprofile.opentracing.jaeger.resources/JaegerMessages.nlsprops
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/AdapterFactoryImpl.java
  dev/com.ibm.ws.microprofile.opentracing.jaeger/src/com/ibm/ws/microprofile/opentracing/jaeger/JaegerTracerFactory.java
Labels: ID reviewed

#8940 Updates to use non local infinispan cache via infinispan.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/shared/resources/infinispan/infinispan.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8932 fix NPE in URLMap class when some specific annotations are used.
  dev/com.ibm.ws.security.authorization.jacc.web/src/com/ibm/ws/security/authorization/jacc/web/impl/URLMap.java
Labels: in:Security, release bug, team:Core Security

#8947 Added infinispan config to fix the SessionCacheTwoServerTimeoutTest tests.
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/jvm.options
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8833 Porting sql server fat to Open Liberty
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_sqlserver/.classpath
  dev/com.ibm.ws.jdbc_fat_sqlserver/.project
  dev/com.ibm.ws.jdbc_fat_sqlserver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat_sqlserver/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_sqlserver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_sqlserver/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_sqlserver/build.gradle
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8944 Re-commit of changing '.' to '%2F' with infinispan session test inclu…
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/cdi/SessionCDITestServlet.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config/test-applications/sessionCacheConfigApp/src/session/cache/web/SessionCacheConfigTestServlet.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/sessionCacheConfigApp/src/session/cache/infinispan/web/SessionCacheConfigTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
Labels: CLA Signed

#8924 Update of JAXWS CXF bundles to use CXF 3.3.3
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.validator.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.validator.3.2/bnd.overrides
Labels: in:Web Services, team:Bobcats

#8830 clarify use of responseType attribute
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, L2 ReviewNotRequired

#8918 changed to one browserservermsg
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.java
Labels: CLA Signed

#8935 Make the FT/Metrics 2.0 feature ready for release
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFT-Metrics-2.0-guard/com.ibm.websphere.appserver.mpFT-Metrics-2.0-guard.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFT-Metrics-2.0-guard/resources/l10n/com.ibm.websphere.appserver.mpFT-Metrics-2.0-guard.properties
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/servers/FaultTolerance11TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/servers/FaultTolerance20TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetrics/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetricsRemoval/server.xml
Labels: CLA Signed

#8961 test bug: wait for ltpa key creation
  dev/com.ibm.ws.microprofile.mpjwt.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt11/tck/Mpjwt11TCKLauncher_aud_env.java
Labels: CLA Signed, noproductcode

#8996 Add a couple tests to OAuth BrowserAndServerLogMessageTest
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/error/impl/BrowserAndServerLogMessageTest.java
Labels: CLA Signed, noproductcode, team:Security SSO

#8598 Issue #8597: Allow configuration of federated CUR to replicate stand-…
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/UserRegistry.java
  dev/com.ibm.ws.security.registry_test.custom/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.registry_test.custom/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.registry_test.custom/src/com/ibm/ws/security/registry/custom/sample/FileRegistrySample.java
  dev/com.ibm.ws.security.registry_test.servlet/test-applications/userRegistry/src/web/UserRegistryServlet.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_RealmPropertyMappingTest.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/RepositoryManager.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/utils/URBridgeEntity.java
  dev/com.ibm.ws.security.wim.registry_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.registry_fat/build.gradle
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/DefaultWIMRealmMultipleReposTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/DefaultWIMRealmTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/FederateStandaloneCurTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/MultiValuedOutputPropMappingTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/WIMURRegressionTest.java
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.FederateStandaloneCur/bootstrap.properties
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.FederateStandaloneCur/server.xml
Labels: CLA Signed, team:Wendigo East

#8928 Issue 8894 - Initial mpHealth-2.1 feature implementation
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.1_zh_TW.properties
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.gitignore
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.1/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.project
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/fat/src/com/ibm/ws/microprofile/health21/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/fat/src/com/ibm/ws/microprofile/health21/tck/Health21TCKLauncher.java
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/servers/Health21TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/servers/Health21TCKServer/jvm.options
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/servers/Health21TCKServer/server.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/.gitignore
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health21/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health21/test/URIProviderProducer.java
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: ID review not needed

#8939 Update concurrent mp features to use parallel activation
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.concurrencyPolicy-1.0.feature
Labels: CLA Signed, performance, team:Performance

#8920 add HTTP call to the testLibertyWebConfigProvider method
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
Labels: in:Web Components, team:Sirius

#8281 Porting persistant_times test bucket to open liberty
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.concurrent.persistent_fat_timers/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_timers/.project
  dev/com.ibm.ws.concurrent.persistent_fat_timers/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_timers/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_timers/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/PersistentExecutorTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_timers/publish/servers/com.ibm.ws.concurrent.persistent.fat.timers/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_timers/publish/servers/com.ibm.ws.concurrent.persistent.fat.timers/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/AutoTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/MyTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/MyTimerInfo.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/MyTimerTracker.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/web/PersistentTimersTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8943 7491 Revert the workaround for issue 7448
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/BundleProcessor.java
Labels: CLA Signed, team:OSGi Infrastructure

#8120 Porting persistant_loadtest test bucket to open liberty
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.project
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/files/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/files/test.file
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/servers/com.ibm.ws.concurrent.persistent.fat.loadtest/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/servers/com.ibm.ws.concurrent.persistent.fat.loadtest/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/LoadTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/TaskResultStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/CancelTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/MultiRunSeparateTriggerFailSometimesResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/MultiRunTriggerResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/SingleRunResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/SingleRunTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9002 update expired certs.
  dev/build.sharedResources/usrShared/resources/security/key.jks
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClientSecurity/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.clientcert.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.anno.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authalias.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.authdata.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.bean.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.hash.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.nouser.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.db.shortname.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.deferred.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.dbidstore.immediate.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ejb.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/resources/security/key.jks
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.jaxrs.fat/resources/security/key.jks
Labels: CLA Signed, noproductcode, test bug

#8946 switch config bucket to Infinispan 10.0.0.CR1
  dev/com.ibm.ws.session.cache_fat_config_infinispan/build.gradle
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/jvm.options
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/server.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/shared/resources/infinispan10/infinispan.xml
  dev/com.ibm.ws.session.cache_fat_config_infinispan/test-applications/sessionCacheConfigApp/src/session/cache/infinispan/web/SessionCacheConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8674 Remove unneeded bundles / features from CDI and JAXRS features
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.cxf.common-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxws-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
Labels: CLA Signed, team:Performance

#9000 Fix for when jks and p12 defaults exists
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSExistsSSLTest.java
Labels: CLA Signed

#8956 Parse HTTP Link headers for multiple links
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/ResponseImpl.java
  dev/com.ibm.ws.jaxrs.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/link/LinkHeaderTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.linkheader/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.linkheader/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/linkheader/src/com/ibm/ws/jaxrs/fat/linkheader/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/linkheader/src/com/ibm/ws/jaxrs/fat/linkheader/TestApplication.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/linkheader/src/com/ibm/ws/jaxrs/fat/linkheader/TestResource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ResponseImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#8948 disable FFDC instrumentation for the cxf 2.6 bundles now that we have…
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.core.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/frontend/WSDLGetInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/frontend/WSDLGetUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/DispatchImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/EndpointImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/EndpointReferenceBuilder.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/JAXWSMethodInvoker.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/ServiceImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/context/WebServiceContextImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/handler/HandlerChainInvoker.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/handler/logical/LogicalHandlerOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/handler/logical/LogicalMessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/handler/soap/SOAPMessageContextImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/interceptors/MessageModeOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/interceptors/SwAOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/interceptors/WebFaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/spi/ProviderImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/support/JaxWsEndpointImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6/src/org/apache/cxf/jaxws/support/JaxWsServiceConfiguration.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.2.6/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6/bnd.bnd
Labels: CLA Signed, in:Web Services, team:Bobcats

#8828 Update metatype.xml file to include json.fields property for logging.osgi
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#9030 Add check for null ssl ref
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLChannelProvider.java
Labels: CLA Signed

#8884 Update product and bundle version for release 19.0.0.10
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#8728 Flow control improvements
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResult.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/H2StreamResultManager.java
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2RateState.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, team:Sirius

#9026 purge stale jwks
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKSetTest.java
Labels: CLA Signed

#9072 Revert "Fix for when jks and p12 defaults exists"
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/CommonSSLTest.java
  dev/com.ibm.ws.ssl_fat_pkcs12/fat/src/com/ibm/ws/ssl/fat/pkcs12/DefaultJKSExistsSSLTest.java
Labels: CLA Signed

#8859 Update Weld jars
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.jboss.weld3/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
Labels: CLA Signed, team:MicroProfileUK

#8184 Porting persistant_multiple test bucket to open liberty
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/.project
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerFactory.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerType.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DatabaseContainerUtil.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/DerbyNoopContainer.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/publish/servers/com.ibm.ws.concurrent.persistent.fat.multiple/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/publish/servers/com.ibm.ws.concurrent.persistent.fat.multiple/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/src/web/DBUpdateTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/src/web/MultiplePersistentExecutorsTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/src/web/RepeatingTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/test-applications/persistmultitest/src/web/RepeatingTrigger.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9070 Enable endpt discovery of app pw and tokens ui management endpoints
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OIDCConstants.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcDiscoveryProviderConfig.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/DiscoveryTest.java
Labels: CLA Signed

#9062 Re-delivery of fix to handle whitespace in tokens
  dev/settings.gradle
  dev/wlp-gradle/bndSettings.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#9063 Update to Gradle 5.6.2
  dev/.gradle-wrapper/gradle-wrapper.jar
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/gradlew
  dev/gradlew.bat
  dev/wlp-gradle/biz.aQute.bnd.gradle
  dev/wlp-gradle/bndSettings.gradle
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#9059 Issue 9058: Port EJB Persistent Timer FAT
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.couchdb_fat/test-applications/couchdb/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/publish/servers/com.ibm.ws.ejbcontainer.timer.persistent.fat.PersistentTimerServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/publish/servers/com.ibm.ws.ejbcontainer.timer.persistent.fat.PersistentTimerServer/server.xml
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/InitTxRecoveryLogEJB.jar/src/com/ibm/ws/ejbcontainer/init/recovery/ejb/InitTxRecoveryLogBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreApp.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/resources/META-INF/ibm-ejb-jar-ext.xmi
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/LateWarningBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/LateWarningHome.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/LateWarningObject.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatefulBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatefulHome.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatefulObject.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessHome.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessObject.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessTimedBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessTimedHome.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessTimedObject.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreWeb.war/src/com/ibm/ws/ejbcontainer/timer/persistent/core/web/TimerAccessOperationsServlet.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreWeb.war/src/com/ibm/ws/ejbcontainer/timer/persistent/core/web/TimerLateWarningServlet.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreWeb.war/src/com/ibm/ws/ejbcontainer/timer/persistent/core/web/TimerSFOperationsServlet.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreWeb.war/src/com/ibm/ws/ejbcontainer/timer/persistent/core/web/TimerSLOperationsServlet.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard

#9045 Revert "Revert "export jsf-2.x impl classes as third-party""
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.2/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.classpath
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.project
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ThirdPartyAPIServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPI.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/JSF23ThirdPartyAPIFailure.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/JSF23ThirdPartyApi.war/src/com/ibm/ws/jsf23/fat/thirdpartyapi/ThirdPartyBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#8342 Performance updates
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ShadowClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/LibertyClassLoaderTest.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/java2sec/PermissionManagerTest.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/VariableEvaluator.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/permissions/PermissionsAdapter.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/SubsystemFeatureDefinitionImpl.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/PathUtils.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/Tr.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/TrConfigurator.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/TraceComponent.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/BurstDateFormat.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/DateFormatHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ProviderFactory.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracingMethodAdapter.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/srt/SRTInputStream31.java
Labels: CLA Signed, team:Performance

#8677 Use extra single quote for nls
  dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#9048 switch bucket to run on Infinispan 10
  dev/com.ibm.ws.session.cache_fat_infinispan/build.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#8704 GA jaasLoginContextEntryRef for JCA
  dev/com.ibm.ws.jca/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#9081 Issue #9080: Fix CouchDB fat file permission
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/FATSuite.java
  dev/com.ibm.ws.couchdb_fat/fat/src/com/ibm/ws/couchdb/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Blizzard

#9076 Added new field TARGET METHOD to SECURITY_SAF_AUTHZ event
  dev/com.ibm.ws.request.probe.audit.servlet/src/com/ibm/ws/request/probe/audit/servlet/AuditPE.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/event/SAFAuthorizationEvent.java
Labels: CLA Signed

#8954 add finally block to close connection in DefaultFaceletFactory
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/view/facelets/impl/DefaultFaceletFactory.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#9036 Issue #8951: Fix OperationNotSupportedException encountered when call…
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/RacfSdbmLdapTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.racf.sdbm/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.racf.sdbm/server.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPFatUtils.java
Labels: CLA Signed, team:Wendigo East

#8467 Enable parallel activation for jsp-2.3 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/el-3.0/com.ibm.websphere.appserver.el-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.3/com.ibm.websphere.appserver.jsp-2.3.feature
Labels: CLA Signed

#9083 Update eclipse settings for jdbc_fat_sqlserver
  dev/com.ibm.ws.jdbc_fat_sqlserver/.project
  dev/com.ibm.ws.jdbc_fat_sqlserver/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#9042 Add @NonNull support
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/generator/mapping/common/NonNullMapper.java
  dev/com.ibm.ws.io.leangen.graphql.spqr.0.9.9/src/io/leangen/graphql/metadata/TypedElement.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#9043 Fix incorrect security manager check
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/helpers/FileUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9054 Include classpath URLs in ClassLoadingService dump introspector
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#9022 Test case for users providing a JSON-B ContextResolver in MP Rest Client
  dev/com.ibm.ws.microprofile.rest.client_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.jsonbContext/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.jsonbContext/resources/security/key.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.jsonbContext/resources/security/trust.jks
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.jsonbContext/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/BasicServiceClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/JsonbContextResolver.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/JsonbContextTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/PrivateVisibilityStrategy.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/Widget.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#9074 Allow 1PC optimization to be disabled
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/OnePCDisabledTest.java
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.1PCDisabled/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.1PCDisabled/jvm.options
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.1PCDisabled/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/OnePCDisabledServlet.java
  dev/com.ibm.ws.transaction.core_fat/test-bundles/txfat/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#9089 Fix for Issue #8037: Use ForkJoinPool when running in a Java SE environment like the TCK
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/CompletionStageRxInvokerImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9088 avoid exporting internals of com.ibm.ws.concurrent.mp bundle
  dev/com.ibm.ws.concurrent.mp.1.0/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/ThreadContextImpl.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/ManagedExecutorFactory.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/ThreadContextConfig.java
  dev/com.ibm.ws.concurrent.mp.1.0/src/com/ibm/ws/concurrent/mp/spi/ThreadContextFactory.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ThreadContextBuilderImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ThreadContextConfigImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ThreadContextImpl.java
Labels: CLA Signed, team:Zombie Apocalypse, tech debt

#8300 Uncouple some execution/instance operations to prevent deadlocks
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/BaseStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/controller/impl/PartitionedStepControllerImpl.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobExecutionEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/IPersistenceManagerService.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/AbstractPersistenceManager.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
Labels: CLA Signed

#9097 Notices for 19.0.0.10
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#9071 Add jakartaee-8.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-8.0/com.ibm.websphere.appserver.jakartaee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-8.0/resources/l10n/com.ibm.websphere.appserver.jakartaee-8.0.properties
  dev/com.ibm.ws.javaee.8.0_fat/bnd.bnd
  dev/com.ibm.ws.javaee.8.0_fat/fat/src/com/ibm/ws/javaee/v80/fat/JavaEE8Test.java
Labels: CLA Signed, team:Zombie Apocalypse

#9091 Enable parallel activation for ssl-1.0 and websocket-1.1
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-1.1/com.ibm.websphere.appserver.websocket-1.1.feature
Labels: CLA Signed

#9044 Java 2 Security permissions
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_config_infinispan/publish/servers/com.ibm.ws.session.cache.fat.config.infinispan/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/bootstrap.properties
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/cdi/SessionCDITestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9107 Fix for Issue #8037: Use Liberty thread pool for SSE
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#9110 test bucket with multiple servers and automatic persistent timer
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/.project
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverA/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverA/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/ejb/autotimer/AutoCountingTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/test-applications/failoverTimersApp/src/failovertimers/web/FailoverTimersTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9034 erroneous CWWKL0058W warning
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#8540 Update yoko
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#9117 Changes for APAR PH15518 for issue #9069
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
Labels: CLA Signed

#9138 Revert "Fix for Issue #8037: Use Liberty thread pool for SSE"
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs21/sse/LibertySseEventSinkImpl.java
Labels: CLA Signed

#9090 Enable parallel activation for jpa-2.2 and jpaContainer-2.2
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.connectionManagement-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.servlet-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jcaSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-2.7.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.2/com.ibm.websphere.appserver.jdbc-4.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-2.2/com.ibm.websphere.appserver.jpa-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-2.2/com.ibm.websphere.appserver.jpaContainer-2.2.feature
Labels: CLA Signed

#7061 6999-CWPKI0023E-commit1
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509KeyManager.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, release bug
