Repository OpenLiberty/open-liberty, pull requests merged in 2020-11, with the labels that each got.

#14755 Make FT tests more reliable
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/FaultToleranceMainTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/AsyncServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/beans/AsyncClassBean.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/beans/FutureAsserts.java
Labels: CLA Signed, noproductcode

#14669 Use App BDAs with MP GraphQL (allows removal of overlay GraphQLConfig)
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLExtension.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/cdi/config/GraphQLConfig.java
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#14386 Another set of build from source
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
Labels: CLA Signed

#14776 Port changeDetector to OpenLiberty
  dev/build.changeDetector/.classpath
  dev/build.changeDetector/.project
  dev/build.changeDetector/.settings/bndtools.core.prefs
  dev/build.changeDetector/.settings/org.eclipse.core.resources.prefs
  dev/build.changeDetector/.settings/org.eclipse.jdt.core.prefs
  dev/build.changeDetector/.settings/org.eclipse.jdt.ui.prefs
  dev/build.changeDetector/bnd.bnd
  dev/build.changeDetector/build.gradle
  dev/build.changeDetector/src/com/ibm/ws/infra/depchain/ChangeDetector.java
  dev/build.changeDetector/src/com/ibm/ws/infra/depchain/Feature.java
  dev/build.changeDetector/src/com/ibm/ws/infra/depchain/FeatureCollection.java
  dev/build.changeDetector/src/com/ibm/ws/infra/depchain/MainArgs.java
  dev/build.changeDetector/test-resources/3581.diff
  dev/build.changeDetector/test-resources/4771.diff
  dev/build.changeDetector/test-resources/4889.diff
  dev/build.changeDetector/test-resources/4931.diff
  dev/build.changeDetector/test-resources/4947.diff
  dev/build.changeDetector/test-resources/4951.diff
  dev/build.changeDetector/test-resources/4956.diff
  dev/build.changeDetector/test-resources/fat-using-all-features.json
  dev/build.changeDetector/test-resources/fat-using-javaee.json
  dev/build.changeDetector/test-resources/fat-using-no-features.json
  dev/build.changeDetector/test-resources/fat-using-servlet.json
  dev/build.changeDetector/test-resources/old-feature-deps-snapshot-do-not-edit.json
  dev/build.changeDetector/test-resources/wlp-feature-snapshot.zip
  dev/build.changeDetector/test/com/ibm/ws/infra/depchain/ChangeDetectorTest.java
  dev/build.changeDetector/test/com/ibm/ws/infra/depchain/SingleBucketTest.java
  dev/build.example_fat/fat/src/com/ibm/ws/example/FATSuite.java
  dev/cnf/resources/bnd/test.bnd
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Zombie Apocalypse

#14788 Cancel previous workflow runs for PRs
  .github/workflows/cleanup-duplicate-runs.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#13795 SSO LTPA support authentication filter
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.webAppSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.authFilter1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.authFilter1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webBundleSecurity1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webBundleSecurity1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.adminSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.adminSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.authFilter-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.wsspi.appserver.webBundleSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.ws.messaging.security/src/com/ibm/ws/messaging/security/internal/MessagingSecurityServiceImpl.java
  dev/com.ibm.ws.security.sso/.classpath
  dev/com.ibm.ws.security.sso/.project
  dev/com.ibm.ws.security.sso/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.sso/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.sso/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.sso/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.sso/bnd.bnd
  dev/com.ibm.ws.security.sso/src/com/ibm/ws/security/sso/SSOAuthFilterImpl.java
  dev/com.ibm.ws.security.sso/src/com/ibm/ws/security/sso/TraceConstants.java
  dev/com.ibm.ws.security.sso/src/com/ibm/ws/security/sso/package-info.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAConfiguration.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManager.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/TraceConstants.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTask.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenService.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/package-info.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManagerTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2FactoryTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPATokenServiceTest.java
  dev/com.ibm.ws.webcontainer.security.admin/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security.app/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.feature/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorFactory.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAuthenticatorFactoryImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/util/SSOAuthFilter.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxyTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/AuthenticateApiTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/SSOAuthenticatorTest.java
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#14786 Enable FATs in GH Actions build
  .github/workflows/openliberty-ci.yml
  dev/build.example_fat/fat/src/com/ibm/ws/example/FATSuite.java
  dev/wlp.lib.extract_fat/bnd.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14764 Issue 13575: Add support for mp.jwt.decrypt.key.location in MP JWT 1.2
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jRsaJWK.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/PemKeyUtil.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKSetTest.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/MpConfigProperties.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JweHelper.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/config/MpConfigPropertiesTest.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.mp.jwt.1.1.config/src/com/ibm/ws/security/mp/jwt/v11/config/impl/MpConfigProxyServiceImpl.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/MicroProfileJwtTaiRequest.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudEnv/server.env
Labels: CLA Signed, team:Security SSO

#14778 Clean up some feature files
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoAppSecurityClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurityS4U2-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.webservicesee-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.interceptor-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.ltpa-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.reactivestreams.reactive-streams-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.security-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.securityInfrastructure-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurityClient-1.0/com.ibm.websphere.appserver.appSecurityClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaMail-1.6/com.ibm.websphere.appserver.jakartaMail-1.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaMail-1.6/resources/l10n/com.ibm.websphere.appserver.jakartaMail-1.6.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-3.0/io.openliberty.jaxb-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.0/io.openliberty.restfulWS-3.0.feature
Labels: CLA Signed, ID review not needed, team:Performance

#14791 11851 Enable jakarta jms features for appClient and ee9 beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-messaging3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.messaging-3.0.internal.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-9.0/io.openliberty.jakartaeeClient-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messaging-3.0/io.openliberty.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingClient-3.0/io.openliberty.messagingClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingSecurity-3.0/io.openliberty.messagingSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingServer-3.0/io.openliberty.messagingServer-3.0.feature
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/build.gradle
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/FATBase.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientIDTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS1AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSendTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/MessageListenerTest.java
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14783 Serverxml vars config source performance
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/ServerXMLDefaultVariableConfigSource.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/ServerXMLVariableConfigSource.java
Labels: CLA Signed

#14790 grpc_fat improvements
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientConfigTests.java
Labels: CLA Signed, noproductcode

#14775 H2 FVT: more orderly test servers shutdown
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2Config31H2On.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2Config40H2Off.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2SecureTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/MultiSessionTests.java
Labels: CLA Signed, noproductcode

#14714 Added Overlay changes for missing faces renames
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/shared/webapp/WebXmlParser.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14802 Issue #14800: Ignore CWWKC1501 in EJB Timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerTestHelper.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#14803 Improve GenerateCategories for handling FAT-only and no-FAT PRs
  .github/workflow-scripts/GenerateCategories.java
  .github/workflows/cleanup-duplicate-runs.yml
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14804 Manually zip/unzip liberty image for upload/download
  .github/workflow-scripts/run-fat-build.sh
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14782 Use createFailureScopeController
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
Labels: CLA Signed

#14794 CDI injection of WorkManager
  dev/com.ibm.ws.concurrent_fat_work/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_work/fat/src/test/concurrent/work/fat/ConcurrentWorkCDIFATTest.java
  dev/com.ibm.ws.concurrent_fat_work/fat/src/test/concurrent/work/fat/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_work/publish/servers/com.ibm.ws.concurrent.fat.work.cdi/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_work/publish/servers/com.ibm.ws.concurrent.fat.work.cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_work/test-applications/WorkTestCDIApp/src/test/concurrent/work/cdi/WorkTestCDIServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14245 EJB Custom Bindings Remove Beta Config Element
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server.err/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.serverxml.testserver/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.noInterface.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/bindings/configtests/web/BindToServerRootServlet.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ContainerProperties.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/publish/servers/com.ibm.ws.ejbcontainer.injection.fat.mdbserver/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.remote.noTrace/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.remote/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.sll/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server/server.xml
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
Labels: CLA Signed

#14595 Wsoc add eeCompatible
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-1.0/com.ibm.websphere.appserver.websocket-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-1.1/com.ibm.websphere.appserver.websocket-1.1.feature
Labels: CLA Signed, in:Transport, jakartaEE, team:Sirius

#14806 grpc_fat ServiceSupportTests improvement
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceSupportTests.java
Labels: CLA Signed, noproductcode

#14809 Fix comment lines in NLS properties files
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/resources/l10n/com.ibm.websphere.appserver.audit-1.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.1/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.2/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.3/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.4/resources/l10n/com.ibm.websphere.appserver.mpConfig-1.4.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-2.0/resources/l10n/io.openliberty.mpConfig-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRA-1.0/resources/l10n/io.openliberty.mpLRA-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRACoordinator-1.0/resources/l10n/io.openliberty.mpLRACoordinator-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/resources/l10n/com.ibm.websphere.appserver.mpOpenTracing-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/resources/l10n/io.openliberty.mpOpenTracing-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/resources/l10n/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.1/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.2/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.4/resources/l10n/com.ibm.websphere.appserver.mpRestClient-1.4.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0.properties
Labels: CLA Signed, team:MicroProfileUK

#14814 Remove z/OS check in test
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplLifecycleMethodServlet.java
Labels: CLA Signed, noproductcode

#14810 SSL auto feature should work with restfulWSClient-3.0 (not just server)
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWSClient3.0-ssl1.0.feature
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14787 Add test for calling CDI.current inside a new thread
  dev/com.ibm.ws.cdi.api_fat/bnd.bnd
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12APIServer/server.xml
  dev/com.ibm.ws.cdi.api_fat/test-applications/cdiCurrentTest.war/src/com/ibm/ws/cdi12/test/common/web/CDICurrentTestServlet.java
Labels: CLA Signed, noproductcode

#14668 Fix connection manager deadlock when purgePolicy=FailingConnectionOnly
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
Labels: CLA Signed, team:Zombie Apocalypse

#14408 move grpc-1.0 and grpcClient-1.0 to GA
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcClientSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcMonitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpc-1.0/io.openliberty.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature
Labels: CLA Signed, in:Transport, team:Sirius

#14831 Fix thread safety issue in web container
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed, team:Performance

#14797 Remove Servlet 5.0 duplicate resource overlays
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/j2ee_1_4.xsd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/j2ee_web_services_1_1.xsd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/j2ee_web_services_client_1_1.xsd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/web-app_2_2.dtd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/web-app_2_3.dtd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/web-app_2_4.xsd
  dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources/web-app_2_5.xsd
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14819 Ensure manifest file for Liberty packaged server archive
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
Labels: CLA Signed

#14834 Use correct ArtifactId for jtidy dependency
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
Labels: CLA Signed, in:Build, team:Zombie Apocalypse

#14792 Issue 13577: NLS updates for JWE decryption
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#14845 Revert "re-introduce and add test for new swidtag"
  dev/build.image/build.gradle
  dev/build.image/publish/ibm.com_WebSphereLiberty-20.0.0.swidtag
  dev/com.ibm.ws.install.packaging_fat/build.gradle
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/CheckTags.java
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/FATSuite.java
Labels: CLA Signed

#14847 Issue 13577: Expanding support for JWE consumption
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.fat.common.jwt/fat/src/com/ibm/ws/security/fat/common/jwt/sharedTests/ConsumeMangledJWTTests.java
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/JwtMessageConstants.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JweHelper.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/utils/JweHelperTest.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/MessageConstants.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
Labels: CLA Signed, team:Security SSO

#14848 Fixes to get things building in eclipse
  dev/build.changeDetector/build.gradle
  dev/com.ibm.ws.concurrent_fat_work/.classpath
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/shared/webapp/webxml/WebXmlParser.java
Labels: CLA Signed, team:Performance

#14836 Fix defaultSystemConfigProperties test failing on escape characters
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/defaultSources/DefaultSourcesTestServlet.java
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#14811 Always remove useKeyTab property when running on IBM JDK
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
Labels: CLA Signed, release bug, team:Zombie Apocalypse

#14851 Upgrade to jakarta.activation 2.0.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mail-2.0/io.openliberty.mail-2.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#14832 Enable JSON Container features for beta
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonbContainer-2.0/io.openliberty.jsonbContainer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonpContainer-2.0/io.openliberty.jsonpContainer-2.0.feature
Labels: CLA Signed

#14860 Fix modified FAT bucket detection for paths containing a second '_fat' token
  .github/workflow-scripts/check-fat-failures.sh
  .github/workflow-scripts/run-fat-build.sh
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/badobserver/TestObserver.java
Labels: CLA Signed, noproductcode

#14824 Further enabling of jakartaee in jsonb FAT
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/FATSuite.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONBContainerTest.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONBInAppTest.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONBTest.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONPContainerTest.java
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JsonUserFeatureTest.java
  dev/com.ibm.ws.jsonb_fat/publish/files/features/testFeatureUsingJsonb-2.0.mf
  dev/com.ibm.ws.jsonb_fat/publish/files/features/testFeatureUsingJsonp-2.0.mf
  dev/com.ibm.ws.jsonp.1.1_fat/bnd.bnd
  dev/com.ibm.ws.jsonp.1.1_fat/build.gradle
  dev/com.ibm.ws.jsonp.1.1_fat/fat/src/com/ibm/ws/jsonp11/fat/FATSuite.java
  dev/com.ibm.ws.jsonp.1.1_fat/fat/src/com/ibm/ws/jsonp11/fat/JSONP11Test.java
  dev/wlp-jakartaee-transform/rules/jakarta-jsonProvider.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed

#14749 Skip locale c.u_US for time pattern testing
  dev/com.ibm.ws.logging.hpel/test/com/ibm/ws/logging/internal/hpel/LocaleUtils.java
Labels: CLA Signed, noproductcode

#14872 Fix anno feature to be a singleton
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/SymbolicNameTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-1.0/com.ibm.websphere.appserver.persistentExecutor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/com.ibm.websphere.appserver.persistentExecutor-2.0.feature
Labels: CLA Signed, team:Performance

#14870 Port JMS Austocloseable FAT from WS-CD-Open and enable jakartaee
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.classpath
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.gitignore
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.project
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/build.gradle
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/fat/src/com/ibm/ws/messaging/JMS20AutoCloseable/fat/Autocloseable/AutoCloseableTest.java
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/fat/src/com/ibm/ws/messaging/JMS20AutoCloseable/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/fat/src/com/ibm/ws/messaging/JMS20AutoCloseable/fat/TestUtils.java
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/publish/files/Qclose.xml
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/publish/files/features/testjmsinternals-1.0.mf
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/publish/servers/SimpleJms20Server/server.xml
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/publish/servers/TestServer/.gitignore
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/publish/servers/TestServer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/test-applications/AutoCloseable/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/test-applications/AutoCloseable/src/web/AutoCloseableTestServlet.java
Labels: CLA Signed, jakartaEE, noproductcode, team:OSGi Infrastructure

#14742 Migrate FAT project 'com.ibm.ws.messaging.open_jms20context_fat' from…
  dev/com.ibm.ws.messaging.open_jms20context_fat/.classpath
  dev/com.ibm.ws.messaging.open_jms20context_fat/.project
  dev/com.ibm.ws.messaging.open_jms20context_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.messaging.open_jms20context_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.messaging.open_jms20context_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_jms20context_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.messaging.open_jms20context_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_jms20context_fat/build.gradle
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118058.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118061.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118062.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118065_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118066_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118067.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118068_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118070.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118075.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118077_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet1Test.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet2Test.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet3Test.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/TestUtils.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/JMSContextClient.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/JMSContextClient_TQ.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/JMSContextEngine.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/JMSContextEngine_TQ.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/features/testjmsinternals-1.0.mf
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/120846_Bindings.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/120846_TcpIp.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/185047_Bindings.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/JMSContext_Client.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/JMSContext_Expiry.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/unused/JMSContext_Server.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextClient/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextClient_118065/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextClient_118066/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextClient_118068/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextClient_118077/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextEngine/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextEngine_118065/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextEngine_118066/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextEngine_118068/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/servers/JMSContextEngine_118077/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext/src/jmscontext/web/JMSContextServlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118067/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118067/src/jmscontext_118067/web/JMSContext_118067Servlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118070/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118070/src/jmscontext_118070/web/JMSContext_118070Servlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118075/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext_118075/src/jmscontext_118075/web/JMSContext_118075Servlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/src/web/#JMSContextServlet.java#
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/src/web/JMSContextServlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/unused/jmsmdb/resources/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/unused/jmsmdb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/unused/jmsmdb/src/jmsmdb/ejb/EJBMessageDrivenBean.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/unused/jmsmdb/src/jmsmdb/ejb/EJBTopicMessageDrivenBean.java
Labels: CLA Signed, in:Java EE Platform, jakartaEE, noproductcode

#14854 update default loginProp
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
Labels: CLA Signed, team:Wendigo East

#14866 HTTP/2 channel needs to check for gRPC request earlier
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed, in:Transport, team:Sirius

#14830 H2: ensure that http connection count gets decremented once
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: CLA Signed

#14853 Stop expirer looping on first message in Transaction
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/Expirer.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpiryIndex.java
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/ExpiryTest.java
Labels: CLA Signed

#14300 Create facesContainer-3.0 Feature
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.facesProvider-3.0.0.Container.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-3.0/io.openliberty.facesContainer-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-3.0/resources/l10n/io.openliberty.facesContainer-3.0.properties
  dev/com.ibm.ws.jsfContainer/bnd.bnd
  dev/com.ibm.ws.jsfContainer/src/com/ibm/ws/jsf/container/cdi/FacesUrlTransformer.java
  dev/com.ibm.ws.jsfContainer/src/com/ibm/ws/jsf/container/cdi/IBMViewHandlerProxy.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/ClassloadingTest.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/ErrorPathsTest.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSFContainerTest.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ELImplicitObjectsViaCDI/src/com/ibm/ws/jsf23/fat/elcdi/beans/ELImplicitObjectBean.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/io.openliberty.facesContainer.classloading.3.0/.classpath
  dev/io.openliberty.facesContainer.classloading.3.0/.project
  dev/io.openliberty.facesContainer.classloading.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.facesContainer.classloading.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.facesContainer.classloading.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.facesContainer.classloading.3.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.facesContainer.classloading.3.0/bnd.bnd
  dev/io.openliberty.facesContainer.classloading.3.0/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/io.openliberty.facesContainer.classloading.3.0/src/com/ibm/ws/jsf/container/classloading30/Faces30LibraryIntegration.java
  dev/io.openliberty.facesContainer.classloading.3.0/src/com/ibm/ws/jsf/container/classloading30/package-info.java
  dev/io.openliberty.org.jboss.weld4/bnd.bnd
  dev/io.openliberty.org.jboss.weld4/test/io/openliberty/weld/jsf/WeldJSFCheckSumTest.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#14849 Add validation rule for ibm:final and avoid NPE
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/wlp-metatypeValidator/src/com/ibm/ws/metatype/validator/events.properties
  dev/wlp-metatypeValidator/src/com/ibm/ws/metatype/validator/xml/MetatypeAd.java
Labels: CLA Signed

#14864 Ignore ambiguous binding warning in tests
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/BadApplicationTests.java
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/EJBAnnTestBase.java
Labels: CLA Signed, noproductcode

#14840 Update MpMetrics 3.0 to use RC3 + new change implementations
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/Constants.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/helper/PrometheusBuilder30.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/helper/Util30.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/impl/Histogram30Impl.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/impl/MetricRegistry30Impl.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/metrics.3.0.bnd
Labels: CLA Signed

#14789 Issue 14734: Fix for empty or null OAuth client name
  dev/com.ibm.ws.security.oauth/src/com/ibm/websphere/security/oauth20/store/OAuthClient.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/BaseClient.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientDBModel.java
Labels: CLA Signed, team:Security SSO

#14827 Add arhive validation which allows prepended scripts
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipValidator.java
Labels: CLA Signed

#14877 11278 Update Jakarta JSON 2.0 APIs to final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.0.0.feature
  dev/com.ibm.ws.org.eclipse.yasson.2.0/bnd.bnd
  dev/com.ibm.ws.org.glassfish.json.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.0/bnd.bnd
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14878 11772 Update Jakarta Transaction 2.0 API to final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.jta-2.0.feature
  dev/io.openliberty.jakarta.transaction.2.0/bnd.bnd
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14886 Move facesContainer 3.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.facesProvider-3.0.0.Container.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-3.0/io.openliberty.facesContainer-3.0.feature
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14879 11851 Update Jakarta Messaging 3.0 API to final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.messaging-3.0.feature
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14893 Beta ee9 auto features for sessionCache, webBundle, and JMS defaultre…
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.app.manager.wab.jakarta-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.messaging.defaultresource-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionCache1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionDatabase1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webBundleSecurity1.0.jakarta.feature
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14823 Add Property Expression FAT test to mpConfig-2.0
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20Tests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/propertyExpression/PropertyExpressionBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/propertyExpression/PropertyExpressionTestServlet.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/org.eclipse.microprofile.config.spi.Converter
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/server.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#14884 Register CDI extensions from SPI against all deployments not just the…
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/ExtensionArchiveImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/WebSphereCDIDeployment.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
Labels: CLA Signed

#14895 Convert ejb jcdi tests to use custom bindings
  dev/com.ibm.ws.ejbcontainer.cdi_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.cdi_fat/fat/src/com/ibm/ws/ejbcontainer/cdi/fat/EJBxCDITest.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/publish/servers/com.ibm.ws.ejbcontainer.cdi.fat.EJB-CDI-Server/server.xml
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIBean.jar/src/com/ibm/ws/ejbcontainer/cdi/jcdi/ejb/UserTranBean.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIBean.jar/src/com/ibm/ws/ejbcontainer/cdi/jcdi/ejb/UserTranStatelessBean.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIWeb.war/src/com/ibm/ws/ejbcontainer/cdi/jcdi/web/BeanManagerInjectionServlet.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIWeb.war/src/com/ibm/ws/ejbcontainer/cdi/jcdi/web/InterceptorIntegrationServlet.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIWeb.war/src/com/ibm/ws/ejbcontainer/cdi/jcdi/web/ResourceServlet.java
Labels: CLA Signed, noproductcode

#14887 Update Jakarta Persistence API (JPA) to final release version 3.0.0.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.0.feature
  dev/io.openliberty.jakarta.persistence.3.0/bnd.bnd
Labels: CLA Signed, in:JPA, jakartaEE, jpa, team:Blizzard

#14841 Add lease renewal time
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseData.java
  dev/com.ibm.ws.transaction/bnd.bnd
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#14863 Enable RestEasy Bean Validation with Hibernate
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-validator3.0.feature
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.classpath
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.gitignore
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.project
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.settings/bndtools.core.prefs
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.jboss.resteasy.validator.provider/bnd.bnd
  dev/io.openliberty.restfulWS.3.0_fat/bnd.bnd
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/ValidatorTest.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/validator/Resource.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/validator/ValidatorTestServlet.java
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/validator/bootstrap.properties
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/validator/jvm.options
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/validator/server.xml
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed

#14005 fix single dot ssoDomain
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/SSOCookieHelperImplTest.java
Labels: CLA Signed, in:Security, release bug, team:Core Security

#14906 Jwtsso without mp jwt
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/BuilderTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FeatureOnlyTest.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/shared/config/jwtSsoFeatures_noMpJwt.xml
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#14911 Remove EJB from CDI description
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/resources/l10n/io.openliberty.cdi-3.0.properties
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#14914 Update MP JWT TCK for new TCK version
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_aud_env.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_aud_noenv.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_aud_noenv2.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_noaud_env.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_noaud_noenv.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/server.env
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/server.env
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/server.env
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/server.env
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
Labels: CLA Signed, noproductcode

#14909 Use uniq token with Logout test
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/fat/src/com/ibm/ws/security/mp/jwt11/fat/MPJwtBasicTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#14919 11851 Fix jakarta messaging connection metadata
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsMetaDataImpl.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118058.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext/src/jmscontext/web/JMSContextServlet.java
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14820 Create ServerLRAFilter as a CDI bean.
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRA-1.0/io.openliberty.mpLRA-1.0.feature
  dev/io.openliberty.microprofile.lra.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraFilterComponent.java
  dev/io.openliberty.org.jboss.narayana.rts/.classpath
  dev/io.openliberty.org.jboss.narayana.rts/bnd.bnd
  dev/io.openliberty.org.jboss.narayana.rts/src/io/openliberty/microprofile/lra/internal/CdiExtensionComponent.java
  dev/io.openliberty.org.jboss.narayana.rts/src/io/openliberty/microprofile/lra/internal/package-info.java
Labels: CLA Signed

#14933 Issue #14931: Fix EJB Handle in App Client
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.enterpriseBeansRemoteClient-2.0.feature
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/fat/src/com/ibm/ws/ejbcontainer/remote/client/fat/tests/EjbLinkTest.java
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkBean.jar/src/com/ibm/ws/ejbcontainer/ejblink/ejb/ComponentBean.java
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkBean.jar/src/com/ibm/ws/ejbcontainer/ejblink/ejb/ComponentRemote.java
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkBean.jar/src/com/ibm/ws/ejbcontainer/ejblink/ejb/ComponentRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkClient.jar/src/com/ibm/ws/ejbcontainer/ejblink/client/EjbLinkClient.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#14813 Update inject and cdi api
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#14862 port web container code for HandleList
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/collaborator/ConnectionHandleCollaborator.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
Labels: CLA Signed, team:Zombie Apocalypse

#14929 Remove comment with link to Narayana code
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/servlet/IndexInitializer.java
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#14871 Issue #14859: Make the jwt-1.0 feature Jakarta EE9 capable.
  dev/com.ibm.websphere.appserver.api.jwt/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jwt1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jwt1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/com.ibm.websphere.appserver.jwt-1.0.feature
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientAdvancedTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientSecurityTest.java
  dev/com.ibm.ws.clientcontainer.cdi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AppClientTest.java
  dev/com.ibm.ws.ejbcontainer.async_fat/fat/src/com/ibm/ws/ejbcontainer/async/fat/tests/AbstractTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/AmbiguousBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BndErrorTest.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/AbstractTest.java
  dev/com.ibm.ws.ejbcontainer.session.passivation_fat/fat/src/com/ibm/ws/ejbcontainer/session/passivation/tests/AbstractTest.java
  dev/com.ibm.ws.javaee.8.0_fat/fat/src/com/ibm/ws/javaee/v80/fat/JavaEE8Test.java
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/ThirdPartyJAXBTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/AnnotationFilter.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/FaultToleranceMainTest.java
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwkEndpointValidationUrlTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigAltKeyStoreTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigNoIdTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumRunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigBuilderTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigGlobalTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIWithLDAPConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiWithLDAPBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderFeatures.xml
  dev/com.ibm.ws.security.jwt_fat.builder/test-applications/jwtbuilderclient/src/com/ibm/ws/jaxrs/fat/jwtbuilderclient/JwtBuilderSetApisClient.java
  dev/com.ibm.ws.security.jwt_fat.consumer/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumHSARunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLConsumerConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLGlobalConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigBlankIdTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigWithGlobalTrustTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/BuilderTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FeatureOnlyTest.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.tx.jta_fat/fat/src/com/ibm/ws/tx/jta/test/SimpleTest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/RepeatTestFilter.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FATServletClient.java
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
Labels: CLA Signed, team:Wendigo East

#14932 Add Beta & Blog parts to feature template
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed

#14953 Revert "Update inject and cdi api"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#14956 14807 update weld inject
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.weld4/test/io/openliberty/weld/jsf/WeldJSFCheckSumTest.java
Labels: CLA Signed

#14940 Disable osgi.checkConfiguration by default
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
Labels: CLA Signed

#14924 Update loginProperty syntax in LDAP FATs
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/globalClientCertFailOverToAppDefined.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/globalClientCertFailOverToBA.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/globalClientCertFailOverToForm.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/globalClientCertNoFailOver.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/files/globalClientCertNoFailOverSupport.xml
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.clientcert.fat/server.xml
  dev/com.ibm.ws.security.wim.adapter.file_fat/publish/files/dyanamicUpdate/ldap_and_custom_registry.xml
  dev/com.ibm.ws.security.wim.adapter.file_fat/publish/files/dyanamicUpdate/ldap_basic_custom_registry.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter2.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertMultipleLDAP.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_invalidSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_multipleSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_validSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin_SBInFilter/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.propertynotsupported/server.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#14968 Revert "14807 update weld inject"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.weld4/test/io/openliberty/weld/jsf/WeldJSFCheckSumTest.java
Labels: CLA Signed

#14947 Wait for configuration update in testEventLoggingLogModeUpdate2
  dev/com.ibm.ws.event.logging_fat/fat/src/com/ibm/ws/event/logging/FATTest.java
Labels: CLA Signed, noproductcode

#14619 [14611] Tolerate mpConfig-2.0
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/JarInWarTest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/RolesAuthTest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.basicMutation/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.basicQuery/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.basicQueryWithConfig/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.defaultvalue/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.deprecation/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.graphQLInterface/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.iface/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.ignore/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.inputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.metrics/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.outputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.rolesAuth/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.types/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.voidQuery/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/metricsApp/src/mpGraphQL10/metrics/MetricsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#14857 make configuration-policy:=require and add default instance
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed

#14970 test that handlelist closes leaked autocommit false connection
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/JDBC43Test.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14821 Make mpConfig duplicate converters deterministic
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/converters/PriorityConverterMap.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/libertyTests/LibertyConfigFieldInjectionBean.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/libertyTests/LibertyFieldTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/Ant.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/AntConverter.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/DiscoveredConfigSource.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/MyTypeConverter1.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/MyTypeConverter2.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/test/MyTypeWithMultipleConverters.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/FieldTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.war/resources/META-INF/services/org.eclipse.microprofile.config.spi.Converter
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20Tests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/ConvertersTestServlet.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/DuplicateConvertersBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/MyTypeConverter1.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/MyTypeConverter2.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/MyTypeWithMultipleConverters.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/resources/convertersWar/org.eclipse.microprofile.config.spi.Converter
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/Config

#14964 Correct FacesContainer Feature File
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-3.0/io.openliberty.facesContainer-3.0.feature
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14905 Add Face 3.0 test for the new faces-config.xml
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/jsf/FacesConfig.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppTestBase.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14972 Disable flaky tests
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
Labels: CLA Signed, noproductcode

#14962 remove ejb trademark from nls files
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansLite-4.0/resources/l10n/io.openliberty.enterpriseBeansLite-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansLite-4.0/resources/l10n/io.openliberty.enterpriseBeansLite-4.0_ru.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#14730 Add mpCompatible-x.x private features
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi3.0-mpContextPropagation1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.1/com.ibm.websphere.appserver.mpConfig-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.2/com.ibm.websphere.appserver.mpConfig-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.3/com.ibm.websphere.appserver.mpConfig-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.4/com.ibm.websphere.appserver.mpConfig-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-2.0/com.ibm.websphere.appserver.mpConfig-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.0/com.ibm.websphere.appserver.mpContextPropagation-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.1/com.ibm.websphere.appserver.mpContextPropagation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.0/com.ibm.websphere.appserver.mpFaultTolerance-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.0/com.ibm.websphere.appserver.mpFaultTolerance-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.1/com.ibm.websphere.appserver.mpFaultTolerance-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-3.0/com.ibm.websphere.appserver.mpFaultTolerance-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.0/com.ibm.websphere.appserver.mpJwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.1/com.ibm.websphere.appserver.mpJwt-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.2/com.ibm.websphere.appserver.mpJwt-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRA-1.0/io.openliberty.mpLRA-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRACoordinator-1.0/io.openliberty.mpLRACoordinator-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.0/com.ibm.websphere.appserver.mpMetrics-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.0/com.ibm.websphere.appserver.mpMetrics-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.2/com.ibm.websphere.appserver.mpMetrics-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.3/com.ibm.websphere.appserver.mpMetrics-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-3.0/com.ibm.websphere.appserver.mpMetrics-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.1/com.ibm.websphere.appserver.mpOpenAPI-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-2.0/com.ibm.websphere.appserver.mpOpenAPI-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/com.ibm.websphere.appserver.mpOpenTracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/com.ibm.websphere.appserver.mpOpenTracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/com.ibm.websphere.appserver.mpOpenTracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/com.ibm.websphere.appserver.mpOpenTracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/com.ibm.websphere.appserver.mpOpenTracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-1.0/com.ibm.websphere.appserver.mpReactiveStreams-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.0/com.ibm.websphere.appserver.mpRestClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.1/com.ibm.websphere.appserver.mpRestClient-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.2/com.ibm.websphere.appserver.mpRestClient-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/com.ibm.websphere.appserver.mpRestClient-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.4/com.ibm.websphere.appserver.mpRestClient-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/com.ibm.websphere.appserver.mpRestClient-2.0.feature
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentCDITest.java
Labels: CLA Signed

#14942 Fix mpConfig-2.0 FAT TCKs
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#14955 add isReady calls to streaming
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
Labels: CLA Signed, noproductcode

#14945 Issue #11940: Final Jakarta Annotation API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-2.0.feature
Labels: CLA Signed, in:Java EE Platform, jakartaEE, team:Blizzard

#14983 Adding more debug to wlp.lib.extract.PackageRunnableTest.testRunnableJar
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#14979 Update Jakarta Server Pages 3.0 API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#15000 add allowed exception in BasicTest
  dev/com.ibm.ws.security.client_fat/fat/src/com/ibm/ws/security/client/fat/BasicTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#14974 Avoid throwing HTTP/2 connection close exception
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
Labels: CLA Signed, in:Transport, team:Sirius

#14998 Pull in GA version of Jakarta RESTful Web Services API JAR
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.0.feature
  dev/io.openliberty.jakarta.restfulWS.3.0/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14997 Do not create a Java SCC with tools
  dev/cnf/resources/bin/tool
  dev/cnf/resources/bin/tool.bat
Labels: CLA Signed

#15007 Issue 15006: Ignore CWIMK0004E temporarily
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_RealmPropertyMappingTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#15008 Update JSTL 2.0 maven coordinate
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
Labels: CLA Signed

#14912 Add start-phase:=CONTAINER_EARLY to facade bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.2/com.ibm.websphere.appserver.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.3/com.ibm.websphere.appserver.jsp-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
Labels: CLA Signed

#12514 12095: Add catch around HttpEndpointInfo initalization
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Sirius

#14920 initialize InstallKernelMap before capturing SharedOutput
  dev/com.ibm.ws.install/test/com/ibm/ws/install/InstallKernelMapTest.java
Labels: CLA Signed, noproductcode

#14994 Issue 14389: Update JwtBuilder API Javadoc to clarify JWE support
  dev/com.ibm.ws.security.jwt/src/com/ibm/websphere/security/jwt/JwtBuilder.java
Labels: CLA Signed, team:Security SSO

#14812 grpc client config should always perform full lookup
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/config/GrpcClientConfigHolder.java
Labels: CLA Signed, in:Transport, team:Sirius

#15015 Test mpOT-2.0 with mp-4.0
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/FATSuite.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncherMicroProfile.java
Labels: CLA Signed, noproductcode

#15009 Move processing of the onError attribute and guard against NPEs
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/SystemConfiguration.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/WSConfigXMLActivator.java
Labels: CLA Signed

#14992 Add FFDCIgnore ZipException to FATTEST.testConfigureInvalidApplication
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
Labels: CLA Signed, noproductcode, test bug

#15018 Fix OOM errors
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/DataModelSerializer.java
Labels: CLA Signed

#15020 Re-enable MP Concurrent tests and add a Repeat Action for 1.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/com.ibm.ws.concurrent.mp_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/build.gradle
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentCDITest.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentConfigTest.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentJAXRSTest.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentTest.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentTxTest.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextProp11RepeatAction.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentTxTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPContextProp1_1_Server/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentTxApp/src/concurrent/mp/fat/tx/web/MPConcurrentTxTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPContextProp1_1_App/src/concurrent/mp/fat/v11/web/MPContextProp1_1_TestServlet.java
Labels: CLA Signed

#14625 Redo 14605 where ds injection fails
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.tx.util/src/com/ibm/tx/util/TMHelper.java
  dev/com.ibm.tx.util/src/com/ibm/tx/util/TMService.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryAgent.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.classpath
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.project
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/build.gradle
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxDBRoSTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxDBTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxRoSTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBRoSServer/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBRoSServer/jvm.options
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBRoSServer/server.xml
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBServer/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBServer/jvm.options
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBDBServer/server.xml
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBRoSServer/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBRoSServer/jvm.options
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBRoSServer/server.xml
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBServer/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBServer/jvm.options
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/publish/servers/com.ibm.ws.transaction_EJBServer/server.xml
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/test-applications/newEJBTx1/src/com/ibm/ws/transaction/ejb/first/InitNewTxBean1.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/test-applications/newEJBTx2/src/com/ibm/ws/transaction/ejb/second/InitNewTxBean2.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/test-applications/newEJBTx3/src/com/ibm/ws/transaction/ejb/third/InitNewTxBean3.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TransactionManagerService.java
Labels: CLA Signed

#15039 Add FFDC to ORBWrapper.activate()
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/ORBWrapper.java
Labels: CLA Signed

#15011 Change RestEasy Bean Validation to match CXF Bean Validation
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanvalidation/JAXRSClientServerValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanvalidation/JAXRSPerRequestValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.beanvalidation/bootstrap.properties
  dev/io.openliberty.org.jboss.resteasy.validator.provider/.classpath
  dev/io.openliberty.org.jboss.resteasy.validator.provider/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider/src/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/validator/ValidatorTestServlet.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15028 Make sure some test features are deleted after the tests run
  dev/com.ibm.ws.context_fat/fat/src/com/ibm/ws/context/fat/ContextServiceFATTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/HandlerTest.java
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FATBase.java
Labels: CLA Signed, noproductcode

#14996 test leaked JMS connection handles
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/jca/cm/handle/HandleList.java
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/jca/cm/handle/HandleListInterface.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/HandleListProxy.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/HCMDetails.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.jakarta/server.xml
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnection.java
Labels: CLA Signed, team:Zombie Apocalypse

#14179 Issue 14711: Jakarta transformation for audit feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.audit1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.audit1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.auditCollector1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.auditCollector1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.auditCollector-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.auditWebProbes-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/com.ibm.websphere.appserver.audit-1.0.feature
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/audit/EJBJarX03JACCAuditTest.java
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/audit/PureAnnA08JAASLoginFromEJBJACCAuditTest.java
  dev/com.ibm.ws.request.probe.audit.servlet/bnd.bnd
  dev/com.ibm.ws.security.audit.file/bnd.bnd
  dev/com.ibm.ws.security.audit.source/bnd.bnd
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/audit/JASPIBasicAuthenticationAuditTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/audit/JASPICallbackBasicAuthAuditTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/audit/JASPIFormLoginAuditTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/audit/JASPIFormLoginJACCAuthorizationAuditTest.java
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/audit/BasicAuthAuditAUTHZTest.java
Labels: CLA Signed, team:Wendigo East

#14916 Issue 14908: Wait on features for ConfigManager modify
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_RealmPropertyMappingTest.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ConfigManager.java
  dev/com.ibm.ws.security.wim.core_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/ConfigManagerFeatureTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/userRegistry.xml
Labels: CLA Signed, team:Wendigo East

#14966 Jms20 fat delay
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.classpath
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.project
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/build.gradle
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullSecOffTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullSecOnTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayLiteSecOffTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayLiteSecOnTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DummyTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/TestUtils.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_1.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_2.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_Alias.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_Debug.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_MDB.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_QueueMDB_Bindings.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_QueueMDB_TCP.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_SSL.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_TopicMDB_Bindings.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_TopicMDB_TCP.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayEngine.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayEngine_Debug.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayEngine_SSL.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/clientLTPAKeys/clientKey.jks
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/clientLTPAKeys/mykey.jks
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/engineLTPAKeys/cert.der
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/engineLTPAKeys/ltpa.keys
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/engineLTPAKeys/mykey.jks
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/engineLTPAKeys/serverKey.jks
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/features/testjmsinternals-1.0.mf
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/servers/DeliveryDelayClient/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/servers/DeliveryDelayEngine/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/resources/WEB-INF/web.xml
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/jmsmdb/src/jmsmdb/ejb/MessageDrivenBean.java
  dev/wlp-jakartaee-transform/rules/jakarta-messaging.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed

#15024 Ensure app path is decoded when matching resources.
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/helloworld/HelloWorldTest.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14865 Add eeCompatible features to private API features for EE
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.annotation-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.cdi-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.connector.internal-1.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.connector.internal-1.7.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.ejb-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.ejb-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.el-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.el-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.interceptor-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.interceptor-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsf-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsp-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.mail-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.mail-1.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence.base-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence.base-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.validation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.validation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.connectors-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.ejb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.faces-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.interceptor-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.jaxb-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.jaxws-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.jndiClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.pages-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence.base-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.jta-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.jta-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile/config.1.4.bnd
Labels: CLA Signed

#14930 Issue 14925: OAuth subject lookup fix
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/common/claims/UserClaimsRetriever.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/common/claims/UserClaimsRetrieverService.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/internal/OAuth20AuthenticatorImpl.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/common/claims/UserClaimsRetrieverTest.java
Labels: CLA Signed, team:Security SSO

#15056 Fix up eclipse settings to get things working again
  dev/com.ibm.ws.messaging.open_jms20context_fat/.classpath
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/src/jmstemporaryqueue/web/JMSContextServlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/src/web/JMSContextServlet.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/.project
  dev/com.ibm.ws.security.spnego/.classpath
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/.classpath
  dev/io.openliberty.org.jboss.weld4/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#15049 Fix test so that it works with a repeat action
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPConcurrentTxTest.java
Labels: CLA Signed, noproductcode

#15055 11851 Add doPriv to jms runtime for subscriber mbean service registra…
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/files/DelayClient_MDB.xml
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/admin/internal/MessagingMBeanFactoryImpl.java
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#15059 message not ported to OpenLiberty
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/HCMDetails.java
Labels: CLA Signed, team:Zombie Apocalypse

#15065 Ignore Quotes in legacy EJB msgs
  dev/com.ibm.ws.ejbcontainer.core/bnd.bnd
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, in:EJB Container, team:Blizzard

#15004 Handle NPE during remote unbind if orb didn't come up
  dev/com.ibm.ws.ejbcontainer.remote/src/com/ibm/ws/ejbcontainer/remote/internal/EJBRemoteRuntimeImpl.java
Labels: CLA Signed

#15062 Update and add description for REST stat metrics for MP Metris 3.0
  dev/io.openliberty.microprofile.metrics.internal.3.0/resources/io/openliberty/microprofile/metrics/internal/resources/Metrics.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#15066 WSOC FVT: change timing for the connectToClass test
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/AnnotatedTest.java
Labels: CLA Signed, noproductcode

#15048 Make OpenAPI 2.0 fully scan module directories
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/IndexUtils.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
Labels: CLA Signed

#15057 OpenAPI: respect config when scanning expanded app
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/IndexUtils.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
Labels: CLA Signed

#15075 move grpc-1.0 and grpcClient-1.0 to edition=core
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcClientSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcMonitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpc-1.0/io.openliberty.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature
Labels: CLA Signed, in:Transport, team:Sirius

#15013 fix gRPC streaming data race condition
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletAdapter.java
Labels: CLA Signed, in:Transport, team:Sirius

#15088 Upgrade connection-2.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, team:Zombie Apocalypse

#15069 Update mpConfig 2.0 to use latest artifacts from Maven Central
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile/Config

#15081 Add Java2 security permissions for testConverterExceptions test
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20Tests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/resources/convertersApp/org.eclipse.microprofile.config.spi.Converter
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/resources/convertersApp/permissions.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#14961 Add remaining websocket tests
  dev/io.openliberty.wsoc.internal_fat/.classpath
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/build.gradle
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/MiscellaneousTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/TraceTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/SecurityTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/TraceEnabledTest.java
  dev/io.openliberty.wsoc.internal_fat/publish/files/Secure/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/miscellaneousTestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/miscellaneousTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/secureTestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/secureTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/resources/dojo.js
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/resources/index.html
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/ApplicationConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/Basic2AnnotatedServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/BasicAnnotatedServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/EndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/LongRunMultiServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/MiscNoCDIInjectedServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/PartialAnnotatedServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/ProgServerEPS.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/StatelessEjb.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/StatelessInterface.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/secure.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/secure.war/resources/dojo.js
  dev/io.openliberty.wsoc.internal_fat/test-applications/secure.war/resources/index.html
  dev/io.openliberty.wsoc.internal_fat/test-applications/secure.war/src/secure/war/SecureTextServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/resources/dojo.js
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/resources/index.html
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/AnnotatedAsyncTextServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/AnnotatedServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/CodedEndpointListener.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/CodedServerEndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/ExtendedServerApplicationConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/MultiServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/PathParamServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/ProgrammaticServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/SinglePublisherMultiClientServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/configurator/AnnotatedConfiguratorServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/configurator/ConfiguratorEndpointConfig.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#15070 Avoid NPE in case where an app handler is unset
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/StartAction.java
Labels: CLA Signed

#15091 Add testcase for DB2 with SSL connection
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/DB2Test.java
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/certs/server.kdb
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/certs/server.sth
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/custom/db2_tls_setup.sh
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/security/db2-keystore.p12
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
  dev/com.ibm.ws.jdbc_fat_db2/test-applications/db2fat/src/db2/web/DB2TestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14855 deliver OL Tag and FAT
  dev/build.image/build.gradle
  dev/build.image/publish/ibm.com_Open_Liberty-21.0.0.swidtag
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/CheckTags.java
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/FATSuite.java
Labels: CLA Signed

#15058 Issue 14917: Clarify JWT message about JWE requirements and feature level required
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
Labels: CLA Signed, L2 Reviewed, team:Security SSO

#15094 Issue #15092: Verify that RestEasy ReactiveClient works by enabling com.ibm.ws.jaxrs.2.1.client_fat to be transformed
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuiteLite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCXFRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCallbackTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientLTPATest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLProxyAuthTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ComplexClientTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ReactiveSampleTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21TimeoutClientTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientCXFRxInvokerTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientCompletionStageRxInvokerTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientJerseyRxInvokerTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ProxyAuthTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ReactiveSampleTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21TimeoutClientTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clientcallback/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clientltpa/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clientproxyAuth/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clientssl/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clienttimeout/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21complexclient/resources/WEB-INF/web.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15076 test that handles parked when left open by message driven bean are closed when transaction ends
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAAnnoServlet.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/mdb/DerbyRAMessageDrivenBean.java
  dev/com.ibm.ws.jca_fat_derbyra/test-resourceadapters/fvt-resourceadapter/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_derbyra/test-resourceadapters/fvt-resourceadapter/src/fat/derbyra/resourceadapter/DerbyConnection.java
Labels: CLA Signed, team:Zombie Apocalypse

#15103 Update mpMetrics to use the MP Metrics 3.0 artifacts from sonatype - via artifactory and DHE - v2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.org.eclipse.microprofile/metrics.3.0.bnd
Labels: CLA Signed
