Repository OpenLiberty/open-liberty, pull requests merged in 2020-02, with the labels that each got.

#10652 Changed tck_suite.xml DOCKTYPE certificates to use http rather than https
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-10-subset.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-11-subset.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
Labels: CLA Signed, noproductcode

#10663 Social login: okdServiceLogin metatype initial drop
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OkdServiceLoginImpl.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Security SSO

#10682 stop cookie processing on token response
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
Labels: CLA Signed

#10615 Secondary language error for chooser
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/lang/LocalesModifier.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/lang/package-info.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/error/impl/BrowserAndServerLogMessage.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/LogoutPages.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/SelectionPageGenerator.java
Labels: CLA Signed

#10685 remove extra cleanout of cache
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLSupportImpl.java
Labels: CLA Signed

#10497 Initial commit:adding decompression ratio support
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, in:Transport, release bug, team:Sirius

#10701 20.0.0.2 NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#10595 10476-Initial mpHealth-2.2 implementation
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/com.ibm.websphere.appserver.microProfile-3.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/resources/l10n/com.ibm.websphere.appserver.mpHealth-2.2_zh_TW.properties
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.gitignore
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.project
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/fat/src/com/ibm/ws/microprofile/health22/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/fat/src/com/ibm/ws/microprofile/health22/tck/Health22TCKLauncher.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/servers/Health22TCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/servers/Health22TCKServer/jvm.options
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/servers/Health22TCKServer/server.xml
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/.gitignore
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health22/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/health22/test/URIProviderProducer.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#10664 Issue #10563: MissedPersistentTimerAction
  dev/com.ibm.ws.ejbcontainer.timer.persistent/src/com/ibm/ws/ejbcontainer/timer/persistent/osgi/internal/EJBPersistentTimerRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent/src/com/ibm/ws/ejbcontainer/timer/persistent/osgi/internal/PersistentTimerTaskHandlerImpl.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/MissedTimerActionEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/missed/ejb/MissedTimerAction.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/MissedTimerActionEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/missed/ejb/MissedTimerActionBean.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/MissedTimerActionWeb.war/src/com/ibm/ws/ejbcontainer/timer/persistent/missed/web/MissedTimerActionServlet.java
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/metatype/metatype.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/EJBTimerServiceElement.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:EJB Container, team:Blizzard

#10673 Upgrade to ASM 7.3.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#10676 Update to MP Config 1.4-RC3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.4/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14Impl.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/NullDefaultInjectionTest.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/apps/nullDefaultInjection/NullDefaultInjectionBean.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/apps/nullDefaultInjection/NullDefaultInjectionServlet.java
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#10593 Add additional tested features,
  dev/com.ibm.ws.cdi.visibility_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#10690 Expose the isWeldProxy methods via CDIService
  dev/com.ibm.ws.cdi.interfaces/src/com/ibm/ws/cdi/CDIService.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
Labels: CLA Signed

#10560 Add test to check result of hitting Readiness endpoint as server is starting
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/src/com/ibm/ws/microprofile/health20/delayed/health/check/app/DelayedServlet.java
Labels: CLA Signed, noproductcode

#10693 Social login service accounts: First drop of impl
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OkdServiceLoginImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialConfigUtils.java
Labels: CLA Signed, team:Security SSO

#10656 Handle Charsets in JsonBProvider
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/JsonbCharsetTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonbCharset/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonbCharset/jvm.options
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonbCharset/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbCharsetApp/src/jaxrs21/fat/jsonbcharset/JsonbCharsetTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbCharsetApp/src/jaxrs21/fat/jsonbcharset/Person.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbCharsetApp/src/jaxrs21/fat/jsonbcharset/Resource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonBProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs/utils/test/JAXRSUtilsTest.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10576 review comment updates
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/expectations/JwtApiExpectation.java
Labels: CLA Signed, team:Security SSO, test bug

#10706 Issue #10704: Fix EJB timer getNextTimeout
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/TimerNpImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#10679 disabled test of login module in JARs within RAR
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnectionMetaData.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnectionFactory.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar1/JAR1LoginModule.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar2/JAR2LoginModule.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10703 Sleep for 600ms so that Windows boxes will report sleep was >= 500.
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/metricsApp/src/mpGraphQL10/metrics/MyGraphQLEndpoint.java
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#10709 Fix timing issue with file updates
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
Labels: CLA Signed, noproductcode

#10700 Issue #10697: LDAP and URBridge need to unescape escaped quotation an…
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/xpath/ldap/util/LdapXPathTranslateHelper.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/utils/URBridgeXPathHelper.java
  dev/com.ibm.ws.security.wim.core/test/com/ibm/ws/security/wim/xpath/WIMXPathInterpreterTest.java
Labels: CLA Signed, team:Wendigo East

#10710 Mp jwt java2 updates
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.builder/configs/server_using_buildApp.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.client/configs/rs_server_orig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.client/configs/rs_server_propagation.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.jvmOptions/configs/rs_server_AltConfigNotInApp_badServerXmlIssuerOnly.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.jvmOptions/configs/rs_server_AltConfigNotInApp_badServerXmlJwksUriOnly.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.jvmOptions/configs/rs_server_AltConfigNotInApp_badServerXmlKeyNameOnly.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.jvmOptions/configs/rs_server_AltConfigNotInApp_goodServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat.jvmOptions/configs/rs_server_AltConfigNotInApp_noServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigInApp_badServerXmlIssuer.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigInApp_badServerXmlJwksUri.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigInApp_badServerXmlKeyName.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigInApp_goodServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigInApp_noServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigNotInApp_goodServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_AltConfigNotInApp_noServerXmlConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_SessionScopeClaimInjectBoolean.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_SessionScopeClaimInjectLong.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_SessionScopeClaimInjectSet.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_SessionScopeClaimInjectString.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_appScopeClaimInjectBoolean.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_appScopeClaimInjectLong.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_appScopeClaimInjectSet.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_appScopeClaimInjectString.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_audience_hs256.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_authFilter_false.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_authFilter_true.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_clockSkew_normal.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_clockSkew_short.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_for_propagation_tests.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_inValidSSLRef.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_invalidKeyName.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_jdk.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_jwk.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_loginConfig_ignoreApplicationAuthMethodFalse.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_loginConfig_ignoreApplicationAuthMethodTrue.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_mapToUserRegistry_false.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_mapToUserRegistry_true.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_noApp.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_noIssuer.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_noJwk.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_noMpJwtConfig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_orig.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_orig_withAudience.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_tokenReuse_false.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_tokenReuse_true.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_userNameAttribute_different.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_userNameAttribute_good.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_userNameAttribute_mapToUserRegistryTrue.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/servers/com.ibm.ws.security.mp.jwt.fat/configs/rs_server_validSSLRef.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/shared/config/builderAppJava2Settings.xml
  dev/com.ibm.ws.security.mp.jwt_fat/publish/shared/config/microProfileAppJava2Settings.xml
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#10681 Add support for closed liberty features
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#10708 Social login service accounts: Complete golden path implementation
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OkdServiceLoginImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialConfigUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAISubjectUtils.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/Oauth2LoginConfigImplTest.java
Labels: CLA Signed, team:Security SSO

#10716 Enable postgres and sqlserver tests where able
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceTest.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10734 Revert "disabled test of login module in JARs within RAR"
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnectionMetaData.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnectionFactory.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar1/JAR1LoginModule.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar2/JAR2LoginModule.java
Labels: CLA Signed, noproductcode

#10688 Re-introduce update repeat fault tolerance
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/suite/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/suite/RepeatMicroProfile13.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/suite/RepeatMicroProfile20.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetrics/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetricsRemoval/server.xml
Labels: CLA Signed, noproductcode

#10718 FT 1.0: Disable BulkheadSyncRetryTest.testNoRetriesBulkhead
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#10671 Fix for Issue #10670: Allow JAX-RS Application.getSingletons() to handle CDI proxy classes
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/ContextandCDI12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandCDI/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandCDI/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/com.ibm.ws.jaxrs20.cdi12.fat.contextandCDI/server.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication1.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication11.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication12.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication2.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication21.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication22.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication3.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication31.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication32.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication4.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication5.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIApplication6.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIFilter.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIFilter2.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIFilter3.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIFilter4.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/CDIUtils.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource2.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource3.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource4.java
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
Labels: CLA Signed, bug, in:JAX-RS, team:Wendigo West

#10645 Add HADB error handling for tx log DB locking scheme
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLHADBRetry.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLogManager.java
Labels: CLA Signed

#10751 changed should run to must run
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, noproductcode

#9597 PR for Issue 9588: Fix JWKs behavior when JWT includes KID
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
Labels: CLA Signed, team:Security SSO

#10727 Disable Timer and Meter tests for Windows platforms due to anomolous java behaviour
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#10724 Social login service accounts: Add caching support
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/CommonCache.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/SingleTableCache.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/structures/SingleTableCacheTest.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OkdServiceLoginImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/Cache.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/Oauth2LoginConfigImplTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/TokenCacheTest.java
Labels: CLA Signed, team:Security SSO

#10749 Enable kafka client trace
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SimpleRxMessagingServer/bootstrap.properties
Labels: CLA Signed, noproductcode

#10747 Updated fault tolerance to use the new MP FT2.1 release
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.faulttolerance.2.1/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/FaultTolerance

#10738 Don't skip processing remainder of work queue when closed socket enco…
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/NBAcceptChannelSelector.java
Labels: CLA Signed

#10746 Fix for Issue #10744: Increase the timeout in BasicSseResource to account for slow build machines
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BasicSseApp/src/jaxrs21sse/basic/BasicSseResource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#10741 remove unused INSTANCE var and cache enableImplicitBeanArchives
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/config/liberty/CDI12ContainerConfig.java
Labels: CLA Signed

#10647 Issue #10646: Clean up Servlet 40 FAT
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCAddJspFileTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCContextRootPrecedence.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCEncodingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCGetMappingSlashStarTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCGetMappingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderSecurityTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletClarificationTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContainerInitializerExceptionTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContainerInitializerFilterServletNameMappingTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletPathForDefaultMappingDefault.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletPathForDefaultMappingFalse.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTrailersTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#10737 FT 1.x: exclude unreliable bulkhead tests
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-10-subset.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-11-subset.xml
Labels: CLA Signed, noproductcode

#10757 Social login service accounts: Process service account user name
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed

#10699 Fixing XA Recovery issue with Postgres and optimized creating table
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceTest.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/server.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10292 Issue #10267: Remove Channel traces from server
  dev/com.ibm.ws.transport.http.compression_fat/fat/src/com/ibm/ws/transport/http/HttpCompressionTests.java
  dev/com.ibm.ws.transport.http.compression_fat/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
Labels: CLA Signed, in:Web Components, team:Sirius

#10740 ensure temporary JAR is created from all test classes that use the server config
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/ConnectionManagerMBeanTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/DependantApplicationTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnectionMetaData.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnectionFactory.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar1/JAR1LoginModule.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/jar2/JAR2LoginModule.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10726 initial dbtaskstore methods to create, read, and update the partition entry for polling
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/Config.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
Labels: CLA Signed, team:Zombie Apocalypse

#10753 tests in PersistentExecutorConfigUpdateTest should not be commented out
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/PersistentExecutorConfigUpdateTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10729 Ensure LTPA Keys are created before hitting https endpoint
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
Labels: CLA Signed, noproductcode

#10715 Initial SameSite FAT Suite checkin
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/resources/SameSiteSetCookie.jsp
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/filter/SameSiteAddCookieSetCookieHeaderFilter.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/filter/SameSiteSetCookieFilter.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/servlet/SameSiteAddCookieServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/servlet/SameSiteAddCookieSetCookieHeaderServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/servlet/SameSiteSessionCreationServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/SameSiteTest.war/src/samesite/servlet/SameSiteSetCookieServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#10765 Move up to the final release version of MP Config 1.4
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.config.1.4/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#10767 Fix for Issue #10253: Add Reactive client to AtInjectTest and InterceptorTest tests
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/AtInjectRxTest.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/InterceptorRxTest.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinjectrx/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinjectrx/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.atinjectrx/server.xml
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.interceptorrx/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.interceptorrx/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.interceptorrx/server.xml
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/atinjectapp/src/jaxrs21/fat/atinject/AtInjectTestRxServlet.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/interceptorapp/src/jaxrs21/fat/interceptor/InterceptorTestRxServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#10748 LoadTestWithFailoverEnabled should tolerate CWWKC1502W
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTestWithFailoverEnabled.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10785 RollbackException due to timeout can happen in LoadTest
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/LoadTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10784 Add catch for SocketTimeoutException
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
Labels: CLA Signed, noproductcode

#10797 Remove package qualification for exceptions
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FeatureUpdate.java
  dev/com.ibm.ws.messaging.open_comms_fat/test-applications/CommsLP/src/com/ibm/ws/messaging/open_comms/fat/CommsLPServlet.java
Labels: CLA Signed, noproductcode

#10778 Remove Informix logic
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10768 update cxf projects to fix eclipse builds on java 11+
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10793 Update Yoko to version that removes Java 7 incompatibility
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#10739 ConnectionManagerMBean.getJndiName JavaDoc is not accurate
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/mbean/ConnectionManagerMBean.java
Labels: CLA Signed, team:Zombie Apocalypse

#10802 disabled test of login module loaded from the application
  dev/com.ibm.ws.jdbc_fat_loadfromapp/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/first/FirstBean.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/first/FirstEJBModLoginModule.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/second/SecondBean.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/second/SecondEJBModLoginModule.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromAppServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromWebModLoginModule.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10736 Move repeat fault tolerance
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/faulttolerance/tck/FaultToleranceTck20Launcher.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIAnnotationsDisabledTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIAsyncTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIBulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDICircuitBreakerTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIFallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDIRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/CDITimeoutTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/TxRetryReorderedTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/TxRetryTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/async/AsyncRequestScopedContextTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/async/AsyncReturnNullTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/ejb/AsyncEJBTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/enablement/DisableEnableTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/validation/ValidationTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/build.gradle
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/CDIFallbackTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/circuitbreaker/CircuitBreakerMetricTest.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.classpath
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.project
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/package-info.java
Labels: CLA Signed, in:MicroProfile/FaultTolerance, noproductcode

#10805 fix slash replacement
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/KeyStoreManager.java
Labels: CLA Signed

#10613 check bundle state during generateXML
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components

#10535 remove synchronize keyword from serverStopping method
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/GeneratePluginConfigMBean.java
Labels: CLA Signed, in:Web Components, team:Sirius

#10174 New test for injecting MP Rest Client into ctor, setter, and field
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/MyCdiManagedObject.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/MPRestClientCallback.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/MPRestClientCallback.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#10728 EJB Custom Bindings: Throw error for namespace in binding
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BndErrorTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error18/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error19/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error20/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error20/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error21/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error21/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error22/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error23/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error24/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error25/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error26/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error26/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error27/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error27/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error28/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/resources/error29/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error18/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error18/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error18/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error19/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error19/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error19/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error20/ejb/RemoteTargetBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error20/ejb/RemoteTargetCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error20/ejb/RemoteTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error20/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error21/ejb/RemoteTargetBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error21/ejb/RemoteTargetCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error21/ejb/RemoteTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error21/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error22/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error22/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error22/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error23/ejb/RemoteTargetBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error23/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error24/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error24/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error24/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error25/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error25/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error25/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error26/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error26/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error26/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error27/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error27/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error27/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error28/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error28/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error28/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error29/ejb/LocalCompBiz.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error29/ejb/LocalTargetHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BndErrorEJB.jar/src/com/ibm/bnd/err/ejb/error29/ejb/TargetBean.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBMDOrchestratorImpl.java
Labels: CLA Signed

#9926 Simple feature start and stop verification
  dev/build.featureStart/.classpath
  dev/build.featureStart/.project
  dev/build.featureStart/.settings/bndtools.core.prefs
  dev/build.featureStart/.settings/org.eclipse.core.resources.prefs
  dev/build.featureStart/.settings/org.eclipse.jdt.core.prefs
  dev/build.featureStart/.settings/org.eclipse.jdt.ui.prefs
  dev/build.featureStart/bnd.bnd
  dev/build.featureStart/build.gradle
  dev/build.featureStart/fat/src/com/ibm/ws/simple/FATSuite.java
  dev/build.featureStart/fat/src/com/ibm/ws/simple/FeaturesStartTest.java
  dev/build.featureStart/publish/servers/features.start.server/bootstrap.properties
  dev/build.featureStart/publish/servers/features.start.server/server.xml
Labels: CLA Signed, noproductcode

#10824 disabled tests of login modules loaded from webapp and library within EAR
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/DerbyLoadFromAppServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/LoadFromWebAppLoginModule.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/first/FirstBean.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/ejb/second/SecondBean.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/loginmod/LoadFromAppLoginModule.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromAppServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10831 Remove incorrect trailing backtick from the README
  README.md
Labels: CLA Signed, noproductcode

#10833 Do not parse empty lines in oss_dependencies.maven
  .dependabot/config.yml
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
Labels: team:Zombie Apocalypse

#10826 update to add project as the group after service account token introspection
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed

#10058 Parallelize beanValidation-2.0, distributedMap-1.0, ejbLite-3.2
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbComponentMetadataDecorator-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbliteJNDI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.beanValidationCore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.ejbCore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.ejbLiteCore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-2.0/com.ibm.websphere.appserver.beanValidation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedMap-1.0/com.ibm.websphere.appserver.distributedMap-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbLite-3.2/com.ibm.websphere.appserver.ejbLite-3.2.feature
Labels: CLA Signed

#10836 Update ConfiguredTopicBean
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConfiguredTopicBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseConfiguredTopicServlet.java
Labels: CLA Signed, in:MicroProfile/Reactive, noproductcode

#10834 load test must allow PersistenceException due to transaction timeout
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/LoadTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10837 Issue10732-Java2SecurityPermissionIssue
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8014/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8014/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8294/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8294/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8461/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8461/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8950/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8950/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh9018/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh9018/web/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh9035/ejb/META-INF/permissions.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh9035/web/META-INF/permissions.xml
Labels: CLA Signed

#10733 Delay retrieval of context root
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/SimpleDeployedAppInfoBase.java
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/WebModuleInfoImpl.java
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfo.java
Labels: CLA Signed

#10781 10780 update open liberty.service file
  dev/build.image/packaging/debuild/scripts/openliberty@.service
  dev/build.image/packaging/rpmbuild/SOURCES/scripts/openliberty@.service
Labels: CLA Signed

#10695 mpjwt flexible header change
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MicroProfileJwtConfig.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
Labels: CLA Signed

#10818 Fix timestamp bug in ConsumerRecordTest
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordServlet.java
Labels: CLA Signed, noproductcode

#10803 Fixing test infrastructure to allow for accurate database tracing
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTestWithFailoverEnabled.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.jaas.fat/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DataSource.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DataSourceProperties.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ModifiableConfigElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/dsprops/Properties_postgresql.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10842 FIXIT - Correct test assertions
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FaceletVDLTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
Labels: CLA Signed, noproductcode, test bug

#10870 Revert "Fix timestamp bug in ConsumerRecordTest"
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordServlet.java
Labels: CLA Signed, noproductcode

#10683 Return InitialContext for empty name lookups on root level context
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/WSContext.java
Labels: CLA Signed

#10838 Ensure SSL passwords are not logged in oracle connection properties
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/PropertyService.java
  dev/com.ibm.ws.jdbc/test/com/ibm/ws/jdbc/internal/InternalTest.java
Labels: CLA Signed, team:Zombie Apocalypse

#10863 tie service account cache entry to config using it
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
Labels: CLA Signed, team:Security SSO

#10468 Ensure OL tests run properly in DB Rotation
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10851 Use Artifactory artifiact of MicroProfile Metrics 2.3 API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/bnd.bnd
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/ConcurrentGauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Counter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Counting.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/DefaultMetadata.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Gauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Histogram.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Metadata.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetadataBuilder.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Meter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Metered.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Metric.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetricFilter.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetricID.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetricRegistry.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetricType.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/MetricUnits.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Sampling.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/SimpleTimer.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Snapshot.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Tag.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/Timer.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/ConcurrentGauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/Counted.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/Gauge.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/Metered.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/Metric.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/RegistryType.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/SimplyTimed.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/Timed.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/annotation/package-info.java
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/src/org/eclipse/microprofile/metrics/package-info.java
Labels: CLA Signed

#10815 Update Yoko to avoid INITIALIZE error on Glassfish interop
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed, release bug

#10859 add SameSite attribute for SSO cookie metatype
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#10862 New messages for cookie SameSite attribute in WebContainer
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed, in:Web Components, team:Sirius

#10874 Fixed a java permission issue
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/WsBndServiceRefOverrideTestServer/server.xml
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#10864 small update to the new social service account handling error message
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#10758 Initial Commit: Transport SameSite Attribute support
  dev/com.ibm.ws.transport.http/bnd.bnd
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpChain.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpEndpointImpl.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Transport, team:Sirius

#10876 Add metatype properties for SameSite
  dev/com.ibm.ws.session/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#10885 translatable classProviderRef
  dev/com.ibm.ws.security.jaas.common/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Zombie Apocalypse

#10848 MicroProfile Metrics 2.3 TCK FAT
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.project
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/build.gradle
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/fat/resources/logging.properties
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/fat/src/com/ibm/ws/microprofile/metrics23/tck/launcher/FATSuite.java
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/fat/src/com/ibm/ws/microprofile/metrics23/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/servers/MetricsTCKServer/jvm.options
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/README.md
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/lib/hamcrest-all-1.3.jar
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/src/test/java/com/ibm/ws/microprofile/metrics/test/ArquillianLoadableExtension.java
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, noproductcode

#10872 Update mpHealth-2.2 API binaries to official release spec
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#10896 AsyncResponseImpl.initContinuation() throws NPE when Continuation is null
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
Labels: CLA Signed, in:JAX-RS, release bug, team:Wendigo West

#10698 Rework how kafka connector handles partition rebalancing
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/KafkaConsumerImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/impl/OffsetAndMetadataImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaConsumer.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/OffsetAndMetadata.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/.classpath
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/AckTracker.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/Batcher.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/CommittingPartitionTracker.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaConnectorException.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaInput.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/PartitionTracker.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/PartitionTrackerFactory.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/ThresholdCounter.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/ThresholdCounterImpl.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/test/src/com/ibm/ws/microprofile/reactive/messaging/kafka/CompletionStageMatcher.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/test/src/com/ibm/ws/microprofile/reactive/messaging/kafka/ThresholdCounterImplTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestConsumer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/KafkaPublisherVerification.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/PlaintextTests.java
Labels: CLA Signed

#10895 Fix Eclipse building error
  dev/build.featureStart/.classpath
Labels: CLA Signed, noproductcode

#10887 Add ibm:beta to metatype annotations
  dev/com.ibm.ws.bnd.annotations/src/com/ibm/ws/bnd/metatype/annotation/Ext.java
Labels: CLA Signed

#10917 Only run test with Java EE 8 features for full fat mode.
  dev/com.ibm.ws.wsat_fat/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Performance

#10640 Update EclipseLink 2.7.5 -> 2.7.6
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part01_fat/test-applications/olgh10310/src/com/ibm/ws/jpa/olgh10310/testlogic/JPATestOLGH10310Logic.java
Labels: CLA Signed

#10822 Issue #10820: Add ability to set a Cookie Attributes in RequestState
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/response/IResponseImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WebContainerRequestState.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: CLA Signed, in:Web Components, team:Sirius

#10817 Issue #10816 - Update Equinox to solve LinkageError
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/bnd.bnd
Labels: CLA Signed

#10886 Fix for Issue #10670: Improve Serviceability of JAX-RS handling of CDI proxy classes
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/ContextandCDI12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource2.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource3.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/contextandCDI/src/com/ibm/ws/jaxrs20/cdi12/fat/contextandCDI/TestResource4.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/InjectionUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/InjectionUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#10905 Enable trace to help debug quiesce errors
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.beanvalidation/bootstrap.properties
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#10713 User specified scheme in authorization header
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtApplicationAndSessionScopedClaimInjectionTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtBasicTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtConfigUsingBuilderTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/MPJwtJDKTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/actions/AuthHeaderPrefixRepeatActions.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/actions/AuthHeaderPrefixTypes.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtLoginConfig_VariationTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtMPConfigTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/fat/src/com/ibm/ws/security/mp/jwt/fat/sharedTests/MPJwtPropagationTests.java
  dev/com.ibm.ws.security.mp.jwt_fat/publish/shared/config/basicRSConfig_withAudience.xml
Labels: CLA Signed, team:Security SSO, test delivery

#10819 Add JSF Fat for Issue #10816
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#10916 Issue 10915: Update cert for WIM SSL AD test
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.ad.ssl/trust.jks
Labels: CLA Signed, noproductcode, team:Wendigo East

#10926 Eclipse settings updates
  dev/com.ibm.websphere.org.eclipse.microprofile.health.2.2/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.metrics.2.3/.classpath
  dev/com.ibm.ws.microprofile.metrics.2.3/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#10829 Same site session cookie
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SameSiteCookie.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionProperties.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/server.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/SessionAffinityManagerImpl.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpSession.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#10801 Issue 10277: Autonomical algorithm for calculating pollInterval.
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#10913 translatable error messages for classProviderRef
  dev/com.ibm.ws.security.jaas.common/resources/com/ibm/ws/security/jaas/common/internal/resources/JAASCommonMessages.nlsprops
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#10897 Report an error when an included file doesn't have server or client a…
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
Labels: CLA Signed, ID reviewed

#10906 Enable support of MPOT1.3 with MPRC1.4 and update TCK test to test this specific configuration
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpOpenTracing1.3-mpRestClient1.2.feature
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing13/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing13/tck/OpentracingRestClientTCKLauncher.java
Labels: CLA Signed

#10934 Issue 10933: Add retries during acme_fat Pebble startup
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#10919 Issue #10918: Clean up the Transport component SameSite code
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
Labels: CLA Signed, in:Transport, team:Sirius

#10928 Make sure that MP 3.3 features use up-to-date MP dependencies
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpFaultTolerance-metrics2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/com.ibm.websphere.appserver.microProfile-3.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.4/com.ibm.websphere.appserver.mpConfig-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-2.1/com.ibm.websphere.appserver.mpFaultTolerance-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.3/com.ibm.websphere.appserver.mpMetrics-2.3.feature
  dev/com.ibm.ws.microprofile.config.1.1.cdi/resources/com/ibm/ws/microprofile/config/cdi/resources/ConfigCDI.nlsprops
  dev/com.ibm.ws.microprofile.config.1.4.cdi/src/com/ibm/ws/microprofile/config14/cdi/Config14CDIExtension.java
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/servers/FaultTolerance21TCKServer/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiInEE8Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.cdi/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.ejb/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.multi.client.cdi/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.tolerateEE8/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.cdiPropsAndProviders/bootstrap.properties
Labels: CLA Signed

#10902 Add test variations for header("Expect", "100-continue")
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: CLA Signed, noproductcode

#10568 SameSite cookie at application level
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletResponse40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
Labels: CLA Signed, in:Web Components, team:Sirius

#10900 Rename com.ibm.websphere.appserver.jaxrs-2.0.properties to com.ibm.we…
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsMonitor-1.0/resources/l10n/com.ibm.websphere.appserver.jaxrsMonitor-1.0.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#10943 10941 update rpmdeb description
  dev/build.image/packaging/debuild/openliberty/debian/control
  dev/build.image/packaging/openliberty.spec.template
Labels: CLA Signed

#10866 Add VR template
  .github/ISSUE_TEMPLATE/vulnerability_report.md
Labels: CLA Signed

#10898 Add getSameSiteCookie for web/admin/feature app configuration
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/UserAuthenticationTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/BrowserStateTest.java
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/twitter/TwitterTokenServicesTest.java
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ReferrerURLCookieHandler.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/SSOCookieHelperImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/FormLoginAuthenticatorTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/ReferrerURLCookieHandlerTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/SSOAuthenticatorTest.java
Labels: CLA Signed

#10956 Re-introduced Fix timestamp bug in ConsumerRecordTest
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConfiguredTopicBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordServlet.java
Labels: CLA Signed, in:MicroProfile/Reactive, noproductcode

#10908 use proxy to redirect from app pid to class provider
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/LoginModuleInStandaloneResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.loginModuleInRA/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAServlet.java
  dev/com.ibm.ws.security.client/bnd.bnd
  dev/com.ibm.ws.security.jaas.common/bnd.bnd
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/internal/ClassProviderCoordinator.java
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/internal/ClassProviderProxy.java
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/internal/JAASLoginModuleConfigImpl.java
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/internal/ModuleConfig.java
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/config/internal/JAASLoginConfigImpl.java
  dev/com.ibm.ws.security.jaas.common_test/test/com/ibm/ws/security/jaas/common/internal/JAASLoginModuleConfigImplTestWithMock.java
Labels: CLA Signed, team:Zombie Apocalypse

#10959 Upgrade Microprofile OpenTracing TCK versions
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#10955 Logout translated incorrectly in German
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/internal/resources/OAuthMessages_de.nlsprops
  dev/com.ibm.ws.security.saml.sso/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.saml.sso/resources/com/ibm/ws/security/saml/sso20/internal/resources/SamlSso20Messages_de.nlsprops
Labels: CLA Signed

#10869 Upload retranslated files
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/accountManager/nls/de/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/clientAdmin/nls/de/messages.js
  dev/com.ibm.ws.security.openidconnect.server/resources/WEB-CONTENT/tokenManager/nls/de/messages.js
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#10911 CXF update
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/commons_text/AggregateTranslator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/commons_text/CharSequenceTranslator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/commons_text/EntityArrays.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/commons_text/LookupTranslator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/commons_text/StringEscapeUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/servlet/servicelist/FormattedServiceListWriter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/servlet/servicelist/UnformattedServiceListWriter.java
Labels: CLA Signed, in:Web Services, team:Bobcats

#10987 Assign dependency updates issues to Tom and Andy by default
  .dependabot/config.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10599 Avoid calling `toString()` when tracing Java dynamic proxies
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/util/BlockingList.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectorProperties.java
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/MetatypeGenerator.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/internal/impl/BaseTraceFormatterTest.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/SchemaSet.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/jmf/impl/JSMessageData.java
  dev/com.ibm.ws.repository.parsers/bnd.bnd
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/internal/ManifestHeaderProcessor.java
  dev/com.ibm.ws.security.authorization/src/com/ibm/ws/security/authorization/RoleSet.java
Labels: CLA Signed, in:Kernel/Bootstrap, team:Wendigo West

#10967 avoid hang resolution when hung-busy
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed, performance, team:Performance

#10976 enable tests of loading login module from top level jar of app
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/ConnectionManagerMBeanTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/DependantApplicationTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/DerbyLoadFromAppServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromAppServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#10980 Port SAML unit tests into repo
  dev/com.ibm.ws.security.saml.sso/.classpath
  dev/com.ibm.ws.security.saml.sso/bnd.bnd
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/SsoRequestTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/clockskew/NotBeforeTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/clockskew/NotOnOrAfterTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/clockskew/SessionNotOnOrAfterTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/error/ErrorHandlerImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/error/SamlExceptionTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/impl/ActivatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/impl/HandlerFactoryTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/AcsHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/AcsSecurityPolicyTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/AssertionValidatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/ResponseValidatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/SAMLMessageXMLSignatureSecurityPolicyRuleTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/SolicitedHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/UnsolicitedHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/acs/WebSSOConsumerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/binding/BasicMessageContextBuilderTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/binding/BasicMessageContextTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/binding/DebugMessageContextTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/common/CommonMockObjects.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/AssertionToSubjectTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/AuthenticatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/InitiatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SAMLRequestTAITest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SAMLResponseTAICushionTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SAMLResponseTAITest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SpCookieRetriverTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SsoConfigImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/SsoServiceImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/DumpDataTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/FileInfoTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/HashUtilsTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/MsgCtxUtilTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/RequestInfoTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/RequestUtilTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/SamlUtilTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/SignatureMethodsTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/UnsolicitedResponseCacheTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/UserDataTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/metadata/AcsDOMMetadataProviderTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/metadata/MetadataHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/metadata/SpMetadataBuilderTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/rs/RsSamlConfigImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/rs/RsSamlHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/slo/SLOHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/slo/SLOMessageContextUtilsTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/slo/SLOPostLogoutHandlerTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/slo/SLOPostLogoutPageBuilderTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/sp/SolicitedTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/sp/UnsolicitedTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/token/Saml20AttributeImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/token/Saml20TokenImplTest.java
  dev/com.ibm.ws.security.saml.sso/test/resources/IdpMetadata/IdpMetadata.xml
  dev/com.ibm.ws.security.saml.wab/.classpath
  dev/com.ibm.ws.security.saml.wab/bnd.bnd
  dev/com.ibm.ws.security.saml.wab/test/com/ibm/ws/security/saml/sso20/web/EndpointServicesTest.java
  dev/com.ibm.ws.security.saml.wab/test/com/ibm/ws/security/saml/sso20/web/EndpointServletTest.java
  dev/com.ibm.ws.security.saml.wab/test/com/ibm/ws/security/saml/sso20/web/RequestFilterTest.java
Labels: CLA Signed, team:Security SSO

#10949 Remove need for metrics-2.3-CDI autofeature... invoke/start bundle through main feature start-up
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpMetrics2.3-cdi1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.3/com.ibm.websphere.appserver.mpMetrics-2.3.feature
Labels: CLA Signed

#10968 Properly handle removal of REST stat metrics when an application is unloaded
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/ApplicationListener.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/impl/SharedMetricRegistries.java
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetrics.java
Labels: CLA Signed

#10944 add ltpa wait
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/InvalidTokenTest.java
  dev/com.ibm.ws.security.mp.jwt_fat_tck/fat/src/org/eclipse/microprofile/jwt/tck/container/jaxrs/RolesAllowedTest.java
Labels: CLA Signed, noproductcode

#10974 Security SSO changes to leverage SameSite cookie code
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/JavaScriptUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/web/JavaScriptUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/SelectionPageGenerator.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/utils/SocialWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/twitter/TwitterTokenServicesTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/SelectionPageGeneratorTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/utils/SocialWebUtilsTest.java
Labels: CLA Signed, team:Security SSO

#10951 10884 WebAdminConfig use the application sameSiteCookie configuration
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
Labels: CLA Signed

#10982 Update Yoko to avoid orb hang on shutdown
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed, release bug

#10971 Check for null entension info
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.java
Labels: CLA Signed

#10995 Issue10930 fix java2 security file normalization
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed

#10969 catch IO exception due to bundle uninstallation in generateXML
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Sirius

#10927 More fine tuned error handling on Log Close
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#11011 Revert "Security SSO changes to leverage SameSite cookie code"
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/JavaScriptUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/web/JavaScriptUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/SelectionPageGenerator.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/utils/SocialWebUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/twitter/TwitterTokenServicesTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/SelectionPageGeneratorTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/utils/SocialWebUtilsTest.java
Labels: CLA Signed

#10998 Allow postgres to participate in 2PC
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/demo/timers/DemoTimerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceTest.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerFactory.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11003 Do not set SameSite when Disabled
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ReferrerURLCookieHandler.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
Labels: CLA Signed
