Repository OpenLiberty/open-liberty, pull requests merged in 2020-07, with the labels that each got.

#12805 Apply org.infinispan.REPL_SYNC to remote Infinispan vendorProperties.
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
Labels: CLA Signed, team:Zombie Apocalypse

#12845 Revert "Issue #11858: Create JakartaEE jaspic-2.0 feature."
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.builtinAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.security-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-3.0/com.ibm.websphere.appserver.appSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/resources/l10n/io.openliberty.appSecurity-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedMap-1.0/com.ibm.websphere.appserver.distributedMap-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-1.1/com.ibm.websphere.appserver.jaspic-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-2.0/io.openliberty.jaspic-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-2.0/resources/l10n/io.openliberty.jaspic-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jndi-1.0/com.ibm.websphere.appserver.jndi-1.0.feature
  dev/com.ibm.websphere.appserver.spi.jaspic/bnd.bnd
  dev/com.ibm.ws.dynacache/bnd.bnd
  dev/com.ibm.ws.security.authentication.builtin/bnd.bnd
  dev/com.ibm.ws.security.authentication.tai/bnd.bnd
  dev/com.ibm.ws.security.jaas.common/bnd.bnd
  dev/com.ibm.ws.security.jaspic/bnd.bnd
  dev/com.ibm.ws.security.javaeesec.cdi/bnd.bnd
  dev/com.ibm.ws.security.javaeesec/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/io.openliberty.jakarta.jaspic.2.0/.classpath
  dev/io.openliberty.jakarta.jaspic.2.0/.gitignore
  dev/io.openliberty.jakarta.jaspic.2.0/.project
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/bnd.bnd
  dev/io.openliberty.jakarta.security.2.0/.classpath
  dev/io.openliberty.jakarta.security.2.0/.gitignore
  dev/io.openliberty.jakarta.security.2.0/.project
  dev/io.openliberty.jakarta.security.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.security.2.0/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties
Labels: CLA Signed

#12843 Issue 12576: Boulder with prune and improved cleanup
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeRevocationTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#12852 Enable EJB Legacy Fat Tests
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB2xInWARBean.war/resources/WEB-INF/ibm-ejb-jar-bnd.xmi
Labels: CLA Signed, noproductcode

#12849 add alwaysPassesTest to failoverTimers fat
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FATSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#12799 Add waitForStringInLog for SRVE0242I (/metrics initialization)
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/CustomAccessLogFieldsTest.java
Labels: CLA Signed, noproductcode

#12786 Move kernel filemonitor FAT into open liberty
  dev/com.ibm.ws.kernel.filemonitor_fat/.gitignore
  dev/com.ibm.ws.kernel.filemonitor_fat/bnd.bnd
  dev/com.ibm.ws.kernel.filemonitor_fat/build.gradle
  dev/com.ibm.ws.kernel.filemonitor_fat/delivery.sets
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/AbstractNotificationTest.java
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/FATSuite.java
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/FileMonitorTest.java
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/FileNotificationMBeanTest.java
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/MonitorReader.java
  dev/com.ibm.ws.kernel.filemonitor_fat/filemonitor_fat.bnd
  dev/com.ibm.ws.kernel.filemonitor_fat/publish/.gitignore
  dev/com.ibm.ws.kernel.filemonitor_fat/publish/features/monitoringPrintingFeature-1.0.mf
  dev/com.ibm.ws.kernel.filemonitor_fat/publish/servers/com.ibm.ws.kernel.filemonitor.server/bootstrap.properties
  dev/com.ibm.ws.kernel.filemonitor_fat/publish/servers/com.ibm.ws.kernel.filemonitor.server/server.xml
  dev/com.ibm.ws.kernel.filemonitor_fat/test-bundles/com.ibm.ws.kernel.filemonitor.monitor.test.bundle/src/com/ibm/ws/kernel/filemonitor/monitor/test/FileMonitorPrintingImplementation.java
  dev/com.ibm.ws.kernel.filemonitor_fat/test-bundles/com.ibm.ws.kernel.filemonitor.monitor.test.bundle/src/com/ibm/ws/kernel/filemonitor/monitor/test/FileMonitorRegistrationHandler.java
  dev/com.ibm.ws.kernel.filemonitor_fat/test.bundle.bnd
Labels: CLA Signed, noproductcode

#12858 Issue #12846: Revert "Revert "Issue #11858: Create JakartaEE jaspic-2…
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.builtinAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.security-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-3.0/com.ibm.websphere.appserver.appSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/resources/l10n/io.openliberty.appSecurity-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedMap-1.0/com.ibm.websphere.appserver.distributedMap-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-1.1/com.ibm.websphere.appserver.jaspic-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-2.0/io.openliberty.jaspic-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-2.0/resources/l10n/io.openliberty.jaspic-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jndi-1.0/com.ibm.websphere.appserver.jndi-1.0.feature
  dev/com.ibm.websphere.appserver.spi.jaspic/bnd.bnd
  dev/com.ibm.ws.dynacache/bnd.bnd
  dev/com.ibm.ws.security.authentication.builtin/bnd.bnd
  dev/com.ibm.ws.security.authentication.tai/bnd.bnd
  dev/com.ibm.ws.security.jaas.common/bnd.bnd
  dev/com.ibm.ws.security.jaspic/bnd.bnd
  dev/com.ibm.ws.security.javaeesec.cdi/bnd.bnd
  dev/com.ibm.ws.security.javaeesec/bnd.bnd
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
  dev/io.openliberty.jakarta.jaspic.2.0/.classpath
  dev/io.openliberty.jakarta.jaspic.2.0/.gitignore
  dev/io.openliberty.jakarta.jaspic.2.0/.project
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jaspic.2.0/bnd.bnd
  dev/io.openliberty.jakarta.security.2.0/.classpath
  dev/io.openliberty.jakarta.security.2.0/.gitignore
  dev/io.openliberty.jakarta.security.2.0/.project
  dev/io.openliberty.jakarta.security.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.security.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.security.2.0/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties
Labels: team:Wendigo East

#12762 Upgrade to Eclipse Transformer
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/settings.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/repos.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
  dev/wlp-jakartaee-transform/bnd.bnd
  dev/wlp-jakartaee-transform/bnd.overrides
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
Labels: CLA Signed

#12575 Add servlet version check & javax, jakarta check in WebApp Handle Types Method
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
Labels: CLA Signed, in:Web Components, team:Sirius

#12862 enable additional trace for defect 275542
  dev/com.ibm.ws.app.manager.wab.installer_fat/publish/servers/com.ibm.ws.app.manager.wab.installer/bootstrap.properties
Labels: CLA Signed, noproductcode

#12847 Removed unsupport property from the java doc
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/wsspi/security/tai/TrustAssociationInterceptor.java
Labels: CLA Signed

#12370 Update xpoweredby header value for the servlet-5.0 feature
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.client/bnd.bnd
  dev/com.ibm.ws.security.saml.sso/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/osgi/WebContainerConstants.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletResponse40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, jakartaEE, team:Sirius

#12802 Address messaging.open_comms_fat bucket failure
  dev/com.ibm.ws.messaging.open_comms_fat/fat/src/com/ibm/ws/messaging/open_comms/fat/FeatureUpdate.java
Labels: CLA Signed, noproductcode

#12844 Add support for the creation.retry.seconds option to the outgoing Kafka connector
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaAdapterFactory.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutgoingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigIncomingBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigOutgoingBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigTest.java
Labels: CLA Signed, ID reviewed

#12877 update SVT focals
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed, noproductcode

#12869 Review updates from PR #12804
  dev/com.ibm.ws.cdi.annotations_fat/fat/src/com/ibm/ws/cdi12/fat/tests/AnnotationsTests.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.api_fat/test-applications/alterableContextApp.war/src/com/ibm/ws/cdi12/alterablecontext/test/AlterableContextTestServlet.java
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointAsParam.war/src/com/ibm/ws/fat/cdi/injectInjectionPointParam/InjectInjectionPointAsParamServlet.java
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointAsParam.war/src/com/ibm/ws/fat/cdi/injectInjectionPointParam/TestBean.java
  dev/com.ibm.ws.cdi.api_fat/test-applications/injectInjectionPointBeansXML.war/src/com/ibm/ws/fat/cdi/injectInjectionPointBeansXML/InjectInjectionPointBeansXMLServlet.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatTests.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: CLA Signed, noproductcode

#12880 Get things building in eclipse again
  dev/cnf/resources/bnd/repos.bnd
  dev/com.ibm.ws.kernel.filemonitor_fat/.classpath
  dev/com.ibm.ws.kernel.filemonitor_fat/.project
  dev/com.ibm.ws.kernel.filemonitor_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.kernel.filemonitor_fat/.settings/org.eclipse.jdt.core.prefs
  dev/wlp-jakartaee-transform/.settings/bndtools.core.prefs
Labels: CLA Signed, team:Performance

#12879 Issue 12029: Add additional Managed Beans FAT
  dev/com.ibm.ws.managedbeans_fat/.classpath
  dev/com.ibm.ws.managedbeans_fat/bnd.bnd
  dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/FATSuite.java
  dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansCdiTest.java
  dev/com.ibm.ws.managedbeans_fat/publish/servers/ManagedBeansCdiServer/bootstrap.properties
  dev/com.ibm.ws.managedbeans_fat/publish/servers/ManagedBeansCdiServer/server.xml
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanEjbWeb.war/src/com/ibm/ws/managedbeans/fat/mb/ejb/web/ManagedBeanEjbServlet.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInjectionWeb.war/src/com/ibm/ws/mb/injection/ManagedBeansInjectionServlet.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInjectionWeb.war/src/com/ibm/ws/mb/injection/TestCdiBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInjectionWeb.war/src/com/ibm/ws/mb/injection/TestManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorApp.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstruct/AroundConstructInterceptor.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstruct/AroundConstructManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstruct/AroundConstructMethodBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstruct/AroundConstructMethodInterceptor.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ChainExceptionInterceptor1.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ChainExceptionInterceptor2.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ChainExceptionInterceptor3.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ChainExceptionManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ConstructorException.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ExceptionInterceptor.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/ExceptionManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/aroundconstructexception/InterceptorException.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/chainaroundconstruct/ChainInterceptor1.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/chainaroundconstruct/ChainInterceptor2.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/chainaroundconstruct/ChainInterceptor3.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/chainaroundconstruct/ChainManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/injection/InjectedManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/paramaroundconstruct/ParamAroundConstructInterceptor.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/paramaroundconstruct/ParamAroundConstructManagedBean.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanInterceptorWeb.war/src/com/ibm/ws/mb/interceptor/web/ManagedBeansInterceptorServlet.java
  dev/com.ibm.ws.managedbeans_fat/test-applications/ManagedBeanWeb.war/src/com/ibm/ws/managedbeans/fat/mb/web/ManagedBeanServlet.java
Labels: CLA Signed, in:Java EE Platform, noproductcode, team:Blizzard, test delivery

#12888 Enable JDK logging for kerberos auth
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/db2/JDBCKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/bootstrap.properties
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#12886 Move the WCServerTest to run in FULL Mode
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#12882 Issue #12881: Move managedBeans-2.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.managedBeansWar-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.ejb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.managedBeansCore-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/com.ibm.websphere.appserver.managedBeans-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed, in:Java EE Platform, team:Blizzard

#12890 Issue #12101: Enable Servlet 31 CDI tests for Jakarta EE9 RepeatTests
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIBeanInterceptorServletTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIListenersTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDINoInjectionTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIServletFilterListenerDynamicTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIServletFilterListenerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIServletInterceptorTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDITests.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIUpgradeHandlerTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#12867 Issue 12865 - Fix cloud starter ApplicationStarted event firing
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootHandler.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.support.shutdown/src/com/ibm/ws/springboot/support/shutdown/ApplicationContextCloser.java
  dev/com.ibm.ws.springboot.support.version22.test.app/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ApplicationStartedEventTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Signed

#11742 Download built from source jars from wasliberty-source-built-maven-local
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/cnf/resources/bnd/repos.bnd
  dev/settings.gradle
Labels: CLA Signed, team:Continuous Delivery

#12903 Upgrade from jakarta concurrency 2.0.0-RC1 to RC2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-2.0.feature
Labels: team:Zombie Apocalypse

#12902 Split JDBC metatype into separate bundle so it can be included by non-auto features
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.0/com.ibm.websphere.appserver.jdbc-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.1/com.ibm.websphere.appserver.jdbc-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.2/com.ibm.websphere.appserver.jdbc-4.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.3/com.ibm.websphere.appserver.jdbc-4.3.feature
  dev/com.ibm.ws.jdbc.metatype/.classpath
  dev/com.ibm.ws.jdbc.metatype/.project
  dev/com.ibm.ws.jdbc.metatype/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc.metatype/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc.metatype/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc.metatype/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc.metatype/bnd.bnd
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#12932 Include oss_source_dependencies.maven in dependabot pom.xml
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
Labels: CLA Signed, team:Continuous Delivery

#12887 Reduce time spent attempting to connect to each remote docker-host svc
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, in:Test Infrastructure, noproductcode, team:Zombie Apocalypse

#12917 Issue 12911: Skip tests on specific OS/JDK
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#12922 gRPC FAT improvements
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesTests.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#12827 ExceptionsSubresourcesTest fails on Sun JDK 8
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.providers/bootstrap.properties
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#12896 Remove traces from SameSite tests as they are not necessary right now.
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#12933 Issue #12891: Fix spelling of initializes in WebContainer
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/wsspi/webcontainer31/WCCustomProperties31.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Signed, in:Web Components, team:Sirius

#12928 Issue 12924: Add FFDC in create/update cert
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#12876 Support IBMRestServlet in JAX-RS 3.0
  dev/build.image/scripts/Liberty- server remote debug.launch
  dev/build.image/scripts/Liberty-FAT remote debug.launch
  dev/com.ibm.websphere.javaee.jaxrs.2.1/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
  dev/com.ibm.ws.jaxrs.2.1.common/resources/META-INF/services/javax.ws.rs.ext.RuntimeDelegate
  dev/com.ibm.ws.jaxrs.2.1.common/resources/META-INF/services/javax.ws.rs.sse.SseEventSource$Builder
  dev/com.ibm.ws.jaxrs.2.1.common/resources/META-INF/services/javax.ws.rs.sse.SseEventSource.Builder
  dev/io.openliberty.org.jboss.resteasy.common/.classpath
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resource/io/openliberty/org/jboss/resteasy/common/nls/JAXRSServer.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/src/com/ibm/websphere/jaxrs/server/IBMRestServlet.java
  dev/io.openliberty.org.jboss.resteasy.common/src/com/ibm/websphere/jaxrs/server/package-info.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/package-info.java
Labels: CLA Signed, ID reviewed, in:JAX-RS, team:Wendigo West

#12572 9214 Warn user about javaee and jakartaee feature compatibility conflicts
  dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/EECompatibilityTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.compatibility.needsNewEe-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.compatibility.newEe-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.compatibility/.gitignore
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.compatibility/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.compatibility/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.compatibility/src/test/compatibility/Activator.java
  dev/com.ibm.ws.kernel.feature_fat/test.compatibility.newEe.bnd
Labels: CLA Signed, ID reviewed, L2 Reviewed, jakartaEE, team:OSGi Infrastructure

#12837 Enforce consistent server config to allow tests running in different orders
  dev/com.ibm.ws.jca_fat_classloading/fat/src/com/ibm/ws/jca/fat/classloading/JCAClassLoadingTest.java
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testLoadResourceAdapterClassFromSingleApp_server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#12925 update rpm/deb build scripts
  dev/build.image/packaging/buildDEB.sh
  dev/build.image/packaging/buildOsNativePackages.sh
  dev/build.image/packaging/buildRPM.sh
Labels: CLA Signed

#12761 Oracle container wait strategy
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.databases/src/componenttest/topology/database/container/OracleContainer.java
  dev/fattest.databases/src/componenttest/topology/database/container/SQLServerContainer.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#12927 Fix NPE in AcmeHistory file
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeHistory.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#12948 Update README.md- Fix Getting Started instructions
  README.md
Labels: CLA Signed, noproductcode

#12763 Improve performance when no tracer is found
  dev/com.ibm.ws.opentracing.1.3/bnd.bnd
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/AppStateListener.java
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingContext.java
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingService.java
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
Labels: CLA Signed

#12814 Handle missing remotablepartition table for sqlserver
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JPAPersistenceManagerImpl.java
Labels: CLA Signed

#12918 JSON access log test: retry reading file if empty on first read
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/CustomAccessLogFieldsTest.java
Labels: CLA Signed, noproductcode

#12919 Update web app security same site test
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#12964 Revert "Include oss_source_dependencies.maven in dependabot pom.xml"
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
Labels: CLA Signed

#12962 Revert "Download built from source jars from wasliberty-source-built-maven-local"
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/cnf/resources/bnd/repos.bnd
  dev/settings.gradle
Labels: CLA Signed

#12884 Add io.openliberty.jakarta.jms.3.0 project
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.jms.3.0/.classpath
  dev/io.openliberty.jakarta.jms.3.0/.project
  dev/io.openliberty.jakarta.jms.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jms.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jms.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jms.3.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jms.3.0/bnd.bnd
  dev/io.openliberty.jakarta.jms.3.0/bnd.overrides
Labels: CLA Signed

#12921 Updated fat buckets with the new guidelines for OL fat buckets
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPCdiTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#12906 Issue 12822: Add custom HTTP connect and read timeouts for acmeCA
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/util/AcmeConstants.java
  dev/com.ibm.ws.security.acme/src/org/shredzone/acme4j/connector/HttpConnector.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/internal/AcmeConfigTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/AcmeCA.java
Labels: CLA Signed, ID reviewed, team:Core Security, team:Wendigo East

#12958 Improve performance when no tracer is found
  dev/com.ibm.ws.opentracing.1.1/bnd.bnd
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/AppStateListener.java
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingContext.java
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
  dev/com.ibm.ws.opentracing.1.2/bnd.bnd
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/AppStateListener.java
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingContext.java
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
  dev/com.ibm.ws.opentracing/bnd.bnd
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/AppStateListener.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingContext.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
Labels: CLA Signed

#12960 [#12875] Ensure resources are invoked when no servlet is in web.xml
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#12973 Revert "Update to Gradle 6.5"
  dev/.gradle-wrapper/gradle-wrapper.jar
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/gradlew
  dev/gradlew.bat
  dev/io.openliberty.jakarta.jaxrs.3.0/.classpath
  dev/io.openliberty.jakarta.jaxrs.3.0/.settings/org.eclipse.core.resources.prefs
Labels: CLA Signed, noproductcode, team:Continuous Delivery

#12956 Issue 12951: Add update cert error message
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
Labels: CLA Signed, team:Core Security, team:Wendigo East

#12959 Remove acronyms from feature descriptionsfor Jakarta
  dev/com.ibm.websphere.appserver.features/visibility/public/el-4.0/resources/l10n/com.ibm.websphere.appserver.el-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-3.0/resources/l10n/com.ibm.websphere.appserver.jsp-3.0.properties
Labels: CLA Signed, in:Web Components, team:Sirius

#12976 [#12975] Authorization support/tests for JAX-RS 3.0 / RESTEasy impl
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-3.0/com.ibm.websphere.appserver.jaxrs-3.0.feature
  dev/com.ibm.ws.jaxrs.2.1_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/securitycontext/JAXRS21SecurityContextTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/uriInfo/UriInfoTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/publish/servers/com.ibm.ws.jaxrs21.fat.uriInfo/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat/test-applications/jaxrs21uriInfo/src/com/ibm/ws/jaxrs21/fat/uriInfo/TestClient.java
  dev/com.ibm.ws.jaxrs.2.1_fat/test-applications/jaxrs21uriInfo/src/com/ibm/ws/jaxrs21/fat/uriInfo/TestResource.java
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#12957 Enable dupxid test
  dev/com.ibm.ws.transaction.cloudsim_fat/.classpath
  dev/com.ibm.ws.transaction.cloudsim_fat/bnd.bnd
  dev/com.ibm.ws.transaction.cloudsim_fat/build.gradle
  dev/com.ibm.ws.transaction.cloudsim_fat/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/DupXidTest.java
  dev/com.ibm.ws.transaction.cloudsim_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/features/cloudtxfat-1.0.mf
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID001/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID001/resources/security/defaultKey.jks
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID001/resources/security/defaultTrust.jks
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID001/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID002/jvm.options
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID002/resources/security/defaultKey.jks
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID002/resources/security/defaultTrust.jks
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/servers/com.ibm.ws.transaction_DUPXID002/server.xml
  dev/com.ibm.ws.transaction.cloudsim_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/DupXidServlet.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/cloudtx/src/com/ibm/ws/cloudtx/ut/util/CloudTestServletBase.java
  dev/com.ibm.ws.transaction.cloudsim_fat/test-bundles/cloudtx/src/com/ibm/ws/cloudtx/ut/util/LastingXAResourceImpl.java
  dev/com.ibm.ws.transaction.core_fat/build.gradle
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/HeuristicsDBTranlogTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/HeuristicsTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/SimpleDBTranlogTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/TransactionScopedTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/TransactionalTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/XADBTranlogTest.java
  dev/com.ibm.ws.transaction.core_fat/fat/src/com/ibm/ws/transaction/test/XATest.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/HeuristicsServlet.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/XAServlet.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transactional/src/com/ibm/ws/transactional/web/TransactionalTestServlet.java
Labels: CLA Signed, noproductcode

#12977 Issue #12966: ejbHome-4.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbliteJNDI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/com.ibm.websphere.appserver.ejbHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/com.ibm.websphere.appserver.ejbHome-4.0_zh_TW.properties
  dev/com.ibm.ws.ejbcontainer.legacy_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.legacy_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SFLocalTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SLLocalTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.sll/.gitignore
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.sll/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.sll/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB2XLocalSpecWeb.war/src/com/ibm/ejb2x/base/spec/sfl/web/SFLocalImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB2XLocalSpecWeb.war/src/com/ibm/ejb2x/base/spec/sll/web/SLLocalImplContextServlet.java
Labels: CLA Signed, L2 ReviewNotRequired, in:EJB Container, team:Blizzard

#12968 Replace deprecated Apache hostname verifier methods
  dev/com.ibm.ws.security.common.jsonwebkey/bnd.bnd
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OAuthClientHttpUtil.java
Labels: CLA Signed, release bug, team:Security SSO

#12872 adding beta feature error message
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
Labels: CLA Signed, L2 Reviewed

#12841 Add rules for TLD transformations
  dev/wlp-jakartaee-transform/rules/jakarta-tld.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, CTS Required, in:Web Components, team:Sirius

#12897 Modify App Name to invalid value app wont restart when renamed back t…
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ResolveFileAction.java
Labels: CLA Signed, release bug

#12952 Make classloader element parent first
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.classloading/resources/OSGI-INF/metatype/classloader.xml
Labels: CLA Signed

#12931 EJB: Enable Injection XML Tests
  dev/com.ibm.ws.ejbcontainer.injection_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.injection_fat/fat/src/com/ibm/ws/ejbcontainer/injection/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/fat/src/com/ibm/ws/ejbcontainer/injection/fat/tests/InjectionXMLTest.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/publish/servers/com.ibm.ws.ejbcontainer.injection.fat.mdbserver/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.injection_fat/publish/servers/com.ibm.ws.ejbcontainer.injection.fat.mdbserver/server.xml
  dev/com.ibm.ws.ejbcontainer.injection_fat/publish/servers/com.ibm.ws.ejbcontainer.injection.fat.server/.gitignore
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJEJBXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejbx/SLSTestFieldBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJEJBXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejbx/SLSTestMethodBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejb/SuperCompSFEnvInjectBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejb/SuperCompSLEnvInjectBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejb/SuperSFEnvInjectBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXBean.jar/src/com/ibm/ws/ejbcontainer/injection/xml/ejb/SuperSLEnvInjectBean.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXWeb.war/src/com/ibm/ws/ejbcontainer/injection/xml/web/BasicSLEJBInjectionServlet.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXWeb.war/src/com/ibm/ws/ejbcontainer/injection/xml/web/BasicSLRemoteEnvInjectionServlet.java
Labels: CLA Signed, noproductcode

#12861 Modify test to improve performance
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/HungRequestTiming.java
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/SlowRequestTiming.java
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java
  dev/com.ibm.ws.request.timing_fat/publish/files/server_hungRequestThreshold2.xml
  dev/com.ibm.ws.request.timing_fat/publish/files/server_hungRequestThreshold3.xml
  dev/com.ibm.ws.request.timing_fat/publish/files/server_sampleRate0.xml
  dev/com.ibm.ws.request.timing_fat/publish/files/server_slowRequestThreshold1.xml
  dev/com.ibm.ws.request.timing_fat/test-applications/jdbcTestPrj_3/src/com/ibm/ws/request/timing/TestJDBC.java
Labels: CLA Signed, noproductcode

#13002 Cleanup of new projects
  dev/com.ibm.ws.logstash.collector_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jacc.2.0/.project
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/BasicTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/WebSocket11Test.java
Labels: CLA Signed, noproductcode, team:Performance

#12949 Update Krb5LoginModuleWrapper to work with IBM JDK 8
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/db2/KerberosPlatformRule.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/db2fat/src/db2/web/JDBCKerberosTestServlet.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
Labels: CLA Signed, team:Zombie Apocalypse

#12990 Promote concurrent-2.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/com.ibm.websphere.appserver.concurrent-2.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#12950 Add buildID to liberty-versions.props
  dev/cnf/build.gradle
Labels: CLA Signed, noproductcode

#12987 Issue #12934: Move ejbLite-4.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.ejbCore-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.ejbLiteCore-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/com.ibm.websphere.appserver.ejbHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbLite-4.0/com.ibm.websphere.appserver.ejbLite-4.0.feature
Labels: CLA Signed, in:EJB Container, team:Blizzard

#12992 Issue 12991: Additional java version for AcmeFatUtils
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#12901 Add new <kerberos> config element
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/db2/JDBCKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/SecureAction.java
  dev/com.ibm.ws.security.auth.data.common/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.auth.data.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/websphere/security/auth/data/AuthData.java
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/websphere/security/auth/data/AuthDataProvider.java
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/ws/security/auth/data/internal/AuthDataImpl.java
  dev/com.ibm.ws.security.auth.data.common/test/com/ibm/websphere/security/auth/data/AuthDataProviderTest.java
  dev/com.ibm.ws.security.auth.data/test/com/ibm/websphere/security/auth/data/WSPrincipalMappingLoginModuleTest.java
  dev/com.ibm.ws.security.jca/bnd.bnd
  dev/com.ibm.ws.security.jca/src/com/ibm/ws/security/jca/internal/AuthDataServiceImpl.java
  dev/com.ibm.ws.security.kerberos.auth/bnd.bnd
  dev/com.ibm.ws.security.kerberos.auth/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.kerberos.auth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.kerberos.auth/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/KerberosService.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/TraceConstants.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/package-info.java
  dev/com.ibm.ws.security.kerberos.java8/resources/com/ibm/ws/security/kerberos/internal/resources/KerberosMessages.nlsprops
  dev/com.ibm.ws.security.spnego/bnd.bnd
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.spnego/resources/com/ibm/ws/security/spnego/internal/resources/SpnegoMessages.nlsprops
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoService.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnegoConfigImpl.java
Labels: CLA Signed, L2 Reviewed, team:Zombie Apocalypse

#13007 Issue 13003: Change sleep to force renew, update method name
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#13009 Issue 11916: Beta Bean Validation 3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.beanValidationCDI-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.beanValidationCore-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-3.0/io.openliberty.beanValidation-3.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#12997 Add authentication=ActiveDirectoryMSI option to sqlserver metatype
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#13008 Additional FAT coverage for appsWriteJson
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigBootstrapTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigTest.java
  dev/com.ibm.ws.logging.json_fat/test-applications/LogstashApp/src/com/ibm/logs/LogServlet.java
Labels: CLA Signed, noproductcode

#13006 13004: Update testContinuationFrameAfterDataFrame
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, noproductcode

#13034 Add msg ID to SPNEGO_CONFLICTING_SETTINGS_CWWKS4323E
  dev/com.ibm.ws.security.spnego/resources/com/ibm/ws/security/spnego/internal/resources/SpnegoMessages.nlsprops
Labels: CLA Signed, team:Zombie Apocalypse

#13035 Issue #12934: Enable EJB CMD auto feature for EJB 4.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbComponentMetadataDecorator-1.0.feature
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#13026 Issue #12029: EE9 Managed Bean FAT with EJB and CDI
  dev/com.ibm.ws.managedbeans_fat/bnd.bnd
  dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansCdiTest.java
  dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansEjbTest.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#12981 Move websocket-2.0 feature to beta
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.0/io.openliberty.websocket-2.0.feature
Labels: CLA Signed, in:Transport, team:Sirius

#13029 Issue #12934: Rename ejbLite-4.0 for Jakarta EE 9
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/io.openliberty.ejbHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbHome-4.0/resources/l10n/io.openliberty.ejbHome-4.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbLite-4.0/io.openliberty.ejbLite-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ejbLite-4.0/resources/l10n/io.openliberty.ejbLite-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/io.openliberty.managedBeans-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/resources/l10n/io.openliberty.managedBeans-2.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed, ID review not needed, in:EJB Container, team:Blizzard

#13038 Enable WebAppSecurity SameSite Test for Jakarta EE9
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#13023 Jakarta Concurrency with Jakarta Enterprise Beans
  dev/com.ibm.ws.concurrent_fat_ejb/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_ejb/build.gradle
  dev/com.ibm.ws.concurrent_fat_ejb/fat/src/com/ibm/ws/concurrent/ejb/fat/ConcurrentEJBTest.java
  dev/com.ibm.ws.concurrent_fat_ejb/publish/servers/com.ibm.ws.concurrent.fat.ejb/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#12893 Change logging.json_fat tests to check trace for server config update …
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigBootstrapTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigTest.java
Labels: CLA Signed, noproductcode

#13053 switch concurrency config updates test bucket to Jakarta
  dev/com.ibm.ws.concurrent_fat_config/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_config/publish/servers/concurrent.config.fat/server.xml
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/ejb/EEConcurrencyUtilsStatelessBean.java
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/web/EEConcurrencyUtilsFATServlet.java
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/web/IncrementTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#13058 Ensure a class can be both an Application subclass and a resource
  dev/io.openliberty.jaxrs.3.0_fat/.classpath
  dev/io.openliberty.jaxrs.3.0_fat/.project
  dev/io.openliberty.jaxrs.3.0_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.3.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.3.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.3.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.3.0_fat/bnd.bnd
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/AppAndResourceTest.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/FATSuite.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResource.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResourceTestServlet.java
  dev/io.openliberty.jaxrs.3.0_fat/publish/servers/appandresource/bootstrap.properties
  dev/io.openliberty.jaxrs.3.0_fat/publish/servers/appandresource/server.xml
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.ext.Providers
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/JAXRSServer.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#13040 Add debug when context root fail to map webapp
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/VirtualHost.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/DynamicVirtualHost.java
Labels: CLA Signed

#12648 12609: Add grpc server config tests
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceSupportTests.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.bad.target.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.grpc.element.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.grpc.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.invalid.max.msg.size.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.small.max.msg.size.and.specific.target.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.small.max.msg.size.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServerOnly/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServerOnly/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/InvalidService.war/src/com/ibm/ws/grpc/fat/invalid/service/InvalidServlet.java
Labels: CLA Signed, noproductcode

#13047 Change date formatting for access log fields
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/AccessLogData.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/CustomAccessLogFieldsTest.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogCurrentTime.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogStartTime.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/source/AccessLogSource.java
Labels: CLA Signed

#13042 Add support for configDropins/defaults folder
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
Labels: CLA Signed

#13081 Changes to com.ibm.ws.app.manager.wab.installer_fat
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/FATSuite.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/publish/servers/com.ibm.ws.app.manager.wab.installer/bootstrap.properties
Labels: CLA Signed, noproductcode

#13076 Issue #13066: Added cdi-ejb and cdi-jndi auto features for jakarta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-ejb4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-jndi1.0.feature
  dev/com.ibm.ws.cdi.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.cdi.ejb.common/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.cdi_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.cdi_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.cdi_fat/fat/src/com/ibm/ws/ejbcontainer/cdi/fat/EJBxCDITest.java
  dev/com.ibm.ws.ejbcontainer.cdi_fat/test-applications/EJB31JCDIWeb.war/src/com/ibm/ws/ejbcontainer/cdi/jcdi/web/InterceptorIntegrationServlet.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, in:EJB Container, team:Blizzard

#13085 Add Concurrent-2.0 to jakartaee-9 - and sort
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/com.ibm.websphere.appserver.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed

#13084 [13083] JSON-B provider for RESTEasy Prototype
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/ClassSubResTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FormBehaviorTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PackageJsonBTestNoFeature.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PatchTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/SubResourceTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.subResourceTest/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/classSubResApp/src/jaxrs21/fat/classSubRes/ClassSubResTestApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/formApp/src/jaxrs21/fat/form/FormResource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbCharsetApp/src/jaxrs21/fat/jsonbcharset/Resource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/Resource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbapp/src/jaxrs21/fat/jsonb/JsonBPOJOResource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbapp/src/jaxrs21/fat/jsonb/JsonBTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/mutableHeadersApp/src/jaxrs21/fat/mutableHeaders/Resource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/patchapp/src/jaxrs21/fat/patch/PatchTestApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/providerPriorityApp/src/jaxrs21/fat/providerPriority/ProviderPriorityTestApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/subResourceApp/src/jaxrs21/fat/subresource/SubResourceTestServlet.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResourceTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.ext.Providers
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/providers/JsonBProvider.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/providers/JsonBProviderDelegator.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/providers/package-info.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#12085 fix decodeUrlPlusSign property
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/files/decodeUrlPlusSign_false.server.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/TestServlet31.war/resources/noplus sign.html
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/TestServlet31.war/resources/plus+sign.html
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/DynamicVirtualHost.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#13070 Add eeCompatible-9.0 feature to the el-4.0 public feature
  dev/com.ibm.websphere.appserver.features/visibility/public/el-4.0/com.ibm.websphere.appserver.el-4.0.feature
Labels: CLA Signed, in:Web Components, team:Sirius

#13051 Issue #12312: Ensure ServerUser is set to LocalSystem
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed, release bug

#13005 Port cdi wsoc tests
  dev/io.openliberty.wsoc.internal_fat/.classpath
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/CdiTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/SessionTest.java
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/AnnotatedCDI1ServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/AnnotatedCDIClientEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/AnnotatedCDIIdleTimeoutServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/AnnotatedFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/AnnotatedFieldInjectionServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ClientTestServletCDI.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CodedServerEndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CodedServerEndpointConfigCDI12.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CodedServerEndpointConfigCDI20.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/Counter.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CounterApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CounterApplicationScoped2.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CounterApplicationScoped20.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CounterDependentScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/CounterSessionScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ExtendedCDIClientEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ExtendedServerApplicationConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/InterceptMeBinding.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/InterceptMeInterceptor.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ProducerBean.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ProgrammaticExtendCDIServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ProgrammaticExtendCDIServerCDI20EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ProgrammaticExtendCDIServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/SimpleServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/SimpleWebSocketBean.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/resources/dojo.js
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/resources/index.html
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/ContextConfigurator.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/ContextServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/Session5ServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/SessionCloseServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/SessionMessageHandlerErrorServerEP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/context.war/src/context/war/SessionServerEP.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#12250 Fix for jakarta feature name change
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, noproductcode

#13079 Add client streaming test to grpc microservices fvt framework
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamReplyA.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamReplyAOrBuilder.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamRequestA.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamRequestAOrBuilder.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/resources/proto/ProducerStore.proto
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerServiceRestClient.java
Labels: CLA Signed, noproductcode

#13025 Remove ibm:beta for LG-265 and LG-286 features
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logstash.collector/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#13095 Issue #13094: Allow MDB method names to start with "ejb"
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/jitdeploy/EJBWrapper.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#13074 context serialization bucket with Jakarta
  dev/com.ibm.ws.context_fat_serialization/bnd.bnd
  dev/com.ibm.ws.context_fat_serialization/build.gradle
  dev/com.ibm.ws.context_fat_serialization/fat/src/test/context/serialization/ContextServiceSerializationTest.java
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, team:Zombie Apocalypse

#13102 Dynamically import com.sun JAXB impl classes in JAX-RS 3.0 / RESTEasy prototype
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: in:JAX-RS, team:Wendigo West

#13061 Added genericType null fix to mpConfig converter
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/converters/ListConverter.java
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/converters/SetConverter.java
  dev/com.ibm.ws.microprofile.config.1.2/test/src/com/ibm/ws/microprofile/config12/test/converters/ConversionUtil.java
  dev/com.ibm.ws.microprofile.config.1.2/test/src/com/ibm/ws/microprofile/config12/test/converters/ListConversionTest.java
  dev/com.ibm.ws.microprofile.config.1.2/test/src/com/ibm/ws/microprofile/config12/test/converters/SetConversionTest.java
Labels: CLA Signed, in:MicroProfile/Config

#12971 Fix performance issue with annotation caching for WABs
  dev/com.ibm.ws.anno/bnd.bnd
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/classsource/internal/ClassSourceImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/ClassInfoCache.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoStoreFactoryImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/service/internal/AnnotationServiceImpl_Service.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsImpl_PolicyData.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsImpl_Scanner.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsImpl_Targets.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/util/internal/UtilImpl_BidirectionalMap.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/util/internal/UtilImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/classsource/internal/ClassSourceImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/classsource/internal/ClassSourceImpl_MappedContainer.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/ClassInfoCacheImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/InfoStoreFactoryImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/service/internal/AnnotationCacheServiceImpl_Service.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/internal/TargetCacheImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/AnnotationTargetsImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/AnnotationTargetsImpl_Targets.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/delta/internal/UtilImpl_BidirectionalMapDelta.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_BidirectionalMap.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_Factory.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_FileStamp.java
  dev/com.ibm.ws.anno/src/com/ibm/wsspi/annocache/util/Util_Factory.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/cases/AnnotationTargetsTest.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/cases/AnnotationTest_BaseClass.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/cases/AnnotationTest_BaseDirectClass.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/cases/InfoStoreTest.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/info/InfoStore_Internals_Test.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/info/InfoStore_TestBase.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/scan/Test_Base_State.java
Labels: CLA Signed

#13056 modifying featureUtility json handling
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#12943 Increase timeouts in gRPC FAT app
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#12972 Add a new spnego authentication error page
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.spnego/resources/com/ibm/ws/security/spnego/internal/resources/SpnegoMessages.nlsprops
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/ErrorPageConfig.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoAuthenticator.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoConfig.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoService.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnegoConfigImpl.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#13118 Reduce the length of test.bucket.path for com.ibm.ws.jaxrs.2.1.client_fat tests
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCXFRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ReactiveSampleTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientCallbackTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientLTPATest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ClientSSLTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ComplexClientTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21ProxyAuthTest/bootstrap.properties
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13117 Resolve incorrect async isFinished
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInputStreamEE7.java
Labels: CLA Signed, in:Transport, in:Web Components, team:Sirius

#13111 Renamed features to io.openliberty.X
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-3.0/io.openliberty.beanValidation-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/el-4.0/io.openliberty.el-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-3.0/io.openliberty.jsp-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed

#13109 Added ee9 version to com.ibm.ws.javaee.version bundle
  dev/com.ibm.ws.javaee.version/src/com/ibm/ws/javaee/version/JavaEEVersion.java
Labels: CLA Signed

#13115 launch wab module uninstall async
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
Labels: CLA Signed

#13125 [#13124] Log exception thrown during app start before shutting it down
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/DynamicVirtualHost.java
Labels: in:Web Components, team:Wendigo West

#13127 Synchronize JSR-375 provider registration for issue #11504
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/BridgeBuilderImpl.java
Labels: CLA Signed, release bug

#13031 Issue 13030: Wait for HTTP to allow ACME startup
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeApplicationStateListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/util/AcmeConstants.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/internal/AcmeConfigTest.java
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/test-applications/app1/resources/index.jsp
  dev/com.ibm.ws.security.acme_fat/test-applications/slowapp.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.acme_fat/test-applications/slowapp.war/resources/package.properties
  dev/com.ibm.ws.security.acme_fat/test-applications/slowapp.war/src/test/app/SlowStopAppListener.java
Labels: ID reviewed, L2 Reviewed, team:Core Security, team:Wendigo East

#13136 Issue 13135: Updates for test failures acme_fat
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#13146 Issue #11970: Add Injection-EJB FAT for Jakarta EE 9
  dev/com.ibm.ws.injection_fat/bnd.bnd
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/DSDTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/EnvEntryTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/RepeatableDSDTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/ResRefTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/ServiceLookupTest.java
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/TranTest.java
Labels: CLA Signed, in:Java EE Platform, noproductcode, team:Blizzard, test delivery

#13119 Use evaluated variables when determining conflicts
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigValidator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/SystemConfiguration.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigValidatorTest.java
Labels: CLA Signed

#13141 Fix bug causing include tag not to be parsed with installUtility and featureUtility
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallUtils.java
Labels: CLA Signed

#13121 Issue 12207: Adding token_type_hint option
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/jose4j/OidcTokenImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/SocialLoginConfig.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OkdServiceLoginImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/IntrospectUserApiUtils.java
Labels: CLA Signed

#13139 13120: Grpc Server Interceptor tests
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.invalid.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.multiple.interceptor.xml
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerInterceptor2.java
Labels: CLA Signed, noproductcode

#13162 Remove ignoreDuplicateEJBBindings beta metatype we decided to not support
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#13168 Add third-party APIs to MP GraphQL 1.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/cdi/config/GraphQLConfig.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/RolesAuthTest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.rolesAuth/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/rolesAuthApp/src/mpGraphQL10/rolesAuth/ClientInterface1.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/rolesAuthApp/src/mpGraphQL10/rolesAuth/ClientInterface2.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/rolesAuthApp/src/mpGraphQL10/rolesAuth/ClientInterfaceBase.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/rolesAuthApp/src/mpGraphQL10/rolesAuth/RolesAuthTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.authorization/src/com/ibm/ws/microprofile/graphql/authorization/component/AuthorizationFilter.java
  dev/com.ibm.ws.microprofile.graphql.authorization/src/com/ibm/ws/microprofile/graphql/authorization/component/AuthorizationInterceptor.java
  dev/com.ibm.ws.microprofile.graphql.authorization/src/com/ibm/ws/microprofile/graphql/authorization/component/GraphQLAuthorizationExtension.java
  dev/com.ibm.ws.microprofile.graphql.authorization/src/com/ibm/ws/microprofile/graphql/authorization/component/GraphQLAuthorizationServletContainerInitializer.java
  dev/com.ibm.ws.microprofile.graphql.metrics.1.0/bnd.bnd
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#13104 infra for migrated tests
  dev/com.ibm.ws.transaction.HADB_fat/.classpath
  dev/com.ibm.ws.transaction.HADB_fat/.project
  dev/com.ibm.ws.transaction.HADB_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.HADB_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.HADB_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.HADB_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.HADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.HADB_fat/build.gradle
  dev/com.ibm.ws.transaction.HADB_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.HADB_fat/fat/src/com/ibm/ws/transaction/test/FailoverTest.java
  dev/com.ibm.ws.transaction.HADB_fat/ifxjdbc.bnd
  dev/com.ibm.ws.transaction.HADB_fat/publish/servers/com.ibm.ws.transaction/bootstrap.properties
  dev/com.ibm.ws.transaction.HADB_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.HADB_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/Driver.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnection.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSource.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxDatabaseMetaData.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.HADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxStatement.java
  dev/com.ibm.ws.transaction.HADB_fat/transaction_fat.bnd
Labels: CLA Signed, noproductcode

#13147 Fix Defect 275540- cdi 2.0 SecureAsyncEventsTest TokenService not found
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/SecureAsyncEventsTest.java
Labels: CLA Signed, noproductcode

#13153 Remove direct dependencies on weld bundles
  dev/com.ibm.ws.jsfContainer.classloading.2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: CLA Signed

#13174 Issue #11969: Enable injection-JPA FAT for Jakarta EE 9
  dev/com.ibm.ws.injection_fat/bnd.bnd
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/JPATest.java
Labels: CLA Signed, in:Java EE Platform, noproductcode, team:Blizzard, test delivery

#13171 Issue #13170: Allow MDB methods to be non-public final
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/jitdeploy/EJBWrapper.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#13175 Add security test to getAppInfo
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesTests.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerProto.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreConsumerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/api/ConsumerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerServiceRestClient.java
Labels: CLA Signed, noproductcode

#13187 Get Eclipse building again
  dev/com.ibm.ws.security.audit_fat.common.tooling/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.authorization.jacc.testprovider/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.jaspic.test/.classpath
  dev/com.ibm.ws.security.jaspic.test/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.jaspic_fat/.classpath
  dev/com.ibm.ws.security.jaspic_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.health.3.0.internal_fat/.classpath
  dev/io.openliberty.org.eclipse.microprofile.health.3.0/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#13172 test deserialization after switching between Jakarta and Java EE
  dev/com.ibm.ws.context_fat_serialization/fat/src/test/context/serialization/ContextServiceSerializationTest.java
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/classloaderContext-EJB-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/classloaderContext-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/defaultContext_ALL_CONTEXT_TYPES-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/jeeMetadataContext-EJB-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/jeeMetadataContext-JSP-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/jeeMetadataContext-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/securityContext-user3-user3-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/resources/WEB-INF/serialized/transactionContext-v20.0.0.8-jakarta.ser
  dev/com.ibm.ws.context_fat_serialization/test-applications/contextserbvt.war/src/test/context/serialization/web/ContextServiceSerializationTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#13166 Issue 12640: Skip 2019I msg on dryRun fetchCert
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/FATSuite.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#13080 Minify fallback on singleton conflict resolution
  dev/build.image/build.gradle
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/MinifiedServerEnforceSingletonTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingleton.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingletonA-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingletonB-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingletonB-2.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingletonC-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/minifyEnforceSingletonC-2.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fat.minify.enforce.singleton/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fat.minify.enforce.singleton/server.xml
Labels: CLA Signed

#13193 Wait for CWWKF0011I before starting test
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/security/ssl/SecuritySSLTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13202 Graphiql
  dev/com.ibm.ws.io.smallrye.graphql/resources/META-INF/ui/graphiql.html
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/ui/GraphiQLUIServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/.classpath
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/UITest.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.ui/bootstrap.properties
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.ui/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/uiApp/src/mpGraphQL10/ui/GraphQLApiClass.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/uiApp/src/mpGraphQL10/ui/UITestServlet.java
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#13200 13165-Declare eeCompatible-9.0 in public Jakarta EE9 features
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaMail-1.6/com.ibm.websphere.appserver.jakartaMail-1.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonb-2.0/com.ibm.websphere.appserver.jsonb-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonbContainer-2.0/com.ibm.websphere.appserver.jsonbContainer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonp-2.0/com.ibm.websphere.appserver.jsonp-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonpContainer-2.0/com.ibm.websphere.appserver.jsonpContainer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-3.0/io.openliberty.jsp-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/io.openliberty.managedBeans-2.0.feature
Labels: jakartaEE, team:OSGi Infrastructure

#13199 Issue #13198: FFDC ignore for FileNotFound Exception
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
Labels: CLA Signed, noproductcode

#13205 Support for Kerberos auth for Oracle-backed JDBC datasources
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc_fat_krb5/.classpath
  dev/com.ibm.ws.jdbc_fat_krb5/README.txt
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/build.gradle
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/DB2KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/KerberosPlatformRule.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/OracleKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/kdc-server/Dockerfile
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/kdc-server/docker-entrypoint.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/Dockerfile
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/setup/1kerberos.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/setup/2oracle.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/startup/01_kerberos.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/startup/02_oracle.sql
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/security/oracle_client.keytab
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-oracle-app/src/jdbc/krb5/oracle/web/OracleKerberosTestServlet.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, team:Zombie Apocalypse

#13189 13024 restart gRPC service apps for all config change events
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/config/GrpcServiceConfigImpl.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
  dev/io.openliberty.grpc.1.0.internal/test/io/openliberty/grpc/internal/config/GrpcServiceConfigTest.java
Labels: CLA Signed, in:Transport, team:Sirius

#13225 Issue #13170: Skip MDB No Methods Interface final methods
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/jitdeploy/EJBWrapper.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#13209 Change "whiteList" to "allowList"
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#13211 Remove unnecessary comments / empty constructor
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/cdi/config/GraphQLConfig.java
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#13107 jwtBuilder configurable nbf claim
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/JwtConfig.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtComponent.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtCreator.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientConfigTestsConfig.xml
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
Labels: CLA Signed, L2 ReviewNotRequired

#13098 Enable jakartaee for rest connector and rest handler
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restConnector2.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restConnector2.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restHandler1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restHandler1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webBundleSecurity1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webBundleSecurity1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.adminSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.adminSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.restHandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.wsspi.appserver.webBundleSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restConnector-2.0/com.ibm.websphere.appserver.restConnector-2.0.feature
  dev/com.ibm.ws.jmx.connector.server.rest/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/build.gradle
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJCATest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJMSTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/build.gradle
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/fat/src/com/ibm/ws/rest/handler/validator/cloudant/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler/bnd.bnd
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, jakartaEE, team:OSGi Infrastructure

#13159 Unify the message nls props between all metrics monitor bundles.
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.2.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.3.0.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.3.x.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/MetricsMonitorTest.java
  dev/com.ibm.ws.microprofile.metrics.3.x.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/com.ibm.ws.microprofile.metrics.monitor/resources/com/ibm/ws/microprofile/metrics/monitor/resources/MonitorMetrics.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#13207 11278-Move JSON features to io.openliberty
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-2.0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-9.0/io.openliberty.jakartaeeClient-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonb-2.0/io.openliberty.jsonb-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonbContainer-2.0/io.openliberty.jsonbContainer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonp-2.0/io.openliberty.jsonp-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonpContainer-2.0/io.openliberty.jsonpContainer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure
