Repository OpenLiberty/open-liberty, pull requests merged in 2020-10, with the labels that each got.

#14224 EJB Custom Bindings BindingsOnError Config for Ambiguous EJBs
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/EJBLocalNamingHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/LocalColonEJBNamingHelper.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.bindings_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/AmbiguousBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BindingNameTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/ComponentIDTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/NoInterfaceBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/ServerXMLBindingTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server.err/server.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousNameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousNameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousNameRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousOtherName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousOtherNameBean.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousOtherNameHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousOtherNameRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousOtherRemoteName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousEJB.jar/src/com/ibm/ambiguous/ejb/AmbiguousRemoteName.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/AmbiguousWeb.war/src/com/ibm/ambiguous/web/AmbiguousTestServlet.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/NameSpaceBinder.java
  dev/com.ibm.ws.ejbcontainer.injection_fat/fat/src/com/ibm/ws/ejbcontainer/injection/fat/tests/InjectionXMLTest.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBLocalNamingHelperImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/LocalColonEJBNamingHelperImpl.java
Labels: CLA Signed

#14218 Less Latching and Better Processing
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreProducerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletAdapter.java
Labels: CLA Signed

#14244 gRPC client header propagation should forward all values for a header
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyHeaderPropagationSupport.java
Labels: CLA Signed, in:Transport, team:Sirius

#14255 Fix up eclipse and feature files from recent PRs
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.faces3.0-beanValidation3.0.feature
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/.project
  dev/io.openliberty.com.fasterxml.jackson/.classpath
  dev/io.openliberty.com.fasterxml.jackson/.settings/bndtools.core.prefs
  dev/io.openliberty.org.jboss.resteasy.common/.classpath
Labels: CLA Signed, team:Performance

#14252 Issue #14251: Move all EJB 4 feature to parallel activation
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-ejb4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.ejbliteJPA-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.enterpriseBeansRemoteClientServer-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.enterpriseBeansRemoteClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeans-4.0/io.openliberty.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansHome-4.0/io.openliberty.enterpriseBeansHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansRemote-4.0/io.openliberty.enterpriseBeansRemote-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/io.openliberty.mdb-4.0.feature
Labels: CLA Signed, in:EJB Container, team:Blizzard

#14274 Removing broken travis file
  .travis.yml
Labels: CLA Signed, noproductcode

#14094 add WebSphere Liberty swidtag
  dev/build.image/build.gradle
  dev/build.image/publish/ibm.com_WebSphereLiberty-20.0.0.swidtag
Labels: CLA Signed, in:Install

#14277 NOTICES for 20.0.0.11
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#14238 MP JWT 1.2 additional NLS updates
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
Labels: CLA Signed, team:Security SSO

#14264 Shorten EJBCustomBinding metatype labels
  dev/com.ibm.ws.ejbcontainer/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed

#14246 Improve performance of config props in server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/.classpath
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.3_fat/publish/servers/ServerXMLServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/serverXMLWebApp/src/com/ibm/ws/microprofile/config13/serverXMLWebApp/web/ServerXMLWebAppBean.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/test-applications/serverXMLWebApp/src/com/ibm/ws/microprofile/config13/serverXMLWebApp/web/ServerXMLWebAppServlet.java
  dev/io.openliberty.microprofile.config.internal.serverxml/bnd.bnd
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/AppPropertiesComponent.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/AppPropertiesTrackingComponent.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/AppPropertyConfigSource.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/OSGiConfigUtils.java
Labels: CLA Signed

#14279 grpcClient config update
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/io.openliberty.grpc.1.0.internal.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, in:Transport, team:Sirius

#14285 MP JWT 1.2 TCK: Update jvm.options to run with beta function
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudNoEnv/jvm.options
Labels: noproductcode, team:Security SSO

#14283 convert persistent executors timers buckets to use jakarta persistent timers
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/publish/servers/com.ibm.ws.concurrent.persistent.fat.demo.timers/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/AutomaticDatabase.java
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/AutomaticIO.java
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/AutomaticMemory.java
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/AutomaticScheduler.java
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/PersistentDemoTimersServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/test-application/demotimers/src/ejb/timers/ProgrammaticTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/publish/servers/com.ibm.ws.concurrent.persistent.fat.timers/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/AutoTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/MyTimer.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/ejb/MyTimerTracker.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/test-applications/timersapp/src/web/PersistentTimersTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14191 Added strings to fix missing javax transformations
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
Labels: CLA Signed, in:Web Components, team:Sirius

#14221 [14220] Use JsonValue as check for isReadable/Writeable
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/providers/JsonPProvider.java
  dev/io.openliberty.org.jboss.resteasy.common/test/io/openliberty/restfulWS/providers/JsonPProviderTest.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14254 Update JPA 3.0 API to RC2 and Eclipselink 3.0 to 879de6b.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.0.feature
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JaxbUnmarshaller.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml30/Persistence.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml30/package-info.java
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/schemas/jakartaee/persistence_3_0.xsd
  dev/com.ibm.ws.jpa_30_fat/.classpath
  dev/com.ibm.ws.jpa_30_fat/.project
  dev/com.ibm.ws.jpa_30_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa_30_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa_30_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa_30_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa_30_fat/bnd.bnd
  dev/com.ibm.ws.jpa_30_fat/build.gradle
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/DatabaseVendor.java
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/JPABootstrapTest.java
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_30_fat/publish/servers/JPABootstrapFATServer/bootstrap.properties
  dev/com.ibm.ws.jpa_30_fat/publish/servers/JPABootstrapFATServer/server.xml
  dev/com.ibm.ws.jpa_30_fat/test-applications/helpers/DatabaseManagement/resources/databasemanagement.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa_30_fat/test-applications/helpers/DatabaseManagement/src/jpahelper/databasemanagement/DatabaseManagementServlet.java
  dev/com.ibm.ws.jpa_30_fat/test-applications/jpabootstrap/resources/jpa-3.0/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_30_fat/test-applications/jpabootstrap/src/jpabootstrap/entity/SimpleTestEntity.java
  dev/com.ibm.ws.jpa_30_fat/test-applications/jpabootstrap/src/jpabootstrap/web/TestJPABootstrapServlet.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/DataPacket.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/MessagingClient.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/MessagingException.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/MessagingProperties.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/jms/AbstractJMSClient.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/jms/JMSClientConfig.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/jms/JMSClientFactory.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/jms/JMSQueueClient.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/jms/JMSTopicClient.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/smc/StatefulMessengerClient.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/msgcli/smc/StatefulMessengerClientBean.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/JMSClientContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/JPAPersistenceContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/MessagingClientContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/StatefulMessengerClientContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/TestExecutionContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testinfo/TestSessionSignature.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/testlogic/JPAEntityClassEnum.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/tranjacket/EMTransactionJacket.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/tranjacket/JTATransactionJacket.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/tranjacket/TransactionJacket.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/tranjacket/TransactionJacketException.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/JEEExecutionContextHelper.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/ejb/BMTEJBTestVehicle.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/ejb/CMTEJBTestVehicle.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/ejb/EJBTestVehicle.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/execontext/VehicleExecutionContext.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/resources/JPAResource.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/resources/TestExecutionResources.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/web/EJBTestVehicleServlet.java
  dev/com.ibm.ws.jpa_30_fat/test-framework/src/com/ibm/ws/testtooling/vehicle/web/JPATestServlet.java
  dev/io.openliberty.jakarta.persistence.3.0/bnd.bnd
Labels: CLA Signed, in:JPA, jakartaEE, team:Blizzard

#14250 Enable subset of MP JWT TCK 1.1 tests
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_noenv.xml
Labels: team:Security SSO

#14209 Enablement of jaxws-2.3 FAT tests in com.ibm.ws.jaxws.2.2.webcontainer_fat
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxws-2.3.feature
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/BindingTypeWsdlMismatchTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/BindingTypeWsdlMismatchTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/CatalogFacilityTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/EJBServiceRefBndTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HandlerChainTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HandlerChainWithWebServiceClientTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HttpConduitPropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/MTOMTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/PortComponentRefTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/ServerSideStubClientTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/VirtualHostTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceInWebXMLTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceInWebXMLTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceRefFeaturesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceRefTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WsBndEndpointOverrideTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WsBndEndpointOverrideTest_Lite.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/src/org/apache/cxf/jaxws/interceptors/MessageModeOutInterceptor.java
Labels: CLA Signed

#14273 MP JWT 1.2: Externalize new supported token signature algorithms
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, L2 ReviewNotRequired, team:Security SSO

#14272 Don't throw warning/errors for Ambiguous Default
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/EJBLocalNamingHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/LocalColonEJBNamingHelper.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBLocalNamingHelperImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/LocalColonEJBNamingHelperImpl.java
Labels: CLA Signed

#14294 Revert "add WebSphere Liberty swidtag"
  dev/build.image/build.gradle
  dev/build.image/publish/ibm.com_WebSphereLiberty-20.0.0.swidtag
Labels: CLA Signed

#14261 Change header name in feature files
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.0/io.openliberty.connectors-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeans-4.0/io.openliberty.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansHome-4.0/io.openliberty.enterpriseBeansHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansLite-4.0/io.openliberty.enterpriseBeansLite-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansRemote-4.0/io.openliberty.enterpriseBeansRemote-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messaging-3.0/io.openliberty.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingClient-3.0/io.openliberty.messagingClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingSecurity-3.0/io.openliberty.messagingSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingServer-3.0/io.openliberty.messagingServer-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.0/io.openliberty.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature/test/test data/com.ibm.websphere.supersededA.mf
Labels: CLA Signed

#13092 Create auto cdi feature for jakarta websockets
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-websocket2.0.feature
  dev/com.ibm.ws.wsoc.cdi.weld/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/CdiTest.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14189 Rename priv servlet
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.builtinAuthentication-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.builtinAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsp-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.jsp-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurityClient-1.0/com.ibm.websphere.appserver.appSecurityClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-1.2/com.ibm.websphere.appserver.cdi-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/io.openliberty.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jacc-1.5/com.ibm.websphere.appserver.jacc-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jacc-2.0/io.openliberty.jacc-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-3.1/com.ibm.websphere.appserver.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-4.0/com.ibm.websphere.appserver.servlet-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionDatabase-1.0/com.ibm.websphere.appserver.sessionDatabase-1.0.feature
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/fat/src/com/ibm/ws/ejbcontainer/remote/client/fat/tests/EjbLinkTest.java
  dev/com.ibm.ws.httpservice/publish/features/com.ibm.websphere.appserver.httpservice-2.2.mf
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ProductFeatureTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/files/prodtestprivate-1.0.mf
Labels: CLA Signed

#14280 Upgrade to Hibernate Validator 6.1.6.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/resources/org/hibernate/validator/ValidationMessages.properties
Labels: CLA Signed, team:Zombie Apocalypse

#14253 add a dopriv to ReferencingAuthenticator in jaxrs-2.0 for java 2 security
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/ReferencingAuthenticator.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14302 Revert "MP JWT 1.2 TCK: Update jvm.options to run with beta function"
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudNoEnv/jvm.options
Labels: CLA Signed, noproductcode

#14304 Revert "MP JWT 1.2: Externalize new supported token signature algorithms"
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#14276 Don't test features using Java level below their required minimum
  dev/build.featureStart_fat/fat/src/com/ibm/ws/simple/FeaturesStartTest.java
  dev/build.featureStart_fat/publish/files/feature-java-levels.properties
Labels: CLA Signed, noproductcode

#14301 convert persistent executor mbean bucket to Jakarta persistent timers
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/files/server2.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/publish/servers/com.ibm.ws.concurrent.persistent.fat.mbean/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/test-applications/persistentmbeantest/src/web/MBeanCounterCallable.java
  dev/com.ibm.ws.concurrent.persistent_fat_mbean/test-applications/persistentmbeantest/src/web/PersistentExecMBeanTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14284 Issue #14282: Ignore CWWKG0014E in EJB FAT
  dev/com.ibm.ws.ejbcontainer.async_fat/fat/src/com/ibm/ws/ejbcontainer/async/fat/tests/AsyncConfigTests.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/RemoteTests.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#14291 Lra m2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/lra.1.0.bnd
Labels: CLA Signed

#13819 13818 expirer
  dev/com.ibm.ws.messaging.msgstore/.gitignore
  dev/com.ibm.ws.messaging.msgstore/bnd.bnd
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/cache/links/AbstractItemLink.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpirableReference.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/Expirer.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpiryIndex.java
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/ExpiryTest.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ejs/util/am/AlarmManager.java
Labels: CLA Signed

#14308 Revert "Enable subset of MP JWT TCK 1.1 tests"
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/bnd.bnd.disabled
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_noenv.xml
Labels: CLA Signed, noproductcode

#14327 Revert "13818 expirer"
  dev/com.ibm.ws.messaging.msgstore/.gitignore
  dev/com.ibm.ws.messaging.msgstore/bnd.bnd
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/cache/links/AbstractItemLink.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpirableReference.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/Expirer.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpiryIndex.java
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/ExpiryTest.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ejs/util/am/AlarmManager.java
Labels: CLA Signed

#14226 upgrade RestEasy to version 4.5.8
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.ext.Providers
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider/bnd.bnd
Labels: CLA Signed

#14293 Fix tests for JsonConfigBootstrapTest and make methods more generic for different servers
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigBootstrapTest.java
  dev/com.ibm.ws.logging.json_fat/publish/files/appsWriteJsonDisabled.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/appsWriteJsonEnabled.xml
Labels: CLA Signed, noproductcode

#14026 Move Kerberos datasource config to GA
  dev/com.ibm.ws.security.auth.data.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.kerberos.auth/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#14325 Fix Java warnings for com.ibm.ws.ras.instrument
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracePreprocessClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracingClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracingMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/buildtasks/AbstractInstrumentationTask.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/buildtasks/InstrumentForTrace.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/buildtasks/InstrumentWithFFDC.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/buildtasks/InstrumentWithTrace.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyTracePreprocessInstrumentation.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/StaticTraceInstrumentation.java
Labels: CLA Signed

#14338 Cleanup from recent pull requests
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/SymbolicNameTest.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-websocket2.0.feature
  dev/com.ibm.ws.jpa_testframework/build.gradle
Labels: CLA Signed, team:Performance

#14287 Issue #14286: Support setting the JNDI java.naming.ldap.derefAliases …
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ConfigConstants.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Wendigo East

#14297 Issue #14069: Enable JSF 2.2 tests for Jakarta EE9
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIConfigByACPTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscLifecycleTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResourceLibraryContractHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22FlashEvents.war/resources/WEB-INF/faces-config.xml
  dev/wlp-jakartaee-transform/rules/jakarta-faces-config.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-dd.properties
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14320 Update MP JWT 1.2 TCK to run with proper features and enable TCK
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt12/tck/Mpjwt12TCKLauncher_aud_noenv.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudNoenv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudNoEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckNoaudNoEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_noenv.xml
Labels: CLA Signed, noproductcode, team:Security SSO

#14278 Issue #13663: Add KnownAs ejbPersistentTimer-4.0
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansPersistentTimer-4.0/io.openliberty.enterpriseBeansPersistentTimer-4.0.feature
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#14351 Add @EJB lookup tests to ServerXML tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/ServerXMLBindingsWeb.war/src/com/ibm/ws/ejbcontainer/bindings/serverxml/bnd/web/ServerXMLBindingsTestServlet.java
Labels: CLA Signed, noproductcode

#14350 Delete the com.ibm.ws.com.fasterxml.jackson project
  dev/com.ibm.ws.com.fasterxml.jackson/.classpath
  dev/com.ibm.ws.com.fasterxml.jackson/.project
  dev/com.ibm.ws.com.fasterxml.jackson/.settings/bndtools.core.prefs
  dev/com.ibm.ws.com.fasterxml.jackson/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.com.fasterxml.jackson/bnd.bnd
Labels: CLA Signed

#14275 Latest mp config
  dev/build.image/scripts/Liberty- server remote debug.launch
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-2.0/io.openliberty.mpConfig-2.0.feature
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/Config14Tests.java
  dev/io.openliberty.io.smallrye.common/.classpath
  dev/io.openliberty.io.smallrye.common/.project
  dev/io.openliberty.io.smallrye.common/.settings/bndtools.core.prefs
  dev/io.openliberty.io.smallrye.common/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.smallrye.common/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.common/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.io.smallrye.common/bnd.bnd
  dev/io.openliberty.io.smallrye.common/bnd.overrides
  dev/io.openliberty.io.smallrye.common/resources/META-INF/beans.xml
  dev/io.openliberty.io.smallrye.common/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/io.openliberty.io.smallrye.config/.gitignore
  dev/io.openliberty.io.smallrye.config/bnd.bnd
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/config/internal_fat_tck/Config20TCKLauncher.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/servers/Config20TCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/servers/Config20TCKServer/server.env
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#14268 testCancelRunningTask transaction timeout from test infrastructure slowness
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14322 Add SystemOut to expose timing on test
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/ClientTestServlet.java
Labels: CLA Signed, noproductcode

#14091 Enable initial EE9 feature testing on jaxrs20 tests
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/SimpleJsonTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/annotationscan/AnnotationScanTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanparam/BeanParamTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanvalidation/JAXRSClientServerValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanvalidation/JAXRSPerRequestValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/bookcontinuationstore/JAXRSContinuationsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/bookstore/JAXRS20ClientServerBookTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/callback/JAXRS20CallBackTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/checkFeature/CheckFeature12Test.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/class_as_provider_resource/SameClassAsProviderAndResourceTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/client/ClientTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/context/ContextTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/contextresolver/DepartmentTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/exceptionmappers/ExceptionMappersTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/exceptionmappingWithOT/ExceptionMappingWithOTTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/extraproviders/ExtraProvidersTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/getClasses_getSingletons/SameClassInGetClassesAndGetSingletonsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/helloworld/HelloWorldTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/ibm/json/IBMJSON4JTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/jackson/JacksonPOJOTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/jackson1x/JacksonPOJOwithUserJacksonLib1xTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/jackson2x/JacksonPOJOwithUserJacksonLib2xTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/jacksonJsonIgnore/JacksonJsonIgnoreTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/json/UTF8Test.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/link/LinkHeaderTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/managedbeans/ManagedBeansTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/paramconverter/ParamConverterTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/params/ParamsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/providercache/ProviderCacheTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/readerwriterprovider/ReaderWriterProvidersTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/resourcealgorithm/SearchPolicyTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/restmetrics/RestMetricsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/security/annotations/SecurityAnnotationsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/security/ssl/SecuritySSLTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/securitycontext/CustomSecurityContextTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/securitycontext/SecurityContextTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/service/scope/ServiceScopeTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/servletcoexist/JAXRSServletCoexistTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/standard/StandardProvidersTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/subresource/ExceptionsSubresourcesTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/thirdpartyjersey/JerseyTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/thirdpartyjerseywithinjection/JerseyInjectionTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/uriInfo/UriInfoTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/validation/ValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/wadl/WADLTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/webcontainer/JAXRSWebContainerTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.options/server.xml
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: CLA Signed

#14342 Issue #14341: Update waitForBackgroundJavaScript delay
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#14323 Fixed MpHealth-3.0 RepeatActions for MpHealth-2.0 tests
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/ApplicationStateHealthCheckTest.java
Labels: CLA Signed, noproductcode

#14319 Issue #14316: Add WLP-AlsoKnownAs to faces-3.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14207 Deliver Eclipselink Overlay for OLGH14192
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/config/SystemProperties.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/helper/ConversionManager.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
  dev/com.ibm.ws.jpa_22_fat/.classpath
  dev/com.ibm.ws.jpa_22_fat/bnd.bnd
  dev/com.ibm.ws.jpa_22_fat/build.gradle
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/jpa22/OLGH14192Test.java
  dev/com.ibm.ws.jpa_22_fat/publish/servers/OLGH14192Server/bootstrap.properties
  dev/com.ibm.ws.jpa_22_fat/publish/servers/OLGH14192Server/server.xml
  dev/com.ibm.ws.jpa_22_fat/test-applications/APARs/OLGH14192/src/olgh14192/OLGH14192TestServlet.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, in:JPA, release bug, team:Blizzard

#14332 Add trace to debug threads not complete during quiesce period
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/publish/servers/OpentracingTCKServer/server.xml
Labels: CLA Signed, noproductcode

#14360 Various fixes for Logstash Testcontainer FAT
  dev/com.ibm.ws.logstash.collector_fat/bnd.bnd
  dev/com.ibm.ws.logstash.collector_fat/build.gradle
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#14354 Run jwtsso FAT bucket with mpJwt 1.1 and 1.2
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/BuilderTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FeatureOnlyTest.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/actions/JwtFatActions.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/actions/RunWithMpJwtVersion.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatUtils.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/shared/config/jwtSsoFeatures_mpJwt11.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/shared/config/jwtSsoFeatures_mpJwt12.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, team:Security SSO, test delivery

#13782 Update Liberty for Java 15 support
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#14330 Issue 13655: Add parallel bundle activation to mpJwt-1.* features
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.0/com.ibm.websphere.appserver.mpJwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.1/com.ibm.websphere.appserver.mpJwt-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.2/io.openliberty.mpJwt-1.2.feature
Labels: CLA Signed, team:Security SSO

#14371 increase test timeouts to accomodate our fvt runs
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
Labels: CLA Signed, noproductcode

#14369 Update MP 4.0 API bundles to only load Jakarta EE 8 package versions
  dev/io.openliberty.org.eclipse.microprofile/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile/config.2.0.bnd
  dev/io.openliberty.org.eclipse.microprofile/metrics.3.0.bnd
  dev/io.openliberty.org.eclipse.microprofile/opentracing.2.0.bnd
  dev/io.openliberty.org.eclipse.microprofile/rest.client.2.0.bnd
Labels: CLA Signed, team:Performance

#14100 Upgrade ASM to 9.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#14195 Add WLP-Activate-Type: parallel to faces-3.0 auto features
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-faces3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.faces3.0-beanValidation3.0.feature
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14271 Use the coordinator feature for tck tests
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/lra/tck/LraTckLauncher.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/servers/LRATCKServer/server.xml
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#14339 Move ThirdPartyServer to in memory DB
  dev/com.ibm.ws.cdi.third.party_fat/publish/servers/cdiThirdPartyServer/server.xml
Labels: CLA Signed, noproductcode

#13844 Add test for aggressive log takeover
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.transaction.cloud_fat.1/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.1/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloud_fat.1/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.1/fat/src/com/ibm/ws/transaction/test/tests/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.1/fat/src/com/ibm/ws/transaction/test/tests/DupXidTest.java
  dev/com.ibm.ws.transaction.cloud_fat.1/publish/files/features/cloudtxfat-1.0.mf
  dev/com.ibm.ws.transaction.cloud_fat.1/publish/servers/com.ibm.ws.transaction_DUPXID001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.1/publish/servers/com.ibm.ws.transaction_DUPXID002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.1/test-applications/transaction/src/com/ibm/ws/transaction/web/Base2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.1/test-applications/transaction/src/com/ibm/ws/transaction/web/DupXidServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.1/test-bundles/cloudtx/src/com/ibm/ws/cloudtx/ut/util/CloudTestServletBase.java
  dev/com.ibm.ws.transaction.cloud_fat.1/test-bundles/cloudtx/src/com/ibm/ws/cloudtx/ut/util/LastingXAResourceImpl.java
  dev/com.ibm.ws.transaction.cloud_fat.2/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.2/.project
  dev/com.ibm.ws.transaction.cloud_fat.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.2/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloud_fat.3/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.3/.project
  dev/com.ibm.ws.transaction.cloud_fat.3/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.3/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloud_fat.4/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.4/.project
  dev/com.ibm.ws.transaction.cloud_fat.4/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.4/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloud_fat.5/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.5/.project
  dev/com.ibm.ws.transaction.cloud_fat.5/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.5/cloudtx.bnd
  dev/com.ibm.ws.transaction.cloud_fat.6/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.6/.project
  dev/com.ibm.ws.transaction.cloud_fat.6/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.6/cloudtx.bnd
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/LastingXAResourceImpl.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceFactoryImpl.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceFactoryService.java
Labels: CLA Signed

#14196 More tolerant XATest Failure Handling
  dev/com.ibm.ws.jta_fat/test-applications/jta/src/web/XAServlet.java
Labels: CLA Signed, noproductcode

#14334 Gradle Parallel improvements: re-order copy tasks
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/build.gradle
  dev/com.ibm.ws.transaction.core_fat.2/build.gradle
  dev/com.ibm.ws.transaction.core_fat.3/build.gradle
  dev/com.ibm.ws.transaction.core_fat.4/build.gradle
  dev/com.ibm.ws.transaction.core_fat.5/build.gradle
  dev/com.ibm.ws.transaction.core_fat.6/build.gradle
  dev/com.ibm.ws.transaction.core_fat.7/build.gradle
  dev/com.ibm.ws.transaction.core_fat.8/build.gradle
  dev/com.ibm.ws.transaction.core_fat.9/build.gradle
Labels: CLA Signed, noproductcode

#14357 gRPC test app improvements
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreClientTestsUtils.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/servletConsumer/ConsumerServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/servletProducer/ProducerServlet.java
Labels: CLA Signed, noproductcode

#14263 Disable all features on conflict
  dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/resolver/FeatureResolver.java
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/DisableAllFeaturesOnConflictTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/EECompatibilityTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.false.a.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.false.b.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.false.c.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.false.d.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.false.e.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.falseConflict-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.falseConflict-2.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.falseConflict-3.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.true.a.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.true.b.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.true.c.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.true.d.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.trueConflict-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.disable.all.features.on.conflict.trueConflict-2.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.disable.onconflict/.gitignore
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.disable.onconflict/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.disable.onconflict/server.xml
Labels: CLA Signed, ID reviewed, L2 Reviewed

#14366 Remove duplicate case JmsMbean.xml file
  dev/com.ibm.ws.messaging.open_jms20_fat/publish/files/JmsMbean.xml
Labels: CLA Signed, in:Messaging, noproductcode, test bug

#14349 Issue 13930: Add mpJwtPropagation-1.2 auto feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-1.2.feature
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/clientconfig/JAXRSClientConfigImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/com/ibm/ws/jaxrs21/clientconfig/JAXRSClientConstants.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
Labels: CLA Signed, team:Security SSO

#14380 Revert "Revert "MP JWT 1.2: Externalize new supported token signature algorithms""
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, L2 ReviewNotRequired, team:Security SSO

#14310 Issue #14289: Move WebSocket 2.0/CDI 3.0 autofeature to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-websocket2.0.feature
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#13810 Connectors 2.0 Jakarta Classloading Testing
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.0/io.openliberty.connectors-2.0.feature
  dev/com.ibm.ws.app.manager.rar/bnd.bnd
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/DeploymentDescriptorParser.java
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/RAAnnotationProcessor.java
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/xml/ra/package-info.java
  dev/com.ibm.ws.jca_fat_classloading/bnd.bnd
  dev/com.ibm.ws.jca_fat_classloading/build.gradle
  dev/com.ibm.ws.jca_fat_classloading/fat/src/com/ibm/ws/jca/fat/classloading/JCAClassLoadingTest.java
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityAll_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityInvalid_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityMatch_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityMismatch_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityNone_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testClassSpaceRestriction_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testInvalidClassProviderRef_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testLoadResourceAdapterClassFromSingleApp_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/servers/com.ibm.ws.jca.fat.classloading/server.xml
  dev/com.ibm.ws.jca_fat_classloading/test-applications/ClassLoadingApp/resources/META-INF/application.xml
  dev/com.ibm.ws.jca_fat_classloading/test-applications/fvtweb/src/web/ClassLoadingTestServlet.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyActivationSpec.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyME.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyMessage.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyQueue.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyResourceAdapter.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyTopic.java
Labels: CLA Signed, team:Zombie Apocalypse

#14204 None as a configurable mpcontext type
  dev/com.ibm.ws.concurrent.mp.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/MPConfigAccessorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#14311 Fix Java warnings for com.ibm.ws.logging.core
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/SimpleRotatingQueue.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/SimpleRotatingSoftQueue.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/logging/internal/DisabledTraceService.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/logging/internal/StackFinder.java
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/logging/internal/WsLogger.java
  dev/com.ibm.ws.logging.core/src/com/ibm/wsspi/logprovider/TrService.java
Labels: CLA Signed

#11458 Enable trace for logservice and yoko
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleEar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleWar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleEar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleWar/bootstrap.properties
Labels: CLA Signed, noproductcode

#14361 Update MP Health 3.0 to RC5
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.health.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/health.3.0.bnd
Labels: CLA Signed

#14362 Change how web fragment absolute ordering test app is updated
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/AnnoCachingTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/FragmentOrderTest.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FileUtils.java
Labels: CLA Signed, noproductcode

#14365 Add finalize method to WSJarURLStreamHandler
  dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/WSJarURLStreamHandler.java
Labels: CLA Signed

#14382 Pull in new version of aries jndi core
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.bnd
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.overrides
Labels: CLA Signed

#14281 277364 delegation provider
  dev/com.ibm.ws.security.appbnd/bnd.bnd
  dev/com.ibm.ws.security.appbnd/src/com/ibm/ws/security/appbnd/internal/authorization/AppBndAuthorizationTableService.java
  dev/com.ibm.ws.security.appbnd/src/com/ibm/ws/security/appbnd/internal/delegation/DefaultDelegationProviderImpl.java
  dev/com.ibm.ws.security.authentication.builtin/bnd.bnd
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/AuthenticationServiceImpl.java
  dev/com.ibm.ws.security.authentication/bnd.bnd
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/delegation/DefaultDelegationProvider.java
Labels: CLA Signed

#14343 Fix Java warnings for com.ibm.ws.logging
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/FFDCData.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/ConsoleLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/FileLogSet.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/IncidentImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/IntrospectionLevelMember.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonLogHandler.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
Labels: CLA Signed

#14312 Fix Java warnings for com.ibm.ws.kernel.boot.logging
  dev/com.ibm.ws.kernel.boot.logging/src/com/ibm/ws/kernel/boot/logging/WsLogManager.java
Labels: CLA Signed

#14353 Fix Java warnings for com.ibm.ws.kernel.boot.core
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/HelpActions.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/archive/ArchiveFactory.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelResolver.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/ServerLock.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/HelpCommand.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/security/SSLSocketFactoryProxy.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/security/WLPDynamicPolicy.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/provisioning/ContentBasedLocalBundleRepository.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/wsspi/kernel/embeddable/ServerBuilder.java
Labels: CLA Signed

#14340 14328 reintroduce expirer
  dev/com.ibm.ws.messaging.msgstore/.gitignore
  dev/com.ibm.ws.messaging.msgstore/bnd.bnd
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/cache/links/AbstractItemLink.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpirableReference.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/Expirer.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/expiry/ExpiryIndex.java
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/ExpiryTest.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ejs/util/am/AlarmManager.java
Labels: CLA Signed

#14384 allow components to add additional features when using EE9 repeat action
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, hacktoberfest-accepted, in:JAX-RS, in:Test Infrastructure, noproductcode, team:Wendigo West

#14214 Fix checkpii error message
  dev/io.openliberty.grpc.1.0.internal.client.security/resources/io/openliberty/grpc/internal/client/security/resources/grpcclientsecuritymessages.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#14394 Add source directory to classpath
  dev/io.openliberty.faces.internal/.classpath
  dev/io.openliberty.org.apache.myfaces.3.0/.classpath
Labels: CLA Signed, in:Web Components, jakartaEE, noproductcode, team:Sirius

#14406 Fix testLogstashEvents()
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#14326 Remove unused fields in com.ibm.ws.ras.instrument
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/FFDCClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyJava8WorkaroundRuntimeTransformer.java
Labels: CLA Signed

#14409 Issue 14101: Fix MP JWT 1.2 TCK RolesAllowedTest setup
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/tckAudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
Labels: CLA Signed, noproductcode, team:Security SSO

#13805 make streaming tests configurable
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
Labels: CLA Signed, noproductcode

#14414 grpc_fat cleanup and test fix
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcTestUtils.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StreamingTests.java
  dev/com.ibm.ws.grpc_fat/test-applications/FavoriteBeerService.war/src/com/ibm/ws/grpc/fat/beer/service/BeerServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientInterceptor2.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerAnnotationInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerAnnotationInterceptor2.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerCDIInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerInterceptor2.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerInterceptor3.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/AppProducerJavaService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StreamingService.war/src/com/ibm/ws/grpc/fat/streaming/service/StreamingServlet.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#14401 Remove finalize() on WSRdbManagedConnectionImpl
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: CLA Signed, in:JDBC/JCA, team:Zombie Apocalypse

#14387 Resteasy test
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/SimpleJsonTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.simpleJson/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/simpleJson/src/com/ibm/ws/jaxrs/fat/simpleJson/JaxrsJsonClientTestServlet.java
Labels: CLA Signed, noproductcode

#14415 Add assert statement for restarting applications
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIInjectionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#14391 Prevent NPE in BootstrapConfig
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
Labels: CLA Signed

#14412 Refactored FT 1.0 Bulkhead Tests with CountDownLatch
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/BulkheadTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/test/src/com/ibm/ws/microprofile/faulttolerance/test/util/AsyncTestFunction.java
Labels: CLA Signed

#10351 PR to update OIDC client metatype to expose clockSkew
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Security SSO

#14392 expand testing of deserialized EJB timers
  dev/com.ibm.ws.concurrent.persistent_fat_compat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_compat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/PersistentExecutorCompatibilityWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/publish/servers/com.ibm.ws.concurrent.persistent.fat.compat/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/EJBTimerDeleted-20.0.0.10-JavaEE.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/EJBTimerWithInfo-20.0.0.10-JavaEE.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/resources/WEB-INF/serialized/EJBTimerWithScheduleExpression-20.0.0.10-JavaEE.ser
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/ejb/MyTimerEJBInWAR.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/PersistentExecCompatibilityTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14413 Issue 13959: MP JWT TCK TokenAsCookie fix in JwkRetriever
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
Labels: CLA Signed, team:Security SSO

#14422 Issue #14421: Avoid EJB Persistent Timers after quiesce
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/PersistentTimerTaskHandler.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerTestHelper.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#14420 AutonomicalPolling1ServerTest should tolerate retries
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/fat/src/com/ibm/ws/concurrent/persistent/fat/autonomicalpolling1serv/AutonomicalPolling1ServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14444 Add back MessageImpl overlay for PR #9235 changes.
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
Labels: CLA Signed, team:Performance

#14337 Transient Exception handling
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#14435 If the garbage collector does not collect unreferenced items, record a soft error only
  dev/com.ibm.ws.messaging.msgstore/test/com/ibm/ws/sib/msgstore/test/ExpiryTest.java
Labels: CLA Signed, noproductcode

#14442 grpc_fat tests need to make sure the expected server.xml is set
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTlsTest.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#14448 Update snapshot to 1006
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile/rest.client.2.0.bnd
Labels: CLA Signed

#14439 Issue #14014: Add WLP-AlsoKnownAs to connectorsInboundSecurity-2.0 fe…
  dev/com.ibm.websphere.appserver.features/visibility/public/connectorsInboundSecurity-2.0/io.openliberty.connectorsInboundSecurity-2.0.feature
Labels: CLA Signed, team:Wendigo East

#14120 Don't produce FFDC when fallback throws exception
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/FallbackStateImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/FallbackServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/test-applications/CDIFaultTolerance.war/src/com/ibm/ws/microprofile/faulttolerance_fat/cdi/beans/ParentFallbackBean.java
Labels: CLA Signed

#14447 Enable more MP JWT TCK tests
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
Labels: team:Security SSO

#14452 Remove com.ibm.ws.concurrent.persistent_fat_loadtest
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.classpath
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.project
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/fat/src/com/ibm/ws/concurrent/persistent/fat/load/LoadTestWithFailoverEnabled.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/files/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/files/test.file
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/servers/com.ibm.ws.concurrent.persistent.fat.loadtest/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/publish/servers/com.ibm.ws.concurrent.persistent.fat.loadtest/server.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/LoadTestServlet.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/TaskResultStore.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/CancelTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/MultiRunSeparateTriggerFailSometimesResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/MultiRunTriggerResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/SingleRunResultTask.java
  dev/com.ibm.ws.concurrent.persistent_fat_loadtest/test-applications/schedtest/src/web/task/SingleRunTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14446 run CDI/Concurrency tests with Jakarta EE
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ApplicationScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/DependentScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/RequestScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ResourcesProducer.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/SessionScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/SingletonScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/SubmitterBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/TaskBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/TransactionalBean.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14368 Enable jakartaee for session data
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionCache1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionCache1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionDatabase1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.sessionDatabase1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionDatabase-1.0/com.ibm.websphere.appserver.sessionDatabase-1.0.feature
  dev/com.ibm.websphere.javaee.jcache.1.1/bnd.bnd
  dev/com.ibm.ws.cdi.lifecycle_fat/bnd.bnd
  dev/com.ibm.ws.cdi.lifecycle_fat/build.gradle
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanLifecycleTest.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EventMetaDataTest.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ObservesInitializedTest.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/fat/tests/SessionDestroyTests.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.lifecycle_fat/publish/servers/cdi12PassivationServer/bootstrap.properties
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat/build.gradle
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/HazelcastClientTest.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerA/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheServerB/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServer/server.xml
  dev/com.ibm.ws.session.cache_fat/publish/servers/sessionCacheTimeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_config/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config/build.gradle
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config/publish/servers/sessionCacheServer/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan_container/build.gradle
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/ResourceTransformationHelper.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/server.xml
  dev/com.ibm.ws.session.db/bnd.bnd
  dev/com.ibm.ws.session.store/bnd.bnd
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpSession.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfigurationFactory.java
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, jakartaEE, team:OSGi Infrastructure

#14443 add security.appbnd_test from CL to OL
  dev/com.ibm.ws.security.appbnd_test/.classpath
  dev/com.ibm.ws.security.appbnd_test/.gitignore
  dev/com.ibm.ws.security.appbnd_test/.project
  dev/com.ibm.ws.security.appbnd_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.appbnd_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.appbnd_test/bnd.bnd
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/authorization/AppBndAuthorizationTableServiceTest.java
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/DefaultDelegationProviderTest.java
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/SecurityRolesBuilder.java
Labels: CLA Signed, in:Security, noproductcode, team:Core Security

#14438 Reduce tracing in MP Rest Client TCK FATs
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#13875 [13874] FAT test case for `ResourceInfo`
  dev/com.ibm.ws.jaxrs.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/resourceinfo/ResourceInfoTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.resourceinfo/.gitignore
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.resourceinfo/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.resourceinfo/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/AbstractResource.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/AbstractResourceImpl.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/App.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/IResource.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/IResourceImpl.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/PreMatchRequestFilter.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/RequestFilter.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/ResponseFilter.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/SimpleResource.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/resourceinfo/src/com/ibm/ws/jaxrs/fat/resourceinfo/SubClassResource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#14441 Port JCA-1.7 fat
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jca.1.7_fat/.classpath
  dev/com.ibm.ws.jca.1.7_fat/.project
  dev/com.ibm.ws.jca.1.7_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca.1.7_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca.1.7_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca.1.7_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca.1.7_fat/bnd.bnd
  dev/com.ibm.ws.jca.1.7_fat/build.gradle
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/fvtra.rar
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/helloworldbeanra.rar
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/helloworldra.rar
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/imsico1210.rar
  dev/com.ibm.ws.jca.1.7_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca.1.7_fat/fat/src/com/ibm/ws/jca/fat/JCA17Test.java
  dev/com.ibm.ws.jca.1.7_fat/publish/servers/com.ibm.ws.jca.fat/bootstrap.properties
  dev/com.ibm.ws.jca.1.7_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtapp/META-INF/application.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/ejb/JCAEJBDDBean.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/ejb/JCAEJBDDLocal.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCAAODFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCAAODSFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCACFDSFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCADDServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCATransactionFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/ActivationSpecAuthImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/ActivationSpecImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/ActivationSpecVerifyImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/AdapterUtil.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/ConnectionEventSender.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/FVTAdapterHelper.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/FVTAdapterImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/FVTAdapterVerifyImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/FVTObjectCache.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/HandleStates.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/Reassociateable.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/XATerminatorWrapper.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/FVTBaseMessageProvider.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/FVTMessage.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/FVTMessageProvider.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/FVTMessageProviderImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/MessageException.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/MessageWaitTimeoutException.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/TextMessageImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/adapter/message/WorkInformation.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/ejs/ras/Tr.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/ejs/ras/TrLevelConstants.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/ejs/ras/TraceComponent.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/ejs/ras/TraceOptions.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/inout/adapter/ActivationSpecImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/src/com/ibm/inout/adapter/AdministeredObjectImpl.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14469 add missing ko NLS file
  dev/io.openliberty.grpc.1.0.internal.client.security/resources/io/openliberty/grpc/internal/client/security/resources/grpcclientsecuritymessages_ko.nlsprops
Labels: CLA Signed, ID review not needed

#14466 Simplify tests and add trace
  dev/com.ibm.ws.transaction.cloud_fat.7/fat/src/com/ibm/ws/transaction/test/DualServerDynamicPostgreSQLTest.java
  dev/com.ibm.ws.transaction.cloud_fat.7/fat/src/com/ibm/ws/transaction/test/PostgreSQLTest.java
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/files/ssl-certs/privkey.pem
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/files/ssl-certs/server.crt
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/files/ssl-certs/server.key
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/files/ssl-certs/server.req
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/resources/security/outboundKeys.p12
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD001/resources/security/outboundKeys.p12
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD002/resources/security/outboundKeys.p12
  dev/com.ibm.ws.transaction.cloud_fat.7/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TimeoutTest.java
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/jvm.options
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/resources/security/defaultKey.jks
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/resources/security/defaultTrust.jks
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/server.xml
  dev/com.ibm.ws.transaction.core_fat.9/fat/src/com/ibm/ws/transaction/test/FATSuite.java
Labels: CLA Signed, noproductcode

#14478 Temp fix to avoid memory leak in RestClientBean.builders
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#14484 Revert "add security.appbnd_test from CL to OL"
  dev/com.ibm.ws.security.appbnd_test/.classpath
  dev/com.ibm.ws.security.appbnd_test/.gitignore
  dev/com.ibm.ws.security.appbnd_test/.project
  dev/com.ibm.ws.security.appbnd_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.appbnd_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.appbnd_test/bnd.bnd
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/authorization/AppBndAuthorizationTableServiceTest.java
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/DefaultDelegationProviderTest.java
  dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/SecurityRolesBuilder.java
Labels: CLA Signed, noproductcode

#14495 fix gRPC service app start and server.xml update window
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
Labels: CLA Signed, in:Transport, team:Sirius

#14464 WSOC FVT: don't defer servlet loading to avoid server stop conflict
  dev/io.openliberty.wsoc.internal_fat/publish/servers/basicTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/webSocket11Server/server.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/basic.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/resources/WEB-INF/web.xml
Labels: CLA Signed, noproductcode

#14488 H2 Close connection on write IOException unless timeout
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed

#14470 Update json logging test to tolerate 'message' key in FFDC JSON
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/ConsoleLogTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JSONEventsTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/MessagesLogEnvTest.java
Labels: CLA Signed, noproductcode, test bug

#14498 Reduce number of PG containers needed per FULL run from 2 to 1
  dev/com.ibm.ws.transaction.cloud_fat.7/fat/src/com/ibm/ws/transaction/test/DualServerDynamicPostgreSQLTest.java
  dev/com.ibm.ws.transaction.cloud_fat.7/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.7/fat/src/com/ibm/ws/transaction/test/PostgreSQLTest.java
Labels: CLA Signed, noproductcode

#14333 Update Eclipselink projects to use GAV format.
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.3.0/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed, in:JPA, team:Blizzard

#14473 Add additional debug to resolve intermittent failure.
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/CallbackResource.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/SecondSettingCompletionCallback.java
Labels: CLA Signed, noproductcode

#14489 Log derby network start
  dev/fattest.simplicity/src/componenttest/topology/database/DerbyNetworkUtilities.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14497 Removing binary files for source
  dev/com.ibm.ws.jca.1.7_fat/.classpath
  dev/com.ibm.ws.jca.1.7_fat/bnd.bnd
  dev/com.ibm.ws.jca.1.7_fat/build.gradle
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/fvtra.rar
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/helloworldbeanra.rar
  dev/com.ibm.ws.jca.1.7_fat/external-resourceadapters/helloworldra.rar
  dev/com.ibm.ws.jca.1.7_fat/fat/src/com/ibm/ws/jca/fat/JCA17Test.java
  dev/com.ibm.ws.jca.1.7_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtapp/META-INF/application.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCAAODFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-applications/fvtweb/src/web/JCAAODSFVTServlet.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/adapter/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyActivationSpec.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyME.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyMessage.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyQueue.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyResourceAdapter.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/fvtra/src/com/ibm/fvtra/DummyTopic.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/resources/META-INF/beans.xml
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldConnectionFactoryImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldConnectionImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldConnectionMetaDataImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldIndexedRecord.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldIndexedRecordImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldInteractionImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldInteractionSpec.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldInteractionSpecImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldManagedConnectionImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldManagedConnectionMetaDataImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldRecordFactoryImpl.java
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldResourceAdapterMetaDataImpl.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#14292 add tlsprofiler securityutility command
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/SecurityUtility.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/TLSProfilerTask.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/TLSProfilerTaskTest.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/utils/StringStartsWithMatcher.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#14479 Issue #14475: Fix AmbiguousEJBReferenceException in App Client
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.ejbRemoteClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.enterpriseBeansRemoteClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansLite-4.0/io.openliberty.enterpriseBeansLite-4.0.feature
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkClient.jar/src/com/ibm/ws/ejbcontainer/ejblink/client/EjbLinkClient.java
Labels: CLA Signed, bug, in:EJB Container, team:Blizzard

#14518 Temporarily limit AppPrereq config change testing.
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AppPrereqTest.java
Labels: CLA Signed, noproductcode

#14427 Update FacesConfigDDParser.java for Jakarta EE9 Faces 3.0
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/jsf/FacesConfigDDParser.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/Faces30Tests.java
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/faces30Server/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/faces30Server/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/faces30Server/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/Faces30FacesConfigTest.war/resources/WEB-INF/faces-config.xml
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#14465 grpc_fat improvements
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientHeaderPropagationTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcTestUtils.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldBasicTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTlsTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/SecureHelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceSupportTests.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.security.default.xml
Labels: CLA Signed, noproductcode

#14508 fix http2_fat Http2SecureTests timeout issue
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.anno_fat/bnd.bnd
  dev/com.ibm.ws.anno_fat/build.gradle
  dev/com.ibm.ws.transport.http2_fat/bnd.bnd
  dev/com.ibm.ws.transport.http2_fat/build.gradle
  dev/com.ibm.ws.transport.http2_fat/fat/src/com/ibm/ws/http2/client/SecureHttp2Client.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2SecureTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/build.gradle
Labels: CLA Signed, in:Transport, team:Sirius, test bug

#14511 Change method of computing variable name
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.java
Labels: CLA Signed

#14482 Check for GC events during server startup
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#13206 [13049] Test case for using JsonNumber
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/JsonpTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonp/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/servers/jaxrs21.fat.jsonp/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonpApp/src/jaxrs21/fat/jsonp/JsonpApp.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonpApp/src/jaxrs21/fat/jsonp/JsonpResource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonpApp/src/jaxrs21/fat/jsonp/JsonpTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/providers/JsonPProvider.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#14513 Issue #13663: Move ejbPersistentTimer-4.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistenceService-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistentExecutorSubset-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeans-4.0/io.openliberty.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansPersistentTimer-4.0/io.openliberty.enterpriseBeansPersistentTimer-4.0.feature
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#14506 Update Jakarta Bean Validation 3.0 API from 3.0.0-M1 to 3.0.0.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#14510 retry deserialization with jakarta classes
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/PersistentExecutorCompatibilityWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_compat/publish/servers/com.ibm.ws.concurrent.persistent.fat.compat/bootstrap.properties
  dev/com.ibm.ws.concurrent.persistent_fat_compat/test-applications/persistentcompattest/src/web/MapCounterRunnable.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/publish/servers/com.ibm.ws.concurrent.persistent.fat.failovertimers.serverB/server.xml
  dev/com.ibm.ws.serialization/src/com/ibm/ws/serialization/DeserializationObjectInputStream.java
  dev/com.ibm.ws.serialization/src/com/ibm/ws/serialization/internal/SerializationServiceImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#14480 Port EJB 1X Stateful Remote tests to OL
  dev/com.ibm.ws.ejbcontainer.fat_tools/src/com/ibm/websphere/ejbcontainer/test/tools/FATHelper.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.legacy_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/EJB1XStatefulTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteHomeCreateServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteHomeMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteHomeRemoveServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplEnvEntryServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplExceptionServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplLifecycleMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteInterfaceContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteInterfaceMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteInterfaceRemoveServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteHomeCreateServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteHomeMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteHomeRemoveServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteImplEnvEntryServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteImplExceptionServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteImplLifecycleMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteInterfaceContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteInterfaceMethodServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteInterfaceRemoveServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/resources/META-INF/ibm-ejb-jar-ext.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRApplException.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRTestReentrance.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRTestReentranceBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRTestReentranceHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRa.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRaBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRaFakeKey.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRaHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSFRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/sfr/ejb/SFRaPassBy.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/resources/META-INF/ibm-ejb-jar-ext.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRApplException.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRTestReentrance.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRTestReentranceBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRTestReentranceHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRa.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRaBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRaFakeKey.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRaHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XSLRemoteSpecEJB.jar/src/com/ibm/ejb1x/base/spec/slr/ejb/SLRaPassBy.java
Labels: CLA Signed, noproductcode

#14486 Update FAT approvers in feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed

#14461 Add default Interceptors to Config Builder
  dev/io.openliberty.io.smallrye.config/src/io/openliberty/microprofile/config/internal/extension/OLSmallRyeConfigProviderResolver.java
Labels: CLA Signed

#14411 Add option to enforce cipher order
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.websphere.appserver.spi.ssl/bnd.bnd
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLLinkConfig.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SocketFactory.java
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired
