Repository OpenLiberty/open-liberty, pull requests merged in 2020-12, with the labels that each got.

#15126 move away from shrinkwrapsharedserver
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanDiscoveryModeNoneTest.java
Labels: CLA Signed, noproductcode

#15134 fix gRPC stream completion race condition
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
Labels: CLA Signed, in:Transport, team:Sirius

#15016 Re-enable osgi.checkConfiguration setting
  dev/com.ibm.ws.appclient.boot/test/com/ibm/ws/kernel/boot/internal/commands/FrameworkManagerTest.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/ProvisionerImpl.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/FrameworkManagerTest.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/launch/internal/ProvisionerTest.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/SystemBundleOverrideTest.java
  dev/com.ibm.ws.kernel.feature_fat/override.systemFeature.providesSwing.bnd
  dev/com.ibm.ws.kernel.feature_fat/override.systemFeature.requiresSwing.bnd
  dev/com.ibm.ws.kernel.feature_fat/override.userFeature.providesSwing.bnd
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.systemFeature.providesJavaxRMI.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.systemFeature.providesSwing.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.systemFeature.requiresJavaxRMI.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.systemFeature.requiresSwing.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.userFeature.providesJavaxRMI.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/override.userFeature.providesSwing.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/override.case1.server.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/files/override.case2.server.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/files/override.case3.server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.override.provides.javax.swing.plaf/src/javax/swing/plaf/ProvidedAPI.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.override.requires.javax.swing.plaf/src/test/override/requires/javax/swing/plat/Activator.java
Labels: CLA Signed

#15073 Update source for debug launch configurations
  dev/build.image/scripts/Liberty- server remote debug.launch
  dev/build.image/scripts/Liberty-FAT remote debug.launch
Labels: CLA Signed

#15135 Stop plugin_cfg.xml generation during server shutdown
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed

#15130 test app needs createClassLoader permission for Derby
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15137 Add WLP-AlsoKnownAs to facesContainer-3.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-3.0/io.openliberty.facesContainer-3.0.feature
Labels: CLA Signed

#15111 test parked handles across EJB methods
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyConnectionCachingBean.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAServlet.java
  dev/com.ibm.ws.jca_fat_derbyra/test-resourceadapters/fvt-resourceadapter/src/fat/derbyra/resourceadapter/DerbyConnection.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15133 Retry getConnection attempts up to 5 times to avoid ORA-12631 errors
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-oracle-app/src/jdbc/krb5/oracle/web/OracleKerberosTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#15123 Add remaining basic wsoc tests
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/build.gradle
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/BasicTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/HeaderTest.java
Labels: CLA Signed, in:Transport, jakartaEE, noproductcode, team:Sirius

#14986 Update MyFaces 2.3 to 2.3.7
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIInjectionTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/converter/FacesConverterCDIWrapper.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/util/CDIUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/validator/FacesValidatorCDIWrapper.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/DefaultFacesConfigurationProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/compiler/NamespaceHandler.java
  dev/io.openliberty.faces.internal/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#15112 Issue #14973: Update Jakarta Standard Tag Lib API to 2.0.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#15047 14807 update weld inject
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/LoginToContinueInterceptor.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/IdentityStoreHandlerServiceImpl.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/CDIHelper.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/DatabaseIdentityStore.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/IdentityStoreHandlerImpl.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtils.java
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/ClaimBean.java
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraFilterComponent.java
  dev/io.openliberty.org.jboss.weld4/test/io/openliberty/weld/jsf/WeldJSFCheckSumTest.java
Labels: CLA Signed

#15142 Increase Reactive Client test timeout values to account for slow response from RestEasy
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CXFRxInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JerseyRxInvokerTestServlet.java
Labels: CLA Signed, noproductcode

#15151 Issue #15150: EJB Fat Permissions for Jakarta EE 9
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncConfigServer/server.xml
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncRemoteServer/server.xml
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncSecureServer/server.xml
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard

#15143 Transform cxf bundles
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.simple.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.addr.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.validator.3.2/bnd.bnd
  dev/com.ibm.ws.webservices.handler/bnd.bnd
  dev/com.ibm.ws.webservices.javaee.common/bnd.bnd
  dev/io.openliberty.jakarta.jws.3.0/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-ws-provider.properties
Labels: CLA Signed, in:Web Services, jakartaEE, team:OSGi Infrastructure

#15155 Ensure all FAT tests run against FT 3.0
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleClassLoading.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/multimodule/tests/TestMultiModuleConfigLoad.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/FallbackMethodTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/completionstage/CDICompletionStageTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptorTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/jaxrs/JaxRsTest.java
Labels: CLA Signed, noproductcode

#15157 Close the JarFile objects
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NonZipExtensionFilesInBootInfLibTests20.java
Labels: CLA Signed, noproductcode

#15149 add HandleList support to EE Concurrency
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.emptyHandleListContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/noShip-1.0/io.openliberty.noShip-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/noShip-1.0/resources/l10n/io.openliberty.noShip-1.0.properties
  dev/com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
  dev/com.ibm.ws.concurrent_fat_db/test-applications/concurrentdbtest/src/concurrent/fat/db/web/ConcurrentDBTestServlet.java
  dev/io.openliberty.handlelist.context.internal/.classpath
  dev/io.openliberty.handlelist.context.internal/.gitignore
  dev/io.openliberty.handlelist.context.internal/.project
  dev/io.openliberty.handlelist.context.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.handlelist.context.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.handlelist.context.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.handlelist.context.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.handlelist.context.internal/bnd.bnd
  dev/io.openliberty.handlelist.context.internal/src/io/openliberty/handlelist/context/internal/EmptyHandleListContext.java
  dev/io.openliberty.handlelist.context.internal/src/io/openliberty/handlelist/context/internal/EmptyHandleListContextProvider.java
  dev/io.openliberty.handlelist.context.internal/src/io/openliberty/handlelist/context/internal/package-info.java
Labels: CLA Signed, team:Zombie Apocalypse

#15164 Issue #13664: Final Jakarta EJB API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.ejb-4.0.feature
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#15136 Rename long name of microProfile-4.0
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/com.ibm.websphere.appserver.microProfile-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/com.ibm.websphere.appserver.microProfile-4.0_zh_TW.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, in:MicroProfile, team:MicroProfileUK

#12563 Send Redirect to Relative URL
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSendRedirectRelativeURLDefault.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSendRedirectRelativeURLTrue.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_Default/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_Default/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_True/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_True/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestAddJspFile.war/resources/sendRedirect.jsp
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, team:Sirius

#15171 HandleList test for Singleton EJB
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/resources/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/DerbyLoadFromAppServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/SingletonBeanInWebApp.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/derbyapp/src/web/derby/StatefulBeanInWebApp.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15167 run custom login module test bucket with Jakarta EE
  dev/com.ibm.ws.jdbc_fat_loadfromapp/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15180 Issue #13661: Deliver final jakarta interceptors API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, in:Java EE Platform, jakartaEE, team:Blizzard

#15191 change persistence timeout to avoid uninteresting build breaks
  dev/io.openliberty.wsoc.internal_fat/publish/servers/basicTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/miscellaneousTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/secureTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/webSocket11Server/server.xml
Labels: CLA Signed, noproductcode

#13829 Implicit Converter Cache
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/converters/PriorityConverter.java
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/converters/ConstructorFunction.java
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/converters/ImplicitConverter.java
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/converters/MethodFunction.java
  dev/com.ibm.ws.microprofile.config.1.2/src/com/ibm/ws/microprofile/config12/impl/Config12ConversionManager.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/Config12ConverterTests.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/converters/Config13ImplicitConverter.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/impl/Config13ConversionManager.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/converters/Config14ImplicitConverter.java
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/impl/Config14ConversionManager.java
Labels: CLA Signed, in:MicroProfile/Config, performance, team:MicroProfileUK

#15095 Issue 14751: Fix JWK lookup code for key text and kid combination
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
Labels: CLA Signed, team:Security SSO

#15175 14934 - refactor com.ibm.ws.jaxrs.2.0.security to get the SSLSocketFactory from JSSEHelper
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/component/JaxRsAppSecurity.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/api/JaxRsAppSecurityService.java
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/component/JaxRsAppSecurityServiceImpl.java
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/component/SSLSupportService.java
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsProxySSLSocketFactory.java
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsSSLManager.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/api/JaxRsAppSecurityService.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15181 autoCloseConnections config property
  dev/com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionEventListener.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CGlobalConfigProperties.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.jakarta/server.xml
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra/server.xml
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#15198 HandleList integration for MicroProfile Context Propagation
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentTxTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentTxApp/src/concurrent/mp/fat/tx/web/MPConcurrentTxTestServlet.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/context/EmptyHandleListContextProvider.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ContextManagerImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ContextManagerProviderImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ManagedExecutorBuilderImpl.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/MicroProfileClearedContextSnapshot.java
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/contextpropagation/ThreadContextBuilderImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#15203 Issue #15202: Handle Daylight Savings in EJB Timer FAT
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/fat/src/com/ibm/ws/ejbcontainer/interceptor/fat/AroundTimeoutTest.java
  dev/com.ibm.ws.ejbcontainer.timer.auto_fat/fat/src/com/ibm/ws/ejbcontainer/timer/auto/fat/tests/AutoCreatedNPTimerTest.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard

#15205 WASReqURLOidc cookie updates for issue #14692
  dev/com.ibm.ws.security.openidconnect.client/resources/com/ibm/ws/security/openidconnect/client/internal/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
Labels: CLA Signed

#15207 Issue #15206: Deliver Jakarta EE9 security features for 21.0.0.2 beta .
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.audit1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.auditCollector1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.authFilter1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.constrainedDelegation1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jwt1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.spnego1.0.jakarta.feature
Labels: CLA Signed, team:Wendigo East

#15187 Update MP Health 3.0 to final API spec release
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.health.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/health.3.0.bnd
Labels: CLA Signed

#15192 fix HTTP/2 connection shutdown test problems
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/utils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/ContinuationFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/HttpMethodTests.java
Labels: CLA Signed, in:Transport, team:Sirius

#15194 Enable EE9 testing for Batch FATs
  dev/com.ibm.ws.jbatch.cdi_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.cdi_fat/build.gradle
  dev/com.ibm.ws.jbatch.cdi_fat/fat/src/fat/junit/BatchInjectionTest.java
  dev/com.ibm.ws.jbatch.cdi_fat/fat/src/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.cdi_fat/fat/src/fat/junit/TranTimeoutCleanupTest.java
  dev/com.ibm.ws.jbatch.misc_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.misc_fat/build.gradle
  dev/com.ibm.ws.jbatch.misc_fat/fat/src/fat/junit/FATTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DataSource.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: CLA Signed, noproductcode

#15200 Upgrade to jakarta.enterprise.concurrent-api 2.0.0
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-2.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#15210 Issue #13177: Remove extra ManagedBeans-War auto feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.managedBeansWar-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.managedBeansWar-2.0.feature
Labels: CLA Signed, in:Java EE Platform, jakartaEE, team:Blizzard

#15165 more detailed logging for adding ejb descriptors
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
Labels: CLA Signed

#15228 Correct IllegalArgument exception to IllegalStateException
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/BasicHttpAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/CustomFormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/FormAuthenticationMechanism.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/LoginToContinueInterceptor.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/IdentityStoreHandlerServiceImpl.java
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/CDIHelper.java
Labels: CLA Signed

#15214 EL Permission investigate
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/resources/META-INF/permissions.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#15215 Issue #15182: Fix CORS tracing to say Access-Control-Request-Header
  dev/com.ibm.ws.webcontainer.cors/src/com/ibm/ws/webcontainer/cors/CorsHelper.java
Labels: CLA Signed

#15226 Update JPA 3.0 Feature Eclipselink to v3.0.0
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.3.0/bnd.bnd
Labels: CLA Signed, in:JPA, jakartaEE, team:Blizzard

#15222 Issue 15221: Adjust wait on renew calculation
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
Labels: noproductcode, team:Core Security, team:Wendigo East

#15235 test automatic close of nondissociatable sharable connection
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15239 Add doPrivs for checking system and SSL properties
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsSSLManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/core/WSX509TrustManager.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15230 [15229] Avoid setting `@RequestScoped` on JAX-RS resources
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15186 fixing windows support for include tag
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ConfigParser.java
Labels: CLA Signed

#15238 Issue 15237: Clear WIM Info from the Audit Manager thread
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ProfileManager.java
Labels: CLA Signed, team:Wendigo East

#15204 Issue #15201: Update the Jakarta EE9 API spec to release version.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authorization-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.security.enterprise-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthentication-2.0/io.openliberty.appAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization-2.0/io.openliberty.appAuthorization-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectorsInboundSecurity-2.0/io.openliberty.connectorsInboundSecurity-2.0.feature
  dev/io.openliberty.jakarta.authentication.2.0/bnd.bnd
  dev/io.openliberty.jakarta.security.2.0/bnd.bnd
Labels: CLA Signed

#15218 Issue #15217: Update jspEngine metatype description
  dev/com.ibm.ws.jsp/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, in:Web Components, team:Sirius

#15248 Remove TODOs from JSP 2.3 code
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/translator/visitor/generator/GeneratorUtilsExtFactoryImpl.java
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/translator/visitor/validator/ElValidatorExtFactoryImpl.java
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/webcontainerext/JspVersionFactoryImpl.java
Labels: CLA Signed, in:Web Components, team:Sirius

#15250 Add additional tests to VisibilityTest
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.classloaderContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jakarta-transactionContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jeeMetadataContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.securityContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.transactionContext-1.0.feature
Labels: CLA Signed, team:Performance

#15223 add addStrictTransportSecurityHeader metatype prop
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, in:Web Components, team:Sirius

#15170 Update mpConfig-2.0 FATs
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20ExceptionTests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20Tests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/unwrap/UnwrapServlet.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20ExceptionServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20ExceptionServer/server.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#15195 Transform jaxws.2.3 integration layer for xmlWS-3.0
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/com.ibm.websphere.appserver.spi.globalhandler/bnd.bnd
  dev/com.ibm.websphere.org.osgi.service.http/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.ejb/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.security/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.web/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.wsat/bnd.bnd
  dev/com.ibm.ws.jaxws.cdi/bnd.bnd
  dev/com.ibm.ws.jaxws.webcontainer/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed

#15231 translatable message for autoCloseConnections
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentTxTestServer/server.xml
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#15193 [15189] Pull in MP Rest Client API/TCK from staging repo
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/rest.client.2.0.bnd
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#15246 delay stop to allow for connection closes
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/TraceTest.java
Labels: CLA Signed, noproductcode

#15243 Issue 15242: Stop CertCheckerTask if the server is stopping
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeCertCheckerTask.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#15208 Fixes for JDBC kerberos support on IBM JDK 8.
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/DB2KerberosContainer.java
  dev/com.ibm.ws.security.jca/src/com/ibm/ws/security/jca/internal/AuthDataServiceImpl.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/KerberosService.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
Labels: CLA Signed, release bug, team:Zombie Apocalypse

#15269 Do not run CI on draft PRs
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15249 Jakarta bundle / feature cleanup
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.enterpriseBeansRemoteClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.ejb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.jta-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/io.openliberty.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/io.openliberty.concurrent-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/resources/l10n/io.openliberty.concurrent-2.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeans-4.0/io.openliberty.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansHome-4.0/io.openliberty.enterpriseBeansHome-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansLite-4.0/io.openliberty.enterpriseBeansLite-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansPersistentTimer-4.0/io.openliberty.enterpriseBeansPersistentTimer-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/enterpriseBeansRemote-4.0/io.openliberty.enterpriseBeansRemote-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/managedBeans-2.0/io.openliberty.managedBeans-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/io.openliberty.mdb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistence-3.0/io.openliberty.persistence-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/com.ibm.websphere.appserver.persistentExecutor-2.0.feature
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_config/bnd.bnd
  dev/com.ibm.ws.jpa.container.ormdiagnostics_3.0_fat/bnd.bnd
  dev/io.openliberty.ejbcontainer.jakarta.fat_tools/bnd.bnd
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.classpath
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.gitignore
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.project
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/bnd.bnd
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/src/jakarta/ejb/EJBException.java
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/test/jakarta/ejb/EJBExceptionTest.java
  dev/io.openliberty.jakarta.soap.2.0/.classpath
  dev/io.openliberty.jakarta.soap.2.0/.project
  dev/io.openliberty.jakarta.soap.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.soap.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.soap.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.soap.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.soap.2.0/bnd.bnd
  dev/io.openliberty.mail.2.0.internal_fat/bnd.bnd
Labels: CLA Signed, ID review not needed, team:Performance

#15233 add allowQueryParamWithNoEqual metatype prop
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, in:Web Components, team:Sirius

#15254 Issue 14975 PR for Update OIDC to switch cache key properly
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
Labels: CLA Signed

#15265 Override `doTrace` to avoid automatic TRACE request rejection
  dev/io.openliberty.org.jboss.resteasy.server/src/com/ibm/websphere/jaxrs/server/IBMRestServlet.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15274 Set batch-2.0 and related features to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.batchSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-batch2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-2.0/io.openliberty.batch-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
Labels: CLA Signed

#15227 Remove some older Jackson 2.x versions
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/build.gradle
  dev/com.ibm.ws.microprofile.openapi.1.1.model/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi.model/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi_fat/build.gradle
  dev/com.ibm.ws.rest.handler.config.openapi/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.openapi/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/.classpath
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/.project
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/.settings/bndtools.core.prefs
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/build.gradle
Labels: CLA Signed

#15289 grpc_fat: expand trace for HelloWorldCDITests
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.xml
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#15224 Skip testEnvironmentConfigSource() on Windows machines
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#15294 Issue #15293: Retry EJB stateful timeout FAT
  dev/com.ibm.ws.ejbcontainer.session.passivation_fat/test-applications/StatefulTimeoutWeb.war/src/com/ibm/ws/ejbcontainer/session/passivation/statefulTimeout/web/StatefulTimeoutServlet.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#15261 potential thread safety issue with HandleList
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/jca/cm/handle/HandleList.java
Labels: CLA Signed, team:Zombie Apocalypse

#15259 Add xmlWS-3.0 auto features
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-xmlws3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlwsEjb-3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlwsSecurity-3.0
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/io.openliberty.xmlBinding.3.0.internal.tools/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed

#15281 Tolerate JMSContext.CLIENT_ACKNOWLEDGE on create session.
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsConnectionImpl.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118058.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSContext/src/jmscontext/web/JMSContextServlet.java
Labels: CLA Signed

#15304 Fix issue with possible NPE from FATTestFramework properties
  dev/com.ibm.ws.jpa_22_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_eclipselink_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_locking_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_ol_fat/fat/src/io/openliberty/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_injection_ejbinwar_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_part01_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_part02_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec10_query_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec20_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_spec21_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/vehicle/web/JPATestServlet.java
Labels: CLA Signed, noproductcode

#15300 Tolerate CWWKC1503W during server shutdown
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15266 Issue #12278: Update to final 2.0.0 WebSocket API JAR
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.0/io.openliberty.websocket-2.0.feature
Labels: CLA Signed, in:Web Components, team:Sirius

#15287 15286 - Jakarta mail 2.0 final release
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mail-2.0/io.openliberty.mail-2.0.feature
Labels: CLA Signed

#15284 Wait for server stop process to end
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractRun.java
  dev/wlp.lib.extract/src/wlp/lib/extract/ShutdownHook.java
Labels: CLA Signed

#15318 Add ch.qos.logback:logback-core:1.1.3 to avoid break
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15324 wsoc fvt: All the buckets need to join the server stop delay party
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/MiscellaneousTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/WebSocket11Test.java
Labels: CLA Signed, noproductcode

#15303 Add new tests for features
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tasks/FeatureBnd.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tasks/FeatureBuilder.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.ejbComponentMetadataDecorator-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jeeMetadataContext-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.contextService-1.0.feature
Labels: CLA Signed, team:Performance

#15292 Allow server.xml to override context root in application.xml
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/ServletConfigurator.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/package-info.java
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfigurator.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
Labels: CLA Signed, enhancement

#15329 Improve metatype desc for tcpOptions addressList props
  dev/com.ibm.ws.channelfw/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, in:Transport, team:Sirius

#12920 test for JAX class injecting into path
  dev/com.ibm.ws.cdi.jee_fat/.classpath
  dev/com.ibm.ws.cdi.jee_fat/bnd.bnd
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi12/fat/tests/InjectIntoPath.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12WebServicesServer/server.xml
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/jaxInjectIntoPathServer/.gitignore
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/jaxInjectIntoPathServer/bootstrap.properties
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/jaxInjectIntoPathServer/server.xml
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/WEB-INF/src/com/ibm/injectintopath/App.java
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/WEB-INF/src/com/ibm/injectintopath/CDIResource.java
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/WEB-INF/src/com/ibm/injectintopath/ClassA.java
Labels: CLA Signed, noproductcode

#14899 refactor how SPI extensions are initilized
  dev/com.ibm.ws.cdi.interfaces/src/io/openliberty/cdi/spi/CDIExtensionMetadata.java
  dev/com.ibm.ws.cdi.internal/resources/com/ibm/ws/cdi/internal/resources/CDI.nlsprops
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/ExtensionArchiveImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/ExtensionArchive.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/WebSphereBeanDeploymentArchive.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/WebSphereCDIDeployment.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BDAFactory.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/ProbeExtensionArchive.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
Labels: CLA Signed, L2 Reviewed

#15321 MP Rest Client 2.0 SSE FATs
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/com.ibm.websphere.appserver.mpRestClient-2.0.feature
  dev/com.ibm.ws.microprofile.rest.client_fat/.classpath
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/build.gradle
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/SseTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient20.sse/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient20.sse/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/GenericSubscriber.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SomeObject.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseResource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/sse/SseMessageBodyReader.java
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#15306 [15305] Pull in https://issues.apache.org/jira/browse/CXF-8378
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/ReferencingAuthenticator.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15308 autoCloseConnections in ConnectionFactoryDefinition
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/ConnectionManagerService.java
  dev/com.ibm.ws.jca_fat_derbyra/bnd.bnd
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyResourceAdapterTest.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAAnnoServlet.java
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/cfd/DerbyRAConnectionFactoryDefinitionServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#15316 config updates to autoCloseConnections
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ConnectionManager.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15326 Fixes the RequestProbe FAT to wait for server config update
  dev/com.ibm.ws.request.probes_fat/fat/src/com/ibm/ws/request/probe/fat/RequestProbeTest.java
  dev/com.ibm.ws.request.probes_fat/publish/servers/ProbeServer/bootstrap.properties
  dev/com.ibm.ws.request.timing/src/com/ibm/ws/request/timing/RequestTimingService.java
Labels: CLA Signed

#15344 Update to use ClassRule on the FATSuite
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/build.gradle
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/BindingTypeWsdlMismatchTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/CXFJMXSupportTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/CatalogFacilityTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/EJBServiceRefBndTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/EndpointPropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HandlerChainTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HandlerChainWithWebServiceClientTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HttpConduitPropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/MTOMTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/PortComponentRefTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/PureCXFTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/ServerSideStubClientTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/VirtualHostTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceContextTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceInWebXMLTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceInWebXMLTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceMonitorTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceRefFeaturesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceRefTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WsBndEndpointOverrideTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WsBndServiceRefOverrideTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/util/ExplodedShrinkHelper.java
Labels: CLA Signed, noproductcode, team:Performance

#15349 Upgrade to Hibernate Validator 6.1.7.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator.cdi/bnd.overrides
  dev/com.ibm.ws.org.hibernate.validator/bnd.bnd
  dev/com.ibm.ws.org.hibernate.validator/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#15352 Update to final Fault Tolerance 3.0 API and TCK
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/faulttolerance.3.0.bnd
Labels: CLA Signed

#15311 Update mpConfig-2.0 to use released versions of MicroProfile and SmallRye Config
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.config/bnd.bnd
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/Config

#15331 Adds a service loader reference to CDIRuntimeImpl (which implements C…
  dev/com.ibm.ws.cdi.weld/resources/META-INF/services/javax.enterprise.inject.spi.CDIProvider
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/AbstractCDIRuntime.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/io.openliberty.jakarta.cdi.3.0/bnd.bnd
  dev/io.openliberty.jakarta.cdi.3.0/resources/META-INF/services/jakarta.enterprise.inject.spi.CDIProvider
  dev/io.openliberty.jakarta.cdi.3.0/src/com/ibm/ws/cdi/provider/service/CDIProviderService.java
  dev/wlp-jakartaee-transform/rules/com.ibm.ws.cdi.weld.CDIProvider.xml.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-CDIRuntimeImpl.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed

#15345 Generate testcontainers config file even if one does not already exist
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15262 Update buckets with missing tested.features in bnd
  dev/com.ibm.ws.cdi.jndi_fat/bnd.bnd
  dev/com.ibm.ws.cdi.lifecycle_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#15340 11793 - return HTTP 415 when JAX-RS request Content-Type header contains an invalid charset
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/helloworld/HelloWorldTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/json/UTF8Test.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.json/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/json/src/com/ibm/ws/jaxrs/fat/json/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/json/src/com/ibm/ws/jaxrs/fat/json/CountryInfo.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/json/src/com/ibm/ws/jaxrs/fat/json/UTF8Resource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/exception/InvalidMediaTypeException.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppErrorReport.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15356 Add default title of "Feature Test Summary"
  .github/ISSUE_TEMPLATE/feature_test_summary.md
Labels: CLA Signed

#15270 Pull in MyFaces API Updates
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/application/Application.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/application/ProjectStage.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/application/StateManager.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/ActionSource.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/EditableValueHolder.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/NamingContainer.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UICommand.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIComponent.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIComponentBase.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIData.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIGraphic.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIInput.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UISelectBoolean.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UISelectMany.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/UIViewRoot.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlBody.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlColumn.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlCommandButton.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlCommandLink.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlDataTable.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlForm.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlGraphicImage.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlHead.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlInputFile.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlInputSecret.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlInputText.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlInputTextarea.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlMessage.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlMessages.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutcomeTargetButton.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutcomeTargetLink.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutputFormat.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutputLabel.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutputLink.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlOutputText.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlPanelGrid.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlPanelGroup.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectBooleanCheckbox.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectManyCheckbox.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectManyListbox.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectManyMenu.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectOneListbox.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectOneMenu.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/component/html/HtmlSelectOneRadio.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/EvaluationException.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/MethodBinding.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/MethodNotFoundException.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/PropertyNotFoundException.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/PropertyResolver.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/ReferenceSyntaxException.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/ValueBinding.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/el/VariableResolver.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/render/ResponseStateManager.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/validator/Validator.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/AttributeTag.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/ConverterTag.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/UIComponentBodyTag.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/UIComponentClassicTagBase.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/UIComponentTag.java
  dev/io.openliberty.jakarta.faces.3.0/src/jakarta/faces/webapp/ValidatorTag.java
Labels: CLA Signed, in:Web Components, team:Sirius

#15358 Ignore server quiesce timeouts in PathParamTest
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/PathParamTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15355 Updates to get tests passing with xmlWS-3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlwsEjb-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlwsSecurity-3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlwsSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/BindingTypeWsdlMismatchTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/EJBServiceRefBndTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HttpConduitPropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/PureCXFTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceInWebXMLTest_Lite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/util/ExplodedShrinkHelper.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/EJBServiceRefBndTest/jaxwstest-2.3_server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/EJBServiceRefBndTest/xmlwsTest-3.0.mf
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/EJBServiceRefBndTest/xmlwstest-3.0_server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/xmlwsTest-3.0.mf
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/xmlwstest-3.0_server.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, team:Performance

#15350 Enable testMultiThreadSecurityContext() CDI 2.0 FAT against EE9
  dev/com.ibm.ws.cdi.2.0_fat/test-applications/secureAsyncEventsApp/src/secureAsyncEventsApp/web/SecureAsyncEventsServlet.java
Labels: CLA Signed, in:CDI/2.0, noproductcode

#15334 info message with leaked connection stack
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/jca/cm/handle/HandleList.java
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/jca/cm/handle/HandleListInterface.java
  dev/com.ibm.ws.jca.cm/resources/com/ibm/ws/jca/cm/internal/resources/J2CAMessages.nlsprops
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/HCMDetails.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/JDBC43Test.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Zombie Apocalypse

#15257 Add ms sql server support and containerized tests
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.project
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/com.ibm.ws.transactions.fat.utils.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/DualServerDynamicMSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/MSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/transaction_fat.bnd
Labels: CLA Signed

#15361 Pull the 3.0 binaries from Maven Central instead of IBM DHE
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#15365 Fix Java 2 Security errors in io.openliberty.restfulWS30.fat
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/appandresource/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/jsonb/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/validator/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/webXmlApp/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/webXmlNoApp/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/xml-with-jaxb/server.xml
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/xml-without-jaxb/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15370 Revert "Add ms sql server support and containerized tests"
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.project
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/com.ibm.ws.transactions.fat.utils.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/DualServerDynamicMSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/MSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/transaction_fat.bnd
Labels: CLA Signed

#15267 Add test for SQLServer with SSL
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/container-files/mssql.conf
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/container-files/mssql.key
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/container-files/mssql.pem
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
Labels: CLA Signed, noproductcode

#14944 Enable junit report
  .github/workflow-scripts/check-fat-failures.sh
  .github/workflow-scripts/generate-params.sh
  .github/workflow-scripts/reclaim-disk-space.sh
  .github/workflow-scripts/run-fat-build.sh
  .github/workflow-scripts/run-unit-tests.sh
  .github/workflow-scripts/upload-unit-tests.sh
  .github/workflow-scripts/validate-copyright-headers.sh
  .github/workflows/cleanup-duplicate-runs.yml
  .github/workflows/openliberty-ci.yml
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15360 Update wsgen and wsimport tooling for xmlWS-3.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlBinding-3.0/io.openliberty.xmlBinding-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/src/com/ibm/ws/jaxws/tools/WsToolsUtils.java
  dev/io.openliberty.xmlBinding.3.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.classpath
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.gitignore
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.project
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsgen/bnd.bnd
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.classpath
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.gitignore
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.project
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools.wsimport/bnd.bnd
  dev/io.openliberty.xmlws.3.0.internal.tools/.classpath
  dev/io.openliberty.xmlws.3.0.internal.tools/.gitignore
  dev/io.openliberty.xmlws.3.0.internal.tools/.project
  dev/io.openliberty.xmlws.3.0.internal.tools/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlws.3.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlws.3.0.internal.tools/src/com/sun/tools/ws/wscompile/WsimportTool.java
  dev/io.openliberty.xmlws.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/WsGen.java
  dev/io.openliberty.xmlws.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/WsImport.java
  dev/io.openliberty.xmlws.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/ant/WsImportTask.java
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
Labels: CLA Signed

#15380 Add timestamps to mvnOutput when downloading artifacts
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#15375 Upgrade to Hibernate Validator 7.0.0.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.hibernate.validator.7.0/bnd.bnd
  dev/io.openliberty.org.hibernate.validator.7.0/bnd.overrides
  dev/io.openliberty.org.hibernate.validator.7.0/resources/org/hibernate/validator/ValidationMessages.properties
  dev/io.openliberty.org.hibernate.validator.cdi.7.0/bnd.bnd
  dev/io.openliberty.org.hibernate.validator.cdi.7.0/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#15359 Add capability to identify errorCodes and sqlStates as stale connections
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/bnd.bnd
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/DSConfig.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2Helper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iNativeHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iToolboxHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DataDirectConnectSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyNetworkClientHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/MicrosoftSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/SybaseHelper.java
  dev/com.ibm.ws.jdbc_fat_v41/.classpath
  dev/com.ibm.ws.jdbc_fat_v41/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_v41/build.gradle
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/ErrorMappingTest.java
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41.errorMap/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41.errorMap/server.xml
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingApp/src/jdbc/fat/v41/errormap/web/ErrorMappingTestServlet.java
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingDriver/src/jdbc/fat/v41/errormap/driver/ErrorMapConnection.java
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingDriver/src/jdbc/fat/v41/errormap/driver/ErrorMapConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingDriver/src/jdbc/fat/v41/errormap/driver/ErrorMapDataSource.java
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingDriver/src/jdbc/fat/v41/errormap/driver/ErrorMapDataSourceImpl.java
Labels: CLA Signed, ID reviewed

#15357 Tolerate SocketException
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryDBTranlogTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
  dev/com.ibm.ws.wsat.recovery_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
Labels: CLA Signed, noproductcode
