Repository OpenLiberty/open-liberty, pull requests merged in 2020-04, with the labels that each got.

#11565 11479: Enhance RP tracking cookie creation/update logic
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RelyingPartyTracker.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/RelyingPartyTrackerTest.java
Labels: CLA Signed, team:Security SSO

#11490 Minor Fix to LDAPHelper
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapHelper.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/LdapHelperTest.java
Labels: CLA Signed, team:Wendigo East

#11555 Fix unset token
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/DeleteAuthCacheImpl.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/CustomCacheKeyProvider.java
Labels: CLA Signed

#11538 createXAException garbles message parameters
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/AdapterUtil.java
Labels: CLA Signed, team:Zombie Apocalypse

#11554 failover1serv test lacks SocketPermission for Derby
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/publish/servers/com.ibm.ws.concurrent.persistent.fat.failover1serv/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11562 tolerate 17+ minute delay in testTransactionTimeoutSuspendedTransactionFENoPolling
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/PersistentErrorTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11587 Add MicroProfile 3.3 to microProfile3 server.xml template
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile3/server.xml
Labels: CLA Signed

#11558 HADB Retry and log close tidy
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLogManager.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#11051 add code comments
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/CoverageMapEndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
Labels: CLA Signed

#11579 Add support for ValidateOnExecution(None) in JAX-RS
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/beanvalidation/JAXRSClientServerValidationTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.beanvalidation/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs/fat/beanvalidation/BookStoreWithValidation.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs/fat/beanvalidation/ClientTestServlet.java
Labels: CLA Signed, noproductcode

#11583 AutonomicalPolling1ServerTest work around transaction timeout
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/publish/servers/com.ibm.ws.concurrent.persistent.fat.autonomicalpolling1serv/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11568 AutonomicalPolling1ServerTest sees J2CA0079E and J2CA008W after server shutdown
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/fat/src/com/ibm/ws/concurrent/persistent/fat/autonomicalpolling1serv/AutonomicalPolling1ServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11531 Issue #11190: Provide better error handling of mis-configuration in a…
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/AcmeProvider.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeApplicationStateListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeConfigService.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/CSROptions.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/web/AcmeAuthorizationServlet.java
  dev/com.ibm.ws.security.acme/src/org/shredzone/acme4j/connector/HttpConnector.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/internal/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/PebbleDriver.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigBringUp.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/AcmeCA.java
Labels: CLA Signed, ID reviewed, team:Wendigo East

#11483 test connectionManager pool size increase and app restart
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/DependantApplicationTest.java
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11576 EJB Remote CustomBindings SimpleBindingName and JNDIName
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/JNDINameWeb.war/src/com/ibm/ejb2x/jndiName/web/JNDINameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/SimpleBindingNameWeb.war/src/com/ibm/ejb3x/SimpleBindingName/web/SimpleBindingNameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
Labels: CLA Signed

#11548 Port jca bean validation tests
  dev/com.ibm.ws.jca_fat_bval/.classpath
  dev/com.ibm.ws.jca_fat_bval/.project
  dev/com.ibm.ws.jca_fat_bval/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_bval/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca_fat_bval/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca_fat_bval/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca_fat_bval/bnd.bnd
  dev/com.ibm.ws.jca_fat_bval/fat/src/com/ibm/ws/jca/fat/bval/BeanValidationTest.java
  dev/com.ibm.ws.jca_fat_bval/fat/src/com/ibm/ws/jca/fat/bval/FATSuite.java
  dev/com.ibm.ws.jca_fat_bval/publish/files/server-invalid-cf.xml
  dev/com.ibm.ws.jca_fat_bval/publish/files/server-invalid-interaction-spec.xml
  dev/com.ibm.ws.jca_fat_bval/publish/files/server-invalid-ra.xml
  dev/com.ibm.ws.jca_fat_bval/publish/files/server-with-mdb.xml
  dev/com.ibm.ws.jca_fat_bval/publish/servers/com.ibm.ws.jca.fat.bval/.gitignore
  dev/com.ibm.ws.jca_fat_bval/publish/servers/com.ibm.ws.jca.fat.bval/bootstrap.properties
  dev/com.ibm.ws.jca_fat_bval/publish/servers/com.ibm.ws.jca.fat.bval/server.xml
  dev/com.ibm.ws.jca_fat_bval/test-applications/jca-bval/src/web/RABValServlet.java
  dev/com.ibm.ws.jca_fat_bval/test-applications/jca-bval/src/web/mdb/BValMessageDrivenBean.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/resources/META-INF/basic-constraints.xml
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/resources/META-INF/validation.xml
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ActivationSpecImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ConnectionFactoryImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ConnectionImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ConnectionSpecImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/InteractionImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/InteractionSpecImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ManagedConnectionImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/MappedRecordImpl.java
  dev/com.ibm.ws.jca_fat_bval/test-resourceadapters/BValRA/src/com/ibm/bval/jca/adapter/ResourceAdapterImpl.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FATServletClient.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11575 Issue #11572: Fix Calendar EJB timer with no expiration
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ContainerTx.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/TimerNpImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#11578 11479: Initial end_session logic for RP tracking
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RelyingPartyTracker.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/RelyingPartyTrackerTest.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
Labels: CLA Signed, team:Security SSO

#11530 Add new message and console format names to metatype.xml
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/ConsoleFormatTest.java
Labels: CLA Signed, ID review not needed, ID reviewed, L2 ReviewNotRequired

#11591 Wrong Type for Simple Timer for mpMetrics-2.3 and Concurrent Gauge mpMetrics-2.x
  dev/com.ibm.ws.microprofile.metrics.cdi.2.0/src/io/astefanutti/metrics/cdi20/MetricProducer.java
  dev/com.ibm.ws.microprofile.metrics.cdi.2.3/src/io/astefanutti/metrics/cdi23/MetricProducer.java
Labels: CLA Signed, release bug

#11566 Use try with resources and remove sharedserver references
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/CDITestBase.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AppConfigPopTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/CDITestBase.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/CDIInjectionTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11220 Adding new JSONObject class for creating new Log events
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils1_1.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils_JSON.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/data/JSONObject.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#11434 9633 new LTPA API and moving auto security features from CL to OL
  dev/com.ibm.websphere.appserver.api.basics/bnd.bnd
  dev/com.ibm.websphere.appserver.api.security.spnego/bnd.bnd
  dev/com.ibm.websphere.appserver.api.security/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoAppSecurityClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoSecurityS4U2-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.security-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.appmanager-1.0.feature
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/auth/ValidationFailedException.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/auth/package-info.java
  dev/com.ibm.ws.security.jaas.common/bnd.bnd
  dev/com.ibm.ws.security.token/bnd.bnd
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/ValidationResultImpl.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/token/ValidationResult.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/token/WSSecurityPropagationHelper.java
  dev/com.ibm.ws.security.token/src/com/ibm/wsspi/security/token/package-info.java
Labels: CLA Signed

#11593 Migrate JAXRS WebContainer FAT testcases to Open Liberty
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.project
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/TestUtils.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/disablejaxrs11/DisableJaxRS11Test.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/helloworld/HelloWorldTest.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/jsonp/JaxRsJsonPTest.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/multipart/MultipartTest.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat.thirdpartylib/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat.thirdpartylib/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat.thirdpartylib/server.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat.thirdpartylib/upload.jsp
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/com.ibm.ws.jaxrs2x.fat/server.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/jaxrs2x.service.DisableJaxRS11/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/jaxrs2x.service.DisableJaxRS11/server.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/jaxrs2x.service.JaxRsJsonPTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/publish/servers/jaxrs2x.service.JaxRsJsonPTest/server.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/disablejaxrs11/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/disablejaxrs11/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/helloworld/resources/.gitignore
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/helloworld/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/helloworld/src/com/ibm/ws/jaxrs2x/fat/helloworld/HelloWorldApplication.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/helloworld/src/com/ibm/ws/jaxrs2x/fat/helloworld/HelloWorldResource.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/jsonp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/jsonp/src/com/ibm/ws/jaxrs2x/fat/jsonp/service/JsonPResource.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/jsonp/src/com/ibm/ws/jaxrs2x/fat/jsonp/service/TestApplication.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/thirdpartylib/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/thirdpartylib/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/thirdpartylib/src/com/ibm/ws/jaxrs2x/fat/thirdparty/multipart/MultiPartApplication.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/thirdpartylib/src/com/ibm/ws/jaxrs2x/fat/thirdparty/multipart/MultipartServiceImpl.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/test-applications/thirdpartylib/src/com/ibm/ws/jaxrs2x/fat/thirdparty/multipart/UploadServiceImpl.java
Labels: CLA Signed

#11603 Brining JCA classloading fat to OL
  dev/com.ibm.ws.jca_fat_classloading/.classpath
  dev/com.ibm.ws.jca_fat_classloading/.project
  dev/com.ibm.ws.jca_fat_classloading/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_classloading/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca_fat_classloading/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca_fat_classloading/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca_fat_classloading/bnd.bnd
  dev/com.ibm.ws.jca_fat_classloading/build.gradle
  dev/com.ibm.ws.jca_fat_classloading/fat/src/com/ibm/ws/jca/fat/classloading/FATSuite.java
  dev/com.ibm.ws.jca_fat_classloading/fat/src/com/ibm/ws/jca/fat/classloading/JCAClassLoadingTest.java
  dev/com.ibm.ws.jca_fat_classloading/publish/.gitignore
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityAll_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityInvalid_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityMatch_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityMismatch_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testApiTypeVisibilityNone_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testClassSpaceRestriction_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testInvalidClassProviderRef_server.xml
  dev/com.ibm.ws.jca_fat_classloading/publish/servers/com.ibm.ws.jca.fat.classloading/bootstrap.properties
  dev/com.ibm.ws.jca_fat_classloading/publish/servers/com.ibm.ws.jca.fat.classloading/server.xml
  dev/com.ibm.ws.jca_fat_classloading/test-applications/ClassLoadingApp/resources/META-INF/application.xml
  dev/com.ibm.ws.jca_fat_classloading/test-applications/fvtweb/src/web/ClassLoadingTestServlet.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyActivationSpec.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyME.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyMessage.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyQueue.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyResourceAdapter.java
  dev/com.ibm.ws.jca_fat_classloading/test-resourceadapters/fvtra/src/ra/DummyTopic.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#9914 add ConnectionTTL to plugin-cfg.xml, along with persistTimeoutReduction parm in pluginConfiguration
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype-mbeans.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/osgi/mbeans/PluginGeneratorTest.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:Web Components, release bug, team:Sirius

#11624 Get things building in eclipse again and other cleanup
  dev/com.ibm.ws.collector.manager/.classpath
  dev/com.ibm.ws.collector/.classpath
  dev/com.ibm.ws.grpc.servlet/.classpath
  dev/com.ibm.ws.grpc_fat/.project
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/grpc/SimpleTest.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/.classpath
  dev/com.ibm.ws.jca_fat_classloading/.classpath
  dev/com.ibm.ws.jca_fat_classloading/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.probe.servlet/.classpath.gradle
  dev/com.ibm.ws.wsat.webservice/.classpath.gradle
Labels: CLA Signed, noproductcode, team:Performance

#11569 Issue 11184: Remove app-early and trace fixes for AcmeCA
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#11602 Repeat the jsonp1.1_fat for jakarta ee9
  dev/com.ibm.ws.jsonp.1.1_fat/bnd.bnd
  dev/com.ibm.ws.jsonp.1.1_fat/build.gradle
  dev/com.ibm.ws.jsonp.1.1_fat/fat/src/com/ibm/ws/jsonp11/fat/FATSuite.java
  dev/com.ibm.ws.jsonp.1.1_fat/test-applications/JSONP11fat/src/web/JSONP11Servlet.java
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/annotation/TestServlet.java
  dev/fattest.simplicity/src/componenttest/annotation/processor/TestServletProcessor.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
Labels: jakartaEE, team:OSGi Infrastructure

#11629 11479: Finalize RP tracking logic
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/api/OAuth20Provider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/internal/LibertyOAuth20Provider.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuthClientTracker.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/internal/LibertyOAuth20ProviderTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/OAuthClientTrackerTest.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
Labels: CLA Signed, team:Security SSO

#11485 rollback is not always exceptional
  dev/com.ibm.ws.transaction.context/bnd.bnd
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextImpl.java
  dev/com.ibm.ws.transaction.context_test/.classpath
  dev/com.ibm.ws.transaction.context_test/.gitignore
  dev/com.ibm.ws.transaction.context_test/.project
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.context_test/bnd.bnd
  dev/com.ibm.ws.transaction.context_test/build-unittest.xml
  dev/com.ibm.ws.transaction.context_test/test/src/com/ibm/ws/transaction/context/internal/TransactionContextTest.java
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction/resources/security/defaultKey.jks
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction/resources/security/defaultTrust.jks
  dev/com.ibm.ws.transaction.core_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/AsyncBean.java
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/SimpleServlet.java
Labels: CLA Signed

#11599 Issue #11596: Wait for CWWKS4105I LTPA configuration is ready
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11634 choose ManagedTask constant based on EE spec level
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.contextService-1.0.feature
  dev/com.ibm.ws.concurrent.persistent/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.context/bnd.bnd
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextDescriptorImpl.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextManager.java
  dev/com.ibm.ws.microprofile.health.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/impl/HealthCheck20ExecutorImpl.java
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/impl/HealthExecutorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#11605 Fix processing of windows paths that start with a variable
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/XMLConfigParserTest.java
Labels: CLA Signed

#11622 Fix the DB2 DDL for the com.ibm.ws.jpa_spec10_query_fat tests olgh801…
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/olgh8014/ddl/WEB-INF/classes/JPA_OLGH8014_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/olgh8294/ddl/WEB-INF/classes/JPA_OLGH8294_CREATE_DB2.ddl
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#11501 reintroduce oidcserverimpl change
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcServerImpl.java
Labels: CLA Signed

#11320 changed error message
  dev/com.ibm.ws.security.saml.sso/resources/com/ibm/ws/security/saml/sso20/internal/resources/SamlSso20Messages.nlsprops
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/internal/AssertionToSubject.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#11608 Test managed executor from CDI producer used by ServletContainerInitializer
  dev/com.ibm.ws.concurrent_fat_cdi/.classpath
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDI2Test.java
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi2/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi2/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/src/concurrent/cdi2/web/ConcurrentCDI2AppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/src/concurrent/cdi2/web/ConcurrentCDI2Servlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/src/concurrent/cdi2/web/ConcurrentCDI2ServletContainerInit.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/src/concurrent/cdi2/web/ConcurrentCDI2ServletContextListener.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDI2App/src/concurrent/cdi2/web/ExecutorProducer.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11616 Add secure attribute set for None value
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed

#11618 fixed metatype description
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.ssl/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID review not needed

#11647 remove EE Concurrency dependency from transaction context
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.contextpropagation.1.0/src/com/ibm/ws/microprofile/context/TransactionContextProvider.java
  dev/com.ibm.ws.transaction.context/bnd.bnd
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextProviderImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#11632 Issue #11619: The CSR subject attributes (c,st,l,o,ou,cn) will now be…
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.acme/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeConfig.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/util/AcmeConstants.java
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/internal/AcmeConfigTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeURISimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.acmeconfigbringup/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/AcmeCA.java
Labels: CLA Signed, team:Wendigo East

#11559 SSL Channel: fix WsByteBuffer double release race condition
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLConnectionLink.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLHandshakeCompletedCallback.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLReadServiceContext.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLUtils.java
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLWriteServiceContext.java
Labels: CLA Signed, in:Transport, release bug, team:Sirius

#11651 Fix incorrect spelling of programmatically in bnd.bnd
  dev/build.example_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat_derbyra/bnd.bnd
  dev/com.ibm.ws.jsp.2.3_fat/bnd.bnd
  dev/com.ibm.ws.repository_fat/bnd.bnd
  dev/com.ibm.ws.transaction.cloudsim_fat/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat/bnd.bnd
  dev/com.ibm.ws.transport.http.compression_fat/bnd.bnd
  dev/com.ibm.ws.wsat_fat/bnd.bnd
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11650 Add java 2 security trace for testAppOrder
  dev/com.ibm.ws.app.manager_fat/publish/files/appOrder/serverBarFoo.xml
  dev/com.ibm.ws.app.manager_fat/publish/files/appOrder/serverFooBar.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11492 Provide new RoleMethodAuthUtil for JAX-RS and other to use
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/providers/security/SecurityAnnoProviderRegister.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/security/LibertyAuthFilter.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/security/LibertySimpleAuthorizingInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageUtils.java
  dev/com.ibm.ws.security.authorization.util/.classpath
  dev/com.ibm.ws.security.authorization.util/.gitignore
  dev/com.ibm.ws.security.authorization.util/.project
  dev/com.ibm.ws.security.authorization.util/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.authorization.util/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.authorization.util/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.authorization.util/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.authorization.util/bnd.bnd
  dev/com.ibm.ws.security.authorization.util/src/com/ibm/ws/security/authorization/util/RoleMethodAuthUtil.java
  dev/com.ibm.ws.security.authorization.util/src/com/ibm/ws/security/authorization/util/UnauthenticatedException.java
  dev/com.ibm.ws.security.authorization.util/src/com/ibm/ws/security/authorization/util/package-info.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/RoleMethodAuthUtilTest.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/classes/DenyAllOnClass.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/classes/NoAnnotationsOnClass.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/classes/PermitAllOnClass.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/classes/PrincipalImpl.java
  dev/com.ibm.ws.security.authorization.util/test/com/ibm/ws/security/authorization/util/classes/RolesAllowedOnClass.java
Labels: CLA Signed, in:JAX-RS, in:Security, team:Wendigo West

#11536 11500-create SprintBoot 22
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version22.test.app/.classpath
  dev/com.ibm.ws.springboot.support.version22.test.app/.project
  dev/com.ibm.ws.springboot.support.version22.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version22.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version22.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version22.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version22.test.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/CustomizationBean.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/MvcConfig.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/TestWebFilter.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/TestWebListener.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/TestWebServlet.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/java/com/ibm/ws/springboot/support/version22/test/app/WebSecurityConfig.java
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/public/file.weby
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/public/useJarUrlsTest.html
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/templates/hello.html
  dev/com.ibm.ws.springboot.support.version22.test.app/src/main/resources/templates/login.html
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests22.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: CLA Needed, CLA Signed, in:SpringBoot

#11660 Fix SimpleJsonTest Java 2 Security Errors
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.simpleJson/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#11690 Ee9 build fixes
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature
  dev/fattest.simplicity/bnd.bnd
  dev/wlp-jakartaee-transform/bnd.bnd
Labels: jakartaEE

#11683 Social login: Minor fixes for SameSite cookies to work
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/EndpointServices.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/EndpointServlet.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/EndpointServicesTest.java
Labels: CLA Signed, team:Security SSO

#11662 Fix ACE in bindings test
  dev/com.ibm.ws.ejbcontainer.bindings_fat/publish/servers/com.ibm.ws.ejbcontainer.bindings.fat.server/server.xml
Labels: CLA Signed, noproductcode

#11625 Port jca configprops
  dev/com.ibm.ws.jca_fat_configprops/.classpath
  dev/com.ibm.ws.jca_fat_configprops/.project
  dev/com.ibm.ws.jca_fat_configprops/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_configprops/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca_fat_configprops/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca_fat_configprops/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca_fat_configprops/bnd.bnd
  dev/com.ibm.ws.jca_fat_configprops/fat/src/com/ibm/ws/jca/fat/configprops/FATSuite.java
  dev/com.ibm.ws.jca_fat_configprops/fat/src/com/ibm/ws/jca/fat/configprops/JCAConfigPropsTest.java
  dev/com.ibm.ws.jca_fat_configprops/publish/servers/com.ibm.ws.jca.fat.configprops/bootstrap.properties
  dev/com.ibm.ws.jca_fat_configprops/publish/servers/com.ibm.ws.jca.fat.configprops/server.xml
  dev/com.ibm.ws.jca_fat_configprops/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat_configprops/test-applications/fvtweb/src/web/ConfigPropsRATestServlet.java
  dev/com.ibm.ws.jca_fat_configprops/test-resourceadapters/MapRA/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_configprops/test-resourceadapters/MapRA/resources/META-INF/wlp-ra.xml
  dev/com.ibm.ws.jca_fat_configprops/test-resourceadapters/MapRA/src/fat/configpropsra/adapter/MapManagedConnectionFactory.java
  dev/com.ibm.ws.jca_fat_configprops/test-resourceadapters/MapRA/src/fat/configpropsra/adapter/MapResourceAdapter.java
Labels: noproductcode, team:Zombie Apocalypse

#11631 Update SCR to 2.1.17.ibm20200407-1
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#11681 Fix type iRequestImpl should be iResponseImpl
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/osgi/response/IResponseImplTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11644 Update jsonFieldMappings metatype.properties to reflect field omissio…
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#11695 Rejig config of transient retry parameters
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.transaction.cloudsim_fat/publish/files/longPeerStaleTimeServer2/server.xml
Labels: CLA Signed

#11526 NLS PII returns from Shipment 2 for 20.0.0.4
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype_de.properties
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#11769 Fix failing checkpii test
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
Labels: CLA Signed, ID reviewed

#11684 Fix ResourceInfoAtStartupTest Java 2 Security Errors
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.resourceinfoatstartup/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#11702 gRPC servlet startup improvements
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServletApplication.java
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServletContainerInitializer.java
  dev/com.ibm.ws.grpc.servlet/test/com/ibm/ws/grpc/servlet/GrpcServletTest.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http2/GrpcServletServices.java
Labels: CLA Signed, in:Transport, team:Sirius

#11763 Issue 11727: Fix read and write file unit tests for Win
  dev/com.ibm.ws.security.acme/test/com/ibm/ws/security/acme/internal/AcmeConfigTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#11729 testPersistentExecPolling unable to get arithmetic sequence of polls in 20 attempts
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/test-applications/autonomicalpolling1servApp/src/autonomicalpolling1serv/web/AutonomicalPolling1ServerTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11725 testNewFailOverEnabledInstanceWhileServerIsRunning warnings to ignore
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/SwitchFromSingleInstanceToFailOverTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11731 testMultipleInstancesCompeteToRunOneLateTaskPC gets FFDC for NullPointerException
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerCoordinatedPollingTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11745 send 401 instead of 403 on redirect to idp
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/sp/Solicited.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/sp/Unsolicited.java
Labels: CLA Signed

#11759 Upgrade to Yasson 1.0.7
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.clientcontainer.json_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.bnd
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#11580 Preserve HTTP response code in mpOpenTracing
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
  dev/com.ibm.ws.opentracing.1.x_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATMPOpenTracing.java
  dev/com.ibm.ws.opentracing.1.x_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATUtilsServer.java
  dev/com.ibm.ws.opentracing.1.x_fat/fat/src/com/ibm/ws/testing/opentracing/test/TestAppException.java
  dev/com.ibm.ws.opentracing.1.x_fat/test-applications/mpOpenTracing/src/com/ibm/ws/testing/mpOpenTracing/MPOpenTracing.java
  dev/com.ibm.ws.opentracing.1.x_fat/test-bundles/opentracing.mock/src/com/ibm/ws/opentracing/mock/OpentracingMockTracer.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingContainerFilter.java
Labels: CLA Signed

#11667 updates to bring us closer to aligning with Jakarta for Concurrency spec
  dev/com.ibm.ws.concurrent.mp_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentTxTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentTxApp/src/concurrent/mp/fat/tx/web/MPConcurrentTxTestServlet.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/LastExecutionImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/TaskLifeCycleCallback.java
  dev/com.ibm.ws.concurrent_fat_policy/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_policy/publish/servers/com.ibm.ws.concurrent.fat.policy/server.xml
  dev/com.ibm.ws.concurrent_fat_policy/test-applications/concurrentpolicyfat/src/web/ConcurrentPolicyFATServlet.java
  dev/com.ibm.ws.concurrent_fat_policy/test-applications/concurrentpolicyfat/src/web/CountingTask.java
  dev/com.ibm.ws.concurrent_fat_policy/test-applications/concurrentpolicyfat/src/web/TaskListener.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextManager.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/services/impl/HealthCheck20ExecutorImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/services/impl/HealthExecutorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#11688 Append interface to simple-binding-name for beans with multiple interfaces
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/NoInterfaceBindingsTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingAbstractServlet.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/NameSpaceBinder.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/SystemNameSpaceBinderImpl.java
Labels: CLA Signed

#11712 Improve ReferenceContext trace
  dev/com.ibm.ws.injection.core/src/com/ibm/ws/injectionengine/ReferenceContextImpl.java
Labels: CLA Signed, in:Java EE Platform, team:Blizzard, was.serviceability

#11657 Adjust EJB Calendar Timer Create Time
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/util/ParsedScheduleExpression.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#11663 Port JCA Dynamic Config
  dev/com.ibm.ws.jca_fat_dynamicConfig/.classpath
  dev/com.ibm.ws.jca_fat_dynamicConfig/.project
  dev/com.ibm.ws.jca_fat_dynamicConfig/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_dynamicConfig/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca_fat_dynamicConfig/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca_fat_dynamicConfig/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca_fat_dynamicConfig/bnd.bnd
  dev/com.ibm.ws.jca_fat_dynamicConfig/fat/src/com/ibm/ws/jca/fat/dynamicConfig/DynaCfgTest.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/fat/src/com/ibm/ws/jca/fat/dynamicConfig/FATSuite.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/publish/servers/com.ibm.ws.jca.fat.dynamicConfig/bootstrap.properties
  dev/com.ibm.ws.jca_fat_dynamicConfig/publish/servers/com.ibm.ws.jca.fat.dynamicConfig/server.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/dynaCfgTestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/dynaCfgTestApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/dynaCfgTestApp/resources/package.properties
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/resources/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/resources/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/src/web/DynamicConfigTestServlet.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-applications/fvtweb/src/web/mdb/DynaCfgMessageDrivenBean.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/resources/META-INF/ra.xml
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgActivationSpec.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgConnection.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgConnectionRequestInfo.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgDataSource.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgDatabaseMetaData.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgManagedConnection.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgManagedConnectionFactory.java
  dev/com.ibm.ws.jca_fat_dynamicConfig/test-resourceadapters/dcra/src/com/ibm/test/dynamicconfigadapter/DynaCfgResourceAdapter.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11628 Port JCA Duplicates fat
  dev/com.ibm.ws.jca_fat_duplicates/.classpath
  dev/com.ibm.ws.jca_fat_duplicates/.project
  dev/com.ibm.ws.jca_fat_duplicates/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_duplicates/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jca_fat_duplicates/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jca_fat_duplicates/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jca_fat_duplicates/bnd.bnd
  dev/com.ibm.ws.jca_fat_duplicates/fat/src/com/ibm/ws/jca/fat/duplicates/DuplicateResourceAdaptersTest.java
  dev/com.ibm.ws.jca_fat_duplicates/fat/src/com/ibm/ws/jca/fat/duplicates/FATSuite.java
  dev/com.ibm.ws.jca_fat_duplicates/publish/servers/com.ibm.ws.jca.fat.duplicates/bootstrap.properties
  dev/com.ibm.ws.jca_fat_duplicates/publish/servers/com.ibm.ws.jca.fat.duplicates/server.xml
  dev/com.ibm.ws.jca_fat_duplicates/test-resourceadapters/DuplicateRA/resources/META-INF/ra.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11710 Issue #11709: Don't wait for feature updates as there are none
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11178 GA of EJB persistent timer fail over
  dev/com.ibm.ws.concurrent.persistent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.ejbcontainer.timer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#11316 GA classProviderRef for JAAS custom login modules
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/internal/ModuleConfig.java
Labels: CLA Signed, team:Zombie Apocalypse

#11529 use newNetwork
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/PlaintextTests.java
Labels: CLA Signed, noproductcode

#11782 Correct the classname in tr.exit
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionBinding.java
Labels: CLA Signed

#11686 Increate supported version from 6 to 9.
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/jandex/internal/SparseIndexReader.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/jandex/internal/SparseIndexReaderVersionImpl_V2.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/data/jandex/AnnoChildWithDefault.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/data/jandex/AnnoChildWithoutDefault.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/data/jandex/AnnoParentWithDefault.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/data/jandex/AnnoParentWithoutDefault.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/anno/test/data/jandex/AnnoTarget.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/JandexSparseReadTest.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/JandexTestUtils.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/SparseIndexPerfTest_Samples.java
  dev/com.ibm.ws.org.jboss.jandex/bnd.bnd
Labels: CLA Signed

#11592 Fix prometheus/open-metrics format for multiple metrics with same name
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/helper/PrometheusBuilder.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/writer/PrometheusMetricWriter.java
  dev/com.ibm.ws.microprofile.metrics.2.3/src/com/ibm/ws/microprofile/metrics23/helper/PrometheusBuilder23.java
  dev/com.ibm.ws.microprofile.metrics.2.3/src/com/ibm/ws/microprofile/metrics23/writer/PrometheusMetricWriter23.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/helper/PrometheusBuilder.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/helper/Util.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/writer/PrometheusMetricWriter.java
Labels: CLA Signed, release bug

#11790 Issue #11786: Add Jakarta Annotation API 2.0.0.RC1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jakarta.annotation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature
  dev/com.ibm.websphere.jakarta.annotation.2.0/.classpath
  dev/com.ibm.websphere.jakarta.annotation.2.0/.gitignore
  dev/com.ibm.websphere.jakarta.annotation.2.0/.project
  dev/com.ibm.websphere.jakarta.annotation.2.0/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.jakarta.annotation.2.0/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.websphere.jakarta.annotation.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.jakarta.annotation.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.websphere.jakarta.annotation.2.0/bnd.bnd
Labels: in:Java EE Platform, team:Blizzard

#11779 Ejb custom bindings remote-home-binding, interface binding-name, and component-id
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/BindingNameWeb.war/src/com/ibm/ejb3x/BindingName/web/BindingNameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/ComponentIDBndWeb.war/src/com/ibm/ejb3x/ComponentIDBnd/web/ComponentIDBndTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3BndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/bnd/web/BindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultComponentBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/HomeBindingNameWeb.war/src/com/ibm/ejb3x/HomeBindingName/web/HomeBindingNameTestServlet.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/NoInterfaceBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/noInterface/bnd/web/NoInterfaceBindingAbstractServlet.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
Labels: CLA Signed

#11705 Issue #11704: Add traces to SameSite Server
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11707 11645: grpc test updates
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/publish/servers/FATServer/dropins/grpc_helloworld_client.war
  dev/com.ibm.ws.grpc_fat/publish/servers/FATServer/dropins/grpc_helloworld_servlet.war
  dev/com.ibm.ws.grpc_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/app1/src/app1/web/TestServletA.java
Labels: CLA Signed, noproductcode

#11749 Allow warning from JNDI
  dev/com.ibm.ws.injection_fat/fat/src/com/ibm/ws/injection/fat/DSDTest.java
Labels: CLA Signed, noproductcode

#11792 Filter out spring boot 2.2 dependencies
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
Labels: CLA Signed

#11751 Correct redirect location
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#11776 Fix NPE in JaxRsMonitorFilter when it is not called as ContainerRequestFilter
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
Labels: CLA Not Needed, CLA Signed, CLA trivial

#11758 Upgrade from ASM 7.3.1 to 8.0.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoVisitor.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoVisitor_Annotation.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/targets/internal/AnnotationTargetsVisitor.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/AnnotationVisitorImpl_Info.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/ClassVisitorImpl_Info.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsVisitorAnnotationBaseImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsVisitorClassImpl.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/ByteCodeMetaData.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/class_scanner/ano/AsmClassAnalyzer.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/MonitoringProxyActivator.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ClassAvailableHookClassAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ProbeInjectionClassAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/ProbeMethodAdapter.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/bci/remap/AddVersionFieldClassAdapter.java
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/bnd.overrides
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/CheckInstrumentableClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/DeferConstructorProcessingMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/RasMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/FFDCIgnoreAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/InjectedTraceAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigClassVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigPackageVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceObjectFieldAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceOptionsAnnotationVisitor.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
  dev/com.ibm.ws.request.probes/src/com/ibm/ws/request/probe/bci/internal/RequestProbeClassVisitor.java
  dev/com.ibm.ws.request.probes/src/com/ibm/ws/request/probe/bci/internal/RequestProbeMethodAdapter.java
Labels: CLA Signed

#11799 avoid unnecessary switch of serlvet features by test case
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/PersistentExecutorConfigUpdateTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate/publish/servers/com.ibm.ws.concurrent.persistent.fat.configupdate/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11780 enable Jakarta in concurrent db, ejb, config tests
  dev/com.ibm.ws.concurrent_fat_config/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_config/publish/servers/concurrent.config.fat/server.xml
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/web/EEConcurrencyUtilsFATServlet.java
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/web/IncrementTask.java
  dev/com.ibm.ws.concurrent_fat_db/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
  dev/com.ibm.ws.concurrent_fat_db/test-applications/concurrentdbtest/src/concurrent/fat/db/web/ConcurrentDBTestServlet.java
  dev/com.ibm.ws.concurrent_fat_ejb/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_ejb/publish/servers/com.ibm.ws.concurrent.fat.ejb/server.xml
  dev/com.ibm.ws.concurrent_fat_ejb/test-applications/concurrent/src/web/ConcurrentFATServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11802 port context bvt bucket to open liberty
  dev/com.ibm.ws.context_fat_customproviders/.classpath
  dev/com.ibm.ws.context_fat_customproviders/.project
  dev/com.ibm.ws.context_fat_customproviders/.settings/bndtools.core.prefs
  dev/com.ibm.ws.context_fat_customproviders/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.context_fat_customproviders/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.context_fat_customproviders/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.context_fat_customproviders/bnd.bnd
  dev/com.ibm.ws.context_fat_customproviders/buffer.bnd
  dev/com.ibm.ws.context_fat_customproviders/build.gradle
  dev/com.ibm.ws.context_fat_customproviders/context_fat_customproviders.bnd
  dev/com.ibm.ws.context_fat_customproviders/fat/src/test/context/ContextServiceTest.java
  dev/com.ibm.ws.context_fat_customproviders/fat/src/test/context/FATSuite.java
  dev/com.ibm.ws.context_fat_customproviders/map.bnd
  dev/com.ibm.ws.context_fat_customproviders/numeration.bnd
  dev/com.ibm.ws.context_fat_customproviders/publish/files/features/contexttest-1.0.mf
  dev/com.ibm.ws.context_fat_customproviders/publish/files/internalFeatures/contextproviderinternals-1.0.mf
  dev/com.ibm.ws.context_fat_customproviders/publish/servers/com.ibm.ws.context.fat.customproviders/bootstrap.properties
  dev/com.ibm.ws.context_fat_customproviders/publish/servers/com.ibm.ws.context.fat.customproviders/server.xml
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/resources/WEB-INF/web.xml
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/AppTask.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/AppWork.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/AppWorkerTask.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/ContextServiceTestServlet.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/GetBufferTask.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferContext.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferService.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/src/test/map/internal/MapContext.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/src/test/map/internal/MapContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/src/test/map/internal/MapService.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/map/src/test/map/internal/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/NumerationService.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/internal/NumerationContext.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/internal/NumerationContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/internal/NumerationServiceImpl.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/internal/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/numeration/src/test/numeration/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/ContextualThread.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/CurrentThreadExecutor.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/internal/ThreadFactoryImpl.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/internal/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/package-info.java
  dev/com.ibm.ws.context_fat_customproviders/threadfactory.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11787 11785: Intermittent h2 timing test failure
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: CLA Signed

#11486 Disable LTPA cookie for SPNEGO authentication
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/authentication/utility/SubjectHelper.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/SSOTokenBytesCacheKeyProvider.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/OidcClientAuthenticator.java
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoAuthenticator.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoConfig.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/Krb5Util.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnegoConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#10868 Change URL and connectionProperties to ibm-obscure
  dev/com.ibm.ws.jdbc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/PropertyService.java
  dev/com.ibm.ws.jdbc_fat_oracle/.classpath
  dev/com.ibm.ws.jdbc_fat_oracle/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_oracle/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTraceTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleUCPTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/jvm.options
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracletracefat/src/trace/web/OracleTraceTestServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracleucpfat/src/ucp/web/OracleUCPTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#11807 Revert "Disable LTPA cookie for SPNEGO authentication"
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/authentication/utility/SubjectHelper.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/SSOTokenBytesCacheKeyProvider.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/OidcClientAuthenticator.java
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoAuthenticator.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoConfig.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/Krb5Util.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnegoConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed

#11701 gRPC authorization support
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/com.ibm.websphere.appserver.grpcClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcServlet-1.0/com.ibm.websphere.appserver.grpcServlet-1.0.feature
  dev/com.ibm.ws.grpc.client/.classpath
  dev/com.ibm.ws.grpc.client/bnd.bnd
  dev/com.ibm.ws.grpc.client/src/META-INF/services/io.grpc.ManagedChannelProvider
  dev/com.ibm.ws.grpc.client/src/com/ibm/ws/grpc/client/LibertyClientInterceptor.java
  dev/com.ibm.ws.grpc.client/src/com/ibm/ws/grpc/client/LibertyManagedChannelProvider.java
  dev/com.ibm.ws.grpc.common/bnd.bnd
  dev/com.ibm.ws.grpc.server/bnd.bnd
  dev/com.ibm.ws.grpc.servlet/.classpath
  dev/com.ibm.ws.grpc.servlet/bnd.bnd
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServerComponent.java
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServletApplication.java
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServletContainerInitializer.java
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/GrpcServletUtils.java
  dev/com.ibm.ws.grpc.servlet/src/com/ibm/ws/grpc/servlet/LibertyAuthorizationInterceptor.java
  dev/com.ibm.ws.grpc.servlet/src/io/grpc/servlet/AsyncServletOutputStreamWriter.java
  dev/com.ibm.ws.grpc.servlet/src/io/grpc/servlet/GrpcServlet.java
  dev/com.ibm.ws.grpc.servlet/src/io/grpc/servlet/ServletAdapter.java
  dev/com.ibm.ws.grpc.servlet/src/io/grpc/servlet/ServletServerStream.java
  dev/com.ibm.ws.grpc.servlet/test/com/ibm/ws/grpc/servlet/GrpcServletTest.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http2/GrpcServletServices.java
Labels: CLA Signed, in:Transport, team:Sirius

#11814 Fix build break
  dev/com.ibm.ws.grpc_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#11806 Fix up recent changes
  dev/com.ibm.ws.com.graphql.java/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.context_fat_customproviders/.classpath
  dev/com.ibm.ws.io.github.classgraph.classgraph.4.6/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.io.leangen.geantyref.1.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.io.smallrye.graphql/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.jboss.jandex/bnd.bnd
  dev/com.ibm.ws.org.jboss.jandex/bnd.overrides
Labels: CLA Signed, team:Performance

#11588 Remove SharedServer and use LibertyServer
  dev/com.ibm.ws.jsp.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsp.2.3_fat/build.gradle
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava8Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerHttpUnit.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPServerTest.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJSP2.3.war/resources/EL30CollectionObjectOperations.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJSPWithJava8.war/resources/index.jsp
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11817 Issue #11816: Avoid EJB app start on server shutdown
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBContainerImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#11374 add boulder CA to acme FAT
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/CAContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/ChalltestsrvContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/PebbleContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/pebble/PebbleContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/pebble/PebbleDriver.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeBoulderSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeCaRestHandlerTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigBringUp.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/FATSuite.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/com.ibm.ws.security.acme_fat/publish/files/boulder.minica.pem
Labels: CLA Signed, noproductcode

#11753 Issue #11746: StartWinService Bug with WLP_OUTPUT_DIR
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartAsServiceTest.java
Labels: CLA Signed, release bug

#11604 Fix issues in jaxws-2.2 and jaxws-2.3 bundles
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/CXFExtensionBundleListener.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/StringMapImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapMessage.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/Soap11FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/saaj/SAAJInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/saaj/SAAJOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.2.6.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.2.6.2/src/org/apache/cxf/ws/policy/PolicyDataEngineImpl.java
Labels: CLA Signed

#11715 Tolerate test setup slowness
  dev/com.ibm.ws.transaction.core_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/RecoveryServlet.java
Labels: CLA Signed, noproductcode

#11762 handle openliberty.io can't be reached to retrieve https://openliber…
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
Labels: CLA Signed

#11783 make sure failing test gets a unique jwt
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
Labels: CLA Signed, noproductcode

#11804 Remove unused imports web container
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed, in:Web Components, team:Sirius

#11694 Retry abort resources
  dev/com.ibm.tx.core/bnd.bnd
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TimeoutManager.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
Labels: CLA Signed

#11700 Move unit tests
  dev/com.ibm.ws.transaction.context/.classpath
  dev/com.ibm.ws.transaction.context/.gitignore
  dev/com.ibm.ws.transaction.context/test/src/com/ibm/ws/transaction/context/internal/TransactionContextTest.java
  dev/com.ibm.ws.transaction.context_test/.classpath
  dev/com.ibm.ws.transaction.context_test/.gitignore
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.context_test/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.context_test/bnd.bnd
Labels: CLA Signed

#11867 Remove remaining unit test .project file
  dev/com.ibm.ws.transaction.context_test/.project
Labels: CLA Signed, noproductcode

#11848 Changed "info" to "debug" on anno service message.
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/service/internal/AnnotationCacheServiceImpl_Service.java
Labels: CLA Signed, release bug

#11831 11830 H2 continuation test error
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, noproductcode

#11560 Initial check in of MessageImpl refactoring
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentDeserializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/OutgoingChainInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/ServiceInvokerInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/phase/PhaseInterceptorChain.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/transport/ChainInitiationObserver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/ws/addressing/ContextUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/test/com/ibm/ws/jaxrs/test/MessageImplTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/AbstractParamInjectionBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/JAXRSBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/JAXRSInvoker.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/ext/MessageContextImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/HttpHeadersImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/PropertyHolderFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/ServletRequestPropertyHolder.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/UriInfoImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/FormUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/ResourceUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/org/apache/cxf/jaxrs/client/AbstractClient.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/Headers.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2/src/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
Labels: CLA Signed

#11728 Issue 11186: Issue warning if the notBefore on the cert is in the future
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
Labels: CLA Signed, L2 Reviewed, team:Core Security, team:Wendigo East

#11736 Issue #11735: When ACME fails to create a certificiate or keystore on…
  dev/com.ibm.ws.crypto.certificate.creator.acme/src/com/ibm/ws/crypto/certificate/creator/acme/AcmeSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/DefaultSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.java
  dev/com.ibm.ws.crypto.certificateutil/test/com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreatorTest.java
  dev/com.ibm.ws.security.acme/resources/com/ibm/ws/security/acme/resources/AcmeMessages.nlsprops
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/AcmeProvider.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeProviderImpl.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeCaRestHandlerTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTaskTest.java
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed, L2 Reviewed, team:Wendigo East

#11756 Update weld3 to latest version
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.jboss.weld3/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
Labels: CLA Signed

#11877 Revert 11807 revert 11486 9445 disable ltpa for spnego
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/authentication/utility/SubjectHelper.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/SSOTokenBytesCacheKeyProvider.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/OidcClientAuthenticator.java
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.spnego/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoAuthenticator.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/SpnegoConfig.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/Krb5Util.java
  dev/com.ibm.ws.security.spnego/src/com/ibm/ws/security/spnego/internal/SpnegoConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed

#11869 Add new testcase that tests Rx with Providers
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/ProviderTest.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.provider/.gitignore
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.provider/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/publish/servers/jaxrs21.fat.provider/server.xml
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/InjectableObject.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/ProviderTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/TestApplication.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/TestEndpoint.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/TestEntity.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/TestEntityMessageBodyReader.java
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/test-applications/provider/src/jaxrs21/fat/provider/TestEntityMessageBodyWriter.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#11883 NOTICES for 20.0.0.5
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#11546 Fixed audit record method field
  dev/com.ibm.ws.request.probe.audit.servlet/src/com/ibm/ws/request/probe/audit/servlet/AuditPE.java
Labels: CLA Signed

#11834 11479: GA the trackOAuthClients OAuth metatype attribute
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#11309 Improve log messages from the kafka connector
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaAdapterException.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaConnectorException.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaOutgoingConnector.java
Labels: CLA Signed, L2 Reviewed

#11838 Add test app for new Java 14 language features
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/FATSuite.java
  dev/com.ibm.ws.java11_fat/fat/src/com/ibm/ws/java11_fat/Java14Test.java
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java14-server/apps/java14-app.war
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java14-server/bootstrap.properties
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java14-server/jvm.options
  dev/com.ibm.ws.java11_fat/publish/servers/java11_fat-java14-server/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11881 Upgrade to SmallRye GraphQL 1.0.1
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
  dev/com.ibm.ws.io.smallrye.graphql/resources/META-INF/services/io.smallrye.graphql.lookup.LookupService
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/CDIDelegateImpl.java
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/SchemaBuilder.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/ArgumentCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/FieldCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/OperationCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/ReferenceCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/type/InputTypeCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/type/InterfaceCreator.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/schema/creator/type/TypeCreator.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/InputFieldsTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/inputFieldsApp/src/mpGraphQL10/inputFields/WidgetClientObject.java
Labels: CLA Signed, in:MicroProfile, team:Wendigo West

#11872 Ensure we run CDI tests with repeat tests for cdi-2.0
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#11880 update PrincipalBean to return unique security name
  dev/com.ibm.ws.security.mp.jwt.cdi/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/principal/PrincipalBean.java
Labels: CLA Signed

#11837 run context custom providers test with Jakarta interfaces
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.context_fat_customproviders/bnd.bnd
  dev/com.ibm.ws.context_fat_customproviders/build.gradle
  dev/com.ibm.ws.context_fat_customproviders/fat/src/test/context/ContextServiceTest.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/ContextServiceTestServlet.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/internal/ThreadFactoryImpl.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
Labels: CLA Signed, team:Zombie Apocalypse

#11892 11767 mpOpenTracing prevent bottlenecking due to lock
  dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
  dev/com.ibm.ws.opentracing.1.2/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
  dev/com.ibm.ws.opentracing.1.3/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
  dev/com.ibm.ws.opentracing/src/com/ibm/ws/opentracing/OpentracingTracerManager.java
Labels: CLA Signed

#11791 Remove beta guard env var WLP_LOGGING_OMIT_JSON_FIELD_MAPPINGS
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
Labels: CLA Signed

#11871 11870 modify npe check
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: CLA Signed, in:Transport, team:Sirius

#11541 Change processing of feature bundles
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfigurator.java
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/StartAction.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/BundleProcessor.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleInstallStatus.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureManagerTest.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/RuntimeUpdateNotification.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
  dev/com.ibm.ws.runtime.update/test/com/ibm/ws/runtime/update/internal/RuntimeUpdateNotificationMBeanTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed

#11623 Appw refine validation, improve message
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs.nlsprops
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/ClientAuthentication.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#10965 Update SAML feature name capitalization
  dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
Labels: CLA Signed, team:Security SSO

#11914 Update .classpath to get unit test build in eclipse.
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.transaction.context/.classpath
Labels: noproductcode, team:Performance

#11866 Fix single metric query for Prometheus format
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/writer/PrometheusMetricWriter.java
  dev/com.ibm.ws.microprofile.metrics.2.3/src/com/ibm/ws/microprofile/metrics23/writer/PrometheusMetricWriter23.java
Labels: CLA Signed

#11900 Issue #11898: Transform Injection Engine for Jakarta EE 9
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.injection-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature
  dev/com.ibm.ws.injection/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, in:Java EE Platform, team:Blizzard

#11714 Pointed microprofile-fault-tolerance-tck to the new Release Candidates
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#11242 update SAML spHostAndPort attribute in metatype.properties
  dev/com.ibm.ws.security.saml.sso/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Security SSO

#11920 Issue #11919: Unblock EJB remtoe app start on shutdown
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#11895 Process features without case sensitivity in FeatureReplacementAction
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11910 Add Allowed/ExpectedFFDC annotations for RepeatedTests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BndErrorTest.java
  dev/fattest.simplicity/src/componenttest/annotation/AllowedFFDC.java
  dev/fattest.simplicity/src/componenttest/annotation/ExpectedFFDC.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode

#11915 Fix EJB IOR profiles
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
  dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
  dev/com.ibm.ws.transport.iiop.open_fat/bnd.bnd
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/com.ibm.ws.transport.iiop.open_fat/fat/src/com/ibm/ws/transport/iiop/open_fat/FATSuite.java
  dev/com.ibm.ws.transport.iiop.open_fat/fat/src/com/ibm/ws/transport/iiop/open_fat/IORTest.java
  dev/com.ibm.ws.transport.iiop.open_fat/publish/.gitignore
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/com.ibm.ws.transport.iiop.open_fat.server/.gitignore
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/com.ibm.ws.transport.iiop.open_fat.server/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/com.ibm.ws.transport.iiop.open_fat.server/server.xml
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/Business.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/Cmsfv2ChildData.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/Cmsfv2ParentData.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestClass.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestEnum.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntf.idl
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntf.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntfHelper.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntfHolder.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntfOperations.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntfPOA.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestIDLIntf_impl.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/TestRemote.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/Interfaces.jar/src/shared/_TestIDLIntfStub.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorba.ear/package.properties
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorba.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorba.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaEjb.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaEjb.jar/src/ejb/BusinessEjb.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaEjb.jar/src/ejb/TestEjb.java
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaWeb.war/package.properties
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaWeb.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.transport.iiop.open_fat/test-applications/TestCorbaWeb.war/src/servlet/IORTestServlet.java
Labels: CLA Signed, release bug

#11935 Revert "run context custom providers test with Jakarta interfaces"
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.context_fat_customproviders/bnd.bnd
  dev/com.ibm.ws.context_fat_customproviders/build.gradle
  dev/com.ibm.ws.context_fat_customproviders/fat/src/test/context/ContextServiceTest.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/ContextServiceTestServlet.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/internal/ThreadFactoryImpl.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
Labels: CLA Signed

#11932 work around resource injection intermittent failure to inject resource
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/ContextServiceTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11926 Update BootstrapChildFirstURLClassloader
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/BootstrapChildFirstURLClassloader.java
Labels: CLA Signed, team:Performance

#11925 Add com.ibm.wsspi.application package to spi
  dev/com.ibm.websphere.appserver.spi.application/bnd.bnd
Labels: CLA Signed

#11937 reintroduce run context custom providers test with Jakarta interfaces
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.context_fat_customproviders/bnd.bnd
  dev/com.ibm.ws.context_fat_customproviders/build.gradle
  dev/com.ibm.ws.context_fat_customproviders/fat/src/test/context/ContextServiceTest.java
  dev/com.ibm.ws.context_fat_customproviders/test-applications/contextbvt/src/test/context/app/ContextServiceTestServlet.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/buffer/src/test/buffer/internal/BufferContextProvider.java
  dev/com.ibm.ws.context_fat_customproviders/test-bundles/threadfactory/src/test/threadfactory/internal/ThreadFactoryImpl.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
Labels: CLA Signed, team:Zombie Apocalypse

#11908 test case failover1serv expect warnings when server shuts down while tasks running
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerCoordinatedPollingTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerTest.java
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/SwitchFromSingleInstanceToFailOverTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#11939 Issue #11938: Export jakarta annotation API
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.anno-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.injection-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature
Labels: CLA Signed, in:Java EE Platform, team:Blizzard
