Repository OpenLiberty/open-liberty, pull requests merged in 2020-08, with the labels that each got.

#13241 Implement subject cache for KerberosService
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-oracle-app/src/jdbc/krb5/oracle/web/OracleKerberosTestServlet.java
  dev/com.ibm.ws.security.jca/bnd.bnd
  dev/com.ibm.ws.security.jca/src/com/ibm/ws/security/jca/internal/AuthDataServiceImpl.java
  dev/com.ibm.ws.security.jca/test/com/ibm/ws/security/jca/internal/AuthDataServiceImplTest.java
  dev/com.ibm.ws.security.kerberos.auth/bnd.bnd
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/KerberosService.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/internal/LRUCache.java
Labels: CLA Signed, team:Zombie Apocalypse

#13276 Add multi app info test consumer
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesTests.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/api/ConsumerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerServiceRestClient.java
Labels: CLA Signed, noproductcode

#13226 Update concurrent feature to use transformer
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.concurrent.mp-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-1.0/com.ibm.websphere.appserver.concurrent-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-2.0/com.ibm.websphere.appserver.concurrent-2.0.feature
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/LastExecutionImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/TaskLifeCycleCallback.java
  dev/io.openliberty.jakarta.concurrency.2.0/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-concurrent-components-xml.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, team:Performance

#13263 Automatically sort file rather than failing
  dev/cnf/build.gradle
  dev/cnf/ibm_java.maven
Labels: CLA Signed, noproductcode

#13237 Transform RESTEasy bundle for JAX-RS 3.0
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.jaxrs-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/com.ibm.websphere.appserver.jaxrs-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrs-3.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrs-3.0/io.openliberty.jaxrs-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/com.ibm.websphere.appserver.jaxrsClient-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-2.2/resources/l10n/com.ibm.websphere.appserver.jaxrsClient-3.0_zh_TW.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxrsClient-3.0/io.openliberty.jaxrsClient-3.0.feature
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/io.openliberty.jakarta.jaxrs.3.0.api_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jaxrs.3.0.api_fat/bnd.bnd
  dev/io.openliberty.jakarta.jaxrs.3.0.api_fat/fat/src/io/openliberty/jakarta/jaxrs30api/fat/app/canload/ApiTestServlet.java
  dev/io.openliberty.jakarta.jaxrs.3.0.api_fat/publish/servers/jaxrs30api/server.xml
  dev/io.openliberty.jaxrs.3.0_fat/bnd.bnd
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/AppAndResourceTest.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResource.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResourceTestServlet.java
  dev/io.openliberty.jaxrs.3.0_fat/publish/servers/appandresource/server.xml
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-jaxrs.properties
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, L2 ReviewNotRequired, in:JAX-RS, team:Wendigo West

#13190 Add FilePermission to test server.xml to read truststore file
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient13.ssl/server.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#13267 Remove com.ibm.ws.require.java8
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.0/com.ibm.websphere.appserver.microProfile-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.2/com.ibm.websphere.appserver.microProfile-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.3/com.ibm.websphere.appserver.microProfile-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-1.4/com.ibm.websphere.appserver.microProfile-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.0/com.ibm.websphere.appserver.microProfile-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.1/com.ibm.websphere.appserver.microProfile-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-2.2/com.ibm.websphere.appserver.microProfile-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.0/com.ibm.websphere.appserver.microProfile-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.2/com.ibm.websphere.appserver.microProfile-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-3.3/com.ibm.websphere.appserver.microProfile-3.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.1/com.ibm.websphere.appserver.mpConfig-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.2/com.ibm.websphere.appserver.mpConfig-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.3/com.ibm.websphere.appserver.mpConfig-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-1.4/com.ibm.websphere.appserver.mpConfig-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-2.0/io.openliberty.mpConfig-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.0/com.ibm.websphere.appserver.mpContextPropagation-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.1/com.ibm.websphere.appserver.mpContextPropagation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.0/com.ibm.websphere.appserver.mpFaultTolerance-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-1.1/com.ibm.websphere.appserver.mpFaultTolerance-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-1.0/com.ibm.websphere.appserver.mpGraphQL-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/io.openliberty.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.0/com.ibm.websphere.appserver.mpMetrics-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-1.1/com.ibm.websphere.appserver.mpMetrics-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.0/com.ibm.websphere.appserver.mpMetrics-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.2/com.ibm.websphere.appserver.mpMetrics-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-2.3/com.ibm.websphere.appserver.mpMetrics-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-3.0/com.ibm.websphere.appserver.mpMetrics-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.0/com.ibm.websphere.appserver.mpOpenAPI-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-1.1/com.ibm.websphere.appserver.mpOpenAPI-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/com.ibm.websphere.appserver.mpOpenTracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/com.ibm.websphere.appserver.mpOpenTracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/com.ibm.websphere.appserver.mpOpenTracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/com.ibm.websphere.appserver.mpOpenTracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-1.0/com.ibm.websphere.appserver.mpReactiveMessaging-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.0/com.ibm.websphere.appserver.mpRestClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.1/com.ibm.websphere.appserver.mpRestClient-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.2/com.ibm.websphere.appserver.mpRestClient-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.3/com.ibm.websphere.appserver.mpRestClient-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.4/com.ibm.websphere.appserver.mpRestClient-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openapi-3.1/com.ibm.websphere.appserver.openapi-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.0/com.ibm.websphere.appserver.opentracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/com.ibm.websphere.appserver.opentracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.2/com.ibm.websphere.appserver.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/scim-2.0/com.ibm.websphere.appserver.scim-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.jwt.1.0/bnd.bnd
  dev/com.ibm.ws.require.java8/.classpath
  dev/com.ibm.ws.require.java8/.project
  dev/com.ibm.ws.require.java8/.settings/bndtools.core.prefs
  dev/com.ibm.ws.require.java8/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.require.java8/bnd.bnd
Labels: CLA Signed, team:Performance

#13290 Wait for CWWKF0011I before starting test
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLTestNoLibertySSLCfg.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientLTPATest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLProxyAuthTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13280 Increase the timeout for the Jersey Tests to account for slow build systems
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JerseyRxInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13291 Add debug to testcase
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/callback/JAXRS20CallBackTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/ClientTestServlet.java
Labels: CLA Signed, noproductcode

#13264 Edit testDecodeUrlPlusSign test and ensure tests wait for config updates
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/files/decodeUrlPlusSign_false.server.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_wcServer/server.xml
Labels: CLA Signed, noproductcode

#13282 Automatically set Kerberos connectionProperties for Oracle
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#13300 Add test for handling arrays as QueryParams parameters
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResource.java
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/appandresource/AppAndResourceTestServlet.java
  dev/io.openliberty.jaxrs.3.0_fat/publish/servers/appandresource/server.xml
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13285 Consume Fault Tolerance 3.0-RC1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/FaultToleranceMainTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/circuitbreaker/CircuitBreakerMetricTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/MetricListServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/faulttolerance/tck/FATSuite.java
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/faulttolerance/tck/FaultToleranceTck30Launcher.java
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/io.openliberty.org.eclipse.microprofile.faulttolerance.3.0/bnd.bnd
Labels: CLA Signed

#13287 Fix issue with RestMetricsTest
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/restmetrics/RestMetricsTest.java
Labels: CLA Signed, noproductcode

#13305 Export SmallRye GraphQL packages at the same version that we pull in
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#13217 Disable metrics TCK tests for java versions 11.0.0 - 11.0.3
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/metrics11/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/fat/src/com/ibm/ws/microprofile/metrics20/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/fat/src/com/ibm/ws/microprofile/metrics22/tck/launcher/MetricsTCKLauncher.java
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/fat/src/com/ibm/ws/microprofile/metrics23/tck/launcher/MetricsTCKLauncher.java
Labels: CLA Signed, noproductcode

#12996 Issue #12555: Overwriting invalid config values to default values
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/ConsoleFormatTest.java
Labels: CLA Signed

#13253 Minor fixes for wlp.lib.extract_fat project
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/ExternalDependencyDownloadTest.java
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#13283 Update Subject cache for Kerberos to be access-ordered instead of ins-ordered
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/KerberosService.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/internal/LRUCache.java
Labels: CLA Signed, team:Zombie Apocalypse

#13293 Fix usage of ConnectionManagerMBean attributes
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManagerMBeanImpl.java
  dev/com.ibm.ws.jdbc_fat_v41/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_v41/build.gradle
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/JDBC41UpgradeTest.java
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/basicfat/src/jdbc/fat/v41/web/BasicTestServlet.java
Labels: CLA Signed, release bug, team:Zombie Apocalypse

#13284 EJB Fat: stop application before server stop for BB
  dev/com.ibm.ws.ejbcontainer.async_fat/fat/src/com/ibm/ws/ejbcontainer/async/fat/tests/AsyncConfigTests.java
Labels: CLA Signed, noproductcode

#13307 Update SunOne test to use UnboundID
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.com.unboundid/bnd.bnd
  dev/com.ibm.ws.com.unboundid/resources/SunOne.ldif
  dev/com.ibm.ws.com.unboundid/src/com/ibm/ws/com/unboundid/InMemorySunLDAPServer.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAP_SSLTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/server.xml
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.registry_fat/build.gradle
Labels: CLA Signed, team:Wendigo East

#13221 Update JAX-B feature kind
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/com.ibm.websphere.appserver.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-3.0/io.openliberty.jaxb-3.0.feature
Labels: CLA Signed

#13322 Update eclipse settings for new components
  dev/io.openliberty.io.opentracing.opentracing-api.0.33.0/.classpath
  dev/io.openliberty.io.opentracing.opentracing-api.0.33.0/.settings/bndtools.core.prefs
  dev/io.openliberty.io.opentracing.opentracing-api.0.33.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.opentracing.opentracing-util.0.33.0/.classpath
  dev/io.openliberty.io.opentracing.opentracing-util.0.33.0/.settings/bndtools.core.prefs
  dev/io.openliberty.io.opentracing.opentracing-util.0.33.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal.rest.client/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.opentracing.2.0.internal.cdi/.settings/bndtools.core.prefs
  dev/io.openliberty.opentracing.2.0.internal.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.opentracing.2.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.opentracing.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.opentracing.2.0.spi/.classpath
  dev/io.openliberty.opentracing.2.0.spi/.settings/bndtools.core.prefs
  dev/io.openliberty.opentracing.2.0.spi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.opentracing.2.0.thirdparty/.classpath
  dev/io.openliberty.opentracing.2.0.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.opentracing.2.0.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.opentracing.2.0/.classpath
  dev/io.openliberty.org.eclipse.microprofile.opentracing.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.opentracing.2.0/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, noproductcode, team:Performance

#13239 Create gRPC objects using managed object service
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.grpc-1.0.feature
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.xml
  dev/com.ibm.ws.grpc_fat/test-applications/FavoriteBeerService.war/src/com/ibm/ws/grpc/fat/beer/service/BeerServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/GreetingCDIBean.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServerCDIInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldService.war/src/com/ibm/ws/grpc/fat/helloworld/service/HelloWorldServlet.java
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyManagedChannelProvider.java
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/src/io/openliberty/grpc/internal/GrpcManagedObjectProvider.java
  dev/io.openliberty.grpc.1.0.internal/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletApplication.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletUtils.java
Labels: CLA Signed, in:Transport, team:Sirius

#13329 Remove Java8 requirement in OpenTracing 2.0 features
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/io.openliberty.mpOpenTracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-2.0/io.openliberty.opentracing-2.0.feature
Labels: CLA Signed

#13247 Enable use of local property file additions and immediate bundle data
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, enhancement, noproductcode

#13328 Issue 13323: Fix messages and resolve ACME test issues
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeClient.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/web/AcmeCaRestHandler.java
  dev/com.ibm.ws.security.acme/src/org/shredzone/acme4j/connector/HttpConnector.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.config_var/bootstrap.properties
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.config_var/server.xml
Labels: CLA Signed, team:Core Security, team:Wendigo East

#13308 Added catch block for SocketException
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
Labels: CLA Signed, noproductcode

#13303 Increasing sleeps for testParallelMultipleRequest
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/HungRequestTiming.java
Labels: CLA Signed, noproductcode

#13110 [#10786] API jars and feature code for MP Rest Client 2.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/io.openliberty.mpRestClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/resources/l10n/com.ibm.websphere.appserver.mpRestClient-2.0_zh_TW.properties
  dev/com.ibm.websphere.org.eclipse.microprofile.rest.client.1.4/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/.classpath
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/.gitignore
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/.project
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile.rest.client.2.0/resources/META-INF/services/javax.enterprise.inject.spi.Extension
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, in:MicroProfile/RestClient, team:Wendigo West

#13330 Remove Javadoc in ConnectionWaitTimeoutException
  dev/com.ibm.ws.jdbc/src/com/ibm/websphere/ce/cm/ConnectionWaitTimeoutException.java
Labels: CLA Signed, team:Zombie Apocalypse

#13343 EJB bindToServerRootConfig element tests
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/BindToServerRootTest.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/bindings/configtests/web/BindToServerRootServlet.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ContainerProperties.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/EJBContainerElement.java
Labels: CLA Signed

#13321 Upgrade to SmallRye GraphQL 1.0.7
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.metrics.1.0/bnd.bnd
Labels: CLA Signed, in:MicroProfile/GraphQL, team:Wendigo West

#13359 [#13357] Add sse package to explicit package imports.
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.overrides
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13319 Rename internal connectors features
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jakarta-connectionManagement-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectors-2.0.internal.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.connectors-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.appserver.connectors-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.0/io.openliberty.connectors-2.0.feature
Labels: CLA Signed, team:Zombie Apocalypse

#13366 Issue #12954: Update the policy properties for Jakarta Authorization …
  dev/com.ibm.ws.security.authorization.jacc.ejb/src/com/ibm/ws/security/authorization/jacc/ejb/impl/EJBSecurityValidatorImpl.java
  dev/com.ibm.ws.security.authorization.jacc.web/src/com/ibm/ws/security/authorization/jacc/web/impl/WebSecurityValidatorImpl.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/PolicyContextHandlerImpl.java
Labels: CLA Signed, team:Wendigo East

#13316 Metatype changes to add ES256 signature algorithm for JWT
  dev/com.ibm.ws.org.jose4j/bnd.bnd
  dev/com.ibm.ws.org.jose4j/bnd.overrides
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jEllipticCurveJWK.java
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/BuilderImpl.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtComponent.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/Constants.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtData.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/web/JwtEndpointServices.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, L2 ReviewNotRequired, team:Security SSO

#13375 Add support for RS384, RS512, ES384, ES512, HS384, and HS512 signature algorithms in JWT
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/Jose4jEllipticCurveJWK.java
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/BuilderImpl.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/Constants.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/web/JwtEndpointServices.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/server/internal/MockJWKProvider.java
Labels: CLA Signed, team:Security SSO

#13356 Eliminate usage of <script> blocks in ant tasks because Nashorn is removed in JDK 15
  dev/cnf/ant/liberty-ghe.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, team:Zombie Apocalypse

#13362 Skip tests for Sun JDK 8 where older keytab encodings are not supported
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/KerberosPlatformRule.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#13365 Issue #13363: Beta the jaspic-2.0, jacc-2.0 and appSecurity-4.0 featu…
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.ejbSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jaccEjb-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jaccWeb-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.builtinAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.distributedMapInternal-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jacc-2.0/io.openliberty.jacc-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/com.ibm.websphere.appserver.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaspic-2.0/io.openliberty.jaspic-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-3.0/io.openliberty.jaxb-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed, team:Wendigo East

#13112 gRPC JMX metrics
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcMonitor-1.0.feature
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServerOnly/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/HelloWorldServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StreamingServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientServlet.java
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.3/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/GrpcClientComponent.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyManagedChannelProvider.java
  dev/io.openliberty.grpc.1.0.internal.common/src/io/openliberty/grpc/internal/Utils.java
  dev/io.openliberty.grpc.1.0.internal.monitor/.classpath
  dev/io.openliberty.grpc.1.0.internal.monitor/.project
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientStats.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientStatsMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMethod.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringClientCall.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringClientCallListener.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringClientInterceptor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringServerCall.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringServerCallListener.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringServerInterceptor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerStats.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerStatsMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/package-info.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/monitor/GrpcClientStatsMXBean.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/monitor/GrpcServerStatsMXBean.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/monitor/package-info.java
  dev/io.openliberty.grpc.1.0.internal/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/GrpcServlet.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletUtils.java
Labels: CLA Signed

#13390 NOTICES for 20.0.0.9
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#13261 Update slf4j-simple to the latest version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/build.gradle
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer1/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerInventory/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerSystem/server.xml
  dev/fattest.simplicity/bnd.bnd
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/build.gradle
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServer1/server.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServerInventory/server.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServerSystem/server.xml
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
  dev/wlp-jakartaee-transform/bnd.bnd
Labels: CLA Signed

#13355 Issue 13354: Check for existing Boulder containers
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#13339 Issue13286-ProvideCredsForOssIndexScan
  dev/wlp-gradle/biz.aQute.bnd.gradle
Labels: CLA Signed, noproductcode

#13358 13196: grpc client interceptor tests
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.invalid.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.multiple.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcClientOnly/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcClientOnly/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientInterceptor.java
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldClient.war/src/com/ibm/ws/grpc/fat/helloworld/client/HelloWorldClientInterceptor2.java
Labels: in:Test Infrastructure, noproductcode, team:Sirius

#13340 Fix #13297 accesslogging test failure
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/CustomAccessLogFieldsTest.java
Labels: CLA Signed, noproductcode

#13352 Issue #13351:Fix testDump with core pattern pipe
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/DumpCommandTest.java
Labels: CLA Signed, noproductcode

#13332 Replace ffdc with debug
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceSupportTests.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed

#13385 Issue #13309: Allow EJB Local to extend RMI Remote
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/jitdeploy/EJBWrapper.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/test-applications/ExceptionBean.jar/src/com/ibm/ws/ejbcontainer/exception/ejb/SLRemoteExLocalRemote.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/test-applications/ExceptionBean.jar/src/com/ibm/ws/ejbcontainer/exception/ejb/SLRemoteExLocalRemoteBean.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/test-applications/ExceptionBean.jar/src/com/ibm/ws/ejbcontainer/exception/ejb/SLRemoteExLocalRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/test-applications/ExceptionWeb.war/src/com/ibm/ws/ejbcontainer/exception/web/ExceptionServlet.java
Labels: in:EJB Container, team:Blizzard

#13097 Issue #13096: Add mdb-4.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/io.openliberty.mdb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/resources/l10n/io.openliberty.mdb-4.0_zh_TW.properties
  dev/com.ibm.ws.ejbcontainer.mdb/bnd.bnd
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, in:EJB Container, jakartaEE, team:Blizzard

#13402 Wait for CWWKF0011I before starting test
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JerseyRxInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13272 delay to initialize all TAIs
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/TAIService.java
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/internal/TAIServiceImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed

#13344 Add Fault Tolerance 3.0 API maven coordinates
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-3.0.feature
Labels: CLA Signed

#13413 Fix ejbcontainer.session.async_fat AsyncWarnTest Order Dependency
  dev/com.ibm.ws.ejbcontainer.session.async_fat/fat/src/com/ibm/ws/ejbcontainer/session/async/fat/AsyncWarnTest.java
Labels: CLA Signed, in:EJB Container, noproductcode, test bug

#13295 Increase wsat FAT timeout & synchronize TM check
  dev/com.ibm.ws.wsat.concurrent_fat/bnd.bnd
  dev/com.ibm.ws.wsat.concurrent_fat/publish/servers/MigrationServer1/server.xml
  dev/com.ibm.ws.wsat.concurrent_fat/publish/servers/MigrationServer2/server.xml
  dev/com.ibm.ws.wsat.concurrent_fat/test-applications/threadedClient/src/com/ibm/ws/wsat/threadedclient/client/threaded/ThreadedClientServlet.java
Labels: CLA Signed, noproductcode

#13429 Add server quiesce trace to mongo fat
  dev/com.ibm.ws.mongo_fat/publish/servers/mongo.fat.server.config.update/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/mongo.fat.server.ssl.default.config/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/mongo.fat.server.ssl/bootstrap.properties
  dev/com.ibm.ws.mongo_fat/publish/servers/mongo.fat.server/bootstrap.properties
Labels: CLA Signed, noproductcode, team:Blizzard

#13403 Split wsat recovery tests
  dev/com.ibm.ws.wsat.recovery_fat.1/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.1/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.1/.project
  dev/com.ibm.ws.wsat.recovery_fat.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.1/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.1/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/SingleRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery1/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery1/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery2/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery2/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATRecovery2/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATSingleRecovery/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATSingleRecovery/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat.1/publish/servers/WSATSingleRecovery/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/resources/WEB-INF/web.xml
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/resources/WEB-INF/wsdl/RecoveryService.wsdl
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/Invoke.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/InvokeResponse.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/MultiRecoverySetupServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/ObjectFactory.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/Recovery.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/RecoveryCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/RecoveryService.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/RecoverySetupServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/SuicideServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/package-info.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryServer/resources/WEB-INF/web.xml
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryServer/resources/WEB-INF/wsdl/RecoveryService.wsdl
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryServer/src/com/ibm/ws/wsat/fat/server/MultiRecoveryCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryServer/src/com/ibm/ws/wsat/fat/server/Recovery.java
  dev/com.ibm.ws.wsat.recovery_fat.1/test-applications/recoveryServer/src/com/ibm/ws/wsat/fat/server/SuicideServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.1/wsat.recovery_fat.bnd
  dev/com.ibm.ws.wsat.recovery_fat.2/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.2/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.2/.project
  dev/com.ibm.ws.wsat.recovery_fat.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.2/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.2/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.2/fat/src/com/ibm/ws/wsat/fat/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.2/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.2/wsat.recovery_fat.bnd
  dev/com.ibm.ws.wsat.recovery_fat.3/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.3/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.3/.project
  dev/com.ibm.ws.wsat.recovery_fat.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.3/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.3/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.3/fat/src/com/ibm/ws/wsat/fat/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.3/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.3/wsat.recovery_fat.bnd
Labels: CLA Signed, noproductcode

#13420 Revisions to address FAT test failure.
  dev/com.ibm.ws.javamail.1.6_fat/fat/src/com/ibm/ws/javamail/fat/IMAPTest.java
  dev/com.ibm.ws.javamail.1.6_fat/fat/src/com/ibm/ws/javamail/fat/SMTPTest.java
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/com.ibm.ws.javamail.fat/server.xml
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/mailSessionTestServer/server.xml
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/IMAP/IMAPInlineServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/IMAP/IMAPJNDIServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/IMAP/IMAPMailSessionServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/POP3/POP3InlineServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/POP3/POP3JNDIServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/POP3/POP3MailSessionServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/POP3/POP3MailTest.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/SMTP/SMTPInlineServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/SMTP/SMTPJNDIServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/SMTP/SMTPMailSessionServlet.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/SMTP/SMTPMailTest.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/TestingApp/src/TestingApp/web/IMAPMailTest.java
Labels: CLA Signed, noproductcode

#13349 Move MP Fault Tolerance 3.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance3.0-metrics.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-3.0/io.openliberty.mpFaultTolerance-3.0.feature
Labels: CLA Signed

#13381 Add GRPC FVT Server Streaming Test and more test code error handling
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerProto.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/resources/proto/ProducerStore.proto
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerServiceRestClient.java
Labels: noproductcode

#13414 13411: update TestContFrameAfterDataFrame test
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, noproductcode, team:Sirius

#13423 Use MicroProfile OpenTracing 2.0 RC2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.opentracing.2.0.internal/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile.opentracing.2.0/bnd.bnd
Labels: CLA Signed

#13417 Issue 13416: Skip some Basic Reg tests based on JDK
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#13442 Add clear error message for IBM JDK 8 with Oracle JDBC using kerberos
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-oracle-app/src/jdbc/krb5/oracle/web/OracleKerberosTestServlet.java
Labels: CLA Signed, L2 Reviewed, team:Zombie Apocalypse

#13410 Support new Sig Alg in JWT builer/consumer
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/ES256private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/ES384private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/ES512private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/PS256private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/PS384private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/PS512private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/RS256private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/RS384private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/RS512private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/JWTTokenBuilder.java
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/utils/JwtTokenBuilderUtils.java
  dev/com.ibm.ws.security.fat.common/publish/shared/config/allAlgSSLSettings.xml
  dev/com.ibm.ws.security.fat.common/publish/shared/securityKeys/allAlgKeyStore.p12
  dev/com.ibm.ws.security.fat.common/publish/shared/securityKeys/allAlgTrustStore.p12
  dev/com.ibm.ws.security.jwt_fat.builder/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwkEndpointValidationUrlTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/utils/BuilderHelpers.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/validation/BuilderTestValidationUtils.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/goodSSLSettings.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/goodSSLSettings2.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientConfigTestsConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/oidcRSClientBasicConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/test-applications/jwtbuilderclient/src/com/ibm/ws/jaxrs/fat/jwtbuilderclient/JwtBuilderSetApisClient.java
  dev/com.ibm.ws.security.jwt_fat.consumer/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/actions/JwtConsumerActions.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/utils/ConsumerHelpers.java
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/servers/com.ibm.ws.security.jwt_fat.consumer/configs/server_configTests.xml
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/shared/config/jwtBuilderApplication.xml
Labels: CLA Signed, team:Security SSO, test delivery

#13444 Clear application REST metrics properly
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
Labels: CLA Signed

#13396 Mark JPA 3.0 beta for 20.0.0.10
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.ejbliteJPA-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jpa3.0-bv3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jpaContainer-cdi.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa-3.0/io.openliberty.jpa-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpaContainer-3.0/io.openliberty.jpaContainer-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/com.ibm.websphere.appserver.webProfile-9.0.feature
Labels: CLA Signed, in:JPA, team:Blizzard

#13448 13447: Clean up H2 connection
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: CLA Signed

#13318 Use Allowlist rather than Whitelist in webcontainer.cors comments
  dev/com.ibm.ws.webcontainer.cors/src/com/ibm/ws/webcontainer/cors/CorsHelper.java
  dev/com.ibm.ws.webcontainer.cors/test/com/ibm/ws/webcontainer/cors/CorsHelperTest.java
Labels: CLA Signed, in:Web Components, team:Sirius

#13418 Issue #13096: Add mdb to feature replace action
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE6FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE7FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard

#13456 Issue 13455: Skip Oracle Java8 for AcmeSimpleTest
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security

#13401 Issue 13400: Adjust message for other JDKs Acme config test
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
Labels: CLA Signed, noproductcode

#13446 Add openidConnectClient config to test Roles
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesTests.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppConsumerProto.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppConsumerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/rsa_key.jks
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/rsa_trust.jks
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/rsa_key.jks
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/rsa_trust.jks
  dev/com.ibm.ws.grpc_fat/publish/servers/StoreServer/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreConsumerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/resources/proto/ConsumerStore.proto
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClient.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/security/TestAppCallCredentials.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/api/ConsumerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerServiceRestClient.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/utilsConsumer/ConsumerUtils.java
Labels: CLA Signed, noproductcode

#13382 Adding information message to let users know a cert is being added to…
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: ID reviewed, L2 Reviewed

#13379 Correct servlet31 and40 fat server configuration issues
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/FormLoginReadListenerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/files/FormLogin_ReadListener/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#13461 Issue 13459: Boulder container improvements
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
Labels: CLA Signed, noproductcode, team:Core Security

#13468 Issue 13467: Add retry in AcmeClientTest
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeClientTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#13463 13453: Increase default H2 test timeout
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13471 Add test for XA recovery using Kerberos authentication
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/TestXAResource.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#13214 LRA participant feature and fat tests
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.lra-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRA-1.0/io.openliberty.mpLRA-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpLRA-1.0/resources/l10n/io.openliberty.mpLRA-1.0.properties
  dev/io.openliberty.microprofile.lra.1.0.internal/.classpath
  dev/io.openliberty.microprofile.lra.1.0.internal/.gitignore
  dev/io.openliberty.microprofile.lra.1.0.internal/.project
  dev/io.openliberty.microprofile.lra.1.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.lra.1.0.internal/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.microprofile.lra.1.0.internal/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.lra.1.0.internal/resources/io/openliberty/microprofile/lra/internal/resources/Lra.nlsprops
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraConfig.java
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraException.java
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraFilterComponent.java
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraRuntimeException.java
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/package-info.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.classpath
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.project
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/lra/tck/FATSuite.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/lra/tck/LraTckLauncher.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/servers/LRATCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/servers/LRATCKServer/jvm.options
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/servers/LRATCKServer/server.xml
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/lra/test/ArquillianLoadableExtension.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/lra/test/LRAArquillianExtension.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/lra/test/LRARecoveryServiceImpl.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/lra/test/LRATckArchiveProcessor.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.classpath
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.project
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/bnd.bnd
  dev/io.openliberty.org.jboss.narayana.rts/.classpath
  dev/io.openliberty.org.jboss.narayana.rts/.project
  dev/io.openliberty.org.jboss.narayana.rts/.settings/bndtools.core.prefs
  dev/io.openliberty.org.jboss.narayana.rts/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.jboss.narayana.rts/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.jboss.narayana.rts/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.jboss.narayana.rts/bnd.bnd
Labels: CLA Signed, L2 Reviewed

#13377 Improve testReadinessEndpointOnServerStart test case to allow for retry
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
Labels: CLA Signed, noproductcode

#13472 Switch to beta and core and back to MP Config 1.4
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsDefaultExceptionMapper-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpMetrics-3.0-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.metrics-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-3.0/io.openliberty.mpMetrics-3.0.feature
  dev/io.openliberty.microprofile.metrics.internal.3.0/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.cdi.3.0/bnd.bnd
Labels: CLA Signed

#13048 Download built from source jars from wasliberty-source-built-maven-local
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/cnf/resources/bnd/repos.bnd
  dev/settings.gradle
Labels: CLA Signed

#13458 Issue 8835: remove Infinispan beta guard
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan/publish/servers/com.ibm.ws.session.cache.fat.infinispan.timeoutServerB/server.xml
Labels: CLA Signed, team:Zombie Apocalypse

#13452 Change mpOT-20 from noship to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpOpenTracing2.0-mpRestClient1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.opentracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/io.openliberty.mpOpenTracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-2.0/io.openliberty.opentracing-2.0.feature
Labels: CLA Signed

#13477 gRPC latency metrics
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.3/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientStats.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcClientStatsMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringClientCallListener.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcMonitoringServerCall.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerStats.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/internal/monitor/GrpcServerStatsMonitor.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/monitor/GrpcClientStatsMXBean.java
  dev/io.openliberty.grpc.1.0.internal.monitor/src/io/openliberty/grpc/monitor/GrpcServerStatsMXBean.java
Labels: CLA Signed

#13408 Move MP Health 3.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.health-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/io.openliberty.mpHealth-3.0.feature
  dev/io.openliberty.microprofile.health.3.0.internal/bnd.bnd
Labels: CLA Signed

#13438 Grpc fvt two way streaming testcase added
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerProto.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/resources/proto/ProducerStore.proto
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerServiceRestClient.java
Labels: CLA Signed, noproductcode

#13483 Handle ejb-jar.xml version 4.0 and application.xml version 9 in ddparser
  dev/com.ibm.ws.javaee.dd.ejb/src/com/ibm/ws/javaee/dd/ejb/EJBJar.java
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/app/Application.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/app/ApplicationAdapter.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/ejb/EJBJarDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/ejb/EJBJarEntryAdapter.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTestBase.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarTestBase.java
Labels: CLA Signed

#13245 Modify JPA HybridPersistenceActivator to not key off ClassLoader.
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence.base-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.persistence.base-2.2.feature
  dev/com.ibm.websphere.javaee.persistence.2.0/bnd.bnd
  dev/com.ibm.websphere.javaee.persistence.2.1/bnd.bnd
  dev/com.ibm.websphere.javaee.persistence.2.2/bnd.bnd
  dev/com.ibm.ws.javaee.persistence.2.1/bnd.bnd
  dev/com.ibm.ws.javaee.persistence.2.1/src/com/ibm/ws/javaee/persistence/internal/HybridPersistenceActivator.java
  dev/com.ibm.ws.javaee.persistence.2.2/bnd.bnd
  dev/com.ibm.ws.javaee.persistence.2.2/src/com/ibm/ws/javaee/persistence/internal/HybridPersistenceActivator.java
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.classpath
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.project
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/bnd.bnd
  dev/com.ibm.ws.jpa.hybridpersistenceactivator/src/com/ibm/ws/javaee/persistence/internal/HybridPersistenceActivator.java
Labels: CLA Signed, in:JPA, team:Blizzard

#13505 Revert "delay to initialize all TAIs"
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/TAIService.java
  dev/com.ibm.ws.security.authentication.tai/src/com/ibm/ws/security/authentication/tai/internal/TAIServiceImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed

#13428 Issue 11703: Add version number to OIDC client Subsystem-Name
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
Labels: CLA Signed, team:Security SSO

#13470 Switch restConnector-2.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restConnector2.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restConnector2.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restHandler1.0.jakarta.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restHandler1.0.javaee.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/com.ibm.websphere.appserver.jakartaee-9.0.feature
Labels: CLA Signed, jakartaEE

#13492 13488: Reorder the unknown frame type test
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/GenericFrameTests.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13409 Refresh renewable Kerberos tickets if there is <10m left on the renewtime
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/internal/LRUCache.java
Labels: CLA Signed, team:Zombie Apocalypse

#13486 Upgrade to Yasson 1.0.8
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.clientcontainer.json_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/bnd.bnd
  dev/com.ibm.ws.jsonb_fat/build.gradle
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.bnd
  dev/com.ibm.ws.org.eclipse.yasson.1.0/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#13501 13500: Update the connectMethod tests to avoid ending prematurely
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/HttpMethodTests.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13028 13027 - jaxrs shouldn't cache SSLSocketFactories in order to propegat…
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/component/SSLSupportService.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#13210 Output msg when is beta release
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessControlHelper.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/productinfo/ProductInfo.java
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
Labels: ID reviewed, L2 Reviewed

#13451 Fix description for jsonAccessLogFields for Logstash Collector
  dev/com.ibm.ws.logstash.collector/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logstash.collector/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#13478 [13476] JAX-RS 3.0 Client SSL Support
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jaxrs2.2-ssl1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jaxrs3.0-ssl1.0.feature
  dev/io.openliberty.jaxrs.3.0.client_fat/.classpath
  dev/io.openliberty.jaxrs.3.0.client_fat/.project
  dev/io.openliberty.jaxrs.3.0.client_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.3.0.client_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.3.0.client_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.3.0.client_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.3.0.client_fat/bnd.bnd
  dev/io.openliberty.jaxrs.3.0.client_fat/fat/src/io/openliberty/jaxrs30/client/fat/FATSuite.java
  dev/io.openliberty.jaxrs.3.0.client_fat/fat/src/io/openliberty/jaxrs30/client/fat/SslTest.java
  dev/io.openliberty.jaxrs.3.0.client_fat/fat/src/io/openliberty/jaxrs30/client/fat/ssl/Resource.java
  dev/io.openliberty.jaxrs.3.0.client_fat/fat/src/io/openliberty/jaxrs30/client/fat/ssl/SslTestServlet.java
  dev/io.openliberty.jaxrs.3.0.client_fat/publish/servers/ssl/bootstrap.properties
  dev/io.openliberty.jaxrs.3.0.client_fat/publish/servers/ssl/resources/security/clientInvalidTrust.jks
  dev/io.openliberty.jaxrs.3.0.client_fat/publish/servers/ssl/resources/security/key.jks
  dev/io.openliberty.jaxrs.3.0.client_fat/publish/servers/ssl/resources/security/trust.jks
  dev/io.openliberty.jaxrs.3.0.client_fat/publish/servers/ssl/server.xml
  dev/io.openliberty.jaxrs.internal.ssl/.classpath
  dev/io.openliberty.jaxrs.internal.ssl/.gitignore
  dev/io.openliberty.jaxrs.internal.ssl/.project
  dev/io.openliberty.jaxrs.internal.ssl/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.internal.ssl/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.internal.ssl/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.internal.ssl/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.internal.ssl/bnd.bnd
  dev/io.openliberty.jaxrs.internal.ssl/src/io/openliberty/jaxrs/internal/ssl/component/SslClientBuilderListener.java
  dev/io.openliberty.jaxrs.internal.ssl/src/io/openliberty/jaxrs/internal/ssl/component/package-info.java
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.client.ClientBuilder
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/jaxrs/client/ClientBuilderListener.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/jaxrs/client/package-info.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/client/LibertyResteasyClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/client/package-info.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#13517 Add option to export services and add Bad Auth tests
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesTests.java
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/api/ConsumerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerServiceRestClient.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/utilsConsumer/ConsumerUtils.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/client/ProducerEndpointFATServlet.java
Labels: CLA Signed, noproductcode

#13504 Address review comments
  dev/io.openliberty.microprofile.lra.1.0.internal/resources/io/openliberty/microprofile/lra/internal/resources/Lra.nlsprops
  dev/io.openliberty.microprofile.lra.1.0.internal/src/io/openliberty/microprofile/lra/internal/LraFilterComponent.java
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/lra/tck/LraTckLauncher.java
  dev/io.openliberty.org.eclipse.microprofile.lra.1.0/bnd.bnd
  dev/io.openliberty.org.jboss.narayana.rts/bnd.bnd
Labels: CLA Signed, ID reviewed

#13491 Refactor and Add beta features to AppClient feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appclient.appClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appclient.appClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-9.0/io.openliberty.jakartaeeClient-9.0.feature
Labels: CLA Signed

#13516 13054: H2 tests timing out
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
Labels: CLA Signed, in:Transport, team:Sirius

#13513 managed executor copy stage and getThreadContext
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.1/com.ibm.websphere.appserver.mpContextPropagation-1.1.feature
  dev/com.ibm.websphere.org.eclipse.microprofile.contextpropagation.1.1/.classpath
  dev/com.ibm.websphere.org.eclipse.microprofile.contextpropagation.1.1/.project
  dev/com.ibm.websphere.org.eclipse.microprofile.contextpropagation.1.1/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.contextpropagation.1.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.org.eclipse.microprofile.contextpropagation.1.1/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/.classpath
  dev/com.ibm.ws.concurrent.mp_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextProp1_1_Test.java
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPContextProp1_1_Server/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPContextProp1_1_Server/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPContextProp1_1_App/src/concurrent/mp/fat/v11/web/MPContextProp1_1_TestServlet.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextualDefaultExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/MPContextPropagationVersion.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ThreadContextImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#13497 Correct springboot feature subsystem names
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-1.5/com.ibm.websphere.appserver.springBoot-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-2.0/com.ibm.websphere.appserver.springBoot-2.0.feature
Labels: CLA Signed

#13529 Add source repo dependabot
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#13384 Create KeyAlgorithmChecker class for JWT and others
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/crypto/KeyAlgorithmChecker.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/crypto/KeyAlgorithmCheckerTest.java
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/BuilderImpl.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtComponent.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtData.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/web/JwtEndpointServices.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder/bootstrap.properties
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
Labels: team:Security SSO

#13347 Add throttle code
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitImpl.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitSectionImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLostLogOwnershipException.java
Labels: CLA Signed

#13462 Update Fault Tolerance 3.0 to work with MP Metrics 3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance3.0-metrics.feature
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/removal/MetricListServlet.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/publish/servers/CDIFaultToleranceMetricsRemoval/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal.metrics/bnd.bnd
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/servers/FaultTolerance30TCKServer/server.xml
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed

#13482 Fix defect 276522- Re-introduce custom orbSSLInitTimeout to cdi.visibility_fat servers
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12BasicServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12EJBServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12SharedLibraryServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12ValidatorInJarServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12WarLibsAccessWarServer/server.xml
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/visTestServer/server.xml
Labels: CLA Signed, in:CDI/1.2, noproductcode, test bug

#13496 gRPC client ssl configuration support
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.grpcClientSecurity-1.0.feature
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/KeyStoreService.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/KeyStoreServiceImpl.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/internal/KeyStoreServiceImplTest.java
  dev/io.openliberty.grpc.1.0.internal.client.security/.classpath
  dev/io.openliberty.grpc.1.0.internal.client.security/.project
  dev/io.openliberty.grpc.1.0.internal.client.security/.settings/bndtools.core.prefs
  dev/io.openliberty.grpc.1.0.internal.client.security/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/src/io/openliberty/grpc/internal/client/security/ssl/LibertyGrpcClientSSLSupport.java
  dev/io.openliberty.grpc.1.0.internal.client.security/src/io/openliberty/grpc/internal/client/security/ssl/package-info.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/GrpcClientComponent.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/GrpcSSLService.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyClientInterceptor.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyManagedChannelProvider.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/security/LibertyGrpcClientOutSSLSupport.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/security/authorization/LibertyGrpcAuthPropagationSupport.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/security/authorization/oauth/GrpcOAuthPropagationHelper.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/security/authorization/oauth/package-info.java
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/security/authorization/package-info.java
Labels: CLA Signed, in:Transport, team:Sirius

#13530 Support for krb5TicketCache on authData element
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.security.auth.data.common/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.auth.data.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/websphere/security/auth/data/AuthData.java
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/ws/security/auth/data/internal/AuthDataImpl.java
  dev/com.ibm.ws.security.auth.data.common/test/com/ibm/websphere/security/auth/data/AuthDataProviderTest.java
  dev/com.ibm.ws.security.auth.data/test/com/ibm/websphere/security/auth/data/WSPrincipalMappingLoginModuleTest.java
  dev/com.ibm.ws.security.jca/src/com/ibm/ws/security/jca/internal/AuthDataServiceImpl.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/KerberosService.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/AuthData.java
Labels: CLA Signed, team:Zombie Apocalypse

#13533 13532: Turn on trace for problematic H2 tests
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.secure/bootstrap.properties
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13520 Flip beta flag
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.clientContainerRemoteSupport-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.jndiClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-9.0/io.openliberty.jakartaeeClient-9.0.feature
Labels: CLA Signed

#13523 Make searching END line more specific to avoid intermittent FAT failures
  dev/com.ibm.ws.request.probes_fat/fat/src/com/ibm/ws/request/probe/fat/RequestProbeTestDynamicFeatureChange.java
Labels: CLA Signed, noproductcode

#13538 Disable OIDC RP certification FAT
  dev/com.ibm.ws.security.social_fat.oidcCertification/build.gradle.disable
Labels: CLA Signed, noproductcode, team:Security SSO

#13543 Issue 13542: Skip response check when grabbing cert for Acme FATs
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security

#13541 Set min java level to 11
  dev/com.ibm.ws.jdbc_fat_v43/bnd.bnd
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#13555 Issue #13551: Avoid EJB module start on server stop
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBModuleRuntimeContainerImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#13527 move gRPC dependencies to 1.31.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletServerStream.java
Labels: CLA Signed, in:Transport, team:Sirius

#13560 Issue 13559: Longer BoulderContainer timeout
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
Labels: CLA Signed, noproductcode

#13570 Issue #13596: URBridge needs to return the security name so that it a…
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
Labels: CLA Signed, team:Wendigo East

#13545 13534: Turn on trace for grpc tests
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServer/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServerOnly/bootstrap.properties
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13558 SPNEGO support for datasources
  dev/com.ibm.ws.jca.cm/bnd.bnd
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManager.java
Labels: CLA Signed, team:Zombie Apocalypse

#13588 release connection after checking http status code
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/browser/HttpClientBrowser.java
Labels: CLA Signed, noproductcode

#13546 Create microProfile-4.0
  dev/build.image/build.gradle
  dev/build.image/profiles/microProfile4/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/io.openliberty.microProfile-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/resources/l10n/io.openliberty.microProfile-4.0_zh_TW.properties
  dev/com.ibm.ws.microprofile.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.0_fat/fat/src/com/ibm/ws/microprofile10/fat/suite/SimpleJAXRSCDITest.java
  dev/com.ibm.ws.microprofile.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.1.2_fat/fat/src/com/ibm/ws/microprofile12/fat/suite/SimpleJAXRSCDITest.java
  dev/wlp-gradle/propertiesSettings.gradle
Labels: CLA Signed, L2 ReviewNotRequired, in:MicroProfile, team:MicroProfileUK

#13405 Handle retryable kafka exceptions gracefully
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/src/com/ibm/ws/microprofile/reactive/messaging/kafka/adapter/KafkaAdapterFactory.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/CommittingPartitionTracker.java
Labels: CLA Signed

#13590 Tolerate underscores in gRPC method names
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletUtils.java
Labels: CLA Signed, in:Transport, team:Sirius

#12874 mpHealth-2.0 Readiness check to report DOWN when application fails to start
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/.classpath
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/ApplicationStateHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DifferentApplicationNameHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/MultipleHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/permissions.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/files/applicationstate-fails-server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/files/applicationstate-original-server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/files/delayed-server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/src/com/ibm/ws/microprofile/health20/fails/to/start/health/check/app/BasicMessagingBean.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/src/com/ibm/ws/microprofile/health20/fails/to/start/health/check/app/FailingReadinessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/FailsToStartHealthCheckApp/src/com/ibm/ws/microprofile/health20/fails/to/start/health/check/app/FailsToStartServlet.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/SuccessfulHealthCheckApp/src/com/ibm/ws/microprofile/health20/successful/health/checks/app/TestLivenessCheck.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/SuccessfulHealthCheckApp/src/com/ibm/ws/microprofile/health20/successful/health/checks/app/TestReadinessCheck.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTracker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
Labels: CLA Signed

#13556 [13549] Resolve CDI warnings at startup
  dev/io.openliberty.jaxrs.3.0_fat/fat/src/io/openliberty/jaxrs30/fat/AppAndResourceTest.java
  dev/io.openliberty.jaxrs.3.0_fat/publish/servers/appandresource/bootstrap.properties
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/beans.xml
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/component/ResteasyInjectionClassListCollaborator.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#13611 Revert "Issue #13596: URBridge needs to return the security name so that it a…"
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
Labels: CLA Signed

#13604 PII TVT updates for 20.0.0.9
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/cs/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/de/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/fr/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/hu/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/it/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/ja/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/ko/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/pt-br/messages.js
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/nls/zh/messages.js
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#13614 Update Yoko binaries with support for IIOP transmission of Supplemental Multilingual Plane characters (such as emoji) in (wide) Strings
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#13606 gRPC TLS tests shouldn't run on java 8
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTlsTest.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#13623 Rename the el-4.0 feature NLS file to match symbolicName
  dev/com.ibm.websphere.appserver.features/visibility/public/el-4.0/resources/l10n/io.openliberty.el-4.0.properties
Labels: CLA Signed, in:Web Components, team:Sirius

#13625 Increase the fudgeFactorTime for the testTimeoutNonRoutable Test to account for slow build systems
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clienttimeout/src/com/ibm/ws/jaxrs21/client/jaxrs21clienttimeout/client/JAXRS21ClientTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#13618 add trace to catch an error message getting generated
  dev/com.ibm.ws.grpc_fat/publish/servers/ConsumerServer/server.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/ProducerServer/server.xml
Labels: CLA Signed, noproductcode

#13531 Adding debug to ProductFeatureTestForBug
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ProductFeatureTest.java
Labels: CLA Signed, noproductcode

#13615 Add grpc-1.0 and grpcClient-1.0 feature descriptions
  dev/com.ibm.websphere.appserver.features/visibility/public/grpc-1.0/resources/l10n/io.openliberty.grpc-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/resources/l10n/io.openliberty.grpcClient-1.0.properties
Labels: CLA Signed, in:Transport, team:Sirius

#13616 Set mark to end of log before performing config update
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#13621 Krb5 fat kinit toleration
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#13100 13032 Answer empty stream instead of null for directory entries.
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
Labels: CLA Signed, bug, release bug

#13637 FVT: allow for multiple concurrent client stream connection testing
  dev/com.ibm.ws.grpc_fat/test-applications/StoreApp.war/src/com/ibm/testapp/g3store/grpcservice/StoreProducerService.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/restProducer/api/ProducerRestEndpoint.java
  dev/com.ibm.ws.grpc_fat/test-applications/StreamingService.war/src/com/ibm/ws/grpc/fat/streaming/service/StreamingServlet.java
Labels: CLA Signed, noproductcode

#13631 Redlist docker-engine machines in the libhpike cluster for jdbc_fat_krb5
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse
