Repository OpenLiberty/open-liberty, pull requests merged in 2021-10, with the labels that each got.

#18811 Add check for hardware type
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
Labels: CLA Signed

#18495 gRPC services need to tolerate EAR packaging
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldEarTest.java
  dev/com.ibm.ws.grpc_fat/publish/servers/HelloWorldServerEar/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/HelloWorldServerEar/server.xml
  dev/com.ibm.ws.grpc_fat/test-applications/HelloWorldApp.ear/resources/META-INF/application.xml
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/GrpcMessages.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/config/GrpcServiceConfigHolder.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/config/GrpcServiceConfigImpl.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/config/GrpcServiceConfigValidation.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/security/GrpcResponseFilter.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/security/GrpcSecurityOutputWriter.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/security/GrpcSecurityServletResponseWrapper.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/security/GrpcServerSecurity.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/security/UnauthorizedException.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletApplication.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletUtils.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/LibertyAuthorizationInterceptor.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/server/monitor/GrpcMonitoringServerInterceptorService.java
  dev/io.openliberty.grpc.1.0.internal/test/io/openliberty/grpc/internal/config/GrpcServiceConfigTest.java
  dev/io.openliberty.grpc.1.0.internal/test/io/openliberty/grpc/internal/servlet/GrpcServletTest.java
Labels: CLA Signed

#18804 add kerberos trace to spnegofat1
  dev/com.ibm.ws.security.spnego_fat.1/publish/servers/S4U2ProxyTest/bootstrap.properties
  dev/com.ibm.ws.security.spnego_fat.1/publish/servers/S4U2SelfTest/bootstrap.properties
Labels: noproductcode, CLA Signed, team:Core Security

#18588 Add OpenJDK 17 to skip list for Windows ACME FAT
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East, team:Core Security

#15680 Update xercesImpl to 2.12.1
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.org.apache.taglibs.standard/bnd.bnd
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
  dev/io.openliberty.org.apache.xerces/.classpath
  dev/io.openliberty.org.apache.xerces/.project
  dev/io.openliberty.org.apache.xerces/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.xerces/bnd.bnd
  dev/io.openliberty.xml-apis/.classpath
  dev/io.openliberty.xml-apis/.project
  dev/io.openliberty.xml-apis/.settings/bndtools.core.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xml-apis/bnd.bnd
Labels: CLA Signed

#18319 Add timeout for windows service commands
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#18797 Add mp jwt20 tck fat
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.classpath
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.project
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/bnd.bnd.disabled
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/Readme.txt
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/DummyForQuarantine.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/FATSuite.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/Mpjwt20TCKLauncher_aud_env.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/Mpjwt20TCKLauncher_aud_noenv.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/Mpjwt20TCKLauncher_aud_noenv2.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/Mpjwt20TCKLauncher_noaud_env.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/com/ibm/ws/microprofile/mpjwt20/tck/Mpjwt20TCKLauncher_noaud_noenv.java
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/server.env
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/server.env
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/server.env
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/bootstrap.properties
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/resources/security/key.jks
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/server.env
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_env.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv2.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_env.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/tck_suite_noaud_noenv.xml
Labels: noproductcode, CLA Signed

#18814 NullPointerException from transactions while computing message for different error
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTranManagerImpl.java
Labels: team:Zombie Apocalypse, CLA Signed

#18830 Issue 18828: Remove Oracle Ldap refs from FATs
  dev/com.ibm.ws.com.unboundid/resources/SunOne.ldif
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryDynamicUpdateTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.multipleldaps/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.attrMappingVar4/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.default/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun/server.xml
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/DefaultWIMRealmMultipleReposTest.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPFatUtils.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed, team:Wendigo East

#18856 Revert "Update xercesImpl to 2.12.1"
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.org.apache.taglibs.standard/bnd.bnd
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
  dev/io.openliberty.org.apache.xerces/.classpath
  dev/io.openliberty.org.apache.xerces/.project
  dev/io.openliberty.org.apache.xerces/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.xerces/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.xerces/bnd.bnd
  dev/io.openliberty.xml-apis/.classpath
  dev/io.openliberty.xml-apis/.project
  dev/io.openliberty.xml-apis/.settings/bndtools.core.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xml-apis/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xml-apis/bnd.bnd
Labels: CLA Signed

#18456 Update jandex to 2.4.0 and smallrye-open-api to 2.1.15
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.anno/publish/jandex/typeannotation-test-1.8-jar-v10.idx
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/jandex/internal/SparseIndexReaderVersionImpl_V2.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/JandexSparseReadTest.java
  dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/JandexTestData.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/User.java
  dev/com.ibm.ws.org.jboss.jandex/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/cache/ConfigSerializer.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/cache/ConfigSerializerTest.java
Labels: CLA Signed

#18820 More detailed messages/logs
  dev/com.ibm.ws.collector.manager/test/com/ibm/ws/collector/manager/buffer/RingBufferTest.java
Labels: noproductcode, CLA Signed

#18845 Issue #18781: Upgrade Bouncy Castle dependencies from 1.61 to 1.69.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.net.shibboleth.utilities.java.support.7.5.1/bnd.overrides
  dev/com.ibm.ws.org.apache.wss4j.ws.security.common.2.3.0/bnd.overrides
  dev/com.ibm.ws.org.cryptacular.cryptacular/bnd.bnd
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/bnd.overrides
  dev/com.ibm.ws.security.acme/bnd.bnd
Labels: CLA Signed

#18651 fix excessive servlet destroyed msgs
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestEDR.war/resources/WEB-INF/tags/sampleTag.tld
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestEDR.war/resources/index.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JspDependent.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#18802 fix installUtility bug
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#18627 enable Resteasy entry/exit trace for restfulWs-3.0
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/build.gradle
Labels: in:JAX-RS, CLA Signed

#18859 Eclipse updates from recent changes
  .github/test-categories/GENERAL
  .github/test-categories/MP_CONFIG
  .github/test-categories/MP_FAULT_TOLERANCE
  .github/test-categories/MP_HEALTH
  .github/test-categories/QUARANTINE
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation/ejb/beanvalidationEjb.jar/META-INF/persistence-oracle-21.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation/web/beanvalidationWeb.war/WEB-INF/classes/META-INF/persistence-oracle-21.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/ejb/beanvalidation20Ejb.jar/META-INF/persistence-oracle-21.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/web/beanvalidation20Web.war/WEB-INF/classes/META-INF/persistence-oracle-21.xml
  dev/io.openliberty.endpoint/.settings/bndtools.core.prefs
  dev/io.openliberty.endpoint/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.netty.internal.impl/.classpath
  dev/io.openliberty.org.glassfish.hk2.osgi-resource-locator/.classpath
Labels: noproductcode, CLA Signed, team:Performance

#18798 [18794] LibertyAuthFilter for checking RoleMethodAuthUtil
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-appSecurity4.0.feature
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/bnd.bnd
  dev/io.openliberty.restfulWS30.appSecurity/.classpath
  dev/io.openliberty.restfulWS30.appSecurity/bnd.bnd
  dev/io.openliberty.restfulWS30.appSecurity/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS30.appSecurity/src/io/openliberty/restfulWS30/appSecurity/LibertyAuthFilter.java
  dev/io.openliberty.restfulWS30.appSecurity/src/io/openliberty/restfulWS30/appSecurity/package-info.java
Labels: in:JAX-RS, CLA Signed, team:Wendigo West

#18889 Fix NPE in URAPIs_ADWildCardTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADWildCardTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#16811 Response output may not close at end of dispatch forward
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC5CloseWrappedResponseOutputAfterForwardTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCCloseWrappedResponseOutputAfterForwardTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_closeWrappedOutputStreamAfterForward/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_closeWrappedOutputStreamAfterForward/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_closeWrappedOutputStreamAfterForward/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/displayPage.jsp
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/indexNoWrap.jsp
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/wrapped/indexWrapped.jsp
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/src/filterandwrapper/war/files/MyFilter.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/src/filterandwrapper/war/files/MyResponseWrapper.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
Labels: in:Web Components, ID reviewed, CLA Signed, release bug, team:Sirius

#18864 Wait for config update
  dev/com.ibm.ws.config.variables_fat/fat/src/test/server/config/ServiceBindingVarTests.java
Labels: noproductcode, CLA Signed

#18881 remove double output
  dev/com.ibm.ws.os.packaging_fat/fat/src/com/ibm/ws/os/packaging/fat/InstallUtilityToolTest.java
Labels: in:Install, test bug

#18895 Stop allowing creation of H2 streams if server is closing
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2InboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: in:Transport, CLA Signed, team:Sirius

#19155 Upgrade RESTEasy to 4.7.2.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.mprestclient/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider/bnd.bnd
Labels: CLA Signed

#19189 Add xtrace for fat debug
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/bootstrap.properties
Labels: noproductcode, CLA Signed

#19163 Split LDAP Kerberos bucket in 2 projects for slow Windows
  .github/test-categories/SECURITY_4
  dev/com.ibm.ws.security.spnego_fat/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.classpath
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.project
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/ApacheDSandKDC.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/CommonBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/KeytabBindLongRunTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/KeytabBindMultiRegistryTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/KeytabBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/Krb5ConfigTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/LdapApacheDSandKDC.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/SimpleBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindLongRunTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindMultiRegistryTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/utils/LdapKerberosUtils.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/files/credCacheExpired.cc
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/files/internalfeatures/securitylibertyinternals-1.0.mf
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/files/wrongUser.keytab
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/jvm.options
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.classpath
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.project
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/KeytabBadPrincipalNameTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/Krb5ConfigJVMProp.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/RealmNameJVMProp.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBadPrincipalJava8.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBadPrincipalNameTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindExpireTests.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/files/credCacheExpired.cc
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/files/internalfeatures/securitylibertyinternals-1.0.mf
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/files/wrongUser.keytab
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/jvm.options
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/server.xml
Labels: noproductcode, CLA Signed, team:Wendigo East
