Repository OpenLiberty/open-liberty, pull requests merged in 2021-02, with the labels that each got.

#15667 Issue 15637: Add metatype config and constants for Kerberos for Ldap
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ConfigConstants.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#15718 Added ignore msg CWWKS5524E
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/BasicAuthTest.java
Labels: CLA Signed, noproductcode

#14430 EL30 lookup improvement
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/BeanELResolver.java
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/ImportHandler.java
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/Jre9Compat.java
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/JreCompat.java
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/StaticFieldELResolver.java
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/Util.java
  dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/Jre9Compat.java
  dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/JreCompat.java
  dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/ReflectionUtil.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#15746 21.0.0.2 NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#15743 Policy was not honored for outbound requests.
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/policy/DynamicAttachmentProvider.java
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/policy/URIDomainExpression.java
Labels: CLA Signed

#15731 Fix JAXB-2.3 failure and expand XML Binding 3.0 tests
  dev/com.ibm.ws.jaxb_fat/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/test-applications/jaxbApp/src/jaxb/web/JAXBTestServlet.java
Labels: CLA Signed, noproductcode

#15700 fixing custom liberty variable parsing
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ConfigParser.java
Labels: CLA Signed

#15758 Resolve various MP Rest Client test issues
  dev/com.ibm.ws.jaxrs.2.0.security/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#15754 Revert surefire.verison from 2.19.1 to 2.17 for mpOpenApi TCKs
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#15764 Feature file updates to fix some errors
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-xmlws3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistence-3.0/io.openliberty.persistence-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistenceContainer-3.0/io.openliberty.persistenceContainer-3.0.feature
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/.settings/bndtools.core.prefs
Labels: CLA Signed, team:Performance

#15768 Issue 15766: Add beta tag to internal BindAuthMech Ldap props
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#15701 refactor useRemoteDocker logic
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15625 Allow IOE configuration for HTTP/2 connections
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: CLA Signed, in:Transport, team:Sirius

#15761 Remove beta fence for issue #15756
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
Labels: CLA Signed

#15772 Issue #15771: Add assert for LTPA configuration
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#15757 Fixed the HungRequestEnableThreadDumps FAT to wait for thread dump cr…
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/HungRequestEnableThreadDumps.java
Labels: CLA Signed, noproductcode

#15723 Add timestamps to mvnOutput attempt 2
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
Labels: CLA Signed, noproductcode

#15751 Issue #15750: Update test to wait for LTPA configuration to complete
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/FormLoginReadListenerTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#15721 more helpful error message for Jakarta/Java EE mismatch with resource adapter annotations
  dev/com.ibm.ws.jca.utils/resources/com/ibm/ws/jca/utils/internal/resources/JcaUtilsMessages.nlsprops
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/MetatypeGenerator.java
Labels: CLA Signed, ID reviewed, team:Zombie Apocalypse

#15753 Remove EJB feature from FAT
  dev/com.ibm.ws.jbatch.misc_fat/publish/servers/BatchDeserialize/server.xml
Labels: CLA Signed, noproductcode

#15788 Issue 15787: Move Kerberos messages to correct file
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/com/ibm/ws/security/wim/adapter/ldap/resources/LdapUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
Labels: CLA Signed, ID reviewed

#15777 update grpc dependencies to 1.35.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.grpc-1.0.feature
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcTestUtils.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppConsumerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/BeerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/streaming/service/StreamingServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/io/grpc/examples/helloworld/GreeterGrpc.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.interceptor.xml
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.server.cdi.xml
  dev/com.ibm.ws.grpc_fat/publish/servers/HelloWorldServer/server.xml
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletServerBuilder.java
  dev/io.openliberty.grpc.client.1.0.thirdparty/.classpath
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/src/io/grpc/netty/GrpcSslContexts.java
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
Labels: CLA Signed, in:Transport, team:Sirius

#15798 CL22321 add callback for policy executor shutdown
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#15795 15794 Test remove minify in packagerunnabletest
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#15807 Remove the EE9 skipped FAT tests from com.ibm.ws.jaxrs.2.1.client_fat JAXRS21ClientCompletionStageRxInvokerTest
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCallbackTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15646 Issue15644ProperMergingOfJava2Permissions
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Constants.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/FilePathUtil.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/GrantEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Parser.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParserException.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/java2sec/PermissionManagerTest.java
Labels: CLA Signed, release bug

#15784 Remove bad references
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version23.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version23.test.app/build.gradle
Labels: CLA Signed

#15800 Allow InvalidTransactionException
  dev/com.ibm.ws.wsat.concurrent_fat/fat/src/com/ibm/ws/wsat/fat/MultiThreadedTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi/fat/src/com/ibm/ws/wsat/fat/MultiRecoveryTest.java
Labels: CLA Signed, noproductcode

#15783 Rename faces-3.0 thirdparty jar
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
  dev/io.openliberty.faces.3.0.thirdparty/.classpath
  dev/io.openliberty.faces.3.0.thirdparty/.project
  dev/io.openliberty.faces.3.0.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.faces.3.0.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.faces.3.0.thirdparty/bnd.bnd
Labels: CLA Signed

#15796 Stop plugin_cfg.xml generation during server shutdown
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/osgi/mbeans/PluginGeneratorTest.java
Labels: CLA Signed, in:Web Components, team:Sirius

#15832 fix github action build
  .github/test-categories/TRANSACTION_1
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15835 ExternalBuild needs 3.4.1 version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#15816 Add new mpConfig escape characters in config value FAT test
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDIConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDIConfigServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDILibertyConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDILibertyConfigServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/ClassLoaderCacheServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/ClassLoadersServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/ClassLoadersServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/DynamicSourcesServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/OrdForDefaultsServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/OrdForDefaultsServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/SharedLibUserServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/SharedLibUserServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/SimpleConfigSourcesServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/SimpleConfigSourcesServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/SimultaneousRequestsServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/StressServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/brokenCDIConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/beans/ConfigPropertyBean.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/ConfigPropertyTestServlet.java
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#15823 Issue #15822: Group membership is ignored if the user does not have t…
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/com/ibm/ws/security/wim/adapter/ldap/resources/LdapUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapEntity.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LdapRdnTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_ADWildCardTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.rdn/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.rdn/server.xml
Labels: CLA Signed, team:Wendigo East

#15843 make test more consistent about task failure warnings
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/SwitchFromSingleInstanceToFailOverTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#15833 Remove artifact manifest file after bvt
  dev/com.ibm.ws.artifact_fat_bvt/fat/src/com/ibm/ws/artifact/fat_bvt/test/FATArtifactBVT.java
Labels: CLA Signed, noproductcode

#15836 Migrate more JPA Query FAT to OL
  dev/com.ibm.ws.jpa_spec10_query_fat/fat/src/com/ibm/ws/jpa/TestSVLLoopAnoQuery_Web.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/testlogic/JULoopQueryAnoTest.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/utils/DeptEmpListView.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/utils/DeptEmpView.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/utils/SimpleDeptEmpView.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/JULoopQueryAnoTestServlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_001_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_002_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_003_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_004_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_005_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_006_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_007_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_008_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_009_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_010_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_011_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_012_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_013_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_014_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_015_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_016_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_017_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_018_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_019_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_020_Servlet.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_021_Servlet.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#15844 Update to use snapshot version of TCK with added timeout padding
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml-java8
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15848 Remove FT 3.0 dependency on concurrency-1.0
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-3.0/com.ibm.websphere.appserver.mpFaultTolerance-3.0.feature
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/interceptors/InterceptorTest.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/AsyncFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/publish/servers/JaxRsFaultTolerance/server.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.spi/bnd.bnd
  dev/com.ibm.ws.microprofile.faulttolerance/bnd.bnd
Labels: CLA Signed

#15839 missing escape character in regex
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/fat/src/com/ibm/ws/concurrent/persistent/fat/simctrl/SimulatedControllerTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15860 Get things building in eclipse again
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.support.version23.test.app/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2/.project
  dev/com.ibm.ws.transaction.cloud_fat.db2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.db2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.derby/.project
  dev/com.ibm.ws.transaction.cloud_fat.derby/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.derby/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.oracle/.project
  dev/com.ibm.ws.transaction.cloud_fat.oracle/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.oracle/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/.project
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/.project
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver/.project
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, team:Performance

#15654 Fix memory leak when applications do not close JAXRS Client objects.
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientBuilderImpl.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientStandaloneTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRSClientStandaloneTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/jaxrsclientstandalone/src/com/ibm/ws/jaxrs20/client/JAXRSClientStandalone/client/ClientTestServlet.java
Labels: CLA Signed, PerfAppPlatform, team:Performance

#15793 More tests for expandLocation property
  dev/com.ibm.ws.app.manager.war/resources/com/ibm/ws/app/manager/war/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfoFactoryImpl.java
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/war/internal/WARDeployedAppInfoFactoryImpl.java
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/ExpandLocationSetToEmptyString.xml
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/ExpandLocationSetToOutsideConfigDir.xml
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/ExpandLocationSetToURL.xml
Labels: CLA Signed, ID reviewed

#15850 Issue #15849: Increase timeout for createSpnAndKeytab SSH command.
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/MsKdcHelper.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#15859 Change @SkipForRepeat to show up as skipped in junit results
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode

#15861 CL22321 policy executor shutdown by identifier match
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutorProvider.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#15858 update Netty to 4.1.59.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
Labels: CLA Signed, in:Transport, team:Sirius

#15854 Relocated ltpa key locations to fix possible access problems
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/WebServiceMonitorTest/clearCache/server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/CXFJMXSupportTestServer/server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/WebServiceMonitorTestServer/server.xml
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#15806 Issue #12268: Update expression language 4.0 api/impl to 10.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-4.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/src/org/apache/el/lang/ELSupport.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#15815 Fix intermittent OAuth unit test failures
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/OAuth20EndpointServicesTest.java
Labels: CLA Signed, noproductcode, team:Security SSO

#15855 Change permissions for sqlserver HADB FAT
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/build.gradle
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/publish/servers/com.ibm.ws.transaction/server.xml
Labels: CLA Signed, noproductcode

#15856 Make test ordering irrelevant
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
Labels: CLA Signed, noproductcode

#15870 Add synchronized blocks to mpConfig AppPropertiesTrackingComponent
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/AppPropertiesTrackingComponent.java
Labels: CLA Signed, in:MicroProfile/Config

#15737 create full fat sub categories
  .github/workflow-scripts/GenerateCategories.java
  .github/workflow-scripts/check-fat-failures.sh
  .github/workflow-scripts/run-fat-build.sh
  .github/workflows/openliberty-ci.yml
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_v43/fat/src/com/ibm/ws/jdbc/fat/v43/FATSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15892 Continue if no modified categories
  .github/workflow-scripts/generate-params.sh
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15905 Update folder check
  .github/workflow-scripts/generate-params.sh
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15760 testcontainers example project
  .github/test-categories/GENERAL
  dev/build.example.testcontainers_fat/.classpath
  dev/build.example.testcontainers_fat/.project
  dev/build.example.testcontainers_fat/.settings/bndtools.core.prefs
  dev/build.example.testcontainers_fat/.settings/org.eclipse.core.resources.prefs
  dev/build.example.testcontainers_fat/.settings/org.eclipse.jdt.core.prefs
  dev/build.example.testcontainers_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/build.example.testcontainers_fat/bnd.bnd
  dev/build.example.testcontainers_fat/build.gradle
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ContainersTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/DatabaseRotationTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/DockerfileTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/FATSuite.java
  dev/build.example.testcontainers_fat/publish/files/postgres/Dockerfile
  dev/build.example.testcontainers_fat/publish/files/postgres/release.sh
  dev/build.example.testcontainers_fat/publish/files/postgres/scripts/initDB.sql
  dev/build.example.testcontainers_fat/publish/servers/build.example.testcontainers.dbrotation/bootstrap.properties
  dev/build.example.testcontainers_fat/publish/servers/build.example.testcontainers.dbrotation/server.xml
  dev/build.example.testcontainers_fat/publish/servers/build.example.testcontainers/bootstrap.properties
  dev/build.example.testcontainers_fat/publish/servers/build.example.testcontainers/server.xml
  dev/build.example.testcontainers_fat/test-applications/app/src/web/dbrotation/DbRotationServlet.java
  dev/build.example.testcontainers_fat/test-applications/app/src/web/generic/ContainersTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15871 Make saml fat gradle more common
  dev/com.ibm.ws.security.saml.sso_fat.2/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.2/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.3/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.3/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.config/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.config/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.logout/gradle.properties
  dev/com.ibm.ws.security.saml.sso_fat/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat/gradle.properties
Labels: CLA Signed, noproductcode, team:Security SSO, test debt

#15901 Issue 15900: Add new fat project for Kerberos Ldap
  .github/test-categories/SECURITY_4
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.classpath
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.project
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/publish/servers/FATServer/server.xml
Labels: CLA Signed, noproductcode

#15915 Issue #15914:Add FFDCAllow for IOException
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
Labels: CLA Signed, noproductcode

#13173 JSP To Load Versions Dynamically
  dev/com.ibm.ws.javaee.version/src/com/ibm/ws/javaee/version/PagesVersion.java
  dev/com.ibm.ws.jsp.2.3/bnd.bnd
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/translator/visitor/generator/GeneratorUtilsExtImpl.java
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/webcontainerext/JspVersionFactoryImpl.java
  dev/com.ibm.ws.jsp.2.3/src/com/ibm/ws/jsp23/webcontainerext/JspVersionImpl.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
  dev/com.ibm.ws.jsp.factories/bnd.bnd
  dev/com.ibm.ws.jsp.factories/src/com/ibm/ws/jsp22/translator/visitor/generator/GeneratorUtilsExtImpl.java
  dev/com.ibm.ws.jsp.factories/src/com/ibm/ws/jsp22/webcontainerext/JspVersionFactoryImpl.java
  dev/com.ibm.ws.jsp/bnd.bnd
  dev/com.ibm.ws.jsp/resources/com/ibm/ws/jsp/resources/messages.nlsprops
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionProcessor.java
  dev/wlp-jakartaee-transform/rules/jakarta-jspVersion.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#15880 CL22143 commonjTimerManager simplicity object
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/CommonjTimerManager.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15895 DatabaseContainerType change
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
Labels: CLA Signed, noproductcode

#15922 Revert "Issue15644ProperMergingOfJava2Permissions"
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Constants.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/FilePathUtil.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/GrantEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Parser.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParserException.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/java2sec/PermissionManagerTest.java
Labels: CLA Signed

#15874 Add db retry logic to sqlserver hadb test
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/fat/src/com/ibm/ws/transaction/test/FailoverTest.java
Labels: CLA Signed, noproductcode

#15898 Port EJBStatefulCacheTest to ejb legacy fat
  dev/com.ibm.ws.ejbcontainer.legacy_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.legacy_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.legacy_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/CacheTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.notrace/.gitignore
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.notrace/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.notrace/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/resources/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/resources/META-INF/ibm-ejb-jar-ext.xmi
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/InitRecoveryLogBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/InitRecoveryLogHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/InitRecoveryLogObj.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/StatefulBMTBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/StatefulBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/StatefulLocalHome.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/StatefulLocalObject.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheEJB.jar/src/com/ibm/ejb2x/base/cache/ejb/StatefulSynchBean.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheWeb.war/src/com/ibm/ejb2x/base/cache/web/StatefulOnceServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheWeb.war/src/com/ibm/ejb2x/base/cache/web/StatefulTranServlet.java
Labels: CLA Signed, noproductcode

#15894 Adding deadline to Templates for blog posts
  .github/ISSUE_TEMPLATE/blog_post_beta.md
  .github/ISSUE_TEMPLATE/blog_post_ga_release.md
Labels: noproductcode

#15883 Issue #15785: NPE in ConfigVar Introspection at server dump
  dev/com.ibm.ws.diagnostics/src/com/ibm/ws/diagnostics/osgi/ConfigVariableIntrospection.java
Labels: CLA Signed, release bug

#15863 Improve build performance
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security.2.6.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security/build.gradle
  dev/com.ibm.ws.org.openid4java/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.api.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml/build.gradle
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/gradle.properties
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
  dev/wlp-gradle/utility/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#15931 Reduce max heap size to 1GB for MP Rest Client 1.0/1.1 TCK FATs
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15933 Fix MP Config Optional Lists
  dev/com.ibm.ws.microprofile.config.1.1.cdi/src/com/ibm/ws/microprofile/config/cdi/ConfigCDIExtension.java
  dev/com.ibm.ws.microprofile.config.1.1.cdi/src/com/ibm/ws/microprofile/config/cdi/ConfigProducer.java
  dev/com.ibm.ws.microprofile.config.1.1.cdi/src/com/ibm/ws/microprofile/config/cdi/ConfigPropertyBean.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/converters/DefaultConverters.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/converters/OptionalConverter.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractConfig.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/interfaces/WebSphereConfig.java
  dev/com.ibm.ws.microprofile.config.1.1/test/src/com/ibm/ws/microprofile/config/extended/test/WebSphereConfigTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/ConfigTCKLauncher.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/test-applications/converterApp/src/com/ibm/ws/microprofile/config12/converter/type/web/TypeConverterBean.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/test-applications/converterApp/src/com/ibm/ws/microprofile/config12/converter/type/web/TypeConverterServlet.java
  dev/com.ibm.ws.microprofile.config.1.3/src/com/ibm/ws/microprofile/config13/converters/Config13DefaultConverters.java
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#15887 Move grpc and netty dependencies to oss_source_dependencies
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
Labels: CLA Signed, in:Build, team:Sirius

#15937 Backport TCK snapshot with timeout changes to MP Rest Client 1.2-1.4
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15735 Issue 15640: Add Ldap kerberos runtime support
  dev/com.ibm.websphere.appserver.features/visibility/public/ldapRegistry-3.0/com.ibm.websphere.appserver.ldapRegistry-3.0.feature
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/com/ibm/ws/security/wim/adapter/ldap/resources/LdapUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/wim/LdapRegistry.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Core Security, team:Wendigo East

#15876 Issue #15744: Update JSF 2.3 to 2.3.8
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/io.openliberty.faces.internal/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#15879 15878 - use the default SSL port if no port is specified when getting the SSLSocketFactory
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15911 CL22150 make await method available for other internal components
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyTaskFuture.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyTaskFutureImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#15950 Revert "Improve build performance"
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security.2.6.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security/build.gradle
  dev/com.ibm.ws.org.openid4java/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.api.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml/build.gradle
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/gradle.properties
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
  dev/wlp-gradle/utility/build.gradle
Labels: CLA Signed, team:Continuous Delivery

#15949 #15916: Adding test case for expandLocation where expand loc is not a…
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/testWarApplication.war
Labels: CLA Signed, noproductcode

#15941 Adding diagnostics for MP Rest Client FAT tests
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/GenericSubscriber.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseResource.java
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15944 Merge multi-homed environment related changes into Liberty
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/jain/protocol/ip/sip/header/HeaderImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/BranchManager.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/SipProxyInfo.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/B2buaHelperImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/IncomingSipServletRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/OutgoingSipServletAckRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/OutgoingSipServletRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/OutgoingSipServletResponse.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/SipServletMessageImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/sessions/SipTransactionUserTable.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/tu/TransactionUserImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/parser/MessageParser.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/parser/SipConstants.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/parser/StreamMessageParser.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/properties/CoreProperties.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/properties/StackProperties.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transactions/ct/SIPInviteClientTransactionImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transport/SIPConnectionsModel.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transport/TransportCommLayerMgr.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/util/SIPStackUtil.java
Labels: CLA Signed

#15930 Invalidate cached config when an error or warning occurs
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigUpdater.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerConfiguration.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
Labels: CLA Signed

#15885 Upgrade ASM to 9.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: CLA Signed, team:Zombie Apocalypse

#15946 Issue 15945: move CWPKI2052I earlier when checking for renewed certs
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#15947 14471 - repeat the valid com.ibm.ws.jaxrs.2.0.cdi.1.2_fat tests with restfulWs-3.0
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/Basic12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/Complex12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/ContextandCDI12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/DisableTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/LifeCycle12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/LifeCycleMismatch12Test.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15709 Bundle Netty Maven Jars into an independant internal feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.io.netty.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.io.netty.ssl.feature
  dev/io.openliberty.io.netty.ssl/.classpath
  dev/io.openliberty.io.netty.ssl/.project
  dev/io.openliberty.io.netty.ssl/.settings/bndtools.core.prefs
  dev/io.openliberty.io.netty.ssl/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/.classpath
  dev/io.openliberty.io.netty/.project
  dev/io.openliberty.io.netty/.settings/bndtools.core.prefs
  dev/io.openliberty.io.netty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.netty/bnd.bnd
Labels: CLA Signed

#15963 Issue 15962: Swap out CRED constants for string on Ldap Kerberos
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/ContextManager.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#15932 Add jwtsso fat for encryption (with tests disabled until runtime supports)
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/EncryptionTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_signES384EncryptRS256.xml
  dev/com.ibm.ws.security.jwtsso_fat/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_signRS512EncryptES256.xml
Labels: CLA Signed, noproductcode, team:Security SSO, test delivery

#15928 Revert "Revert "Issue15644ProperMergingOfJava2Permissions""
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Constants.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/FilePathUtil.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/GrantEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/Parser.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParserException.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionEntry.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/java2sec/PermissionManagerTest.java
Labels: CLA Signed

#15904 First attempt at JWT consumer caching
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/SingleTableCache.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/JwtCacheTest.java
Labels: CLA Signed, team:Security SSO

#15967 Fix NPE in AbstractNotificationTest for empty fileList
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/AbstractNotificationTest.java
Labels: CLA Signed, noproductcode

#15918 EJB change gradle task for pulling in rar fat tool project
  dev/com.ibm.ws.ejbcontainer.injection_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/build.gradle
Labels: CLA Signed, noproductcode

#15544 Issue 15543: Add debug from Boulder for acme fats
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/boulder/BoulderContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeRevocationTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#15957 Add new message and warnning for when exception is caught by the default exception mapper
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/resources/io/openliberty/microprofile/metrics/internal/monitor/resources/MonitorMetrics.nlsprops
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MetricsJaxRsEMCallbackImpl.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/fat/src/io/openliberty/microprofile/metrics30/internal/tck/launcher/MetricsTCKLauncher.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingRestClientTCKLauncher.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncher.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncherMicroProfile.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#15980 Defer EJBHome lookup until first use
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/util/UUID.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EntityHandle.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EntityHomeHandle.java
  dev/com.ibm.ws.ejbcontainer.remote.portable.core/src/com/ibm/ws/ejb/portable/EJBMetaDataImpl.java
  dev/com.ibm.ws.ejbcontainer.remote.portable.core/src/com/ibm/ws/ejb/portable/HomeHandleImpl.java
Labels: CLA Signed, in:EJB Container, team:Blizzard

#15981 Try defining jboss-servlet-api_3.0_spec version in TCKs
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/Config, in:MicroProfile/FaultTolerance, in:MicroProfile/OpenAPI, noproductcode, team:MicroProfileUK

#15983 initial integration point and mock DataStoreHelper and driver for tests
  .github/test-categories/JDBC
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/bnd.bnd
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/package-info.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/DSConfig.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_heritage/.classpath
  dev/com.ibm.ws.jdbc_fat_heritage/.project
  dev/com.ibm.ws.jdbc_fat_heritage/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat_heritage/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_heritage/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_heritage/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_heritage/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_heritage/build.gradle
  dev/com.ibm.ws.jdbc_fat_heritage/fat/src/test/jdbc/heritage/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_heritage/fat/src/test/jdbc/heritage/HeritageJDBCTest.java
  dev/com.ibm.ws.jdbc_fat_heritage/jdbcHeritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritage/jdbc_fat_heritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritage/publish/files/features/jdbcHeritage-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritage/publish/files/internalFeatures/dataStoreHelper-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritage/publish/servers/com.ibm.ws.jdbc.heritage/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_heritage/publish/servers/com.ibm.ws.jdbc.heritage/server.xml
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-bundles/jdbcHeritage/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc_fat_heritage/test-bundles/jdbcHeritage/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#15917 Check for Beta edition and include beta elements
  dev/com.ibm.ws.config.schemagen/test/com/ibm/ws/config/schemagen/internal/Generatorv2WithSchmea11BetaBuildTest.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
Labels: CLA Signed

#15602 Move wsoc 2 bundle api to private feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.0/io.openliberty.websocket-2.0.feature
Labels: CLA Signed, in:Transport, team:Sirius

#15994 Remove bottleneck in transaction code
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: CLA Signed, performance, team:Performance

#15813 Add debug to File#renameTo in PluginGenerator
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Sirius

#15977 Create a UDP connection using the selected outbound interface
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transport/TransportCommLayerMgr.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/sip/SipUdpConnLink.java
Labels: CLA Signed

#15631 Continue iterating if the ejbDescripter fetches the wrong bean
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIEJBManagedObjectFactoryImpl.java
Labels: CLA Signed

#15988 Ensure container can run startup script
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ContainersTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/DockerfileTest.java
  dev/build.example.testcontainers_fat/publish/files/postgres/Dockerfile
  dev/build.example.testcontainers_fat/publish/files/postgres/release.sh
  dev/build.example.testcontainers_fat/publish/files/postgres/scripts/initDB.sql
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15984 Consume SmallRye Config 2.1.0 and tidy FATs
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20ExceptionTests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20PropertyExpressionExceptionTests1.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20PropertyExpressionExceptionTests2.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenInjection/BadConfigPropertyInConstructorBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenInjection/BadConfigPropertyInMethodBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenInjection/ConfigUnnamedConstructorInjectionBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenInjection/MissingPropertyExpressionBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20ExceptionServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20ExceptionServer/server.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20NoCDIServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20PropertyExpressionExceptionServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20PropertyExpressionExceptionServer/server.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20Server/bootstrap.properties
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#15161 Remove references to sonatype OSS snapshots repo
  dev/cnf/resources/bnd/repos.bnd
  dev/settings.gradle
  dev/wlp-gradle/subprojects/maven-central-mirror.gradle
  dev/wlp-gradle/subprojects/repos.gradle
Labels: CLA Signed

#15986 FT test: Wait for security service to start
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat/fat/src/com/ibm/websphere/microprofile/faulttolerance_fat/tests/ejb/AsyncEJBTest.java
Labels: CLA Signed, noproductcode

#15997 Remove some overhead checking if http2 and encoding
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpConstants.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
Labels: CLA Signed, performance, team:Performance

#15999 Add new SIP Container custom properties to the metadata
  dev/com.ibm.ws.sipcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.sipcontainer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#15990 DataStoreHelperMetaData methods for networktimeout readonly schema typemap
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_heritage/publish/servers/com.ibm.ws.jdbc.heritage/server.xml
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelperMetaData.java
Labels: CLA Signed, team:Zombie Apocalypse

#15831 Test change to recursive find in perm mgr code
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed

#16004 281853 - timing issue in jwtsso server startup
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/CommonWaitForAppChecks.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/BuilderTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ConfigAttributeTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieExpirationTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/CookieProcessingTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/SigAlgTests.java
Labels: CLA Signed, team:Security SSO, test bug

#16013 Remove nonexistent src path from .classpath
  dev/com.ibm.ws.jdbc_fat_heritage/.classpath
Labels: CLA Signed, noproductcode, team:Performance

#15995 Backport of increased tolerance level for Timer and Meter tests for MP Metrics
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#16002 Update to Felix SCR 2.1.26
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#15998 MP Config Introspection
  dev/com.ibm.ws.microprofile.config.1.1.services/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1.services/src/com/ibm/ws/microprofile/config11/services/Config11ProviderResolverComponent.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractProviderResolver.java
  dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/ConfigWrapper.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDIConfigServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/CDIConfigServer/server.env
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/converters.war/resources/META-INF/microprofile-config.properties
  dev/com.ibm.ws.microprofile.config.1.2.services/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2.services/src/com/ibm/ws/microprofile/config12/services/Config12ProviderResolverComponent.java
  dev/com.ibm.ws.microprofile.config.1.3.services/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3.services/src/com/ibm/ws/microprofile/config13/services/Config13ProviderResolverComponent.java
  dev/com.ibm.ws.microprofile.config.1.4.services/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4.services/src/com/ibm/ws/microprofile/config14/services/Config14ProviderResolverComponent.java
  dev/io.openliberty.io.smallrye.config/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.config/src/io/openliberty/microprofile/config/internal/extension/ConfigWrapper.java
  dev/io.openliberty.io.smallrye.config/src/io/openliberty/microprofile/config/internal/extension/OLSmallRyeConfigProviderResolver.java
  dev/io.openliberty.microprofile.config.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.config.internal.common/src/io/openliberty/microprofile/config/internal/common/ConfigIntrospectionProvider.java
  dev/io.openliberty.microprofile.config.internal.common/src/io/openliberty/microprofile/config/internal/common/ConfigIntrospector.java
Labels: CLA Signed

#16008 Define exact version of SmallRye Config packages as 2.1.0
  dev/io.openliberty.io.smallrye.config/bnd.bnd
Labels: CLA Signed, in:MicroProfile/Config, team:MicroProfileUK

#16015 Use Equinox org.eclipse.osgi release version 3.15.200
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_ibm.maven
  dev/cnf/oss_source_dependencies.maven
  dev/org.eclipse.osgi/bnd.bnd
Labels: CLA Signed

#15687 GA all MicroProfile 4.0 features and remove beta guards for MP JWT 1.2
  dev/build.image/profiles/javaee8/features.xml
  dev/build.image/profiles/webProfile8/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationConfigSchema-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationValidatorSchema-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsDefaultExceptionMapper-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance3.0-metrics.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpMetrics-3.0-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpOpenTracing2.0-mpRestClient2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.config-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.jwt-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.metrics-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.openapi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.opentracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.0/com.ibm.websphere.appserver.microProfile-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-2.0/com.ibm.websphere.appserver.mpConfig-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-3.0/com.ibm.websphere.appserver.mpFaultTolerance-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-1.2/com.ibm.websphere.appserver.mpJwt-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-3.0/com.ibm.websphere.appserver.mpMetrics-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-2.0/com.ibm.websphere.appserver.mpOpenAPI-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/com.ibm.websphere.appserver.mpOpenTracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/com.ibm.websphere.appserver.mpRestClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-2.0/com.ibm.websphere.appserver.opentracing-2.0.feature
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/JwtConfigUtil.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/config/JwtConfigUtilTest.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder/jvm.options
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/servers/com.ibm.ws.security.jwt_fat.consumer/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat.builder/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat.client/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat.jvmOptions/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.2.fat.builder/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.2.fat.jvmOptions/jvm.options
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.2.fat/jvm.options
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudEnv/jvm.options
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckNoaudNoEnv/jvm.options
Labels: CLA Signed, in:MicroProfile, team:MicroProfileUK, team:Security SSO

#15982 PR for Issue 15755: NLS updates for MP JWT messages
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/MpConfigProperties.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Security SSO

#16003 Issue 15431: Update JWT metatype descriptions to make them clearer
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, team:Security SSO

#15893 SSO JWT support authentication filter.
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenHelper.java
  dev/com.ibm.ws.security.credentials/src/com/ibm/ws/security/jwtsso/token/proxy/JwtSSOTokenProxy.java
  dev/com.ibm.ws.security.jwtsso.token/src/com/ibm/ws/security/jwtsso/token/JwtSSOTokenImpl.java
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/config/JwtSsoBuilderConfig.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/config/JwtSsoConfig.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoBuilderComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/internal/JwtSsoComponent.java
  dev/com.ibm.ws.security.jwtsso/src/com/ibm/ws/security/jwtsso/utils/JwtSsoConstants.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIRequestHelper.java
  dev/com.ibm.ws.security.sso/src/com/ibm/ws/security/sso/SSOAuthFilterImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/util/SSOAuthFilter.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#15992 Add --illegal-access=permit to ANT build process for Java 16
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed, team:Zombie Apocalypse

#16006 datastorehelper isolation level for statement cache and uow detection
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/AccessIntent.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2Helper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DataDirectConnectSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyNetworkClientHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/MicrosoftSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/SybaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSConnectionRequestInfoImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritage/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_heritage/publish/servers/com.ibm.ws.jdbc.heritage/server.xml
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelperMetaData.java
Labels: CLA Signed, team:Zombie Apocalypse

#16023 Update Yoko for improved connection handling
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed, release bug

#16010 update weld4 to final
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, noproductcode

#15907 RTC381749 - use seperate jars for jakarta
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDI12ExtensionSPIConstructorExceptionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDI12ExtensionSPITest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDI12ExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.extension_fat/test-applications/applicationExtension.jar/src/test/PlainExtension.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/RepeatTestFilter.java
Labels: CLA Signed, noproductcode

#16032 legacy DataStoreHelper connection setup
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc_fat_heritage/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16030 Update to released equinox bundles
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.eclipse.equinox.coordinator/bnd.bnd
  dev/com.ibm.ws.org.eclipse.equinox.metatype/bnd.bnd
  dev/com.ibm.ws.org.eclipse.equinox.metatype/bnd.overrides
  dev/com.ibm.ws.org.eclipse.equinox.region/bnd.bnd
Labels: CLA Signed

#16017 Issue #16001: Support jakarta in EJBDDParser
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/InterceptorMetaDataHelper.java
  dev/com.ibm.ws.javaee.dd.ejb/src/com/ibm/ws/javaee/dd/ejb/MessageDriven.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/ejb/EJBJarDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/ejb/EJBJarType.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarTestBase.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/MessageDrivenBeanTest.java
Labels: CLA Signed, in:EJB Container, jakartaEE, team:Blizzard

#16036 Update Docker image to use TLS1.2 for JDBC testDB2SecureConnection
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/custom/db2_tls_setup.sh
Labels: CLA Signed, noproductcode

#16027 Update test to run server features with the word client in them
  dev/build.featureStart_fat/fat/src/com/ibm/ws/simple/FeaturesStartTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appclient.appClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.appclient.appClient-2.0.feature
Labels: CLA Signed, jakartaEE, team:Performance

#16011 Logstash ssl test failure
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
  dev/com.ibm.ws.logstash.collector_fat/publish/files/server_reset.xml
Labels: CLA Signed, noproductcode

#16052 legacy interop with doConnectionSetupPerTransaction
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2Helper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DataDirectConnectSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/MicrosoftSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/SybaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSConnectionRequestInfoImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16040 Issue 16039: Lower JWT cache limit from 50k to 500
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
Labels: CLA Signed, team:Security SSO

#16029 CL22150: Add getLongRunningPolicyExecutor method to WSManagedExecutorService.
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/WSManagedExecutorService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/ext/ManagedExecutorExtension.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextualDefaultExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/UnusableExecutor.java
Labels: CLA Signed, team:Zombie Apocalypse

#14927 Issue 14926: Prevent beanValidation-1.1 from attempting to cache a CDI bean manager when the CMD isn't available.
  dev/com.ibm.ws.beanvalidation.v11.cdi/src/com/ibm/ws/beanvalidation/v11/cdi/internal/ValidationReleasableFactoryImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#16049 JWT isLoggedOut - Change synch to be more efficient
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/TAIJwtUtils.java
Labels: CLA Signed, performance, team:Performance

#16055 Update cloudant FAT to use TLS1.2 for Java 16
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/FATSuite.java
  dev/com.ibm.ws.cloudant_fat/publish/files/couchdb-ssl/Dockerfile
  dev/com.ibm.ws.cloudant_fat/publish/files/couchdb-ssl/couchdb-config/testcontainers_config.ini
  dev/com.ibm.ws.cloudant_fat/publish/servers/com.ibm.ws.cloudant.fat.outboundSSL/jvm.options
  dev/com.ibm.ws.cloudant_fat/publish/servers/com.ibm.ws.cloudant.fat/jvm.options
Labels: CLA Signed, noproductcode

#16056 Fix thread wait
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
Labels: CLA Signed

#16066 NullPointerException on parked managed connection
  dev/com.ibm.ws.jca.1.7_fat/test-resourceadapters/helloworldra/src/com/ibm/helloworldra/HelloWorldManagedConnectionImpl.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15846 Debug wab install
  dev/com.ibm.ws.app.manager.wab.installer_fat/publish/servers/com.ibm.ws.app.manager.wab.installer/bootstrap.properties
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
Labels: CLA Signed
