Repository OpenLiberty/open-liberty, pull requests merged in 2021-11, with the labels that each got.

#19194 mpOpenApi-2.0 merge improvements
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/merge/MergeProcessor.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/AssertModel.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/MergeProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/ComponentsMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/ExtensionsMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/OpenAPIProviderCustom.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/OperationIDMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/PathsMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/SecurityMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/ServersMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/TagsMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/TestUtil.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/package-info.java
Labels: CLA Signed

#19203 Remove unneeded restfulWSCleint feature from microProfile-5.0 feature file
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-5.0/io.openliberty.microProfile-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.0/io.openliberty.restfulWS-3.0.feature
Labels: in:JAX-RS, CLA Signed

#19171 eclipse cleanup for MDB JMS FAT
  dev/com.ibm.ws.ejbcontainer.mdb.jms_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.mdb.jms_fat/bnd.bnd
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#19149 javamail.1.6_fat imported
  dev/com.ibm.ws.javamail.1.6_fat/.classpath
  dev/com.ibm.ws.javamail.1.6_fat/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/fat/src/com/ibm/ws/javamail/fat/AppClientTest.java
  dev/com.ibm.ws.javamail.1.6_fat/fat/src/com/ibm/ws/javamail/fat/FATSuite.java
  dev/com.ibm.ws.javamail.1.6_fat/publish/clients/javamail.client_fat/.gitignore
  dev/com.ibm.ws.javamail.1.6_fat/publish/clients/javamail.client_fat/bootstrap.properties
  dev/com.ibm.ws.javamail.1.6_fat/publish/clients/javamail.client_fat/client.xml
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/package.properties
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/resources/META-INF/application-client.xml
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/src/com/ibm/ws/javamail/client/Main.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientApp/src/com/ibm/ws/javamail/client/SendReceiveMailFromClientTest.java
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientEAR/package.properties
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientEAR/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientEAR/resources/META-INF/application.xml
  dev/com.ibm.ws.javamail.1.6_fat/test-applications/JavaMailClientEAR/resources/META-INF/permissions.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#19196 Ensure restfulWSClient-3.0 works with XML resources with xmlBinding-3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-xmlBinding3.0.feature
  dev/com.ibm.ws.jaxrs.2.0.client_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.client_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxrs.2.0.client_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/XmlBindingTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/xmlbinding/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/xmlbinding/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/xmlbinding/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/xmlbinding/src/xmlbinding/ReturnXmlFilter.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/xmlbinding/src/xmlbinding/Widget.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/xmlbinding/src/xmlbinding/XmlBindingTestServlet.java
Labels: in:JAX-RS, CLA Signed, team:Wendigo West

#19175 third party context providers
  dev/com.ibm.ws.concurrent_fat_jakarta/.classpath
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/build.gradle
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestApp/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/LocationUtils/src/test/context/location/ZipCode.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/LocationUtils/src/test/context/location/ZipCodeContextProvider.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/LocationUtils/src/test/context/location/ZipCodeContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/LocationUtils/src/test/context/location/ZipCodeContextSnapshot.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/PriorityContext/src/test/context/priority/PriorityContextProvider.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/PriorityContext/src/test/context/priority/PriorityContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/PriorityContext/src/test/context/priority/PriorityContextSnapshot.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/list/ListContext.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/list/ListContextProvider.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/list/ListContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/list/ListContextSnapshot.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/timing/Timestamp.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/timing/TimestampContextProvider.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/timing/TimestampContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-libraries/StatUtils/src/test/context/timing/TimestampContextSnapshot.java
  dev/io.openliberty.concurrent/bnd.bnd
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/context/ThirdPartyContext.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/context/ThirdPartyContextCoordinator.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/context/package-info.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#19169 update comment dates
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionEventListener.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
Labels: CLA Signed

#19191 Bring in eclipselink performance fix removing getStackTrace calls
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/src/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
Labels: CLA Signed, team:Performance, performance

#19205 Issue #19204: Update copyright date range formatting
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestInjection.war/src/com/ibm/ws/jsp23/fat/testinjection/tagHandler/JspCdiHitMeTag.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19209 configurable transaction context on ContextServiceDefinition
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ApplicationScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/RequestScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/SingletonScopedBean.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextManager.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextProviderImpl.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ContextServiceResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#19045 Transform destinationType in activation specs
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20security/fat/JMSConsumerTest/JMSConsumerTest.java
  dev/com.ibm.ws.messaging.open_jms20security_fat/test-applications/JMSConsumer/src/web/JMSConsumerServlet.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/WasJmsProperties.java
Labels: noproductcode, CLA Signed

#18894 Add code to retry SQL operations on tx recovery logs
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitSectionImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLog.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/publish/servers/com.ibm.ws.transaction_multipleretries/bootstrap.properties
  dev/com.ibm.ws.transaction.DerbyHADB_fat/publish/servers/com.ibm.ws.transaction_multipleretries/server.xml
  dev/com.ibm.ws.transaction.DerbyHADB_fat/publish/servers/com.ibm.ws.transaction_recover/bootstrap.properties
  dev/com.ibm.ws.transaction.DerbyHADB_fat/publish/servers/com.ibm.ws.transaction_recover/server.xml
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnection.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSource.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSourceBeanInfo.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction.DerbyHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: in:Transactions, CLA Signed

#19202 fix ClassCastException in JSP
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJDT.war/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJDT.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJDT.war/resources/index.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/compiler/JDTCompiler.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#19221 Fixes for Eclipse github actions and gradle builds
  .github/test-categories/QUARANTINE
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.spnego/.project
  dev/io.openliberty.concurrent/.classpath
Labels: CLA Signed, team:Performance

#19222 Update Liberty app classloader shared classes cache logic
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
Labels: CLA Signed, team:Performance, performance

#18284 14901-Allow-variable-resolution-in-server-env
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#19228 update to 20211103 snapshot build
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
  dev/io.openliberty.jakarta.concurrency.3.0/bnd.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#19218 mpOpenApi-2.0 merging fixes
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/MergedOpenAPIProvider.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/merge/MergeProcessor.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/MessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/MergeProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/clashing-extension-1.yaml
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/clashing-extension-2.yaml
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/test/merge/parts/ExtensionsMergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTestResourceTest1.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPITestUtil.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: ID reviewed, CLA Signed

#19229 Update OpenTracing to RC4
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/opentracing.3.0.bnd
Labels: CLA Signed

#19232 No long need to check the provider
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/JSSEProviderFactory.java
Labels: CLA Signed

#19235 Update postgreSQL table query
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
Labels: CLA Signed

#19131 Remove attribute useJandex from the springBootApplication configuration
  dev/com.ibm.ws.app.manager.springboot/resources/OSGI-INF/metatype/metatype.xml
Labels: team:OSGi Infrastructure, CLA Signed, in:SpringBoot

#19216 Transformed third party and stable API bundle updates and other updates
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.api.ejbcontainer/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
  dev/com.ibm.websphere.javaee.jsp.tld.2.2/bnd.bnd
  dev/com.ibm.websphere.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.cdi.spi/bnd.bnd
  dev/io.openliberty.ejbcontainer/bnd.bnd
  dev/io.openliberty.federatedRepository.spi/bnd.bnd
  dev/io.openliberty.globalhandler.spi/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.classpath
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.project
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.grpc.1.0.jakarta/.classpath
  dev/io.openliberty.io.grpc.1.0.jakarta/.project
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/bndtools.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/bnd.bnd
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
  dev/io.openliberty.jacc/bnd.bnd
  dev/io.openliberty.jakarta.pages.tld.3.0/.classpath
  dev/io.openliberty.jakarta.pages.tld.3.0/.gitignore
  dev/io.openliberty.jakarta.pages.tld.3.0/.project
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/bnd.bnd
  dev/io.openliberty.jaspic.spi/bnd.bnd
  dev/io.openliberty.jaxrs30/bnd.bnd
  dev/io.openliberty.jwt/bnd.bnd
  dev/io.openliberty.oauth/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/.classpath
  dev/io.openliberty.org.osgi.service.http/.gitignore
  dev/io.openliberty.org.osgi.service.http/.project
  dev/io.openliberty.org.osgi.service.http/.settings/bndtools.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/bnd.overrides
  dev/io.openliberty.security/bnd.bnd
  dev/io.openliberty.securityClient/bnd.bnd
  dev/io.openliberty.servlet.spi/bnd.bnd
  dev/io.openliberty.servlet/bnd.bnd
  dev/io.openliberty.transaction/bnd.bnd
  dev/io.openliberty.webCache/bnd.bnd
  dev/io.openliberty.webcontainer.security.app/bnd.bnd
  dev/io.openliberty.wsat.spi/bnd.bnd
  dev/io.openliberty.wsoc/bnd.bnd
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, team:Performance, jakartaEE9

#19248 Enable property for DB2 row size limit
  dev/com.ibm.ws.session.db/src/com/ibm/ws/session/store/db/DatabaseHashMap.java
Labels: CLA Signed

#19240 add tests of application.xml resource definitions, initially disabled
  dev/com.ibm.ws.concurrent_fat_jakarta/.classpath
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/Factorial.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19257 Revert "Transformed third party and stable API bundle updates and other updates"
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.api.ejbcontainer/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
  dev/com.ibm.websphere.javaee.jsp.tld.2.2/bnd.bnd
  dev/com.ibm.websphere.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.cdi.spi/bnd.bnd
  dev/io.openliberty.ejbcontainer/bnd.bnd
  dev/io.openliberty.federatedRepository.spi/bnd.bnd
  dev/io.openliberty.globalhandler.spi/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.classpath
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.project
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.grpc.1.0.jakarta/.classpath
  dev/io.openliberty.io.grpc.1.0.jakarta/.project
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/bndtools.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/bnd.bnd
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
  dev/io.openliberty.jacc/bnd.bnd
  dev/io.openliberty.jakarta.pages.tld.3.0/.classpath
  dev/io.openliberty.jakarta.pages.tld.3.0/.gitignore
  dev/io.openliberty.jakarta.pages.tld.3.0/.project
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/bnd.bnd
  dev/io.openliberty.jaspic.spi/bnd.bnd
  dev/io.openliberty.jaxrs30/bnd.bnd
  dev/io.openliberty.jwt/bnd.bnd
  dev/io.openliberty.oauth/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/.classpath
  dev/io.openliberty.org.osgi.service.http/.gitignore
  dev/io.openliberty.org.osgi.service.http/.project
  dev/io.openliberty.org.osgi.service.http/.settings/bndtools.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/bnd.overrides
  dev/io.openliberty.security/bnd.bnd
  dev/io.openliberty.securityClient/bnd.bnd
  dev/io.openliberty.servlet.spi/bnd.bnd
  dev/io.openliberty.servlet/bnd.bnd
  dev/io.openliberty.transaction/bnd.bnd
  dev/io.openliberty.webCache/bnd.bnd
  dev/io.openliberty.webcontainer.security.app/bnd.bnd
  dev/io.openliberty.wsat.spi/bnd.bnd
  dev/io.openliberty.wsoc/bnd.bnd
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed

#19230 remove extranous swidtag
  dev/build.image/build.gradle
  dev/build.image/publish/openliberty.io_OpenLiberty.swidtag
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/CheckTags.java
Labels: CLA Signed

#19259 Transformed third party and stable API bundle updates and other updates (try 2)
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.api.ejbcontainer/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlws.common-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
  dev/com.ibm.websphere.javaee.jsp.tld.2.2/bnd.bnd
  dev/com.ibm.websphere.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.cdi.spi/bnd.bnd
  dev/io.openliberty.ejbcontainer/bnd.bnd
  dev/io.openliberty.federatedRepository.spi/bnd.bnd
  dev/io.openliberty.globalhandler.spi/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.classpath
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.project
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.grpc.1.0.jakarta/.classpath
  dev/io.openliberty.io.grpc.1.0.jakarta/.project
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/bndtools.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.grpc.1.0.jakarta/bnd.bnd
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
  dev/io.openliberty.jacc/bnd.bnd
  dev/io.openliberty.jakarta.pages.tld.3.0/.classpath
  dev/io.openliberty.jakarta.pages.tld.3.0/.gitignore
  dev/io.openliberty.jakarta.pages.tld.3.0/.project
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.pages.tld.3.0/bnd.bnd
  dev/io.openliberty.jaspic.spi/bnd.bnd
  dev/io.openliberty.jaxrs30/bnd.bnd
  dev/io.openliberty.jwt/bnd.bnd
  dev/io.openliberty.oauth/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/.classpath
  dev/io.openliberty.org.osgi.service.http/.gitignore
  dev/io.openliberty.org.osgi.service.http/.project
  dev/io.openliberty.org.osgi.service.http/.settings/bndtools.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.osgi.service.http/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.osgi.service.http/bnd.bnd
  dev/io.openliberty.org.osgi.service.http/bnd.overrides
  dev/io.openliberty.security/bnd.bnd
  dev/io.openliberty.securityClient/bnd.bnd
  dev/io.openliberty.servlet.spi/bnd.bnd
  dev/io.openliberty.servlet/bnd.bnd
  dev/io.openliberty.transaction/bnd.bnd
  dev/io.openliberty.webCache/bnd.bnd
  dev/io.openliberty.webcontainer.security.app/bnd.bnd
  dev/io.openliberty.wsat.spi/bnd.bnd
  dev/io.openliberty.wsoc/bnd.bnd
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, team:Performance

#18676 Issue #18381: Remove ibm:beta=true for configurable http header metatype
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
Labels: in:Transport, CLA Signed, team:Sirius

#19254 J2CA0027E missed for Failover1ServerCoordinatedPollingTest
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerCoordinatedPollingTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19252 testIdentityNamePrecedence unreliable use of isDone
  dev/com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#19249 Very explicit debug statements for RingBufferTest
  dev/com.ibm.ws.collector.manager/test/com/ibm/ws/collector/manager/buffer/RingBufferTest.java
Labels: noproductcode, CLA Signed

#19255 Add missing nls properties files to build.pii.package
  dev/com.ibm.websphere.appserver.api.oauth/bnd.bnd
  dev/com.ibm.websphere.javaee.el.3.0/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.2/build.gradle
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_cs.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_de.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_es.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_fr.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_hu.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_it.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_ja.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_ko.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_pl.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_pt_BR.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_ro.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_ru.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_zh.properties
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs_zh_TW.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_cs.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_de.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_es.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_fr.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_hu.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_it.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ja.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ko.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_pl.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_pt_BR.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ro.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ru.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_zh.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_zh_TW.properties
  dev/io.openliberty.oauth/bnd.bnd
Labels: CLA Signed, team:Performance

#19261 Increase the timeout duration for jdbc FAT testConfigChangeDataSource
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#19236 Move MP 5.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpOpenTracing3.0-mpRestClient3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.opentracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-5.0/io.openliberty.microProfile-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/io.openliberty.mpOpenTracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-3.0/io.openliberty.opentracing-3.0.feature
Labels: CLA Signed

#18816 Update OidcClientConfigImpl to make SSLSupport service mandatory
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryErrorTests.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
Labels: CLA Signed, team:Security SSO

#19243 Remove the temp file. The file has been replaced by jakarta-text.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed

#19244 Update MP OpenAPI 3.0 API and TCK to RC5
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.openapi.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/openapi.3.0.bnd
Labels: CLA Signed

#19270 Allow for OpenTracing warning
  dev/io.openliberty.microprofile5.internal_fat/fat/src/io/openliberty/microprofile5/internal/test/suite/MP5CompatibleTest.java
Labels: noproductcode, CLA Signed

#19272 Merge opentracing-3.0 into mpOpenTracing-3.0
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/io.openliberty.mpOpenTracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-3.0/io.openliberty.opentracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-3.0/resources/l10n/io.openliberty.opentracing-3.0.properties
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/files/features/io.openliberty.opentracing.mock-3.0.mf
Labels: CLA Signed

#19280 Check default config settings to drive reprocessing config
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/ConfigVariable.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.java
Labels: CLA Signed

#19279 Fix jwtSso-1.0 EE9 enablement in the OIDC server fat
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/oidc_featuresWithJwtSso.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#19298 update xdump statement
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/bootstrap.properties
Labels: noproductcode, CLA Signed

#19301 Move restfulWSLogging-3.0 feature back to beta
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSLogging-3.0/io.openliberty.restfulWSLogging-3.0.feature
Labels: CLA Signed

#19283 Update security repeat rules
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestFeatureEE9RepeatAction.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestFeatureRepeatAction.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestRepeatAction.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwkEndpointValidationUrlTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigAltKeyStoreTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigNoIdTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumRunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigBuilderTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigGlobalTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIWithLDAPConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiWithLDAPBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumHSARunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLConsumerConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLGlobalConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigBlankIdTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigWithGlobalTrustTests.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/IBM/OidcJaxRSClientAPITests.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/OidcClientJaxrsRepeatAction.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/oidc/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/IDPInitiated/UserFeatureOnlyIDPInitiatedTests.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/EncryptionUnsolicitedSPInitiatedTests.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/UserFeatureOnlySolicitedSPInitiatedTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/PkixUnsolicitedSPInitiatedTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/TimeUnsolicitedSPInitiatedTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/TrustedIssuerUnsolicitedSPInitiatedTests.java
Labels: test bug, CLA Signed, team:Security SSO

#19295 Revise string checking in testAbsenceOfDuplicatesInRecoveryLogs
  dev/com.ibm.ws.transaction.DerbyHADB_fat/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
Labels: noproductcode, CLA Signed

#19304 Remove dependency on kernel classes for doPriv
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java
Labels: CLA Signed, team:Wendigo West, in:MicroProfile/RestClient

#19300 Do Priv call to retrieve MBeanServer in monitor bundle
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/MeterCollection.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/monitor/internal/MonitoringFrameworkExtender.java
  dev/com.ibm.ws.monitor/src/com/ibm/ws/pmi/server/PmiRegistry.java
Labels: CLA Signed

#19282 Fix Async Servlet Error Handling When Using AppSecurity Features
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/collaborator/CollaboratorHelper.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#19308 Increase maximum unlocked listeners
  dev/com.ibm.ws.messaging.common/.classpath
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/items/MessageEventListeners.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/items/MessageItem.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/items/MessageItemReference.java
Labels: CLA Signed

#19330 Migrate JPA Container:Hibernate FAT to Open Liberty
  .github/test-categories/JPA_1
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.classpath
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.project
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/fat/src/com/ibm/ws/jpa/tests/container_hibernate/FATSuite.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/fat/src/com/ibm/ws/jpa/tests/container_hibernate/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/fat/src/com/ibm/ws/jpa/tests/container_hibernate/TestHibernate.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/publish/servers/com.ibm.ws.jpa.container.fat.hibernate/.gitignore
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/publish/servers/com.ibm.ws.jpa.container.fat.hibernate/bootstrap.properties
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/publish/servers/com.ibm.ws.jpa.container.fat.hibernate/server.xml
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/test-applications/hibertest/hibertest.ear/META-INF/application.xml
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/test-applications/hibertest/hibertest.ear/META-INF/permissions.xml
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/test-applications/hibertest/hibertest.ear/hibertest.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/test-applications/hibertest/src/com/ibm/ws/jpa/tests/container/hibernate/entity/AvgSnowfall.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/test-applications/hibertest/src/com/ibm/ws/jpa/tests/container/hibernate/web/HibernateJPATestServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#19337 OLGH18653: Update Eclipselink 2.7 (JPA 2.2) and 3.0 (JPA 3.0) to use …
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed

#19350 criu Add skip annotation
  dev/fattest.simplicity/src/componenttest/annotation/SkipIfCheckpointNotSupported.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/CheckpointSupportFilter.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/TestWithFATServlet.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/TestWithFATServlet2.java
Labels: CRIU

#19347 Repeat com.ibm.ws.microprofile.openapi_fat
  dev/com.ibm.ws.microprofile.openapi_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.microprofile.openapi_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.microprofile.openapi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi_fat/build.gradle
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/EndpointAvailabilityTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ProxySupportTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/UICustomizationTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/annotations/AnnotationProcessingTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/annotations/NonPublicFieldVisibilityApplication.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/annotations/PrivateFieldVisibilityApplication.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/filter/FilterConfigTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/filter/MyTestFilter.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPIConnection.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPITestUtil.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFive.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFour.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestSix.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestTwo.java
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/AnnotationProcessingServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/JAXRSApp.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/data/UserData.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/Airline.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/Booking.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/CreditCard.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/Flight.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/Review.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/model/User.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/resources/AirlinesResource.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/resources/AvailabilityResource.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/resources/ReviewResource.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/resources/UserResource.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/appWithAnnotations/src/app/web/airlines/resources/bookings/BookingResource.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/complete-flow/src/app/web/complete/flow/app/JAXRSApp.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/complete-flow/src/app/web/complete/flow/filter/OASFilterImpl.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/complete-flow/src/app/web/complete/flow/model/reader/ModelReaderImpl.java
  dev/com.ibm.ws.microprofile.openapi_fat/test-applications/simpleServlet/src/app/web/servlet/SimpleServlet.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#19034 Remove feature version from FeatureInfo output
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/FeatureInfoCommandTask.java
Labels: CLA Signed

#19365 Repeat io.openliberty.microprofile.openapi.2.0.internal_fat
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/build.gradle
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/ApplicationProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTestResource.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/TestServlet.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/test1/DeploymentTestApp.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPIConnection.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPITestUtil.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/test-applications/complete-flow/src/app/web/complete/flow/app/JAXRSApp.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/test-applications/complete-flow/src/app/web/complete/flow/filter/OASFilterImpl.java
Labels: noproductcode, CLA Signed

#19370 Avoid usage of thread context loader to load LibertySSLSocketFactory
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/security/SSLSocketFactoryProxy.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed

#19042 Add whiteboard for ClassFileTransformer services
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoaderFactory.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ParentLastClassLoader.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/LibertyClassLoaderTest.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/ProtectionDomainTest.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/TestUtil.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/TransformerTest.java
Labels: CLA Signed

#19238 Serviceability: Print Http header contents
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/PasswordNullifier.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ServletRequestInfoDebug.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
Labels: CLA Signed

#19200 Expose the ability to configure ignoreAffinityRequests in metatype
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype-mbeans.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/osgi/mbeans/PluginGeneratorTest.java
Labels: ID reviewed, CLA Signed

#19356 287840 remove policy file dir
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/files/envVars/jvm.options
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/files/envVars/jvm.options
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/publish/files/envVars/jvm.options
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/publish/files/envVars/jvm.options
Labels: noproductcode, test bug, team:Security SSO

#19266 Run existing MP Rest Client FATs on 3.0 (RESTEasy) implementation
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/build.gradle
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiInEE8Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicEJBTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CdiPropsAndProvidersTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagation12Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagationTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HostnameVerifierTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/MultiClientCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/PropsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/SseTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.collections/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.remoteServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient20.sse/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/asyncApp/src/mpRestClient11/async/AccountsPayableService.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/asyncApp/src/mpRestClient11/async/DoubleReader.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicCdiClientApp/src/mpRestClient10/basicCdi/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicClientApp/src/mpRestClient10/basic/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicEJBClientApp/src/mpRestClient10/basicEJB/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicRemoteApp/src/remoteApp/basic/BasicService.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/ClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/headerPropagation12App/src/mpRestClient12/headerPropagation/HeaderPropagationTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/headerPropagationApp/src/mpRestClient10/headerPropagation/HeaderPropagationFilter.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/headerPropagationApp/src/mpRestClient10/headerPropagation/Resource.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/produceConsumeApp/src/mpRestClient11/produceConsume/MyClient.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/produceConsumeApp/src/mpRestClient11/produceConsume/ProduceConsumeTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/produceConsumeApp/src/mpRestClient11/produceConsume/Widget.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/propsApp/src/mpRestClient10/props/PropsTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/GenericSubscriber.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseClientTestServlet.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/RestClientListeners.java
  dev/io.openliberty.restfulWS.internal.ssl/bnd.bnd
  dev/io.openliberty.restfulWS.internal.ssl/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientListener
  dev/io.openliberty.restfulWS.internal.ssl/src/io/openliberty/restfulWS/internal/ssl/component/SslClientBuilderListener.java
  dev/io.openliberty.restfulWS.internal.ssl/src/io/openliberty/restfulWS/internal/ssl/component/SslMpClientBuilderListener.java
Labels: CLA Signed, team:Wendigo West, in:MicroProfile/RestClient

#19312 Allow utility scripts to expand variables in server.env
  dev/cnf/resources/bin/tool
Labels: CLA Signed

#19352 Extra debug for RingBufferTest
  dev/com.ibm.ws.collector.manager/test/com/ibm/ws/collector/manager/buffer/RingBufferTest.java
Labels: noproductcode

#19379 Issue 19378 : Update PackageRunnableTest to use stop command vs proce…
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: noproductcode, CLA Signed

#19281 Increase timeout for testConfigChangeWithActiveConnections
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#19369 Fix issue with null bundle name and description for transformed bundles
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: noproductcode, CLA Signed, team:Performance

#19381 update JAXRSClient100ContinueTest to use BouncyCastle with Mockserver
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClient100ContinueTest.java
Labels: noproductcode, CLA Signed

#19359 Change to ConcurrentHashMap
  dev/com.ibm.ws.jaxrs.2.0.cdi/src/com/ibm/ws/jaxrs20/cdi/component/JaxRsFactoryImplicitBeanCDICustomizer.java
Labels: performance

#19030 Update Yoko version with improved doPriv usage
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#19362 Cleanup multiple things
  .github/test-categories/MP_METRICS_2
  .github/test-categories/OPENTRACING
  .github/test-categories/SECURITY_SOCIAL_1
  dev/com.ibm.websphere.appserver.features/visibility/public/openapi-3.1/com.ibm.websphere.appserver.openapi-3.1.feature
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/audit/EJBJarX03JACCAuditTest.java
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/audit/PureAnnA08JAASLoginFromEJBJACCAuditTest.java
  dev/com.ibm.ws.install.featureUtility.featureutil/bnd.bnd
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLProxyAuthTest.java
  dev/com.ibm.ws.jaxws.webcontainer/bnd.bnd
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/TranTimeoutTest.java
  dev/com.ibm.ws.repository/bnd.bnd
  dev/com.ibm.ws.security.fat.common.mp.jwt/fat/src/com/ibm/ws/security/fat/common/mp/jwt/sharedTests/MPJwt12MPConfigTests.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIBasicAuthJACCAuthorizationTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPICallbackBasicAuthTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPICallbackFormLoginTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIDynamicFeatureTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIFormLoginJACCAuthorizationTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIFormLoginTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIRegisterSessionTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIRequestDispatcherTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIRuntimeRegistrationTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIServerPersistenceTest.java
  dev/com.ibm.ws.security.jaspic_fat/fat/src/com/ibm/ws/security/jaspic11/fat/JASPIWrappingTest.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/MPJwt12ConfigUsingBuilderTests.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/configInAppTests/MPJwt12MPConfigInApp_Tests.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/featureSupportTests/feature1_1/Feature11Enabled_ConfigInServerXmlTests.java
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20CustomStoreClient01Hash.java
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20DerbyClient01Hash.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/SameSiteTests.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/CommonTests/genericWebClientAuthCodeCommonTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/CommonTests/genericWebClientAuthCodeTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OAuth/OAuthInvokeNonexistentPathTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OAuth/OAuthWebClientAuthCodeCustomStoreBellTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OAuth/OAuthWebClientAuthCodeCustomStoreHashTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OAuth/OAuthWebClientAuthCodeDerbyHashTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OAuth/OAuthWebClientAuthCodeTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCInvokeNonexistentPathTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCWebClientAuthCodeCustomStoreBellTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCWebClientAuthCodeCustomStoreHashTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCWebClientAuthCodeDerbyHashTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCWebClientAuthCodeTest.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/common/BasicSAMLTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicTests.java
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/S4U2ProxyTest.java
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/S4U2SelfTest.java
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/audit/BasicAuthAuditAUTHZTest.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/opentracing/internal/jaeger_fat/JaegerConfigTest.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/opentracing/internal/jaeger_fat/JaegerTraceTest.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal.rest.client/bnd.bnd
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATMPOpenTracing.java
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATOpentracing.java
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATOpentracingHelloWorld.java
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATTestBase.java
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/MicroProfile40NoTracer.java
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/TestSpanUtils.java
  dev/io.openliberty.org.apache.taglibs.standard/.classpath
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
Labels: team:Performance

#19321 mpOpenApi-2.0: remove multi-module beta guard
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/MergeDisabledAlerter.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/ModuleSelectionConfig.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeTestServer/jvm.options
Labels: CLA Signed

#19388 Refine the MP Config Stress Test
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/stress.war/src/com/ibm/ws/microprofile/appConfig/stress/test/StressTestServlet.java
Labels: noproductcode, CLA Signed

#19305 add code to wait for keystore readiness
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/servers/ServerInstanceUtils.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
Labels: test bug, CLA Signed, team:Security SSO

#19340 Allow for late arriving FFDCs
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests_NoServerSSL.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#19335 Close inputStream
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCachingIntrospectorOutput.java
Labels: noproductcode, CLA Signed

#19245 Remove beta flag for OIDC client access token cache attributes
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#18654 Upgrade ASM to 9.2
  .gitignore
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoStoreImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/InfoStoreImpl.java
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: team:Zombie Apocalypse, CLA Signed

#19387 mpOpenApi-2.0: avoid processing apps on shutdown
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/ApplicationRegistry.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/shutdown/ShutdownTest.java
Labels: CLA Signed

#19296 Adding OpenTracing-3.0 fat bucket for JakartaEE 9
  dev/io.openliberty.opentracing.3.x_fat/.classpath
  dev/io.openliberty.opentracing.3.x_fat/.project
  dev/io.openliberty.opentracing.3.x_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.opentracing.3.x_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.opentracing.3.x_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.opentracing.3.x_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.opentracing.3.x_fat/bnd.bnd
  dev/io.openliberty.opentracing.3.x_fat/build.gradle
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATLogging.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATMPOpenTracing.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATNotes.txt
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATOpentracing.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATOpentracingConstants.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATOpentracingHelloWorld.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATSuite.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATTestBase.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATUtilsServer.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATUtilsSpans.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/MicroProfile50NoTracer.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/SubStringReader.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/TestAppException.java
  dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/TestSpanUtils.java
  dev/io.openliberty.opentracing.3.x_fat/opentracing.mock30.bnd
  dev/io.openliberty.opentracing.3.x_fat/opentracing_fat.bnd
  dev/io.openliberty.opentracing.3.x_fat/publish/files/features/io.openliberty.opentracing.mock-3.0.mf
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer1/.gitignore
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer1/bootstrap.properties
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer1/server.xml
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer2/.gitignore
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer2/bootstrap.properties
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer2/server.xml
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer3/.gitignore
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer3/bootstrap.properties
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer3/server.xml
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer4/.gitignore
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer4/bootstrap.properties
  dev/io.openliberty.opentracing.3.x_fat/publish/servers/opentracingFATServer4/server.xml
  dev/io.openliberty.opentracing.3.x_fat/test-applications/jaxrsHelloWorld/resources/beans.xml
  dev/io.openliberty.opentracing.3.x_fat/test-applications/jaxrsHelloWorld/src/io/openliberty/opentracing/internal/test/helloworld/HelloWorldJAXRS.java
  dev/io.openliberty.opentracing.3.x_fat/test-applications/mpOpenTracing/resources/beans.xml
  dev/io.openliberty.opentracing.3.x_fat/test-applications/mpOpenTracing/src/io/openliberty/opentracing/internal/test/mpot/MPOpenTracing.java
  dev/io.openliberty.opentracing.3.x_fat/test-applications/mpOpenTracing/src/io/openliberty/opentracing/internal/test/mpot/POJO.java
  dev/io.openliberty.opentracing.3.x_fat/test-applications/serviceApp/resources/beans.xml
  dev/io.openliberty.opentracing.3.x_fat/test-applications/serviceApp/src/io/openliberty/opentracing/internal/test/service/FATOpentracingConstants.java
  dev/io.openliberty.opentracing.3.x_fat/test-applications/serviceApp/src/io/openliberty/opentracing/internal/test/service/FATOpentracingService.java
  dev/io.openliberty.opentracing.3.x_fat/test-applications/serviceApp/src/io/openliberty/opentracing/internal/test/service/FATUtilsService.java
  dev/io.openliberty.opentracing.3.x_fat/test-bundles/opentracing.mock/src/io/openliberty/opentracing/internal/mock/OpentracingMockTracer.java
  dev/io.openliberty.opentracing.3.x_fat/test-bundles/opentracing.mock/src/io/openliberty/opentracing/internal/mock/OpentracingMockTracerFactory.java
  dev/io.openliberty.opentracing.3.x_fat/test-bundles/opentracing.mock/src/io/openliberty/opentracing/internal/mock/package-info.java
  dev/io.openliberty.opentracing.3.x_fat/test-bundles/opentracing.mock/src/io/openliberty/opentracing/spi/tracer/OpentracingTracerFactory.java
  dev/io.openliberty.opentracing.3.x_fat/test-bundles/opentracing.mock/src/io/openliberty/opentracing/spi/tracer/package-info.java
Labels: noproductcode, CLA Signed

#19412 demo timers test gets CWWKZ0002E due to transaction timeout on slow infrastructure
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/publish/servers/com.ibm.ws.concurrent.persistent.fat.demo.timers/server.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19409 NullPointerException when max or priority are unspecified
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: bug, team:Zombie Apocalypse, CLA Signed

#19425 Update xdump statement
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/bootstrap.properties
Labels: noproductcode, CLA Signed

#19427 Revert "Update Yoko version with improved doPriv usage"
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#19377 EJB MDB RA FAT add countdownlatches for timer tests
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/MDBTimedBMTBean.java
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/MDBTimedCMTBean.java
Labels: noproductcode, CLA Signed

#19168 Support URLEncoded client cert
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTestEncodedX590.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/jvm.options
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestX590EncodedCert.war/src/encodedcert/servlet/TestOpenCertificate.java
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius

#18931 JVM Working Directory Feature
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: CLA Signed

#19431 Update Yoko binaries
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#19429 Update to xercesImpl 2.12.1
  dev/ant_build.js/build.gradle
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.noMpJwt/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
Labels: CLA Signed

#19435 #19433 Treat AdapterAlreadyExists as unexceptional
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/NamingServiceAdapterActivator.java
Labels: CLA Signed

#19391 Use modern start util
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
Labels: CLA Signed

#19170 Avoid inferring caller for SystemOut/Err events in hpel
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.java
Labels: CLA Signed

#19445 Tolerate EOFException in recovery tests
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest1.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest2.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest3.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest4.java
Labels: noproductcode, CLA Signed

#19441 put grpc_fat protobuf compilation behind prop
  dev/com.ibm.ws.grpc_fat/README.md
  dev/com.ibm.ws.grpc_fat/build.gradle
Labels: noproductcode, CLA Signed

#19467 Revert "Update to xercesImpl 2.12.1"
  dev/ant_build.js/build.gradle
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.noMpJwt/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
Labels: CLA Signed

#19338 Fix policy attachments issue 19334
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/bus/LibertyApplicationBusFactory.java
Labels: CLA Signed

#19464 JAX-WS, JAX-B, JavaMail: Limit tracing in FAT buckets
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/com.ibm.ws.javamail.fat/bootstrap.properties
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/com.ibm.ws.javamail.management.j2ee.fat/bootstrap.properties
  dev/com.ibm.ws.javamail.1.6_fat/publish/servers/mailSessionTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/com.ibm.ws.jaxb.tools.TestServer/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat.no-jaxb-feature/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_internal_optional_feature_toleration_fat/bootstrap.properties
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_optional_feature_toleration_fat/bootstrap.properties
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/com.ibm.ws.jaxws.virtualhost/bootstrap.properties
  dev/com.ibm.ws.jaxws.clientcontainer_fat/publish/servers/JaxWsTransportSecurityServer/bootstrap.properties
  dev/io.openliberty.mail.2.0.internal_fat/publish/servers/com.ibm.ws.javamail.fat/bootstrap.properties
  dev/io.openliberty.mail.2.0.internal_fat/publish/servers/mailSessionTestServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#19146 grpc microprofile enablement for EE9 FAT
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreConsumerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreProducerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesRESTClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesSecurityTests.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointJWTCookieFATServlet.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
Labels: in:Transport, CLA Signed, team:Sirius

#19421 [19413] Test that CXF's _type and _ctype are honored and can be disabled
  dev/com.ibm.ws.jaxrs.2.1_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.1_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/AbstractTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/CxfReservedTypeAndCTypeTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/JAXRS21SecurityAnnotationsTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/JAXRS21SecurityAnnotationsTestRolesAsGroups.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/JAXRS21SecurityContextTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/JAXRS21SecuritySSLTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/TestUtils.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/UriInfoTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat/publish/servers/jaxrs21.fat.typeAndCType/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.1_fat/publish/servers/jaxrs21.fat.typeAndCType/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat/test-applications/jaxrs21typeAndCType/src/typeAndCType/AppAndResource.java
  dev/com.ibm.ws.jaxrs.2.1_fat/test-applications/jaxrs21typeAndCType/src/typeAndCType/ClientTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/NoOpPreprocessor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/provider/ServerProviderFactory.java
Labels: in:JAX-RS, CLA Signed, team:Wendigo West

#19472 Update xerces impl4
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
Labels: CLA Signed

#19450 Add dynamic config of tx retriable sqlcodes
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.transaction.hadb_fat.derby/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Transaction.java
Labels: CLA Signed

#19430 Create xerces impl bundle
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/build.gradle
  dev/io.openliberty.org.apache.xercesImpl/.classpath
  dev/io.openliberty.org.apache.xercesImpl/.gitignore
  dev/io.openliberty.org.apache.xercesImpl/.project
  dev/io.openliberty.org.apache.xercesImpl/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.xercesImpl/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.xercesImpl/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.xercesImpl/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.xercesImpl/bnd.bnd
  dev/io.openliberty.org.apache.xercesImpl/bnd.overrides
Labels: CLA Signed

#19481 Change from mp metrics 4.0 rc4 to final release
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/metrics.4.0.bnd
Labels: CLA Signed

#19483 Revert "grpc microprofile enablement for EE9 FAT"
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreConsumerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreProducerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesRESTClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesSecurityTests.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointJWTCookieFATServlet.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
Labels: CLA Signed

#19473 Update the isWin check for ACME FAT
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19475 transaction timeout on MultiplePersistentExecutorsWithFailoverEnabledTest
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/MultiplePersistentExecutorsWithFailoverEnabledTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19323 287571 wait for keystore
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/servers/ServerInstanceUtils.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigBuilderTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder.rs/bootstrap.properties
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder/bootstrap.properties
Labels: test bug, CLA Signed, team:Security SSO

#19495 Java 2 Security permissions for DataSourceChangeTest
  dev/com.ibm.ws.transaction.recovery_fat.1/publish/servers/recovery.dblog/server.xml
Labels: noproductcode, CLA Signed

#19490 Handle webservice call failure
  dev/com.ibm.ws.wsat.concurrent_fat/test-applications/threadedClient/src/com/ibm/ws/wsat/threadedclient/client/threaded/ThreadedClientServlet.java
  dev/com.ibm.ws.wsat.concurrent_fat/test-applications/threadedServer/src/com/ibm/ws/wsat/threadedserver/server/MultiThreaded.java
Labels: noproductcode, CLA Signed

#19492 Move additional test to krb5.2 fat bucket
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindLongRunTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19437 Remove zero width spaces
  dev/com.ibm.ws.cdi.2.0.weld/src/com/ibm/ws/cdi/proxy/AbstractProxyServices.java
Labels: CLA Signed

#19488 Duplicate Files Defining Same Component (Property.jsx and property.js…
  dev/com.ibm.ws.openapi.ui/swagger-ui/src/core/components/Property.jsx
Labels: CLA Not Needed, CLA Needed, CLA trivial

#19419 Create FAT for new config attr jwtAccessTokenRemoteValidation
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/TestServer.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcPropagationRemoteValidationTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/files/serversettings/oidcRemoteValidationRSClients.xml
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/files/serversettings/oidcUserinfoProvider.xml
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rs/configs/rs_server_withOpStub_remoteValidation.xml
Labels: noproductcode, CLA Signed, team:Security SSO, test delivery

#19496 close dump file before stopping server
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
Labels: noproductcode, CLA Signed
