Repository OpenLiberty/open-liberty, pull requests merged in 2021-01, with the labels that each got.

#15391 various threading bugs in the Liberty scheduled executor and get it to run tasks on a policy executor
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ScheduledPolicyExecutorTask.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ScheduledExecutorImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/SchedulingHelper.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/SchedulingRunnableFixedHelper.java
  dev/com.ibm.ws.threading_policy_fat/policyExecutor_fat.bnd
  dev/com.ibm.ws.threading_policy_fat/publish/servers/PolicyExecutorServer/server.xml
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledCallableTask.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledRunnableTask.java
  dev/com.ibm.ws.threading_policy_fat/test-bundles/testpolicyexecutor/src/test/policyexecutor/bundle_fat/LibertyScheduledExecutorProvider.java
Labels: CLA Signed, team:Zombie Apocalypse

#15384 Fix mpOpenAPI-2.0 scanning of application deployed with loose config
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/ApplicationProcessor.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/cache/ConfigSerializer.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/IndexUtils.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/test1/DeploymentTestApp.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/test1/DeploymentTestResource.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/test2/DeploymentTestResource2.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/files/looseWar.war.xml
Labels: CLA Signed

#12783 Orphaned transaction changes
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_cs.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_de.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_es.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_fr.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_hu.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_it.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_ja.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_ko.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_pl.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_pt_BR.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_ro.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_ru.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_zh.nlsprops
  dev/com.ibm.ws.messaging.msgstore/resources/com/ibm/ws/objectManager/CWSOMMessages_zh_TW.nlsprops
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/objectManager/InternalTransaction.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/objectManager/ObjectManagerState.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/objectManager/Transaction.java
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#12986 Revisions for hang in client session close.
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsSessionImpl.java
Labels: CLA Signed

#15389 updated include tag parsing
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ConfigParser.java
Labels: CLA Signed

#15402 Notices for 21.0.0.1
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#15395 Use MP Rest Client 2.0 API from final Maven Repo instead of staging
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15398 Get things building in eclipse again
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/com/ibm/injectintopath/App.java
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/com/ibm/injectintopath/CDIResource.java
  dev/com.ibm.ws.cdi.jee_fat/test-applications/injectIntoPath.war/src/com/ibm/injectintopath/ClassA.java
  dev/com.ibm.ws.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.logstash.collector_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan_container/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.6/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.dualDB/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/.project
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.simpleDB/.project
  dev/com.ibm.ws.transaction.cloud_fat.simpleDB/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/build.gradle
  dev/com.ibm.ws.wssecurity.fat.utils.common/.settings/bndtools.core.prefs
  dev/fattest.databases/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.classpath
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.gitignore
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.project
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsgen/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.classpath
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.gitignore
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.project
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools.wsimport/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools/.classpath
  dev/io.openliberty.xmlWS.3.0.internal.tools/.gitignore
  dev/io.openliberty.xmlWS.3.0.internal.tools/.project
  dev/io.openliberty.xmlWS.3.0.internal.tools/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlWS.3.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools/src/com/sun/tools/ws/wscompile/WsimportTool.java
  dev/io.openliberty.xmlWS.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/WsGen.java
  dev/io.openliberty.xmlWS.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/WsImport.java
  dev/io.openliberty.xmlWS.3.0.internal.tools/src/io/openliberty/xmlWS30/tools/ant/WsImportTask.java
Labels: CLA Signed, team:Performance

#15404 Add queryParam tests with special characters
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/paramconverter/src/com/ibm/ws/jaxrs/fat/paramconverter/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/paramconverter/src/com/ibm/ws/jaxrs/fat/paramconverter/TestResource.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15199 Wait indefinitely for the variable registry service
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/SystemConfiguration.java
Labels: CLA Signed

#15385 Main build for github actions
  .github/workflow-scripts/run-fat-build.sh
  .github/workflow-scripts/run-unit-tests.sh
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15369 Add jakarta.inject import to batch.2.0
  dev/io.openliberty.jakarta.batch.2.0/bnd.bnd
Labels: CLA Signed

#15413 Update feature replacement to handle multiple versions being added
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: CLA Signed, noproductcode, team:Performance

#15394 Re-introduce ms sql server support and containerized tests
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.project
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/com.ibm.ws.transactions.fat.utils.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/DualServerDynamicMSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/MSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/transaction_fat.bnd
Labels: CLA Signed

#15422 Review JakartaEE9Action change that was done in PR #15307
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: CLA Signed, noproductcode, team:Performance

#15410 Wait for JMS server start message
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20security/fat/JMSContextTest/JMSContextTest.java
Labels: CLA Signed, noproductcode

#15406 Update EclipseLink 2.6_WAS
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
Labels: CLA Signed

#15291 beta autoCloseConnections (HandleList)
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.emptyHandleListContext-1.0.feature
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentTxTestServer/server.xml
  dev/com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#15424 Update to SmallRye Config 2.0.1 for Java 2 security fix
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20Tests.java
Labels: CLA Signed, in:MicroProfile/Config

#15426 Update FT 3.0 API link to maven central
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-3.0.feature
Labels: CLA Signed

#15417 make id required for distributed map
  dev/com.ibm.ws.dynacache/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.dynacache/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#15396 Use MicroProfile Opentracing 2.0 GM version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/opentracing.2.0.bnd
Labels: CLA Signed

#15419 Add xmlWS-3.0 to tested features for JAX-WS EJB fat
  dev/com.ibm.ws.jaxws.ejb_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.ejb_fat/build.gradle
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBInWarServiceTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBJndiTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSBasicTest.java
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/suite/FATSuite.java
Labels: CLA Signed, noproductcode

#15435 11793 - remove webcontainer dependency on com.ibm.ws.org.apache.cxf.rt.transport.http.3.2
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/cxf/exceptions/InvalidCharsetException.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/helloworld/HelloWorldTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/endpoint/AbstractJaxRsWebEndpoint.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/com/ibm/ws/cxf/exceptions/InvalidCharsetException.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppErrorReport.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15430 Jwt builder oom update
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/actions/JwtTokenActions.java
  dev/com.ibm.ws.security.fat.common.mp.jwt/src/com/ibm/ws/security/fat/common/mp/jwt/actions/MpJwtFatActions.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/actions/JwtBuilderActions.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/actions/JwtConsumerActions.java
Labels: CLA Signed, team:Security SSO, test debt

#15438 Create new test-category for mpJwt Security FATs
  .github/test-categories/MP_JWT_3
Labels: CLA Signed, noproductcode, team:Security SSO, test delivery

#15403 Fixed the AssumptionViolatedException in MPHealth FAT
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
Labels: CLA Signed, noproductcode

#15414 tolerate CWWKC1503W in testTimerFailsOverWhenServerStops
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15450 Update FAT approvers to use GitHub team
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed, noproductcode

#15427 tests for suspend and resume of scheduled executor via a policy executor
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledBlockingQueueTask.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15330 Add JSTL sources jar for API project
  dev/io.openliberty.jakarta.jstl.2.0/build.gradle
Labels: CLA Signed, in:Web Components, jakartaEE, noproductcode, team:Sirius

#15448 Issue #15447: Fix CouchDB FAT
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.couchdb_fat/publish/servers/com.ibm.ws.couchdb.fat.server/server.xml
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
Labels: CLA Signed, team:Blizzard

#15445 Ensure async servlet support is enabled when `@ApplicationPath` not used
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15446 Move weblcient close to finally block
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/actions/JwtBuilderActions.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/actions/JwtConsumerActions.java
Labels: CLA Signed, noproductcode, team:Security SSO, test debt

#15425 Ignore AppForceRestart on quiesce
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureManagerTest.java
Labels: CLA Signed

#15439 Temporary skip zOS for GC events
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#15436 Add beta fence for issue #14692
  dev/com.ibm.ws.security.openidconnect.client/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
Labels: CLA Signed

#14913 removed beta fence for nbfOffset attribute in jwtBuilder
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#15423 Make sure flat configuration is merged appropriately
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/ConfigEvaluatorTest.java
Labels: CLA Signed

#15401 Add check for new/removed fats
  .github/test-categories/CONCURRENT_1
  .github/test-categories/CONCURRENT_2
  .github/test-categories/CONCURRENT_3
  .github/test-categories/EJB_2
  .github/test-categories/GENERAL
  .github/test-categories/INSTALL
  .github/test-categories/JAVAEE
  .github/test-categories/JAXWS
  .github/test-categories/JCA
  .github/test-categories/JPA_1
  .github/test-categories/JPA_2
  .github/test-categories/KERNEL_2
  .github/test-categories/MESSAGING
  .github/test-categories/MISC
  .github/test-categories/MP_JWT_3
  .github/test-categories/MP_METRICS_2
  .github/test-categories/MP_REST_CLIENT_1
  .github/test-categories/QUARANTINE
  .github/test-categories/SECURITY_3
  .github/test-categories/SECURITY_5
  .github/test-categories/SECURITY_6
  .github/test-categories/TRANSACTION_1
  .github/test-categories/TRANSACTION_2
  .github/workflow-scripts/GenerateCategories.java
  .github/workflow-scripts/run-fat-build.sh
  .github/workflow-scripts/run-unit-tests.sh
  .github/workflow-scripts/validate-new-tests.sh
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15464 Add tags and minor updates
  .github/ISSUE_TEMPLATE/blog_post_beta.md
Labels: noproductcode

#15465 Add labels and minor tweaks to GA Blog template
  .github/ISSUE_TEMPLATE/blog_post_ga_release.md
Labels: noproductcode

#15457 Avoid calling WeldBootstrap when looking up a BeanManager to prevent …
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/injection/EEValidationUtils.java
Labels: CLA Signed

#15462 JCA annotations not processed for v2.0
  dev/com.ibm.ws.jca.utils/src/com/ibm/ws/jca/utils/metagen/RAAnnotationProcessor.java
Labels: team:Zombie Apocalypse

#15456 Defect 262716: Avoid deletion of application before stopping the server
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ExtractedAppTests20.java
Labels: CLA Signed, noproductcode

#15468 Adding localConnector to jakartaee-9 package
  dev/build.image/profiles/jakartaee9/features.xml
Labels: CLA Signed

#15452 Update MP JWT 1.2 to use final version of MicroProfile API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.jwt-1.2.feature
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/fat/src/Readme.txt
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/jwt.1.2.bnd
Labels: CLA Signed, team:Security SSO

#15460 Fix Indirection Reference issue for TestContainers
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_locking/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.jpa_eclipselink_fat/bnd.bnd
  dev/com.ibm.ws.jpa_locking_fat/bnd.bnd
  dev/com.ibm.ws.jpa_ol_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_injection_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part01_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part02_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_query_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#15467 Use Class.getName() instead of hard coded string.
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/metadata/SecurityServletConfiguratorHelper.java
Labels: CLA Signed, team:Performance

#15393 Fix setter to include env var for JSON log field serverName
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/ContainerEnvVarTest.java
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/FATSuite.java
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ContainerHostEnvServer/server.env
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ContainerHostEnvServer/server.xml
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ContainerNameEnvServer/server.env
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ContainerNameEnvServer/server.xml
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonLogHandler.java
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/suite/FATSuite.java
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/ContainerEnvVarTest.java
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/ContainerEnvServer/ bootstrap.properties
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/ContainerEnvServer/resources/security/key.p12
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/ContainerEnvServer/server.env
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/ContainerEnvServer/server.xml
Labels: CLA Signed

#15458 Update mpOpenAPI-2.0 Artifacts
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.openapi-2.0.feature
  dev/io.openliberty.io.smallrye.openapi.core/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi.jaxrs/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/cache/ConfigSerializer.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/openapi.2.0.bnd
Labels: CLA Signed, in:MicroProfile/OpenAPI

#15466 cleanup known failures in GH actions build
  .github/test-categories/INSTALL
  .github/test-categories/QUARANTINE
  .github/test-categories/SECURITY_3
  .github/test-categories/SECURITY_5
  .github/test-categories/SECURITY_6
  .github/workflow-scripts/check-fat-failures.sh
  .github/workflow-scripts/run-fat-build.sh
  .github/workflow-scripts/validate-tests.sh
  .github/workflows/openliberty-ci.yml
Labels: noproductcode, team:Zombie Apocalypse

#15381 upgrade testcontainers to 1.15.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_locking/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_db2/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.jpa_eclipselink_fat/bnd.bnd
  dev/com.ibm.ws.jpa_locking_fat/bnd.bnd
  dev/com.ibm.ws.jpa_ol_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_injection_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part01_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part02_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_query_fat/bnd.bnd
  dev/com.ibm.ws.logstash.collector_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan_container/bnd.bnd
  dev/com.ibm.ws.transaction.HADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.db_fat/bnd.bnd
  dev/fattest.databases/bnd.bnd
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.databases/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.databases/src/componenttest/topology/database/container/SQLServerContainer.java
  dev/fattest.simplicity/bnd.bnd
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Zombie Apocalypse

#15459 Fixes the SocketTimeOutException in Health FAT
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/ApplicationStateHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/bootstrap.properties
Labels: CLA Signed, noproductcode

#15477 Increase TCK app deploy timeout for slower build machines
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: in:MicroProfile/GraphQL, in:MicroProfile/RestClient, team:Wendigo West

#15478 Extend TCK Timeout cushion for slower build machines
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
Labels: in:MicroProfile/RestClient, team:Wendigo West

#15482 Increase heap size for Maven surefire plugin for MP Rest Client TCKs
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: in:MicroProfile/RestClient, team:Wendigo West

#15492 Handle beans.xml with discoveryMode="none" - no beanManager
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/cdi/LibertyCdiInjectorFactory.java
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/cdi/LibertyFallbackInjectorFactory.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/AppAndResourceCDIBeanDiscoveryModeDisabledTest.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
Labels: in:JAX-RS, team:Wendigo West

#15093 Insert null checks for context to avoid NPEs
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/HttpServletRequestInjectionProxy.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/HttpServletResponseInjectionProxy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/HttpServletRequestInjectionProxy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/HttpServletResponseInjectionProxy.java
Labels: CLA Signed

#15500 [15499] Add corrective action to MP Rest Client scoping/perf message
  dev/com.ibm.ws.microprofile.rest.client.cdi/resources/com/ibm/ws/microprofile/rest/client/cdi/nls/MPRestClientMessages.nlsprops
Labels: in:MicroProfile/RestClient, team:Wendigo West

#15510 Increase grpc_fat producer and consumer deadlines
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/grpcConsumer/api/ConsumerGrpcServiceClientImpl.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreProducerApp.war/src/com/ibm/testapp/g3store/grpcProducer/api/ProducerGrpcServiceClientImpl.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius

#15514 change arrayList type
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
Labels: CLA Signed

#15511 CL22177 isSuspended and getMaxConcurrency for policy executor
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#15501 CL22178 callback for handling failed resubmit
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ScheduledPolicyExecutorTask.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/SchedulingHelper.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/SchedulingRunnableFixedHelper.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledCallableTask.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledRunnableTask.java
Labels: team:Zombie Apocalypse

#15509 Handle `JsonString` types
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonpApp/src/jaxrs21/fat/jsonp/JsonpResource.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonpApp/src/jaxrs21/fat/jsonp/JsonpTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/providers/JsonPProvider.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15486 Fix handling Windows paths in mergeFile
  dev/fattest.simplicity/src/componenttest/topology/utils/CommonMergeTools.java
Labels: noproductcode, team:Security SSO, test bug

#15508 Add debug to PackageRunnableTest
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#15513 Defect 269099: disable test until uber jar creation works reliably
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityThinTest.java
Labels: CLA Signed, noproductcode

#15489 handle ORA-12631 when testing oracle kerberos
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-oracle-app/src/jdbc/krb5/oracle/web/OracleKerberosTestServlet.java
Labels: noproductcode, team:Zombie Apocalypse

#15515 Add mpConfig-2.0 tests for the behaviour when CDI-2.0 isn't defined
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20NoCDITests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/noCDI/NoCDITestServlet.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20NoCDIServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20NoCDIServer/server.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#15516 Fix broken local builds for com.ibm.ws.jaxrs.2.0.client_fat
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15485 Upgrade to Gradle 6.8
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/com.ibm.ws.logging_test/test/properties/bad.properties
Labels: noproductcode, team:Continuous Delivery

#15531 quarantine mislabeled projects
  .github/test-categories/QUARANTINE
  .github/test-categories/SECURITY_5
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15529 Remove the EE9 skipped FAT tests from com.ibm.ws.jaxrs.2.0.client_fat BasicClientTest
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/BasicClientTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15504 Adjust db competeforlogs method
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/fat/src/com/ibm/ws/transaction/test/MSSQLServerTest.java
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/fat/src/com/ibm/ws/transaction/test/PostgreSQLTest.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleDB/fat/src/com/ibm/ws/transaction/test/tests/Simple2PCCloudTest.java
Labels: noproductcode

#15481 Issue #15480: Remove comments that are not necessary
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDICommon/src/com/ibm/ws/jsf22/fat/cdicommon/managed/CustomELResolver.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDICommon/src/com/ibm/ws/jsf22/fat/cdicommon/managed/CustomNavigationHandler.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDICommon/src/com/ibm/ws/jsf23/fat/cdi/common/managed/CustomELResolver.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDICommon/src/com/ibm/ws/jsf23/fat/cdi/common/managed/CustomNavigationHandler.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestInjection.war/src/com/ibm/ws/jsp23/fat/testinjection/listeners/JspCdiTagLibraryEventListenerCI.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestInjection.war/src/com/ibm/ws/jsp23/fat/testinjection/listeners/JspCdiTagLibraryEventListenerFI.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestInjection.war/src/com/ibm/ws/jsp23/fat/testinjection/listeners/JspCdiTagLibraryEventListenerMI.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestServlet40.war/src/testservlet40/war/listeners/SessionTimeoutContextListenerImpl.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/common/BinaryStreamDecoder.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/basic.war/src/basic/war/CodedServerEndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/basic.war/src/basic/war/LinkedListHashSetMessageHandler.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/miscellaneous.war/src/miscellaneous/war/EndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/trace.war/src/trace/war/CodedServerEndpointConfig.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/websocket11.war/src/websocket11/war/CodedServerEndpointConfig11.java
Labels: in:Transport, in:Web Components, noproductcode, team:Sirius

#15519 remove workaround for RepeatTests
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15434 Wait for system WABs before registering ServerStarted service
  dev/com.ibm.ws.app.manager.wab.installer_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/AbstractWABTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/ConfigurableWABTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/FATSuite.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/WabStartDelayTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/publish/files/configs/testWabStartDelay.xml
  dev/com.ibm.ws.app.manager.wab.installer_fat/test-bundles/test.wab1/src/test/wab1/ContextListener.java
  dev/com.ibm.ws.app.manager.wab/bnd.bnd
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WAB.java
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/ServerReadyStatus.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
Labels: CLA Signed

#15505 Preserve jakarta transformer logs in the event of a failure
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: noproductcode, team:Zombie Apocalypse

#15535 Issue #15522: Upgrade commons compress to 1.20
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.app.manager.wab.installer_fat/build.gradle
  dev/com.ibm.ws.kernel.boot.archive/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/build.gradle
  dev/com.ibm.ws.logging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.compress/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/io.openliberty.microprofile.health.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/bnd.bnd
Labels: CLA Signed

#15429 Roll fattest.databases into fattest.simplicity
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_locking/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_locking/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/build.gradle
  dev/com.ibm.ws.concurrent.persistent_fat_timers/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_timers/build.gradle
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/bnd.bnd
  dev/com.ibm.ws.jdbc_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.jpa_eclipselink_fat/bnd.bnd
  dev/com.ibm.ws.jpa_eclipselink_fat/build.gradle
  dev/com.ibm.ws.jpa_locking_fat/bnd.bnd
  dev/com.ibm.ws.jpa_locking_fat/build.gradle
  dev/com.ibm.ws.jpa_ol_fat/bnd.bnd
  dev/com.ibm.ws.jpa_ol_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_injection_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_injection_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_part01_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part01_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_part02_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part02_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_query_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_query_fat/build.gradle
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.transaction.HADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql/build.gradle
  dev/com.ibm.ws.transaction.db_fat/bnd.bnd
  dev/com.ibm.ws.transaction.db_fat/build.gradle
  dev/fattest.databases/.classpath
  dev/fattest.databases/.project
  dev/fattest.databases/.settings/bndtools.core.prefs
  dev/fattest.databases/.settings/org.eclipse.core.resources.prefs
  dev/fattest.databases/.settings/org.eclipse.jdt.core.prefs
  dev/fattest.databases/bnd.bnd
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/resources/init-sqlserver.sql
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DerbyClientContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DerbyNoopContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/OracleContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/PostgreSQLContainer.java
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, noproductcode, team:Performance

#15160 Add expandLocation attribute for AutoExpand
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfoFactoryImpl.java
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/war/internal/WARDeployedAppInfoFactoryImpl.java
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/ApplicationManager.java
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AbstractAppManagerTest.java
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/definedEarServerExpandLocation.xml
  dev/com.ibm.ws.app.manager_fat/publish/files/autoExpand/definedWarServerExpandLocation.xml
  dev/com.ibm.ws.app.manager_fat/publish/servers/autoExtractTestServer/jvm.options
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#15520 Fix sleep time debug in PackageRunnableTest
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#15518 Enable EmptyTokenTest without InvalidToken test
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
Labels: CLA Signed, noproductcode, team:Security SSO

#15521 Wait for empty queue before restarting apps
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
Labels: CLA Signed

#15537 Support ManagedBeans as RESTful WS Components
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/ManagedBeansTest.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/managedbeans/App.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/managedbeans/ManagedBeansTestServlet.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/managedbeans/Resource.java
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/managedbeans/bootstrap.properties
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/managedbeans/server.xml
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15536 Rename occurrences of was-liberty to websphere
  dev/build.changeDetector/src/com/ibm/ws/infra/depchain/ChangeDetector.java
  dev/cnf/ant/delivery_validation.xml
  dev/cnf/ant/liberty-ghe.xml
  dev/cnf/ant/pass-back.xml
  dev/cnf/ant/push-commits-to-master.xml
  dev/cnf/ant/universal_properties.xml
  dev/com.ibm.ws.wssecurity.fat.utils.common/fat/src/com/ibm/ws/wssecurity/fat/utils/common/CommonTests.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestService.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: CLA Signed

#15490 Compare OS using lower case
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: noproductcode

#15545 Additional trasnsforms for xml WS
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
Labels: CLA Signed, team:Performance

#15539 Updated dependencies to pull SR OpenAPI-2.1.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#15528 Issue #15527: Add src dir to .classpath
  dev/io.openliberty.jakarta.servlet.5.0/.classpath
Labels: CLA Signed, in:Web Components, jakartaEE, noproductcode, team:Sirius

#15532 Add EJBException to unwrappedexceptions list
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigImpl.java
  dev/io.openliberty.restfulWS.3.0_fat/bnd.bnd
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/ExceptionTest.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/exception/ExceptionTestServlet.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/exception/Resource.java
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/exception/bootstrap.properties
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/exception/server.xml
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15549 test that ManagedThreadFactory is still working after app restart if looked up again
  dev/com.ibm.ws.concurrent_fat_config/fat/src/com/ibm/ws/concurrent/fat/EEConcurrencyConfigTest.java
  dev/com.ibm.ws.concurrent_fat_config/publish/servers/concurrent.config.fat/server.xml
  dev/com.ibm.ws.concurrent_fat_config/test-applications/concurrent/src/fat/concurrent/web/EEConcurrencyUtilsFATServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15547 CL22175 single catch-up for fixed-rate execution
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ScheduledPolicyExecutorTask.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/SchedulingRunnableFixedHelper.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledBlockingQueueTask.java
Labels: CLA Signed, team:Zombie Apocalypse

#15525 Update OSS building from source
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
Labels: CLA Signed

#15526 Update OSS building from source
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
Labels: CLA Signed

#15554 Add keystore to tests
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleEar/resources/security/key.p12
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleWar/resources/security/key.p12
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleEar/resources/security/key.p12
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleWar/resources/security/key.p12
Labels: CLA Signed, noproductcode

#15560 Minor updates to MP Rest Client feature / tests
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-2.0/com.ibm.websphere.appserver.mpRestClient-2.0.feature
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseClientTestServlet.java
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#15562 Early exit when dir.listFiles() returns null
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed, in:Application Services, team:Wendigo West

#15563 Synchronize access to configProperties map
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigImpl.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15557 Output session max messages
  dev/com.ibm.ws.session/src/com/ibm/ws/session/store/memory/MemoryStore.java
Labels: CLA Signed

#15565 Guard against environments where chmod doesn't exist
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractUtils.java
Labels: CLA Signed

#14661 trusted header configuration improvements
  dev/com.ibm.ws.http2.client/bnd.bnd
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCell.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCellFastStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCellSlowStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterList.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterListFastStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterListSlowStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterListStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/package-info.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/HttpDispatcher.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/TrustedHeaderOriginLists.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/dispatcher/internal/HttpDispatcherTest.java
Labels: CLA Signed, CLA trivial, ID reviewed, in:Transport, team:Sirius

#15568 Update SmallRye Config to version 2.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed, in:MicroProfile/Config

#15572 Issue #12029: ManagedBeans bindings FAT for Jakarta EE 9
  dev/com.ibm.ws.managedbeans_fat/bnd.bnd
  dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeanBindingsEJBTest.java
Labels: CLA Signed, in:Java EE Platform, jakartaEE, noproductcode, team:Blizzard, test delivery

#15362 edit description
  dev/com.ibm.websphere.appserver.features/visibility/public/ldapRegistry-3.0/resources/l10n/com.ibm.websphere.appserver.ldapRegistry-3.0.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#15564 switch to MP Context Propagation 1.2 TCK
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.classpath
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.project
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/README.md
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/bnd.bnd
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/fat/src/com/ibm/ws/concurrent/mp/v1_2/fat/tck/FATSuite.java
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/fat/src/com/ibm/ws/concurrent/mp/v1_2/fat/tck/MPContextPropagationTCKLauncher.java
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/servers/tckServerForMPContextPropagation12/bootstrap.properties
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/servers/tckServerForMPContextPropagation12/jvm.options
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/servers/tckServerForMPContextPropagation12/server.xml
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15313 Jms fat cleanup
  dev/com.ibm.ws.messaging.open_jms20AutoCloseable_fat/fat/src/com/ibm/ws/messaging/JMS20AutoCloseable/fat/Autocloseable/AutoCloseableTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/ContextInject/JMSContextInjectTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/DummyTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/DurableUnshared/DurableUnsharedTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSConsumerTest/JMSConsumerTest_118076.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSConsumerTest/JMSConsumerTest_118077.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest/JMSEjbJarXmlMdbTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest/JMSRedeliveryTest_120846.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSDCFTest/JMSDCFTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSDCFTest/JMSDCFVarTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSMBeanTest/JMSMBeanTest.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSProducerTest/JMSProducerTest_118071.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSProducerTest/JMSProducerTest_118073.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSProducerTest/JMSProducer_Test118073.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet1Test.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet2Test.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketTestSuite.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionTest_129623.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionTest_129626.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionWithMsgSelTest_129623.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionWithMsgSelTest_129626.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118058.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118061.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118062.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118065_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118066_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118067.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118068_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118070.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118075.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/JMSContextTest_118077_TQ.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet1Test.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet2Test.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/LiteBucketSet3Test.java
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/Transaction/JMSContextTest_118065.java
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20security/fat/DummyTest.java
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20security/fat/FATSuite.java
Labels: CLA Signed, noproductcode

#15574 Fix the GitHub Actions builds from failing validate-tests.sh
  .github/test-categories/MP_MISC
Labels: CLA Signed, noproductcode

#15567 Add additional mpConfig-2.0 FAT tests
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20ExceptionTests.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20PropertyExpressionExceptionTests1.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/Config20PropertyExpressionExceptionTests2.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenInjection/BadConfigPropertiesBean.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenPropertyExpression/MissingPropertyExpressionBean1.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/brokenPropertyExpression/MissingPropertyExpressionBean2.java
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20PropertyExpressionExceptionServer/bootstrap.properties
  dev/io.openliberty.microprofile.config.2.0.internal_fat/publish/servers/Config20PropertyExpressionExceptionServer/server.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#15474 Issue #11777: Add prepareJSPThreadCount to the metatype.
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPPrepareJSPThreadCountDefaultValueTests.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPPrepareJSPThreadCountNonDefaultValueTests.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountDefaultServer/.gitignore
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountDefaultServer/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountDefaultServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountNonDefaultServer/.gitignore
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountNonDefaultServer/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountNonDefaultServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/SimpleJSPApp.war/resources/HelloWorld.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/SimpleJSPApp.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsp/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jsp/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/JspOptions.java
Labels: L2 ReviewNotRequired, in:Web Components, team:Sirius

#15141 JSTL Refactoring
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.2/com.ibm.websphere.appserver.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.3/com.ibm.websphere.appserver.jsp-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
  dev/com.ibm.ws.jsp.jstl.facade/bnd.bnd
  dev/com.ibm.ws.jsp/bnd.bnd
  dev/com.ibm.ws.org.apache.taglibs.standard/.classpath
  dev/com.ibm.ws.org.apache.taglibs.standard/.project
  dev/com.ibm.ws.org.apache.taglibs.standard/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.taglibs.standard/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.taglibs.standard/bnd.bnd
  dev/io.openliberty.jstl.facade/.classpath
  dev/io.openliberty.jstl.facade/.gitignore
  dev/io.openliberty.jstl.facade/.project
  dev/io.openliberty.jstl.facade/.settings/bndtools.core.prefs
  dev/io.openliberty.jstl.facade/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jstl.facade/bnd.bnd
  dev/io.openliberty.org.apache.taglibs.standard/.classpath
  dev/io.openliberty.org.apache.taglibs.standard/.project
  dev/io.openliberty.org.apache.taglibs.standard/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.taglibs.standard/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.taglibs.standard/bnd.bnd
  dev/io.openliberty.org.apache.taglibs.standard/build.gradle
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
Labels: CLA Signed

#14987 Add copyright to bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIBVServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIWSOCServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23Server/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23jpa22Server/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsfCDIConfigByACPServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsfCDIFacesInMetaInfServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsfCDIFacesInWebXMLServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsfFeatureConflictServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ContextRootPrecedenceServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_PushBuilderSecurity/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_SCIException/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletPathForDefaultMapping_Default/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletPathForDefaultMapping_False/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_addJspFileServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_stopAppStartListenerExceptionServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_wcServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_stopAppStartListenerExceptionServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_wcServer/bootstrap.properties
Labels: CLA Signed, noproductcode

#15299 Ignore server quiesce timeouts in MP Rest Client FATs
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiInEE8Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicEJBTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CdiPropsAndProvidersTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagation12Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagationTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HostnameVerifierTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/MultiClientCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/PropsTest.java
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15449 Update private feature to list GA API coordinates
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.rest.client-2.0.feature
Labels: CLA Signed, in:MicroProfile/RestClient, team:Wendigo West

#15366 Add new SQLServer TX HADB FAT suite
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.classpath
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.project
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/build.gradle
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/fat/src/com/ibm/ws/transaction/test/FailoverTest.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/ifxjdbc.bnd
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/publish/servers/com.ibm.ws.transaction/bootstrap.properties
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnection.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSource.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSourceBeanInfo.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxDatabaseMetaData.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-bundles/ifxlib/src/com/informix/jdbcx/IfxStatement.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/transaction_fat.bnd
Labels: CLA Signed, noproductcode

#15592 Update MPCompatible test to use MP Context Prop 1.2
  dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/MPCompatibleTest.java
  dev/io.openliberty.microprofile.internal_fat/publish/servers/MPCompatibleServer/MP40andMPCtx12.xml
Labels: CLA Signed, noproductcode

#15578 Add Permissions for Java 2 Security on SQLServer cloud tx tests
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.mssqlserver/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
Labels: CLA Signed, noproductcode

#15580 Issue #15579: Add AllowFFDC to App Mgr test
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/FATTest.java
Labels: CLA Signed, noproductcode

#15556 Check for null notification
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/BundleProcessor.java
Labels: CLA Signed

#15600 rebase onto integration before build
  .github/test-categories/CONCURRENT_1
  .github/test-categories/TRANSACTION_3
  .github/workflow-scripts/validate-rebase-integration.sh
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15147 ClassCastException during caching of static servlet wrapper
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/servlet/CacheServletWrapper40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
Labels: CLA Signed, release bug

#15587 Increase heap size for MP Rest Client and GraphQL TCK servers to 4GB
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/jvm.options
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
Labels: CLA Signed, in:MicroProfile/GraphQL, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#15603 Remove validate rebase
  .github/workflows/openliberty-ci.yml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15595 Tidy SQL Server and Derby HADB FAT suites and rename many methods
  dev/com.ibm.ws.transaction.HADB_fat/fat/src/com/ibm/ws/transaction/test/FailoverTest.java
  dev/com.ibm.ws.transaction.HADB_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.HADB_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/build.gradle
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/fat/src/com/ibm/ws/transaction/test/FailoverTest.java
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
Labels: CLA Signed, noproductcode

#15604 Remove the EE9 skipped FAT tests from com.ibm.ws.jaxrs.2.0.client_fat ComplexClientTest
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/ComplexClientTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/HandleResponsesTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/complexclient/src/com/ibm/ws/jaxrs20/client/ComplexClientTest/client/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/handleresponses/src/com/ibm/ws/jaxrs20/client/HandleResponsesTest/client/ClientTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15594 Clean up formatting of the JSP 2.3 FAT server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountDefaultServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23_prepareJSPThreadCountNonDefaultServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jsp23jsp22Server/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspCdiServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspJava8Server/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#15601 trusted header improvements: rework IP address validity check
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterList.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/TrustedHeaderOriginLists.java
Labels: CLA Signed, in:Transport, team:Sirius

#15612 add/remove fats from category
  .github/test-categories/WSAT_2
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15534 13027 - cache the SSLContext and SSLSocketFactory
  dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsSSLManager.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#15606 Issue 14732: Fix EmptyTokenTest for MP JWT TCK
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/servers/jwt12tckAudNoenv/server.xml
  dev/io.openliberty.microprofile.jwt.1.2.internal_fat_tck/publish/tckRunner/tck/tck_suite_aud_noenv.xml
Labels: CLA Signed, team:Security SSO

#15619 Ensure streams close while scanning classes
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/IndexUtils.java
Labels: CLA Signed

#15622 Issue #15621: Remove SharedServer from WCEncodingTest
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCEncodingTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#15624 Cleanup of eclipse files and other small cleanup items.
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-9.0/io.openliberty.webProfile-9.0.feature
  dev/com.ibm.ws.org.apache.taglibs.standard/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.lps/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.lps/.project
  dev/com.ibm.ws.wsat.recovery_fat.multi/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.multi/.project
  dev/io.openliberty.jakarta.servlet.5.0/bnd.bnd
  dev/io.openliberty.org.apache.taglibs.standard/.classpath
  dev/wlp.lib.extract_fat/bnd.bnd
Labels: CLA Signed, team:Performance

#15607 cleanup security fats
  .github/test-categories/QUARANTINE
  .github/test-categories/SECURITY_5
  .github/test-categories/SECURITY_6
  dev/com.ibm.ws.security.saml.sso_fat/build.gradle
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#15367 Update EclipseLink 2.7.7 -> 2.7.8
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/config/SystemProperties.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/helper/ConversionManager.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/sessions/Project.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/AbstractJPAProviderIntegration.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh14457/ejb/olgh14457Ejb.jar/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh14457/src/com/ibm/ws/jpa/olgh14457/testlogic/JPATestOLGH14457Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh14457/web/olgh14457Web.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/olgh14137/src/com/ibm/ws/jpa/olgh14137/testlogic/JPATestOLGH14137Logic.java
  dev/com.ibm.ws.jpa_spec21_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
Labels: CLA Signed, in:JPA, team:Blizzard

#15609 Add BATCH GitHub Actions test category; Fix comments explaining invalid vs. valid XML
  .github/test-categories/BATCH
  .github/test-categories/JAXWS
  dev/com.ibm.jbatch.container/test/files/invalid.job1.xml
  dev/com.ibm.jbatch.container/test/files/invalid.job2.xml
  dev/com.ibm.jbatch.container/test/files/valid.job1.xml
  dev/com.ibm.jbatch.container/test/files/valid.job2.xml
Labels: CLA Signed

#15634 Remove the EE9 skipped FAT tests from com.ibm.ws.jaxrs.2.0.client_fat JAXRS20ClientAsyncInvokerTest
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/IBMJson4JProvidersTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCXFRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CXFRxInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CompletionStageRxInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JerseyRxInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15627 Make OpenAPI test wait for HTTPS port to be open
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/DefaultHostListener.java
Labels: CLA Signed

#15655 Temporarily remove dependency on mpCompatible-0.0
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.contextpropagation-1.0.feature
Labels: CLA Signed, in:MicroProfile, in:MicroProfile/FaultTolerance

#15630 CL22175 clarify getNextFixedRateExecutionTime
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ScheduledPolicyExecutorTask.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/ScheduledBlockingQueueTask.java
Labels: CLA Signed, team:Zombie Apocalypse

#15663 use setHeader and only invoke when all data read
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/LibertyReadWriteListenerTest.war/src/com/ibm/ws/webcontainer/servlet_31_fat/libertyreadwritelistenertest/war/readListener/TestAsyncReadListener.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius, test bug

#15633 Remove Deprecated TestContainer API and various cleanup
  dev/com.ibm.ws.jpa_30_fat/bnd.bnd
  dev/com.ibm.ws.jpa_30_fat/build.gradle
  dev/com.ibm.ws.jpa_30_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_eclipselink_fat/bnd.bnd
  dev/com.ibm.ws.jpa_eclipselink_fat/build.gradle
  dev/com.ibm.ws.jpa_eclipselink_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_locking_fat/bnd.bnd
  dev/com.ibm.ws.jpa_locking_fat/build.gradle
  dev/com.ibm.ws.jpa_ol_fat/bnd.bnd
  dev/com.ibm.ws.jpa_ol_fat/build.gradle
  dev/com.ibm.ws.jpa_ol_fat/fat/src/io/openliberty/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec10_injection_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_injection_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec10_part01_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part01_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_part02_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_part02_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_spec10_query_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec10_query_fat/build.gradle
  dev/com.ibm.ws.jpa_spec20_fat/bnd.bnd
  dev/com.ibm.ws.jpa_spec20_fat/build.gradle
  dev/com.ibm.ws.jpa_spec21_fat/bnd.bnd
Labels: CLA Signed, noproductcode

#15582 fix a jaxrs-2.1 client fat ssl build break
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#15673 mpOpenAPI-2.0 Informative CWWKO1661E Error Message
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/ApplicationProcessor.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: CLA Signed, L2 Reviewed

#15681 Update feature_test_summary.md
  .github/ISSUE_TEMPLATE/feature_test_summary.md
Labels: CLA Signed, noproductcode

#15653 don't print message if server is shutting down
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
Labels: CLA Signed

#15589 Fix Defect 280598
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/Krb5ConfigTest.java
Labels: CLA Signed, noproductcode

#15660 Migrate additional JPA Query fat test cases.
  dev/com.ibm.ws.jpa_spec10_query_fat/build.gradle
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_DERBY.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_HSQL.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_INFORMIX.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_MYSQL.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_ORACLE.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_SYBASE.ddl
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/testlogic/JULoopQueryAnoTest.java
  dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/JULoopQueryAnoTestServlet.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard

#15666 Add WAB FATS
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/AbstractWABTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/FATSuite.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/WabAdditionalTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/WabStartDelayTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/test-bundles/test.wab1/resources/OSGI-INF/internal.txt
  dev/com.ibm.ws.app.manager.wab.installer_fat/test-bundles/test.wab1/resources/WEB-INF/web.xml
  dev/com.ibm.ws.app.manager.wab.installer_fat/test-bundles/test.wab1/resources/hello.html
  dev/com.ibm.ws.app.manager.wab.installer_fat/test-bundles/test.wab1/src/test/wab1/WebXmlMapped.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/test.wab1.bnd
Labels: CLA Signed, noproductcode
