Repository OpenLiberty/open-liberty, pull requests merged in 2021-04, with the labels that each got.

#16418 Fix for #16416 Java2Security exception from adding custom principal to subject for Jaspic
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiCallbackHandler.java
Labels: CLA Signed, team:Core Security

#16442 update Netty dependencies to 4.1.62
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: CLA Signed, in:Transport, team:Sirius

#16438 Throw low-level SIException back to the client
  dev/com.ibm.ws.messaging.comms.server/src/com/ibm/ws/sib/comms/server/clientsupport/StaticCATXATransaction.java
Labels: CLA Signed

#16447 Increase the orb timeout
  dev/com.ibm.ws.security.client_fat/publish/clients/myFileMonitorClient/client.xml
Labels: CLA Signed, noproductcode

#16221 switch PostgreSQL targetServerType to generic string
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Zombie Apocalypse

#16450 Issue #16449: Remove SharedServer from JSPServerHttpUnit test class
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/JSPServerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16446 Cleanup invalid DDL statements in JPA Spec 1.0 Part 2 FAT bucket
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_DB2.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_HSQL.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_INFORMIX.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_MYSQL.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_ORACLE.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DELETE_SYBASE.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_DB2.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_HSQL.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_INFORMIX.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_MYSQL.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_spec10_part02_fat/test-applications/jpa10/relationships/oneXmany/ddl/WEB-INF/classes/JPA10_ONEXMANY_DROP_SYBASE.ddl
Labels: CLA Signed, noproductcode

#16443 16334: Update wsoc testcases
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/BasicTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi12Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/MiscellaneousTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/TraceTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/WebSocket11Test.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/HeaderTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/util/WebServerSetup.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTest.java
Labels: CLA Signed, noproductcode

#16177 Fix Expression Factory Annotations for TCK EL Signature Test
  dev/io.openliberty.jakarta.expressionLanguage.4.0/src/jakarta/el/ExpressionFactory.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/src/org/apache/el/ExpressionFactoryImpl.java
Labels: CLA Signed, in:Web Components, team:Sirius

#16456 Fix small timing issue with bundle resolution
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/BundleProcessor.java
Labels: CLA Signed

#16453 Issue #16452: Remove SharedServer from VHServerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/VHServerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16312 Fix issues with initDatabase() method
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
Labels: CLA Signed, GitHub Build, noproductcode, team:Zombie Apocalypse, test bug

#16477 Issue 16476: Longer wait and more trace for AcmeValidityAndRenewTest
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/CAContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#16473 make sure example.com is available before using in saml logout bucket
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLCommonTestHelpers.java
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/common/OneServerSPCookieLogoutTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test debt

#16467 tolerate WTRN0052E when connection goes away
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/Failover1ServerCoordinatedPollingTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#16210 15724 kernel.boot fat
  dev/com.ibm.ws.kernel.boot_fat/build.gradle
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/AbstractLooseConfigTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseConfigDropinsTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseConfigParameterizedTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseConfigTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseContentsTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseFilterTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseRunnableTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/resources/configs/Filter.war.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/resources/looseConfig/filterContent/sample0.txt
  dev/com.ibm.ws.kernel.boot_fat/publish/resources/looseConfig/filterContent/sample0.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/resources/looseConfig/filterContent/sample1.txt
  dev/com.ibm.ws.kernel.boot_fat/publish/resources/looseConfig/filterContent/sample1.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.loose.config.fat/looseConfig/filterContent/sample0.txt
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.loose.config.fat/looseConfig/filterContent/sample0.xml
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.loose.config.fat/looseConfig/filterContent/sample1.txt
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.loose.config.fat/looseConfig/filterContent/sample1.xml
Labels: CLA Signed, noproductcode

#16420 Update jsf 2.2 default value logging
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java
Labels: CLA Signed, in:Web Components, team:Sirius

#16487 Revert "Validate visitor el support"
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/visitor/validator/ValidateVisitor.java
  dev/com.ibm.ws.org.apache.jasper.el.2.2/bnd.bnd
  dev/com.ibm.ws.org.apache.jasper.el.2.2/src/org/apache/el/lang/ELSupport.java
  dev/com.ibm.ws.security.authorization.jacc.sample.proxyprovider/.classpath
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/.classpath
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/src/org/apache/el/lang/ELSupport.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#16097 update JavaMail 1.5 and 1.6 feature descriptions
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.5/resources/l10n/com.ibm.websphere.appserver.javaMail-1.5.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.6/resources/l10n/com.ibm.websphere.appserver.javaMail-1.6.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#16125 ID edit: add info from KC for dataSource
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#16123 ID edit: add httpOptions description from KC
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#16124 ID edit: add info from KC for connectionManager
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#16483 Issue 16482: Correct message checking for TicketCacheBadPrincipalJava8
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBadPrincipalJava8.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#16485 Increase Mongo FAT connection timeout
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoConfigUpdateTest.java
Labels: CLA Signed, noproductcode, team:Blizzard, test bug

#16414 NPE when installing CL feature onto OL runtime
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
Labels: CLA Signed

#16484 clean up SAML .gitignore files
  dev/com.ibm.ws.security.saml.sso_fat.2/publish/servers/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.2/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.2.missingMetaData/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.2/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.2/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config.mapToUserRegistry/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/servers/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config.2/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/publish/servers/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.endpoint.samlmetadata/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/servers/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.config.rs/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.config.sp/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.merged_sp_rs/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.rs/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.sp/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.logout/publish/servers/com.ibm.ws.security.saml.sso_fat.logout.server2/.gitignore
  dev/com.ibm.ws.security.saml.sso_fat.logout/publish/servers/com.ibm.ws.security.saml.sso_fat.logout/.gitignore
Labels: CLA Signed, noproductcode, team:Security SSO, test debt

#16451 Remove non-word chars from table names
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.noShutdown/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_FSCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_FSCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/defaultAttributesServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longLeaseLengthFSServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longLeaseLengthServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longPeerStaleTimeServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longPeerStaleTimeServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerLockingDisabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerLockingEnabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/Simple2PCCloudServlet.java
Labels: CLA Signed

#16503 Revert "Remove non-word chars from table names"
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.noShutdown/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_FSCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_FSCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/defaultAttributesServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longLeaseLengthFSServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longLeaseLengthServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longPeerStaleTimeServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/longPeerStaleTimeServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerLockingDisabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerLockingEnabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/Simple2PCCloudServlet.java
Labels: CLA Signed

#16499 add orb timeouts
  dev/com.ibm.ws.jaxws.clientcontainer_fat/publish/clients/JaxWsTransportSecurityClient/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_nonexistentHandler.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_unauthzUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_userNotDefined.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLPromptClient/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_with_ibm_ciphersuite.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_with_nonIBM_ciphersuite.xml
Labels: CLA Signed, noproductcode

#16497 tolerate FFDCs in SwitchFromSingleInstanceToFailOverTest
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/SwitchFromSingleInstanceToFailOverTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#16512 Issue 16511: Swap JVM change to after server stop
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/RealmNameJVMProp.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#16510 DeliveryDelayFullTest, use feature list from server
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: CLA Signed, noproductcode

#16529 supply properties to DataStoreHelper
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_heritage/publish/servers/com.ibm.ws.jdbc.heritage/server.xml
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16519 Suppress NotInMessageStore FFDC
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/itemstreams/PubSubMessageItemStream.java
Labels: CLA Signed

#16469 Issue #16468: Remove SharedServer from HttpSessionAttListener test class
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/HttpSessionAttListenerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16527 Issue #16526: Remove invalid servlet 3.1 configuration
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_vhServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16523 Fix test failure in RTC 281668. Also addresses stability issues in RT…
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/InitClass.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/KdcHelper.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/MsKdcHelper.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/SPNEGOConstants.java
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
  dev/com.ibm.ws.security.spnego_fat.2/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat.2/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16493 Port changes from WS-CD-Open that were made between when I moved the …
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonTest.java
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/SameSiteTests.java
Labels: CLA Signed, team:Wendigo East

#16514 Issue 16513: Remove sslProtocol on Oracle LDAP SSL test
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/server.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#16530 split SAML jaxrs config FAT class to avoid reconfig timeouts
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedConfigCommonTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigNoReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigWithReconfigTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#16432 Update the schema gen to correctly link child first composition
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
Labels: CLA Signed

#16491 Clear map after testHandleListClosesParkedHandleWhenMDBTransactionEnds
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRAAnnoServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#16532 @SkipForRepeat cleanup - jaxrs.2.0_fat bucket
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/context/ContextTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/ibm/json/IBMJSON4JTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/jackson/JacksonPOJOTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/json/UTF8Test.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/managedbeans/ManagedBeansTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/multipart/MultipartTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/paramconverter/ParamConverterTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/readerwriterprovider/ReaderWriterProvidersTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/security/ssl/SecuritySSLTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/securitycontext/CustomSecurityContextTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/servletcoexist/JAXRSServletCoexistTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/thirdpartyjerseywithinjection/JerseyInjectionTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/context/src/com/ibm/ws/jaxrs/fat/context/ContextUtil.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/context/src/com/ibm/ws/jaxrs/fat/context/DemoApplication.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/customsecuritycontext/src/com/ibm/ws/jaxrs/fat/customsecuritycontext/servlet/CustomSecurityContextTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#16543 Session active counter
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionContextImpl.java
Labels: CLA Signed

#16549 test Subject from AccessControlContext after security context propagated
  dev/com.ibm.ws.concurrent.mp_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.mp_fat/build.gradle
  dev/com.ibm.ws.concurrent.mp_fat/publish/servers/MPConcurrentConfigTestServer/server.xml
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#16479 Issue #16478: Remove SharedServer from WCServerHttpUnit
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16481 Issue #13522: Remove internal on enableMultiReadOfPostData metaType
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, in:Web Components, team:Sirius

#16501 Wait for sleep to finish in DelayAppStartupHealthCheckTest
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/test-applications/DelayedHealthCheckApp/src/com/ibm/ws/microprofile/health20/delayed/health/check/app/DelayedServlet.java
Labels: CLA Signed, noproductcode

#16534 Additional FAT waits on certain log messages
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/AbstractWABTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/ConfigurableWABTests.java
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/WabAdditionalTests.java
Labels: CLA Signed, noproductcode

#16346 Re-apply improve incremental build
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security.2.6.2/build.gradle
  dev/com.ibm.ws.org.apache.cxf.ws.security/build.gradle
  dev/com.ibm.ws.org.openid4java/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.api.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5/build.gradle
  dev/com.ibm.ws.org.opensaml.opensaml/build.gradle
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Continuous Delivery

#16553 Update FTS template to clarify positive/negative test meaning
  .github/ISSUE_TEMPLATE/feature_test_summary.md
Labels: CLA Signed, noproductcode

#16548 Fix test failure for RTC 280705, second attempt.
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/ServicePrincipalNamesTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16244 Renaming master branch to release
  .github/ISSUE_TEMPLATE/feature.md
  CONTRIBUTING.md
  README.md
  dev/cnf/build.bnd
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#16561 Update README adding master rename instructions
  README.md
Labels: CLA Signed, noproductcode

#16520 Add websocket tests for CDI @Transactional annotations
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/Mandatory.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/Never.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/Supports.java
  dev/io.openliberty.wsoc.internal_fat/.classpath
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/Cdi20TxTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/CdiTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestRunner.java
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TxTestServer/bootstrap.properties
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi20TxTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxMandatoryFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxNeverFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxNotSupportedFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxRequiredFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxRequiresNewFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/AnnotatedTxSupportsFieldInjectionServerCDI12EP.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/Counter.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterDependentScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxMandatoryApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxNeverApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxNotSupportedApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxRequiredApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxRequiresNewApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/CounterTxSupportsApplicationScoped.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/ProducerBean.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cditx.war/src/cditx/war/SimpleWebSocketBean.java
Labels: CLA Signed

#16560 Fix for test failure in RTC 282932.
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/Krb5ConfigTest.java
  dev/com.ibm.ws.security.spnego_fat/publish/servers/Krb5ConfigTest/configs/invalidKrbKeytabFileName_NonExistentFileName.xml
  dev/com.ibm.ws.security.spnego_fat/publish/servers/Krb5ConfigTest/configs/krbConfigAtDefaultLocation.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#16528 EJB Persistent Timer fat updates
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerTestHelper.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessTimedBean.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#16556 Add getPolicy permission to http2_fat apps
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2Config31H2Off.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2Config31H2On.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2Config40H2Off.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2FullTracingTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2LiteModeTests.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/MultiSessionTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2TestModule.war/resources/META-INF/permissions.xml
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#16455 Issue #16454 - Update regex in testDump test case
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandline/DumpCommandTest.java
Labels: CLA Signed, noproductcode, test bug

#16541 Rename Plugin-cfg using Files#move
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Sirius

#16475 Issue #16474 : fix invalid cacheDirPerm for AIX in test case
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartJavaEnvironmentVariablesTest.java
Labels: CLA Signed, noproductcode, test bug

#16570 Add JVM options for command port enabled test
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandport/ServerCommandPortTest.java
Labels: CLA Signed, noproductcode

#16574 Remove bad char at end of template xml
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/webProfile7/server.xml
Labels: CLA Signed

#16577 upgrade to 21.1.0.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_krb5/build.gradle
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.postgresql/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/build.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Zombie Apocalypse

#16470 Refactor SRTServletRequest to enable dynamic proxies
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/webcontainer/JAXRSWebContainerTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/webcontainer/src/com/ibm/ws/jaxrs/fat/webcontainer/WebContainerContextInjectionResource.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java
  dev/com.ibm.ws.security.mp.jwt/test/com/ibm/ws/security/mp/jwt/config/MpConfigUtilTest.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIWebUtils.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/PostParameterHelper.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebAppDispatcherContext40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/servlet/CacheServletWrapper40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/ISRTServletRequest40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletRequest40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/FileServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/ServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/ISRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/ContextParameterInjector.java
Labels: CLA Signed, in:JAX-RS, in:Security, in:Web Components, team:Wendigo West

#16566 testMultiSharedNonDurableConsumer_SecOff test infrastructure stall
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionWithMsgSelTest_129623.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/SharedSubscription/SharedSubscriptionWithMsgSelTest_129626.java
  dev/com.ibm.ws.messaging.open_jms20_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/TestUtils.java
  dev/com.ibm.ws.messaging.open_jms20_fat/test-applications/SharedSubscriptionWithMsgSel/src/sharedsubscriptionwithmsgsel/web/SharedSubscriptionWithMsgSelServlet.java
Labels: CLA Signed, noproductcode

#16593 Remove the EE9 skipped FAT tests from com.ibm.ws.jaxrs.2.1.client_fat JAXRS21ClientCXFRxInvokerTest
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuiteLite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCXFRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLProxyAuthTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ReactiveSampleTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21TimeoutClientTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JAXRS21BookStore2.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clienttimeout/src/com/ibm/ws/jaxrs21/client/jaxrs21clienttimeout/client/JAXRS21ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21reactivesample/src/com/ibm/ws/jaxrs21/fat/JAXRS21ReactiveSample/server/ReactiveTestResource.java
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS.3.0.client_fat/.classpath
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/test/PathParamTest.java
  dev/io.openliberty.restfulWS.3.0.client_fat/publish/servers/PathParamTest/bootstrap.properties
Labels: CLA Signed

#16559 permit IBM JDK for Oracle 21c JDBC driver kerberos
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16594 Fix for test failure in RTC 283163.
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATTest_SearchBase.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16597 allow additional SSL handshake message
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/GenericOidcClientTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#16569 Tweak FAT test to handle different exception messages and FFDC output timing and RuntimeExceptions
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/annotationscan/AnnotationScanTest.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#16564 Synchronize lease delete and act on server stopping
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/SharedServerLeaseLog.java
Labels: CLA Signed

#16602 Issue #16601: Fix package test case to use .pax as default for zos
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
Labels: CLA Signed, noproductcode, test bug

#16608 Issue 16605: Add more trace to CustomStoreSample
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#16603 remove AccessIntent from OpenLiberty
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/AccessIntent.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/GenericDataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritage/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/GenericDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16610 test fixes
  dev/com.ibm.ws.security.client_fat/fat/src/com/ibm/ws/security/client/fat/ProgrammaticJaasLoginConfigFileTest.java
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticJaasLoginConfigFileTestClient/configs/client_customJaasLoginModule.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticJaasLoginConfigFileTestClient/configs/client_customLoginModule.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/javacolonClientInjection/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_orig.xml
Labels: CLA Signed, noproductcode

#16595 ClassNotFoundException in com.ibm.ws.wssecurity_fat.wsscxf
  dev/com.ibm.ws.wssecurity_fat.wsscxf/test-applications/wsstemplatesclientwithep/resources/WEB-INF/web.xml
Labels: in:Web Services, noproductcode, team:Bobcats

#16550 Request Timing Metrics
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/.classpath
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/.gitignore
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/.project
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/.settings/bndtools.core.prefs
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/bnd.bnd
  dev/com.ibm.websphere.appserver.api.requestTimingMonitor/com.ibm.websphere.appserver.api.requestTimingMonitor.pom
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoRequestTimingMonitor-1.0.feature
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.0/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.3/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/com.ibm.ws.request.timing.monitor/.classpath
  dev/com.ibm.ws.request.timing.monitor/.project
  dev/com.ibm.ws.request.timing.monitor/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.timing.monitor/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.timing.monitor/bnd.bnd
  dev/com.ibm.ws.request.timing.monitor/src/com/ibm/websphere/request/timing/RequestTimingStatsMXBean.java
  dev/com.ibm.ws.request.timing.monitor/src/com/ibm/websphere/request/timing/package-info.java
  dev/com.ibm.ws.request.timing.monitor/src/com/ibm/ws/request/timing/monitor/RequestTimingMonitor.java
  dev/com.ibm.ws.request.timing.monitor/src/com/ibm/ws/request/timing/monitor/RequestTimingStats.java
  dev/com.ibm.ws.request.timing.monitor/src/com/ibm/ws/request/timing/monitor/package-info.java
  dev/com.ibm.ws.request.timing.monitor_fat/.classpath
  dev/com.ibm.ws.request.timing.monitor_fat/.project
  dev/com.ibm.ws.request.timing.monitor_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.request.timing.monitor_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.request.timing.monitor_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.request.timing.monitor_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.request.timing.monitor_fat/bnd.bnd
  dev/com.ibm.ws.request.timing.monitor_fat/build.gradle
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/FATSuite.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingEventTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMbeanTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/package-info.java
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/disableBothFeatures.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/enableBothFeatures.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/enableMonitor-1.0.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/enableRequestTiming-1.0.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverHungRequest.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverHungRequestMetrics.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverSlowRequest.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverSlowRequestMetrics.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/.gitignore
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/server.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/.gitignore
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/server.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/.gitignore
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/server.xml
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/resources/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/src/com/ibm/ws/request/timing/app/RequestTimingServlet.java
  dev/com.ibm.ws.request.timing.monitor_fat/test-applications/RequestTimingWebApp/src/com/ibm/ws/request/timing/app/TestFilter.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/resources/io/openliberty/microprofile/metrics/internal/resources/Metrics.nlsprops
Labels: CLA Signed, ID reviewed, L2 Reviewed

#16606 Add wait for ssl restart to sigAlg tests
  dev/com.ibm.ws.security.jwtsso_fat/fat/src/com/ibm/ws/security/jwtsso/fat/SigAlgTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#16607 Update bnd dependencies to consistent version (5.3.0)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.bnd.annotations/bnd.bnd
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed

#16600 Clear the queue under a separate transaction.
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: CLA Signed, noproductcode

#16619 Add more debug to PackageRunnableTest for jar issue
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#16622 Add systemouts and trace to debug problem with EE9 testAsyncInvoker_getConnectionTimeout
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#16586 Add -Xdump option to determine intermittent classloading breaks
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/ManagedBonusPayout/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/batchFAT/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.everyone_security.fat/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.jpa.ddl.test/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.jpa.persistence/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.memory.persistence/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.nosecurity.fat/jvm.options
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20CacheServer/jvm.options
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20OrderColumnServer/jvm.options
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20Server/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/BasicAuthTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/NonSecureServerTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SSLCipherTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SSLnonIBMCipherTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SecureServerTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/javacolonServerInjection/jvm.options
Labels: CLA Signed, noproductcode, team:OSGi Infrastructure

#16436 Fix test failure in RTC 278913 (2nd try).
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FileUtils.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16584 Fix test failure in RTC 269583.
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecBase.jar/src/web/jar/base/FlexibleBaseNoJavaEESecServlet.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16592 Upgrade Arquillian version to 1.3.0.Final in MP TCKs
  dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.openapi.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.openapi_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_git_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom-manual.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile, noproductcode, team:Wendigo West

#16558 Issue #16557: Remove SharedServer from UpgradeWrite/ReadListenerHttpUnit test
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeReadListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeWriteListenerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16616 Set preclean false
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryDBTranlogTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode

#16633 Update to use StandardCharsets for UTF-8 and ISO-8859-1
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/persistence/jpa/JobInstanceEntity.java
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/JobXMLSource.java
  dev/com.ibm.ws.adaptable.module/src/com/ibm/ws/adaptable/module/internal/AddEntryToOverlayContainerAdapter.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/jandex/internal/SparseDotName.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/TCPProxyResponse.java
  dev/com.ibm.ws.common.encoder/src/com/ibm/ws/common/internal/encoder/Base64Coder.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/schemagen/internal/SchemaWriter.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/metadata/internal/J2EENameImpl.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/HashedData.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordHashGenerator.java
  dev/com.ibm.ws.dynacache.web/src/com/ibm/ws/cache/web/config/ConfigManager.java
  dev/com.ibm.ws.dynacache/src/com/ibm/ws/cache/CacheOnDisk.java
  dev/com.ibm.ws.dynamic.bundle/src/com/ibm/ws/dynamic/bundle/BundleFactory.java
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/saml/PropagationHandler.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/utils/UriEncoder.java
  dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/dispatcher/BatchJmsDispatcher.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/bridge/BatchInternalDispatcherImpl.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/ZipHelper.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobInstances.java
  dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/http/StringEntityReader.java
  dev/com.ibm.ws.jmx.connector.local/src/com/ibm/ws/jmx/connector/local/LocalConnectorActivator.java
  dev/com.ibm.ws.jndi.iiop/src/com/ibm/ws/jndi/iiop/CorbanameUrlContextFactory.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelResolver.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/ServerCommand.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/commands/ServerCommandClientTest.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/location/internal/WsLocationAdminImpl.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/CpuInfo.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/LDAPUtils.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/util/Utf8Codec.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/trm/topology/LinkCellule.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/comms/common/CommsByteBuffer.java
  dev/com.ibm.ws.messaging.jms.common/src/com/ibm/ws/sib/jms/util/Utf8Codec.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/impl/WeightedSnapshot.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/WeightedSnapshot.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/StaticFileProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/CustomCSSProcessor.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/OpenAPIUIBundlesUpdater.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/parser/OpenAPIV3Parser.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/parser/util/RefUtils.java
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/OpenAPIUtils.java
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/customization/CustomCSSProcessor.java
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/customization/OpenAPIUIBundlesUpdater.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterListFastStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/GenericKeys.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/HeaderStorage.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/extension/DefaultExtensionProcessor.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/util/Utils.java
Labels: CLA Signed, team:Performance

#16632 Issue #16630: Fix Java 16 hotspot illegal access error
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMbeanTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/illegalAccess/jvm.options
Labels: CLA Signed, noproductcode

#16656 Make `@ApplicationPath` a CDI bean-defining annotation
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/ResteasyCDIExtensionMetadata.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/CDIInjectIntoAppTest.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/cdiInjectIntoApp/CDIInjectIntoAppTestServlet.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/cdiInjectIntoApp/InvocationCounter.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/cdiInjectIntoApp/InvocationCounterImpl.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/cdiInjectIntoApp/MyApplication.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/cdiInjectIntoApp/MyResource.java
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/cdiinjectintoapp/bootstrap.properties
  dev/io.openliberty.restfulWS.3.0_fat/publish/servers/cdiinjectintoapp/server.xml
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#16629 Update globalhandler feature to only have one
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWSClient3.0-globalhandler2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.globalhandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.globalhandler1.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.globalhandler1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.globalhandler-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/com.ibm.ws.webservices.handler/bnd.bnd
  dev/io.openliberty.restfulWS.3.0.client_fat/.classpath
  dev/io.openliberty.restfulWS.internal.globalhandler/bnd.bnd
  dev/io.openliberty.restfulWS.internal.globalhandler/src/io/openliberty/restfulWS/internal/globalhandler/RESTfulGlobalHandlerMessageContext.java
  dev/io.openliberty.restfulWS.internal.globalhandler/src/io/openliberty/restfulWS/internal/globalhandler/RESTfulWSHandlerImpl.java
  dev/io.openliberty.webservices.handler.2.0/.classpath
  dev/io.openliberty.webservices.handler.2.0/.gitignore
  dev/io.openliberty.webservices.handler.2.0/.project
  dev/io.openliberty.webservices.handler.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.webservices.handler.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.webservices.handler.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.webservices.handler.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webservices.handler.2.0/bnd.bnd
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/webservices/handler/impl/GlobalHandlerService.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/webservices/handler/impl/GlobalHandlerServiceImpl.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/webservices/handler/impl/WSSPIHandlerConstants.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/webservices/handler/impl/package-info.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/wsspi/webservices/handler/GlobalHandlerMessageContext.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/wsspi/webservices/handler/Handler.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/wsspi/webservices/handler/HandlerConstants.java
  dev/io.openliberty.webservices.handler.2.0/src/com/ibm/wsspi/webservices/handler/package-info.java
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/MyHandlerFeature.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/RSHandler1Feature.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/RSHandler2Feature.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/RSMessageContextAPITestFeature.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandler1Feature1.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandler2Feature2.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandler3Feature3.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandler5Feature5.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandlerRuleFeature.mf
  dev/io.openliberty.ws.global.handler.internal_fat/publish/features/ee9/TestHandlerRuleFeature2.mf
  dev/io.openliberty.wsoc.internal_fat/.classpath
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
Labels: CLA Signed, jakartaEE, team:Performance

#16643 Upgrade to commons-io:2.8.0
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/resources/bnd/anttaskdefs.bnd
  dev/com.ibm.ws.cloudant_fat/build.gradle
  dev/com.ibm.ws.couchdb_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jbatch.open_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.org.apache.commons.io/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.mp.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.social/bnd.bnd
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/build.gradle
  dev/com.ibm.ws.security.mp.jwt.1.2_fat/build.gradle
  dev/com.ibm.ws.security.saml.sso/bnd.bnd
  dev/com.ibm.ws.security.social_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/wlp-mavenRepoTasks/bnd.bnd
Labels: CLA Signed

#16653 name conflict with jdbc heritage tests
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.classpath
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.project
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jdbc_fat_heritageinterop/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/build.gradle
  dev/com.ibm.ws.jdbc_fat_heritageinterop/fat/src/test/jdbc/heritage/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/fat/src/test/jdbc/heritage/HeritageJDBCTest.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/jdbcHeritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/jdbc_fat_heritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/files/features/jdbcHeritage-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/files/internalFeatures/dataStoreHelper-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/servers/com.ibm.ws.jdbc.heritage/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/servers/com.ibm.ws.jdbc.heritage/server.xml
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDDataSource.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HeritageDBConnection.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HeritageDBConnectionBadException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HeritageDBDoesNotImplementItException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HeritageDBDuplicateKeyException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HeritageDBFeatureUnavailableException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HeritageDBStaleConnectionException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/DuplicateKeyException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/PortableSQLException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/StaleConnectionException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/StaleStatementException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/package-info.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/GenericDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/package-info.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#16571 Issue #16568: Remove SharedServer from UpgradeReadWriteTimeout tests
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeReadWriteTimeoutHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16657 Use original feature name and rename file to satisfy feature verifica…
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.autoTimingMonitor-1.0.feature
Labels: CLA Signed

#16281 Use nested repeat action ID
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode

#16664 Issue 16663: Add additional messsage to check on TicketCacheBadPrincipalJava8
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBadPrincipalJava8.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#16665 Change leaseRenewalTime to leaseRenewalThreshold
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed, ID reviewed

#16662 Update bnd to version be consistently 5.3.0
  dev/fattest.simplicity/bnd.bnd
  dev/wlp-jakartaee-transform/bnd.bnd
Labels: CLA Signed

#16682 Revert "Add -Xdump option to determine intermittent classloading breaks"
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/ManagedBonusPayout/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/batchFAT/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.everyone_security.fat/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.jpa.ddl.test/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.jpa.persistence/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat.memory.persistence/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.fat/jvm.options
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/com.ibm.ws.jbatch.nosecurity.fat/jvm.options
  dev/com.ibm.ws.jpa.tests.spec21.issues_fat/test-applications/olgh8820/ejb/olgh8820Ejb.war/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20CacheServer/jvm.options
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20OrderColumnServer/jvm.options
  dev/com.ibm.ws.jpa_spec20_fat/publish/servers/JPA20Server/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/BasicAuthTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/NonSecureServerTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SSLCipherTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SSLnonIBMCipherTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/SecureServerTest/jvm.options
  dev/com.ibm.ws.security.client_fat/publish/servers/javacolonServerInjection/jvm.options
Labels: CLA Signed, noproductcode

#16675 Add SkipForRepeat(EE9_FEATURES) for intermittent EE9 only failing tests
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientInvocationTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ReactiveSampleTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#16670 additional commons-ui upgrades
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.security.fat.common/bnd.bnd
Labels: CLA Signed

#16658 More feature updates for Jakarta 9 enablement
  .github/test-categories/LOGGING_2
  dev/build.image/profiles/jakartaee9/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jakarta-jcaSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.javaee-jcaSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.app.manager.wab-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.app.manager.wab.jakarta-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.authData-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.authData-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jcaSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jcaSecurity.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jcaSecurity.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistentExecutor.internal.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistentExecutor.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.wsspi.appserver.webBundle-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-1.0/com.ibm.websphere.appserver.persistentExecutor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/com.ibm.websphere.appserver.persistentExecutor-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/persistentExecutor-2.0/resources/l10n/com.ibm.websphere.appserver.persistentExecutor-2.0_zh_TW.properties
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/publish/files/features/timerInterfacesTestFeature-2.0.mf
  dev/com.ibm.ws.concurrent.persistent_fat_compat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat_compat/fat/src/com/ibm/ws/concurrent/persistent/fat/compat/PersistentExecutorCompatibilityWithFailoverEnabledTest.java
  dev/com.ibm.ws.jpa.container.v22/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.injection.common/build.gradle
Labels: CLA Signed, jakartaEE, team:Performance

#16668 Fix #2 for test failure in RTC 282932. Unconditionally reset the serv…
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/CommonTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16667 Add null check to LTPA filter check in SSOAuthFilterImpl
  dev/com.ibm.ws.security.sso/src/com/ibm/ws/security/sso/SSOAuthFilterImpl.java
Labels: CLA Signed, team:Core Security, team:Security SSO

#16645 Debug Websocket Test -- testSinglePublisherMultipleReciverTextSuccess
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/TraceEnabledTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestContext.java
Labels: CLA Signed, noproductcode

#16546 Avoid virtual host missing warning if server is in the process of shutting down
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/DynamicVirtualHostManager.java
Labels: CLA Signed, release bug, team:Sirius

#16659 Update jaxrs21 FAT for Java 16
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PatchTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/publish/files/patch_java9_jvm/jvm.options
Labels: CLA Signed, noproductcode

#16701 Update tested.features settings for EE9 testing
  dev/com.ibm.ws.security.oidc.client_fat/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oidc/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat/bnd.bnd
  dev/com.ibm.ws.transaction.DB2HADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.DerbyHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.OracleHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.PostgresqlHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.SQLServerHADB_fat/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/bnd.bnd
Labels: CLA Signed, GitHub Build, noproductcode, team:Performance

#16639 Issue #16638: Remove SharedServer from Async Tests
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/AsyncReadListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/AsyncWriteListenerHttpUnit.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16698 Add SkipForRepeat(EE9_FEATURES) for intermittent EE9 only failing tests
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/customsecuritycontext/src/com/ibm/ws/jaxrs/fat/customsecuritycontext/servlet/CustomSecurityContextTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#16692 Ignore ProcessingException FFDC in JAXRS20ClientAsyncInvokerTest
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#16696 Issue 16695: Add check for no-op test config update
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#16689 Add timing delay to avoid intermittent issue
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/callback/src/com/ibm/ws/jaxrs/fat/callback/ClientTestServlet.java
Labels: CLA Signed, noproductcode, test bug

#16704 Issue 16703: Add permissions for CustomStoreSample
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/MongoDBServlet.xml
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#16706 Issue 16705: Move from consul Oracle server to unboundID for Ldap FATs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_MultipleLDAPsTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAPTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAPTest_URAttrMappingVar4.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/URAPIs_SUNLDAP_DefaultConfigTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.multipleldaps/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.attrMappingVar4/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.default/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun/server.xml
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/DefaultWIMRealmMultipleReposTest.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/DefaultWIMRealmTest.java
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.DefaultWIMRealm/server.xml
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.DefaultWIMRealmMultipleRepos/server.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#16609 16563 add exports for dump action for java16
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestEnableThreadDumps.java
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestTiming.java
  dev/com.ibm.ws.request.timing.hung_fat/publish/files/add-exports/jvm.options
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java
  dev/com.ibm.ws.request.timing_fat/publish/files/add-exports/jvm.options
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired, noproductcode

#14400 Application context path can not end with a slash
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC5GetContextPath.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_GetContextPath/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_GetContextPath/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/Servlet5TestApp.war/resources/testGetContextPath.jsp
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebGroupConfiguration.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, in:Web Components, release bug, team:Sirius

#16680 upgrading sqlserver database and driver for testing
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_sqlserver/build.gradle
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/release.sh
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, GitHub Build, team:Zombie Apocalypse

#16631 Mark setHtmlContentTypeOnError as available
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, in:Web Components, team:Sirius

#16690 Open com.sun.jndi.url.ldap package in java.naming module
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: CLA Signed

#16687 Add runtime trace to websocket traceTestServer
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16623 Beta fence Request Timing Metrics
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/bootstrap.properties
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
Labels: CLA Signed

#16714 Add systemouts and trace to debug problem with testSecuritySSL
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/security/ssl/SecuritySSLTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/security/src/com/ibm/ws/jaxrs/fat/securitycontext/SecurityContextUtils.java
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/javax.ws.rs.ext.Providers
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#16691 Trigger server dump when test server startup validation fails
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, noproductcode, team:Sirius, test bug

#16718 adding more timeout
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_emptyPwd.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_emptyUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_nullPwd.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_nullUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_customLoginModule.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_orig.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_withCredentials.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLAutoAcceptClient/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLPromptClient/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLTestClient/client.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_badPassword.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_badUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_emptyPassword.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_emptyUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_noUserPassword.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_unauthorizedUser.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_xorPassword.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/noDefaultKeyClient/configs/client_orig.xml
Labels: CLA Signed, noproductcode

#16716 transition from inheritance model to direct use of legacy datastorehelper
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/AdapterUtil.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2Helper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2JCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iNativeHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DB2iToolboxHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DataDirectConnectSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DerbyNetworkClientHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/InformixJCCHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/MicrosoftSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/SybaseHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbXaResourceImpl.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcPreparedStatement.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcStatement.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/jdbcHeritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/files/features/jdbcHeritage-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/HDConnection.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/appprofile/accessintent/AccessIntent.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/appprofile/accessintent/package-info.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/GenericDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16699 Add option to allow the build to specify complete feature list
  dev/build.image/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
Labels: CLA Signed

#16654 Add debug for test failure in RTC 281672.
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/SPNEGOConstants.java
  dev/com.ibm.ws.security.spnego_fat/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/addSpnToKeytabOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/createUserAndSetSpnOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/createWinKeytabFileOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/createWinUserOL.vbs
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/deleteUserSpnOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/removeWinUsersOL.vbs
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/setUserSpnOL.bat
Labels: CLA Signed, noproductcode, team:Wendigo East

#16722 Fix compile failure in MP metrics internal 3.0 monitor
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/bnd.bnd
Labels: CLA Signed, team:Zombie Apocalypse

#16715 Interim fix to use the released 2.0.5-RC1 and 1.1.4-RC1 to address Java 16
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#16635 ensure IllegalStateException does not prevent purge
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
Labels: CLA Signed, team:Zombie Apocalypse

#16721 Move debug logic outside of the the sync block in ZipFileHandleImpl
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
Labels: CLA Signed, performance, team:Performance

#16713 Issue 16712: Add more tuning for CustomStoreSample
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoServerSelector.java
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#16734 Add timing trace in bat files for all KDC scripts to help in debuggin…
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/addSpnToKeytabOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/createUserAndSetSpnOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/createWinKeytabFileOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/deleteUserSpnOL.bat
  dev/com.ibm.ws.security.spnego_fat/publish/files/kerberos/setUserSpnOL.bat
Labels: CLA Signed, noproductcode, team:Wendigo East

#16677 Issue #16676: Transform acmeCA-2.0 feature for EE9 namespaces.
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.acmeCA2.0.internal.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.acmeCA2.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.socialLogin1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeApplicationStateListener.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/web/AcmeAuthorizationServlet.java
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeCaRestHandlerTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeDisableTriggerSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeRevocationTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSwapDirectoriesTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeURIConfigVariationsTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeURISimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/FATSuite.java
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
Labels: CLA Signed

#16730 Adding trace for test failure in RTC 278913. Windows systems are stil…
  dev/fattest.simplicity/src/componenttest/topology/utils/FileUtils.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#16731 remove references to GenericDataStoreHelper that were missed
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#16727 use jdbc-4.2 for compatibility with both Java 8 and 11
  dev/com.ibm.ws.concurrent.persistent_fat/bnd.bnd
  dev/com.ibm.ws.concurrent.persistent_fat/publish/files/features/timerInterfacesTestFeature-2.0.mf
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#16717 allow additional SSL Handshake message in OP - not RP
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/GenericOidcClientTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#16710 Add tracing to wsoc servers to debug quiesce error
  dev/io.openliberty.wsoc.internal_fat/publish/servers/basicTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16239 Updates to SAF registry auth
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/jaas/modules/UsernameAndPasswordLoginModule.java
  dev/com.ibm.ws.security.wim.registry/bnd.bnd
  dev/com.ibm.ws.security/src/com/ibm/ws/security/context/SubjectRegistryManager.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/context/internal/SubjectRegistryThreadContext.java
Labels: CLA Signed, team:Wendigo East

#14177 The WebContainer properties may not be updated accordingly
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Signed, in:Web Components, team:Sirius

#16655 Made changes to migrate wsoc tests to a new client version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.wsoc.internal_fat/build.gradle
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/endpoints/client/basic/AnnotatedClientEP.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/endpoints/client/basic/AnnotatedConfiguratorClientEP.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/endpoints/client/basic/IdleTimeoutTCKClientEP.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
Labels: CLA Signed

#16660 Wait for ObjectFactory References
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/OSGiInjectionEngineImpl.java
Labels: CLA Signed, in:Java EE Platform, team:Blizzard

#16733 Workaround for Java 2 security issue in servlet-5.0 API
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed, in:Web Components, team:Wendigo West

#16744 Move MP Rest Client TCK version to 2.0.1-RC1
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#16748 Make memory threshold configurable for multipart attachments in RESTEasy
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.multipart/jvm.options
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West
