Repository OpenLiberty/open-liberty, pull requests merged in 2021-05, with the labels that each got.

#16995 Revert "Keep separate track of prime (root) feature conflicts"
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverTest.java
  dev/com.ibm.ws.kernel.feature/test/resolverData/lib/features/t7.p-2.0.mf
Labels: CLA Signed

#16829 Issue16810-FixCodeBaseNormalization
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed, release bug

#16808 Issue16807 support new java policy location per open jdk 9
  .github/test-categories/JDBC
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed, release bug

#16824 Add code to create /lib/extract/ folder if not installed
  dev/wlp.lib.extract_fat/build.gradle
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#16840 clean up jaxrs test by removing unused SSL context that can be confusing
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/complexclient/src/com/ibm/ws/jaxrs20/client/ComplexClientTest/client/ClientTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#16814 upgrade the version of mockserver and enable validation in the JaxRS ProxyAuth Tests
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClient100ContinueTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLProxyAuthTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.ProxyAuthTest/resources/security/trust.jks
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17010 Remove debug statements from SoapActionInInterceptor
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
Labels: CLA Signed

#17011 Revert "Issue16807 support new java policy location per open jdk 9"
  .github/test-categories/JDBC
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed

#16974 Add wsoc tracing to basicTestServer
  dev/io.openliberty.wsoc.internal_fat/publish/servers/basicTestServer/server.xml
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#16949 Ignore FFDC CloneNotSupportedException
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/BasicAuthCacheKeyProvider.java
Labels: CLA Signed

#16345 Issue 15722: Update Kerberos for LDAP from beta to GA
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConnection.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/CommonBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/Krb5ConfigJVMProp.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/RealmNameJVMProp.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/jvm.options
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
Labels: CLA Signed, team:Core Security, team:Wendigo East

#16783 Bump libthrift to 0.14.1 in the MP OT bundles
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/build.gradle
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/opentracing/internal/jaeger_fat/JaegerConfigTest.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/opentracing/internal/jaeger_fat/JaegerTraceTest.java
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServer1/server.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServerInventory/server.xml
  dev/io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat/publish/servers/jaegerServerSystem/server.xml
Labels: CLA Signed

#16842 Add --illegal-access=permit for JDBC Kerberos FAT for Java 16
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/ErrorPathTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/PostgresKerberosTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#17032 Remove JSON4J from EE9 RestfulWS feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
Labels: CLA Signed

#17014 Increase async timetout to accommodate network latency in TestAsync
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/LibertyReadWriteListenerTest.war/src/com/ibm/ws/webcontainer/servlet_31_fat/libertyreadwritelistenertest/war/readListener/TestAsyncReadServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17030 Disabling tests that intermittently fail on Windows when running with…
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleNoExpandTest.java
Labels: CLA Signed, noproductcode

#17016 Revert "Revert "Issue16807 support new java policy location per open jdk 9""
  .github/test-categories/JDBC
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/ParseJavaPolicy.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed, release bug

#17033 Fix test failure for RTC 282681. The test was calling the SSL endpoin…
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/AutoApplySessionTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#17036 more client config updates
  dev/com.ibm.ws.security.client_fat/publish/clients/ProgrammaticLoginTestClient/configs/client_appWithCallbackHandler_badPwd.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_aesPassword.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_with_ibm_ciphersuite.xml
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/configs/client_with_nonIBM_ciphersuite.xml
Labels: CLA Signed, noproductcode

#17038 Address Illegal Access issues on Java 16
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingEventTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMbeanTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/add-exports/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/illegalAccess/jvm.options
Labels: CLA Signed, noproductcode

#17039 Use final release version of MP Metrics 1.1.4 and 2.0.5
  dev/com.ibm.ws.microprofile.metrics.1.1.noAuth_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.metrics.2.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#16786 Retain lease on recovery failure paths
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/FailureScopeController.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#17046 Fix for defect in RTC 283650. The test was not waiting for the config…
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#17015 Fix for test failure in RTC 283253. Update the client certificates so…
  dev/com.ibm.ws.security.registry_test.servlet/test-applications/userRegistry/src/web/UserRegistryServlet.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/LDAPwithDefaultOutboundSSL.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/LDAPwithDynamicOutboundSSL.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter2.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertMultipleLDAP.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1ExtraOID.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1Invalid.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser2.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser5.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_ca.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_root.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/generateCertChain.sh
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/generateCertificates.sh
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/outboundSSL.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ids.ssl.trustonly/old_certs/LdapSSLTrustStore.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ids.ssl/old_certs/LdapSSLKeyStore.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.registry.ldap.fat.ids.ssl/old_certs/LdapSSLTrustStore.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/resources/security/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.bell/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/resources/security/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom.certmapper.feature/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.outbound.ssl/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/oldcerts/key.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.ssl/oldcerts/trust.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/resources/security/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin_SBInFilter/resources/security/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin_SBInFilter/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.certlogin_SBInFilter/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/resources/security/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/resources/security/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.fedcertlogin/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.ssl/oldcerts/LdapSSLKeyStore.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.ssl/oldcerts/LdapSSLTrustStore.jks
Labels: CLA Signed, noproductcode, team:Wendigo East

#16987 testScheduleOneTimeTasks checks wrong value
  dev/com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#16989 testTimerFailsOverWhenServerStops timer rolls back during shutdown
  dev/com.ibm.ws.concurrent.persistent_fat_failovertimers/fat/src/com/ibm/ws/concurrent/persistent/fat/failovertimers/FailoverTimersTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#17049 Update helper class formatting prior to adding embedded mongoDB
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MongoDBUtils.java
  dev/com.ibm.ws.security.oauth_test.custom_servlets/test-applications/oAuth20MongoSetup/src/web/oAuth20MongoSetup.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#17052 Fix throughput performance problem in new cxf version
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed, performance, team:Performance

#17051 Issue 17050: Updates for Ldap Kerberos Tests
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/SimpleBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#17045 Avoid network related test failure
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AutoExtractTest.java
Labels: CLA Signed, noproductcode

#16798 Issue #16797: Remove SharedServer from CDINoInjectionTests
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDINoInjectionTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17042 Repeat calls to receiveBodyNoWait in JMSProducerServlet
  dev/com.ibm.ws.messaging.open_jms20_fat/test-applications/JMSProducer/src/jmsproducer/web/JMSProducerServlet.java
Labels: CLA Signed, noproductcode

#17064 Add new featureManager attr package.server.conflict
  dev/build.image/build.gradle
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#15897 Create Shared Bundle Between JSF-2.3 & Faces-3.0
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/javax.faces.application.ApplicationFactory
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/org.apache.myfaces.config.annotation.LifecycleProvider
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/org.apache.myfaces.config.annotation.LifecycleProviderFactory
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/org.apache.myfaces.spi.AnnotationProvider
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/org.apache.myfaces.spi.FaceletConfigResourceProvider
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/META-INF/services/org.apache.myfaces.spi.InjectionProvider
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/cdi/WASCDIAnnotationInjectionProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/WASApplicationFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/WASApplicationImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/WASJSFConfig.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/annotation/WASMyFacesAnnotationProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/annotation/WebSphereAnnotationLifecycleProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/annotation/WebSphereLifecycleProviderFactory.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/annotation/package-info.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/package-info.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/resource/LibertyFaceletConfigResourceProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/config/resource/package-info.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/ee/WASMyFacesContainerInitializer.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/extprocessor/JSFExtensionFactory.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/extprocessor/package-info.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/spi/impl/WASCDIAnnotationDelegateInjectionProvider.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/spi/impl/package-info.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/taglibconfig/JSFGlobalTagLibConfig.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/com/ibm/ws/jsf/taglibconfig/package-info.java
  dev/io.openliberty.faces.internal/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-faces-initialization.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, in:Web Components, team:Sirius

#17062 Test container support updates for EJB-in-WAR JPA FAT.
  dev/com.ibm.ws.jpa.tests.spec10.injection.common/publish/servers/JPAServer/server.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/ejb_in_war/EjbInWar_Test.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/ejb_in_war/FATSuite.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/publish/servers/JPAServer/server.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/helpers/DatabaseManagement/src/jpahelper/databasemanagement/DatabaseManagementServlet.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DFI_EIW.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DFI_EIW.war/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DFI_EIW.war/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DMI_EIW.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DMI_EIW.war/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/DMI_EIW.war/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/JNDI_EIW.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/JNDI_EIW.war/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/JNDI_EIW.war/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/META-INF/permissions.xml
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/test-applications/injection_ejbinwar/libs/jpapulib.jar/META-INF/persistence.xml
Labels: CLA Signed, in:JPA, team:Blizzard

#17083 Adding separate EE9 api/api bundle projects
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.globalhandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/com.ibm.websphere.appserver.jwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/oauth-2.0/com.ibm.websphere.appserver.oauth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.0/com.ibm.websphere.appserver.passwordUtilities-1.0.feature
Labels: CLA Signed

#16973 Issue #16743: Update MyFaces 2.3 to 2.3.9
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/io.openliberty.faces.internal/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#17076 changed service to type in java doc
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/jca/cm/mbean/ConnectionManagerMBean.java
Labels: CLA Signed, team:Zombie Apocalypse

#17079 Issue #17078 : Update loose package to skip on zos due to zip/pax
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseContentsTest.java
Labels: CLA Signed, noproductcode

#17077 Add debug information
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
Labels: CLA Signed

#17065 Correcting IBM JDK LoginModule behavior plus minor fixes
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
  dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java
Labels: CLA Signed

#17086 Remove jakarta generated api bundle from feature definitions
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.globalhandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/com.ibm.websphere.appserver.jwt-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/oauth-2.0/com.ibm.websphere.appserver.oauth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.0/com.ibm.websphere.appserver.passwordUtilities-1.0.feature
Labels: CLA Signed

#17106 Add SkipForRepeat(EE9_FEATURES) for intermittent EE9 only failing tests
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientJerseyRxInvokerTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17125 Add EJB client tests with escape in JNDI
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/RemoteClientWeb.war/src/com/ibm/ws/ejbcontainer/remote/client/web/RemoteTxAttrServlet.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#17109 Fix test failures in RTC 283807.
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleDBRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleNoExpandTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
Labels: CLA Signed, noproductcode

#17104 Issue 17103: Ignore CWWKG0027W config update on DynamicUpdateTest
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/DynamicUpdateTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#17120 Add HttpTransport=all to WSOC Servers & Some Debug Lines
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/endpoints/client/basic/ProgrammaticClientEP.java
  dev/io.openliberty.wsoc.internal_fat/publish/servers/basicTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/cdi12TestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/secureTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/src/cdi/war/ProgrammaticExtendCDIServerCDI12EP.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17124 Adjust error text.
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/util/WSUtil.java
Labels: CLA Signed

#17095 grpc_fat: correctly wait for channel termination
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcTestUtils.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceInterceptorTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceSupportTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StreamingTests.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#17113 Tolerate CWWKN0005W
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
Labels: CLA Signed, noproductcode

#17070 Add some SkipForRepeats
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicCoreTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicCoreTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
Labels: CLA Signed, noproductcode

#17122 Issue 17121: Fix primary and failover LDAP host groupings on FATs
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertComplexFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter1.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertInvalidFilter2.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertMultipleLDAP.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_invalidSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_multipleSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/dynamicUpdate/server_validSearchBase.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertComplexFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertExactDN.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertInvalidFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientCertNonMatchingFilter.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/fedclientcert.server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/reuseConnectionOn.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.custom/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.attrMappingVar1/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.attrMappingVar2/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.attrMappingVar3/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.tds.failover/server.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/master_server.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_multiple_realms.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_multiple_under_realm.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_single_under_realm.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/with_UR_mapping.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/without_primary_realm.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#17057 Update SR reactive streams operators to 1.0.13
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.io.smallrye.reactive.streams-operators/bnd.bnd
Labels: CLA Signed

#17044 Plugin generator should better handle bad bundle states
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: CLA Signed, in:Web Components, team:Sirius

#17139 Fix for RTC 283750 test failure. The keystores were not previously ge…
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/DummyServerKeyFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/DummyServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1ExtraOID.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser1Invalid.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser2.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser3.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/LDAPUser5.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_ca.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/chain_root.pem
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/files/clientcert/generateCertificates.sh
Labels: CLA Signed, noproductcode, team:Wendigo East

#17088 For defect in RTC 283686 make updates that were made in WS-CD-Open af…
  dev/com.ibm.ws.security.social_fat.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/CommonTests/SameSiteTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_BasicConfigTests_oidc_usingSocialConfig.java
  dev/com.ibm.ws.security.social_fat.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_BasicTests_oidc_usingSocialDiscoveryConfig.java
  dev/com.ibm.ws.security.social_fat.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_ErrorConfigTests_oidc_usingSocialDiscoveryConfig.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#17118 Isolate SSL testing from non SSL tests
  .github/test-categories/JDBC
  .github/workflow-scripts/run-fat-build.sh
  dev/com.ibm.ws.jdbc_fat_sqlserver/build.gradle
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerSSLTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/release.sh
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver.ssl/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver.ssl/jvm.options
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver.ssl/security/truststore.p12
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver.ssl/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/ssl/SQLServerTestSSLServlet.java
Labels: CLA Signed, GitHub Build, noproductcode, team:Zombie Apocalypse

#17138 Allow more completion replays
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATRecovery2/server.xml
Labels: CLA Signed, noproductcode

#17148 Revert "Adjust error text."
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/util/WSUtil.java
Labels: CLA Signed

#16155 Update FeatureList for Java 16
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#16775 Issue 16604: Swap CustomStoreSample to embedded MongoDB
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.oauth.oidc_fat.common/bnd.bnd
  dev/com.ibm.ws.security.oauth.oidc_fat.common/build.gradle
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTest.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MongoDBUtils.java
  dev/com.ibm.ws.security.oauth_fat/bnd.bnd
  dev/com.ibm.ws.security.oauth_fat/build.gradle
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20TestCommon.java
  dev/com.ibm.ws.security.oauth_test.custom_servlets/test-applications/oAuth20MongoSetup/src/web/oAuth20MongoSetup.java
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
Labels: CLA Signed, team:Security SSO, team:Wendigo East

#17119 in-memory task list out of sync after commit error
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
Labels: CLA Signed, release bug, team:Zombie Apocalypse

#17156 Add new tests to JAXRS21ClientCompletionStageRxInvokerTest to verify timeout property precedence
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCompletionStageRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CompletionStageRxInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17154 Issue 17142: Reduce connectTimeout in DynamicUpdateTest
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/master_server.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_multiple_realms.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_multiple_under_realm.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/multiple_ldaps_and_single_under_realm.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/with_UR_mapping.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/files/dynamicUpdate/without_primary_realm.xml
  dev/com.ibm.ws.security.wim.core_fat/publish/servers/com.ibm.ws.security.wim.core.fat.dynamic/server.xml
Labels: CLA Signed, noproductcode, team:Wendigo East

#17146 Issue #17145: The bnd.bnd file in com.ibm.ws.security.social_fat.Libe…
  dev/com.ibm.ws.security.social_fat.LibertyOP/bnd.bnd
Labels: CLA Signed, noproductcode, team:Wendigo East

#17153 Synchronize start action callback methods
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
Labels: CLA Signed

#15524 adding json generation support
  dev/com.ibm.ws.install.featureUtility/resources/com/ibm/ws/install/featureUtility/internal/resources/FeatureUtilityToolOptions.nlsprops
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallFeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallServerAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#17111 Update to use reactive streams 1.0.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.reactivestreams.reactive-streams-1.0.feature
  dev/com.ibm.websphere.org.eclipse.microprofile/reactive.streams.operators.1.0.bnd
  dev/com.ibm.websphere.org.reactivestreams.reactive-streams.1.0/bnd.bnd
  dev/com.ibm.ws.io.reactivex.rxjava.2.2/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_git_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.reactive.streams.operators.cdi/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/test-applications/ReactiveStreamsTest/src/com/ibm/ws/microprofile/reactive/streams/test/basic/ReactiveStreamsTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/build.gradle
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/bnd.bnd
  dev/com.ibm.ws.org.reactivestreams.reactive-streams.1.0/.classpath
  dev/com.ibm.ws.org.reactivestreams.reactive-streams.1.0/.project
  dev/com.ibm.ws.org.reactivestreams.reactive-streams.1.0/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.reactivestreams.reactive-streams.1.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.reactivestreams.reactive-streams.1.0/bnd.bnd
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/bnd.bnd
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, GitHub Build, team:Performance

#17172 Fix up io.openliberty.org.testcontainers component
  dev/com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat/bnd.bnd
  dev/io.openliberty.org.testcontainers/.classpath
  dev/io.openliberty.org.testcontainers/.settings/bndtools.core.prefs
  dev/io.openliberty.org.testcontainers/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.testcontainers/bnd.bnd
Labels: CLA Signed, team:Performance

#16752 Delete old commons logging and codec projects
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.classpath
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.gitignore
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.project
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.3/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.3/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.classpath
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.gitignore
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.project
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.4/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.codec.1.4/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.codec.1.4/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.codec/.classpath
  dev/com.ibm.ws.org.apache.commons.codec/.gitignore
  dev/com.ibm.ws.org.apache.commons.codec/.project
  dev/com.ibm.ws.org.apache.commons.codec/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.codec/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.codec/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.codec/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.codec/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.logging/.classpath
  dev/com.ibm.ws.org.apache.commons.logging/.gitignore
  dev/com.ibm.ws.org.apache.commons.logging/.project
  dev/com.ibm.ws.org.apache.commons.logging/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.logging/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.logging/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.logging/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.logging/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.logging/resources/META-INF/LICENSE.txt
  dev/com.ibm.ws.org.apache.commons.logging/src/org/apache/commons/logging/Log.java
  dev/com.ibm.ws.org.apache.commons.logging/src/org/apache/commons/logging/LogConfigurationException.java
  dev/com.ibm.ws.org.apache.commons.logging/src/org/apache/commons/logging/LogFactory.java
  dev/com.ibm.ws.org.apache.commons.logging/src/org/apache/commons/logging/LogSource.java
  dev/com.ibm.ws.org.apache.commons.logging/src/org/apache/commons/logging/impl/Jdk14Logger.java
Labels: CLA Signed

#17168 Update grpc_fat trace
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcClientOnly/bootstrap.properties
  dev/com.ibm.ws.grpc_fat/publish/servers/GrpcServerOnly/bootstrap.properties
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#17084 update jaxrs proxy auth fat tests to use bouncy castle so mockserver …
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLProxyAuthTest.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17082 add a doPrivs to org.jboss.resteasy.spi.config.DefaultConfiguration
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17189 Remove extra copyright
  dev/io.openliberty.ws.global.handler.internal_fat/test-applications/rs20ApplicationWithClient/src/com/ibm/samples/jaxrs/HelloRest20ClientServlet.java
Labels: CLA Signed, noproductcode, team:Performance

#17073 Adjusting default to max amount of requests on persist connections
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
Labels: CLA Signed, in:Transport, team:Sirius

#16624 Ensure JAX-RS JsonPProvider can work in Java SE environment
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonPProvider.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs21/providers/json/JavaSEJsonPProviderTest.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17184 Issue 16642: Jakartaize WIM Base, which depends on JAXB.
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wimcore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wimcore.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wimcore.internal.ee-9.0.feature
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.ws.security.wim.core_fat/bnd.bnd
  dev/com.ibm.ws.security.wim.core_fat/build.gradle
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/DynamicUpdateTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/InvalidBaseEntryInRealmTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/MaxSearchResultTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/NoRegistryConfiguredTest.java
  dev/com.ibm.ws.security.wim.core_fat/fat/src/com/ibm/ws/security/wim/core/fat/WimCoreRegressionTest.java
  dev/wlp-jakartaee-transform/rules/jakarta-bundles.properties
Labels: CLA Signed, team:Wendigo East

#16804 Orb init race
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
  dev/com.ibm.ws.transport.iiop/.classpath
  dev/com.ibm.ws.transport.iiop/bnd.bnd
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/AcidReference.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/ORBWrapper.java
  dev/com.ibm.ws.transport.iiop/test/com/ibm/ws/transport/iiop/internal/AcidReferenceTest.java
Labels: CLA Signed

#17183 Use a longer timeout
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/current/CDICurrentTestServlet.java
Labels: CLA Signed, noproductcode

#17200 Issue 17199: Add retry on token create for CustomStoreSample
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
Labels: CLA Signed, noproductcode, team:Security SSO

#17193 Issue 17188: Add test features for bnd on SPNEGO fat
  dev/com.ibm.ws.security.spnego_fat.1/bnd.bnd
Labels: CLA Signed, noproductcode, team:Core Security

#17198 Issue 17197: Update granttypes test for CustomStore permissions
  dev/com.ibm.ws.security.oidc.server_fat/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat/configs/server_grantTypesCustomStore.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat/configs/server_grantTypesCustomStoreBell.xml
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#17192 Add new tests to JAXRS21ClientCXFRxInvokerTest to verify timeout properties
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientCXFRxInvokerTest.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CXFRxInvokerTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17159 Enable default SSL configuration if none is selected by user
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLDefaultTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLFiltersTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLTestNoLibertySSLCfg.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLTestNoLibertySSLFeature.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/jaxrsclientssl/src/com/ibm/ws/jaxrs20/client/JAXRSClientSSL/client/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLTest.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/PatchTest.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/ssl/SslTestServlet.java
  dev/io.openliberty.restfulWS.internal.ssl/src/io/openliberty/restfulWS/internal/ssl/component/SslClientBuilderListener.java
Labels: CLA Signed, GitHub Build, in:JAX-RS, team:Wendigo West

#17158 Adjust error text.
  dev/com.ibm.ws.container.service.compat/src/com/ibm/ws/util/WSUtil.java
  dev/com.ibm.ws.container.service/test/com/ibm/ws/util/WSUtilTest.java
Labels: CLA Signed

#17206 Issue 17205: Skip bad DNS on SUSE ACME FAT
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#17151 Exclude unreliable mpConfig TCK tests
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/io.openliberty.microprofile.config.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, in:MicroProfile/Config, noproductcode

#16751 Update non Jakarta 9 features to have eeCompatible
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wimcore-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonp-1.0/com.ibm.websphere.appserver.jsonp-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-1.5/com.ibm.websphere.appserver.springBoot-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-2.0/com.ibm.websphere.appserver.springBoot-2.0.feature
Labels: CLA Signed, jakartaEE, team:Performance

#17194 Use Logger to allow expected warnings to be suppressed
  dev/io.openliberty.org.jboss.resteasy.validator.provider/src/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
Labels: CLA Signed, performance, team:Performance

#17208 Increase wait time in testMemoryLeak_ClientStandalone for slow test systems
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/jaxrsclientstandalone/src/com/ibm/ws/jaxrs20/client/JAXRSClientStandalone/client/ClientTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17217 Fix ConcurrentModificationException in ConfigImpl when iterating over System.getProperties().keySet()
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigImpl.java
Labels: CLA Signed

#17207 omit unused Informix property
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/DatabaseHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#17211 Only run original and latest MP versions in LITE mode; all else in FULL
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#17164 Issue #16440: Update ExpressionLanguage 4.0 API/Impl to 10.0.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-4.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.jakarta.expressionLanguage.4.0/src/jakarta/el/ExpressionFactory.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/src/org/apache/el/ExpressionFactoryImpl.java
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#16518 enable allowqueryparamwithnoequal by default in JAX-RS 3.0
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.beanparam/server.xml
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanparam/src/com/ibm/ws/jaxrs/fat/beanparam/BeanParamEntity.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanparam/src/com/ibm/ws/jaxrs/fat/beanparam/ClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanparam/src/com/ibm/ws/jaxrs/fat/beanparam/InnerBeanParamEntity.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/beanparam/src/com/ibm/ws/jaxrs/fat/beanparam/TestResource.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/FormParamInjector.java
Labels: CLA Signed

#17191 17150 Add endpoint icons to minified server content
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/SubsystemFeatureDefinitionImpl.java
Labels: CLA Signed

#16746 PR for Issue 15023: Fix WASReqURLOidc encoding problem
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
Labels: CLA Signed, team:Security SSO

#17222 Repeat calls to receiveNoWait in JMSContextServlet
  dev/com.ibm.ws.messaging.open_jms20_fat/test-applications/JMSProducer/src/jmsproducer/web/JMSProducerServlet.java
  dev/com.ibm.ws.messaging.open_jms20context_fat/test-applications/JMSTemporaryQueue/src/jmstemporaryqueue/web/JMSContextServlet.java
Labels: CLA Signed, noproductcode

#17227 Issue #16743: Update maven coordinates in api feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jsf-2.3.feature
Labels: CLA Signed, in:Web Components, team:Sirius

#17245 Trace com.ibm.ws.messaging.open_clientcontainer.fat.JMS2AsyncSend.tes…
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSend.java
Labels: CLA Signed, noproductcode

#16615 Issue #16614: add src directory to classpath
  dev/io.openliberty.jakarta.pages.3.0/.classpath
Labels: CLA Signed, in:Web Components, jakartaEE, noproductcode, team:Sirius

#17234 Adding SAN entry with hostname to default certificates
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
Labels: CLA Signed

#17212 Skip SQLServer secure ssl test on z/os
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/ssl/SQLServerTestSSLServlet.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseContentsTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseRunnableTest.java
  dev/fattest.simplicity/src/componenttest/annotation/SkipIfSysProp.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#17107 Issue17105-AddProperRetryLogicForSigningAudit
  dev/com.ibm.ws.security.audit.file/src/com/ibm/ws/security/audit/file/AuditFileHandler.java
Labels: CLA Signed

#16612 Move beta flag setting earlier in bootstrap
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/BootstrapConfig.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/location/internal/Activator.java
Labels: CLA Signed

#17247 Trace com.ibm.ws.messaging.open_clientcontainer.fat.JMS1AsyncSend.tes…
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS1AsyncSend.java
Labels: CLA Signed, noproductcode

#17248 Increase wait time in JAXRS21TimeoutClientTest for slow Windows test systems
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21clienttimeout/src/com/ibm/ws/jaxrs21/client/jaxrs21clienttimeout/client/JAXRS21ClientTestServlet.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17260 remove mock DataStoreHelper interfaces
  dev/com.ibm.ws.jdbc/bnd.bnd
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/DataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/GenericDataStoreHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/heritage/package-info.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageDriver/src/test/jdbc/heritage/driver/helper/HDDataStoreHelperMetaData.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/GenericDataStoreHelper.java
Labels: CLA Signed, team:Zombie Apocalypse

#17261 simplicity objects for identifyException config
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DataSource.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HeritageSettings.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/IdentifyException.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#17231 update cxf core bundle to import saaj14 classes
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.overrides
Labels: CLA Signed, noproductcode

#17265 Add new project to actions files and organize
  .github/test-categories/SECURITY_3
  .github/test-categories/SECURITY_5
  .github/test-categories/SECURITY_OIDC_1
  .github/test-categories/SECURITY_SOCIAL_1
Labels: CLA Signed, GitHub Build, noproductcode, team:Security SSO, test delivery

#17262 Stage 1 of refactoring ApacheDSandKDC, move out variables
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/ApacheDSandKDC.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/LdapApacheDSandKDC.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/TicketCacheBindLongRunTest.java
Labels: CLA Signed, noproductcode

#17266 Add 21.0.0.6 Notices
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#17171 Fix multi-database test failures in `com.ibm.ws.jpa_eclipselink_fat`
  dev/com.ibm.ws.jpa_eclipselink_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/common/src/com/ibm/ws/jpa/query/sqlcapture/SQLListener.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/common/src/com/ibm/ws/jpa/query/sqlcapture/eclipselink/ECLSessionCustomizer.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_HSQL.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_INFORMIX.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_ORACLE.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_CREATE_SYBASE.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_DB2.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_HSQL.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_INFORMIX.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_MYSQL.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_SQLSERVER.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/ddl/WEB-INF/classes/JPA_OLGH16588_DROP_SYBASE.ddl
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/src/com/ibm/ws/jpa/olgh16588/testlogic/JPATestOLGH16588Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16772/src/com/ibm/ws/jpa/olgh16772/testlogic/JPATestOLGH16772Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
Labels: CLA Signed, in:JPA, noproductcode, team:Blizzard, test bug

#17272 warning during config update in DelayExecutionFATTest
  dev/com.ibm.ws.concurrent.persistent_fat_delayexec/fat/src/com/ibm/ws/concurrent/persistent/delayexec/DelayExecutionFATTest.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#17270 Clean up jakarta jaxb API and impl bundles
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlBinding-3.0.feature
  dev/io.openliberty.jakarta.xmlBinding.3.0/.classpath
  dev/io.openliberty.jakarta.xmlBinding.3.0/bnd.bnd
  dev/io.openliberty.jakarta.xmlBinding.3.0/src/jakarta/xml/bind/ModuleUtil.java
  dev/io.openliberty.xmlBinding.3.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools/bnd.bnd
Labels: CLA Signed, team:Performance

#17288 Fix source directories in eclipse settings files
  dev/com.ibm.ws.cdi.extension_fat/.classpath
  dev/com.ibm.ws.cdi.extension_fat/test-applications/SPIExtension.war/src/com/ibm/ws/cdi/extension/spi/test/app/MissPlacedBean.java
  dev/com.ibm.ws.cdi.extension_fat/test-applications/SPIExtension.war/src/com/ibm/ws/cdi/extension/spi/test/app/OuterBean.java
  dev/com.ibm.ws.cdi.extension_fat/test-applications/SPIExtension.war/src/com/ibm/ws/cdi/extension/spi/test/app/WellPlacedBean.java
  dev/com.ibm.ws.org.apache.cxf.rt.security.3.4.1/.classpath
  dev/com.ibm.ws.org.apache.wss4j.ws.security.dom.2.3.0/.classpath
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/.classpath
  dev/io.openliberty.jakarta.cdi.3.0/.classpath
Labels: CLA Signed, noproductcode

#17144 Use different message to detect success
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/com/ibm/ws/wsat/fat/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi/fat/src/com/ibm/ws/wsat/fat/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.single/fat/src/com/ibm/ws/wsat/fat/SingleRecoveryTest.java
Labels: CLA Signed, noproductcode

#17281 spnego fat temporary quarentine to refactor
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/DynamicSpnegoConfigTest.java
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/S4U2ProxyTest.java
  dev/com.ibm.ws.security.spnego_fat.2/fat/src/com/ibm/ws/security/spnego/fat/AuthFilterElementTest.java
  dev/com.ibm.ws.security.spnego_fat.2/fat/src/com/ibm/ws/security/spnego/fat/DynamicAuthFilterTest.java
  dev/com.ibm.ws.security.spnego_fat.2/fat/src/com/ibm/ws/security/spnego/fat/InvokeAfterSSOTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/BasicAuthTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/CanonicalHostNameTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/IncludeClientGSSCredentialInSubjectTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/IncludeCustomCacheKeyTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/Krb5ConfigTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/ServicePrincipalNamesTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/SpnegoTokenHelperApiTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/TrustedActiveDirectoryDomainsTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#16954 create new tests for parm handling with isClientSideRedirectSupported equals false
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientWasReqURLTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test delivery

#17236 Issue 17230: Add back remote mongoDB for all
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTest.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MongoDBUtils.java
  dev/com.ibm.ws.security.oauth_fat/bnd.bnd
  dev/com.ibm.ws.security.oauth_fat/build.gradle
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20TestCommon.java
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore.bell.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore.xor.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore2.bell.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore2.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore3.bell.fat/server.xml
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.customstore3.fat/server.xml
  dev/com.ibm.ws.security.oauth_test.custom_servlets/test-applications/oAuth20MongoSetup/src/web/oAuth20MongoSetup.java
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#17269 17268-PH37460-useJandex-autoExpand
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfoFactoryImpl.java
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/war/internal/WARDeployedAppInfoFactoryImpl.java
Labels: CLA Signed

#17127 added NPE checks to SessionGet and SessionPut
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTwoServerTimeoutTest.java
Labels: CLA Signed, noproductcode

#13683 added allowSerializedAccess, maxWaitTime and accessOnTimeout to metatype.properties
  dev/com.ibm.ws.session/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired

#17140 added session null pointer check
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/SessionCacheTimeoutTest.java
Labels: CLA Signed, noproductcode

#17258 http2_fat: remove unnecessary commons dependencies
  dev/com.ibm.ws.transport.http2_fat/build.gradle
Labels: CLA Signed, noproductcode, test bug

#17267 recreate datastorehelper when identifyException changes
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc_fat_v41/build.gradle
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/ErrorMappingConfigUpdateTest.java
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41.errorMapConfigUpdate/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41.errorMapConfigUpdate/server.xml
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/errorMappingApp/src/jdbc/fat/v41/errormap/web/ErrorMappingTestServlet.java
Labels: CLA Signed, team:Zombie Apocalypse

#17209 skip HttpInputStreamImpl buffer retrieval in closed state
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/AsyncReadCallback.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/srt/SRTInputStream31.java
Labels: CLA Signed, in:Web Components, team:Sirius

#17256 Remove Beta Guards, and remove FAT start up check that is after the server start
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MappingTable.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/add-exports/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureServer/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithEventFeature/jvm.options
  dev/com.ibm.ws.request.timing.monitor_fat/publish/servers/RequestTimingFeatureWithMetrics/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
Labels: CLA Signed

#17259 SQLServer reset transaction timeout
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#16847 Make the JAX-RS 3.0 file upload in-memory threshold configurable
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17284 Add trace for EJB timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/publish/servers/com.ibm.ws.ejbcontainer.timer.persistent.fat.PersistentTimerRestartServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/publish/servers/com.ibm.ws.ejbcontainer.timer.persistent.fat.PersistentTimerServer/bootstrap.properties
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#17302 add aha, link to backlog, socialization req
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed

#17264 close connections in testDurableSubscriberWithoutClientID
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/fat/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientIDTest.java
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/ClientIDClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/ClientID.java
Labels: CLA Signed, noproductcode

#17301 add channelfw trace for springboot.support_fat testBlockingIOServlet40
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebFluxTests20Servlet40.java
Labels: CLA Signed, noproductcode, test bug

#17257 Add code to create manifest in PackageRunnable test
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed, noproductcode

#17185 Coordinate TX Startup with DataSource Factory Setting
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#17303 Ensure context root has leading slash
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfigurator.java
Labels: CLA Signed, regression, release bug

#17285 ObjectClosedException
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/jdbc/WSJdbcWrapper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/ObjectClosedException.java
Labels: CLA Signed, team:Zombie Apocalypse

#17311 Add "In Progress" label step
  .github/ISSUE_TEMPLATE/feature.md
Labels: CLA Signed

#17306 Issue #17286 : change skip logic for zos where test cannot run
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageLooseContentsTest.java
Labels: CLA Signed, noproductcode

#17324 Revert "better align the JDBC heritage interop test bucket"
  dev/com.ibm.ws.jdbc_fat_heritageinterop/.classpath
  dev/com.ibm.ws.jdbc_fat_heritageinterop/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/build.gradle
  dev/com.ibm.ws.jdbc_fat_heritageinterop/fat/src/test/jdbc/heritage/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/jdbcHeritage.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/jdbcHeritageApi.bnd
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/files/features/jdbcHeritage-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritageinterop/publish/files/internalFeatures/dataStoreHelper-1.0.mf
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-applications/heritageApp/src/test/jdbc/heritage/app/JDBCHeritageTestServlet.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/appprofile/accessintent/AccessIntent.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/appprofile/accessintent/package-info.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/DuplicateKeyException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/PortableSQLException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/StaleConnectionException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/StaleStatementException.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/ce/cm/package-info.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/GenericDataStoreHelper.java
  dev/com.ibm.ws.jdbc_fat_heritageinterop/test-bundles/jdbcHeritage/src/com/ibm/websphere/rsadapter/package-info.java
Labels: CLA Signed, noproductcode

#17316 add escape characters so '+' can appear in doc
  dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/classloader.properties
Labels: CLA Signed

#17251 Issue 12778: Fix JWK cache issue in JwKRetriever
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/JwtConstants.java
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/actions/JwtTokenActions.java
  dev/com.ibm.ws.security.fat.common.mp.jwt/fat/src/com/ibm/ws/security/fat/common/mp/jwt/sharedTests/MPJwtMPConfigTests.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/fat/src/com/ibm/ws/security/mp/jwt11/fat/MPJwtJwkTokenCacheTests.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat.builder/configs/server_jwkCacheTests_1.xml
  dev/com.ibm.ws.security.mp.jwt.1.1_fat/publish/servers/com.ibm.ws.security.mp.jwt.1.1.fat.builder/configs/server_jwkCacheTests_2.xml
Labels: CLA Signed, team:Security SSO

#17292 Issue #17291: Beta Jakarta EE9 support for WIM / federated repositories.
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wimcore.internal.ee-9.0.feature
Labels: CLA Signed, team:Wendigo East

#17309 Issue17308-FixConcurrentModificationJ2Sec
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/java2sec/PermissionManager.java
Labels: CLA Signed, release bug

#17315 http2_fat secure h2 client is not closing connections correctly
  dev/com.ibm.ws.transport.http2_fat/fat/src/com/ibm/ws/http2/client/SecureHttp2Client.java
Labels: CLA Signed, in:Transport, noproductcode, team:Sirius, test bug

#17307 Skip SQLServer SSL Secure test on IBM JDK
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerSSLTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/ssl/SQLServerTestSSLServlet.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse, test bug

#17290 Modify trace & timeouts
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinator.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinatorTran.java
  dev/com.ibm.ws.wsat.migration_fat.1/test-applications/simpleClient/src/com/ibm/ws/wsat/simpleclient/client/simple/SimpleClientServlet.java
Labels: CLA Signed

#17275 Update com.ibm.websphere.appserver.jwt-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/jwt-1.0/resources/l10n/com.ibm.websphere.appserver.jwt-1.0.properties
Labels: CLA Signed, ID reviewed
