Repository OpenLiberty/open-liberty, pull requests merged in 2021-12, with the labels that each got.

#19523 Update range of io.grpc versions for EE9
  dev/io.openliberty.grpc.1.0.internal.client.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
Labels: CLA Signed, release bug

#19517 NullPointerException on abort from transaction timeout
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: team:Zombie Apocalypse, CLA Signed

#19518 Code is incorrectly expecting Void.class to identify void return type
  dev/io.openliberty.concurrent.cdi/src/io/openliberty/concurrent/cdi/interceptor/AsyncInterceptor.java
Labels: bug, team:Zombie Apocalypse, CLA Signed

#19515 Make tests wait for Discovery to complete and tokenEndpoint app to load
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/DiscoveryUtils.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryBasicTests.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryErrorTests.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryJWTBasicTests.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/IBM/OidcJaxRSClientAPITests.java
Labels: test bug, CLA Signed, team:Security SSO

#19512 Clean up and add trace for acmeCA FATs
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeDisableTriggerSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeRevocationTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19528 Fix up eclipse and github actions for recent changes
  .github/test-categories/MP_JWT_2
  .github/test-categories/MP_METRICS_2
  .github/test-categories/OPENTRACING
  .github/test-categories/QUARANTINE
  .github/test-categories/SECURITY_SOCIAL_1
  .github/test-categories/WEBCONTAINER_2
  dev/com.ibm.ws.javaee.ddmodel.ws/.classpath
  dev/com.ibm.ws.javaee.ddmodel.wsbnd/.classpath
  dev/com.ibm.ws.messaging.common/.classpath
  dev/io.openliberty.accesslists.internal/.classpath
  dev/io.openliberty.accesslists.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.accesslists.internal/.settings/org.eclipse.jdt.core.prefs
Labels: noproductcode, CLA Signed, team:Performance, GitHub Build

#19502 [19501] - add the multi release jar flag to microprofile rest client
  dev/io.openliberty.org.jboss.resteasy.mprestclient/bnd.bnd
Labels: CLA Signed, in:MicroProfile/RestClient

#19440 Don't put processed file paths into errors
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/helpers/FileTransferHelper.java
Labels: CLA Signed, release bug

#19383 [19199] Translate user visible exception message in AsyncResponeImpl
  dev/com.ibm.ws.jaxrs.2.0.common/resources/com/ibm/ws/jaxrs20/internal/resources/JaxRsCommonMessages.nlsprops
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/resources/internal/JAXRS21FrontendMessages.nlsprops
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/AsyncResponseImpl.java
Labels: in:JAX-RS, ID reviewed, CLA Signed, L2 Reviewed

#19091 updates to LdapIdentityStore
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/LdapIdentityStore.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/LdapIdentityStoreDeferredSettingsTest.java
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/JavaEESecAnnotatedBasicAuthServletDeferred.war/src/web/war/annotatedbasic/deferred/LdapSettingsBean.java
Labels: CLA Signed, team:Wendigo East

#19439 Adding properties' files for OT-3.0
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/resources/l10n/io.openliberty.mpOpenTracing-3.0_zh_TW.properties
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#19406 Issue #19405: Reduce the number of server restarts
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCResponseHeadersTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19407 Make sure the release lock request is based on the same authdata that was used for the obtain lock
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/AuthenticationServiceImpl.java
Labels: CLA Signed, performance

#19260 Change variable resolution to variable expansion
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#19353 PR for Issue 16320: Close database connection in OAuth getDBType call
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/db/OAuthJDBCImpl.java
Labels: team:Security SSO

#19543 Update Config and FaultTolerance APIs
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/io.openliberty.microprofile.config.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/config.3.0.bnd
  dev/io.openliberty.org.eclipse.microprofile/faulttolerance.4.0.bnd
Labels: CLA Signed

#19363 Update to GA binaries of MP context propagation 1.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.contextpropagation-1.3.feature
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile/contextpropagation.1.3.bnd.disabled
Labels: team:Zombie Apocalypse

#19507 SRVE0250I and SRVE0164E should be logged regardless of trace
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/DynamicVirtualHost.java
Labels: CLA Signed

#19367 FeatureManager/FeatureUtility set install directory
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallFeatureAction.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallServerAction.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/iFix/com.ibm.websphere.appserver.testIfix-1.0.cs
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/iFix/com.ibm.ws.install.testIfix_1.0.jar
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/iFix/lpmf.lpmf
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/iFix/testIfix-1.0.mf
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/iFix/xml.xml
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/cmdline/ExeInstallAction.java
Labels: CLA Signed

#19544 Update Server Working Dir test cases
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: noproductcode, CLA Signed

#19526 move xtrace to correct file
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/jvm.options
Labels: noproductcode, CLA Signed

#19549 OpenAPI: Cancel listener synchronously
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/OpenAPIModuleListener.java
Labels: CLA Signed

#19548 OpenAPI FAT: Set read timeout
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPIConnection.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPIConnection.java
Labels: noproductcode, CLA Signed

#19550 server.env tests for variable expansion
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerEnvTest.java
Labels: noproductcode, CLA Signed

#19555 Disable test for server.env expansion var enablement
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerEnvTest.java
Labels: noproductcode, CLA Signed

#19539 Transform classes found in shared class cache
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading_test/test/com/ibm/ws/classloading/internal/TransformerTest.java
Labels: CLA Signed, In Progress

#19530 Tolerate a little slow server restart in http_fat: 288001
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/accesslists/Utils.java
Labels: noproductcode, CLA Signed

#18399 Check for HAM/config provider more efficiently
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/BridgeBuilderImpl.java
  dev/com.ibm.ws.security.javaeesec/test/com/ibm/ws/security/javaeesec/BridgeBuilderImplTest.java
Labels: CLA Signed

#19557 Transaction lease logs in DB resilience to DataSource changes
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.cloud_fat.base/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
Labels: CLA Signed

#19556 Removed duplicate msg
  dev/com.ibm.ws.security.authentication.builtin/resources/com/ibm/ws/security/authentication/internal/resources/AuthenticationMessages.nlsprops
Labels: CLA Signed

#19554 Updates for JVM Working Dir edge cases with tests
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: CLA Signed

#19527 273841-remove-jsession-cookie
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/login.jsp
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/toolbox.jsp
Labels: CLA Signed

#19322 Update MP JWT 2.0 to use final version of the API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.jwt-2.0.feature
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/jwt.2.0.bnd
Labels: CLA Signed, team:Security SSO

#19536 Add xerces impl to build path
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.2/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#19572 Reset Server Configs in Transaction HADB Failover tests
  dev/com.ibm.ws.transaction.hadb_fat.derby/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
Labels: noproductcode, CLA Signed

#19568 update to snapshot build from Dec 6
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/io.openliberty.jakarta.concurrency.3.0/bnd.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#19565 test case for asynchronous method join
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/DependentScopedBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19578 Issue #19576: Remove duplicate EJB message
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_cs.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_de.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_es.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_fr.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_hu.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_it.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_ja.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_ko.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_pl.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_pt_BR.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_ro.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_ru.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_zh.nlsprops
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container_zh_TW.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_cs.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_de.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_es.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_fr.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_hu.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_it.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_ja.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_ko.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_pl.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_pt_BR.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_ro.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_ru.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_zh.nlsprops
  dev/com.ibm.ws.ejbcontainer.jpa/resources/com/ibm/ws/ejbcontainer/jpa/resources/EJBJPAMessages_zh_TW.nlsprops
Labels: in:EJB Container, ID review not needed, team:Blizzard, CLA Signed, L2 ReviewNotRequired

#19521 Update WebContainer url-encoded cert test
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTestEncodedX590.java
Labels: noproductcode, CLA Signed

#19537 Enable EE9 Repeat Tests for Remaining gRPC FAT Tests (MicroProfile)
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/FATSuite.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreConsumerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreProducerServletClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesRESTClientTests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesSecurityTests.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointJWTCookieFATServlet.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MappingTable.java
Labels: in:Transport, CLA Signed, team:Sirius

#19570 Update mpOT API from RC4 to final release
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/opentracing.3.0.bnd
Labels: CLA Signed

#19591 Update tests to not run with Java 8 when testing EE 10 features
  dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestAToL.java
  dev/build.featureStart.aToL_fat/publish/files/feature-java-levels.properties
  dev/build.featureStart.mToZ_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestMToZ.java
  dev/build.featureStart.mToZ_fat/publish/files/feature-java-levels.properties
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/FATSuite.java
Labels: noproductcode, CLA Signed, team:Performance, jakartaEE10

#19516 Force prepare of 2PC resources
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction.core_fat.1/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.1/build.gradle
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/ForcePrepareTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/OnePCOptimizationDisabledTest.java
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.1PCOptimizationDisabled/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.1PCOptimizationDisabled/jvm.options
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.1PCOptimizationDisabled/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.forcePrepare/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.forcePrepare/jvm.options
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.forcePrepare/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/test-applications/transaction/src/com/ibm/ws/transaction/web/ForcePrepareServlet.java
  dev/com.ibm.ws.transaction.core_fat.1/test-applications/transaction/src/com/ibm/ws/transaction/web/OnePCOptimizationDisabledServlet.java
  dev/com.ibm.ws.transaction.core_fat.10/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.10/build.gradle
  dev/com.ibm.ws.transaction.core_fat.2/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.2/build.gradle
  dev/com.ibm.ws.transaction.core_fat.3/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.3/build.gradle
  dev/com.ibm.ws.transaction.core_fat.4/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.4/build.gradle
  dev/com.ibm.ws.transaction.core_fat.5/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.5/build.gradle
  dev/com.ibm.ws.transaction.core_fat.6/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.6/build.gradle
  dev/com.ibm.ws.transaction.core_fat.7/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.7/build.gradle
  dev/com.ibm.ws.transaction.core_fat.8/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.8/build.gradle
  dev/com.ibm.ws.transaction.core_fat.9/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.9/build.gradle
  dev/com.ibm.ws.transaction.core_fat.9/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/build.gradle
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#19478 Clarify FATServlet failure messages
  dev/com.ibm.ws.componenttest.2.0/bnd.bnd
  dev/com.ibm.ws.componenttest.2.0/src/componenttest/app/AssertionErrorSerializer.java
  dev/com.ibm.ws.componenttest.2.0/src/componenttest/app/FATServlet.java
  dev/com.ibm.ws.componenttest/bnd.bnd
  dev/com.ibm.ws.componenttest/src/componenttest/app/AssertionErrorSerializer.java
  dev/com.ibm.ws.componenttest/src/componenttest/app/FATServlet.java
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/annotation/processor/TestServletProcessor.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/SyntheticServletTest.java
  dev/fattest.simplicity/src/componenttest/topology/utils/FATServletClient.java
Labels: CLA Signed

#19583 Update to latest Open API 3.0 version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.openapi.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#19552 Initial implementation of MP Rest Client 3.0 / MP Fault Tolerance 4.0
  dev/build.image/scripts/Liberty- server remote debug.launch
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/build.gradle
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/RetryTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/TimeoutTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.retry/server.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/publish/servers/mpRestClientFT.timeout/server.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/InAppConfigSource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/InAppConfigSource.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/TimeoutTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/DefaultMethodInvocationHandler.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/InterceptorInvoker.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyProxyInvocationHandler.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/MPRestClientInvocationContextImpl.java
Labels: team:Wendigo West, in:MicroProfile/RestClient

#19575 JVM Working Dir url and spaces test cases
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: noproductcode, CLA Signed

#19595 Update jsp.2.3_fat comment
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19586 Revert "Serviceability: Print Http header contents "
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/PasswordNullifier.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ServletRequestInfoDebug.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
Labels: CLA Signed

#19364 New Feature: mpGraphQL-2.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.mpGraphQL1.0-metrics2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpGraphQL2.0-appSecurity4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.graphql-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/io.openliberty.mpGraphQL-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/resources/l10n/io.openliberty.mpGraphQL-2.0_zh_TW.properties
  dev/com.ibm.ws.com.graphql.java/bnd.bnd
  dev/com.ibm.ws.io.smallrye.graphql/bnd.bnd
  dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java
  dev/com.ibm.ws.io.smallrye.graphql/src/io/smallrye/graphql/execution/context/SmallRyeContext.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/fat/src/com/ibm/ws/microprofile/graphql/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/rolesAuthApp/src/mpGraphQL10/rolesAuth/RolesAuthTestServlet.java
  dev/com.ibm.ws.microprofile.graphql.authorization/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.metrics.1.0/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql.metrics.1.0/src/com/ibm/ws/microprofile/graphql/metrics/component/MetricsService.java
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/lib/global/.gitkeep
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/.classpath
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/.project
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/FATSuite.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/json-20190722.jar
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/.gitignore
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/graphql/test/ArquillianLoadableExtension.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/io.openliberty.org.eclipse.microprofile/graphql.2.0.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-text.properties
Labels: team:Wendigo West, in:MicroProfile/GraphQL, GitHub Build

#19491 Improve getting all stack traces for Slow RequestTiming
  dev/com.ibm.ws.request.probes/src/com/ibm/wsspi/requestContext/RequestContext.java
Labels: CLA Signed

#19540 branch coupling enablement
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/DSConfig.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/MicrosoftSQLServerHelper.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
Labels: team:Zombie Apocalypse, CLA Signed

#19598 Update string to search for in WS-Security SAML CXF test
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken/OneServerTests/CxfSAMLBasic1ServerTests.java
Labels: noproductcode, CLA Signed, team:Security SSO

#19346 18752 consume access lists bundle
  dev/com.ibm.ws.channelfw/bnd.bnd
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/AccessLists.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ValidateUtils.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/package-info.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/udpchannel/internal/AccessLists.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/udpchannel/internal/UDPChannel.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/udpchannel/internal/package-info.java
  dev/com.ibm.ws.transport.http/bnd.bnd
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCell.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCellFastStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterCellSlowStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterList.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/filter/FilterListSlowStr.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/TrustedHeaderOriginLists.java
  dev/io.openliberty.accesslists.internal/bnd.bnd
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/AccessLists.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterCell.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterCellFastStr.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterCellSlowStr.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterList.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterListFastStr.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/tcpchannel/internal/FilterListStr.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/udpchannel/internal/AccessLists.java
  dev/io.openliberty.accesslists.internal/src/com/ibm/ws/udpchannel/internal/UDPFilterList.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/AccessListKeysFacade.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/AddressAccessLists.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/AddressAndHostNameAccessLists.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterCell.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterCellFastStr.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterCellSlowStr.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterList.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterListFastStr.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterListSlowStr.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/FilterListStr.java
  dev/io.openliberty.accesslists.internal/src/io/openliberty/accesslists/filterlist/package-info.java
  dev/io.openliberty.accesslists.internal/test/io/openliberty/accesslists/internal/test/AccessListsUnitTests.java
  dev/io.openliberty.accesslists.internal/test/io/openliberty/accesslists/internal/test/UnitTestAccessListConfig.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/AccessListHandler.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/AccessLists.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/FilterCellSlowStr.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/FilterListFastStr.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/FilterListSlowStr.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/FilterListStr.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPConfigurationImpl.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/ValidateUtils.java
  dev/io.openliberty.transport.http_fat/bnd.bnd
  dev/io.openliberty.transport.http_fat/publish/files/AccessListsTests_testConfigReplaceSubs_server.xml
  dev/io.openliberty.transport.http_fat/publish/files/AccessListsTests_testConfigReplace_server.xml
Labels: CLA Signed

#19603 mpOpenAPI: Don't scan if scanning is disabled
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/ApplicationProcessor.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/ApplicationProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/ApplicationProcessorServer/bootstrap.properties
Labels: CLA Signed

#19600 Update jandex to 2.4.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.org.jboss.jandex/bnd.bnd
Labels: CLA Signed

#19604 Use class loader of jdbcDriver libraryRef to load custom exceptions and data store helpers
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.java
Labels: bug, team:Zombie Apocalypse, CLA Signed

#19610 Enable user-provided interceptors to work with MP Rest Client 3.0
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/Driver.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/LoggableInterceptor.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/timeoutApp/src/mpRestClientFT/timeout/TimeoutTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java
Labels: CLA Signed, team:Wendigo West, in:MicroProfile/RestClient

#19210 PR for Issue 17649: Remove beta guards for OIDC JWE support
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/config/JwtConfigUtilTest.java
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.opWithStub/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rs/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.jaxrs.opWithStub/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.jaxrs.rp/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.jaxrs.rs/jvm.options
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat.jaxrs.config.RSserver/jvm.options
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelperTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.opWithStub/jvm.options
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/jvm.options
Labels: CLA Signed, team:Security SSO

#19524 Cache config test update
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheErrorPathsTest.java
Labels: noproductcode, CLA Signed

#19574 Delete zip file at end of test
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/DumpArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
Labels: noproductcode, CLA Signed

#19632 Revert "move xtrace to correct file"
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.audit/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mc/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.security.authorization.jacc.dynamic_fat/jvm.options
Labels: noproductcode, CLA Signed

#19645 openapi: cancel module listener job on shutdown
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/OpenAPIModuleListener.java
Labels: CLA Signed

#19634 Fail to load forbidden classes
  dev/com.ibm.ws.classloading/bnd.bnd
  dev/com.ibm.ws.classloading/resources/com/ibm/ws/classloading/internal/forbidden.properties
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
Labels: CLA Signed

#19579 Wait for the restored configuration before stopping the test server
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/CommonTests.java
Labels: noproductcode, CLA Signed

#19656 Fix java2sec issue and test port bugs in MP Rest Client FATs
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/RetryTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/TimeoutTest.java
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/MeterCollection.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/DefaultMethodInvocationHandler.java
Labels: CLA Signed, team:Wendigo West, in:MicroProfile/RestClient

#19561 Switch MicroProfile 5.0 and MP Context Propagation 1.3 to GA
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee9/features.xml
  dev/build.image/profiles/webProfile9/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-mpContextPropagation1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance4.0-metrics.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpMetrics-4.0-monitor-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpOpenTracing3.0-mpRestClient3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWSDefaultExceptionMapper-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jwtSso1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.health-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.jwt-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.metrics-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.opentracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-5.0/io.openliberty.microProfile-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.0/io.openliberty.mpConfig-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/io.openliberty.mpContextPropagation-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-4.0/io.openliberty.mpFaultTolerance-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.0/io.openliberty.mpJwt-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-4.0/io.openliberty.mpMetrics-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-3.0/io.openliberty.mpOpenAPI-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/io.openliberty.mpOpenTracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-3.0/io.openliberty.mpRestClient-3.0.feature
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/.classpath
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/.project
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile/contextpropagation.1.3.bnd
Labels: CLA Signed

#19314 Upgrade testcontainers 1.16.2
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/FATSuite.java
  dev/build.example.testcontainers_fat/publish/servers/build.example.testcontainers.dbrotation/server.xml
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/release.sh
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/security/db2-keystore.p12
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/DB2KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/OracleKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/PostgresKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/Dockerfile
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/release.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/setup/2oracle.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/startup/01_kerberos.sh
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/containters/OracleSSLContainer.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/release.sh
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/setup/enable_ssl.sh
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/security/cwallet.sso
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/security/ewallet.p12
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/store/client-keystore.jks
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/store/client-truststore.jks
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DerbyClientContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DerbyNoopContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/OracleContainer.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/PostgreSQLContainer.java
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/resources/logback-test.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: team:Zombie Apocalypse, CLA Signed

#19667 NOTICES for 22001
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#19661 RM: fix kafka container version
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/KafkaSaslPlainContainer.java
Labels: noproductcode, CLA Signed

#19599 Remove comment about java2 security
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19655 Issue #19654: Use findStringsInLogsUsingMark where necessary
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCResponseHeadersTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19651 Delete renamed private feature.
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.messaging-3.0.internal.feature
Labels: CLA Signed, team:Performance

#19648 JVM Working Dir skip on non jcmd.exe environments
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: noproductcode, CLA Signed

#19626 asynchronous methods can run inline on join and untimed get
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/WSManagedExecutorService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/ext/ManagedExecutorExtension.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/AsyncMethod.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextualDefaultExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/UnusableExecutor.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/io.openliberty.concurrent.cdi/bnd.bnd
  dev/io.openliberty.concurrent.cdi/src/io/openliberty/concurrent/cdi/interceptor/AsyncInterceptor.java
Labels: team:Zombie Apocalypse, CLA Signed

#19646 Enable Last Two EE9 Grpc Tests
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldCDITests.java
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/HelloWorldTest.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointFATServlet.java
  dev/com.ibm.ws.grpc_fat/test-applications/StoreConsumerApp.war/src/com/ibm/testapp/g3store/restConsumer/client/ConsumerEndpointJWTCookieFATServlet.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
Labels: CLA Signed

#19614 [19529] - move mpGraphQL-2.0 from noship to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpGraphQL2.0-appSecurity4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.graphql-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpGraphQL-2.0/io.openliberty.mpGraphQL-2.0.feature
Labels: CLA Signed, in:MicroProfile/GraphQL

#19638 Extra 21.0.0.12 PII Translations
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpContextPropagation-1.3/resources/l10n/io.openliberty.mpContextPropagation-1.3_zh_TW.properties
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
  dev/com.ibm.ws.security.audit.file/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_cs.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_de.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_es.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_fr.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_hu.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_it.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ja.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ko.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_pl.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_pt_BR.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ro.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_ru.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_zh.properties
  dev/io.openliberty.jakarta.expressionLanguage.4.0/resources/jakarta/el/LocalStrings_zh_TW.properties
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#19643 Add new name of AdoptOpenJDK to isWin Acme check
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19669 Interrupt and obtrude asynchronous methods
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/MyManagedBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19560 Tckresults
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
  dev/fattest.simplicity/src/componenttest/topology/utils/TestSuiteXmlParser.java
Labels: noproductcode, CLA Signed

#19424 remove atomic service reference
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
Labels: CLA Signed

#19671 Doubling gradle jvm mem
  dev/gradle.properties
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#19649 featureUtility fat test clean up
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/plainServerXml/server.xml
Labels: noproductcode, CLA Signed

#19658 Improve JPA config trace and obfuscate passwords
  dev/com.ibm.ws.jpa.container.core/resources/com/ibm/ws/jpa/jpa.nlsprops
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/AbstractJPAComponent.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPUnitInfo.java
  dev/com.ibm.ws.jpa.container/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
Labels: ID reviewed, CLA Signed

#19652 Tidy up SQLException Handling in Transaction DB logging
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxStatement.java
Labels: CLA Signed

#19223 Fix CNFEs when running com.ibm.ws.security.oidc.client_fat.spnego and…
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.spnego/build.gradle
Labels: noproductcode, CLA Signed, team:Wendigo East

#19606 GA the identifyException subelement of dataSource
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
Labels: team:Zombie Apocalypse, CLA Signed

#19674 test configuration of transaction context on ContextServiceDefinition
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ApplicationScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/RequestScopedBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19682 Revert "remove atomic service reference"
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
Labels: CLA Signed

#19660 Make ra.inbound.impl package private
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/DispatchableMessage.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaActivationSpecImpl.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaBusSecurityAction.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaColocatingEndpointActivation.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaCommonEndpointActivation.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaEndpointInvokerImpl.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaLockedMessageEnumeration.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaMessageToken.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaScalableEndpointActivation.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/ra/inbound/impl/SibRaXaResource.java
Labels: CLA Signed

#19677 fix codepath where async method returns different stage
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/WSManagedExecutorService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/ext/ManagedExecutorExtension.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/AsyncMethod.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextualDefaultExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/UnusableExecutor.java
  dev/io.openliberty.concurrent.cdi/src/io/openliberty/concurrent/cdi/interceptor/AsyncInterceptor.java
Labels: bug, team:Zombie Apocalypse, CLA Signed

#19678 Add runtime trace for Quiesce failure
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.fat/bootstrap.properties
Labels: noproductcode, CLA Signed, team:Wendigo East

#19681 Issue #19680: Trace the referral configuration in JNDI_CALL trace whe…
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/context/TimedDirContext.java
Labels: CLA Signed, team:Wendigo East

#19635 featureUtility installServerFeatures user feature bug
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/AbstractDirector.java
Labels: CLA Signed

#19686 Openapi tck cleanup
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/src/test/java/io/openliberty/microprofile/openapi20/test/ArquillianLoadableExtension.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/src/test/resources/arquillian.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck-suite.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#19612 Prolong finish for async requests
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RegisteredSyncs.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/ltc/impl/LTCUOWCallback.java
  dev/com.ibm.tx.core/src/com/ibm/ws/Transaction/JTA/Util.java
  dev/com.ibm.tx.core/src/com/ibm/ws/uow/UOWScopeCallbackManager.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DupXidTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/WaitForRecoveryTest.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/RemoteTransactionControllerService.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/ltc/embeddable/impl/LTCCallbacks.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/remote/RemoteTransactionController.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinator.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinatorTran.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATTransaction.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/ProtocolImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/CoordinatorResource.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/TranManagerImpl.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/common/impl/WSATCoordinatorTranTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/common/impl/WSATTransactionTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/service/impl/HandlerImplTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/service/impl/ProtocolImplTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/service/impl/RegistrationImplTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/tm/impl/CoordinatorFactoryServiceTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/tm/impl/ParticipantFactoryServiceTest.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/tm/impl/ParticipantResourceTest.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/com/ibm/ws/wsat/fat/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.2/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.single/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.single/fat/src/com/ibm/ws/wsat/fat/SingleRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.single/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/MultiRecoverySetupServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.single/test-applications/recoveryClient/src/com/ibm/ws/wsat/fat/client/recovery/RecoverySetupServlet.java
  dev/com.ibm.ws.wsat_fat.db/fat/src/com/ibm/ws/wsat/fat/tests/MultiServerTest.java
  dev/com.ibm.ws.wsat_fat.db/test-applications/endtoend/src/com/ibm/ws/wsat/endtoend/client/endtoend/EndToEndClientServlet.java
  dev/com.ibm.ws.wsat_fat.multi/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
Labels: CLA Signed

#19697 Update Oracle JDK version for ACME FATs
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed

#19696 Add additional debug during updates for CustomStoreSample
  dev/com.ibm.ws.security.oauth_test.custom_store/src/security/custom/store/CustomStoreSample.java
Labels: noproductcode, CLA Signed, team:Wendigo East, team:Security SSO
