Repository OpenLiberty/open-liberty, pull requests merged in 2021-07, with the labels that each got.

#17736 Issue #13717: EE 9 EJB Session Async FAT
  dev/com.ibm.ws.ejbcontainer.session.async_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.session.async_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.session.async_fat/fat/src/com/ibm/ws/ejbcontainer/session/async/fat/AsyncErrTest.java
  dev/com.ibm.ws.ejbcontainer.session.async_fat/fat/src/com/ibm/ws/ejbcontainer/session/async/fat/AsyncWarnTest.java
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/AsyncErr2BeanApp_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/EJBTrace_server_EE8.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/EJBTrace_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/MetaDataTrace_server_EE8.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/MetaDataTrace_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/checkFalse_server_EE8.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/checkFalse_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/checkTrue_server_EE8.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/checkTrue_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/default_server_EE8.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/files/default_server_EE9.xml
  dev/com.ibm.ws.ejbcontainer.session.async_fat/publish/servers/com.ibm.ws.ejbcontainer.session.async.fat.AsyncWarnServer/server.xml
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#17648 Issue #17647: Remove SharedServer from WCAddJspFileTest
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCAddJspFileTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestAddJspFile.ear/resources/jsp/forbidden.jsp
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17732 Issue 17731: Skip new winJDK level and ignore config update msg ACME FATs
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#17735 Issue 16994: Update how dynamic reconfig of social login affects discovery data
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, team:Security SSO

#17720 Add more invalid JWE tests to the RP and RS FATs
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/utils/JwtTokenBuilderUtils.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/test-applications/testTokenEndpoint/src/com/ibm/ws/security/fat/testTokenEndpoint/TokenEndpointServlet.java
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientEncryptionTests.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/noOP/NoOPEncryptionRSServerTests.java
Labels: CLA Signed, team:Security SSO, test delivery

#17679 Port MYFACES-4065 and MYFACES-4187
  dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/application/ResourceHandlerImpl.java
Labels: CLA Signed, in:Web Components, release bug, team:Sirius

#15921 Use JSTL 2.0 TLDs in Pages 3.0
  dev/com.ibm.ws.jsp/bnd.bnd
  dev/com.ibm.ws.jsp/resources/com/ibm/ws/jsp/resources/taglibcacheconfig.tags.2.0.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/GlobalTagLibraryCache.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/config/TagLibCacheConfigParser.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/.classpath
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/.project
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/bnd.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-tld.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-master.properties
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#17447 Apply BZ 65358: Improve EL matching of varargs methods.
  dev/com.ibm.websphere.javaee.el.3.0/src/javax/el/Util.java
  dev/com.ibm.ws.el.3.0_fat/.classpath
  dev/com.ibm.ws.el.3.0_fat/bnd.bnd
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30VarargsMethodMatchingTest.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/src/com/ibm/ws/el30/fat/varargstest/EL30VarargsMethodMatchingServlet.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/src/com/ibm/ws/el30/fat/varargstest/EL30VarargsMethodMatchingTestBean.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/src/com/ibm/ws/el30/fat/varargstest/EnumBean.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestVarargsMatching.war/src/com/ibm/ws/el30/fat/varargstest/IEnum.java
  dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/ReflectionUtil.java
Labels: CLA Signed

#17672 intial refactoring of SPNEGO FAT to use local ApacheDS KDC
  dev/com.ibm.ws.security.spnego.fat.common/bnd.bnd
  dev/com.ibm.ws.security.spnego.fat.common/build.gradle
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/ApacheKDCCommonTest.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/ApacheKDCforSPNEGO.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/CommonTestHelper.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/InitClass.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/KdcHelper.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/Krb5Helper.java
  dev/com.ibm.ws.security.spnego_fat/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat/build.gradle
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/BasicAuthTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
  dev/com.ibm.ws.security.spnego_fat/publish/servers/BasicAuthTest/configs/trimKerberosRealmFromPrincipal_customJaasLogin.xml
  dev/com.ibm.ws.security.spnego_fat/publish/servers/BasicAuthTest/server.xml
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/ApacheDSandKDC.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Spnego.java
Labels: CLA Signed, team:Core Security

#17746 config: fix getObscuredDefaultValue
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/AbstractLibertyVariable.java
Labels: CLA Signed

#17745 Issue #13717: EE 9 EJB Remote FAT
  dev/com.ibm.ws.ejbcontainer.remote_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/BadApplicationTests.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/RemoteTests.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/Server2ServerTests.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/files/ExtendsThrowableEE9.xml
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.BadAppServer/server.xml
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.RemoteServer/server.xml
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.RemoteServerClient/server.xml
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.RemoteSessionServer/server.xml
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/BasicRemote.war/src/com/ibm/ws/ejbcontainer/remote/fat/basic/BasicRemoteTestServlet.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/EJBHomeTest.war/src/com/ibm/ws/ejbcontainer/remote/fat/home/EJBHomeTestServlet.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/SingletonWeb.war/src/com/ibm/ws/ejbcontainer/remote/singleton/mix/web/PassivationServlet.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/StatelessAnnWeb.war/src/com/ibm/ws/ejbcontainer/remote/ejb3session/sl/ann/web/TxAttrComp2Servlet.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/StatelessAnnWeb.war/src/com/ibm/ws/ejbcontainer/remote/ejb3session/sl/ann/web/TxAttrCompView2Servlet.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#17753 update DB2 ssl testing to explictly request TLSv1.2
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#17755 Add runtime update trace to help debug server quiesce issue
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/publish/servers/com.ibm.ws.concurrent.persistent.fat.autonomicalpolling1serv/bootstrap.properties
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#17769 Avoid ConcurrentModificationException in MP Config
  dev/com.ibm.ws.microprofile.config.1.4/src/com/ibm/ws/microprofile/config14/sources/SystemConfig14Source.java
Labels: CLA Signed, bug, release bug

#17633 Fix liberty_audit not found test
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashCollectorTest.java
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#17601 Issue #17596: Use impl version in faces api bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/io.openliberty.jakarta.faces.3.0/bnd.bnd
Labels: CLA Signed, in:Web Components, team:Sirius

#17773 Update JMS 2.0 Security RepeatTests
  dev/com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/ibm/ws/messaging/JMS20security/fat/FATSuite.java
Labels: CLA Signed, noproductcode

#17800 EJB remote FAT wait for cfg update
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/BadApplicationTests.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#17780 Fix ApacheDS stop and add port checks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/ApacheDSandKDC.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/LdapApacheDSandKDC.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#17803 Fix for server test defect breaks
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/autoFeatureServerXml/server.xml
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/serverX.zip
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/usrFeaturesServerXml/server.xml
Labels: CLA Signed, noproductcode

#17718 Issue #17716: Remove SharedServer from WCTrailersTest
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTrailersTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/listeners/ReadListenerGetTrailers.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/servlets/ServletGetTrailers.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/servlets/ServletSetTrailers.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17802 Updating SLF4J api versions
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer1/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer2/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServer3/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerInventory/server.xml
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/publish/servers/jaegerServerSystem/server.xml
Labels: CLA Signed, noproductcode

#17793 Validate SOAP format: Fix for issue 17774
  dev/com.ibm.ws.jaxws.common/src/com/ibm/ws/jaxws/support/LibertyLoggingInInterceptor.java
Labels: CLA Signed

#17779 externalize new sig algs in oidc client
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#17785 Sleep for revoke completion on Boulder for Acme
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeRevocationTest.java
Labels: CLA Signed, noproductcode, team:Core Security, team:Wendigo East

#17786 Add additional timeouts on MongoDB validate for CustomStore
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MongoDBUtils.java
  dev/com.ibm.ws.security.oauth_test.custom_servlets/test-applications/oAuth20MongoSetup/src/web/oAuth20MongoSetup.java
Labels: CLA Signed, noproductcode, team:Security SSO, team:Wendigo East

#17806 fix xml-apis jar version
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP/build.gradle
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#17724 Fix cert in mis-match signer tests
  dev/com.ibm.ws.security.saml.sso_fat.common/securitykeys/multiKeyWrongDefaultSamlSpCert.jks
  dev/com.ibm.ws.security.saml.sso_fat.common/securitykeys/samlspWrongCert.jks
Labels: CLA Signed, Debug, noproductcode, team:Security SSO, test bug

#17804 Split suite
  .github/test-categories/WSAT_2
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest1.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest2.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest3.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest4.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/.project
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/wsat.recovery_fat.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/.classpath
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/.gitignore
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/.project
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/bnd.bnd
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/wsat.recovery_fat.bnd
Labels: CLA Signed, noproductcode

#17752 Add wait for SSL restart during reconfigs - in ported CL FATs
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonTest.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestServer.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTest.java
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLCommonTest.java
Labels: CLA Signed, team:Security SSO, test debt

#17792 Issue #17791 - Add hotspot fix and debug to DebugServerCommandPortTest
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/commandport/ServerCommandPortTest.java
Labels: CLA Signed, noproductcode

#17778 Issue #17777: Remove SharedServer
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletClarificationTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestServlet40Clarifications.war/src/servletclarifications/servlets/ServletClarification.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17811 allow quiesce warnings during test shutdown
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/servers/ServerTracker.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/servers/ServerTrackerTest.java
Labels: CLA Signed, team:Security SSO, test bug

#17611 Disable Logstash Collector tests for z/OS machines
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashSSLTest.java
Labels: CLA Signed, noproductcode

#17775 Skip test with IBM JAVA 11
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/HealthCenterTest.java
Labels: CLA Signed, noproductcode

#17821 Preferred text for linked documentation
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans.properties
Labels: CLA Signed, ID reviewed

#17809 Add extra time to debug for ringBufferTest
  dev/com.ibm.ws.collector.manager/test/com/ibm/ws/collector/manager/buffer/RingBufferTest.java
Labels: CLA Signed, noproductcode

#17805 increase timeout again
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/current/CDICurrentTestServlet.java
Labels: CLA Signed, noproductcode

#17583 update wsSecuritySaml and samlWeb features
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee9.opensaml-2.6.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee9.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecuritySaml1.1.internal.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecuritySaml1.1.internal.jaxws-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecuritySaml1.1.internal.jaxws-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/wsSecuritySaml-1.1/com.ibm.websphere.appserver.wsSecuritySaml-1.1.feature
  dev/com.ibm.ws.org.apache.santuario.xmlsec.2.2.0/bnd.overrides
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/bnd.bnd
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/bnd.overrides
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/src/org/apache/wss4j/stax/setup/WSSec.java
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.api.3.4.5/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml.storage.api.3.4.5/bnd.overrides
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/common/BasicEncryptionTests.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/common/DefaultConfigMissingMetaDataTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/common/PkixSAMLTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.3/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLMessageConstants.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLMisc1ConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLSSLConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigNoReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigWithReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlAPITests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlBasicTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlPkixTests.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/common/BasicSAMLTests.java
  dev/com.ibm.ws.security.saml.websso.2.0/bnd.bnd
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/MsgCtxUtil.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/utils/MsgCtxUtilTest.java
Labels: CLA Signed

#17827 Issue #17826: Remove SharedServer
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContainerInitializerFilterServletNameMappingTest.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17824 Fix up new FAT buckets
  .github/test-categories/JAXWS
  .github/test-categories/KERNEL_3
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/.classpath
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/Converter.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/ConverterService.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/Converter.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterService.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceHTTP.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceSOAP11.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceSOAP11MTOM.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceSOAP12.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceSOAP12MTOM.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceWSDLLocation.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/samples/jaxws/converter/bindtype/ConverterServiceXFormat.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/HelloNoWSDLInterface.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/HelloNoWSDLService.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/ObjectFactory.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/SayHello.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/SayHelloResponse.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/endpoint/properties/client/package-info.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/liberty/test/wscontext/WebServiceContextTestService.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/liberty/test/wscontext/WebServiceContextTestServiceImpl.java
Labels: CLA Signed, GitHub Build, noproductcode, team:Performance

#17711 Issue 17692: Avoid memory leaks
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.2.6.2/src/org/apache/cxf/transport/http/osgi/HTTPTransportActivator.java
Labels: CLA Signed

#17784 Continue feature installation even when user feature is present
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallServerAction.java
Labels: CLA Signed

#17640 Revert "Revert "Create the lock base on hashtable in subject instead of authentication data""
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/AuthenticationServiceImpl.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationConstants.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/AuthenticationData.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/WSAuthenticationData.java
Labels: CLA Signed

#17743 Delete recovery logs on clean shutdown in HA env
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/FailureScopeController.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogHandle.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RLSUtils.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogManager.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogManagerImpl.java
Labels: CLA Signed

#17838 Fix Build Break: 285120 - spnegoFAT jdk check
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/ApacheKDCforSPNEGO.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
Labels: CLA Signed, noproductcode

#17739 Only run jaxrs-2.0 FAT bucket if Java level is less than 16
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, in:JAX-RS, noproductcode, team:Wendigo West

#17729 Cleanup some intermittently failing test cases
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/publish/servers/jaxrs21.client.JAXRS21TimeoutClientTest/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/jsonbContextApp/src/mpRestClient12/jsonbContext/JsonbContextTestServlet.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: CLA Signed, in:JAX-RS, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#17823 Updated RequestTiming Test if condition to retry servlet hit
  dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/TimingRequestTiming.java
Labels: CLA Signed, noproductcode

#17835 Updated MPHealth 3.0/3.1 TCK Maven dependencies
  dev/io.openliberty.microprofile.health.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, noproductcode

#17820 Tolerate CWWKE0701E
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/SimpleTest.java
  dev/com.ibm.ws.transaction.core_fat.10/build.gradle
  dev/com.ibm.ws.transaction.core_fat.10/fat/src/com/ibm/ws/transaction/test/.gitignore
  dev/com.ibm.ws.transaction.core_fat.10/fat/src/com/ibm/ws/transaction/test/tests/SimpleDBTranlogTestNoRecOnStart.java
  dev/com.ibm.ws.transaction.core_fat.10/fat/src/com/ibm/ws/transaction/test/tests/SimpleTestNoRecOnStart.java
  dev/fattest.simplicity/src/componenttest/topology/impl/PortDetectionUtil.java
Labels: CLA Signed, noproductcode

#17699 Wait for message roundtrip
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: CLA Signed, noproductcode

#17849 Experimentation with library loading resource adapter classes
  dev/com.ibm.ws.jca_fat_classloading/.classpath
  dev/com.ibm.ws.jca_fat_classloading/bnd.bnd
  dev/com.ibm.ws.jca_fat_classloading/fat/src/com/ibm/ws/jca/fat/classloading/JCAClassLoadingTest.java
  dev/com.ibm.ws.jca_fat_classloading/publish/files/testResourceAdapterClassesAccessibleToSharedLibrary_server.xml
  dev/com.ibm.ws.jca_fat_classloading/test-applications/fvtweb/src/web/ClassLoadingTestServlet.java
  dev/com.ibm.ws.jca_fat_classloading/test-libraries/testlib/src/com/ibm/ws/jca/fat/classloading/sharedlib/LibraryClassThatDoesNotUseResourceAdapterClasses.java
  dev/com.ibm.ws.jca_fat_classloading/test-libraries/testlib/src/com/ibm/ws/jca/fat/classloading/sharedlib/LibraryClassThatUsesResourceAdapterClasses.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#17675 Enable extra logging for testcontainers
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ContainersTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/DatabaseRotationTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/DockerfileTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/FATSuite.java
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/resources/logback-test.xml
Labels: CLA Signed, team:Zombie Apocalypse

#17497 AdminCenter to use encrypted file name to persist toolbox and tool data
  dev/com.ibm.ws.ui/resources/com/ibm/ws/ui/internal/resources/UIMessages.nlsprops
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/pojo/POJOLoaderService.java
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/pojo/PlainTextLoaderService.java
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/pojo/Toolbox.java
Labels: CLA Signed, ID reviewed, L2 Reviewed

#17403 Add isActive method for endpoints
  dev/com.ibm.websphere.appserver.api.kernel.service/bnd.bnd
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/PauseableComponentControllerImpl.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/service/PauseableComponentController.java
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/service/ServerEndpointControlMBeanTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.service/jvm.options
  dev/com.ibm.ws.kernel.service/src/com/ibm/websphere/kernel/server/ServerEndpointControlMBean.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/websphere/kernel/server/package-info.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/server/internal/ServerEndpointControlMBeanImpl.java
Labels: CLA Signed

#17751 PR for Issue 17653: Update OIDC UserInfo processing to handle JWS responses
  dev/com.ibm.ws.security.openidconnect.client/resources/com/ibm/ws/security/openidconnect/client/internal/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/jose4j/util/EcJwkTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, team:Security SSO

#17865 Fix up eclipse and test categories after new fats added.
  .github/test-categories/CLASSLOADING
  .github/test-categories/JAXWS
  .github/test-categories/KERNEL_3
  .github/test-categories/SECURITY_5
  dev/com.ibm.ws.security.authentication.filter_fat/.classpath
  dev/com.ibm.ws.transaction.core_fat.10/.classpath
  dev/com.ibm.ws.transaction.core_fat.10/.project
Labels: CLA Signed, noproductcode, team:Performance

#17850 Upgrade to latest version of MP Rest Client 2.0 TCK
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed, in:MicroProfile/RestClient, noproductcode, team:Wendigo West

#17417 don't enable service if it already exists
  dev/build.image/packaging/debuild/openliberty/debian/postinst
  dev/build.image/packaging/openliberty.spec.template
Labels: CLA Signed

#17816 repeatable ffdc support
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/common/BasicEncryptionTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/common/PkixSAMLTests.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLMisc1ConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLSSLConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigNoReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigWithReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlAPITests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlBasicTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlPkixTests.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/common/BasicSAMLTests.java
  dev/fattest.simplicity/src/componenttest/annotation/AllowedFFDC.java
  dev/fattest.simplicity/src/componenttest/annotation/AllowedFFDCs.java
  dev/fattest.simplicity/src/componenttest/annotation/ExpectedFFDC.java
  dev/fattest.simplicity/src/componenttest/annotation/ExpectedFFDCs.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: CLA Signed, noproductcode

#17861 Allow special characters / URL encoding in queryParam
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/paramconverter/src/com/ibm/ws/jaxrs/fat/paramconverter/ClientTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed

#17874 Add wait in EJB automatic timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.auto_fat/test-applications/AutoNPTimersEJB.jar/src/com/ibm/ws/ejbcontainer/timer/auto/npTimer/ejb/AutoCreatedTimerDriverBean.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#17434 Issue #15979: JPA defaultProperties metatype
  dev/com.ibm.ws.jpa.container.core/resources/com/ibm/ws/jpa/jpa.nlsprops
  dev/com.ibm.ws.jpa.container/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jpa.container/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
Labels: CLA Signed, ID reviewed, L2 Reviewed, in:JPA, team:Blizzard

#17868 Issue #17757: Fix rmicCompatible EJB passivation
  dev/com.ibm.ws.ejbcontainer.remote.portable.core/src/com/ibm/ejs/container/SerializedStub.java
  dev/com.ibm.ws.ejbcontainer.remote/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.remote/src/com/ibm/ws/ejbcontainer/remote/internal/SerializedStubString.java
  dev/com.ibm.ws.ejbcontainer.remote/src/com/ibm/ws/ejbcontainer/remote/internal/StubObjectResolver.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/EJBHomeTest.war/src/com/ibm/ws/ejbcontainer/remote/fat/home/EJBHomeTestServlet.java
  dev/com.ibm.ws.ejbcontainer.remote_fat/test-applications/SingletonWeb.war/src/com/ibm/ws/ejbcontainer/remote/singleton/mix/web/PassivationServlet.java
Labels: CLA Signed, in:EJB Container, release bug, team:Blizzard

#17858 Add className="javax.management.MBeanServerPermission" name="createMBeanServer"
  dev/com.ibm.ws.messaging.open_jms20context_fat/publish/files/JMSContextClient.xml
Labels: CLA Signed, noproductcode

#17859 Add extra threads to server
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/current/CDICurrentTestServlet.java
  dev/com.ibm.ws.cdi.api_fat/publish/servers/cdi12APIServer/server.xml
Labels: CLA Signed, noproductcode

#17891 Revert "Allow special characters / URL encoding in queryParam"
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/paramconverter/src/com/ibm/ws/jaxrs/fat/paramconverter/ClientTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed

#17881 Issue #17880: Use try-with-resources for WebClient
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17879 Issue #17878: Remove SharedServer from WCPushBuilderTest
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPushBuilderTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletClarificationTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestPushBuilderAPI.war/src/testpushbuilderapi/servlets/PushBuilderAPIServlet.java
Labels: CLA Signed, in:Web Components, noproductcode, team:Sirius

#17884 Do not use soap 1.2 methods to process soap 1.1 SoapFault
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.2.6.2/src/org/apache/cxf/jaxws/interceptors/WebFaultOutInterceptor.java
Labels: CLA Signed

#17847 3058 plus symbol
  dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/classloader.properties
Labels: CLA Signed

#17877 Fix Race Condition Regarding JSP's classloaderCreated variable
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestEDR.war/resources/trackDependencies.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionServletWrapper.java
Labels: CLA Signed, in:Web Components, team:Sirius

#17863 spnego fat: allow timeout warning in shutdown messages
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/BasicAuthTest.java
Labels: CLA Signed, noproductcode, team:Core Security

#17895 Allow special characters / URL encoding in queryParam
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/paramconverter/src/com/ibm/ws/jaxrs/fat/paramconverter/ClientTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/JAXRSUtils.java
Labels: CLA Signed

#17632 Issue 17404: Add cache to OIDC client inbound propagation processing (part 2)
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/CacheEntry.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/CommonCache.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/SingleTableCache.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/structures/CacheEntryTest.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/structures/SingleTableCacheTest.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheHelper.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheHelperTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/common/Constants.java
Labels: CLA Signed, ID reviewed, L2 ReviewNotRequired, team:Security SSO

#17902 Add wait in EJB BadApp FAT for Windows
  dev/com.ibm.ws.ejbcontainer.remote_fat/fat/src/com/ibm/ws/ejbcontainer/remote/fat/tests/BadApplicationTests.java
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test bug

#17710 Update EclipseLink 2.7.8 -> 2.7.9
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/sessions/Project.java
  dev/com.ibm.ws.jpa.tests.spec10.query/test-applications/olgh17369/src/com/ibm/ws/jpa/olgh17369/testlogic/JPATestOLGH17369Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query/test-applications/olgh17373/src/com/ibm/ws/jpa/olgh17373/testlogic/JPATestOLGH17373Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query/test-applications/olgh17376/src/com/ibm/ws/jpa/olgh17376/testlogic/JPATestOLGH17376Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query/test-applications/olgh17407/src/com/ibm/ws/jpa/olgh17407/testlogic/JPATestOLGH17407Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh14457/src/com/ibm/ws/jpa/olgh14457/testlogic/JPATestOLGH14457Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16588/src/com/ibm/ws/jpa/olgh16588/testlogic/JPATestOLGH16588Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16685/src/com/ibm/ws/jpa/olgh16685/testlogic/JPATestOLGH16685Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16772/src/com/ibm/ws/jpa/olgh16772/testlogic/JPATestOLGH16772Logic.java
  dev/com.ibm.ws.jpa_eclipselink_fat/test-applications/olgh16970/src/com/ibm/ws/jpa/olgh16970/testlogic/JPATestOLGH16970Logic.java
  dev/com.ibm.ws.jpa_spec20_fat/test-applications/olgh16686/src/com/ibm/ws/jpa/olgh16686/testlogic/JPATestOLGH16686Logic.java
Labels: CLA Signed, in:JPA, team:Blizzard

#17867 criu: Add SnapshotHook to support multiple restores by restoring .sCommand
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/ServerCommandListener.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/commands/ServerCommandClientTest.java
Labels: CRIU

#17899 remove obsolete shutdown callback method
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
Labels: CLA Signed, team:Zombie Apocalypse

#17801 use ManagedChannelRegistry instead of ServiceLoader to register ManagedChannelProvider
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientConfigTests.java
  dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.disabled.server.xml
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/src/META-INF/services/io.grpc.ManagedChannelProvider
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/GrpcClientComponent.java
Labels: CLA Signed, in:Transport, team:Sirius

#17900 Avoid major version changes to utils package
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/location/internal/Activator.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/TimestampUtils.java
Labels: CRIU

#17944 Fix restore time
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/TimestampUtils.java
Labels: CLA Signed

#17911 2020.08 NLS Translations
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_cs.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_de.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_es.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_fr.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_hu.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_it.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_ja.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_ko.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_pl.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_pt_BR.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_ro.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_ru.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_zh.nlsprops
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS_zh_TW.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_de.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_es.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_it.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_cs.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_de.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_es.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_fr.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_hu.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_it.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_ja.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_ko.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_pl.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_pt_BR.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_ro.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_ru.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_zh.nlsprops
  dev/io.openliberty.org.jboss.resteasy.common/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#17941 Fix maven coordinate changes from #17710
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
Labels: CLA Signed, in:JPA, team:Blizzard

#17936 Test that uses quartz in open liberty
  dev/com.ibm.ws.concurrent_fat_quartz/.classpath
  dev/com.ibm.ws.concurrent_fat_quartz/.project
  dev/com.ibm.ws.concurrent_fat_quartz/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent_fat_quartz/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent_fat_quartz/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent_fat_quartz/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent_fat_quartz/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_quartz/build.gradle
  dev/com.ibm.ws.concurrent_fat_quartz/fat/src/com/ibm/ws/concurrent/fat/quartz/ConcurrentQuartzTest.java
  dev/com.ibm.ws.concurrent_fat_quartz/fat/src/com/ibm/ws/concurrent/fat/quartz/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_quartz/publish/servers/com.ibm.ws.concurrent.fat.quartz/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_quartz/publish/servers/com.ibm.ws.concurrent.fat.quartz/quartz.properties
  dev/com.ibm.ws.concurrent_fat_quartz/publish/servers/com.ibm.ws.concurrent.fat.quartz/server.xml
  dev/com.ibm.ws.concurrent_fat_quartz/test-applications/quartzapp/src/concurrent/fat/quartz/web/JobTracker.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-applications/quartzapp/src/concurrent/fat/quartz/web/LengthyJob.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-applications/quartzapp/src/concurrent/fat/quartz/web/LookupOnInitJob.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-applications/quartzapp/src/concurrent/fat/quartz/web/LookupOnRunJob.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-applications/quartzapp/src/concurrent/fat/quartz/web/QuartzTestServlet.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-quartz-extensions/threading/src/example/quartz/concurrent/ManagedExecutorThreadExecutor.java
  dev/com.ibm.ws.concurrent_fat_quartz/test-quartz-extensions/threading/src/example/quartz/concurrent/ManagedExecutorThreadPool.java
Labels: CLA Signed, noproductcode, team:Zombie Apocalypse

#17808 Issue #17807 - Split buildFeatureStart_fat
  dev/build.featureStart.aToL_fat/.classpath
  dev/build.featureStart.aToL_fat/.project
  dev/build.featureStart.aToL_fat/.settings/bndtools.core.prefs
  dev/build.featureStart.aToL_fat/.settings/org.eclipse.core.resources.prefs
  dev/build.featureStart.aToL_fat/.settings/org.eclipse.jdt.core.prefs
  dev/build.featureStart.aToL_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/build.featureStart.aToL_fat/bnd.bnd
  dev/build.featureStart.aToL_fat/build.gradle
  dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FATSuite.java
  dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestAToL.java
  dev/build.featureStart.aToL_fat/publish/files/feature-java-levels.properties
  dev/build.featureStart.aToL_fat/publish/servers/features.start.a.to.l.server/bootstrap.properties
  dev/build.featureStart.aToL_fat/publish/servers/features.start.a.to.l.server/server.xml
  dev/build.featureStart.mToZ_fat/.classpath
  dev/build.featureStart.mToZ_fat/.project
  dev/build.featureStart.mToZ_fat/.settings/bndtools.core.prefs
  dev/build.featureStart.mToZ_fat/.settings/org.eclipse.core.resources.prefs
  dev/build.featureStart.mToZ_fat/.settings/org.eclipse.jdt.core.prefs
  dev/build.featureStart.mToZ_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/build.featureStart.mToZ_fat/bnd.bnd
  dev/build.featureStart.mToZ_fat/build.gradle
  dev/build.featureStart.mToZ_fat/fat/src/com/ibm/ws/simple/FATSuite.java
  dev/build.featureStart.mToZ_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestMToZ.java
  dev/build.featureStart.mToZ_fat/publish/files/feature-java-levels.properties
  dev/build.featureStart.mToZ_fat/publish/servers/features.start.m.to.z.server/bootstrap.properties
  dev/build.featureStart.mToZ_fat/publish/servers/features.start.m.to.z.server/server.xml
Labels: CLA Signed, noproductcode

#17935 Issue #14501: For the applications that are stored as binary in com.i…
  dev/com.ibm.ws.security.client_fat/.classpath
  dev/com.ibm.ws.security.client_fat/bnd.bnd
  dev/com.ibm.ws.security.client_fat/build.gradle
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLCmdClient/apps/earDD.ear
  dev/com.ibm.ws.security.client_fat/publish/clients/mySSLTestClient/apps/earDD.ear
  dev/com.ibm.ws.security.client_fat/publish/clients/myTestClient/apps/TechnologySamples.ear
  dev/com.ibm.ws.security.client_fat/test-applications/TechnologySamples.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/TechnologySamples.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.security.client_fat/test-applications/TechnologySamples.ear/resources/META-INF/ibm-application-bnd.xmi
  dev/com.ibm.ws.security.client_fat/test-applications/TechnologySamples.ear/resources/META-INF/ibm-application-ext.xmi
  dev/com.ibm.ws.security.client_fat/test-applications/TechnologySamples.ear/resources/META-INF/was.policy
  dev/com.ibm.ws.security.client_fat/test-applications/TestBeans.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.client_fat/test-applications/TestBeans.war/src/com/ibm/ws/app/manager/war/test/EjbDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/TestBeans.war/src/com/ibm/ws/app/manager/war/test/EjbNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/earDD.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/earDD.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestSingletonEjbDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestStatefulEjbDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestStatelessEjbDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanSingletonDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanStatefulDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31DD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanStatelessDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestSingletonEjbNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestStatefulEjbNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/InterfaceTestStatelessEjbNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanSingletonNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanStatefulNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/ejb31NoDD.jar/src/com/ibm/ws/app/manager/war/test/TestBeanStatelessNoDD.java
  dev/com.ibm.ws.security.client_fat/test-applications/helloWorld.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/helloWorld.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.security.client_fat/test-applications/helloWorld.jar/src/com/ibm/ws/app/manager/client/HelloWorld.java
Labels: CLA Signed, noproductcode, team:Wendigo East

#17897 Wait for SSL to be ready after server restart
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLMessageConstants.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/BasicSolicitedSPInitiatedTests.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#17924 Introduce 2 long lease servers to Tx Cloud Fats
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleaselogfail/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleaselogfail/server.xml
Labels: CLA Signed, noproductcode

#17918 282675 social fats cleanup web client
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests_NoServerSSL.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicDiscoveryConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_ErrorDiscoveryConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/utils/SocialCommonTest.java
Labels: CLA Signed, noproductcode, team:Security SSO, test bug

#17934 move ee9 transform func from oidc to security common
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonTest.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTest.java
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLCommonTest.java
Labels: CLA Signed

#17776 perform jwe id token verification in FATs
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/JwtTokenForTest.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonValidationTools.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/Constants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/TestSettings.java
  dev/com.ibm.ws.security.oidc.client_fat/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientEncryptionTests.java
Labels: CLA Signed

#17681 Don't put exception stack in json error objects
  dev/com.ibm.ws.jmx.connector.client.rest/src/com/ibm/ws/jmx/connector/converter/JSONConverter.java
  dev/com.ibm.ws.jmx.connector.client.rest/test/com/ibm/ws/jmx/connector/converter/JSONConverterTest.java
Labels: CLA Signed

#17922 Jakarta ee9 fat wsscxf
  dev/com.ibm.ws.wssecurity_fat.wsscxf/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/caller/CxfCallerUNTTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/caller/CxfCallerX509AsymTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/caller/CxfCallerX509SymTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/nowssec/CxfNoWssecTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfBspTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfInteropX509Tests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfSampleTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfSymSampleTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfDeriveKeyTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfPasswordDigestTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfSSLUNTBasicTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfSSLUNTNonceTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfSSLUNTNonceTimeOutTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfUNTBasicTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfUNTNonceTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfUntNoPassTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfWssTemplatesTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/wsstemplates/CxfWssTemplatesTestsWithExternalPolicy.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/wsstemplates/CxfWssTemplatesTestsWithWSDL.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.sample/apps/WSSampleSeiClient.war
  dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.sample/apps/webcontent.war
Labels: CLA Signed, noproductcode

#17871 hide passwords in cxf FAT logs
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/AbstractHTTPDestination.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/usernametoken/CxfUNTBasicTests.java
Labels: CLA Signed

#17945 disable testPropertyConfigSource
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: CLA Signed, noproductcode

#17933 Wait till LTPA configuration is ready
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/WebServiceMonitorTest.java
Labels: CLA Signed, noproductcode

#17970 waitForStringInLog method with default timeout is used
  dev/io.openliberty.ws.global.handler.internal_fat/fat/src/com/ibm/ws/webservices/handler/fat/HandlerChainTest.java
Labels: CLA Signed, in:Web Services, noproductcode, team:Bobcats

#17949 Issue #13717: EE 9 EJB Exception FAT
  dev/com.ibm.ws.ejbcontainer.exception_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.exception_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.exception_fat/fat/src/com/ibm/ws/ejbcontainer/exception/fat/tests/ExceptionTest.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/fat/src/com/ibm/ws/ejbcontainer/exception/fat/tests/InheritedApplicationExceptionTest.java
  dev/com.ibm.ws.ejbcontainer.exception_fat/publish/servers/com.ibm.ws.ejbcontainer.exception.fat.AppExceptionServer/server.xml
  dev/com.ibm.ws.ejbcontainer.exception_fat/publish/servers/com.ibm.ws.ejbcontainer.exception.fat.ExceptionServer/server.xml
Labels: CLA Signed, in:EJB Container, noproductcode, team:Blizzard, test delivery

#17939 Issue #13717: EE 9 EJB Interceptor FAT
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.interceptor_fat/fat/src/com/ibm/ws/ejbcontainer/interceptor/fat/AroundTimeoutTest.java
Labels: CLA Signed, in:EJB Container, jakartaEE, noproductcode, team:Blizzard, test delivery

#17929 Issue #13717: EE 9 EJB Interceptor V32 FAT
  dev/com.ibm.ws.ejbcontainer.interceptor.v32_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.interceptor.v32_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.interceptor.v32_fat/fat/src/com/ibm/ws/ejbcontainer/interceptor/v32/fat/tests/UnspecifiedContextTest.java
Labels: CLA Signed, in:EJB Container, jakartaEE, noproductcode, team:Blizzard, test delivery

#17930 Ensure jaxrs-2.0 feature works with JDK 16 OOTB
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/annotationscan/AnnotationScanTest.java
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17915 Move MicroProfile 4.1 to GA
  dev/build.image/build.gradle
  dev/build.image/profiles/javaee8/features.xml
  dev/build.image/profiles/microProfile4/features.xml
  dev/build.image/profiles/webProfile8/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.microprofile.health-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-4.1/com.ibm.websphere.appserver.microProfile-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.1/com.ibm.websphere.appserver.mpHealth-3.1.feature
  dev/com.ibm.ws.kernel.boot/publish/templates/servers/microProfile4/server.xml
  dev/io.openliberty.opentracing.2.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATSuite.java
Labels: CLA Signed

#17978 Defect 283910 fix SpringBoot ConfigActuatorXMLOverrideTests20
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigActuatorXMLOverrideTests20.java
Labels: CLA Signed, in:SpringBoot, noproductcode, team:OSGi Infrastructure

#17917 Add thread-context=true to Servlet API Exports
  dev/io.openliberty.jakarta.servlet.5.0/bnd.bnd
Labels: CLA Signed, in:Web Components, jakartaEE, team:Sirius

#17903 Upgrade RESTEasy to 4.7.0.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigProviderResolver
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigProviderResolverImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigSourceImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/package-info.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/ContextParameterInjector.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/FormInjector.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/IAttachmentImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/IBMMultipartProvider.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/IMultipartBodyImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/spi/config/DefaultConfiguration.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/util/TypeConverter.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/RESTfulServletContainerInitializer.java
  dev/io.openliberty.org.jboss.resteasy.validator.provider/bnd.bnd
Labels: CLA Signed, in:JAX-RS, team:Wendigo West

#17981 Jakarta ee9 fat wsscxf saml.2
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/OneServerTests/CxfSAMLCaller1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/TwoServerTests/CxfSAMLCaller2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/common/CxfSAMLCallerTests.java
Labels: CLA Signed, noproductcode

#17977 Jakarta ee9 fat wsscxf saml.1
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/OneServerTests/CxfSAMLWSSTemplates1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/OneServerTests/CxfSSLSAMLBasic1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/TwoServerTests/CxfSAMLWSSTemplates2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/TwoServerTests/CxfSSLSAMLBasic2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/common/CxfSAMLWSSTemplatesTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/common/CxfSSLSAMLBasicTests.java
Labels: CLA Signed, noproductcode

#17984 jakarta update to saml.5 fat
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/OneServerTests/CxfSAMLAsymSignEnc1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/OneServerTests/CxfSAMLSymSignEnc1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/TwoServerTests/CxfSAMLAsymSignEnc2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/TwoServerTests/CxfSAMLSymSignEnc2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/common/CxfSAMLAsymSignEncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/common/CxfSAMLSymSignEncTests.java
Labels: CLA Signed, noproductcode

#17983 jakarta update to saml.4 fat
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken4/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken4/TwoServerTests/CxfSAMLCaller2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.4/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken4/common/CxfSAMLCallerTests.java
Labels: CLA Signed, noproductcode

#17979 Jakarta ee9 fat wsscxf saml.3
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken3/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken3/TwoServerTests/CxfSAMLCaller2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken3/common/CxfSAMLCallerTests.java
Labels: CLA Signed, noproductcode

#17988 Remove legacy warning for missing SSL properties file
  dev/com.ibm.ws.messaging.common/resources/com/ibm/ws/sib/jfapchannel/CWSIJMessages.nlsprops
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/comms/ConnectionMetaData.java
  dev/com.ibm.ws.messaging.comms.client/resources/com/ibm/ws/sib/jfapchannel/CWSIJMessages.nlsprops
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/comms/client/ConnectionMetaDataImpl.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/ConversationMetaData.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/JFapChannelConstants.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/framework/Framework.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/octracker/OutboundConnectionTracker.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/richclient/framework/impl/RichClientFramework.java
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/richclient/impl/ConversationMetaDataImpl.java
Labels: CLA Signed, ID review not needed

#17976 mpOpenAPI: fix multipleOf validation check
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/validation/SchemaValidator.java
  dev/com.ibm.ws.microprofile.openapi/test/com/ibm/ws/microprofile/openapi/validation/test/SchemaValidatorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/utils/ValidationMessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/validation/SchemaValidator.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/validation/test/SchemaValidatorTest.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_cs.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_de.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_es.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_fr.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_hu.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_it.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_ja.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_ko.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_pl.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_pt_BR.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_ro.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_ru.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_zh.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/validation/ValidationMessages_zh_TW.nlsprops
Labels: CLA Signed, ID review not needed, L2 ReviewNotRequired

#17992 Allow backslash in BasicRegistry entities
  dev/com.ibm.ws.security.registry.basic/src/com/ibm/ws/security/registry/basic/internal/BasicRegistry.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/basic.server.xml.orig
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat/server.xml
Labels: CLA Signed, release bug, team:Wendigo East

#17925 Issue #13717: EE 9 EJB Legacy FAT
  dev/com.ibm.ws.ejbcontainer.legacy_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.legacy_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/CacheTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/EJB1XStatefulTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/EJBinWAR2xTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/PassivationRegressionTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SFLocalTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SFPassivationTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SFRemoteTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SLLocalTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/fat/src/com/ibm/ws/ejbcontainer/legacy/fat/tests/SLRemoteTest.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.notrace/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.remote.noTrace/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/publish/servers/com.ibm.ws.ejbcontainer.legacy.server.remote/server.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/sfr/web/SFRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB1XRemoteSpecWeb.war/src/com/ibm/ejb1x/base/spec/slr/web/SLRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB2XRemoteSpecWeb.war/src/com/ibm/ejb2x/base/spec/sfr/web/SFRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJB2XRemoteSpecWeb.war/src/com/ibm/ejb2x/base/spec/slr/web/SLRemoteImplContextServlet.java
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulPassivationWeb.war/src/com/ibm/ejb2x/base/pitt/web/PassivationRegressionServlet.java
Labels: CLA Signed, in:EJB Container, jakartaEE, noproductcode, team:Blizzard, test delivery

#17905 ee9 update for wsscxf.1 fat
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/sha2sig/CxfSha2SigTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/wss11enc/CxfWss11EncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/wss11sig/CxfWss11SigTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfEndSupTokensAsymTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfEndSupTokensSymTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigSymSha2NegativeTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigSymTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509ASyncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509BasicTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509CrlTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509EncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509ObjectTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509OverRideTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509SigTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509StrTypeTests.java
Labels: CLA Signed, noproductcode

#17986 Retain more tx recovery test diagnostic files
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
Labels: CLA Signed, noproductcode

#17995 Issue #17994:Add Permissions to snoop.war to avoid java 2 sec error i…
  dev/com.ibm.ws.app.manager_fat/test-applications/snoop.war/resources/META-INF/permissions.xml
Labels: CLA Signed, noproductcode

#17956 Wsat serviceability
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.tx.util/src/com/ibm/tx/util/Utils.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicRotationTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicCoreTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicCoreTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicDBTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicDBTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicFSTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicFSTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.wsat.concurrent_fat/publish/servers/MigrationServer1/server.xml
  dev/com.ibm.ws.wsat.concurrent_fat/publish/servers/MigrationServer2/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/LPSDisabled/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/MigrationServer1/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/MigrationServer2/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/MigrationServer3/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/WSATSleep/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATRecovery1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATRecovery2/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATSingleRecovery/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/MultiServerTest/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/ThirdServer/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATBasic/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server2/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATSSL_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATSSL_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATSSL_Server2/server.xml
Labels: CLA Signed
