Repository OpenLiberty/open-liberty, pull requests merged in 2022-07, with the labels that each got.

#21612 Update activation to the final 2.1.0 version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.1.feature
Labels: CLA Signed, team:Performance

#21590 Enable deep linking in OpenAPI UI
  dev/com.ibm.ws.openapi.ui/swagger-ui/dev.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/index.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/mpOpenApi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/openapi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/mpOpenApi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/openapi.html
Labels: CLA Signed

#21623 Update Weld
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/io.openliberty.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.0/io.openliberty.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.cdi/bnd.bnd
  dev/com.ibm.ws.org.jboss.logging/bnd.bnd
  dev/io.openliberty.cdi.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.cdi.4.0.thirdparty/bnd.bnd
  dev/io.openliberty.org.jboss.weld5.se/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.overrides
Labels: CLA Signed

#21599 Port MYFACES-4432
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resources/implicit_objects.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/src/com/ibm/ws/jsf23/fat/elimplicit/cdi/beans/ELImplicitObjectBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/cdi/JsfArtifactProducer.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/el/unified/resolver/implicitobject/ImplicitObjectResolver.java
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/cdi/JsfArtifactProducer.java
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/el/unified/resolver/implicitobject/ImplicitObjectResolver.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#21624 EE10 compatibility
  dev/com.ibm.ws.transaction.core_fat.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.cdi/build.gradle
  dev/com.ibm.ws.transaction.core_fat.cdi/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat.cdi/fat/src/com/ibm/ws/transaction/test/TransactionScopedTest.java
  dev/com.ibm.ws.transaction.core_fat.cdi/fat/src/com/ibm/ws/transaction/test/TransactionalEJBTest.java
  dev/com.ibm.ws.transaction.core_fat.cdi/test-applications/transactional/src/com/ibm/ws/transactional/web/TransactionalTestServlet.java
  dev/com.ibm.ws.transaction.core_fat.cdi/test-applications/transactionalEJB/src/com/ibm/ws/transactionalEJB/web/TransactionalEJBTestServlet.java
Labels: noproductcode, CLA Signed

#21630 Update CDI JNDI tests and repeat against EE10
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionTest.java
  dev/com.ibm.ws.cdi.jndi_fat/.classpath
  dev/com.ibm.ws.cdi.jndi_fat/bnd.bnd
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/FATSuite.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/lookup/BeanManagerLookupServlet.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/lookup/BeanManagerLookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/lookup/MyBean.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/strings/JNDILookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/strings/JNDIStrings.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/strings/LookupServlet.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/strings/ObserverBean.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi/jndi/strings/application.xml
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BeanManagerLookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/CDI12JNDIBeanManagerTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/fat/tests/JNDILookupTest.java
  dev/com.ibm.ws.cdi.jndi_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.jndi_fat/publish/servers/cdi12BasicServer/server.xml
  dev/com.ibm.ws.cdi.jndi_fat/publish/servers/cdi12JNDIServer/server.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.jar/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.jar/resources/META-INF/application-client.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.jar/src/com/ibm/ws/clientcontainer/fat/AppBean.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.jar/src/com/ibm/ws/clientcontainer/fat/HelloAppClient.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/HelloAppClient.jar/src/com/ibm/ws/clientcontainer/fat/TestLoginCallbackHandler.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.war/src/cdi12/beanmanagerlookup/test/BeanManagerLookupServlet.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/beanManagerLookupApp.war/src/cdi12/beanmanagerlookup/test/MyBean.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/cdi12helloworldtest.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/cdi12helloworldtest.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/cdi12helloworldtest.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/cdi12helloworldtest.war/src/cdi12/helloworld/test/HelloServlet.java
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/jndiLookup.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.jndi_fat/test-applications/jndiLookup.war/src/com/ibm/ws/cdi12/test/jndi/LookupServlet.java
Labels: noproductcode, CLA Signed

#21660 Revert "Update Weld"
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/io.openliberty.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.0/io.openliberty.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.thirdparty.cdi-2.0/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.cdi/bnd.bnd
  dev/com.ibm.ws.org.jboss.logging/bnd.bnd
  dev/io.openliberty.cdi.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.cdi.4.0.thirdparty/bnd.bnd
  dev/io.openliberty.org.jboss.weld5.se/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.overrides
Labels: CLA Signed

#21463 preventing NPE when uninstalling iFixes on Windows
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#21654 Update .settings
  dev/io.openliberty.webcontainer.servlet.6.0.internal/.settings/org.eclipse.jdt.ui.prefs
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#21657 increase timeout
  dev/com.ibm.ws.clientcontainer.cdi_fat/publish/clients/cdiClient/client.xml
Labels: noproductcode, CLA Signed

#21402 RepeatedAnnotations
  dev/com.ibm.ws.messaging.open_31_fat/.classpath
  dev/com.ibm.ws.messaging.open_31_fat/.project
  dev/com.ibm.ws.messaging.open_31_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.messaging.open_31_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.messaging.open_31_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_31_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.messaging.open_31_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_31_fat/build.gradle
  dev/com.ibm.ws.messaging.open_31_fat/fat/src/com/ibm/ws/messaging/repeatedAnnotations/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_31_fat/fat/src/com/ibm/ws/messaging/repeatedAnnotations/fat/RepeatedAnnotationsTest.java
  dev/com.ibm.ws.messaging.open_31_fat/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.messaging.open_31_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.messaging.open_31_fat/test-applications/repeatedAnnotations/resources/index.jsp
  dev/com.ibm.ws.messaging.open_31_fat/test-applications/repeatedAnnotations/src/repeatedAnnotations/ejb/RepeatedAnnotationsBean.java
  dev/com.ibm.ws.messaging.open_31_fat/test-applications/repeatedAnnotations/src/repeatedAnnotations/web/RepeatedAnnotationsServlet.java
  dev/com.ibm.ws.messaging.open_jms20_fat/publish/files/JMSContextInjectClient.xml
Labels: noproductcode, CLA Signed

#21671 Issue #21670: Update facelet to output HttpSession not Session
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resources/implicit_objects.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#21618 Repeat EE10 or EE9 only in lite mode based on Java level
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/FATSuite.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE10

#21667 featureUtility revert to backslash in FormatUrlSuffix
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
Labels: CLA Signed

#21600 featureUtility fix progressBar NPE
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
Labels: CLA Signed

#21673 check if ran by featureUtility
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/InstallFeatureAction.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/InstallKernelInteractive.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/Director.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelImpl.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#20505 18739 jaxrs31prototype
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-appSecurity4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-validator3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-xmlBinding3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-validator3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-xmlBinding4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.1/io.openliberty.restfulWS-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.defaultexceptionmapper_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.defaultexceptionmapper_fat/fat/src/com/ibm/ws/jaxrs/defaultexceptionmapper_fat/FATSuite.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/.classpath
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/.project
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/fat/src/io/openliberty/jakarta/rest31/tck/FATSuite.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/fat/src/io/openliberty/jakarta/rest31/tck/JakartaRest31TckPackageTest.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/jvm.options.debug
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/lib/global/.gitkeep
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/.gitignore
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/src/main/java/io/openliberty/jakarta/rest/test/ArquillianLoadableExtension.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/src/main/resources/arquillian.xml
  dev/io.openliberty.jaxrs30/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/src/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/fat/src/io/openliberty/restfulWS30/cdi30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
  dev/io.openliberty.restfulWS30.appSecurity/bnd.bnd
  dev/io.openliberty.restfulWS31.appSecurity/.project
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#21525 Servlet 6.0 Create WC structure
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/io.openliberty.servlet.6.0.internal.factories/bnd.bnd
  dev/io.openliberty.servlet.6.0.internal.factories/src/io/openliberty/servlet/internal/osgi/response/factory/IRequestResponseFactory60Impl.java
  dev/io.openliberty.servlet.6.0.internal.factories/src/io/openliberty/servlet/internal/osgi/srt/factory/SRTConnectionContextPool60Impl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/request/IRequest60Impl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/request/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/srt/SRTConnectionContext60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/srt/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/srt/SRTServletConnection.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/srt/SRTServletRequest60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/srt/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/websphere/servlet60/IRequest60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/websphere/servlet60/package-info.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#21221 Test oracle wallet using p12 keystore
  dev/com.ibm.ws.jdbc_fat_oracle/.project
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclesslfat/src/ssl/web/OracleSSLTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21680 template methods
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/TemplateTestApp/src/test/jakarta/data/template/web/TemplateTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/TemplateTestApp/src/test/jakarta/data/template/web/Vehicle.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/IdNotFoundException.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/MappingException.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/DataPersistence.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/QueryHandler.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/TemplateImpl.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21695 Removed check for the two expiration fields
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed

#20462 20479: Admin center: input json validation added.
  dev/com.ibm.websphere.appserver.features/visibility/public/adminCenter-1.0/com.ibm.websphere.appserver.adminCenter-1.0.feature
  dev/com.ibm.ws.ui/bnd.bnd
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/ToolDataAPI.java
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/ToolboxAPI.java
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
Labels: CLA Signed

#21099 Create Websocket 2.1 API bundles
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.1.feature
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/SessionIdleTimeout.java
  dev/io.openliberty.jakarta.websocket.2.1/.classpath
  dev/io.openliberty.jakarta.websocket.2.1/.project
  dev/io.openliberty.jakarta.websocket.2.1/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.websocket.2.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.websocket.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.websocket.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.websocket.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.2.1/build.gradle
  dev/io.openliberty.jakarta.websocket.client.2.1/.classpath
  dev/io.openliberty.jakarta.websocket.client.2.1/.project
  dev/io.openliberty.jakarta.websocket.client.2.1/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.websocket.client.2.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.websocket.client.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.websocket.client.2.1/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.websocket.client.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.client.2.1/build.gradle
  dev/io.openliberty.wsoc.2.1.internal_fat/.classpath
  dev/io.openliberty.wsoc.2.1.internal_fat/.project
  dev/io.openliberty.wsoc.2.1.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.wsoc.2.1.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.wsoc.2.1.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.wsoc.2.1.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.wsoc.2.1.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.2.1.internal_fat/build.gradle
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/common/Constants.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/common/SingleRequestClientTestRunner.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/common/Utils.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/common/WsocUpgradeServlet.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/endpoints/client/basic/TimeOutClientEP.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/all/TimeOutTest.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/OnlyRunNotOnZRule.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/WebServerControl.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/WebServerSetup.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/MultiClientRunner.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/MultiClientTestContext.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/PublishTask.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/TestHelper.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/TestWsocContainer.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTest.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestContext.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestException.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestRunner.java
  dev/io.openliberty.wsoc.2.1.internal_fat/publish/servers/basic21TestServer/bootstrap.properties
  dev/io.openliberty.wsoc.2.1.internal_fat/publish/servers/basic21TestServer/server.xml
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/resources/WEB-INF/web.xml
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/resources/dojo.js
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/resources/index.html
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/src/basic/war/NegativeTimeOutServerEP.java
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/src/basic/war/ZeroTimeOutServerEP.java
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
  dev/io.openliberty.wsoc.internal_fat/test-applications/cdi.war/resources/WEB-INF/beans.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#21645 installUtility/featureUtility remove resolveAutoFeatures
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#21678 register RegisterRestClient as a BDA
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/io/openliberty/microprofile/rest/client30/internal/RestClientCdiExtensionMetadata.java
Labels: CLA Signed

#21699 Revert "installUtility/featureUtility remove resolveAutoFeatures"
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#21606 Revert "Revert "PR for Issue 21372: Update BCL code to check http URIs for public client""
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidator.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidatorTest.java
Labels: CLA Signed, team:Security SSO

#21709 Update tests to remove skip for repeat for ee9
  dev/com.ibm.ws.jaxrs.2.0_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/ExceptionMappingWithOTTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/RestMetricsTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/.classpath
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE10Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: noproductcode, CLA Signed, team:Performance

#21706 Temporarily skip EE10 for InjectIntoPathTest
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jaxrs/inject/InjectIntoPathTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jaxrs/inject/war/CDIResource.java
Labels: noproductcode, CLA Signed

#21696 Issue#20854: Re-enable CDI, Transaction, Servlet31 tests for EE10
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/StatefulSessionBeanInjectionTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jsf/SimpleJSFTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jsf/SimpleJSFWithSharedLibTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jsp/SimpleJSPTest.java
  dev/com.ibm.ws.transaction.core_fat.cdi/test-applications/transactional/src/com/ibm/ws/transactional/web/TransactionalTestServlet.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/FormLoginReadListenerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#21716 Repeat Infinispan per java version
  dev/com.ibm.ws.session.cache_fat_infinispan_container/fat/src/com/ibm/ws/session/cache/fat/infinispan/container/FATSuite.java
Labels: noproductcode, CLA Signed

#21715 Remove info logging from CXF 3.4 overlays
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/Soap12FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/service/factory/ReflectionServiceFactoryBean.java
Labels: CLA Signed

#21712 fixing log rollover tests
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
Labels: noproductcode, CLA Signed

#21705 Revise TX Lease Log select for update semantics
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRetry.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
Labels: CLA Signed

#21721 Beta mpOpenAPI-3.1
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-3.1/io.openliberty.mpOpenAPI-3.1.feature
Labels: CLA Signed

#21718 Issue #21717: Fix comment typo: require should be requires.
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#21733 Use quick log test for testMaxFileSizePriorityRolling
  dev/com.ibm.ws.logging_fat/bnd.bnd
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
  dev/com.ibm.ws.logging_fat/test-applications/quick-log-test/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.logging_fat/test-applications/quick-log-test/resources/beans.xml
  dev/com.ibm.ws.logging_fat/test-applications/quick-log-test/src/com/ibm/ws/logging/fat/quick/log/test/QuickLogTest.java
Labels: noproductcode, CLA Signed

#21728 Test when config changes on restore for injection into application scope CDI beans.
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPConfigTest.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/ApplicationScopedOnCheckpointBean.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/MPConfigBeanWithApplicationScope.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/MPConfigServlet.java
Labels: noproductcode, CLA Signed

#21595 Switch Jakarta EE10 Core Profile features to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi4.0-concurrent3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi4.0-servlet6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jsonb.compatibility.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jsonp.compatibility.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.globalhandler1.0.internal.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.connectors-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.pages-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence.base-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlBinding-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-3.0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-3.0.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbInternal-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpInternal-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.internal-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.0/io.openliberty.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.0/io.openliberty.concurrent-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/expressionLanguage-5.0/io.openliberty.expressionLanguage-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonb-3.0/io.openliberty.jsonb-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonbContainer-3.0/io.openliberty.jsonbContainer-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonp-2.1/io.openliberty.jsonp-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsonpContainer-2.1/io.openliberty.jsonpContainer-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.1/io.openliberty.restfulWS-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/fat/src/com/ibm/ws/concurrent/mp/fat/jakarta/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/WEB-INF/beans.xml
  dev/io.openliberty.data.internal_fat/bnd.bnd
  dev/io.openliberty.data.internal_fat/publish/files/internalFeatures/data-1.0.mf
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.template.fat/server.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/server.xml
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
Labels: CLA Signed

#21741 change internal representation to a long
  dev/com.ibm.ws.dynacache/src/com/ibm/ws/cache/TimeLimitDaemon.java
Labels: CLA Signed

#21544 Add debug information for MpHealth Semeru JDK CDI TCK failure
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/services/impl/HealthCheck31CDIBeanInvokerImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat_tck/publish/servers/Health31TCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/publish/servers/Health40TCKServer/bootstrap.properties
Labels: CLA Signed

#21749 Temporarily disabling OT test
  dev/com.ibm.ws.opentracing.1.x_fat/fat/src/com/ibm/ws/testing/opentracing/test/FATMPOpenTracing.java
Labels: noproductcode, CLA Signed

#21760 Jakarta Security: Fix OIDC feature manifests for proper bundles
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectClient1.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectServer1.0.internal.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectServer1.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectServer1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.socialLogin1.0.internal.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.socialLogin1.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.socialLogin1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
Labels: CLA Signed, team:Security SSO

#21720 Remove beta fence for timed log rollover
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverbootstrap/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/jvm.options
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/AccessLogger.java
Labels: CLA Signed, target:22008

#21746 Disable beta-guard
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.ConsoleLogServer/jvm.options
  dev/com.ibm.ws.logging.json_fat/publish/servers/com.ibm.ws.logging.json.MessagesLogEnvServer/jvm.options
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils_JSON.java
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/LogstashServer/jvm.options
Labels: CLA Signed

#21756 Issue #21735: Tolerate pause of MDB during server stop
  dev/com.ibm.ws.ejbcontainer.mdb/src/com/ibm/ws/ejbcontainer/mdb/internal/MessageEndpointFactoryImpl.java
Labels: in:EJB Container, team:Blizzard, CLA Signed

#21778 Fix telemetry internal bundle
  dev/io.openliberty.microprofile.telemetry.internal/bnd.bnd
Labels: CLA Signed

#21702 Retry results check
  dev/com.ibm.ws.wsat.recovery_fat.single/fat/src/com/ibm/ws/wsat/fat/SingleRecoveryTest.java
Labels: noproductcode, CLA Signed

#21725 Avoid possible deadlock on checkpoint restore.
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/CpuInfo.java
Labels: CLA Signed

#21752 Port license changes from https://issues.redhat.com/browse/RESTEASY-3161
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/AsyncWriterInterceptor.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/AsyncWriterInterceptorContext.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/spi/AsyncWriterInterceptor.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/spi/AsyncWriterInterceptorContext.java
Labels: CLA Signed

#21771 Added clockSkew for MP JWT 2.1 for Issue #21187
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/MpConfigProperties.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
Labels: CLA Signed

#21723 fix 291296 to skip OSX JDK
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfBspTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf/fat/src/com/ibm/ws/wssecurity/fat/cxf/sample/CxfInteropX509Tests.java
Labels: noproductcode, CLA Signed

#21636 Test failures in 'com.ibm.ws.jpa.tests.spec20_fat'
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_POPULATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_POPULATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_DEFAULT_POPULATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_POPULATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_POPULATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_HIBERNATE_POPULATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_POPULATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_POPULATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ddl/WEB-INF/classes/JPA_OLGH21204_OPENJPA_POPULATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20CacheServer/database.xml
  dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20CacheServer/server.xml
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh10515/ddl/WEB-INF/classes/OLGH10515_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_HSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_INFORMIX.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_CREATE_SYBASE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_HSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_INFORMIX.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_MYSQL.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/ddl/WEB-INF/classes/OLGH16686_DROP_SYBASE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/src/com/ibm/ws/jpa/olgh16686/model/ElemCollEmbedTemporalOLGH16686.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/src/com/ibm/ws/jpa/olgh16686/model/ElemCollEntityOLGH16686.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh16686/src/com/ibm/ws/jpa/olgh16686/testlogic/JPATestOLGH16686Logic.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/vehicle/web/AbstractDatabaseManagementServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#21780 Bnd and Eclipse updates from recent changes
  dev/io.openliberty.jakarta.servlet.jsp.tags.3.0.internal/bnd.bnd
  dev/io.openliberty.jstl.2.0.facade/.project
  dev/io.openliberty.pages.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/.classpath
Labels: CLA Signed, team:Performance

#21559 21541 Reintroduce 21411: Artifact error message updates
  dev/com.ibm.ws.artifact.equinox.module/src/com/ibm/ws/artifact/equinox/module/internal/ModuleBundleFile.java
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/FileArtifactNotifier.java
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileContainerFactory.java
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileEntry.java
  dev/com.ibm.ws.artifact.loose/src/com/ibm/ws/artifact/loose/internal/LooseArtifactNotifier.java
  dev/com.ibm.ws.artifact.overlay/bnd.bnd
  dev/com.ibm.ws.artifact.overlay/resources/com/ibm/ws/artifact/overlay/internal/resources/ArtifactOverlayMessages.nlsprops
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/DirectoryBasedOverlayContainerImpl.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/DirectoryBasedOverlayNotifier.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/OverlayContainerFactoryImpl.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/package-info.java
  dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/NotABundleResourceURLConnection.java
  dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/WSJarURLStreamHandler.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileArtifactNotifier.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerFactory.java
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
  dev/com.ibm.ws.artifact/src/com/ibm/wsspi/artifact/DefaultArtifactNotification.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/CpuInfo.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/FileUtils.java
Labels: in:Kernel/Bootstrap, ID reviewed, CLA Signed, L2 Reviewed

#21762 Force shutdown after test
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
Labels: noproductcode, CLA Signed

#21791 Add test that injects the Config object to an early CDI bean
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPConfigTest.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/ApplicationScopedOnCheckpointBeanWithConfigObject.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/MPConfigServlet.java
Labels: noproductcode, CLA Signed

#21784 testWebDDManagedExecutorDefinition LPContextService not available
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21687 Created an application for testing rest client proxy with checkpoint
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RESTclientTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/AlternateApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/AlternateEndpoint.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ClientApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ClientEndpoints.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/RESTclient.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ServerApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ServerEndpoint.java
Labels: noproductcode, CLA Signed

#21727 Updated FeautureUtility so if there is a connection reset issue the a…
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
Labels: noproductcode, CLA Signed

#21742 Remove extra call to criu from the bin/server script.
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed, CRIU

#21767 update com.ibm.ws.jaxrs.2.1.client_fat tests to include OS/400 when checking if the test is running on z/OS or not
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CXFRxInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CompletionStageRxInvokerTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/JerseyRxInvokerTestServlet.java
Labels: in:JAX-RS, noproductcode, test bug, CLA Signed

#21133 Updated featureUtility InstallUtils to fix NPE issue
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallUtils.java
Labels: CLA Signed

#21807 Fixed copyright headers
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ClientEndpoints.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/RESTclient.java
Labels: noproductcode, CLA Signed

#21754 Clear logs mark in logging JSON FAT
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JSONEventsTest.java
Labels: noproductcode, CLA Signed

#21800 Update JPA Query FAT for changes needed to run on DB2 on zOS
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh14137/ddl/WEB-INF/classes/JPA_OLGH14137_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17369/ddl/WEB-INF/classes/JPA_OLGH17369_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17373/ddl/WEB-INF/classes/JPA_OLGH17373_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17376/ddl/WEB-INF/classes/JPA_OLGH17376_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17376/ddl/WEB-INF/classes/JPA_OLGH17376_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17407/ddl/WEB-INF/classes/JPA_OLGH17407_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17407/ddl/WEB-INF/classes/JPA_OLGH17407_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19185/ddl/WEB-INF/classes/JPA_OLGH19185_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19185/ddl/WEB-INF/classes/JPA_OLGH19185_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/ddl/WEB-INF/classes/JPA_OLGH19342_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/ddl/WEB-INF/classes/JPA_OLGH19342_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/ddl/WEB-INF/classes/JPA_OLGH19998_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/ddl/WEB-INF/classes/JPA_OLGH19998_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/src/com/ibm/ws/jpa/olgh19998/ejb/TestOLGH19998_EJB_SFEx_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/src/com/ibm/ws/jpa/olgh19998/ejb/TestOLGH19998_EJB_SF_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/src/com/ibm/ws/jpa/olgh19998/ejb/TestOLGH19998_EJB_SL_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/src/com/ibm/ws/jpa/olgh19998/web/TestOLGH19998Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh20890/ddl/WEB-INF/classes/JPA_OLGH20890_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh20890/ddl/WEB-INF/classes/JPA_OLGH20890_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh8014/ddl/WEB-INF/classes/JPA_OLGH8014_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh8014/ddl/WEB-INF/classes/JPA_OLGH8014_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_DEFAULT_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_OPENJPA_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat/fat/src/com/ibm/ws/jpa/tests/spec10/query/RepeatWithJPA21Hibernate.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#21792 com.ibm.ws.ui_rest_fat test problem
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/CatalogPersistenceTest.java
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/FeatureToolServiceTest.java
Labels: noproductcode, CLA Signed

#21610 Issue #21609: Fix test failure in windows service bucket
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartAsServiceTest.java
Labels: noproductcode, CLA Signed

#21787 Updates from review comments from PR #21076
  dev/com.ibm.ws.session/src/com/ibm/ws/session/AbstractHttpSessionFacade.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/AbstractSessionData.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/HttpSessionFacade.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionData.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/http/AbstractHttpSession.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/http/HttpSessionImpl.java
  dev/com.ibm.ws.session/src/com/ibm/wsspi/session/ISession.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/converged/WsHttpSessionFacade.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/wsspi/sip/converge/ConvergedHttpSessionImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/IHttpSession.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionFacadeImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionImpl.java
  dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/HttpSessionFacade60.java
  dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/SessionData60.java
  dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/http/HttpSessionImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/session/impl/HttpSessionContextImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/session/impl/WCHttpSessionImpl60.java
Labels: CLA Signed, team:Performance

#21819 Wrap Jakarta Security 3.0 annotations for issue #21155
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/identitystore/ELHelper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal/.gitignore
  dev/io.openliberty.security.jakartasec.3.0.internal/.project
  dev/io.openliberty.security.jakartasec.3.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/ClaimsDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/JakartaSec30Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/LogoutDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdProviderMetadataWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/ClaimsDefinitionWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/LogoutDefinitionWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/OpenIdProviderMetadataWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/TestClaimsDefinition.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/TestLogoutDefinition.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/ClaimsMappingConfig.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/ClientManager.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/LogoutConfig.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/OidcClientConfig.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/OidcProviderMetadata.java
Labels: CLA Signed

#21774 Issue #20452: Add tests for the new MethodReference APIs
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/.classpath
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50MethodReferenceTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_methodReferenceServer/.gitignore
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_methodReferenceServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_methodReferenceServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50MethodReferenceTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50MethodReferenceTest.war/src/io/openliberty/el50/fat/method/reference/servlet/EL50MethodReferenceServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#21823 experiment with version
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Product.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/DataPersistence.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21806 PR for Issue 21766: Do not make BCL calls for public clients with HTTP BCL URIs
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidator.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelperTest.java
Labels: CLA Signed, team:Security SSO

#21803 Ensure blob data is correctly handled by Oracle driver
  dev/com.ibm.ws.jdbc_fat_oracle/build.gradle
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/resources/data/myDataFile.txt
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21788 Update the Microprofile Rest Client TCK FAT projects
  dev/com.ibm.ws.microprofile.graphql_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
Labels: in:JAX-RS, noproductcode, CLA Signed

#21829 update github actions build
  .github/workflows/openliberty-ci.yml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, GitHub Build

#21786 Debug to identify the returned CPUInfoAccessor
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/CpuInfo.java
Labels: CLA Signed

#21833 Add verbose GC for Win machine test debug on LDAP KRB5 bucket
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/publish/servers/com.ibm.ws.security.registry.ldap.fat.krb5.base/jvm.options
Labels: noproductcode, CLA Signed, team:Wendigo East

#21781 Deliver Social Client Backchannel Logout tests plus some test updates
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BackChannelLogoutCommonTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/BackChannelLogout_RegisterClients.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/Constants.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/SkipIfSocialClient.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/client_configTests_filters.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oidcClient_configTests.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oidcProvider_configTests.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oidcProvider_configTests_notLocalStore.xml
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestServer.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTest.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/test-applications/oauthclient/resources/refresh.jsp
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/bnd.bnd
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/gradle.properties
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/files/serversettings/socialClientFeatures.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/files/serversettings/socialClient_configTests.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/files/serversettings/socialClient_httpMethods.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/files/serversettings/socialClient_logoutTokenValidation.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/bootstrap.properties
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/configs/social_server_basicTests.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/configs/social_server_basicTests_false.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/configs/social_server_basicTests_true.xml
Labels: CLA Signed, team:Security SSO, test delivery

#21834 Temporarily add EJB trace for RTC 289803
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/server.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21799 Temporarily disable EE10 tests for WSAT
  dev/com.ibm.ws.wsat.common_fat/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.concurrent_fat/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.2/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.3/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.4/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.5/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.2/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.single/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.assertion/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.db/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.db_optional/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.dbs/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.dbs_optional/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.multi/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/com.ibm.ws.wsat_fat.ssl/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#21795 retry test status checks
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.wsat.recovery_fat.single/fat/src/com/ibm/ws/wsat/fat/SingleRecoveryTest.java
Labels: CLA Signed

#21710 Fix Jakarta Rest TCK issues when running EE10
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/concurrent/LibertyRestfulWSThreadContextImpl.java
Labels: CLA Signed

#21813 Remove CDIProvider services file and move bnd to common project
  dev/io.openliberty.jakarta.cdi.4.0/.classpath
  dev/io.openliberty.jakarta.cdi.4.0/.gitignore
  dev/io.openliberty.jakarta.cdi.4.0/.project
  dev/io.openliberty.jakarta.cdi.4.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.cdi.4.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.cdi.4.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.cdi.4.0/resources/META-INF/services/jakarta.enterprise.inject.spi.CDIProvider
  dev/io.openliberty.jakarta/cdi.4.0.bnd
Labels: CLA Signed

#21765 mpOpenApi-1.x: Split Accept header before matching
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/OpenAPIServlet.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ContentTypeTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
Labels: CLA Signed

#21835 LTPATokenizer fixes
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenizer.java
Labels: bug, in:Security, team:Core Security

#21650 Issue #20419: Servlet 6 disable ability to enable X-Powered-By
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/build.gradle
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60XPoweredByHeaderTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/SimpleTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_xPoweredByHeaderTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_xPoweredByHeaderTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SimpleTest.war/src/simpletest/servlets/TestServlet.java
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 ReviewNotRequired, jakartaEE10

#21838 Additional log mark reset for ACME fat
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeConfigVariationsTest.java
Labels: noproductcode, CLA Signed, team:Core Security

#21836 Autoclose context in JMS2AsyncSend.testJMS2TransactionAndListener
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSend.java
Labels: noproductcode, CLA Signed

#21851 Fix EJB FAT synchronization issue
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/ejb/CheckpointStatistics.java
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#21859 Fix to multiple protocols with the IBM JDK
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLLinkConfig.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
Labels: CLA Signed

#21856 Security configuration problem on FAT bucket is resolved
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFNegativePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFNegativePropertiesTestServer/server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFPositivePropertiesTestServer/server.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#21854 Update HttpUtils to use response HttpEntity as message for non-200 responses
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
Labels: CLA Signed, team:Security SSO

#21758 Update connectors-2.1 features
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.connectorsInboundSecurity-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.appserver.connectors-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.1/io.openliberty.connectors-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectorsInboundSecurity-2.0/io.openliberty.connectorsInboundSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-10.0/io.openliberty.jakartaee-10.0.feature
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/ConnectionManagerMBeanTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/DependantApplicationTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/JCATest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr/server.xml
  dev/com.ibm.ws.jca_fat_configprops/bnd.bnd
  dev/com.ibm.ws.jca_fat_configprops/fat/src/com/ibm/ws/jca/fat/configprops/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE10Action.java
  dev/io.openliberty.jakarta/connector.2.1.bnd
  dev/io.openliberty.jakarta/connectors.2.1.bnd
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/wlp-jakartaee-transform/rules/jakarta-xml-dd.properties
Labels: team:Zombie Apocalypse, CLA Signed, GitHub Build

#21848 Add connection retries in tx test code
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/Simple2PCCloudServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
Labels: noproductcode, CLA Signed

#21861 Converting RESTclient test application to Java EE 8
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/AlternateApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/AlternateEndpoint.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ClientApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ClientEndpoints.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/RESTclient.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ServerApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/restClient/src/restClient/ServerEndpoint.java
Labels: noproductcode, CLA Signed

#21875 Remove unused class
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/PersistedConfigManager.java
Labels: CLA Signed

#21877 Handle extra Timed out msg during server start retry
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestServer.java
Labels: test bug, CLA Signed, team:Security SSO

#21870 Add trace and additional retry on MongoDB CustomStore setup
  dev/com.ibm.ws.security.oauth_test.custom_servlets/test-applications/oAuth20MongoSetup/src/web/oAuth20MongoSetup.java
Labels: noproductcode, CLA Signed, team:Security SSO

#21881 mpOpenAPI: lazily initialize selection config
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ApplicationRegistry.java
Labels: CLA Signed

#21885 asynchronous notifications cause unexpected order
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/PublisherImpl.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21888 Fix missed GSON references
  dev/com.ibm.websphere.appserver.features/visibility/public/adminCenter-1.0/com.ibm.websphere.appserver.adminCenter-1.0.feature
  dev/com.ibm.ws.security.fat.common.backchannelLogout/bnd.bnd
  dev/com.ibm.ws.security.oauth.oidc_fat.common/build.gradle
  dev/com.ibm.ws.security.oauth_test.servlets/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.backchannelLogout/bnd.bnd
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/bnd.bnd
  dev/com.ibm.ws.ui/bnd.bnd
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/build.gradle
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerInventory/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerSystem/server.xml
Labels: CLA Signed, team:Security SSO

#21876 PR for Issue 21159: Refactoring work for sending OIDC authorization request
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/com.ibm.websphere.appserver.socialLogin-1.0.feature
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/crypto/HashUtils.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/OidcClientAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ClientConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/HashUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcSessionUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/HashUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequestTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequestUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/OidcUrlNotHttpsException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/OidcClientStorageConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/OidcCookieUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/Utils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/OidcCookieUtilsTest.java
Labels: CLA Signed, team:Security SSO

#21676 Remove creation of default key.p12 in SAML FATs
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/files/serversettings/BasicRegistry.xml
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/files/serversettings/BasicRegistry_withExtraUsers.xml
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/files/serversettings/BasicRegistry_withoutIDPUsers.xml
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/files/serversettings/BasicRegistry_withIDPGroup.xml
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/common/BasicSAMLTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#21894 Enable trace if task threads fail to stop: concurrent_persistent_fat_failoverserv1
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/publish/servers/com.ibm.ws.concurrent.persistent.fat.failover1serv/bootstrap.properties
Labels: noproductcode, CLA Signed

#21879 Fix obtaining the refresh_token for the bcl uri omitted tests
  dev/com.ibm.ws.security.oauth.oidc_fat.common/common-classes/src/web/BaseServlet.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonValidationTools.java
Labels: noproductcode, CLA Signed, team:Security SSO

#21611 21243_bootstrap_upgrade.
  dev/ant_build.js/build.gradle
  dev/ant_build.js/public_imports/internal_imports/bootstrap.xml
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/css/charts.css
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/graphs/logAnalytics/charts/Chart.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/graphs/logAnalytics/templates/LogAnalyticsGraph.html
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/css/editor.css
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/dev/jshintglobals.json
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/core.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/editorForm.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/editorTree.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/serverExplorer.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/settings.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/customizations/featureListCustomization.js
Labels: CLA Signed

#21871 Replay completion properly
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/ProtocolImpl.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
Labels: CLA Signed

#21912 Adjust attributeCache timeout for LdapRegressionTest
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
Labels: noproductcode, CLA Signed

#21909 Add longer DS timeout for bundle startup in JASPI FAT
  dev/com.ibm.ws.security.jaspic_fat/publish/servers/com.ibm.ws.security.jaspic11.fat/bootstrap.properties
Labels: noproductcode, CLA Signed, team:Core Security

#21897 experiment with distinct, collection types, and various other improvements
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Select.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/DataPersistence.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/QueryHandler.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21904 errant config tests for Concurrency resource definitions
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyErrorTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta.error/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestError/src/test/jakarta/concurrency/web/error/config/ResourceDefinitionErrorServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestError/src/test/jakarta/concurrency/web/error/executordef/ManagedExecutorDefinitionErrorServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestError/src/test/jakarta/concurrency/web/error/scheduledexecutordef/ManagedScheduledExecutorDefinitionErrorServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21906 Fix test bug 291351
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/BellPropertiesTest.java
Labels: noproductcode, test bug, team:OSGi Infrastructure, CLA Signed
