Repository OpenLiberty/open-liberty, pull requests merged in 2022-08, with the labels that each got.

#21911 Change BELL SPI visibility attribute name to spiVisibility
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_cs.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_de.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_es.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_fr.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_hu.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_it.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ja.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ko.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_pl.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_pt_BR.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ro.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ru.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_zh.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_zh_TW.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/metatype/bells.xml
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
  dev/com.ibm.ws.classloading.bells_fat/publish/servers/bell_spi_server/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Bell.java
Labels: ID Required, ID reviewed, team:OSGi Infrastructure, CLA Signed

#21905 Address test failure in RTC 291253, where sessioncache-1.0 was not be…
  dev/io.openliberty.jcache.internal_fat.hazelcast/bnd.bnd
  dev/io.openliberty.jcache.internal_fat.infinispan/bnd.bnd
Labels: noproductcode, CLA Signed, team:Wendigo East

#21908 Updating jca tests to not run EE10 features on Java 8
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat_configprops/fat/src/com/ibm/ws/jca/fat/configprops/FATSuite.java
Labels: noproductcode, CLA Signed

#21910 Add a longer featureList wait on Windows for FATs
  dev/fattest.simplicity/src/componenttest/depchain/FeatureList.java
Labels: noproductcode, CLA Signed

#21926 fix typos in blog issue templates
  .github/ISSUE_TEMPLATE/blog_post_beta.md
  .github/ISSUE_TEMPLATE/blog_post_ga_release.md
Labels: CLA Needed, noproductcode

#21933 update .com.squareup.okio-jvm/.project
  dev/io.openliberty.com.squareup.okio-jvm/.project
Labels: noproductcode, CLA Signed

#21922 Add SSL init timeouts
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/publish/clients/com.ibm.ws.ejbcontainer.remote.client.fat.clientInjection/client.xml
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.client.fat.serverInjection/server.xml
Labels: noproductcode, CLA Signed

#21731 Update saml web sso feature to use opensaml v3
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
  dev/com.ibm.ws.org.apache.santuario.xmlsec.2.2.0/bnd.overrides
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/common/BasicEncryptionTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/common/PkixSAMLTests.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLMisc1ConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/SAMLSSLConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigNoReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedSSLConfigWithReconfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlAPITests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlBasicTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlPkixTests.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/common/BasicSAMLTests.java
  dev/com.ibm.ws.security.saml.wab/bnd.bnd
  dev/com.ibm.ws.security.saml.wab/test/com/ibm/ws/security/saml/sso20/web/EndpointServicesTest.java
  dev/com.ibm.ws.security.saml.wab/test/com/ibm/ws/security/saml/sso20/web/EndpointServletTest.java
Labels: CLA Signed

#21617 move SRTServletRequestThreadData from threadlocal to instance for performance
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/srt/SRTServletRequest31.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTConnectionContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequestThreadData.java
Labels: CLA Signed, team:Performance, performance

#21931 tolerate CWWKC1503W from DemoTimerTest
  dev/com.ibm.ws.concurrent.persistent_fat_demo_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/demo/timers/DemoTimerTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#16188 Calculate system packages
  dev/com.ibm.ws.collector.manager/bnd.bnd
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapManifest.java
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_1.6.0.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_1.7.0.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_1.8.0.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_10.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_11.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_12.properties
  dev/com.ibm.ws.kernel.boot/resources/OSGI-OPT/websphere/system-packages_9.properties
  dev/com.ibm.ws.kernel.boot_test/test/com/ibm/ws/kernel/boot/internal/BootstrapManifestTest.java
Labels: CLA Signed

#21936 MP Fault Tolerance 1.x: Fix timeout cancellation race condition
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/src/com/ibm/ws/microprofile/faulttolerance/executor/impl/TimeoutImpl.java
  dev/com.ibm.ws.microprofile.faulttolerance.1.0/src/com/ibm/ws/microprofile/faulttolerance/executor/impl/package-info.java
Labels: CLA Signed

#21932 Updates to support new keyring prefixes
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/WSKeyStore.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/test/com/ibm/ws/ssl/config/WSKeyStoreTest.java
Labels: CLA Signed

#21942 Fix NPE when executorSrvc gets nulled out on shutdown
  dev/com.ibm.ws.webserver.plugin.runtime/src/com/ibm/ws/webserver/plugin/runtime/listeners/GeneratePluginConfigListener.java
Labels: CLA Signed

#21928 testPollIntervalStable insufficient attempts
  dev/com.ibm.ws.concurrent.persistent_fat_auto_pollinterval/fat/src/com/ibm/ws/concurrent/persistent/fat/autonomicalpolling1serv/AutonomicalPolling1ServerTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21938 tests for resource definitions with invalid ContextService
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestError/src/test/jakarta/concurrency/web/error/config/ResourceDefinitionErrorServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21925 tolerate transaction timeouts in testRetryFourWithOneSkipFailWithFailoverEnabled
  dev/com.ibm.ws.concurrent.persistent_fat_retry/test-applications/retrytest/src/web/PersistentRetryTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21921 testFailingTaskAndAutoPurgeFENoPolling does not count some failures
  dev/com.ibm.ws.concurrent.persistent_fat_errorpaths/test-applications/persistenterrtest/src/web/PersistentErrorTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21935 Add app manager traces to jsf23 fat
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/faces30Server/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIConfigByACPServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIConfigByACPServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIFacesInMetaInfServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIFacesInMetaInfServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIFacesInWebXMLServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIFacesInWebXMLServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIGeneralServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CDIInjectionServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ClassLevelBeanValidationServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23CommandScriptServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ComponentSearchServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23EvalScriptsServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ExternalContextStartupShutdownServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23FaceletVDLServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23FacesDataModelServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23GeneralServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23IterableSupportServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23MapSupportServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23SelectOneRadioGroupServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23UIRepeatConditionServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23UISelectManyServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ViewParamertersServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23ViewResourceServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23WebSocketServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23jpa22Server/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsfFeatureConflictServer/bootstrap.properties
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#21943 Fix test for windows
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
Labels: noproductcode

#21939 Fix build break in RTC 291008. Wait for HTTPS endpoint to startup aft…
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheLtpaLoggedOutCookieCacheServerRestartTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#21940 Issue 21613: GA the passwordUtilities-1.1 feature.
  dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.1/com.ibm.websphere.appserver.passwordUtilities-1.1.feature
Labels: CLA Signed, team:Wendigo East

#21946 Move checkpoint feature to beta
  dev/com.ibm.websphere.appserver.features/visibility/public/checkpoint-1.0/io.openliberty.checkpoint-1.0.feature
Labels: CLA Signed

#21889 Fix app validation logic for started servers
  dev/com.ibm.ws.ejbcontainer.bindings_fat/fat/src/com/ibm/ws/ejbcontainer/bindings/fat/tests/ServerXMLBindingTest.java
  dev/com.ibm.ws.jpa.tests.ormdiagnostics_3.0_fat/fat/src/com/ibm/ws/jpa/ormdiagnostics/tests/TestExample_EAR.java
  dev/com.ibm.ws.jpa.tests.ormdiagnostics_3.0_fat/fat/src/com/ibm/ws/jpa/ormdiagnostics/tests/TestExample_WAR.java
  dev/com.ibm.ws.jpa.tests.ormdiagnostics_fat/fat/src/com/ibm/ws/jpa/ormdiagnostics/tests/TestExample_EAR.java
  dev/com.ibm.ws.jpa.tests.ormdiagnostics_fat/fat/src/com/ibm/ws/jpa/ormdiagnostics/tests/TestExample_WAR.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FaceletVDLTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/JSFApplication.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/RealFlushTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPITestUtil.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleRealmTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleDBRunAsTest.java
  dev/com.ibm.ws.security.javaeesec_fat.4/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleTestProtectedServlet.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat/FeatureTest.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/FATHelper.java
  dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCResponseHeadersTest.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ShrinkHelper.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
Labels: noproductcode, CLA Signed

#21882 Remove concurrency dependency in restfulWSClient 3.1 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-10.0/io.openliberty.jakartaee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-10.0/io.openliberty.webProfile-10.0.feature
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/AbstractTest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRS20ClientAsyncInvokerTestWithConcurrency.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest2/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest2/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRS20ClientAsyncInvokerTest2/server.xml
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21executors/src/jaxrs21executors/MyRequestFilter.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21executors/src/jaxrs21executors/MyResponseFilter.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/resources/META-INF/services/org.jboss.resteasy.spi.concurrent.ThreadContext
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/org/jboss/resteasy/common/client/LibertyResteasyClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/org/jboss/resteasy/common/client/OsgiFacade.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/AsyncClientExecutorService.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/concurrent/LibertyRestfulWSThreadContextImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/concurrent/package-info.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/internal/AsyncClientExecutorHelper.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/internal/ClientAsyncTaskWrapperComponent.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/internal/ThreadContextAsyncTaskWrapper.java
  dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/org/jboss/resteasy/common/client/OsgiFacade.java
Labels: CLA Signed

#21963 Make repeat test LITE for checkpoint FAT
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RESTclientTest.java
Labels: noproductcode, CLA Signed

#21949 Issue21948-FixFailingEJBTest
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnServletToEJBRunAsTest.java
Labels: noproductcode, CLA Signed

#21736 Add overlay for JAXB Marshaller/Unmarshaller pooling in CXF
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBDataBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataReaderImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataWriterImpl.java
Labels: CLA Signed

#21951 Issue21950-FixBuildBreakEJBTest
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnMergeConflictXMLBindingsTest.java
Labels: noproductcode, CLA Signed

#21959 Fix of internal server error in property setting test
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/wsfeatures/client/WSAPropertyTestServlet.java
Labels: in:Web Services, team:Bobcats

#21947 Issue21920-FixEBJFatTest
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnA01Test.java
Labels: noproductcode, CLA Signed

#21954 Misc small refactor cleanup for OIDC Jakarta work
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/crypto/HashUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/HashUtilsTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/OidcCookieUtilsTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/utils/UtilsTest.java
Labels: noproductcode, CLA Signed, team:Security SSO

#21967 Change to use private features to allow toleration of resteasy cdi ee…
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpRestClient.internal.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpRestClient.internal.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-3.0/io.openliberty.mpRestClient-3.0.feature
  dev/io.openliberty.org.jboss.resteasy.mprestclient/bnd.bnd
Labels: CLA Signed

#21965 Add user registry and keystore to server config
  dev/io.openliberty.microprofile.internal_fat/publish/servers/MPCompatibleServer/MP40andEE9.xml
Labels: noproductcode, CLA Signed

#21989 Telemetry 1.0
  dev/io.openliberty.io.opentelemetry.internal/bnd.bnd
  dev/io.openliberty.io.opentelemetry/bnd.bnd
Labels: CLA Signed

#21988 Pass type to ContextResolver for Jsonb for JAXRS
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/test-applications/jsonbContextResolverApp/src/jaxrs21/fat/jsonbcontextresolver/JsonbContextResolver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs21/providers/json/JsonBProvider.java
  dev/io.openliberty.restfulWS30.jsonb20provider/src/io/openliberty/restfulWS30/jsonb20provider/JsonBProvider.java
Labels: in:JAX-RS, CLA Signed, team:Performance

#21966 Saf keyring updates to the security utility
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/utils/SAFEncryptionKey.java
Labels: CLA Signed

#21964 result and aggregate functions
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductCount.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Result.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Select.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/QueryHandler.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21961 increase allowed ffdc retries and timeout, and remove some dead code
  dev/com.ibm.ws.jca_fat_regr.cfg.prop/fat/src/suite/r80/base/jca16/ann/ConfigPropertyValidatorTest.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/suite/r80/base/jca16/ann/ConfigPropertyMergeActionTest.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/suite/r80/base/jca16/ann/ConfigPropertyValidatorTest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#21982 Create common SecuritySSLUtils class for SSO code to use
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/ssl/NoSSLSocketFactoryException.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/ssl/SecuritySSLUtils.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/ssl/package-info.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/HttpClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
Labels: CLA Signed, team:Security SSO

#21732 Servlet 6.0 Request Connection ID Part2
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInboundConnectionExtended.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/request/IRequest60Impl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/srt/SRTServletConnection.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/srt/SRTServletRequest60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/websphere/servlet60/IRequest60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SimpleTest.war/src/simpletest/servlets/TestServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#21987 Fix test bug 291759
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/TemplateTests.java
Labels: noproductcode, CLA Signed

#21822 OidcClientCore Storage Subsystem - CookieBased
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/JakartaOIDCConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/CookieBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/SessionBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/Storage.java
Labels: CLA Signed, team:Security SSO, jakartaEE10

#21960 Add filtering mechanism for known test matches
  dev/ant_build.js/lib/bootstrap/bootstrap-5.1.3.jar
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode

#21999 Update eclipse and bnd settings to get things building right again
  .github/test-categories/JCA
  .github/test-categories/QUARANTINE
  dev/cnf/build.bnd
  dev/com.ibm.ws.jca_fat_regr.cfg.prop/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_regr.rar.beanVal/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jca_fat_regr/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat/.classpath
  dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal/.settings/org.eclipse.jdt.core.prefs
Labels: CLA Signed, team:Performance, GitHub Build

#22000 Issue21988-FixJacc15BuildBreak
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/BasicAuthTest.java
  dev/com.ibm.ws.webcontainer.security_test.servlets/src/com/ibm/ws/webcontainer/security/test/servlets/TestConfiguration.java
Labels: noproductcode, CLA Signed

#21839 Bcl saml tests
  .github/test-categories/SECURITY_BACKCHANNELLOGOUT_1
  .github/test-categories/SECURITY_BACKCHANNELLOGOUT_2
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BackChannelLogoutCommonTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/AfterLogoutStates.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/Constants.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.classpath
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.project
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/bnd.bnd.disabled
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/gradle.properties
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/files/serversettings/saml_authorize.xml
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/configs/op_server_basicTests.xml
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/configs/op_server_basicTests_false.xml
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/configs/op_server_basicTests_true.xml
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/jvm.options
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/bnd.bnd.disabled
Labels: noproductcode, CLA Signed, team:Security SSO, test delivery

#21980 Revert "Issue21950-FixBuildBreakEJBTest"
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnMergeConflictXMLBindingsTest.java
Labels: noproductcode, CLA Signed

#21913 add reset() to JSAdminService
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/admin/JsAdminService.java
  dev/com.ibm.ws.messaging.runtime/resources/com/ibm/ws/sib/admin/internal/CWSIDMessages.nlsprops
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/messaging/service/JsAdminServiceImpl.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/admin/internal/JsMainImpl.java
  dev/com.ibm.ws.messaging_test.fw/src/com/ibm/ws/sib/admin/impl/JsAdminServiceImpl.java
Labels: ID review not needed, CLA Signed, L2 Reviewed

#21898 AdminCenter accessibility fixes to login and preference pages
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/css/tablet.css
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/js/widgets/LibertyPrefs.js
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/js/widgets/templates/LibertyPrefs.html
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/login/login.css
Labels: CLA Signed

#22003 Fix JPA FAT framework build
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.1_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/build.gradle
Labels: noproductcode, CLA Signed

#21853 decode encoded passwords from properties file
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallLogUtils.java
Labels: CLA Signed

#22002 Fix test failure in RTC 290954.
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CachingProviderService.java
Labels: CLA Signed, team:Wendigo East

#21890 Skip SlowRequestTiming Warnings in RequestProbe JDBC FAT
  dev/com.ibm.ws.request.probe.jdbc_fat/fat/src/com/ibm/ws/request/probe/jdbc/fat/RequestProbeJDBCTest.java
  dev/com.ibm.ws.request.probe.jdbc_fat/fat/src/com/ibm/ws/request/probe/jdbc/fat/RequestProbeJDBCUnRegTDTest.java
Labels: noproductcode, CLA Signed

#22001 Delete obsolete bcl project
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.classpath
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.project
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/bnd.bnd.disabled
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/build.gradle
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/ClientConfigTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/CommonTests/BackChannelLogoutCommonTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/HttpMethodsTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/LogoutTokenCreationTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/LogoutTokenValidationTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/fat/src/com/ibm/ws/security/oidc_social/backchannelLogout/fat/ServerConfigTests.java
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/OPMisc.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/backchannelLogoutTestApp.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/client_logoutTokenValidation_filters.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/client_logoutTokenValidation_variables.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/formlogin_1.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/goodBasicRegistry.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/goodSSLSettings.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcClientFeatures.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcClient_httpMethods.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcClient_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcClient_validateLogoutTokenCreation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcProvider_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcProvider_validateLogoutTokenCreation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/oidcServerFeatures.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/socialClientFeatures.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/socialClient_httpMethods.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/files/serversettings/socialClient_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op/bootstrap.properties
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op/configs/op_server_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op/configs/op_server_validateLogoutTokenCreation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op/jvm.options
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/bootstrap.properties
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/configs/rp_server_httpMethod.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/configs/rp_server_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/configs/rp_server_validateLogoutTokenCreation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/jvm.options
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/bootstrap.properties
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/configs/social_server_httpMethod.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/configs/social_server_logoutTokenValidation.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/jvm.options
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/test-applications/backchannelLogoutTestApp/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/test-applications/backchannelLogoutTestApp/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/test-applications/backchannelLogoutTestApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.oidc.social_fat.backchannelLogout/test-applications/backchannelLogoutTestApp/src/com/ibm/ws/security/fat/backChannelLogoutTestApps/LogBackChannelLogout_logoutToken_Servlet.java
Labels: noproductcode, CLA Signed, team:Security SSO, test delivery

#21991 Add mpTelemetry fat bucket
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/hotadd/Telemetry10Servlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/resources/META-INF/microprofile-config.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/resources/permissions.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10/server.xml
Labels: CLA Signed

#21953 Move MPTelemetry-1.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.telemetry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
Labels: CLA Signed

#21883 changes to handling LTPAToken2
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAConfiguration.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTask.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPATokenizer.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2FactoryTest.java
Labels: in:Security, CLA Signed, team:Core Security

#22013 Process cxf.ignore.unsupported.policy correctly
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyEngineImpl.java
Labels: CLA Signed

#21978 Moving to 4.x version of http components for opensaml
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-2.6.feature
  dev/com.ibm.ws.org.apache.commons.httpclient/bnd.bnd
Labels: CLA Signed

#21976 Issue #21975: fix spelling of listener
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23GeneralTests.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/LibertyReadWriteListenerTest.war/src/com/ibm/ws/webcontainer/servlet_31_fat/libertyreadwritelistenertest/war/upgradeHandler/UpgradeHandlerTestServlet.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/collaborator/CollaboratorHelper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/servlet/IServletContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/servlet/ServletReferenceListener.java
Labels: in:Web Components, CLA Signed, team:Sirius

#21979 Added repeat test to test applications that use the checkpointFATServer
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BasicServletTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LogsVerificationTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/OSGiConsoleTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFATServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#21873 Split long running test suite - part 2
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest3.java
Labels: noproductcode, CLA Signed

#21818 Issue #21817: Use jar for classpath on zos
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: noproductcode, CLA Signed

#22034 add checkpoint jdbc fat
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/build.gradle
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/security/db2-keystore.p12
  dev/io.openliberty.checkpoint_fat/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/db2fat/src/io/openliberty/checkpoint/db2/web/DB2TestServlet.java
Labels: noproductcode, CLA Signed

#22052 Revert "JAX-B: Add xmlBinding-4.0 Impl and tests"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlBinding-4.0/io.openliberty.xmlBinding-4.0.feature
  dev/com.ibm.ws.jaxb_fat/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/FATSuite.java
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/LibertyJAXBTest.java
  dev/com.ibm.ws.jaxb_fat/test-applications/jaxbApp/src/jaxb/web/JAXBTestServlet.java
  dev/io.openliberty.jakarta.xmlBinding.4.0/.classpath
  dev/io.openliberty.jakarta.xmlBinding.4.0/bnd.bnd
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.classpath
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.gitignore
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.project
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlBinding.4.0.internal.tools/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlBinding.4.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlBinding.4.0.internal.tools/resources/META-INF/services/jakarta.xml.bind.JAXBContext
  dev/io.openliberty.xmlBinding.4.0.internal.tools/resources/META-INF/services/jakarta.xml.bind.JAXBContextFactory
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.classpath
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.project
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.xmlBinding.4.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.xmlBinding.4.0.internal_fat/bnd.bnd
  dev/io.openliberty.xmlBinding.4.0.internal_fat/build.gradle
  dev/io.openliberty.xmlBinding.4.0.internal_fat/fat/src/io/openliberty/xmlbinding40/fat/FATSuite.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/fat/src/io/openliberty/xmlbinding40/fat/LibertyJAXBRIContextTest.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/fat/src/io/openliberty/xmlbinding40/fat/LibertyThirdPartyJAXBImplContextTest.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_fat/bootstrap.properties
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_fat/schemaEE10.xml
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_fat/server.xml
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_thirdpartyimpl_fat/bootstrap.properties
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_thirdpartyimpl_fat/jvm.options
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_thirdpartyimpl_fat/schemaEE10.xml
  dev/io.openliberty.xmlBinding.4.0.internal_fat/publish/servers/jaxb_thirdpartyimpl_fat/server.xml
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/JAXBContextTestServlet.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/Image.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/Item.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/Items.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/ObjectFactory.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/PurchaseOrderType.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/ShippingAddress.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/package-info.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/utils/JAXBContextUtils.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/utils/JAXBXMLSchemaConstants.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/utils/StringSchemaOutputResolver.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/thirdPartyJaxbImplContextApp/src/jaxbimpl/thirdparty/web/ThirdPartyJAXBImplContextTestServlet.java
Labels: CLA Signed

#22042 address missing doPriv() in the updated samlWeb runtime
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/slo/SPInitiatedSLO.java
Labels: CLA Signed, team:Security SSO

#22029 Fix error with Telemetry Client Filter
  dev/io.openliberty.io.opentelemetry/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/cdi/OpenTelemetryProducer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/hotadd/PatchTestApp.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/hotadd/Telemetry10Servlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10/server.xml
Labels: CLA Signed

#22027 Fix test failure in RTC 291613.
  dev/io.openliberty.jcache.internal/resources/io.openliberty.jcache.internal/resources/JCacheMessages.nlsprops
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDynamicUpdateTest.java
Labels: CLA Signed, team:Wendigo East, L2 Reviewed

#22028 Add java 2 permission
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/test-applications/EjbLinkTest.ear/resources/META-INF/permissions.xml
Labels: noproductcode, CLA Signed

#21874 Split long running test suite - part 3
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicDBTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicDBTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicFSTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicFSTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.tx.jta_fat/fat/src/com/ibm/ws/tx/jta/test/FATSuite.java
Labels: noproductcode, CLA Signed

#21995 Minor fixes
  dev/ant_build.js/.gitignore
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-5.0/resources/l10n/io.openliberty.microProfile-5.0_de.properties
  dev/io.openliberty.com.squareup.okhttp/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.com.squareup.okhttp/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.com.squareup.okhttp/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.com.squareup.okio-jvm/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.com.squareup.okio-jvm/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.com.squareup.okio-jvm/.settings/org.eclipse.jdt.ui.prefs
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#22036 Add some extra tests in VisibilityTest and fix features that were wrong.
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.connectorsInboundSecurity-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jcache.internal-1.1.feature
Labels: CLA Signed, team:Performance

#22044 Update Jackson to 2.12.7
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.couchdb_fat/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson.jr/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson/bnd.bnd
  dev/io.openliberty.org.testcontainers/bnd.bnd
Labels: CLA Signed

#22045 Omit checkpoint image from test server archives
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#22030 Fix RequestTiming CN NLS message to switch variables positions
  dev/com.ibm.ws.request.timing/resources/com/ibm/ws/request/timing/internal/resources/LoggingMessages_zh.nlsprops
Labels: CLA Signed, L2 Reviewed

#22048 com.ibm.ws.ui_rest.fat test problems
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/ToolboxAPIv1Test.java
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/ToolboxPersistenceTest.java
Labels: noproductcode, CLA Signed

#22021 Skip testZeroTimeOut
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#22031 Update LDAPRegistryContextPoolNoConfigTest to use local LDAP instead of remote LDAP
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryContextPoolNoConfigTest.java
Labels: noproductcode, CLA Signed

#22062 Update abandon test to remove debug for now
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/BatchJobOperatorApiWithAppSecurityTest.java
Labels: noproductcode, test bug, CLA Signed

#21895 TokenAge for MP JWT 2.1 For Issue #21186
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/config/JwtConsumerConfig.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtConsumerConfigImpl.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/MicroProfileJwtConfig.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/MicroProfileJwtConfigImpl.java
Labels: CLA Signed

#22070 Switch groupid's of ibm ws rebundled jars for scanning
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
  dev/build.depScanner/src/io/openliberty/depScanner/Module.java
Labels: noproductcode, CLA Signed

#22050 xmlBinding-4.0: Change xmlBinding-4.0 to beta
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlBinding-4.0/io.openliberty.xmlBinding-4.0.feature
Labels: CLA Signed

#22069 Remove invalid ":" chacter from uri base in the bus id
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/JAXRSClientImpl.java
Labels: in:JAX-RS, CLA Signed

#22071 Fix performance regression when using XLXP with the new CXF level.
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBDataBinding.java
Labels: CLA Signed, team:Performance, performance

#22080 Restart the server before running the dynamic test
  dev/com.ibm.ws.security.authentication.filter_fat/fat/src/com/ibm/ws/security/authentication/filter/fat/DynamicAuthFilterTest.java
Labels: noproductcode, test bug, CLA Signed

#22079 22059 logging change
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/phase/PhaseInterceptorChain.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#22085 JAX-B: Remove Moxy as it's only needed for as a test dependency.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#22075 Issue22066-FixBuildBreakinDynamicJacc2
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnMergeConflictXMLBindingsInWarEarTest.java
Labels: noproductcode, CLA Signed

#22065 Issue22064-FixBuildBreakDynamicJacc
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/DynamicJACCFeatureTest.java
Labels: noproductcode, CLA Signed

#22086 Create internal xmlbinding 4.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectors-2.1.internal.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.xmlBinding.internal-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthentication-3.0/io.openliberty.appAuthentication-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistenceContainer-3.1/io.openliberty.persistenceContainer-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlBinding-4.0/io.openliberty.xmlBinding-4.0.feature
Labels: CLA Signed, team:Performance

#22098 Disable ConcurrentErrorTest app validation
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyErrorTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22094 update feature test for jca-2.1
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/AlternateFeatureNamesTest.java
Labels: team:Zombie Apocalypse

#22009 Clarify oracle URL property behavior
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed, L2 ReviewNotRequired

#21886 init oidcclientcore token subsystem
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/GenericOidcClientTests.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/HttpClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtilTest.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_usingSocialConfig_withDisplayNames.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicDiscoveryConfigTests.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/BadPostRequestException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/HttpConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtil.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponse.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtilWithTraceTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenRequestorTest.java
Labels: CLA Signed

#22107 testUpdateMultiple erroneous order
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22101 testRepositoryCustomMethods premature close of SubmissionPublisher
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/PublisherImpl.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22118 persistence 3.1 beta enablement miss
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectionManager1.0.internal.ee-10.0.feature
Labels: CLA Signed, team:Performance

#22024 Make mpConfig-3.0 compatible with EE10
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.0/io.openliberty.mpConfig-3.0.feature
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextPropActions.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoadersTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/OrdinalsForDefaultsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SharedLibTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/StressTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/FieldTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/Config12ConverterTests.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ConfigOrdinalServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/Config14Tests.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/FeatureUtilities.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/FeatureUtilities.java
Labels: CLA Signed, DO NOT MERGE

#22097 policy executor java 19 methods
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyTaskFuture.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyTaskFutureImpl.java
  dev/com.ibm.ws.threading_policy_fat/fat/src/com/ibm/ws/threading/policy/PolicyExecutorTest.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#22105 testAggregateFunctions intermittent empty set to clear
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#22104 Fix ArrayIndexOutOfBounds failure found in RTC 290630 test failure. A…
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jcache.internal/resources/io.openliberty.jcache.internal/resources/JCacheMessages.nlsprops
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CachingProviderService.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDynamicUpdateTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheOauth20AuthenticationCacheTest.java
  dev/io.openliberty.jcache.internal_fat.infinispan/bnd.bnd
  dev/io.openliberty.jcache.internal_fat.infinispan/build.gradle
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/docker/InfinispanContainer.java
Labels: ID reviewed, CLA Signed, team:Wendigo East

#22110 com.ibm.ws.ui_rest_fat: Add call to ignore expected error in CatalogPersistenceTest
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/CatalogPersistenceTest.java
Labels: noproductcode, CLA Signed

#22124 Revert "Make mpConfig-3.0 compatible with EE10"
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.0/io.openliberty.mpConfig-3.0.feature
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextPropActions.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoadersTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/OrdinalsForDefaultsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SharedLibTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/StressTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/FieldTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/Config12ConverterTests.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ConfigOrdinalServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/Config14Tests.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/FeatureUtilities.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/FeatureUtilities.java
Labels: CLA Signed

#22072 Add timedExit feature to rollover test server xmls
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverdisabled/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/server.xml
Labels: noproductcode, CLA Signed

#22117 align with jnosql removal of stereotype
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/DiscriminatorColumn.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/DiscriminatorValue.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Embeddable.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Entity.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Inheritance.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22128 Adjust Stateful cache timeout test
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulCacheWeb.war/src/com/ibm/ejb2x/base/cache/web/StatefulTranServlet.java
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#22126 Redeliver mpConfig-3.0 compatibility with MP6
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.0/io.openliberty.mpConfig-3.0.feature
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextPropActions.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoadersTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/OrdinalsForDefaultsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SharedLibTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/StressTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/cdiConfig.jar/src/com/ibm/ws/microprofile/appConfig/cdi/web/FieldTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.2_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2_fat/fat/src/com/ibm/ws/microprofile/config12/test/Config12ConverterTests.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ConfigOrdinalServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/ServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.3_fat/fat/src/com/ibm/ws/microprofile/config13/test/VariableServerXMLTest.java
  dev/com.ibm.ws.microprofile.config.1.4_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/Config14Tests.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/FeatureUtilities.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/FeatureUtilities.java
Labels: CLA Signed

#22037 Fix test failure in RTC 291270. It appears that even though Infinispa…
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/docker/InfinispanContainer.java
Labels: noproductcode, CLA Signed

#22099 Added repeat test rule to the timeout test class
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPFaultToleranceTimeoutTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/timeoutServer/server.xml
Labels: noproductcode, CLA Signed

#22068 Created a repeated test for LocalEJBTest class
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LocalEJBTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/bootstrap.properties
Labels: noproductcode, CLA Signed

#22131 Jakarta Mail 2.1 Implementation bundle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.classpath
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.gitignore
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.project
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/bnd.bnd
Labels: in:Web Services, team:Bobcats

#22116 update features for connectors-2.1 beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectors-2.1.internal.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.appserver.connectors-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.1/io.openliberty.connectors-2.1.feature
Labels: team:Zombie Apocalypse, CLA Signed

#22138 27547-RemovingFont.
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/fonts/BunueloCleanPro-Light.woff
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/fonts/BunueloCleanPro-SemiBold.woff
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
Labels: CLA Signed

#22088 Update mpOpenAPI-3.1 to have MP 6 compatibility
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-3.1/io.openliberty.mpOpenAPI-3.1.feature
  dev/com.ibm.ws.microprofile.openapi_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ContentTypeTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/EndpointAvailabilityTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/OpenApiActions.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ProxySupportTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/UICustomizationTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/annotations/AnnotationProcessingTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/filter/FilterConfigTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFive.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFour.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestSix.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestTwo.java
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/ApplicationProcessorServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/EndpointAvailabilityServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/FilterServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/ProxySupportServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/UICustomizationServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFive/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFour/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerOne/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerSix/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerThree/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/ApplicationProcessorTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/OpenApiActions.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/ApplicationProcessorServer/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeTestServer/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPITestServer/server.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/fat/src/io/openliberty/microprofile/openapi31/fat/tck/OpenAPITckTest.java
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#22141 Update mpRestClient-3.0 to tolerate MP 6 and EE 10
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-3.0.feature
  dev/com.ibm.ws.microprofile.rest.client_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicEJBTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagation12Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagationTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HostnameVerifierTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/MultiClientCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/PropsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/SseTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.basic.cdi/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.headerPropagation/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.multi.client.cdi/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.props/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.async/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.produceConsume/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.headerPropagation/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient12.jsonbContext/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient13.ssl/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient20.sse/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/basicClientApp/src/mpRestClient10/basic/BasicClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/handleresponsesApp/src/mpRestClient10/handleresponses/ClientTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/headerPropagation12App/src/mpRestClient12/headerPropagation/HeaderPropagationTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/propsApp/src/mpRestClient10/props/PropsTestServlet.java
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/SseClientTestServlet.java
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
Labels: CLA Signed

#22019 Issue #22018: remove faces internal from impl bundles
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/io.openliberty.faces.internal/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.3.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#22146 Issue22140-BuildBreakinWebJacc15
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/BasicAuthTest.java
  dev/com.ibm.ws.webcontainer.security_test.servlets/src/com/ibm/ws/webcontainer/security/test/servlets/TestConfiguration.java
Labels: noproductcode, CLA Signed

#22132 Make checkpoint more portable by setting env variables by default
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/ValidFeaturesTest.java
Labels: CLA Signed

#21821 Issue #20428: Don't throw UnsupportedOperationException
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/webapp/WebApp31.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServletContextUnsupportedOperationExceptionTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationExceptionr/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationExceptionr/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationExceptionr/server.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/TestProgrammaticListenerAddition.jar/src/com/ibm/ws/webcontainer/servlet_31_fat/testprogrammaticlisteneraddition/jar/listeners/MyProgrammaticServletContextListener.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebApp40.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContextUnsupportedOperationExceptionTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletContext_UnsupportedOperationExceptionr/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletContext_UnsupportedOperationExceptionr/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletContext_UnsupportedOperationExceptionr/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestProgrammaticListenerAddition.jar/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestProgrammaticListenerAddition.jar/src/com/ibm/ws/webcontainer/servlet_40_fat/testprogrammaticlisteneraddition/jar/listeners/MyProgrammaticServletContextListener.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TestProgrammaticListenerAddition.jar/src/com/ibm/ws/webcontainer/servlet_40_fat/testprogrammaticlisteneraddition/jar/listeners/MyServletContainerInitializer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22120 Update persistence service dependency to beta
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpRestClient.internal.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpRestClient.internal.cdi-4.0.feature
  dev/com.ibm.ws.ejbcontainer.injection_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.injection_fat/fat/src/com/ibm/ws/ejbcontainer/injection/fat/tests/LookupOverrideTest.java
  dev/com.ibm.ws.ejbcontainer.timer.calendar_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer.calendar_fat/fat/src/com/ibm/ws/ejbcontainer/timer/calendar/fat/tests/NextTimeoutPersistentTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/NoDatasourceTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/NoTablesTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerRestartTest.java
Labels: CLA Signed, team:Performance

#22164 Revert "Jakarta Mail 2.1 Implementation bundle"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.classpath
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.gitignore
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.project
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.angus.mail.2.1/bnd.bnd
Labels: CLA Signed

#22156 Rename BELL FAT SpiTypeVisibilityTest
  dev/com.ibm.ws.classloading.bells_fat/.classpath
  dev/com.ibm.ws.classloading.bells_fat/bnd.bnd
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/BellSpiVisibilityTest.java
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/FATSuite.java
  dev/com.ibm.ws.classloading.bells_fat/publish/servers/bell_spi_server/server.xml
  dev/com.ibm.ws.classloading.bells_fat/test-applications/SpiVisibility.war/src/com/ibm/ws/classloading/bells/TestSpiVisibilityServlet.java
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiTypeVisible.jar/resources/META-INF/services/com.ibm.ws.classloading.exporting.test.TestInterface
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiTypeVisible.jar/resources/META-INF/services/com.ibm.ws.classloading.exporting.test.TestInterface2
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiVisible.jar/resources/META-INF/services/com.ibm.ws.classloading.exporting.test.TestInterface
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiVisible.jar/resources/META-INF/services/com.ibm.ws.classloading.exporting.test.TestInterface2
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiVisible.jar/src/com/ibm/ws/test/SpiVisible.java
  dev/com.ibm.ws.classloading.bells_fat/test-applications/testSpiVisible.jar/src/com/ibm/ws/test/SpiVisibleRESTHandlerImpl.java
Labels: noproductcode, team:OSGi Infrastructure, CLA Signed

#22152 Fix Admin Center Explore tool error dialog text layout problem
  dev/com.ibm.ws.ui.shared/resources/WEB-CONTENT/cssShared/dialog.css
Labels: CLA Signed

#22157 Update messaging 3.1 fat to use Java 11 and EE10 APIs.
  dev/com.ibm.ws.messaging.open_31_fat/.classpath
  dev/com.ibm.ws.messaging.open_31_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.messaging.open_31_fat/bnd.bnd
  dev/com.ibm.ws.messaging.open_31_fat/build.gradle
  dev/com.ibm.ws.messaging.open_31_fat/fat/src/com/ibm/ws/messaging/repeatedAnnotations/fat/FATSuite.java
  dev/com.ibm.ws.messaging.open_31_fat/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.messaging.open_31_fat/test-applications/repeatedAnnotations/src/repeatedAnnotations/ejb/RepeatedAnnotationsBean.java
  dev/com.ibm.ws.messaging.open_31_fat/test-applications/repeatedAnnotations/src/repeatedAnnotations/web/RepeatedAnnotationsServlet.java
Labels: noproductcode, CLA Signed

#22136 Add xmlbinding to JPA Hibernate testing for EE10
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat/publish/shared/config/hibernate31-cfg.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat/publish/shared/config/hibernate31-cfg.xml
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat/publish/shared/config/hibernate31-cfg.xml
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat/publish/shared/config/hibernate31-cfg.xml
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_CREATE_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DELETE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DELETE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DELETE_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DELETE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DELETE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DROP_DB2.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/derivedIdentity/ddl/WEB-INF/classes/JPA20_DERIVEDIDENTITY_DROP_SQLSERVER.ddl
Labels: noproductcode, CLA Signed

#22161 Rest client FAT review comments
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.headerPropagation/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.produceConsume/server.xml
Labels: noproductcode, CLA Signed

#20394 Extra log line
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
Labels: CLA Signed

#22061 Upgrade to RESTEasy 6.1.0.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/src/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/AsyncWriterInterceptor.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/AsyncWriterInterceptorContext.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
Labels: in:JAX-RS, CLA Signed, team:Wendigo West

#22169 Add missing Jakarta Rest autofeatures to the beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-validator3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-xmlBinding4.0.feature
Labels: CLA Signed

#22163 Restore logs on error
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint/test/io/openliberty/checkpoint/internal/CheckpointImplTest.java
Labels: CLA Signed

#22175 Skip Concurrency TCK InheritedAPITests
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22170 EJBClient Fat remove short timed exit from client server
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/publish/clients/com.ibm.ws.ejbcontainer.remote.client.fat.clientInjection/bootstrap.properties
Labels: noproductcode, CLA Signed

#22033 mpTelemetry end to end test with Jaeger
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.gitignore
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.project
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.settings/org.jboss.ide.eclipse.as.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AutoInstrumentationTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/MicroProfileTelemetryTestBase.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ValidateHelper.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/testServer1/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/testServer1/server.env
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/testServer1/server.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/test-applications/system/src/io/openliberty/guides/system/SystemApplication.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/test-applications/system/src/io/openliberty/guides/system/SystemResource.java
Labels: noproductcode, CLA Signed

#22137 Cleanup leaked FAT servers after timeout
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: test bug, team:Blizzard, CLA Signed

#22171 Switch to BatchSpanProcessor
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/cdi/OpenTelemetryProducer.java
Labels: CLA Signed

#22127 Fixed hideMessage attribute removal in server config
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConfigUtils.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/TestHideMessages.java
  dev/com.ibm.ws.logging_fat/publish/files/server-emptyHideMsg.xml
  dev/com.ibm.ws.logging_fat/publish/files/server-hideMsgAttrbRemoval.xml
  dev/com.ibm.ws.logging_fat/publish/files/server-twoMessageIds.xml
Labels: CLA Signed

#22168 Modify FAT to test usernames with special characters
  dev/com.ibm.ws.security.javaeesec_fat.4/fat/src/com/ibm/ws/security/javaeesec/fat/SecurityContextEJBTest.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.ejb.fat/server.xml
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2FactoryTest.java
Labels: in:Security, noproductcode, CLA Signed, team:Core Security

#22160 Issue #22159: Increase start timeout embedded fat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/wsspi/kernel/embeddable/EmbeddedServerDriver.java
Labels: noproductcode, CLA Signed

#22142 PR for Issue 21159: Nonce/request URL storage and OP discovery enhancements
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.op/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rpd/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rpd2/bootstrap.properties
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ClientConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequestTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequestParameters.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequestUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/discovery/DiscoveryHandler.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/discovery/OidcDiscoveryConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/OidcDiscoveryException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/CookieBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/OidcClientStorageConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/OidcStorageUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequestUtilsTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequestTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/OidcStorageUtilsTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#22133 Create webBundle.internal feature that doesn't expose servlet 6.0 for EE10 for liberty product features to use.
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.servlet-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.servlet-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.servlet-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundle.internal.servlet-6.0.feature
Labels: CLA Signed, team:Performance

#22074 use onStart as workaround to Java 19 bug
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedForkJoinWorkerThread.java
Labels: team:Zombie Apocalypse, CLA Signed

#22147 Added "overwrite" deployment option to ShrinkHelper methods in test a…
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BasicServletTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LogsVerificationTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPFaultToleranceTimeoutTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/OSGiConsoleTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RESTclientTest.java
Labels: noproductcode, CLA Signed

#22153 completable future Java 19 methods
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletionStage.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#22143 Refactoring and processing of Jakarta Security 3.0 annotations for issue #21155
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-5.0/io.openliberty.appSecurity-5.0.feature
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/HttpAuthenticationMechanismsTracker.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/PrimarySecurityCDIExtension.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/HttpAuthenticationMechanismsTrackerTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/JavaEESecCDIExtensionTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/TestHttpAuthenticationMechanismsTracker.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.project
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.settings/bndtools.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/resources/META-INF/beans.xml
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/resources/io/openliberty/security/jakartasec/cdi/internal/resources/JakartaSecurity30Messages.nlsprops
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/TraceConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/JakartaSecurity30CDIExtension.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/JakartaSecurity30CDIExtensionMetadata.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.project
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/test/SimplestAnnotatedTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.rp/bootstrap.properties
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.rp/jvm.options
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.rp/server.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotated.war/src/oidc/servlets/OidcAnnotatedServlet.java
Labels: ID review not needed, CLA Signed, L2 Reviewed

#22177 Enable Servlet 31 CDI Tests for EE10 Repeat
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDITests.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_cdiServer/server.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/CDI12Test.jar/resources/META-INF/beans.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/CDI12TestEE10.war/resources/WEB-INF/beans.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22184 Refactor some of AuthorizationCodeHandler
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/OidcClientAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandlerTest.java
Labels: CLA Signed, team:Security SSO

#22176 Move to the liberty arquillian plugin version 2.1.0
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/servers/tckServerForMPContextPropagation13/server.xml
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/tckRunner/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/fattest.simplicity/build.gradle
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/configDropins/defaults/test.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/standalone.pom.xml
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.config.3.0.internal_fat_tck/publish/servers/Config30TCKServer/server.xml
  dev/io.openliberty.microprofile.config.3.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.config.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/servers/FaultTolerance40TCKServer/server.xml
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/publish/servers/Health40TCKServer/server.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckAudNoenv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/servers/jwt20tckNoaudNoEnv/server.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.4.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.openapi.3.0.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.openapi.3.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.openapi.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/servers/OpentracingRestClientTCKServer/server.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/servers/OpentracingTCKServer/server.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/servers/OpentracingTCKServerMicroProfile/server.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.telemetry_git_fat_tck/publish/servers/TelemetryGitTCKServer/server.xml
  dev/io.openliberty.microprofile.telemetry_git_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.telemetry_git_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed, team:Performance

#22199 Fix build break for not picking up the overlay class.
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
Labels: CLA Signed, team:Performance

#22195 Update FAT bnd.bnd with new testcontainers directive
  dev/io.openliberty.checkpoint_fat/bnd.bnd
Labels: noproductcode, CLA Signed
