Repository OpenLiberty/open-liberty, pull requests merged in 2022-03, with the labels that each got.

#20275 20273 unrevert20203
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jcache.internal-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/io.openliberty.distributedSecurityCache-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/distributedSecurityCache-1.0/resources/l10n/io.openliberty.distributedSecurityCache-1.0_zh_TW.properties
  dev/com.ibm.ws.security.authentication.builtin/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.jcache.internal/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.jcache.internal/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.2/server.xml
Labels: CLA Signed

#20281 Server config tool: Text contrast with its background is less than the WCAG AA minimum requirements
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/css/editor.css
Labels: CLA Signed

#20267 Issue #19618: Tighten control over lookup keys in CacheObject so it i…
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/cache/CacheObject.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDeleteAuthCacheTest.java
Labels: CLA Signed, team:Wendigo East

#20088 Issue 20059: Add validation for OAuth client backchannel logout URI
  dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/internal/resources/OAuthMessages.nlsprops
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidator.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/plugins/OidcBaseClientValidatorTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#20288 Check if failure list is empty in FailoverTest
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
Labels: noproductcode, CLA Signed

#19779 Update grpc-java and protobuf to latest versions
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpc1.0.internal.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpc1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-9.0.feature
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppConsumerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/BeerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/streaming/service/StreamingServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/io/grpc/examples/helloworld/GreeterGrpc.java
  dev/io.openliberty.grpc.1.0.internal.client.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.grpc.1.0.jakarta/bnd.bnd
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
Labels: in:Transport, ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#20297 Temporary skip the test class when the OS is windows
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertTest.java
Labels: noproductcode, CLA Signed

#20292 Fix testing failure found in RTC 289527.
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheCustomPrincipalCastingTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#20290 OIDC Back-channel logout: New metatype and RP logout endpoint
  dev/com.ibm.ws.security.common.jsonwebkey/resources/com/ibm/ws/security/common/jwk/internal/resources/JWKCommonMessages.nlsprops
  dev/com.ibm.ws.security.common/src/io/openliberty/security/common/serialization/Beta.java
  dev/com.ibm.ws.security.common/src/io/openliberty/security/common/serialization/package-info.java
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClient.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/GsonStrategies.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OidcOAuth20Util.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/RegistrationEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.client/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.client/resources/WEB-INF/web.xml
  dev/com.ibm.ws.security.openidconnect.client/resources/com/ibm/ws/security/openidconnect/client/internal/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcBackchannelLogoutServlet.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutException.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/package-info.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/JsonTokenUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutHelperTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidatorTest.java
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcServerConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/DiscoveryTest.java
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialLoginRequest.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/EndpointServices.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/RequestFilter.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/EndpointServicesTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcServerConfig.java
Labels: CLA Signed, team:Security SSO, L2 Reviewed

#20144 Remove trace spec from bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.db2.1/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/bnd.bnd
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/bnd.bnd
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/bnd.bnd
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/bnd.bnd
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/test-bundles/ifxlib/src/com/informix/database/ConnectionManager.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/TxTestUtils.java
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATRecovery1/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATRecovery2/bootstrap.properties
  dev/com.ibm.ws.wsat.recovery_fat.single/publish/servers/WSATSingleRecovery/bootstrap.properties
Labels: CLA Signed

#20305 Integrate message file entry addition for OLGH20291 (for issue OLGH20…
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
Labels: team:Blizzard, CLA Signed

#20246 EJB timer move postinvoke delay to after recreating CDL
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/MDBTimedCMTBean.java
  dev/com.ibm.ws.ejbcontainer.timer.np_fat/test-applications/NpTimerOperationsEJB.jar/src/com/ibm/ws/ejbcontainer/timer/np/operations/ejb/SingletonTimedBean.java
  dev/com.ibm.ws.ejbcontainer.timer.np_fat/test-applications/NpTimerOperationsEJB.jar/src/com/ibm/ws/ejbcontainer/timer/np/operations/ejb/StatelessTimedBean.java
Labels: noproductcode, CLA Signed

#20263 fix NPE taglib notfound w skipmetainf
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPSkipMetaInfTests.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspSkipMetaInfServer/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspSkipMetaInfServer/server.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JspDependent.java
Labels: in:Web Components, CLA Signed, regression, release bug, team:Sirius

#20220 Update feature template
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#20299 Issue 20298: Avoid ConcurrentModificationException during dynamic config update for FedRep and User Repos
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ConfigManager.java
Labels: CLA Signed, team:Wendigo East

#20296 translatable messages for Concurrency 3.0
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/test-applications/MPContextProp2_0_App/src/concurrent/mp/fat/v20/web/MPContextProp2_0_TestServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/resources/io/openliberty/concurrent/internal/cdi/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/AsyncInterceptor.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/package-info.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/package-info.java
  dev/io.openliberty.concurrent.internal/bnd.bnd
  dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/context/ThirdPartyContext.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/context/ThirdPartyContextCoordinator.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/context/package-info.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/AppDefinedResourceFactory.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/package-info.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed, L2 Reviewed

#20319 Update feature template
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#20328 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#20332 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#20316 Add some checking for null properties
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/JSSEHelper.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/protocol/LibertySSLSocketFactory.java
Labels: CLA Signed

#20326 improve trace of context propagation
  dev/com.ibm.ws.classloader.context/src/com/ibm/ws/classloader/context/internal/ClassloaderContextImpl.java
  dev/com.ibm.ws.classloader.context/src/com/ibm/ws/classloader/context/internal/ClassloaderContextProviderImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ThreadGroupTracker.java
  dev/com.ibm.ws.context/bnd.bnd
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ContextualObject.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextDescriptorImpl.java
  dev/com.ibm.ws.context/src/com/ibm/ws/context/service/serializable/ThreadContextManager.java
  dev/com.ibm.ws.javaee.metadata.context/src/com/ibm/ws/javaee/metadata/context/internal/JEEMetadataContextImpl.java
  dev/com.ibm.ws.javaee.metadata.context/src/com/ibm/ws/javaee/metadata/context/internal/JEEMetadataContextProviderImpl.java
  dev/com.ibm.ws.security.context/src/com/ibm/ws/security/context/internal/SecurityContextImpl.java
  dev/com.ibm.ws.security.context/src/com/ibm/ws/security/context/internal/SecurityContextProviderImpl.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/SerialTransactionContextImpl.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextImpl.java
  dev/com.ibm.ws.transaction.context/src/com/ibm/ws/transaction/context/internal/TransactionContextProviderImpl.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/context/ThirdPartyContext.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/context/ThirdPartyContextCoordinator.java
  dev/io.openliberty.handlelist.context.internal/src/io/openliberty/handlelist/context/internal/EmptyHandleListContext.java
Labels: team:Zombie Apocalypse, CLA Signed

#20325 Update to use 2 threads when running in a 2 CPU environment
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
Labels: noproductcode, CLA Signed, team:Performance

#20329 Eclipse / bnd / and github action updates for recent changes
  .github/test-categories/CDI_2
  .github/test-categories/SECURITY_5
  .github/test-categories/Z_APPCLIENT
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/src/concurrent/mp/fat/v13/web/MPContextProp1_3_TestServlet.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators.cdi/bnd.bnd
  dev/com.ibm.ws.openapi.ui.private/.classpath
  dev/com.ibm.ws.openapi.ui/.classpath
  dev/com.ibm.ws.security.jaas.common_test/bnd.bnd
  dev/io.openliberty.jcache.internal/.classpath
  dev/io.openliberty.ws.jaxws.tools_fat/.project
  dev/io.openliberty.ws.jaxws.tools_fat/.settings/bndtools.core.prefs
Labels: CLA Signed, team:Performance, GitHub Build

#20304 Improve messages for checkpoint/restore for translation
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/TimestampUtils.java
  dev/io.openliberty.checkpoint/resources/io/openliberty/checkpoint/resources/CheckpointMessages.nlsprops
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
Labels: ID reviewed, CLA Signed

#20323 Apply ID recommendations to messages for OLGH20289 that were delivere…
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
Labels: ID reviewed, team:Blizzard, CLA Signed

#20219 Issue 19627: Update MP JWT to wait for config proxy services to start before activating
  dev/com.ibm.ws.security.mp.jwt.1.1.config/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.security.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java
  dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/tai/MicroProfileJwtTAI.java
  dev/com.ibm.ws.security.mp.jwt/test/com/ibm/ws/security/mp/jwt/config/MpConfigUtilTest.java
  dev/io.openliberty.security.mp.jwt.1.2.config/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed, team:Security SSO

#20347 update help
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode

#20317 Change order of WebApp initialization during applications checkpoint
  dev/com.ibm.ws.webcontainer.servlet.3.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.0.factories/src/com/ibm/ws/webcontainer/osgi/webapp/internal/WebAppFactoryImpl.java
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/src/com/ibm/ws/webcontainer31/osgi/webapp/factory/WebAppFactoryImpl31.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/webapp/WebApp31.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/test/com/ibm/ws/webcontainer/webapp/MethodsForProgrammaticConfigurationOfServletsTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/src/com/ibm/ws/webcontainer40/osgi/webapp/factory/WebAppFactory40Impl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebApp40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/webapp/SRTServletRequestTest.java
Labels: CLA Signed, team:Performance, performance

#20345 Update Oracle JDK for ACMEFatUtils
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19945 log stdout of find command
  dev/com.ibm.ws.install.packaging_fat/fat/src/com/ibm/ws/install/packaging/fat/InstallPackagesToolTest.java
Labels: noproductcode, CLA Signed

#20361 Update swagger-ui build and test instructions
  dev/com.ibm.ws.openapi.ui/swagger-ui/README.md
Labels: noproductcode, CLA Signed

#20333 Yasson 3.0.0-RC1 from staging
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-3.0.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbInternal-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-10.0/io.openliberty.jakartaee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-10.0/io.openliberty.webProfile-10.0.feature
  dev/io.openliberty.jakarta.jsonb.3.0/.classpath
  dev/io.openliberty.jakarta.jsonb.3.0/.gitignore
  dev/io.openliberty.jakarta.jsonb.3.0/.project
  dev/io.openliberty.jakarta.jsonb.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jsonb.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jsonb.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jsonb.3.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jsonb.3.0/bnd.bnd
  dev/io.openliberty.org.eclipse.yasson.3.0/.classpath
  dev/io.openliberty.org.eclipse.yasson.3.0/.project
  dev/io.openliberty.org.eclipse.yasson.3.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.yasson.3.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.yasson.3.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.yasson.3.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.eclipse.yasson.3.0/bnd.bnd
  dev/io.openliberty.org.eclipse.yasson.3.0/bnd.overrides
  dev/io.openliberty.org.eclipse.yasson.3.0/build.gradle
  dev/io.openliberty.org.eclipse.yasson.3.0/resources/yasson-messages.properties
  dev/io.openliberty.org.eclipse.yasson.3.0/test/io/openliberty/org/eclipse/yasson/YassonMessageTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#20271 Explore tool accessibility fixes
  dev/com.ibm.ws.ui.shared/resources/WEB-CONTENT/jsShared/utils/imgUtils.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/DashboardPane.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/ObjectViewHeaderPane.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/ResourceButton.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/ResourcePane.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/cardFactory.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/shared/BaseCard.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/shared/StateIcon.js
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/AppOnClusterCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/AppOnServerCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/ApplicationCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/ClusterCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/DashboardPane.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/HostCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/ResourcePane.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/RuntimeOnHostCard.html
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/widgets/templates/ServerCard.html
Labels: CLA Signed

#20334 Update to lazily get expensive audit data
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/jacc/EJBJaccAuthorizationHelper.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/source/AuditServiceImpl.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/audit/Audit.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAuthenticatorProxy.java
Labels: CLA Signed, team:Performance, performance

#20313 Mitigate test box slowness
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/remote/TransactionWrapper.java
  dev/com.ibm.ws.wsat.migration_fat.1/bnd.bnd
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/SleepTest.java
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/WSATSleep/bootstrap.properties
  dev/com.ibm.ws.wsat.migration_fat.1/publish/servers/WSATSleep/server.xml
  dev/com.ibm.ws.wsat.migration_fat.1/test-applications/simpleClient/src/com/ibm/ws/wsat/simpleclient/client/simple/SimpleClientServlet.java
  dev/com.ibm.ws.wsat.migration_fat.1/test-applications/simpleServer/src/com/ibm/ws/wsat/simpleserver/server/WSATSimple.java
  dev/com.ibm.ws.wsat.migration_fat.2/bnd.bnd
  dev/com.ibm.ws.wsat.migration_fat.3/bnd.bnd
  dev/com.ibm.ws.wsat.migration_fat.4/bnd.bnd
  dev/com.ibm.ws.wsat.migration_fat.5/bnd.bnd
Labels: CLA Signed

#20369 Skip prop test on z/OS
  dev/com.ibm.ws.security.oidc.server_fat.claimPropagation/fat/src/com/ibm/ws/security/openidconnect/server/fat/claimPropagation/CommonTests/BasicIdTokenClaimPropagationTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#20354 Issue #20353: Fix NullPointerException in EJBWARRuntime
  dev/com.ibm.ws.ejbcontainer.remote.client/src/com/ibm/ws/ejbcontainer/remote/client/internal/EJBClientRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer.war/src/com/ibm/ws/ejbcontainer/war/internal/EJBWARRuntimeImpl.java
Labels: bug, in:EJB Container, team:Blizzard, CLA Signed

#20338 EJB add warning during remote bind if orb is unavailable
  dev/com.ibm.ws.ejbcontainer.core/resources/com/ibm/ejs/container/container.nlsprops
  dev/com.ibm.ws.ejbcontainer.remote/src/com/ibm/ws/ejbcontainer/remote/internal/EJBRemoteRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/EJBRemoteRuntime.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/NameSpaceBinderImpl.java
Labels: in:EJB Container, ID reviewed, team:Blizzard, CLA Signed

#20377 Tolerate more ResourceAllocationExceptions
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest2.java
Labels: noproductcode, CLA Signed

#20373 Close all streams for test keystores in AcmeFatUtils
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeSimpleTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East, team:Core Security

#20383 test bucket for JSON-B 3.0
  dev/io.openliberty.jakarta.jsonb.internal_fat/.classpath
  dev/io.openliberty.jakarta.jsonb.internal_fat/.project
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/FATSuite.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/JsonBTest.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/bootstrap.properties
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/server.xml
  dev/io.openliberty.jakarta.jsonb.internal_fat/test-applications/jsonbtestapp/src/test/jsonb/web/JsonBTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#20376 CXF trace updates - issue 20363
  dev/com.ibm.ws.org.apache.cxf.cxf.api.2.6.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.2.6.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.ws.security.2.6.2/src/org/apache/cxf/ws/security/wss4j/policyhandlers/AbstractBindingBuilder.java
Labels: CLA Signed

#20340 add java.security.AllPermission to the Microprofile RestClient 2.0 TCk
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/servers/FATServer/server.xml
Labels: noproductcode, CLA Signed, in:MicroProfile/RestClient

#20341 update com.ibm.ws.jaxrs.2.1_fat's tested features
  dev/com.ibm.ws.jaxrs.2.1_fat/bnd.bnd
Labels: in:JAX-RS, noproductcode, CLA Signed

#20365 Generate io.openliberty.microprofile.graphql.2.0.internal_fat_tck results adoc
  dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
Labels: noproductcode, CLA Signed, in:MicroProfile/GraphQL

#20315 JAX-RS and JAX-WS interoperability FAT
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.classpath
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.gitignore
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.project
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/bnd.bnd
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/build.gradle
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/fat/FATSuite.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/fat/WebServicesInteroperabilityTest.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/fat/util/TestUtils.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/Hello.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/HelloResponse.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/ObjectFactory.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/People.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/PeopleService.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/jaxws/test/wsr/server/stub/package-info.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/.gitignore
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/PeopleService.wsdl
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/bootstrap.properties
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/server.xml
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/InteropStartClientTestServlet.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/InteropStartResource.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/PrototypeApplication.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/PrototypeClientTestServlet.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/PrototypeResource.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxws-peopleservice/src/com/ibm/ws/jaxws/test/wsr/server/People.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxws-peopleservice/src/com/ibm/ws/jaxws/test/wsr/server/impl/Bill.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#20291 Remove Java Security support with Java 18+, as per OLGH#20289
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.security.auth.data_fat/fat/src/com/ibm/ws/security/auth/data/fat/Java2SecurityTest.java
  dev/com.ibm.ws.security.client_fat/fat/src/com/ibm/ws/security/client/fat/Java2Test.java
Labels: ID review not needed, team:Blizzard, CLA Signed, L2 Reviewed

#20375 update java permissiion
  dev/com.ibm.ws.security.oauth_fat/publish/files/serversettings/java2Permissions.xml
Labels: noproductcode, test bug, team:Security SSO

#20137 Update FeatureList for Java 18
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: team:Blizzard, CLA Signed, Java 18

#20257 Fix duplicate NLS message IDs in social login
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_cs.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_de.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_es.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_fr.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_hu.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_it.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_ja.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_ko.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_pl.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_pt_BR.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_ro.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_ru.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_zh.nlsprops
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages_zh_TW.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_ErrorConfigTests_oidc_usingSocialDiscoveryConfig.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_ErrorDiscoveryConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/utils/SocialMessageConstants.java
Labels: ID review not needed, CLA Signed, team:Security SSO, POC Approved, L2 Reviewed

#20308 Issue 20058 and 20060: Add initial logout token validation
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidatorTest.java
Labels: CLA Signed, team:Security SSO

#20378 Use BeanManager.getEvent() to fire events on CDI 2.0+
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi1.2-transaction1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.cdi2.0-transaction1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.transaction-2.0.feature
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/resources/META-INF/beans.xml
  dev/com.ibm.ws.transaction.cdi/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/AbstractTransactionContext.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/package-info.java
  dev/io.openliberty.transaction.internal.cdi12/.classpath
  dev/io.openliberty.transaction.internal.cdi12/.gitignore
  dev/io.openliberty.transaction.internal.cdi12/.project
  dev/io.openliberty.transaction.internal.cdi12/.settings/bndtools.core.prefs
  dev/io.openliberty.transaction.internal.cdi12/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.transaction.internal.cdi12/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.transaction.internal.cdi12/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.transaction.internal.cdi12/bnd.bnd
  dev/io.openliberty.transaction.internal.cdi12/resources/META-INF/beans.xml
  dev/io.openliberty.transaction.internal.cdi12/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/io.openliberty.transaction.internal.cdi12/src/io/openliberty/transaction/internal/cdi12/CDI12TransactionContext.java
  dev/io.openliberty.transaction.internal.cdi12/src/io/openliberty/transaction/internal/cdi12/CDI12TransactionContextExtension.java
  dev/io.openliberty.transaction.internal.cdi20/.classpath
  dev/io.openliberty.transaction.internal.cdi20/.gitignore
  dev/io.openliberty.transaction.internal.cdi20/.project
  dev/io.openliberty.transaction.internal.cdi20/.settings/bndtools.core.prefs
  dev/io.openliberty.transaction.internal.cdi20/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.transaction.internal.cdi20/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.transaction.internal.cdi20/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.transaction.internal.cdi20/bnd.bnd
  dev/io.openliberty.transaction.internal.cdi20/resources/META-INF/beans.xml
  dev/io.openliberty.transaction.internal.cdi20/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  dev/io.openliberty.transaction.internal.cdi20/src/io/openliberty/transaction/internal/cdi20/CDI20TransactionContext.java
  dev/io.openliberty.transaction.internal.cdi20/src/io/openliberty/transaction/internal/cdi20/CDI20TransactionContextExtension.java
  dev/wlp-jakartaee-transform/rules/jakarta-text.properties
Labels: CLA Signed

#20295 integration between oidc end_session and saml logout
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/MockServletRequest.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/internal/utils/HttpRequestInfo.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/slo/SLOHandler.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/slo/SPInitiatedSLO.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/InitiatorTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/internal/utils/RequestInfoTest.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/sp/SolicitedTest.java
  dev/com.ibm.ws.webcontainer.security.feature/bnd.bnd
Labels: CLA Signed

#20370 Fix keystore file names (replace jks.jks with jks)
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/BasicRegistry_ssl_user_missing_in_trust.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/BasicRegistry_ssl_user_missing_in_trust_required.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/certRequiredJavaPermissions.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat.cert_required/jvm.options
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#20393 fix more java2 permission issues with Java 18
  dev/com.ibm.ws.security.oidc.server_fat.claimPropagation/publish/files/serversettings/OPJava2Permissions.xml
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/publish/files/serversettings/OPJava2Permissions.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#20398 switch to Jakarta EE 10 deployment descriptors
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-6.0/com.ibm.websphere.appserver.servlet-6.0.feature
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/internal/WebFragmentsInfoImpl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebApp40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/io.openliberty.servlet.internal.6.0.factories/.classpath
  dev/io.openliberty.servlet.internal.6.0.factories/.gitignore
  dev/io.openliberty.servlet.internal.6.0.factories/.project
  dev/io.openliberty.servlet.internal.6.0.factories/.settings/bndtools.core.prefs
  dev/io.openliberty.servlet.internal.6.0.factories/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.servlet.internal.6.0.factories/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.servlet.internal.6.0.factories/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.servlet.internal.6.0.factories/bnd.bnd
  dev/io.openliberty.servlet.internal.6.0.factories/src/com/ibm/ws/webcontainer/speclevel/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/com/ibm/ws/webcontainer/speclevel/servletSpecLevel.properties
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/async/factory/AsyncContextFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/async/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/container/config/factory/WebAppConfiguratorFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/container/config/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/response/factory/IRequestResponseFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/response/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/srt/factory/SRTConnectionContextPool60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/srt/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/webapp/factory/WebAppFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/osgi/webapp/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/servlet/factory/CacheServletWrapperFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/servlet/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/session/impl/factory/SessionContextRegistryImplFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/session/impl/factory/package-info.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/util/factory/URIMatcherFactory60Impl.java
  dev/io.openliberty.servlet.internal.6.0.factories/src/io/openliberty/servlet/internal/v60/util/factory/package-info.java
Labels: team:Zombie Apocalypse, CLA Signed

#20351 Update many weld versions
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.jboss.weld3/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
  dev/io.openliberty.org.jboss.weld4.se/bnd.bnd
  dev/io.openliberty.org.jboss.weld4/bnd.bnd
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.overrides
Labels: CLA Signed

#20380 check ibmjdk8 for localKDC spnego tests
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
Labels: noproductcode, test bug, CLA Signed

#20161 Add launch overrides for "illegal.access.permit" for IIOP FATs
  dev/com.ibm.ws.transport.iiop.open_fat/override/autoFVT/src/ant/launch-overrides.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: noproductcode, CLA Signed

#20387 Remove handling of new reference elements from EJB descriptor parsing.
  dev/com.ibm.ws.javaee.dd.ejb/src/com/ibm/ws/javaee/dd/ejb/EJBJar.java
  dev/com.ibm.ws.javaee.dd/diff_jakartaee_10-9.txt
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/ejb-jar_4_0.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/updates.txt
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/DDParserSpec.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/ejb/EJBJarDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTestBase.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarEnterpriseBeanTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarInterceptorTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/ejb/EJBJarTest.java
Labels: bug, in:Kernel/Bootstrap, CLA Signed, regression, jakartaEE10

#20395 Issue 20058 and 20060: Enhance logout token validation
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/common/internal/resources/OidcCommonMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidatorTest.java
Labels: CLA Signed, team:Security SSO

#20388 Create workflow to update OpenAPI UI dependencies
  .github/workflows/update-openapi-ui.yml
Labels: noproductcode, CLA Signed

#20389 Build changes for swagger-ui 4.6.0
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/webpack.config.js
Labels: CLA Signed

#20225 Add CDI core bucket
  dev/io.openliberty.cdi.core_fat/.classpath
  dev/io.openliberty.cdi.core_fat/.project
  dev/io.openliberty.cdi.core_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.cdi.core_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.cdi.core_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.cdi.core_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.cdi.core_fat/bnd.bnd
  dev/io.openliberty.cdi.core_fat/build.gradle
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/FATSuite.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/RepeatRule.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/Repeats.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/events/CDIEventTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/events/app/CDIEventTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/events/app/EventObserver.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/events/app/TestEvent.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/events/app/beans.xml
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/injection/CDIInjectionTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/injection/app/CDIInjectionTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/injection/app/InjectedBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/injection/app/InjectionTestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/injection/app/beans.xml
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/CDIInterceptorTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/AroundInvokeBinding.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/AroundInvokeClassTestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/AroundInvokeInterceptor.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/AroundInvokeMethodTestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/CDIInterceptorTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/ExecutionRecorder.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/LifecycleBinding.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/LifecycleInterceptor.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/LifecycleTestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/interceptors/app/beans.xml
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/lookup/CDILookupTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/lookup/app/CDILookupTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/lookup/app/LookupTestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/lookup/app/beans.xml
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/CDIProducerTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/app/CDIProducerTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/app/ProducedBy.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/app/Producers.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/app/TestBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/producers/app/beans.xml
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/CDIScopeTest.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/app/AppScopedBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/app/CDIScopeTestServlet.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/app/DependentScopedBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/app/RequestScopedBean.java
  dev/io.openliberty.cdi.core_fat/fat/src/io/openliberty/cdi/internal/core/scopes/app/beans.xml
  dev/io.openliberty.cdi.core_fat/publish/servers/cdiCoreServer/bootstrap.properties
  dev/io.openliberty.cdi.core_fat/publish/servers/cdiCoreServer/server.xml
Labels: noproductcode, CLA Signed

#20420 EE 10 deployment descriptor elements in web.xml and application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/LShimMessages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/merge/ContextServiceComparator.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/merge/ManagedExecutorComparator.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/merge/ManagedScheduledExecutorComparator.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/merge/ManagedThreadFactoryComparator.java
Labels: team:Zombie Apocalypse, CLA Signed

#20442 timing window where task cancel is ignored
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
Labels: team:Zombie Apocalypse, CLA Signed

#20469 FFDCs in testHADBNonRecoverableRuntimeFailover to be allowed
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest1.java
Labels: noproductcode, CLA Signed

#20480 Notices for 22.0.0.4
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#20475 Handle delay in example.com response
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/common/SAMLLogoutCommonTest.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#20470 Reduce to 1 sleep for Custom Repo on UserEnumTest
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/UserEnumerationTest.java
  dev/com.ibm.ws.security.wim.repository_test.custom.delay/src/com/myorg/SampleCustomRepositoryDelay.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#20274 Improve windows installation performance with IBM IM
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
  dev/com.ibm.ws.install/test/com/ibm/ws/install/UninstallDirectorTest.java
Labels: CLA Signed

#20465 cleared context defaults to Transaction
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ContextServiceType.java
Labels: team:Zombie Apocalypse, CLA Signed

#20482 Update RESTful WS integration bundle to work with JSON-B 3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-jsonb2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-10.0/io.openliberty.jakartaee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/webProfile-10.0/io.openliberty.webProfile-10.0.feature
  dev/io.openliberty.restfulWS30.jsonb20provider/bnd.bnd
  dev/io.openliberty.restfulWS30.jsonb20provider/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS30.jsonb20provider/src/io/openliberty/restfulWS30/jsonb20provider/JsonBProvider.java
Labels: CLA Signed, team:Performance, jakartaEE10

#20489 fix Claim Propagation test class names
  dev/com.ibm.ws.security.oidc.social_fat.claimPropagation/fat/src/com/ibm/ws/security/oidc_social/claimPropagation/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.social_fat.claimPropagation/fat/src/com/ibm/ws/security/oidc_social/claimPropagation/fat/OIDC/OIDCBasicIdTokenClaimPropagationTests.java
  dev/com.ibm.ws.security.oidc.social_fat.claimPropagation/fat/src/com/ibm/ws/security/oidc_social/claimPropagation/fat/Social/SocialBasicIdTokenClaimPropagationTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#20440 Issue 20058 and 20060: Remainder of required logout token validation
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidatorTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#19968 Issue 18669: Add concurrency test testEJBAnnoManagedThreadFactoryInitialization.
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/MTFDBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#20411 Update Equinox Framework to 3.17.200
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_source_dependencies.maven
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
Labels: CLA Signed

#20501 Revert "test bucket for JSON-B 3.0"
  dev/io.openliberty.jakarta.jsonb.internal_fat/.classpath
  dev/io.openliberty.jakarta.jsonb.internal_fat/.project
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/FATSuite.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/JsonBTest.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/bootstrap.properties
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/server.xml
  dev/io.openliberty.jakarta.jsonb.internal_fat/test-applications/jsonbtestapp/src/test/jsonb/web/JsonBTestServlet.java
Labels: noproductcode, CLA Signed

#20494 add concurrencyPolicy trace to help debug intermittent test failure
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta/bootstrap.properties
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#20477 Move grpc API bundles to be jars instead of bundles in the feature files.
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpc1.0.internal.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpc1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.grpcClient1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpc-1.0/io.openliberty.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
Labels: CLA Signed, team:Performance

#20471 Pre-initialize statics for ORB ValueHandler and other classes during applications checkpoint
  dev/com.ibm.ws.transport.iiop/bnd.bnd
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/ORBWrapperInternal.java
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RemoteEJBTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/resources/META-INF/permissions.xml
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/resources/WEB-INF/beans.xml
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/src/ejbapp1/EJBEvent.java
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/src/ejbapp1/RemoteEJBServlet.java
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/src/ejbapp1/RemoteInterface.java
  dev/io.openliberty.checkpoint_fat/test-applications/ejbapp1/src/ejbapp1/TestObserver.java
Labels: CLA Signed, team:Performance, performance

#20499 work-around the failure loading jaxb service provider impl in wss4j-stax/xmlsec init
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/bus/LibertyApplicationBusFactory.java
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/bnd.bnd
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/bnd.overrides
  dev/com.ibm.ws.org.apache.wss4j.ws.security.stax.2.3.0/src/org/apache/wss4j/stax/setup/WSSec.java
Labels: CLA Signed

#19738 PR for Issue 19721: Externalize authorizationHeaderScheme MP JWT config attribute
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 ReviewNotRequired

#20516 Spruce up command-line help for schemaGen command
  dev/com.ibm.ws.config.schemagen/src/com/ibm/ws/config/schemagen/internal/Generator.java
  dev/com.ibm.ws.config.schemagen/src/com/ibm/ws/config/schemagen/internal/GeneratorOptions.java
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigOptions.nlsprops
Labels: CLA Signed

#20473 Dump resource states on state change
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/LastingXAResourceImpl.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/TxTestUtils.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest3.java
Labels: CLA Signed

#20493 Fix chkpii error in com.ibm.ws.ssl
  dev/com.ibm.ws.ssl/resources/com/ibm/ws/ssl/resources/ssl.nlsprops
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#20401 Issue #20400: Create Servlet 6.0 FAT Bucket
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.project
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webcontainer.servlet.6.0_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0_fat/build.gradle
  dev/io.openliberty.webcontainer.servlet.6.0_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/test/SimpleTest.java
  dev/io.openliberty.webcontainer.servlet.6.0_fat/publish/servers/servlet60_simpleTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0_fat/publish/servers/servlet60_simpleTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0_fat/test-applications/SimpleTest.war/src/simpletest/servlets/TestServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#20511 redeliver JSON-B tests
  .github/test-categories/JSON
  dev/io.openliberty.jakarta.jsonb.internal_fat/.classpath
  dev/io.openliberty.jakarta.jsonb.internal_fat/.project
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.jsonb.internal_fat/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/FATSuite.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/fat/src/io/openliberty/jakarta/jsonb/internal/fat/JsonBTest.java
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/bootstrap.properties
  dev/io.openliberty.jakarta.jsonb.internal_fat/publish/servers/io.openliberty.jakarta.jsonb.internal.fat/server.xml
  dev/io.openliberty.jakarta.jsonb.internal_fat/test-applications/jsonbtestapp/src/test/jsonb/web/JsonBTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#20507 merging for context service definition
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.injection.core/src/com/ibm/wsspi/injectionengine/InjectionBinding.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ContextServiceType.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceDefinitionProvider.java
Labels: team:Zombie Apocalypse, CLA Signed

#20519 Work around issue with JSONB TCK and JDK 13+
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/fat/src/io/openliberty/jakarta/jsonb/tck/JsonbTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#20397 Remove beta guard ssl cert url encoded string
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/jvm.options
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius

#20535 Revert "Improve windows installation performance with IBM IM"
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
  dev/com.ibm.ws.install/test/com/ibm/ws/install/UninstallDirectorTest.java
Labels: CLA Signed

#20497 Tighten coordination of peer recoveryComplete processing
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/FailureScopeController.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#20528 Update Java 18 FAT to be build with GM build Java 18.
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java18TestJava2SecurityDisabled.java
  dev/io.openliberty.java.internal_fat/publish/servers/java18-cdi-server/apps/io.openliberty.java.internal_fat_18.war
  dev/io.openliberty.java.internal_fat/publish/servers/java18-java2sec-disabled-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java18-java2sec-disabled-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java18-java2sec-disabled-server/server.xml
  dev/io.openliberty.java.internal_fat/publish/servers/java18-server/apps/io.openliberty.java.internal_fat_18.war
Labels: noproductcode, team:Blizzard, Java 18

#20518 Preload classes for all checkpoint types
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/ORBWrapperInternal.java
Labels: CLA Signed, team:Performance, performance

#20382 support ehcache config files (using version 2 schema) and ws-security.cache.config.file option for wss4j
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-4.0.feature
  dev/com.ibm.ws.net.sf.ehcache.core/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.rt.security.3.4.1/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.rt.security.3.4.1/src/org/apache/cxf/rt/security/utils/SecurityUtils.java
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/src/org/apache/cxf/ws/security/cache/CXFEHCacheReplayCache.java
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/src/org/apache/cxf/ws/security/tokenstore/EHCacheTokenStore.java
  dev/com.ibm.ws.org.apache.wss4j.ws.security.common.2.3.0/src/org/apache/wss4j/common/cache/EHCacheExpiry.java
  dev/com.ibm.ws.org.apache.wss4j.ws.security.common.2.3.0/src/org/apache/wss4j/common/cache/EHCacheReplayCache.java
  dev/com.ibm.ws.org.apache.wss4j.ws.security.dom.2.3.0/src/org/apache/wss4j/dom/processor/UsernameTokenProcessor.java
  dev/com.ibm.ws.wssecurity.3.4.1/bnd.bnd
  dev/com.ibm.ws.wssecurity.3.4.1/src/com/ibm/ws/wssecurity/cxf/interceptor/WSSecurityLibertyPluginInterceptor.java
  dev/com.ibm.ws.wssecurity.3.4.1/src/com/ibm/ws/wssecurity/cxf/validator/UsernameTokenValidator.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/files/serversettings/caller_1_NotIncludeTokenInSub.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/files/serversettings/securityProvider_1_AsymSignEnc.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/files/serversettings/securityProvider_1_symSignEnc.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/servers/com.ibm.ws.wssecurity_fat.saml.2servers/cxf-ehcache_ee7.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_1.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller/cxf-ehcache_ee7.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.ssl/cxf-ehcache_ee8.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.ssl/server_customize.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf/publish/servers/com.ibm.ws.wssecurity_fat.ssl/server_customize_ee8.xml
  dev/io.openliberty.jaxws.wssecurity/.classpath
  dev/io.openliberty.jaxws.wssecurity/.project
  dev/io.openliberty.jaxws.wssecurity/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxws.wssecurity/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxws.wssecurity/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxws.wssecurity/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxws.wssecurity/bnd.bnd
  dev/io.openliberty.jaxws.wssecurity/src/io/openliberty/jaxws/wssecurity/WSSecurityFeatureHelperServiceImpl.java
  dev/io.openliberty.wssecurity/.classpath
  dev/io.openliberty.wssecurity/.project
  dev/io.openliberty.wssecurity/.settings/bndtools.core.prefs
  dev/io.openliberty.wssecurity/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.wssecurity/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.wssecurity/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.wssecurity/bnd.bnd
  dev/io.openliberty.wssecurity/src/io/openliberty/wssecurity/WSSecurityFeatureHelper.java
  dev/io.openliberty.wssecurity/src/io/openliberty/wssecurity/WSSecurityFeatureHelperService.java
Labels: CLA Signed

#20526 PR for Issue 20525: Enhance JWT builder jwkEnabled config attribute description
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, team:Security SSO

#20546 Add MinimumJavaLevel with "javaLevel=11" to new EE 10 FAT classes.
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/core/DDValidAppTests_J10.java
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/core/DDValidModTests_J10.java
Labels: in:Kernel/Bootstrap, noproductcode, test bug, CLA Signed, jakartaEE10

#20483 Policy related Changes are moved to CXF 3.4
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/src/org/apache/cxf/jaxws/interceptors/SwAOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyEngineImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationInInterceptor.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#20579 Disable osgi.checkConfiguration by default
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkConfigurator.java
Labels: CLA Signed

#20573 Expose BuildServicesImpl to the CDI API bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.0/io.openliberty.cdi-4.0.feature
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.classpath
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.project
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.settings/bndtools.core.prefs
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.cdi.4.0.internal.services.fragment/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.cdi.4.0.internal.services.fragment/bnd.bnd
  dev/io.openliberty.cdi.4.0.internal.services.fragment/resources/META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildServices
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/bce/enhance/EnhanceTestExtension.java
Labels: CLA Signed

#20600 Add --add-opens for java.text for javacolon tests
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: CLA Signed

#20555 Update response builder to fix issue with newline during parsing of output
  dev/com.ibm.ws.security.fat.common/test-applications/formlogin/src/com/ibm/ws/security/fat/common/apps/formlogin/BaseServlet.java
Labels: test bug, CLA Signed, team:Security SSO

#20496 OIDC Back-channel logout: Various intermediate enhancements
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/jose4j/JwtCreator.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/OIDCConstants.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/LogoutTokenValidatorTest.java
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcServerConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandler.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCAbstractDiscoveryModel.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/Discovery.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/package-info.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/DiscoveryTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelperTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcServerConfig.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#20606 Add extra nls files
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_cs.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_de.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_es.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_fr.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_hu.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_it.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_ja.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_ko.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_pl.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_pt_BR.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_ro.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_ru.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_zh.nlsprops
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/resources/com/ibm/ws/microprofile/faulttolerance/cdi/resources/FaultToleranceCDI_zh_TW.nlsprops
Labels: ID review not needed, L2 ReviewNotRequired

#20551 ensure PrometheusBuilder does not make separate retrieveal of SimpleTimer max/min values
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/helper/PrometheusBuilder30.java
Labels: CLA Signed

#20550 check for IBM Krb5LoginModule exist
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/Krb5Helper.java
Labels: noproductcode, CLA Signed

#20514 updates to new saml websso runtime
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/HttpRequestInfo.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/slo/SLOHandler.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/slo/SPInitiatedSLO.java
Labels: CLA Signed

#20615 Update the Servlet 6.0 FAT javac.source/target to 11
  dev/io.openliberty.webcontainer.servlet.6.0_fat/bnd.bnd
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#20478 Issue #20306: Update netty dependencies to 4.1.75.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.jakarta.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: in:Transport, CLA Signed, team:Sirius

#20595 Issue #20368: Default EJBInitAtStartup for CRIU
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSHome.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/AbstractEJBRuntime.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/ejbcontainer/runtime/EJBRuntime.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/WCCMMetaData.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/metadata/WCCMMetaDataImpl.java
Labels: in:EJB Container, team:Blizzard, CLA Signed, CRIU

#20444 Issue #20412: Adding test to validate SAML with distributed auth cache.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/AuthCache.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/InMemoryAuthCache.java
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/JCacheAuthCache.java
  dev/com.ibm.ws.security.authentication.builtin/test/com/ibm/ws/security/authentication/internal/cache/InMemoryCacheTest.java
  dev/com.ibm.ws.security.authentication/src/com/ibm/ws/security/authentication/cache/CacheObject.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestHelpers.java
  dev/com.ibm.ws.security.saml.sso/bnd.bnd
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/rs/ByteArrayDecoder.java
  dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/token/Saml20TokenImpl.java
  dev/com.ibm.ws.security.saml.sso/test/com/ibm/ws/security/saml/sso20/token/Saml20TokenImplTest.java
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLCommonTestHelpers.java
  dev/com.ibm.ws.security.saml.sso_fat.common/test-applications/samlclient.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/SPInitiated/BasicSolicitedSPInitiatedTests.java
  dev/com.ibm.ws.security.saml.websso.2.0/bnd.bnd
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/rs/ByteArrayDecoder.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/token/Saml20TokenImpl.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/AbstractTokenImpl.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/bnd.bnd
  dev/io.openliberty.jcache.internal_fat.hazelcast/build.gradle
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/BaseTestCase.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/FATSuite.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheAuthenticationCacheTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDeleteAuthCacheTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheSamlAuthenticationCacheTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/docker/KeycloakAdmin.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/docker/KeycloakContainer.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/docker/KeycloakUtils.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/resources/security/ltpa.keys
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/resources/security/ltpa.keys
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/bnd.bnd
  dev/io.openliberty.jcache.internal_fat.infinispan/build.gradle
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/FATSuite.java
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/resources/security/ltpa.keys
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/server.xml
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/resources/security/ltpa.keys
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/server.xml
Labels: CLA Signed, team:Wendigo East

#18693 LG-278: handle stack traces written to System.out / System.err as a single event in logs
  dev/com.ibm.ws.logging.osgi/bnd.bnd
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging.osgi/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/Activator.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/LoggingConfigurationService.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/MethodProxy.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/ReflectionHelper.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/StackJoinerManager.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/bci/AddVersionFieldClassAdapter.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/bci/ThrowableClassAdapter.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/bci/ThrowableClassFileTransformer.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/bci/ThrowableMethodAdapter.java
  dev/com.ibm.ws.logging.osgi/src/com/ibm/ws/logging/internal/osgi/stackjoiner/boot/templates/ThrowableProxy.java
  dev/com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.logging/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LoggingConstants.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/utils/StackJoinerConfigurations.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/FATSuite.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
  dev/com.ibm.ws.logging_fat/publish/files/stackJoiner/server-disableStackJoiner.xml
  dev/com.ibm.ws.logging_fat/publish/files/stackJoiner/server-enableStackJoiner.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.bootStrapConfig/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.bootStrapConfig/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.bootStrapConfig/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.dynamicConfig/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.dynamicConfig/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.dynamicConfig/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envAndBootStrapConfig/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envAndBootStrapConfig/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envAndBootStrapConfig/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envAndBootStrapConfig/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envConfig/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envConfig/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envConfig/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.envConfig/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.eventSizeThreshold/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.eventSizeThreshold/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.eventSizeThreshold/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.eventSizeThreshold/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.serverXMLConfig/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.serverXMLConfig/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner.serverXMLConfig/server.xml
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner/bootstrap.properties
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner/jvm.options
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner/server.env
  dev/com.ibm.ws.logging_fat/publish/servers/com.ibm.ws.logging.stackjoiner/server.xml
  dev/com.ibm.ws.logging_fat/test-applications/broken-servlet/src/com/ibm/ws/logging/fat/broken/servlet/BrokenWithCustomPrintStreamServlet.java
  dev/com.ibm.ws.logging_fat/test-applications/broken-servlet/src/com/ibm/ws/logging/fat/broken/servlet/ExtremelyLongStackTrace.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#20629 Add 2022 releases and removed 2020 releases
  SECURITY.md
Labels: noproductcode, CLA Signed

#20639 Issue #20547: Execute servlet 4.0 fat with EE10 features
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerMiscTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerPropertyTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#20632 Concurrency 3.0 resources defined in web fragment
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyJSPTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta.jsp/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/MaxAsync.jsp
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/SecurityCleared.jsp
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/SecurityPropagated.jsp
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/SecurityUnchanged.jsp
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/ThreadPriority.jsp
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyJSPTestApp/src/test/jakarta/concurrency/jsp/ConcurrencyJSPTestServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyWebFragment/resources/META-INF/web-fragment.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#20646 EJSHome NullCheck pmiFactory during destroy
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSHome.java
Labels: CLA Signed

#20625 Updates for latest Open J9 with checkpoint support
  dev/com.ibm.ws.kernel.boot.core/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RemoteEJBTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/TestSPIConfig.java
  dev/io.openliberty.checkpoint_fat/publish/files/addImmutableEnvKey/server.env
  dev/io.openliberty.checkpoint_fat/test-applications/mpapp1/src/mpapp1/MPConfigServlet.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestCheckpointHook.java
Labels: CLA Signed, CRIU

#20657 Publish new schemaGen script
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
Labels: CLA Signed

#20663 Create server logs directory if it does not exist
  dev/com.ibm.ws.config.server.schemagen/src/com/ibm/ws/config/server/schemagen/ServerSchemaGenCommand.java
Labels: CLA Signed
