Repository OpenLiberty/open-liberty, pull requests merged in 2022-09, with the labels that each got.

#22319 FAT for Cookie setAttribute
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60CookieSetAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_cookieSetAttributeTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_cookieSetAttributeTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/CookieSetAttributeTest.war/src/cookiesetattribute/servlets/CookieSetAttributeServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22332 updates to entity annotations for records
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Column.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Id.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22359 Update OidcHttpAuthenticationMechanism to start processing callback for issue #21165
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/beans/Utils.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanismTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationCodeFlow.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/Flow.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/AuthenticationErrorResponseException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/NoStateValueStoredException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/RequestDoesNotMatchExpectedUrlException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/RequestStateDoesNotMatchStoredStateException.java
Labels: CLA Signed

#22275 init userinfo subsystem
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/UserInfoEndpointNotHttpsException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/UserInfoResponseException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/UserInfoResponseNot200Exception.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/HttpConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtil.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/userinfo/UserInfoResponse.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/userinfo/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenRequestorTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestorTest.java
Labels: CLA Signed

#22353 Wait for mongo to be ready before registering clients
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/BackChannelLogout_RegisterClients.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#22343 Skip testNegativeoTimeOut
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java
Labels: noproductcode, CLA Signed

#22338 Create MP JWT 2.1 feature files based off of PR #22083
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-appSecurity.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-appSecurity4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jwtSso1.0.internal.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.jwt-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/io.openliberty.mpJwt-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_cs.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_de.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_es.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_fr.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_hu.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_it.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_ja.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_ko.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_pl.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_pt_BR.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_ro.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_ru.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_zh.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/resources/l10n/io.openliberty.mpJwt-2.1_zh_TW.properties
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonSecurityFat.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonTest.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestFeatureEE10RepeatAction.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatConstants.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/utils/JwtFatUtils.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/shared/config/featuresWithoutJwtSso_ee10.xml
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/shared/config/jwtSsoFeatures_noMpJwt_ee10.xml
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/.classpath
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/bnd.bnd
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1/.classpath
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/featureSupportTests/feature1_1/Feature11Enabled_ConfigInAppTests.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/featureSupportTests/feature1_1/Feature11Enabled_ConfigInServerXmlTests.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/featureSupportTests/feature1_1/Feature11Enabled_MpConfigAsEnvVars.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/featureSupportTests/feature1_1/Feature11Enabled_MpConfigAsSystemProperties.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1/.classpath
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/io.openliberty.org.eclipse.microprofile/jwt.2.1.bnd
  dev/io.openliberty.security.mp.jwt.2.1.config/.classpath
  dev/io.openliberty.security.mp.jwt.2.1.config/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.mp.jwt.2.1.config/bnd.bnd
Labels: ID review not needed, CLA Signed, team:Performance

#22193 Update transformer to version 0.5.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.beanvalidation.v20.cdi/src/com/ibm/ws/beanvalidation/v20/cdi/internal/LibertyHibernateValidatorExtension.java
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/original.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/transformed.bnd
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
  dev/wlp-jakartaee-transform/rules/com.ibm.ws.cdi.weld.CDIProvider.xml.properties
  dev/wlp-jakartaee-transform/rules/jakarta-batch.properties
  dev/wlp-jakartaee-transform/rules/jakarta-cdiLibertyTransactionService.properties
  dev/wlp-jakartaee-transform/rules/jakarta-concurrent-components-xml.properties
  dev/wlp-jakartaee-transform/rules/jakarta-connectors.properties
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
  dev/wlp-jakartaee-transform/rules/jakarta-ejb-components-xml.properties
  dev/wlp-jakartaee-transform/rules/jakarta-enterpriseInjectSpiExtension.properties
  dev/wlp-jakartaee-transform/rules/jakarta-faces-config.properties
  dev/wlp-jakartaee-transform/rules/jakarta-faces-initialization.properties
  dev/wlp-jakartaee-transform/rules/jakarta-jsonProvider.properties
  dev/wlp-jakartaee-transform/rules/jakarta-jspVersion.properties
  dev/wlp-jakartaee-transform/rules/jakarta-resource.properties
  dev/wlp-jakartaee-transform/rules/jakarta-restfulWS.properties
  dev/wlp-jakartaee-transform/rules/jakarta-servletVersion.properties
  dev/wlp-jakartaee-transform/rules/jakarta-text.properties
  dev/wlp-jakartaee-transform/rules/jakarta-transactionContext.properties
  dev/wlp-jakartaee-transform/rules/jakarta-transactionContextExtension.properties
  dev/wlp-jakartaee-transform/rules/jakarta-transactionManager.properties
  dev/wlp-jakartaee-transform/rules/jakarta-transactionSynchronizationRegistry.properties
  dev/wlp-jakartaee-transform/rules/jakarta-userTransaction.properties
  dev/wlp-jakartaee-transform/rules/jakarta-websocketResources.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-CDIRuntimeImpl.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-securityEnterprise.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-servletContainerInitializer.properties
  dev/wlp-jakartaee-transform/rules/jakarta-xml-ws-provider.properties
Labels: CLA Signed, DO NOT MERGE, team:Performance

#22335 Add to bnd buildpath to address an eclipse compile issue.
  dev/io.openliberty.checkpoint_fat_persistence/bnd.bnd
Labels: noproductcode, CLA Signed

#22331 Ignore invalid resources in checkAtomicity()
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
Labels: CLA Signed

#22339 Changes needed to allow restfulWS30 tests to repeat for EE10
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/bnd.bnd
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/fat/src/io/openliberty/jakarta/restfulWS30api/fat/CanLoadRESTfulWS30APIsTest.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/bnd.bnd
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/fat/src/io/openliberty/restfulWS30/cdi30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/publish/servers/io.openliberty.restfulWS.3.0.cdi.3.0.fat.basic/server.xml
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/publish/servers/io.openliberty.restfulWS.3.0.cdi.3.0.fat.lifecyclemismatch/server.xml
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/basic/src/io/openliberty/restfulWS30/cdi30/fat/basic/Student.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/complex/src/io/openliberty/restfulWS30/cdi30/fat/complex/ContextRequestFilter.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/complex/src/io/openliberty/restfulWS30/cdi30/fat/complex/SimpleBean.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/complex/src/io/openliberty/restfulWS30/cdi30/fat/complex/Student.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/complex/src/io/openliberty/restfulWS30/cdi30/fat/complex/Teacher.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/lifecyclemethod/src/io/openliberty/restfulWS30/cdi30/fat/lifecyclemethod/LifeCycleStudent.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/test-applications/lifecyclemethod/src/io/openliberty/restfulWS30/cdi30/fat/lifecyclemethod/LifeCycleTeacher.java
  dev/io.openliberty.restfulWS.3.0.client_fat/bnd.bnd
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0_fat/bnd.bnd
  dev/io.openliberty.restfulWS.3.0_fat/fat/src/io/openliberty/restfulWS30/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#22365 Fix ConcurrentModificationException for notifyListeners
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/CpuInfo.java
Labels: CLA Signed

#22373 Myfaces 4451
  dev/io.openliberty.jakarta.faces.4.0/.classpath
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/application/StateManagerWrapper.java
Labels: in:Web Components, team:Sirius, jakartaEE10

#22337 FAT for ServletRequest Id and ServletConnection
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60RequestConnectionTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_requestConnectionTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_requestConnectionTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/RequestConnectionTest.war/src/requestconnection/servlets/TestServletRequestID.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22234 Issue #22227: update Yoko for null field interoperability
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#21864 Add messaging singleton mechanism
  dev/com.ibm.ws.messaging.common/bnd.bnd
  dev/com.ibm.ws.messaging.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.messaging.common/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/LifecycleError.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/Singleton.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonAgent.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonMonitor.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonsReady.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/common/service/CommonServiceFacade.java
  dev/com.ibm.ws.messaging.msgstore/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.messaging.msgstore/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/impl/MessageStoreImpl.java
  dev/com.ibm.ws.messaging.runtime/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.messaging.runtime/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/messaging/service/JsAdminServiceImpl.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/ItemInterfaceFactory.java
Labels: CLA Signed

#22381 Reduce EJB FAT repeats on Windows
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/NoDatasourceTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/NoTablesTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerRestartTest.java
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#22167 Dont check server stopping early in lease deletion
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
Labels: CLA Signed

#22354 Run MP FT 4.0 TCK with just core EE features
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/servers/FaultTolerance40TCKServer/server.xml
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: noproductcode, CLA Signed

#22326 Jakarta security fat setup
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonSecurityFat.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/TestActions.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/bnd.bnd.disabled
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/test/SimplestAnnotatedTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.op/bootstrap.properties
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.op/configs/server_orig.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.op/jvm.options
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/io.openliberty.security.jakartasec-3.0_fat.rp/configs/server_orig.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/OPMisc.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/goodBasicRegistry.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/oauthRoles_1.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/oidcProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/op_fatTestPorts.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/op_features.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/rp_fatTestPorts.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/rp_features.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotated.war/src/oidc/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotated.war/src/oidc/servlets/OidcAnnotatedServlet.java
Labels: CLA Signed, team:Security SSO, test delivery

#22181 Remove warning since Liberty does not ship Woodstox
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxUtils.java
Labels: CLA Signed

#22336 PR for Issue 21157: Add SSL support for discovery
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
Labels: CLA Signed, team:Security SSO

#22329 PR for Issue 22300: Fix issue with empty strings returned from provider metadata
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
Labels: CLA Signed, team:Security SSO

#22375 Myfaces 4452
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/UIData.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22386 Myfaces 4454
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/context/ExternalContextWrapper.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/render/Renderer.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22403 Clean up remaining JAXB and JAXWS 2.3 references
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxwsClient-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wimcore.internal.ee-6.0.feature
  dev/com.ibm.ws.jaxws.2.3.wsat/.classpath
  dev/com.ibm.ws.jaxws.2.3.wsat/.project
  dev/com.ibm.ws.jaxws.2.3.wsat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jaxws.2.3.wsat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jaxws.2.3.wsat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jaxws.2.3.wsat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jaxws.2.3.wsat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.wsat/src/com/ibm/ws/jaxws/wsat/WSATFeatureBusListener.java
Labels: CLA Signed, team:Performance

#22394 Register OidcIdentityStoreBean for issue #21169
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/JakartaSecurity30CDIExtension.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/OidcIdentityStoreBean.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/extensions/JakartaSecurity30CDIExtensionTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/extensions/OidcIdentityStoreBeanTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/AuthenticationErrorResponseException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/NoStateValueStoredException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/RequestStateDoesNotMatchStoredStateException.java
Labels: CLA Signed

#22407 22.0.0.10 Notices
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#22398 Fix spiVisibility attribute name and desc post-translation
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_cs.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_de.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_es.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_fr.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_hu.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_it.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ja.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ko.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_pl.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_pt_BR.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ro.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_ru.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_zh.properties
  dev/com.ibm.ws.classloading.bells/resources/OSGI-INF/l10n/bells_zh_TW.properties
Labels: ID reviewed, team:OSGi Infrastructure, CLA Signed

#22376 Add tests for appSecurity with checkpoint
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/AppsecurityTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAppSecurity/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAppSecurity/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAppSecurity/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/resources/error.html
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/resources/error403.html
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/resources/index.html
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/resources/welcome.html
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/src/appsecurity/AppsecurityBean.java
  dev/io.openliberty.checkpoint_fat/test-applications/appsecurity/src/appsecurity/AppsecurityServlet.java
Labels: noproductcode, CLA Signed

#22401 Fix message for invalid checkpoint phase when in container
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#22387 Myfaces 4453
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/behavior/FacesBehavior.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/convert/FacesConverter.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/event/WebsocketEvent.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/flow/builder/FlowBuilderParameter.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/flow/builder/FlowDefinition.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/model/FacesDataModel.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/push/Push.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/validator/FacesValidator.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/wrapper/FacesBehaviorCDIWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/wrapper/FacesClientBehaviorCDIWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/wrapper/FacesConverterCDIWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/wrapper/FacesValidatorCDIWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/push/EndpointImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22327 featureUtility repo connection failure error code
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/ReturnCode.java
Labels: CLA Signed

#22379 AdminCenter and its tools: change locale selection based on the browser language settings
  dev/com.ibm.ws.ui.shared/resources/WEB-CONTENT/jsShared/bidiConfig.jsp
  dev/com.ibm.ws.ui.tool.explore/bnd.bnd
  dev/com.ibm.ws.ui.tool.explore/import.xml
  dev/com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui.tool.javaBatch/bnd.bnd
  dev/com.ibm.ws.ui.tool.javaBatch/import.xml
  dev/com.ibm.ws.ui.tool.javaBatch/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/js/toolbox/views/toolbox.js
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/login.jsp
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/login/login.js
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/toolbox.jsp
  dev/com.ibm.ws.ui/resources/WEB-INF/web.xml
Labels: CLA Signed

#22392 Fix ToolboxAPIv1Test.catalogRemoveCausesToolboxRemove test
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/ToolboxAPIv1Test.java
Labels: noproductcode, CLA Signed

#22400 Beta Servlet 6.0
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-6.0/com.ibm.websphere.appserver.servlet-6.0.feature
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22406 Update CDI non-contextual FAT and run on EE10
  dev/com.ibm.ws.cdi.noncontextual_fat/.classpath
  dev/com.ibm.ws.cdi.noncontextual_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.noncontextual_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.noncontextual_fat/bnd.bnd
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/Bar.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/Baz.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/Foo.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/NonContextualBean.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/NonContextualInjectionPointTestServlet.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualInjectionPointWar/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualWar/NonContextualBean.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualWar/NonContextualTestServlet.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/nonContextualWar/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/vetoAndExtendWar/MyBean.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/vetoAndExtendWar/ServletExtension.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/vetoAndExtendWar/VetoAndExtendTestServlet.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/apps/vetoAndExtendWar/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/FATSuite.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/NonContextualInjectionPointTest.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/NonContextualTests.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/fat/tests/VetoAndExtendTests.java
  dev/com.ibm.ws.cdi.noncontextual_fat/fat/src/com/ibm/ws/cdi12/suite/FATSuite.java
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/nonContextualServer/server.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/vetoAndExtendServer/server.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/appNonContextual.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/appNonContextual.war/src/test/non/contextual/NonContextualBean.java
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/nonContextual.ear/resources/META-INF/application.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/nonContextual.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/nonContextual.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.cdi.noncontextual_fat/test-applications/vetoAndExtendNonContextual.war/src/test/vetoandextend/MyServlet.java
Labels: noproductcode, CLA Signed

#22426 PH46816: Header validation
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpXForwardedAndForwardedHeaderTests.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/PrivateHeaderTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_privateHeaderServer/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_privateHeaderServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_privateHeaderServer/server.xml
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/test-applications/TestServlet31.war/src/com/ibm/ws/webcontainer/servlet_31_fat/testservlet31/war/servlets/PrivateHeadersTestServlet.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/osgi/request/IRequestImplTest.java
Labels: CLA Signed, target:220010

#22448 remove token from logs
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
Labels: noproductcode, CLA Signed

#22402 ignore reg change timeout error msg
  dev/com.ibm.ws.jca_fat_regr/fat/src/suite/r80/base/jca16/ann/ConnectionDefinitionMergeActionTest.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/suite/r80/base/jca16/ann/ConnectionDefinitionsMergeActionTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22419 remove tests duplicated in com.ibm.ws.jca_fat
  dev/com.ibm.ws.jca_fat_regr/fat/src/com/ibm/ws/jca/fat/regr/FATSuite.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/com/ibm/ws/jca/fat/regr/app/InboundSecurityTest.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/com/ibm/ws/jca/fat/regr/app/InboundSecurityTestRapid.java
  dev/com.ibm.ws.jca_fat_regr/fat/src/suite/r80/base/jca16/ann/ConnectorValidatorTest.java
  dev/com.ibm.ws.jca_fat_regr/publish/servers/com.ibm.ws.jca.fat.regr/server.xml
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/ejb/inboundsec/SampleMdb.java
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/ejb/inboundsec/SampleSessionImpl.java
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/ejb/inboundsec/SampleSessionLocal.java
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/ejb/inboundsec/SecureSessionImpl.java
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/ejb/inboundsec/SecureSessionLocal.java
  dev/com.ibm.ws.jca_fat_regr/test-applications/fvtweb/src/web/inboundsec/InboundSecurityTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22399 PR for Issue 21165: Add additional support for verifying OIDC callback
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/OidcClientAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthenticationResponseValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthenticationResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationCodeFlow.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthenticationResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/AuthenticationErrorResponseException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/AuthenticationResponseException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/NoStateValueStoredException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/OidcClientConfigurationException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/OidcDiscoveryException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/OidcUrlNotHttpsException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/RequestDoesNotMatchExpectedUrlException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/RequestStateDoesNotMatchStoredStateException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/StateTimestampException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/OidcStorageUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/Utils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthenticationResponseValidatorTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#22428 Update io.openliberty.org.testcontainers/cache/projects
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed

#22451 Issue #19609: Upgrade Hazelcast version for JCache tests to 5.1.3 fro…
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jcache.internal_fat.hazelcast/bnd.bnd
  dev/io.openliberty.jcache.internal_fat.hazelcast/build.gradle
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDeleteAuthCacheTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/plugins/HazelcastTestPlugin.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.failure.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.oauth20.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.oidcclient.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.oidclogin.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/server.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/configs/libraries.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/test-applications/providerinapp/src/web/providerinapp/ProviderInAppServlet.java
Labels: CLA Signed, team:Wendigo East

#22417 like keyword and contains for non-collections
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/DataPersistence.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/EntityInfo.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/QueryHandler.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22328 Java 19 FAT test
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java18TestJava2SecurityDisabled.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java19Test.java
  dev/io.openliberty.java.internal_fat/publish/servers/java19-server/apps/io.openliberty.java.internal_fat_19.war
  dev/io.openliberty.java.internal_fat/publish/servers/java19-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java19-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java19-server/server.xml
  dev/io.openliberty.java.internal_fat/src-reference/java19/io/openliberty/java/internal/TestApp.java
  dev/io.openliberty.java.internal_fat/src-reference/java19/io/openliberty/java/internal/TestService.java
  dev/io.openliberty.java.internal_fat/src-reference/java19/io/openliberty/java/internal/package-info.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 19

#22408 Jakarta security 30 identitystore implementation
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.server/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/credential/OidcTokensCredential.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/credential/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/IdTokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidationException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/CommonJose4jUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenValidatorTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#22442 MYFACES-4457 UIWebSocket getEventNames signature fix
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/UIWebsocket.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22304 Issue #22303: On z/OS running Java 11 a FFDC with caused by AttachNotSupportedException occurs when feature localConnector-1.0 is specified.
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#22248 Cache routes to avoid looking up the uri info every request.
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryContainerFilter.java
Labels: CLA Signed, team:Performance, performance

#22462 Fix for test failures in RTC 291613. No longer will emit FFDC for fai…
  dev/io.openliberty.jcache.internal/resources/io.openliberty.jcache.internal/resources/JCacheMessages.nlsprops
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CachingProviderService.java
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/plugins/InfinispanTestPlugin.java
Labels: CLA Signed, team:Wendigo East

#22450 implement session based storage
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/SessionBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/SessionBasedStorageTest.java
Labels: CLA Signed

#22461 Open com.sun.jndi.dns to jdk.naming.dns module
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: team:Zombie Apocalypse, CLA Signed, java 17

#22452 FeatureUtility round progress bar percentage
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ProgressBar.java
Labels: CLA Signed

#22473 Revert "implement session based storage"
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/SessionBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/SessionBasedStorageTest.java
Labels: CLA Signed

#22459 Fix wab checkpoint hook
  dev/com.ibm.ws.app.manager.wab/bnd.bnd
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABCheckpointHook.java
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#22469 Ensure test server doesn't leak
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/Base2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/SimpleFS2PCCloudServlet.java
Labels: noproductcode, CLA Signed

#22323 Tidy up stale lease in tx failover tests
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
Labels: CLA Signed

#22475 Revert "Revert "implement session based storage""
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthenticationResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/SessionBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/SessionBasedStorageTest.java
Labels: CLA Signed

#22482 Issue 22465: Add EL support for OpenIdProviderMetadataWrapper
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/JakartaSec30Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdProviderMetadataWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/LogoutDefinitionWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/OpenIdProviderMetadataWrapperTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/TestLogoutDefinition.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/TestOpenIdProviderMetadataDefinition.java
Labels: CLA Signed, team:Security SSO

#22384 New JPA 3.1 testing
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestAggregateLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestArithmeticLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestComparisonLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestFunctionLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestOrderingLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestUpdateLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.classpath
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.gitignore
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.project
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/fat/src/com/ibm/ws/jpa/tests/eclipselink/query/FATSuite.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/fat/src/com/ibm/ws/jpa/tests/eclipselink/query/RepeatWithJPA31.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat/publish/shared/config/jpa31-cfg.xml
  dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh14457/src/com/ibm/ws/jpa/olgh14457/testlogic/JPATestOLGH14457Logic.java
  dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh19176/src/com/ibm/ws/jpa/olgh19176/testlogic/JPATestOLGH19176Logic.java
  dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/fat/src/com/ibm/ws/jpa/jpa31/JPA31Test.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_CREATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_CREATE_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_CREATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_CREATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_DROP_DB2.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_DROP_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_DROP_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_DROP_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_DROP_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_POPULATE_DB2.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_POPULATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_POPULATE_ORACLE.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_POPULATE_POSTGRES.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/ddl/WEB-INF/classes/JPA31_POPULATE_SQLSERVER.ddl
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/Case2Entity.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/Case2Entity_.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/Case3Entity.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/Case3Entity_.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/CaseEntity.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/models/CaseEntity_.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestCaseConditionExpressionServlet.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/web/jpa31.war/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/entity/tests/TestOLGH21204_Web.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/ejb/olgh21204Ejb.jar/META-INF/persistence-oracle-21.xml
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/src/com/ibm/ws/jpa/olgh21204/testlogic/JPATestOLGH21204Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/olgh21204/web/olgh21204Web.war/WEB-INF/classes/META-INF/persistence-oracle-21.xml
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_fat.common/test-applications/olgh19182/src/com/ibm/ws/jpa/olgh19182/testlogic/JPATestOLGH19182Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17369/src/com/ibm/ws/jpa/olgh17369/testlogic/JPATestOLGH17369Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19185/src/com/ibm/ws/jpa/olgh19185/testlogic/JPATestOLGH19185Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/testlogic/JPATestOLGH19342Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19998/src/com/ibm/ws/jpa/olgh19998/testlogic/JPATestOLGH19998Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh20890/src/com/ibm/ws/jpa/olgh20890/testlogic/JPATestOLGH20890Logic.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/vehicle/web/AbstractDatabaseManagementServlet.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/vehicle/web/EJBTestVehicleServlet.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/vehicle/web/JPATestServlet.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed

#22479 preparing to share jwk utilities between oidc and jakarta30 security and other minor updates
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-5.0/io.openliberty.appSecurity-5.0.feature
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/ssl/SecuritySSLUtils.java
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/credential/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/IdTokenValidator.java
Labels: CLA Signed

#22481 Fix portable issues with checkpoint and restore across different chipsets
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#22472 entity type always inferred
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/OrderRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/Data.java
  dev/io.openliberty.data.internal_fat/test-bundles/data/src/io/openliberty/data/internal/cdi/DataExtension.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22440 Quicker HTTP2 upgrade header check
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/upgrade/H2HandlerImpl.java
Labels: CLA Signed, team:Performance, performance

#22431 Scanning improvements
  dev/build.depScanner/bnd.bnd
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
  dev/build.depScanner/src/io/openliberty/depScanner/CheckRepoAndProductPOMs.java
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#22505 Enable JSF23CDIGeneralTests for Faces 4.0
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
Labels: noproductcode, CLA Signed

#22501 Enable JSF23SelectOneRadioGroupTests.java for Jakarta EE10 Faces 4.0
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22510 Update jetty version in pom.xml for telemetry TCK
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#22532 Revert "Use varargs in SibTr and SibMessage"
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ws/sib/utils/ras/SibMessage.java
  dev/com.ibm.ws.messaging.utils/src/com/ibm/ws/sib/utils/ras/SibTr.java
Labels: CLA Signed

#22513 Initial implementation of token and claims interfaces for issue #21166
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/JakartaSec30Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/AccessTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/ClaimsImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/CloneClaimsAction.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/IdentityTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/JwtClaimsImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/OpenIdClaimsImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/RefreshTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/package-info.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/AccessTokenImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/ClaimsImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/IdentityTokenImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/JwtClaimsImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/RefreshTokenImplTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponse.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenRequestorTest.java
Labels: CLA Signed

#22441 check for ipv6 before creating topicHost
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/chfw/GenericEndpointImpl.java
Labels: CLA Signed

#22523 Add OpenIdContextImpl for token support
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OpenIdContextImpl.java
Labels: CLA Signed

#22524 Change to no longer transform the idp application 3 times.
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/ShibbolethHelpers.java
  dev/com.ibm.ws.security.saml.sso_fat.common/ShibbolethCommon.gradle
Labels: CLA Signed, team:Performance

#22150 JSTL Transform and Xalan update
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSTLTests.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJSTL.war/resources/transformStyle.xsl
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJSTL.war/resources/xmlTransformTag.jsp
  dev/com.ibm.ws.org.apache.taglibs.standard/bnd.bnd
  dev/io.openliberty.org.apache.taglibs.standard.3.0/bnd.bnd
  dev/io.openliberty.org.apache.taglibs.standard/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, target:220011

#22537 Revert "Jakarta Mail 2.1 tests"
  .github/test-categories/MISC
  dev/io.openliberty.mail.2.0.internal_fat/bnd.bnd
  dev/io.openliberty.mail.2.0.internal_fat/build.gradle
  dev/io.openliberty.mail.2.0.internal_fat/fat/src/io/openliberty/mail/fat/FATSuite.java
  dev/io.openliberty.mail.2.0.internal_fat/test-applications/TestingApp/src/TestingApp/SMTP/SMTPInlineServlet.java
  dev/io.openliberty.mail.2.1.internal_fat/.classpath
  dev/io.openliberty.mail.2.1.internal_fat/.project
  dev/io.openliberty.mail.2.1.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.mail.2.1.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.mail.2.1.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.mail.2.1.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.mail.2.1.internal_fat/bnd.bnd
  dev/io.openliberty.mail.2.1.internal_fat/build.gradle
  dev/io.openliberty.mail.2.1.internal_fat/fat/src/io/openliberty/mail/fat/FATSuite.java
  dev/io.openliberty.mail.2.1.internal_fat/fat/src/io/openliberty/mail/fat/StreamProviderTest.java
  dev/io.openliberty.mail.2.1.internal_fat/publish/servers/mailSessionTestServer/bootstrap.properties
  dev/io.openliberty.mail.2.1.internal_fat/publish/servers/mailSessionTestServer/server.xml
  dev/io.openliberty.mail.2.1.internal_fat/test-applications/TestingApp/resources/.gitignore
  dev/io.openliberty.mail.2.1.internal_fat/test-applications/TestingApp/resources/META-INF/MANIFEST.MF
  dev/io.openliberty.mail.2.1.internal_fat/test-applications/TestingApp/resources/META-INF/permissions.xml
  dev/io.openliberty.mail.2.1.internal_fat/test-applications/TestingApp/src/TestingApp/StreamProvider/StreamProviderSessionServlet.java
Labels: noproductcode, CLA Signed

#22514 Jakarta security 30 identitystore implementation (2)
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/EndpointRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/CommonJose4jUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/utils/CommonJose4jUtilsTest.java
Labels: CLA Signed

#22424 Add initial test for checkpoint and WebSocket
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebSocketTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/webSocketServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/webSocketServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webSocketServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/openAPIapp/src/io/openliberty/checkpoint_fat/ApplicationRoot.java
  dev/io.openliberty.checkpoint_fat/test-applications/webSocketTest/src/webSocketTest/AlternateEndpoint.java
  dev/io.openliberty.checkpoint_fat/test-applications/webSocketTest/src/webSocketTest/DefaultEndpoint.java
  dev/io.openliberty.checkpoint_fat/test-applications/webSocketTest/src/webSocketTest/SocketClient.java
  dev/io.openliberty.checkpoint_fat/test-applications/webSocketTest/src/webSocketTest/SocketStartup.java
Labels: noproductcode, CLA Signed

#22531 Enable JSF23JPA22Test for EE10 Faces 4.0
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23JPA22Test.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22530 Issue #22529: cleanup bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationExceptionr/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_privateHeaderServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_wcServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ContextRootPrecedenceServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_PushBuilderSecurity/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_SCIException/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletContext_UnsupportedOperationExceptionr/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletPathForDefaultMapping_Default/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_ServletPathForDefaultMapping_False/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_X590CertServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_addJspFileServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_excludeAllHandledTypesClasses/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_headers/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_jspCdi/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_monitor/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSite/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sameSiteSecurity/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_Default/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_sendRedirectURL_True/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_stopAppStartListenerExceptionServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_wcServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_GetContextPath/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet50_wcServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_simpleTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_cookieSetAttributeTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_getRealPathTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_requestConnectionTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_xPoweredByHeaderTest/bootstrap.properties
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#22525 Enable jsf23 general and repeat tests for ee10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23GeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23UIRepeatConditionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/GlobalPhaseListenerQueueException.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/PerViewPhaseListenerDoNotQueueException.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/PerViewPhaseListenerQueueException.war/resources/META-INF/permissions.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22372 Servlet60 SessionCookieConfig new APIs
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionApplicationParameters.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionContext.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionCookieConfigImpl.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/SessionCookieConfigImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
  dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/SessionCookieConfigImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/container/config/factory/WebAppConfiguratorFactory60Impl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/container/config/WebAppConfiguratorHelper60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/container/config/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/session/impl/HttpSessionContextImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60SessionCookieConfigSCITest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60SessionCookieConfigXMLTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_sessionCookieConfigSCITest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_sessionCookieConfigSCITest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_sessionCookieConfigXMLTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_sessionCookieConfigXMLTest/jvm.options
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_sessionCookieConfigXMLTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/src/testsci/jar/servlets/ServletContainerInitializerImpl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/src/testsci/jar/servlets/TestSessionCookieConfigServlet.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.war/resources/WEB-INF/web.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22457 fixes for jbatch fats
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/BatchJobOperatorApiWithAppSecurityTest.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/DDLTest.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/util/BatchFATHelper.java
Labels: noproductcode, test bug, CLA Signed

#22515 fix cannot set status - response already committed warning
  dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/HttpMessageContextImpl.java
Labels: CLA Signed

#22447 Issue #22351: remove FlashImpl overlays
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/flash/FlashImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22544 PR for Issue 21171: Initial code for getting caller name and groups from tokens
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/identitystore/OidcIdentityStoreTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
Labels: CLA Signed, team:Security SSO

#21869 Add JCache serialization tests
  dev/com.ibm.ws.security.authentication/bnd.bnd
  dev/com.ibm.ws.security.authentication/test-resources/ser-files/CacheObject_1.ser
  dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
  dev/com.ibm.ws.security.social/test-resources/ser-files/UserProfile_1.ser
  dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/TestJwtToken.java
  dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/UserProfileSerializationTest.java
  dev/com.ibm.ws.security.token.ltpa/test-resources/test data/ser-files/LTPAToken2_1.ser
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2SerializationTest.java
  dev/com.ibm.ws.security.token/test-resources/ser-files/SingleSignonTokenImpl_1.ser
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/SerializationTest.java
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/TestToken.java
  dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/TestTokenServiceImpl.java
Labels: CLA Signed

#22413 Move websocket-2.1 to beta
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.1/io.openliberty.websocket-2.1.feature
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22460 Mark Pages 3.1 (and Tags 3.0) as Beta
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.1/io.openliberty.pages-3.1.feature
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22543 22542: Update test
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpXForwardedAndForwardedHeaderTests.java
Labels: noproductcode, test bug, CLA Signed, team:Sirius

#22528 Add checkpoint test for Jakarta Server Faces
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/build.gradle
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FacesTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/createDDL.ddl
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-frontendUI/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-frontendUI/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-frontendUI/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/resources/META-INF/MANIFEST.MF
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/resources/META-INF/persistence.xml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/src/java/io/openliberty/guides/event/dao/EventDao.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/src/java/io/openliberty/guides/event/models/.Event.java.swp
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/src/java/io/openliberty/guides/event/models/Event.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/src/java/io/openliberty/guides/event/resources/EventApplication.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/backendServices/src/java/io/openliberty/guides/event/resources/EventResource.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/META-INF/MANIFEST.MF
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/META-INF/microprofile-config.properties
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/WEB-INF/faces-config.xml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/content/eventForm.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/content/mainPage.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/content/updateEventForm.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/eventmanager.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/header/header.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/images/openliberty.png
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/navBar/leftNav.xhtml
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/resources/stylesheet.css
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/client/BadRequestExceptionMapper.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/client/EventClient.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/client/UnknownUrlException.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/client/UnknownUrlExceptionMapper.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/ui/EventBean.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/ui/facelets/PageDispatcher.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/ui/facelets/PageLoader.java
  dev/io.openliberty.checkpoint_fat/test-applications/eventMgr/frontendUI/src/java/io/openliberty/guides/event/ui/util/TimeMapUtil.java
Labels: noproductcode, CLA Signed

#22377 Add `com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat` FAT
  .github/test-categories/JPA_1
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestAggregateLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestComparisonLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestOrderingLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestUpdateLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.classpath
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.gitignore
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.project
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/fat/src/com/ibm/ws/jpa/tests/eclipselink/query/FATSuite.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/fat/src/com/ibm/ws/jpa/tests/eclipselink/query/RepeatWithJPA22.java
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat/publish/shared/config/jpa22-cfg.xml
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed

#22491 Revert "Open com.sun.jndi.dns to jdk.naming.dns module"
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: team:Zombie Apocalypse, CLA Signed, java 17

#22489 Transform select test servers
  dev/com.ibm.ws.transaction.hadb_fat.db2.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.lease/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.retriablecodes/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTestRetriableCodes.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSourceBeanInfo.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPreparedStatement.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.lease/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.lease/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.lease/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.retriablecodes/fat/src/com/ibm/ws/transaction/test/FATSuite.java
Labels: noproductcode, CLA Signed

#22576 Add facesContainer-4.0 to expectedFailures
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22559 Jakarta security 30 identitystore implementation (3)
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/credential/OidcTokensCredential.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/AuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/EndpointRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/IdTokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/CommonJose4jUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenValidatorTest.java
Labels: CLA Signed

#22556 Java level and Eclipse setting updates
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/.classpath
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/.project
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.pages.3.1.internal.factories/bnd.bnd
Labels: CLA Signed, team:Performance

#22561 Initial enablement of JSF 2.2 FAT for EE10
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIConfigByACPTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFlowsTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AppConfigPopTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentRendererTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22FlashEventsTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22IncludeTest.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22InputFileTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22LocalizationTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscLifecycleTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResourceLibraryContractHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ViewActionAndPhaseIdTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ViewPoolingTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtml5Tests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22557 fix_RTC_291274
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509token/CxfX509CrlTests.java
Labels: noproductcode, CLA Signed

#21625 Issue #21300: Update Servlet 6.0 Resources
  dev/io.openliberty.jakarta.servlet.6.0/.classpath
  dev/io.openliberty.jakarta.servlet.6.0/src/jakarta/servlet/resources/XMLSchema.dtd
  dev/io.openliberty.jakarta.servlet.6.0/src/jakarta/servlet/resources/datatypes.dtd
  dev/io.openliberty.jakarta.servlet.6.0/src/jakarta/servlet/resources/xml.xsd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22506 Clear test resources at the right time
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.single/test-applications/recoveryServer/src/com/ibm/ws/wsat/fat/server/ClearResourcesServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.single/test-applications/recoveryServer/src/com/ibm/ws/wsat/fat/server/MultiRecoveryCheckServlet.java
Labels: noproductcode, CLA Signed

#22586 Update to SnakeYAML 1.32
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.com.fasterxml.jackson/bnd.bnd
Labels: CLA Signed

#22588 Cleanup eclipse compile failure and unused feature that isn't needed
  dev/com.ibm.websphere.appserver.features/visibility/public/nosqlUnused-1.0/io.openliberty.nosqlUnused-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/nosqlUnused-1.0/resources/l10n/io.openliberty.nosqlUnused-1.0.properties
  dev/io.openliberty.jakarta.nosql.1.0/bnd.bnd
  dev/io.openliberty.jakarta.nosql.1.0/original.bnd
  dev/io.openliberty.jakarta.nosql.1.0/transformed.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
Labels: ID review not needed, CLA Signed, team:Performance

#22591 More token and claims updates for issue #21166
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/AccessTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/AccessTokenImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/IdentityTokenImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/tokens/OpenIdClaimsImplTest.java
Labels: CLA Signed

#22571 Fix issue with states getting changes in two new getPolicyConfig methods
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2.1/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/EJBJakarta10Base.java
  dev/com.ibm.ws.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/provider/WSPolicyConfigurationFactoryImpl.java
Labels: CLA Signed

#22583 initial impl of TokenRefresher
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/JakartaOidcTokenRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRefresher.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
Labels: CLA Signed, team:Security SSO, team:Core Security

#22580 Add OIDC logout
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/CustomLogoutStrategy.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/LocalLogoutStrategy.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/LogoutHandler.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/RPInitiatedLogoutStrategy.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/package-info.java
Labels: CLA Signed

#22594 Fix app security test rule
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/SessionImpl.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/AppsecurityTest.java
Labels: CLA Signed

#22360 Open com.sun.jndi.dns to jdk.naming.dns module
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: CLA Needed, CLA Signed

#22607 Update remaining CDI FAT tests for EE10
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/BeanDiscoveryModeNoneTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jaxrs/inject/InjectIntoPathTest.java
  dev/io.openliberty.cdi.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.cdi.3.0.internal_fat/build.gradle
  dev/io.openliberty.cdi.3.0.internal_fat/fat/src/io/openliberty/cdi30/internal/fat/tests/CDI30BeansXMLTest.java
Labels: noproductcode, CLA Signed

#22610 Fix CDI12ExtensionTest on EE10
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/helloworld/HelloWorldExtensionTestServlet.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionTest.java
Labels: noproductcode, CLA Signed

#22616 Improve EJB Handle testing
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/StatefulPassivationEJB.jar/src/com/ibm/ejb2x/base/pitt/ejb/BMTXSessionBean.java
Labels: in:EJB Container, noproductcode, team:Blizzard, CLA Signed, test delivery

#22609 Update java 19 test WAR to GA Java 19 level
  dev/io.openliberty.java.internal_fat/publish/servers/java19-server/apps/io.openliberty.java.internal_fat_19.war
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 19

#22449 Re-read environment variables for logging sources and formats on rest…
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/LogProviderConfigImpl.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LogsVerificationTest.java
  dev/io.openliberty.checkpoint_fat/publish/files/varfiles/server.env
Labels: CLA Signed

#22495 Updates for running tests on ARM
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/DB2KerberosContainer.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
Labels: noproductcode, CLA Signed

#22601 jakarta security 30, create credentialvalidationresult with issuer in addition to caller and group claims
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/utils/CommonJose4jUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenValidatorTest.java
Labels: CLA Signed

#22613 Fix one of the build failure captured in comment 4 of RTC 292562. Gen…
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/BaseTestCase.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/plugins/HazelcastTestPlugin.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/plugins/TestPlugin.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-client-localhost-only.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-localhost-only-multicastDisabled.xml
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/shared/resources/hazelcast/hazelcast-localhost-only.xml
Labels: noproductcode, CLA Signed, team:Wendigo East

#22590 modify float test to include new values for Java 19
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/RealFlushTest.java
Labels: noproductcode, CLA Signed

#22095 Update to Concurrency service release 3.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.ws.concurrent_fat_db/build.gradle
  dev/com.ibm.ws.concurrent_fat_policy/build.gradle
  dev/io.openliberty.jakarta.concurrency.3.0/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/standalone.pom.xml
Labels: team:Zombie Apocalypse, CLA Signed

#22597 [22596] - Escape CXF's services listing stylesheet path in jaxrs-2.0
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/commons_text/AggregateTranslator.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/commons_text/CharSequenceTranslator.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/commons_text/EntityArrays.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/commons_text/LookupTranslator.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/commons_text/StringEscapeUtils.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/servlet/servicelist/FormattedServiceListWriter.java
Labels: in:JAX-RS, CLA Signed, target:220011

#22573 minor featureUtility improvement
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
Labels: CLA Signed

#22575 update OidcHttpAuthenticationMechanism to store full request
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequestTest.java
Labels: CLA Signed

#22567 Message translation for session cookie config
  dev/com.ibm.ws.session/resources/com/ibm/ws/session/resources/WASSessionCore.nlsprops
  dev/io.openliberty.session.6.0.internal/bnd.bnd
  dev/io.openliberty.session.6.0.internal/resources/io/openliberty/session60/internal/resources/SessionMessages.nlsprops
  dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/SessionCookieConfigImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/src/testsci/jar/servlets/ServletContainerInitializerImpl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/src/testsci/jar/servlets/TestSessionCookieConfigServlet.java
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, jakartaEE10

#22619 add logoutHandler to client
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/LogoutHandler.java
Labels: CLA Signed

#22622 add unit tests for cookie based storage
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/CookieBasedStorageTest.java
Labels: noproductcode, CLA Signed

#21907 Update Concurrency TCK test suite to service release 3.0.2
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/README.md
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/build.gradle
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/FATSuite.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/bootstrap.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/configDropins/defaults/test.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/jvm.options
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/resources/logging/logging.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/server.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKWebServer/bootstrap.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKWebServer/configDropins/defaults/test.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKWebServer/jvm.options
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKWebServer/resources/logging/logging.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKWebServer/server.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/standalone.pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/tck-suite-full.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/tck-suite-web.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22637 Add server.env file to test server
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.log.verification.test/server.env
Labels: noproductcode, CLA Signed

#22641 Increase Retry Interval to 200ns
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/RemoteFile.java
Labels: noproductcode, CLA Signed

#22648 Improve FAT leaked server cleanup
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: test bug, CLA Signed

#22652 FeaturesStartTestAToL.testFeaturesStart should not run on java8 for data-1.0
  dev/build.featureStart.aToL_fat/publish/files/feature-java-levels.properties
  dev/build.featureStart.mToZ_fat/publish/files/feature-java-levels.properties
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#22500 Speed up SAML Fats in LITE mode - plus clean up extra error msgs
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/common/DefaultConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/common/PkixSAMLTests.java
  dev/com.ibm.ws.security.saml.sso_fat.common/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/fat/src/com/ibm/ws/security/saml/fat/logout/IDPInitiated/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/fat/src/com/ibm/ws/security/saml/fat/logout/httpServletRequest/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/fat/src/com/ibm/ws/security/saml/fat/logout/ibmSecurityLogout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#22650 MYFACES-4465: avoid ClassCastException
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/LambdaMetadataTargetImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22579 Produce and inject openIdContext
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OpenIdContextBean.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/JakartaSecurity30CDIExtension.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/extensions/OpenIdContextProducer.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/bnd.bnd.disabled
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotated.war/src/oidc/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotated.war/src/oidc/servlets/OidcAnnotatedServlet.java
Labels: CLA Signed

#22633 Skip reversal of service list
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/ConcurrentServiceReferenceSet.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/interceptor/RegisterRequestInterceptor.java
Labels: CLA Signed

#22617 Update connectors inbound security feature description for EE 10
  dev/com.ibm.websphere.appserver.features/visibility/public/connectorsInboundSecurity-2.0/resources/l10n/io.openliberty.connectorsInboundSecurity-2.0.properties
Labels: team:Zombie Apocalypse, CLA Signed, L2 ReviewNotRequired

#22642 Port Faces 4.0 Fixes
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/WebSocket.war/resources/faces40/OpenCloseWebSocketTest.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/WebSocket.war/resources/faces40/PushWebSocketTest.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/WebSocket.war/resources/faces40/websocketListeners.js
  dev/io.openliberty.faces.4.0.thirdparty/bnd.bnd
  dev/io.openliberty.faces.4.0.thirdparty/src/org/apache/myfaces/renderkit/html/base/HtmlButtonRendererBase.java
  dev/io.openliberty.faces.4.0.thirdparty/src/org/apache/myfaces/renderkit/html/base/util/HtmlJavaScriptUtils.java
  dev/io.openliberty.faces.4.0.thirdparty/src/org/apache/myfaces/renderkit/html/base/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/FacesArtifactProducerExtension.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#22646 add state hash to cookie name when storing request data
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequestTest.java
Labels: CLA Signed

#22625 Added wait for server config update for hideMessage logging tests
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/TestHideMessages.java
Labels: noproductcode, CLA Signed

#22545 Make message/console source values case insensitive
  dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JsonConfigBootstrapTest.java
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonConsoleSourceCaseInsensitive.xml
  dev/com.ibm.ws.logging.json_fat/publish/files/jsonMessageSourceAccessLogCaseInsensitive.xml
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#22587 FAT for Faces 4.0 ExternalContext addResponseCookie API
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/ExternalContextAddResponseCookieTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ExternalContextAddResponseCookieTest/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ExternalContextAddResponseCookieTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExternalContextAddResponseCookie.war/resources/ExternalContextAddResponseCookie.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExternalContextAddResponseCookie.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExternalContextAddResponseCookie.war/src/io/openliberty/org/apache/myfaces40/fat/externalContext/addResponseCookie/bean/ExternalContextAddResponseCookieBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#22627 fix logging permissions error in Java Security Builds
  dev/com.ibm.ws.logging_fat/test-applications/quick-log-test/src/com/ibm/ws/logging/fat/quick/log/test/QuickLogTest.java
Labels: noproductcode, CLA Signed

#22621 Only transform relevant servers
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD001/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD002/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer2/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer2/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer2/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer2/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/longPeerStaleTimeServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingDisabledServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingDisabledServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingDisabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingEnabledServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingEnabledServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/publish/servers/peerLockingEnabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/com/ibm/ws/transaction/test/tests/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.transaction/bnd.bnd
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TransactionManagerService.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: CLA Signed

#22666 Eclipse and bnd updates from recent changes
  dev/com.ibm.jbatch.container/transformed10.bnd
  dev/com.ibm.jbatch.internal.ee10/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
Labels: CLA Signed, team:Performance

#22674 move first part of mock code from test bucket
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.data1.0-jdbc.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.data1.0-persistence3.1.feature
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/NoSQLDataProvider.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PersistenceDataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryHandler.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/DataProvider.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/DataExtension.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/DataExtensionMetadata.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/EntityGroupKey.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/RepositoryProducer.java
Labels: team:Zombie Apocalypse

#22551 Fix test bug 199875
  dev/com.ibm.ws.classloading.bells_fat/bnd.bnd
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/BellFatTest.java
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/BellPropertiesTest.java
  dev/com.ibm.ws.classloading.bells_fat/fat/src/com/ibm/ws/classloading/BellSpiVisibilityTest.java
  dev/com.ibm.ws.classloading.bells_fat/publish/servers/bell_fat_server/bootstrap.properties
  dev/com.ibm.ws.classloading.bells_fat/publish/servers/bell_fat_server/jvm.options
  dev/com.ibm.ws.classloading.bells_fat/publish/servers/bell_fat_server/server.xml
Labels: noproductcode, test bug, team:OSGi Infrastructure

#22548 Fix failure in RTC 291613. Test was deleting caches between test meth…
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDynamicUpdateTest.java
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/docker/InfinispanContainer.java
  dev/io.openliberty.jcache.internal_fat.infinispan/fat/src/io/openliberty/jcache/internal/fat/plugins/InfinispanTestPlugin.java
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.casting.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.failure.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.failure.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.auth.cache.restart.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.delete.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.dynamicupdate.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.jwt.cookie.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.ltpa.cookie.cache.restart.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oauth20.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oauth20.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oidcclient.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oidcclient.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oidclogin.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.oidclogin.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.provider.in.app.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.1/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.saml.auth.cache.2/bootstrap.properties
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.spnego.auth.cache.1/bootstrap.properties
Labels: noproductcode, CLA Signed, team:Wendigo East

#22684 Update to MicroProfile Config 3.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/io.openliberty.microprofile.config.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/config.3.0.bnd
Labels: CLA Signed

#22683 Update to MicroProfile Fault Tolerance 4.0.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-4.0.feature
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/faulttolerance.4.0.bnd
Labels: CLA Signed

#22697 Adds ability of getting stored original request for issue #21163
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OpenIdContextImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/identitystore/OpenIdContextImplTest.java
Labels: CLA Signed

#22640 Update TCK Results output
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TestCaseResult.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TestSuiteResult.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TestSuiteXmlParser.java
Labels: noproductcode, CLA Signed
