Repository OpenLiberty/open-liberty, pull requests merged in 2022-01, with the labels that each got.

#19695 Specify timeout in correct units
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest.java
Labels: noproductcode, CLA Signed

#19699 transaction context for ContextServiceDefinition
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/WSManagedExecutorService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/AsyncMethod.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedCompletableFuture.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ApplicationScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/DependentScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/SessionScopedBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ContextServiceResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#19711 Fix Eclipse .classpath file for FAT com.ibm.ws.jpa.tests.container_mo…
  dev/com.ibm.ws.jpa.tests.container_modifyconfig_fat/.classpath
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#19679 suppress printed 405 stack trace in messages.log for jaxrs-2.0 and jaxrs-2.1
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/providers/customexceptionmapper/CustomExceptionMapperRegister.java
  dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/providers/customexceptionmapper/CustomExceptionMapperRegister.java
Labels: in:JAX-RS, CLA Signed

#19706 testIdentityNamePrecedence gets empty result after insufficient retries
  dev/com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19690 MP Config: improve performance of ServerXML vars
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/OSGiConfigUtils.java
  dev/io.openliberty.microprofile.config.internal.serverxml/src/io/openliberty/microprofile/config/internal/serverxml/ServerXMLDefaultVariableConfigSource.java
Labels: CLA Signed

#19538 Extra debug 3. Testing infrastructure or JDK is somehow calling COH twice in the same run, need to find out where.. and how
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/CapturedOutputHolder.java
  dev/com.ibm.ws.junit.extensions/src/com/ibm/websphere/ras/TrConfigZapper.java
Labels: CLA Signed

#19689 Remove any empty strings in hideMessageids
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#19724 Update isWin ACME check for adoptimum JDK
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19717 Tolerate ResourceAllocationExceptions in Tx Failover tests
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/com/ibm/ws/transaction/test/tests/FailoverTest2.java
Labels: noproductcode, CLA Signed

#19719 Issue #19707: RunnableJarHangsOnCtrlC
  dev/wlp.lib.extract/src/wlp/lib/extract/ShutdownHook.java
Labels: CLA Signed, release bug

#19722 temporarily tolerate EE 9 features for beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi-concurrent3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.0/io.openliberty.concurrent-3.0.feature
Labels: team:Zombie Apocalypse, CLA Signed

#19714 unchanged context for version 2.0 managed executor methods
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedExecutorServiceImpl.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/DependentScopedBean.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ResourcesProducer.java
Labels: team:Zombie Apocalypse, CLA Signed

#19720 Fix issue with com.ibm.ws.jpa.tests.container.client_fat bucket where…
  dev/com.ibm.ws.jpa.tests.container.client_fat/fat/src/com/ibm/ws/jpa/clientcontainer/fat/BasicFieldInjectTest.java
  dev/com.ibm.ws.jpa.tests.container.client_fat/fat/src/com/ibm/ws/jpa/clientcontainer/fat/BasicJNDIInjectTest.java
  dev/com.ibm.ws.jpa.tests.container.client_fat/fat/src/com/ibm/ws/jpa/clientcontainer/fat/BasicMethodInjectTest.java
  dev/com.ibm.ws.jpa.tests.container.client_fat/fat/src/com/ibm/ws/jpa/clientcontainer/fat/FATSuite.java
  dev/com.ibm.ws.jpa.tests.container.client_fat/publish/clients/BasicJPAFieldInjClient/client.xml
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#19715 Wait for token and userinfo test endpoints to be ready
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientConsumeUserinfoTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientEncryptionTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientSignatureAlgTests.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/IBM/OidcJaxRSClientAPITests.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_Encryption_oidc_usingSocialConfig.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_SignatureAlg_oidc_usingSocialConfig.java
Labels: test bug, CLA Signed, team:Security SSO

#19611 Reduce Oracle database helper `DSRA8207I` messages
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTraceTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracletracefat/src/trace/web/OracleTraceTestServlet.java
Labels: team:Zombie Apocalypse

#19709 Tolerate HeuristicCommitException
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/PartnerLogData.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/PartnerLogTable.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/XARecoveryData.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/ProtocolImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/TranManagerImpl.java
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/SimpleTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/com/ibm/ws/wsat/fat/tests/MultiRecoveryTest3.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed

#19728 Ensure ant override also copies prop file
  dev/com.ibm.ws.jmx_fat/build.gradle
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/properties.xml
  dev/com.ibm.ws.kernel.boot_fat/build.gradle
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/properties.xml
Labels: noproductcode, CLA Signed

#19740 Revert "temporarily tolerate EE 9 features for beta"
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi-concurrent3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.0/io.openliberty.concurrent-3.0.feature
Labels: CLA Signed

#19734 Remove check for shib_idp_session cookie on logout.
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/common/TimeoutTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#19737 test currentContextExecutor and getExecutionProperties
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/RequestScopedBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19743 redeliver 19722 with updated test
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi-concurrent3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.0/io.openliberty.concurrent-3.0.feature
  dev/io.openliberty.jakartaee9.internal_fat/bnd.bnd
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#19745 Reduce AccessController.doPriv calls
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileData.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/FileUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/SystemUtils.java
Labels: CLA Signed, team:Performance, performance

#19742 Clean up eclipse and github actions and switch gradle to require Java 11
  .github/test-categories/MP_GRAPHQL
  .github/test-categories/TRANSACTION_1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.concurrent_fat_jakarta/.classpath
  dev/com.ibm.ws.concurrent_fat_jakarta/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3.feature/.classpath
  dev/com.ibm.ws.jdbc.4.3.feature/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc.4.3.feature/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3/.classpath
  dev/com.ibm.ws.jdbc.4.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc.4.3/bnd.bnd
  dev/com.ibm.ws.jdbc.4.3/lib/java.sql.4.3.jar
  dev/com.ibm.ws.jdbc_fat_v43/.classpath
  dev/com.ibm.ws.jdbc_fat_v43/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jdbc_fat_v43/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container.client_fat/.classpath
  dev/io.openliberty.accesslists.internal/.classpath
  dev/io.openliberty.concurrent.cdi/.classpath
  dev/io.openliberty.concurrent.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.concurrent.cdi/bnd.bnd
  dev/io.openliberty.concurrent/.classpath
  dev/io.openliberty.concurrent/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.concurrent/bnd.bnd
  dev/io.openliberty.java11.internal/.classpath
  dev/io.openliberty.java11.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.java11.internal/bnd.bnd
  dev/settings.gradle
Labels: CLA Signed, team:Performance

#19684 remove atomic service reference again with an explicit mandatory
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
Labels: CLA Signed

#19747 test case with concurrency 3.0 resource definition annotions in an EJB
  dev/com.ibm.ws.concurrent_fat_jakarta/.classpath
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyTest.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/com.ibm.ws.injection.core/src/com/ibm/wsspi/injectionengine/JNDIEnvironmentRefType.java
Labels: team:Zombie Apocalypse, CLA Signed

#19725 don't archive server after test on windows
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
Labels: noproductcode, CLA Signed

#19744 Disable EE9 repeat on Windows in a couple long running OIDC Fats
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/FATSuite.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#19739 Minor JPA FAT cleanup
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat/publish/shared/config/hibernate21-cfg.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat/publish/shared/config/openjpa21-cfg.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat/publish/shared/config/hibernate22-cfg.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat/publish/shared/config/openjpa22-cfg.xml
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat/publish/shared/config/hibernate30-cfg.xml
  dev/com.ibm.ws.jpa.tests.eclipselink_fat/fat/src/com/ibm/ws/jpa/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.eclipselink_fat/test-applications/olgh19176/src/com/ibm/ws/jpa/olgh19176/testlogic/JPATestOLGH19176Logic.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/test-applications/defaultproperties/src/com/ibm/ws/jpa/defaultproperties/testlogic/DefaultPropertiesLogic.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/test-applications/overridepersistencecontext/src/com/ibm/ws/jpa/overridepersistencecontext/testlogic/OverridePersistenceContextLogic.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/test-applications/overridepersistencexml/src/com/ibm/ws/jpa/overridepersistencexml/testlogic/OverridePersistenceXmlLogic.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat/publish/shared/config/hibernate21-cfg.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat/publish/shared/config/openjpa21-cfg.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat/publish/shared/config/hibernate22-cfg.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat/publish/shared/config/openjpa22-cfg.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat/publish/shared/config/hibernate30-cfg.xml
  dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/fat/src/com/ibm/ws/jpa/spec10/embeddable/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/basic/src/com/ibm/ws/jpa/embeddable/basic/testlogic/EmbeddableBasicLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/BasicAnnotationTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/PKGeneratorTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/ReadOnlyTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/entitymanager/tests/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_fat.common/test-applications/entitymanager/src/com/ibm/ws/jpa/entitymanager/testlogic/EntityManagerLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_fat.common/test-applications/olgh19182/src/com/ibm/ws/jpa/olgh19182/testlogic/JPATestOLGH19182Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/query/tests/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17369/src/com/ibm/ws/jpa/olgh17369/testlogic/JPATestOLGH17369Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh17373/src/com/ibm/ws/jpa/olgh17373/testlogic/JPATestOLGH17373Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19185/src/com/ibm/ws/jpa/olgh19185/testlogic/JPATestOLGH19185Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/testlogic/JPATestOLGH19342Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh8014/src/com/ibm/ws/jpa/olgh8014/testlogic/JPATestOLGH8014Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/svlquery/src/com/ibm/ws/query/testlogic/JULoopQueryAnoTest.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/svlquery/src/com/ibm/ws/query/testlogic/JULoopQueryXMLTest.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/svlquery/src/com/ibm/ws/query/utils/SetupQueryTestCase.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/fat/src/com/ibm/ws/jpa/tests/spec20/JPAFATServletClient.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/olgh9018/src/com/ibm/ws/jpa/olgh9018/testlogic/JPATestOLGH9018Logic.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/query/src/com/ibm/ws/jpa/query/testlogic/QueryLogic.java
  dev/com.ibm.ws.jpa.tests.spec20_fat/test-applications/util/src/com/ibm/ws/jpa/fvt/util/testlogic/UtilTestLogic.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/jpaprovider/JPAPersistenceProvider.java
  dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
Labels: noproductcode, CLA Signed

#19757 Use xtrace on getshort
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
Labels: noproductcode, CLA Signed

#19758 need separate processor instances
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ContextServiceDefinitionProvider.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedScheduledExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedThreadFactoryDefinitionProvider.java
Labels: team:Zombie Apocalypse, CLA Signed

#19730 Renew Lease on TX leaseRenewer creation
  dev/com.ibm.tx.core/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/tests/Simple2PCCloudTest.java
Labels: CLA Signed

#19763 Prevent InjectionProcessor caching
  dev/com.ibm.ws.injection.core/src/com/ibm/wsspi/injectionengine/InjectionProcessor.java
Labels: in:Java EE Platform, team:Blizzard, CLA Signed

#19532 Dump server in MDB20Test.testBMTIA
  dev/com.ibm.ws.ejbcontainer.mdb.jms_fat/fat/src/com/ibm/ws/ejbcontainer/mdb/jms/fat/tests/MDB20Test.java
Labels: noproductcode, CLA Signed

#19771 test concurrency resource definition annotations in EJBs
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19776 Fix threading unittest ScheduledExecutorImplTest
  dev/com.ibm.ws.threading/test/com/ibm/ws/threading/internal/ScheduledExecutorImplTest.java
Labels: in:Kernel/Bootstrap, noproductcode, team:OSGi Infrastructure, CLA Signed

#19766 EE repeat actions
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatTests.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureSet.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
Labels: noproductcode, CLA Signed

#19761 Add additional port check on stop for AcmeClientTest
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeClientTest.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/HttpChallengeServer.java
Labels: noproductcode, CLA Signed

#19791 preventing NPE by checking if the String returned by getMessageKey() …
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
Labels: CLA Signed

#19782 Fix MDB RA FAT synchronization
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/ConcurBMTException.java
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/ConcurBMTNonJMS.java
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/ConcurCMTException.java
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/ConcurCMTNonJMS.java
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#19783 fix memory leak in provider tracking
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/context/ThirdPartyContextCoordinator.java
Labels: team:Zombie Apocalypse, CLA Signed

#19691 Issue #19480: Fix duplicate messages in WIM.
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/com/ibm/ws/security/wim/adapter/ldap/resources/LdapUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.core/resources/com/ibm/ws/security/wim/util/resources/WimUtilMessages.nlsprops
Labels: ID reviewed, CLA Signed, team:Wendigo East, L2 Reviewed

#19727 Fix PortableRemoteObject.narrow() signature
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#19778 Concurrent 3.0 TCK Suite
  dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.classpath
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.project
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/build.gradle
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/FATSuite.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/bootstrap.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/jvm.options
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/logging/logging.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/arquillian.p12
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/liberty.p12
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/setup.sh
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/server.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/tck-suite-full.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19789 adding ENGLISH locale to the toUpperCase() call to prevent corruption of the function name generated
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/DataModelSerializer.java
Labels: CLA Signed, release bug

#19805 EJBTimerTest fix interval countdown latch waiting in timeout
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/test-applications/MsgEndpointEJB.jar/src/com/ibm/ws/ejbcontainer/fat/msgendpoint/ejb/MDBTimedCMTBean.java
  dev/com.ibm.ws.ejbcontainer.timer.np_fat/test-applications/NpTimerOperationsEJB.jar/src/com/ibm/ws/ejbcontainer/timer/np/operations/ejb/SingletonTimedBean.java
  dev/com.ibm.ws.ejbcontainer.timer.np_fat/test-applications/NpTimerOperationsEJB.jar/src/com/ibm/ws/ejbcontainer/timer/np/operations/ejb/StatelessTimedBean.java
Labels: noproductcode, CLA Signed

#19823 resource definitions in EJB deployment descriptor
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19828 Revert "Use xtrace on getshort"
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/jvm.options
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/jvm.options
Labels: noproductcode, CLA Signed

#19777 Update EclipseLink 2.7.9 -> 2.7.10
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink_fat/test-applications/olgh19176/src/com/ibm/ws/jpa/olgh19176/testlogic/JPATestOLGH19176Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_fat.common/test-applications/olgh19182/src/com/ibm/ws/jpa/olgh19182/testlogic/JPATestOLGH19182Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19185/src/com/ibm/ws/jpa/olgh19185/testlogic/JPATestOLGH19185Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/testlogic/JPATestOLGH19342Logic.java
Labels: CLA Signed

#19768 Remove jee9 workarounds
  dev/com.ibm.ws.transaction.core_fat.1/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/HeuristicsDBTranlogTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/HeuristicsTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/SimpleDBTranlogTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/SimpleTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TimeoutTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TransactionalTest.java
  dev/com.ibm.ws.transaction.core_fat.1/fat/src/com/ibm/ws/transaction/test/tests/XATestBase.java
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.dblog/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.dblog_noRecoveryOnStartup/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction.timeout/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction_commitPriority/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction_eventListener/server.xml
  dev/com.ibm.ws.transaction.core_fat.1/publish/servers/com.ibm.ws.transaction_noRecoveryOnStartup/server.xml
  dev/com.ibm.ws.transaction.core_fat.10/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.10/fat/src/com/ibm/ws/transaction/test/tests/SimpleDBTranlogTestNoRecOnStart.java
  dev/com.ibm.ws.transaction.core_fat.10/fat/src/com/ibm/ws/transaction/test/tests/SimpleTestNoRecOnStart.java
  dev/com.ibm.ws.transaction.core_fat.2/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.3/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.4/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.5/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.6/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.7/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.8/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.9/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxDBRoSTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxDBTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxRoSTest.java
  dev/com.ibm.ws.transaction.core_fat.startMultiEJB/fat/src/com/ibm/ws/transaction/test/tests/EJBNewTxTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/DataSourceChangeTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryDBTranlogTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/XAFlowTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/publish/servers/com.ibm.ws.transaction_XAFlow/server.xml
  dev/com.ibm.ws.transaction.recovery_fat.3/bnd.bnd
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/SimpleTest.java
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/com/ibm/ws/wsat/fat/tests/WSATTest.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: noproductcode, CLA Signed

#19830 Fix Feature Info Output
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/FeatureInfoCommandTask.java
Labels: release bug

#19827 Ejb timer test
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/EjbSessionBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/EjbSessionBeanLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/MyCDIInterceptor.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/MyCDIInterceptorBinding.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/RequestScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/SessionScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newTimer/TestEjbTimerServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/FATSuite.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/NewEjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/newEjbTimer.war/resources/META-INF/permissions.xml
Labels: noproductcode, CLA Signed

#19815 Added new line under the last line of coding standards
  CONTRIBUTING.md
Labels: noproductcode, CLA Signed

#19797 PR for Issue 17448: Remove beta guards for jwtAccessTokenRemoteValidation
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#19834 rename folder
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/EjbSessionBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/EjbSessionBeanLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/MyCDIInterceptor.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/MyCDIInterceptorBinding.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/RequestScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/SessionScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/TestEjbTimerServlet.java
Labels: noproductcode, CLA Signed

#19794 Update date used in testUserAgentNeedsUpdateFalseCondition
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtmlUnit.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19825 Update Concurrecy TCK for JSP tests
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/server.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19541 propagate third party claims for id tokens
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/authentication/utility/SubjectHelper.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20Constants.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/responsetype/impl/OAuth20ResponseTypeHandlerCodeImpl.java
  dev/com.ibm.ws.security.openidconnect.server/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcServerConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandler.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCGrantTypeHandlerCodeImpl.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/OIDCResponseTypeHandlerImplicitImpl.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/server/internal/OidcServerConfigImplTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandlerTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/server/plugins/OIDCGrantTypeHandlerCodeImplTest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/openidconnect/OidcServerConfig.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#19819 Fix timing issue and enable better callback tracing
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
Labels: CLA Signed

#19546 adding block so windows doesn't run retrieveUninstallFileList twice
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#19818 Update restConnector features for mpOpenApi-3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationConfigSchema-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationValidatorSchema-3.0.feature
  dev/com.ibm.ws.rest.handler.config_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJCATest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJMSTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/FATSuite.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDataSourceTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJMSTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jca.fat/server.xml
  dev/io.openliberty.rest.handler.config.openapi.common/bnd.bnd
  dev/io.openliberty.rest.handler.validator.openapi.2.0/bnd.bnd
  dev/io.openliberty.rest.handler.validator.openapi.2.0/src/io/openliberty/rest/handler/validator/openapi20/ValidatorSchemaRESTHandler.java
  dev/io.openliberty.rest.handler.validator.openapi.2.0/src/io/openliberty/rest/handler/validator/openapi20/package-info.java
Labels: CLA Signed

#19838 Avoid TCK key/truststore conflicts
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/arquillian.p12
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/liberty.p12
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/resources/security/setup.sh
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKServer/server.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19836 Update oracle version on Acme FAT isWinJDK check
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/utils/AcmeFatUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19078 fix classloader issue with http client
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/HttpUtils.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/HttpClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientHttpUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OAuthClientHttpUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OAuthClientUtil.java
Labels: CLA Signed

#19835 Don't archive server on windows in multiple introspection test
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperMultipleIntrospectionTest.java
Labels: noproductcode, CLA Signed

#19847 enable development snapshot concurrency 3.0 TCK build
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19850 add allowed ffdc for one test
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/BatchJobOperatorApiWithAppSecurityTest.java
Labels: noproductcode, test bug, CLA Signed

#19857 Add Retry to obtain MongoDB in FAT
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoServerSelector.java
Labels: noproductcode, test bug, team:Blizzard, CLA Signed

#19833 wssecurity test updates to allow ffdc
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/common/CxfSAMLWSSTemplatesTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/common/CxfSAMLAsymSignEncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/common/CxfSAMLSymSignEncTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken/common/CxfSAMLWSSTemplatesTests.java
Labels: noproductcode, CLA Signed

#19852 Fix hardcoded realm from expectations
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/JDK11Expectations.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/JDK8Expectations.java
  dev/com.ibm.ws.security.spnego_fat.1/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
Labels: noproductcode, test bug, CLA Signed

#19865 Delete EERepeatTests and allow more CDI FATs to repeat with EE10
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/AsyncEventsTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/BasicCdi20Tests.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/BuiltinAnnoLiteralsTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/CDIContainerConfigTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/SecureAsyncEventsTest.java
  dev/com.ibm.ws.cdi.api_fat/bnd.bnd
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/bnd.bnd
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/implicitBeanArchive/ImplicitBeanArchiveTest.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/implicitBeanArchivesDisabled/ImplicitBeanArchivesDisabledTest.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/implicitEJB/ImplicitEJBTest.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/implicitWar/ImplicitWarTest.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/implicitWarLibJars/ImplicitWarLibJarsTest.java
  dev/com.ibm.ws.cdi.beansxml.implicit_fat/fat/src/com/ibm/ws/cdi/beansxml/implicit/fat/noAnnotations/ImplicitBeanArchiveNoAnnotationsTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/bnd.bnd
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/AfterTypeDiscoveryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/ClassExclusionTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/CustomerProvidedXMLParserFactoryTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/DisablingBeansXmlValidationTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/EmptyCDITest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/EnablingBeansXmlValidationTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/EnablingBeansXmlValidationTestEE7.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/MultipleBeansXmlTest.java
  dev/com.ibm.ws.cdi.beansxml_fat/fat/src/com/ibm/ws/cdi/beansxml/fat/tests/WebBeansBeansXmlInWeldTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/AroundConstructEjbTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/CDIManagedBeanInterceptorTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbConstructorInjectionTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbDiscoveryTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbScopeTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/InjectParameterTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/MultipleNamedEJBTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/NewEjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/RemoteEJBTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/StatefulSessionBeanInjectionTest.java
  dev/com.ibm.ws.cdi.third.party_fat/fat/src/com/ibm/ws/cdi12/fat/tests/HibernateSearchTest.java
  dev/com.ibm.ws.cdi.third.party_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ThirdPartyTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/BasicVisibilityTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/EJBVisibilityTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/SharedLibraryTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/ValidatorInJarTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi12/fat/tests/VisTest.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatTests.java
Labels: noproductcode, CLA Signed

#19859 ContextServiceDefinition used from different EJB
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ContextServiceDefinerBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19873 Cdi40 fats part2
  dev/com.ibm.ws.cdi.2.0_fat/bnd.bnd
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/AsyncEventsTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/BasicCdi20Tests.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/BuiltinAnnoLiteralsTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/CDIContainerConfigTest.java
  dev/com.ibm.ws.cdi.2.0_fat/fat/src/com/ibm/ws/cdi20/fat/tests/SecureAsyncEventsTest.java
  dev/com.ibm.ws.cdi.ejb_fat/bnd.bnd
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/AroundConstructEjbTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/CDIManagedBeanInterceptorTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbConstructorInjectionTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbDiscoveryTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbScopeTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/InjectParameterTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/MultipleNamedEJBTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/NewEjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/RemoteEJBTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/StatefulSessionBeanInjectionTest.java
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/remoteEJB.war/resources/META-INF/permissions.xml
Labels: noproductcode, CLA Signed

#19866 Work around slow server issues
  dev/com.ibm.ws.app.manager_fat/test-applications/slowapp.war/src/test/app/SlowStopAppListener.java
Labels: noproductcode, CLA Signed

#19820 Update JPA FAT Bucket for Oracle database support.
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/entity/tests/Entity_EJB.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/entity/tests/Entity_Web.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#19881 avoid matching services that are not resource factories
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent/src/io/openliberty/concurrent/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#19877 include Concurrency 3.0 TCK bucket in test lists
  .github/test-categories/CONCURRENT_3
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19775 Issue 5158: Correctly clean WASOidcNonce cookie in OIDC flows
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonMessageTools.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/Constants.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/AutomationTools.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/WebFormUtils.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/utils/AutomationToolsTest.java
  dev/com.ibm.ws.security.fat.common/test/com/ibm/ws/security/fat/common/web/WebFormUtilsTest.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonValidationTools.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCookieVerificationTests.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
Labels: CLA Signed, team:Security SSO

#19884 Avoid NPE in ExternalTestService
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestService.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#18990 fix NPE for tld file not found
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestEDR.war/resources/index.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JspDependent.java
Labels: in:Web Components, CLA Signed, regression, release bug, team:Sirius

#19241 beta of Concurrency 3.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi-concurrent3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakartaeePlatform-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.0/io.openliberty.concurrent-3.0.feature
  dev/io.openliberty.concurrent.cdi/bnd.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#19855 modify log deletion
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogHandle.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RLSUtils.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/com/ibm/ws/transaction/web/Base2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/com/ibm/ws/transaction/test/tests/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/publish/servers/FSCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/publish/servers/FSCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/publish/servers/longLeaseLengthFSServer1/server.xml
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/DataSourceChangeTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryDBTranlogTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/RecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/TestUtils.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/WaitForRecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.1/fat/src/com/ibm/ws/transaction/test/tests/XAFlowTest.java
Labels: CLA Signed

#19901 Update CDI Extension FAT
  dev/com.ibm.ws.cdi.extension_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.cdi.extension_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.cdi.extension_fat/bnd.bnd
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/AppExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionSPIConstructorExceptionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionSPITest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDIExtensionRepeatActions.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/DynamicBeanExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/FATSuite.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/ObserverTest.java
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.helloworld.extension-1.2.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.helloworld.extension-3.0.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.internals-1.2.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.internals-3.0.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.spi.constructor.fail.extension-1.2.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.spi.constructor.fail.extension-3.0.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.spi.extension-1.2.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.spi.extension-3.0.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/servers/cdi12RuntimeExtensionServer/server.xml
  dev/com.ibm.ws.cdi.extension_fat/publish/servers/cdi12SPIConstructorExceptionExtensionServer/server.xml
  dev/com.ibm.ws.cdi.extension_fat/publish/servers/cdi12SPIExtensionServer/server.xml
Labels: noproductcode, CLA Signed

#19902 Issue 5158: Add FAT for socialLogin feature
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonValidationTools.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCookieVerificationTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_CookieVerificationTests.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/configs/server_LibertyOP_cookieVerificationTests.xml
Labels: noproductcode, CLA Signed, team:Security SSO

#19909 tests for app-defined Concurrency resources in web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19886 Update LibertyClient and LibertyServer to run with JVM option "-Djava…
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/Launcher.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/cmdline/UtilityMain.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/wsspi/kernel/embeddable/ServerBuilder.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed

#19883 Update maven deps in MPHealth TCK
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#19904 Avoid FFDC by waiting for LTPA to start
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/ConcurrencyJSPTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19803 Introduce retry logic for tx SQL Lease log
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLHADBRetry.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRetriableLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRetry.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseTable.java
Labels: CLA Signed

#19854 add null check for security role user's and group's name
  dev/com.ibm.ws.security.appbnd/src/com/ibm/ws/security/appbnd/internal/authorization/AppBndAuthorizationTableService.java
Labels: CLA Signed

#19784 Issue #19781: Fix WIMUserRegistry.isValidGroup and isValidUser to onl…
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/ValidBridge.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/WIMURRegressionTest.java
Labels: CLA Signed, team:Wendigo East

#19882 Update server.bat with ping vs timeout command
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed, release bug

#19908 Issue #19906: Ensure WIM config changes are processed by the LDAP reg…
  dev/com.ibm.websphere.security.wim.base/src/com/ibm/websphere/security/wim/ras/WIMMessageKey.java
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap/resources/com/ibm/ws/security/wim/adapter/ldap/resources/LdapUtilMessages.nlsprops
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/ConfigManager.java
Labels: ID reviewed, CLA Signed

#19788 Asynchronously attempt to load ThreadPoolStats
  dev/com.ibm.ws.microprofile.metrics.2.0.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetricsHandler.java
  dev/com.ibm.ws.microprofile.metrics.2.3.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetricsHandler.java
  dev/com.ibm.ws.microprofile.metrics.monitor/src/com/ibm/ws/microprofile/metrics/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MonitorMetricsHandler.java
Labels: CLA Signed

#19837 xtrace
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.env
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/server.env
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.env
Labels: noproductcode, CLA Signed

#19913 Updates from recent changes
  .github/test-categories/CHECKPOINT
  .github/test-categories/GENERAL
  .github/test-categories/JAXRS_3
  .github/test-categories/JAXWS
  dev/com.ibm.ws.cdi.visibility_fat/bnd.bnd
  dev/com.ibm.ws.com.google.guava/bnd.overrides
  dev/com.ibm.ws.config_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/.classpath
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.net.shibboleth.utilities.java.support.7.5.1/bnd.overrides
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml/.classpath
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.0/bnd.bnd
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/bnd.bnd
  dev/io.openliberty.ws.jaxrs.global.handler.internal_fat/bnd.bnd
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/bnd.bnd
Labels: CLA Signed, team:Performance, GitHub Build

#19920 Issue #19919: Minor test comment and formatting fix
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30MiscTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19864 add nls message for 3rd party idtoken propagation error
  dev/com.ibm.ws.security.openidconnect.server/resources/com/ibm/ws/security/openidconnect/server/internal/resources/OidcServerMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandler.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandlerTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#19923 Add wait for LTPA ready to feature tests
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/FeatureOnlyTest.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#19925 tests for merging context service definitions
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19922 Fix test failure in RTC283807.
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/EJBModuleRealmTest.java
  dev/com.ibm.ws.security.javaeesec_fat.2/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalLoginTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19916 Update LDAP character encoding
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapHelper.java
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/xpath/ldap/util/LdapXPathTranslateHelper.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/EncodeSpecialCharactersTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/FATSuite.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.encodespecialcharacters/bootstrap.properties
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.encodespecialcharacters/server.xml
Labels: CLA Signed

#19929 Add a retry on addPartition for KRB LDAP server
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/ApacheDSandKDC.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#19898 PII Fixes for 22.0.0.2
  dev/com.ibm.ws.security.audit.file/resources/OSGI-INF/l10n/metatype.properties
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#19938 use unmodified proposed final 3.0 TCK from Jakarta staging
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/standalone.pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19896 More toleration of ResourceAllocationException
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/com/ibm/ws/transaction/test/dbrotationtests/DualServerDynamicDBRotationTest2.java
Labels: noproductcode, CLA Signed

#19936 Issue #19935: Remove SharedServer
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/NBMultiReadTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#19954 Notices for 22.0.0.2 release
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#19845 19841: defaultHostName variable should work with bootstrap.properties
  dev/com.ibm.ws.channelfw/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: in:Transport, CLA Signed, team:Sirius

#19899 update CDI API to 2.0.SP1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.websphere.javaee.cdi.2.0/bnd.bnd
Labels: CLA Signed

#19871 Fix RepositoryResolver install lists for tolerated dependencies
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/ProductRequirementInformation.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolutionException.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/LibertyVersion.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/CapabilityMatching.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRepository.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRequirement.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/MissingRequirementMatcher.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/MockFeature.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/RepositoryResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/ResolutionTests.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResourceMatcher.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsaTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverResultMatcher.java
Labels: CLA Signed

#19786 Issue #19785: When calling isValidGroup on a federated SAF registry w…
  dev/com.ibm.ws.security.wim.core/src/com/ibm/ws/security/wim/adapter/urbridge/URBridge.java
Labels: CLA Signed, team:Wendigo East

#19958 resource definitions in EJB deployment descriptor are not part of EE 10
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestEJB/src/test/jakarta/concurrency/ejb/ExecutorBean.java
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#19872 Remove beta guards for JPA default properties feature
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPUnitInfo.java
  dev/com.ibm.ws.jpa.container/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/publish/servers/JPAConfigServer/jvm.options
Labels: in:JPA, team:Blizzard, CLA Signed

#19844 Script for ws-schemagen.jar plus update help
  dev/com.ibm.ws.config.schemagen.schemagen/bnd.bnd
  dev/com.ibm.ws.config.schemagen/src/com/ibm/ws/config/schemagen/internal/Generator.java
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigOptions.nlsprops
Labels: ID review not needed, CLA Signed, L2 Reviewed

#19963 Follow-up changes for fixing RepositoryResolver install lists for tolerated dependencies
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/RepositoryResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverResultMatcher.java
Labels: CLA Signed

#19952 Rest Client 3.0: FT annotations on class
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpRestClient3.0-mpFaultTolerance4.0.feature
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceCDIComponent.java
  dev/com.ibm.ws.microprofile.faulttolerance.cdi/src/com/ibm/ws/microprofile/faulttolerance/cdi/FaultToleranceInterceptor.java
  dev/com.ibm.ws.microprofile.faulttolerance.spi/src/com/ibm/ws/microprofile/faulttolerance/spi/FTAnnotationInspector.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/RetryTest.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/ClassRetryClient.java
  dev/com.ibm.ws.microprofile.rest.client.FT_fat/test-applications/retryApp/src/mpRestClientFT/retry/RetryTestServlet.java
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/.classpath
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/.project
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/bnd.bnd
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/src/io/openliberty/microprofile/rest/client30/internal/ft/RestClientFTAnnotationInspector.java
  dev/io.openliberty.microprofile.rest.client.3.0.internal.ft/src/io/openliberty/microprofile/rest/client30/internal/ft/package-info.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java
Labels: CLA Signed, release bug

#19962 Ejb timer test
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/EjbSessionBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/EjbSessionBeanLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/MyCDIInterceptorBinding.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/RequestScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/newtimer/TestEjbTimerServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/ApplicationScopedCounter.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/EjbSessionBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/EjbSessionBean2.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/EjbSessionBeanLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/IncrementCountersRunnableTask.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/MyCDIInterceptor.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/MyCDIInterceptorBinding.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/RequestScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/RequestScopedCounter.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/SessionBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/SessionScopedBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/SessionScopedCounter.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/TestEjbNoTimerServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/TestEjbTimerServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/TestEjbTimerTimeOutServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/timer/view/EjbSessionBeanLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/FATSuite.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/NewEjbTimerTest.java
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/EjbTimer.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/ejbTimer.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.cdi.ejb_fat/test-applications/ejbTimer.war/resources/WEB-INF/beans.xml
Labels: noproductcode, CLA Signed

#19466 Add support to start selectors immediately for outbound channels
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/AioTCPChannel.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/AioWorkQueueManager.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/ConnectChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/NioTCPChannel.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/SocketRWChannelSelector.java
  dev/com.ibm.ws.channelfw/src/com/ibm/ws/tcpchannel/internal/WorkQueueManager.java
Labels: in:Transport, ID reviewed, CLA Signed, team:Sirius

#19942 Clean up WebContainer comment ONly to Only
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
Labels: in:Web Components, CLA Signed, team:Sirius

#19949 Lookup DataSource in HADB TX FailoverServlet
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/resources/.gitignore
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/resources/WEB-INF/web.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/com/ibm/ws/transaction/web/FailoverServlet.java
Labels: noproductcode, CLA Signed

#19950 logging for extension creation
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
Labels: CLA Signed

#19971 Update LibertyClient and LibertyServer simplicity classes to better h…
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, team:Blizzard, CLA Signed, Java 18

#19934 Clarify usage of the Tr API
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/Tr.java
Labels: CLA Signed

#19985 Revert "adding block so windows doesn't run retrieveUninstallFileList twice"
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed
