Repository OpenLiberty/open-liberty, pull requests merged in 2023-01, with the labels that each got.

#23660 add missing JSPG0077E
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/error0077.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#23759 Security 3.0: Add messages to ClaimsImpl
  dev/io.openliberty.security.jakartasec.3.0.internal/resources/io/openliberty/security/jakartasec/internal/resources/JakartaSecurity30Messages.nlsprops
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/ClaimsImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/package-info.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#23768 Get issuer from IdentityToken and add debug on OidcHttpAuthMech
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
Labels: CLA Signed

#22578 Remove pages-3.1 feature from faces-4.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/io.openliberty.faces-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.2/src/com/ibm/ws/jsf/extprocessor/JSFExtensionFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSFEL.war/src/com/ibm/ws/jsf22/el/components/CustomComponent.java
  dev/com.ibm.ws.jsf.jsp.shared/.classpath
  dev/com.ibm.ws.jsf.jsp.shared/.project
  dev/com.ibm.ws.jsf.jsp.shared/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jsf.jsp.shared/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jsf.jsp.shared/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jsf.jsp.shared/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jsf.jsp.shared/bnd.bnd
  dev/com.ibm.ws.jsf.jsp.shared/original.bnd
  dev/com.ibm.ws.jsf.jsp.shared/src/com/ibm/ws/jsf/jsp/shared/util/JspURIMatcher.java
  dev/com.ibm.ws.jsf.jsp.shared/src/com/ibm/ws/jsf/jsp/shared/util/package-info.java
  dev/com.ibm.ws.jsf.jsp.shared/transformed.bnd
  dev/com.ibm.ws.jsf.shared/bnd.bnd
  dev/io.openliberty.faces.4.0.internal/bnd.bnd
  dev/io.openliberty.faces.4.0.internal/src/io/openliberty/faces40/internal/ee/WASMyFacesContainerInitializer.java
  dev/io.openliberty.faces.4.0.internal/src/io/openliberty/faces40/internal/extprocessor/JSFExtensionFactory.java
  dev/io.openliberty.faces.internal/bnd.bnd
  dev/io.openliberty.faces.internal/src/com/ibm/ws/jsf/extprocessor/JSFExtensionFactory.java
Labels: in:Web Components, team:Sirius, jakartaEE10

#23779 Clean up Faces 4.0 bundle, remove remaining taglibconfig references
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/beans.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23791 Fix various Eclipse classpath issues
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.2/.classpath
  dev/io.openliberty.data.internal_fat_jpa/.classpath
Labels: noproductcode, team:Blizzard, CLA Signed

#23788 convert parameter value to String
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/jdbc-drivers/proxy/src/jdbc/driver/proxy/ProxyDataSource.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/server.xml
Labels: team:Zombie Apocalypse, CLA Signed

#23681 Get providerMetadata from Discovery and allow for null metadata on serialization
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OpenIdContextImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OpenIdContextUtils.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test-resources/testdata/ser-files/OpenIdContextImpl_1.ser
  dev/io.openliberty.security.jakartasec.3.0.internal/test-resources/testdata/ser-files/OpenIdContextImpl_2.ser
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/identitystore/OpenIdContextImplSerializationTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/identitystore/OpenIdContextImplTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTests.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/config/MetadataUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/config/MetadataUtilsTest.java
Labels: CLA Signed

#23790 Fix security EE10 repeat rules
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestFeatureEE10RepeatAction.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/SecurityTestFeatureEE9RepeatAction.java
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/files/serversettings/samlTestApplication.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
Labels: test bug, CLA Signed, team:Security SSO

#23795 Synchronized session attribute update method for JCache
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: CLA Signed

#23789 Split peer locking tests
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.project
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD001/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD001/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD002/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD002/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer2/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer2/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer2/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer2/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingDisabledServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingDisabledServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingDisabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingEnabledServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingEnabledServer1/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/peerLockingEnabledServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.gitignore
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.project
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/build.gradle
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/tests/DualServerPeerLockingTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking/fat/src/com/ibm/ws/transaction/test/.gitignore
Labels: noproductcode, CLA Signed

#23804 EJBSecurityCollaborator add waitForSecurityTime property
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncConfigServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncRemoteServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncSecureServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/publish/servers/ejbcontainer.mdb.ra.fat.MsgEndpointServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.SecureRemoteServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.SecureRemoteServerClient/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security/src/com/ibm/ws/ejbcontainer/security/internal/EJBSecurityCollaboratorImpl.java
  dev/com.ibm.ws.ejbcontainer.timer.auto_fat/publish/servers/AutoNPTimerContextPropServer/bootstrap.properties
Labels: CLA Signed

#23780 19911 - make getClassloader private
  dev/io.openliberty.cdi.4.0.internal.weld/src/com/ibm/ws/cdi/proxy/ProxyServicesImpl.java
Labels: CLA Signed

#23745 copy pkce parameters in oauth consent form
  dev/com.ibm.ws.security.oauth/resources/scripts/oauthForm.js
  dev/com.ibm.ws.security.openidconnect.server/resources/scripts/oauthForm.js
Labels: CLA Signed, team:Security SSO

#23787 Test checkpoint/restore with managedBeans
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/ManagedBeansTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointManagedBeans/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointManagedBeans/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointManagedBeans/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/managedBeans/src/managedBeans/ManagedBeanServlet.java
  dev/io.openliberty.checkpoint_fat/test-applications/managedBeans/src/managedBeans/TestManagedBean.java
Labels: noproductcode, CLA Signed

#23786 Repeat MP41 test against MP60
  dev/io.openliberty.microprofile41.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile41.internal_fat/fat/src/io/openliberty/microprofile41/internal/test/suite/BasicHealthTest.java
Labels: noproductcode, CLA Signed

#23822 ID on an embeddable
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/TemplateImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Badge.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employee.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employees.java
Labels: team:Zombie Apocalypse, CLA Signed

#23821 Fix intermittent checkpoint fat failure
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPJWT/server.xml
Labels: noproductcode, CLA Signed

#23805 Add support for @Before @After to FatServlet
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/BasicSseApp/src/jaxrs21sse/basic/BasicSseTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/DelaySseApp/src/jaxrs21sse/delay/DelaySseTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseJaxbApp/src/jaxrs21sse/jaxb/SseJaxbTestServlet.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseJsonbApp/src/jaxrs21sse/jsonb/SseJsonbTestServlet.java
  dev/fattest.simplicity/src/componenttest/annotation/processor/TestServletProcessor.java
Labels: noproductcode, CLA Signed

#23826 Bnd and eclipse settings updates
  dev/com.ibm.ws.concurrent.persistent_fat/timerInterfacesTestFeature.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jsf.shared/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger.adapter/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.servicemix.bundles.bcel/.project
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/bnd.overrides
  dev/com.ibm.ws.request.timing.jdbc/bnd.bnd
  dev/com.ibm.ws.request.timing.servlet/bnd.bnd
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.sipcontainer/bnd.bnd
  dev/com.ibm.ws.wsoc.1.1/bnd.bnd
  dev/fattest.simplicity/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.pages.tld.3.1/bnd.bnd
  dev/io.openliberty.jakarta.persistence.3.0/bnd.bnd
  dev/io.openliberty.jakarta.persistence.3.1/bnd.bnd
  dev/io.openliberty.jakarta.xmlBinding.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.eclipse.persistence-3.0/bnd.bnd
  dev/io.openliberty.org.eclipse.persistence-3.1/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.xmlBinding.3.0.internal.tools/bnd.bnd
  dev/io.openliberty.xmlBinding.4.0.internal.tools/bnd.bnd
Labels: CLA Signed, team:Performance

#23619 Overlay el j2sec property issue
  dev/io.openliberty.jakarta.expressionLanguage.5.0/.classpath
  dev/io.openliberty.jakarta.expressionLanguage.5.0/src/jakarta/el/Util.java
Labels: in:Transport, in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23825 Fix test failure for RTC 294304. The test will now wait for the appli…
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnA01Test.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#23797 Ensure that a valid repeat is used for all Java versions
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/LargeProjectRepeatActions.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
Labels: test bug, CLA Signed, team:Security SSO

#23831 Remove nonexistent source directories from .classpath files.
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.derby.lease/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/.classpath
Labels: noproductcode, CLA Signed, team:Performance

#23621 Proposed update from EPLv1 to EPLv2
  LICENSE
  README.md
  dev/build.image/publish/LICENSE
Labels: CLA Signed

#23383 Remove old packages from cdi-2.0 and 3.0
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-2.0/com.ibm.websphere.appserver.cdi-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-3.0/io.openliberty.cdi-3.0.feature
Labels: CLA Signed

#23809 Update Faces 4.0 to 4.0.0-RC3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/componentClass20.vm
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/FacesComponent.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/UIComponent.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/_ComponentAttributesMap.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/html/HtmlInputFile.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/html/HtmlInputSecret.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/context/PartialResponseWriter.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/convert/NumberConverter.java
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/model/SelectItem.java
  dev/io.openliberty.jakarta.faces.4.0/src/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorUtils.java
  dev/io.openliberty.jakarta.faces.4.0/src/org/apache/myfaces/core/api/shared/lang/PropertyDescriptorWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/application/ApplicationImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/application/ApplicationImplEventManager.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/application/FacesServletMappingUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/application/NavigationHandlerImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/view/ViewScopeEventListener.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/view/ViewScopeExtension.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/annotation/AnnotationConfigurator.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/element/FacesConfig.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/impl/FacesConfigDispenserImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/impl/element/FacesConfigImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/servlet/PartialViewContextImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/servlet/ServletExternalContextImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/el/resolver/LambdaBeanELResolver.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/flow/cdi/FlowScopeContext.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/flow/cdi/FlowScopeContextualStorageHolder.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/base/HtmlCheckboxRendererBase.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/base/HtmlRadioRendererBase.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/SelectItemsUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/BeanPropertyTagRule.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/LambdaMetadataTargetImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/webapp/FacesInitializerImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23836 reserved word usage
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Thing.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Things.java
Labels: team:Zombie Apocalypse, CLA Signed

#23810 Update the oAuth FAT repeat rules to reduce runtime
  dev/com.ibm.ws.security.oauth_fat/build.gradle
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/FATSuite.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#23824 Do not register monitor metrics when MetricRegistry is null
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/internal/MonitorMetrics.java
Labels: CLA Signed

#23830 Update error messages with translatable messages and clean up comments
  dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/internal/SharedMetricRegistries.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/internal/SmallryeMetricsCDIMetadata.java
Labels: ID reviewed, CLA Signed

#23828 Jakarta Security 3.0: Updates to allow none as a sig alg, optimize signature checking
  dev/io.openliberty.security.common.jwt/bnd.bnd
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/exceptions/EncodedSignatureEmptyException.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/exceptions/SignatureAlgorithmDoesNotMatchHeaderException.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/jws/JwsSignatureVerifier.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/jws/JwsVerificationKeyHelper.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/config/MetadataUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/jwt/JwtUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/config/MetadataUtilsTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestorTest.java
Labels: CLA Signed, team:Security SSO

#23482 Update Jakarta API bundles
  dev/io.openliberty.jakarta.activation.2.0/bnd.bnd
  dev/io.openliberty.jakarta.activation.2.1/bnd.bnd
  dev/io.openliberty.jakarta.annotation.2.0/bnd.bnd
  dev/io.openliberty.jakarta.annotation.2.1/bnd.bnd
  dev/io.openliberty.jakarta.authentication.2.0/bnd.bnd
  dev/io.openliberty.jakarta.authorization.2.0/bnd.bnd
  dev/io.openliberty.jakarta.batch.2.0/bnd.bnd
  dev/io.openliberty.jakarta.batch.2.1/bnd.bnd
  dev/io.openliberty.jakarta.cdi.3.0/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.2.0/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.0/bnd.bnd
  dev/io.openliberty.jakarta.connectors.2.0/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0/bnd.bnd
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.3.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.interceptor.2.0/bnd.bnd
  dev/io.openliberty.jakarta.interceptor.2.1/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.3.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.1/bnd.bnd
  dev/io.openliberty.jakarta.jstl.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jws.3.0/bnd.bnd
  dev/io.openliberty.jakarta.mail.2.0/bnd.bnd
  dev/io.openliberty.jakarta.messaging.3.0/bnd.bnd
  dev/io.openliberty.jakarta.messaging.3.0/bnd.overrides
  dev/io.openliberty.jakarta.nosql.1.0/bnd.bnd
  dev/io.openliberty.jakarta.pages.3.0/bnd.bnd
  dev/io.openliberty.jakarta.pages.tld.3.0/bnd.bnd
  dev/io.openliberty.jakarta.persistence.3.0/bnd.bnd
  dev/io.openliberty.jakarta.persistence.3.1/bnd.bnd
  dev/io.openliberty.jakarta.restfulWS.3.0/bnd.bnd
  dev/io.openliberty.jakarta.security.2.0/bnd.bnd
  dev/io.openliberty.jakarta.security.3.0/bnd.bnd
  dev/io.openliberty.jakarta.servlet.6.0/bnd.bnd
  dev/io.openliberty.jakarta.soap.2.0/bnd.bnd
  dev/io.openliberty.jakarta.transaction.2.0/bnd.bnd
  dev/io.openliberty.jakarta.validation.3.0/bnd.bnd
  dev/io.openliberty.jakarta.websocket.2.0/bnd.bnd
  dev/io.openliberty.jakarta.websocket.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.client.2.1/bnd.bnd
  dev/io.openliberty.jakarta.xmlBinding.3.0/bnd.bnd
  dev/io.openliberty.jakarta.xmlBinding.4.0/bnd.bnd
  dev/io.openliberty.jakarta.xmlWS.3.0/bnd.bnd
  dev/io.openliberty.jakarta/cdi.4.0.bnd
Labels: CLA Signed

#23829 Add fragment order tests according to the servlet specification
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/internal/WebFragmentsInfoImpl.java
  dev/com.ibm.ws.container.service/test/com/ibm/ws/container/service/config/internal/FragmentOrderingTest.java
Labels: CLA Signed

#23844 Collect CNFE from all lookup attempts as suppressed exceptions
  dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/internal/WASURLObjectFactoryFinder.java
Labels: CLA Signed

#23858 dropTables config property (internal)
  dev/com.ibm.ws.persistence/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
  dev/io.openliberty.data.internal_fat_config/.classpath
  dev/io.openliberty.data.internal_fat_config/.project
  dev/io.openliberty.data.internal_fat_config/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_config/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_config/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_config/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_config/bnd.bnd
  dev/io.openliberty.data.internal_fat_config/build.gradle
  dev/io.openliberty.data.internal_fat_config/fat/src/test/jakarta/data/config/DataConfigTest.java
  dev/io.openliberty.data.internal_fat_config/fat/src/test/jakarta/data/config/FATSuite.java
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/bootstrap.properties
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/server.xml
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Assertions.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/DataConfigTestServlet.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employee.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Person.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Student.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
Labels: team:Zombie Apocalypse, CLA Signed

#23764 Security 3.0: Add error message for TokenResponseValidator
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenResponseValidatorTest.java
Labels: ID reviewed, CLA Signed

#23864 Fix Defect 294367 (JSF22LocalizationTesterTests Failure )
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22LocalizationTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22LocalizationTester.war/resources/WEB-INF/faces-config.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22LocalizationTester.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22LocalizationTester.war/src/com/ibm/ws/jsf22/fat/localprops/jsf22_localization_resources.properties
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22LocalizationTester.war/src/com/ibm/ws/jsf22/fat/localprops/jsf22_localization_resources_zh_CN.properties
  dev/wlp-jakartaee-transform/rules/jakarta-direct.properties
  dev/wlp-jakartaee-transform/rules/jakarta-facelet.properties
  dev/wlp-jakartaee-transform/rules/jakarta-text.properties
Labels: CLA Signed

#23847 Update copyright header date range to include 2023
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22AppConfigPop.war/resources/WEB-INF/web.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#23750 Enabled cdi40 for faces40 automatically
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/io.openliberty.faces-4.0.feature
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentRendererTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22FlashEventsTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22InputFileTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22LocalizationTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscLifecycleTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResourceLibraryContractHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ViewActionAndPhaseIdTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtml5Tests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_UIViewRootGetDoctypeTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_externalContextAddResponseCookieTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_facesContextGetLifecycleServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_layoutAttribute/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_multipleInputFileTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_selectItemsServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_thirdPartyAPIServer/server.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23626 MP JWT 2.1 NLS messages for issue #20081
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.jwt-2.1.feature
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/internal/ConsumerUtilTest.java
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.mp.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.jwt.2.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/jwt.2.1.bnd
Labels: CLA Signed, L2 Reviewed, ID waiting on development

#23842 Add unit tests for ToDos in OidcIdentityStoreTest
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/TestClaimsDefinition.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/identitystore/OidcIdentityStoreTest.java
Labels: noproductcode, CLA Signed

#23857 Disable FFDC checking
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/fat/src/com/ibm/ws/wsat/fat/FATSuite.java
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/ACEScanner.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTestAction.java
Labels: noproductcode, CLA Signed

#23888 Fix server start test bug
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStopTest.java
Labels: noproductcode, CLA Signed

#23835 Move checkpoint to boot.common, remove FEATURES checkpoint and getPhase(String), resalt ProtectedString
  dev/com.ibm.ws.app.manager.wab/bnd.bnd
  dev/com.ibm.ws.app.manager/bnd.bnd
  dev/com.ibm.ws.config/bnd.bnd
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.kernel.boot.common/bnd.bnd
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointHook.java
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/package-info.java
  dev/com.ibm.ws.kernel.boot.core/bnd.bnd
  dev/com.ibm.ws.kernel.boot.nested/bnd.bnd
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.feature.core/bnd.bnd
  dev/com.ibm.ws.kernel.feature/bnd.bnd
  dev/com.ibm.ws.logging.core/bnd.bnd
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/ProtectedString.java
  dev/com.ibm.ws.logging_test/bnd.bnd
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.timedexit/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer/bnd.bnd
  dev/com.ibm.ws.webserver.plugin.runtime/bnd.bnd
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint/bnd.bnd
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint/test/io/openliberty/checkpoint/internal/CheckpointImplTest.java
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/OpenAPITest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SlowAppStartTest.java
  dev/io.openliberty.checkpoint_fat/publish/files/TestSPIConfig.fail.checkpoint/server.xml
  dev/io.openliberty.checkpoint_fat/publish/files/TestSPIConfig.fail.restore/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/server.xml
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestCheckpointHook.java
  dev/io.openliberty.checkpoint_fat/test.checkpoint.config.bundle.bnd
  dev/io.openliberty.ejbcontainer.checkpoint_fat/fat/src/io/openliberty/ejbcontainer/checkpoint/fat/tests/EjbStartCheckpointTest.java
  dev/io.openliberty.io.smallrye.config/bnd.bnd
Labels: CLA Signed

#23841 decode initial request query parameters before the final redirection
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/HttpRequestInfo.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/utils/InitialRequestUtilTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/utils/MsgCtxUtilTest.java
Labels: CLA Signed, team:Security SSO

#23863 Increase short lived token times again for Jakarta logout tests.
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/AccessTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonLogoutAndRefreshTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/publish/shared/config/oidcProvider.xml
Labels: test bug, CLA Signed, team:Security SSO, jakartaEE10

#23862 Jakarta Security 3.0: Add misc unit tests
  dev/com.ibm.ws.security.test.common/src/com/ibm/ws/security/test/common/jwt/utils/JwtUnitTestUtils.java
  dev/io.openliberty.security.common.jwt/.classpath
  dev/io.openliberty.security.common.jwt/bnd.bnd
  dev/io.openliberty.security.common.jwt/resources/io/openliberty/security/common/jwt/internal/resources/SecurityCommonJwtMessages.nlsprops
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/exceptions/SignatureAlgorithmDoesNotMatchHeaderException.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/exceptions/SigningKeyNotSpecifiedException.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/jws/JwsSignatureVerifier.java
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/jws/JwsVerificationKeyHelper.java
  dev/io.openliberty.security.common.jwt/test/io/openliberty/security/common/jwt/jws/JwsSignatureVerifierTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/jwt/JwtUtils.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenResponseValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/jwt/JwtUtilsTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenResponseValidatorTest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/userinfo/UserInfoRequestorTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#23882 Need to normalize keystore path when monitoring
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/config/SSLConfigManager.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/KeystoreConfigurationFactory.java
Labels: CLA Signed

#23880 Add CRIU_PATH env to set path to criu
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#23803 Add compilePersonalRTC.properties
  .ci-orchestrator/compile.properties
  .ci-orchestrator/compilePersonal.properties
  .ci-orchestrator/compilePersonalRTC.properties
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/rtcbuild.yml
Labels: CLA Signed, team:Continuous Delivery

#23744 Add accept file input testing
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AcceptInputFileTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_acceptInputFileTest/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_acceptInputFileTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AcceptInputFileTest.war/resources/AcceptInputFile.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AcceptInputFileTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AcceptInputFileTest.war/src/io/openliberty/org/apache/faces40/fat/inputfile/beans/AcceptFilesBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, jakartaEE10

#23898 Fix FragmentOrderTest timing problem
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/FragmentOrderTest.java
Labels: noproductcode, CLA Signed

#23895 Issue23894-FixJava2SecurityBuildBreak
  dev/com.ibm.ws.security.jaspic_fat/test-applications/JASPIFormLoginServlet.war/resources/META-INF/permissions.xml
Labels: noproductcode, CLA Signed

#23886 Myfaces 4488 and myfaces 4544
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/resource/default.dtd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23910 Update scheduledPersonalBuilds.yml
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/rtcbuild.yml
  .ci-orchestrator/scheduledPersonalBuilds.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#23893 make corrections to copyright headers
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employee.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Student.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#23915 experiment with composing queries by annotation
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Condition.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ShippingAddresses.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Update.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Where.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Condition.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Count.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Delete.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Exists.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Filter.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Operation.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Select.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Update.java
Labels: team:Zombie Apocalypse, CLA Signed

#23870 Test to demonstrate FFDC on tran log delete at shutdown
  dev/com.ibm.ws.transaction.cloud_fat.base/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_DUPXID001/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_DUPXID002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Base2PCCloudServlet.java
Labels: noproductcode, CLA Signed

#23906 Correct Scope error message and add missing unit tests to OpenIdAuthMech test
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/test/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapperTest.java
Labels: CLA Signed

#23900 Change broken admin center doc link to point to openliberty doc
  dev/com.ibm.ws.transport.http/resources/wasdev_files/adminCenter-welcome.js
Labels: CLA Signed

#23935 Disable server stop --timeout option and tests
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerHelpActions.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
Labels: CLA Signed

#23941 Fix bad merge
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance

#23956 Notices for 23.0.0.1
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed, target:23001

#23874 Further testing for 23448
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/RestRouteCache.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
Labels: CLA Signed

#23919 filter with OR
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Filter.java
Labels: team:Zombie Apocalypse

#23936 Fix EE10 repeat rules for SAML
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/fat/src/com/ibm/ws/security/saml/sso/fat/config/mapToUserRegistry/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/fat/src/com/ibm/ws/security/saml/sso/fat/endpoint/samlmetadata/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/fat/src/com/ibm/ws/security/saml/fat/logout/IDPInitiated/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/fat/src/com/ibm/ws/security/saml/fat/logout/httpServletRequest/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/fat/src/com/ibm/ws/security/saml/fat/logout/ibmSecurityLogout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/FATSuite.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#23899 Fix by increasing timeout
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#23959 ay11 fixes and minor changes to the server config validation dialog
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/css/editor.css
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
Labels: CLA Signed

#23926 JAX-WS: Unmarshaller error when optional JAXB Elements when Unmarshaller obtained from pool
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/soapEnvelopePrefix/src/com/ibm/ws/jaxws/test/soapenv/prefix/SoapEnvelopePrefixTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBDataBinding.java
Labels: CLA Signed

#23924 IllegalStateException
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/lifecycle/ApplicationPrereqMonitor.java
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/lifecycle/ApplicationStartBarrierImpl.java
Labels: CLA Signed

#23917 Upgrade to Jakarta Rest TCK version 3.1.3 resolving challenges
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#23946 Update to use GAV in repo references in BND where possible and other small fixes
  dev/cnf/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.servlet.3.0/bnd.bnd
  dev/com.ibm.websphere.javaee.validation.1.1/bnd.bnd
  dev/com.ibm.ws.com.sun.mail.javax.mail.1.6/bnd.bnd
  dev/com.ibm.ws.com.sun.mail.javax.mail.1.6/bnd.overrides
  dev/com.ibm.ws.com.sun.mail.javax.mail/bnd.bnd
  dev/com.ibm.ws.com.sun.mail.javax.mail/bnd.overrides
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.bnd
  dev/com.ibm.ws.org.apache.aries.jndi.core/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.collections/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.collections/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.collections/build.xml.working
  dev/com.ibm.ws.org.apache.commons.fileupload/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.eclipse.equinox.console/bnd.overrides
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/io.openliberty.com.sun.mail.jakarta.mail.2.0/bnd.bnd
  dev/io.openliberty.com.sun.mail.jakarta.mail.2.0/bnd.overrides
  dev/io.openliberty.org.apache.myfaces.3.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: CLA Signed, team:Performance

#23839 Test bells-1.0 with checkpoint/restore
  dev/com.ibm.websphere.appserver.features/visibility/public/bells-1.0/com.ibm.websphere.appserver.bells-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-1.0/com.ibm.websphere.appserver.concurrent-1.0.feature
  dev/com.ibm.ws.componenttest.2.0/publish/features/com.ibm.websphere.appserver.componenttest-2.0.mf
  dev/com.ibm.ws.componenttest/publish/features/com.ibm.websphere.appserver.componenttest-1.0.mf
  dev/com.ibm.ws.timedexit/publish/features/com.ibm.websphere.appserver.timedexit-1.0.mf
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebProfileEARtest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/CRIULogLevelTest/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/ValidFeatures/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAppSecurity/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFATServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-beanServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-frontendUI/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointJsonb/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointJsonp/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPConfig/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPHealth/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPJWT/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPMetrics/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerInventory/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerSystem/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointManagedBeans/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointSSL/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.log.verification.test/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.osgi.console.test/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/jndiServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/openAPIserver/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/slowStartAppServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/webProfileEARserver/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/webProfileJSP/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/webSocketServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/test-applications/app1/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/io.openliberty.checkpoint_fat/test-applications/app1/src/app1/AppInitializer.java
Labels: CLA Signed

#23911 For Java 20, JSP adjust option jdkSourceLevel up to level 8 if not already
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/JspOptions.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#23974 shorter name for comparisons
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Prime.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Compare.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Filter.java
Labels: team:Zombie Apocalypse, CLA Signed

#23921 Improved shutdown handling
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/PartnerLogData.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogImpl.java
Labels: CLA Signed

#23980 Add @SkipIfCheckpointNotSupported to the test
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/JsonpTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/ManagedBeansTest.java
Labels: noproductcode, CLA Signed

#23994 Revert "filter with OR"
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Filter.java
Labels: CLA Signed

#23686 Update to Smallrye OpenAPI 3.1.1 and add Jandex 3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jandex.internal-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-3.1/io.openliberty.mpOpenAPI-3.1.feature
  dev/io.openliberty.io.smallrye.jandex3/.classpath
  dev/io.openliberty.io.smallrye.jandex3/.gitignore
  dev/io.openliberty.io.smallrye.jandex3/.project
  dev/io.openliberty.io.smallrye.jandex3/.settings/bndtools.core.prefs
  dev/io.openliberty.io.smallrye.jandex3/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.smallrye.jandex3/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.jandex3/bnd.bnd
  dev/io.openliberty.io.smallrye.jandex3/bnd.overrides
  dev/io.openliberty.io.smallrye.openapi.core/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi.jaxrs/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi3.core/.classpath
  dev/io.openliberty.io.smallrye.openapi3.core/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi3.core/src/io/smallrye/openapi/api/util/VersionUtil.java
  dev/io.openliberty.io.smallrye.openapi3.jaxrs/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/src/io/openliberty/microprofile/openapi20/internal/services/impl/ConfigFieldProvider20Impl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/cache/ConfigSerializer.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/services/ConfigFieldProvider.java
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/src/io/openliberty/microprofile/openapi31/internal/services/impl/ConfigFieldProvider31Impl.java
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/test/io/openliberty/microprofile/openapi31/internal/services/impl/test/ConfigFieldProvider31ImplTest.java
  dev/io.openliberty.microprofile.openapi.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.jboss.narayana.rts/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
Labels: CLA Signed

#23997 Update JSF22IncludeTest for Faces 4.0
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22IncludeTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#23955 MYFACES-4543
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/flash/FlashImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/lifecycle/clientwindow/ClientWindowFactoryImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23912 Fix ToDo in TestOpenIdAuthMech
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/TestOpenIdAuthenticationMechanismDefinition.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/TestOpenIdProviderMetadataDefinition.java
Labels: noproductcode, CLA Signed

#23998 support old format of start-info
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentSerializer.java
Labels: CLA Signed

#23891 Upgrade SQLServer container
  dev/com.ibm.ws.jdbc_fat_sqlserver/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerSSLTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/release.sh
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver.ssl/security/truststore.p12
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/container-license-acceptance.txt
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/io.openliberty.org.testcontainers/cache/images
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#23562 Rerun runtime trace injection if problem byte codes are detected.
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/AbstractRasClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/AbstractRasMethodAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/AbstractTracingRasClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/JSR47TracingClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracePreprocessClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/LibertyTracingClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/bci/WebSphereTrTracingClassAdapter.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/ComputeRequiredException.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.java
Labels: in:Kernel/Bootstrap, CLA Signed, release bug

#23725 jakarta security 3.0 fat cleanup
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/expectations/Expectations.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseCallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationClaimsDefinitionTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationELValuesOverrideWithoutHttpSessionTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationResponseModeTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationScopeTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationUseNonceTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationUserInfoTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_scope.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_useNonce.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcScopeProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcUseNonceProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/UseNonceFalse.war/src/oidc/client/useNonceFalse/servlets/UseNonceFalseServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/UseNonceFalseWithEL.war/src/oidc/client/useNonceFalseWithEL/servlets/UseNonceFalseWithELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/UseNonceTrue.war/src/oidc/client/useNonceTrue/servlets/UseNonceTrueServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/UseNonceTrueWithEL.war/src/oidc/client/useNonceTrueWithEL/servlets/UseNonceTrueWithELServlet.java
Labels: CLA Signed

#23879 add fat tests for OpenIdAuthenticationMechanismDefinition extraParameters
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/configs/TestConfigMaps.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseOpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationExtraParametersTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_extraParameters.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcProvider_extraParameters.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersLeadingSpaceInKey.war/src/oidc/client/extraParametersLeadingSpaceInKey/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersLeadingSpaceInKey.war/src/oidc/client/extraParametersLeadingSpaceInKey/servlets/ExtraParametersLeadingSpaceInKeyServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersLeadingSpaceInKey.war/src/oidc/client/extraParametersLeadingSpaceInKey/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParam.war/src/oidc/client/extraParametersOneParam/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParam.war/src/oidc/client/extraParametersOneParam/servlets/ExtraParametersOneParamServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParam.war/src/oidc/client/extraParametersOneParam/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParamWithEL.war/src/oidc/client/extraParametersOneParamWithEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParamWithEL.war/src/oidc/client/extraParametersOneParamWithEL/servlets/ExtraParametersOneParamWithELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersOneParamWithEL.war/src/oidc/client/extraParametersOneParamWithEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersSpaceAsKey.war/src/oidc/client/extraParametersSpaceAsKey/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersSpaceAsKey.war/src/oidc/client/extraParametersSpaceAsKey/servlets/ExtraParametersSpaceAsKeyServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersSpaceAsKey.war/src/oidc/client/extraParametersSpaceAsKey/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersTwoParams.war/src/oidc/client/extraParametersTwoParams/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersTwoParams.war/src/oidc/client/extraParametersTwoParams/servlets/ExtraParametersTwoParamsServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersTwoParams.war/src/oidc/client/extraParametersTwoParams/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersUsingEL.war/src/oidc/client/extraParametersUsingEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersUsingEL.war/src/oidc/client/extraParametersUsingEL/servlets/ExtraParametersUsingELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ExtraParametersUsingEL.war/src/oidc/client/extraParametersUsingEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequest.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthorizationRequestTest.java
Labels: CLA Signed

#23996 reintroduce OR filter
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ProductRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Filter.java
Labels: team:Zombie Apocalypse, CLA Signed

#23939 Don't update file while polling is still enabled
  dev/com.ibm.ws.config.variables_fat/fat/src/test/server/config/ServiceBindingVarTests.java
Labels: noproductcode, CLA Signed

#23970 Added TCP portOpenRetries to MpHealth20 FAT to resolve port binding issues
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/DelayAppStartupHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/fat/src/com/ibm/ws/microprofile/health20/fat/MultipleHealthCheckTest.java
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DelayedHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DifferentAppNameHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/FailedApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/MultipleHealthCheck/server.xml
Labels: noproductcode, CLA Signed

#24006 Update ifix header processing for subbundles
  dev/wlp-gradle/subprojects/assemble.gradle
Labels: noproductcode, CLA Signed, team:Performance

#23962 Update to Expression Language 10.1.5 and removed Util.java overlay
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-5.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.5.0/.classpath
  dev/io.openliberty.jakarta.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.5.0/build.gradle
  dev/io.openliberty.jakarta.expressionLanguage.5.0/src/jakarta/el/Util.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/build.gradle
Labels: in:Transport, in:Web Components, CLA Signed, team:Sirius

#23963 Add Telemetry logging exporter
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.opentelemetry.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLoggingExporterTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/LoggingServlet.java
Labels: CLA Signed

#23920 WebContainer performance improvements
  dev/com.ibm.ws.httpservice/test/com/ibm/ws/httpsvc/test/SessionTest.java
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/AuthUtils.java
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpRequestImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpResponseImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/HeaderStorage.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/KeyMatcher.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/values/HttpHeaderKeys.java
  dev/com.ibm.ws.transport.http/src/io/openliberty/http/ext/HttpRequestExt.java
  dev/com.ibm.ws.transport.http/src/io/openliberty/http/ext/HttpResponseExt.java
  dev/com.ibm.ws.webcontainer.cors/bnd.bnd
  dev/com.ibm.ws.webcontainer.cors/src/com/ibm/ws/webcontainer/cors/CorsHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebRequestImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/BasicAuthAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/upgrade/H2HandlerImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterChain.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/response/IResponseImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/FileServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/RequestUtils.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/HttpSessionContextImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/ISRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/util/ListEnumeration.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/EncodingUtils.java
Labels: CLA Signed, team:Performance, performance

#24026 Update javadoc options to use addBooleanOption
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: noproductcode, CLA Signed, team:Performance

#24014 Implement OidcHttpAuthenticationMechanism's cleanSubject for issue #21177
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanismTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/logout/LogoutHandler.java
Labels: CLA Signed

#24017 Skip repeating EE9 on Fyre Windows
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#23993 Jsf22 component tester tests faces40
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/WEB-INF/component-taglib.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/resources/test-resources/collapsiblePanel.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/resources/test-resources/components.css
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/templateDoctag.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/templateDoctype.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testActionListenerOrder.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testCollapsiblePanel.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testDoctag.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testDoctype.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testMarquee.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/testTranslator.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/todosDoctag.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/resources/todosDoctype.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/MarqueeComponent.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/TranslatorComponent.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/beans/faces40/ActionListenerBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/beans/faces40/CollapsiblePanelController.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/beans/jsf22/ActionListenerBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ComponentTester.war/src/com/ibm/ws/jsf22/fat/componenttester/beans/jsf22/CollapsiblePanelController.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24002 Use SatisfyingConditionTarget to simplify process running condition
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/KeystoreConfigurationFactory.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/SSLComponent.java
Labels: CLA Signed

#23776 featureUtility proxy without auth
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
Labels: CLA Signed

#23992 Upgrade Oracle container and driver to 21c
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_krb5/README.txt
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/OracleKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/Dockerfile
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/release.sh
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/setup/2oracle.sh
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/build.gradle
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/containters/OracleSSLContainer.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/release.sh
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/setup/enable_ssl.sh
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/README.txt
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/security/cwallet.sso
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/security/ewallet.p12
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/store/client-keystore.jks
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/store/client-truststore.jks
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/io.openliberty.org.testcontainers/cache/images
  dev/wlp-gradle/subprojects/fat.gradle
Labels: team:Zombie Apocalypse, CLA Signed

#23840 Introduce testing for ajax execute and render `@this`
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AjaxRenderExecuteThisTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ajaxRenderExecuteThis/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ajaxRenderExecuteThis/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/ajaxRenderExecuteThis.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/resources/components/component.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/resources/components/wrapper.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/src/io/openliberty/org/apache/faces40/fat/ajax/beans/AjaxBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#23979 Add debug to JPA test to diagnose 293070
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestNewQueryTimeFunctionsServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#24021 Issue24019-FixBuildBreak291158
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnMergeConflictXMLBindingsTest.java
Labels: noproductcode, CLA Signed

#23783 Address Concurrency issues in Liberty Jakarta Rest for EE10
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/build.gradle
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/fat/src/com/ibm/ws/jaxrs/executor/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/publish/servers/com.ibm.ws.jaxrs.2.1.fat.executor/server.xml
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/test-applications/jaxrsapp/src/web/jaxrstest/JAXRSExecutorTestServlet.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/fat/src/io/openliberty/jakarta/rest31/tck/JakartaRest31TckPackageTest.java
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/AsyncClientExecutorService.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/concurrent/ContextualExecutorService.java
Labels: CLA Signed

#24022 Updates to personalbuild.yml and rtcbuild.yml
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/rtcbuild.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#23742 Don't reject URIs with encoded '/' with servlet 6
  dev/com.ibm.ws.jmx.connector.server.rest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/AttributeHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/MBeanAttributeRouterHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/MBeanHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/MBeanOperationHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/NotificationRegistrationsHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/helpers/RESTHelper.java
  dev/com.ibm.ws.jmx.connector.server.rest/test/com/ibm/ws/jmx/connector/server/rest/helpers/RESTHelperTest.java
Labels: CLA Signed

#24035 Issue #24034: Only skip EE9 on Windows when not running locally
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24029 Update to Felix SCR 2.2.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
Labels: CLA Signed

#23965 Added test for getContainerDefaultConfigurator access
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/all/MiscTest.java
  dev/io.openliberty.wsoc.2.1.internal_fat/test-applications/basic21.war/src/basic/war/ServerEPConfig.java
Labels: in:Transport, in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#23953 Port MYFACES-4505, & MYFACES-4532
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-development.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-minimal.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/composite/ClientBehaviorAttachedObjectTargetImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/composite/ClientBehaviorRedirectEventComponentWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/faces/core/AjaxHandler.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24008 Fix WL server dump on IBM i
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerDumpPackager.java
Labels: team:Zombie Apocalypse, CLA Signed, release bug

#24041 Add LargeProjectRepeatActions to oidc client.fat.2
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#23861 Add message to show only added features and always show full list of …
  dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/DisableAllFeaturesOnConflictTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FeatureTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/files/server_add_featureXA.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature/bootstrap.properties
  dev/fattest.simplicity/src/componenttest/depchain/FeatureDependencyProcessor.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24042 Don't use redirect-query-check with the static resource list
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/transport/servlet/AbstractHTTPServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/servlet/AbstractHTTPServlet.java
Labels: in:JAX-RS, CLA Signed, target:23002

#24032 Fail to run tests when run on non criu jvms if @SkipIfCheckpointNotSupported annotation is not added on the test class.
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SkipIfCheckpointNotSupportedAnnotationTest.java
Labels: noproductcode, CLA Signed

#23932 Create Basic OTel API test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAPITest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/BaggageAPIServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/CommonSDKServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/ContextAPIServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/TraceAPIServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Api/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Api/server.xml
Labels: noproductcode, CLA Signed

#24058 Update MP FT API to 4.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-4.0.feature
  dev/io.openliberty.org.eclipse.microprofile/faulttolerance.4.0.bnd
Labels: CLA Signed

#24028 23972 take2longtranatshutdown
  dev/com.ibm.ws.transaction.cloud_fat.base/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.base/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/LongTranTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_longtran/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_longtran/jvm.options
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_longtran/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/longtran/src/com/ibm/ws/longtran/web/LongtranServlet.java
Labels: noproductcode, CLA Signed

#23811 JSFHtmlUnittests ee10
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resources/testCompositeComponentAttribute.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resources/testProcessValueChangeAndProcessAction.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resources/testProcessValueChangeAndProcessActionResult.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resourcesFaces40/resources/components/compositeComponent.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/resourcesJSF22/resources/components/compositeComponent.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/faces40/AnimalBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/faces40/MethodExpressionBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/faces40/TestGetType.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/jsf22/AnimalBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/jsf22/MethodExpressionBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/jsf22/TestGetType.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/utilities/faces40/MethodExpressionHelper.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/utilities/jsf22/MethodExpressionHelper.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.jar/resources/META-INF/resources/templates/basicTemplate.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/WEB-INF/resources/scripts/simpleMessageScript.js
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/WEB-INF/resources/templates/basicTemplate.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/checkifLibraryExists.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/loadViewFromExternalLocation.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/mapViewIdToResource.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/messageToPerson.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/personInformation.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/resources/testUserAgentNeedsUpdateMethod.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/faces40/LoadViewFromExternalLocationBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/faces40/MapResourcePathBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/faces40/PersonInformationBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/faces40/ResourceUserAgentBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/jsf22/LoadViewFromExternalLocationBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/jsf22/MapResourcePathBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/jsf22/PersonInformationBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22TestResources.war/src/com/ibm/ws/jsf22/fat/resources/beans/jsf22/ResourceUserAgentBean.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/el/FacesELContext.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#23845 Jsf22 misc tests ee10
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22MiscellaneousServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22MiscellaneousServer/server.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.jar/src/com/ibm/ws/jsf22/fat/miscbean/jar/AppManagerBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.jar/src/com/ibm/ws/jsf22/fat/miscbean/jar/EmailBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.jar/src/com/ibm/ws/jsf22/fat/miscbean/jar/ViewScopedManagedBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.jar/src/com/ibm/ws/jsf22/fat/miscbean/jar/faces40/MiscellaneousViewScopeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.jar/src/com/ibm/ws/jsf22/fat/miscbean/jar/jsf22/MiscellaneousViewScopeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/WEB-INF/faces-config.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/protectedPage.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testAPI.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testCSRF.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testCustomValueBindingTag.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testExpressionFactoryImplConsistency.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testResetValues.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testSimple.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testViewScopeBinding.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/testViewScopeMyFaces.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/viewScope/errorPage.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/resources/viewScope/resultPage.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/src/com/ibm/ws/jsf22/fat/miscbean/ValueBindingTag.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/src/com/ibm/ws/jsf22/fat/miscbean/faces40/MiscellaneousBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/src/com/ibm/ws/jsf22/fat/miscbean/faces40/MiscellaneousEmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/src/com/ibm/ws/jsf22/fat/miscbean/jsf22/MiscellaneousBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22Miscellaneous.war/src/com/ibm/ws/jsf22/fat/miscbean/jsf22/MiscellaneousEmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/resources/invalidate.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/src/com/ibm/ws/jsf22/fat/viewscopedleak/SessionSizeHelper.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/src/com/ibm/ws/jsf22/fat/viewscopedleak/ViewScopedCDIBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24053 Add Wsoc,Http,and Webcontainer traces
  dev/com.ibm.ws.jsf.2.3_fat/publish/servers/jsf23WebSocketServer/bootstrap.properties
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24023 Bump to smallrye metrics 5.0.0-M6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
Labels: CLA Signed

#24031 support multiple services that are implementing UnprotectedResourceService
  dev/com.ibm.ws.webcontainer.security.feature/bnd.bnd
Labels: CLA Signed

#24071 Revert "Add message to show only added features and always show full list of …"
  dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/DisableAllFeaturesOnConflictTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FeatureTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/files/server_add_featureXA.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature/bootstrap.properties
  dev/fattest.simplicity/src/componenttest/depchain/FeatureDependencyProcessor.java
Labels: CLA Signed

#24033 EJB Client Test: Ignore slow starting app warning on windows
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/fat/src/com/ibm/ws/ejbcontainer/remote/client/fat/tests/EjbLinkTest.java
Labels: noproductcode, CLA Signed

#23988 Added button role for cancelFilterHref and deleteSearchInputHref
  dev/com.ibm.ws.ui/resources/WEB-CONTENT/js/widgets/LibertyToolbox.js
Labels: CLA Signed, Squad: UI

#24059 add fat tests for OpenIdAuthenticationMechanismDefinition display and displayExpression
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonAnnotatedSecurityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/configs/TestConfigMaps.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseOpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/MinimumBaseOpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationDisplayTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_display.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcDisplayProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEL.war/src/oidc/client/displayEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEL.war/src/oidc/client/displayEL/servlets/DisplayELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEL.war/src/oidc/client/displayEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEmpty.war/src/oidc/client/displayEmpty/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEmpty.war/src/oidc/client/displayEmpty/servlets/DisplayEmptyServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayEmpty.war/src/oidc/client/displayEmpty/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPage.war/src/oidc/client/displayPage/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPage.war/src/oidc/client/displayPage/servlets/DisplayPageServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPage.war/src/oidc/client/displayPage/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopup.war/src/oidc/client/displayPopup/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopup.war/src/oidc/client/displayPopup/servlets/DisplayPopupServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopup.war/src/oidc/client/displayPopup/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopupWithEL.war/src/oidc/client/displayPopupWithEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopupWithEL.war/src/oidc/client/displayPopupWithEL/servlets/DisplayPopupWithELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayPopupWithEL.war/src/oidc/client/displayPopupWithEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayTouch.war/src/oidc/client/displayTouch/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayTouch.war/src/oidc/client/displayTouch/servlets/DisplayTouchServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayTouch.war/src/oidc/client/displayTouch/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayWap.war/src/oidc/client/displayWap/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayWap.war/src/oidc/client/displayWap/servlets/DisplayWapServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/DisplayWap.war/src/oidc/client/displayWap/servlets/OpenIdConfig.java
Labels: CLA Signed

#24083 Basic scenarios with EmbeddedId and intermixed name patterns
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Account.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/AccountId.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Accounts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#24060 Add tests for updated bell properties with checkpoint/restore.
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
  dev/io.openliberty.checkpoint_fat/publish/features/user.feature.checkpoint.bells-1.0.mf
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/bells/resources/META-INF/services/javax.servlet.ServletContainerInitializer
  dev/io.openliberty.checkpoint_fat/test-applications/bells/resources/META-INF/services/test.checkpoint.bells.bundle.TestInterface
  dev/io.openliberty.checkpoint_fat/test-applications/bells/src/bells/AppInitializer.java
  dev/io.openliberty.checkpoint_fat/test-applications/bells/src/bells/ServletA.java
  dev/io.openliberty.checkpoint_fat/test-applications/bells/src/bells/TestInterfaceImpl.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.bells.bundle/src/test/checkpoint/bells/bundle/TestInterface.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.bells.bundle/src/test/checkpoint/bells/bundle/TestUser.java
  dev/io.openliberty.checkpoint_fat/test.checkpoint.bells.bundle.bnd
Labels: noproductcode, CLA Signed

#24052 Help Debug why servlet Mbean is not registered for TestEDF2 in com.ibm.ws.microprofile.metrics.2.x.monitor_fat
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF2/bootstrap.properties
Labels: noproductcode, CLA Signed

#24085 Use ShrinkHelper.exportDropinAppToServer to ensure apps are started
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/CDIFlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSFContainerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24076 Jsf22 reset values and ajax delay tests ee10
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22TracingServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.2_fat/publish/servers/jsf22TracingServer/server.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/WEB-INF/faces-config.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/ajaxDelayTest.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/ajaxDelayTestNone.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/ajaxZeroDelayTest.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/resources/resetValuesTest.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/src/com/ibm/ws/jsf22/fat/ajax/ajaxDelay/faces40/EmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/src/com/ibm/ws/jsf22/fat/ajax/ajaxDelay/jsf22/EmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/src/com/ibm/ws/jsf22/fat/ajax/resetValue/faces40/ResetBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22Ajax.war/src/com/ibm/ws/jsf22/fat/ajax/resetValue/jsf22/ResetBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24070 Update the CRIUSupport API to the latest EA of OpenJ9
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/openj9/ExecuteCRIU_OpenJ9.java
  dev/io.openliberty.org.eclipse.openj9.criu/src/org/eclipse/openj9/criu/CRIUSupport.java
  dev/io.openliberty.org.eclipse.openj9.criu/src/org/eclipse/openj9/criu/RestoreException.java
Labels: CLA Signed

#24065 Change configuration to only run the most recent version of the tests…
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_executor/fat/src/com/ibm/ws/jaxrs/executor/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.defaultexceptionmapper_fat/fat/src/com/ibm/ws/jaxrs/defaultexceptionmapper_fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EmptyAction.java
  dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/fat/src/io/openliberty/restfulWS30/cdi30/fat/FATSuite.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#24096 MYFACES-4552
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/impl/FacesConfigUnmarshallerImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24078 Tidy test servers
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/tests/DualServerPeerLockingTest2.java
Labels: noproductcode, CLA Signed

#24082 24077: DoNotAllowDuplicateSetCookie property not working
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/FATSuite.java
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/HttpSetCookieTests.java
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/AllowDuplicateSetCookies-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/publish/files/remoteIPConfig/DoNotAllowDuplicateSetCookies-server.xml
  dev/com.ibm.ws.transport.http.remoteip_fat/test-applications/EndpointInformation/src/com/ibm/ws/transport/http/servlets/EndpointInformationServlet.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
Labels: in:Transport, CLA Signed

#24050 Reject WSAT traffic during quiesce
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/RemoteTransactionControllerService.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/remote/TransactionWrapper.java
Labels: CLA Signed

#24074 Telemetry misconfiguration test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrsmisconfig/JaxRsMisConfigEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MisConfig/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MisConfig/server.xml
Labels: noproductcode, CLA Signed

#24064 Create Async Context propagation test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/MultiThreadedContextTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/context/MultiThreadedContextServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Context/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Context/server.xml
Labels: noproductcode, CLA Signed

#23816 Remove privileges from proxy services
  dev/com.ibm.ws.cdi.1.2.weld/src/com/ibm/ws/cdi/proxy/ProxyServicesImpl.java
  dev/com.ibm.ws.cdi.2.0.weld/src/com/ibm/ws/cdi/proxy/ProxyServicesImpl.java
  dev/com.ibm.ws.org.jboss.weld/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/bean/proxy/ProxyFactory.java
  dev/io.openliberty.cdi.4.0.internal.weld/src/com/ibm/ws/cdi/proxy/ProxyServicesImpl.java
Labels: CLA Signed

#24113 Update test case for slow test machines
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTimeoutTest.java
Labels: noproductcode, CLA Signed

#24106 Enable testViewScopeInjections for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIInjectionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/FactoryInfo.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/NavigationHandler.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/NavigationHandlerFail.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/NavigationHandlerPass.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/TestBean.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/TestResolver.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/ViewScope.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resourcesFaces40/WEB-INF/faces-config.xml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIInjectionTests.war/resourcesJSF23/WEB-INF/faces-config.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24098 Update MP Metrics 5.0 TCK to use final release
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#24103 Update MP Metrics 5.0 TCK to use final release
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#24107 Fix checkpoint FAT
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/test-applications/app1/resources/META-INF/services/javax.servlet.ServletContainerInitializer
Labels: noproductcode, CLA Signed

#24130 Updates to build files for correct building
  dev/cnf/build.bnd
  dev/com.ibm.ws.jpa.tests.javasupport_fat/.classpath
  dev/com.ibm.ws.jpa.tests.javasupport_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1/.classpath
Labels: CLA Signed, team:Performance

#23905 Fix NPE in JakartaEE9Action#transformApp
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius
