Repository OpenLiberty/open-liberty, pull requests merged in 2023-08, with the labels that each got.

#25859 NOTICES for 23.0.0.8
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#25844 Springboot websocket fat test
  dev/io.openliberty.springboot.fat30.security.app/.classpath
  dev/io.openliberty.springboot.fat30.security.app/.gitignore
  dev/io.openliberty.springboot.fat30.security.app/.project
  dev/io.openliberty.springboot.fat30.security.app/.settings/bndtools.core.prefs
  dev/io.openliberty.springboot.fat30.security.app/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.springboot.fat30.security.app/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.springboot.fat30.security.app/bnd.bnd
  dev/io.openliberty.springboot.fat30.security.app/build.gradle
  dev/io.openliberty.springboot.fat30.security.app/springboot.gradle
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/CustomizationBean.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/MvcConfig.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/SecurityConfiguration.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/TestApplication.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/TestErrorPageRegistrar.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/TestWebFilter.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/TestWebListener.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/java/com/ibm/ws/springboot/fat30/test/app/TestWebServlet.java
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/application.properties
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/public/defaultErrorPage.html
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/public/errorPageException.html
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/public/file.weby
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/public/noSuchPage.html
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/public/useJarUrlsTest.html
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/server-keystore.jks
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/server-truststore.jks
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/templates/hello.html
  dev/io.openliberty.springboot.fat30.security.app/src/main/resources/templates/login.html
  dev/io.openliberty.springboot.fat30_fat/bnd.bnd
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingWebsocketFeatureTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/SpringSecurityTests30.java
  dev/io.openliberty.springboot.fat30_fat/publish/servers/SpringBootTests/jvm.options
Labels: noproductcode, CLA Signed

#25661 First drop of mpReactiveMessaging-3.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.reactive.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-3.0/io.openliberty.mpReactiveMessaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-3.0/resources/l10n/io.openliberty.mpReactiveMessaging-3.0.properties
  dev/com.ibm.ws.io.smallrye.reactive.converter-api/bnd.bnd
  dev/com.ibm.ws.io.smallrye.reactive.messaging-provider/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.adapter/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/original.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/transformed.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseConfiguredTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseProducerRecordTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomKeySerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/ReactiveStreamsTckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BasicReactiveMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/MissingGroupIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/PlaintextTests.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/ReactiveMessagingActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.classpath
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.project
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.settings/bndtools.core.prefs
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.reactive.converter-api3/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.io.smallrye.reactive.converter-api3/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.classpath
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.gitignore
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.project
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.settings/bndtools.core.prefs
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/resources/META-INF/beans.xml
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/src/io/openliberty/microprofile/reactive/messaging30/internal/OLReactiveMessaging30Extension.java
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/src/io/smallrye/reactive/messaging/providers/connectors/WorkerPoolRegistry.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
  dev/io.openliberty.org.eclipse.microprofile/reactive.messaging.3.0.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: ID review not needed, CLA Signed, in:MicroProfile/Reactive, L2 ReviewNotRequired

#25829 Wait for recovery before testing
  dev/com.ibm.ws.wsat_fat.db/publish/servers/MultiServerTest/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/MultiServerTest/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/ThirdServer/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/ThirdServer/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATBasic/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATBasic/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Client/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Server1/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Client/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server1/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server2/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server2/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Client/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Server1/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Server1/server.xml
Labels: noproductcode, CLA Signed

#25843 Update to use MP Config 3.1-RC2 api and tck
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.config.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/config.3.1.bnd
Labels: CLA Signed

#25828 Set content-length header to match size of updated content
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/servlet/filter/HtmlResponseWrapper.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/servlet/filter/OpenAPIEndpointFilter.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/com/ibm/ws/microprofile/openapi/servlet/filter/HtmlResponseWrapper.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/com/ibm/ws/microprofile/openapi/servlet/filter/OpenAPIEndpointFilter.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UICustomPathTest.java
Labels: CLA Signed

#25724 Add support for MPOpenAPI custom endpoints for proxies
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/ProxySupportUtil.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/ProxySupportUtil.java
  dev/io.openliberty.microprofile.openapi.internal.common/src/io/openliberty/microprofile/openapi/internal/common/OpenAPIEndpointManager.java
Labels: CLA Signed

#25726 Add MP OpenAPI UI OAuth Selenium Tests
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/SecureTestResource.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/FATSuite.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UICustomPathTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIOauthTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/publish/servers/openapi-ui-custom-oauth-test/bootstrap.properties
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/publish/servers/openapi-ui-custom-oauth-test/server.xml
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/publish/servers/openapi-ui-test/server.xml
Labels: noproductcode, CLA Signed

#25810 Updated tracing for netty unittests
  dev/io.openliberty.netty.internal.impl/test/io/openliberty/netty/internal/impl/NettyFrameworkImplTest.java
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#25887 Ignore concurrency transaction race condition when uninstalling application
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#25841 Replace TM service reference with TX Mgr factory in JPAComponentImpl
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FacesTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/server.xml
Labels: CLA Signed

#25874 Increasing the timeout so that defaultOrb and virtual host can be configured on slow machines
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests15.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests20.java
  dev/com.ibm.ws.springboot.support.web.server/src/com/ibm/ws/springboot/support/web/server/internal/WebInstance.java
Labels: noproductcode, CLA Signed

#25846 PR for Issue 22358: Update check on original redirect URL for OIDC social login clients
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/EndpointServices.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/test/CommonTestClass.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/EndpointServicesTest.java
Labels: CLA Signed, team:Security SSO, ID waiting on development

#25820 Update Jakarta EE tests to fix failures with different combinations
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolverTcpTransport.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/JakartaEE10Test.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/JakartaEE9Test.java
Labels: team:Performance

#25907 Update eclipse settings for new spring boot app project
  dev/io.openliberty.springboot.fat30.security.app/.classpath
  dev/io.openliberty.springboot.fat30.security.app/.project
  dev/io.openliberty.springboot.fat30.security.app/.settings/org.eclipse.buildship.core.prefs
Labels: noproductcode, CLA Signed, team:Performance

#25882 Remove Gradle 7 deprecated method usage.
  dev/build.image/build.gradle
  dev/build.pii.package/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/build.gradle
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/updatebinaries.gradle
  dev/com.ibm.websphere.security_fat.1/build.gradle
  dev/com.ibm.ws.com.unboundid/build.gradle
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2.1/build.gradle
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/build.gradle
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.security_test.servlets/build.gradle
  dev/com.ibm.ws.jbatch.fat.common/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.repository_fat/build.gradle
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.audit_fat.common.tooling/build.gradle
  dev/com.ibm.ws.security.auth.data_fat/build.gradle
  dev/com.ibm.ws.security.client_fat/build.gradle
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/build.gradle
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.fat.common.social/build.gradle
  dev/com.ibm.ws.security.fat.common/build.gradle
  dev/com.ibm.ws.security.jaspic.jakarta10_fat/build.gradle
  dev/com.ibm.ws.security.jaspic_fat/build.gradle
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.oauth.oidc_fat.common/build.gradle
  dev/com.ibm.ws.security.oauth_test.custom_servlets/build.gradle
  dev/com.ibm.ws.security.oauth_test.servlets/build.gradle
  dev/com.ibm.ws.security.registry.basic_fat/build.gradle
  dev/com.ibm.ws.security.registry_test.servlet/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.spnego.fat.common/build.gradle
  dev/com.ibm.ws.security.token.ltpa_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
  dev/com.ibm.ws.security.wim_test.servlet/build.gradle
  dev/com.ibm.ws.webcontainer.security_test.servlets/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.6/build.gradle
  dev/io.openliberty.checkpoint_fat_security_oidc_social/build.gradle
  dev/io.openliberty.jcache.internal_fat.hazelcast/build.gradle
  dev/io.openliberty.jcache.internal_fat.infinispan/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.persistence.3.0.thirdparty/build.gradle
  dev/io.openliberty.persistence.3.1.thirdparty/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/build.gradle
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/jacoco.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Performance

#25903 make Derby workaround permanent
  dev/com.ibm.ws.jca_fat_bvt/fat/src/test/client/jca/JCABVTTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25901 validation of entities on update and return types for saveAll
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employees.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/ShippingAddresses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/TaxPayers.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Entitlements.java
Labels: team:Zombie Apocalypse, CLA Signed

#25895 Avoid reactivating when optional CDIJSFInitializer service goes away
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/io.openliberty.faces.4.0.internal/bnd.bnd
  dev/io.openliberty.faces.internal/bnd.bnd
Labels: CLA Signed

#25849 Max Java version is set to 17
  dev/io.openliberty.jaxws.security_fat.ssl/fat/src/com/ibm/ws/jaxws/security/fat/SSLConfigurationNoTrustStoreTest.java
  dev/io.openliberty.jaxws.security_fat.ssl/fat/src/com/ibm/ws/jaxws/security/fat/SSLRefConfigurationTest.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#25914 Stop accessing ${archiveFileName} in build.gradle file
  dev/com.ibm.ws.jbatch.fat.common/build.gradle
Labels: noproductcode, CLA Signed, team:Performance

#25900 update okio version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.com.squareup.okio-jvm/bnd.bnd
  dev/io.openliberty.org.jetbrains.kotlin/bnd.bnd
Labels: CLA Signed, release:23009

#25877 Set streaming fixed length call is reenabled
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/URLConnectionHTTPConduit.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#25792 Update JavaEESecTestBase.setServerConfiguration function
  dev/com.ibm.ws.security.javaeesec_fat.4/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertFailOverTest.java
Labels: noproductcode, CLA Signed

#25875 Remove unnecessary metatype from app manager lifecycle
  dev/com.ibm.ws.app.manager.lifecycle/bnd.bnd
  dev/com.ibm.ws.app.manager.lifecycle/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#25905 Fix ServerLock testRunningServer method for WSL
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/ServerLock.java
Labels: CLA Signed

#25789 Standardize artifactory logic between maven and docker
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryImageNameSubstitutorTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25888 Move bouncycastle bundles into a private feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wss4j-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.bouncycastle.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee9.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wss4j-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/wsSecurity-1.1/com.ibm.websphere.appserver.wsSecurity-1.1.feature
Labels: CLA Signed, team:Performance

#25821 Allow a little wiggle room on exp checks
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/commonTools/PKCEPrivateKeyJwtCommonTooling.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25917 remove beta tag
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#25825 Private key jwt fat 3
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java.mine
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25720 FeatureUtility FAT set up testContainer for http request
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/build.gradle
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FATSuite.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/simple-keyserver/Dockerfile
  dev/com.ibm.ws.install.featureUtility_fat/publish/simple-keyserver/release.sh
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed

#25832 Suppressed CloneNotSupportedException For Issue #25830
  dev/com.ibm.ws.security.authentication.builtin/src/com/ibm/ws/security/authentication/internal/cache/keyproviders/BasicAuthCacheKeyProvider.java
Labels: CLA Signed

#25701 Update Jakarta Data TCK
  dev/io.openliberty.jakarta.data.1.0_fat_tck/build.gradle
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.core/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.web/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/core/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/core/src/test/resources/arquillian.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/standalone/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/web/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/web/src/test/resources/arquillian.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25760 25759 - Enable user's to set CXF's useHttpsURLConnectionDefaultSslSoc…
  dev/com.ibm.ws.jaxrs.2.0.client/src/com/ibm/ws/jaxrs20/client/security/LibertyJaxRsClientSSLOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MatchingSSLCiphersTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MisMatchingSSLCiphersTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/CiphersTest/src/io/openliberty/jaxrs/client/fat/matchingCiphers/MatchingSSLCiphersClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/CiphersTest/src/io/openliberty/jaxrs/client/fat/mismatchingCiphers/MisMatchingSSLCiphersClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/clientconfig/JAXRSClientConstants.java
Labels: in:JAX-RS, CLA Signed

#25890 JAX-WS: Prevent CXF from ignoring imported WDSL Namespaces used by <wsdl:header> message parts
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapBindingFactory.java
Labels: CLA Signed

#25936 Set Java min version for beanValidation-3.1 in startup tests.
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
Labels: noproductcode, CLA Signed, team:Performance

#25916 Ensure no new add events got missed when deactivating on removed service
  dev/com.ibm.ws.org.apache.felix.scr/src/org/apache/felix/scr/impl/manager/DependencyManager.java
Labels: CLA Signed

#25920 Update OpenShiftUserApiUtils to get groups from API response
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtilsTest.java
Labels: CLA Signed, team:Security SSO

#25817 Create a new EE11 Pages 4.0 FAT
  dev/io.openliberty.pages.4.0.internal_fat/.classpath
  dev/io.openliberty.pages.4.0.internal_fat/.project
  dev/io.openliberty.pages.4.0.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.pages.4.0.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.pages.4.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.pages.4.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.pages.4.0.internal_fat/bnd.bnd
  dev/io.openliberty.pages.4.0.internal_fat/build.gradle
  dev/io.openliberty.pages.4.0.internal_fat/fat/src/io/openliberty/pages40/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#25868 Increase JPA Client Timeout
  dev/com.ibm.ws.jpa.tests.container.client_fat/publish/clients/BasicJPAFieldInjClient/client.xml
  dev/com.ibm.ws.jpa.tests.container.client_fat/publish/clients/BasicJPAJNDIClient/client.xml
  dev/com.ibm.ws.jpa.tests.container.client_fat/publish/clients/BasicJPAMethodInjClient/client.xml
Labels: noproductcode, test bug, in:JPA, team:Blizzard, CLA Signed

#25910 tests for updating and removing invalid entities
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creatures.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25831 Use modern java idiom
  dev/com.ibm.ws.security.csiv2.client/src/com/ibm/ws/transport/iiop/client/security/CSIv2ClientSubsystemFactory.java
  dev/com.ibm.ws.security.csiv2.common/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SSLSubsystemFactory.java
  dev/com.ibm.ws.security.csiv2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
  dev/com.ibm.ws.transport.iiop.open_fat/fat/src/test/iiop/interceptor/TestSubsystemFactory.java
  dev/com.ibm.ws.transport.iiop.transaction/src/com/ibm/ws/transport/iiop/transaction/TransactionSubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/internal/NamingServiceSubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/spi/SubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/yoko/DefaultSocketFactorySubsystemFactory.java
  dev/com.ibm.ws.transport.iiop/src/com/ibm/ws/transport/iiop/yoko/DispatchSubsystemFactory.java
Labels: CLA Signed

#25935 PR for Issue 25927: Fix JWK retrieval logic for JWKs missing 'use' entry
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JwKRetrieverTest.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/jwk_minimum_test.json
Labels: CLA Signed, team:Security SSO

#25929 296004 fat rewrite
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/DumpArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperMultipleIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/LookupZipArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCacheIntrospection.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCachingIntrospectorOutput.java
  dev/com.ibm.ws.artifact_fat/test-applications/HoldingServlet/src/com/ibm/ws/artifact/fat/zip/HoldingServlet.java
Labels: in:Build, in:Kernel/Bootstrap, noproductcode, test debt, CLA Signed

#25788 Deferred cache prototype.
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/CollectionUtils.java
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/DeferredCache.java
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/DeployedAppInfoBase.java
Labels: in:Kernel/Bootstrap, CLA Signed, performance

#25939 Revert "296004 fat rewrite"
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/DumpArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperMultipleIntrospectionTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/LookupZipArchive.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCacheIntrospection.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/ZipCachingIntrospectorOutput.java
  dev/com.ibm.ws.artifact_fat/test-applications/HoldingServlet/src/com/ibm/ws/artifact/fat/zip/HoldingServlet.java
Labels: noproductcode, CLA Signed

#25680 Enable skipped jsf.2.2_fat tests via selenium
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/JSFUtils.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25660 Set Min Java Level on FeatureSet
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDIExtensionRepeatActions.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/ejb/EJBVisibilityTests.java
  dev/com.ibm.ws.concurrent.mp_fat/fat/src/com/ibm/ws/concurrent/mp/fat/MPContextPropActions.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseConfiguredTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseProducerRecordTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomKeySerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/ReactiveStreamsTckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BasicReactiveMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/MissingGroupIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/ReactiveMessagingActions.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveConcurrentWorkTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveJaxRSTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsContextTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsTest.java
  dev/com.ibm.ws.tx.jta_fat_hibernate/fat/src/com/ibm/ws/tx/jta/fat/hibernate/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureSet.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE10Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE11Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE9Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/BasicJAXRSCDITest.java
  dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/ConfiguredJAXRSCDITest.java
Labels: CLA Signed

#25942 JAX-WS: Refactor LibertyCXFNegativePropertiesTest
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFNegativePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFNegativePropertiesTestServer/handler.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFNegativePropertiesTestServer/server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/libertyCXFProperties/src/com/ibm/ws/properties/test/servlet/LibertyCXFNegativePropertiesTestServlet.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/client/stub/ImageServicePropertyImplService.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/wsfeatures/client/WSAPropertyTestServlet.java
Labels: noproductcode, CLA Signed

#25880 Bump SmallRye Metrics to 5.0.1 and update API usage in MP Metrics 5.0 feature
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/SharedMetricRegistries.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/internal/ApplicationListener50.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/internal/SmallryeMetricsCDIMetadata.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/smallrye/metrics/adapters/SRSharedMetricRegistriesAdapter.java
  dev/io.openliberty.microprofile.metrics.5.0.private.internal/src/io/openliberty/microprofile/metrics/internal/privateapi/PrivateMetricsRESTHandler.java
  dev/io.openliberty.microprofile.metrics.5.0.public.internal/src/io/openliberty/microprofile/metrics/internal/publicapi/PublicMetricsRESTHandler.java
Labels: CLA Signed

#25947 Add new dir to java lib path path for CriuSupport
  dev/fattest.simplicity/src/componenttest/topology/impl/JavaInfo.java
Labels: noproductcode, CLA Signed

#25946 inject qualified instances
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
Labels: team:Zombie Apocalypse, CLA Signed

#25950 Allow different cert ffdc with different jdks
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25951 Expect an additional error message for WasReqURLTests
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientWasReqURLTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25686 Enable JSF 2.3 ajax / JS tests via Selenium framework
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/JSFUtils.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23EvalScriptsTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resourcesFaces40/implicit_objects.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resourcesJSF23/implicit_objects.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/src/com/ibm/ws/jsf23/fat/elimplicit/cdi/beans/ELImplicitObjectBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25826 18499 ltpa
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/FileBasedActionable.java
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/LTPAFileMonitor.java
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/SecurityFileMonitor.java
  dev/com.ibm.ws.crypto.ltpakeyutil/bnd.bnd
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyFileUtility.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/SsoConfigImpl.java
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.token.ltpa/resources/com/ibm/ws/security/token/ltpa/internal/resources/LTPAMessages.nlsprops
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAConfiguration.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManager.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAValidationKeysInfo.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConstants.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTask.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManagerTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2FactoryTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2SerializationTest.java
  dev/com.ibm.ws.security.token/src/com/ibm/ws/security/token/internal/TokenManagerImpl.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/internal/KeystoreConfigurationFactory.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#25949 Fix MP RS 3.0 TCK performance issue
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/fat/src/io/openliberty/microprofile/reactive/streams/operators30/tck/FATSuite.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/fat/src/io/openliberty/microprofile/reactive/streams/operators30/tck/ReactiveStreams30TCKLauncher.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/servers/ReactiveStreams30TCKServer/jvm.options
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/tckRunner/tck/src/test/java/org/eclipse/microprofile/reactive/streams/operators/tck/ReactiveStreamsTck.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/tckRunner/tck/src/test/java/org/eclipse/microprofile/reactive/streams/operators/tck/arquillian/ReactiveStreamsCdiTck.java
Labels: noproductcode, CLA Signed

#25960 Fix Origin header behavior in OIDC client
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtil.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenRequestorTest.java
Labels: CLA Signed, team:Security SSO

#25965 Avoid NullPointerException on null input
  dev/com.ibm.tx.jta/src/com/ibm/ws/Transaction/JTA/Util.java
Labels: CLA Signed

#25956 test jwt sso cookie with context root set
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/ReplayCookieTests.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/actions/JwtFatActions.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_noFeature_withContextRoot.xml
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_useLtpaIfJwtAbsent_true_configureSecondApp.xml
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_withBuilderApp_jwtCookie_withContextRoot.xml
Labels: noproductcode, CLA Signed

#25824 Initial implementation of org.crac API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.3/io.openliberty.crac-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.3/resources/l10n/io.openliberty.crac-1.3.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-3.0/io.openliberty.springBoot-3.0.feature
  dev/com.ibm.ws.app.manager.springboot/bnd.bnd
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/VirtualHostImpl.java
  dev/io.openliberty.checkpoint/bnd.bnd
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointTransformer.java
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/criu/DeployCheckpoint.java
  dev/io.openliberty.checkpoint/test/io/openliberty/checkpoint/internal/CheckpointImplTest.java
  dev/io.openliberty.checkpoint_fat_crac/.classpath
  dev/io.openliberty.checkpoint_fat_crac/.project
  dev/io.openliberty.checkpoint_fat_crac/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_crac/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_crac/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_crac/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_crac/bnd.bnd
  dev/io.openliberty.checkpoint_fat_crac/build.gradle
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceFailCheckpointTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceFailRestoreTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceOrderTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceRequestNotSupportedTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceRequestPhaseAfterAppStartTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceRequestPhaseBeforeAppStartTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/FATSuite.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/fail/checkpoint/CRaCResourceFailCheckpointServlet.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/fail/restore/CRaCResourceFailRestoreServlet.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/request/fail/incorrect/phase/CRaCResourceRequestFailIncorrectPhaseServlet.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/request/fail/notsupported/CRaCResourceRequestFailNotSupportedServlet.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/resource/order/CRaCResourceOrderServlet.java
  dev/io.openliberty.checkpoint_fat_crac/publish/servers/cracFATServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_crac/publish/servers/cracFATServer/jvm.options
  dev/io.openliberty.checkpoint_fat_crac/publish/servers/cracFATServer/server.xml
  dev/io.openliberty.org.crac/.classpath
  dev/io.openliberty.org.crac/.gitignore
  dev/io.openliberty.org.crac/.project
  dev/io.openliberty.org.crac/.settings/bndtools.core.prefs
  dev/io.openliberty.org.crac/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.crac/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.crac/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.crac/bnd.bnd
  dev/io.openliberty.org.crac/src/io/openliberty/crac/LibertyCheckpoint.java
  dev/io.openliberty.org.crac/src/io/openliberty/crac/package-info.java
  dev/io.openliberty.org.crac/src/org/crac/Core.java
  dev/io.openliberty.org.crac/src/org/crac/GlobalContextWrapper.java
  dev/io.openliberty.springboot.support.web.server.version30/bnd.bnd
  dev/io.openliberty.springboot.support.web.server.version30/src/io/openliberty/springboot/support/web/server/version30/container/LibertyServletWebServerFactory.java
Labels: CLA Signed, L2 ReviewNotRequired, ID waiting on development

#25974 Tidy up the MP Reactive Streams TCK projects
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat_tck/publish/servers/ReactiveStreamsTCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/servers/ReactiveStreams30TCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#25954 Handle unique Java behavior in Private Key Jwt Tests
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java
  dev/com.ibm.ws.security.oidc.client_fat.3/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientPrivateKeyJwtTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_Social_PrivateKeyJwtTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25980 Update server script to fix sed command
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#25976 Improve portability of checkpoint for power and z/OS systems
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#25984 Add SpringBoot3 application tag with War test
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigSpringBootApplicationTagWarTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#25985 Experiment with obtaining entity manager
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/RepositoryAssist.java
Labels: team:Zombie Apocalypse, CLA Signed

#25959 Issue #25790: Remove dependencies on ManagedBean
  dev/com.ibm.ws.ejbcontainer/bnd.bnd
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/ModuleInitDataFactory.java
  dev/com.ibm.ws.ejbcontainer_test/test/com/ibm/ws/ejbcontainer/osgi/internal/AnnoMockery.java
  dev/com.ibm.ws.injection.core/src/com/ibm/ws/injectionengine/processor/ResourceProcessor.java
Labels: team:Zombie Apocalypse, in:Java EE Platform, CLA Signed, jakartaEE11

#25898 Deal with servlet 6 slash behaviour in FileHandler
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/handlers/FileHandler.java
  dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/helpers/RESTHelper.java
  dev/com.ibm.ws.jmx.connector.server.rest/test/com/ibm/ws/jmx/connector/server/rest/helpers/RESTHelperTest.java
Labels: CLA Signed

#25994 generic array return type
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/CustomRepository.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#25967 Test aws advanced jdbc wrapper
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_postgresql/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/PostgreSQLAWSTest.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/PostgreSQLTest.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLAWSTest/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLAWSTest/server.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLAWSTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#26010 startWinService stopWinService default timeouts too short
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#25983 Jakarta REST updates
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-4.0/io.openliberty.restfulWSClient-4.0.feature
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/registry/ConstantResourceInvoker.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/registry/SegmentNode.java
Labels: CLA Signed, team:Performance

#26004 Rtc293249 enable logs
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transaction_cdi/server.xml
Labels: noproductcode, CLA Signed

#25911 Add repeats to Reactive Messaging Tests
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/jsonb/JsonbTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/containers/ExtendedKafkaContainer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/KafkaTestClientProvider.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/nolib/KafkaNoLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/invalid/LibertyLoginModuleInvalidTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseConfiguredTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseProducerRecordTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomKeySerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tls/KafkaTlsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/loginModuleClassloading/LoginModuleClassloadingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BasicReactiveMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaUtils.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/MissingGroupIDTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/PlaintextTests.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/SaslPlainTests.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/TlsTests.java
Labels: noproductcode, CLA Signed

#26001 Enable jdbc-4.1 and 4.3 features for instantOn. Add new versions to FATS
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.1/com.ibm.websphere.appserver.jdbc-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc-4.3/com.ibm.websphere.appserver.jdbc-4.3.feature
  dev/io.openliberty.checkpoint_fat_persistence/bnd.bnd
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/SessionDatabaseTest.java
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/server.xml
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/sessionDatabaseServer/server.xml
Labels: CLA Signed

#26014 Add test for multiple apps using org.crac and mark org.crac as stable API
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.3/io.openliberty.crac-1.3.feature
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceMultiAppTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/FATSuite.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/multiple1/MultiApp1Servlet.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/multiple2/MultiApp2Servlet.java
  dev/io.openliberty.checkpoint_fat_crac/publish/servers/cracFATServer/server.xml
Labels: CLA Signed

#25981 Test springboot with checkpoint/retsore
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/io.openliberty.checkpoint.springboot.fat30.app/.classpath
  dev/io.openliberty.checkpoint.springboot.fat30.app/.gitignore
  dev/io.openliberty.checkpoint.springboot.fat30.app/.project
  dev/io.openliberty.checkpoint.springboot.fat30.app/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint.springboot.fat30.app/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint.springboot.fat30.app/bnd.bnd
  dev/io.openliberty.checkpoint.springboot.fat30.app/build.gradle
  dev/io.openliberty.checkpoint.springboot.fat30.app/springboot.gradle
  dev/io.openliberty.checkpoint.springboot.fat30.app/src/main/java/io/openliberty/checkpoint/springboot/fat30/app/TestApplication.java
  dev/io.openliberty.checkpoint.springboot.fat30.app/src/main/resources/application.properties
  dev/io.openliberty.checkpoint_fat_springboot/.classpath
  dev/io.openliberty.checkpoint_fat_springboot/.project
  dev/io.openliberty.checkpoint_fat_springboot/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_springboot/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_springboot/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_springboot/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_springboot/bnd.bnd
  dev/io.openliberty.checkpoint_fat_springboot/build.gradle
  dev/io.openliberty.checkpoint_fat_springboot/fat/src/io/openliberty/checkpoint/fat/springboot/BasicSpringBootTests.java
  dev/io.openliberty.checkpoint_fat_springboot/fat/src/io/openliberty/checkpoint/fat/springboot/FATSuite.java
  dev/io.openliberty.checkpoint_fat_springboot/publish/servers/checkpointSpringBoot/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_springboot/publish/servers/checkpointSpringBoot/jvm.options
  dev/io.openliberty.checkpoint_fat_springboot/publish/servers/checkpointSpringBoot/server.xml
Labels: CLA Signed

#26017 25259 ltpa key rotation fat
  dev/com.ibm.ws.security.token.ltpa_fat/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa_fat/build.gradle
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/FATSuite.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation2.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation3.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/bootstrap.properties
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/jvm.options
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/LTPA.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: noproductcode, CLA Signed, team:Core Security

#26029 Fix up eclipse and bnd issues with new project
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/ExtensionArchiveFactory.java
  dev/io.openliberty.cdi.4.0.interfaces/bnd.bnd
  dev/io.openliberty.checkpoint_fat_springboot/.classpath
  dev/io.openliberty.checkpoint_fat_springboot/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.metrics.5.1.internal/.classpath
Labels: CLA Signed, team:Performance

#25982 Update testcontainer cache files
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26020 MicroProfile Metrics v5.1.0 TCK using RC1
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.classpath
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.project
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/fat/resources/logging.properties
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/fat/src/io/openliberty/microprofile/metrics51/internal/tck/launcher/FATSuite.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/fat/src/io/openliberty/microprofile/metrics51/internal/tck/launcher/MetricsTCKLauncher.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/servers/MetricsTCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/servers/MetricsTCKServer/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/servers/MetricsTCKServer/server.env
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/servers/MetricsTCKServer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/README.md
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/metrics/internal/test/ArquillianLoadableExtension.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: noproductcode, CLA Signed

#26019 Mark crac-1.3 feature as beta
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.3/io.openliberty.crac-1.3.feature
Labels: CLA Signed

#25239 Upgrade to Gradle 8.3 and support compiling Java 21 projects
  dev/.gradle-wrapper/gradle-wrapper.jar
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/gradlew
  dev/gradlew.bat
  dev/wlp-gradle/java.gradle
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#26036 Update min java level for jdbc FAT test
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/SessionDatabaseTest.java
Labels: noproductcode, CLA Signed

#26032 Call all listeners for starting/started events even with errors
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/state/internal/ApplicationStateManager.java
Labels: CLA Signed

#26040 experiment with validation conditional on valid annotation
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creatures.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Entitlements.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Rectangles.java
Labels: team:Zombie Apocalypse, CLA Signed

#26013 Installkernel check instance of string for verify for plugins
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#26025 Flush and close the outputstream
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebFluxTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebFluxTests.java
Labels: noproductcode, CLA Signed

#26038 PR to remove SB 3 beta guard for ga release
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.springBootServerSupport.servlet60-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.springBootHandler-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-3.0/io.openliberty.springBoot-3.0.feature
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
  dev/io.openliberty.springboot.fat30_fat/publish/servers/SpringBootTests/jvm.options
Labels: CLA Signed

#25636 remove beta for featureUtility verify signature
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureAction.java
  dev/com.ibm.ws.install.featureUtility/test/com/ibm/ws/install/featureUtility/FeatureUtilityTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
Labels: CLA Signed

#25993 Environment variable LOG_DIR not respected in server.xml
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#26022 Skip Agent tests for Java 21+
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 21

#26055 Revert "remove beta for featureUtility verify signature "
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/cli/FeatureAction.java
  dev/com.ibm.ws.install.featureUtility/test/com/ibm/ws/install/featureUtility/FeatureUtilityTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
Labels: CLA Signed

#26048 Remove unnecessary call to uname for performance
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#25773 25149 - allow for directories to be used for includes
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
  dev/com.ibm.ws.config/test-resources/test_xml_config/usr/servers/directory.include/server.xml
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/XMLConfigParserTest.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/common/a.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/common/b.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/common/c.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/server.xml
  dev/com.ibm.ws.config_fat/test-applications/restart/src/test/server/config/restart/ConfigRestartTestServlet.java
Labels: CLA Signed

#26057 Fix performance regression in JAXRS 2.1
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/impl/Rfc3986UriValidator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/utils/HttpUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs/utils/test/InvalidUriTest.java
Labels: CLA Signed, team:Performance, performance

#26067 Revert "Environment variable LOG_DIR not respected in server.xml"
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#25295 Return 400 for non-valid URI
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet-servletSpi2.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC400BadRequestTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC500BadRequestDefaultTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_400ResponseServer/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_400ResponseServer/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_400ResponseServer/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_500ResponseServer_Default/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_500ResponseServer_Default/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_500ResponseServer_Default/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/Test400BadRequestURI.war/src/test400BadRequest/servlets/TestServlet.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#26066 Fixed LTPA metatype bug
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#26034 Correct message code in "testNeedSpringBootFeature15".
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot15FeatureTests.java
Labels: in:Kernel/Bootstrap, noproductcode, test bug, CLA Signed, in:CDI/3.0

#26058 Fix @ExpectedFFDC annotation on OIDC private key jwt FAT
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java
Labels: noproductcode, CLA Signed, team:Security SSO

#25772 Move sshd version 2.5.1 to 2.9.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.spnego/build.gradle
  dev/com.ibm.ws.security.spnego.fat.common/bnd.bnd
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/KdcHelper.java
Labels: CLA Signed

#26007 Update security client fat timeout issue
  dev/com.ibm.ws.security.client_fat/build.gradle
  dev/com.ibm.ws.security.client_fat/fat/src/com/ibm/ws/security/client/fat/FATSuite.java
Labels: noproductcode, test bug, CLA Signed

#25988 Update Fats that use the kafka-clients jar to latest
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/build.gradle
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/FailedApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SharedLibRxMessagingServer/server.xml
Labels: CLA Signed

#26080 Switch MP61 to beta
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance4.0-mpMetrics5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpGraphQL2.0-metrics5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.metrics-5.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-6.1/io.openliberty.microProfile-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.1/io.openliberty.mpConfig-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-5.1/io.openliberty.mpMetrics-5.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
Labels: CLA Signed

#26060 add beta tag for LTPA key rotation
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Core Security

#26097 fix testAppWaitsForDeclaredPrereq fat test
  dev/com.ibm.ws.app.manager_fat/fat/src/componenttest/application/manager/test/AppPrereqTest.java
Labels: noproductcode, CLA Signed

#26092 unwanted FFDC on shutdown
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
Labels: team:Zombie Apocalypse, CLA Signed

#26095 ConcurrentCDITest initializationError when accessing Java 17 classes
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26098 PostgreSQL AWS test lacks java 2 security permissions
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/server-PostgreSQLAWSTest/server.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26111 Fix log message checking for KafkaBadConfigTest
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigTest.java
Labels: noproductcode, CLA Signed

#26116 Port csiv2 unit test
  dev/com.ibm.ws.jbatch.jms/bnd.bnd
  dev/com.ibm.ws.security.csiv2/.classpath
  dev/com.ibm.ws.security.csiv2/bnd.bnd
  dev/com.ibm.ws.security.csiv2/build.gradle
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfigTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/AuthenticatorImplTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/config/css/ClientConfigHelperTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/config/css/ClientLTPAMechConfigTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/config/css/ClientSASITTDistinguishedNameTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/config/tss/ServerConfigHelperTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/server/config/tss/ServerLTPAMechConfigTest.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/tools/InputStreamTestDouble.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/tools/OutputStreamTestDouble.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/security/csiv2/tools/TestCodec.java
  dev/com.ibm.ws.security.csiv2/test/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactoryTest.java
Labels: CLA Signed

#26130 Remove TLSProfilerTaskTest
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/TLSProfilerTaskTest.java
Labels: noproductcode, CLA Signed

#26125 Add classloading trace to CDI NonContextualTests
  dev/com.ibm.ws.cdi.noncontextual_fat/publish/servers/nonContextualServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#26108 beta guard include directories
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/XMLConfigParserTest.java
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.include.directory/jvm.options
Labels: CLA Signed
