Repository OpenLiberty/open-liberty, pull requests merged in 2023-11, with the labels that each got.

#26773 Skip DB2 JCC precedence tests on IBMi
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
  dev/com.ibm.ws.jdbc_fat_db2/test-applications/db2fat/src/db2/web/DB2TestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#26787 Ensure TCK's setup defaultKeyStore
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/servers/ConcurrentTCKFullServer/server.xml
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/publish/servers/ConcurrentTCKFullServer/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.full/server.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#26781 Switch to HTTP for application servlet hits
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/DefaultHistogramBucketsTest.java
Labels: noproductcode, CLA Signed

#26782 Introduce unit test for DatabaseContainerFactory
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerFactoryTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26739 Support FIPS 140-3 for IBM JDK 8
  dev/com.ibm.websphere.appserver.api.ssl/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/public/ssl-1.0/com.ibm.websphere.appserver.ssl-1.0.feature
  dev/com.ibm.ws.crypto.ltpakeyutil/bnd.bnd
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPADigSignature.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyUtil.java
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
  dev/com.ibm.ws.ssl/bnd.bnd
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/Constants.java
  dev/com.ibm.ws.ssl/src/com/ibm/websphere/ssl/package-info.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/JSSEProviderFactory.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/AbstractJSSEProvider.java
  dev/com.ibm.ws.ssl/src/com/ibm/ws/ssl/provider/IBMJSSEProvider.java
Labels: CLA Signed

#26798 mpTelemetry-1.1 EE9 compatibility review comments
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-9.0.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryActions.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/TestExceptionMapper.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/multiapp1/MultiApp1TestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/TestSpans.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/jakarta/TelemetryClientBuilderListener.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/rest/jakarta/TelemetryClientAsyncTaskWrapper.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/rest/jakarta/package-info.java
  dev/io.openliberty.microprofile.telemetry.internal.common/transformed.bnd
Labels: CLA Signed

#26790 update otel oss dependencies
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.com.squareup.okhttp/bnd.bnd
  dev/io.openliberty.com.squareup.okio-jvm/bnd.bnd
  dev/io.openliberty.io.zipkin.zipkin2/bnd.bnd
Labels: CLA Signed

#26783 Use life cycle annotations rather than method name
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Houses.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Accounts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Tariffs.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/TaxPayers.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Entitlements.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/By.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
Labels: team:Zombie Apocalypse, CLA Signed

#26599 Refresh resolved host when fragment cannot attach
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/Provisioner.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FeatureFragmentTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.feature.fragment-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.feature.host-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fragment/.gitignore
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fragment/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fragment/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.fragment.bundle/src/test/feature/fragment/bundle/FragmentComponent.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.fragment.bundle/src/test/feature/fragment/bundle/package-info.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.host.bundle/src/test/feature/host/bundle/HostComponent.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.host.bundle/src/test/feature/host/bundle/package-info.java
  dev/com.ibm.ws.kernel.feature_fat/test.feature.fragment.bundle.bnd
  dev/com.ibm.ws.kernel.feature_fat/test.feature.host.bundle.bnd
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
  dev/com.ibm.ws.org.apache.felix.scr/src/org/apache/felix/scr/impl/Activator.java
Labels: CLA Signed

#26795 Allow expected FFDCs when querying metrics during server shutdown in …
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/MetricsMonitorTest.java
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/MetricsMonitorTest.java
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/MetricsMonitorTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/TestEnableDisableFeaturesTest.java
Labels: noproductcode, CLA Signed

#26789 DataSource service refresh handling by Transaction Recvovery Logs
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#26361 Remove useInMemory JSP option as it's broken and not requested
  dev/com.ibm.ws.jsp/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jsp/resources/com/ibm/ws/jsp/resources/messages.nlsprops
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/Constants.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/JspOptions.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/compiler/InMemoryJDTCompiler.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/compiler/InMemoryJspCompilerFactory.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/compiler/InMemoryJspCompilerResult.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/context/InMemoryJspTranslationContext.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/generator/InMemoryGenerateJspVisitor.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/generator/InMemoryGenerateTagFileVisitor.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/generator/InMemoryWriter.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/resource/InMemoryJspResourceFactory.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/resource/InMemoryJspResources.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/resource/InMemoryResources.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/resource/InMemoryTagFileResources.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/webcontainerext/AbstractInMemoryJSPExtensionServletWrapper.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/inmemory/webcontainerext/InMemoryJspClassLoader.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/TagLibraryCache.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/utils/JspTranslatorUtil.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/visitor/configuration/JspVisitorConfiguration.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/AbstractJSPExtensionProcessor.java
Labels: in:Web Components, CLA Signed, team:Sirius

#26585 A warning message should be logged on restore when a config property is updated after checkpoint even if the property had no default value.
  dev/io.openliberty.checkpoint_fat_mpconfig/fat/src/io/openliberty/checkpoint/fat/MPConfigTest.java
  dev/io.openliberty.checkpoint_fat_mpconfig/test-applications/mpapp1/src/mpapp1/ApplicationScopedOnCheckpointBean.java
  dev/io.openliberty.checkpoint_fat_mpconfig/test-applications/mpapp1/src/mpapp1/MPConfigServlet.java
Labels: noproductcode, CLA Signed, CRIU

#26803 Update Telemetry1.1 TCK version
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#26817 transition from method name prefix to annotation based
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
Labels: team:Zombie Apocalypse, CLA Signed

#26733 OL fattest.simplicity update to enable FIPS 140-3
  dev/fattest.simplicity/src/componenttest/topology/impl/JavaInfo.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#26800 Redirect makeCurrent and storeInContext
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/ContextAPIServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/bean/TelemetryBeanTestServlet.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/SpanProxy.java
Labels: CLA Signed

#26765 Enabled WebContainer trace
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_id_update/bootstrap.properties
Labels: noproductcode, CLA Signed

#26812 Tx Peer recovery: Schedule the next lease renewal irrespective of the success or failure of the last lease renewal attempt
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
Labels: CLA Signed

#26829 Adding Mutiny test
  dev/com.ibm.ws.concurrent_fat_reactive/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_reactive/build.gradle
  dev/com.ibm.ws.concurrent_fat_reactive/fat/src/com/ibm/ws/concurrent/fat/reactive/ConcurrentReactiveTest.java
  dev/com.ibm.ws.concurrent_fat_reactive/publish/servers/com.ibm.ws.concurrent.fat.reactive.ReactiveServer/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_reactive/publish/servers/com.ibm.ws.concurrent.fat.reactive.ReactiveServer/server.xml
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ConcurrentReactiveServlet.java
Labels: noproductcode, CLA Signed

#26797 Test mpTelemetry-1.1 with EE7 and EE8
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/spanTestServer/server.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/MultiThreadedContextTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAPITest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryActions.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryBeanTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvOnlyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigNullTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigSystemPropTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryDisabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryGlobalOpenTelemetryTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLoggingExporterTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLongRunningTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServiceNameTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServletTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryShimTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetrySpiTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryWithSpanErrorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10JaxWithConcurrency/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.1.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/javax/TelemetryJaxRsProviderRegister.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/javax/package-info.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#26825 Telemetry 1.1: Register TelemetryContainerFilter when using EE7/8
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/AbstractSpanMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/javax/TelemetryJaxRsProviderRegister.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/rest/AbstractTelemetryContainerFilter.java
Labels: CLA Signed

#26837 Fix jax-rs async for Telemetry with EE7 and EE8
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
Labels: CLA Signed

#24036 Clarify process for externally requested features, remove a11y and g11n approvals, add InstantOn approval
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#26847 JAX-WS: Fix of Header part occurrence in Body
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapBindingFactory.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#26830 use ScheduledExecutorService instead of Timer
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/InMemoryOidcSessionCache.java
Labels: CLA Signed

#26849 Telemetry: Add missing method to GlobalOpenTelemetry
  dev/io.openliberty.io.opentelemetry.1.29/src/io/opentelemetry/api/GlobalOpenTelemetry.java
  dev/io.openliberty.io.opentelemetry/src/io/opentelemetry/api/GlobalOpenTelemetry.java
Labels: CLA Signed

#26808 Start server at the top of the minute
  dev/com.ibm.ws.logging_2_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/server.xml
Labels: noproductcode, CLA Signed

#26819 Fix server config processing in <include> directory to be case-insensitive
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
Labels: CLA Signed

#26855 Properly release lease locks
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LeaseLogImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/SharedServerLeaseLog.java
Labels: CLA Signed

#26731 UpdateTrigger and enableDirectoryMonitoring changes
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/SecurityFileMonitor.java
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.token.ltpa/resources/com/ibm/ws/security/token/ltpa/internal/resources/LTPAMessages.nlsprops
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAConfiguration.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManager.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAValidationKeysInfo.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2Factory.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation1.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation2.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation3.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/LTPA.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ValidationKeys.java
Labels: ID reviewed, CLA Signed, team:Core Security, L2 Reviewed

#15072 14935 Fix non-optimal FreePool invalid connection cleanup
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionEventListener.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/app/DependantApplicationTest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.jakarta/server.xml
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml
  dev/com.ibm.ws.jca_fat/test-applications/fvtweb/src/web/JCAFVTServlet.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnection.java
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTManagedConnectionFactory.java
Labels: team:Zombie Apocalypse, CLA Signed, release bug

#26858 Retrieve gc.time from MP Metrics, instead of GC MXBean for computed m…
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/computed/internal/ComputedMonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/computed/ComputedMonitorMetricsHandler.java
Labels: CLA Signed

#26813 Fix defect 293864
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: CLA Signed

#26857 Repeat Telemetry Jaeger FAT bucket against EE7 and 8
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agent/AgentTestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agentconfig/AgentConfigTestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agentconfig/TestClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agentconfig/WithSpanBean.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/opentracing/CrossFeatureClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/telemetry/CrossFeatureClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/telemetry/CrossFeatureResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/spanTest/TestApplication.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/spanTest/TestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerBaseTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerLegacyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerOtlpTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerSecureOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerSecureOtlpTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/TracingNotEnabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/JaegerQueryClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/JaegerSpanMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServiceNameTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServletTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetrySpiTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryWithSpanErrorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/injected/InjectedClientTestClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/injected/InjectedClientTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/injected/InjectedClientTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/SpanDataMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/resources/META-INF/beans.xml
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/cdi/SPIMetaData.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/cdi/TelemetryExtension.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.classpath
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.project
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/package-info.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/spans/AbstractSpanMatcher.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/spans/package-info.java
Labels: CLA Signed

#26871 Fix up files from previous changes
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/io.openliberty.checkpoint_fat_jms/.classpath
  dev/io.openliberty.checkpoint_fat_jms/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
Labels: CLA Signed, team:Performance

#26801 Force interpretation of Swagger UI js as UTF-8
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/servlet/filter/OpenAPIEndpointFilter.java
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/app/TestResource.java
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/com/ibm/ws/microprofile/openapi/servlet/filter/OpenAPIEndpointFilter.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/TestResource.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UICustomPathTest.java
Labels: CLA Signed

#26533 gRPC library refresh to 1.57.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/grpc-1.0/io.openliberty.grpc-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ClientConfigTests.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppConsumerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppProducerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/BeerServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/streaming/service/StreamingServiceGrpc.java
  dev/com.ibm.ws.grpc_fat/generated-src/io/grpc/examples/helloworld/GreeterGrpc.java
  dev/io.openliberty.grpc.1.0.internal.client.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/original.bnd
  dev/io.openliberty.grpc.1.0.internal.client/src/io/openliberty/grpc/internal/client/LibertyManagedChannelProvider.java
  dev/io.openliberty.grpc.1.0.internal.client/transformed.bnd
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/original.bnd
  dev/io.openliberty.grpc.1.0.internal.common/transformed.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal/original.bnd
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/AsyncServletOutputStreamWriter.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletAdapter.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletServerBuilder.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletServerStream.java
  dev/io.openliberty.grpc.1.0.internal/transformed.bnd
  dev/io.openliberty.grpc.1.0/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/original.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/transformed.bnd
  dev/io.openliberty.io.grpc.1.0/bnd.bnd
  dev/io.openliberty.io.grpc.1.0/original.bnd
  dev/io.openliberty.io.grpc.1.0/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/build.gradle
Labels: ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired, target:230011, release:230011

#26873 Update test to not include mpTelemetry-1.1 when testing Java 8
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/JakartaEE9Test.java
Labels: noproductcode, CLA Signed, team:Performance

#26538 only get primaryKeyImportDir when needed
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
Labels: CLA Signed, team:Core Security

#26820 Fix failing OpenAPI CORS test
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/OpenAPICorsTest.java
Labels: noproductcode, CLA Signed

#26553 update server include docs
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/SchemaData.nlsprops
Labels: ID reviewed, CLA Signed, L2 Reviewed

#26879 Jakarta Validation record tests
  dev/io.openliberty.jakarta.validation.v31_fat/.classpath
  dev/io.openliberty.jakarta.validation.v31_fat/.project
  dev/io.openliberty.jakarta.validation.v31_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.validation.v31_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.validation.v31_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.validation.v31_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.validation.v31_fat/bnd.bnd
  dev/io.openliberty.jakarta.validation.v31_fat/fat/src/io/openliberty/jakarta/validation/v31/fat/FATSuite.java
  dev/io.openliberty.jakarta.validation.v31_fat/fat/src/io/openliberty/jakarta/validation/v31/fat/Validation31Test.java
  dev/io.openliberty.jakarta.validation.v31_fat/publish/servers/validation.v31.fat/bootstrap.properties
  dev/io.openliberty.jakarta.validation.v31_fat/publish/servers/validation.v31.fat/server.xml
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/resources/WEB-INF/beans.xml
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/EmailAddress.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/Person.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/Validation31TestServlet.java
Labels: noproductcode, CLA Signed

#26884 Improving mutinyTest error handling
  dev/com.ibm.ws.concurrent_fat_reactive/publish/servers/com.ibm.ws.concurrent.fat.reactive.ReactiveServer/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ConcurrentReactiveServlet.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/MutinySubscriber.java
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/bootstrap.properties
Labels: noproductcode, CLA Signed

#26861 Telemetry: Change TelemetryServletFilter getHttpRoute
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/servlet/HttpTraceTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/servlet/PlaceHolderServlet.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
Labels: CLA Signed

#26898 replace Filter functions and remove Filter
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Condition.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/ParamInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Compare.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Count.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Exists.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Filter.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Function.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Select.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/function/Extract.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/function/Rounded.java
Labels: team:Zombie Apocalypse, CLA Signed

#26897 Improving the messages for LTPA
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.token.ltpa/resources/com/ibm/ws/security/token/ltpa/internal/resources/LTPAMessages.nlsprops
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
Labels: ID reviewed, CLA Signed, team:Core Security, L2 Reviewed

#26474 Fix ppc64le GLIBC_TUNABLES to allow only P8 hwcaps
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#26863 remove beta checking for sending resource param with auth requests in authorization_code grant flow
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
Labels: CLA Signed

#26018 For quality of life, output the EE level in more places
  dev/fattest.simplicity/src/componenttest/exception/TopologyException.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#26862 Filtering versions of woodstox
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#26901 spec updates to use Optional for Cursor on Pageable
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PaginatedIterator.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pageable.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
Labels: team:Zombie Apocalypse, CLA Signed

#26719 support getting caller and group information from multiple tokens
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/PayloadConstants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MessageConstants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/test-applications/testTokenEndpoint/src/com/ibm/ws/security/fat/testTokenEndpoint/TokenEndpointServlet.java
  dev/com.ibm.ws.security.oidc.client_fat.4/.classpath
  dev/com.ibm.ws.security.oidc.client_fat.4/.project
  dev/com.ibm.ws.security.oidc.client_fat.4/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.4/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.client_fat.4/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.4/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.client_fat.4/bnd.bnd
  dev/com.ibm.ws.security.oidc.client_fat.4/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.4/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.4/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCallerClaims.java
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/defaultSSLSettings.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/goodBasicRegistry.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/miscNoSslSettings.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcClientBasicConfig.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcClientFeatures.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcProvider.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.opWithStub/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.opWithStub/configs/op_server_orig.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.rp/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.rp/configs/rp_server_orig.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.rp/jvm.options
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AttributeToSubject.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/Constants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: CLA Signed, L2 ReviewNotRequired

#26796 Catch up the pb.yml to latest and run pbbeta on build keyword
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#26885 Switch mpTelemetry-1.1 feature tolerates order
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAloneTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Alone/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Alone/server.xml
Labels: CLA Signed

#26883 Telemetry: Don't attempt to compute route when subresources are used
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestSubResource.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryContainerFilter.java
Labels: CLA Signed

#26909 Call RestClientBuilderListener for client beans on EE7/8
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2/src/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3/src/org/apache/cxf/microprofile/client/cdi/RestClientBean.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/injected/InjectedClientTestServlet.java
Labels: CLA Signed

#26875 Liberty Bootstrap ClassLoader changes for concurrency
  dev/com.ibm.ws.artifact.zip/bnd.bnd
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/LibertyLoader.java
  dev/com.ibm.ws.kernel.boot.common/src/com/ibm/ws/kernel/boot/classloader/NameBasedClassLoaderLock.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/utils/KeyBasedLockStore.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/BootstrapChildFirstURLClassloader.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarFileClassLoader.java
Labels: CLA Signed, team:Performance, performance

#26916 Fix expected name in AgentConfigTest
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
Labels: noproductcode, CLA Signed

#26906 Telemetry agent test fix
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agent/AgentTestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
Labels: noproductcode, CLA Signed

#26912 mpTelemetry-1.0 include query in http.target
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestServlet.java
Labels: CLA Signed

#26927 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#26878 add tests for scenarios to cover retrieving caller claims from multiple tokens
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/Constants.java
  dev/com.ibm.ws.security.oidc.client_fat.4/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCallerClaims.java
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcClientBasicConfig.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcProvider.xml
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtilTest.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#26821 Fix RM FAT repeats not loading in mpConfig-3.1 for MP 6.1 repeat
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/publish/servers/SimpleRxMessagingServer/server.xml
Labels: noproductcode, CLA Signed

#26921 Telemetry: Add subresource test for java agent
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agent/AgentSubResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agent/AgentTestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
Labels: noproductcode, CLA Signed

#26930 Issue #26929: Add stop to server start tests
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartAsServiceTest.java
Labels: noproductcode, CLA Signed

#26932 Issue #26931- missing resource for message
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessControlHelper.java
Labels: CLA Signed

#26923 add wc trace to DeliveryDelayClient in com.ibm.ws.messaging.open_jms20deliverydelay_fat
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/servers/DeliveryDelayClient/bootstrap.properties
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#26954 javaMail-1.x: Export Activation APIs as specification APIs
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.5/com.ibm.websphere.appserver.javaMail-1.5.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaMail-1.6/com.ibm.websphere.appserver.javaMail-1.6.feature
Labels: CLA Signed

#26953 JPA entity with attribute converter
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/OffsetDateTimeToStringConverter.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Order.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creatures.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#26955 Testing updateTrigger as disabled
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
Labels: noproductcode, CLA Signed, team:Core Security

#26933 fix ltpa mbean for validation keys
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
Labels: CLA Signed, team:Core Security

#26956 fetch caller claims from multiple tokens - address review comments
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/oidcClientBasicConfig.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.opWithStub/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.rp/bootstrap.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/Constants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtilTest.java
Labels: CLA Signed

#26944 Modify forbidden class support
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
Labels: CLA Signed

#26815 Servlet 6.1 Factory
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.internal-6.1.feature
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/osgi/webapp/WebApp40.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.gitignore
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.project
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.settings/bndtools.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/com/ibm/ws/webcontainer/speclevel/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/com/ibm/ws/webcontainer/speclevel/servletSpecLevel.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/async/factory/AsyncContextFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/async/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/container/config/factory/WebAppConfiguratorFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/container/config/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/response/factory/IRequestResponseFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/response/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/srt/factory/SRTConnectionContextPool61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/srt/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/webapp/factory/WebAppFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/webapp/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/servlet/factory/CacheServletWrapperFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/servlet/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/session/impl/factory/SessionContextRegistryImplFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/session/impl/factory/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/util/factory/URIMatcherFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/util/factory/package-info.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#26913 use ScheduledExecutorService instead of Timer in JtiNonceCache
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JtiNonceCache.java
Labels: CLA Signed

#26972 update santuario xmlsec version to 2.3.4
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.santuario.xmlsec.2.2.0/bnd.bnd
  dev/com.ibm.ws.org.apache.santuario.xmlsec.2.2.0/bnd.overrides
Labels: CLA Signed

#26950 Throw correct exceptions from @Transactional interceptors
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/Required.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/RequiresNew.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/TransactionalInterceptor.java
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transaction_cdi/.gitignore
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transactional/.gitignore
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transactional/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transactional/jvm.options
  dev/com.ibm.ws.transaction.core_fat.cdi/publish/servers/com.ibm.ws.transactional/server.xml
  dev/com.ibm.ws.transaction.core_fat.cdi/test-applications/transactional/src/com/ibm/ws/transactional/web/CheckedUncheckedTestBean.java
  dev/com.ibm.ws.transaction.core_fat.cdi/test-applications/transactional/src/com/ibm/ws/transactional/web/CheckedUncheckedTestServlet.java
Labels: CLA Signed

#26979 Check console log for restore success and fix timing issue with restore log dir changes.
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed

#26936 fix verify message typo
  dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
Labels: ID reviewed, CLA Signed, L2 Reviewed

#26984 LTPA FAT cacheEnabled update
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Authentication.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
Labels: noproductcode, CLA Signed, team:Core Security

#26896 Enable sequential peer recovery
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TranLogConfiguration.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseData.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed

#26988 Add ltpa mbean tests
  dev/com.ibm.ws.security.token.ltpa_fat/bnd.bnd
  dev/com.ibm.ws.security.token.ltpa_fat/build.gradle
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
Labels: noproductcode, CLA Signed, team:Core Security

#26957 remove beta check from fetch caller claims from multiple tokens feature and tests
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.4.rp/jvm.options
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
Labels: CLA Signed

#26986 Fix issues found when generating API / SPI doc for features
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.globalhandler-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.globalhandler-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.security.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundleSecurity1.0.internal.ee-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webBundleSecurity1.0.internal.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthentication-2.0/io.openliberty.appAuthentication-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthentication-3.0/io.openliberty.appAuthentication-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthentication-3.1/io.openliberty.appAuthentication-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/nosql-1.0/io.openliberty.nosql-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/helloworld/HelloWorldResource.java
  dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/BasicJAXRSCDITest.java
Labels: CLA Signed, team:Performance

#26581 Include MP 6.1 in OL zips
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee10/features.xml
  dev/build.image/profiles/microProfile6/features.xml
  dev/build.image/profiles/webProfile10/features.xml
  dev/build.image/publish/wlp/templates/servers/microProfile6/server.xml
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.microprofile.cdi.api-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.microprofile.cdi.api-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry1.1.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config.3.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config.3.0.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.health-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.metrics-5.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-6.1/io.openliberty.microProfile-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.0/io.openliberty.mpConfig-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.1/io.openliberty.mpConfig-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-4.0/io.openliberty.mpFaultTolerance-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics-5.1/io.openliberty.mpMetrics-5.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-3.0/io.openliberty.mpRestClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
Labels: CLA Signed

#26894 Add quotes around -D option values. Remove duplicate options
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#26996 Upgrade to gradle 8.4
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/gradlew
Labels: noproductcode, CLA Signed, team:Performance

#26658 Update metatype descriptions for OpenAPI Endpoints
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#27005 26942 liberty startup script does not resolve symbolic link to bin directory
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#27015 NOTICES for 23.0.0.12
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#26995 ltpa keyrotation debug cleanup
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/LTPAKeyInfoManager.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
Labels: CLA Signed, team:Core Security

#27014 Fix exporting the same API twice with different types
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-7.0/com.ibm.websphere.appserver.javaeeClient-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/javaeeClient-8.0/com.ibm.websphere.appserver.javaeeClient-8.0.feature
Labels: CLA Signed, team:Performance

#27009 Remove ltpa key rotation beta guards
  dev/com.ibm.ws.security.token.ltpa/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.contextRootCookiePathTestServer/jvm.options
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/jvm.options
Labels: CLA Signed, team:Core Security

#27019 Wait for schedule in concurrent persistent JCA FAT
  dev/com.ibm.ws.concurrent.persistent_fat_jca/fat/src/fat/concurrent/persistent/jca/PersistRATest.java
  dev/com.ibm.ws.concurrent.persistent_fat_jca/test-resourceadapters/PersistRA/src/fat/persistra/resourceadapter/PSETestResourceAdapter.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#27018 Add repeat for MP5.0 for Telemetry TCK
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/fat/src/io/openliberty/microprofile/telemetry/internal_fat_tck/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/fat/src/io/openliberty/microprofile/telemetry/internal_fat_tck/Telemetry11TCKLauncher.java
Labels: noproductcode, CLA Signed

#26432 Remove MP OpenAPI endpoint customisation beta guards
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigTest.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.openapi.internal.common/src/io/openliberty/microprofile/openapi/internal/common/OpenAPIEndpointManager.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UICustomPathTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIOauthTest.java
Labels: CLA Signed

#27022 Update OpenAPI UI to newer Axios version
  dev/com.ibm.ws.openapi.ui/swagger-ui/package-lock.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
Labels: noproductcode, CLA Signed

#26990 Telemetry: Use correct @WithSpan binding
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/cdi/WithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/WithSpanExtension.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/WithSpanServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/permissions-ee7.xml
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/cdi/WithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/AbstractWithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/transformed.bnd
Labels: CLA Signed

#27023 Added a wait to Computed MPMetrics FAT to ensure ServletStats MBean are registered before calling /metrics
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
Labels: noproductcode, CLA Signed

#26510 Ltpa key absolute and relative path tests
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyFileManager.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed, team:Core Security

#26968 Catch IllegalArgumentExceptions in ConfigEvaluator - display message
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java
Labels: CLA Signed

#27031 Preserve server logs for XAFlowCallback tests
  dev/com.ibm.ws.transaction.recovery_fat.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.recovery_fat.3/fat/src/tests/WaitForRecoveryTest.java
  dev/com.ibm.ws.transaction.recovery_fat.3/fat/src/tests/XAFlowTest.java
  dev/com.ibm.ws.transaction.recovery_fat.3/publish/servers/com.ibm.ws.transaction_waitForRecovery/server.xml
Labels: noproductcode, CLA Signed

#27028 introduce lease expiry threshold
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseData.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseTable.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.fat.util/bnd.bnd
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATSecurityUtils.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#27029 Explicity drop test tables
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicTestBase.java
Labels: noproductcode, CLA Signed

#27032 Increase DS lock timeout for EJB Async FAT
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncConfigServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncCoreServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncRemoteServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.async_fat/publish/servers/com.ibm.ws.ejbcontainer.async.fat.AsyncSecureServer/bootstrap.properties
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27024 skip test when fips 140-3 is enabled and supported on liberty server
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/FATSuite.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoBasicTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoConfigUpdateTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoDefaultSSLTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLInvalidTrustTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#26983 Save config when preparing to checkpoint
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStore.java
Labels: CLA Signed

#26711 Generate FAT help file and minor cleanup
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.transport.http.compression_fat/fat/src/com/ibm/ws/transport/http/FATSuite.java
  dev/com.ibm.ws.transport.http.remoteip_fat/fat/src/com/ibm/ws/transport/http/FATSuite.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.5.0_fat/fat/src/io/openliberty/org/apache/myfaces50/fat/FATSuite.java
  dev/io.openliberty.pages.3.1.internal_fat/fat/src/io/openliberty/pages31/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27013 Create jakarta servlet 6.1 project
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature
  dev/io.openliberty.jakarta/resources/servlet-6.1/jakarta/servlet/resources/XMLSchema.dtd
  dev/io.openliberty.jakarta/resources/servlet-6.1/jakarta/servlet/resources/datatypes.dtd
  dev/io.openliberty.jakarta/resources/servlet-6.1/jakarta/servlet/resources/xml.xsd
  dev/io.openliberty.jakarta/servlet.6.1.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27043 Explicit imports for CpuInfo
  dev/com.ibm.tx.jta/bnd.bnd
  dev/com.ibm.tx.util/bnd.bnd
Labels: CLA Signed

#27053 Tolerate java.sql.SQLRecoverableException
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
Labels: noproductcode, CLA Signed

#27064 Telemetry: Cleaning up dependencies in the TCKs
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.telemetry.1.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#27058 Update Require-Capability JavaSE to 21
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27070 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#26928 remove wlp entries from jsp bundles
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.jsf.jsp.shared/bnd.bnd
  dev/com.ibm.ws.jsf.shared/bnd.bnd
  dev/com.ibm.ws.jsp.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/io.openliberty.pages.3.1.internal.factories/bnd.bnd
  dev/io.openliberty.session.6.0.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal.factories/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal/bnd.bnd
Labels: CLA Needed, CLA Signed
