Repository OpenLiberty/open-liberty, pull requests merged in 2023-02, with the labels that each got.

#24030 Change org.gradle.jvmargs to -Xmx6400m
  dev/gradle.properties
Labels: CLA Signed, team:Continuous Delivery

#24100 Use https to access dhe
  dev/settings.gradle
Labels: noproductcode, CLA Signed

#24105 Cache TCCL
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WSATServiceImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WebClientImpl.java
Labels: CLA Signed

#24134 Remove unnecessary otel test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvOnlyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigNullTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigSystemPropTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/Telemetry10Servlet.java
Labels: noproductcode, CLA Signed

#24128 Update non-empty beans.xml test
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/config/LegacyConfigTest.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/config/beansxml/beans.xml
Labels: noproductcode, CLA Signed

#24140 Improve empty beans.xml check
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.cdi.weld/test/com/ibm/ws/cdi/impl/test/EmptyBeansTest.java
  dev/com.ibm.ws.cdi.weld/test/com/ibm/ws/cdi/impl/test/trash.xml
  dev/com.ibm.ws.cdi.weld/test/com/ibm/ws/cdi/impl/test/zero_bytes.xml
Labels: CLA Signed

#24114 Update Faces 4.0 to 4.0.0-RC4
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/faces40/AnimalBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSFEL.war/src/com/ibm/ws/jsf22/el/components/CustomComponent.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/flash/FlashImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/el/FacesELContext.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/flow/cdi/FlowScopeContext.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/lifecycle/clientwindow/ClientWindowFactoryImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/resource/default.dtd
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/util/WebXmlParser.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/composite/ClientBehaviorAttachedObjectTargetImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/composite/ClientBehaviorRedirectEventComponentWrapper.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/tag/faces/core/AjaxHandler.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24143 fix npe when request.getCookies returns null
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/CookieBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/CookieBasedStorageTest.java
Labels: CLA Signed

#23237 URI Paths Canonicalization
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet-servletSpi2.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppConfiguration.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppErrorReport.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/osgi/container/config/WebAppConfiguratorHelper60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationBadRequestTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalizationTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalizationTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalizationTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalizationTest.war/resources/jsp/errorPage.jsp
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalizationTest.war/resources/landingPage.jsp
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalizationTest.war/src/servlets/DecodeNormalizeURI.java
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 Reviewed, jakartaEE10

#24166 Test Failure due to timing issues
  dev/com.ibm.ws.session.cache_fat_config/fat/src/com/ibm/ws/session/cache/config/fat/SessionCacheConfigUpdateTest.java
Labels: noproductcode, CLA Signed

#24127 Update to new versions of jakarta APIs and default implementations
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.glassfish.json.2.0/bnd.bnd
  dev/io.openliberty.com.sun.mail.jakarta.mail.2.0/bnd.bnd
  dev/io.openliberty.com.sun.mail.jakarta.mail.2.0/bnd.overrides
  dev/io.openliberty.com.sun.xml.messaging.saaj/2.0.bnd
  dev/io.openliberty.jakarta.activation.2.0/bnd.bnd
  dev/io.openliberty.jakarta.activation.2.1/bnd.bnd
  dev/io.openliberty.jakarta.cdi.3.0/bnd.bnd
  dev/io.openliberty.jakarta.enterpriseBeans.4.0/bnd.bnd
  dev/io.openliberty.jakarta.interceptor.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.1/bnd.bnd
  dev/io.openliberty.jakarta.mail.2.0/bnd.bnd
  dev/io.openliberty.jakarta.soap.2.0/bnd.bnd
  dev/io.openliberty.jakarta.transaction.2.0/bnd.bnd
  dev/io.openliberty.jakarta.validation.3.0/bnd.bnd
  dev/io.openliberty.jakarta.xmlWS.3.0/bnd.bnd
  dev/io.openliberty.jakarta/mail.2.1.bnd
  dev/io.openliberty.org.eclipse.angus.mail/bnd.bnd
  dev/io.openliberty.xmlWS.3.0.internal.tools/bnd.bnd
Labels: CLA Signed, team:Performance

#24109 Myfaces 4555
  dev/io.openliberty.jakarta.faces.4.0/.classpath
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/annotation/FacesConfig.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24170 Remove js files that were missed when updating to RC4
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-development.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-minimal.js
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24102 Don't cleanup TranManagerSet at Tran Manager shutdown
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
Labels: CLA Signed

#24090 Update jbatch test for timing issue
  dev/com.ibm.ws.jbatch.open.bonuspayout_fat/fat/src/batch/fat/junit/BonusPayoutViaJBatchUtilityTest.java
Labels: noproductcode, test bug, CLA Signed

#24197 Fix Clock test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/CommonSDKServlet.java
Labels: noproductcode, CLA Signed

#24181 WTRN0052E during server shut down
  dev/com.ibm.ws.concurrent.persistent_fat_failover1serv/fat/src/com/ibm/ws/concurrent/persistent/fat/failover1serv/SwitchFromSingleInstanceToFailOverTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24178 Increase app start time in EJB FAT
  dev/io.openliberty.ejbcontainer.checkpoint_fat/publish/servers/EjbStartCheckpointMockServer/server.xml
Labels: in:EJB Container, noproductcode, test bug, team:Blizzard, CLA Signed

#24158 Add test for cookie setAttribute SameSite that has precedence over server setting
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60CookieSetAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_cookieSetAttributeTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/CookieSetAttributeTest.war/src/cookiesetattribute/servlets/CookieSetAttributeServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24132 Use IgnoreUnrecognizedVMOptions to avoid unrecognized VM option on checkpoint
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#24175 Tidy up MP Telemetry 1.0 TCK dependencies
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/telemetry/internal_fat_tck/Telemetry10TCKLauncher.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#24193 Revert "Add running condition to datasource"
  dev/com.ibm.ws.jdbc/bnd.bnd
Labels: CLA Signed

#24220 Fix up eclipse files from recent PRs.
  dev/io.openliberty.jaxws.security_fat/.classpath
  dev/io.openliberty.jaxws.security_fat/.project
  dev/io.openliberty.jaxws.security_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxws.security_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxws.security_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxws.security_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.ws.jaxrs.global.handler.internal_fat/.classpath
Labels: noproductcode, CLA Signed, team:Performance

#24108 For RTC294574, make sure min java limits are in place for com.ibm.ws.…
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA20_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA21_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA22_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA30_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#23967 Test annotation literals for Faces 4.0
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AnnotationLiteralsTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_AnnotationLiteralsTest/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_AnnotationLiteralsTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/WEB-INF/testBehavior.taglib.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/annotationLiterals.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlow/testFlow-flow.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlow/testFlow.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlow/testFlow2.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlowNext/testFlowNext.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlowNext/testFlowNext2.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/AttributeFilter.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/ClientBehavior.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/ConfigBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/FaceletViewBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/FlowMapBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/FlowMapNextBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/FlowNext.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/IntegerConverter.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/IntegerDataModel.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/IntegerValidator.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/ManagedPropertyBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/ManagedPropertyCreator.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/TestBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/src/io/openliberty/org/apache/faces40/fat/literals/ViewScopedBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MultipleInputFileTest.war/resources/MutipleInputFile.xhtml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24185 PR for Issue 24037: Update SAML metatype descriptions
  dev/com.ibm.ws.security.saml.websso.2.0/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 ReviewNotRequired

#24208 24206: Adjust wsoc test timer
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
Labels: in:Transport, team:Sirius

#24209 Update Faces 4.0 tests to use new URNs
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExtensionlessMappingNoFacesServletTest.war/resources/ExtensionlessMappingNoFacesServlet.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExtensionlessMappingTest.war/resources/ExtensionlessMapping.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ExternalContextAddResponseCookie.war/resources/ExternalContextAddResponseCookie.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/Faces40ThirdPartyApi.war/resources/Faces40ThirdPartyAPI.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/Faces40ThirdPartyApi.war/resources/Faces40ThirdPartyAPIFailure.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/FacesContextGetLifecycle.war/resources/FacesContextGetLifecycle.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/InputTextType.war/resources/InputTextType.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SelectItemTests.war/resources/selectItemGroup.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SelectItemTests.war/resources/selectItemGroups.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SimpleTest.war/resources/SimpleTest.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/UIViewRootGetDoctypeTest.war/resources/UIViewRootGetDoctype.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24152 Enable Spec Issue 1404 and 1423 tests for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24154 Enable Spec Issue 1430 test for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23GeneralTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24172 Myfaces 4550
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/component/validate/ValidateWholeBeanComponent.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24198 Clean up eclipse warnings in telemetry projects
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/SpanMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/cdi/SpanProxy.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvOnlyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigNullTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigSystemPropTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLoggingExporterTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/bean/TelemetryBeanTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/BaggageServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ConfigServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/LoggingServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/MetricsDisabledServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/OpenTelemetryBeanServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ServiceNameServlet.java
Labels: CLA Signed

#24121 Issue 20846: Create facelet views completely in Java without the use of a facelet file.
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/ProgrammaticFaceletTests.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_programmaticFaceletServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_programmaticFaceletServer/osgi.debug.options
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_programmaticFaceletServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/HtmlAndJava.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/welcome.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/BasicViewFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/FieldFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/HtmlAndJavaFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/MethodFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/NameBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/ParamFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/TestFieldAndMethodViewDeclarations.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24239 Fix JPA test case for RTC 290560
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/testlogic/JPATestOLGH19342Logic.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#24144 Port MYFACES-4553
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/application/NavigationHandlerImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24173 UnsupportedClassVersionError in test init
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/fat/src/com/ibm/ws/concurrent/mp/fat/jakarta/MPContextProp1_3_EE10_Test.java
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/test-applications/MPContextProp1_3_EE10_App/src/concurrent/mp/fat/v13/ee10/web/MPContextProp1_3_EE10_TestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24061 Update version of old wss4j package
  dev/com.ibm.ws.org.apache.wss4j.ws.security.common.2.3.0/bnd.overrides
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/bundles/com.ibm.ws.wssecurity.example.cbh_1.0.0.jar
Labels: noproductcode, CLA Signed

#24233 MYFACES PR 509
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/UIComponent.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24136 Added server alternate
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE8FeatureReplacementAction.java
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/fat/src/com/ibm/ws/webservices/handler/fat/HandlerChainTest.java
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/bootstrap.properties
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/server.xml
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerClient/META-INF/resources/wsdl/sayHelloService.wsdl
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerClient/META-INF/resources/wsdl/sayHelloServiceTypes.xsd
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerClient/WEB-INF/classes/com/ibm/samples/jaxws/client/.gitignore
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerClient/WEB-INF/classes/com/ibm/samples/jaxws/client/servlet/handler/handler-test-client.xml
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerClient/WEB-INF/web.xml
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerProvider/WEB-INF/classes/com/ibm/samples/jaxws/.gitignore
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerProvider/WEB-INF/classes/com/ibm/samples/jaxws/handler/handler-test-provider.xml
  dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/servers/HandlerChainTestServerAlternate/testHandlerProvider/WEB-INF/web.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#24177 Port MYFACES-4533 to Faces 4.0
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-minimal.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-development.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/internal-resources/jakarta.faces/faces-minimal.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/context/servlet/RequestParameterMap.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/util/ViewNamespaceUtils.java
Labels: in:Web Components, CLA Signed, team:Sirius

#24242 Increase facelets buffer size jsf22 stateless view tests
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22StatelessView.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/JSF22StatelessView/resources/WEB-INF/web.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24241 Check isEE10 first
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/ClassloadingTest.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#23968 add updated unittests and improve tracing for saml websso feature
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/acs/AcsHandler.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/acs/SolicitedHandler.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/acs/UnsolicitedHandler.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/HttpRequestInfo.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/acs/SolicitedHandlerTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/acs/UnsolicitedHandlerTest.java
Labels: CLA Signed

#24237 PH52079 - upgrade mime4j to 0.8.9
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: in:JAX-RS, CLA Signed

#24238 PH52095 - CXF-8706: CXF MTOM handler allow content injection
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/attachment/AttachmentUtil.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentUtil.java
Labels: in:JAX-RS, CLA Signed

#24201 Removing NBSP from date/time
  dev/com.ibm.ws.logging.hpel/src/com/ibm/ws/logging/hpel/FormatSet.java
Labels: CLA Signed

#24160 Enable FacesDataModel tests for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FacesDataModelTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24079 Update feature add/remove for LargeProjectRepeatAction
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/LargeProjectRepeatActions.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/oidc/FATSuite.java
Labels: CLA Signed

#24191 MYFACES-4551
  dev/io.openliberty.jakarta.faces.4.0/src/jakarta/faces/component/UISelectOne.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/RendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
Labels: in:Web Components, team:Sirius, jakartaEE10

#24156 Call JaxRsFactoryImplicitBeanCDICustomizer.afterServiceInvoke() to release CreationContexts
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BeanValidationApplication.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BookStoreWithValidationPerRequestLeak.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsInvoker.java
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsServerFactoryBean.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
Labels: in:JAX-RS, CLA Signed

#24231 Enable test that was disabled for RC4
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFHtmlUnit.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22BackwardCompatibilityTests.war/src/com/ibm/ws/jsf22/fat/backwards/beans/faces40/AnimalBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#23964 Issue #23954: Make the authCache->cacheRef and webAppSecurity->logged…
  dev/com.ibm.ws.security.authentication.builtin/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.authentication.builtin/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Wendigo East

#24187 24157: Validate header names
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/channel/test/api/HttpRequestMessageImplTest.java
Labels: in:Transport, CLA Signed, team:Sirius

#24248 Update Programmatic view test to use new Faces 4.0 URNs
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/HtmlAndJava.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/resources/welcome.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/BasicViewFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/FieldFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/HtmlAndJavaFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/MethodFacelet.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/NameBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ProgrammaticFaceletTests.war/src/io/openliberty/org/apache/faces40/fat/programmaticfacelettests/ParamFacelet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24229 Telemetry: More JAX-RS tests and bug fixes
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryClientAsyncTaskWrapper.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryServletContainerInitializer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryServletRequestListener.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLongRunningTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServiceNameTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetrySpiTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/TestExceptionMapper.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestEndpoint.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestEndpointClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/async/JaxRsServerAsyncTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3MultiPropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3PropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/JaegerPropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTraceBaggagePropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTracePropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/multiapp1/MultiApp1TestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/multiapp2/MultiApp2TestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/customizer/CustomizerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/exporter/ExporterTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/PropagatorTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/resource/ResourceTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ServiceNameServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/AbstractSpanMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/SpanDataMatcher.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/TestSpans.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/common/spanexporter/InMemorySpanExporter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/server.xml
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/AsyncClientExecutorService.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/ClientAsyncTaskWrapper.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/internal/AsyncClientExecutorHelper.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/io/openliberty/restfulWS/client/internal/ThreadContextAsyncTaskWrapper.java
Labels: CLA Signed

#24051 Remove beta flag server config val
  dev/com.ibm.ws.rest.handler.config.openapi/bnd.bnd
  dev/com.ibm.ws.rest.handler.config.openapi/src/com/ibm/ws/rest/handler/config/openapi/ConfigSchemaRESTHandler.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator.openapi/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.openapi/src/com/ibm/ws/rest/handler/validator/openapi/ValidatorSchemaRESTHandler.java
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/utils/validationUtils.js
  dev/io.openliberty.rest.handler.config.openapi.2.0/bnd.bnd
  dev/io.openliberty.rest.handler.config.openapi.2.0/src/io/openliberty/rest/handler/config/openapi20/ConfigSchemaRESTHandler.java
  dev/io.openliberty.rest.handler.validator.openapi.2.0/bnd.bnd
  dev/io.openliberty.rest.handler.validator.openapi.2.0/src/io/openliberty/rest/handler/validator/openapi20/ValidatorSchemaRESTHandler.java
Labels: CLA Signed, target:23002

#24240 fix ay11 violations for server config val
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/editorForm.js
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/dialogs/validateConnection.js
Labels: CLA Signed, target:23002

#24257 IdClass parameters on queries
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Condition.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Accounts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employees.java
Labels: team:Zombie Apocalypse, CLA Signed

#24215 Faces 4.0 test for new URNs
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/Faces40URNTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_URN/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_URN/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/Faces40URN.war/resources/Faces40URN.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/Faces40URN.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/Faces40URN.war/src/io/openliberty/org/apache/faces40/fat/urn/component/TestComponent.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24253 Remove JSFApplication from JSF23CDIGeneralTests
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24163 Make JAXRS CDI 2.1 FAT test consistent with corresponding 2.0 version…
  dev/com.ibm.ws.jaxrs.2.1.cdi.2.0_fat/fat/src/com/ibm/ws/jaxrs21/cdi20/fat/ResourceInfoAtStartupTest.java
Labels: in:JAX-RS, noproductcode, CLA Signed

#24260 JAX-WS: Rework HttpConduitPropertiesTest to fix timout issues
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HttpConduitPropertiesTest.java
Labels: noproductcode, CLA Signed

#24261 Update test to pass the correct version for wsimport for EE9
  dev/io.openliberty.ws.jaxws.tools_fat/fat/src/com/ibm/ws/jaxws/tools/FATSuite.java
  dev/io.openliberty.ws.jaxws.tools_fat/fat/src/com/ibm/ws/jaxws/tools/test/FATTest.java
Labels: noproductcode, CLA Signed, team:Performance

#24218 Test restConnector-2.0 with checkpoint/restore
  dev/com.ibm.websphere.appserver.features/visibility/public/restConnector-2.0/com.ibm.websphere.appserver.restConnector-2.0.feature
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RestConnectorTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointRestConnector/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointRestConnector/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointRestConnector/server.xml
Labels: CLA Signed

#24162 initialize outputAutoFVTDirectory variable in wlp.lib.extract_fat
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: noproductcode, test bug, CLA Signed

#24246 fix esa intsall case without shortname set
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#24259 Fix server start test bug
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ServerHelpActions.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
Labels: CLA Signed

#24243 Telemetry: Don't set the current context in the client filter
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryClientFilter.java
Labels: CLA Signed

#24269 Telemetry: test JAX-RS redirect and invalid
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/server.xml
Labels: noproductcode, CLA Signed

#24267 Update restfulWS 3.x features to include xmlBinding API jar
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.0/io.openliberty.restfulWSClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/bnd.bnd
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/fat/src/io/openliberty/jakarta/restfulWS30api/fat/FATSuite.java
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/fat/src/io/openliberty/jakarta/restfulWS30api/fat/app/canload/ApiTestServlet.java
  dev/io.openliberty.jakarta.restfulWS.3.0.api_fat/publish/servers/jaxrs30api/server.xml
  dev/io.openliberty.jakarta.restfulWS.3.0/bnd.bnd
  dev/io.openliberty.jakarta.restfulWS.3.1.api_fat/bnd.bnd
  dev/io.openliberty.jakarta.restfulWS.3.1.api_fat/fat/src/io/openliberty/jakarta/restfulWS31api/fat/FATSuite.java
  dev/io.openliberty.jakarta.restfulWS.3.1.api_fat/fat/src/io/openliberty/jakarta/restfulWS31api/fat/app/canload/ApiTestServlet.java
  dev/io.openliberty.jakarta.restfulWS.3.1.api_fat/publish/servers/jaxrs31api/server.xml
  dev/io.openliberty.jakarta/restfulWS.3.1.bnd
Labels: CLA Signed, team:Performance

#24266 JAX-WS: Add ignore for `CWWKO0801E` in JAX-WS negative test case.
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFNegativePropertiesTest.java
Labels: noproductcode, CLA Signed

#24203 Enable ajax tests with myfaces 4.0-rc4
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AjaxRenderExecuteThisTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ajaxRenderExecuteThis/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_ajaxRenderExecuteThis/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/ajaxRenderExecuteThis.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/resources/components/addressComponent.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/resources/resources/components/addressWrapper.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/src/io/openliberty/org/apache/faces40/fat/ajax/beans/AddressBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AjaxRenderExecuteThisTest.war/src/io/openliberty/org/apache/faces40/fat/ajax/beans/AjaxBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24264 Enable jsf22 flows tests ee10
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/server_testCommonLib.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/server_testFeatureConflict.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/server_testGlobalLib.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/server_testPrivateLib.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.beanval/server.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.cdi/server.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.errorpaths/server.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat.ws/server.xml
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/servers/jsf.container.2.3_fat/server.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24249 Enable jsfContainer_fat_2.3 web socket test for ee10
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24271 Telemetry: document tests via JAX-RS as deliberate
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
Labels: noproductcode, CLA Signed

#24291 Notices for 23.0.0.2
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#24282 update handling of the saml assertions with mutiple Attributes with the same name
  dev/com.ibm.ws.security.saml.websso.2.0/bnd.bnd
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/AssertionToSubject.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/AssertionToSubjectTest.java
Labels: CLA Signed

#24254 Myfaces 4559
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resourcesFaces40/implicit_objects.xhtml
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ELImplicitObjectsViaCDI.war/resourcesJSF23/implicit_objects.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/cdi/FacesArtifactProducer.java
Labels: in:Web Components, team:Sirius, jakartaEE10

#24129 Add tests for UIComponent#subscribeToEvent() improvmenets
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/SubscribeToEventTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_subscribeToEventTest/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_subscribeToEventTest/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SubscribeToEventTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SubscribeToEventTest.war/resources/subscribeToEventTest.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SubscribeToEventTest.war/src/io/openliberty/org/apache/faces40/fat/subscribe/SubscribeTest.java
Labels: team:Zombie Apocalypse, noproductcode

#24283 Fix IllegalStateException, 403 error, and NOT_DONE status for issues #24062, #24204, and #24207
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/AuthenticateApiTest.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanismTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
Labels: CLA Signed, jakartaEE10

#24268 Enable JSF23WebSocketTests for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24263 Test tracing between opentracing and mpTelemetry
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/opentracing/CrossFeatureClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/opentracing/CrossFeatureResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/telemetry/CrossFeatureClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/crossfeature/telemetry/CrossFeatureResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/JaegerContainer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingServer/server.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureTelemetryServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureTelemetryServer/server.xml
Labels: noproductcode, CLA Signed

#24199 Clean up Telemetry bundles
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.telemetry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
  dev/io.openliberty.io.opentelemetry.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/longrunning/LongRunningTask.java
  dev/io.openliberty.mpTelemetry.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile/bnd.bnd
Labels: CLA Signed

#24292 Enable testSelectOneRadioGroup_uiRepeat test for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24146 28206 - Server Config - Source - violations on a11y checkpoint 1.4.3
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/css/editor.css
Labels: CLA Signed

#24278 Test audit-1.0 with checkpoint/restore
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-1.0/com.ibm.websphere.appserver.audit-1.0.feature
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/AuditTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPConfigTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPHealthTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAudit/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAudit/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAudit/server.xml
Labels: CLA Signed

#24303 Remove unused code
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/JSFApplication.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/JSFImplementation.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/UseImplementation.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/WebArchiveInfo.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24169 add fat tests for OpenIdAuthenticationMechanismDefinition tokenMinValidity and tokenMinValidityExpression
  dev/io.openliberty.security.jakartasec.3.0.internal/resources/io/openliberty/security/jakartasec/internal/resources/JakartaSecurity30Messages.nlsprops
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/JakartaSec30Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/tokens/AccessTokenImpl.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonAnnotatedSecurityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/configs/TestConfigMaps.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/MessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseOpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTokenMinValidityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_tokenMinValidity.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcTokenMinValidityProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/MaximumAnnotation.war/src/oidc/client/maximumAnnotation/servlets/MaximumAnnotationServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/MaximumAnnotationUsingEL.war/src/oidc/client/maximumAnnotationUsingEL/servlets/MaximumAnnotationUsingELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity0s.war/src/oidc/client/tokenMinValidity0s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity0s.war/src/oidc/client/tokenMinValidity0s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity0s.war/src/oidc/client/tokenMinValidity0s/servlets/TokenMinValidity0sServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity20s.war/src/oidc/client/tokenMinValidity20s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity20s.war/src/oidc/client/tokenMinValidity20s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity20s.war/src/oidc/client/tokenMinValidity20s/servlets/TokenMinValidity20sServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity30s.war/src/oidc/client/tokenMinValidity30s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity30s.war/src/oidc/client/tokenMinValidity30s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity30s.war/src/oidc/client/tokenMinValidity30s/servlets/TokenMinValidity30sServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5s.war/src/oidc/client/tokenMinValidity5s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5s.war/src/oidc/client/tokenMinValidity5s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5s.war/src/oidc/client/tokenMinValidity5s/servlets/TokenMinValidity5sServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5sWithEL.war/src/oidc/client/tokenMinValidity5sWithEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5sWithEL.war/src/oidc/client/tokenMinValidity5sWithEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity5sWithEL.war/src/oidc/client/tokenMinValidity5sWithEL/servlets/TokenMinValidity5sWithELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity60s.war/src/oidc/client/tokenMinValidity60s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity60s.war/src/oidc/client/tokenMinValidity60s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidity60s.war/src/oidc/client/tokenMinValidity60s/servlets/TokenMinValidity60sServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityDefault.war/src/oidc/client/tokenMinValidityDefault/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityDefault.war/src/oidc/client/tokenMinValidityDefault/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityDefault.war/src/oidc/client/tokenMinValidityDefault/servlets/TokenMinValidityDefaultServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityEL.war/src/oidc/client/tokenMinValidityEL/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityEL.war/src/oidc/client/tokenMinValidityEL/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityEL.war/src/oidc/client/tokenMinValidityEL/servlets/TokenMinValidityELServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityNegative5s.war/src/oidc/client/tokenMinValidityNegative5s/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityNegative5s.war/src/oidc/client/tokenMinValidityNegative5s/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/TokenMinValidityNegative5s.war/src/oidc/client/tokenMinValidityNegative5s/servlets/TokenMinValidityNegative5sServlet.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24217 add jdk 17 env for esa parser
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/EsaParser.java
Labels: CLA Signed

#24308 sync up change with websphere liberty fat
  dev/com.ibm.ws.jbatch.open.security_fat/fat/src/batch/fat/junit/BatchJobOperatorApiWithAppSecurityTest.java
Labels: noproductcode, test bug, CLA Signed

#24327 JAX-WS and JAX-RS: Add timeouts to Rest Clients in interop Test
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/.classpath
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-prototype/src/com/ibm/ws/jaxrs/fat/prototype/PrototypeClientTestServlet.java
  dev/io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxws-peopleservice/src/com/ibm/ws/jaxws/test/wsr/server/impl/Bill.java
Labels: noproductcode, CLA Signed

#24149 Issue 20813: Faces 4.0 FAT tests for outputScript and outputStylesheet.
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/JSFUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/Html5Tests.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/WebSocketTests.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_WebSocketServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_WebSocketServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_html5Server/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_html5Server/osgi.debug.options
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_html5Server/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/WEB-INF/resources/css/styles.css
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/WEB-INF/resources/scripts/helloMessage.js
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputScript.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputScriptHtml5.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputStylesheet.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputStylesheetHtml5.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/resources/OnErrorWebSocketTest.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/resources/websocketListeners.js
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/src/io/openliberty/org/apache/faces40/fat/websocket/WebsocketPushBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24306 Add comment about why tests are skipped for EE10
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSFContainerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24312 Fix to get correct host port info
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFPositivePropertiesTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/wsfeatures/client/WSAPropertyTestServlet.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#24314 token validation update
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenValidatorTest.java
Labels: CLA Signed

#24341 Revert "Fix to get correct host port info"
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFPositivePropertiesTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/wsfeatures/client/WSAPropertyTestServlet.java
Labels: noproductcode, CLA Signed

#23350 Update Gradle to 7.4.1: test
  .ci-orchestrator/compile.properties
  .ci-orchestrator/compilePersonalRTC.properties
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/scheduledPersonalBuilds.yml
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/build.image/build.gradle
  dev/build.pii.package/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jbatch.fat.common/build.gradle
  dev/com.ibm.ws.jbatch.open_fat/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/ShibbolethCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/springboot.gradle.disabled
  dev/com.ibm.ws.springboot.support.version20.test.actuator.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.java.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.multi.context.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.war.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webanno.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.websocket.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version20.test.websocket.app/build.gradle
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CDITests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15Servlet40.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPage15Test.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/InvalidAppTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MimeMapping15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingSslFeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot15FeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UnsupportedConfigWarningTest15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UseDefaultHostTest15.java
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/settings.gradle
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#24234 SR Metrics 5.0-RC3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
Labels: CLA Signed

#24324 Remove -Xsyslog:none -Djdk.nativeEC=false options for InstantOn
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#24133 Create FAT tests for @OpenIdProviderMetadata
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/configs/TestConfigMaps.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/MessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseOpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/utils/ServletLogger.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationProviderMetadataTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/servers/jakartasec-3.0_fat.config.op/configs/server_providerMetadata.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/publish/shared/config/oidcProviderMetadataProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/AuthorizationEndpointServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/EndSessionEndpointServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/GenericTestServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/JwksURIServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/TokenEndpointServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/Endpoints.war/src/endpoints/servlets/UserinfoEndpointServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ProviderMetadata.war/src/providerMetadata/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ProviderMetadata.war/src/providerMetadata/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/test-applications/ProviderMetadata.war/src/providerMetadata/servlets/ProviderMetadataServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/fat/src/io/openliberty/security/jakartasec/fat/logout/tests/BasicLogoutTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/publish/shared/config/oidcProvider.xml
Labels: noproductcode, CLA Signed, team:Security SSO, test delivery

#24349 Incorrect host port (corrected)
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFNegativePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/LibertyCXFPositivePropertiesTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/webServiceRefFeatures/src/com/ibm/ws/test/wsfeatures/client/WSAPropertyTestServlet.java
Labels: in:Web Services, noproductcode, team:Bobcats

#24346 Update tests to use new URNs
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputScript.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputScriptHtml5.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputStylesheet.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/HTML5Tests.war/resources/outputStylesheetHtml5.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/SubscribeToEventTest.war/resources/subscribeToEventTest.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/WebSocket.war/resources/OnErrorWebSocketTest.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24280 Remove pages-3.1 feature from facesContainer-4.0 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.0/io.openliberty.facesContainer-4.0.feature
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24281 IdClass as a named parameter
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#24302 SubjectDN change to remove the IBM from the name
  dev/com.ibm.ws.crypto.certificateutil/src/com/ibm/ws/crypto/certificateutil/DefaultSubjectDN.java
  dev/com.ibm.ws.crypto.certificateutil/test/com/ibm/ws/crypto/certificateutil/DefaultSubjectDNTest.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTaskTest.java
Labels: CLA Signed

#24328 Telemetry - Enable strict context checking in tests
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/MultiThreadedContextTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAPITest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryBeanTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvOnlyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigNullTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigSystemPropTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLoggingExporterTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLongRunningTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServiceNameTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetrySpiTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/api/ContextAPIServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/bean/TelemetryBeanTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/context/MultiThreadedContextServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3MultiPropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3PropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/JaegerPropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTraceBaggagePropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTracePropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/PropagatorTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Api/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Bean/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10ConfigEnv/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10ConfigNull/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10ConfigServerVar/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10ConfigSystemProp/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Context/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10LongRunning/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MisConfig/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MultiApp/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Spi/jvm.options
Labels: noproductcode, CLA Signed

#24334 Fix TelemetryMisconfigTest with regex
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
Labels: noproductcode, CLA Signed

#24332 Update mavencoordinates to match the updates in PR #24127
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.enterpriseBeans-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.interceptor-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.nosql-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.0.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.jta-2.0.feature
Labels: CLA Signed, team:Performance

#24326 purge futures list when application is stopped
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ConcurrencyService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceImpl.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedScheduledExecutorServiceImpl.java
Labels: team:Zombie Apocalypse, CLA Signed

#24337 Fix RTC294574
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/publish/servers/javaSupportServer_JPA30/apps/JakartaSupportTest_111.war
Labels: noproductcode, CLA Signed

#24183 Disable IBM i tests that have never worked
  dev/com.ibm.ws.jdbc_fat_db2/test-applications/db2fat/src/db2/web/DB2TestServlet.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/test-applications/otherapp/src/web/other/LoadFromAppServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLTestServlet.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartJavaEnvironmentVariablesTest.java
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerAppDefinedResourcesTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
  dev/fattest.simplicity/src/componenttest/annotation/SkipIfSysProp.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
Labels: noproductcode, CLA Signed

#24364 Update EERepeatAction to behave like MicroProfileActions
  dev/fattest.simplicity/src/componenttest/rules/repeater/EERepeatActions.java
Labels: noproductcode, CLA Signed, team:Performance

#24210 Stop servers in @After
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
Labels: noproductcode, CLA Signed

#24365 Add feature before doing checkpoint
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SSLTest.java
Labels: noproductcode, CLA Signed

#18371 Allow oracle JDBC driver to log to seperate file
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleCustomTrace.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTraceTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/jvm.options
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracletracefat/src/trace/web/OracleTraceTestServlet.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#24307 Make snakeyaml use SafeConstructor by default
  dev/io.openliberty.com.fasterxml.jackson/.classpath
  dev/io.openliberty.com.fasterxml.jackson/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson/src/org/yaml/snakeyaml/Yaml.java
Labels: CLA Signed, target:23002

#24378 sort criteria precedence and limit data type update
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Limit.java
Labels: team:Zombie Apocalypse, CLA Signed

#24385 include beta jar in dev/api/spec
  dev/io.openliberty.jakarta.data.1.0/bnd.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#24390 RTC294172 RTC293474 RTC294307 Build break fixes
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jsf/SimpleJSFWithSharedLibTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/vistest/VisTest.java
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
Labels: noproductcode, CLA Signed

#24406 disable jakarta sec 3.0 tokenMinValidity fat tests
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/FATSuite.java
Labels: noproductcode, CLA Signed

#24394 SmallRye Metrics 5.0.0-RC4
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
Labels: CLA Signed

#23097 [TS010666588] skip illegal characters in jvm.options.
  dev/com.ibm.ws.appclient.boot.ws-client/publish/bin/client
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartJVMOptionsTest.java
Labels: CLA Signed

#24368 XML Binding 4.0: Prevent duplicate field in Item test class
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/dataobjects/Items.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#24222 Ol 28618
  dev/build.featureStart.base/.classpath
  dev/build.featureStart.base/bnd.bnd
  dev/build.featureStart.base/overview.txt
  dev/build.featureStart.base/readme.java.txt
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-stable.txt
  dev/build.featureStart.base/src/com/ibm/ws/simple/base/FeaturesStartTestBase.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/FeaturesStartTestBase.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/FileRewriter.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureData.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureErrors.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureFilter.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureLevels.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureReports.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureStability.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/package-info.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/package-info.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/utils/NamedParameterized.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/utils/package-info.java
  dev/build.featureStart.base/timing.txt
  dev/build.featureStart.part1_fat/fat/src/com/ibm/ws/test/featurestart/FATSuite.java
  dev/build.featureStart.part1_fat/fat/src/com/ibm/ws/test/featurestart/FeaturesStartTest1.java
  dev/build.featureStart.part2_fat/fat/src/com/ibm/ws/test/featurestart/FATSuite.java
  dev/build.featureStart.part2_fat/fat/src/com/ibm/ws/test/featurestart/FeaturesStartTest2.java
  dev/build.featureStart.part3_fat/fat/src/com/ibm/ws/simple/FeaturesStartTest3.java
  dev/build.featureStart.part3_fat/fat/src/com/ibm/ws/test/featurestart/FATSuite.java
  dev/build.featureStart.part3_fat/fat/src/com/ibm/ws/test/featurestart/FeaturesStartTest3.java
  dev/build.featureStart.part4_fat/fat/src/com/ibm/ws/simple/FeaturesStartTest4.java
  dev/build.featureStart.part4_fat/fat/src/com/ibm/ws/test/featurestart/FATSuite.java
  dev/build.featureStart.part4_fat/fat/src/com/ibm/ws/test/featurestart/FeaturesStartTest4.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#24355 add new messages to log idtoken validation failures
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenValidator.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/TokenValidatorTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 Reviewed

#24382 Only validate header name once
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/values/HttpHeaderKeys.java
Labels: CLA Signed, team:Performance, performance

#24381 Update MP Metrics 5.0 tests for SmallRye RC3 updates
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/monitoring/GrpcMetricsTestUtils.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/RestMetricsTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/TestEnableDisableFeaturesTest.java
Labels: noproductcode, CLA Signed, team:Performance

#24147 Fix OL FATs that fail on IBM i due to incorrect shell usage
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/JAXBToolsTest.java
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/WADLTest.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/utility/SpringBootUtilityScriptUtils.java
  dev/io.openliberty.ws.jaxws.tools_fat/fat/src/com/ibm/ws/jaxws/tools/test/FATTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24389 disable test on java 8
  dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/test/JAXRS21ClientSSLProxyAuthTest.java
Labels: noproductcode, CLA Signed

#24325 New FAT for jbatch 2.1 CDI
  dev/com.ibm.ws.jbatch.cdi_fat/fat/src/fat/junit/BatchInjectionTest.java
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/resources/InjectionNonStringProps.xml
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/src/app/injection/BatchInjectionServlet.java
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/src/app/injection/ee10/InjectablesNonStringProps.java
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/src/app/injection/ee10/NonStringPropsBean.java
Labels: noproductcode, CLA Signed

#24388 Add checks for unexpected app restart in checkpoint FATS
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#24228 Rework SingletonMonitor to use Modify instead of configevent
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.app.manager/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/lifecycle/ApplicationPrereqMonitor.java
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/lifecycle/ApplicationStartBarrierImpl.java
  dev/com.ibm.ws.messaging.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.messaging.common/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonMonitor.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonsReady.java
Labels: CLA Signed

#24347 Additional URIPathCanonicalization Tests
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationBadRequestTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationServerXMLTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60URIPathCanonicalizationWebXMLTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalServerXMLTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalServerXMLTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalWebXMLTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_uriPathCanonicalWebXMLTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalWebXmlTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalWebXmlTest.war/src/uripathwebxml/servlets/DecodeNormalizeURI_2.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/URIPathCanonicalizationTest.war/src/uripath/servlets/DecodeNormalizeURI.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24348 Mail 2.0: Add missing mapping files to bnd.bnd.
  dev/io.openliberty.mail.2.0.internal/bnd.bnd
Labels: CLA Signed

#24412 Added extra test to detect third party library addition
  dev/io.openliberty.xmlBinding.4.0.internal_fat/build.gradle
  dev/io.openliberty.xmlBinding.4.0.internal_fat/fat/src/io/openliberty/xmlbinding40/fat/LibertyJAXBRIContextTest.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/fat/src/io/openliberty/xmlbinding40/fat/util/ExplodedShrinkHelper.java
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/JAXBContextTestServlet.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#24373 Changes needed to avoid Java2 security exceptions and quiesce warnings
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/OSGiBeanLocator.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/ClientFeatureTest.java
  dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/RegisterRestClientTest.java
Labels: CLA Signed

#23755 Refactored OpenAPIUIBundlesUpdater to use service listeners for OpenA…
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/OpenAPIUIBundlesListener.java
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/OpenAPIUIBundlesUpdater.java
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/customization/OpenAPIUIBundlesListener.java
  dev/com.ibm.ws.openapi.3.1/src/com/ibm/ws/openapi31/customization/OpenAPIUIBundlesUpdater.java
Labels: CLA Signed

#24404 Update com.ibm.ws.jaxrs20.fat.AnnotationScanTest for RTC289602
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/AnnotationScanTest.java
Labels: noproductcode, team:Blizzard, CLA Signed

#24408 Resolve RTC291838 with change to FAT com.ibm.ws.jaxrs.2.0_fat
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/SecuritySSLTest.java
Labels: noproductcode, team:Blizzard, CLA Signed

#24425 Revert "Only validate header name once"
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/values/HttpHeaderKeys.java
Labels: CLA Signed

#24363 Fix transaction testcontainer timeouts
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
Labels: team:Zombie Apocalypse

#23916 Fix wlp.lib.extract_fat.PackageRunnableTest.testRunnableJar on IBM i
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractRun.java
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractUtils.java
  dev/wlp.lib.extract/src/wlp/lib/extract/ShutdownHook.java
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#24417 Account for a cert path error on client auth
  dev/io.openliberty.jaxws.security_fat/fat/src/com/ibm/ws/jaxws/security/fat/ClientCertificateTest.java
Labels: noproductcode, CLA Signed

#24299 Pages API: export 3.1.1 package versions
  dev/io.openliberty.jakarta/pages.3.1.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24416 Improved exception handling
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/vistest/VisTest.java
Labels: noproductcode, CLA Signed

#24424 Remove server reconfiguration from wsoc SecureTest
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/SecureTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/TraceTest.java
  dev/io.openliberty.wsoc.internal_fat/publish/files/Secure/server.xml
  dev/io.openliberty.wsoc.internal_fat/publish/servers/secureTestServer/server.xml
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#24330 Jakarta Faces rename
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/io.openliberty.faces-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.0/resources/l10n/io.openliberty.faces-4.0.properties
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.0/io.openliberty.facesContainer-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.0/resources/l10n/io.openliberty.facesContainer-4.0.properties
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-facelettaglibrary_4_0.xsd
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 ReviewNotRequired, jakartaEE10

#24433 add Java EE annotation to buildpath
  dev/com.ibm.ws.transport.iiop.open_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#24411 adding sort criteria to custom queries
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
Labels: team:Zombie Apocalypse, CLA Signed

#24429 check to prevent npe in case access token is missing in the token response
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
Labels: CLA Signed
