Repository OpenLiberty/open-liberty, pull requests merged in 2023-05, with the labels that each got.

#25142 validationTimeout description should include how the timeout is applied per connection
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
Labels: team:Zombie Apocalypse, CLA Signed

#25067 Checkpoint openid connect client
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectClient-1.0/com.ibm.websphere.appserver.openidConnectClient-1.0.feature
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.classpath
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.project
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_security_oidc_social/bnd.bnd
  dev/io.openliberty.checkpoint_fat_security_oidc_social/build.gradle
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/oidc/OidcClientBasicTests.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/social/LibertyOP_BasicTests_oauth_usingSocialConfig.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/securty/common/FATSuite.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/files/internalFeatures/securitylibertyinternals-1.0.mf
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/securitykeys/rsa_badTrust.jks
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/securitykeys/rsa_badTrust.jks.orig
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/securitykeys/rsa_trust.jks
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/securitykeys/rsa_trust_for_LibertyOP.jks
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.op/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.op/configs/server.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.op/jvm.options
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/configs/server.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/jvm.options
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/configs/server.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/jvm.options
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/server.env
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/configs/server.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/configs/server_withJwtSsoFeature.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/jvm.options
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/server.env
Labels: CLA Signed

#25133 Issue 21826: Add prototype code for creating private_key_jwt client authentication
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/config/DiscoveryConfigUtils.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/expectations/UserInfoJsonExpectation.java
  dev/com.ibm.ws.security.openidconnect.client/resources/com/ibm/ws/security/openidconnect/client/internal/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheHelper.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheHelperTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/jose4j/util/EcJwkTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/OidcTokenImplBase.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ClientConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConfigUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/Constants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcCommonClientRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/TraceConstantsCommonMessages.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/PrivateKeyJwtAuthMethod.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/TokenEndpointAuthMethod.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/TokenEndpointAuthMethodSettingsException.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/package-info.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/JWT.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/impl/IdTokenImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/client/jose4j/util/OidcTokenImplBaseTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/ConfigUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/token/auth/PrivateKeyJwtAuthMethodTest.java
  dev/com.ibm.ws.security.openidconnect.common/src/com/ibm/websphere/security/openidconnect/package-info.java
  dev/com.ibm.ws.security.openidconnect.common/src/com/ibm/ws/security/openidconnect/common/impl/PropagationHelperImpl.java
  dev/com.ibm.ws.security.openidconnect.server/resources/sessionMgmt.jsp
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/ServerConstants.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/OidcServerConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/IDTokenHandler.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/PrivateKeyJwtAuthException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/PrivateKeyJwtAuthMissingKeyException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethod.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethodTest.java
Labels: CLA Signed, team:Security SSO

#25105 Enbaled WebProfileJSPtest with basic checkpoint and restore coverage
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebProfileJSPtest.java
Labels: noproductcode, CLA Signed

#25143 Update tests due to 3hrs limit on Fyre Windows
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/AsyncReadListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/AsyncWriteListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDINoInjectionTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDITests.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/FormLoginReadListenerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/HttpSessionAttListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/JSPServerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/NBMultiReadTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/PrivateHeaderTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeReadListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeReadWriteTimeoutHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/UpgradeWriteListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/VHServerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServletContextUnsupportedOperationExceptionTest.java
Labels: noproductcode, CLA Signed

#25155 Enable instant on ejb timer test
  dev/com.ibm.ws.app.manager.wab/src/com/ibm/ws/app/manager/wab/internal/WABInstaller.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LocalEJBTest.java
Labels: CLA Signed

#25147 Enabled OpenAPI for coverage with checkpoint and restore
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/OpenAPITest.java
Labels: noproductcode, CLA Signed

#25127 LibertyServer improvments for checkpoint FATS
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointFailTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/server.env
Labels: ID reviewed, CLA Signed, L2 Reviewed

#25130 Tolerate HeuristicRollbackException
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/fat/src/tests/MultiRecoveryTest3.java
Labels: noproductcode, CLA Signed

#24529 Remove extendedHandshake property from Plugin autogeneration
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype-mbeans.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype-mbeans.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/mbeans/PluginGenerator.java
Labels: in:Web Components, ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#25167 Change from SimpleDateFormat in ThreadLocals to DataTimeFormatter
  dev/com.ibm.tx.util/src/com/ibm/tx/util/Utils.java
  dev/com.ibm.websphere.security/src/com/ibm/websphere/security/audit/AuditEvent.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_Utils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipCachingServiceImpl.java
  dev/com.ibm.ws.dynacache.web/src/com/ibm/ws/cache/web/ExternalCacheFragment.java
  dev/com.ibm.ws.http.plugin.merge/src/com/ibm/ws/http/plugin/merge/internal/PluginMergeToolImpl.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/interceptor/CachedTime.java
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/interceptor/JAXRSOutInterceptor.java
  dev/com.ibm.ws.jaxrs.2.0.common/test/com/ibm/ws/jaxrs/utils/test/JAXRSOutInterceptorTest.java
  dev/com.ibm.ws.jaxrs.2.0.common/test/org/apache/cxf/jaxrs/interceptor/CachedTimeAccessor.java
  dev/com.ibm.ws.jbatch.joblog/src/com/ibm/ws/jbatch/joblog/internal/impl/JobLogManagerImpl.java
  dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/utils/TaskIO.java
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/DataFormatHelper.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/CachedTime.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs/utils/test/JAXRSOutInterceptorTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/org/apache/cxf/jaxrs/interceptor/CachedTimeAccessor.java
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/AcmeHistory.java
  dev/com.ibm.ws.security.audit.file/src/com/ibm/ws/security/audit/logutils/FileLogSet.java
  dev/com.ibm.ws.security.audit.file/src/com/ibm/ws/security/audit/logutils/FileLogUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpDateFormatImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpLocalFormat.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/internal/HttpDateFormatTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: CLA Signed, team:Performance, performance

#25184 additional patterns
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Houses.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#24940 Convert to units defined by parameter
  dev/com.ibm.ws.request.timing/src/com/ibm/ws/request/timing/queue/QueueableRequest.java
Labels: CLA Signed

#25195 Ensure no null obj is passed when tags are null + update FATS
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/FATSuite.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingEventTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMbeanTest.java
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/internal/MonitorMetrics.java
Labels: CLA Signed

#25196 Ensure Equinox state is saved before checkpoint
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
Labels: CLA Signed

#25211 Fix the failing FAT test CheckpointFailTest
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointFailTest.java
Labels: noproductcode, CLA Signed

#25218 Ensure the loader has access to checkpoint before transforming
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointTransformer.java
Labels: CLA Signed

#25221 Consider all jar poms
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePomJar.java
Labels: CLA Signed

#25146 Pkce fat 1
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.classpath
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.project
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/CommonPKCE.gradle
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/bnd.bnd
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/build.gradle
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PKCE/PKCEClientTests.java
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PKCE/package-info.java
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/publish/servers/com.ibm.ws.security.SSO.op.pkce/bootstrap.properties
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/publish/servers/com.ibm.ws.security.SSO.op.pkce/configs/op_server_PKCE.xml
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/publish/shared/config/goodBasicRegistry.xml
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/publish/shared/config/oidcProvider_PKCE.xml
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/publish/shared/config/oidcServerFeatures.xml
  dev/com.ibm.ws.security.fat.common.social/src/com/ibm/ws/security/fat/common/social/MessageConstants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/Constants.java
  dev/com.ibm.ws.security.oidc.client_fat.3/.classpath
  dev/com.ibm.ws.security.oidc.client_fat.3/.project
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.client_fat.3/bnd.bnd
  dev/com.ibm.ws.security.oidc.client_fat.3/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.3/fat/src/com/ibm/ws/security/openidconnect/client/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.3/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientPKCETests.java
  dev/com.ibm.ws.security.oidc.client_fat.3/gradle.properties
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/formlogin_1.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/goodBasicRegistry.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/oidcClientFeatures.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/oidcClientPKCEConfig.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp.pkce/bootstrap.properties
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp.pkce/configs/rp_server_PKCE.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp.pkce/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.classpath
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.project
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/bnd.bnd
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/fat/src/com/ibm/ws/security/social/fat/LibertyOP/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_Social_PKCETests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/gradle.properties
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/files/serversettings/LibertyOP_pkce_oidc_SocialConfig.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/files/serversettings/goodLibertyOPRegistry.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social.pkce/bootstrap.properties
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social.pkce/configs/server_LibertyOP_PKCE.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social.pkce/jvm.options
Labels: CLA Signed, team:Security SSO, test delivery

#25205 Resolve code review comments from PR 25148
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/SSLUtils.java
Labels: CLA Signed

#25206 Increased the test application start up from for MP Health 3.1 FAT
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/DefaultOverallStartupStatusUpAppStartupTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/DelayedHealthCheckApp/src/io/openliberty/microprofile/health31/delayed/health/check/app/DelayedServlet.java
Labels: noproductcode, CLA Signed

#25203 avoid claiming task when application is unavailable
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/db/DatabaseTaskStore.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/PersistentExecutorImpl.java
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/wsspi/concurrent/persistent/TaskStore.java
Labels: team:Zombie Apocalypse, CLA Signed

#25231 Handle Peer Locking Heartbeat at Shutdown
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: CLA Signed

#25234 Log condition corrected
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/HandlerChainWithWebServiceClientTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#25242 Update javadoc arguments for building with Java 17
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: noproductcode, CLA Signed, team:Performance

#25240 Rework the mapCache fat
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MapCacheTest.java
  dev/io.openliberty.checkpoint_fat/test-applications/mapCache/src/mapCacheApp/MapCache.java
Labels: noproductcode, CLA Signed

#25230 Fix resource leaks in MP OpenAPI 2.0+
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ApplicationProcessor.java
Labels: CLA Signed

#25198 Handle early transaction recovery log failures better
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxStatement.java
Labels: CLA Signed

#25250 add CDI trace
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction/server.xml
Labels: noproductcode, CLA Signed

#25183 JNoSQL loading Entities
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/nosql-1.0/io.openliberty.nosql-1.0.feature
  dev/io.openliberty.data.internal.nosql/.classpath
  dev/io.openliberty.data.internal.nosql/bnd.bnd
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/cdi/DocumentExtensionProvider.java
  dev/io.openliberty.data.internal_fat_nosql/bnd.bnd
  dev/io.openliberty.data.internal_fat_nosql/fat/src/test/jakarta/data/nosql/DataNoSQLTest.java
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/server.xml
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/DataNoSQLServlet.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/Employee.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/Employees.java
  dev/io.openliberty.jakarta.nosql.1.0/bnd.bnd
  dev/io.openliberty.org.eclipse.jnosql.1.0/.classpath
  dev/io.openliberty.org.eclipse.jnosql.1.0/.project
  dev/io.openliberty.org.eclipse.jnosql.1.0/bnd.bnd
Labels: CLA Signed

#25236 Fix log marks on windows servlet31 fat
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServletContextUnsupportedOperationExceptionTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationException/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationException/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_ServletContext_UnsupportedOperationException/server.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25241 Check for errors in log after a server checkpoint
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPFaultToleranceTimeoutTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/URAPIs_Federation_2LDAPsTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/timeoutServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/bells/src/bells/AppInitializer.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/JPATest.java
Labels: noproductcode, CLA Signed

#25192 Grab exclusive lock to logging on checkpoint
  dev/com.ibm.ws.crypto.ltpakeyutil/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.security/bnd.bnd
  dev/com.ibm.ws.event/bnd.bnd
  dev/com.ibm.ws.jbatch.jms/bnd.bnd
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointHook.java
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.filemonitor/bnd.bnd
  dev/com.ibm.ws.logging.hpel/bnd.bnd
  dev/com.ibm.ws.logging.osgi/bnd.bnd
  dev/com.ibm.ws.logging/bnd.bnd
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.product.utility/bnd.bnd
  dev/com.ibm.ws.security.spnego/bnd.bnd
  dev/com.ibm.ws.security.wim.core/bnd.bnd
  dev/com.ibm.ws.security/bnd.bnd
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint/test/io/openliberty/checkpoint/internal/CheckpointImplTest.java
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/wlp.lib.extract_test/bnd.bnd
Labels: CLA Signed

#25253 Added retry request capability to requestTiming FATs
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestEnableThreadDumps.java
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestTiming.java
Labels: noproductcode, CLA Signed

#25054 add portOpenRetries for intermittent zOS timing errors - 295457
  dev/com.ibm.ws.componenttest/autoFVT-defaults/fatTestPorts.xml
  dev/fattest.simplicity/autoFVT-defaults/fatTestPorts.xml
Labels: team:Zombie Apocalypse, CLA Signed

#25263 Avoid deleting created dropins folder before checkpoint
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/monitor/DropinMonitor.java
Labels: CLA Signed

#25249 Delete test tables between repeats
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestRetriableCodes.java
Labels: CLA Signed

#25154 adding more unittests to samlWeb project
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/SsoRequestTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/clockskew/NotBeforeTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/clockskew/NotOnOrAfterTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/clockskew/SessionNotOnOrAfterTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/error/ErrorHandlerImplTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/error/SamlExceptionTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/impl/HandlerFactoryTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/common/CommonMockObjects.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/AuthenticatorTest.java
Labels: noproductcode, CLA Signed

#25267 Fix checkpoint tests
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/ConcurrencyTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPHealthTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPHealth/server.xml
Labels: noproductcode, CLA Signed

#25258 Test jaspic/appAuthentication with checkpoint/restore
  dev/io.openliberty.checkpoint_fat_security_oidc_social/.classpath
  dev/io.openliberty.checkpoint_fat_security_oidc_social/bnd.bnd
  dev/io.openliberty.checkpoint_fat_security_oidc_social/build.gradle
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/common/FATSuite.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/jaspic/JASPIBasicAuthenticationTest.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/jaspic/JASPIFatUtils.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/jaspic/JASPITestBase.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/oidc/OidcClientBasicTests.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/social/LibertyOP_BasicTests_oauth_usingSocialConfig.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/features/jaspicUserTestFeature-1.0.mf
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/features/jaspicUserTestFeature-2.0.mf
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/features/jaspicUserTestFeature-3.0.mf
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.jaspic11.fat/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.jaspic11.fat/jvm.options
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.jaspic11.fat/resources/security/key.jks
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.jaspic11.fat/resources/security/ltpa.keys
  dev/io.openliberty.checkpoint_fat_security_oidc_social/publish/servers/com.ibm.ws.security.jaspic11.fat/server.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBase.jar/package.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBase.jar/src/web/FlexibleBaseServlet.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/package.properties
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/resources/META-INF/MANIFEST.MF
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/resources/META-INF/permissions.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/resources/WEB-INF/ibm-web-ext.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_security_oidc_social/test-applications/JASPIBasicAuthServlet.war/src/web/JASPIBasicAuthServlet.java
Labels: noproductcode, CLA Signed

#25191 Use Maven Wrapper to run TCK FATs
  dev/.gitignore
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/jvm.options
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/StreamMonitor.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKUtilities.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/maven-wrapper.properties
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/mvnw
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/mvnw.cmd
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/settings.xml
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/test/DependencyParserTest.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#25186 Update EclipseLink 2.7.11 -> 2.7.12
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/BeanValidationExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/ConcurrencyExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/DBWSExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.nlsprops
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/query/FATSuite.java
Labels: ID review not needed, in:JPA, team:Blizzard, CLA Signed, L2 Reviewed

#25194 Upgrade jose4j to 0.9.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.jose4j/bnd.bnd
  dev/com.ibm.ws.org.jose4j/bnd.overrides
  dev/com.ibm.ws.security.fat.common.mp.jwt/fat/src/com/ibm/ws/security/fat/common/mp/jwt/sharedTests/MPJwt12MPConfigTests.java
  dev/com.ibm.ws.security.jwt/test/com/ibm/ws/security/jwt/utils/JweHelperTest.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientEncryptionTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_EncryptionTests.java
Labels: CLA Signed, team:Security SSO, release:23006

#25238 Update gradle-enterprise.init.gradle script
  dev/wlp-gradle/init-scripts/gradle-enterprise.init.gradle
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#25255 Add unit testing for testcontainers
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistry.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryImageNameSubstitutorTest.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryRegistryTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25181 25168: Close close timing window
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: in:Transport, CLA Signed, team:Sirius

#25278 Make PKCE tests use a longer read timeout
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PKCE/PKCEClientTests.java
Labels: noproductcode, CLA Signed, team:Security SSO

#25276 PR for Issue 25137: Log error and description returned in OIDC redirect
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PKCE/PKCEClientTests.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MessageConstants.java
  dev/com.ibm.ws.security.openidconnect.client/resources/com/ibm/ws/security/openidconnect/client/internal/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServlet.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
Labels: CLA Signed, team:Security SSO

#25095 Update expression language5.0 to10.1.8
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-5.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.5.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50Coercion.war/src/io/openliberty/el50/fat/coercion/servlets/lambda/EL50LambdaExpressionCoercionServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius

#25285 Remove usage of SecureRandom.getInstanceStrong from OIDC PKCE code
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchange.java
Labels: CLA Signed, team:Security SSO

#25281 persistence service updates and record-like class on Java 11
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/InMemoryMappingFile.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/PUInfoImpl.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/ClassDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipt.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
Labels: team:Zombie Apocalypse, CLA Signed

#25273 PR for Issue 25247: Do not require client secret for OIDC clients using private_key_jwt token auth method
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/OidcClientAuthenticatorTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandlerTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/internal/OidcLoginConfigImplTest.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/utils/SocialMessageConstants.java
Labels: CLA Signed, team:Security SSO

#25272 Add SOAP trace
  dev/com.ibm.ws.wsat_fat.db/publish/servers/MultiServerTest/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/ThirdServer/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATBasic/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDBDisabled_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server2/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Client/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATEJB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.multi/fat/src/tests/MultiServerTest.java
  dev/com.ibm.ws.wsat_fat.multi/test-applications/endtoend/src/web/endtoend/client/endtoend/EndToEndClientServlet.java
  dev/com.ibm.ws.wsat_fat.multi/test-applications/endtoend/src/web/endtoend/server/HelloImplTwoway.java
  dev/com.ibm.ws.wsat_fat.ssl/publish/servers/WSATSSL_Client/server.xml
  dev/com.ibm.ws.wsat_fat.ssl/publish/servers/WSATSSL_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.ssl/publish/servers/WSATSSL_Server2/server.xml
Labels: noproductcode, CLA Signed

#25256 Fix "java.lang.IllegalStateException: Subject is read-only"
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
Labels: CLA Signed, release bug

#25305 CrudRepository methods with record
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PaginatedIterator.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#25307 timer expiration can cause deadlock in proxy mode
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/ExpirationTimer.java
Labels: CLA Signed

#25225 Remove com.ibm.ws.runtime.update traces as it is no longer needed
  dev/io.openliberty.wsoc.internal_fat/publish/servers/traceTestServer/server.xml
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#25304 Register checkpoint running condition after wait for config updates
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
Labels: CLA Signed

#25284 Return correct object in JSFContainerApplicationFactory#getWrapped
  dev/com.ibm.ws.jsfContainer/src/com/ibm/ws/jsf/container/application/JSFContainerApplicationFactory.java
Labels: in:Web Components, CLA Signed, team:Sirius

#25298 Verify app providers test updates
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/CDIFlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.2/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/CDIFlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22BeanValidationTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22FlowsTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF22StatelessViewTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25290 TCK Runner improvements
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/servers/FATServer/jvm.options
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKUtilities.java
  dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#25293 Performance improvements for REST monitor / metrics scenarios
  dev/com.ibm.ws.jaxrs.2.0_fat/publish/servers/com.ibm.ws.jaxrs.fat.restmetrics/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/RestMonitorKeyCache.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMonitorKeyCache.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed, team:Performance, performance

#25324 Update eclipse related files from recent updates
  dev/com.ibm.ws.security.oidc.client_fat.3/.classpath
  dev/com.ibm.ws.security.oidc.client_fat.3/.project
  dev/com.ibm.ws.security.oidc.client_fat.3/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.classpath
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.project
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.webserver.plugin.utility_fat/.settings/org.eclipse.buildship.core.prefs
  dev/com.ibm.ws.wsat_fat.assertion/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat_fat.assertion/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat_fat.db/.classpath
  dev/com.ibm.ws.wsat_fat.ssl/.classpath
  dev/io.openliberty.data.internal.nosql/.classpath
  dev/io.openliberty.jakarta.expressionLanguage.4.0/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/.classpath
  dev/io.openliberty.org.eclipse.jnosql.1.0/.classpath
  dev/io.openliberty.org.eclipse.jnosql.1.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.jnosql.1.0/.settings/org.eclipse.jdt.core.prefs
Labels: noproductcode, CLA Signed, team:Performance

#24714 Enable @FormParam for EntityParts
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
  dev/io.openliberty.org.jboss.resteasy.server.ee10/src/com/ibm/websphere/jaxrs/server/IBMRestServlet.java
  dev/io.openliberty.org.jboss.resteasy.server.ee10/src/io/openliberty/org/jboss/resteasy/server/component/RESTfulServletContainerInitializer.java
  dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartResource.java
  dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartTestServlet.java
  dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/Util.java
Labels: CLA Signed

#25208 Update acme project to use jose4j 0.9.3 from 0.6.5
  dev/com.ibm.ws.security.acme/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
Labels: CLA Signed, team:Core Security, target:23006, release:23006

#25318 Handle toString exception when trace statement includes {0
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceFormatter.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/internal/impl/BaseTraceFormatterTest.java
Labels: CLA Signed, team:Performance

#25322 BCL FAT updates for iSeries
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25325 Apply lowercase conversion to checkpoint argument
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/LaunchArguments.java
Labels: CLA Signed

#25315 Fix clientSecret checks for OIDC in social login
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
Labels: CLA Signed, team:Security SSO

#25331 Issue 19029: Add disabled option for PKCE in OIDC client
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ClientConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed, team:Security SSO

#25300 removed synchronized from invalideTU method in TransactionUserWrapper
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/tu/TransactionUserWrapper.java
Labels: CLA Signed, release bug

#25320 Convert logging to use DateTimeFormatter
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/DataFormatHelper.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/BurstDateFormat.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonHelpers.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorJsonUtils_JSON.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/DateFormatHelper.java
  dev/com.ibm.ws.logging_test/test/com/ibm/ws/logging/collector/BurstDateFormatterTest.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/source/AccessLogSource.java
Labels: CLA Signed, team:Performance, performance

#25326 Defer tx recovery until restore config updates complete
  dev/com.ibm.ws.transaction/bnd.bnd
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TransactionManagerService.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionLogTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionManagerTest.java
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/server.xml
Labels: CLA Signed

#25339 Use Artifactory as an additional mvn repository
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/settings.xml
Labels: noproductcode, CLA Signed
