Repository OpenLiberty/open-liberty, pull requests merged in 2023-10, with the labels that each got.

#26442 Fix telemetry misconfig test
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
Labels: noproductcode, CLA Signed

#26429 Handle trace rollover in multi server peer recovery reroute tests
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/fat/src/tests/ReroutePeerRecoveryTest.java
Labels: noproductcode, CLA Signed

#26415 Avoid deadlock in WSAT recovery
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogFileHeader.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoverableUnitSectionImpl.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATTransaction.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/HandlerImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/RegistrationImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/CoordinatorFactoryService.java
Labels: CLA Signed

#26456 example of build compatible extension for Jakarta Data provider
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/CompositeBeanCreator.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/CompositeBuildCompatibleExtension.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/CompositeRepository.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/web/ProviderTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26469 Wait for FFDC in JDBC FAT
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/DataSourceTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:JDBC/JCA

#26379 Update the shared class cache URL used for non jar / zip files.
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
Labels: CLA Signed, team:Performance

#26466 should not try to send bcl requests if no bcl uri is setup
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelperTest.java
Labels: CLA Signed

#25897 Update expression language50 to10.1.11
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-5.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.5.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius

#26333 Set args to null in event of exception to avoid calling onMessage
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/LinkRead.java
Labels: in:Web Components, CLA Signed, team:Sirius

#26420 26419 - avoid tracing CacheControlHeaderProvider
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
Labels: in:JAX-RS, CLA Signed

#26476 Set MinimumJavaLevel for Faces40CDISessionPersistence class
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/faces40/Faces40CDISessionPersistence.java
Labels: noproductcode, CLA Signed

#26468 JPA Postgres and Consul error message
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseManager.java
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestService.java
Labels: CLA Signed

#26486 PR for Issue 26453: Clarify jwtBuilder expiresInSeconds description
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, team:Security SSO

#26506 Fixed computed metrics when mp_app tag is used in MpMetrics-5.0
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/bnd.bnd
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/computed/internal/ComputedMonitorMetrics.java
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/computed/internal/ComputedMonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/internal/MonitorMetrics.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#26462 Update ASM to 9.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
Labels: team:Zombie Apocalypse, CLA Signed, Java 22

#26511 query annotation using method parameter names
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/CompositeBuildCompatibleExtension.java
Labels: team:Zombie Apocalypse, CLA Signed

#26421 Enable H2 SSL tests
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2SecureTests.java
Labels: in:Transport, in:Web Components, noproductcode, CLA Signed, team:Sirius

#26514 Update SmallRye Metrics to 5.1.0-RC2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
Labels: CLA Signed

#26464 Use entire expire time to wait for lock on console.log
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessControlHelper.java
Labels: CLA Signed

#26530 Update comment in CDIExtensionMetadata
  dev/com.ibm.ws.cdi.interfaces/src/io/openliberty/cdi/spi/CDIExtensionMetadata.java
Labels: CLA Signed

#26526 update StaticMetamodel to latest from spec
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/AttributeInfoImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/BeanDefiningAnnotationMetadata.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/House_.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CityAttrNames1.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CityAttrNames2.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/EntityModelUnknown_.java
  dev/io.openliberty.jakarta.data.1.0/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/model/Attribute.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/model/AttributeInfo.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/model/StaticMetamodel.java
Labels: team:Zombie Apocalypse, CLA Signed

#26524 Updated Computed Metrics FAT to wait for server config and clean up
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/files/server_monitorFilter5.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/files/server_monitorFilter6.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/files/server_monitorFilter7.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/files/server_monitorFilter8.xml
Labels: noproductcode, CLA Signed

#26441 Fix ltpa validation keys directory monitoring
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/LTPAFileMonitor.java
  dev/com.ibm.websphere.security/src/com/ibm/ws/security/filemonitor/SecurityFileMonitor.java
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
Labels: CLA Signed, team:Core Security

#26470 Servicablity - Add logging to indicate reasons for return code 21 on server stop
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/ProcessControlHelper.java
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
Labels: ID reviewed, CLA Signed, L2 Reviewed

#26531 Skip LastExecutionTests and TriggerTests for Jakarta EE 10
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/FATSuite.java
Labels: noproductcode, CLA Signed

#26537 Issue #11533: Test EJB remote feature dynamic updates
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.project
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/fat/src/com/ibm/ws/ejbcontainer/remote/config/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/fat/src/com/ibm/ws/ejbcontainer/remote/config/fat/tests/RebindConfigUpdateTest.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server.ssl/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server.ssl/resources/security/key.jks
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server.ssl/resources/security/ltpa.keys
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server.ssl/server.xml
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.config.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsLocalBusiness.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsLocalEJB.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsLocalHome.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsRemoteBusiness.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsRemoteEJB.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/ConfigTestsTestBean.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/JavaColonLookupBean.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/JavaColonLookupLocalEJB.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsEJB.jar/src/com/ibm/ws/ejbcontainer/remote/configtests/ejb/JavaColonLookupLocalHome.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/RebindConfigUpdateServlet.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarLocalBusiness.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarLocalEJB.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarLocalHome.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarRemoteBusiness.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarRemoteEJB.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarRemoteHome.java
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/test-applications/ConfigTestsWeb.war/src/com/ibm/ws/ejbcontainer/remote/configtests/web/ejb/ConfigTestsWarTestBean.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test debt

#26271 Add gradle repo to buildDepScanner
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
  dev/build.depScanner/src/io/openliberty/depScanner/Jar.java
  dev/build.depScanner/src/io/openliberty/depScanner/Module.java
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#26504 add additional trace to the JAXRS21ClientCXFRxInvokerTest
  dev/com.ibm.ws.jaxrs.2.1.client_fat/test-applications/jaxrs21bookstore/src/com/ibm/ws/jaxrs21/fat/JAXRS21bookstore/CXFRxInvokerTestServlet.java
Labels: noproductcode, CLA Signed

#26024 Repeat el fats with el60 feature
  dev/com.ibm.ws.el.3.0_fat/bnd.bnd
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/ELUtils.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL22OperatorsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30CoercionRulesTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30LambdaExpressionsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30ListCollectionObjectOperationsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30MethodExpressionInvocationsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30MiscTests.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30OperatorPrecedenceTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30OperatorsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30ReservedWordsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30StaticFieldsAndMethodsTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30VarargsMethodMatchingTest.java
  dev/com.ibm.ws.el.3.0_fat/publish/servers/elServer/bootstrap.properties
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/src/com/ibm/ws/el30/fat/servlets/EL30InvocationMethodExpressionsServlet.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/ELUtils.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50ArrayCoercionTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50BasicTests.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50DefaultMethodsTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50LambdaExpressionCoercionTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50MethodReferenceTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50BasicTests.war/src/io/openliberty/el50/fat/basic/servlets/EL50BasicTestsServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26545 Remove SkipForRepeat now that Yasson version is updated
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/test-applications/ifaceApp/src/mpGraphQL10/iface/InterfaceTestServlet.java
Labels: noproductcode, CLA Signed, team:Performance

#26513 JAX-WS: bootstrap.properties replacement is refactored
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/LibertyCXFPositivePropertiesTest.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#26550 Revert "edit docs for include server.xml tag"
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/SchemaData.nlsprops
Labels: CLA Signed

#26389 Fix MYFACES-4628
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/bugfixes/MyFaces4628Test.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4628/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4628/osgi.debug.options
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4628/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4628.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4628.war/resources/test.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4628.war/src/io/openliberty/org/apache/faces40/fat/myfaces4628/bean/SelectBean.java
Labels: in:Web Components, team:Sirius

#26356 Update ECJ/JDT to 3.35/4.29 for Java 21 Support in JSP/Pages
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.eclipse.jdt.core.java17/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#26475 Increase some test timeouts
  dev/com.ibm.ws.jaxws.wsat/src/com/ibm/ws/wsat/policy/WSATPolicyAwareInterceptor.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TransactionManagerService.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATEndpoint.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATTransaction.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/WSATContext.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WSATConfigServiceImpl.java
  dev/com.ibm.ws.wsat.migration_fat.1/test-applications/simpleClient/src/web/simpleclient/SimpleClientServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/test-applications/recoveryClient/src/client/MultiRecoverySetupServlet.java
  dev/com.ibm.ws.wsat.webservice/src/com/ibm/ws/wsat/interceptor/WSATInterceptorServiceImpl.java
Labels: CLA Signed

#26546 Extra diagnostics for timeout tests
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/RemoteTransactionControllerService.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WSATConfigServiceImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WebClientImpl.java
  dev/com.ibm.ws.wsat.migration_fat.3/fat/src/tests/SleepTest.java
Labels: CLA Signed

#26543 Enable localConnector-1.0 for InstantOn
  dev/com.ibm.websphere.appserver.features/visibility/public/localConnector-1.0/com.ibm.websphere.appserver.localConnector-1.0.feature
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/com.ibm.ws.jmx.fat.jmxtest.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LocalConnectorTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/jmx/LocalConnector.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/jmx/package-info.java
  dev/io.openliberty.checkpoint_fat/publish/features/jmxtest-1.0.mf
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointLocalConnector/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointLocalConnector/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointLocalConnector/server.xml
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/Messages.properties
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/ServerConnector.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/TestBean.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/TestBean1.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/TestBean2.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test-mbeans/src/com/ibm/ws/jmx/test/fat/package-info.java
Labels: CLA Signed

#26477 Initial Faces 5.0 FAT
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.project
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.myfaces.5.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.myfaces.5.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.5.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.5.0_fat/fat/src/io/openliberty/org/apache/myfaces50/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.5.0_fat/fat/src/io/openliberty/org/apache/myfaces50/fat/JSFUtils.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26570 insert annotation returns entity
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
Labels: team:Zombie Apocalypse, CLA Signed

#26572 Fix up Java and eclipse settings
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/io.openliberty.microprofile.reactive.messaging.3.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.reactive.messaging.3.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee11/bnd.bnd
Labels: CLA Signed, team:Performance

#26552 Update Java specific FATs to handle JAR or WAR files
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 21

#26571 Updaet to SmallRye Metrics 5.1.0-RC3 and disable optional test until …
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: CLA Signed

#26508 Run ConfigRefresher.changesEnded in multi-threaded checkpoint hook
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigRefresher.java
Labels: CLA Signed

#26555 Initial drop of concurrency reactive bucket and first test using Flow
  dev/com.ibm.ws.concurrent_fat_reactive/.classpath
  dev/com.ibm.ws.concurrent_fat_reactive/.project
  dev/com.ibm.ws.concurrent_fat_reactive/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent_fat_reactive/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent_fat_reactive/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent_fat_reactive/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent_fat_reactive/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_reactive/fat/src/com/ibm/ws/concurrent/fat/reactive/ConcurrentReactiveTest.java
  dev/com.ibm.ws.concurrent_fat_reactive/fat/src/com/ibm/ws/concurrent/fat/reactive/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_reactive/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_reactive/publish/servers/FATServer/server.xml
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ConcurrentReactiveServlet.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadPublisher.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadSnapshot.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadSubscriber.java
Labels: noproductcode, CLA Signed

#26579 wlp-docgen.jar is not shipped and should be filtered from scan
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#26575 Issue #26574: Improve CNTR0047E
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/MessageDrivenBeanO.java
  dev/com.ibm.ws.ejbcontainer.mdb.core/src/com/ibm/ws/ejbcontainer/mdb/BMMessageDrivenBeanO.java
  dev/com.ibm.ws.ejbcontainer.mdb.core/src/com/ibm/ws/ejbcontainer/mdb/CMMessageDrivenBeanO.java
Labels: team:Zombie Apocalypse, in:EJB Container, CLA Signed, serviceability

#26586 Wait for config update in concurrent persistent FAT
  dev/com.ibm.ws.concurrent.persistent_fat_compatibility/fat/src/com/ibm/ws/concurrent/persistent/fat/compatibility/FatTestConcurrentCompatible.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#26564 Wait for interrupt in JDBC FAT
  dev/com.ibm.ws.jdbc_fat/test-applications/basicfat/src/basicfat/DataSourceTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:JDBC/JCA

#26285 Remove unused classes (jsp tools) from the JSP Impl
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/TagLibraryCache.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/tools/AbstractJspModC.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/tools/FileBasedJspContext.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/tools/JspFileUtils.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/utils/JspTranslatorUtil.java
  dev/com.ibm.ws.jsp/src/com/ibm/wsspi/jsp/tools/JspTools.java
  dev/com.ibm.ws.jsp/src/com/ibm/wsspi/jsp/tools/JspToolsFactory.java
  dev/com.ibm.ws.jsp/src/com/ibm/wsspi/jsp/tools/JspToolsFactoryHelper.java
  dev/com.ibm.ws.jsp/src/com/ibm/wsspi/jsp/tools/JspToolsOptionKey.java
  dev/com.ibm.ws.jsp/src/com/ibm/wsspi/jsp/tools/JspToolsOptionsMap.java
Labels: in:Web Components, CLA Signed, team:Sirius

#26566 Enable instant on for jaxws/xmlws and repeat tests for EE9 and EE10
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-4.0/io.openliberty.xmlWS-4.0.feature
  dev/com.ibm.ws.jaxws.ejb_fat/fat/src/com/ibm/ws/jaxws/ejb/fat/EJBWSBasicTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/jaxWSVirtualHost/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/jaxWSVirtualHost/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/bnd.bnd
  dev/io.openliberty.checkpoint_fat_xmlws/fat/src/io/openliberty/checkpoint/jaxws/fat/EJBWSBasicTest.java
  dev/io.openliberty.checkpoint_fat_xmlws/fat/src/io/openliberty/checkpoint/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/io.openliberty.checkpoint_fat_xmlws/fat/src/io/openliberty/checkpoint/jaxws/fat/WebServiceRefTest.java
  dev/io.openliberty.checkpoint_fat_xmlws/fat/src/io/openliberty/checkpoint/jaxws/suite/FATSuite.java
  dev/io.openliberty.checkpoint_fat_xmlws/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/EJBWSBasicServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/EJBWSBasicServer/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/LibertyCXFPositivePropertiesTestServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/LibertyCXFPositivePropertiesTestServer/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/WebServiceRefTestServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/WebServiceRefTestServer/jvm.options
Labels: CLA Signed

#26397 Share JSP 2.3, 3.0, & 3.1 org.apache.jasper & factory code
  dev/cnf/build.bnd
  dev/com.ibm.ws.jsp.2.3/README.txt
  dev/io.openliberty.pages.3.1.internal.factories/bnd.bnd
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/translator/visitor/generator/GeneratorUtilsExtFactoryImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/translator/visitor/generator/GeneratorUtilsExtImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/translator/visitor/validator/ELValidatorExtImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/translator/visitor/validator/ElValidatorExtFactoryImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/webcontainerext/ws/PrepareJspHelper23.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/webcontainerext/ws/PrepareJspHelper23Factory.java
  dev/io.openliberty.pages.3.1.internal.factories/src/com/ibm/ws/pages31/webcontainerext/ws/package-info.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/JasperException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/ELContextImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/ELContextWrapper.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/ExpressionEvaluatorImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/ExpressionImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/FunctionMapperImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspELException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspMethodExpression.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspMethodNotFoundException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspPropertyNotFoundException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspPropertyNotWritableException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/JspValueExpression.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/el/VariableResolverImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/BodyContentImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/HttpJspBase.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JcdiWrappedJspApplicationContextImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JcdiWrappedJspFactoryImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspApplicationContextImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspException.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspFactoryImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspFragmentHelper.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspRuntimeLibrary.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspWriterImpl.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/PerThreadTagHandlerPool.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/ProtectedFunctionMapper.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/ServletResponseWrapperInclude.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/TagHandlerPool.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/package-info.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/packageinfo
Labels: in:Web Components, team:Sirius

#26592 upgrade netty libraries to 4.1.100
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: CLA Signed, team:Sirius, target:230011, release:230011

#26595 Update annotation on method with entity results
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
Labels: team:Zombie Apocalypse, CLA Signed

#26598 Update deps for MP Metrics 5.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.metrics-5.1.feature
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/metrics.5.1.bnd
Labels: CLA Signed

#26606 Removing Docgen jar from scanning
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#26548 Improve use of WSContextService in MP Reactive Streams Operators 3.0
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveConcurrentWorkTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveJaxRSTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsContextTest.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/bnd.bnd
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/resources/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/LibertyExecutionModel.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/LibertyReactiveStreamsEngineImpl.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/RsoContextExecutor.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/StreamRunner.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/StreamTask.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/AbstractReactiveUnitTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/SetInstanceTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/TestExecutionModel.java
Labels: CLA Signed

#26588 Initial checkin jms FAT to checkpoint/restore
  dev/io.openliberty.checkpoint_fat_jms/.classpath
  dev/io.openliberty.checkpoint_fat_jms/.gitignore
  dev/io.openliberty.checkpoint_fat_jms/.project
  dev/io.openliberty.checkpoint_fat_jms/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_jms/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_jms/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_jms/bnd.bnd
  dev/io.openliberty.checkpoint_fat_jms/build.gradle
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpClientTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpEngineTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpClientTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpEngineTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/DummyTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/TestUtils.java
  dev/io.openliberty.checkpoint_fat_jms/publish/files/Lite1Client.xml
  dev/io.openliberty.checkpoint_fat_jms/publish/files/Lite1Engine.xml
  dev/io.openliberty.checkpoint_fat_jms/publish/files/Lite2Client.xml
  dev/io.openliberty.checkpoint_fat_jms/publish/files/Lite2Engine.xml
  dev/io.openliberty.checkpoint_fat_jms/publish/files/features/testjmsinternals-1.0.mf
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet1Client/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet1Engine/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet2Client/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet2Engine/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSConsumer_118076/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSConsumer_118076/src/jmsconsumer_118076/web/JMSConsumer_118076Servlet.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSConsumer_118077/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSConsumer_118077/src/jmsconsumer_118077/web/JMSConsumer_118077Servlet.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSContextInject/resources/WEB-INF/beans.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSContextInject/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSContextInject/src/jmscontextinject/ejb/JMSDefinitionBean.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSContextInject/src/jmscontextinject/ejb/SampleSecureStatelessBean.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSContextInject/src/jmscontextinject/web/JMSContextInjectServlet.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSMBeans/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSMBeans/src/jmsmbeans/web/JMSMBeanTestServlet.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSProducer/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSProducer/src/jmsproducer/web/JMSProducerServlet.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSProducer_118073/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/JMSProducer_118073/src/jmsproducer_118073/web/JMSProducer_118073Servlet.java
Labels: noproductcode, CLA Signed

#26611 26610 mdb in bean discovery none archive
  dev/com.ibm.ws.cdi.ejb_fat/bnd.bnd
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/ejbdiscovery/ejbs/interfaces/StatelessLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/ejbdiscovery/none/UndiscoveredStatelessBean.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/ejbdiscovery/none/UndiscoveredStatelessLocal.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/ejbdiscovery/servlet/DiscoveryServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbTestEar/jar/JarMdb.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbTestEar/jarNoBeanDiscovery/JarMdbNotDiscovered.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbTestEar/jarNoBeanDiscovery/beans.xml
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbTestEar/lib/EarTestMessageHolder.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbTestEar/war/EarMdbTestServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbWar/BasicMdb.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbWar/BasicMdbTestServlet.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/mdbWar/TestMessageHolder.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/EjbDiscoveryTest.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/FATSuite.java
  dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/tests/MdbTest.java
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12MdbServer/bootstrap.properties
  dev/com.ibm.ws.cdi.ejb_fat/publish/servers/cdi12MdbServer/server.xml
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/inject/InjectInjectionObjectFactory.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIEJBManagedObjectFactoryImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/BeanDeploymentArchiveImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/JndiHelperComponentMetaData.java
Labels: CLA Signed

#26625 match the spec API for BasicRepository
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#26624 lifecycle methods that return records
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebate.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebates.java
  dev/io.openliberty.data.internal_fat_validation/publish/servers/io.openliberty.data.internal.fat.validation/bootstrap.properties
Labels: team:Zombie Apocalypse, CLA Signed

#26627 Fix config updates in RAR BeanValidation FAT
  dev/com.ibm.ws.jca_fat_regr.rar.beanVal/fat/src/suite/r80/base/jca16/jbv/RarBeanValidationTest11.java
  dev/com.ibm.ws.jca_fat_regr.rar.beanVal/fat/src/suite/r80/base/jca16/jbv/RarBeanValidationTest20.java
  dev/com.ibm.ws.jca_fat_regr.rar.beanVal/fat/src/suite/r80/base/jca16/jbv/RarBeanValidationTestCommon.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:JDBC/JCA

#26613 Tidy competeForLog test
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
Labels: noproductcode, CLA Signed

#26589 Update EclipseLink ASM to 9.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed, Java 22

#26629 Update to SmallRye Metrics 5.1.0 final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
Labels: CLA Signed

#26635 test lifecycle methods returning array and iterables of records
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebates.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26630 Added permission to the server.xml for the JPAConfigServer.
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/publish/servers/JPAConfigServer/server.xml
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#26639 Prevent Derby Dual Boot in com.ibm.ws.concurrent.persistent.fat
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/PersistentExecutorWithFailoverEnabledTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#26638 Update Jakarta EE 11 features and test framework to require Java 21
  dev/build.example_fat/fat/src/com/ibm/ws/example/FATSuite.java
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.1/io.openliberty.concurrent-3.1.feature
  dev/com.ibm.ws.ejbcontainer.remote.config_fat/fat/src/com/ibm/ws/ejbcontainer/remote/config/fat/tests/RebindConfigUpdateTest.java
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EmptyAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE11Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatActions.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
Labels: CLA Signed, team:Performance

#26567 Run patched JSON-B TCK for z/OS testing
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/fat/src/io/openliberty/jakarta/jsonb/tck/JsonbTckLauncher.java
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/publish/tckRunner/tck/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26621 Heartbeat Synchronization
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#26653 Update EE 11 FATs to use Java 21
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/bnd.bnd
  dev/io.openliberty.pages.4.0.internal_fat/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance

#26647 Reinstate null DataSourceFactory service ref check in JTMConfiguratio…
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: CLA Signed

#26652 Fixed ClassCastException in Computed Metrics code for MP Metrics
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/computed/internal/ComputedMonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/computed/ComputedMonitorMetricsHandler.java
Labels: CLA Signed

#26661 Missed EE 11 FAT to update to Java 21
  dev/io.openliberty.org.apache.myfaces.5.0_fat/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance

#26644 Minor updates to JWT NLS messages
  dev/com.ibm.ws.security.jwt/resources/com/ibm/ws/security/jwt/internal/resources/JWTMessages.nlsprops
Labels: CLA Signed, team:Security SSO, ID waiting on development

#26593 Run RSO 3.0 streams synchronously by default
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-3.0/io.openliberty.mpReactiveStreams-3.0.feature
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/context/ReactiveStreamsContextTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsContextTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/bnd.bnd
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/resources/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/LibertyExecutionModel.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/RsoContextExecutor.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/package-info.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/CompletionStageTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/TestExecutionModel.java
Labels: CLA Signed

#26668 Fixed the computed REST Elapsed Time metric calculation
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/computed/internal/ComputedMonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/computed/ComputedMonitorMetricsHandler.java
Labels: CLA Signed

#26601 Use Charset instead of charset name in order to remove bottlenecks
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/hpack/H2Headers.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/hpack/HpackConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/EncodingUtils.java
Labels: CLA Signed, team:Performance, performance

#26671 changed tracepoints in SipLogExtension, SipApplicationSessionImpl
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/SipApplicationSessionImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/util/SipLogExtension.java
Labels: CLA Signed

#26667 fix timing issue in rollover test
  dev/com.ibm.ws.logging_2_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
Labels: noproductcode, CLA Signed

#26677 Allow checkpoint when java 2 security manager configured on JVM18+
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointWithSecurityManager.java
Labels: CLA Signed

#26679 mixed JPA entities on a repository
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employees.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/MixedRepository.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Unpopulated.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26584 Remove beta fencing for HTTP request tracing
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/TelemetryAgent/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingZipkinServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureTelemetryServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/spanTestServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletContainerInitializer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10JaxWithConcurrency/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10JaxWithConcurrency/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MisConfig/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Servlet/jvm.options
Labels: CLA Signed

#26673 Clean up bnd and remove unnecessary repeat
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/JSFUtils.java
  dev/io.openliberty.org.apache.myfaces.5.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.5.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.5.0_fat/fat/src/io/openliberty/org/apache/myfaces50/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.5.0_fat/fat/src/io/openliberty/org/apache/myfaces50/fat/JSFUtils.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26409 runtime update to support specifying signatureAlgorithm config option with older schema
  dev/com.ibm.ws.wssecurity.3.4.1/bnd.bnd
  dev/com.ibm.ws.wssecurity.3.4.1/build.gradle
  dev/com.ibm.ws.wssecurity.3.4.1/src/com/ibm/ws/wssecurity/signature/SignatureAlgorithms.java
  dev/com.ibm.ws.wssecurity.3.4.1/test/com/ibm/ws/wssecurity/signature/SignatureAlgorithmsTest.java
Labels: CLA Signed

#26695 Update ConcurrentCDITest to use minimum java level 21
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#26666 Initial Servlet 6.1 FAT
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.project
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/build.gradle
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26697 Fix ConfigTest.traceTest while running on Oracle
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#26626 Update to hold WeakReference to Thread in JVMInterruptObject and add JUnit Test
  dev/com.ibm.ws.request.interrupt/.classpath
  dev/com.ibm.ws.request.interrupt/bnd.bnd
  dev/com.ibm.ws.request.interrupt/src/com/ibm/ws/request/interrupt/internal/InterruptibleThreadInfrastructureImpl.java
  dev/com.ibm.ws.request.interrupt/src/com/ibm/ws/request/interrupt/internal/InterruptibleThreadObject.java
  dev/com.ibm.ws.request.interrupt/src/com/ibm/ws/request/interrupt/internal/JVMInterruptObject.java
  dev/com.ibm.ws.request.interrupt/test/com/ibm/ws/request/interrupt/internal/WeakReferenceThreadsTest.java
Labels: CLA Signed

#26706 Initialize single instance of repository just once
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
Labels: team:Zombie Apocalypse, CLA Signed

#26707 remove async send timeToLive test
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS1AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS1AsyncSend.java
Labels: noproductcode, CLA Signed

#26701 Flow.Subscriber proxy test and onError/onComplete testing
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ConcurrentReactiveServlet.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadProcessor.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadPublisher.java
  dev/com.ibm.ws.concurrent_fat_reactive/test-applications/reactiveapp/src/reactiveapp/web/ThreadSubscriber.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#26715 http request telemetry perf improvement
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
Labels: CLA Signed

#26712 Reduce trace in EJB Checkpoint FAT
  dev/io.openliberty.ejbcontainer.checkpoint_fat/publish/servers/EjbStartCheckpointMockServer/bootstrap.properties
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#26704 Ltpa fixes
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAToken2.java
Labels: CLA Signed, team:Core Security

#26662 Remove beta guards for new computed metrics for MP Metrics 3.0, 4.0, and 5.0
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/bnd.bnd
  dev/io.openliberty.microprofile.metrics.5.0.monitor.internal/src/io/openliberty/microprofile/metrics/internal/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.3.0.monitor/src/io/openliberty/microprofile/metrics/internal/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/ComputedMetricsServer/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/ComputedMetricsServer/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/ComputedMetricsServer/jvm.options
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#26716 Fix Jakarta Data messaging issues
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_cs.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_de.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_es.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_fr.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_hu.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_it.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_ja.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_ko.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_pl.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_pt_BR.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_ro.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_ru.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_zh.nlsprops
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages_zh_TW.nlsprops
Labels: team:Zombie Apocalypse, ID review not needed, CLA Signed

#26738 26737: Relax ConnectionPoolStats abortConnections Test Timing
  dev/com.ibm.ws.jca_fat_mbean/test-applications/fvtweb/src/web/ConnectionPoolStatsServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:JDBC/JCA

#26720 Added doPrivileged for setAccessible when parsing JPQL query with EXT…
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/jpa/jpql/parser/AbstractExpression.java
Labels: in:JPA, team:Blizzard, CLA Signed

#26554 Make quiesce timeout configurable
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerEnvTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStopTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/Utils.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.serverstart.fat/jvm.options
  dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/RuntimeUpdateManagerImpl.java
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.threading/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/ThreadQuiesce.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/test/com/ibm/ws/threading/internal/ExecutorServiceImplTest.java
Labels: ID reviewed, CLA Signed

#26743 Revert "Remove beta fencing for HTTP request tracing"
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/TelemetryAgent/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureOpenTracingZipkinServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/crossFeatureTelemetryServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/publish/servers/spanTestServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletContainerInitializer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Jax/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10JaxWithConcurrency/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10JaxWithConcurrency/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10MisConfig/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10Servlet/jvm.options
Labels: CLA Signed

#26745 Notices for 23.0.0.11
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#26729 Redeliver: Run RSO 3.0 streams synchronously by default
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-3.0/io.openliberty.mpReactiveStreams-3.0.feature
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/context/ReactiveStreamsContextTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.streams.operators_fat/fat/src/com/ibm/ws/microprofile/reactive/streams/test/suite/ReactiveStreamsContextTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/bnd.bnd
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/resources/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/LibertyExecutionModel.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/RsoContextExecutor.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/src/io/openliberty/microprofile/reactive/streams/operators30/spi/impl/package-info.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/META-INF/services/io.smallrye.mutiny.jakarta.streams.spi.ExecutionModel
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/CompletionStageTest.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal/test/src/io/openliberty/microprofile/reactive/streams/test/TestExecutionModel.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/fat/src/io/openliberty/microprofile/reactive/streams/operators30/tck/FATSuite.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/fat/src/io/openliberty/microprofile/reactive/streams/operators30/tck/ReactiveStreams30TCKLauncher.java
  dev/io.openliberty.microprofile.reactive.streams.operators30.internal_fat_tck/publish/servers/ReactiveStreams30TCKServer/server.xml
Labels: CLA Signed

#26684 set thread context metadata for startup event
  dev/com.ibm.ws.cdi.internal/resources/com/ibm/ws/cdi/internal/resources/CDI.nlsprops
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/ApplicationImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/CDIArchiveImpl.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/Application.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIRuntime.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/ContextBeginnerEnder.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/AbstractCDIRuntime.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/injection/EEValidationUtils.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/ContextBeginnerEnderImpl.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/FATSuite.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/ear/ejb/EjbApplicationScopedBean.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/AbstractObserver.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/JNDILookupBean.java
Labels: ID Required, ID reviewed, CLA Signed

#26541 Add FAT tests for OpenAPI with CORS
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/OpenAPICorsTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/CorsServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/CorsServer/server.xml
Labels: noproductcode

#26749 Prevent tran timeout in NextTimeoutServlet timer waits
  dev/com.ibm.ws.ejbcontainer.timer.calendar_fat/test-applications/TimerCalTestEJB.jar/src/com/ibm/ws/ejbcontainer/timer/cal/ejb/NextTimeoutBean.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#26741 replace liberty Update annotation
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Shipments.java
  dev/io.openliberty.data.internal_fat_jpa/build.gradle
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Count.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Exists.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Filter.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Operation.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Select.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Update.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Add.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Assign.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Divide.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Multiply.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/SubtractFrom.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/package-info.java
Labels: team:Zombie Apocalypse, CLA Signed

#26753 Add CONSTRUCTOR target to InjectedTrace annotation
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/annotation/InjectedTrace.java
Labels: CLA Signed, team:Performance

#26752 set useSeparateSessionInvalidatorThreadPool property to false in the metrics monitor FATS
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF1/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF10/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF11/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF12/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF2/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF3/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF4/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF5/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF6/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF8/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/MetricsMonitorServer/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF1/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF10/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF11/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF12/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF2/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF3/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF4/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF5/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF6/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF8/serverConfig.xml
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF9/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/ComputedMetricsServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/MetricsMonitorServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF10/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF11/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF2/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF3/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF4/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF5/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF6/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF8/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF9/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/ComputedMetricsServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/MetricsMonitorServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF10/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF11/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF2/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF3/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF4/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF5/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF6/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF8/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF9/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/ComputedMetricsServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/MetricsMonitorServer/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF10/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF11/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF2/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF3/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF4/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF5/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF6/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF8/serverConfig.xml
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF9/serverConfig.xml
Labels: noproductcode, CLA Signed

#26730 Update LibertyRuntimeTransformer and tests
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava11.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava17.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava21.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava6.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava7.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava7StaticInit.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava8.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava8Lambdas.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava8StaticInit.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/HelloWorldJava8StaticLambdas.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/example/bytecode/README.md
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
  dev/com.ibm.ws.ras.instrument_test/test/test data/com/ibm/example/bytecode/HelloWorldJava11.class
  dev/com.ibm.ws.ras.instrument_test/test/test data/com/ibm/example/bytecode/HelloWorldJava17.class
  dev/com.ibm.ws.ras.instrument_test/test/test data/com/ibm/example/bytecode/HelloWorldJava21.class
Labels: team:Zombie Apocalypse, CLA Signed

#26742 Release peer locks following peer recovery
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
Labels: CLA Signed

#26728 Add fast.ack option to Kafka Reactive Messaging Connector
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaConnectorConstants.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaInput.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaPostProcessReceptionBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestConsumer.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/LivePartitionTestSubscriberMethodBean.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/KafkaPublisherVerification.java
  dev/io.openliberty.microprofile.reactive.messaging.3.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.reactive.messaging.3.0.internal/resources/OSGI-INF/wlp/defaultInstances.xml
Labels: CLA Signed

#26740 Allow users to configure Microprofile Rest Client 2.0 with the follow…
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
Labels: CLA Signed, in:MicroProfile/RestClient

#26756 server config update SHA to SHA256 cipher for FIPS
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MatchingSSLCiphersTest/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MisMatchingSSLCiphersTest/server.xml
Labels: noproductcode, CLA Signed

#26751 Update to use ReentrantLock instead of synchronized
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
Labels: CLA Signed, team:Performance, performance

#26702 Update MP Config 3.1 Dependencies
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/mpConfig-3.1/io.openliberty.mpConfig-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-3.0/io.openliberty.mpReactiveStreams-3.0.feature
  dev/io.openliberty.io.smallrye.common2/.classpath
  dev/io.openliberty.io.smallrye.common2/.project
  dev/io.openliberty.io.smallrye.common2/.settings/bndtools.core.prefs
  dev/io.openliberty.io.smallrye.common2/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.smallrye.common2/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.smallrye.common2/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.io.smallrye.common2/bnd.bnd
  dev/io.openliberty.io.smallrye.config3/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-api4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/bnd.bnd
  dev/io.openliberty.microprofile.config.3.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/config.3.1.bnd
Labels: CLA Signed

#26392 Remove Jsp's packageinfo from org/apache/jasper/runtime/ package
  dev/com.ibm.ws.jsp.2.3/bnd.bnd
  dev/com.ibm.ws.jsp.2.3/src/org/apache/jasper/runtime/package-info.java
  dev/com.ibm.ws.jsp.2.3/src/org/apache/jasper/runtime/packageinfo
Labels: in:Web Components, team:Sirius

#26764 Fix test failure caused by PR 26601
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/EncodingUtils.java
  dev/com.ibm.ws.webcontainer/test/com/ibm/ws/webcontainer/webapp/SRTServletRequestTest.java
Labels: CLA Signed, team:Performance

#26708 Initial WebSocket 2.2 FAT
  dev/io.openliberty.wsoc.2.2.internal_fat/.classpath
  dev/io.openliberty.wsoc.2.2.internal_fat/.project
  dev/io.openliberty.wsoc.2.2.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.wsoc.2.2.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.wsoc.2.2.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.wsoc.2.2.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.wsoc.2.2.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.2.2.internal_fat/build.gradle
  dev/io.openliberty.wsoc.2.2.internal_fat/fat/src/io/openliberty/wsoc22/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26762 Retry getBackendURL if lease is locked
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/XidImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/ws/Transaction/JTS/Configuration.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
Labels: CLA Signed

#26758 Update parallel classloader locking for Liberty classloaders
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/LibertyLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/providers/WeakLibraryListener.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/KeyBasedLockStore.java
Labels: team:Performance, performance

#26770 Double config update timeout for slow machines
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/fat/src/com/ibm/ws/concurrent/persistent/fat/initial/polling/InitialPollingTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency
