Repository OpenLiberty/open-liberty, pull requests merged in 2023-04, with the labels that each got.

#24911 Add permissions for Custom UserRegistry running as a Bell
  dev/com.ibm.ws.security.wim.registry_fat/publish/servers/com.ibm.ws.security.wim.registry.fat.FederateStandaloneCurBell/server.xml
Labels: noproductcode, CLA Signed

#24834 24765 add support for enum props
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jdbc/resources/com/ibm/ws/rsadapter/resources/IBMDataStoreAdapterNLS.nlsprops
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/postgresql-test-server/server.xml
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed, L2 Reviewed

#24747 Initial InstantOn changes for WebProfile Transactions
  dev/com.ibm.tx.jta/bnd.bnd
  dev/com.ibm.tx.jta/resources/com/ibm/ws/Transaction/resources/TransactionMsgs.nlsprops
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/com.ibm.ws.transaction/bnd.bnd
  dev/com.ibm.ws.transaction/resources/com/ibm/ws/transaction/services/TransactionMessages.nlsprops
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TransactionManagerService.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LocalEJBTest.java
  dev/io.openliberty.checkpoint_fat/test-applications/timeoutTest/src/timeoutTest/TimeoutStartup.java
  dev/io.openliberty.checkpoint_fat_transaction/.classpath
  dev/io.openliberty.checkpoint_fat_transaction/bnd.bnd
  dev/io.openliberty.checkpoint_fat_transaction/build.gradle
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/RecoveryTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/RecoveryTestBase.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/ServletStartupTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/ServletTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/StartupBeanTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionLogTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionManagerTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionScopedBeanTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionalBeanTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/util/RecoveryUtils.java
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionManager/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionManager/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionManager/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionRecovery/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionRecovery/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionRecovery/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionrecovery/src/servlets/recovery/RecoveryServlet.java
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionservlet/src/servlets/simple/AsyncBean.java
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionservlet/src/servlets/simple/SimpleServlet.java
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionservlet/src/servlets/simple/package-info.java
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionstartupbean/src/com/ibm/ws/transaction/ejb/first/InitNewTxBean1.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/fat/src/io/openliberty/ejbcontainer/checkpoint/fat/tests/EjbStartCheckpointTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24893 rename io.openliberty.io.opentelemetry.internal
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.io.opentelemetry/.classpath
  dev/io.openliberty.io.opentelemetry/.project
  dev/io.openliberty.io.opentelemetry/.settings/bndtools.core.prefs
  dev/io.openliberty.io.opentelemetry/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.opentelemetry/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.opentelemetry/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.io.opentelemetry/bnd.bnd
  dev/io.openliberty.io.opentelemetry/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ConfigurablePropagatorProvider
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_cs.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_de.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_es.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_fr.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_hu.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_it.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_ja.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_ko.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_pl.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_pt_BR.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_ro.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_ru.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_zh.nlsprops
  dev/io.openliberty.io.opentelemetry/resources/io/openliberty/io/opentelemetry/resources/MPTelemetry_zh_TW.nlsprops
  dev/io.openliberty.io.opentelemetry/src/io/opentelemetry/api/GlobalOpenTelemetry.java
  dev/io.openliberty.io.opentelemetry/src/io/opentelemetry/api/package-info.java
  dev/io.openliberty.io.opentelemetry/src/io/opentelemetry/instrumentation/annotations/WithSpan.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.mpTelemetry.1.0.thirdparty/bnd.bnd
Labels: ID review not needed, CLA Signed

#24857 clean up JSF 2.3 FAT test classes
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/CDITestBase.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/JSFUtils.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/Faces30Tests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIConfigByACPTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIInjectionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ClassLevelBeanValidationTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ComponentSearchTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23EvalScriptsTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ExternalContextStartupShutdownTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FaceletVDLTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FacesDataModelTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23GeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23IterableSupportTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23JPA22Test.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23MapSupportTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23UIRepeatConditionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23UISelectManyTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ViewParametersTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ViewResourceTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSFFeatureConflictTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24707 LibertyServer debug and JPA Checkpoint FAT assertion
  dev/com.ibm.ws.jpa.tests.container.checkpoint_fat.common/fat/src/com/ibm/ws/jpa/tests/container/checkpoint/tests/AbstractFATSuite.java
  dev/com.ibm.ws.jpa.tests.container.checkpoint_fat.common/fat/src/com/ibm/ws/jpa/tests/container/checkpoint/tests/JPADataSourceCheckpointTest_EJB.java
  dev/com.ibm.ws.jpa.tests.container.checkpoint_fat.common/fat/src/com/ibm/ws/jpa/tests/container/checkpoint/tests/JPADataSourceCheckpointTest_Web.java
  dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.1_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.0_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat/bnd.bnd
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#24914 Remove reference to old version of transformer.
  dev/cnf/oss_ibm.maven
  dev/wlp-jakartaee-transform/bnd.bnd
  dev/wlp-jakartaee-transform/bnd.overrides
Labels: CLA Signed, team:Performance

#24910 experiment with multiple databases
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DelegatingResourceFactory.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Repository.java
Labels: team:Zombie Apocalypse, CLA Signed

#24843 ignore logging ffdc when securerandom with the SHA1PRNG algorithm fails
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/jwk/utils/JsonUtils.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/OAuthUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jwk/Util.java
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/SamlUtil.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/SocialUtil.java
Labels: CLA Signed

#24861 Update repeat rules for Social
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oidcServerFeatures.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/fat/src/com/ibm/ws/security/social/fat/LibertyOP/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.claimPropagation/fat/src/com/ibm/ws/security/social/claimPropagation/fat/FATSuite.java
  dev/com.ibm.ws.security.social_fat.OpenShift/bnd.bnd
  dev/com.ibm.ws.security.social_fat.OpenShift/fat/src/com/ibm/ws/security/social/fat/OpenShift/FATSuite.java
  dev/com.ibm.ws.security.social_fat.delegated/bnd.bnd
  dev/com.ibm.ws.security.social_fat.delegated/fat/src/com/ibm/ws/security/social/fat/delegated/FATSuite.java
  dev/com.ibm.ws.security.social_fat.delegated/publish/files/serversettings/external_op_features.xml
  dev/com.ibm.ws.security.social_fat.delegated/publish/files/serversettings/op_features.xml
  dev/com.ibm.ws.security.social_fat.multiProvider/bnd.bnd
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/FATSuite.java
  dev/com.ibm.ws.security.social_fat.okdServiceLogin/bnd.bnd
  dev/com.ibm.ws.security.social_fat.okdServiceLogin/fat/src/com/ibm/ws/security/social/fat/okdServiceLogin/FATSuite.java
  dev/com.ibm.ws.security.social_fat/publish/files/serversettings/socialLoginRunableFeatures.xml
Labels: test bug, CLA Signed, team:Security SSO

#24887 Cleanup WebContainer bnd.bnd
  dev/com.ibm.ws.webcontainer/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#24913 Better error messages when SELinux blocks netlink system calls.
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointFailTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/publish/files/testlogs/checkpoint.log
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/server.xml
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24935 Revert "Use mvn wrapper"
  dev/.gitignore
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/maven-wrapper.jar
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/maven-wrapper.properties
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/mvnw
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/mvnw.cmd
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/settings.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#24882 Reduce dependency on Hostname/addr in jwt builder tests
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/LargeProjectRepeatActions.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwkEndpointValidationUrlTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigAltKeyStoreTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumRunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigBuilderTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIMinimumSSLConfigGlobalTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIWithLDAPConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiWithLDAPBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/utils/BuilderHelpers.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder/configs/server_minimumConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/servers/com.ibm.ws.security.jwt_fat.builder/configs/server_minimumSSLConfig2.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientBasicConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientConfigNoIdTestsConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientConfigTestsConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/oidcRSClientBasicConfig.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ConfigElement.java
Labels: test bug, CLA Signed, team:Security SSO

#24837 MYFACES-4594
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/webapp/FacesInitializerImpl.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java
Labels: in:Web Components, CLA Signed

#24928 resource ref bindings and UUID
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Product.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
Labels: team:Zombie Apocalypse, CLA Signed

#24932 ServerConfig test datasource connection: click Add login config property button
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
Labels: CLA Signed

#24819 Add new VisibilityTest for tolerated public / protected features
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureInfo.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureVerifier.java
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-9.1/io.openliberty.jakartaeeClient-9.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-5.0/io.openliberty.microProfile-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/com.ibm.websphere.appserver.mpOpenTracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openapi-3.1/com.ibm.websphere.appserver.openapi-3.1.feature
Labels: CLA Signed, team:Performance

#24919 Revert the Revert of: Create com.ibm.ws.security.oidc.server_fat.oauth FAT project
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.classpath
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.project
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oauth/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oauth/fat/src/com/ibm/ws/security/openidconnect/server/fat/oauth/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/CommonTests/genericWebClientAuthCertTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/CommonTests/GenericCookieNameTests.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/CommonTests/GenericGrantTypesTests.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthCookieNameTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthGrantTypesTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthPKCETest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthPromptLoginTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthScopesClientCredentialTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthScopesImplicitTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthScopesPasswordTest.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/OAuth/OAuthScopesTest.java
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/misc.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat/configs/server_clientcred_oauth.xml
Labels: noproductcode, test debt, CLA Signed, team:Security SSO

#24776 Upgrade to RESTEasy 6.2.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/concurrent/ContextualExecutorService.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ContextParameterInjector.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ResourceLocatorInvoker.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/multipart/ResteasyEntityPartBuilder.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/config/DefaultConfiguration.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
Labels: CLA Signed

#24515 Avoid inferred datasources on IBMi when db rotation
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestRetriableCodes.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.retriablecodes/fat/src/suite/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
Labels: team:Zombie Apocalypse, test bug, CLA Signed

#24927 Switch to posix sed command for server.env
  dev/com.ibm.ws.appclient.boot.ws-client/publish/bin/client
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerEnvTest.java
Labels: CLA Signed, release bug, target:23004

#24930 Add console log header when restoring from checkpoint
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/BootstrapConstants.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java
Labels: CLA Signed

#24791 Stop building EE9 and MP5 zips
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee9/features.xml
  dev/build.image/profiles/microProfile5/features.xml
  dev/build.image/profiles/webProfile9/features.xml
Labels: CLA Signed

#24937 JSONBContainerTest wait for config update
  dev/com.ibm.ws.jsonb_fat/fat/src/com/ibm/ws/jsonb/fat/JSONBContainerTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#24920 Update artifactory image name substitutor
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ProgrammaticImageTest.java
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_multiple/fat/src/com/ibm/ws/concurrent/persistent/fat/multiple/FATSuite.java
  dev/com.ibm.ws.concurrent.persistent_fat_timers/fat/src/com/ibm/ws/concurrent/persistent/fat/timers/FATSuite.java
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/docker/pebble/PebbleContainer.java
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeCaRestHandlerTest.java
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/resources/META-INF/services/org.testcontainers.dockerclient.DockerClientProviderStrategy
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalDockerClientFilter.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
  dev/io.openliberty.org.testcontainers/cache/projects
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#24942 fix ay11 for Add login config property button
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/index.jsp
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/dialogs/validateConnection.js
Labels: CLA Signed

#24722 Add configurable option for FileUpload
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxPropertyTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/FileUploadFileCountMaxTest.war/src/filecountmax/GetPartName.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: in:Web Components, CLA Signed, team:Sirius, L2 Reviewed, ID waiting on development

#24931 Improve serviceability of new transaction checkpoint hook
  dev/com.ibm.tx.jta/resources/com/ibm/ws/Transaction/resources/TransactionMsgs.nlsprops
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TransactionImpl.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/ServletStartupTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/StartupBeanTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24950 Optimize update poms
  dev/build.cleanPom/.classpath
  dev/build.cleanPom/.gitignore
  dev/build.cleanPom/bnd.bnd
  dev/build.cleanPom/src/io/openliberty/process/PostProcessBNDPom.java
  dev/build.depScanner/bnd.bnd
  dev/build.image/build.gradle
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
  dev/wlp-updatePom/.classpath
  dev/wlp-updatePom/.project
  dev/wlp-updatePom/.settings/bndtools.core.prefs
  dev/wlp-updatePom/.settings/org.eclipse.core.resources.prefs
  dev/wlp-updatePom/.settings/org.eclipse.jdt.core.prefs
  dev/wlp-updatePom/.settings/org.eclipse.jdt.ui.prefs
  dev/wlp-updatePom/bnd.bnd
  dev/wlp-updatePom/gradle/log.init.gradle
  dev/wlp-updatePom/gradle/timing.init.gradle
  dev/wlp-updatePom/src/io/openliberty/build/update/Update.java
  dev/wlp-updatePom/src/io/openliberty/build/update/UpdateDirectory.java
  dev/wlp-updatePom/src/io/openliberty/build/update/UpdateFactory.java
  dev/wlp-updatePom/src/io/openliberty/build/update/UpdateFile.java
  dev/wlp-updatePom/src/io/openliberty/build/update/UpdateImpl.java
  dev/wlp-updatePom/src/io/openliberty/build/update/UpdateRunner.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/PomUtils.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePom.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePomFiles.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePomJar.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePomJars.java
  dev/wlp-updatePom/src/io/openliberty/build/update/util/FileUtils.java
  dev/wlp-updatePom/src/io/openliberty/build/update/util/Logger.java
Labels: CLA Signed

#24957 Revert "Add configurable option for FileUpload"
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxPropertyTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/FileUploadFileCountMaxTest.war/src/filecountmax/GetPartName.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: CLA Signed

#24799 add test on return.security.error
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigSymEE7LiteTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/publish/servers/com.ibm.ws.wssecurity_fat.x509migsym.ee7lite/.gitignore
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/publish/servers/com.ibm.ws.wssecurity_fat.x509migsym.ee7lite/bootstrap.properties
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/publish/servers/com.ibm.ws.wssecurity_fat.x509migsym.ee7lite/server.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/publish/servers/com.ibm.ws.wssecurity_fat.x509migsym.ee7lite/server_sha512.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/publish/servers/com.ibm.ws.wssecurity_fat.x509migsym.ee7lite/server_sha512_disable_return_error.xml
Labels: noproductcode, CLA Signed

#24924 Add @Trivial to ApplicationManager LogRecordContext inner class
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/ApplicationManager.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/TraceClassFileTransformer.java
Labels: CLA Signed

#24004 allow more output to response following exception in forward based on wc parm
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPExceptionTests.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspServletExceptionWrapServer/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspServletExceptionWrapServer/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/exception.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/include.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/moreoutput.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/testfwdexc.jsp
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppRequestDispatcher.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
Labels: in:Web Components, ID reviewed, CLA Signed, release bug, team:Sirius, L2 ReviewNotRequired

#24960 Quick fix to updater path logic
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/PomUtils.java
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/UpdatePomJar.java
Labels: CLA Signed

#24880 Directly retrieve servlet context form request
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/rest/BaseMetricsRESTProxyServlet.java
Labels: CLA Signed

#24946 WSAT to support SOAP 1 Provider acting as gateway
  dev/com.ibm.ws.wsat.webservice/src/com/ibm/ws/wsat/utils/WSCoorUtil.java
Labels: CLA Signed

#24947 Update Eclipselink ASM to 9.5.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed

#24951 Checkpoint social login
  dev/com.ibm.websphere.appserver.features/visibility/public/jwtSso-1.0/com.ibm.websphere.appserver.jwtSso-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/oauth-2.0/com.ibm.websphere.appserver.oauth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/com.ibm.websphere.appserver.socialLogin-1.0.feature
  dev/io.openliberty.checkpoint_fat_social_login/.classpath
  dev/io.openliberty.checkpoint_fat_social_login/.project
  dev/io.openliberty.checkpoint_fat_social_login/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_social_login/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_social_login/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_social_login/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_social_login/bnd.bnd
  dev/io.openliberty.checkpoint_fat_social_login/build.gradle
  dev/io.openliberty.checkpoint_fat_social_login/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat_social_login/fat/src/io/openliberty/checkpoint/fat/LibertyOP_BasicTests_oauth_usingSocialConfig.java
  dev/io.openliberty.checkpoint_fat_social_login/publish/files/internalfeatures/securitylibertyinternals-1.0.mf
  dev/io.openliberty.checkpoint_fat_social_login/publish/securitykeys/rsa_badTrust.jks
  dev/io.openliberty.checkpoint_fat_social_login/publish/securitykeys/rsa_badTrust.jks.orig
  dev/io.openliberty.checkpoint_fat_social_login/publish/securitykeys/rsa_trust.jks
  dev/io.openliberty.checkpoint_fat_social_login/publish/securitykeys/rsa_trust_for_LibertyOP.jks
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/configs/server.xml
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/jvm.options
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/server.env
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/configs/server.xml
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/configs/server_withJwtSsoFeature.xml
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/jvm.options
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/server.env
Labels: CLA Signed

#24961 Add classloading trace to the JPA container ModifyConfig FAT
  dev/com.ibm.ws.jpa.tests.container_modifyconfig_fat/publish/servers/com.ibm.ws.jpa.container.fat.modifyconfig/bootstrap.properties
Labels: noproductcode, CLA Signed

#24969 Improve ScheduleExpression increment testing
  dev/com.ibm.ws.ejbcontainer.core/test/com/ibm/ejs/container/ScheduleExpressionParserTest.java
Labels: in:EJB Container, noproductcode, team:Blizzard, CLA Signed, test delivery

#24965 add maximum connections to pmi
  dev/com.ibm.websphere.appserver.api.connectionpool/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.connectionpoolmonitor-1.0.feature
  dev/com.ibm.ws.connectionpool.monitor/bnd.bnd
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/websphere/connectionpool/monitor/ConnectionPoolStatsMXBean.java
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/websphere/connectionpool/monitor/package-info.java
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/ws/connectionpool/monitor/ConnectionPoolMonitor.java
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/ws/connectionpool/monitor/ConnectionPoolStats.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/websphere/jca/pmi/JCAPMIHelper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/websphere/jca/pmi/package-info.java
  dev/com.ibm.ws.jca_fat_mbean/fat/src/com/ibm/ws/jca/mbean/fat/app/ConnectionPoolStatsTest.java
  dev/com.ibm.ws.jca_fat_mbean/test-applications/fvtweb/src/web/ConnectionPoolStatsServlet.java
Labels: CLA Signed

#24975 Fix race condition with derby during tests
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
Labels: CLA Signed

#24974 PH52739 - Use the new file utilities to create temporary files.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/core/ResourceLocatorInvoker.java
Labels: in:JAX-RS, CLA Signed, target:23004

#24999 Issue #20368: Stop pre-creating EJBs for Checkpoint
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ContainerConfigConstants.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/ContainerProperties.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/container/EJSHome.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ejs/csi/EJBApplicationMetaData.java
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/fat/src/io/openliberty/ejbcontainer/checkpoint/fat/tests/EjbStartCheckpointTest.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/web/EjbStartCheckpointServlet.java
Labels: in:EJB Container, team:Blizzard, CLA Signed, CRIU

#25004 Issue 19029: Initial metatype for OIDC client PKCE support
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
Labels: ID review not needed, CLA Signed, team:Security SSO

#24996 implement maxInUseTime and tests
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jca.cm/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManagerServiceImpl.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/FreePool.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CConstants.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CGlobalConfigProperties.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/PoolManager.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/TaskTimer.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/TaskTimerMaxInUseTime.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/TaskTimerReaperThread.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/websphere/jca/pmi/JCAPMIHelper.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ws/j2c/poolmanager/ConnectionPoolProperties.java
  dev/com.ibm.ws.jdbc_fat_v41/fat/src/com/ibm/ws/jdbc/fat/v41/JDBC41Test.java
  dev/com.ibm.ws.jdbc_fat_v41/publish/files/server_derby40.xml
  dev/com.ibm.ws.jdbc_fat_v41/publish/servers/com.ibm.ws.jdbc.fat.v41/server.xml
  dev/com.ibm.ws.jdbc_fat_v41/test-applications/basicfat/src/jdbc/fat/v41/web/BasicTestServlet.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ConnectionManager.java
Labels: ID reviewed, CLA Signed

#25006 Jakarta Data tests with ManyToMany
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customer.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DeliveryLocation.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Street.java
Labels: team:Zombie Apocalypse, CLA Signed

#24956 Update LTPACrypto to support HW provider
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
Labels: CLA Signed

#24959 Add new configurable property for fileUpload
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.servlet-servletSpi1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet-servletSpi2.0.feature
  dev/com.ibm.websphere.appserver.spi.servlet/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxPropertyTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCFileUpLoadFileCountMaxTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMax/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/publish/servers/servlet40_FileUploadFileCountMaxProperty/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/FileUploadFileCountMaxTest.war/src/filecountmax/GetPartName.java
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletRequest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/package-info.java
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: in:Web Components, CLA Signed, release bug, team:Sirius, target:23004

#24918 Force writing of diagnostic logs in peer locking tests
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/tests/DualServerPeerLockingTest2.java
Labels: noproductcode, CLA Signed

#25016 Repeat cloud tests properly
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicFSTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicFSTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DupXidTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/LongTranTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/longtran/src/com/ibm/ws/longtran/web/LongtranServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/.classpath
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/suite/FATSuite.java
Labels: noproductcode, CLA Signed

#25007 Issue 19029: Initial drop of data structures for PKCE support
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20ComponentImpl.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20Constants.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/PkceMethodPlain.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/PkceMethodS256.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchange.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchangeMethod.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/package-info.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/PkceMethodPlainTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/PkceMethodS256Test.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchangeMethodTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchangeTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
Labels: CLA Signed, team:Security SSO

#24998 add dynamic config change to max connections limit pmi test
  dev/com.ibm.ws.jca_fat_mbean/fat/src/com/ibm/ws/jca/mbean/fat/app/ConnectionPoolStatsTest.java
  dev/com.ibm.ws.jca_fat_mbean/publish/servers/com.ibm.ws.jca.jdbc.mbean.fat.app.connPool/server.xml
  dev/com.ibm.ws.jca_fat_mbean/test-applications/fvtweb/src/web/ConnectionPoolStatsServlet.java
Labels: noproductcode, CLA Signed

#25021 Issue #20368: Fix EJB Checkpoint FAT for Startup Singletons
  dev/io.openliberty.ejbcontainer.checkpoint_fat/fat/src/io/openliberty/ejbcontainer/checkpoint/fat/tests/EjbStartCheckpointTest.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/publish/servers/EjbStartCheckpointMockServer/jvm.options
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/ejb/SGCheckpointBeanA.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/ejb/SGCheckpointBeanB.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/other/ejb/SGCheckpointBeanG.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/other/ejb/SGCheckpointBeanH.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/other/ejb/SLCheckpointBeanH.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherEJB.jar/src/io/openliberty/ejbcontainer/fat/checkpoint/other/ejb/SLCheckpointBeanJ.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/other/web/SGCheckpointBeanS.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointOtherWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/other/web/SGCheckpointBeanT.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/web/EjbStartCheckpointServlet.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/web/SGCheckpointBeanM.java
  dev/io.openliberty.ejbcontainer.checkpoint_fat/test-applications/CheckpointWeb.war/src/io/openliberty/ejbcontainer/fat/checkpoint/web/SGCheckpointBeanN.java
Labels: in:EJB Container, noproductcode, team:Blizzard, test delivery, CRIU

#24983 Increase retriable cloud test server lease length
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriablecloud/server.xml
Labels: noproductcode, CLA Signed

#24972 In DB TX Logging change sqlserver lock hints
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
Labels: CLA Signed

#25023 Remove unused duplicate MP Config messages
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_cs.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_de.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_es.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_fr.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_hu.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_it.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_ja.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_ko.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_pl.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_pt_BR.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_ro.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_ru.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_zh.nlsprops
  dev/io.openliberty.microprofile.config.internal.serverxml/resources/io/openliberty/microprofile/config/internal/serverxml/resources/ConfigServerXML_zh_TW.nlsprops
Labels: ID review not needed, CLA Signed, L2 Reviewed

#25029 Adding mdb to message ignore list
  dev/com.ibm.ws.jca_fat_regr.rar.beanVal/fat/src/suite/r80/base/jca16/jbv/RarBeanValidationTestCommon.java
Labels: noproductcode, CLA Signed

#24995 ignore logout token claims that are not understood
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/LogoutTokenValidationTests.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/internal/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/internal/LogoutTokenValidatorTest.java
Labels: CLA Signed

#24384 Added testcase for distributedMap to checkpoint fat suite
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MapCacheTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMapCache/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMapCache/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMapCache/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/mapCache/src/mapCacheApp/MapCache.java
Labels: noproductcode, CLA Signed

#24778 Update expression language40 to10.0.27
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-4.0.feature
  dev/io.openliberty.jakarta.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.4.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.4.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius

#25037 Add Java 21 support to com.ibm.ws.jpa.tests.javasupport_fat
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/AbstractTestJavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA21_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA22_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA30_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
  dev/com.ibm.ws.jpa.tests.javasupport_fat/publish/servers/javaSupportServer_JPA21/apps/JavaSupportTest_21.war
  dev/com.ibm.ws.jpa.tests.javasupport_fat/publish/servers/javaSupportServer_JPA22/apps/JavaSupportTest_21.war
  dev/com.ibm.ws.jpa.tests.javasupport_fat/publish/servers/javaSupportServer_JPA30/apps/JakartaSupportTest_21.war
  dev/com.ibm.ws.jpa.tests.javasupport_fat/publish/servers/javaSupportServer_JPA31/apps/JakartaSupportTest_21.war
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed, Java 21

#25031 Refactored MPFaultToleranceTimeoutTest to use CDI instead of EJB
  dev/io.openliberty.checkpoint_fat/publish/servers/timeoutServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/timeoutTest/src/timeoutTest/TimeoutStartup.java
Labels: noproductcode, CLA Signed

#25027 Issue #25010: Fixed getEntityByIdentifier to not call the WIM GET met…
  dev/com.ibm.websphere.security_fat.1/test-applications/WebsphereUserRegistry/src/web/UserRegistryServlet.java
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/BridgeUtils.java
Labels: CLA Signed, team:Wendigo East

#25001 Automated OpenAPI UI testing with Selenium
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/containers/ImageVerifier.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.classpath
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.project
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/build.gradle
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/TestResource.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/FATSuite.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/publish/servers/openapi-ui-test/bootstrap.properties
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/publish/servers/openapi-ui-test/server.xml
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: CLA Signed

#24988 JAX-WS and JAX-RS 2.1: Prep CXF Core project source for CXF 3.5
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentSerializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentUtil.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/CXFExtensionBundleListener.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/OSGiBeanLocator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/logging/LogUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/spi/NamespaceClassGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/util/ProxyHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/endpoint/ClientImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/phase/PhaseInterceptorChain.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxSource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/transport/ChainInitiationObserver.java
Labels: CLA Signed

#25049 Increase tx timout duration in testTransactionEnlistment
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionServlet/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/test-applications/transactionservlet/src/servlets/simple/SimpleServlet.java
Labels: noproductcode, CLA Signed

#25052 Issue #25008: When configuring a non-identifier property as the outpu…
  dev/com.ibm.ws.security.wim.registry/src/com/ibm/ws/security/wim/registry/util/SearchBridge.java
  dev/com.ibm.ws.security.wim.registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/WIMURRegressionTest.java
Labels: CLA Signed

#25025 Reduce test container starts
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicTestBase.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/fat/src/tests/DualServerPeerLockingTest.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.lease/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.db2.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.db2.retriablecodes/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.db2.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.lease/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.oracle.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.lease/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.retriablecodes/.classpath
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.retriablecodes/fat/src/suite/FATSuite.java
Labels: CLA Signed

#24968 Revert " Debug if a request with session header is sent"
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/rest/BaseMetricsRESTProxyServlet.java
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
Labels: CLA Signed

#25030 Log first entry for ignored messages after logging is fully restored
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/LogsVerificationTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.log.verification.test/server.xml
Labels: CLA Signed

#24802 Added testcase for WebCache with checkpoint and restore
  dev/com.ibm.websphere.appserver.features/visibility/public/webCache-1.0/com.ibm.websphere.appserver.webCache-1.0.feature
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebCacheTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/cachespec.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/webCacheApp/src/WebCacheApp/CachedServlet.java
Labels: CLA Signed

#25051 Increased the test application start up time for MP Health FATs
  dev/io.openliberty.microprofile.health.3.0.internal_fat/fat/src/io/openliberty/microprofile/health30/fat/DefaultOverallReadinessStatusUpAppStartupTest.java
  dev/io.openliberty.microprofile.health.3.0.internal_fat/test-applications/DelayedHealthCheckApp/src/io/openliberty/microprofile/health30/delayed/health/check/app/DelayedServlet.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/DefaultOverallStartupStatusUpAppStartupTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/DelayedHealthCheckApp/src/io/openliberty/microprofile/health31/delayed/health/check/app/DelayedServlet.java
Labels: noproductcode, CLA Signed

#24898 Extra diag for ws invocation fails
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/tests/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/fat/src/suite/FATSuite.java
Labels: noproductcode, CLA Signed

#25077 Remove allowed.features bootstrap properties for webCache feature
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#25079 Issue 21826: Initial data structures and metatype for OIDC Private Key JWT client authn
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcClientUtilTest.java
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/http/OidcClientHttpUtil.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenConstants.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethod.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/package-info.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethodTest.java
Labels: CLA Signed, team:Security SSO

#25080 Verify the transaction log datasource configures at restore
  dev/io.openliberty.checkpoint_fat_transaction/build.gradle
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionLogTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionManagerTest.java
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionManager/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionRecovery/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionServlet/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionStartupBean/server.xml
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionalBean/server.xml
Labels: noproductcode, CLA Signed

#25068 Fix conditional rules for jakartasec
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonAnnotatedSecurityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationSigningTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/sharedTests/BasicOIDCAnnotationTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25083 Allow invalidation processes continue after deserialization exceptions
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
Labels: CLA Signed

#24775 HttpConduitProperties test is refactored
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/HttpConduitPropertiesTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForMatchedPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForMatchedServiceRef.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForMatchedServiceRefAndPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForMultipleSampleApp.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForNoMatchedPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForNoMatchedServiceRef.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testPropertiesForTwoServiceRefInOneApp.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/ibm-ws-bnd_testReceiveTimeout.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForMatchedPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForMatchedServiceRef.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForMatchedServiceRefAndPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForMultipleSampleApp.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForNoMatchedPort.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForNoMatchedServiceRef.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testPropertiesForTwoServiceRefInOneApp.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/HttpConduitPropertiesTest/includeFiles/testReceiveTimeout.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/HttpConduitPropertiesTestServer/include/httpConduitProperties.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/servers/HttpConduitPropertiesTestServer/server.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#25003 Wait for JMS restart after config change
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonsReady.java
  dev/com.ibm.ws.messaging.comms.server/src/com/ibm/ws/sib/trm/attach/TrmSingleton.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/servers/DeliveryDelayClient/bootstrap.properties
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/publish/servers/DeliveryDelayEngine/bootstrap.properties
Labels: CLA Signed

#24980 24864: Http/2 Frame size error with compression
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/compression/DeflateOutputHandler.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/compression/GzipOutputHandler.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/FATSuite.java
  dev/com.ibm.ws.transport.http2_fat/fat/src/test/server/transport/http2/Http2CompressionTests.java
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.compression/bootstrap.properties
  dev/com.ibm.ws.transport.http2_fat/publish/servers/com.ibm.ws.transport.http2.fat.compression/server.xml
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/DataFrameTests.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2FATDriver.war/src/http2/test/driver/war/servlets/H2FATDriverServlet.java
  dev/com.ibm.ws.transport.http2_fat/test-applications/H2TestModule.war/src/http2/test/war/servlets/H2Compression.java
Labels: in:Transport, ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#25098 Update message
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
Labels: CLA Signed

#25000 Added test class to test xml bindings with checkpoint and restore.
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlBinding-4.0/io.openliberty.xmlBinding-4.0.feature
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/XMLbindingsTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/xmlBindingServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/xmlBindingServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/xmlBindingServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/xmlBindings/src/xmlBinding/Endpoints.java
  dev/io.openliberty.checkpoint_fat/test-applications/xmlBindings/src/xmlBinding/ServerRoot.java
  dev/io.openliberty.checkpoint_fat/test-applications/xmlBindings/src/xmlBinding/XMLobject.java
Labels: CLA Signed

#25034 Issue 19029: Initial code for PKCE support in OIDC RP
  dev/com.ibm.websphere.appserver.features/visibility/public/socialLogin-1.0/com.ibm.websphere.appserver.socialLogin-1.0.feature
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MessageConstants.java
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchange.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchangeMethodTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/pkce/ProofKeyForCodeExchangeTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/CoverageMapEndpointServicesTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcAuthorizationRequest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/pkce/ProofKeyForCodeExchangeCache.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/pkce/ProofKeyForCodeExchangeHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/pkce/package-info.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/pkce/ProofKeyForCodeExchangeHelperTest.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/CustomSelectionPageTests.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_LocalAuthentication.java
Labels: CLA Signed, team:Security SSO

#25112 Remove checkpoint in container FAT test
  dev/io.openliberty.checkpoint_fat_container/.classpath
  dev/io.openliberty.checkpoint_fat_container/.project
  dev/io.openliberty.checkpoint_fat_container/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_container/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_container/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_container/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_container/bnd.bnd
  dev/io.openliberty.checkpoint_fat_container/build.gradle
  dev/io.openliberty.checkpoint_fat_container/fat/src/io/openliberty/checkpoint/fat/container/ContainersTestBase.java
  dev/io.openliberty.checkpoint_fat_container/fat/src/io/openliberty/checkpoint/fat/container/FATSuite.java
  dev/io.openliberty.checkpoint_fat_container/publish/files/Dockerfile
  dev/io.openliberty.checkpoint_fat_container/publish/files/scripts/checkpoint
  dev/io.openliberty.checkpoint_fat_container/publish/files/scripts/execServer
  dev/io.openliberty.checkpoint_fat_container/publish/files/scripts/launcher
  dev/io.openliberty.checkpoint_fat_container/publish/files/scripts/pidplus
  dev/io.openliberty.checkpoint_fat_container/publish/servers/checkpoint.fat.container/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_container/publish/servers/checkpoint.fat.container/jvm.options
  dev/io.openliberty.checkpoint_fat_container/publish/servers/checkpoint.fat.container/server.xml
  dev/io.openliberty.checkpoint_fat_container/test-applications/servletA/src/com/ibm/ws/testapp/ServletA.java
Labels: noproductcode, CLA Signed

#25094 Increase stale failover test server lease length
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriablecloud/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_stalecloud/server.xml
Labels: noproductcode, CLA Signed

#25110 remove as alias for delete
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Accounts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#25115 Fix test defect in CheckpointSPITest
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestCheckpointHook.java
Labels: noproductcode, CLA Signed

#25041 Add ZOS test skip and remove invalid testing
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/query/tests/olgh/TestOLGH19342_EJB.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/ejb/TestOLGH19342_EJB_SFEx_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/ejb/TestOLGH19342_EJB_SF_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/ejb/TestOLGH19342_EJB_SL_Servlet.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/testlogic/JPATestOLGH19342Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_fat.common/test-applications/olgh19342/src/com/ibm/ws/jpa/olgh19342/web/TestOLGH19342Servlet.java
Labels: noproductcode, CLA Signed

#25123 Fix test setup method name, verify the message for context initialization
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebProfileJSPWithELTest.java
Labels: noproductcode, CLA Signed

#25120 Add missing dependency for jaxb to compile in Eclipse IDE
  dev/io.openliberty.checkpoint_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#25121 Add -Xdump option to dump on deadlock in single threaded mode
  dev/io.openliberty.checkpoint_fat/publish/servers/CRIULogLevelTest/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/ValidFeatures/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAppSecurity/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointAudit/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointConcurrency/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointEJB/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFATServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-beanServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-frontendUI/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFailServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointJsonb/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointJsonp/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPConfig/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPHealth/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPJWT/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPMetrics/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerInventory/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenTracing-jaegerServerSystem/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPTelemetry/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointManagedBeans/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMapCache/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointRestConnector/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointSSL/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointWithSecurityManager/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.log.verification.test/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointfat.osgi.console.test/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.auth.data.fat.dpm.pu11/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.federation/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/jaxWSVirtualHost/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/jndiServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/openAPIserver/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/restClientServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/slowStartAppServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/timeoutServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webCacheServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webProfileEARserver/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webProfileJSP/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/webSocketServer/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/xmlBindingServer/jvm.options
  dev/io.openliberty.checkpoint_fat_beanvalidation/publish/servers/checkpointBeanValidation/jvm.options
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/checkpointfat.jpa/jvm.options
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/jvm.options
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/sessionDatabaseServer/jvm.options
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/jvm.options
  dev/io.openliberty.checkpoint_fat_social_login/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionDbLog/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionManager/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionRecovery/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionScopedBean/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionServlet/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionServletStartup/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionStartupBean/jvm.options
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionalBean/jvm.options
Labels: noproductcode, CLA Signed

#25132 Fix up recent changes
  dev/com.ibm.ws.install.featureUtility/.classpath
  dev/com.ibm.ws.install/.classpath
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
  dev/com.ibm.ws.jbatch.open_fat/.classpath
  dev/com.ibm.ws.jndi.open_fat/.project
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.nopeerlocking/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_stalecloud/bootstrap.properties
  dev/wlp-updatePom/.classpath
Labels: CLA Signed, team:Performance

#25125 Define partial order for library change notifications
  dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/Bell.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/SharedLibraryImpl.java
  dev/com.ibm.ws.jpa.tests.container_modifyconfig_fat/publish/servers/com.ibm.ws.jpa.container.fat.modifyconfig/bootstrap.properties
Labels: CLA Signed

#25136 Add InstantOn test for using config dropins
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITest.java
  dev/io.openliberty.checkpoint_fat/publish/files/configVariables/a_value
  dev/io.openliberty.checkpoint_fat/publish/files/configVariables/b_value
  dev/io.openliberty.checkpoint_fat/publish/files/configVariables/c_value
  dev/io.openliberty.checkpoint_fat/publish/files/dropinConfigChange/override.xml
Labels: noproductcode, CLA Signed

#25128 Ensure checkpoint is set to null after test run
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/RESTclientTest.java
Labels: noproductcode, CLA Signed

#25131 selections in findBy
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Houses.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/TaxPayers.java
Labels: team:Zombie Apocalypse, CLA Signed

#25065 JAX-WS: Prep CXF Bindings SOAP project source for CXF 3.5
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapBindingFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/SoapMessage.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/MustUnderstandInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/RPCInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/ReadHeadersInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/Soap11FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/Soap12FaultOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapActionInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/SoapPreProtocolOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/TibcoSoapActionInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/jms/interceptor/SoapFaultFactory.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/saaj/SAAJInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/saaj/SAAJOutInterceptor.java
Labels: CLA Signed

#25124 JAX-WS: Prep CXF Databinding JAXB project source for CXF 3.5
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBContextInitializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBDataBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/attachment/JAXBAttachmentSchemaValidationHack.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataReaderImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataWriterImpl.java
Labels: CLA Signed

#25126 Disable entry exit debug on methods
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
Labels: CLA Signed
