Repository OpenLiberty/open-liberty, pull requests merged in 2023-07, with the labels that each got.

#25575 PR for Issue 25524: Fix x5t calculation in OIDC Private Key JWT
  dev/com.ibm.ws.security.common/bnd.bnd
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/ssl/SecuritySSLUtils.java
  dev/com.ibm.ws.security.fat.common.SSO.clientTests/fat/src/com/ibm/ws/security/SSO/clientTests/PrivateKeyJwt/PrivateKeyJwtClientTests.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/MessageConstants.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/ConvergedClientConfig.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/PrivateKeyJwtAuthMethod.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/token/auth/TokenEndpointAuthMethod.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/token/auth/PrivateKeyJwtAuthMethodTest.java
  dev/com.ibm.ws.security.social/bnd.bnd
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/Oauth2LoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/OidcLoginConfigImpl.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/PrivateKeyJwtAuthException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/PrivateKeyJwtAuthMissingKeyException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/exceptions/TokenEndpointAuthMethodSettingsException.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/TokenRequestor.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethod.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/TokenEndpointAuthMethod.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethodTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 Reviewed

#24876 Support cookie path the same as context root of web module
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/UserAuthenticationTest.java
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorHelper.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/BasicAuthAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/CertificateLoginAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/FormLoginExtensionProcessor.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/TAIAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/SSOCookieHelperImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxyTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/AuthenticateApiTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/BasicAuthAuthenticatorTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/CertificateLoginAuthenticatorTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/FormLoginExtensionProcessorTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/SSOAuthenticatorTest.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#25616 Session timebase write update when in service mode
  dev/com.ibm.ws.session.store/src/com/ibm/ws/session/store/common/BackedHashMap.java
Labels: CLA Signed, release bug

#25551 Better clean up after ServerEnvTest fat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerEnvTest.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/ServerStartTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, test bug, CLA Signed

#20564 require-java to support range
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/BundleList.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureResourceImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/FeatureResource.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRequirement.java
Labels: ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#25536 Test oracle ojdbc8 on Java 17
  dev/build.example.testcontainers_fat/test-applications/app/src/web/dbrotation/DbRotationServlet.java
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_krb5/build.gradle
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
Labels: team:Zombie Apocalypse, CLA Signed

#25629 Update to handle wlp-jakartaee-transform having generate replacement
  dev/cnf/build.gradle
Labels: noproductcode, CLA Signed, team:Performance

#25582 Fix EE10 test bug
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#25633 PR for Issue 25615: OIDC Private Key JWT enhancement: Use trustStoreRef if configured
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/AuthorizationCodeHandler.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethod.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethodTest.java
Labels: CLA Signed, team:Security SSO

#25593 Moving logging tests to logging_2_fat bucket
  dev/com.ibm.ws.logging_2_fat/bnd.bnd
  dev/com.ibm.ws.logging_2_fat/fat/src/com/ibm/ws/logging/fat/FATSuite.java
  dev/com.ibm.ws.logging_2_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverbootstrap/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverbootstrap/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverbootstrap/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverbootstrap/server.xml
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverdisabled/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverdisabled/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverdisabled/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverdisabled/server.xml
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverenv/server.xml
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverjson/server.xml
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrollovernotrace/server.xml
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/bootstrap.properties
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/jvm.options
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/server.env
  dev/com.ibm.ws.logging_2_fat/publish/servers/com.ibm.ws.logging.timedrolloverxml/server.xml
  dev/com.ibm.ws.logging_2_fat/test-applications/quick-log-test/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.logging_2_fat/test-applications/quick-log-test/resources/beans.xml
  dev/com.ibm.ws.logging_2_fat/test-applications/quick-log-test/src/com/ibm/ws/logging/fat/quick/log/test/QuickLogTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#25638 Log stacks on trace
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/AbstractObserver.java
Labels: noproductcode, CLA Signed

#25611 Improvements to the Checkpoint Transaction FAT suite
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/MockServletTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/RecoveryTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/RecoveryTestBase.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/ServletStartupTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/ServletTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/Simple2PCCloudTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/StartupBeanTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionLogTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionManagerTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionScopedBeanTest.java
  dev/io.openliberty.checkpoint_fat_transaction/fat/src/io/openliberty/checkpoint/fat/TransactionalBeanTest.java
Labels: noproductcode, CLA Signed

#25624 jNoSQL Jakarta data MongoContainer and test
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.data1.0-nosql1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/nosql-1.0/io.openliberty.nosql-1.0.feature
  dev/io.openliberty.data.internal.nosql/.classpath
  dev/io.openliberty.data.internal.nosql/.gitignore
  dev/io.openliberty.data.internal.nosql/.project
  dev/io.openliberty.data.internal.nosql/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal.nosql/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal.nosql/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal.nosql/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal.nosql/bnd.bnd
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_cs.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_de.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_es.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_fr.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_hu.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_it.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_ja.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_ko.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_pl.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_pt_BR.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_ro.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_ru.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_zh.nlsprops
  dev/io.openliberty.data.internal.nosql/resources/io/openliberty/concurrent/internal/nosql/resources/CWWKDMessages_zh_TW.nlsprops
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/cdi/DocumentExtensionProvider.java
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/package-info.java
  dev/io.openliberty.data.internal_fat_nosql/bnd.bnd
  dev/io.openliberty.data.internal_fat_nosql/build.gradle
  dev/io.openliberty.data.internal_fat_nosql/fat/src/test/jakarta/data/nosql/DataNoSQLTest.java
  dev/io.openliberty.data.internal_fat_nosql/fat/src/test/jakarta/data/nosql/FATSuite.java
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/bootstrap.properties
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/server.xml
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/DataNoSQLServlet.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/Employee.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/Employees.java
  dev/io.openliberty.org.eclipse.jnosql.1.0/.classpath
  dev/io.openliberty.org.eclipse.jnosql.1.0/.project
  dev/io.openliberty.org.eclipse.jnosql.1.0/bnd.bnd
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, ID review not needed, CLA Signed

#25652 Cleanup EJB and JPA Checkpoint FAT
  dev/com.ibm.ws.jpa.tests.container.checkpoint_fat.common/publish/servers/JPACheckpointServer/jvm.options
  dev/com.ibm.ws.jpa.tests.container.checkpoint_fat.common/publish/servers/JPACheckpointServer/server.xml
  dev/io.openliberty.ejbcontainer.checkpoint_fat/publish/servers/EjbStartCheckpointMockServer/jvm.options
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, in:JPA, CLA Signed

#25664 Fix type to update to 3.18.300 framework version
  dev/org.eclipse.osgi/bnd.bnd
Labels: CLA Signed

#25653 ignore CWWKO0801E SSL unknown_certificate exception message as tests …
  dev/com.ibm.ws.jaxws.clientcontainer_fat/fat/src/com/ibm/ws/jaxws/clientcontainer/fat/ClientSecurityTest.java
Labels: CLA Needed, noproductcode, CLA Signed

#25676 update comment
  dev/io.openliberty.org.jboss.weld5/build.gradle
Labels: noproductcode, CLA Signed

#25671 id type results for find and delete
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
Labels: team:Zombie Apocalypse, CLA Signed

#25678 PR for Issue 25674: Fix typo in OAuth trace statements
  dev/com.ibm.ws.security.oauth/src/com/ibm/oauth/core/internal/oauth20/OAuth20ComponentImpl.java
Labels: CLA Signed, team:Security SSO

#25647 restrict the parsing of elements in Reason header
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/util/SipUtil.java
Labels: CLA Signed

#25666 Temp fix for jvm bug detecting criu support
  dev/fattest.simplicity/src/componenttest/topology/impl/JavaInfo.java
  dev/fattest.simplicity/src/componenttest/topology/impl/probe/CriuSupport.java
Labels: noproductcode, CLA Signed

#25510 Redeliver fixes for repository resolver problems again
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/tmp/adminCenterServerXml/server.xml
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/FeatureTreeWalker.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/Walker.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRepository.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/RepositoryResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/ResolutionTests.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/LibertyVersionRangeTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/LibertyVersionTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/FeatureResolverTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsaTest.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverRepositoryTest.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/connections/SingleFileRepositoryConnection.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/connections/ZipRepositoryConnection.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/AbstractFileClient.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/FileDataCache.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/SingleFileClient.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/ZipClient.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/AppliesToFilterInfo.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Asset.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/AssetInformation.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Attachment.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/AttachmentInfo.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/CopyUtils.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Feedback.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/FilterVersion.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/ImageDetails.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/JavaSEVersionRequirements.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Link.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Provider.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/RequireFeatureWithTolerates.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/Reviewed.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/StateUpdateAction.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/User.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/model/WlpInformation.java
  dev/com.ibm.ws.repository/test/com/ibm/ws/repository/transport/model/test/AssetTest.java
Labels: CLA Signed, DO NOT MERGE

#25692 296448 Add permission to Java FAT
  dev/io.openliberty.java.internal_fat/publish/servers/java-illegal-access-exception-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java17-cdi-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java17-server/bootstrap.properties
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25687 Cleanup the Expression Language 5.0 FAT bucket
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/ELUtils.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50ArrayCoercionTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50BasicTests.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50DefaultMethodsTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50LambdaExpressionCoercionTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/tests/EL50MethodReferenceTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_arrayServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_arrayServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_basicServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_basicServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_defaultMethodsServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_defaultMethodsServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_lambdaServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_lambdaServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_methodReferenceServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/publish/servers/expressionLanguage50_methodReferenceServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50BasicTests.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50BasicTests.war/src/io/openliberty/el50/fat/basic/servlets/EL50BasicTestsServlet.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50BasicTests.war/src/io/openliberty/el50/fat/basic/servlets/SimpleBean.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50Coercion.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50Coercion.war/src/io/openliberty/el50/fat/coercion/servlets/array/EL50ArrayCoercionServlet.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50DefaultMethodBeanELResolverTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50DefaultMethodBeanELResolverTest.war/src/io/openliberty/el50/fat/defaultmethods/servlet/EL50DefaultMethodsServlet.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50MethodReferenceTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50MethodReferenceTest.war/src/io/openliberty/el50/fat/method/reference/servlet/EL50MethodReferenceServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25683 Always collect server logs when checkpointValidate() fails
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#25705 Revert "add Liberty change markers to PR23267 resteasy mods"
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
Labels: CLA Signed

#25707 Revert "Cache InitData instance to avoid cost of re-creating"
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ServletUtil.java
Labels: CLA Signed

#25682 Initial Expression Language 6.0 FAT
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.classpath
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.project
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage60/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage60/fat/tests/SimpleTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/publish/servers/expressionLanguage60_simpleTestServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/publish/servers/expressionLanguage60_simpleTestServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60SimpleTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60SimpleTest.war/src/io/openliberty/el60/fat/simpletest/servlets/SimpleTestServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#25698 Update BouncyCastle libs for install
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
Labels: CLA Signed

#25696 update netty to 4.1.94 and reduce duplicate bundle including of it in grpc client
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/grpcClient-1.0/io.openliberty.grpcClient-1.0.feature
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client.security/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.client/bnd.bnd
  dev/io.openliberty.grpc.client.1.0.thirdparty/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: CLA Signed

#25620 Update Jackson to 2.15.2
  dev/ant_build.js/build.gradle
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/parser/util/DeserializationUtils.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/utils/OpenAPITestUtil.java
  dev/io.openliberty.com.fasterxml.jackson.jaxrs/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson/.classpath
  dev/io.openliberty.com.fasterxml.jackson/bnd.bnd
  dev/io.openliberty.com.fasterxml.jackson/src/org/yaml/snakeyaml/Yaml.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPITestUtil.java
Labels: CLA Signed

#25651 create new bouncycastle projects
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wss4j-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.ee9.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wss4j-2.3.feature
  dev/com.ibm.ws.net.shibboleth.utilities.java.support.7.5.1/bnd.bnd
  dev/com.ibm.ws.net.shibboleth.utilities.java.support.7.5.1/bnd.overrides
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/bnd.bnd
  dev/com.ibm.ws.org.opensaml.opensaml.core.3.4.5/bnd.overrides
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.classpath
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.gitignore
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.project
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.settings/bndtools.core.prefs
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/bnd.bnd
  dev/io.openliberty.org.bouncycastle.bcpkix-jdk18on/bnd.overrides
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.classpath
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.gitignore
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.project
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.settings/bndtools.core.prefs
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/bnd.bnd
  dev/io.openliberty.org.bouncycastle.bcprov-jdk18on/bnd.overrides
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.classpath
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.gitignore
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.project
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.settings/bndtools.core.prefs
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/bnd.bnd
  dev/io.openliberty.org.bouncycastle.bcutil-jdk18on/bnd.overrides
Labels: CLA Signed

#25673 update oidc provider config attribute descriptions
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed, L2 ReviewNotRequired, ID waiting on development

#25713 JAX-WS: SOAP Attributes- prefix cannot be null when creaing QName Error
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/soapEnvelopePrefix/src/com/ibm/ws/jaxws/test/soapenv/prefix/SoapEnvelopePrefixTestServlet.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/ReadHeadersInterceptor.java
Labels: CLA Signed

#25721 Issue #25712: Fix NPE in deferred injection processing
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/naming/DeferredNonCompInjectionJavaColonHelper.java
Labels: team:Zombie Apocalypse, in:Java EE Platform, CLA Signed

#25518 Create ECJ/JDT Bundles for Java 11 & 17
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.2/com.ibm.websphere.appserver.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.3/com.ibm.websphere.appserver.jsp-2.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.0/io.openliberty.pages-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.1/io.openliberty.pages-3.1.feature
  dev/com.ibm.ws.org.eclipse.jdt.core/bnd.bnd
  dev/io.openliberty.org.eclipse.jdt.core.java11/.classpath
  dev/io.openliberty.org.eclipse.jdt.core.java11/.gitignore
  dev/io.openliberty.org.eclipse.jdt.core.java11/.project
  dev/io.openliberty.org.eclipse.jdt.core.java11/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java11/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java11/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java11/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java11/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java11/bnd.bnd
  dev/io.openliberty.org.eclipse.jdt.core.java17/.classpath
  dev/io.openliberty.org.eclipse.jdt.core.java17/.gitignore
  dev/io.openliberty.org.eclipse.jdt.core.java17/.project
  dev/io.openliberty.org.eclipse.jdt.core.java17/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java17/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java17/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java17/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java17/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.eclipse.jdt.core.java17/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#25725 Resubmit update to Weld 5.1.1 but use SP1 instead of Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.0/io.openliberty.cdi-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.1/io.openliberty.cdi-4.1.feature
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.classpath
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.gitignore
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.project
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.settings/bndtools.core.prefs
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.jboss.classfilewriter.1.3/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.jboss.classfilewriter.1.3/bnd.bnd
  dev/io.openliberty.org.jboss.classfilewriter.1.3/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/README
  dev/io.openliberty.org.jboss.weld5/bnd.bnd
  dev/io.openliberty.org.jboss.weld5/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.template
  dev/io.openliberty.org.jboss.weld5/build.gradle
  dev/io.openliberty.org.jboss.weld5/check-me-in-if-i-change.bnd
Labels: CLA Signed

#25722 create test bucket for validation
  dev/io.openliberty.data.internal_fat_validation/.classpath
  dev/io.openliberty.data.internal_fat_validation/.project
  dev/io.openliberty.data.internal_fat_validation/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_validation/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_validation/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_validation/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_validation/bnd.bnd
  dev/io.openliberty.data.internal_fat_validation/build.gradle
  dev/io.openliberty.data.internal_fat_validation/fat/src/test/jakarta/data/validation/DataValidationTest.java
  dev/io.openliberty.data.internal_fat_validation/fat/src/test/jakarta/data/validation/FATSuite.java
  dev/io.openliberty.data.internal_fat_validation/publish/servers/io.openliberty.data.internal.fat.validation/bootstrap.properties
  dev/io.openliberty.data.internal_fat_validation/publish/servers/io.openliberty.data.internal.fat.validation/server.xml
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/resources/WEB-INF/classes/META-INF/persistence.xml
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Assertions.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creature.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creatures.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Entitlement.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Entitlements.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Rectangle.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Rectangles.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25654 Update testcontainers
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/resources/META-INF/services/org.testcontainers.dockerclient.DockerClientProviderStrategy
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalDockerClientFilter.java
  dev/fattest.simplicity/src/componenttest/containers/ExternalDockerClientStrategy.java
  dev/fattest.simplicity/src/componenttest/containers/ImageVerifier.java
  dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryImageNameSubstitutorTest.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryRegistryTest.java
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/images
Labels: team:Zombie Apocalypse, CLA Signed

#25718 Update features to use common bundles
  dev/com.ibm.websphere.appserver.features/visibility/public/acmeCA-2.0/com.ibm.websphere.appserver.acmeCA-2.0.feature
  dev/com.ibm.ws.security.acme/bnd.bnd
Labels: CLA Signed

#25685 Remove Equinox overlay
  dev/org.eclipse.osgi/.classpath
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/BundleLoader.java
Labels: CLA Signed

#25727 PR for Issue 22358: Update check on redirect URL obtained from WASReqUrlSocial cookie
  dev/com.ibm.ws.security.social/resources/com/ibm/ws/security/social/resources/SocialMessages.nlsprops
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/web/EndpointServices.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/test/CommonTestClass.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/web/EndpointServicesTest.java
Labels: ID reviewed, CLA Signed, team:Security SSO

#25711 update SpnegoHelper javadoc
  dev/com.ibm.ws.security.kerberos.java8/src/com/ibm/websphere/security/s4u2proxy/SpnegoHelper.java
Labels: CLA Signed

#25606 Update Eclipselink from 4.0.1 to 4.0.2.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/weaving/PersistenceWeaver.java
Labels: CLA Signed

#25742 change netty library versions to add Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: in:Transport, CLA Signed, team:Sirius

#25736 Readd Changes for 25167 and Cleanup of CXF Upgrade
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.xml.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/CachedTime.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/JAXRSOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs/utils/test/JAXRSOutInterceptorTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/org/apache/cxf/jaxrs/interceptor/CachedTimeAccessor.java
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/src/org/apache/cxf/ws/security/cache/CXFEHCacheReplayCache.java
Labels: CLA Signed

#25738 PR for Issue 19029: Remove beta guards for OIDC PKCE support
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp.pkce/jvm.options
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.3/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social.pkce/jvm.options
Labels: CLA Signed, team:Security SSO

#25684 Temp overlay to fix SCR for dynamic greedy references
  dev/com.ibm.ws.org.apache.felix.scr/.classpath
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
  dev/com.ibm.ws.org.apache.felix.scr/src/org/apache/felix/scr/impl/manager/DependencyManager.java
Labels: CLA Signed

#25733 Remove older bouncycastle references
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jaxrs.2.0.client_fat/build.gradle
  dev/com.ibm.ws.jaxrs.2.1.client_fat/build.gradle
  dev/fattest.simplicity/bnd.bnd
Labels: CLA Signed

#25466 Make earlyMessageTraceKiller_Timer a daemon thread
  dev/com.ibm.ws.logging.core/src/com/ibm/ws/collector/manager/buffer/BufferManagerEMQHelper.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
Labels: CLA Signed

#25746 Git, bnd and eclipse settings updates
  .gitignore
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.servlet.3.1/bnd.bnd
  dev/com.ibm.ws.bnd.annotations/bnd.bnd
  dev/com.ibm.ws.cdi.third.party_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.beanvalidation/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.client/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.concurrent/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.ejb/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.managedbeans/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.server/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_db2/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.microprofile.opentracing.jaeger_fat/bnd.bnd
  dev/com.ibm.ws.security.fat.common.mp.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.builder/bnd.bnd
  dev/com.ibm.ws.security.jwt_fat.consumer/bnd.bnd
  dev/com.ibm.ws.security.oauth.oidc_fat.common/bnd.bnd
  dev/com.ibm.ws.security.oauth_fat/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oauth/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oidc/bnd.bnd
  dev/com.ibm.ws.wssecurity.3.4.1/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.3/bnd.bnd
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/bnd.bnd
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat_persistence/bnd.bnd
  dev/io.openliberty.org.eclipse.jdt.core.java11/bnd.bnd
  dev/io.openliberty.org.eclipse.jdt.core.java17/bnd.bnd
  dev/io.openliberty.org.eclipse.jnosql.1.0/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.jnosql.1.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/bnd.bnd
Labels: CLA Signed, team:Performance

#25756 Add cssparser to the required libraries list for spnego test
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
Labels: noproductcode, CLA Signed, team:Performance

#25740 Reduce BC jars size for install
  dev/com.ibm.ws.install/bnd.bnd
Labels: CLA Signed

#25757 Enable tests on Java 8
  dev/com.ibm.ws.wsat.recovery_fat.single.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.single.2/fat/src/suite/FATSuite.java
Labels: noproductcode, CLA Signed

#25758 upgrade protobuf to 3.23.4
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppNameRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/AppResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/Creator.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/DeleteRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/DeleteResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/GenreCountResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/GenreCounts.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/GenreRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/MultiCreateResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/NameResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/Price.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/PriceResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/PurchaseRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/RetailApp.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/RetailAppResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamReplyA.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/test/g3store/grpc/StreamRequestA.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/Beer.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/BeerResponse.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/beer/service/RequestedBeerType.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/streaming/service/StreamReply.java
  dev/com.ibm.ws.grpc_fat/generated-src/com/ibm/ws/grpc/fat/streaming/service/StreamRequest.java
  dev/com.ibm.ws.grpc_fat/generated-src/io/grpc/examples/helloworld/HelloReply.java
  dev/com.ibm.ws.grpc_fat/generated-src/io/grpc/examples/helloworld/HelloRequest.java
  dev/io.openliberty.grpc.1.0.internal.client.monitor/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.common/bnd.bnd
  dev/io.openliberty.grpc.1.0.internal.monitor/bnd.bnd
Labels: CLA Signed

#25774 Fix TCKUtilities.useArtifactory()
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKUtilities.java
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/ChecksumTest.java
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/DependencyParserTest.java
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/TCKUtilitiesTest.java
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/dependency.txt
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/windowsDependency.txt
  dev/wlp-gradle/subprojects/fat.gradle
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#25798 Update spelling of Expression in Expression Language 5.0 FAT
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#25806 Fix maven central badge link
  README.md
Labels: noproductcode, CLA Signed

#25793 Fix trailing comma in feature files
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.0/io.openliberty.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.1/io.openliberty.restfulWS-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-4.0/io.openliberty.restfulWS-4.0.feature
Labels: CLA Signed, team:Performance

#25799 Adjust timeouts
  dev/com.ibm.ws.wsat.migration_fat.1/test-applications/simpleClient/src/web/simpleclient/SimpleClientServlet.java
Labels: noproductcode, CLA Signed

#25787 experiment with bean for default instance
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyResourceBean.java
Labels: team:Zombie Apocalypse, CLA Signed

#25815 Fix int parse error for java 1.8 in FeatureAuditor
  dev/com.ibm.ws.springboot.support.shutdown/src/com/ibm/ws/springboot/support/shutdown/FeatureAuditor.java
Labels: CLA Signed

#25802 Allow a longer connection timeout
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseOpenIdConfig.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25803 Allow more time for the JWT Builder to run secureRandom
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/actions/JwtBuilderActions.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#25807 Enable FAT trace for client JMS1Container
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/publish/clients/com.ibm.ws.open_clientcontainer.fat.JMS1Container/bootstrap.properties
Labels: noproductcode, CLA Signed

#25750 Issue 21826: Update keyAliasName description for OIDC clients
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 ReviewNotRequired

#25801 Added initial delay for Netty quiesce verifier
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/impl/NettyFrameworkImpl.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/impl/NettyQuiesceListener.java
Labels: in:Transport, CLA Signed, team:Sirius

#25805 Issue #25804: Add sun.nio.ch to java9.options
  dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options
Labels: CLA Signed

#25837 Use containsKey rather than the Groovy specific hasProperty
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#25840 Incorrect default for session cache id property
  dev/com.ibm.ws.session.db/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed
