Repository OpenLiberty/open-liberty, pull requests merged in 2023-03, with the labels that each got.

#23859 Fix to missing class exception when using lambdas
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#24495 281155 Batch CDI FAT: Increase DB tran timeout
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/resources/TranTimeoutCleanupBefore.xml
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/resources/TranTimeoutCleanupBeforePartition.xml
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/resources/TranTimeoutCleanupBeforeSplitFlow.xml
Labels: noproductcode, CLA Signed

#24489 Avoid timing issues with Oracle custom logging
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleCustomTrace.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#24446 Create Jakarta securityContext.authenticate tests
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/MessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/publish/shared/config/RPJava2Permissions.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonAnnotatedSecurityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/OpenIdContextExpectationHelpers.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/ResponseValues.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/ServletMessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/WsSubjectExpectationHelpers.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseCallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/utils/OpenIdContextLogger.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/utils/RequestLogger.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/utils/ServletLogger.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/SimpleServlet.war/src/oidc/client/simple/servlets/SimpleServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/AuthenticationTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/openIdConfig.properties
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/servers/jakartasec-3.0_fat.rp/bootstrap.properties
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/oidcProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppInjectServlet.war/src/oidc/authAppInjection/servlets/AuthenticationAppServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppInjectServlet.war/src/oidc/authAppInjection/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppInjectServlet.war/src/oidc/authAppInjection/servlets/OpenIdConfig.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppNoInjectServlet.war/src/oidc/authAppNoInjection/servlets/AuthenticationAppServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppNoInjectServlet.war/src/oidc/authAppNoInjection/servlets/CallbackServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppNoInjectServlet.war/src/oidc/authAppNoInjection/servlets/OpenIdConfig.java
Labels: CLA Signed, team:Security SSO, test delivery, jakartaEE10

#24509 Singleton monitor dump and FFDC improvements
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonMonitor.java
  dev/com.ibm.ws.webcontainer.security/bnd.bnd
Labels: CLA Signed

#24318 Add all faces context parameter rules for transformation
  dev/wlp-jakartaee-transform/rules/jakarta-xml-dd.properties
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24497 Avoid resource injection for inferred datasources on IBMi
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/servers/com.ibm.ws.jdbc.fat.sqlserver/server.xml
  dev/com.ibm.ws.jdbc_fat_sqlserver/test-applications/sqlserverfat/src/web/SQLServerTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#24500 Support federated registry with InstantOn
  dev/com.ibm.websphere.appserver.features/visibility/public/federatedRegistry-1.0/com.ibm.websphere.appserver.federatedRegistry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/ldapRegistry-3.0/com.ibm.websphere.appserver.ldapRegistry-3.0.feature
  dev/com.ibm.ws.security.wim.adapter.ldap/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapAdapter.java
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/build.gradle
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/URAPIs_Federation_2LDAPsTest.java
  dev/io.openliberty.checkpoint_fat/publish/files/internalfeatures/securitylibertyinternals-1.0.mf
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.federation/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.federation/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.federation/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.federation/server.xml
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#24491 Remove spring boot 1.5.x test application project and use the pre-built artifact in FAT
  dev/com.ibm.ws.springboot.support.version15.test.app/.classpath
  dev/com.ibm.ws.springboot.support.version15.test.app/.gitignore
  dev/com.ibm.ws.springboot.support.version15.test.app/.project
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/MimeMappingCustomizer.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/file.weby
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
Labels: CLA Signed

#24520 Revert "Remove spring boot 1.5.x test application project and use the pre-built artifact in FAT"
  dev/com.ibm.ws.springboot.support.version15.test.app/.classpath
  dev/com.ibm.ws.springboot.support.version15.test.app/.gitignore
  dev/com.ibm.ws.springboot.support.version15.test.app/.project
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/springboot.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/MimeMappingCustomizer.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/file.weby
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
Labels: CLA Signed

#24414 Retry Gradle version update
  .ci-orchestrator/compile.properties
  .ci-orchestrator/compilePersonalRTC.properties
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/scheduledPersonalBuilds.yml
  dev/.gradle-wrapper/gradle-wrapper.properties
  dev/build.image/build.gradle
  dev/build.pii.package/build.gradle
  dev/cnf/build.gradle
  dev/com.ibm.websphere.appserver.features/build.gradle
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jbatch.fat.common/build.gradle
  dev/com.ibm.ws.jbatch.open_fat/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.1/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.2/build.gradle
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/build.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/SAMLCommon.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/ShibbolethCommon.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/build.gradle
  dev/com.ibm.ws.security.social_fat.LibertyOP.2/build.gradle
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/build.gradle
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/springboot.gradle.disabled
  dev/com.ibm.ws.springboot.support.version20.test.actuator.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.java.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.multi.context.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.war.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webanno.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.webflux.app/build.gradle
  dev/com.ibm.ws.springboot.support.version20.test.websocket.app/bnd.bnd
  dev/com.ibm.ws.springboot.support.version20.test.websocket.app/build.gradle
  dev/com.ibm.ws.springboot.support_fat/bnd.bnd
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CDITests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15Servlet40.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPage15Test.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/InvalidAppTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MimeMapping15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingSslFeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot15FeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UnsupportedConfigWarningTest15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UseDefaultHostTest15.java
  dev/com.ibm.ws.transport.iiop.open_fat/build.gradle
  dev/settings.gradle
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#24485 Run SkipIfCheckpointNotSupportedAnnotationTest on Linux only
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SkipIfCheckpointNotSupportedAnnotationTest.java
Labels: noproductcode, CLA Signed

#23364 Discoverable embedded pom's
  dev/build.cleanPom/.classpath
  dev/build.cleanPom/.gitignore
  dev/build.cleanPom/.project
  dev/build.cleanPom/.settings/bndtools.core.prefs
  dev/build.cleanPom/.settings/org.eclipse.core.resources.prefs
  dev/build.cleanPom/.settings/org.eclipse.jdt.core.prefs
  dev/build.cleanPom/.settings/org.eclipse.jdt.ui.prefs
  dev/build.cleanPom/bnd.bnd
  dev/build.cleanPom/src/io/openliberty/process/PostProcessBNDPom.java
  dev/cnf/build.bnd
  dev/cnf/build.gradle
  dev/com.ibm.ws.openapi.ui/bnd.bnd
  dev/com.ibm.ws.springboot.support.shutdown/bnd/springBootCloser.bnd
  dev/com.ibm.ws.springboot.support.web.server.version15/bnd/springBoot15Server.bnd
  dev/com.ibm.ws.springboot.support.web.server.version20/bnd/springBoot20Server.bnd
  dev/com.ibm.ws.ui.tool.explore/bnd.bnd
  dev/com.ibm.ws.ui.tool.explore/package-lock.json
  dev/com.ibm.ws.ui.tool.explore/package.json
  dev/com.ibm.ws.ui.tool.javaBatch/bnd.bnd
  dev/com.ibm.ws.ui.tool.javaBatch/package-lock.json
  dev/com.ibm.ws.ui.tool.javaBatch/package.json
  dev/com.ibm.ws.ui.tool.serverConfig/bnd.bnd
  dev/com.ibm.ws.ui.tool.serverConfig/package-lock.json
  dev/com.ibm.ws.ui.tool.serverConfig/package.json
  dev/com.ibm.ws.ui/main.bnd
  dev/com.ibm.ws.ui/package-lock.json
  dev/com.ibm.ws.ui/package.json
  dev/io.openliberty.com.google.gson/bnd.bnd
  dev/io.openliberty.com.google.gson/bnd.overrides
  dev/wlp-gradle/bndSettings.gradle
  dev/wlp-gradle/subprojects/assemble.gradle
Labels: CLA Signed

#24528 Revert checking for committed response for issue #24525
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/AuthenticateApiTest.java
Labels: CLA Signed

#24496 Update FeatureList and EsaResourceImpl for Java 20
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: team:Zombie Apocalypse, CLA Signed, Java 20

#24527 Use pre built spring boot 1.5.x artifact for FAT
  dev/com.ibm.ws.springboot.support.version15.test.app/.classpath
  dev/com.ibm.ws.springboot.support.version15.test.app/.gitignore
  dev/com.ibm.ws.springboot.support.version15.test.app/.project
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.support.version15.test.app/bnd.bnd.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/build.gradle.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/springboot.gradle.disabled
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/MimeMappingCustomizer.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestApplication.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/java/com/ibm/ws/springboot/support/version15/test/app/TestErrorPageRegistrar.java
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/defaultErrorPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/errorPageException.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/file.weby
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/public/noSuchPage.html
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-keystore.jks
  dev/com.ibm.ws.springboot.support.version15.test.app/src/main/resources/server-truststore.jks
  dev/com.ibm.ws.springboot.support_fat/build.gradle
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CDITests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests15Servlet40.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/ErrorPage15Test.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/InvalidAppTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/JavaeeFeatureTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MimeMapping15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingServletTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingSslFeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/NeedSpringBoot15FeatureTests.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLTests15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UnsupportedConfigWarningTest15.java
  dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/UseDefaultHostTest15.java
Labels: CLA Signed

#24518 Make SSO FATs handle infrastructure issues better wrt junit reporting
  dev/com.ibm.ws.security.fat.common/.classpath
  dev/com.ibm.ws.security.fat.common/bnd.bnd
  dev/com.ibm.ws.security.fat.common/fat/src/com/ibm/ws/security/fat/common/AlwaysRunAndPassTest.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/ldaputils/CommonAltRemoteLDAPServerSuite.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/ldaputils/CommonLocalLDAPServerSuite.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/ldaputils/CommonRemoteLDAPServerSuite.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/FATSuite.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.1/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.0/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.jwtsso_fat.noMpJwt/fat/src/com/ibm/ws/security/jwtsso/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.envVars/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.sysProps/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.envVars/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.sysProps/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.envVars/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.sysProps/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.envVars/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.sysProps/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/mp/jwt11/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/mp/jwt12/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.commonTest/fat/src/com/ibm/ws/security/mp/jwt21/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1/fat/src/com/ibm/ws/security/mp/jwt21/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2/fat/src/com/ibm/ws/security/mp/jwt21/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0/fat/src/com/ibm/ws/security/mp/jwt21/fat/FATSuite.java
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1/fat/src/com/ibm/ws/security/mp/jwt21/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.spnego/fat/src/com/ibm/ws/security/openidconnect/client_fat/spnego/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.noOP/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.oauth/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/oidc/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.spnego/fat/src/com/ibm/ws/security/openidconnect/server/fat/spnego/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/fat/src/com/ibm/ws/security/saml/fat/logout/IDPInitiated/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/fat/src/com/ibm/ws/security/saml/fat/logout/httpServletRequest/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/fat/src/com/ibm/ws/security/saml/fat/logout/ibmSecurityLogout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
Labels: test debt, CLA Signed, team:Security SSO

#24374 Enable testCDIManagedProperty for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/CDIManagedProperty.war/resources/index.xhtml
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/CDIManagedProperty/resources/index.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24345 Enable testUIRepeatCondition for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23UIRepeatConditionTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/UIRepeatConditionCheck.war/resources/UIRepeatBeginEnd.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24516 Prevent mp rest client tck from running on slow windows machines, avoiding bogus build-break defects
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client13_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client14_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/AsyncMethodTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicEJBTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/BasicTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CdiPropsAndProvidersTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CollectionsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HandleResponsesTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagation12Test.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HeaderPropagationTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/HostnameVerifierTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/JsonbContextTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/MultiClientCdiTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/ProduceConsumeTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/PropsTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/com.ibm.ws.microprofile.rest.client_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/FATSuite.java
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
Labels: noproductcode, CLA Signed

#24531 Update java.gradle for JDK 20
  dev/wlp-gradle/java.gradle
Labels: noproductcode, team:Blizzard, CLA Signed, Java 20

#24551 Enable testFlowMap in Faces 4.0 FAT bucket
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AnnotationLiteralsTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/annotationLiterals.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlow/testFlow.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlow/testFlow2.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlowNext/testFlowNext.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/AnnotationLiteralsTest.war/resources/testFlowNext/testFlowNext2.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24549 Enable testExternalContextGetRealPath_Startup_Shutdown for EE10
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23ExternalContextStartupShutdownTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24517 Update Faces to 4.0.0 Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.faces.4.0/.classpath
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.LICENSE.txt
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.LICENSE.txt
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/HtmlCommandScriptRenderer.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/resource/FacesJSResourceLoader.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24553 Update comment for skipped test
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24547 Enabled view scope pre destroy test faces40
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopedCDIBean.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopedJSFBean.war/resources/index.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24545 Add time for Leap Day on Renew Acme FAT
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeValidityAndRenewTest.java
Labels: noproductcode, CLA Signed

#24542 Test passwordUtilities-1.1 with InstantOn
  dev/com.ibm.websphere.appserver.features/visibility/public/passwordUtilities-1.1/com.ibm.websphere.appserver.passwordUtilities-1.1.feature
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/PasswordUtilsTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.auth.data.fat.dpm.pu11/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.auth.data.fat.dpm.pu11/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.auth.data.fat.dpm.pu11/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/com.ibm.ws.security.auth.data.fat.dpm.pu11/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/DefaultPrincipalMappingApp/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat/test-applications/DefaultPrincipalMappingApp/src/io/openliberty/checkpoint/fat/passwordutil/web/DefaultPrincipalMappingServlet.java
Labels: CLA Signed

#24554 Avoid tests buckets timing out by changing to allow only a sub-set of the tests to run on slow hardware.
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#24093 Issue 24092: Prevent aborted connections from invoking endRequest and end during cleanup/destroy.
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
  dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed, release bug

#24567 Issue 24566: Set IBM Provider on ACME Revocation checks on hybrid JDK
  dev/com.ibm.ws.security.acme/src/com/ibm/ws/security/acme/internal/CertificateRevocationChecker.java
Labels: CLA Signed

#24507 serverConfig - retrieve file list under configDropins for admin role only
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/fileExplorer.js
Labels: CLA Signed, team:Admin Center

#24440 Clear injection contexts for the error path in a catch block instead of finally
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/.classpath
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/EJBSubResourceTest.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/io.openliberty.jaxrs.fat.ejbsubresource/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/io.openliberty.jaxrs.fat.ejbsubresource/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/publish/servers/io.openliberty.jaxrs.fat.ejbsubresource/server.xml
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/ejbsubresource/src/io/openliberty/jaxrs/ejbsubresource/EJBSubResourceApplication.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/ejbsubresource/src/io/openliberty/jaxrs/ejbsubresource/EJBSubResourceClientTestServlet.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/ejbsubresource/src/io/openliberty/jaxrs/ejbsubresource/ILocalSingletonBean.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/ejbsubresource/src/io/openliberty/jaxrs/ejbsubresource/LocalSingletonBean.java
  dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/ejbsubresource/src/io/openliberty/jaxrs/ejbsubresource/SingletonRootResource.java
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsInvoker.java
  dev/com.ibm.ws.jaxrs.2.0.server/src/com/ibm/ws/jaxrs20/server/LibertyJaxRsServerFactoryBean.java
Labels: in:JAX-RS, CLA Signed

#24544 log error if jwks read or connect timeout is negative
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/JakartaSec30Constants.java
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/OpenIdAuthenticationMechanismDefinitionWrapper.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationSigningTests.java
Labels: CLA Signed

#24564 Update jwks read timeout in ProviderMetadata app
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/test-applications/ProviderMetadata.war/src/providerMetadata/servlets/ProviderMetadataServlet.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24572 Update testACPNavigationRule for EE10
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AppConfigPopTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22AppConfigPop.war/resources/nav.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24574 Enable testClientWindowReuseInFlow
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/ClientWindowScopedTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ClientWindowScopedTest.war/resources/clientWindowCount.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ClientWindowScopedTest.war/resources/clientWindowHierarchy.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ClientWindowScopedTest.war/resources/confirm/confirm.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/ClientWindowScopedTest.war/resources/confirmNext/confirmNext.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24568 Update java requirement for mpJwt 2.1 FATs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.commonTest/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0/bnd.bnd
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1/bnd.bnd
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24418 Ported JNDI FAT Tests
  dev/com.ibm.ws.jndi.open_fat/.classpath
  dev/com.ibm.ws.jndi.open_fat/.project
  dev/com.ibm.ws.jndi.open_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jndi.open_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jndi.open_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jndi.open_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jndi.open_fat/bnd.bnd
  dev/com.ibm.ws.jndi.open_fat/build.gradle
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/FATSuite.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/JNDIEntryTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/JNDIFeatureTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/JNDIGlobalRefTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/JNDIGlobalTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/JNDIURLEntryTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/ParentLastJndiTests.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/ServletMethodRunner.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/Util.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/data/AppName.java
  dev/com.ibm.ws.jndi.open_fat/fat/src/com/ibm/ws/jndi/global/fat/data/ServletName.java
  dev/com.ibm.ws.jndi.open_fat/publish/files/JNDIEntryUpdate/IDUpdate.xml
  dev/com.ibm.ws.jndi.open_fat/publish/files/JNDIEntryUpdate/uncommentedServer.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_decode/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_decode/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_dynamic_update/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_dynamic_update/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_dynamic_update/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_fat/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_id_update/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_id_update/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_entry_id_update/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_global_ref_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_global_ref_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_fat/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_unknown_fat/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_unknown_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/jndi_url_entry_unknown_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/publish/servers/parentlast_fat/.gitignore
  dev/com.ibm.ws.jndi.open_fat/publish/servers/parentlast_fat/bootstrap.properties
  dev/com.ibm.ws.jndi.open_fat/publish/servers/parentlast_fat/server.xml
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiEntry.war/package.properties
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiEntry.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiEntry.war/src/com/ibm/ws/jndi/fat/web/ReadJndiEntry.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiURLEntry.war/package.properties
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiURLEntry.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jndi.open_fat/test-applications/ReadJndiURLEntry.war/src/com/ibm/ws/jndi/fat/web/ReadJndiURLEntry.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/factory.jar/package.properties
  dev/com.ibm.ws.jndi.open_fat/test-applications/factory.jar/src/com/ibm/ws/jndi/fat/factory/ObjectFactoryImpl.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/jndi-global.war/package.properties
  dev/com.ibm.ws.jndi.open_fat/test-applications/jndi-global.war/src/com/ibm/ws/jndi/global/fat/web/JNDIRefTestServlet.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/jndi-global.war/src/com/ibm/ws/jndi/global/fat/web/JNDITestServlet.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/jndi-global.war/src/com/ibm/ws/jndi/global/fat/web/MockICF.java
  dev/com.ibm.ws.jndi.open_fat/test-applications/parentLast.war/package.properties
  dev/com.ibm.ws.jndi.open_fat/test-applications/parentLast.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jndi.open_fat/test-applications/parentLast.war/src/com/ibm/ws/jndi/fat/parentlast/ParentLastJndiServlet.java
Labels: noproductcode, CLA Signed

#24587 Export org.apache.myfaces.util.lang to thread-context for faces 4.0
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24557 Enable MyFaces-4433 test for ee10
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIConfigByACP.jar/src/com/ibm/ws/jsf22/fat/cdiconfigbyacp/jar/ACPJarInitializer.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIConfigByACP.war/src/com/ibm/ws/jsf22/fat/cdiconfigbyacp/ACPWarInitializer.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/CountBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/MixedNested1.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/ProgrammaticSwitch.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/SimpleFlowBuilder.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/TestBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/CDIFacesFlows.war/src/com/ibm/ws/jsf22/fat/cdiflows/beans/TestBeanInitFinalize.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ClientWindow.war/src/com/ibm/ws/jsf22/fat/clientwindow/jsf22/EmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22ClientWindowFaces40.war/src/com/ibm/ws/jsf22/fat/clientwindow/faces40/EmployeeBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22FacesFlows.war/src/com/ibm/ws/jsf22/fat/flows/beans/faces40/InitializerBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/JSF22FacesFlows.war/src/com/ibm/ws/jsf22/fat/flows/beans/jsf22/InitializerBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI30335.jar/src/com/ibm/ws/jsf22/fat/tests/PI30335/ManagedBean1.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI30335.jar/src/com/ibm/ws/jsf22/fat/tests/PI30335/ManagedBean2.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI46218Flow1.war/src/com/ibm/ws/jsf22/fat/PI46218Flow1/FlowBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI46218Flow1.war/src/com/ibm/ws/jsf22/fat/PI46218Flow1/flows/FlowFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI46218Flow2.war/src/com/ibm/ws/jsf22/fat/PI46218Flow2/beans/FlowBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI46218Flow2.war/src/com/ibm/ws/jsf22/fat/PI46218Flow2/flows/FlowFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI47600.war/src/com/ibm/ws/jsf22/fat/tests/PI47600/InputTextWithClass.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI57255CDI.war/src/com/ibm/ws/jsf22/fat/PI57255/beans/FlowBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI57255CDI.war/src/com/ibm/ws/jsf22/fat/PI57255/flows/FlowFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI59422.war/src/com/ibm/ws/jsf22/fat/PI59422/FlowBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI59422.war/src/com/ibm/ws/jsf22/fat/PI59422/FlowFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI59422.war/src/com/ibm/ws/jsf22/fat/PI59422/FlowManager.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI63135.war/src/com/ibm/ws/jsf22/fat/PI63135/EmptyToNullStringELResolver.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64714.war/src/com/ibm/ws/jsf22/fat/PI64714/IndexBeanPI64714.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64718.war/src/com/ibm/ws/jsf22/fat/PI64718/ArraySizeValidation.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64718.war/src/com/ibm/ws/jsf22/fat/PI64718/ArraySizeValidator.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64718.war/src/com/ibm/ws/jsf22/fat/PI64718/IndexBeanPI64718.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64718.war/src/com/ibm/ws/jsf22/fat/PI64718/ListSizeValidation.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI64718.war/src/com/ibm/ws/jsf22/fat/PI64718/ListSizeValidator.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI67525.war/src/com/ibm/ws/jsf22/fat/PI67525/UploadBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI85492.war/src/com/ibm/ws/jsf22/fat/PI85492/TestExceptionHandler.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI85492.war/src/com/ibm/ws/jsf22/fat/PI85492/TestExceptionHandlerFactory.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI85492.war/src/com/ibm/ws/jsf22/fat/PI85492/TestPhaseListener.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI90507.war/src/com/ibm/ws/jsf22/fat/PI90507/MyBackingBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/PI90507.war/src/com/ibm/ws/jsf22/fat/PI90507/TestActionListener.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22ViewAction.war/src/com/ibm/ws/jsf22/fat/viewaction/faces40/NumberBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22ViewAction.war/src/com/ibm/ws/jsf22/fat/viewaction/jsf22/NumberBean.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22ViewAction.war/src/com/ibm/ws/jsf22/fat/viewaction/phaselistener/AnyPhaseListener.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22ViewAction.war/src/com/ibm/ws/jsf22/fat/viewaction/phaselistener/RenderResponsePhaseListener.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestJSF22ViewAction.war/src/com/ibm/ws/jsf22/fat/viewaction/phaselistener/RestoreViewPhaseListener.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestResourceContractsFromJar.war/src/com/ibm/ws/jsf22/fat/contractsfromjar/beans/faces40/PickContract.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/TestResourceContractsFromJar.war/src/com/ibm/ws/jsf22/fat/contractsfromjar/beans/jsf22/PickContract.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopeLeak.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopedCDIBean.war/src/com/ibm/ws/jsf22/fat/viewscopedcdi/ViewScopedBean2.java
  dev/com.ibm.ws.jsf.2.2_fat/test-applications/ViewScopedCDIBean.war/src/com/ibm/ws/jsf22/fat/viewscopedcdi/ViewScopedCDIBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24556 Use SoReuseAddr in JMS SecurityFat
  dev/com.ibm.ws.messaging.open_jms20security_fat/publish/files/JMSContext_ssl.xml
Labels: noproductcode, CLA Signed

#24581 Increase timeoutCushion for TCK timeout tests to account for slower h…
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/servers/FATServer/jvm.options
Labels: noproductcode, CLA Signed

#24602 OneToOne entities
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/ShippingAddresses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Driver.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Drivers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DriversLicense.java
Labels: team:Zombie Apocalypse, CLA Signed

#24479 fix and add additional testing for jakarta security 3.0 callback checks
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/MessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/servlets/BaseUnsecuredServlet.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationELValuesOverrideWithoutHttpSessionTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationPromptTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationResponseModeTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationScopeTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/FATSuite.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/AuthenticationEndpointValidationTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/BasicOIDCAnnotationUseRedirectToOriginalResourceTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/oidcProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotatedWithEL.war/src/oidc/client/withEL/servlets/OidcAnnotatedServletWithEL.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/SimplestAnnotatedWithEL.war/src/oidc/client/withEL/servlets/UnsecuredServlet.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthenticationResponseValidatorTest.java
Labels: CLA Signed

#24477 Additional FAT tests to validate libraryRef attribute of mpMetrics
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.classpath
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.project
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/fat/resources/logging.properties
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/fat/src/io/openliberty/microprofile/metrics50/internal/tck/launcher/FATSuite.java
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/fat/src/io/openliberty/microprofile/metrics50/internal/tck/launcher/LibraryRefTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerPrometheus/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerPrometheus/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerPrometheus/server.xml
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerUseless/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerUseless/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/MicrometerUseless/server.xml
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NoMicrometerCore/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NoMicrometerCore/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NoMicrometerCore/server.xml
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NonExistentLibrary/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NonExistentLibrary/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/publish/servers/NonExistentLibrary/server.xml
Labels: noproductcode, CLA Signed

#24530 Fix test failure in RTC 294713. The CustomSSLSocketFactory used for L…
  dev/fattest.simplicity/src/componenttest/topology/utils/CustomSSLSocketFactory.java
  dev/fattest.simplicity/src/componenttest/topology/utils/LDAPUtils.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#24630 Fix case for metatype
  dev/com.ibm.ws.cdi.weld/resources/OSGI-INF/l10n/metatype.properties
Labels: team:Performance

#24605 Add tested.features for iSeries
  dev/com.ibm.ws.transaction.cloud_fat.base/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.dualFS/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/bnd.bnd
Labels: noproductcode, CLA Signed

#24612 Uncomment gradle files (pull down source/javadoc jars)
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE10

#24623 Remove hard-coded port in test app annotation
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/RedirectToOriginalResourceTruePromptNone.war/src/oidc/client/redirectToOriginalResourceTruePromptNone/servlets/RedirectToOriginalResourceTruePromptNoneServlet.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, jakartaEE10

#24513 Avoid inferring datasources where not needed and skip tests not valid on IBM i
  dev/com.ibm.ws.jdbc_fat_db2/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
  dev/com.ibm.ws.jdbc_fat_db2/test-applications/db2fat/src/db2/web/DB2TestServlet.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle/server.xml
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oraclejdbcfat/src/web/OracleTestServlet.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/postgresql-test-server/server.xml
  dev/com.ibm.ws.jdbc_fat_postgresql/test-applications/postgresqlApp/src/jdbc/fat/postgresql/web/PostgreSQLTestServlet.java
Labels: noproductcode, CLA Signed

#24628 Use OpenIdContext instance in Subject instead of CDI proxy for issue #24622
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
Labels: CLA Signed

#24593 Update short token lifetime tests to avoid tokens expiring too soon
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/test-applications/BaseServlet.war/src/oidc/client/base/utils/ShortTokenLifetimePrep.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTokenMinValidityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/fat/src/io/openliberty/security/jakartasec/fat/logout/tests/BasicLogoutTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.refresh/fat/src/io/openliberty/security/jakartasec/fat/refresh/tests/BasicRefreshTests.java
Labels: noproductcode, CLA Signed, team:Security SSO, jakartaEE10

#24535 Issue #24534: Msg for wrong package Resource annotation
  dev/com.ibm.ws.container.service/resources/com/ibm/ws/container/service/resources/Messages.nlsprops
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/internal/AnnotationsImpl.java
  dev/io.openliberty.injection.jakarta_fat/.classpath
  dev/io.openliberty.injection.jakarta_fat/.project
  dev/io.openliberty.injection.jakarta_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.injection.jakarta_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.injection.jakarta_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.injection.jakarta_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.injection.jakarta_fat/bnd.bnd
  dev/io.openliberty.injection.jakarta_fat/fat/src/io/openliberty/injection/jakarta/fat/FATSuite.java
  dev/io.openliberty.injection.jakarta_fat/fat/src/io/openliberty/injection/jakarta/fat/tests/WrongPackageTest.java
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE10Server/bootstrap.properties
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE10Server/jvm.options
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE10Server/server.xml
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE9Server/bootstrap.properties
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE9Server/jvm.options
  dev/io.openliberty.injection.jakarta_fat/publish/servers/InjectionJakartaEE9Server/server.xml
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageEJB.jar/src/io/openliberty/injection/jakarta/ejb/JakartaSingletonBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageEJB.jar/src/io/openliberty/injection/jakarta/ejb/JakartaSingletonResourcesBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageEJB.jar/src/io/openliberty/injection/jakarta/ejb/JakartaStatefulPreDestroyBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageEJB.jar/src/io/openliberty/injection/jakarta/ejb/JakartaStatelessBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageWeb.war/src/io/openliberty/injection/jakarta/web/JakartaSingletonWarBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageWeb.war/src/io/openliberty/injection/jakarta/web/JakartaStatelessWarBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageWeb.war/src/io/openliberty/injection/jakarta/web/JakartaStatelessWarPostConstructBean.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageWeb.war/src/io/openliberty/injection/jakarta/web/WrongPackageServlet.java
  dev/io.openliberty.injection.jakarta_fat/test-applications/WrongPackageWebApp.war/src/io/openliberty/injection/jakarta/webapp/WrongPackageWebAppServlet.java
Labels: in:Java EE Platform, ID reviewed, team:Blizzard, CLA Signed, L2 Reviewed

#24569 check if extractDir is not a directory
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: noproductcode, CLA Signed

#24653 Fix up eclipse files from recent merges
  dev/build.featureStart.base/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.commonTest/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.commonTest/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1/.classpath
  dev/com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/.project
Labels: noproductcode, CLA Signed, team:Performance

#24654 add logservice trace to com.ibm.ws.cdi.jee_fat
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12JSFServer/server.xml
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12JSFWithSharedLibServer/server.xml
Labels: noproductcode, CLA Signed

#24514 Add util method to get interceptor bindings from invocation context
  dev/com.ibm.ws.cdi.extension_fat/bnd.bnd
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/InterceptedBean.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/InterceptedMethodsBean.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/InvocationContextTestServlet.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/MyInterceptor.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/MyInterceptorBinding.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/MyNonBindingInterceptor.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/MyNonBindingInterceptorBinding.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/apps/invocationContext/MyUnusedInterceptorBinding.java
  dev/com.ibm.ws.cdi.extension_fat/fat/src/com/ibm/ws/cdi/extension/tests/CDI12ExtensionTest.java
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.internals-1.2.mf
  dev/com.ibm.ws.cdi.extension_fat/publish/features/cdi.internals-3.0.mf
  dev/com.ibm.ws.cdi.interfaces/bnd.bnd
  dev/com.ibm.ws.cdi.interfaces/src/com/ibm/ws/cdi/CDIService.java
  dev/com.ibm.ws.cdi.internal/bnd.bnd
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/interfaces/CDIUtils.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/AbstractCDIRuntime.java
  dev/wlp-jakartaee-transform/rules/jakarta-renames.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed

#24649 querying and ordering on Many/One to One entity attributes
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCard.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customer.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Drivers.java
Labels: team:Zombie Apocalypse, CLA Signed

#24632 expose packages to thread-context to avoid de-serialization problems
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24571 Switch webAppSecurity-2.0 auto feature to a private feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.webAppSecurity-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-4.0/io.openliberty.appSecurity-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-5.0/io.openliberty.appSecurity-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpJwt-2.1/io.openliberty.mpJwt-2.1.feature
Labels: CLA Signed, team:Performance

#24570 Upgrade to commons-io:2.11.0 and commons-fileupload:1.5
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_source_dependencies.maven
  dev/cnf/resources/bnd/anttaskdefs.bnd
  dev/com.ibm.ws.org.apache.commons.fileupload/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.fileupload/bnd.overrides
  dev/com.ibm.ws.org.apache.commons.io/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
Labels: CLA Signed

#24610 Objectclass in filter should be case insensitive
  dev/com.ibm.ws.security.wim.adapter.ldap/src/com/ibm/ws/security/wim/adapter/ldap/LdapConfigManager.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
Labels: CLA Signed, team:Wendigo East, release bug

#24636 Fix passivation of CDI beans with injected Event
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi/lifecycle/apps/transientReferenceWithPersistenceWar/PassivationBean.java
  dev/com.ibm.ws.cdi.lifecycle_fat/fat/src/com/ibm/ws/cdi/lifecycle/apps/transientReferenceWithPersistenceWar/TestEvent.java
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.overrides
Labels: noproductcode, CLA Signed

#24657 Add timeout to docker engine ping
  dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
Labels: noproductcode, CLA Signed

#24640 Allow servers to be hit by a port scanner while tests are running
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestServer.java
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20TestCommon.java
Labels: test bug, CLA Signed, team:Security SSO

#24639 oidc client code updates
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtilTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/clients/common/OidcUtilTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/storage/CookieBasedStorage.java
  dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/storage/CookieBasedStorageTest.java
Labels: CLA Signed

#24635 add validate json to user input data for PUT
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/ToolDataAPI.java
Labels: CLA Signed

#24510 set headers on REST response
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/AdminCenterRouter.java
Labels: CLA Signed, team:Admin Center

#24591 Update filter tests to allow LdapAdapter activation
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.2/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegressionTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#24643 OIDC: Move RP-initiated logout (end_session) OP code into separate class
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogout.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogoutTest.java
Labels: CLA Signed, team:Security SSO

#24499 Only validate header name once (attempt #2)
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/genericbnf/internal/BNFHeadersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpTrailerGeneratorImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpTrailersImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpResponseImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/values/HttpHeaderKeys.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/channel/test/api/HttpRequestMessageImplTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/channel/test/api/HttpResponseMessageImplTest.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/channel/test/api/HttpTrailersImplTest.java
Labels: CLA Signed, team:Performance, performance

#24655 Sorting dataSet before calculating standard deviation
  dev/com.ibm.ws.monitor/src/com/ibm/websphere/monitor/meters/StatisticsMeter.java
Labels: CLA Signed

#24650 Update the JPA 3.1 FAT's QueryTimeFunction to skip if too close to mi…
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestNewQueryTimeFunctionsServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#24644 Update JPA FAT for DB2 z/OS testing
  dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/ddl/WEB-INF/classes/JPA_JPA31_ECLIPSELINK_CREATE_DB2ZOS.ddl
  dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/ddl/WEB-INF/classes/JPA_JPA31_ECLIPSELINK_DROP_DB2ZOS.ddl
  dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java
  dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh16772/src/com/ibm/ws/jpa/olgh16772/testlogic/JPATestOLGH16772Logic.java
  dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec20_fat.common/test-applications/olgh9339/src/com/ibm/ws/jpa/olgh9339/testlogic/JPATestOLGH9339Logic.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#24068 Re-enable FT Metrics test with MP6
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java
  dev/com.ibm.ws.microprofile.faulttolerance_repeat_tests/src/com/ibm/ws/microprofile/faulttolerance/fat/repeat/RepeatFaultTolerance.java
Labels: noproductcode, CLA Signed

#24661 Refactor RP-initiated logout code in OidcEndpointServices
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogout.java
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogoutTokenAndRequestData.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogoutTest.java
Labels: CLA Signed, team:Security SSO

#24669 Actually call the Java 20 FAT test
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java20Test.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 20

#24675 FixBuildBreakInJavaeesecFAT
  dev/com.ibm.ws.security.javaeesec_fat.4/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertFailOverTest.java
Labels: noproductcode, CLA Signed

#24667 Issue24666-FixBuildBreakInEJBContainerJACCFat
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/PureAnnMergeConflictXMLBindingsInWarEarTest.java
Labels: noproductcode, CLA Signed

#24660 Stop using SimpleDateFormat in CachedTime with CXF
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/interceptor/CachedTime.java
  dev/com.ibm.ws.jaxrs.2.0.common/test/com/ibm/ws/jaxrs/utils/test/JAXRSOutInterceptorTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/org/apache/cxf/jaxrs/interceptor/CachedTime.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/test/com/ibm/ws/jaxrs/utils/test/JAXRSOutInterceptorTest.java
Labels: CLA Signed, team:Performance, performance

#24063 Added testcase to test scheduled task execution with checkpoint and r…
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/ConcurrencyTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointConcurrency/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointConcurrency/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointConcurrency/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/concurrentApp/src/concurrentApp/ConcurrentApp.java
  dev/io.openliberty.checkpoint_fat/test-applications/concurrentApp/src/concurrentApp/RepeatedTrigger.java
Labels: noproductcode, CLA Signed

#24664 Reduce frequency of scheduled test pipelines and revert unittest step
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/scheduledPersonalBuilds.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#24576 Scanning improvements: filter InHouse Jars and test projects - upgrade dojo version
  dev/build.cleanPom/src/io/openliberty/process/PostProcessBNDPom.java
  dev/cnf/build.bnd
  dev/com.ibm.ws.ui.tool.explore/package-lock.json
  dev/com.ibm.ws.ui.tool.explore/package.json
  dev/com.ibm.ws.ui.tool.javaBatch/package.json
  dev/com.ibm.ws.ui.tool.serverConfig/package.json
  dev/com.ibm.ws.ui/package-lock.json
  dev/com.ibm.ws.ui/package.json
  dev/wlp-gradle/subprojects/assemble.gradle
Labels: CLA Signed

#24618 Port myfaces 4588
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.LICENSE.txt
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.LICENSE.txt
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.org.apache.myfaces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE10

#24684 Skip default logging tests in JSF 2.2 FAT
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#24462 Cleanup any asyncServlet non-daemon threads at the server shutdown
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#24695 Increase threshold for EE10 to avoid build-break under load.
  dev/com.ibm.ws.jaxrs.2.0_fat/test-applications/restmetrics/src/com/ibm/ws/jaxrs/fat/restmetrics/RestMetricsResource.java
Labels: noproductcode, CLA Signed

#24620 Use the application name in the cache name
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session.cache/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.server/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.serverB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerA/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/publish/servers/com.ibm.ws.session.cache.fat.infinispan.container.timeoutServerB/server.xml
  dev/com.ibm.ws.session.cache_fat_infinispan_container/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionProperties.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/SessionContextRegistryImpl.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#24676 Revert "FixBuildBreakInJavaeesecFAT"
  dev/com.ibm.ws.security.javaeesec_fat.4/fat/src/com/ibm/ws/security/javaeesec/fat/MultipleModuleGlobalClientCertFailOverTest.java
Labels: noproductcode, CLA Signed

#24699 PR for Issue 17842: Add asymmetric algorithm support to OIDC RP-initiated logout
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogoutTest.java
Labels: CLA Signed, team:Security SSO

#24659 Enable com.ibm.ws.microprofile.rest.client_fat to run on MP5.0 and 60 (EE9/EE10)
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/CdiPropsAndProvidersTest.java
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient10.remoteServer/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient11.cdiPropsAndProviders/server.xml
  dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/cdiPropsAndProvidersApp/src/mpRestClient11/cdiPropsAndProviders/CdiPropsAndProvidersTestServlet.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
Labels: CLA Signed

#24682 Add securityContext.authenticate test with expired token
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/AuthenticationTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/publish/shared/config/oidcProvider.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/test-applications/AuthAppInjectServlet.war/src/oidc/authAppInjection/servlets/AuthenticationAppServlet.java
Labels: noproductcode, test debt, CLA Signed, team:Security SSO, jakartaEE10

#24686 Moving logging tests to only run in FULL mode due to timeouts
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/FfdcCleanupTest.java
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
Labels: noproductcode, CLA Signed

#24687 Use separate RTC build definition to allow more builds to be kept
  .ci-orchestrator/compilePersonal.properties
  .ci-orchestrator/personalbuild.yml
  .ci-orchestrator/scheduledPersonalBuilds.yml
Labels: CLA Signed

#24663 AddAdditionalTraceToJACCPolicyConfig
  dev/com.ibm.ws.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/provider/AllPolicyConfigs.java
Labels: CLA Signed

#24704 Remove restConnector from jakarta ee 10 convenience feature.
  dev/build.image/profiles/jakartaee10/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-10.0/io.openliberty.jakartaee-10.0.feature
Labels: CLA Signed, team:Performance, target:23003

#24708 Revert "mpTelemetry-1.0 supersedes all open tracing features"
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.0/com.ibm.websphere.appserver.mpOpenTracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.1/com.ibm.websphere.appserver.mpOpenTracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.2/com.ibm.websphere.appserver.mpOpenTracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-1.3/com.ibm.websphere.appserver.mpOpenTracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-2.0/com.ibm.websphere.appserver.mpOpenTracing-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenTracing-3.0/io.openliberty.mpOpenTracing-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.0/com.ibm.websphere.appserver.opentracing-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.1/com.ibm.websphere.appserver.opentracing-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.2/com.ibm.websphere.appserver.opentracing-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-1.3/com.ibm.websphere.appserver.opentracing-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/opentracing-2.0/com.ibm.websphere.appserver.opentracing-2.0.feature
Labels: CLA Signed, target:23003

#24494 Test mpTelemetry with checkpoint/restore
  dev/io.openliberty.checkpoint_fat/.classpath
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/build.gradle
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPTelemetryTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPTelemetry/bootstrap.properties
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPTelemetry/jvm.options
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPTelemetry/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPTelemetry/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/mpTelemetry/src/mpTelemetry/MpTelemetryServlet.java
  dev/io.openliberty.checkpoint_fat/test-applications/mpTelemetry/src/mpTelemetry/microprofile-config.properties
Labels: noproductcode, CLA Signed

#24710 Set auth type when no processing is needed for expiration checks for issue #22940
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/src/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanism.java
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/test/io/openliberty/security/jakartasec/cdi/beans/OidcHttpAuthenticationMechanismTest.java
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/client/Client.java
Labels: CLA Signed

#24689 OneToMany with collection returned
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#24319 Transactional annotation for Jakarta Data
  dev/com.ibm.ws.transaction.cdi/bnd.bnd
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/TransactionalInterceptor.java
  dev/com.ibm.ws.transaction/bnd.bnd
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
Labels: team:Zombie Apocalypse, CLA Signed

#24711 PR for Issue 17842: Add unit tests for OIDC RP-initiated logout code
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcEndpointServices.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/OidcEndpointServicesTest.java
Labels: CLA Signed, team:Security SSO

#24706 Update tests to deal with slow responses for jaxrs client tests
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/CommonTests/JaxRSClientReAuthnTests.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/IBM/OidcJaxRSClientReAuthnTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24713 Fix test failure in RTC 293867. Add warning allowed server warning me…
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheDynamicUpdateTest.java
Labels: noproductcode, CLA Signed, team:Wendigo East

#24627 Fixes #24584
  dev/com.ibm.ws.http.plugin.merge/src/com/ibm/ws/http/plugin/merge/internal/PluginMergeToolImpl.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/FATSuite.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/PluginUtilityEndpointMergeTest.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/XMLCompare.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/fat/src/com/ibm/ws/webserver/plugin/utility/fat/XMLIssue.java
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test1/expected.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test1/source/plugin-cfg1.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test1/source/plugin-cfg2.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test2/expected.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test2/source/srv01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/test2/source/srv02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/expected.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/source/srv01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/source/srv02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/source/srv03-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/source/test-app01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-name/source/test-app02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/expected.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/source/srv01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/source/srv02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/source/srv03-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/source/test-app01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost-port/source/test-app02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/expected.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/source/srv01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/source/srv02-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/source/srv03-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/source/test-app01-plugin-cfg.xml
  dev/com.ibm.ws.webserver.plugin.utility_fat/publish/files/endpointtests/vhost/source/test-app02-plugin-cfg.xml
Labels: CLA Signed

#24729 Revert "Cleanup any asyncServlet non-daemon threads at the server shutdown"
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed

#24731 Update MP Telemetry Container filter.
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry/internal/rest/TelemetryContainerFilter.java
Labels: CLA Signed, team:Performance

#24383 Mark Long Running Transactions Rollback Only at Shutdown
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/LongTranTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/longtran/src/com/ibm/ws/longtran/web/LongtranServlet.java
Labels: CLA Signed

#24732 Add RESTEASY 3283 fix to liberty's RestEasy code
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/fat/src/io/openliberty/jakarta/rest31/tck/JakartaRest31TckPackageTest.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ResourceLocatorInvoker.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/registry/ConstantResourceInvoker.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/registry/SegmentNode.java
Labels: team:Performance

#24744 Invalid messages will hog thread
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/parser/MessageParser.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transport/connections/SIPConnectionAdapter.java
Labels: CLA Signed

#24728 24702: Extend timeouts
  dev/com.ibm.ws.transport.http2_fat/fat/src/com/ibm/ws/http2/client/SecureHttp2Client.java
Labels: in:Transport, noproductcode, CLA Signed

#24436 Quieten shutdown messaging for invalid transaction recovery logs
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/resources/com/ibm/ws/Transaction/resources/TransactionMsgs.nlsprops
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/FailureScopeController.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/PartnerLogTable.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryFailedException.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogImpl.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#24760 Debug if a request with session header is sent to /metrics
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/BaseMetricsRESTProxyServlet.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/rest/BaseMetricsRESTProxyServlet.java
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/servers/TestEDF5/bootstrap.properties
Labels: CLA Signed

#24739 stricter header for ui api
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/AdminCenterRouter.java
Labels: CLA Signed

#24750 Update Java 20 FAT WAR with GA Java 20 build
  dev/io.openliberty.java.internal_fat/publish/servers/java20-server/apps/io.openliberty.java.internal_fat_20.war
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 20

#24771 Added Title for All Search Icons
  dev/com.ibm.ws.ui.shared/resources/WEB-CONTENT/jsShared/utils/imgUtils.js
Labels: CLA Signed

#24753 Telemetry tck pom
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#24742 Rtc293555 jsp osgi
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12JSFServer/server.xml
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12JSFWithSharedLibServer/server.xml
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/webcontainerext/JSPExtensionFactory.java
Labels: CLA Signed

#24769 move JPA entities to Data JPA tests
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Package.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Person.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Prime.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Order.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/OrderRepo.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/ShippingAddress.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/ShippingAddresses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/StreetAddress.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Tariff.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Tariffs.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Tax.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/WorkAddress.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/WorkAddresses.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24763 ignore logging ffdc when securerandom with the SHA1PRNG algorithm fails
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/random/RandomUtils.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcUtil.java
Labels: CLA Signed

#24796 Add ExpectedFFDC for java.lang.UnsupportedOperationException
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointWithSecurityManager.java
Labels: noproductcode, CLA Signed

#24755 Wait for CWWK0103I message when using the rest connector
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/FeaturelistGeneratorMBeanTest.java
  dev/com.ibm.ws.kernel.filemonitor_fat/fat/src/com/ibm/ws/kernel/filemonitor/fat/FileNotificationMBeanTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#24743 Allow expired token during short token prep method call
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/ShortTokenLifetimePrep.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTokenMinValidityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/fat/src/io/openliberty/security/jakartasec/fat/logout/tests/BasicLogoutTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.refresh/fat/src/io/openliberty/security/jakartasec/fat/refresh/tests/BasicRefreshTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24723 Clear application metadata on init failure
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/SimpleDeployedAppInfoBase.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http2/GrpcServletServices.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServletApplication.java
  dev/io.openliberty.grpc.1.0.internal/test/io/openliberty/grpc/internal/servlet/GrpcServletTest.java
Labels: CLA Signed

#24745 Check for CWWKF0008I after feature update before proceeding
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/fat/src/com/ibm/ws/microprofile/metrics/monitor_fat/TestEnableDisableFeaturesTest.java
Labels: noproductcode, CLA Signed

#24773 Updates to OIDC back-channel logout token creation in line with the spec
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OAuth20TokenImpl.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/jose4j/JWTData.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/jose4j/JwsSigner.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/jose4j/util/EcJwkTest.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilder.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilderTest.java
Labels: CLA Signed, team:Security SSO

#24803 switch from data provider to CDI extension step
  dev/io.openliberty.data.internal.nosql/bnd.bnd
  dev/io.openliberty.data.internal.nosql/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/NoSQLDataProvider.java
  dev/io.openliberty.data.internal.nosql/src/io/openliberty/data/internal/nosql/QueryHandler.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PersistenceDataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/TemplateImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/TemplateProducer.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/package-info.java
  dev/io.openliberty.data.internal/bnd.bnd
  dev/io.openliberty.data.internal/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.data.internal/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/LibertyDataProvider.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/BeanDefiningAnnotationMetadata.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/DataExtensionMetadata.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/cdi/package-info.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/PalindromeExtension.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/PalindromeProvider.java
  dev/io.openliberty.data.internal_fat/test-applications/ProviderTestApp/src/test/jakarta/data/inmemory/provider/PalindromeRepositoryProducer.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/DataNoSQLServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/provider/DataProvider.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Repository.java
Labels: team:Zombie Apocalypse, CLA Signed

#24621 Organize Faces/JSF impl exports
  dev/com.ibm.ws.jsf.2.2/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.3.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius

#24805 PR for Issue 24804: Add support for encrypted internalClientSecret in OAuth
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/internal/LibertyOAuth20Provider.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/internal/LibertyOAuth20ProviderTest.java
Labels: CLA Signed, team:Security SSO

#24740 Jwks timeout tests fail on really slow machines
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/commonTests/CommonAnnotatedSecurityTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationSigningTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24832 remove synchronized from createSIPListenningConnection method to prevent deadlock
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transaction/transport/SIPConnectionsModel.java
Labels: CLA Signed, release bug

#24815 Change audit code to call secureRandom
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditCrypto.java
Labels: CLA Signed

#24821 Update com.ibm.ws.kernel.feature.resolver to Java 7.
  dev/com.ibm.ws.kernel.feature.resolver/.classpath
  dev/com.ibm.ws.kernel.feature.resolver/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.kernel.feature.resolver/bnd.bnd
  dev/com.ibm.ws.kernel.feature.resolver/build.gradle
  dev/wlp-gradle/java.gradle
Labels: CLA Signed, team:Performance

#24820 Add new WebContainer message
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 Reviewed

#24852 Allow additional ssl handshake error messages in negative test
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryErrorBadOpTrustStoreTests.java
Labels: noproductcode, test debt, CLA Signed, team:Security SSO

#24810 Update ToolboxPersistenceTest.java
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/CatalogPersistenceTest.java
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/ToolboxPersistenceTest.java
Labels: noproductcode, CLA Signed, team:Admin Center

#24703 get status from HttpServletRequest when not an instance of IExtendedResponse
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
Labels: CLA Signed

#24733 Cleanup AsyncContext non-daemon threads at server shutdown
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
Labels: CLA Signed

#24809 Update SAML tests for changes due to RFC 9110
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLCommonTestHelpers.java
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLConstants.java
  dev/com.ibm.ws.security.saml.sso_fat.common/src/com/ibm/ws/security/saml20/fat/commonTest/SAMLTestSettings.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/IDPInitiated/RSSamlIDPInitiatedMiscConfigTests.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/common/RSSamlAPITests.java
Labels: noproductcode, test debt, CLA Signed, team:Security SSO

#24836 Create com.ibm.ws.security.oidc.server_fat.oauth FAT project
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.classpath
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.project
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/bndtools.core.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.security.oidc.server_fat.oauth/bnd.bnd
  dev/com.ibm.ws.security.oidc.server_fat.oauth/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oauth/fat/src/com/ibm/ws/security/openidconnect/server/fat/oauth/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/CommonTests/genericWebClientAuthCertTest.java
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/misc.xml
Labels: noproductcode, test bug, test debt, CLA Signed, team:Security SSO

#24860 Remove unnecessary defaultKeyStore and avoid keytool issue
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/LDAPRegistry_customClaims.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/goodSSLSettings3.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#24725 Fixes #24565 - handle exception for getUserRegistry api call
  dev/com.ibm.websphere.security.impl/src/com/ibm/ws/security/intfc/internal/WSSecurityServiceImpl.java
  dev/com.ibm.websphere.security.impl/test/com/ibm/wsspi/security/registry/RegistryHelperTest.java
  dev/com.ibm.ws.security.registry/src/com/ibm/ws/security/registry/internal/UserRegistryServiceImpl.java
  dev/com.ibm.ws.security/src/com/ibm/ws/security/internal/SecurityServiceImpl.java
Labels: CLA Signed, team:Core Security

#24866 add ability to run test buckets against different databases
  dev/io.openliberty.data.internal_fat/bnd.bnd
  dev/io.openliberty.data.internal_fat/build.gradle
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/FATSuite.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/bnd.bnd
  dev/io.openliberty.data.internal_fat_jpa/build.gradle
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/FATSuite.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#24746 new lite test with cbh
  dev/com.ibm.ws.wssecurity.fat.utils.common/fat/src/com/ibm/ws/wssecurity/fat/utils/common/RepeatWithEE7cbh10.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/build.gradle
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/OneServerTests/CxfSAMLCaller1ServerEE7LiteTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/OneServerTests/CxfSAMLCaller1ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/TwoServerTests/CxfSAMLCaller2ServerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/common/CxfSAMLCallerTests.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/caller_1_NotIncludeTokenInSub.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/caller_1_maptoUR.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_1.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_bad_realmIdentifiers.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_good_realmIdentifiers.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_groupIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_groupIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_identifiersGood.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_identifiersOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_realmIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_realmIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_userIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_userIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_userUniqueIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_Group_userUniqueIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_groupIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_groupIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_identifiersGood.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_identifiersOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_realmIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_realmIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_userIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_userIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_userUniqueIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_No_userUniqueIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_groupIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_groupIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_identifiersGood.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_identifiersOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_realmIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_realmIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_userIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_userIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_userUniqueIdentifierBad.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_mapToUserRegistry_User_userUniqueIdentifierOmitted.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProviderWithCaller_maptoUR.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProvider_1.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProvider_1_AsymSignEnc.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProvider_1_AsymSignEnc_wss4j.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/securityProvider_1_symSignEnc.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller.ee7lite/.gitignore
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller.ee7lite/bootstrap.properties
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller.ee7lite/configs/server_2in1_asymProtection.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller.ee7lite/cxf-ehcache_ee7.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/servers/com.ibm.ws.wssecurity_fat.saml.caller.ee7lite/cxf-ehcache_ee8.xml
Labels: noproductcode, CLA Signed

#24756 update ui package.json files
  dev/com.ibm.ws.ui.tool.explore/package.json
  dev/com.ibm.ws.ui.tool.javaBatch/package.json
  dev/com.ibm.ws.ui.tool.serverConfig/package.json
  dev/com.ibm.ws.ui/package.json
Labels: noproductcode, CLA Signed

#24877 Repeat tests for EE9 and EE10
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MPConfigTest.java
Labels: noproductcode, CLA Signed

#24862 Disable CRIU HW breakpoints for restore
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#24873 Disable CRIU HW breakpoints for restore
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed
