Repository OpenLiberty/open-liberty, pull requests merged in 2024-06, with the labels that each got.

#28592 Read-write WLP-Platforms from feature manifests
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/SubsystemFeatureDefinitionImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXML.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXMLConstants.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/ProvisioningFeatureDefinition.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtilsTest.java
  dev/com.ibm.ws.kernel.feature/test/test data/com.ibm.websphere.supersededA.mf
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/MockFeature.java
Labels: CLA Signed

#28590 Change io.openliberty.mpTelemetry-2.0.feature to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.0/io.openliberty.mpTelemetry-2.0.feature
Labels: CLA Signed

#28618 Revert "Read-write WLP-Platforms from feature manifests"
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/SubsystemFeatureDefinitionImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXML.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXMLConstants.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/ProvisioningFeatureDefinition.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtilsTest.java
  dev/com.ibm.ws.kernel.feature/test/test data/com.ibm.websphere.supersededA.mf
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/MockFeature.java
Labels: CLA Signed

#28602 Add request attribute for secure protocol
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/response/factory/IRequestResponseFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/request/IRequest61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/request/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletRequest61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/websphere/servlet61/IRequest61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/websphere/servlet61/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61SecureProtocolTLSDefaultAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61SecureProtocolTLSv1_2AttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SecureProtocolTLSv1_2AttributeTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SecureProtocolTLSv1_2AttributeTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SecureProtocolTLSv1_3AttributeTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SecureProtocolTLSv1_3AttributeTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/SecureProtocolRequestAttribute.war/src/secureprotocol/servlets/SecureProtocolRequestAttribute.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28613 Re-disable long running test
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
Labels: noproductcode, CLA Signed, team:Performance

#28585 Re-introduce "Fix errors during Database Rotation"
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_Web.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_Web.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/fat/src/com/ibm/ws/jpa/jpa31/AsmServiceTest.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_EJB.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_Web.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#28596 Add Telemetry-2.0 jaeger and zipkin container test repeats
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerLegacyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
Labels: noproductcode, CLA Signed

#28622 add minimum java level to tests
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessJavaEEToMicroProfileTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessServletToMicroProfileTest.java
Labels: noproductcode, CLA Signed

#28631 Update fattest.simplicity to generate replacement
  dev/fattest.simplicity/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance

#28594 Add crypto messages and logging utils
  dev/com.ibm.ws.crypto.common/resources/com/ibm/ws/crypto/common/resources/CryptoCommonMessages.nlsprops
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/CryptoMessageUtils.java
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/CryptoUtils.java
Labels: ID reviewed, CLA Signed

#28624 Fix spelling mistake in testPrepareJSPThreadCountDefault
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPPrepareJSPThreadCountDefaultValueTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#28627 resource accessor methods for datasource and connection
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/server.xml
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/DataConfigTestServlet.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employee.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
Labels: team:Zombie Apocalypse, CLA Signed

#28593 jsfContainer Failing FAT Tests Changed from HTMLUnit to Selenium
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/utils/JSFUtils.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ELImplicitObjectsViaCDI/resourcesFaces40/implicit_objects.xhtml
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ELImplicitObjectsViaCDI/resourcesJSF23/implicit_objects.xhtml
  dev/com.ibm.ws.jsfContainer_fat_2.3/test-applications/ELImplicitObjectsViaCDI/src/com/ibm/ws/jsf23/fat/elcdi/beans/ELImplicitObjectBean.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#28637 Support Null Charset Encoding
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/webapp/WebApp61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletRequest61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletResponse61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/CharSetEncodingTest.war/src/charset/servlets/TestCharSetEncodingServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28471 Update CHIPS - Session Options + Other Fixes
  dev/com.ibm.ws.session/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionProperties.java
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/HttpCookie.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCPartitionedAttributeTests.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/HttpSession.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/SameSite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60PartitionedAttributeTests.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/CookieSetAttributeTest.war/src/cookiesetattribute/servlets/CookieSetAttributeServlet.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/PartitionedServlet60Test.war/src/partitioned/servlets/PartitionedCookieServlet.java
Labels: in:Web Components, ID review not needed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#28532 Pull in final WebSocket 2.2 API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta/websocket.client.2.2.bnd
  dev/io.openliberty.jakarta/websocket.server.2.2.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28319 Update Security for CHIPS (Partitioned Cookies)
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/web/JavaScriptUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/web/JavaScriptUtilsTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/OAuthClientTrackerTest.java
  dev/com.ibm.ws.security.oauth/test/com/ibm/ws/security/oauth20/web/UserAuthenticationTest.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/web/OidcRedirectServletTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/com/ibm/ws/security/openidconnect/web/BrowserStateTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/SsoRequestTest.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/AuthenticatorTest.java
  dev/com.ibm.ws.security.social/test/com/ibm/ws/security/social/twitter/TwitterTokenServicesTest.java
  dev/com.ibm.ws.webcontainer.security.admin/src/com/ibm/ws/webcontainer/security/admin/internal/WebAdminSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.feature/src/com/ibm/ws/webcontainer/security/feature/internal/FeatureWebSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/ReferrerURLCookieHandler.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/SSOCookieHelperImpl.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityConfig.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/SSOCookieHelperImplTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/FormLoginAuthenticatorTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/ReferrerURLCookieHandlerTest.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WebContainerRequestState.java
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#28649 resource accessor methods without authDataRef
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/server.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/DefaultDSEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/DefaultDSRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/PersistenceUnitRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/ServerDSIdRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/ServerDSJNDIRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestWeb/src/test/jakarta/data/datastore/web/ServerDSResRefRepo.java
Labels: team:Zombie Apocalypse, CLA Signed

#28645 versionless added after packaging
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#28632 JAX-RS: add jaxb bundle to feature jars for wadl2java
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jaxrs.common-2.1.feature
  dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/WADLTest.java
Labels: CLA Signed

#28664 Change to not enable java security if testing data-1.1 feature
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed, team:Performance

#28630 Fix jsp_defaultHTML test to also check for 302
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
Labels: noproductcode, CLA Signed

#28620 Read-write WLP-Platforms from feature manifests - take 2
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtils.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/SubsystemFeatureDefinitionImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXML.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXMLConstants.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/provisioning/ProvisioningFeatureDefinition.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/FeatureResolverInterfacesTest.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/subsystem/FeatureDefinitionUtilsTest.java
  dev/com.ibm.ws.kernel.feature/test/test data/com.ibm.websphere.supersededA.mf
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/internal/kernel/KernelResolverEsa.java
  dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/MockFeature.java
Labels: CLA Signed

#28633 Update to not include fattest.simplicity.jar in autoFVT.zip files
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/build.gradle
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/build.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Performance

#28677 Missed a dependsOn for com.ibm.ws.componenttest
  dev/fattest.simplicity/build.gradle
Labels: noproductcode, CLA Signed, team:Performance

#28678 Update FAT building to depend on fattest.simplicity assemble task
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed, team:Performance

#28621 Introduce transactionLogDBName for DB2 on z/OS
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: ID reviewed, CLA Signed

#28648 Create atomic dispatcher state - improved
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/dispatcher/DispatcherState.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/dispatcher/SpillDispatcher.java
  dev/com.ibm.ws.messaging.msgstore/src/com/ibm/ws/sib/msgstore/persistence/dispatcher/StateUtils.java
Labels: CLA Signed

#28679 Update package names to match their directory name
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
Labels: noproductcode, CLA Signed, team:Performance

#28643 Fix aggressive takeover tests
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Base2PCCloudServlet.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
Labels: CLA Signed

#28672 fix possible out of bounds in WC WebApp
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#28684 Delivery of Final version of Persistence API 3.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.2.feature
  dev/io.openliberty.jakarta/persistence.3.2.bnd
  dev/io.openliberty.org.eclipse.persistence-3.2/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed, jakartaEE11

#28601 Code cleanup feature repository
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature/test/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepositoryTest.java
Labels: CLA Signed

#28682 Clean up launch.xml and other extra files
  dev/com.ibm.ws.componenttest/autoFVT-defaults/.gitignore
  dev/com.ibm.ws.componenttest/autoFVT-defaults/TestBuild.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/configuration.properties
  dev/com.ibm.ws.componenttest/autoFVT-defaults/fatTestCommon.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/fatTestPorts.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/ignoredFFDCs.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/logging.properties
  dev/com.ibm.ws.componenttest/autoFVT-defaults/productSample.properties
  dev/com.ibm.ws.componenttest/autoFVT-defaults/productSampleServer.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/productSample_noBootstrap.properties
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/properties.xml
  dev/com.ibm.ws.componenttest/autoFVT-defaults/testports.properties
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch-overrides.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/properties.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/properties.xml
Labels: CLA Signed, team:Performance

#28681 Update Jakarta Authorization 3.0 to final version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authorization-3.0.feature
  dev/io.openliberty.jakarta/authorization.3.0.bnd
Labels: CLA Signed, team:Performance

#28695 Update HamcrestArchiveProcessor comment to say which build.gradle
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/tck/HamcrestArchiveProcessor.java
Labels: noproductcode, CLA Signed

#28578 Install tools update feature product match logic
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/EsaResource.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
  dev/wlp.lib.extract/src/wlp/lib/extract/ProductMatch.java
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractor.java
  dev/wlp.lib.extract/test/wlp/lib/extract/SelfExtractorTest.java
Labels: CLA Signed

#28703 Add test for versionless private feature not moved to beta / ga
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.jdbc-4.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpFaultTolerance-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpTelemetry-2.0.feature
Labels: CLA Signed, team:Performance

#28697 299145 - Derby Deadlock FFDC Fix
  dev/com.ibm.ws.jbatch.open.bonuspayout_fat/fat/src/batch/fat/junit/BonusPayoutViaJBatchUtilityTest.java
Labels: noproductcode, CLA Signed

#28559 Fix AtomicServiceReference setReference order issues
  dev/com.ibm.websphere.security/src/com/ibm/wsspi/security/registry/RegistryHelper.java
  dev/com.ibm.ws.junit.extensions/src/test/common/ComponentContextMockery.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/AtomicServiceReference.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/wsspi/kernel/service/utils/AtomicServiceReferenceTest.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/wsspi/kernel/service/utils/TestServiceReference.java
  dev/com.ibm.ws.security.client/src/com/ibm/ws/security/client/internal/jaas/JAASClientService.java
  dev/com.ibm.ws.security.jaas.common/src/com/ibm/ws/security/jaas/common/JAASConfigurationFactory.java
  dev/com.ibm.ws.security.mp.jwt.proxy/src/com/ibm/ws/security/mp/jwt/proxy/MpJwtHelper.java
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/util/ConfigUtils.java
Labels: CLA Signed

#28642 JAXB 2.2: Remove RI from TCCL
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat.no-jaxb-feature/server.xml
  dev/com.ibm.ws.jaxb_fat/test-applications/thirdPartyJaxbApp/src/jaxb/thirdparty/web/ThirdPartyJAXBFromAppTestServlet.java
Labels: CLA Signed

#28675 Server is already non-secured, use normal HTTP call (io.openliberty.http.monitor.fat)
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
Labels: noproductcode, CLA Signed

#28706 Fix JPA FAT project dependency
  dev/com.ibm.ws.jpa.tests.eclipselink.query_32_fat.common/bnd.bnd
Labels: team:Zombie Apocalypse, noproductcode, test bug, in:JPA, CLA Signed, jakartaEE11

#28700 Add note about syncQueryTimeoutWithTransactionTimeout on the tranlog …
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed

#28686 Create MP7 zip
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
  dev/build.image/build.gradle
  dev/build.image/profiles/microProfile7/features.xml
  dev/build.image/publish/wlp/templates/servers/microProfile7/server.xml
Labels: CLA Signed

#28718 Adding ignore for spring test packages
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#28688 Fix the source view save in Server Config
  dev/com.ibm.ws.ui.tool.serverConfig/resources/WEB-CONTENT/js/components/editor.js
Labels: CLA Signed

#28722 Update to depend on assembleBinaryDependencies instead of assemble
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed, team:Performance

#28702 JAX-RS 2.1: Remove CXF 3.2 wadl2java bundle
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.jaxrs-2.1.feature
  dev/com.ibm.ws.jaxrs.2.1.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.defaultexceptionmapper/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.gitignore
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.project
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2/bnd.bnd
Labels: CLA Signed

#28721 Write tests for Hibernate using BasicRepositoryMethods
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.classpath
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.project
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_jpa_hibernate/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_jpa_hibernate/bnd.bnd
  dev/io.openliberty.data.internal_fat_jpa_hibernate/build.gradle
  dev/io.openliberty.data.internal_fat_jpa_hibernate/fat/src/test/jakarta/data/jpa/hibernate/DataJPAHibernateTest.java
  dev/io.openliberty.data.internal_fat_jpa_hibernate/fat/src/test/jakarta/data/jpa/hibernate/FATSuite.java
  dev/io.openliberty.data.internal_fat_jpa_hibernate/publish/servers/io.openliberty.data.internal.fat.jpa.hibernate/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa_hibernate/publish/servers/io.openliberty.data.internal.fat.jpa.hibernate/server.xml
  dev/io.openliberty.data.internal_fat_jpa_hibernate/test-applications/DataJPAHibernateTestApp/resources/WEB-INF/classes/META-INF/persistence.xml
  dev/io.openliberty.data.internal_fat_jpa_hibernate/test-applications/DataJPAHibernateTestApp/src/test/jakarta/data/jpa/hibernate/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa_hibernate/test-applications/DataJPAHibernateTestApp/src/test/jakarta/data/jpa/hibernate/web/City.java
  dev/io.openliberty.data.internal_fat_jpa_hibernate/test-applications/DataJPAHibernateTestApp/src/test/jakarta/data/jpa/hibernate/web/CityId.java
  dev/io.openliberty.data.internal_fat_jpa_hibernate/test-applications/DataJPAHibernateTestApp/src/test/jakarta/data/jpa/hibernate/web/DataJPAHibernateTestServlet.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28727 Remove packageServerConflict for MP7
  dev/build.image/build.gradle
Labels: CLA Signed

#28708 Update z/os plans to use more machines
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed

#28691 Call afterRestore when a checkpoint fails
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCMXBeanTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceFailCheckpointTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceFailRestoreTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceMultiAppTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceOrderTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceRequestPhaseAfterAppStartTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/CRaCResourceRequestPhaseBeforeAppStartTest.java
  dev/io.openliberty.checkpoint_fat_crac/fat/src/io/openliberty/checkpoint/fat/crac/app/fail/checkpoint/CRaCResourceFailCheckpointServlet.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/LibertyCheckpoint.java
Labels: CLA Signed

#28739 use jakarta data from multiple modules in app
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DataComponentMetaData.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DataModuleMetaData.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DelegatingResourceFactory.java
  dev/io.openliberty.data.internal_fat_datastore/.classpath
  dev/io.openliberty.data.internal_fat_datastore/bnd.bnd
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DataStoreTest.java
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/server.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/resources/DataStoreTestWeb1/WEB-INF/classes/META-INF/persistence.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/resources/DataStoreTestWeb1/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/resources/DataStoreTestWeb2/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/resources/WEB-INF/classes/META-INF/persistence.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/lib/DSDEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/lib/DSDRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/lib/ServerDSEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DefaultDSEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DefaultDSRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/PersistenceUnitEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/PersistenceUnitRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/QualifiedDSRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/QualifiedPersistenceUnitRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/ResourceProducer.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/ResourceQualifier.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/ServerDSIdRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/ServerDSJNDIRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/ServerDSResRefRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/DataStoreSecondServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/WebModule2DSResRefRepo.java
Labels: team:Zombie Apocalypse, CLA Signed

#28720 Update Pages 4.0 API to final version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta/pages.4.0.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28655 Change splitted to split
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60CookieSetAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61SetCookieRandomAttributes.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/SetCookieViaResponseHeader.war/src/setcookie/servlets/SetCookieAttributesViaResponseHeader.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27505 FeatureUtility enable no proxy
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
Labels: CLA Signed

#28711 Retrieve leases correctly
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
Labels: CLA Signed

#28728 Remove mpTelemetry mp60 test repeats
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerBaseTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/MetricsDisabledServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/telemetry/internal_fat_tck/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/telemetry/internal_fat_tck/Telemetry20TCKLauncher.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20TCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20TCKServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20TCKServer/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
Labels: noproductcode, CLA Signed

#28715 permission added for JSPJava7Test
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspJava7Server/server.xml
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#28736 working packaging with versionless
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#28740 Update Servlet 6.1 API to final version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature
  dev/io.openliberty.jakarta/servlet.6.1.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28753 Revert "FeatureUtility enable no proxy"
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
Labels: CLA Signed

#28759 Add missing tolerates for EE 11 features
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization/io.openliberty.versionless.appAuthorization.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jacc/io.openliberty.versionless.jacc.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket/io.openliberty.versionless.websocket.feature
Labels: CLA Signed, team:Performance

#28749 Accommodate `302` response for `jsp_defaultHTML()`
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
Labels: noproductcode, CLA Signed

#28473 Enable WCPartitionedCookieAttributeSecurityTest
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/tests/WCPartitionedAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/tests/WCPartitionedCookieAttributeSecurityTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitioned/.gitignore
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitioned/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitioned/jvm.options
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitioned/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitionedSecurity/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitionedSecurity/jvm.options
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitionedSecurity/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/PartitionedTest.war/resources/PartitionedSetCookie.jsp
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/PartitionedTest.war/src/partitioned/servlets/DuplicatePartitionedCookieServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/PartitionedTest.war/src/partitioned/servlets/PartitionedCookieServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/PartitionedTest.war/src/partitioned/servlets/PartitionedSessionCreationServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/PartitionedTest.war/src/partitioned/servlets/PartitionedSplitCookieServlet.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#28687 Selenium util jar
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22APARSeleniumTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23EvalScriptsTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/CustomDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/ExtendedWebDriver.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/selenium_util/WebPage.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23WebSocketTests.java
  dev/io.openliberty.faces.fat.selenium.util.internal/.classpath
  dev/io.openliberty.faces.fat.selenium.util.internal/.project
  dev/io.openliberty.faces.fat.selenium.util.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.faces.fat.selenium.util.internal/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.faces.fat.selenium.util.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.faces.fat.selenium.util.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.faces.fat.selenium.util.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.faces.fat.selenium.util.internal/bnd.bnd
  dev/io.openliberty.faces.fat.selenium.util.internal/src/io/openliberty/faces/fat/selenium/util/internal/CustomDriver.java
  dev/io.openliberty.faces.fat.selenium.util.internal/src/io/openliberty/faces/fat/selenium/util/internal/ExtendedWebDriver.java
  dev/io.openliberty.faces.fat.selenium.util.internal/src/io/openliberty/faces/fat/selenium/util/internal/WebPage.java
  dev/io.openliberty.faces.fat.selenium.util.internal/src/io/openliberty/faces/fat/selenium/util/internal/package-info.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/selenium_util/WebPage.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/MultipleInputFileTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/WebSocketTests.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/bugfixes/MyFaces4658Test.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/CustomDriver.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/ExtendedWebDriver.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/WebPage.java
Labels: CLA Signed

#28734 Reverting file lock checking on Windows
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
  dev/com.ibm.ws.install/test/com/ibm/ws/install/UninstallDirectorTest.java
Labels: CLA Signed

#28760 Fix extra catch in DataTestServlet
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
Labels: noproductcode, CLA Signed

#28733 platforms get cached
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
Labels: CLA Signed

#28765 Update persistence to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.batch2.1.internal.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.jpa-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-11.0/io.openliberty.jakartaeeClient-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jpa/io.openliberty.versionless.jpa.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistence-3.2/io.openliberty.persistence-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistence/io.openliberty.versionless.persistence.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistenceContainer-3.2/io.openliberty.persistenceContainer-3.2.feature
Labels: CLA Signed

#28767 Wait for correct message in ConfigRESTHandlerTest fat
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerTest.java
Labels: noproductcode, CLA Signed

#28773 Updated Validation 3.1 APIs to released version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.1.feature
  dev/io.openliberty.jakarta/validation.3.1.bnd
Labels: CLA Signed

#28404 If configured to use jar URLs then do not return virtual dir URLs
  dev/com.ibm.ws.artifact.zip/resources/com/ibm/ws/artifact/zip/internal/resources/ZipArtifactMessages.nlsprops
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.artifact_fat/.classpath
  dev/com.ibm.ws.artifact_fat/bnd.bnd
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATNoDirectoryZipTest.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATResourceProtocol.java
  dev/com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATSuite.java
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.nodir.zip/.gitignore
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.nodir.zip/bootstrap.properties
  dev/com.ibm.ws.artifact_fat/publish/servers/com.ibm.ws.artifact.nodir.zip/server.xml
  dev/com.ibm.ws.artifact_fat/test-applications/noDirZip/src/nodirzip/fat/test/app/NoDirectoryZipServlet.java
Labels: ID reviewed, CLA Signed

#28787 Filter another version of netty coming in from test transitive
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#28779 Fix Defect 300579
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/JSF23CDIGeneralTests.java
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#28802 Update to move data-1.0 feature to core edition
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VersionlessTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.data1.0-jdbc.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.data-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.data-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistenceService-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/data/io.openliberty.versionless.data.feature
Labels: CLA Signed, team:Performance

#28732 MpTelemetry 2.0 Log implementation for beta release
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.0/io.openliberty.mpTelemetry-2.0.feature
  dev/com.ibm.ws.collector/bnd.bnd
  dev/com.ibm.ws.collector/original.bnd
  dev/com.ibm.ws.collector/src/com/ibm/ws/collector/Collector.java
  dev/com.ibm.ws.collector/transformed.bnd
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/isolation/InMemoryMetricReader.java
  dev/io.openliberty.io.opentelemetry.2.0/bnd.bnd
  dev/io.openliberty.io.opentelemetry.2.0/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.logs.ConfigurableLogRecordExporterProvider
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/config/OpenTelemetryVersionedConfigurationImpl.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryDisabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/config/OpenTelemetryVersionedConfigurationImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/config/OpenTelemetryVersionedConfigurationImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/.classpath
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/.project
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/OpenTelemetryLogHandler.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/TelemetryLogEmitter.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/constants/OpenTelemetryConstants.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryInfoFactory.java
  dev/io.openliberty.mpTelemetry.2.0.thirdparty/bnd.bnd
Labels: CLA Signed

#28792 Add EE11 test for EL and JSP
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/WebProfileJSPWithELTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/webProfileJSPWithEL/jvm.options
Labels: noproductcode, CLA Signed

#28306 JAX-WS: Class name is added to CXF logs
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/io/openliberty/cxf/logging/CXFLogger.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/logging/LogUtils.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#28751 Add tests and some clean up
  dev/com.ibm.ws.crypto.common/resources/com/ibm/ws/crypto/common/resources/CryptoCommonMessages.nlsprops
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/CryptoMessageUtils.java
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/CryptoUtils.java
  dev/com.ibm.ws.crypto.common/test/com/ibm/ws/crypto/common/CryptoUtilsTest.java
Labels: ID reviewed, CLA Signed

#28625 Remove auditCollector-2.0
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.auditCollector-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/audit-2.0/com.ibm.websphere.appserver.audit-2.0.feature
Labels: CLA Signed

#28768 Move facesContainer-4.1 and websocket-2.2 to beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.facesProvider-4.1.0.Container.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.websocket-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.1/io.openliberty.facesContainer-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.2/io.openliberty.websocket-2.2.feature
Labels: in:Transport, in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28789 Update jsch version
  dev/ant_build.js/build.gradle
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#28808 Add additional MP7 compatibility tests
  dev/io.openliberty.microprofile41.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile41.internal_fat/fat/src/io/openliberty/microprofile41/internal/test/suite/BasicHealthTest.java
  dev/io.openliberty.microprofile5.internal_fat/fat/src/io/openliberty/microprofile5/internal/test/suite/MP5CompatibleTest.java
  dev/io.openliberty.microprofile5.internal_fat/publish/servers/MP5CompatibleServer/MP50andEE10.xml
  dev/io.openliberty.microprofile7.internal_fat/.classpath
  dev/io.openliberty.microprofile7.internal_fat/.project
  dev/io.openliberty.microprofile7.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile7.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile7.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile7.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile7.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/helloworld/HelloWorldApplication.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/helloworld/HelloWorldBean.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/helloworld/HelloWorldResource.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/helloworld/basic/BasicHelloWorldBean.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/helloworld/config/ConfiguredHelloWorldBean.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/FATSuite.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/MP7CompatibleTest.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/MP7EE10CompatibleTest.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/MP7EE11CompatibleTest.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/MP7EE9CompatibleTest.java
  dev/io.openliberty.microprofile7.internal_fat/fat/src/io/openliberty/microprofile7/internal/test/suite/MPCompatibilityTestUtils.java
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70CompatibleServer/bootstrap.properties
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70CompatibleServer/server.xml
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE10/bootstrap.properties
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE10/server.xml
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE11/bootstrap.properties
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE11/server.xml
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE9/bootstrap.properties
  dev/io.openliberty.microprofile7.internal_fat/publish/servers/MP70andEE9/server.xml
Labels: noproductcode, CLA Signed

#28786 data config element
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Data.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DatabaseStore.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_config/fat/src/test/jakarta/data/config/DataConfigTest.java
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/server.xml
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATestCheckpoint.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#28815 honour mpConfig priorities when getting otel properties
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#28811 Use location service to get ${wlp.user.dir}
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: CLA Signed

#28809 jvm metrics followup
  dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/isolation/InMemoryMetricReader.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/config/OpenTelemetryVersionedConfigurationImpl.java
Labels: CLA Signed

#28828 Get the server object on the injection path
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/customizer/CustomizerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/exporter/ExporterTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/PropagatorTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/resource/ResourceTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/sampler/SamplerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ConfigServlet.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#28831 Update to final version of EE 11 Authentication, Data and Concurrency API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authentication-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.data-1.0.feature
  dev/io.openliberty.jakarta/authentication.3.1.bnd
  dev/io.openliberty.jakarta/concurrency.3.1.bnd
  dev/io.openliberty.jakarta/data.1.0.bnd
Labels: CLA Signed, team:Performance

#28665 Update EclipseLink 2.7.14 -> 2.7.15
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/build.gradle
Labels: in:JPA, team:Blizzard, CLA Signed

#28837 Revert "data config element"
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Data.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DatabaseStore.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_config/fat/src/test/jakarta/data/config/DataConfigTest.java
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/server.xml
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATestCheckpoint.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: CLA Signed

#28822 Event logging fat improvement
  dev/com.ibm.ws.event.logging_fat/fat/src/com/ibm/ws/event/logging/FATTest.java
Labels: noproductcode, CLA Signed

#28829 Issue24387
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AjaxRenderExecuteThisTest.java
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#21604 Remove javax.transaction.xa package from transaction API bundles
  dev/com.ibm.websphere.javaee.transaction.1.1/bnd.bnd
  dev/com.ibm.websphere.javaee.transaction.1.2/bnd.bnd
  dev/com.ibm.ws.transaction.core_fat.misc/publish/files/features/utdecorator-1.0.mf
  dev/com.ibm.ws.transaction.test.util/publish/features/txtest-1.0.mf
  dev/com.ibm.ws.transaction.test.util/publish/features/txtest-2.0.mf
  dev/io.openliberty.jakarta.transaction.2.0/bnd.bnd
Labels: CLA Signed, team:Performance

#28843 Update to reference 4.1 jakarta API bundle instead of 4.0
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
Labels: CLA Signed, team:Performance

#28819 Ignore ApplicationComponentMetaData for Bean Validation start up
  dev/com.ibm.ws.jpa.container.beanvalidation.1.1/src/com/ibm/ws/jpa/container/beanvalidation/JPABVComponentImpl.java
  dev/com.ibm.ws.jpa.container.beanvalidation.2.0/src/com/ibm/ws/jpa/container/beanvalidation/JPABV20ComponentImpl.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/ApplicationComponentMetaData.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/ApplicationModuleMetaData.java
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/container/osgi/internal/JPAComponentImpl.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/fat/src/com/ibm/ws/jpa/tests/container_hibernate/TestHibernate.java
  dev/com.ibm.ws.jpa.tests.container_hibernate_fat/publish/servers/com.ibm.ws.jpa.container.fat.hibernate/bootstrap.properties
Labels: CLA Signed

#28836 Update to MicroProfile Rest Client 4.0 APIs
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-4.0.feature
  dev/io.openliberty.org.eclipse.microprofile/rest.client.4.0.bnd
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10plus.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee11.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9and10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed

#28558 Fix memory leak in JAXRSClientConfigHolder
  dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/clientconfig/JAXRSClientConfigHolder.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2/src/com/ibm/ws/jaxrs21/clientconfig/JAXRSClientConfigHolder.java
Labels: in:JAX-RS, CLA Signed

#28761 Removing Metrics 3.0/4.0 Beta Fence
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/helper/BucketManager.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/helper/PrometheusBuilder30.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/impl/Histogram30Impl.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/impl/Timer30Impl.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/BadHistogramTimer/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/DefaultBucketServer/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/HistogramConfig/jvm.options
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/TimerConfig/jvm.options
Labels: CLA Signed

#28846 Ensure fattest.simplicity is available to FAT suites after jar
  dev/fattest.simplicity/build.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28816 Switch to EE 11 only and promote dataContainer-1.0 to beta
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.data1.0-jdbc.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/dataContainer-1.0/io.openliberty.dataContainer-1.0.feature
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Data.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/DatabaseStore.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfiguration.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE10Action.java
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_cs.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_de.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_es.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_fr.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_hu.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_it.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_ja.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_ko.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_pl.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_pt_BR.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_ro.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_ru.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_zh.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/l10n/metatype_zh_TW.properties
  dev/io.openliberty.data.internal.persistence/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.checkpoint.fat/server.xml
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat_config/fat/src/test/jakarta/data/config/DataConfigTest.java
  dev/io.openliberty.data.internal_fat_config/publish/servers/io.openliberty.data.internal.fat.config/server.xml
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Employees.java
  dev/io.openliberty.data.internal_fat_config/test-applications/DataConfigTestApp/src/test/jakarta/data/config/web/Students.java
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/server.xml
  dev/io.openliberty.data.internal_fat_exp/publish/servers/io.openliberty.data.internal.fat.exp/server.xml
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATestCheckpoint.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql.container/server.xml
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/server.xml
  dev/io.openliberty.data.internal_fat_validation/fat/src/test/jakarta/data/validation/DataValidationTest.java
  dev/io.openliberty.data.internal_fat_validation/publish/servers/io.openliberty.data.internal.fat.validation/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core.nosql/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.full/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.web/server.xml
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10Features.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9Features.java
Labels: team:Zombie Apocalypse, CLA Signed

#28818 Handle extra CancellationException wrapper in Java 23 (300394)
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/test-applications/MPContextProp1_3_EE9_App/src/concurrent/mp/fat/v13/ee9/web/MPContextProp1_3_EE9_TestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 23

#28785 Fix Subject.getSubject changes for Java 23
  dev/com.ibm.ws.componenttest/src/componenttest/app/FATUtilities.java
  dev/com.ibm.ws.componenttest/src/componenttest/app/JavaInfo.java
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/test-resourceadapters/adapter.regr/src/com/ibm/adapter/work/FVTComplexJCA16WorkImpl.java
Labels: team:Zombie Apocalypse, CLA Signed, Java 23

#28834 JAX-WS and JAX-RS 2.1: Add Java 23 and above compatible Subject methods in DefaultLogEventMapper
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2/bnd.overrides
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2/src/org/apache/cxf/ext/logging/event/DefaultLogEventMapper.java
Labels: CLA Signed

#28839 The bLoader may be null and the code must avoid NPE if it is
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/GatewayClassLoader.java
Labels: CLA Signed

#28701 fix user feature sig verification
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#28848 PR 1: Add CDITest Batch Checkpoint Tests
  dev/com.ibm.ws.jbatch.open_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/CDITestCheckpoint.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.open_fat/publish/files/CDITestCheckpoint/server.xml
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/.gitignore
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/bootstrap.properties
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/derby.properties
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/server.xml
Labels: noproductcode, CLA Signed

#28873 Missing period in description
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/constants/OpenTelemetryConstants.java
Labels: CLA Signed

#28840 Removing Metrics Authorization for FATs
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/BadHistogramTimerConfigTest.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/DefaultHistogramBucketsTest.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/HistogramConfigFieldTest.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/TimerConfigFieldTest.java
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/BadHistogramTimer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/DefaultBucketServer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/HistogramConfig/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/TimerConfig/server.xml
Labels: noproductcode, CLA Signed

#28824 Update EclipseLink 4.0.2 -> 4.0.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/build.gradle
  dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/exceptions/i18n/JAXBExceptionResource.nlsprops
  dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
  dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/ASMFactory.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/ClassReader.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/ClassWriter.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/EclipseLinkASMClassWriter.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/Opcodes.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/dynamic/DynamicClassWriter.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/metadata/MetadataDynamicClassWriter.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataClass.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/weaving/ComputeClassWriter.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/internal/jpa/weaving/PersistenceWeaver.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/jpa/jpql/parser/AbstractExpression.java
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/mappings/converters/UUIDConverter.java
Labels: in:JPA, team:Blizzard, CLA Signed, L2 Reviewed, ID waiting on development

#28865 Avoid running 0 tests
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/FATSuite.java
Labels: noproductcode, CLA Signed

#28569 Fix Jakarta Data checkpoint tests for DB Rotation
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtensionProvider.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTestCheckpoint.java
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.checkpoint.fat/server.env
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.checkpoint.fat/server.xml
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATestCheckpoint.java
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.env
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.xml
Labels: team:Zombie Apocalypse, test bug, CLA Signed

#28807 Add MP7 repeats for Metrics
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-mpMetrics-monitor1.0.feature
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MPMetricsElement.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/DefaultHistogramBucketsTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/LibraryRefTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/fat/src/io/openliberty/microprofile/metrics51/internal/tck/launcher/MetricsTCKLauncher.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/ComputedMetricsTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/FATSuite.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/MetricsMonitorTest.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/fat/src/io/openliberty/microprofile/metrics/internal/monitor_fat/TestEnableDisableFeaturesTest.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
Labels: CLA Signed

#28880 Remove websocket log message
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/link/LinkWriteExt10.java
Labels: in:Transport, CLA Signed, team:Sirius, jakartaEE11

#28835 Lock peer lease for deletion
  dev/com.ibm.rls.jdbc/src/com/ibm/rls/jdbc/SQLRecoveryLogFactory.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
Labels: CLA Signed

#28883 add back correct versionless packaging
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#28795 Delete lease when recovery logs are missing
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/Configuration.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/CoordinationLock.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileLogProperties.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogFileHandle.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogHandle.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/MultiScopeRecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLogsMissingException.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RLSUtils.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogManagerImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/StreamLogProperties.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/SimpleFS2PCCloudTest.java
Labels: CLA Signed

#28890 Tolerate DataStoreAdapterException
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest1.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DualServerDynamicDBRotationTest2.java
Labels: noproductcode, CLA Signed

#28893 Suppress NoSuchFileException and FileNotFoundException when deleting …
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
Labels: CLA Signed

#28906 Fix datasourceChangeTests
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
Labels: noproductcode, CLA Signed

#28900 Use MP Fault Tolerance 4.1-RC1 API
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.eclipse.microprofile/faulttolerance.4.1.bnd
Labels: CLA Signed

#28886 Beta mpRestClient-4.0 and microProfile-7.0
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpRestClient-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpRestClient.internal.cdi-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-7.0/io.openliberty.microProfile-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-4.0/io.openliberty.mpRestClient-4.0.feature
Labels: CLA Signed

#28897 MpTelemetry- Check for null in OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#28888 Minor Message Change for updating ValidationExceptionResource
  dev/io.openliberty.persistence.3.2.thirdparty/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
Labels: in:JPA, team:Blizzard, CLA Signed

#28804 Versionless Messaging
  dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverResultImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/resolver/FeatureResolver.java
Labels: ID reviewed, CLA Signed

#28842 Notices for 24.0.0.7
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#28868 some versionless tests based on versioned tests - disabled for now
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/VerifyData.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/VerifyXML.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/VerifyXMLConstants.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/BaselineResolutionEnablement.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/BaselineResolutionUnitTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/BaselineVersionlessSingletonUnitTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/FATSuite.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/util/RepositoryUtil.java
Labels: CLA Signed

#28917 Allow for recovery from connection failure
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Simple2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/SimpleFS2PCCloudTest.java
Labels: noproductcode, CLA Signed

#28853 Use attribute keys in metric recorder impl
  dev/io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck/fat/src/io/openliberty/microprofile/faulttolerance41/tck/FaultToleranceTck41Launcher.java
  dev/io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.telemetry/src/io/openliberty/microprofile/faulttolerance/telemetry/metrics/integration/MetricRecorderImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/resources/io/openliberty/microprofile/telemetry/internal/common/resources/MPTelemetry.nlsprops
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#28914 Issue #28911: Intermittent java:global NameNotFoundException
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/OSGiInjectionScopeData.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
Labels: team:Zombie Apocalypse, in:Java EE Platform, CLA Signed, release bug

#28934 Eclipse settings updates
  dev/com.ibm.ws.kernel.feature.resolver_fat/.classpath
  dev/com.ibm.ws.kernel.feature/.classpath
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/.settings/org.eclipse.jdt.core.prefs
Labels: noproductcode, CLA Signed, team:Performance

#28938 Code review comments from PR 28864
  dev/com.ibm.ws.microprofile.rest.client_fat/fat/src/com/ibm/ws/microprofile/rest/client/fat/FATSuite.java
  dev/io.openliberty.microprofile.rest.client.4.0.internal_fat_tck/.classpath
  dev/io.openliberty.microprofile.rest.client.4.0.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.rest.client.4.0.internal_fat_tck/bnd.bnd
Labels: noproductcode, CLA Signed, in:MicroProfile/RestClient

#28714 Update Concurrency TCK to 3.1.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.1.feature
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/publish/tckRunner/tck/standalone.pom.xml
  dev/io.openliberty.jakarta/concurrency.3.1.bnd
Labels: CLA Signed

#28932 change beta versionless features
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.jsp-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jdbc/io.openliberty.versionless.jdbc.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsp/io.openliberty.versionless.jsp.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages/io.openliberty.versionless.pages.feature
Labels: CLA Signed

#28899 Beta Partitioned Feature
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImplTest.java
Labels: in:Web Components, CLA Signed, team:Sirius

#28926 Address timing problem after aggressive takeover test
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
Labels: noproductcode, CLA Signed

#28943 Correct API call with conversion to get the right value
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
Labels: CLA Signed

#28901 Overlay for Oracle 23 Support
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
  dev/io.openliberty.persistence.3.0.thirdparty/src/org/eclipse/persistence/platform/database/Oracle23Platform.java
  dev/io.openliberty.persistence.3.0.thirdparty/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
  dev/io.openliberty.persistence.3.0.thirdparty/src/org/eclipse/persistence/platform/internal/databaseaccess/DatasourcePlatform.java
  dev/io.openliberty.persistence.3.0.thirdparty/src/org/eclipse/persistence/platform/internal/databaseaccess/Platform.java
Labels: in:JPA, CLA Signed

#28948 Skipping features that don't resolve or can't be found
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#28951 Issue 28950: Clean up PackageProcessor.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
Labels: CLA Signed
