Repository OpenLiberty/open-liberty, pull requests merged in 2024-05, with the labels that each got.

#28311 eliminate unsupported select codepath
  dev/io.openliberty.data.1.0.internal/src/io/openliberty/data/internal/v1_0/Data_1_0.java
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/version/DataVersionCompatibility.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Reservations.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Select.java
Labels: team:Zombie Apocalypse, CLA Signed

#28290 Prevent unnecessary FFDC when server stops
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
Labels: CLA Signed

#28231 Issue #28170: Add Warn for PPV in Package Cmd
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageProcessor.java
  dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommandTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.bootstrap.fat/jvm.options
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#28310 Skip signature testing for Jakarta Data on windows
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28309 JAX-WS: Fix LibertyWebServiceClientInInterceptor and add Unit Tests
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/client/LibertyWebServiceClientInInterceptor.java
  dev/com.ibm.ws.jaxws.2.3.common/test/com/ibm/ws/jaxws/client/LibertyWebServiceClientInInterceptorTest.java
Labels: CLA Signed

#28240 Changing FixManagerTests to be able to run on IFix builds
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FixManagerTest.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.fix.manager/src/test/kernel/feature/fix/manager/FixManagerServlet.java
Labels: noproductcode, CLA Signed

#28299 Beta Validation 3.1
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-3.1/io.openliberty.beanValidation-3.1.feature
Labels: CLA Signed

#28298 Rest filter experiment
  dev/com.ibm.ws.jaxrs.2.x.monitor.component/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/MonitorAppStateListener.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/RestMetricsCallback.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/package-info.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/.classpath
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
  dev/io.openliberty.restfulWS.mpMetrics.filter/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/MonitorAppStateListener.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMetricsCallbackImpl.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMonitorKeyCache.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#28315 Workaround for issue 22396
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
Labels: CLA Signed

#28304 Removing workaround for json4j bundle
  dev/wlp-featureTasks/src/com/ibm/ws/wlp/feature/tasks/FeatureBnd.java
Labels: CLA Signed

#28316 Use propagated gtrid in local Xid of imported transaction
  dev/com.ibm.tx.jta/src/com/ibm/ws/Transaction/JTA/Util.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
  dev/com.ibm.ws.wsat_fat.multi/fat/src/tests/MultiServerTest.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: CLA Signed

#28325 Refer to a record entity in the JDQL FROM clause
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
Labels: team:Zombie Apocalypse, CLA Signed

#28313 Use com.ibm.fips.mode
  dev/com.ibm.ws.crypto.common/bnd.bnd
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/FipsUtils.java
  dev/com.ibm.ws.crypto.common/test/com/ibm/ws/crypto/common/FipsUtilsTest.java
Labels: CLA Signed

#28242 CVEReporting: Adding checkpoint FAT tests
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/CVEReportingElement.java
  dev/io.openliberty.reporting.internal_fat/bnd.bnd
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/CVEReportingCheckpointTest.java
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/FATSuite.java
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.checkpoint.server/bootstrap.properties
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.checkpoint.server/jvm.options
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.checkpoint.server/server.env
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.checkpoint.server/server.xml
Labels: noproductcode, CLA Signed

#28278 Update TCK to use new 3.0.1 version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.reactive.messaging-3.0.feature
  dev/io.openliberty.microprofile.reactive.messaging30.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.eclipse.microprofile/reactive.messaging.3.0.bnd
Labels: CLA Signed

#28318 Allowing Delete and OrderBy
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
Labels: CLA Signed

#28339 JDQL update and delete with record entity, and omitted select clause returning different type
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebates.java
Labels: team:Zombie Apocalypse, CLA Signed

#28353 Revert "Consolidate to use one JAX-RS filter from `com.ibm.ws.jaxrs.2.x.monitor` for MP Metrics 5.x"
  dev/com.ibm.ws.jaxrs.2.x.monitor.component/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/MonitorAppStateListener.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/RestMetricsCallback.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/package-info.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/.classpath
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
  dev/io.openliberty.restfulWS.mpMetrics.filter/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/MonitorAppStateListener.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMetricsCallbackImpl.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMonitorKeyCache.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#28263 Notices for 24.0.0.5
  dev/build.image/publish/BETA_NOTICES
Labels: CLA Signed

#28302 CVE Reporting: Adding parameters used to generate id
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelUtils.java
  dev/io.openliberty.reporting.internal/bnd.bnd
  dev/io.openliberty.reporting.internal/resources/io/openliberty/reporting/internal/resources/CVEReporting.nlsprops
  dev/io.openliberty.reporting.internal/src/io/openliberty/reporting/internal/DataCollector.java
  dev/io.openliberty.reporting.internal/src/io/openliberty/reporting/internal/ReporterTask.java
Labels: ID reviewed, CLA Signed

#28357 Increase trace for concurrent persistent FAT
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/servers/com.ibm.ws.concurrent.persistent.fat.simctrl/bootstrap.properties
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#28352 Issue #28350: Avoid NullPointerException for connection during shutdown
  dev/com.ibm.ws.concurrent.persistent_fat_configupdate_databasetaskstore/fat/src/com/ibm/ws/concurrent/persistent/fat/configupd/db/ExecEnabledDBStoreConfigUpdateTest.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: bug, team:Zombie Apocalypse, CLA Signed, in:Concurrency, serviceability

#28345 Write instructions for verifying Jakarta Data TCK
  dev/io.openliberty.jakarta.data.1.0_fat_tck/.gitignore
  dev/io.openliberty.jakarta.data.1.0_fat_tck/README.md
  dev/io.openliberty.jakarta.data.1.0_fat_tck/build.gradle
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core.nosql/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core.nosql/jvm.options
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core.nosql/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core/jvm.options
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.core/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.full/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.full/jvm.options
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.full/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.web/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.web/jvm.options
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.jakarta.data.1.0.web/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/verification.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28343 Fixing Db2 Data JPA test
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: noproductcode, CLA Signed

#28348 Update test to handle slow test system
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/fat/src/com/ibm/ws/security/openidconnect/client/fat/jaxrs/CommonTests/JaxRSClientReAuthnTests.java
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/files/serversettings/provider_OP_ReAuthn.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#28296 Update to MyFaces 4.1.0-RC2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/io.openliberty.faces.4.1.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/webapp/MyFacesContainerInitializer.java
Labels: in:Web Components, CLA Signed, team:Sirius

#28370 subset result types using single attribute or record
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/PurchaseTime.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebates.java
Labels: team:Zombie Apocalypse, CLA Signed

#28229 Update to include common FAT jars in fattest.simplicity
  dev/build.example_fat/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/build.gradle
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed, team:Performance

#28371 Data JPA tests on Postgres
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: noproductcode, CLA Signed

#28367 Add com.ibm.ws.jaxws.webcontainer package to thread context
  dev/com.ibm.ws.jaxws.webcontainer/bnd.bnd
Labels: CLA Signed, team:Performance

#28379 Increase trace for persistent timer failure
  dev/com.ibm.ws.ejbcontainer.timer.calendar_fat/publish/servers/com.ibm.ws.ejbcontainer.timer.cal.fat.PersistentTimerServer/bootstrap.properties
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test debt, CLA Signed

#28382 improve error messages and remove commented out invalid scenario
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebates.java
Labels: team:Zombie Apocalypse, CLA Signed

#28360 CVE Reporting: Functionality for when ssl or transportSecurity features are enabled
  dev/io.openliberty.reporting.internal/src/io/openliberty/reporting/internal/CVEServiceClient.java
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/CVEResponseTest.java
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/response/CVEReportingResponseEndpoints.java
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.response.app.server/server.xml
  dev/io.openliberty.reporting.internal_fat/publish/servers/io.openliberty.reporting.response.test.server/server.xml
Labels: CLA Signed

#28375 Prevent transactions feature from loading automatically with Validation 3.1
  dev/com.ibm.websphere.appserver.features/visibility/public/beanValidation-3.1/io.openliberty.beanValidation-3.1.feature
Labels: CLA Signed

#28361 Create Tests for 4.1 RC2 Code
  dev/io.openliberty.org.apache.myfaces.4.1_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.1_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/ConfigTests.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/RenderIdTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/RowStatePreservedTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/UUIDConverterTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_rowStatePreserved/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_rowStatePreserved/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Config_Spec1764.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/HTML4_noIDs.xhtml_xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/HTML4_withIDs.xhtml_xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/HTML5_noIDs.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/HTML5_withIDs.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/WEB-INF/faces-config.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/XML_noIDs.xhtml_xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/XML_withIDs.xhtml_xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/rowStatePreserved_Spec1263.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/rowStatePreserved_Spec1263.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/rowStatePreserved_Spec1263.war/src/io/openliberty/org/apache/myfaces41/fat/rowStatePreserved/Item.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/rowStatePreserved_Spec1263.war/src/io/openliberty/org/apache/myfaces41/fat/rowStatePreserved/ItemsBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/resources/index_explicit_converter.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/resources/index_implicit_converter.xhtml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#28172 Apply MYFACES-4658 and MYFACES-4605
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/bugfixes/MyFaces4658Test.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4658/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4658/osgi.debug.options
  dev/io.openliberty.org.apache.myfaces.4.0_fat/publish/servers/faces40_myfaces4658/server.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/resources/WEB-INF/beans.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/resources/WEB-INF/customTag.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/src/io/openliberty/org/apache/faces40/fat/myfaces4658/ConfirmBean.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/test-applications/MYFACES-4658.war/src/io/openliberty/org/apache/faces40/fat/myfaces4658/ConfirmBehavior.java
Labels: in:Web Components, CLA Signed, team:Sirius

#28364 Consolidate to use one JAX-RS filter from com.ibm.ws.jaxrs.2.x.monitor for MP Metrics 5.x (+ dynamic service fix)
  dev/com.ibm.ws.jaxrs.2.x.monitor.component/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/MonitorAppStateListener.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/RestMetricsCallback.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/metrics/service/package-info.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/.classpath
  dev/io.openliberty.restfulWS.mpMetrics.filter/bnd.bnd
  dev/io.openliberty.restfulWS.mpMetrics.filter/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/MonitorAppStateListener.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMetricsCallbackImpl.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestMonitorKeyCache.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#28381 Skipping Data tests on Postgres due to EclipseLink issues
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
Labels: noproductcode, CLA Signed

#28199 JAX-WS and JAX-RS 2.1: Add additional logging to CXF's JAXB code for improved servicability.
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/EscapeHandlerInvocationHandler.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBContextCache.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/NamespaceMapper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/SchemaCollectionContextProxy.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBContextInitializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBDataBinding.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBEncoderDecoder.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBSchemaInitializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/attachment/JAXBAttachmentSchemaValidationHack.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataReaderImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/io/DataWriterImpl.java
Labels: CLA Signed

#28169 Ph59682
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/common/xml/ParseSupport.java
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/common/xml/TransformSupport.java
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/el/xml/ParseTag.java
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/el/xml/TransformTag.java
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/rt/xml/ParseTag.java
  dev/io.openliberty.org.apache.taglibs.standard/src/org/apache/taglibs/standard/tag/rt/xml/TransformTag.java
Labels: CLA Signed, target:24006

#28365 Fix integration of virtual threads into threading bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.1/io.openliberty.concurrent-3.1.feature
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/location/internal/Activator.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/JavaInfo.java
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutorProvider.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/VirtualThreadDisallowed.java
  dev/io.openliberty.threading.internal.java21/bnd.bnd
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_cs.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_de.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_es.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_fr.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_hu.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_it.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_ja.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_ko.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_pl.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_pt_BR.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_ro.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_ru.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_zh.nlsprops
  dev/io.openliberty.threading.internal.java21/resources/io/openliberty/threading/internal/java21/resources/ThreadingMessages_zh_TW.nlsprops
  dev/io.openliberty.threading.virtual.internal/.classpath
  dev/io.openliberty.threading.virtual.internal/.gitignore
  dev/io.openliberty.threading.virtual.internal/.project
  dev/io.openliberty.threading.virtual.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.threading.virtual.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.threading.virtual.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.threading.virtual.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.threading.virtual.internal/bnd.bnd
  dev/io.openliberty.threading.virtual.internal/src/io/openliberty/threading/virtual/internal/VirtualThreadOperations.java
  dev/io.openliberty.threading.virtual.internal/src/io/openliberty/threading/virtual/internal/package-info.java
  dev/io.openliberty.threading.virtual/.classpath
  dev/io.openliberty.threading.virtual/.gitignore
  dev/io.openliberty.threading.virtual/.project
  dev/io.openliberty.threading.virtual/.settings/bndtools.core.prefs
  dev/io.openliberty.threading.virtual/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.threading.virtual/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.threading.virtual/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.threading.virtual/bnd.bnd
  dev/io.openliberty.threading.virtual/src/io/openliberty/threading/virtual/VirtualThreadOps.java
  dev/io.openliberty.threading.virtual/src/io/openliberty/threading/virtual/package-info.java
Labels: team:Zombie Apocalypse, ID review not needed, CLA Signed, L2 ReviewNotRequired

#28369 Update persistence-3.2 feature to use Liberty's asm bundle
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/AbstractJPAProviderIntegration.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/fat/src/com/ibm/ws/jpa/jpa31/AsmServiceTest.java
Labels: CLA Signed, team:Performance, performance

#28342 Changes to deliver staged version of Persistence API 3.2 (i.e. M3)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.2.feature
  dev/io.openliberty.jakarta/persistence.3.2.bnd
  dev/io.openliberty.org.eclipse.persistence-3.2/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed

#28391 Start test after recovery completes
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.norecoverygroup/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.shortlease/server.xml
Labels: noproductcode, CLA Signed

#28407 Instant, BigDecimal, and BigInteger basic types
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DebtPerWorker.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DemographicInfo.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Demographics.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27859 Fix jdkSourceLevel
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava17Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava21Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava7Test.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspJava7Server/.gitignore
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspJava7Server/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/jspJava7Server/server.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestJSPWithJava17.war/resources/testJava21.jsp
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/JspOptions.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/compiler/JDTCompiler.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/compiler/StandardJspCompiler.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/JspEngineElement.java
Labels: in:Web Components, release bug, team:Sirius

#28410 don't use root tmp directory
  dev/com.ibm.ws.cdi.third.party_fat/fat/src/com/ibm/ws/cdi/thirdparty/tests/HibernateSearchTest.java
  dev/com.ibm.ws.cdi.third.party_fat/publish/servers/cdi20HibernateSearchServer/persistence.xml
Labels: noproductcode, CLA Signed

#28236 Enhance async servlet log
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/AsyncReadCallback.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/listener/ReadListenerRunnable.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/async/listener/WriteListenerRunnable.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/async/AsyncContextImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/async/ServiceWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28297 Fail the checkpoint if the application fails to start
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/StartAction.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint.springboot.fat30.app/src/main/java/io/openliberty/checkpoint/springboot/fat30/app/TestApplication.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/test-applications/app2/src/app2/EarlyStartupAppCode.java
  dev/io.openliberty.checkpoint_fat_springboot/fat/src/io/openliberty/checkpoint/fat/springboot/BasicSpringBootFailStart.java
  dev/io.openliberty.checkpoint_fat_springboot/fat/src/io/openliberty/checkpoint/fat/springboot/FATSuite.java
Labels: CLA Signed

#28412 Repeat earlier Bean Validation tests with Jakarta Validation 3.1
  dev/com.ibm.ws.beanvalidation.v11_fat/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/FATSuite.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/basic/BasicValidation11Test.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/cdi/BeanValidation11CDITest.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/cdi/BeanValidation20CDITest.java
  dev/com.ibm.ws.beanvalidation.v11_fat/fat/src/com/ibm/ws/beanvalidation/fat/ejb/EJBModule11Test.java
  dev/com.ibm.ws.beanvalidation.v20_fat/bnd.bnd
  dev/com.ibm.ws.beanvalidation.v20_fat/fat/src/com/ibm/ws/bval/v20/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#28425 refactor method parameter annotations to distinguish versions
  dev/io.openliberty.data.1.0.internal/src/io/openliberty/data/internal/v1_0/Data_1_0.java
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/ParamInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/version/DataVersionCompatibility.java
Labels: team:Zombie Apocalypse, CLA Signed

#28428 Move crac API to dev/api/stable folder
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.4/io.openliberty.crac-1.4.feature
  dev/io.openliberty.checkpoint_fat_crac/bnd.bnd
  dev/io.openliberty.checkpoint_fat_crac/build.gradle
  dev/io.openliberty.org.crac.1.4/.classpath
  dev/io.openliberty.org.crac.1.4/.gitignore
  dev/io.openliberty.org.crac.1.4/.project
  dev/io.openliberty.org.crac.1.4/.settings/bndtools.core.prefs
  dev/io.openliberty.org.crac.1.4/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.crac.1.4/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.crac.1.4/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.crac.1.4/bnd.bnd
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_cs.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_de.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_es.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_fr.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_hu.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_it.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_ja.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_ko.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_pl.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_pt_BR.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_ro.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_ru.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_zh.nlsprops
  dev/io.openliberty.org.crac.1.4/resources/io/openliberty/crac/resources/CRaCMessages_zh_TW.nlsprops
  dev/io.openliberty.org.crac.1.4/src/org/crac/Core.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/GlobalContextWrapper.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/LibertyCheckpoint.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/management/CRaCImpl.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/management/CRaCMXBean.java
  dev/io.openliberty.org.crac.1.4/src/org/crac/package-info.java
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#28416 Fix errors during Database Rotation
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_Web.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_Web.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/fat/src/com/ibm/ws/jpa/jpa31/AsmServiceTest.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_EJB.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_Web.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28376 update bcprov lib to 1.78.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.install/bnd.bnd
Labels: CLA Signed, target:24006

#28086 Upgrade EE10 to RESTEasy 6.2.8
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee10/src/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.cdi.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee11/src/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/concurrent/ContextualExecutorService.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ContextParameterInjector.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormInjector.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ResourceLocatorInvoker.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/ServerResponseWriter.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/providerfactory/CommonProviders.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/server/servlet/ServletContainerDispatcher.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/config/DefaultConfiguration.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/config/Options.java
  dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/src/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartResource.java
  dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartTestServlet.java
Labels: CLA Signed

#27768 Add error messages when credential validation fails due to missing values
  dev/io.openliberty.security.jakartasec.3.0.internal/resources/io/openliberty/security/jakartasec/internal/resources/JakartaSecurity30Messages.nlsprops
  dev/io.openliberty.security.jakartasec.3.0.internal/src/io/openliberty/security/jakartasec/identitystore/OidcIdentityStore.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/MessageConstants.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationClaimsDefinitionTests.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationUserInfoTests.java
Labels: ID reviewed, CLA Signed, team:Security SSO, L2 Reviewed, In Progress

#28395 Log a warning message when HTTP Session Cache attributes are updated at restore
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache/resources/com/ibm/ws/session/store/cache/resources/WASSessionCache.nlsprops
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheStoreService.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/bnd.bnd
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/build.gradle
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheConfigUpdateTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheOneServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/FATSuite.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/publish/servers/com.ibm.ws.session.cache.config.fat.infinispan.checkpointServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/publish/servers/com.ibm.ws.session.cache.config.fat.infinispan.checkpointServer/derby.properties
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/publish/servers/com.ibm.ws.session.cache.config.fat.infinispan.checkpointServer/jvm.options
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/publish/servers/com.ibm.ws.session.cache.config.fat.infinispan.checkpointServer/server.env
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/publish/servers/com.ibm.ws.session.cache.config.fat.infinispan.checkpointServer/server.xml
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/fat/src/io/openliberty/checkpoint/session/cache/infinispan/container/CheckpointSessionCacheOneServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/fat/src/io/openliberty/checkpoint/session/cache/infinispan/container/CheckpointSessionCacheTwoServerTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#28415 Initial no-ship delivery of HTTP Stats (for Mbeans and for mpMetrics-5.x)
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.httpStat-monitor1.0.jakarta.feature
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/io.openliberty.http.monitor/.classpath
  dev/io.openliberty.http.monitor/.gitignore
  dev/io.openliberty.http.monitor/.project
  dev/io.openliberty.http.monitor/.settings/bndtools.core.prefs
  dev/io.openliberty.http.monitor/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStatAttributes.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStats.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletContainerInitializer.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/mbean/HttpStatsMXBean.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/mbean/package-info.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/metrics/HTTPMetricAdapter.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/metrics/RestMetricManager.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/metrics/package-info.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/package-info.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/MPMetricsHTTPMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/package-info.java
  dev/io.openliberty.microprofile.metrics.5.1.internal/bnd.bnd
Labels: CLA Signed

#28454 Increase trace for concurrent persistent FAT
  dev/com.ibm.ws.concurrent.persistent_fat_simctrl/publish/servers/com.ibm.ws.concurrent.persistent.fat.simctrl/bootstrap.properties
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#28433 Implementing callInTransaction method
  dev/com.ibm.ws.jpa.container.v32/src/com/ibm/ws/jpa/container/v32/JPAEMFactoryV32.java
Labels: in:JPA, CLA Signed

#28423 Update netty dependencies from 4.1.100.Final to 4.1.109.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: in:Transport, CLA Signed, team:Sirius

#28346 fix issue with security re-auth/restore and GRPC
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
Labels: CLA Signed

#28462 Improve beta and release post templates
  .github/ISSUE_TEMPLATE/04_blog_post_beta.md
  .github/ISSUE_TEMPLATE/05_blog_post_ga_release.md
Labels: noproductcode, CLA Signed

#28456 return types for record entities
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28445 Fix NPE in toString()
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/EmbeddableTransactionImpl.java
Labels: CLA Signed

#28474 Updates from recent changes
  dev/com.ibm.ws.kernel.feature.core/.classpath
  dev/com.ibm.ws.kernel.feature.resolver/.classpath
  dev/com.ibm.ws.kernel.feature.resolver_fat/.classpath
  dev/com.ibm.ws.repository.resolver/.classpath
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureUtilities.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE10Action.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE11Action.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11Features.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/.classpath
  dev/io.openliberty.threading.virtual/.settings/org.eclipse.jdt.core.prefs
  dev/wlp.lib.extract/.classpath
  dev/wlp.lib.extract/bnd.bnd
Labels: CLA Signed, team:Performance

#28458 Use stopAppStartUponListenerException for EE 8
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFATServer/server.xml
Labels: noproductcode, CLA Signed

#28356 oidc client update to make sure that we can access post params
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
Labels: CLA Signed

#28453 Remove disallowed, unused algorithm constants
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/asn1/oiw/OIWObjectIdentifiers.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/asn1/pkcs/PKCSObjectIdentifiers.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/asn1/x509/X509ObjectIdentifiers.java
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/asn1/x9/X9ObjectIdentifiers.java
Labels: CLA Signed

#28488 Increasing timeout
  dev/com.ibm.ws.config.schemagen/test/com/ibm/ws/config/schemagen/internal/SchemaGenTest.java
Labels: noproductcode, CLA Signed

#28476 Introduce minimum perf factor
  dev/com.ibm.ws.wsat.migration_fat.3/fat/src/tests/SleepTest.java
Labels: noproductcode, CLA Signed

#28478 Increase client inactivity timeout to cope with slow test servers
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server1/server.xml
  dev/com.ibm.ws.wsat_fat.db/publish/servers/WSATDB_Server2/server.xml
Labels: noproductcode, CLA Signed

#28482 Inhibit peer recovery during regular recovery tests
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.5/publish/servers/WSATRecovery3/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.5/publish/servers/WSATRecoveryClient1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.5/publish/servers/WSATRecoveryServer1/server.xml
Labels: CLA Signed

#28440 Add trace for WebAppInvocationCollaborator
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/collaborator/CollaboratorHelperImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/collaborator/CollaboratorServiceImpl.java
Labels: in:Web Components, team:Sirius, trace

#27761 Update to the latest Jakarta API service releases
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.activation-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.nosql-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlBinding-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.xmlWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-3.0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonbImpl-3.0.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jsonpImpl-2.1.1.feature
  dev/io.openliberty.jakarta.activation.2.1/bnd.bnd
  dev/io.openliberty.jakarta.jsonb.3.0/bnd.bnd
  dev/io.openliberty.jakarta.jsonp.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.2.1/build.gradle
  dev/io.openliberty.jakarta.websocket.client.2.1/bnd.bnd
  dev/io.openliberty.jakarta.websocket.client.2.1/build.gradle
  dev/io.openliberty.jakarta.xmlBinding.4.0/bnd.bnd
  dev/io.openliberty.jakarta/mail.2.1.bnd
  dev/io.openliberty.jakarta/soap.3.0.bnd
  dev/io.openliberty.jakarta/xmlWS.4.0.bnd
  dev/io.openliberty.jaxws.beanvalidation_fat/.project
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.wsoc.2.1.internal_fat/build.gradle
Labels: CLA Signed, team:Performance

#28119 Install tools update feature product match logic
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
  dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/EsaResource.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
  dev/wlp.lib.extract/src/wlp/lib/extract/ProductMatch.java
  dev/wlp.lib.extract/src/wlp/lib/extract/SelfExtractor.java
  dev/wlp.lib.extract/test/wlp/lib/extract/SelfExtractorTest.java
Labels: CLA Signed

#28432 Generate Set-Cookie from SessionCookieConfig not include the configured attributes
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/SessionAffinityManagerImpl.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/session/impl/HttpSessionContextImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal/src/io/openliberty/webcontainer60/session/impl/SessionAffinityManagerImpl60.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60SessionCookieConfigXMLTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/SessionCookieConfigSCI.jar/src/testsci/jar/servlets/TestSessionCookieConfigServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius

#28487 Fix Jakarta Data tests for Oracle
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTestCheckpoint.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATestCheckpoint.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28489 Tolerate javax.xml.stream.XMLStreamException
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/fat/src/tests/ReroutePeerRecoveryTest.java
Labels: noproductcode, CLA Signed

#28492 CVE Reporting: Fix for testNonExistingServer failures
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/CVEResponseTest.java
Labels: noproductcode, CLA Signed

#28503 Adding Sort validation and test for Sort.of
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: CLA Signed

#28500 record with embeddable
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/ClassDefiner.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Rating.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Ratings.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/TaxPayers.java
Labels: team:Zombie Apocalypse, CLA Signed

#28512 Revert "HTTP Stats fixes, deregistering mbean + beta"
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.httpStat-monitor1.0.jakarta.feature
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/MonitorAppStateListener.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/build.gradle
Labels: CLA Signed

#28506 Update stabilized features to not start up when using Jakarta 11
  dev/com.ibm.websphere.appserver.features/visibility/public/couchdb-1.0/com.ibm.websphere.appserver.couchdb-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mongodb-2.0/com.ibm.websphere.appserver.mongodb-2.0.feature
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11Features.java
Labels: CLA Signed, team:Performance

#28437 Remove beta guard for crac-1.4 and InstantOn support for springBoot-3.0
  dev/com.ibm.websphere.appserver.features/visibility/public/crac-1.4/io.openliberty.crac-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-3.0/io.openliberty.springBoot-3.0.feature
  dev/io.openliberty.checkpoint_fat_crac/publish/servers/cracFATServer/jvm.options
  dev/io.openliberty.checkpoint_fat_springboot/publish/servers/checkpointSpringBoot/jvm.options
  dev/io.openliberty.checkpoint_fat_springboot_data/publish/servers/checkpointSpringBootData/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_springboot_data/publish/servers/checkpointSpringBootData/jvm.options
  dev/io.openliberty.org.crac.1.4/src/org/crac/LibertyCheckpoint.java
Labels: CLA Signed

#28467 crypto.common updates - fix bundle not being exported and update FIPS check
  dev/com.ibm.ws.crypto.common/bnd.bnd
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/FipsUtils.java
  dev/com.ibm.ws.crypto.common/src/com/ibm/ws/crypto/common/package-info.java
  dev/com.ibm.ws.crypto.common/test/com/ibm/ws/crypto/common/FipsUtilsTest.java
Labels: CLA Signed, team:Core Security

#28513 Invalid JASPIC warning.
  dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java
Labels: CLA Signed

#28485 Connectors support for InstantOn
  dev/com.ibm.ws.jca/bnd.bnd
  dev/com.ibm.ws.jca/resources/com/ibm/ws/jca/internal/resources/J2CAMessages.nlsprops
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/J2CTimer.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/WorkProxy.java
  dev/com.ibm.ws.jca_fat_derbyra/bnd.bnd
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyRACheckpointLimitationsTest.java
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyRACheckpointTest.java
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/FATSuite.java
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/bootstrap.properties
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/jvm.options
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/server.env
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/server.xml
  dev/com.ibm.ws.jca_fat_derbyra/test-applications/fvtweb/src/web/DerbyRACheckpointServlet.java
  dev/com.ibm.ws.jca_fat_derbyra/test-resourceadapters/fvt-resourceadapter/src/fat/derbyra/resourceadapter/DerbyResourceAdapter.java
  dev/com.ibm.ws.security.auth.data.common/bnd.bnd
  dev/com.ibm.ws.security.auth.data.common/src/com/ibm/ws/security/auth/data/internal/AuthDataImpl.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointPasswordUtilities/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/DefaultPrincipalMappingApp/src/io/openliberty/checkpoint/fat/passwordutil/web/DefaultPrincipalMappingServlet.java
Labels: ID reviewed, CLA Signed

#28227 Remove InstantOn beta guards for Jakarta Messaging, Connectors and MDB
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.0/io.openliberty.connectors-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/connectors-2.1/io.openliberty.connectors-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jca-1.7/com.ibm.websphere.appserver.jca-1.7.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jms-2.0/com.ibm.websphere.appserver.jms-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-3.2/com.ibm.websphere.appserver.mdb-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mdb-4.0/io.openliberty.mdb-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messaging-3.0/io.openliberty.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messaging-3.1/io.openliberty.messaging-3.1.feature
  dev/io.openliberty.ejbcontainer.mdb.checkpoint_fat/publish/servers/checkpointMsgEndpointServer/bootstrap.properties
  dev/io.openliberty.ejbcontainer.mdb.checkpoint_fat/publish/servers/checkpointMsgEndpointServer/jvm.options
Labels: CLA Signed

#28531 MPOpenAPI IndexUtils javadoc fixes
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/IndexUtils.java
Labels: CLA Signed

#28539 Wait for SSL start before starting the test.
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/JakartaEE10Test.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/JakartaEE11Test.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/JakartaEE9Test.java
Labels: noproductcode, CLA Signed, team:Performance

#28524 Update compatibility list for EE 11 features
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11Features.java
Labels: noproductcode, CLA Signed, team:Performance

#28540 Remove beta guard from Connectors Checkpoint FAT
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/jvm.options
Labels: noproductcode, CLA Signed

#28535 Correct FeatureResolverImpl.addPostponed.
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed, Versionless

#28537 Re-introduce (re-switch) `io.openliberty.httpStat-monitor1.0.jakarta` to beta (incl. fixes)
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.httpStat-monitor1.0.jakarta.feature
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected_WL.xml
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/MonitorAppStateListener.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletContainerInitializer.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/mbean/HttpStatsMXBean.java
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat/build.gradle
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/build.gradle
Labels: CLA Signed

#28551 Initialize Derby before concurrent access in FAT
  dev/com.ibm.ws.concurrent.persistent_fat_feature/test-bundles/userFeature/src/test/concurrent/persistent/feature/TaskStoreTester.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#28546 disable resolver fat tests
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/BaselineSingletonUnitTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/FATSuite.java
Labels: noproductcode, CLA Signed

#28534 Add WLP-Platform to mpVersion features
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-1.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-1.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-1.4.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-3.3.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-5.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-6.1.feature
Labels: CLA Signed

#28530 Add WLP-Platform to eeCompatible features
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-9.0.feature
Labels: CLA Signed

#28547 Refactor todos for Jakarta Data testing
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28554 Add TODOs for database failures on Jakarta Data TCK
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/standalone/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28393 Put faces-4.1 in Beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.facesProvider-4.1.0.MyFaces.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.jsf-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.faces-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.1/io.openliberty.faces-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces/io.openliberty.versionless.faces.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf/io.openliberty.versionless.jsf.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/websocket-2.2/io.openliberty.websocket-2.2.feature
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected_WL.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#28553 Skip on Java 23 plus for MP Concurrency test
  dev/com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentConfigApp/src/concurrent/mp/fat/config/web/MPConcurrentConfigTestServlet.java
Labels: noproductcode, CLA Signed

#28486 Add Feature label to issues opened using feature template
  .github/ISSUE_TEMPLATE/03_feature.md
Labels: CLA Signed

#28544 Add repeats for MpTelemetry-2.0 JaxRs Tests
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestServlet.java
Labels: noproductcode, CLA Signed

#28543 JAX-WS: Implement IgnoreUnexpectedElementValidationEventHandler for beta ignoreUnexpectedElements config
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/IgnoreUnexpectedElementConfigTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/global-false-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/global-true-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/incorrect-servicename-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-false-global-false-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-false-global-true-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-false-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-true-global-false-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-true-global-true-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/files/AddedElementHandlerChainTestServer/servicename-true-server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/servers/AddedElementHandlerChainTestServer/jvm.options
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/test-applications/testHandlerClient/src/com/ibm/samples/jaxws/client/servlet/IgnoreUnexpectedElementTestServiceServlet.java
  dev/com.ibm.ws.jaxws.2.3.common/bnd.bnd
  dev/com.ibm.ws.jaxws.2.3.common/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/client/LibertyWebServiceClientInInterceptor.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/internal/ConfigHolder.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/jaxb/IgnoreUnknownElementValidationEventHandler.java
  dev/com.ibm.ws.jaxws.2.3.common/test/com/ibm/ws/jaxws/client/LibertyWebServiceClientInInterceptorTest.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/io/openliberty/jaxws/jaxb/IgnoreUnexpectedElementValidationEventHandler.java
Labels: CLA Signed

#28509 Clean up JSPJava7Test test ordering problem and cleanup other JSPJava tests
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava11Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava21Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava7Test.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava8Test.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#28573 Tolerate catch-up EJB timers in NP Timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#28579 Update comments for MpTelemetry-2.0 tests
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerBaseTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/responses/JaxRsResponseCodeTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/route/JaxRsRouteTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/MetricsDisabledServlet.java
Labels: noproductcode, CLA Signed

#28583 Revert "Fix errors during Database Rotation"
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_Web.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_EJB.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation_Web.java
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/fat/src/com/ibm/ws/jpa/jpa31/AsmServiceTest.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_EJB.java
  dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/fat/src/com/ibm/ws/jpa/tests/jpaconfig/tests/DefaultProperties_Web.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28576 Update JSON B/P TCKs to not run on Java 23
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/fat/src/io/openliberty/jakarta/jsonb/tck/JsonbTckLauncher.java
  dev/io.openliberty.jakarta.jsonp.2.1_fat_tck/fat/src/io/openliberty/jakarta/jsonp/tck/JsonpTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#28575 change eeCompatible 0.0 to noship
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-0.0.feature
Labels: CLA Signed

#28562 Upgrade Restfulws to RESTEasy 7.0.0.Alpha2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS4.0-validator3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS4.0-xmlBinding4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-4.0/io.openliberty.restfulWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-4.0/io.openliberty.restfulWSClient-4.0.feature
  dev/io.openliberty.org.jboss.resteasy.cdi.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee11/build.gradle
  dev/io.openliberty.org.jboss.resteasy.common.ee11/src/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  dev/io.openliberty.org.jboss.resteasy.jaxb.provider.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee11/bnd.bnd
  dev/io.openliberty.restfulWS.3.0_fat/bnd.bnd
Labels: in:JAX-RS

#28362 Set-Cookie header with arbitrary attributes
  dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/cookies/CookieHeaderByteParser.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/cookies/CookieUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/HttpDispatcher.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee/behaviors/HttpBehavior.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60CookieSetAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61SetCookieRandomAttributes.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SetCookieAttributes/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_SetCookieAttributes/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/SetCookieViaResponseHeader.war/src/setcookie/servlets/SetCookieAttributesViaResponseHeader.java
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 Reviewed, jakartaEE11

#28577 Add Telemetry logging exporter provider for metrics
  dev/io.openliberty.io.opentelemetry.2.0/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.metrics.ConfigurableMetricExporterProvider
Labels: CLA Signed

#28588 collection attributes
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/AreaInfo.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/City.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/TaxPayers.java
Labels: team:Zombie Apocalypse, CLA Signed

#28521 XML Binding 4.0: Remove RI from TCCL and add new feature tests
  dev/com.ibm.ws.jaxb_fat/build.gradle
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/ThirdPartyJAXBFromAppTest.java
  dev/com.ibm.ws.jaxb_fat/publish/files/server-ee10.xml
  dev/com.ibm.ws.jaxb_fat/publish/files/server-ee9.xml
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat.no-jaxb-feature/jvm.options
  dev/com.ibm.ws.jaxb_fat/publish/servers/jaxb_fat/jvm.options
  dev/com.ibm.ws.jaxb_fat/test-applications/thirdPartyJaxbApp/src/jaxb/thirdparty/web/ThirdPartyJAXBFromAppTestServlet.java
  dev/io.openliberty.xmlBinding.4.0.internal.tools/bnd.bnd
Labels: CLA Signed

#28565 FATS for HTTP Stats/metrics (+ a fix for creating path)
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.http.monitor_fat/.classpath
  dev/io.openliberty.http.monitor_fat/.project
  dev/io.openliberty.http.monitor_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.http.monitor_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.http.monitor_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.http.monitor_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.http.monitor_fat/bnd.bnd
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/NoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/RestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/publish/servers/JSPServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/JSPServer/jvm.options
  dev/io.openliberty.http.monitor_fat/publish/servers/JSPServer/server.xml
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleRestServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleRestServer/jvm.options
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleRestServer/server.xml
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleServletServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleServletServer/jvm.options
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleServletServer/server.xml
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/Testhtml.html
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/WEB-INF/web.xml
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/configured.jsp
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/default.html
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/unconfigured.jsp
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/ApplicationResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/FailResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/ParamsResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/SimpleResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/ServletApp/src/io/openliberty/http/monitor/fat/servletApp/FailServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/ServletApp/src/io/openliberty/http/monitor/fat/servletApp/SimpleServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/RootWildCardServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/SubWildCard1.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/SubWildCard2.java
Labels: CLA Signed

#28600 Fixup eclipse settings files
  dev/io.openliberty.microprofile.faulttolerance.telemetry/.classpath
  dev/io.openliberty.microprofile.faulttolerance.telemetry/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.request.probe.audit.rest/.project
Labels: noproductcode, CLA Signed, team:Performance

#28548 Include all dependencies in archive expander jar.
  dev/com.ibm.ws.filetransfer.routing.archiveExpander/bnd.bnd
Labels: CLA Signed

#28581 Remove CVE Reporting bundle from Kernel manifest
  dev/com.ibm.ws.kernel.boot/publish/platform/kernelCore-1.0.mf
  dev/io.openliberty.reporting.internal_fat/fat/src/io/openliberty/reporting/internal/fat/FATSuite.java
Labels: CLA Signed

#28611 Revert mail-api 2.1 update from PR #27761
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.mail-2.1.feature
  dev/io.openliberty.jakarta/mail.2.1.bnd
Labels: CLA Signed, team:Performance
