Repository OpenLiberty/open-liberty, pull requests merged in 2024-03, with the labels that each got.

#27807 page impls and method to obtain Cursor from spec
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/KeysetAwarePageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/KeysetAwareSliceRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/PageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/SliceRecord.java
Labels: team:Zombie Apocalypse, CLA Signed

#27764 Issue #27763: Add CWWKB0758E to FeatureErrors.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureErrors.java
Labels: noproductcode, CLA Signed

#27805 JAX-WS: Share ComponentMetaData with child threads
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/threading/LibertyJaxWsAutomaticWorkQueueImpl.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/threading/LibertyJaxWsWorkQueueThreadContextHelper.java
  dev/io.openliberty.jaxws.beanvalidation_fat/.classpath
  dev/io.openliberty.jaxws.beanvalidation_fat/.gitignore
  dev/io.openliberty.jaxws.beanvalidation_fat/.project
  dev/io.openliberty.jaxws.beanvalidation_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxws.beanvalidation_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxws.beanvalidation_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxws.beanvalidation_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxws.beanvalidation_fat/bnd.bnd
  dev/io.openliberty.jaxws.beanvalidation_fat/build.gradle
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/beanvalidation/AbstractBeanValidationTest.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/beanvalidation/BeanValidationTest.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/beanvalidation/CDIBeanValidationTest.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/beanvalidation/FATSuite.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/beanvalidation/InjectionBeanValidationTest.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/BeanValidationWebService.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/CDIBeanValidationWebService.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/OneWayWithJAXBAnnotatedMethodValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/OneWayWithJAXBAnnotatedValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/OneWayWithMethodValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/OneWayWithValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithMethodValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithMethodValidationResponse.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidationJAXBAnnotatedMethodValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidationJAXBAnnotatedMethodValidationResponse.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidationJAXBAnnotatedValidation.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidationJAXBAnnotatedValidationResponse.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/TwoWayWithValidationResponse.java
  dev/io.openliberty.jaxws.beanvalidation_fat/fat/src/com/ibm/ws/jaxws/cdi/beanvalidation/stubs/package-info.java
  dev/io.openliberty.jaxws.beanvalidation_fat/publish/servers/beanValidationServer/bootstrap.properties
  dev/io.openliberty.jaxws.beanvalidation_fat/publish/servers/beanValidationServer/server.xml
  dev/io.openliberty.jaxws.beanvalidation_fat/publish/servers/cdiBeanValidationServer/bootstrap.properties
  dev/io.openliberty.jaxws.beanvalidation_fat/publish/servers/cdiBeanValidationServer/server.xml
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/beanValidation/resources/WEB-INF/wsdl/CDIBeanValidationWebService.wsdl
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/beanValidation/src/com/ibm/ws/jaxws/beanvalidation/BeanValidationWebServiceImpl.java
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/beanValidation/src/com/ibm/ws/jaxws/beanvalidation/InjectionValidatorBeanValidationWebServiceImpl.java
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/beanValidation/src/com/ibm/ws/jaxws/beanvalidation/InjectionValidatorFactoryBeanValidationWebServiceImpl.java
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/cdiBeanValidation/resources/WEB-INF/beans.xml
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/cdiBeanValidation/resources/WEB-INF/wsdl/CDIBeanValidationWebService.wsdl
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/cdiBeanValidation/src/com/ibm/ws/jaxws/cdi/beanvalidation/CDIValidatorBeanValidationWebServiceImpl.java
  dev/io.openliberty.jaxws.beanvalidation_fat/test-applications/cdiBeanValidation/src/com/ibm/ws/jaxws/cdi/beanvalidation/CDIValidatorFactoryBeanValidationWebServiceImpl.java
Labels: CLA Signed

#27795 remove unused code from mcwrapper class
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/J2CGlobalConfigProperties.java
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
Labels: CLA Signed

#27802 Update 02_feature_request.md to use new label
  .github/ISSUE_TEMPLATE/02_feature_request.md
Labels: noproductcode, CLA Signed

#27678 Add test to remove sensitive headers from TRACE requests
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61DoTraceRemoveSensitiveHeadersTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_DoTraceRemoveHeadersTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_DoTraceRemoveHeadersTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DoTraceRemoveSensitiveHeaders.war/src/removeheaders/servlets/RemoveSensitiveHeadersServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27785 Added NLS_MESSAGEFORMAT_VAR to the MP Health NLSPROPS file
  dev/io.openliberty.microprofile.health.internal.common/resources/io/openliberty/microprofile/health/resources/Health.nlsprops
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#27806 use long instead of integer in SipApplicationSession
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/appqueue/NativeMessageDispatchingHandler.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/asynch/AsynchronousWorkListenerWrapper.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/asynch/AsynchronousWorkTask.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/events/EventsDispatcher.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/events/ListenerTask.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/osgi/ServletInstanceHolderInterface.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/parser/ServletsInstanceHolder.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/ProxyBranchTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/ProxyTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/router/tasks/RoutedTask.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/SipApplicationSessionImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/BaseTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/ExpirationTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/Invite2xxRetransmitTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/ReliabeResponseRetransmitTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/timer/ServletTimerImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/util/Queueable.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/SignalingEndOfTask.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/ThreadLocalStorage.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/filters/SipServletListener.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/message/SipMessage.java
Labels: CLA Signed

#27227 26527 add core policy wsdl trace
  dev/com.ibm.ws.jaxws.ejb_fat/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentSerializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentUtil.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/CXFExtensionBundleListener.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/logging/LogUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/spi/NamespaceClassGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/util/ProxyHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/configuration/jsse/TLSClientParameters.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/endpoint/ClientImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/AttachmentOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/MessageSenderInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/OneWayProcessorInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/OutgoingChainInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/ServiceInvokerInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxInEndingInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxOutEndingInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/phase/PhaseInterceptorChain.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/invoker/AbstractInvoker.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/AbstractMessageContainer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/MessagePartInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxSource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/transport/ChainInitiationObserver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/workqueue/SynchronousExecutor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyEngineImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/mtom/MTOMPolicyInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/selector/MinimalAlternativeSelector.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/interceptors/BareOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/interceptors/DocLiteralInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/service/factory/ReflectionServiceFactoryBean.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl11/WSDLServiceBuilder.java
Labels: CLA Signed

#27814 Update tests to set orbSSLInitTimeout to not time out
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleEar/server.xml
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleWar/server.xml
  dev/com.ibm.ws.javaee.8.0_fat/publish/servers/javaee8.fat/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee10toMP/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee7toMP/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee8toMP/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee9toMP/server.xml
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/bowlingball/server.xml
  dev/io.openliberty.jakartaee10.internal_fat/publish/servers/jakartaee10.fat/server.xml
  dev/io.openliberty.jakartaee9.internal_fat/publish/servers/jakartaee9.fat/server.xml
  dev/io.openliberty.jee.internal_fat/publish/servers/simpleEar/server.xml
  dev/io.openliberty.jee.internal_fat/publish/servers/simpleWar/server.xml
  dev/io.openliberty.microprofile.internal_fat/publish/servers/MPCompatibleServer/MP40andEE8.xml
  dev/io.openliberty.microprofile5.internal_fat/publish/servers/MP5CompatibleServer/MP50andEE9.xml
  dev/io.openliberty.microprofile6.internal_fat/publish/servers/MP6andEE10/server.xml
  dev/io.openliberty.microprofile61.internal_fat/publish/servers/MP61andEE10/server.xml
Labels: noproductcode, CLA Signed, team:Performance

#27816 hasNext and hasPrevious from spec
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetAwareSlice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/KeysetAwarePageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/KeysetAwareSliceRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/PageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/SliceRecord.java
Labels: team:Zombie Apocalypse, CLA Signed

#27813 Fix permissions in EJB FAT
  dev/com.ibm.ws.couchdb_fat/publish/servers/com.ibm.ws.couchdb.fat.server/server.xml
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSATestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSMTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/EJB3INJSXTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.injection_fat/test-applications/LookupOverrideTestApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.legacy_fat/test-applications/EJBinWARTestApp.ear/resources/META-INF/permissions.xml
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27815 NLS translations for 24.0.0.3
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_cs.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_de.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_es.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_fr.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_hu.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_it.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_ja.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_ko.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_pl.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_pt_BR.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_ro.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_ru.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_zh.nlsprops
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages_zh_TW.nlsprops
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#27773 Update Pages 4.0 API to M2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.pages-4.0.feature
  dev/io.openliberty.jakarta/pages.4.0.bnd
  dev/io.openliberty.pages.4.0.internal_fat/fat/src/io/openliberty/pages40/fat/tests/Pages40ChangesTest.java
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/WEB-INF/web.xml
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/errorPage.jsp
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27792 update weld and cdi-api
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta/cdi.4.1.bnd
  dev/io.openliberty.org.jboss.weld6/build.gradle
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#27818 Increase appMgr startTimeout for server checkpointFaces-backendServices
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointFaces-backendServices/server.xml
Labels: noproductcode, team:OSGi Infrastructure

#27713 Add first set of Faces 4.1 Tests
  dev/io.openliberty.org.apache.myfaces.4.1_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/CustomDriver.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/ExtendedWebDriver.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/selenium_util/WebPage.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/CompositeExtensionTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/ConfigTests.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/ContentLengthTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/Faces41CDITests.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/RenderIdTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/UUIDConverterTest.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/files/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_cdiServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_cdiServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_compositeExtensionServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_compositeExtensionServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_configServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_configServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_contentLengthLongServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_contentLengthLongServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_renderIdServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_renderIdServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_uuidServer/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_uuidServer/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Config_Spec1764.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Config_Spec1764.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/noflow.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/return.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/simple/simple-flow.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/resources/simple/simple.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/faces41/fat/flow/beans/Bean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/faces41/fat/flow/beans/FlowBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/faces41/fat/flow/beans/Tracker.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/WEB-INF/faces-config.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/src/io/openliberty/org/apache/faces41/fat/namespace/view/NamespacedView.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/SetResponseContentLengthLong_Spec1829.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/SetResponseContentLengthLong_Spec1829.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/SetResponseContentLengthLong_Spec1829.war/src/io/openliberty/org/apache/faces41/fat/contentlengthlong/beans/ContentLengthLongBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/resources/view.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/resources/view2.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/src/io/openliberty/org/apache/faces41/fat/view/bean/Tracker.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/src/io/openliberty/org/apache/faces41/fat/view/bean/ViewBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/compositeExtension_Spec1549.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/compositeExtension_Spec1549.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/resources/fail.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/resources/index.xhtml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/src/io/openliberty/org/apache/faces41/fat/uuidconverter/beans/FailBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/src/io/openliberty/org/apache/faces41/fat/uuidconverter/beans/SuccessBean.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27110 Use http header for authentications
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/FeatureUtilityToolTest.java
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
  dev/io.openliberty.org.testcontainers/cache/images
Labels: CLA Signed

#27360 Using configAdmin to find undetected apps for mpHealth
  dev/com.ibm.ws.microprofile.health.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTracker.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30ServiceImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/HealthCheck31ServiceImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.health.3.1.internal_fat/build.gradle
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/suite/FATSuite.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminDropinsCheck/bootstrap.properties
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminDropinsCheck/server.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminWrongAppCheck/bootstrap.properties
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminWrongAppCheck/server.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminXmlCheck/bootstrap.properties
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminXmlCheck/server.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/FailedConfigAdminApplicationStateHealthCheck/bootstrap.properties
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/FailedConfigAdminApplicationStateHealthCheck/server.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminDropinsCheckApp/src/io/openliberty/microprofile/health31/config/admin/dropins/checks/app/TestLivenessCheck.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminDropinsCheckApp/src/io/openliberty/microprofile/health31/config/admin/dropins/checks/app/TestReadinessCheck.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminXmlCheckApp/src/io/openliberty/microprofile/health31/config/admin/xml/checks/app/TestLivenessCheck.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminXmlCheckApp/src/io/openliberty/microprofile/health31/config/admin/xml/checks/app/TestReadinessCheck.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/resources/META-INF/MANIFEST.MF
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/resources/META-INF/microprofile-config.properties
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/resources/WEB-INF/web.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/src/io/openliberty/microprofile/health31/fails/to/start/health/check/app/BasicMessagingBean.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/src/io/openliberty/microprofile/health31/fails/to/start/health/check/app/FailingReadinessCheck.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/src/io/openliberty/microprofile/health31/fails/to/start/health/check/app/FailsToStartServlet.java
Labels: CLA Signed

#27803 Adding existence check before warning users to reinstall an iFix.
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/IFixUtils.java
Labels: CLA Signed, release bug

#27827 Add client ID to App two producer to prevent cross app conflicts
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/mtls/mutliple/multipleapp/KafkaMtlsMultipleAppsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/mtls/single/KafkaMtlsIncorrectKeyTest.java
Labels: noproductcode, CLA Signed

#27822 metadata for ManagedThreadFactory beans
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/PropagatingAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/metadata/MTFComponentMetaData.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/metadata/MTFDeferredMetaDataFactory.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/metadata/MTFModuleMetaData.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/metadata/package-info.java
Labels: team:Zombie Apocalypse, CLA Signed

#27382 Jakarta Security, Authn, Authz initial work
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authentication-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.authorization-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.security.enterprise-4.0.feature
  dev/io.openliberty.jakarta/authentication.3.1.bnd
  dev/io.openliberty.jakarta/authorization.3.0.bnd
  dev/io.openliberty.jakarta/security.4.0.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
Labels: CLA Signed, team:Security SSO

#27468 remove back-channel logout beta guards
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op/jvm.options
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp/jvm.options
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rp2/jvm.options
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/servers/com.ibm.ws.security.backchannelLogout_fat.rs/jvm.options
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/OidcBaseClient.java
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCookieVerificationTests.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/publish/servers/com.ibm.ws.security.backchannelLogout_fat.op.saml/jvm.options
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutHelper.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/client/jose4j/util/Jose4jUtil.java
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/internal/JwtUtils.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutService.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginSessionInvalidatorTAI.java
  dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/SocialLoginTAI.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_CookieVerificationTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social.prop/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social2/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social.prop/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social/jvm.options
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/publish/servers/com.ibm.ws.security.backchannelLogout_fat.social2/jvm.options
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
Labels: CLA Signed

#27838 Add isLoggable checks before calling trace statements
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
Labels: CLA Signed, team:Performance, performance

#27800 Fix for CWWKS9590W warning for new Ciphers without WITH in their cip…
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java
Labels: CLA Signed

#27831 JAX-WS: Set eclipse settings on our beanvalidation fat to be 1.8 consistently.
  dev/com.ibm.ws.app.manager_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/io.openliberty.jaxws.beanvalidation_fat/.settings/org.eclipse.jdt.core.prefs
Labels: noproductcode, CLA Signed

#27849 JAX-WS: clean up io.openliberty.jaxws.beanvalidation_fat/bnd.bnd
  dev/io.openliberty.jaxws.beanvalidation_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#27836 JAX-WS: NPE on added trace
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/service/factory/ReflectionServiceFactoryBean.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#27847 Increase Concurrent Polling FAT timeout
  dev/com.ibm.ws.concurrent.persistent_fat_initial_polling/fat/src/com/ibm/ws/concurrent/persistent/fat/initial/polling/InitialPollingTest.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:Concurrency

#27839 server script not working on IBM i after verbose:gc changes
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: team:Zombie Apocalypse, CLA Signed

#27821 add new ldap server certificate to truststore
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.outbound.ssl/AlternateServerTrustFile.jks
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.outbound.ssl/LdapSSLTrustStore.jks
Labels: noproductcode, CLA Signed

#27860 slice consolidated into page
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Personnel.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/CursoredPage.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Page.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequestCursor.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/CursoredPageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/KeysetAwarePageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/PageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/SliceRecord.java
Labels: team:Zombie Apocalypse, CLA Signed

#27848 JAX-WS and JAX-RS 2.1: Add Guard statements to CXF trace
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentSerializer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/attachment/AttachmentUtil.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/bus/osgi/CXFExtensionBundleListener.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/jaxb/JAXBUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/spi/NamespaceClassGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/common/util/ProxyHelper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/endpoint/ClientImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/AttachmentOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/OneWayProcessorInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/OutgoingChainInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/ServiceInvokerInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxInEndingInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxOutEndingInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/interceptor/StaxOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/message/MessageImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/phase/PhaseInterceptorChain.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/invoker/AbstractInvoker.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/AbstractMessageContainer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/service/model/EndpointInfo.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxSource.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/staxutils/StaxUtils.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/transport/ChainInitiationObserver.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyEngineImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/mtom/MTOMPolicyInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/selector/MinimalAlternativeSelector.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/interceptors/BareOutInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/interceptors/DocLiteralInInterceptor.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl/service/factory/ReflectionServiceFactoryBean.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/src/org/apache/cxf/wsdl11/WSDLServiceBuilder.java
Labels: CLA Signed

#27866 Update EE 11 annotation, validation and rest transform rules
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10plus.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee11.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, team:Performance

#27820 JAX-WS: Add ManagedExecutor fat tests
  dev/io.openliberty.jaxws.executor_fat/.classpath
  dev/io.openliberty.jaxws.executor_fat/.gitignore
  dev/io.openliberty.jaxws.executor_fat/.project
  dev/io.openliberty.jaxws.executor_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxws.executor_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxws.executor_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxws.executor_fat/.settings/org.eclipse.wst.common.project.facet.core.xml
  dev/io.openliberty.jaxws.executor_fat/.settings/org.eclipse.wst.ws.service.policy.prefs
  dev/io.openliberty.jaxws.executor_fat/bnd.bnd
  dev/io.openliberty.jaxws.executor_fat/build.gradle
  dev/io.openliberty.jaxws.executor_fat/fat/src/io/openliberty/jaxws/executor/FATSuite.java
  dev/io.openliberty.jaxws.executor_fat/fat/src/io/openliberty/jaxws/executor/JAXWSExecutorTest.java
  dev/io.openliberty.jaxws.executor_fat/publish/servers/jaxwsExecutorTest/bootstrap.properties
  dev/io.openliberty.jaxws.executor_fat/publish/servers/jaxwsExecutorTest/server.xml
  dev/io.openliberty.jaxws.executor_fat/test-applications/simpleservice/resources/META-INF/permissions.xml
  dev/io.openliberty.jaxws.executor_fat/test-applications/simpleservice/src/io/openliberty/jaxws/fat/JAXWSExecutorTestServlet.java
  dev/io.openliberty.jaxws.executor_fat/test-applications/simpleservice/src/io/openliberty/jaxws/fat/SimpleWebService.java
  dev/io.openliberty.jaxws.executor_fat/test-applications/simpleservice/src/io/openliberty/jaxws/fat/SimpleWebServiceImpl.java
Labels: noproductcode, CLA Signed

#27829 Update message ID
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, jakartaEE11

#27701 runAsServer before signing/verifying jws and encrypting/decrypting jwe
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/ConsumerUtil.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JweHelper.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwsSigner.java
  dev/com.ibm.ws.security.oauth/bnd.bnd
  dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/jose4j/JwsSigner.java
  dev/com.ibm.ws.security.openidconnect.clients.common/bnd.bnd
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/JWT.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/JsonTokenUtil.java
  dev/io.openliberty.security.common.jwt/bnd.bnd
  dev/io.openliberty.security.common.jwt/src/io/openliberty/security/common/jwt/jws/JwsSignatureVerifier.java
  dev/io.openliberty.security.oidcclientcore.internal/bnd.bnd
  dev/io.openliberty.security.oidcclientcore.internal/src/io/openliberty/security/oidcclientcore/token/auth/PrivateKeyJwtAuthMethod.java
Labels: CLA Signed

#27872 Resolved UUID not working as Generated ID
  dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestUUIDEntityIDServlet.java
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/mappings/converters/UUIDConverter.java
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/mappings/converters/UUIDConverter.java
Labels: in:JPA, team:Blizzard, CLA Signed

#27732 Update OptionalELResolver to support method invocation
  dev/io.openliberty.jakarta.expressionLanguage.6.0/src/jakarta/el/OptionalELResolver.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/.classpath
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage60/fat/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage60/fat/tests/EL60OptionalELResolverTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/publish/servers/expressionLanguage60_optionalELResolverServer/bootstrap.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/publish/servers/expressionLanguage60_optionalELResolverServer/server.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60OptionalELResolverTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60OptionalELResolverTest.war/src/io/openliberty/el60/fat/optionalelresolver/beans/AnotherSimpleBean.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60OptionalELResolverTest.war/src/io/openliberty/el60/fat/optionalelresolver/beans/SimpleBeanWithOptionalProperty.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60OptionalELResolverTest.war/src/io/openliberty/el60/fat/optionalelresolver/servlets/EL60OptionalELResolverTestServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27881 Fix NullPointerException in JarFileClassLoader
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/internal/classloader/JarFileClassLoader.java
Labels: CLA Signed, team:Performance

#27892 re-enable tests with UUID now that issue is fixed
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/PurchaseOrder.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27891 prepare for Jakarta Data Query Language
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
Labels: team:Zombie Apocalypse, CLA Signed

#27888 Add Checkpoint PB support (on via test-trigger)
  .ci-orchestrator/jvms/dev/checkpoint_linux_x86_64.properties
  .ci-orchestrator/pb.yml
Labels: CLA Signed

#27887 Update fattest.simplicity for changes in WebSphere Liberty
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE6FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEEAction.java
Labels: noproductcode, CLA Signed, team:Performance

#27880 Add checkpoint as testedfeature
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat/bnd.bnd
  dev/io.openliberty.checkpoint_fat_beanvalidation/bnd.bnd
  dev/io.openliberty.checkpoint_fat_crac/bnd.bnd
  dev/io.openliberty.checkpoint_fat_jms/bnd.bnd
  dev/io.openliberty.checkpoint_fat_mail/bnd.bnd
  dev/io.openliberty.checkpoint_fat_mpconfig/bnd.bnd
  dev/io.openliberty.checkpoint_fat_persistence/bnd.bnd
  dev/io.openliberty.checkpoint_fat_security_oidc_social/bnd.bnd
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/bnd.bnd
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/bnd.bnd
  dev/io.openliberty.checkpoint_fat_springboot/bnd.bnd
  dev/io.openliberty.checkpoint_fat_transaction/bnd.bnd
  dev/io.openliberty.checkpoint_fat_xmlws/bnd.bnd
  dev/io.openliberty.data.internal_fat/bnd.bnd
  dev/io.openliberty.data.internal_fat_jpa/bnd.bnd
  dev/io.openliberty.ejbcontainer.checkpoint_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#27883 Fix duration check
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/servlet/HttpTraceTestServlet.java
Labels: noproductcode, CLA Signed

#27841 JAX-WS and JAX-RS 2.1: Integrate JAX-WS with Concurrent features.
  dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsConcurrent-1.0.ee8.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.jaxws-concurrent.feature
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/com/ibm/ws/cxf/client/AsyncClientRunnableWrapper.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/com/ibm/ws/cxf/client/component/AsyncClientRunnableWrapperManager.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/com/ibm/ws/cxf/client/component/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/com/ibm/ws/cxf/client/package-info.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/HTTPConduit.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2/src/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
  dev/io.openliberty.cxf.concurrent/.classpath
  dev/io.openliberty.cxf.concurrent/.gitignore
  dev/io.openliberty.cxf.concurrent/.project
  dev/io.openliberty.cxf.concurrent/.settings/bndtools.core.prefs
  dev/io.openliberty.cxf.concurrent/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.cxf.concurrent/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.cxf.concurrent/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.cxf.concurrent/bnd.bnd
  dev/io.openliberty.cxf.concurrent/src/com/ibm/ws/cxf/concurrent/component/ManagedExecutorRunnableWrapper.java
Labels: CLA Signed

#27903 Revert "Update annotation, validation and restfulWS APIs to export EE 11 version"
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.1.feature
  dev/com.ibm.ws.concurrent_fat_reactive/bnd.bnd
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.data.internal.persistence/bnd.bnd
  dev/io.openliberty.data.internal/bnd.bnd
  dev/io.openliberty.jakarta.validation.v31_fat/bnd.bnd
  dev/io.openliberty.jakarta.validation.v31_fat/publish/servers/validation.v31.fat/server.xml
  dev/io.openliberty.jakarta/annotation.3.0.bnd
  dev/io.openliberty.jakarta/restfulWS.4.0.bnd
  dev/io.openliberty.jakarta/validation.3.1.bnd
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1_fat/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.cdi.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
  dev/io.openliberty.restfulWS.internal.ssl/bnd.bnd
  dev/io.openliberty.restfulWS30.appSecurity/bnd.bnd
  dev/io.openliberty.restfulWS30.jsonb20provider/bnd.bnd
Labels: CLA Signed

#27902 Fix NPE
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
Labels: in:Web Components, team:Sirius

#27634 Support read and write ByteBuffer in ServletInputStream and ServletOutputStream
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/response/WCOutputStream31.java
  dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/srt/SRTInputStream31.java
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTInputStream.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal.factories/src/io/openliberty/webcontainer/servlet/internal/osgi/response/factory/IRequestResponseFactory61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/response/IResponse61Impl.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/response/WCOutputStream61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/response/package-info.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTInputStream61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletRequest61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61ReadWriteByteBufferTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ReadWriteByteBuffer/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ReadWriteByteBuffer/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/ReadWriteByteBuffer.war/src/readwritebytebuffer/servlets/ReadWriteByteBuffer.java
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 Reviewed, jakartaEE11

#27895 Update Jakarta Persistence API 3.2.0-M2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.2.feature
  dev/io.openliberty.jakarta/persistence.3.2.bnd
Labels: in:JPA, team:Blizzard, CLA Signed

#27901 Jakarta Data spec API updates post M3
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PaginatedIterator.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/StreamableImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Streamable.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/CursoredPage.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetAwarePage.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetAwareSlice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Page.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequestCursor.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/CursoredPageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/CrudRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27893 Repeat io.openliberty.wsoc.internal_fat for Jakarta EE11
  dev/io.openliberty.wsoc.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27884 Do not reprocess config files on restore from file monitor
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigFileMonitor.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigurationMonitor.java
Labels: CLA Signed

#27918 JDQL WHERE clause only or with ORDER BY
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
Labels: team:Zombie Apocalypse, CLA Signed

#27907 Pom utils excludes for non-shipped dependencies
  dev/wlp-updatePom/src/io/openliberty/build/update/pom/PomUtils.java
Labels: CLA Signed

#27898 Add the Checkpoint testing step to all development PB triggers.
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed

#27765 Containerize the KDC for Spnego_fat
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/Krb5Helper.java
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/SPNEGOConstants.java
  dev/com.ibm.ws.security.spnego_fat/bnd.bnd
  dev/com.ibm.ws.security.spnego_fat/build.gradle
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/BasicAuthTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/ContainerKDCCommonTest.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/FATSuite.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/KerberosContainer.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/ServicePrincipalNamesTest.java
  dev/com.ibm.ws.security.spnego_fat/publish/files/resources/security/kerberos/jaas.conf
  dev/com.ibm.ws.security.spnego_fat/publish/files/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.spnego_fat/publish/servers/BasicAuthTest/configs/trimKerberosRealmFromPrincipal_customJaasLogin.xml
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed, team:Core Security

#27924 JDQL FROM clause
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/MixedRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27917 Add classloading trace to MetricsClassLoaderTest_10
  dev/com.ibm.ws.microprofile.metrics_fat/fat/src/com/ibm/ws/microprofile/metrics/tck/launcher/MetricsClassLoaderTest_10.java
  dev/com.ibm.ws.microprofile.metrics_fat/publish/servers/MetricsClassLoaderServer_1.0/bootstrap.properties
Labels: noproductcode, CLA Signed

#27916 Add request attribute jakarta.servlet.error.query_string
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61DispatcherErrorMethodAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DispatcherErrorMethodAttributeTest.war/src/errormethod/servlets/ErrorPageServlet.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DispatcherErrorMethodAttributeTest.war/src/errormethod/servlets/TestErrorMethodAttributeServlet.java
Labels: in:Web Components, team:Sirius, jakartaEE11

#27931 Liberty Containerized v24.0.0.1 pen test issue: 152195: Missing Security Related HTTP Headers (Informational)
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/BatchRequestUtil.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobDefinitions.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobExecutions.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/JobInstances.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/StepExecutions.java
  dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/utils/BatchJSONHelper.java
Labels: CLA Signed

#27932 JAX-WS: Remove unnecessary reflection invocation in SAAJUtils
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/saaj/SAAJUtils.java
Labels: CLA Signed

#27929 Add missing comma for tested.features
  dev/io.openliberty.checkpoint_fat_transaction/bnd.bnd
Labels: noproductcode, CLA Signed

#27928 Delete lease files properly
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/util/Utils.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/PeerLeaseData.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryLogManagerImpl.java
Labels: CLA Signed

#27936 Extend the timeout for CWWKO0219I: TCP Channel defaultHttpEndpoint-ssl
  dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/CustomAccessLogFieldsTest.java
Labels: noproductcode, CLA Signed

#27844 Fix 27779 - JSP Stackoverflow
  dev/com.ibm.ws.jsp.2.3/src/org/apache/jasper/runtime/JspContextWrapper.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/OLGH27779.war/resources/WEB-INF/tags/include.tag
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/OLGH27779.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/OLGH27779.war/resources/include.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/OLGH27779.war/resources/index.jsp
  dev/com.ibm.ws.jsp/src/org/apache/jasper/runtime/JspContextWrapper.java
  dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/JspContextWrapper.java
Labels: in:Web Components, ID review not needed, CLA Signed, release bug, team:Sirius

#27914 return all config files with fetchConfigurationFiles
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/SystemConfiguration.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerXMLConfigurationMBeanTest.java
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.schemaGen.mbean/configDropins/defaults/a.xml
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.schemaGen.mbean/configDropins/overrides/b.xml
Labels: CLA Signed

#27878 Upgrade mime4j to 0.8.10
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: CLA Signed, target:24004

#27920 Add wait for JMSServer to DelayFullTest.testDDRemoveAddServerFeature
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
Labels: noproductcode, CLA Signed

#27941 Add missing classpath entries and organize
  dev/io.openliberty.org.apache.myfaces.4.1_fat/.classpath
  dev/io.openliberty.org.apache.myfaces.4.1_fat/bnd.bnd
Labels: noproductcode, CLA Signed

#27921 Dont try realpath or readlink on OS390
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#27625 Remove potential null timestamps from TCKs and add report generation time
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TestSuiteResult.java
Labels: noproductcode, CLA Signed

#27948 Give applications 60s to start before launching checkpoint
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/checkpointfat.jpa/server.xml
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/server.xml
Labels: noproductcode

#27954 Adding additional debug and trace statements for configAdmin
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminDropinsCheck/server.xml
Labels: CLA Signed

#27944 Swagger-UI dependency update March 2024
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/index.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-0e9d7c115c8dd50ee2cc.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-0e9d7c115c8dd50ee2cc.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-35b3219247920e7ab44f.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-35b3219247920e7ab44f.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-255724880023aedf60ee.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-255724880023aedf60ee.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-7b5741fd872120b3691d.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-7b5741fd872120b3691d.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/mpOpenApi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/openapi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/package-lock.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/src/style/original/_layout.scss
Labels: CLA Signed, target:24004

#27955 Fix copyright date and display name
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/OLGH27779.war/resources/WEB-INF/web.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27855 Read in monitor-1.0 configuration to disable or enable the registered…
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/MonitorAppStateListener.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/MonitorAppStateListener.java
  dev/io.openliberty.restfulWS.mpMetrics.filter/src/io/openliberty/restfulws/mpmetrics/RestfulWsMonitorFilter.java
Labels: CLA Signed

#27333 Fix large string persistence for config
  dev/com.ibm.ws.config.schemagen/test/com/ibm/ws/config/schemagen/internal/SchemaGenTest.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStorageHelper.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/admin/internal/ConfigurationStorageHelperTest.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/XMLConfigParserTest.java
Labels: in:Kernel/Bootstrap, CLA Signed, release bug

#27946 updates to lifecycle method return types
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/CursoredPage.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/impl/CursoredPageRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/CrudRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27942 Increased invalidation alarm delay during startup for RequestTiming FAT
  dev/com.ibm.ws.request.timing.hung_fat/publish/servers/HungRequestTimingServer/serverSessionConfig.xml
Labels: noproductcode, CLA Signed

#27757 Filter out bad values from env var
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#27965 fix invalid proxy format error message
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#27973 Fix Eclipse Errors in FAT
  dev/io.openliberty.io.opentelemetry.2.0/.settings/bndtools.core.prefs
  dev/io.openliberty.io.opentelemetry.2.0/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.io.opentelemetry.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.opentelemetry.2.0/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxws.executor_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/.project
Labels: noproductcode, CLA Signed

#27975 Fix more eclipse errors in FAT
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/myfaces41/fat/flow/beans/Bean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/myfaces41/fat/flow/beans/FlowBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/Flow_Spec1342_Spec1739.war/src/io/openliberty/org/apache/myfaces41/fat/flow/beans/Tracker.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/RenderId_Spec1760.war/src/io/openliberty/org/apache/myfaces41/fat/namespace/view/NamespacedView.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/SetResponseContentLengthLong_Spec1829.war/src/io/openliberty/org/apache/myfaces41/fat/contentlengthlong/beans/ContentLengthLongBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/src/io/openliberty/org/apache/myfaces41/fat/view/bean/Tracker.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/ViewScopeEvents_Spec1739.war/src/io/openliberty/org/apache/myfaces41/fat/view/bean/ViewBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/src/io/openliberty/org/apache/myfaces41/fat/uuidconverter/beans/FailBean.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/uuidConverter_Spec1819.war/src/io/openliberty/org/apache/myfaces41/fat/uuidconverter/beans/SuccessBean.java
Labels: noproductcode, CLA Signed

#27956 Wait for tests to completely finish
  dev/com.ibm.ws.wsat_fat.multi/fat/src/tests/MultiServerTest.java
Labels: noproductcode, CLA Signed

#27969 3 methods removed from BasicRepository
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27976 insert parenthesis around WHERE clause for cursor pagination
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/MixedRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27981 removal of Query.count from spec
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/MixedRepository.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/Query.java
Labels: team:Zombie Apocalypse, CLA Signed

#27977 Ignore slow starting adapter in FAT
  dev/com.ibm.ws.ejbcontainer.mdb.ra_fat/fat/src/com/ibm/ws/ejbcontainer/mdb/ra/fat/tests/MsgEndpointTest.java
  dev/io.openliberty.ejbcontainer.mdb.checkpoint_fat/fat/src/io/openliberty/ejbcontainer/mdb/ra/checkpoint/fat/tests/MsgEndpointTest.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27978 Update CDI API to 4.1.0.RC1, fix weld version refs
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.1/io.openliberty.cdi-4.1.feature
  dev/io.openliberty.cdi.4.1.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta/cdi.4.1.bnd
Labels: CLA Signed

#27980 Update common annotations API to 3.0.0-M1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-3.0.feature
  dev/io.openliberty.jakarta/annotation.3.0.bnd
Labels: CLA Signed

#27950 Check var dir files on restore and monitor config files after restore
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigFileMonitor.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigRefresher.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigurationMonitor.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITest.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITestConfig.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat/publish/files/configVariables/d_value_props.properties
  dev/io.openliberty.checkpoint_fat/publish/files/configVariablesDefaults/c_value
  dev/io.openliberty.checkpoint_fat/publish/files/configVariablesDefaults/d_value_props.properties
  dev/io.openliberty.checkpoint_fat/publish/files/dropinConfigChange/override.xml
  dev/io.openliberty.checkpoint_fat/publish/files/envConfigChange/server.env
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/variables/c_value
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/variables/d_value_props.properties
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestCheckpointHook.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestStaticHookRegister.java
Labels: CLA Signed

#27979 beta the concurrent-3.1 feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi4.1-concurrent3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.interceptor-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakartaeePlatform-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.persistentExecutor.internal.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/concurrent-3.1/io.openliberty.concurrent-3.1.feature
Labels: team:Zombie Apocalypse, CLA Signed

#27521 Add canonicalization to path parameter for ServletContext methods
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/filter/WebAppFilterManager.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/RequestUtils.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/webapp/WebApp61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletRequest61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61PathCanonicalizationTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_PathCanonicalizationTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_PathCanonicalizationTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/PathCanonicalizationTest.war/resources/index.html
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/PathCanonicalizationTest.war/resources/subFolder/index1.html
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/PathCanonicalizationTest.war/resources/subFolder/subFolder2/index2.html
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/PathCanonicalizationTest.war/src/pathcanonicalization/TestPathCanonicalizationServlet.java
Labels: in:Web Components, team:Sirius, jakartaEE11

#27959 JAX-WS: Add beta metatype for webServiceClient
  dev/com.ibm.ws.jaxws.2.3.common/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jaxws.2.3.common/resources/OSGI-INF/metatype/metatype.xml
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#27982 Update Java 22 specific FAT with GA build
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 22

#27988 Add appSecurity-6.0 to list of features to enable security
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.java
  dev/io.openliberty.grpc.1.0.internal/src/io/openliberty/grpc/internal/servlet/GrpcServerComponent.java
Labels: CLA Signed, team:Performance

#27937 GVT test cases
  dev/com.ibm.ws.gvt.rest_fat/bnd.bnd
  dev/com.ibm.ws.gvt.rest_fat/build.gradle
  dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/BaseTestCase.java
  dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/FATSuite.java
  dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtTest.java
  dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
  dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/bootstrap.properties
  dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/server.xml
  dev/com.ibm.ws.gvt.rest_fat/publish/shared/resources/configs/basicRegistry.xml
  dev/com.ibm.ws.gvt.rest_fat/publish/shared/resources/configs/httpEndpoint1.xml
  dev/com.ibm.ws.gvt.rest_fat/publish/shared/resources/configs/ssl.xml
  dev/com.ibm.ws.gvt.rest_fat/publish/shared/resources/security/keystore.p12
  dev/com.ibm.ws.gvt.rest_fat/publish/shared/resources/security/truststore.p12
Labels: noproductcode, CLA Signed

#27996 Use the staged API artifacts for annotations-3.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-3.0.feature
  dev/io.openliberty.jakarta/annotation.3.0.bnd
Labels: CLA Signed

#27999 more complete simulation of JDQL
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
Labels: team:Zombie Apocalypse, CLA Signed

#27995 Disable running the session cache checkpoint tests on regular build temporarily
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/bnd.bnd
Labels: noproductcode, CLA Signed

#28007 Update FeatureLevels test for mpTelemetry-2.0
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
Labels: noproductcode, CLA Signed

#27984 Update Jakarta Concurrency for RC1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.1.feature
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/FATSuite.java
  dev/io.openliberty.jakarta/concurrency.3.1.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#28011 ParserBase buffering adjustments
  dev/com.ibm.ws.repository.parsers/src/com/ibm/ws/repository/parsers/ParserBase.java
Labels: CLA Signed

#28016 Get things building in eclipse
  dev/com.ibm.ws.gvt.rest_fat/.classpath
  dev/com.ibm.ws.gvt.rest_fat/.project
  dev/com.ibm.ws.gvt.rest_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.gvt.rest_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.gvt.rest_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.gvt.rest_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletRequest61.java
Labels: CLA Signed, team:Performance

#28008 Allow InternalLogException in batch lease deletion test
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
Labels: noproductcode, CLA Signed

#28010 Comment out testDDRemoveAddServerFeature tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
Labels: noproductcode, CLA Signed

#27989 Refactoring health tests
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminDropinsCheck/server.xml
Labels: noproductcode, CLA Signed

#27986 Increase the application start timeout value for Checkpoint
  dev/com.ibm.ws.app.manager/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/ApplicationStateCoordinator.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SlowAppStartTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/slowStartAppServer/server.xml
  dev/io.openliberty.checkpoint_fat/test-applications/startupcode/src/startupcode1/ServletA.java
  dev/io.openliberty.checkpoint_fat/test-applications/startupcode/src/startupcode2/ServletB.java
Labels: CLA Needed

#27411 Beta expressionLanguage-6.0, pages-4.0 and servlet-6.1 for Jakarta EE11
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.annotation-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.expressionLanguage-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.pages-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.internal-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/expressionLanguage-6.0/io.openliberty.expressionLanguage-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/pages-4.0/io.openliberty.pages-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/servlet-6.1/com.ibm.websphere.appserver.servlet-6.1.feature
  dev/com.ibm.ws.javaee.ddmodel_fat/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27991 Updating the new persistence.xml schema and adding a new FAT
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPACompPUnitInfo.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPUnitInfo.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPxmlInfo.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JaxbPUnit.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JaxbPUnit32.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JaxbPersistence32.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JaxbUnmarshaller.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/ObjectFactory.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/Persistence.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/PersistenceUnitCachingType.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/PersistenceUnitTransactionType.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/PersistenceUnitValidationModeType.java
  dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/pxml32/package-info.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/puparser/Constants.java
  dev/com.ibm.ws.jpa.container.ormdiagnostics/src/com/ibm/ws/jpa/diagnostics/puparser/JPA_Schema.java
  dev/com.ibm.ws.jpa.container/src/com/ibm/ws/jpa/schemas/jakartaee/persistence_3_2.xsd
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.classpath
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.project
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/build.gradle
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/fat/src/com/ibm/ws/jpa/jpa32/JPABootstrapTest.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/publish/servers/JPABootstrapFATServer/bootstrap.properties
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/publish/servers/JPABootstrapFATServer/server.xml
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/helpers/DatabaseManagement/resources/databasemanagement.war/WEB-INF/web.xml
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/helpers/DatabaseManagement/src/jpahelper/databasemanagement/DatabaseManagementServlet.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jpabootstrap/resources/jpa-3.2/web/WEB-INF/classes/META-INF/persistence.xml
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jpabootstrap/src/jpabootstrap/entity/SimpleTestEntity.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jpabootstrap/src/jpabootstrap/web/TestJPABootstrapServlet.java
  dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/PUInfoImpl.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: in:JPA, team:Blizzard, CLA Signed

#28022 Don't rollback on closed connections
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnection.java
Labels: noproductcode, CLA Signed

#28006 Beta CDI 4.1
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi4.1-servlet6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.org.eclipse.persistence-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.persistence.base-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectClient1.0.internal.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.openidConnectServer1.0.internal.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.1/io.openliberty.cdi-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/persistenceContainer-3.2/io.openliberty.persistenceContainer-3.2.feature
Labels: CLA Signed

#28028 Update missed bundle range to use minor version
  dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/com.ibm.websphere.appserver.openidConnectServer-1.0.feature
Labels: CLA Signed, team:Performance

#28017 Update Jakarta Concurrency to RC2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.concurrency-3.1.feature
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta/concurrency.3.1.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#28002 Prevent multiple threads trying to close the storage output
  dev/org.eclipse.osgi/.classpath
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/src/org/eclipse/osgi/storage/Storage.java
Labels: CLA Signed

#28025 Fix EJB timer FAT verification
  dev/com.ibm.ws.ejbcontainer.timer.np_fat/test-applications/NpTimersWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/web/AbstractAnnotationTxServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#28014 Fix CVE-2024-27270
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
Labels: in:Web Components, CLA Signed, team:Sirius

#27590 Update FeatureList and EsaResourceImpl for Java 22
  dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/resources/internal/EsaResourceImpl.java
Labels: team:Zombie Apocalypse, CLA Signed, Java 22

#28032 Remove noship-1.0 from tested.features for Expression Language repeated FATs
  dev/com.ibm.ws.el.3.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/bnd.bnd
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27972 WLP_INSTALL_DIR set incorrectly when wlp/bin is a symbolic link
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#27997 Add feature start testing steps for Open Liberty and WAS Liberty
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#27994 Add missing decode to social request handling
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/web/WebRequestUtils.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/RedirectionProcessor.java
Labels: CLA Signed, team:Security SSO, In Progress

#28031 MYFACES-4657
  dev/io.openliberty.org.apache.myfaces.4.1/.classpath
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/webapp/MyFacesContainerInitializer.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#26772 Clean up endpointSessionMap and httpSessionMap during http session expiration
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/EndpointManager.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/WebSocketServletContainerInitializer.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/WsocHttpSessionIdListener.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#28030 test waits insufficient amount of time
  dev/com.ibm.ws.jca_fat/test-resourceadapters/fvt-resourceadapter/src/fat/jca/resourceadapter/FVTMessageProducer.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed
