Repository OpenLiberty/open-liberty, pull requests merged in 2024-11, with the labels that each got.

#29795 Update Swagger-ui dependencies to latest
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/index.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-658fe5fd5282367f2bb1.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-658fe5fd5282367f2bb1.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-6a8ecee8e7c998b79c82.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-6a8ecee8e7c998b79c82.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-5b339aeece5d8ff98c86.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-5b339aeece5d8ff98c86.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-bdf9b527ec6da92b71c5.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-bdf9b527ec6da92b71c5.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/mpOpenApi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/openapi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/package-lock.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
Labels: CLA Signed, target:240012

#30022 SmallRye OpenAPI 4.0.1 update - performance fix
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.openapi4.core/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi4.jaxrs/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi4.model/bnd.bnd
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/test/io/openliberty/microprofile/openapi40/internal/services/impl/test/ConfigFieldProvider40ImplTest.java
Labels: CLA Signed

#29755 Ensure that the feature version check applies even when the server.xml is replaced at runtime
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/JAXRSClientSSLTestNoLibertySSLFeature.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/jaxrs20.client.JAXRSClientSSLTestNoLibertySSLCfg/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30023 Remove old -Xdump settings ClassCastExceptions
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29986 Enable Batch as Beta
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-1.0/com.ibm.websphere.appserver.batch-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-2.0/io.openliberty.batch-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/batch-2.1/io.openliberty.batch-2.1.feature
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/batchFAT/bootstrap.properties
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/batchFAT/jvm.options
Labels: CLA Signed

#29917 Use caching for tags/labels/attributes for HTTP Metrics
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStats.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpStatAttributes.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/MPMetricsHTTPMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
Labels: CLA Signed

#30021 featureUtility proxy environment variable bug
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#29679 remove beta for featureUtility no proxy
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#30035 Update MP OpenAPI API to 4.0.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-4.0.feature
  dev/io.openliberty.org.eclipse.microprofile/openapi.4.0.bnd
Labels: CLA Signed

#30042 mpOpenAPI: server.xml message for missing include
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ModuleSelectionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/MessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/StartupWarningMessagesTest.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: CLA Signed

#29999 remove ConfigurationTokenMinValidityTests_tokenMinValidity_5s
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTokenMinValidityTests.java
Labels: noproductcode, CLA Signed

#30041 WS-Security SAML FAT:: Update repeat action to match SAML Web SSO repeat actions
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken1/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken2/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken3/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken5/FATSuite.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.6/fat/src/com/ibm/ws/wssecurity/fat/cxf/samltoken6/FATSuite.java
Labels: noproductcode, CLA Signed

#29885 Fixes #29802 - The Gitter link in the default page returns 404
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/twitter_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
Labels: CLA Needed

#30039 Fix 29802
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/twitter_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
Labels: CLA Signed

#29231 Externalising the SSLSessionCacheSize property
  dev/com.ibm.ws.channel.ssl/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.channel.ssl/resources/OSGI-INF/metatype/metatype.xml
Labels: in:Transport, in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 ReviewNotRequired

#30025 Adjusting AuthUtil to process trailing whitespace
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/AuthUtils.java
Labels: CLA Signed

#30055 MP OpenAPI: reduce FAT repeats on slow tests
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigBothTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigTest.java
Labels: noproductcode, CLA Signed

#30043 Ensure that the CDI vis tests repeat against the correct features
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/cdi12EJBServer/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30051 NullPointerException in finally of testUsingUCP
  dev/com.ibm.ws.jdbc_fat_oracle/test-applications/oracleucpfat/src/ucp/web/OracleUCPTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30060 Remove mention of z/OS related to attach
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#29997 Remove many false positives from .secrets.baseline
  .secrets.baseline
Labels: noproductcode, CLA Signed

#30065 JAX-WS: ignoreUnexpectedElements settings is moved to default servrer.xml
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/GzipInterceptorsTest.java
  dev/io.openliberty.jaxws.config_fat/publish/files/GzipInterceptorsTestServer/server.xml
  dev/io.openliberty.jaxws.config_fat/publish/servers/GzipInterceptorsTestServer/server.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#30064 Fix Logstash Collector Audit test failure
  dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/LogstashCollectorTest.java
Labels: noproductcode, CLA Signed

#30057 Pull in MyFaces 4.1.0-RC3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.faces.4.1/.classpath
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/build.gradle
  dev/io.openliberty.jakarta.faces.4.1/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.1/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.1/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.1/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.jakarta.faces.4.1/src/org/apache/myfaces/core/api/shared/lang/ClassUtils.java
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/application/FacesServletMappingUtils.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/cdi/view/ViewScopeEventListenerBridge.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/flow/cdi/FlowScopeContextualStorageHolder.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/util/lang/ClassUtils.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/view/facelets/compiler/CompilationManager.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#30061 Move invalid log tests into OL
  dev/com.ibm.ws.transaction.core_fat.base/fat/src/com/ibm/ws/transaction/test/FATSuite.java
  dev/com.ibm.ws.transaction.core_fat.base/fat/src/com/ibm/ws/transaction/test/tests/BadLogTest.java
  dev/com.ibm.ws.transaction.core_fat.base/publish/servers/com.ibm.ws.transaction_badlog/bootstrap.properties
  dev/com.ibm.ws.transaction.core_fat.base/publish/servers/com.ibm.ws.transaction_badlog/server.xml
  dev/com.ibm.ws.transaction.core_fat.base/test-applications/transaction/src/servlets/BadLogServlet.java
Labels: noproductcode, CLA Signed

#30072 Reset log marks to handle concurrent recovery
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/tests/LPSTest.java
Labels: noproductcode

#30052 Improvements to enumeration constructors
  dev/io.openliberty.data/src/io/openliberty/data/repository/Is.java
Labels: team:Zombie Apocalypse, CLA Signed

#30081 add RESTEasy trace to crossFeatureOpenTracingZipkinServer
  dev/com.ibm.ws.microprofile.rest.client12_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.rest.client_fat/publish/servers/mpRestClient20.sse/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/publish/servers/crossFeatureOpenTracingZipkinServer/bootstrap.properties
Labels: noproductcode

#30071 test on all open telemetry versions
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryUserFeatureAppScopedTest.java
Labels: noproductcode, CLA Signed

#30026 Add CheckpointRule to repeat existing tests for InstantOn
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityCheckpointTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityTestRapid.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr.checkpoint/bootstrap.properties
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr.checkpoint/jvm.options
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr.checkpoint/server.xml
  dev/fattest.simplicity/src/componenttest/rules/repeater/CheckpointRule.java
Labels: noproductcode, CLA Signed

#30082 Add debug from OpenTelemetry Collector and increase metric export interval for `io.openliberty.http.monitor_fat`
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSFApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerNoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerRestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
  dev/io.openliberty.http.monitor_fat/publish/files/config.yaml
Labels: noproductcode

#30068 Add keystore to cloudant FAT
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/fat/src/com/ibm/ws/rest/handler/validator/cloudant/fat/ValidateCloudantTest.java
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/publish/servers/com.ibm.ws.rest.handler.validator.cloudant.fat/resources/security/key.jks
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/publish/servers/com.ibm.ws.rest.handler.validator.cloudant.fat/server.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, in:JDBC/JCA

#30062 test for invalid entity
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Invention.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Inventions.java
Labels: team:Zombie Apocalypse, CLA Signed

#30037 Prepare IntervalTask for checkpoint
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITestConfig.java
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestStaticHookRegister.java
Labels: CLA Signed

#30074 Reduced logs in testMessageLogs in mpTelemetry Logs container FAT
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/msgSourceServer.xml
Labels: noproductcode, CLA Signed

#30044 Refactor different delay tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#30085 Change check times in delivery delay set tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode

#28993 Config attribute to allow undeclared checked exceptions to be thrown …
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction.cdi/src/com/ibm/tx/jta/cdi/interceptors/TransactionalInterceptor.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
Labels: ID reviewed, L2 ReviewNotRequired

#30047 Filter transitive test dependency
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#30067 Update container images (database)
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ContainersTest.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/FATSuite.java
  dev/build.example.testcontainers_fat/fat/src/com/ibm/ws/testcontainers/example/ProgrammaticImageTest.java
  dev/build.example.testcontainers_fat/publish/files/postgres/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/Dockerfile
  dev/com.ibm.ws.jdbc_fat_db2/publish/files/db2/release.sh
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/DB2KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/db2/Dockerfile
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/postgresql/Dockerfile
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/ThreadLocalConnectionTest.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/files/postgresql-ssl/Dockerfile
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerSSLTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/fat/src/com/ibm/ws/jdbc/fat/sqlserver/SQLServerTest.java
  dev/com.ibm.ws.jdbc_fat_sqlserver/publish/files/sqlserver-ssl/Dockerfile
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0.ee10/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/container-license-acceptance.txt
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/container-license-acceptance.txt
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/resources/init-sqlserver.sql
  dev/fattest.simplicity/src/componenttest/annotation/SkipIfSysProp.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerFactoryTest.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerTypeTest.java
  dev/io.openliberty.checkpoint_fat_persistence/bnd.bnd
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/JPATest.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/JakartaDataTest.java
  dev/io.openliberty.checkpoint_fat_springboot_data/bnd.bnd
  dev/io.openliberty.checkpoint_fat_springboot_data/fat/src/io/openliberty/checkpoint/fat/springboot/data/FATSuite.java
  dev/io.openliberty.org.testcontainers/cache/images
Labels: team:Zombie Apocalypse, tech debt, noproductcode, CLA Signed

#30059 Update EE11 schema for web-jsptaglibrary
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-jsptaglibrary_4_0.xsd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#30096 Ensure that com.ibm.ws.concurrent.mp_fat_jakarta repeats with the correct features
  dev/com.ibm.ws.concurrent.mp_fat_jakarta/publish/servers/com.ibm.ws.concurrent.mp.fat.1.3.ee10/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30097 Remove JAXRS server from exempt list
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30098 Ensure that the MP Config 1.3 TCK repeats with the correct features
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/config13/tck/Config13TCKLauncher.java
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/config13/tck/FATSuite.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30099 Ensure that the MP Graph QL 1.0 FAT repeats with the correct features
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.basicMutation/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.basicQuery/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.defaultvalue/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.deprecation/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.graphQLInterface/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.iface/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.ignore/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.inputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.jarInWar/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.metrics/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.outputFields/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.rolesAuth/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.types/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.ui/server.xml
  dev/com.ibm.ws.microprofile.graphql.1.0_fat/publish/servers/mpGraphQL10.voidQuery/server.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30104 Cleanup from recent merges
  dev/com.ibm.ws.classloading_classpath_fat/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi4.model/.classpath
  dev/io.openliberty.io.smallrye.openapi4.model/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/bnd.bnd
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/bnd.bnd
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/bnd.bnd
Labels: CLA Signed, team:Performance

#30107 refactoring to QueryInfo
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Util.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
Labels: team:Zombie Apocalypse, CLA Signed

#30113 Remove test auto features from build.image/wlp/lib/features directory that can affect jakarta ee fat tests
  dev/com.ibm.ws.cdi.visibility_fat/publish/features/visTest-1.2.mf
  dev/com.ibm.ws.cdi.visibility_fat/publish/features/visTest-3.0.mf
  dev/com.ibm.ws.logging_fat/publish/features/logServiceTest-1.0.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/IBMShortNameManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/SubsystemNameManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/SubsystemSymbolicNameManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/basicAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/basicProtectedAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/basicPublicAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/emptyIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/gifIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/invalidRelativeIconURIHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/jpegIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/mixedSizedIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/mixedSizedWithUnsizedIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/multiUIEndpointManifestHeader.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/multiUnsizedIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/noIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/noSizedIconHeaderManifest.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/originalUpdateAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/singleUIEndpointAndNonEndpointWABManifestHeader.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/singleUIEndpointManifestHeader.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/updatedUpdateAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/urlInMultipleWabs.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/urlInSingleWab.mf
  dev/com.ibm.ws.ui_rest_fat/publish/features/usr.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/prodextn1.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/prodextn1originalUpdateAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/prodextn1updatedUpdateAutoFeatureTool.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/prodextn2.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/prodextn3.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/protectedprodextn.mf
  dev/com.ibm.ws.ui_rest_fat/publish/productfeatures/publicprodextn.mf
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureUtilities.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10Features.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/JakartaEE10Test.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11Features.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/JakartaEE11Test.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9Features.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/JakartaEE9Test.java
Labels: noproductcode, team:Performance

#30108 JAX-WS Sec: Timeout increased for a long search
  dev/com.ibm.ws.wssecurity_fat.wsscxf.2/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigSymEE7LiteTests.java
Labels: noproductcode, CLA Signed, team:Bobcats, in:Web Services Security

#30031 Update EclipseLink ASM to 9.7.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink/bnd.bnd
  dev/io.openliberty.persistence.3.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.1.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed, Java 24

#30076 Fixes : Db2: Eclipselink creates table with Db2 data type DOUBLE instead of REAL for a Java float
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/DB2Platform.java
Labels: CLA Signed

#30103 Ensure com.ibm.ws.request.timing.monitor_fat is repeated with correct features.
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverHungRequestMetrics.xml
  dev/com.ibm.ws.request.timing.monitor_fat/publish/files/serverSlowRequestMetrics.xml
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30115 debug: Add arquillian trace for Concurrency TCK
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Debug

#30106 `io.openliberty.microprofile.telemetry.internal.monitor_fat` improvements
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/BaseTestClass.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/LibertyMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/SessionMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/files/config.yaml
Labels: noproductcode, CLA Signed

#30094 Use a retry method when querying the values from the Otel collector o…
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSFApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerNoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerRestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
Labels: noproductcode, CLA Signed

#30017 add jakartaee8 platform for versionless
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.eeCompatible-8.0.feature
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureRepository.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessMessagesTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessServletToMicroProfileTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/server.xml
Labels: CLA Signed

#30105 Enhance CheckpointRule to be more general for other FATs
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityTest.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityTestRapid.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/CheckpointSupportFilter.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/CheckpointRule.java
Labels: noproductcode, CLA Signed

#30120 Avoid FFDC for SSLException to retain Legacy behavior
  dev/io.openliberty.netty.internal.tls.impl/src/io/openliberty/netty/internal/tls/impl/NettyTlsProviderImpl.java
Labels: team:Sirius

#30092 add interim fix message
  dev/wlp.lib.extract/resources/wlp/lib/extract/SelfExtractMessages.nlsprops
Labels: ID review not needed, CLA Signed, L2 Reviewed

#30122 Test enabled for EL issue 2282 (DB2)
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, CLA Signed

#30133 more places to avoid logging customer data
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
Labels: team:Zombie Apocalypse, CLA Signed

#28419 Oauth should not intercept an unprotected Request
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
Labels: CLA Signed

#30129 Add keystore to Java EE v8 FAT
  dev/com.ibm.ws.javaee.8.0_fat/publish/servers/javaee8.fat/resources/security/key.jks
  dev/com.ibm.ws.javaee.8.0_fat/publish/servers/javaee8.fat/server.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#30132 Add keystore to Jakarta EE v11 FAT
  dev/io.openliberty.jakartaee11.internal_fat/publish/servers/jakartaee11.fat/resources/security/key.jks
  dev/io.openliberty.jakartaee11.internal_fat/publish/servers/jakartaee11.fat/server.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#30032 Remove beta guard from telemetry SPI
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.0/io.openliberty.mpTelemetry-2.0.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryUserFeatureAppScopedTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryUserFeatureTest.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/spi/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.spi/bnd.bnd
Labels: CLA Signed

#30128 Ensure io.openliberty.microprofile.metrics.internal.5.x.monitor_fat is repeated with correct features
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/publish/files/server_monitorOnly.xml
Labels: noproductcode, CLA Signed

#30138 Simplify logic to not use lambdas and method handles
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfo.java
Labels: CLA Signed, team:Performance

#30136 style: spell invoke correctly
  dev/com.ibm.ws.ejbcontainer.core/src/com/ibm/ws/metadata/ejb/EJBMDOrchestrator.java
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/document/XMLEncodingDetector.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_CookieVerificationTests.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/CommonTests/SameSiteTests.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_BasicConfigTests_oidc_usingSocialConfig.java
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_BasicTests_oidc_usingSocialDiscoveryConfig.java
  dev/com.ibm.ws.security.social_fat.delegated/fat/src/com/ibm/ws/security/social/fat/delegated/OidcDelegatedSocialLoginWithLibertyOPTests.java
  dev/com.ibm.ws.security.social_fat.delegated/fat/src/com/ibm/ws/security/social/fat/delegated/OidcDelegatedSocialLoginWithProvidersTests.java
  dev/com.ibm.ws.security.social_fat.delegated/fat/src/com/ibm/ws/security/social/fat/delegated/OidcDelegatedSocialLoginWithSelectionPageTests.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/CustomSelectionPageTests.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_LocalAuthentication.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_usingSocialConfig_withDisplayNames.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_usingSocialConfig_withFilters.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/MultiProvider_usingSocialConfig_withQueryParams.java
  dev/com.ibm.ws.security.social_fat.multiProvider/fat/src/com/ibm/ws/security/social/fat/multiProvider/commonTests/Social_MultiProvider_BasicTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicConfigTests_NoServerSSL.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicDiscoveryConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_BasicTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_EncryptionTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_ErrorDiscoveryConfigTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_SignatureAlgTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/utils/SocialCommonTest.java
  dev/io.openliberty.checkpoint_fat_security_oidc_social/fat/src/io/openliberty/checkpoint/fat/security/social/LibertyOP_BasicTests_oauth_usingSocialConfig.java
Labels: CLA Signed

#30086 Simplify HADB tests
  dev/com.ibm.ws.transaction.hadb_fat.db2.1/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.db2.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.db2.lease/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.db2.retriablecodes/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest1.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestRetriableCodes.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnectionPoolDataSource.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.lease/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.derby.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.oracle.1/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.oracle.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.oracle.lease/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.1/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.2/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.lease/build.gradle
  dev/com.ibm.ws.transaction.hadb_fat.sqlserver.retriablecodes/build.gradle
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/HADBTestConstants.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/HADBTestControl.java
Labels: noproductcode, CLA Signed

#30126 Increase logging level in JMSAsyncSendTests
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/Util.java
Labels: noproductcode, CLA Signed

#29961 Switch MP7 to GA ... including MP Open API
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee10/features.xml
  dev/build.image/profiles/jakartaee11/features.xml
  dev/build.image/profiles/microProfile7/features.xml
  dev/build.image/profiles/webProfile10/features.xml
  dev/build.image/profiles/webProfile11/features.xml
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance4.1-mpTelemetry2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpFaultTolerance-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpOpenAPI-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpRestClient-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.faulttolerance-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-7.0/io.openliberty.microProfile-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-4.1/io.openliberty.mpFaultTolerance-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-4.0/io.openliberty.mpOpenAPI-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-4.0/io.openliberty.mpRestClient-4.0.feature
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/OpenAPIConfigTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal.servlet/src/io/openliberty/microprofile/openapi20/internal/servlet/ApplicationServlet.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ModuleSelectionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/OpenAPIInfoConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/OpenAPIVersionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigBothTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeTestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeTestServer/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeWithServerXMLTestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPITestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIWarningMessageTestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/VersionTestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.4.0.internal_fat/publish/servers/OpenAPIValidationServer/jvm.options
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.openapi.internal.common/src/io/openliberty/microprofile/openapi/internal/common/OpenAPIAppConfigProviderImpl.java
Labels: CLA Signed

#30127 fix: post semaphore on recovery failure
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.jca_fat_derbyra/publish/servers/com.ibm.ws.jca.fat.derbyra.checkpoint/bootstrap.properties
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
Labels: CLA Signed

#30075 JAX-WS: Increase timeouts in config fat buckets.
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableDefaultValidationTest.java
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationTest.java
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/GzipInterceptorsTest.java
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/IgnoreUnexpectedElementConfigTest.java
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/WebServiceBndServiceRefPropertiesConfigTest.java
  dev/io.openliberty.jaxws.config_fat/test-applications/testWebServiceClient/resources/META-INF/resources/permissions.xml
  dev/io.openliberty.jaxws.config_fat/test-applications/testWebServiceClient/resources/META-INF/resources/wsdl/SayHelloService.wsdl
  dev/io.openliberty.jaxws.config_fat/test-applications/testWebServiceClient/resources/META-INF/resources/wsdl/sayHelloServiceTypes.xsd
  dev/io.openliberty.jaxws.config_fat/test-applications/testWebServiceClient/resources/META-INF/resources/wsdl/sayHelloServiceWithHandler.wsdl
Labels: noproductcode, CLA Signed

#29914 Remove beta same site incompat
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_incompatible/jvm.options
Labels: in:Transport, CLA Signed, team:Sirius

#30144 Issue #30143 : Fix test port in server endpoint controlmbean
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.service/server.xml
Labels: noproductcode, CLA Signed

#30125 Fix cxf logging
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2/src/org/apache/cxf/ext/logging/osgi/Activator.java
Labels: CLA Signed

#30130 correct post test cleanup
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/current/CDICurrentTestServlet.java
Labels: noproductcode, CLA Signed

#30137 Identify database product on connection retry
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/DBUtils.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/server.xml
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/BaseTestClass.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
Labels: CLA Signed

#30151 Post archive to save logs on checkpoint fail tests
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyRACheckpointLimitationsTest.java
Labels: noproductcode, CLA Signed

#30116 Fix premature startup mode exit - issue 29944
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed

#30176 Revert "Increase logging level in JMSAsyncSendTests"
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/common/src/com/ibm/ws/messaging/open_clientcontainer/fat/Util.java
Labels: noproductcode

#30149 use phasers directly
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30153 Update server dump to not wait indefinitely to complete
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed, team:Performance

#30145 empty list of entities
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Util.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#30177 Ignore CWWKD020 in Jakarta Data TCK
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, jakartaEE11

#30195 29582 run fewer repeats on io.openliberty.microprofile.telemetry.2.0.logging.internal_fat
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryApplicationConfigTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetrySourcesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceTest.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
Labels: noproductcode, CLA Signed

#30192 improve corbaname escaping
  dev/com.ibm.ws.jndi.iiop/src/com/ibm/ws/jndi/iiop/CorbanameUrlContextFactory.java
  dev/com.ibm.ws.jndi.iiop/src/com/ibm/ws/jndi/iiop/CosNameUtil.java
  dev/com.ibm.ws.jndi.iiop/src/com/ibm/ws/jndi/iiop/OrbContext.java
  dev/com.ibm.ws.jndi.iiop/test/com/ibm/ws/jndi/iiop/CorbanameEscapeTestSuite.java
  dev/com.ibm.ws.jndi.iiop/test/com/ibm/ws/jndi/iiop/TestFacade.java
Labels: CLA Signed

#30160 encapsulate recovery manager 1/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30175 Fix ClassLoading Failures OIDC Spnego Bucket
  dev/com.ibm.ws.security.oidc.server_fat.spnego/build.gradle
Labels: noproductcode, CLA Signed

#30189 Allow JSP test to skip feature check
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#30159 escape characters and comparison of char property ignoring case
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Demographics.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Employees.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/PurchaseOrder.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30201 Fix tests for changes in PR #30127
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyRACheckpointLimitationsTest.java
Labels: noproductcode

#30196 Pause testing infinispan with Java 23 and plus
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheConfigUpdateTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheOneServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheTwoServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan/fat/src/io/openliberty/checkpoint/session/cache/infinispan/CheckpointSessionCacheTwoServerTimeoutTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/fat/src/io/openliberty/checkpoint/session/cache/infinispan/container/CheckpointSessionCacheOneServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/fat/src/io/openliberty/checkpoint/session/cache/infinispan/container/CheckpointSessionCacheTwoServerTest.java
  dev/io.openliberty.checkpoint_fat_session_cache_infinispan_container/fat/src/io/openliberty/checkpoint/session/cache/infinispan/container/CheckpointSessionCacheTwoServerTimeoutTest.java
Labels: noproductcode, CLA Signed

#30185 Resetting Hibernate Validator compatibility range with EL
  dev/io.openliberty.org.hibernate.validator.7.0/bnd.overrides
Labels: noproductcode, CLA Signed

#30202 Test taskAborted on cancel from queue
  dev/com.ibm.ws.concurrent_fat_policy/test-applications/concurrentpolicyfat/src/web/ConcurrentPolicyFATServlet.java
Labels: noproductcode

#30182 Remove redundant test method and check this gets labeled noproductcode
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/TxTestUtils.java
Labels: noproductcode, CLA Signed

#30190 test: verify db2 can log to seperate file
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/DB2Test.java
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
  dev/com.ibm.ws.jdbc_fat_db2/test-applications/db2fat/src/db2/web/DB2TestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test debt, CLA Signed

#30049 Add beta support for AES-256 Password Encoding
  dev/com.ibm.websphere.appserver.spi.kernel.service/bnd.bnd
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/InvalidPasswordDecodingException.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/package-info.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/AESKeyManager.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/PasswordCipherUtilTest.java
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
  dev/com.ibm.ws.security.utility.securityutil/bnd.bnd
Labels: CLA Signed, team:Core Security

#30197 general review of DataProvider
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
Labels: team:Zombie Apocalypse, CLA Signed

#30184 OpenAPI: Reduce repeats for OpenAPIConfigTest
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/ConfigServerTestHelper.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigQuickTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigTest.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/filter/FilterConfigTest.java
Labels: noproductcode, CLA Signed

#30174 encapsulate recovery manager 15/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30169 encapsulate recovery manager 10/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30167 encapsulate recovery manager 8/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30166 encapsulate recovery manager 7/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30179 Added test case for recreating OL issue 29781
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Store.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, CLA Signed

#30157 Add additional tests for ddlGen that aligns with proposed doc
  dev/fattest.simplicity/resources/init-sqlserver.sql
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/src/componenttest/topology/utils/DDLGenScript.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerPropertiesTest.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/authDataServer.xml
  dev/fattest.simplicity/test/componenttest/topology/database/container/dataSourceServer.xml
  dev/fattest.simplicity/test/componenttest/topology/database/container/libraryServer.xml
  dev/io.openliberty.data.internal_fat_ddlgen/fat/src/test/jakarta/data/ddlgen/DDLGenTest.java
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/server.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/resources/WEB-INF/classes/META-INF/persistence.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Auto.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Automobile.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Car.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Cars.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Mobile.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/SUV.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/SUVs.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Sedan.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Sedans.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Truck.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Trucks.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Van.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Vans.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30140 Fix Faces 4.1 API to Pass Signature Tests
  dev/io.openliberty.jakarta.faces.4.1/.classpath
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/src/jakarta/faces/component/ActionSource.java
  dev/io.openliberty.jakarta.faces.4.1/src/jakarta/faces/component/ActionSource2.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#30191 Active condition
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/LibertyProcess.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/ActiveConditionTest.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/publish/features/test.active.condition-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.active.condition/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.active.condition/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.active.condition/src/test/active/condition/TestActiveCondition.java
  dev/com.ibm.ws.kernel.feature_fat/test.active.condition.bnd
Labels: CLA Signed

#30161 encapsulate recovery manager 2/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30163 encapsulate recovery manager 4/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30165 encapsulate recovery manager 6/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30168 encapsulate recovery manager 9/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30187 Add test for ZonedDateTime comparisons
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/DemographicInformation.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30186 Don't activate components or continue heartbeats during shutdown
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLogManager.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/TMRecoveryService.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WSATConfigServiceImpl.java
Labels: CLA Signed

#30164 encapsulate recovery manager 5/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30172 encapsulate recovery manager 13/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30207 refactor: convert TrmMessageType to enum
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/TrmMessageFactoryImpl.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/TrmRouteDataImpl.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/trm/TrmMessageType.java
Labels: CLA Signed

#30206 refactor: convert SubscriptionMessageType to enum
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/control/SubscriptionMessageType.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/SubscriptionMessageImpl.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/proxyhandler/NeighbourProxyListener.java
Labels: CLA Signed

#30214 empty list of entities redelivery
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Util.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
Labels: team:Zombie Apocalypse, ID review not needed, CLA Signed

#30152 CDI: Update to Weld 6 CR1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/public/cdi-4.1/io.openliberty.cdi-4.1.feature
  dev/io.openliberty.cdi.4.1.thirdparty/bnd.bnd
  dev/io.openliberty.org.jboss.weld6/bnd.bnd
  dev/io.openliberty.org.jboss.weld6/build.gradle
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#30208 refactor: convert TrmFirstContactMessageType to enum
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/trm/TrmFirstContactMessageType.java
Labels: CLA Signed

#30221 Set intervals to 1 second like the rest of the FAT
  dev/io.openliberty.http.monitor_fat/publish/resources/META-INF/microprofile-config.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerJustServer/jvm.options
Labels: noproductcode, CLA Signed

#29987 Create new DynamicConfigRuleCheckpoint for batch JDBC test
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/DynamicConfigRuleCheckpoint.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/JdbcConfigTestCheckpoint.java
Labels: noproductcode, CLA Signed

#30204 Overlay equinox PR 698
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/container/KeyBasedLockStore.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/EquinoxClassLoader.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/ModuleClassLoader.java
Labels: CLA Signed

#30162 encapsulate recovery manager 3/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30170 encapsulate recovery manager 11/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30173 encapsulate recovery manager 14/15
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#30239 OpenAPI: Don't use default ports for CacheTest
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java
Labels: noproductcode, CLA Signed

#30243 Add names to synchronized locks using KeyBaseLockStore
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
  dev/com.ibm.ws.kernel.boot.common/src/com/ibm/ws/kernel/boot/classloader/NameBasedClassLoaderLock.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/utils/KeyBasedLockStore.java
Labels: CLA Signed

#30209 refactor: convert JmsBodyType to enum
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/JmsBodyType.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/JsJmsMessageFactoryImpl.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/sib/mfp/impl/JsJmsMessageImpl.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsMessageImpl.java
Labels: CLA Signed

#30193 document application prereq use
  dev/com.ibm.ws.app.manager.lifecycle/src/com/ibm/wsspi/application/lifecycle/ApplicationPrereq.java
Labels: CLA Signed

#30150 Enable pages feature change fat for ee11
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#30238 dbProduct must be volatile
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/DBUtils.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/jakartaee8/server.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.active.condition/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test.active.condition.bnd
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/BaseTestClass.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
Labels: CLA Signed

#30188 Additional properties needed to complete checklist
  .ci-orchestrator/checks.yml
  .ci-orchestrator/pb.yml
  .ci-orchestrator/pbRTCBuild.yml
Labels: noproductcode, CLA Signed

#30234 Disable pbRTCBuild.yml from running on !build
  .ci-orchestrator/pb.yml
  .ci-orchestrator/pbRTCBuild.yml
Labels: noproductcode, CLA Signed

#30232 Disable OpenAPI UI FAT screen recordings
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UICustomPathTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIOauthTest.java
Labels: noproductcode, CLA Signed

#30256 OpenAPI: Use mark when checking for log messages
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigServerXMLTest.java
Labels: noproductcode, CLA Signed

#30229 Cleanup Simplified API persistent delivery delay tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#30257 WSTXMPR002AFVT can tolerate DataStoreAdapterException & ResourceAlloc…
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/tests/MultiRecoveryTest1.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.8.ee10/fat/src/tests/DBRerouteRecoveryTest.java
Labels: noproductcode, CLA Signed

#30220 Update to Equinox Framework version 3.21.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.kernel.boot/publish/platform/kernel-1.0.mf
  dev/com.ibm.wsspi.thirdparty.equinox/bnd.bnd
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/cds/CDSBundleFile.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/cds/CDSHookConfigurator.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/cds/CDSHookImpls.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/debug/Debug.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/EquinoxClassLoader.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/ModuleClassLoader.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/url/URLStreamHandlerProxy.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/storage/Storage.java
Labels: ID review not needed, CLA Signed

#30267 Update product and bundle version for release 25.0.0.1; copyright year
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#30266 Removing transitive test dep
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#30244 Update Batch Checkpoint files with Copyright headers
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/DynamicConfigRuleCheckpoint.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/JdbcConfigTestCheckpoint.java
Labels: noproductcode, CLA Signed

#30222 NLS messages for new Jakarta Concurrency function
  dev/io.openliberty.concurrent.internal.cdi/resources/io/openliberty/concurrent/internal/cdi/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduleCronTrigger.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/AppDefinedResourceFactory.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactory.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed, L2 Reviewed

#30269 Increase clientInactivityTimeout for multi-process recovery tests
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/wsat/fat/util/WSATTest.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/tests/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/tests/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.2/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.3/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.4/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.5/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.6/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/publish/servers/WSATRecoveryServer1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.8.ee10/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.8/build.gradle
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/build.gradle
Labels: CLA Signed

#30268 test: add yoko verbose trace
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleEar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Full.simpleWar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleEar/bootstrap.properties
  dev/com.ibm.ws.javaee.7.0_fat/publish/servers/javaee7Web.simpleWar/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/bandyball/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/basketball/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/bouncyball/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/bowlingball/bootstrap.properties
  dev/com.ibm.ws.transport.iiop.open_fat/publish/servers/buckyball/bootstrap.properties
Labels: noproductcode, CLA Signed

#30233 feat: temporarily substitute alternative artifactory mirror
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryImageNameSubstitutorTest.java
  dev/io.openliberty.org.testcontainers/.classpath
  dev/io.openliberty.org.testcontainers/build.gradle
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/dockerfiles/kyleaure/cloudant-developer/1.0/Dockerfile
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/CacheFiles.java
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/CustomImages.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29618 allow reproxy of request on cancelled branch
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/BranchManager.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/properties/CoreProperties.java
Labels: CLA Signed

#30259 AES256 password encoding - FAT test updates
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/customAESBasicRegistry.xml
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/defaultAESBasicRegistry.xml
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.federated/jvm.options
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat/jvm.options
Labels: noproductcode, CLA Signed, team:Core Security

#30237 Remove logic to skip EE9 repeat on Windows
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat.2/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius
