Repository OpenLiberty/open-liberty, pull requests merged in 2024-01, with the labels that each got.

#27202 Add portOpenRetries setting for secondary servers
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.nopeerlocking/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_CLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_FSCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/com.ibm.ws.transaction_LKCLOUD002/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/defaultAttributesServer2/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.1/publish/servers/longPeerStaleTimeServer2/server.xml
Labels: noproductcode, CLA Signed

#27160 Delete com.ibm.ws.org.apache.commons.discovery Bundle
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-3.0/io.openliberty.faces-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.2/com.ibm.websphere.appserver.jsf-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jsf-2.3/com.ibm.websphere.appserver.jsf-2.3.feature
  dev/com.ibm.ws.org.apache.commons.discovery/.classpath
  dev/com.ibm.ws.org.apache.commons.discovery/.gitignore
  dev/com.ibm.ws.org.apache.commons.discovery/.project
  dev/com.ibm.ws.org.apache.commons.discovery/.settings/bndtools.core.prefs
  dev/com.ibm.ws.org.apache.commons.discovery/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.org.apache.commons.discovery/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.org.apache.commons.discovery/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.org.apache.commons.discovery/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.discovery/bnd.overrides
Labels: in:Web Components, CLA Signed, team:Sirius

#27246 Fix EJB remote FAT http port
  dev/com.ibm.ws.ejbcontainer.remote_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.fat.SecureRemoteServer/server.xml
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27237 Issue #27235 : Skip Java 8 for tests
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/Servlet6toHealth.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/ee10toMP.java
Labels: noproductcode, CLA Signed

#27233 Update wait to 5100 ms to allow jetty to intialize
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java
Labels: in:Web Components, team:Sirius

#27245 Remove daytrader7 from runJandex.bat
  dev/com.ibm.ws.anno/publish/jandex/runJandex.bat
Labels: CLA Signed

#27248 scheduled asynchronous methods initial implementation
  dev/com.ibm.ws.concurrent_fat_schedasync/.classpath
  dev/com.ibm.ws.concurrent_fat_schedasync/.project
  dev/com.ibm.ws.concurrent_fat_schedasync/.settings/bndtools.core.prefs
  dev/com.ibm.ws.concurrent_fat_schedasync/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.concurrent_fat_schedasync/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.concurrent_fat_schedasync/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.concurrent_fat_schedasync/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_schedasync/fat/src/test/concurrency/schedasync/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_schedasync/fat/src/test/concurrency/schedasync/ScheduledAsyncMethodsTest.java
  dev/com.ibm.ws.concurrent_fat_schedasync/publish/servers/com.ibm.ws.concurrent.fat.schedasync/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_schedasync/publish/servers/com.ibm.ws.concurrent.fat.schedasync/server.xml
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncAppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncTestServlet.java
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/AsyncInterceptor.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduleCronTrigger.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduledAsyncMethod.java
Labels: team:Zombie Apocalypse, CLA Signed

#27221 Concurrent-3.1 Update Deployment Descriptors
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javaeedd-1.0.feature
  dev/com.ibm.websphere.appserver.spi.javaeedd/bnd.bnd
  dev/com.ibm.websphere.appserver.spi.javaeedd/com.ibm.websphere.appserver.spi.javaeedd.pom
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/PlatformVersion.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/common/ContextService.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/common/ManagedExecutor.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/common/ManagedScheduledExecutor.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/common/ManagedThreadFactory.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/common/package-info.java
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/app/Application.java
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/web/WebApp.java
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/web/package-info.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/app/ApplicationDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ContextServiceType.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ManagedExecutorType.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ManagedScheduledExecutorType.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/ManagedThreadFactoryType.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/common/XSDTokenType.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/web/WebAppDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/web/WebFragmentDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/DDJakarta10Elements.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/DDJakarta11Elements.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/app/AppTestBase.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/web/WebAppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/web/WebAppTestBase.java
Labels: team:Zombie Apocalypse, CLA Signed

#27236 Use Faces 4.0 libraries (with bad MANIFEST.MF) in ErrorPathsTest
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/tests/ErrorPathsTest.java
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/MANIFEST_badMojarra_40.MF
  dev/com.ibm.ws.jsfContainer_fat_2.3/publish/files/MANIFEST_badMyfacesApi_40.MF
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27038 Create Websocket 2.2 API with 2.2.0-M1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.2.feature
  dev/io.openliberty.jakarta/websocket.client.2.2.bnd
  dev/io.openliberty.jakarta/websocket.server.2.2.bnd
Labels: CLA Signed

#27255 Increase EJB Timer FAT delay tolerance
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27226 Servlet 6.1 Add Test for New HTTP Response Status Codes
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61HTTPResponseCodesTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_HttpResponseCodesTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_HttpResponseCodesTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/HTTPResponseCodesTest.war/src/httpcodes/servlets/TestHttpResponseCodesServlet.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE11

#27170 Enable Servlet 6.1 EE11 repeat for com.ibm.ws.webcontainer.servlet.3.1_fat
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServletContextUnsupportedOperationExceptionTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27251 Update OpenAPI UI dependencies
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/index.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-05fbaeccf4fe5daf5add.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-05fbaeccf4fe5daf5add.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-35b3219247920e7ab44f.css
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-35b3219247920e7ab44f.css.map
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-189e14358544351fa14f.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-189e14358544351fa14f.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-7b5741fd872120b3691d.js
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/liberty-swagger-ui-bundle-7b5741fd872120b3691d.js.LICENSE.txt
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/mpOpenApi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/dist/openapi.html
  dev/com.ibm.ws.openapi.ui/swagger-ui/package-lock.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/src/style/original/_layout.scss
Labels: CLA Signed

#27262 JAX-WS: SOAP response default is set UTF-8
  dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/src/org/apache/cxf/helpers/HttpHeaderHelper.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#27256 Allow both jakarta and javax ffdcs
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO

#27265 295260-Remove SQLJ tests for IBM i
  dev/com.ibm.ws.jdbc_fat_db2/fat/src/com/ibm/ws/jdbc/fat/db2/SQLJTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, ibmi

#27247 update metatype name and desc for back-channel logout
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
Labels: ID reviewed, CLA Signed, L2 ReviewNotRequired

#27271 commentry
  dev/com.ibm.ws.jsfContainer/src/com/ibm/ws/jsf/container/cdi/IBMViewHandlerProxy.java
Labels: CLA Signed

#27275 Updating MP Config 3.1 API maven coordinates to match version in maven central
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.config-3.1.feature
Labels: CLA Signed

#27270 log out the records if we find the wrong number
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat.common/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/framework/KafkaReader.java
Labels: noproductcode, CLA Signed

#27264 Update SpringBootThinUtil for Spring Boot 3.1.x
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
Labels: CLA Signed

#27272 Updates for building using Java 21 instead of Java 17
  dev/com.ibm.ws.event/test/com/ibm/ws/event/internal/EventEngineImplTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap/test/com/ibm/ws/security/wim/adapter/ldap/context/ContextManagerTest.java
  dev/com.ibm.ws.serialization/test/com/ibm/ws/serialization/DeserializationObjectInputStreamTest.java
  dev/io.openliberty.concurrent.internal.cdi/.classpath
  dev/io.openliberty.concurrent.internal.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.jboss.weld6/bnd.bnd
  dev/settings.gradle
  dev/wlp-gradle/java.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Performance

#27258 Web tier fat updates
  dev/com.ibm.ws.el.3.0_fat/bnd.bnd
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/tests/EL30MiscTests.java
  dev/com.ibm.ws.el.3.0_fat/test-applications/TestEL3.0.war/src/com/ibm/ws/el30/fat/servlets/EL30InvocationMethodExpressionsServlet.java
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsp.2.3_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC400BadRequestTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WC500BadRequestDefaultTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerMiscTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServerTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletContextUnsupportedOperationExceptionTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/test-applications/EL50BasicTests.war/src/io/openliberty/el50/fat/basic/servlets/EL50BasicTestsServlet.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27267 Try to workaround in memory LDAP shutown issue
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/utils/ldaputils/CommonLocalLDAPServerSuite.java
Labels: test bug, CLA Signed, team:Security SSO

#27278 Update ending copyright for bundles to be 2024
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed, team:Performance

#27284 context propagation to scheduled async methods
  dev/com.ibm.ws.concurrent_fat_schedasync/fat/src/test/concurrency/schedasync/ScheduledAsyncMethodsTest.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncAppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncTestServlet.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/AsyncInterceptor.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduleCronTrigger.java
Labels: team:Zombie Apocalypse, CLA Signed

#27285 BasicRepository.count method renamed to comply with Query by Method Name BNF
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
Labels: team:Zombie Apocalypse, CLA Signed

#27259 Resolving NPE and adding a unit test to confirm expected behavior
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
Labels: CLA Signed

#27289 Update buildpath in jaxws FAT for Eclipse
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
Labels: noproductcode, test bug, CLA Signed

#27239 Only create one JSON instance per health service
  dev/io.openliberty.jsonsupport.internal/src/com/ibm/websphere/jsonsupport/JSONFactory.java
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30HttpResponseBuilder.java
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30ServiceImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/HealthCheck31ServiceImpl.java
Labels: CLA Signed, performance

#27276 Update SpringBootThinUtil for Spring Boot 3.2.x
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
Labels: CLA Signed

#27216 Remove beta flag for instant on support for jaxws/xmlws
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxws-2.2/com.ibm.websphere.appserver.jaxws-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-3.0/io.openliberty.xmlWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-4.0/io.openliberty.xmlWS-4.0.feature
  dev/io.openliberty.checkpoint_fat/publish/servers/jaxWSVirtualHost/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/fat/src/io/openliberty/checkpoint/jaxws/fat/LibertyCXFPositivePropertiesTest.java
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/EJBWSBasicServer/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/LibertyCXFPositivePropertiesTestServer/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/WebServiceRefTestServer/jvm.options
Labels: CLA Signed

#27286 Pages 4.0 Clean Up
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSP23JSP22ServerTest.java
  dev/com.ibm.ws.jsp/resources/com/ibm/ws/jsp/resources/messages.nlsprops
  dev/io.openliberty.pages.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.pages.3.1.internal_fat/fat/src/io/openliberty/pages31/fat/tests/MiscTests.java
  dev/io.openliberty.pages.4.0.internal.factories/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.pages.4.0.internal.factories/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.pages.4.0.internal_fat/bnd.bnd
  dev/io.openliberty.pages.4.0.internal_fat/publish/servers/pages40Server/bootstrap.properties
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/errorPage.jsp
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/isThreadSafe.jsp
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/jspFallback.jsp
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/jspParams.jsp
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/jspPlugin.jsp
  dev/io.openliberty.pages.4.0.internal_fat/test-applications/Pages40Changes.war/resources/testQueryStringonError.jsp
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, jakartaEE11

#27263 Update earlier fix and try different way for ffdc checking
  dev/com.ibm.ws.jbatch.cdi_fat/fat/src/fat/junit/TranTimeoutCleanupTest.java
  dev/com.ibm.ws.jbatch.cdi_fat/test-applications/implicit/src/app/timeout/TranTimeoutCleanupServlet.java
  dev/com.ibm.ws.jbatch.open.partition_fat/fat/src/batch/fat/junit/PartitionReducerTest.java
Labels: noproductcode, test bug, CLA Signed

#27297 Fix telemetry typos from oltp to otlp
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent129Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerOtlpTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/TracingNotEnabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/JaegerContainer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/otelCollector/OtelCollectorContainer.java
Labels: noproductcode, CLA Signed

#27238 Add Beta guards to Liberty-kafka connector new options
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/KafkaCustomContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/invalid/KakfaInvalidContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
Labels: CLA Signed

#27203 Improve install performance from directory repository
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
  dev/com.ibm.ws.repository.test.utils/src/com/ibm/ws/lars/testutils/clients/DirectoryWriteableClient.java
  dev/com.ibm.ws.repository.test.utils/src/com/ibm/ws/lars/testutils/fixtures/FileRepositoryFixture.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/common/enums/ReadMode.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/connections/DirectoryRepositoryConnection.java
  dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/DirectoryClient.java
  dev/com.ibm.ws.repository/test/com/ibm/ws/repository/connections/test/RepositoryConnectionTest.java
  dev/com.ibm.ws.repository_fat/fat/src/com/ibm/ws/repository/transport/client/test/FileClientLicenseTest.java
  dev/com.ibm.ws.repository_fat/fat/src/com/ibm/ws/repository/transport/client/test/InvalidDirectoryClientTest.java
Labels: CLA Signed

#27279 Fix incorrect post fat kill usage
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: CLA Signed

#26877 Properly handle H2 upgrade with data packets
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInputStreamImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: in:Transport, CLA Signed, team:Sirius

#27313 24.0.0.1 Notices
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#27307 Update bnd and eclipse settings for recent changes
  dev/com.ibm.ws.concurrent_fat_schedasync/.classpath
  dev/com.ibm.ws.concurrent_fat_schedasync/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_jpa/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.persistence.api.3.2/.classpath
  dev/io.openliberty.jakarta.persistence.api.3.2/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.persistence.api.3.2/bnd.bnd
  dev/io.openliberty.org.eclipse.persistence-3.2/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.pages.4.0.internal.factories/bnd.bnd
  dev/io.openliberty.pages.4.0.internal_fat/.classpath
  dev/io.openliberty.persistence.3.2.thirdparty/.classpath
Labels: CLA Signed, team:Performance

#27312 More toleration of comms errors
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/fat/src/tests/ReroutePeerRecoveryTest.java
Labels: noproductcode, CLA Signed

#26843 Home Server should aggressively claim its recovery logs
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/FailureScopeController.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirector.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.norecoverygroup/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.norecoverygroup/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.peerServerPrecedence/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.peerServerPrecedence/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.shortlease/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.shortlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.shortlease/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.shortlease/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerPrecedenceServer1/bootstrap.properties
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/peerPrecedenceServer1/server.xml
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Base2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Simple2PCCloudServlet.java
  dev/com.ibm.ws.transaction.cloud_fat.peerlocking.2/fat/src/tests/DualServerPeerLockingTest2.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.fastcheck/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD002.fastcheck/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxConnection.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxPooledConnection.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-bundles/ifxlib/src/com/informix/jdbcx/IfxStatement.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
Labels: CLA Signed

#27295 Only create one JSON instance per mpHealth 1.0 and 2.0 service
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20HttpResponseBuilder.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckHttpResponseBuilder.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckServiceImpl.java
Labels: CLA Signed

#27321 first steps for managed thread factory with virtual=true
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedVirtualThreadAction.java
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/Concurrency31Test.java
  dev/com.ibm.ws.concurrent_fat_jakarta/fat/src/test/jakarta/concurrency/FATSuite.java
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta.ee11/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta.ee11/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#27320 add instantOn to versionless features
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth/io.openliberty.versionless.mpHealth.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpMetrics/io.openliberty.versionless.mpMetrics.feature
Labels: CLA Signed

#27315 Add assert message
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/servlet/HttpTraceTestServlet.java
Labels: noproductcode, CLA Signed

#27317 xmlBinding-4.0: Prevent test ordering from causing CNFE in JAXBContextTest
  dev/io.openliberty.xmlBinding.4.0.internal_fat/test-applications/jaxbApp/src/jaxb/web/JAXBContextTestServlet.java
Labels: noproductcode, CLA Signed

#27330 JAX-WS: Add timeout increase for JAX-WS clients in Interop Tests
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/fat/src/com/ibm/ws/fat/WebServicesInteroperabilityTest.java
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/bootstrap.properties
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/publish/servers/WebServicesInteroperabilityServer/server.xml
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-interop/src/io/openliberty/interop/InteropStartResource.java
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxrs-interop/src/io/openliberty/interop/util/InteropConstants.java
  dev/io.openliberty.jaxrs.2.1.jaxws.2.2_fat/test-applications/jaxws-peopleservice/src/com/ibm/ws/jaxws/test/wsr/server/impl/Bill.java
Labels: noproductcode, CLA Signed

#27334 Remove embedded tag project poms
  dev/io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal/bnd.bnd
  dev/io.openliberty.jakarta.servlet.jsp.tags.3.0.internal/bnd.bnd
Labels: CLA Signed

#27293 scheduled asynchronous methods on virtual threads
  dev/com.ibm.ws.concurrent_fat_schedasync/publish/servers/com.ibm.ws.concurrent.fat.schedasync/server.xml
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncAppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncTestServlet.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/com.ibm.ws.threading_policy_fat/test-applications/vtpolicyapp/src/web/vt/PolicyVirtualThreadServlet.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduledAsyncMethod.java
Labels: team:Zombie Apocalypse, CLA Signed

#27322 Remove renamed features
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectors-2.0.internal.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.connectors-2.1.internal.feature
Labels: CLA Signed, team:Performance

#27281 Create script to update OpenAPI UI with latest Swagger UI version
  dev/com.ibm.ws.openapi.ui/update-openapi-ui.sh
Labels: noproductcode, CLA Signed

#27167 Expand selenium OpenAPI UI tests
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/app/TestResource.java
  dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/SecureTestResource.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/TestApplication.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/app/TestResource.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIBasicTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/fat/src/io/openliberty/microprofile/openapi/ui/internal/fat/tests/UIOauthTest.java
Labels: noproductcode, CLA Signed

#27305 27120 kafka server stop
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/util/KafkaUtils.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#27340 Concurrency 3.1 injection binding for qualifier and virtual
  dev/io.openliberty.concurrent.internal/bnd.bnd
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryDefinitionProvider.java
Labels: team:Zombie Apocalypse, CLA Signed

#27033 Deadlock in sipcontainer caused by proxy branch timeout
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/ProxyBranchImpl.java
Labels: CLA Signed

#27287 Reduce how many times we transform the idp war
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/CommonTest.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/ShibbolethHelpers.java
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/actions/LargeProjectRepeatActions.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.2/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.3/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/fat/src/com/ibm/ws/security/saml/sso/fat/config/mapToUserRegistry/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.config/fat/src/com/ibm/ws/security/saml/sso/fat/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/fat/src/com/ibm/ws/security/saml/sso/fat/endpoint/samlmetadata/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/fat/src/com/ibm/ws/security/saml/fat/jaxrs/config/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/fat/src/com/ibm/ws/security/saml/fat/jaxrs/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated/fat/src/com/ibm/ws/security/saml/fat/logout/IDPInitiated/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest/fat/src/com/ibm/ws/security/saml/fat/logout/httpServletRequest/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout/fat/src/com/ibm/ws/security/saml/fat/logout/ibmSecurityLogout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat.logout/fat/src/com/ibm/ws/security/saml/fat/logout/FATSuite.java
  dev/com.ibm.ws.security.saml.sso_fat/fat/src/com/ibm/ws/security/saml/fat/FATSuite.java
Labels: test bug, CLA Signed, team:Security SSO, In Progress

#27310 Use correct channel for Reactive Messaging Custom Context AppMetadata test
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/KafkaCustomContextTestServlet.java
Labels: noproductcode, CLA Signed

#27324 Re-introduce: update metatype name and desc for back-channel logout
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.oauth/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
Labels: ID reviewed, CLA Signed

#27343 Introduce LogsUnderlyingTablesMissingException
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitImpl.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLRecoverableUnitSectionImpl.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/LogsUnderlyingTablesMissingException.java
Labels: CLA Signed

#27346 Fix access_token parser
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/TokenKeeper.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#27347 JAX-WS: Testing soap response encoding
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/.classpath
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/EncodingTest.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/FATSuite.java
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/servers/EncodingTestServer/PeopleService.wsdl
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/servers/EncodingTestServer/bootstrap.properties
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/servers/EncodingTestServer/server.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/test-applications/encodingTest/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/test-applications/encodingTest/src/com/ibm/ws/jaxws/test/wsr/test/servlet/EncodingTestServlet.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#27354 simulate qualifiers for executors and contextservice
  dev/com.ibm.ws.concurrent/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/Unrecognized.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithoutAppContext.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ContextServiceBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedScheduledExecutorBean.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#27308 Better key generation for SSL tests
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATSecurityUtils.java
Labels: CLA Signed

#27358 managed executors with virtual=true
  dev/com.ibm.ws.concurrent_fat_jakarta/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#27363 Update .classpath and bnd files
  dev/com.ibm.ws.cdi.lifecycle_fat/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta/.classpath
  dev/com.ibm.ws.install.featureUtility/.classpath
  dev/com.ibm.ws.jaxrs.2.x.monitor/.classpath
  dev/com.ibm.ws.jbatch.open.bonuspayout_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.open.partition_fat/.classpath
  dev/com.ibm.ws.jbatch.open.partition_fat/bnd.bnd
  dev/com.ibm.ws.jbatch.open.security_fat/.classpath
  dev/com.ibm.ws.jbatch.open_fat/.classpath
  dev/com.ibm.ws.logging_fat/bnd.bnd
  dev/com.ibm.ws.security.jaspic.jakarta10_fat/bnd.bnd
  dev/io.openliberty.ejbcontainer.mdb.checkpoint_fat/.classpath
  dev/io.openliberty.io.opentelemetry/.classpath
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/bnd.bnd
  dev/io.openliberty.pages.3.1.internal_fat/.classpath
  dev/io.openliberty.restfulWS.internal.globalhandler/.classpath
  dev/io.openliberty.restfulWS.mpMetrics.filter/.classpath
  dev/io.openliberty.security.jakartasec.3.0.internal.cdi/.classpath
Labels: noproductcode, CLA Signed, team:Performance

#27332 Update io.openliberty.jaxrs30 API bundle / javadoc and other updates
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWS-3.0/io.openliberty.restfulWS-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-4.0/io.openliberty.restfulWSClient-4.0.feature
  dev/io.openliberty.jaxrs30/bnd.bnd
  dev/io.openliberty.jaxrs30/original.bnd
  dev/io.openliberty.jaxrs30/transformed.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/src/com/ibm/websphere/jaxrs20/multipart/IAttachment.java
  dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/providers/multipart/IAttachmentImpl.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java
  dev/io.openliberty.org.jboss.resteasy.server.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.server/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.validator.provider/bnd.bnd
Labels: CLA Signed, team:Performance

#27376 Fixes to make things build in eclipse
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/util/KafkaUtils.java
  dev/io.openliberty.pages.3.1.internal_fat/test-applications/Misc.war/src/io/openliberty/pages31/fat/misc/AnInterface.java
  dev/io.openliberty.pages.3.1.internal_fat/test-applications/Misc.war/src/io/openliberty/pages31/fat/misc/Cafe.java
  dev/io.openliberty.pages.3.1.internal_fat/test-applications/Misc.war/src/io/openliberty/pages31/fat/misc/Coffee.java
  dev/io.openliberty.pages.3.1.internal_fat/test-applications/Misc.war/src/io/openliberty/pages31/fat/misc/other/Sugar.java
Labels: noproductcode, CLA Signed, team:Performance

#27349 Upload Jakarta EE 11 schemas and update tests
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/application_11.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/jakartaee_11.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/jsp_4_0.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-app_6_1.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-common_6_1.xsd
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/CommonTests.java
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/FATSuite.java
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/core/DDValidAppTests_J11.java
  dev/com.ibm.ws.javaee.ddmodel_fat/fat/src/com/ibm/ws/javaee/ddmodel/suite/core/DDValidModTests_J11.java
  dev/com.ibm.ws.javaee.ddmodel_fat/publish/files/server_app_j11.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/publish/files/server_mod_j11.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/MANIFEST.MF
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ejb-jar.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm-ejb-jar-bnd.xmi
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm-ejb-jar-ext.xmi
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm-ejb-jar-ext.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm-managed-bean-bnd.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/EJBTest.jar/resources_j11/META-INF/ibm_ejbext.properties
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTest.war/resources_j11/META-INF/permissions.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTest.war/resources_j11/WEB-INF/ibm-web-bnd.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTest.war/resources_j11/WEB-INF/ibm-web-ext.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTest.war/resources_j11/WEB-INF/ibm-ws-bnd.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTest.war/resources_j11/WEB-INF/web.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/ServletTestNoBnd.war/resources_j11/WEB-INF/web.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/Test.ear/resources_j11/META-INF/application.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/Test.ear/resources_j11/META-INF/ibm-application-bnd.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/Test.ear/resources_j11/META-INF/ibm-application-ext.xml
  dev/com.ibm.ws.javaee.ddmodel_fat/test-applications/Test.ear/resources_j11/META-INF/permissions.xml
Labels: team:Zombie Apocalypse, CLA Signed

#27367 Add peerRecoveryPrecedence to get correct behavior for test
  dev/io.openliberty.checkpoint_fat_transaction/publish/servers/checkpointTransactionLongLeaseServer/server.xml
Labels: noproductcode, CLA Signed

#27356 Fix dir checksums are generated into
  dev/build.image/build.gradle
Labels: CLA Signed

#27373 Fix InstantOn persistence FAT break 298584
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/SessionDatabaseTest.java
Labels: noproductcode, CLA Signed

#27380 virtual true on managed thread factory
  dev/com.ibm.ws.concurrent_fat_jakarta/publish/servers/com.ibm.ws.concurrent.fat.jakarta.ee11/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorDefinitionBinding.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryDefinitionBinding.java
Labels: team:Zombie Apocalypse, CLA Signed

#27359 Junits for records
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/Person.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/Validation31TestServlet.java
Labels: noproductcode, CLA Signed

#27261 Clarify the behaviors of response addHeader and setHeader
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/srt/SRTServletResponse.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletResponse61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61AddAndSetHeaderTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_AddAndSetHeaderTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_AddAndSetHeaderTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/AddAndSetHeaderTest.war/src/headers/servlets/TestAddAndSetHeadersServlet.java
Labels: in:Web Components, team:Sirius, jakartaEE11

#27370 Suppress FFDC for IOException & FileNotFoundException
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.wsat.migration_fat.7/publish/servers/MigrationServer1/server.xml
  dev/com.ibm.ws.wsat.migration_fat.7/publish/servers/MigrationServer2/server.xml
  dev/com.ibm.ws.wsat.migration_fat.7/publish/servers/MigrationServer3/server.xml
Labels: CLA Signed

#27338 Update Reactive Messaging and Mutiny Packages
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/util/KafkaUtils.java
  dev/io.openliberty.io.smallrye.reactive.messaging-api4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.mutiny/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.streams-operators-jakarta/bnd.bnd
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat.common/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/common/KafkaUtils.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/validation/KafkaValidationTests.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/validation/OutgoingConnectorMultipleUpstreams.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/validation/IncomingMethodWithMultipleUpstreams.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/validation/ValidationTests.java
Labels: CLA Signed

#27369 Replace FFDC with warning on recovery log deletion failure
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
Labels: CLA Signed

#27388 Replace FFDC with warning on recovery log drop table failure
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#27361 jUnit for GroupSequence on Java Records
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/FirstGroup.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/SecondGroup.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/SignupForm.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/Validation31TestServlet.java
  dev/io.openliberty.jakarta.validation.v31_fat/test-applications/val31/src/val31/web/ValidationOrder.java
Labels: noproductcode, CLA Signed

#27395 Add alias keywords to pipelines
  .ci-orchestrator/pb.yml
  .ci-orchestrator/pbRTCBuild.yml
Labels: noproductcode, CLA Signed

#27387 InstantOn fix to persist config on checkpoint
  dev/com.ibm.ws.config/src/com/ibm/ws/config/admin/internal/ConfigurationStore.java
Labels: CLA Signed

#27374 cleanup JAX-RS 2.1 feature and upgrade to 2.1.1 API jar
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.javax.jaxrs-2.1.feature
  dev/com.ibm.websphere.javaee.jaxrs.2.1/bnd.bnd
Labels: in:JAX-RS, CLA Signed

#27389 Update MP Metrics 5.x Tck -> 5.0.2 and 5.1.1
  dev/io.openliberty.microprofile.metrics.internal.5.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#27399 Use unique group ids for custom context tests
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/KafkaCustomContextTest.java
Labels: noproductcode, CLA Signed

#27386 Work around session cleanup timing issue
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/OAuth20DynamicConfig01.java
  dev/com.ibm.ws.security.oauth_fat/publish/servers/com.ibm.ws.security.oauth-2.0.fat/server.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#27404 qualifiers on context service and executor definitions
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/bootstrap.properties
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/Unrecognized.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithoutAppContext.java
  dev/io.openliberty.concurrent.internal.cdi/bnd.bnd
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ContextServiceBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedScheduledExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/QualifierProxy.java
  dev/io.openliberty.concurrent.internal/bnd.bnd
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactories.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/package-info.java
Labels: team:Zombie Apocalypse, CLA Signed

#27393 Fix BundleFactory usage of MessageDigest
  dev/com.ibm.ws.dynamic.bundle/src/com/ibm/ws/dynamic/bundle/BundleFactory.java
Labels: CLA Signed

#27414 qualifiers on managed thread factory definition
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, CLA Signed

#27412 Workaround slowness of first request to OP
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/src/io/openliberty/security/jakartasec/fat/utils/ShortTokenLifetimePrep.java
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationTokenMinValidityTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#27357 Fix JavaIllegalAccessTest dns test values
  dev/io.openliberty.java.internal_fat/test-applications/illegalaccess/src/test/web/IllegalAccessTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27384 Update liberty-kafka connector Nack message
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
Labels: ID reviewed, CLA Signed, L2 Reviewed

#27304 Modifications to work around a Java 8/Shibboleth/LDAP issue
  dev/com.ibm.ws.security.fat.common/src/com/ibm/ws/security/fat/common/TestServer.java
  dev/com.ibm.ws.security.saml.sso_fat.common/ShibbolethCommon.gradle
  dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/metadata/spOPMetadata.xml.orig
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: test bug, CLA Signed, team:Security SSO, In Progress

#27416 Update install kernel map lib
  dev/com.ibm.ws.install.map/bnd.bnd
Labels: CLA Signed

#27409 Update org.eclipse.osgi to 3.18.600
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
Labels: CLA Signed

#27348 Config3.1: Updating SmallRye Jars
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.common2/bnd.bnd
  dev/io.openliberty.io.smallrye.config3/bnd.bnd
  dev/io.openliberty.io.smallrye.config3/src/io/openliberty/microprofile/config/internal/extension/OLSmallRyeConfigBuilder.java
Labels: CLA Signed

#27408 Add session cookieSameSite to the ibmui cookies group
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
Labels: in:Web Components, CLA Signed, team:Sirius

#26975 Create logging for constant pool bug
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.env
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.xml
  dev/com.ibm.ws.org.jboss.weld/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/FileLogger.java
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigClassVisitor.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/AbstractInstrumentation.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/DynamicTraceInstrumentation.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLogger.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLoggerTest.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyTracePreprocessInstrumentation.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/StaticTraceInstrumentation.java
  dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/UnitTestLibertyRuntimeTransformer.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/StaticTraceTestTransformer.java
  dev/io.openliberty.org.jboss.weld4/bnd.bnd
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/FileLogger.java
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
Labels: CLA Signed

#27403 Delete peer server lease if its recovery logs are missing
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryAgent.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirector.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
Labels: CLA Signed

#27426 Increase tolerance in EJB timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/fat/src/com/ibm/ws/ejbcontainer/timer/persistent/fat/tests/PersistentTimerCoreTest.java
  dev/com.ibm.ws.ejbcontainer.timer.persistent_fat/test-applications/PersistentTimerCoreEJB.jar/src/com/ibm/ws/ejbcontainer/timer/persistent/core/ejb/StatelessTimedBean.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27423 Add retry logic to property decryption
  dev/fattest.simplicity/src/componenttest/topology/utils/ExternalTestService.java
Labels: noproductcode, CLA Signed

#26129 jaxws-2.2 and jaxb-2.2: Update RI to 2.3.6/2.3.9
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.jbatch.container/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.ws.anno/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
  dev/com.ibm.ws.jaxb.tools.schemagen/bnd.bnd
  dev/com.ibm.ws.jaxb.tools.xjc/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb-tools.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_schemagen.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_xjc.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools.wadl2java/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxws.X.wsat_fat/build.gradle
  dev/com.ibm.ws.jaxws.ejb_fat/build.gradle
  dev/com.ibm.ws.jaxws.tools.wsgen/bnd.bnd
  dev/com.ibm.ws.jaxws.tools.wsimport/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/src/com/sun/tools/ws/wscompile/WsimportTool.java
  dev/com.ibm.ws.kernel.cmdline/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file_fat/bnd.bnd
  dev/com.ibm.ws.tx.jta_fat_hibernate/build.gradle
  dev/com.ibm.ws.wsat.common/bnd.bnd
  dev/fattest.simplicity/bnd.bnd
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.classpath
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.project
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/bnd.bnd
  dev/io.openliberty.jaxws.global.handler.internal_fat/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.1/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.ssl/bnd.bnd
  dev/io.openliberty.jaxws.security_fat/bnd.bnd
  dev/io.openliberty.mail.2.0.internal_fat/build.gradle
  dev/io.openliberty.xmlws.4.0.internal_fat/build.gradle
Labels: CLA Signed

#27350 Servlet 6.1: Add Additional Response sendRedirect methods
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/srt/SRTConnectionContext61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/webapp/WebApp61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/osgi/webapp/WebAppDispatcherContext61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal/src/io/openliberty/webcontainer61/srt/SRTServletResponse61.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61ResponseSendRedirectTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ResponseSendRedirectTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ResponseSendRedirectTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/ResponseSendRedirectTest.war/src/sendredirect/servlets/TestResponseSendRedirectServlet.java
Labels: in:Web Components, ID reviewed, CLA Signed, team:Sirius, L2 Reviewed, jakartaEE11

#27424 Reset test servers between tests
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/tests/MultiRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.6/fat/src/tests/DBRerouteRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/fat/src/tests/ReroutePeerRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/publish/servers/WSATRecoveryClient3/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.7/publish/servers/WSATRecoveryServer3/server.xml
Labels: noproductcode, CLA Signed

#27288 add exp claim to logout token
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BackChannelLogoutCommonTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/HttpMethodsTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/LogoutTokenValidationTests.java
  dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/common/internal/resources/OidcCommonMessages.nlsprops
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/BackchannelLogoutConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/backchannellogout/internal/LogoutTokenValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/token/PayloadConstants.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/backchannellogout/internal/LogoutTokenValidatorTest.java
  dev/com.ibm.ws.security.openidconnect.clients.common/test/com/ibm/ws/security/openidconnect/jose4j/Jose4jValidatorTests.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilder.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilderTest.java
Labels: ID reviewed, CLA Signed

#27433 Tolerate return code of 71 when Semeru Java cannot find criu pre-req
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/JavaInfoIsCriuSupportedTest.java
Labels: noproductcode, CLA Signed

#27427 make managed thread factory bean application scoped
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/context/location/Location.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/context/location/LocationContextProvider.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/context/location/LocationContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/context/location/LocationContextSnapshot.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithTransactionContext.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
Labels: team:Zombie Apocalypse, CLA Signed

#27434 Don't set Java security manager when running with EE 11 features
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE11Action.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, team:Performance, jakartaEE11

#27431 Ignore correct message in Java17Test: CWWJS0007W
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPJava17Test.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27401 Initialize tryShellExtensions before using it
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#26732 Update facesContainer-4.1 to accept 4.1 jars
  dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.1/io.openliberty.facesContainer-4.1.feature
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.classpath
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.project
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.settings/bndtools.core.prefs
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.facesContainer.4.1.internal.classloading/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.facesContainer.4.1.internal.classloading/bnd.bnd
  dev/io.openliberty.facesContainer.4.1.internal.classloading/resources/OSGI-INF/wlp/defaultInstances.xml
  dev/io.openliberty.facesContainer.4.1.internal.classloading/src/io/openliberty/faces41/internal/container/classloading/Faces41LibraryIntegration.java
  dev/io.openliberty.facesContainer.4.1.internal.classloading/src/io/openliberty/faces41/internal/container/classloading/package-info.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27337 Update EclipseLink 2.7.13 -> 2.7.14
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/build.gradle
  dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
Labels: ID reviewed, in:JPA, team:Blizzard, CLA Signed, L2 Reviewed

#27455 Revert "Config3.1: Updating SmallRye Jars"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.common2/bnd.bnd
  dev/io.openliberty.io.smallrye.config3/bnd.bnd
  dev/io.openliberty.io.smallrye.config3/src/io/openliberty/microprofile/config/internal/extension/OLSmallRyeConfigBuilder.java
Labels: CLA Signed

#27417 Servlet61 Add Test for Empty URL Patterns Mapping
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61EmptyURLPatternMappingTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_EmptyUrlPatternMappingTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_EmptyUrlPatternMappingTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/EmptyURLPatternMappingTest.war/src/emptymapping/servlets/TestEmptyUrlPatternMappingServlet.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE11

#27436 Servlet61 Add test to verify request getDateHeader and getIntHeader
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61AddAndSetHeaderTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_AddAndSetHeaderTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/AddAndSetHeaderTest.war/src/headers/servlets/TestAddAndSetHeadersServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27457 Don't run LRA TCK on z/OS
  dev/io.openliberty.microprofile.lra.1.0.internal_fat_tck/fat/src/io/openliberty/microprofile/lra/tck/LraTckLauncher.java
Labels: noproductcode, CLA Signed

#27465 JAX-WS: Java 2 Security Fix for a test
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/publish/servers/EncodingTestServer/server.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#27470 Revert "JAXB: Update fattest.simplicity/bnd.bnd's JAXB dependency"
  dev/com.ibm.ws.tx.jta_fat_hibernate/build.gradle
  dev/fattest.simplicity/build.gradle
  dev/io.openliberty.mail.2.0.internal_fat/build.gradle
Labels: noproductcode, CLA Signed

#27472 Revert "jaxws-2.2 and jaxb-2.2: Update RI to 2.3.6/2.3.9"
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.jbatch.container/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.ws.anno/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
  dev/com.ibm.ws.jaxb.tools.schemagen/bnd.bnd
  dev/com.ibm.ws.jaxb.tools.xjc/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb-tools.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_schemagen.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_xjc.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools.wadl2java/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxws.X.wsat_fat/build.gradle
  dev/com.ibm.ws.jaxws.ejb_fat/build.gradle
  dev/com.ibm.ws.jaxws.tools.wsgen/bnd.bnd
  dev/com.ibm.ws.jaxws.tools.wsimport/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/src/com/sun/tools/ws/wscompile/WsimportTool.java
  dev/com.ibm.ws.kernel.cmdline/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file_fat/bnd.bnd
  dev/com.ibm.ws.tx.jta_fat_hibernate/build.gradle
  dev/com.ibm.ws.wsat.common/bnd.bnd
  dev/fattest.simplicity/bnd.bnd
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.classpath
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.project
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/bnd.bnd
  dev/io.openliberty.jaxws.global.handler.internal_fat/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.1/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.ssl/bnd.bnd
  dev/io.openliberty.jaxws.security_fat/bnd.bnd
  dev/io.openliberty.mail.2.0.internal_fat/build.gradle
  dev/io.openliberty.xmlws.4.0.internal_fat/build.gradle
Labels: CLA Signed

#27418 Servlet61 Clarify HttpServletMapping getMatchValue
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletRequest40.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61HTTPServletMappingTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_HttpServletMappingTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_HttpServletMappingTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/HTTPServletMappingTest.war/src/getmapping/servlets/GetMappingServlet.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27458 Fix web-app 6.1 schema issues
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/internal/WebFragmentsInfoImpl.java
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/PlatformVersion.java
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-fragment_6_1.xsd
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/web/WebFragment.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/web/WebFragmentTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/web/WebFragmentTestBase.java
Labels: team:Zombie Apocalypse, CLA Signed

#27379 Add ServiceCaller to kernel service to be a common OSGi util class
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ServiceCaller.java
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/src/io/openliberty/microprofile/reactive/messaging30/internal/OLReactiveMessaging30Extension.java
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/OpenTelemetryProducer.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/helpers/OSGIHelpers.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
Labels: CLA Signed

#27454 disable on java 21
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent129Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
Labels: noproductcode, CLA Signed

#27478 Stop producing empty poms for command jars
  dev/com.ibm.ws.appclient.boot.ws-client/bnd.bnd
  dev/com.ibm.ws.config.schemagen.schemagen/bnd.bnd
  dev/com.ibm.ws.jaxws.tools.wsgen/bnd.bnd
  dev/com.ibm.ws.kernel.boot.ws-launch/bnd.bnd
  dev/com.ibm.ws.kernel.boot.ws-server/bnd.bnd
  dev/com.ibm.ws.kernel.feature.featurelist/bnd.bnd
  dev/io.openliberty.xmlBinding.3.0.internal.tools.schemagen/bnd.bnd
  dev/io.openliberty.xmlBinding.3.0.internal.tools.xjc/bnd.bnd
Labels: CLA Signed

#27474 Qualifier attribute comparisons and qualifiers in web deployment descriptor
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithTransactionContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithoutLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/src/concurrent/cdi/web/WithoutTransactionContext.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ContextServiceBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedScheduledExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/QualifierProxy.java
Labels: team:Zombie Apocalypse, CLA Signed

#27480 More updates for Java security enablement with EE 11 features
  dev/fattest.simplicity/src/componenttest/rules/repeater/JakartaEE11Action.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed, team:Performance, jakartaEE11

#27479 Clean up OSGi use of CDIService
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ServiceCaller.java
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/src/io/openliberty/microprofile/reactive/messaging30/internal/OLReactiveMessaging30Extension.java
  dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/AbstractWithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/OpenTelemetryProducer.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/transformed.bnd
Labels: CLA Signed

#27429 Update TCKResultsWriter to generate a separate file for each repeat
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
Labels: noproductcode, CLA Signed

#27447 Remove app bound vendor metrics during application shutdown
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/GrpcMetricsTest.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/ApplicationListener.java
  dev/com.ibm.ws.microprofile.metrics.2.0/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/ApplicationListener.java
  dev/com.ibm.ws.microprofile.metrics/src/com/ibm/ws/microprofile/metrics/impl/MetricRegistryImpl.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/internal/ApplicationListener50.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/ApplicationListener30.java
  dev/io.openliberty.microprofile.metrics.internal.3.0/src/io/openliberty/microprofile/metrics30/internal/impl/MetricRegistry30Impl.java
Labels: CLA Signed

#27446 Fix cache tests due to infrastructure issues
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
Labels: noproductcode, CLA Signed

#27481 use service caller for OSGi
  dev/com.ibm.websphere.rest.handler/src/com/ibm/wsspi/rest/config/ConfigBasedRESTHandler.java
Labels: CLA Signed

#27419 Update to Felix SCR 2.2.10
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.apache.felix.scr/.classpath
  dev/com.ibm.ws.org.apache.felix.scr/bnd.bnd
  dev/com.ibm.ws.org.apache.felix.scr/src/org/apache/felix/scr/impl/Activator.java
  dev/com.ibm.ws.org.apache.felix.scr/src/org/apache/felix/scr/impl/manager/DependencyManager.java
Labels: CLA Signed

#27486 Enable pb.yml pipeline on #build keyword
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed

#27392 Reuse WebDriver in Faces Selenium Tests
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22APARSeleniumTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFCompELTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CommandScriptTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23EvalScriptsTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23WebSocketTests.java
  dev/com.ibm.ws.jsf.2.3_fat/test-applications/ConverterValidatorBehaviorInjectionTarget.war/resources/WEB-INF/beans.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#27489 Reduce trace - remove channelfw trace
  dev/com.ibm.ws.security.saml.sso_fat.2/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.2.missingMetaData/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.2/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.2/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.3/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.3/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.shibboleth/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config.mapToUserRegistry/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config.2/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.config/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.endpoint.samlmetadata/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.config.rs/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.config.sp/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.merged_sp_rs/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.rs/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.jaxrs.sp/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout/publish/servers/com.ibm.ws.security.saml.sso_fat.logout.server2/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat.logout/publish/servers/com.ibm.ws.security.saml.sso_fat.logout/bootstrap.properties
  dev/com.ibm.ws.security.saml.sso_fat/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat/bootstrap.properties
Labels: noproductcode, test debt, CLA Signed, team:Security SSO, In Progress

#27390 add fallback to get oidc config from id token iss for bcl
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogout.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutService.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilder.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelperTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutServiceTest.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilderTest.java
Labels: CLA Signed

#27484 Allow expected FFDC for RM tests which interact with MP metrics
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/metrics/MetricsTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/metrics/MultiAppMetricsTest.java
  dev/io.openliberty.microprofile.reactive.messaging30.internal_fat_tck/fat/src/io/openliberty/microprofile/reactive/messaging30/tck/ReactiveMessagingTCKLauncher.java
Labels: noproductcode, CLA Signed

#27425 Update to the M16 version for Expression Language 6.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.jakarta.expressionLanguage.6.0/src/jakarta/el/CompositeELResolver.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27512 Fix memory leak in CXF caused by large number of PidInfo objects: Issue 27294
  dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/ConduitConfigurer.java
  dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/ConduitConfigurer.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/http/osgi/ConfigAdminHttpConduitConfigurer.java
Labels: CLA Signed

#27510 qualifiers on context-service definition in application xml
  dev/com.ibm.ws.concurrent_fat_cdi/.classpath
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/context/location/Location.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/context/location/LocationContextProvider.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/context/location/LocationContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/context/location/LocationContextSnapshot.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ClearingAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/IgnoringTransactionContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/PropagatingLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/Unrecognized.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithTransactionContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithoutAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithoutLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/WithoutTransactionContext.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactories.java
Labels: team:Zombie Apocalypse, CLA Signed

#27495 Added a wait for application start message in MPHealth31 FAT
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckTest.java
Labels: noproductcode, CLA Signed

#27504 Add doPriv to calls to ServiceCaller
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ServiceCaller.java
Labels: CLA Signed

#27511 Update tx recovery log timestamp at assert open
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#27514 Increase EJB timer FAT delay tolerance
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed
