Repository OpenLiberty/open-liberty, pull requests merged in 2024-08, with the labels that each got.

#29247 Skip testSortByVersionFunction on postgresql
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29246 FIx and update Oracle trace testing
  dev/com.ibm.ws.jdbc_fat/fat/src/com/ibm/ws/jdbc/fat/tests/ConfigTest.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleCheckpointTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTraceTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ssl/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.trace/bootstrap.properties
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ucp/bootstrap.properties
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29238 Delete SingleJson.json file after automated build
  dev/com.ibm.websphere.appserver.features/build.gradle
Labels: noproductcode, CLA Signed

#29244 Don't override ABORTED
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATParticipant.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.1/fat/src/tests/MultiRecoveryTest.java
Labels: CLA Signed

#29254 Update FT TCK to 4.1-RC4 and enable tests
  dev/io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: noproductcode, CLA Signed

#29257 Add a few more filters on test packages
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#26450 Add headers to scim-2.0 responses
  dev/com.ibm.ws.security.wim.scim.2.0/src/com/ibm/ws/security/wim/scim20/rest/SCIMRESTHandler.java
Labels: CLA Signed

#29255 small thread pool on startup for better large config start performance
  dev/com.ibm.ws.threading/bnd.bnd
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ExecutorServiceImpl.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
  dev/com.ibm.ws.threading/test/com/ibm/ws/threading/internal/ExecutorServiceImplTest.java
Labels: CLA Signed, team:Performance, performance

#28392 Prepare CHIPs for GA
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.op/jvm.options
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rp/jvm.options
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.op/jvm.options
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/servers/com.ibm.ws.security.social_fat.LibertyOP.social/jvm.options
  dev/com.ibm.ws.session/bnd.bnd
  dev/com.ibm.ws.session/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionManagerConfig.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionProperties.java
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/cookies/CookieUtils.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/CookieData.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/genericbnf/KeyMatcher.java
  dev/com.ibm.ws.webcontainer.cors/bnd.bnd
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitioned/jvm.options
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/session/impl/SessionAffinityManagerImpl.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WebContainerRequestState.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60CookieSetAttributeTest.java
Labels: in:Transport, in:Web Components, ID Required, CLA Signed, team:Sirius

#29285 Remove source folder config for feature visibility folders
  dev/com.ibm.websphere.appserver.features/.classpath
Labels: noproductcode, CLA Signed

#29264 idea for test bucket to run ddlgen output
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_ddlgen/.classpath
  dev/io.openliberty.data.internal_fat_ddlgen/.project
  dev/io.openliberty.data.internal_fat_ddlgen/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_ddlgen/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_ddlgen/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_ddlgen/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_ddlgen/bnd.bnd
  dev/io.openliberty.data.internal_fat_ddlgen/build.gradle
  dev/io.openliberty.data.internal_fat_ddlgen/fat/src/test/jakarta/data/ddlgen/DDLGenTest.java
  dev/io.openliberty.data.internal_fat_ddlgen/fat/src/test/jakarta/data/ddlgen/FATSuite.java
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/bootstrap.properties
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/server.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/resources/WEB-INF/ibm-web-bnd.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Part.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Parts.java
Labels: team:Zombie Apocalypse, CLA Signed

#28327 Clarify the scope of the webAppSecurity attributes
  dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed, team:Core Security, L2 ReviewNotRequired

#29208 Skip adding Attributes for HTTP Metrics for OpenTelemery if not present
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
Labels: CLA Signed

#29281 map os type in the same way as OsResource
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ResourceServlet.java
Labels: noproductcode, CLA Signed

#29283 Ensure some tests run
  dev/com.ibm.ws.transaction.cloud_fat.db2.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
Labels: noproductcode, CLA Signed

#29282 Versionless Caching tests pass on non-linux operating systems
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessCachingTest.java
Labels: noproductcode, CLA Signed

#29295 stop servers after test
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessJavaEEToMicroProfileTest.java
Labels: noproductcode, CLA Signed

#29268 Clean up Servlet 3.1 FAT test classes
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/CDIUpgradeHandlerTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/PrivateHeaderTest.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#29270 Jakarta Data recreate bug fix
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#29291 Fix test bug when java.version = 23-ea
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, Java 23

#29141 re-enable request timing metrics
  dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
Labels: noproductcode

#29214 Increase slow threshold to resolve any slow test issues, we're not te…
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/LibertyMetricServer/server.xml
Labels: noproductcode, CLA Signed

#29294 virtual true not ignored for ManagedThreadFactoryDefinition on Java 17
  dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29302 Ignore start failure when test has already passed
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTest2.java
Labels: noproductcode, CLA Signed

#29248 remove logging created for constant pool bug
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.org.jboss.weld/bnd.bnd
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/FileLogger.java
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/server.env
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/servers/FaultTolerance40TCKServer/bootstrap.properties
  dev/io.openliberty.org.jboss.weld4/bnd.bnd
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/FileLogger.java
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
Labels: CLA Signed

#29300 detecting version attribute
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Part.java
Labels: team:Zombie Apocalypse, CLA Signed

#29293 29288 wadlgenerator
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
Labels: in:JAX-RS, CLA Signed

#29304 Issue #29303 : NPE check in PauseableComponentQuiesceListener.java
  dev/com.ibm.ws.runtime.update/src/com/ibm/ws/runtime/update/internal/PauseableComponentQuiesceListener.java
Labels: CLA Signed

#29305 Avoid re-activation of CacheServiceImpl when the server config is updated after checkpoint
  dev/io.openliberty.checkpoint_fat_jcache_hazelcast/fat/src/io/openliberty/checkpoint/jcache/fat/JCacheProviderInAppTest.java
  dev/io.openliberty.checkpoint_fat_jcache_hazelcast/publish/servers/io.openliberty.jcache.internal.fat.provider.in.app.1/server.env
  dev/io.openliberty.checkpoint_fat_jcache_hazelcast/publish/servers/io.openliberty.jcache.internal.fat.provider.in.app.1/server.xml
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/Activator.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CachingProviderService.java
Labels: CLA Signed

#29210 Faces 4.1 Update Schemas
  dev/com.ibm.ws.javaee.dd.common/src/com/ibm/ws/javaee/dd/PlatformVersion.java
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-facelettaglibrary_4_1.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-facesconfig_4_1.xsd
  dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/web-partialresponse_4_1.xsd
  dev/com.ibm.ws.javaee.dd/src/com/ibm/ws/javaee/dd/jsf/FacesConfig.java
  dev/com.ibm.ws.javaee.ddmodel/src/com/ibm/ws/javaee/ddmodel/jsf/FacesConfigDDParser.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppHeaderTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppTest.java
  dev/com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppTestBase.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29310 Ignore start failure when test has already passed
  dev/com.ibm.ws.transaction.recovery_fat.3/fat/src/tests/WaitForRecoveryTest.java
Labels: noproductcode, CLA Signed

#29271 29253 Refactor info factory
  dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/info/package-info.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/rest/rest/client/user/MessageAndRestClientTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/info/package-info.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/config/OpenTelemetryVersionedConfigurationImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/info/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryFFDC/server.xml
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/OpenTelemetryProducer.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/constants/OpenTelemetryConstants.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryLifecycleManager.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryPropertiesReader.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemtryLifecycleManagerImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/transformed.bnd
Labels: CLA Signed

#28051 Remove noship-1.0 from tested.features in com.ibm.ws.javaee.ddmodel_fat
  dev/com.ibm.ws.javaee.ddmodel_fat/bnd.bnd
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#29322 requirements around primary entity
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/validation/EntityValidatorImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/People.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#29261 Set and export JAVA_HOME when not set.
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
Labels: CLA Signed

#29048 SameSite=None Incompatible Clients implementation and FAT Tests
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/cookies/SameSiteCookieUtils.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/http/channel/test/api/SameSiteCookieUtilsTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/.classpath
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/bnd.bnd
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteIncompatibleClientsTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_incompatible/bootstrap.properties
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_incompatible/jvm.options
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_incompatible/server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/test-applications/IncompatibleClientTest.war/src/incompatible/servlets/IncompatibleClientServlet.java
Labels: in:Transport, CLA Signed, team:Sirius

#29324 Add java 2 security permission to OpenTracing 2.0 FAT
  dev/io.openliberty.opentracing.2.x_fat/publish/servers/opentracingFATServer1/server.xml
  dev/io.openliberty.opentracing.2.x_fat/publish/servers/opentracingFATServer2/server.xml
  dev/io.openliberty.opentracing.2.x_fat/publish/servers/opentracingFATServer3/server.xml
  dev/io.openliberty.opentracing.2.x_fat/publish/servers/opentracingFATServer4/server.xml
Labels: noproductcode, CLA Signed

#29301 Subject is readOnly error is thrown in a race condition
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorHelper.java
Labels: CLA Signed

#29328 wait for GC before looking for metrics
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/spanTest/TestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/MetricsOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/otelCollector/OtelCollectorQueryClient.java
Labels: noproductcode, CLA Signed

#29330 updates per review of version attribute detection
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Part.java
Labels: team:Zombie Apocalypse, CLA Signed

#29320 remove custom features from baseline singleton resolution tests
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected_WL.xml
Labels: noproductcode, CLA Signed

#29336 require PageRequest for CursoredPage
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#29317 check only public features when running baseline tests
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/VerifyDelta.java
Labels: CLA Signed

#29053 Add FAT to verify faces-config.xml with 4.1 version causes no error
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/fat/src/io/openliberty/org/apache/myfaces41/fat/test/FacesConfigVersion41Test.java
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_FacesConfigVersion_41_Server/bootstrap.properties
  dev/io.openliberty.org.apache.myfaces.4.1_fat/publish/servers/faces41_FacesConfigVersion_41_Server/server.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/FacesConfigVersion41.war/resources/WEB-INF/faces-config.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/SetResponseContentLengthLong_Spec1829.war/resources/WEB-INF/web.xml
  dev/io.openliberty.org.apache.myfaces.4.1_fat/test-applications/rowStatePreserved_Spec1263.war/resources/WEB-INF/web.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#29318 Extra trace for wait timeout
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATParticipant.java
Labels: CLA Signed

#29309 Add Java 23 specific FAT test
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java23Test.java
  dev/io.openliberty.java.internal_fat/publish/servers/java23-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java23-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java23-server/server.xml
  dev/io.openliberty.java.internal_fat/src-reference/java17/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java18/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java19/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java20/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java21/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java22/module-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java23/io/openliberty/java/internal/TestApp.java
  dev/io.openliberty.java.internal_fat/src-reference/java23/io/openliberty/java/internal/TestService.java
  dev/io.openliberty.java.internal_fat/src-reference/java23/io/openliberty/java/internal/package-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java23/module-info.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 23

#29343 Revert "29288 wadlgenerator"
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
Labels: CLA Signed

#29203 update to get oidc provider without accessing request parameter or header
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/MultiServerBCLTests.java
Labels: CLA Signed

#29191 Allow mpTelemetry-2.0 to work with Java 8
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/io.openliberty.http.monitor/.classpath
  dev/io.openliberty.http.monitor/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.io.opentelemetry.2.0/.classpath
  dev/io.openliberty.io.opentelemetry.2.0/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.io.opentelemetry.2.0/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/agent/AgentTestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/spanTest/TestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerBaseTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/MetricsOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/otelCollector/OtelCollectorQueryClient.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/publish/files/otel-collector-config-metrics.yaml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAloneTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/customizer/CustomizerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/exporter/ExporterTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/PropagatorTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/TestPropagator.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/resource/ResourceTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/sampler/SamplerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/MetricsDisabledServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.classpath
  dev/io.openliberty.microprofile.telemetry.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/connpool/MPTelemetryConnectionPoolMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/.classpath
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/.classpath
  dev/io.openliberty.microprofile.telemetry.internal.common/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/AbstractWithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.classpath
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
  dev/io.openliberty.microprofile.telemetry.monitor.internal/.classpath
  dev/io.openliberty.microprofile.telemetry.monitor.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.monitor.internal/bnd.bnd
Labels: CLA Signed

#29346 Config runtime ignores metrics
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigRuntimeModeIgnoresMPConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10IgnoreMPConfig/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10IgnoreMPConfig/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10IgnoreMPConfig/server.xml
Labels: CLA Signed

#29274 Backport HTTP Metrics support for mpTelemetry-2.0 until JEE7
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.servlet3.1-monitor1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.servlet5.0-monitor1.0.feature
  dev/com.ibm.ws.jaxrs.2.x.monitor/src/com/ibm/ws/jaxrs/monitor/JaxRsMonitorFilter.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/microprofile_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/microprofile_expected_WL.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/platform_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/platform_expected_WL.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/singleton_expected_WL.xml
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor/original.bnd
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/Servlet4Helper.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletContainerInitializer.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.http.monitor/transformed.bnd
  dev/io.openliberty.http.monitor_fat/bnd.bnd
  dev/io.openliberty.http.monitor_fat/build.gradle
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerNoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerRestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/NoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/RestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerServletServer/server.xml
  dev/io.openliberty.http.monitor_fat/publish/servers/JSPServer/server.xml
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleRestServer/server.xml
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleServletServer/server.xml
  dev/io.openliberty.http.monitor_fat/test-applications/JspApp/resource/WEB-INF/web.xml
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/ApplicationResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/FailResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/ParamsResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/RestApp/src/io/openliberty/http/monitor/fat/restApp/SimpleResource.java
  dev/io.openliberty.http.monitor_fat/test-applications/ServletApp/src/io/openliberty/http/monitor/fat/servletApp/FailServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/ServletApp/src/io/openliberty/http/monitor/fat/servletApp/SimpleServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/RootWildCardServlet.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/SubWildCard1.java
  dev/io.openliberty.http.monitor_fat/test-applications/WildCardServletApp/src/io/openliberty/http/monitor/fat/wildCardServletApp/SubWildCard2.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/original.bnd
Labels: CLA Signed

#29326 Logging container fat
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.project
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULDuplicateTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULLogServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/TestUtils.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/FFDCSourceServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/allJULSources.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/allSourcesServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/config.yaml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/traceSourceServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/resources/META-INF/microprofile-config.properties
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryAgentJULMessages/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryAgentJULMessages/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryAgentJULMessages/server.env
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryAgentJULMessages/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryLogsServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryLogsServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryLogsServer/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/MpTelemetryLogApp/FFDCServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/MpTelemetryLogApp/LogServlet.java
Labels: noproductcode, CLA Signed

#29352 Fix `TelemetryAttributesTest`
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAttributesTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ResourceServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/permissions-TelemetryAttributesTest.xml
Labels: noproductcode, CLA Signed

#29359 Add telemetry metrics api tests
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/metricTest/TestApplication.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/apps/metricTest/TestResource.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JvmMetricsOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/MetricsApiOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
Labels: noproductcode, CLA Signed

#29325 Update OpenTelemetry sdk version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.opentelemetry.2.0/bnd.bnd
  dev/io.openliberty.microprofile.faulttolerance.telemetry/bnd.bnd
Labels: CLA Signed

#29333 Add some CHIPs tests to FULL mode
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/tests/WCPartitionedAttributeTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#29354 Improve arquillian error messages for Data TCK
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/pom.xml
Labels: enhancement, noproductcode, CLA Signed

#29356 Versionless: Filter compatibility features added to packaging
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: in:Kernel/Bootstrap, CLA Signed, Versionless

#29339 Remove unnecessary attribute as per UFO review and gate keep logic wh…
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/MonitorAppStateListener.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletFilter.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/helper/Constants.java
  dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/MPMetricsHTTPMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
Labels: CLA Signed

#29040 Fix StackOverflowError in Resteasy code augmented with Liberty Trace
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common.ee11/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: CLA Signed

#29349 Create a test for HTTP metrics when OTel is in runtime mode
  dev/fattest.simplicity/src/componenttest/rules/repeater/MicroProfileActions.java
  dev/io.openliberty.http.monitor_fat/bnd.bnd
  dev/io.openliberty.http.monitor_fat/build.gradle
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerNoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerRestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
  dev/io.openliberty.http.monitor_fat/publish/files/config.yaml
  dev/io.openliberty.http.monitor_fat/publish/resources/META-INF/microprofile-config.properties
Labels: noproductcode, CLA Signed

#29357 emit warning if runtime and app mode explicitly disagree
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigRuntimeModeIgnoresMPConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryGlobalOpenTelemetryTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10IgnoreMPConfig/server.xml
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/resources/io/openliberty/microprofile/telemetry/internal/common/resources/MPTelemetry.nlsprops
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryPropertiesReader.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemtryLifecycleManagerImpl.java
Labels: ID reviewed, CLA Signed

#29373 Adding additional test
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetrySourcesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/invalidAndValidSources.xml
Labels: noproductcode, CLA Signed

#29082 Telemetry shim test
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryShimTest.java
Labels: CLA Signed

#29371 29370 unknown service
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/Constants.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerRestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/RuntimeInstanceServlet.java
  dev/io.openliberty.microprofile.telemetry.internal.common/resources/io/openliberty/microprofile/telemetry/internal/common/resources/MPTelemetry.nlsprops
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/constants/OpenTelemetryConstants.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/DisposedOpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/LibertyMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/SessionMetricsTest.java
Labels: ID reviewed, CLA Signed

#29375 Fix issues with checkpoint tests in FAT
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceTest.java
Labels: noproductcode, CLA Signed

#29365 Add javaPermission to OpenTracing 1.x FAT
  dev/com.ibm.ws.opentracing.1.x_fat/publish/servers/opentracingFATServer1/server.xml
  dev/com.ibm.ws.opentracing.1.x_fat/publish/servers/opentracingFATServer2/server.xml
  dev/com.ibm.ws.opentracing.1.x_fat/publish/servers/opentracingFATServer3/server.xml
  dev/com.ibm.ws.opentracing.1.x_fat/publish/servers/opentracingFATServer4/server.xml
Labels: noproductcode, CLA Signed

#29368 ensure safe type conversions
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Items.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Demographics.java
Labels: team:Zombie Apocalypse, CLA Signed

#29345 29288 wadlgenerator
  dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
  dev/com.ibm.ws.jaxrs.2.0.common/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2/src/org/apache/cxf/jaxrs/model/wadl/WadlGenerator.java
Labels: in:JAX-RS, CLA Signed

#29183 JAX-WS: Add beta enableDefaultValidation metatype
  dev/com.ibm.ws.jaxws.2.3.common/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.jaxws.2.3.common/resources/OSGI-INF/metatype/metatype.xml
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#29382 Issue #29381: update Yoko to fix IOR trace bug
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.org.apache.yoko.corba.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.core/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.osgi/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.impl/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.rmi.spec/bnd.bnd
  dev/com.ibm.ws.org.apache.yoko.util/bnd.bnd
Labels: CLA Signed

#29380 Disable telemetry monitor jdbc test on Java 8
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
Labels: noproductcode, CLA Signed

#29393 Telemetry fat repeats
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/MpTelemetryLogApp/FFDCServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/MpTelemetryLogApp/LogServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryAgentJULMessagesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryApplicationConfigTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetrySourcesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TestUtils.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/allSources.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/emptySource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/invalidSource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/messageSource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/noSource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/files/noTelemetryAttribute.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAgentJULMessages/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAgentJULMessages/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAgentJULMessages/server.env
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAgentJULMessages/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAppConfig/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryDropins/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryFFDC/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryMessage/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetrySources/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryTrace/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/fat/MpTelemetryLogApp/AccessServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/fat/MpTelemetryLogApp/ExtensionServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/fat/MpTelemetryLogApp/LogServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/fat/MpTelemetryLogApp/MpTelemetryServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/MpTelemetryLogApp/src/io/openliberty/microprofile/telemetry/logging/internal/fat/MpTelemetryLogApp/TraceServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/ffdc-servlet/src/io/openliberty/microprofile/telemetry/logging/internal/fat/ffdc/servlet/FFDCInInitServlet.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/test-applications/ffdc-servlet/src/io/openliberty/microprofile/telemetry/logging/internal/fat/ffdc/servlet/FFDCServlet.java
Labels: noproductcode, CLA Signed

#29384 fix os.type value for z/os
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/ResourceServlet.java
Labels: noproductcode, CLA Signed

#29404 Add doPriv for classloading
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
Labels: CLA Signed

#29363 Update Expression Language 6.0 to M24
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_cs.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_de.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_es.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_fr.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_hu.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_it.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_ja.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_ko.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_pl.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_pt_BR.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_ro.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_ru.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_zh.properties
  dev/io.openliberty.jakarta.expressionLanguage.6.0/resources/jakarta/el/LocalStrings_zh_TW.properties
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29374 Update beans.xml to 4.1
  dev/io.openliberty.org.apache.myfaces.4.1/src/META-INF/beans.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29391 Remove beta metadata from platform element
  dev/com.ibm.ws.kernel.feature/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Signed

#29400 SELECT clause on its own
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Products.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Demographics.java
Labels: team:Zombie Apocalypse, CLA Signed

#29405 Update metadata.props description for platform
  dev/com.ibm.ws.kernel.feature/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed

#29337 Add cpu-util to Liberty startup thread pool hang consideration
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
Labels: CLA Signed

#29415 update keystores for jcache checkpoint tests and disable hnv
  dev/io.openliberty.checkpoint_fat_jcache_hazelcast/publish/shared/resources/security/keystore.p12
  dev/io.openliberty.checkpoint_fat_jcache_hazelcast/publish/shared/resources/security/truststore.p12
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/server.xml
Labels: noproductcode, CLA Signed

#29417 Fix DerbyRA Checkpoint test failure
  dev/com.ibm.ws.jca_fat_derbyra/fat/src/com/ibm/ws/jca/fat/derbyra/DerbyRACheckpointLimitationsTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: team:Zombie Apocalypse, noproductcode, test bug

#29419 Refactored testHungRequestTiming test in RequestTiming FAT
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestTiming.java
Labels: noproductcode, CLA Signed

#29426 Use jdbc-4.2 for `ConnectionPoolMetricTest`
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/ConnectionPoolMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/LibertyMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/fat/src/io/openliberty/microprofile/telemetry/internal/monitor_fat/SessionMetricsTest.java
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/ConnPoolMetricsServer/server.xml
Labels: noproductcode, CLA Signed

#29433 ignore hnv warnings for hnv disabled in checkpoint fat
  dev/io.openliberty.checkpoint_fat_persistence/fat/src/io/openliberty/checkpoint/fat/DB2Test.java
Labels: noproductcode, CLA Signed

#29406 Fix additional tests that cannot handle java.version = 23-ea
  dev/com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, Java 23

#29278 Set CDI's application TCCL during shutdown events
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/io.openliberty.cdi.4.0.internal_fat/bnd.bnd
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/StartupEventsTest.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/ear/war/StartupEventsServlet.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/AbstractObserver.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/LoggedTest.java
  dev/io.openliberty.cdi.4.0.internal_fat/fat/src/io/openliberty/cdi40/internal/fat/startupEvents/sharedLib/TestLoggingObserver.java
  dev/io.openliberty.cdi.4.0.internal_fat/publish/servers/StartupEventsServer/server.xml
Labels: CLA Signed

#27428 Update osgi.contract version to 6.0.0 and name to JakartaExpressionLanguage
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi4.1-servlet6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appSecurity-6.0/io.openliberty.appSecurity-6.0.feature
  dev/io.openliberty.cdi.4.0.internal.web/bnd.bnd
  dev/io.openliberty.cdi.4.1.internal.web/.classpath
  dev/io.openliberty.cdi.4.1.internal.web/.gitignore
  dev/io.openliberty.cdi.4.1.internal.web/.project
  dev/io.openliberty.cdi.4.1.internal.web/.settings/bndtools.core.prefs
  dev/io.openliberty.cdi.4.1.internal.web/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.cdi.4.1.internal.web/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.cdi.4.1.internal.web/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.cdi.4.1.internal.web/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.security.jakartasec.3.0.internal/bnd.bnd
  dev/io.openliberty.security.jakartasec.4.0.internal/.classpath
  dev/io.openliberty.security.jakartasec.4.0.internal/.gitignore
  dev/io.openliberty.security.jakartasec.4.0.internal/.project
  dev/io.openliberty.security.jakartasec.4.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.security.jakartasec.4.0.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.security.jakartasec.4.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.security.jakartasec.4.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.security.jakartasec.4.0.internal/bnd.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29422 JDQL processing updates and more test permutations for count queries
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipt.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
Labels: team:Zombie Apocalypse, CLA Signed

#29436 In the connectionpool.monitor bundle we directly update histograms wi…
  dev/com.ibm.ws.connectionpool.monitor/bnd.bnd
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/ws/connectionpool/monitor/metrics/MetricsManager.java
Labels: CLA Signed

#29401 Moving ESA parse - compare json tests to OL
  dev/cnf/oss_ibm.maven
  dev/com.ibm.ws.repository.parsers/.classpath
  dev/com.ibm.ws.repository.parsers/bnd.bnd
  dev/com.ibm.ws.repository.parsers/build.gradle
  dev/com.ibm.ws.repository.parsers/test-resources/esa/.gitignore
  dev/com.ibm.ws.repository.parsers/test-resources/esa/esaJsonOnly/com.ibm.websphere.appserver.anno-1.0.esa.json
  dev/com.ibm.ws.repository.parsers/test-resources/esa/esaJsonOnly/com.ibm.websphere.appserver.jsp-2.3.esa.json
  dev/com.ibm.ws.repository.parsers/test-resources/reference/com.ibm.websphere.appserver.anno-1.0.esa.json
  dev/com.ibm.ws.repository.parsers/test-resources/reference/com.ibm.websphere.appserver.jsp-2.3.esa.json
  dev/com.ibm.ws.repository.parsers/test/com/ibm/ws/repository/parsers/internal/CreateJsonRepositoryFilesTest.java
  dev/com.ibm.ws.repository.test.utils/bnd.bnd
  dev/com.ibm.ws.repository.test.utils/src/com/ibm/ws/repository/base/JsonAnyOrderMatcher.java
Labels: team:Zombie Apocalypse, CLA Signed

#29296 Return a consistent status code 404 for non-existing static resources
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/extension/DefaultExtensionProcessor.java
Labels: in:Web Components, CLA Signed, team:Sirius

#29434 CDI: Fix deserialization of HttpSession bean
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/FATSuite.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/session/CDISessionPersistenceTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/session/app/CDISessionPersistenceServlet.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/session/app/MySessionBean.java
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdiSessionPersistenceServer/bootstrap.properties
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdiSessionPersistenceServer/server.xml
  dev/com.ibm.ws.org.jboss.weld/bnd.overrides
  dev/com.ibm.ws.org.jboss.weld3/bnd.overrides
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/bnd.template
  dev/io.openliberty.org.jboss.weld5/check-me-in-if-i-change.bnd
  dev/io.openliberty.org.jboss.weld6/bnd.template
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#29451 Remove Java 8 settings from bnd files since it is the configured default
  dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/opentracing.mock11.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/opentracing.mock12.bnd
  dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/opentracing.mock13.bnd
  dev/com.ibm.ws.microprofile.opentracing_fat_tck/opentracing.mock.bnd
  dev/com.ibm.ws.opentracing.1.x_fat/opentracing.mock11.bnd
  dev/com.ibm.ws.opentracing.1.x_fat/opentracing.mock12.bnd
  dev/com.ibm.ws.opentracing.1.x_fat/opentracing.mock13.bnd
  dev/com.ibm.ws.opentracing_fat/opentracing.mock.bnd
  dev/io.openliberty.http.monitor/bnd.bnd
  dev/io.openliberty.http.monitor_fat/bnd.bnd
  dev/io.openliberty.io.opentelemetry.2.0/bnd.bnd
  dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/opentracing.mock.2.0.bnd
  dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/opentracing.mock.3.0.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.monitor.internal/bnd.bnd
  dev/io.openliberty.opentracing.2.x_fat/opentracing.mock20.bnd
  dev/io.openliberty.opentracing.3.x_fat/opentracing.mock30.bnd
Labels: CLA Signed, team:Performance

#29232 Automate Validation 3.1 TCK
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.classpath
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.project
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.settings/org.eclipse.buildship.core.prefs
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/README.md
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/FATSuite.java
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/ValidationTckLauncher.java
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/features/io.openliberty.valThirdParty-3.1.mf
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/servers/ValidationTCKServer/bootstrap.properties
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/servers/ValidationTCKServer/jvm.options
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/servers/ValidationTCKServer/server.xml
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/logging.properties
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
Labels: noproductcode, CLA Signed

#29442 Update body field with exception type when FFDC event message is null
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULDuplicateTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULLogServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/MpTelemetryLogMappingUtils.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesTest.java
Labels: CLA Signed

#29418 Generate artifactory auth token for docker instead of pulling a shared token
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistry.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryRegistryTest.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29394 Changes to deliver EclipseLink Snapshot 5.0.0-20240820
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
Labels: CLA Signed

#29449 Add the ConsoleLogRecordExporterProvider to mpTelemetry-2.0
  dev/io.openliberty.io.opentelemetry.2.0/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.logs.ConfigurableLogRecordExporterProvider
  dev/io.openliberty.io.opentelemetry.2.0/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.metrics.ConfigurableMetricExporterProvider
  dev/io.openliberty.io.opentelemetry.2.0/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20LogsConfigTCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20MetricsConfigTCKServer/bootstrap.properties
Labels: CLA Signed

#29458 Revert "Return a consistent status code 404 for non-existing static resources"
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/extension/DefaultExtensionProcessor.java
Labels: in:Web Components, team:Sirius

#29424 Pause Infinispan testing until it supports Java 23+ (300615)
  dev/com.ibm.ws.session.cache_fat_config_infinispan/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheConfigUpdateTest.java
  dev/com.ibm.ws.session.cache_fat_config_infinispan/fat/src/com/ibm/ws/session/cache/config/fat/infinispan/SessionCacheErrorPathsTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/bnd.bnd
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/FATSuite.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTwoServerTimeoutTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 23

#29446 Remove beta guard from MpTelemetry 2.0
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.servlet3.1-monitor1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpTelemetry-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.rest.client-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.0/io.openliberty.mpTelemetry-2.0.feature
  dev/com.ibm.ws.connectionpool.monitor/src/com/ibm/ws/connectionpool/monitor/metrics/MetricsManager.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/MonitorAppStateListener.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/ServletContainerInitializer.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/mbean/HttpServerStatsMXBean.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/servers/Telemetry20TCKServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryAgentJULMessages/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryLogsServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryAppConfig/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryDropins/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryFFDC/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryMessage/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetrySources/jvm.options
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/publish/servers/TelemetryTrace/jvm.options
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/ConnPoolMetricsServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/LibertyMetricServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/SessionsMetricsServer/jvm.options
  dev/io.openliberty.microprofile.telemetry.monitor.internal/src/io/openliberty/microprofile/telemetry/internal/monitor/MonitorMetricsHandler.java
  dev/io.openliberty.microprofile.telemetry.monitor.internal/src/io/openliberty/microprofile/telemetry/internal/monitor/internal/MonitorMetrics.java
Labels: CLA Signed

#29468 remove workaround for 28912 and 29117
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Participant.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Rating.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Part.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Demographics.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Point.java
Labels: team:Zombie Apocalypse, CLA Signed

#29466 Fix reflection of injected ServletContext
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/session/app/MySessionBean.java
  dev/io.openliberty.org.jboss.weld4/bnd.overrides
  dev/io.openliberty.org.jboss.weld5/build.gradle
  dev/io.openliberty.org.jboss.weld5/check-me-in-if-i-change.bnd
  dev/io.openliberty.org.jboss.weld6/build.gradle
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#29461 Remove MaximumJavaLevel from MP JWT 2.0 FAT TCK
  dev/io.openliberty.microprofile.jwt.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/jwt20/internal/tck/FATSuite.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29474 Fix http monitor checkpoint
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/Servlet4Helper.java
Labels: CLA Signed

#29455 Disable SASL Tests for Java versions >22
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/checkpoint/CheckpointKafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslPlainTest.java
Labels: noproductcode, CLA Signed

#29481 cursor pagination without WHERE clause
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#29482 Update projects to build with Java 17 only in Eclipse
  dev/com.ibm.ws.concurrent.persistent/src/com/ibm/ws/concurrent/persistent/internal/TaskStatusImpl.java
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.wsdl.3.2/bnd.bnd
  dev/com.ibm.ws.security.context/src/com/ibm/ws/security/context/internal/SecurityContextImpl.java
  dev/io.openliberty.checkpoint_fat_xmlws/bnd.bnd
  dev/io.openliberty.jaxws.executor_fat/bnd.bnd
Labels: CLA Signed, team:Performance

#26784 ConfigurableWABTests skip session context error
  dev/com.ibm.ws.app.manager.wab.installer_fat/fat/src/com/ibm/ws/app/manager/wab/installer/fat/ConfigurableWABTests.java
Labels: in:Web Components, noproductcode, test bug, CLA Signed, team:Sirius

#29480 Fix Missing Trailer Fields in Response
  dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/SRTServletResponse40.java
Labels: in:Web Components, CLA Signed, team:Sirius

#29476 Ensure behavior or element-collection fetch
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Rating.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Ratings.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Mobile.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/MobilePhones.java
Labels: team:Zombie Apocalypse, CLA Signed

#29492 Hopefully final PR for x.y.100 to x.(y+1) change
  dev/com.ibm.ws.artifact_fat/build-test.xml.bak
  dev/com.ibm.ws.collector.manager/build-bvt.xml.disabled
  dev/com.ibm.ws.collector/build-bvt.xml.disabled
  dev/com.ibm.ws.concurrent.persistent/build-api-spi.xml.disabled
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/custom/CustomManifest.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/custom/CustomManifestTest.java
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/noDescription/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/noFeature/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/noImplClass/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/simpleCustomEncryption/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/valid/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/simple_custom_encryption/bin/tools/extensions/ws-customPasswordEncryption/simpleCustomEncryption/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/multiple_extensions/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/no_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/no_matching_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.crypto.passwordutil/test/test_data/tool_classpath_files/one_extension/META-INF/MANIFEST.MF
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelBootstrap.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/KernelResolver.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/provisioning/ContentBasedLocalBundleRepository.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/provisioning/VersionUtility.java
  dev/com.ibm.ws.product.utility/test/com/ibm/ws/product/utility/extension/utils/TestUtils.java
Labels: CLA Signed, team:Performance

#29489 Update jcache test suite to avoid failures during assemble
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/suite/FATSuite.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29483 More logging for repeat action and test method entry and exit
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/RepeatTests.java
Labels: noproductcode, CLA Signed

#29479 Add user feature local esa install test
  dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
  dev/com.ibm.ws.install.featureUtility_fat/build.gradle
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
  dev/com.ibm.ws.install.featureUtility_fat/publish/.gitignore
Labels: CLA Signed, release bug

#29495 Test mpTelemetry 2.0 with io.openliberty.jakartaee9.internal_fat'
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9Features.java
Labels: noproductcode, CLA Signed

#29491 Jakarta Data TODOs: Converers and record entity signatures
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#29497 29496 mpmetrics overlay memory leak
  dev/io.openliberty.io.smallrye.metrics/.classpath
  dev/io.openliberty.io.smallrye.metrics/bnd.bnd
  dev/io.openliberty.io.smallrye.metrics/src/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
Labels: CLA Signed

#29490 initial set of error messages for jakarta data
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal/resources/io/openliberty/data/internal/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTestCheckpoint.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Receipts.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Customers.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29502 Add translations for OIDC client token endpoint auth methods
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
Labels: ID reviewed, CLA Signed, team:Security SSO

#29500 Used ServiceTracker to get healthService in MP Health 31+
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/servlet/HealthCheckLivenessServlet.java
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/servlet/HealthCheckReadinessServlet.java
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/servlet/HealthCheckServlet.java
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/servlet/HealthCheckStartupServlet.java
Labels: CLA Signed

#29501 Allow logs to go stale
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLog.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/HeartbeatLogManager.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
Labels: CLA Signed

#29504 BadConnectorID test wait for exception instead of immediately on server start
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/BadConnectorIDTest.java
Labels: noproductcode, CLA Signed

#29347 follow up to refactoring
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryPropertiesReader.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemtryLifecycleManagerImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
Labels: CLA Signed

#29454 Rtc301434 split tel fat buckets to avoid timeouts
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/suite/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent129Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent210Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerLegacyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerOtlpTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerSecureOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerSecureOtlpTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JvmMetricsOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/MetricsApiOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/TracingNotEnabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegrationWithConcurrency.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/MultiThreadedContextTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/Telemetry10.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAPITest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryAttributesTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryBeanTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvOnlyTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigNullTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigRuntimeModeIgnoresMPConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigServerVarTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigSystemPropTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryDisabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryGlobalOpenTelemetryTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLoggingExporterTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryLongRunningTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryRuntimeInstanceTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServiceNameTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryServletTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryShimTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetrySpiTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryWithSpanErrorTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryApplicationConfigTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryMessagesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetrySourcesTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceCheckpointTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryTraceTest.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
Labels: noproductcode, CLA Signed

#29515 Fix errors in settings that affect eclipse
  dev/com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1/bnd.bnd
  dev/com.ibm.ws.repository.parsers/.classpath
Labels: CLA Signed, team:Performance

#29511 Add sessions attributes to avoid invalidation issue with MP Metrics 3.0 FAT
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/BadHistogramTimer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/DefaultBucketServer/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/HistogramConfig/server.xml
  dev/io.openliberty.microprofile.metrics.internal.3.0_fat/publish/servers/TimerConfig/server.xml
Labels: noproductcode, CLA Signed

#29516 Change to use ConcurrentHashMap instead of ReadWriteLock
  dev/com.ibm.ws.logging.core/src/com/ibm/websphere/logging/hpel/LogRecordContext.java
Labels: CLA Signed, team:Performance, Java 22, Java 23

#29514 Fix EJB Timer FAT verification
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#29512 Wait for SSL to start to avoid issues with windows locking for security setup
  dev/io.openliberty.microprofile.metrics.internal.5.1_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/LibraryRefTest.java
Labels: noproductcode, CLA Signed

#29485 update auto-feature for mpOpenAPI 4
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationConfigSchema-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationValidatorSchema-3.0.feature
  dev/com.ibm.ws.rest.handler.config_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
  dev/io.openliberty.rest.handler.config.openapi.2.0/bnd.bnd
  dev/io.openliberty.rest.handler.validator.openapi.2.0/bnd.bnd
Labels: CLA Signed

#29313 Catch more potential instances of NotInMessageStore Exception
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/store/items/MessageItem.java
Labels: CLA Signed

#29519 Remove meaningless checks from transacted send tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#29509 Resolving test timing bug
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULDuplicateTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULLogServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingBridgeServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/TestUtils.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/config.yaml
Labels: noproductcode, CLA Signed

#29506 Check for trace enablement to improve performance
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpBaseMessageImpl.java
Labels: in:Transport, CLA Signed, team:Sirius

#28876 expose OpenTelemetryAccessor as an SPI
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.0/io.openliberty.mpTelemetry-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-1.1/io.openliberty.mpTelemetry-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.0/io.openliberty.mpTelemetry-2.0.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal/src/io/openliberty/microprofile/telemetry10/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/.classpath
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/base_test.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/build.gradle
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryUserFeatureAppScopedTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryUserFeatureTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/userfeature/UserFeatureServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/features/telemetry.user.feature-1.0.mf
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/features/telemetry.user.feature-2.0.mf
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/files/jakarta/serverxmlsnippet.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/files/javax/serverxmlsnippet.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10UserFeature/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10UserFeature/jvm.options
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10UserFeature/server.xml
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/test-bundles/telemetry.user.feature/src/io/openliberty/telemetry/user/feature/TelemetryServletContainerInitializer.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/test-bundles/telemetry.user.feature/src/io/openliberty/telemetry/user/feature/UserFeatureServletFilter.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/user-feature.bnd
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/OpenTelemetryLogHandler.java
  dev/io.openliberty.microprofile.telemetry.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/OpenTelemetryProducer.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/AbstractOpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/DisabledOpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/DisposedOpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/EnabledOpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/ErrorOpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryInfoInternal.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemetryLifecycleManager.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/info/OpenTelemtryLifecycleManagerImpl.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryInfoFactory.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/spi/OpenTelemetryAccessor.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/spi/OpenTelemetryInfo.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/spi/package-info.java
  dev/io.openliberty.microprofile.telemetry.internal.common/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.spi/.classpath
  dev/io.openliberty.microprofile.telemetry.spi/.project
  dev/io.openliberty.microprofile.telemetry.spi/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.spi/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.spi/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.spi/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.spi/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.spi/io.openliberty.microprofile.telemetry.spi.pom
Labels: CLA Signed

#29523 Filter old transitive versions of Netty Codec from Mend
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#29513 second batch of error message for Jakarta Data
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTest.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed
