Repository OpenLiberty/open-liberty, pull requests merged in 2024-02, with the labels that each got.

#27526 Add EE11 repeat to CDI 3.0 bucket
  dev/io.openliberty.cdi.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.cdi.3.0.internal_fat/fat/src/io/openliberty/cdi30/internal/fat/tests/CDI30BeansXMLTest.java
Labels: noproductcode, CLA Signed

#27499 JAXB: Upgrade JAXB to 2.3.9
  dev/ant_build.js/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.jbatch.container/bnd.bnd
  dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.internal.optional.jaxb-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jaxb-2.2/com.ibm.websphere.appserver.jaxb-2.2.feature
  dev/com.ibm.websphere.security.wim.base/bnd.bnd
  dev/com.ibm.ws.anno/bnd.bnd
  dev/com.ibm.ws.javamail.1.6_fat/build.gradle
  dev/com.ibm.ws.jaxb.tools.schemagen/bnd.bnd
  dev/com.ibm.ws.jaxb.tools.xjc/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb-tools.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_schemagen.bnd
  dev/com.ibm.ws.jaxb.tools/jaxb_xjc.bnd
  dev/com.ibm.ws.jaxrs.2.0.tools.wadl2java/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/bnd.bnd
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/bnd.bnd
  dev/com.ibm.ws.jaxws.X.wsat_fat/build.gradle
  dev/com.ibm.ws.jaxws.ejb_fat/build.gradle
  dev/com.ibm.ws.jaxws.tools.wsgen/bnd.bnd
  dev/com.ibm.ws.jaxws.tools.wsimport/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/src/com/sun/tools/ws/wscompile/WsimportTool.java
  dev/com.ibm.ws.kernel.cmdline/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.2/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.3/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.4/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.file_fat/bnd.bnd
  dev/com.ibm.ws.tx.jta_fat_hibernate/build.gradle
  dev/com.ibm.ws.wsat.common/bnd.bnd
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/build.gradle
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.classpath
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.project
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/bnd.bnd
  dev/io.openliberty.jaxws.global.handler.internal_fat/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.1/bnd.bnd
  dev/io.openliberty.jaxws.security_fat.ssl/bnd.bnd
  dev/io.openliberty.jaxws.security_fat/bnd.bnd
  dev/io.openliberty.mail.2.0.internal_fat/build.gradle
  dev/io.openliberty.xmlws.4.0.internal_fat/build.gradle
Labels: CLA Signed

#27531 Avoid parse error when unmarshalling server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/ServerConfigurationFactory.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27524 CDI 4.1 repeats for visibility bucket
  dev/com.ibm.ws.cdi.visibility_fat/bnd.bnd
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/basic/BasicVisibilityTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/ejb/EJBVisibilityTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/sharedlib/SharedLibraryTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/validatorInJar/ValidatorInJarTest.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/vistest/VisTest.java
  dev/com.ibm.ws.cdi.visibility_fat/publish/features/visTest-3.0.mf
  dev/fattest.simplicity/src/componenttest/rules/repeater/TransformSubActionImpl.java
Labels: noproductcode, CLA Signed

#27469 Update Smallrye RM to 4.16.0 and Mutiny to 2.5.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.io.smallrye.reactive.messaging-api4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.messaging-provider4/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.mutiny/bnd.bnd
  dev/io.openliberty.io.smallrye.reactive.streams-operators-jakarta/bnd.bnd
Labels: CLA Signed

#27540 Update resteasy-tracing-api exports to correct version
  dev/io.openliberty.org.jboss.resteasy.common.ee10/bnd.bnd
  dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
Labels: CLA Signed

#27549 JAXB: Update fattest.simplicity/build.gradle to force dependency order
  dev/fattest.simplicity/build.gradle
Labels: noproductcode, CLA Signed

#27466 Performance updates for application start
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/classsource/internal/ClassSourceImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsTableAnnotationsImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsTableClassesImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsTableClassesMultiImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsTableImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsTableTimeStampImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsVisitorClassImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsVisitorJandexConverterImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/internal/TargetsVisitorSparseJandexConverterImpl.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_BidirectionalMap.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_EmptyBidirectionalMap.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_EmptyInternMap.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_FileStamp.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/util/internal/UtilImpl_InternMap.java
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/SimpleDeployedAppInfoBase.java
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootApplicationImpl.java
  dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfo.java
  dev/com.ibm.ws.artifact.file/src/com/ibm/ws/artifact/file/internal/FileEntry.java
  dev/com.ibm.ws.artifact.overlay/src/com/ibm/ws/artifact/overlay/internal/DirectoryBasedOverlayContainerImpl.java
  dev/com.ibm.ws.artifact.url/src/com/ibm/ws/artifact/url/internal/WSJarURLStreamHandler.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileData.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileHandleImpl.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileReaper.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainer.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileContainerUtils.java
  dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/ZipFileEntry.java
  dev/com.ibm.ws.artifact.zip/test/com/ibm/ws/artifact/zip/cache/test/ZipFileReaperTest.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/annocache/internal/AnnotationsImpl.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/app/deploy/ManifestClassPathUtils.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/app/deploy/extended/ManifestClassPathHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/app/deploy/internal/WebModuleClassesInfoAdapter.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/config/internal/WebFragmentsInfoImpl.java
  dev/com.ibm.ws.kernel.filemonitor/src/com/ibm/ws/kernel/filemonitor/internal/DirectoryUpdateMonitor.java
Labels: CLA Signed, team:Performance, performance

#27550 tests for web.xml override of qualifiers
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/OverriddenQualifier1.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/OverriddenQualifier2.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/OverridingQualifier1.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/OverridingQualifier2.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27539 Utilise new kafkaStopServer method in RM Kafka FATs
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/jsonb/JsonbTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/ack/auto/KafkaAutoAckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/checkpoint/CheckpointKafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/KafkaDefaultContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/KafkaCustomContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/invalid/KakfaInvalidContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/flatmap/KafkaFlatMapTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/badconfig/KafkaBadConfigTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/invalid/nolib/KafkaNoLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/LibertyLoginModuleTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/invalid/LibertyLoginModuleInvalidTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/none/LibertyLoginModuleNoEncTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/special_chars/LibertyLoginModuleSpecialCharsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/liberty_login/xor/LibertyLoginModuleXorTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/ConsumerRecordTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseConfiguredTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/message/UseProducerRecordTopicTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sasl_plain/KafkaSaslPlainTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomKeySerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/serializer/KafkaCustomSerializerTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/sharedLib/KafkaSharedLibTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tls/KafkaTlsTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/loginModuleClassloading/LoginModuleClassloadingTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/suite/KafkaMessagingTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/emitter/basic/KafkaEmitterTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/emitter/nack/KafkaEmitterNackRestfulTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/emitter/restful/KafkaEmitterRestfulTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/metrics/MetricsTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/metrics/MultiAppMetricsTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/kafka/nack/KafkaNackTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/telemetry/ReactiveMessagingTelemetryTest.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/fat/src/io/openliberty/microprofile/reactive/messaging/fat/telemetry/ReactiveMessagingTelemetryTestWithJAXRS.java
Labels: noproductcode, CLA Signed

#27527 trim env var to allow for spaces
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#27533 remove versionless features from console output
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
Labels: CLA Signed

#27563 Fix up MANIFEST.MF file that cause transformer error.
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandler.ear/resources/META-INF/MANIFEST.MF
Labels: noproductcode, CLA Signed, team:Performance

#27548 prevent double contextualization of processor via contextualSubscriber
  dev/io.openliberty.concurrent.internal.compat31/src/io/openliberty/concurrent/internal/compat/ContextServiceBase.java
Labels: team:Zombie Apocalypse, CLA Signed

#27581 Fix up MANIFEST.MF files that cause transformer error.
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerBadPwd.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerEmptyPwd.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerEmptyUser.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerNullUser.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerUnauthzUser.ear/resources/META-INF/MANIFEST.MF
  dev/com.ibm.ws.security.client_fat/test-applications/ProgrammaticLoginWithCallbackHandlerUserNotDefined.ear/resources/META-INF/MANIFEST.MF
Labels: noproductcode, CLA Signed, team:Performance

#27577 Assume.assumeTrue exception caused test failure
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
  dev/com.ibm.ws.session.cache_fat_infinispan/test-applications/sessionCacheApp/src/session/cache/infinispan/web/SessionCacheTestServlet.java
Labels: noproductcode, CLA Signed

#27522 Feature prioritization instructions update
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#27585 Update feature.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: noproductcode, CLA Signed

#27506 Change to use Jakarta EE JSON technologies for mpHealth-3.0+
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.1/com.ibm.websphere.appserver.mpHealth-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/io.openliberty.microprofile.health.3.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30HttpResponseBuilder.java
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30ServiceImpl.java
  dev/io.openliberty.microprofile.health.3.1.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/HealthCheck31ServiceImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/bnd.bnd
Labels: CLA Signed, team:Performance

#27535 SQLMultiscopeRecoveryLogs instance lock variables
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLMultiScopeRecoveryLog.java
Labels: CLA Signed

#27587 enable logging for RTC285987
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
Labels: noproductcode, CLA Signed

#27583 Remove test that times out because it legitimately needs longer than …
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite-lite.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/tck-suite.xml
Labels: noproductcode, CLA Signed

#27582 Changes to handle circular static initialisation issue.
  dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/ASMFactory.java
Labels: in:JPA, team:Blizzard, CLA Signed

#27355 JAX-WS: Issue accessing ibm-ws-bnd.xml file in a test
  dev/io.openliberty.jaxws.security_fat/fat/src/com/ibm/ws/jaxws/security/fat/EJBInJarServiceSecurityTest.java
  dev/io.openliberty.jaxws.security_fat/fat/src/com/ibm/ws/jaxws/security/fat/EJBInJarServiceSecurityWithBndTest.java
  dev/io.openliberty.jaxws.security_fat/fat/src/com/ibm/ws/jaxws/security/fat/EJBInJarServiceSecurityWithoutBndTest.java
  dev/io.openliberty.jaxws.security_fat/fat/src/com/ibm/ws/jaxws/security/fat/FATSuite.java
  dev/io.openliberty.jaxws.security_fat/test-applications/EJBInJarServiceSecurity/resources/META-INF/ibm-ws-bnd.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#27507 Remove RM and RSO 3.0 beta guards and update features to GA
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpReactiveStreams3.0-cdi3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.reactive.messaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.reactive.streams.operators-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveMessaging-3.0/io.openliberty.mpReactiveMessaging-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-3.0/io.openliberty.mpReactiveStreams-3.0.feature
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/bnd.bnd
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka/src/com/ibm/ws/microprofile/reactive/messaging/kafka/KafkaIncomingConnector.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/KafkaCustomContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/context/custom/invalid/KakfaInvalidContextTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/delivery/KafkaAcknowledgementTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/partitions/KafkaPartitionTest.java
Labels: CLA Signed

#27593 add do priv
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/service/util/ServiceCaller.java
Labels: CLA Signed

#27597 type safe sorts in Jakarta Data
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PaginatedIterator.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/SortableAttributeImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/TextAttributeImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Houses.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/_House.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CityAttrNames1.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CityAttrNames2.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/PurchaseOrder.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/_EntityModelUnknown.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Order.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Sort.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/SortableAttribute.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/TextAttribute.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetAwareSlice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pageable.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
Labels: team:Zombie Apocalypse, CLA Signed

#27569 Change to use Jakarta EE JSON technologies for mpHealth-1.0 and mpHealth-2.x
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.1/com.ibm.websphere.appserver.mpHealth-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/com.ibm.ws.microprofile.health.2.0/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20HttpResponseBuilder.java
  dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
  dev/com.ibm.ws.microprofile.health.2.2_fat_tck/bnd.bnd
  dev/com.ibm.ws.microprofile.health/bnd.bnd
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckHttpResponseBuilder.java
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/HealthCheckServiceImpl.java
Labels: CLA Signed

#27528 Select for update in lease scans
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/LeaseTimeoutManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/TxRecoveryAgentImpl.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.fastcheck/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.fastcheck/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/test-applications/transaction/src/web/FailoverServlet.java
Labels: CLA Signed

#27515 Add Java 22 specific test to FAT
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java22Test.java
  dev/io.openliberty.java.internal_fat/publish/servers/java22-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java22-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java22-server/server.xml
  dev/io.openliberty.java.internal_fat/src-reference/java22/io/openliberty/java/internal/TestApp.java
  dev/io.openliberty.java.internal_fat/src-reference/java22/io/openliberty/java/internal/TestService.java
  dev/io.openliberty.java.internal_fat/src-reference/java22/io/openliberty/java/internal/package-info.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 22

#27609 NOTICES for 24.0.0.2
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#27494 Servlet61 Clarify ServletRequest getParameter and other parameter methods.
  dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/RequestUtils.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61RequestParameterTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_RequestParameterTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_RequestParameterTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/RequestParameterTest.war/src/getparameter/servlets/GetParametersServlet.java
Labels: in:Web Components, ID Required, CLA Signed, team:Sirius, jakartaEE11

#27623 Code cleanup - Remove the TODOs
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_2.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.0_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/FATSuite.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#27615 Re-order issue templates
  .github/ISSUE_TEMPLATE/01_bug_report.md
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/03_feature.md
  .github/ISSUE_TEMPLATE/04_blog_post_beta.md
  .github/ISSUE_TEMPLATE/05_blog_post_ga_release.md
  .github/ISSUE_TEMPLATE/06_feature_test_summary.md
  .github/ISSUE_TEMPLATE/07_other-issue.md
Labels: noproductcode, CLA Signed

#27599 Fixes for build and running FATs with Java 21.
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.componenttest/autoFVT-defaults/src/ant/launch.xml
  dev/com.ibm.ws.jmx_fat/override/autoFVT/src/ant/launch.xml
  dev/com.ibm.ws.kernel.boot_fat/override/autoFVT/src/ant/launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/bnd.bnd
  dev/wlp-gradle/subprojects/fat.gradle
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Performance

#27530 Add some more BCL FAT tests
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BackChannelLogoutCommonTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/MultiServerBCLTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/RevocationBCLTests.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/AfterLogoutStates.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/Constants.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/utils/VariationSettings.java
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/client_configTests_filters.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oauthProvider_configTests_localStore.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/oidcClient_configTests.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/saml_authorize.xml
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/Constants.java
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/ValidationData.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/RevocationBCLTests.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1/bnd.bnd.disabled
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1/publish/files/serversettings/saml_authorize.xml
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/bnd.bnd.disabled
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/RevocationBCLTests.java
  dev/com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2/publish/files/serversettings/saml_authorize.xml
  dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/web/OidcRpInitiatedLogout.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestException.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutRequestHelper.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutService.java
  dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/LogoutTokenBuilder.java
  dev/com.ibm.ws.security.openidconnect.server/test/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutServiceTest.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/publish/files/serversettings/socialClient_configTests.xml
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/FATSuite.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/RevocationBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/publish/files/serversettings/socialClient_configTests.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/AuthenticateApi.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/UnprotectedResourceService.java
Labels: CLA Signed, team:Security SSO, test delivery, In Progress

#27614 Removed TODOs related to EclipseLink update from 3.0.3 to 3.0.4
  dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.0_fat/fat/src/com/ibm/ws/jpa/tests/spec10/query/FATSuite.java
Labels: noproductcode, test debt, in:JPA, CLA Signed

#27619 Fix JPA Spec 10 FAT with JPA 32
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/FATSuite.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/JPA10Injection_MDB.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA21.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA22.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA22Hibernate.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA22OpenJPA312.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA30.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeatWithJPA32.java
  dev/com.ibm.ws.jpa.tests.spec10.injection.mdb_fat/fat/src/com/ibm/ws/jpa/tests/spec10/injection/mdb/RepeaterInfo.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA21.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA22.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA22Hibernate.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA22OpenJPA312.java
  dev/com.ibm.ws.jpa.tests.spec10.injection_fat.common/fat/src/com/ibm/ws/jpa/tests/spec10/injection/common/RepeatWithJPA30.java
Labels: noproductcode, test bug, in:JPA, team:Blizzard, CLA Signed

#27631 typed pageable missed from api and impl
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/_Prime.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
Labels: team:Zombie Apocalypse, CLA Signed

#27592 Remove comment that is not necessary
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60RecordELResolverTest.war/src/io/openliberty/el60/fat/recordelresolver/servlets/EL60RecordELResolverTestServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27633 JDBC 43 fat fixes for IBM i
  dev/com.ibm.ws.jdbc_fat_v43/publish/servers/com.ibm.ws.jdbc.fat.v43/server.xml
Labels: noproductcode, CLA Signed

#27529 Add FAT for Servlet 6.1 ServletResponse no-op clarification
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61ResponseNoOpAfterCommit.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ResponseNoOpAfterCommit/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_ResponseNoOpAfterCommit/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/ResponseNoOpAfterCommit.war/src/response/noop/servlets/TestResponseNoOpAfterCommitServlet.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#26215 add verbose:gc as default
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/FATSuite.java
  dev/com.ibm.ws.kernel.boot_fat/fat/src/com/ibm/ws/kernel/boot/VerboseLogTest.java
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.verbose.fat/bootstrap.properties
  dev/com.ibm.ws.kernel.boot_fat/publish/servers/com.ibm.ws.kernel.boot.verbose.fat/server.xml
Labels: CLA Signed

#27520 GRPC as a servlet: Move flushing of last frame of a stream to occur as part of trailer writing
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/ServiceConfigTests.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/AsyncServletOutputStreamWriter.java
  dev/io.openliberty.grpc.1.0.internal/src/io/grpc/servlet/ServletServerStream.java
Labels: in:Transport, CLA Signed, release bug, team:Sirius, gRPC

#27650 Increase app start time in EJBLink FAT
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/publish/clients/com.ibm.ws.ejbcontainer.remote.client.fat.clientInjection/client.xml
  dev/com.ibm.ws.ejbcontainer.remote.client_fat/publish/servers/com.ibm.ws.ejbcontainer.remote.client.fat.serverInjection/server.xml
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#27648 qualifiers on context service in application deployment descriptor
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/server.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIEJB/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/ClearingAppContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/IgnoringTransactionContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/Invoker.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/InvokerEJB.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ejb/PropagatingLocationContext.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/OSGiInjectionEngineImpl.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtensionMetadata.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ContextServiceBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedScheduledExecutorBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/AppDefinedResourceFactory.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/QualifierProxy.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactories.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactory.java
Labels: team:Zombie Apocalypse, CLA Signed

#27485 Create Faces 4.1 Projects
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.faces-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/faces-4.1/io.openliberty.faces-4.1.feature
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIConfigByACPTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInMetaInfTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDIFacesInWebXMLTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/CDITests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AparTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22AppConfigPopTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22IncludeTest.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22StatelessViewTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ThirdPartyApiTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFServerTest.java
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23FaceletVDLTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SelectOneRadioGroupTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23SpecIssueTests.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSFFeatureConflictTests.java
  dev/io.openliberty.faces.4.1.thirdparty/.classpath
  dev/io.openliberty.faces.4.1.thirdparty/.project
  dev/io.openliberty.faces.4.1.thirdparty/.settings/bndtools.core.prefs
  dev/io.openliberty.faces.4.1.thirdparty/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.faces.4.1.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.faces.4.1.thirdparty/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.faces.4.1.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/.classpath
  dev/io.openliberty.jakarta.faces.4.1/.project
  dev/io.openliberty.jakarta.faces.4.1/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.faces.4.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.faces.4.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.faces.4.1/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/FATSuite.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AjaxRenderExecuteThisTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/AnnotationLiteralsTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/MultipleInputFileTest.java
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/WebSocketTests.java
  dev/io.openliberty.org.apache.myfaces.4.1/.classpath
  dev/io.openliberty.org.apache.myfaces.4.1/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.myfaces.4.1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.myfaces.4.1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.myfaces.4.1/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/src/META-INF/beans.xml
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27653 Increase FeatureList generation timeout
  dev/fattest.simplicity/src/componenttest/depchain/FeatureList.java
Labels: noproductcode, CLA Signed

#27641 Delete features that match bundle name and add a test
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/bnd.bnd
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/SymbolicNameTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.io.netty.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.io.netty.ssl.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.netty.internal-1.0.feature
  dev/com.ibm.ws.bnd.annotations/bnd.bnd
Labels: CLA Signed, team:Performance

#27624 Update apache commons to 3.14.0
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.cdi.jee_fat/build.gradle
  dev/com.ibm.ws.grpc_fat/build.gradle
  dev/com.ibm.ws.jsf.2.2_fat/build.gradle
  dev/com.ibm.ws.jsf.2.3_fat/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.2/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.org.apache.commons.lang3/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.lang3/bnd.overrides
  dev/com.ibm.ws.security.fat.common.jwt/build.gradle
  dev/com.ibm.ws.security.jwt_fat.builder/build.gradle
  dev/com.ibm.ws.security.jwt_fat.consumer/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.1/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-1.2/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.0/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.mpJwt-2.1/build.gradle
  dev/com.ibm.ws.security.jwtsso_fat.noMpJwt/build.gradle
  dev/com.ibm.ws.springboot.fat20_fat/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat.2/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0_fat/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1_fat/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.1/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.2/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.logout/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.refresh/build.gradle
  dev/io.openliberty.security.jakartasec.3.0.internal_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/build.gradle
Labels: CLA Signed

#27627 Allow leeway when checking Thread.sleep lasted the expected time
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/servlet/HttpTraceTestServlet.java
Labels: noproductcode, CLA Signed

#27654 server command not handle space in path on Windows
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed

#27658 Make sure that all JWT Consumer test classes wait for the jwtconsumerclient app to start
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumHSARunnableConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLConsumerConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerAPIMinimumSSLGlobalConfigTests.java
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#27667 Fix for CWWKS9590W Warning
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java
Labels: CLA Signed, release bug

#27662 Remove module-info class files from bundles
  dev/com.ibm.ws.install/bnd.bnd
  dev/com.ibm.ws.jaxb.tools/bnd.bnd
  dev/com.ibm.ws.jaxws.tools/bnd.bnd
  dev/io.openliberty.com.google.gson/bnd.bnd
  dev/io.openliberty.jaxrs.2.0.wadl2java.jaxb.runtime/bnd.bnd
Labels: CLA Signed, team:Performance

#27673 Revert "Fix for CWWKS9590W Warning"
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java
Labels: CLA Signed

#27671 Fix CommunicationException in JavaIllegalAccessTest
  dev/io.openliberty.java.internal_fat/test-applications/illegalaccess/src/test/web/IllegalAccessTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27672 apply component metadata from ejb or create web component metadata
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/cdi/MTFBeanResourceInfo.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/cdi/package-info.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.injection/src/com/ibm/ws/injectionengine/osgi/internal/OSGiInjectionEngineImpl.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/MTFBeanResourceInfoImpl.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/AppDefinedResourceFactory.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/qualified/QualifiedResourceFactory.java
Labels: team:Zombie Apocalypse, CLA Signed

#27677 Update features to be singletons when WebSphere Liberty has a version
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureFileList.java
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/utils/FeatureMapFactory.java
  dev/com.ibm.websphere.appserver.features/visibility/public/jmsMdb-3.2/com.ibm.websphere.appserver.jmsMdb-3.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/scim-2.0/com.ibm.websphere.appserver.scim-2.0.feature
Labels: CLA Signed, team:Performance

#27684 catch everything
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
Labels: CLA Signed

#27676 Create Jakarta EE 11 packages
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee11/features.xml
  dev/build.image/profiles/webProfile11/features.xml
  dev/build.image/publish/wlp/templates/clients/jakartaeeClient11/client.xml
  dev/build.image/publish/wlp/templates/servers/jakartaee11/server.xml
  dev/build.image/publish/wlp/templates/servers/webProfile11/server.xml
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-11.0/io.openliberty.jakartaee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jakartaeeClient-11.0/io.openliberty.jakartaeeClient-11.0.feature
Labels: CLA Signed, team:Performance

#27682 Skipping the need to inject an OpenTelemetryInfo here divides the nan…
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/OpenTelemetryProducer.java
Labels: CLA Signed

#27219 27218: cfw perf update
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInputStreamEE7Extended.java
Labels: CLA Signed, performance

#27094 install kernel add multiple esa resource
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ResolveDirector.java
Labels: CLA Signed

#27578 Add new error.method attribute to error dispatch
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebApp.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/webapp/WebAppDispatcherContext.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/fat/src/io/openliberty/webcontainer/servlet61/fat/tests/Servlet61DispatcherErrorMethodAttributeTest.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_DispatcherErrorMethodTest/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/publish/servers/servlet61_DispatcherErrorMethodTest/server.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DispatcherErrorMethodAttributeTest.war/resources/WEB-INF/web.xml
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DispatcherErrorMethodAttributeTest.war/src/errormethod/servlets/ErrorPageServlet.java
  dev/io.openliberty.webcontainer.servlet.6.1.internal_fat/test-applications/DispatcherErrorMethodAttributeTest.war/src/errormethod/servlets/TestErrorMethodAttributeServlet.java
Labels: in:Web Components, team:Sirius, jakartaEE11

#27632 Update testcontainers to 1.19.5
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.app.manager.wab.installer_fat/build.gradle
  dev/com.ibm.ws.classloading.bells_fat/build.gradle
  dev/com.ibm.ws.filetransfer.routing.archiveExpander/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/OracleKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/files/oracle/Dockerfile
  dev/com.ibm.ws.jdbc_fat_oracle/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleCustomTrace.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTraceTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleUCPTest.java
  dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/containters/OracleSSLContainer.java
  dev/com.ibm.ws.jdbc_fat_oracle/publish/files/oracle-ssl/Dockerfile
  dev/com.ibm.ws.kernel.boot.archive/bnd.bnd
  dev/com.ibm.ws.kernel.boot_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/build.gradle
  dev/com.ibm.ws.logging_2_fat/bnd.bnd
  dev/com.ibm.ws.logging_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health.2.0_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.health_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.2.x.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics.monitor_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.metrics_fat/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.compress/bnd.bnd
  dev/com.ibm.ws.org.apache.commons.compress/bnd.overrides
  dev/com.ibm.ws.security.fat.common.claimPropagation/CommonClaimPropagation.gradle
  dev/com.ibm.ws.security.fat.common.claimPropagation/build.gradle
  dev/com.ibm.ws.security.oauth.oidc_fat.common/build.gradle
  dev/com.ibm.ws.security.oauth_fat/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.noOP/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.oauth/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.oidc/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oauth/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.oidc/build.gradle
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/containers/ImageVerifier.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/OracleXEContainer.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryRegistryTest.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerFactoryTest.java
  dev/io.openliberty.microprofile.health.3.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.3.x.monitor_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.4.x.monitor_fat/bnd.bnd
  dev/io.openliberty.microprofile.metrics.internal.5.x.monitor_fat/bnd.bnd
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/images
Labels: team:Zombie Apocalypse, CLA Signed

#27689 Peer Recovery Precedence server in FATs needs long lease interval
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleaselogfail/bootstrap.properties
Labels: noproductcode, CLA Signed

#27694 get provider config without req provider hint
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/MultiServerBCLTests.java
Labels: CLA Signed

#27441 Register with most immediate superior
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/FileSharedServerLeaseLog.java
  dev/com.ibm.ws.transaction.cloud_fat.simpleFS/fat/src/suite/SimpleFS2PCCloudTest.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinator.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATCoordinatorTran.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATEndpoint.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATParticipant.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATTransaction.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/WSATUtil.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/HandlerImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/ProtocolImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/RegistrationImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/ParticipantFactoryService.java
  dev/com.ibm.ws.wsat.common/test/com/ibm/ws/wsat/common/impl/WSATParticipantTest.java
  dev/com.ibm.ws.wsat.webservice/bnd.bnd
  dev/com.ibm.ws.wsat.webservice/src/com/ibm/ws/wsat/interceptor/CoorContextOutInterceptor.java
  dev/com.ibm.ws.wsat.webservice/src/com/ibm/ws/wsat/utils/WSATRequestHandler.java
  dev/com.ibm.ws.wsat.webservice/src/com/ibm/ws/wsat/utils/WSCoorUtil.java
  dev/com.ibm.ws.wsat_fat.multi.misroute/.classpath
  dev/com.ibm.ws.wsat_fat.multi.misroute/.project
  dev/com.ibm.ws.wsat_fat.multi.misroute/.settings/bndtools.core.prefs
  dev/com.ibm.ws.wsat_fat.multi.misroute/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.wsat_fat.multi.misroute/bnd.bnd
  dev/com.ibm.ws.wsat_fat.multi.misroute/build.gradle
  dev/com.ibm.ws.wsat_fat.multi.misroute/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat_fat.multi.misroute/fat/src/tests/MultiServerRerouteTest.java
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/FourthServer/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/FourthServer/server.xml
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/MultiServerTest/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/MultiServerTest/server.xml
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/ThirdServer/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/ThirdServer/server.xml
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/WSATBasic/bootstrap.properties
  dev/com.ibm.ws.wsat_fat.multi.misroute/publish/servers/WSATBasic/server.xml
  dev/com.ibm.ws.wsat_fat.multi/fat/src/tests/MultiServerTest.java
  dev/fattest.simplicity/autoFVT-defaults/testports.properties
Labels: CLA Signed

#27705 Tolerate FFDC from ResourceException in DatasourceChangeTest
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/Simple2PCCloudTest.java
Labels: noproductcode, CLA Signed

#27703 SQL Server Lease Access set to Serializable isolation level
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
Labels: CLA Signed

#27708 rename Pageable to PageRequest
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PaginatedIterator.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Tariffs.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Order.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetAwareSlice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetCursor.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Slice.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/BasicRepository.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/repository/PageableRepository.java
Labels: CLA Signed

#27714 Upgrade postgres test driver
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jdbc_fat_postgresql/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_postgresql/build.gradle
  dev/com.ibm.ws.transaction.db_fat/bnd.bnd
  dev/com.ibm.ws.transaction.db_fat/build.gradle
  dev/com.ibm.ws.wsat.migration_fat.6/bnd.bnd
  dev/wlp-gradle/subprojects/fat.gradle
Labels: CLA Signed

#27655 remove logout call on auth exception to fix bug sessionCache
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.ltpaKeyRotationTestServer/server.xml
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/SSOAuthenticator.java
  dev/com.ibm.ws.webcontainer.security/test/com/ibm/ws/webcontainer/security/internal/SSOAuthenticatorTest.java
Labels: CLA Signed, team:Core Security

#27448 Enable Instant On for sessionCache-1.0
  dev/com.ibm.websphere.appserver.features/visibility/public/jcacheContainer-1.1/com.ibm.websphere.appserver.jcacheContainer-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sessionCache-1.0/com.ibm.websphere.appserver.sessionCache-1.0.feature
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
  dev/com.ibm.ws.kernel.boot.nested/src/com/ibm/ws/kernel/launch/internal/FrameworkManager.java
  dev/com.ibm.ws.session.cache/bnd.bnd
  dev/com.ibm.ws.session.cache/src/com/ibm/ws/session/store/cache/CacheHashMap.java
  dev/com.ibm.ws.session/src/com/ibm/ws/session/SessionContext.java
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/CheckpointImpl.java
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointSPITest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/jvm.options
  dev/io.openliberty.checkpoint_fat/test-bundles/test.checkpoint.config.bundle/src/test/checkpoint/config/bundle/TestStaticHookRegister.java
  dev/io.openliberty.jcache.internal/bnd.bnd
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheManagerServiceImpl.java
  dev/io.openliberty.jcache.internal/src/io/openliberty/jcache/internal/CacheServiceImpl.java
Labels: CLA Signed

#27706 Fix for CWWKS9590W warning for new Ciphers without WITH in their cipher names.
  dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java
Labels: CLA Signed

#27726 Get things building in eclipse and fix other incorrect settings
  dev/io.openliberty.cdi.4.1.internal.services.fragment/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jaxws_fat/.classpath
  dev/io.openliberty.jaxws_fat/.project
  dev/io.openliberty.jaxws_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/EchoString.java
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/EchoStringService.java
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/EchoStringimpl.java
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/ObjectFactory.java
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/SOAPService1.java
  dev/io.openliberty.jaxws_fat/fat/src/fats/cxf/basic/jaxws/SimpleService.java
  dev/io.openliberty.jaxws_fat/test-applications/cxfclient/src/fats/cxf/basic/jaxws/types/FaultDetail.java
  dev/io.openliberty.jaxws_fat/test-applications/cxfclient/src/fats/cxf/basic/jaxws/types/GetVer.java
  dev/io.openliberty.jaxws_fat/test-applications/cxfclient/src/fats/cxf/basic/jaxws/types/GetVerResponse.java
  dev/io.openliberty.jaxws_fat/test-applications/cxfclient/src/fats/cxf/basic/jaxws/types/ObjectFactory.java
  dev/io.openliberty.jaxws_fat/test-applications/cxfclient/src/fats/cxf/basic/jaxws/types/package-info.java
  dev/io.openliberty.jaxws_fat/test-applications/simpleservice/src/fats/cxf/basic/jaxws/SOAPService1.java
  dev/io.openliberty.jaxws_fat/test-applications/simpleservice/src/fats/cxf/basic/jaxws/SimpleService.java
Labels: CLA Signed, team:Performance

#27580 Repeat wsoc 2.1 FAT with wsoc 2.2 (EE11)
  dev/com.ibm.ws.el.3.0_fat/fat/src/com/ibm/ws/el/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat.2/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/FATSuite.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage50/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.wsoc.2.1.internal_fat/bnd.bnd
  dev/io.openliberty.wsoc.2.1.internal_fat/build.gradle
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius, jakartaEE11

#27733 more ways to get class
  dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
  dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
Labels: CLA Signed

#27737 enable weld dump
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
  dev/com.ibm.ws.security.javaeesec_fat/publish/servers/com.ibm.ws.security.javaeesec.fat/bootstrap.properties
  dev/io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck/publish/servers/FaultTolerance40TCKServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#27717 Increase transaction timeout for slow running machines
  dev/com.ibm.ws.wsat_fat.ssl.misroute/publish/servers/WSATSSL_Client/server.xml
Labels: noproductcode, CLA Signed

#27228 Update Jakarta Data TCK runner to use M3
  dev/io.openliberty.data.internal_fat_nosql/build.gradle
  dev/io.openliberty.data.internal_fat_nosql/fat/src/test/jakarta/data/nosql/DataNoSQLTest.java
  dev/io.openliberty.data.internal_fat_nosql/test-applications/DataNoSQLApp/src/test/jakarta/data/nosql/web/DataNoSQLServlet.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0_fat_tck/build.gradle
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.core.nosql/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.core.nosql/jvm.options
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/servers/io.openliberty.org.jakarta.data.1.0.core.nosql/server.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/logging.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/standalone/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#27637 Fix job purge for in memory persistence
  dev/com.ibm.jbatch.container/src/com/ibm/jbatch/container/services/impl/MemoryPersistenceManagerImpl.java
  dev/com.ibm.ws.jbatch.fat.common/src/com/ibm/ws/jbatch/test/BatchRestUtils.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/InMemoryPersistenceTest.java
  dev/com.ibm.ws.jbatch.open_fat/test-applications/batchSecurity.war/resources/WEB-INF/classes/META-INF/batch-jobs/sleepy_partition.xml
Labels: CLA Signed

#27736 spec API update to add Order.getSorts
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Order.java
Labels: team:Zombie Apocalypse, CLA Signed

#27743 metamodel attribute impl added to spec
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.0/io.openliberty.data-1.0.feature
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/Model.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/_TaxPayer.java
  dev/io.openliberty.jakarta.data.1.0/bnd.bnd
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/impl/AttributeRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/impl/SortableAttributeRecord.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/impl/TextAttributeRecord.java
Labels: team:Zombie Apocalypse, CLA Signed

#27691 kernal: Creating a interface for getting fix lists (ifixes, tfixes) from featureManager class
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/FixManager.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureManager.java
  dev/com.ibm.ws.kernel.feature_fat/.classpath
  dev/com.ibm.ws.kernel.feature_fat/bnd.bnd
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FATSuite.java
  dev/com.ibm.ws.kernel.feature_fat/fat/src/com/ibm/ws/kernel/feature/fat/FixManagerTest.java
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle1_1.0.0.20130101.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle1_1.0.0.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle2_1.0.0.20130101.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle2_1.0.0.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle3_1.0.0.20130101.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle3_1.0.0.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle4_1.0.0.20130101.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningInterimFixesTestBundle4_1.0.0.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningTestBundle_1.0.1.201204040001-TestAPAR0001-TestAPAR0002.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningTestBundle_1.0.1.201204040001-TestAPAR0001.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/ProvisioningTestBundle_1.0.1.jar
  dev/com.ibm.ws.kernel.feature_fat/publish/files/interimFixesServer.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/files/singleInterimFixServer.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/files/test.InterimFixManagerTest-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/test.InterimFixesManagerTest-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/test.TestFixManagerTest-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/test.featurefixmanager-1.0.mf
  dev/com.ibm.ws.kernel.feature_fat/publish/files/testFixesServer.xml
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fix.manager/bootstrap.properties
  dev/com.ibm.ws.kernel.feature_fat/publish/servers/com.ibm.ws.kernel.feature.fix.manager/server.xml
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.feature.fix.manager/src/test/kernel/feature/fix/manager/FixManagerServlet.java
  dev/com.ibm.ws.kernel.feature_fat/test.feature.fix.manager.bnd
Labels: CLA Signed

#27730 Added delay invalidation alarm attribute to RequestTiming FAT
  dev/com.ibm.ws.request.timing.hung_fat/publish/servers/HungRequestTimingServer/serverSessionConfig.xml
Labels: noproductcode, CLA Signed

#27753 type parameter added to Attribute
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/AttributeImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/Model.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/SortableAttributeImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/model/TextAttributeImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/_House.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/_Prime.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CityAttrNames2.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/_TaxPayer.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/Attribute.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/SortableAttribute.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/metamodel/impl/AttributeRecord.java
Labels: team:Zombie Apocalypse, CLA Signed

#27728 fix transaction abort processing
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.java
Labels: team:Zombie Apocalypse

#27769 Update missed auto feature for EE 11 support
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.connectorsInboundSecurity-2.1.feature
Labels: CLA Signed, team:Performance

#27739 Start tests at the top of the minute
  dev/com.ibm.ws.logging_2_fat/fat/src/com/ibm/ws/logging/fat/TimeBasedLogRolloverTest.java
Labels: noproductcode, CLA Signed

#27746 Allow port retries on test servers
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/rp2_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.backchannelLogout/publish/files/serversettings/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.claimPropagation/publish/files/serversettings/op_external_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.claimPropagation/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.mp.jwt/publish/shared/config/builder_fatTestPorts.xml
  dev/com.ibm.ws.security.fat.common.mp.jwt/publish/shared/config/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/op_fatTestPorts.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/shared/config/fatTestPorts.xml
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/shared/config/misc.xml
  dev/com.ibm.ws.security.jwtsso_fat.commonTest/publish/servers/com.ibm.ws.security.jwtsso.fat/configs/server_noSslPort.xml
  dev/com.ibm.ws.security.mp.jwt.1.1_fat.commonTest/publish/shared/config/client_fatTestPorts.xml
  dev/com.ibm.ws.security.oauth.oidc_fat.common/publish/files/serversettings/op_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.1/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/files/serversettings/fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.2/publish/files/serversettings/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.3/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.4/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.jaxrs/publish/files/serversettings/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/oidc/serversettings/fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/oidc/serversettings/op_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/oidc/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/server_modules/configs/host_info.xml
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/servers/BackendServer/server.xml
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/publish/files/serversettings/rs_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/files/server_modules/configs/host_info.xml
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/files/serversettings/fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/files/serversettings/op_fatTestPorts.xml
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/servers/BackendServer/server.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/fatTestPorts.xml
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.shibboleth/configs/server_orig.xml
  dev/com.ibm.ws.security.saml.sso_fat.common/publish/servers/com.ibm.ws.security.saml.sso-2.0_fat.shibboleth/configs/server_samesite.xml
  dev/com.ibm.ws.security.saml.sso_fat.config/publish/files/serversettings/misc2.xml
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs.config/publish/files/serversettings/fatTestPorts2.xml
  dev/com.ibm.ws.security.saml.sso_fat.jaxrs/publish/files/serversettings/fatTestPorts2.xml
  dev/com.ibm.ws.security.saml.sso_fat.logout/publish/files/serversettings/fattestports2.xml
  dev/com.ibm.ws.security.social_fat.commonTest.LibertyOP/publish/files/serversettings/rp_samesite_misc.xml
  dev/com.ibm.ws.security.social_fat.delegated/publish/files/serversettings/external_op_fatTestPorts.xml
  dev/com.ibm.ws.security.social_fat.delegated/publish/files/serversettings/op_fatTestPorts.xml
  dev/com.ibm.ws.security.social_fat.delegated/publish/files/serversettings/rp_fatTestPorts.xml
  dev/com.ibm.ws.security.social_fat.multiProvider/publish/files/serversettings/op_fatTestPorts.xml
  dev/com.ibm.ws.security.social_fat.okdServiceLogin/publish/files/serversettings/op_misc.xml
  dev/com.ibm.ws.security.social_fat/publish/files/serversettings/misc.xml
  dev/com.ibm.ws.security.social_fat/publish/shared/config/misc.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/publish/shared/config/op_fatTestPorts.xml
  dev/io.openliberty.security.jakartasec.3.0.internal_fat.common/publish/shared/config/rp_fatTestPorts.xml
Labels: noproductcode, test bug, CLA Signed, team:Security SSO, In Progress

#27740 Revert "get provider config without req provider hint"
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientImpl.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/BasicBCLTests.java
  dev/com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2/fat/src/com/ibm/ws/security/backchannelLogout/fat/MultiServerBCLTests.java
Labels: CLA Signed

#27758 NPE Fix for a test on z/OS
  dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/libertyCXFProperties/src/com/ibm/ws/properties/test/service/ImageServiceImpl.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#27760 Expect ChangesSummary event from Compile Liberty Images executionId
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed, team:Continuous Delivery

#27772 Move Servlet 6.1 API to M2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature
  dev/io.openliberty.jakarta/servlet.6.1.bnd
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#27774 Add propagateXAResourceTransactionTimeout
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/XARecoveryData.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.transaction.core_fat.base/publish/servers/com.ibm.ws.transaction/jvm.options
  dev/com.ibm.ws.transaction.core_fat.base/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.tx.embeddable/bnd.bnd
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableConfigurationProviderImpl.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/EmbeddableRuntimeMetaDataProviderImpl.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/config/package-info.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/ltc/embeddable/config/package-info.java
Labels: ID review not needed, CLA Signed, L2 ReviewNotRequired

#27784 Cursor.elements added to spec
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/KeysetAwarePageImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/KeysetCursor.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
Labels: team:Zombie Apocalypse, CLA Signed

#27786 spec update to allow sort criteria from entity subclasses
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/Order.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/PageRequest.java
  dev/io.openliberty.jakarta.data.1.0/src/jakarta/data/page/Pagination.java
Labels: team:Zombie Apocalypse, CLA Signed

#27735 Unregister static hook service and clear rank mappings
  dev/com.ibm.ws.kernel.boot.common/src/io/openliberty/checkpoint/spi/CheckpointPhase.java
Labels: CLA Signed

#27707 variable in include location can be empty
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/XMLConfigParser.java
  dev/com.ibm.ws.config/test/com/ibm/ws/config/xml/internal/XMLConfigParserTest.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.import.empty.variable/bootstrap.properties
  dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.import.empty.variable/server.xml
Labels: CLA Signed

#27780 Upgrade pipeline JVM to Oracle HotSpot OpenJDK 21 GA
  .ci-orchestrator/jvms/dev/linux_x86_64.properties
Labels: CLA Signed, team:Continuous Delivery
