Repository OpenLiberty/open-liberty, pull requests merged in 2024-10, with the labels that each got.

#29674 Update Expression Language 6.0 API/IMPL to M26
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29752 Increase tolerated EJB timer delay on Mac OSX
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#29740 Overlays created for Issue Fix 28874
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org.eclipse.persistence.jpa.jpql.parser/AbstractPathExpression.java
Labels: in:JPA, team:Blizzard, CLA Signed

#29754 Add orbSSLInitTimeout config to featureStart tests.
  dev/build.featureStart.part1_fat/publish/servers/features.start.1.server/server.xml
  dev/build.featureStart.part2_fat/publish/servers/features.start.2.server/server.xml
  dev/build.featureStart.part3_fat/publish/servers/features.start.3.server/server.xml
  dev/build.featureStart.part4_fat/publish/servers/features.start.4.server/server.xml
Labels: noproductcode, CLA Signed, team:Performance

#29753 Update embedded messaging security tests for checkpoint
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpClientTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpEngineTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpClientTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpEngineTest.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/JMSMDBTest.java
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/MDBTest/server.xml
  dev/io.openliberty.checkpoint_fat_jms/test-applications/MDBTestApp/src/mdb/test/app/EJBAnnotatedMessageDrivenBean.java
  dev/io.openliberty.checkpoint_fat_jms/test-applications/MDBTestWeb/src/mdb/test/web/JMSContextInjectServlet.java
Labels: noproductcode, CLA Signed

#29478 updating shutdown hook to write failures to a log file and updating the test to read from the log file if one exists
  dev/wlp.lib.extract/src/wlp/lib/extract/ShutdownHook.java
  dev/wlp.lib.extract_fat/fat/src/wlp/lib/extract/PackageRunnableTest.java
Labels: CLA Signed

#29731 Update MP Rest Client to use RESTEasy 3.0.0.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.resteasy.mprestclient.4.0/bnd.bnd
Labels: CLA Signed

#29667 fix gvt failure in some locales by overriding to utf8
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyFileManager.java
Labels: noproductcode, CLA Signed

#29760 Fix testTimestampAsVersion on Oracle
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#29763 propagation of custom context type to virtual ManagedThreadFactory thread
  dev/com.ibm.ws.concurrent_fat_jakarta_11/.classpath
  dev/com.ibm.ws.concurrent_fat_jakarta_11/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_jakarta_11/fat/src/test/jakarta/concurrency/Concurrency31Test.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/publish/servers/com.ibm.ws.concurrent.fat.jakarta.ee11/server.xml
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-libraries/TimeZoneContext/src/test/context/timezone/TimeZone.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-libraries/TimeZoneContext/src/test/context/timezone/TimeZoneContextProvider.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-libraries/TimeZoneContext/src/test/context/timezone/TimeZoneContextRestorer.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-libraries/TimeZoneContext/src/test/context/timezone/TimeZoneContextSnapshot.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29758 Explicitly configure mpConfig to avoid repeat errors
  dev/io.openliberty.checkpoint_fat/publish/servers/openAPIserver/server.xml
Labels: noproductcode, CLA Signed

#29623 Port MYFACES-4681 to Faces 4.1
  dev/io.openliberty.org.apache.myfaces.4.0_fat/fat/src/io/openliberty/org/apache/myfaces40/fat/tests/Html5Tests.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/view/facelets/compiler/CompilationManager.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29762 Explicitly configure features to avoid repeat errors
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPHealth/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPJWT/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPMetrics/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointMPOpenAPIConfig/server.xml
  dev/io.openliberty.checkpoint_fat/publish/servers/timeoutServer/server.xml
Labels: noproductcode, CLA Signed

#28705 Update Data TCK to version 1.0.1
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/logging.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/verification.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/standalone/pom.xml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29756 remove workarounds for EclipseLink bug
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
Labels: team:Zombie Apocalypse, CLA Signed

#29761 Add more traces for ConnectionPoolMetricsTest
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/ConnPoolMetricsServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#29716 Fat okd service fix
  dev/com.ibm.ws.security.social_fat.okdServiceLogin/test-applications/StubbedOKDServiceLogin/src/com/ibm/ws/fat/OKDServiceLogin/UserValidationApi.java
Labels: noproductcode, CLA Signed

#29775 Enable tests for 28874
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Rebate.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#29741 Support CDI.current() in threads that were not created by Jakarta Concurrency.
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/current/CDICurrentTestServlet.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/threads/extension/CDIExtension.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/threads/extension/SimpleBean.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/threads/extension/javax.enterprise.inject.spi.Extension
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.internal/src/com/ibm/ws/cdi/internal/archive/liberty/RuntimeFactory.java
  dev/com.ibm.ws.cdi.weld/bnd.bnd
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/AbstractCDIRuntime.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIContainerImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/CDIImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/liberty/CDIRuntimeImpl.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/LibertyClassLoadingService.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoadingServiceImpl.java
Labels: CLA Signed

#29743 Update MpTelemetry EE10 feature file
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/VisibilityTest.java
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-6.1/io.openliberty.microProfile-6.1.feature
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureJaegerTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/CrossFeatureZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/JaegerBaseTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/ClientWithNoCdi.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/JaxRsIntegration.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryDisabledTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/methods/JaxRsMethodTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/customizer/CustomizerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/exporter/ExporterTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/propagator/PropagatorTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/resource/ResourceTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/spi/sampler/SamplerTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/MetricsDisabledServlet.java
  dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/TelemetryActions.java
Labels: CLA Signed

#29777 managed executors with virtual=true in deployment descriptor
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestApp/resources/META-INF/application.xml
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/resources/WEB-INF/web.xml
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29721 Fixing build break in Validation TCK
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/ValidationTckLauncher.java
Labels: noproductcode, CLA Signed

#29779 Remove the servers from the exempt list.
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29399 Servlet 6.1 - Replaces Max-Age=0 with Expires in Set-Cookie
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/cookies/CookieUtils.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60RequestCookieHeaderTest.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#29787 untimed invokeAny and invokeAll with virtual threads
  dev/com.ibm.ws.concurrency.policy/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/PolicyExecutor.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29586 Update server description for server31_servletMappingServer
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/publish/servers/servlet31_servletMappingServer/server.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#29786 Adding new false positive version to filter
  dev/build.depScanner/src/io/openliberty/depScanner/Repository.java
Labels: noproductcode, CLA Signed

#29794 Reduce trace generated by HADB test servers
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.fastcheck/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_ANYDBCLOUD001.longleasecompete/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_multipleretries/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_multipleretries/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_nonretriable/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_nonretriable/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_recover/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_recover/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriable/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriable/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriablecloud/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_retriablecloud/server.xml
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_stalecloud/bootstrap.properties
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/publish/servers/com.ibm.ws.transaction_stalecloud/server.xml
Labels: noproductcode, CLA Signed

#29593 Pipeline configuration for required copyright header checking
  .ci-orchestrator/checks.yml
Labels: noproductcode, CLA Signed

#29804 DataErrorPathsTest CWWJP9991W on autocreate table
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29799 Validation of qualifier annotations and add various NLS messages for Concurrency 3.1
  dev/com.ibm.ws.concurrent/resources/com/ibm/ws/concurrent/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/AppDefinedResourceFactory.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ConcurrencyResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceDefinitionProvider.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29789 Upgrade testcontainers to 1.20.2
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jsf.2.2_fat.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsfContainer_fat_2.3/bnd.bnd
  dev/com.ibm.ws.openapi.ui_fat/bnd.bnd
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/containers/ImageVerifier.java
  dev/fattest.simplicity/test/componenttest/containers/ImageVerifierTest.java
  dev/io.openliberty.microprofile.openapi.ui.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0_fat/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1_fat/bnd.bnd
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/images
Labels: enhancement, team:Zombie Apocalypse, CLA Signed

#29736 Jakarta Data DDL Generation enhancements and testing
  dev/com.ibm.ws.persistence.mbean/src/com/ibm/ws/persistence/mbean/internal/DDLGenerationMBeanImpl.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerFactory.java
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerType.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/DatabaseContainerTypeTest.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_datastore/build.gradle
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DDLGenScriptHelper.java
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DataStoreTest.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/MultiEntityRepo1.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/OrderingRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/DataStoreSecondServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/OrderingRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].databaseStore[ServerDataSource]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].databaseStore[java.app.jdbc.DataSourceDef]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].databaseStore[jdbc.ServerDataSource]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestEJB.jar].databaseStore[java.module.env.jdbc.ServerDataSourceRef]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestEJB.jar].databaseStore[java.module.jdbc.DataSourceDef]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestWeb1.war].databaseStore[java.comp.DefaultDataSource]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestWeb1.war].databaseStore[java.module.env.jdbc.ServerDataSourceRef]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestWeb2.war].databaseStore[java.comp.DefaultDataSource]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestWeb2.war].databaseStore[java.module.env.jdbc.ServerDataSourceRef]_JakartaData.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/databaseStore[defaultDatabaseStore]_persistentExecutor.ddl
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/databaseStore[java.global.env.jdbc.ServerDataSourceRef]_JakartaData.ddl
Labels: team:Zombie Apocalypse, CLA Signed

#29810 Remove unnecessary jvm.options files from test servers
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/classpathTestDefaultLoader/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/classpathTestDefaultLoaderDropins/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/privateLibraryTest/jvm.options
Labels: noproductcode, CLA Signed

#29713 remove versionless features from the productInfo featureInfo command
  dev/com.ibm.ws.product.utility/src/com/ibm/ws/product/utility/extension/FeatureInfoCommandTask.java
Labels: CLA Signed

#29801 Fix JMX client README path
  dev/com.ibm.ws.jmx.scripting.client/publish/clients/jython/README
Labels: CLA Signed

#29811 repository operation hung when persistence unit lacks a required entity
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Volunteer.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/WrongPersistenceUnitRefRepo.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29820 Update Data TCK to generate valid certification adoc file
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#29829 Fix webModuleClassPathLoader label size
  dev/com.ibm.ws.app.manager.war/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed

#29791 Match the TCCL between CDI extension observers and constructor
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/threads/extension/CDIExtension.java
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/apps/threads/extension/permissions.xml
  dev/com.ibm.ws.cdi.api_fat/fat/src/com/ibm/ws/cdi/api/fat/tests/CDIAPITests.java
  dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
Labels: CLA Signed

#29785 issue #29780: reintroduce fix for GVT failure
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyFileManager.java
Labels: noproductcode, CLA Signed

#29826 NOTICES for 24.0.0.11
  dev/build.image/publish/BETA_NOTICES
  dev/build.image/publish/NOTICES
Labels: CLA Signed

#29698 message ordering multiple contexts test
  dev/com.ibm.ws.messaging.open_clientcontainer_fat/test-applications/JMS2AsyncSendClient.jar/src/com/ibm/ws/messaging/open_clientcontainer/fat/JMS2AsyncSend.java
Labels: noproductcode, CLA Signed

#29796 Add EJB J2EE Management FAT
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.project
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/fat/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/fat/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/tests/EJBJ2EEManagementTest.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/resources/security/key.jks
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/resources/security/ltpa.keys
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/server.xml
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/test-applications/EJBJ2EEManagement.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/test-applications/EJBJ2EEManagement.jar/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/ejb/EJBJ2EEManagementMDB.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/test-applications/EJBJ2EEManagement.jar/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/ejb/EJBJ2EEManagementSFSB.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/test-applications/EJBJ2EEManagement.jar/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/ejb/EJBJ2EEManagementSGSB.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/test-applications/EJBJ2EEManagement.jar/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/ejb/EJBJ2EEManagementSLSB.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test debt, CLA Signed

#29814 Increase FAT minimum timer delay on Mac OSX
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#29805 Rationalize recovery tests
  dev/com.ibm.ws.jta_fat/test-applications/jta/src/web/XAServlet.java
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
  dev/com.ibm.ws.wsat.concurrent_fat/test-applications/threadedClient/src/com/ibm/ws/wsat/threadedclient/client/threaded/CoordinatorCheckServlet.java
  dev/com.ibm.ws.wsat.concurrent_fat/test-applications/threadedServer/src/com/ibm/ws/wsat/threadedserver/server/ParticipantCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/fat/src/tests/LPSTest.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/test-applications/recoveryClient/src/client/RecoveryCheckServlet.java
  dev/com.ibm.ws.wsat.recovery_fat.lps/test-applications/recoveryServer/src/server/Recovery.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.5/fat/src/tests/MultiRecoveryTest5.java
  dev/com.ibm.ws.wsat.recovery_fat.single.1/fat/src/tests/SingleRecoveryTest.java
Labels: CLA Signed

#29838 Add zjaas.conf file to spnego buckets others than spnego_fat
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.spnego.op/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/files/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat.endpoint.clientregistration/resources/security/kerberos/zjaas.conf
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.spnego.auth.cache.1/resources/security/kerberos/zjaas.conf
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.spnego.auth.cache.1/resources/security/kerberos/zjaas.conf
Labels: noproductcode, CLA Signed

#29813 Remove beta flag for embedded messaging InstantOn
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingClient-3.0/io.openliberty.messagingClient-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingSecurity-3.0/io.openliberty.messagingSecurity-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/messagingServer-3.0/io.openliberty.messagingServer-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/wasJmsClient-2.0/com.ibm.websphere.appserver.wasJmsClient-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/wasJmsSecurity-1.0/com.ibm.websphere.appserver.wasJmsSecurity-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/wasJmsServer-1.0/com.ibm.websphere.appserver.wasJmsServer-1.0.feature
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet1Client/jvm.options
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet1Engine/jvm.options
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet2Client/jvm.options
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/LiteSet2Engine/jvm.options
  dev/io.openliberty.checkpoint_fat_jms/publish/servers/MDBTest/jvm.options
Labels: CLA Signed

#29834 Use constructor injection for mandatory references
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfigurator.java
Labels: CLA Signed

#29839 Remove beta flag in InstantOn header for Jakarta Authorization
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization-2.0/io.openliberty.appAuthorization-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization-2.1/io.openliberty.appAuthorization-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization-3.0/io.openliberty.appAuthorization-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/jacc-1.5/com.ibm.websphere.appserver.jacc-1.5.feature
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/EJBAnnTestBase.java
Labels: CLA Signed

#29830 FutureEMBuilder output full exception for caught throwable
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/logging.properties
Labels: team:Zombie Apocalypse, CLA Signed

#29832 Update Jakarta Authorization 3.0 implementation
  dev/com.ibm.ws.security.authorization.jacc.ejb/src/com/ibm/ws/security/authorization/jacc/ejb/impl/EJBSecurityValidatorImpl.java
  dev/com.ibm.ws.security.authorization.jacc.web/src/com/ibm/ws/security/authorization/jacc/web/impl/WebSecurityValidatorImpl.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/PolicyProxy.java
  dev/com.ibm.ws.security.authorization.jacc/src/io/openliberty/security/authorization/jacc/internal/proxy/JavaSePolicyProxyImpl.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/com/ibm/wsspi/security/authorization/jacc/ProviderService.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/JakartaPolicyFactoryProxyImpl.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/ProviderServiceProxyImpl.java
  dev/io.openliberty.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/provider/JaccPolicyProxy.java
  dev/io.openliberty.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/provider/PolicyFactoryImpl.java
  dev/io.openliberty.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/service/ProviderServiceImpl.java
Labels: CLA Signed, team:Performance

#29840 Don't reduce transaction timeout in simple WSAT tests
  dev/com.ibm.ws.wsat.migration_fat.1/fat/src/tests/SimpleTest.java
Labels: noproductcode, CLA Signed

#29824 document refreshServerXMLFromPublish paramater
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29837 Backport MWRAPPER-150
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/mvnw
Labels: noproductcode, CLA Signed

#29836 NLS messages for one or more repositories
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/RecordTransformer.java
  dev/io.openliberty.data.internal.persistence/test/io/openliberty/data/internal/persistence/service/GenerateEntityClassBytesTest.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29853 Consolidate Postgresql constants
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.lease/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.hadb_fat.postgresql.retriablecodes/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.6/fat/src/tests/DBRerouteTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.8/fat/src/tests/DBRerouteRecoveryTest.java
Labels: CLA Signed

#29806 Update ASM in OL to 9.7.1 (Java 24)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
  dev/com.ibm.ws.org.objectweb.asm/src/io/openliberty/asm/ASMHelper.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
Labels: team:Zombie Apocalypse, CLA Signed, Java 24

#29854 Recreate OpenLiberty#29460
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Participant.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, in:JPA, CLA Signed

#29850 Enable "LibbyBot" checks to run as part of personal pipeline
  .ci-orchestrator/checks.yml
  .ci-orchestrator/pb.yml
  .ci-orchestrator/pbRTCBuild.yml
Labels: CLA Signed

#29864 Make toString output consistent with Liberty trace
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextServiceWithExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ContextualDefaultExecutor.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ScheduledTask.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/UnusableExecutor.java
  dev/com.ibm.ws.jca/src/com/ibm/ws/jca/service/EndpointActivationService.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/StatementCacheKey.java
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
Labels: team:Zombie Apocalypse, CLA Signed

#29857 Tolerate slow systems in EJB timer FAT
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#29862 Remove comparison annotations that are not in Jakarta Data
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Items.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/PrimeNumbers.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Reservations.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Shipments.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Towns.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Is.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/Contains.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/EndsWith.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/GreaterThan.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/GreaterThanEqual.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/In.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/LessThan.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/LessThanEqual.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/Like.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/StartsWith.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/comparison/package-info.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/function/IgnoreCase.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/function/Not.java
Labels: team:Zombie Apocalypse, CLA Signed

#29872 JAX-WS: Servlet feature is added to prevent FeatureReplacementAction replacement issue
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableDefaultValidationTestServer/global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableDefaultValidationTestServer/server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableDefaultValidationTestServer/servicename-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/incorrect-servicename-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/servicename-false-global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/servicename-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/servicename-true-global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationTestServer/servicename-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/incorrect-portname-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/portname-false-global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/portname-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/portname-true-global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/portname-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/EnableSchemaValidationWebServiceTestServer/server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/GzipInterceptorsTestServer/server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/incorrect-servicename-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-false-global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-false-global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-true-global-false-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-true-global-true-server.xml
  dev/io.openliberty.jaxws.config_fat/publish/files/IgnoreUnexpectedElementConfigTestServer/servicename-true-server.xml
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#29858 Fix Machine.getOSVersion()
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/Machine.java
Labels: noproductcode, CLA Signed, team:Performance

#29848 Test Connectors Inbound Security with Instant On
  dev/com.ibm.ws.jca_fat/bnd.bnd
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/FATSuite.java
  dev/com.ibm.ws.jca_fat/fat/src/com/ibm/ws/jca/fat/regr/InboundSecurityCheckpointTest.java
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr.checkpoint/bootstrap.properties
  dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat.regr.checkpoint/server.xml
Labels: noproductcode, CLA Signed

#29860 Disable MP Health 2.0 FAT traces
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/bootstrap.properties
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/ApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DelayedHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/DifferentAppNameHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/FailedApplicationStateHealthCheck/server.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat/publish/servers/MultipleHealthCheck/server.xml
Labels: noproductcode, CLA Signed

#29873 Reduce testcontainer restarts
  dev/com.ibm.ws.wsat.migration_fat.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.migration_fat.6/fat/src/tests/DBRerouteTest.java
Labels: noproductcode, CLA Signed

#29783 Avoid waiting for recovery when recovery failed
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
Labels: CLA Signed

#29892 named query parameters and remove IdClass workarounds
  dev/io.openliberty.data.1.0.internal/src/io/openliberty/data/internal/v1_0/Data_1_0.java
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Towns.java
Labels: team:Zombie Apocalypse, CLA Signed

#29846 Add xdump for strange NoClassMethodError
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29891 Adjusting case sensitivity on cookie attribute regex on OIDC test
  dev/com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientCookieVerificationTests.java
Labels: noproductcode, CLA Signed

#29877 Allow configuration of OpenAPI output version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MpOpenAPIElement.java
  dev/io.openliberty.io.smallrye.openapi4.core/bnd.bnd
  dev/io.openliberty.io.smallrye.openapi4.jaxrs/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/src/io/openliberty/microprofile/openapi20/internal/services/impl/OpenAPIVersionConfig20Impl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal.servlet/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal.servlet/src/io/openliberty/microprofile/openapi20/internal/servlet/ApplicationServlet.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/OpenAPIVersionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/services/OpenAPIVersionConfig.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/MessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/test/io/openliberty/microprofile/openapi20/internal/TestOpenAPIVersion.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/OpenAPIVersionTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/VersionTestApp.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/VersionTestData.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/VersionTestResource.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/VersionTestServer/bootstrap.properties
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/VersionTestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/VersionTestServer/server.xml
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/src/io/openliberty/microprofile/openapi31/internal/services/impl/OpenAPIVersionConfig31Impl.java
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/src/io/openliberty/microprofile/openapi40/internal/services/impl/OpenAPIVersionConfig40Impl.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: ID reviewed, CLA Signed

#29890 Fix typo in error message
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
Labels: noproductcode, CLA Signed

#29907 28009 consolidate basic delivery delay test code
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#29911 Trace server config before updating
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29773 Add JDBC Checkpoint Batch test
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/CDITestCheckpoint.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/DynamicConfigRule.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/FATSuite.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/JPAPersistenceManagerImplTest.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/JdbcConfigTestCheckpoint.java
  dev/com.ibm.ws.jbatch.open_fat/publish/files/JDBCPersistenceCheckpoint/jdbc.config.myschema1.server.xml
  dev/com.ibm.ws.jbatch.open_fat/publish/files/JDBCPersistenceCheckpoint/jdbc.config.myschema1.tp1.server.xml
  dev/com.ibm.ws.jbatch.open_fat/publish/files/JDBCPersistenceCheckpoint/jdbc.config.myschema1.tp2.server.xml
  dev/com.ibm.ws.jbatch.open_fat/publish/files/JDBCPersistenceCheckpoint/jdbc.config.myschema2.server.xml
  dev/com.ibm.ws.jbatch.open_fat/publish/servers/batchFAT/bootstrap.properties
Labels: noproductcode, CLA Signed

#29471 HTTP Stats Performance Changes
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/metrics/MetricsManager.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
Labels: CLA Signed

#29919 Removing case sensitive check on cookie attributes
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/CookieNameOidcClientTests.java
Labels: noproductcode, CLA Signed

#29469 if server xml is deleted, do not remove configuration
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigFileMonitor.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigRefresher.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#29904 fix mislabeled elements
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed

#29916 Fix #29915 - audit partitionedCookie changes
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/internal/WebAppSecurityConfigImpl.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/publish/servers/servlet40_partitionedSecurity/jvm.options
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#29926 Fix Class path for com.ibm.ws.security.oidc.client_fat.spnego
  dev/com.ibm.ws.security.oidc.client_fat.spnego/bnd.bnd
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
Labels: noproductcode, CLA Signed

#29886 Fix test_SPNEGO_OIDC_CreateClientWithEveryParamVariation1
  dev/com.ibm.ws.security.oidc.server_fat.spnego/bnd.bnd
Labels: noproductcode, CLA Signed

#29936 fix duplicate ordering error
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Orders.java
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#29924 build: use valid environment variable names
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#29930 Updates testcontainers 1.20.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/src/componenttest/containers/ExternalDockerClientFilter.java
  dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
  dev/io.openliberty.org.testcontainers/bnd.bnd
Labels: team:Zombie Apocalypse, CLA Signed

#29931 check if versioned feature exists before processing
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
Labels: CLA Signed

#29910 Add server.xml config for OpenAPI Info section
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MpOpenAPIElement.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MpOpenAPIInfoElement.java
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/src/io/openliberty/microprofile/openapi20/internal/services/impl/OpenAPIInfoConfig20Impl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal.servlet/src/io/openliberty/microprofile/openapi20/internal/servlet/ApplicationServlet.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.openapi.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/OpenAPIInfoConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/services/OpenAPIInfoConfig.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/MessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigServerXMLTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPITestUtil.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/OpenAPIVersionTest.java
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/src/io/openliberty/microprofile/openapi31/internal/services/impl/OpenAPIInfoConfig31Impl.java
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/src/io/openliberty/microprofile/openapi40/internal/services/impl/OpenAPIInfoConfig40Impl.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: CLA Signed

#29943 mpOpenAPI-4.0: Default to including all modules
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal.services/src/io/openliberty/microprofile/openapi20/internal/services/impl/ModuleSelectionConfig20Impl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ModuleSelectionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigTest.java
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/bnd.bnd
  dev/io.openliberty.microprofile.openapi.3.1.internal.services/src/io/openliberty/microprofile/openapi31/internal/services/impl/ModuleSelectionConfig31Impl.java
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/bnd.bnd
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/src/io/openliberty/microprofile/openapi40/internal/services/impl/ModuleSelectionConfig40Impl.java
Labels: CLA Signed

#29948 Terminate tests when processing is done
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLSharedServerLeaseLog.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.ws.transaction.hadb_fat.derby.1/fat/src/tests/FailoverTestLease.java
Labels: CLA Signed

#29956 Couple of small cleanup items
  dev/io.openliberty.mpTelemetry.2.0.thirdparty/.classpath
  dev/io.openliberty.mpTelemetry.2.0.thirdparty/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.mpTelemetry.2.0.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/jpa/jpql/parser/AbstractPathExpression.java
Labels: CLA Signed, team:Performance

#29953 Remove temp test file in finally block
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/utils/PathUtils.java
Labels: CLA Signed

#29932 interrupt virtual threads when application component stops
  dev/com.ibm.ws.concurrent/bnd.bnd
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedForkJoinWorkerThread.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedVirtualThreadAction.java
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ThreadGroupTracker.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/fat/src/test/jakarta/concurrency/Concurrency31Test.java
  dev/com.ibm.ws.concurrent_fat_jakarta_11/test-applications/Concurrency31TestWeb/src/test/jakarta/concurrency31/web/Concurrency31TestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#29929 (LibertyOP Test) Removing case sensitivity from cookie attribute
  dev/com.ibm.ws.security.social_fat.LibertyOP.1/fat/src/com/ibm/ws/security/social/fat/LibertyOP/LibertyOP_CookieVerificationTests.java
Labels: noproductcode, CLA Signed

#29923 Don't import jsonsupport
  dev/com.ibm.ws.jmx.connector.server.rest/bnd.bnd
Labels: CLA Signed

#29957 mpOpenAPI module selection further tests
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigBothTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigServerXMLTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeServerXMLTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeServerXMLTestWithUpdate.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/utils/OpenAPITestUtil.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeTestServer/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPIMergeWithServerXMLTestServer/server.xml
Labels: CLA Signed

#29955 extra trace to diagnose the failed Otel pushes
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerJSFServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerJSPServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerJustServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerRestServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/ContainerServletServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/JSFServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/JSPServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleRestServer/bootstrap.properties
  dev/io.openliberty.http.monitor_fat/publish/servers/SimpleServletServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/ConnPoolMetricsServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/LibertyMetricServer/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.internal.monitor_fat/publish/servers/SessionsMetricsServer/bootstrap.properties
Labels: noproductcode, CLA Signed

#29972 Correct build path for OpenAPI 4.0 unit tests
  dev/io.openliberty.microprofile.openapi.4.0.internal.services/bnd.bnd
Labels: CLA Signed

#29941 Merge different delivery delay tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/fat/src/com/ibm/ws/messaging/jms20/deliverydelay/fat/DelayFullTest.java
Labels: noproductcode, CLA Signed

#29965 refactor: use Phaser for EventSemaphore
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/EventSemaphore.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/impl/RecoveryManager.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
Labels: CLA Signed

#29905 error detection for query language parameters
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/_Voter.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#29947 Stop using tccl
  dev/io.openliberty.org.apache.commons.logging/src/org/apache/commons/logging/LogFactory.java
  dev/io.openliberty.org.apache.commons.logging_fat/.classpath
  dev/io.openliberty.org.apache.commons.logging_fat/.project
  dev/io.openliberty.org.apache.commons.logging_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.org.apache.commons.logging_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.org.apache.commons.logging_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.apache.commons.logging_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.org.apache.commons.logging_fat/bnd.bnd
  dev/io.openliberty.org.apache.commons.logging_fat/build.gradle
  dev/io.openliberty.org.apache.commons.logging_fat/fat/src/io/openliberty/checkpoint/fat/CommonsLoggingTCCLTest.java
  dev/io.openliberty.org.apache.commons.logging_fat/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.org.apache.commons.logging_fat/feature_fat.bnd
  dev/io.openliberty.org.apache.commons.logging_fat/io.openliberty.commons.logging.test.bundle.bnd
  dev/io.openliberty.org.apache.commons.logging_fat/publish/files/features/test.commons.logging-1.0.mf
  dev/io.openliberty.org.apache.commons.logging_fat/publish/servers/commonsLoggingServer/bootstrap.properties
  dev/io.openliberty.org.apache.commons.logging_fat/publish/servers/commonsLoggingServer/server.xml
  dev/io.openliberty.org.apache.commons.logging_fat/test-applications/testCommonsLoggingServlet/src/io/openliberty/commons/logging/test/app/TestCommonsLogging.java
  dev/io.openliberty.org.apache.commons.logging_fat/test-bundles/io.openliberty.commons.logging.test.bundle/src/io/openliberty/commons/logging/test/bundle/DoTest.java
  dev/io.openliberty.org.apache.commons.logging_fat/test-bundles/io.openliberty.commons.logging.test.bundle/src/io/openliberty/commons/logging/test/bundle/package-info.java
Labels: CLA Signed

#29969 Replace @-char in cached lib container path
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/LibraryGeneration.java
Labels: CLA Signed

#29879 set heap max to 2gb
  dev/io.openliberty.microprofile.rest.client.4.0.internal_fat_tck/publish/servers/FATServer/jvm.options
Labels: noproductcode, CLA Signed

#29920 Add TCKRunner logging configuration
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/logging.properties
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/publish/tckRunner/tck/standalone.pom.xml
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherFull.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncherWeb.java
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.jakarta.concurrency.3.1_fat_tck/publish/tckRunner/tck/standalone.pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/logging.properties
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/pom.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/platform/verification.xml
  dev/io.openliberty.jakarta.data.1.0_fat_tck/publish/tckRunner/standalone/pom.xml
Labels: enhancement, team:Zombie Apocalypse, noproductcode, CLA Signed

#29942 29876 app naming
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ModuleSelectionConfigImpl.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigServerXMLTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigTest.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
  dev/io.openliberty.microprofile.openapi.internal.common/src/io/openliberty/microprofile/openapi/internal/common/OpenAPIAppConfigProviderImpl.java
Labels: ID reviewed, CLA Signed

#29978 update metatype doc
  dev/com.ibm.ws.ssl/resources/OSGI-INF/l10n/metatype.properties
Labels: CLA Signed

#29977 Use OpenAPI version config before validating
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFive/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFour/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerOne/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerSix/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerThree/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/server.xml
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/ValidationComponent.java
  dev/io.openliberty.microprofile.openapi.4.0.internal_fat/fat/src/io/openliberty/microprofile/openapi40/fat/FATSuite.java
  dev/io.openliberty.microprofile.openapi.4.0.internal_fat/fat/src/io/openliberty/microprofile/openapi40/fat/validation/ValidationTestCrossVersion.java
  dev/io.openliberty.microprofile.openapi.4.0.internal_fat/fat/src/io/openliberty/microprofile/openapi40/fat/validation/validation-openapi30.yml
  dev/io.openliberty.microprofile.openapi.4.0.internal_fat/publish/servers/OpenAPIValidationServer/jvm.options
Labels: CLA Signed

#29991 mpOpenAPI: Repeat ShutdownTest
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/shutdown/ShutdownTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPITestServer/jvm.options
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPITestServer/server.xml
Labels: noproductcode, CLA Signed

#29990 Correct casing for mpOpenAPI.info element name
  dev/io.openliberty.microprofile.openapi.internal.common/resources/OSGI-INF/l10n/metatype.properties
Labels: ID reviewed, CLA Signed

#29959 Fix delivery delay classic api tests
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#29995 feat: add immutable BitSet
  dev/com.ibm.ws.jndi.iiop/src/com/ibm/ws/jndi/iiop/ImmutableBitSet.java
Labels: CLA Signed

#29895 Add step for creating code checklist
  .ci-orchestrator/checks.yml
  .ci-orchestrator/pb.yml
  .ci-orchestrator/pbRTCBuild.yml
Labels: CLA Signed

#30003 Try test again to accout for slow systems
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/MapCacheTest.java
Labels: noproductcode, CLA Signed

#29971 test: finish unit testing TCKResultInfo
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/build.gradle
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsWriter.java
  dev/fattest.simplicity/test/componenttest/topology/utils/tck/TCKResultInfoTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#29968 Enable database rotation for Jakarta Data DDLGen testing
  dev/com.ibm.ws.concurrent.persistent_fat/fat/src/com/ibm/ws/concurrent/persistent/fat/DDLGenScriptHelper.java
  dev/com.ibm.ws.jbatch.fat.common/src/com/ibm/ws/jbatch/test/BatchRestUtils.java
  dev/com.ibm.ws.jbatch.open.bonuspayout_fat/fat/src/batch/fat/util/BatchFATHelper.java
  dev/com.ibm.ws.jbatch.open.partition_fat/fat/src/batch/fat/util/BatchFATHelper.java
  dev/com.ibm.ws.jbatch.open.security_fat/fat/src/batch/fat/util/BatchFATHelper.java
  dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/util/BatchFATHelper.java
  dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
  dev/fattest.simplicity/src/componenttest/topology/utils/DDLGenScript.java
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DDLGenScriptHelper.java
  dev/io.openliberty.data.internal_fat_ddlgen/fat/src/test/jakarta/data/ddlgen/DDLGenTest.java
  dev/io.openliberty.data.internal_fat_ddlgen/fat/src/test/jakarta/data/ddlgen/FATSuite.java
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/bootstrap.properties
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/server.xml
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/DDLGenTestServlet.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Part.java
  dev/io.openliberty.data.internal_fat_ddlgen/test-applications/DDLGenTestApp/src/test/jakarta/data/ddlgen/web/Parts.java
Labels: team:Zombie Apocalypse, CLA Signed

#30004 Revert "Update Open Liberty Welcome Page"
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/img/twitter_logo.png
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html
Labels: CLA Signed

#29981 Restore original server configuration
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/DecodeUrlPlusSignTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#29952 when server.xml is deleted throw an error
  dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigFileMonitor.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigRefresher.java
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ServerXMLConfiguration.java
  dev/com.ibm.ws.config_fat/fat/src/test/server/config/ServerConfigTest.java
Labels: noproductcode, CLA Signed

#30012 Remove -Xdump for unexplained NCDFE on the Providers class
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#29993 Issue 277: Upgrade Hibernate Core to 5.3.20
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.tx.jta_fat_hibernate/bnd.bnd
Labels: noproductcode, CLA Signed

#30001 repository method sort parameters for pagination
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#30020 fix spnego tests when machine hostname cannot be determined
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/InitClass.java
Labels: noproductcode, CLA Signed, team:Core Security

#29984 Issue #29983: Add CWWKE0702E to FeatureErrors.java
  dev/build.featureStart.base/src/com/ibm/ws/test/featurestart/features/FeatureErrors.java
Labels: noproductcode, CLA Signed
