Repository OpenLiberty/open-liberty, pull requests merged in 2025-05, with the labels that each got.

#31271 Run MP Reactive Messaging Kafka tests with Kafka client 4.0.0
  dev/com.ibm.websphere.org.eclipse.microprofile/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.secure_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.secure_fat/publish/servers/CheckpointSimpleRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.secure_fat/publish/servers/ContextRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.secure_fat/publish/servers/CustomContextRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging.kafka.secure_fat/publish/servers/SimpleRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/build.gradle
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/KafkaPublisherVerification.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/fat/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/tck/ReactiveStreamsTckTest.java
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/ConcurrentRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/ContextRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/CustomContextRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/JsonbRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SharedLibRxMessagingServer/server.xml
  dev/com.ibm.ws.microprofile.reactive.messaging_fat/publish/servers/SimpleRxMessagingServer/server.xml
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat.common/include-kafka-client.gradle
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat.common/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/common/KafkaUtils.java
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat.common/src/com/ibm/ws/microprofile/reactive/messaging/fat/kafka/common/permissions.xml
  dev/io.openliberty.microprofile.reactive.messaging.internal_fat/build.gradle
Labels: noproductcode, CLA Signed

#31430 Correct spelling of customized
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/accesslists/Utils.java
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#30941 Update where the OIDC Provider is set in thread
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
  dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OidcClientRequest.java
  dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebProviderAuthenticatorProxy.java
Labels: CLA Signed

#31420 Fix BasicTest.testNoDefaultKeyTest
  dev/com.ibm.ws.security.client_fat/test-applications/BasicCalculatorClient.jar/src/com/ibm/websphere/samples/technologysamples/basiccalcclient/BasicCalculatorClientJ2EEMain.java
Labels: noproductcode, CLA Signed

#31444 Add product extensions to auto feature check
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureUtilities.java
Labels: noproductcode, CLA Signed, team:Performance

#31433 Fix for Data deadlock with EJB in .war
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestEJB.java
Labels: CLA Signed

#31440 entity with multiple of same embedded type
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Segment.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31434 Allow attribute converter for ZonedDateTime
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/EntityManagerBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Util.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/DataJavaGlobalTest.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/Reminder.java
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed

#31438 Speed up MP OpenAPI FAT
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/FATSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFive.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFour.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestSix.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestTwo.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/ValidationSuite.java
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestFive.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestFour.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestOne.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestSix.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestThree.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/validationTestTwo.yaml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServer/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFive/dropins/Validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFour/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFour/dropins/Validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerFour/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerOne/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerOne/dropins/openapi_validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerOne/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerSix/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerSix/dropins/Validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerSix/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerThree/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerThree/dropins/Validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerThree/server.xml
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/bootstrap.properties
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/dropins/openapi_validation.war
  dev/com.ibm.ws.microprofile.openapi_fat/publish/servers/validationServerTwo/server.xml
Labels: noproductcode, CLA Signed

#31464 Revert "Fix for Data deadlock with EJB in .war"
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestEJB.java
Labels: team:Zombie Apocalypse

#31421 Add Spring data/JPA integration test for Spring Framework V5 and V6 app
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.fat20.data.app/.classpath
  dev/com.ibm.ws.springboot.fat20.data.app/.gitignore
  dev/com.ibm.ws.springboot.fat20.data.app/.project
  dev/com.ibm.ws.springboot.fat20.data.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.fat20.data.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.fat20.data.app/bnd.bnd
  dev/com.ibm.ws.springboot.fat20.data.app/build.gradle
  dev/com.ibm.ws.springboot.fat20.data.app/springboot.gradle
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/AccessingDataJpaApplication.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/CustomerConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/EmployeeConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/TestPersistence.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/WebContext.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/customer/Customer.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/customer/CustomerRepository.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/employee/Employee.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/employee/EmployeeRepository.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/resources/META-INF/persistence.xml
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/webapp/WEB-INF/web.xml
  dev/com.ibm.ws.springboot.fat20_fat/bnd.bnd
  dev/com.ibm.ws.springboot.fat20_fat/build.gradle
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAAppAbstractTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAAppTests20War.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests20War.java
  dev/io.openliberty.springboot.fat30.data.app/.classpath
  dev/io.openliberty.springboot.fat30.data.app/.gitignore
  dev/io.openliberty.springboot.fat30.data.app/.project
  dev/io.openliberty.springboot.fat30.data.app/.settings/bndtools.core.prefs
  dev/io.openliberty.springboot.fat30.data.app/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.springboot.fat30.data.app/bnd.bnd
  dev/io.openliberty.springboot.fat30.data.app/build.gradle
  dev/io.openliberty.springboot.fat30.data.app/springboot.gradle
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/AccessingDataJpaApplication.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/CustomerConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/EmployeeConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/TestPersistence.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/WebContext.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/customer/Customer.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/customer/CustomerRepository.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/employee/Employee.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/employee/EmployeeRepository.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/resources/META-INF/persistence.xml
  dev/io.openliberty.springboot.fat30.data.app/src/main/resources/application.properties
  dev/io.openliberty.springboot.fat30.data.app/src/main/webapp/WEB-INF/web.xml
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/java/io/openliberty/springboot/support/version30/test/transaction/app/ManagingTransactionsApplication.java
  dev/io.openliberty.springboot.fat30_fat/bnd.bnd
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAAppAbstractTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAAppTests30War.java
Labels: CLA Signed

#31371 Update to MyFaces 4.0.3 with MYFACES-4721 (autocomplete update)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.faces.4.0.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/config/webparameters/MyfacesConfig.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/ViewPoolProcessor.java
Labels: in:Web Components, CLA Signed, team:Sirius

#31416 update tested.features for com.ibm.ws.jaxrs.2.1.client_fat
  dev/com.ibm.ws.jaxrs.2.1.client_fat/bnd.bnd
Labels: in:JAX-RS, noproductcode, CLA Signed

#31396 Use childOption for ServerBootstrap SO_LINGER
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPConfigurationImpl.java
  dev/io.openliberty.netty.internal.impl/test/io/openliberty/netty/internal/impl/NettyFrameworkImplTest.java
Labels: in:Transport, CLA Signed, team:Sirius

#31355 Remove Auto-generated catch block comment in ConnectionDataGroup
  dev/com.ibm.ws.messaging.comms.client/src/com/ibm/ws/sib/jfapchannel/impl/octracker/ConnectionDataGroup.java
Labels: in:Transport, CLA Signed, team:Sirius

#31458 fix for RTC defect 304499
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, CLA Signed

#31461 Release Mp7.1 as beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.mpVersion-7.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpOpenAPI-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.versionless.mpTelemetry-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpCompatible-7.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.openapi-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/microProfile-7.1/io.openliberty.microProfile-7.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpOpenAPI-4.1/io.openliberty.mpOpenAPI-4.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpTelemetry-2.1/io.openliberty.mpTelemetry-2.1.feature
Labels: CLA Signed

#31382 Increase peerTimeBeforeStale for testMultiPeerTakeoverFailure
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
Labels: noproductcode

#31428 Skip zOS for agent related tests
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULDuplicateTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/JULLogServletTest.java
Labels: noproductcode, CLA Signed

#31470 Spring data jpa hibernate tests
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/AccessingDataJpaApplication.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/HibernatePersistenceCustomerConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/HibernatePersistenceEmployeeConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/LibertyPersistenceCustomerConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/LibertyPersistenceEmployeeConfiguration.java
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAHibernateAppTests20War.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JPALibertyAppTests20War.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/MultipleApplicationsNotSupported20.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLMutualAuthTests15.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/AccessingDataJpaApplication.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/HibernatePersistenceCustomerConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/HibernatePersistenceEmployeeConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/LibertyPersistenceCustomerConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/LibertyPersistenceEmployeeConfiguration.java
  dev/io.openliberty.springboot.fat30.data.app/src/main/resources/application.properties
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ApplicationArgsTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ApplicationStartedEventTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/CDITests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebFluxTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/CommonWebServerTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigActuatorXMLOverrideTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigDropinRootTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigServerXMLOverrideTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/ConfigSpringBootApplicationTagWarTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/EnableSpringBootTraceTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAAppAbstractTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JPAHibernateAppTests30War.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JPALibertyAppTests30War.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/MissingSslFeatureTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/MultipleApplicationsNotSupported30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/SSLCommonTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/TemplateTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/UnsupportedConfigWarningTestBase.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/WebSocketAbstractTests.java
Labels: CLA Signed

#31478 Access repository from startup event
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/DataJavaGlobalTest.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/DataGlobalRestApp.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/webapp/DataGlobalWebAppServlet.java
Labels: team:Zombie Apocalypse, noproductcode

#31471 Jakarta Data Repository in EJB application
  dev/io.openliberty.data.internal_fat_datastore/.classpath
  dev/io.openliberty.data.internal_fat_datastore/bnd.bnd
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DataStoreTest.java
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/server.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/DataEJBAppBean.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/EJBAppDSRefRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/EJBAppEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreEJBApp].module[DataStoreEJBApp.jar].databaseStore[java.module.env.jdbc.ServerDataSourceRef]_JakartaData.ddl
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31488 Adding Data test for Observes Initialized ApplicationScope
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/webapp/DataGlobalWebAppServlet.java
Labels: noproductcode

#31485 Add sources and javadoc for MyFaces 2.3.11
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31491 EJB method that observes startup uses repository
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/DataEJBAppBean.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/DataEJBAppBeanInterface.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/DataStoreTestEJB.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode

#31042 Prevent different versions of mpHealth from loading at the same time
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealthCompatible-0.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealthCompatible-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-1.0/com.ibm.websphere.appserver.mpHealth-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.0/com.ibm.websphere.appserver.mpHealth-2.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.1/com.ibm.websphere.appserver.mpHealth-2.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-2.2/com.ibm.websphere.appserver.mpHealth-2.2.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.0/com.ibm.websphere.appserver.mpHealth-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-3.1/com.ibm.websphere.appserver.mpHealth-3.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.classpath
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.project
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.health.4.0.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal_fat/cognitiveMetadata.yml
  dev/io.openliberty.microprofile.health.4.0.internal_fat/fat/src/io/openliberty/microprofile/health40/fat/FATSuite.java
  dev/io.openliberty.microprofile.health.4.0.internal_fat/fat/src/io/openliberty/microprofile/health40/fat/MPHealthConflictingFeaturesTest.java
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/.gitignore
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And10/bootstrap.properties
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And10/server.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And22/bootstrap.properties
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And22/server.xml
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And31/bootstrap.properties
  dev/io.openliberty.microprofile.health.4.0.internal_fat/publish/servers/MPHealth40And31/server.xml
Labels: CLA Signed

#31234 Create More Faces CheckPoint Tests
  dev/com.ibm.ws.jsf.2.2_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentRendererTests.java
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/com.ibm.ws.jsf.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23UIRepeatConditionTests.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE11

#31479 Add open port retries for MP Health 31 FAT
  dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckFastTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/SlowAppStartupHealthCheckFast/server.xml
Labels: noproductcode, CLA Signed

#31499 SessionCacheTwoServerTimeoutTest: server start error
  dev/com.ibm.ws.session.cache_fat/fat/src/com/ibm/ws/session/cache/fat/SessionCacheTwoServerTimeoutTest.java
Labels: noproductcode, CLA Signed

#31494 fix: increase connectionWaitTimeout for UCP tests
  dev/com.ibm.ws.jdbc_fat_oracle/publish/servers/com.ibm.ws.jdbc.fat.oracle.ucp/server.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed

#31437 Update Expression Language 6.0 to 11.0.6
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#31435 Update WebContainer metatype descriptions
  dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
Labels: in:Web Components, CLA Signed, team:Sirius

#31495 Fix AutoComplete Logging in Faces
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#31475 Current soln to ISE encountered when Health check is invoked inbetwee…
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/AppTracker40Impl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthCheck40ServiceImpl.java
Labels: CLA Signed

#31459 Refactor tel 2.1.internal
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpTelemetry2.1.ee-9.0.feature
  dev/io.openliberty.microprofile.telemetry.2.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/internal/semconv/SemconvConstantsAccessorImpl.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/.classpath
  dev/io.openliberty.microprofile.telemetry.2.1.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.1.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.telemetry.2.1.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.telemetry.2.1.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.telemetry.2.1.internal/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.1.internal/original.bnd
  dev/io.openliberty.microprofile.telemetry.2.1.internal/resources/META-INF/services/jakarta.ws.rs.ext.Providers
  dev/io.openliberty.microprofile.telemetry.2.1.internal/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderListener
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/cdi/OpenTelemetryMeterProducer.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/cdi/SPIMetaData.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/cdi/TelemetryExtension.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/cdi/WithSpanInterceptor.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/cdi/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/connpool/MPTelemetryConnectionPoolMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/connpool/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/helper/InstrumenterActivator.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/helper/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/http/MPTelemetryHTTPMetricsAdapterImpl.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/http/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/info/OpenTelemetryInfoFactoryImpl.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/info/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryClientFilter.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryContainerFilter.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryRestClientBuilderListener.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryServletContainerInitializer.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/jakarta/TelemetryClientBuilderListener.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/jakarta/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/javax/TelemetryJaxRsProviderRegister.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/javax/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/package-info.java
  dev/io.openliberty.microprofile.telemetry.2.1.internal/transformed.bnd
  dev/io.openliberty.microprofile.telemetry.2.1.logging.internal/src/io/openliberty/microprofile/telemetry21/internal/semconv/SemconvConstantsAccessorImpl.java
  dev/io.openliberty.microprofile.telemetry.logging.internal.common/src/io/openliberty/microprofile/telemetry20/logging/internal/semconv/SemcovConstantsAccessor.java
Labels: CLA Signed

#31497 repository used from Observes Startup method of EJB in WAR
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/DataEJBInWebModule.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web2/DataStoreSecondServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#31395 add SystemProperty 'io.openliberty.restfulws.prioritizeClientBuilderS…
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/SimpleSSLMultipleServersClientAPITest.java
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/.gitignore
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/bootstrap.properties
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/jvm.options
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/resources/security/defaultkey.p12
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/resources/security/defaulttrust.p12
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/resources/security/key.jks
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/resources/security/trust.jks
  dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.SimpleSSLMultiServerTestA_mismatching_default/server.xml
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/simpleSSL/src/io/openliberty/jaxrs/client/fat/simpleSSL/multi/servlet/clientapi/SimpleSSLMultipleServersClientAPIClientTestServlet.java
  dev/io.openliberty.restfulWS.internal.ssl/src/io/openliberty/restfulWS/internal/ssl/component/SslClientBuilderListener.java
Labels: CLA Signed

#31500 refactor: update postgres krb5 image
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/PostgresKerberosContainer.java
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/postgres-krb5/17.0.0.1/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/postgres-krb5/17.0.0.1/files/krb5.conf
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/postgres-krb5/17.0.0.1/startup/db_setup.sh
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31496 doc: update cloudant metadata
  dev/com.ibm.ws.rest.handler.validator.cloudant_fat/cognitiveMetadata.yml
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30839 Extending the scope of the maxFiles parameter in logging configuration
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/LoggerOffThread.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/LoggerOnThread.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/AccessLogRolloverTest.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-default-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-invalid-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-zero-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/common.xml
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/server.xml
Labels: in:Transport, CLA Signed, team:Sirius

#31489 Tolerate ISE in case of recovery log deletion
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
Labels: noproductcode, CLA Signed

#31412 Set dump output directory to a location that will be uploaded
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode, CLA Signed

#31516 Revert "Set dump output directory to a location that will be uploaded"
  dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.concurrent.mp.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.concurrent.mp_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.2_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.3_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.config.1.4_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.graphql_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.1.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.0_fat_tck/publish/tckRunner/tck/pom.xml
  dev/com.ibm.ws.microprofile.health.2.1_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.rest.client.3.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode

#30066 proxy auth for https connection
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/VerifySignatureUtility.java
Labels: CLA Signed

#31502 Enable MyFaces 4.0.3 JavaDoc and Sources
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31472 Stop logging error from JDBC driver when closing connection
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/MCWrapper.java
Labels: team:Zombie Apocalypse, CLA Signed

#31510 Netty: Remove unused imports from `NettyInboundChain`
  dev/com.ibm.ws.messaging.comms.server/src/com/ibm/ws/jfap/inbound/channel/NettyInboundChain.java
Labels: in:Transport, CLA Signed, team:Sirius

#31517 feat: add "inspect" command to OSGi console
  dev/com.ibm.ws.kernel.service/bnd.bnd
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/server/internal/InspectCommand.java
Labels: CLA Signed

#31090 Update MyFaces to 4.1.1
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSFSimpleHtmlUnit.java
  dev/io.openliberty.faces.4.1.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/config/webparameters/MyfacesConfig.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#31512 Tolerate ResourceAllocationException in dynamic embedded container au…
  dev/io.openliberty.transaction.containerAuth_fat.derby/fat/src/tests/ContainerAuthTest.java
Labels: noproductcode, CLA Signed

#31225 Update maxOpenConnections tests and update Netty implementation
  dev/io.openliberty.netty.internal.impl/bnd.bnd
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/impl/NettyConstants.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/impl/NettyFrameworkImpl.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/MaxOpenConnectionsHandler.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPChannelInitializerImpl.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPConfigurationImpl.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/MaxOpenConnectionsTest.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/MaxOpenConnectionsTests.java
Labels: in:Transport, team:Sirius

#31521 Null check for RunHealthCheck
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthCheck40ServiceImpl.java
Labels: CLA Signed

#31443 Bump the SSHD Versions for SPNEGO Bucket
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.spnego/build.gradle
  dev/com.ibm.ws.security.spnego.fat.common/bnd.bnd
Labels: CLA Signed

#31538 feat: improve 'inspect' command after demo feedback
  dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/lifecycle/ApplicationPrereqMonitor.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/kernel/server/internal/InspectCommand.java
  dev/com.ibm.ws.logging.core/src/com/ibm/wsspi/logging/Introspector.java
  dev/com.ibm.ws.messaging.common/src/com/ibm/ws/messaging/lifecycle/SingletonMonitor.java
Labels: CLA Signed

#31522 Remove TODO and security exempt line from EE 11 test buckets that don't need it
  dev/com.ibm.ws.concurrent_fat_cdi/publish/servers/concurrent_fat_cdi/bootstrap.properties
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.checkpoint.fat/bootstrap.properties
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/bootstrap.properties
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/bootstrap.properties
  dev/io.openliberty.data.internal_fat_ddlgen/publish/servers/io.openliberty.data.internal.fat.ddlgen/bootstrap.properties
  dev/io.openliberty.data.internal_fat_errorpaths/publish/servers/io.openliberty.data.internal.fat.errpaths/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.checkpoint.fat.jpa/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa/publish/servers/io.openliberty.data.internal.fat.jpa/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa_hibernate/publish/servers/io.openliberty.data.internal.fat.jpa.hibernate.integrate/bootstrap.properties
  dev/io.openliberty.data.internal_fat_jpa_hibernate/publish/servers/io.openliberty.data.internal.fat.jpa.hibernate/bootstrap.properties
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql.container/bootstrap.properties
  dev/io.openliberty.data.internal_fat_nosql/publish/servers/io.openliberty.data.internal.fat.nosql/bootstrap.properties
  dev/io.openliberty.data.internal_fat_validation/publish/servers/io.openliberty.data.internal.fat.validation/bootstrap.properties
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31507 Fix BasicTest.testNoDefaultKeyTest
  dev/com.ibm.ws.security.client_fat/test-applications/BasicCalculatorClient.jar/src/com/ibm/websphere/samples/technologysamples/basiccalcclient/BasicCalculatorClientJ2EEMain.java
Labels: noproductcode, CLA Signed

#31543 Test case needs to specify scale for to prevent it from defaulting to 0
  dev/io.openliberty.data.internal_fat_jpa/fat/src/test/jakarta/data/jpa/DataJPATest.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DemographicInfo.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31294 Refactoring the tests for IgnoreWriteAfterCommit property
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPChannelTest.java
Labels: noproductcode, CLA Signed

#31553 Overlay to update field mapping for java.time.Instant in SQL Server
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/SQLServerPlatform.java
Labels: in:JPA, team:Blizzard, CLA Signed

#31542 Update MpConfig 3.1 TCK repeats
  dev/io.openliberty.microprofile.config.3.1.internal_fat_tck/fat/src/io/openliberty/microprofile/config/internal_fat_tck/Config31TCKLauncher.java
  dev/io.openliberty.microprofile.config.internal_repeat_tests/src/io/openliberty/microprofile/config/fat/repeat/ConfigRepeatActions.java
Labels: noproductcode, CLA Signed

#31534 Enable MyFaces 4.1.1 javadoc and sources
  dev/io.openliberty.jakarta.faces.4.1/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.1/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.1/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius

#31520 Weaving deadlock fix
  dev/org.eclipse.osgi/.classpath
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/serviceregistry/ServiceRegistry.java
Labels: CLA Signed

#31545 Wait for TCP Channel started message in SoReuseAddr test
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/SoReuseAddrTests.java
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#31560 Link open issues to code for reproducing them
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/ShippingAddress.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/ShippingAddresses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/StreetAddress.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31567 Address various TODOs in tests or link back to blocking issues
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Animals.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Apartment.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Participants.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Items.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Cities.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31130 Update to latest 2.3.11, 4.0.3, and 4.1.1 MyFaces for testing
  dev/com.ibm.ws.jsfContainer_fat_2.3/build.gradle
  dev/com.ibm.ws.jsfContainer_fat_2.3/fat/src/com/ibm/ws/jsf/container/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31530 Skip EE9 Repeat on Windows for `com.ibm.ws.jsp.2.3_fat`
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31577 Use database specific method of modifying datasource properties
  dev/io.openliberty.transaction.containerAuth_fat.derby/fat/src/tests/ContainerAuthTest.java
Labels: noproductcode, CLA Signed

#31547 MP OpenAPI translate cache warning messages
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/cache/CacheEntry.java
  dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/MessageConstants.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java
  dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
Labels: ID reviewed, CLA Signed

#31571 Revert "dependency: update testcontainers 1.20.3 -> 1.21.0"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/containers/ImageVerifier.java
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
Labels: team:Zombie Apocalypse, CLA Signed

#31579 Test Coverage Improvement For Jakarta Persistence 3.2
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/.classpath
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/fat/src/com/ibm/ws/jpa/FATSuite.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/fat/src/com/ibm/ws/jpa/jpa32/JakartaPersistenceTest.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/publish/servers/JakartaPersistenceServer/bootstrap.properties 
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/publish/servers/JakartaPersistenceServer/server.xml
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartapersistence/src/io/openliberty/jpa/persistence/tests/web/JakartaPersistenceServlet.java
Labels: noproductcode, in:JPA, CLA Signed

#31584 Update EJB FAT to wait for ports on Z
  dev/com.ibm.ws.ejbcontainer.session.passivation_fat/fat/src/com/ibm/ws/ejbcontainer/session/passivation/tests/StatefulTimeoutTest.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#31540 More MP Health file based health check FATS
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/ConfigTest.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/FATSuite.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/SimpleFileBasedHealthCheckTest.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/utils/Constants.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadCheckIntervalHealthServer/bootstrap.properties
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadCheckIntervalHealthServer/jvm.options
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadCheckIntervalHealthServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadStartupCheckIntervalHealthServer/bootstrap.properties
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadStartupCheckIntervalHealthServer/jvm.options
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/BadStartupCheckIntervalHealthServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongCheckInterval/bootstrap.properties
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongCheckInterval/jvm.options
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongCheckInterval/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongStartupCheckInterval/bootstrap.properties
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongStartupCheckInterval/jvm.options
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServerLongStartupCheckInterval/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/OnlyStartupCheckHealthServer/bootstrap.properties
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/OnlyStartupCheckHealthServer/jvm.options
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/OnlyStartupCheckHealthServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/test-applications/FileHealthCheckApp/src/io/openliberty/microprofile/health/file/healthcheck/app/HealthAppServlet.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/test-applications/FileHealthCheckApp/src/io/openliberty/microprofile/health/file/healthcheck/app/start/wait/five/StartupCheckUpAfterFive.java
Labels: noproductcode, CLA Signed

#31564 Defect 292475: Wait an extra 600ms before making a wsoc connection
  dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/util/wsoc/WsocTestRunner.java
Labels: noproductcode

#31308 Avoid cached data between plugin generation
  dev/com.ibm.ws.http.plugin.merge/src/com/ibm/ws/http/plugin/merge/internal/PluginMergeToolImpl.java
Labels: in:Web Components, CLA Signed, release bug, team:Sirius

#31526 Update Netty AccessListHandler
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPChannelInitializerImpl.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/TcpOptionsDefaultTests.java
Labels: in:Transport, CLA Signed, team:Sirius

#31599 Add versionless compatibility testing to the EE 9, 10 and 11 fat buckets
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/tests/EE10Features.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jarkartaee10/internal/tests/util/FATFeatureResolver.java
  dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jarkartaee10/internal/tests/util/FATFeatureTester.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/EE11Features.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/util/FATFeatureResolver.java
  dev/io.openliberty.jakartaee11.internal_fat/fat/src/io/openliberty/jakartaee11/internal/tests/util/FATFeatureTester.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9FeatureCompatibilityTest.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9Features.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/util/FATFeatureResolver.java
  dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/util/FATFeatureTester.java
Labels: noproductcode, team:Performance

#31601 Use new getCRIUSupport method in Semeru
  dev/io.openliberty.checkpoint/src/io/openliberty/checkpoint/internal/openj9/ExecuteCRIU_OpenJ9.java
  dev/io.openliberty.org.eclipse.openj9.criu/src/org/eclipse/openj9/criu/CRIUSupport.java
Labels: CLA Signed

#31536 refactor: Oracle Kerberos container at runtime
  dev/com.ibm.ws.jdbc_fat_krb5/bnd.bnd
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/DB2KerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/ErrorPathTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/OracleKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/PostgresKerberosTest.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/KerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/containers/OracleKerberosContainer.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/rules/IBMJava8Rule.java
  dev/com.ibm.ws.jdbc_fat_krb5/fat/src/com/ibm/ws/jdbc/fat/krb5/rules/KerberosPlatformRule.java
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/security/.gitkeep
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/security/oracle_client.keytab
  dev/com.ibm.ws.jdbc_fat_krb5/publish/servers/com.ibm.ws.jdbc.fat.krb5.oracle/server.xml
  dev/fattest.simplicity/src/componenttest/topology/database/container/OracleXEContainer.java
  dev/io.openliberty.org.testcontainers/bnd.bnd
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/kdc-jdbc-server/3.0.0.1/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/kdc-jdbc-server/3.0.0.1/docker-entrypoint.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/kdc-jdbc-server/3.0.0.1/supervisord.conf
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23-full-faststart/startup/01_kerberos.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23.0.0.1-full-faststart/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23.0.0.1-full-faststart/setup/1kerberos.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23.0.0.1-full-faststart/setup/2oracle.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23.0.0.1-full-faststart/startup/01_kerberos.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/oracle-krb5/23.0.0.1-full-faststart/startup/02_oracle.sql
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31600 CWWKD1035E message reports incorrect PageRequest mode
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#31598 Add debug to msgParsedState for defect 296983
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpServiceContextImpl.java
Labels: in:Web Components, CLA Signed, team:Sirius

#31587 Test to Recreate Open Liberty issue #31559
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/ShippingAddress.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/StreetAddress.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#31596 Extra diagnostics for problem with FIPS
  dev/com.ibm.ws.transaction.test.util/src/com/ibm/tx/jta/ut/util/XAResourceImpl.java
Labels: CLA Signed

#31514 Remove liteCheckpointFATs step as this will now be covered by the normal FAT step
  .ci-orchestrator/pb.yml
  .ci-orchestrator/steps/fats/liteCheckpointFATs.yml
Labels: noproductcode, CLA Signed

#31608 MP OpenAPI 4.1 integration with config validation
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationConfigSchema-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.configValidationValidatorSchema-3.0.feature
  dev/com.ibm.ws.rest.handler.config_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.config_fat/publish/servers/com.ibm.ws.rest.handler.config.openapi.fat/server.xml
  dev/com.ibm.ws.rest.handler.validator_fat/bnd.bnd
  dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateOpenApiSchemaTest.java
  dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.openapi.fat/server.xml
Labels: CLA Signed

#31606 Update to released org.eclipse.osgi:3.23.0 version
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/bnd.bnd
Labels: CLA Signed

#31552 Used Tr.debug, instead of printStackTrace in Logging components
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseFFDCService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/JsonLogHandler.java
Labels: CLA Signed

#31585 Update OIDC SPNEGO FATs metadata to point to Core Security
  dev/com.ibm.ws.security.oidc.client_fat.spnego/cognitiveMetadata.yml
  dev/com.ibm.ws.security.oidc.server_fat.spnego/cognitiveMetadata.yml
Labels: noproductcode, CLA Signed, team:Security SSO

#31618 Update SpringBoot version to fix weaving on Java 23+
  dev/io.openliberty.springboot.fat30.data.app/build.gradle
Labels: noproductcode

#31427 add fips enabled unit and fat tests, and also improve existing fips fat tests
  dev/com.ibm.ws.kernel.service/bnd.bnd
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/ws/common/crypto/CryptoUtilsTest.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed

#31613 Skip testMaxSessionIdleTimeout on s390x
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/BasicTest.java
Labels: in:Web Components, noproductcode, team:Sirius

#31617 Time individual tests
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java
Labels: noproductcode

#31482 Adjust timeout settings to accommodate slow test infrastructure
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/config/DefaultConfigurationProvider.java
  dev/com.ibm.tx.jta/src/com/ibm/tx/jta/util/TxTMHelper.java
  dev/com.ibm.tx.util/src/com/ibm/tx/config/ConfigurationProvider.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecLogServiceImpl.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorFactory.java
  dev/com.ibm.ws.recoverylog/src/com/ibm/ws/recoverylog/spi/RecoveryDirectorImpl.java
  dev/com.ibm.ws.transaction/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/JTMConfigurationProvider.java
  dev/com.ibm.ws.transaction/src/com/ibm/ws/transaction/services/RemoteTransactionControllerService.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/jta/embeddable/impl/WSATParticipantWrapper.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/remote/RemoteTransactionController.java
  dev/com.ibm.ws.tx.embeddable/src/com/ibm/tx/remote/TransactionWrapper.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/common/impl/WSATParticipant.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/ProtocolImpl.java
  dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/tm/impl/TranManagerImpl.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryClient1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryClient2/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryClient3/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryServer1/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryServer2/server.xml
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/publish/servers/WSATRecoveryServer3/server.xml
Labels: noproductcode, CLA Signed

#31622 Replace runTest with runInServlet to avoid assertion
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/DBRotationTest.java
Labels: noproductcode, CLA Signed

#31529 CDI test for a duplicate lib in two wars
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/basic/BasicVisibilityTests.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/duplicate/lib/DuplicateLibraryBean.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/duplicate/war1/DuplicateWar1Servlet.java
  dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/duplicate/war2/DuplicateWar2Servlet.java
Labels: noproductcode, CLA Signed

#31659 Revert "Extending the scope of the maxFiles parameter in logging configuration"
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/LoggerOffThread.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/LoggerOnThread.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/AccessLogRolloverTest.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-default-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-invalid-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/files/accessLogging/server-rollover-zero-maxFiles.xml
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/common.xml
  dev/io.openliberty.transport.http_fat/publish/servers/Accesslogging/server.xml
Labels: CLA Signed

#31631 Update jsch version
  dev/ant_build.js/build.gradle
  dev/cnf/build.gradle
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
Labels: CLA Signed

#31654 Calling old resolve features method doesn't break with versionless features
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverImpl.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/BaselineResolutionErrorCaseTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/FATSuite.java
Labels: CLA Signed

#31665 Update upper range of testMaxSessionIdleTimeout
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/BasicTest.java
  dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/AnnotatedTest.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31664 Do not reuse entity objects from failed transaction
  dev/com.ibm.ws.springboot.fat20.data.app/src/main/java/com/ibm/ws/springboot/support/version20/test/data/app/AccessingDataJpaApplication.java
  dev/io.openliberty.springboot.fat30.data.app/build.gradle
  dev/io.openliberty.springboot.fat30.data.app/src/main/java/com/ibm/ws/springboot/support/version30/test/data/app/AccessingDataJpaApplication.java
Labels: CLA Signed

#31688 Remove temp.txt
  dev/temp.txt
Labels: noproductcode

#31570 Test to Recreate Open Liberty issue #30789
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Door.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Garage.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/House.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Kitchen.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#31590 Test Spring JMS integration
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.springboot.fat20.jms.app/.classpath
  dev/com.ibm.ws.springboot.fat20.jms.app/.gitignore
  dev/com.ibm.ws.springboot.fat20.jms.app/.project
  dev/com.ibm.ws.springboot.fat20.jms.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.fat20.jms.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.fat20.jms.app/bnd.bnd
  dev/com.ibm.ws.springboot.fat20.jms.app/build.gradle
  dev/com.ibm.ws.springboot.fat20.jms.app/springboot.gradle
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/java/com/ibm/ws/springboot/support/version20/test/jms/app/JmsApplication.java
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/java/com/ibm/ws/springboot/support/version20/test/jms/app/JmsConfig.java
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/java/com/ibm/ws/springboot/support/version20/test/jms/app/JmsController.java
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/java/com/ibm/ws/springboot/support/version20/test/jms/app/MessageReceiver.java
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/java/com/ibm/ws/springboot/support/version20/test/jms/app/MessageService.java
  dev/com.ibm.ws.springboot.fat20.jms.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.fat20_fat/bnd.bnd
  dev/com.ibm.ws.springboot.fat20_fat/build.gradle
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsAbstractTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsSpringBootAppTests20.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsWebAppTests20.java
  dev/com.ibm.ws.springboot.fat20_fat/publish/files/mqconfig.mqsc
  dev/com.ibm.ws.springboot.fat20_fat/publish/servers/SpringBootTests/includeJms.xml
  dev/com.ibm.ws.springboot.fat20_fat/publish/servers/SpringBootTests/server.env
  dev/io.openliberty.springboot.fat30.jms.app/.classpath
  dev/io.openliberty.springboot.fat30.jms.app/.gitignore
  dev/io.openliberty.springboot.fat30.jms.app/.project
  dev/io.openliberty.springboot.fat30.jms.app/.settings/bndtools.core.prefs
  dev/io.openliberty.springboot.fat30.jms.app/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.springboot.fat30.jms.app/bnd.bnd
  dev/io.openliberty.springboot.fat30.jms.app/build.gradle
  dev/io.openliberty.springboot.fat30.jms.app/springboot.gradle
  dev/io.openliberty.springboot.fat30.jms.app/src/main/java/io/openliberty/springboot/support/version30/test/jms/app/JmsApplication.java
  dev/io.openliberty.springboot.fat30.jms.app/src/main/java/io/openliberty/springboot/support/version30/test/jms/app/JmsConfig.java
  dev/io.openliberty.springboot.fat30.jms.app/src/main/java/io/openliberty/springboot/support/version30/test/jms/app/JmsController.java
  dev/io.openliberty.springboot.fat30.jms.app/src/main/java/io/openliberty/springboot/support/version30/test/jms/app/MessageReceiver.java
  dev/io.openliberty.springboot.fat30.jms.app/src/main/java/io/openliberty/springboot/support/version30/test/jms/app/MessageService.java
  dev/io.openliberty.springboot.fat30.jms.app/src/main/resources/application.properties
  dev/io.openliberty.springboot.fat30_fat/bnd.bnd
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsAbstractTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsSpringBootAppTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JmsWebAppTests30.java
  dev/io.openliberty.springboot.fat30_fat/publish/files/mqconfig.mqsc
  dev/io.openliberty.springboot.fat30_fat/publish/servers/SpringBootTests/includeJms.xml
  dev/io.openliberty.springboot.fat30_fat/publish/servers/SpringBootTests/server.env
Labels: CLA Signed
