Repository OpenLiberty/open-liberty, pull requests merged in 2025-04, with the labels that each got.

#31110 Update metadata to indicate this bucket uses testcontainers
  dev/com.ibm.ws.wsat.migration_fat.6/cognitiveMetadata.yml
Labels: noproductcode, CLA Signed

#31074 Add maxOpenConnections FAT
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/TcpOptions.java
  dev/io.openliberty.transport.http_fat/bnd.bnd
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/MaxOpenConnectionsTest.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/RepeatWithServlet30.java
  dev/io.openliberty.transport.http_fat/publish/servers/MaxOpenConnections/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/MaxOpenConnections/server.xml
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#31114 Jakarta Data repositories in ServletContextListener
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/ResRefDelegator.java
  dev/io.openliberty.data.internal_fat/fat/src/test/jakarta/data/DataTestCheckpoint.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataServletContextListener.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/StartupSingletonEJB.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreServletContextListener.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#31106 disabled test for ServletContextListener scenario
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataServletContextListener.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreServletContextListener.java
Labels: team:Zombie Apocalypse, CLA Signed

#31092 PH65529
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.grpc_fat/bnd.bnd
  dev/io.openliberty.io.netty.ssl/bnd.bnd
  dev/io.openliberty.io.netty/bnd.bnd
Labels: in:Transport, CLA Signed, team:Sirius, target:25004

#31031 fix RTC301400 keystore
  dev/com.ibm.ws.security.oauth.oidc_fat.common/securitykeys/readme-gen-rsa-key-nohost.txt
  dev/com.ibm.ws.security.oauth.oidc_fat.common/securitykeys/rsa_key_nohost.jks
  dev/com.ibm.ws.security.oauth.oidc_fat.common/securitykeys/rsa_trust_nohost.jks
Labels: noproductcode, CLA Signed

#31132 Add separate invalidated session server config to mpTelemetry audit FAT
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/allSourcesWithAudit.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/auditFileHandlerServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/auditServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/invalidAuditSource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/noAuditSourceFeature.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/onlyAuditFeature.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/onlyAuditSource.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/servers/TelemetryAudit/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/servers/TelemetryAudit/serverSessionConfig.xml
Labels: noproductcode, CLA Signed

#31030 increase ltpa ready message timeout to 2 mins for windows
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
Labels: noproductcode, CLA Signed

#31139 fix: cloudant allowable ffdc from IBM JDK
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/CloudantTest.java
Labels: team:Zombie Apocalypse, noproductcode, test debt, CLA Signed

#31148 Revert "Update to MyFaces 4.0.3"
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.faces.4.0.thirdparty/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/bnd.bnd
  dev/io.openliberty.jakarta.faces.4.0/build.gradle
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces-development.js.map
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.br
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.gz
  dev/io.openliberty.jakarta.faces.4.0/src/META-INF/resources/jakarta.faces/faces.js.map
  dev/io.openliberty.org.apache.myfaces.4.0/bnd.bnd
  dev/io.openliberty.org.apache.myfaces.4.0/build.gradle
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/renderkit/html/util/HtmlRendererUtils.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/view/facelets/ViewPoolProcessor.java
Labels: in:Web Components, team:Sirius

#31152 Revert MyFaces 2.3.11 Update
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-minimal-modern.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-minimal.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-uncompressed-full.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.util/_Lang.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_AjaxRequest.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_AjaxUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/javax.faces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/javax.faces/jsf.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/_util/_Lang.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_AjaxRequest.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/jsf-experimental.js
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ApplicationFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/RuntimeConfig.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/FacesContextImplBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/CommonPropertyUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/util/Purgeable.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/ViewPoolProcessor.java
Labels: in:Web Components, team:Sirius

#31049 use pre-generated ltpa keys in security acme fat
  dev/com.ibm.ws.security.acme_fat/bnd.bnd
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.config_var/resources/security/ltpa.keys
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.renew/resources/security/ltpa.keys
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.rest/resources/security/ltpa.keys
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.revocation/resources/security/ltpa.keys
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.simple/resources/security/ltpa.keys
  dev/com.ibm.ws.security.acme_fat/publish/servers/com.ibm.ws.security.acme.fat.trigger/resources/security/ltpa.keys
Labels: noproductcode, CLA Signed

#31133 Remove Auto-generated TODO comments in H2ConnectionLinkProxy
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2ConnectionLinkProxy.java
Labels: in:Transport, CLA Signed, team:Sirius

#31150 fix: dockerfile path parsing
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/CacheFiles.java
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/Dockerfile.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31140 debug: add debugging when config.json is malformed
  dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
  dev/fattest.simplicity/src/componenttest/containers/registry/ArtifactoryRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/registry/InternalRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/registry/Registry.java
  dev/fattest.simplicity/test/componenttest/containers/registry/ArtifactoryRegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/registry/InternalRegistryTest.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Debug

#31145 add aes-128 encoding option for #31105
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
Labels: ID reviewed, CLA Signed, team:Core Security, L2 Reviewed

#31048 Hopefully final time fixing Java security failure
  dev/com.ibm.ws.jdbc_fat_derby/publish/servers/com.ibm.ws.jdbc.fat.derby/server.xml
Labels: noproductcode, CLA Signed, team:Performance

#31122 Test Bug: Update Content Length for Java 24 Builds in JSP Test
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/TestServlet.war/resources/Servlet31RequestResponseTest.jsp
Labels: noproductcode, CLA Signed

#31137 Overlay netty rapid reset
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/http2/LibertyUpgradeCodec.java
  dev/io.openliberty.io.netty/src/io/netty/handler/codec/http2/HttpToHttp2ConnectionHandlerBuilder.java
Labels: in:Transport, team:Sirius

#31154 Add test to load ResourceBundle properties from lib folder and JAR
  dev/com.ibm.ws.classloading_classpath_fat/test-applications/testLib7.jar/resources/io/openliberty/classloading/test/resources/MyResource7.properties
  dev/com.ibm.ws.classloading_classpath_fat/test-applications/testLib9.jar/resources/io/openliberty/classloading/test/resources/MyResource9.properties
  dev/com.ibm.ws.classloading_classpath_fat/test-applications/testLibFileSet/src/io/openliberty/classloading/lib/path/test/app/LibPathTestServlet.java
Labels: noproductcode, CLA Signed

#31162 Add Sizing section to feature template
  .github/ISSUE_TEMPLATE/03_feature.md
Labels: noproductcode, CLA Signed

#31163 Treat dns responses with rcode: 9 as DNS lookup failures
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/dns/impl/chfw/Dns.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/dns/impl/netty/Dns.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/chfw/SipResolver.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolver.java
Labels: CLA Signed

#31147 Tolerate DataStoreAdapterException in rerouting tests
  dev/com.ibm.ws.wsat.migration_fat.6/fat/src/tests/DBRerouteTest.java
Labels: noproductcode, CLA Signed

#31149 Add triage notes to cloud FATs
  dev/com.ibm.ws.transaction.cloud_fat.base/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.db2.0.ee10/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.derby.0.ee10/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0.ee10/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0.ee10/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0.ee10/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/cognitiveMetadata.yml
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/cognitiveMetadata.yml
Labels: noproductcode, CLA Signed

#31063 Fix for 28659, Resolve Jakarta Persistence 3.2 timestamp failures in jpa-beanvalidation FAT
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.classpath
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.project
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.settings/bndtools.core.prefs
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/bnd.bnd
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/test-applications/beanvalidation20/ddl/WEB-INF/classes/JPA_BEAN_VALIDATION_20_DEFAULT_CREATE_DERBY.ddl
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/src/com/ibm/ws/jpa/beanvalidation20/ejb/TestBeanValidation20_EJB_SFEx_Servlet.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/src/com/ibm/ws/jpa/beanvalidation20/ejb/TestBeanValidation20_EJB_SF_Servlet.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/src/com/ibm/ws/jpa/beanvalidation20/ejb/TestBeanValidation20_EJB_SL_Servlet.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/test-applications/beanvalidation20/src/com/ibm/ws/jpa/beanvalidation20/web/TestBeanValidation20Servlet.java
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat/build.gradle
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#31165 Cleanup formatting and remove JSTL that isn't needed
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/resources/footer.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/resources/index.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/resources/indexEE11.jsp
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/resources/page2.jsp
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31178 Update EE6FeatureReplacementAction to have an isEnabled method
  dev/com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat/fat/src/com/ibm/ws/jpa/tests/beanvalidation/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_2.0_fat/fat/src/com/ibm/ws/jpa/tests/embeddable/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_2.0_fat/fat/src/com/ibm/ws/jpa/tests/spec10/entity/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec10.query_jpa_2.0_fat/fat/src/com/ibm/ws/jpa/tests/spec10/query/RepeatWithJPA20.java
  dev/com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat/fat/src/com/ibm/ws/jpa/tests/spec20/RepeatWithJPA20.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/EE6FeatureReplacementAction.java
  dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/RepeatWithServlet30.java
Labels: noproductcode, CLA Signed, team:Performance

#31176 Treat DNS response with rcode: 8 as a lookup failure
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/dns/impl/chfw/Dns.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/dns/impl/netty/Dns.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/chfw/SipResolver.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolver.java
Labels: CLA Signed

#31199 Move fat/src before test-application src
  dev/com.ibm.ws.transport.http2_fat/.classpath
Labels: in:Transport, noproductcode, team:Sirius

#31202 Fix spelling of customer and formatting
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/outbound/WsocChain.java
Labels: in:Transport, team:Sirius

#31204 Fix spelling of Optional in EL 6.0 FAT
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60OptionalELResolverTest.war/src/io/openliberty/el60/fat/optionalelresolver/servlets/EL60OptionalELResolverTestServlet.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE11

#31171 Fix for RTC Defect 302075
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, CLA Signed

#31196 Copyright update
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/bnd.bnd
Labels: noproductcode, in:JPA, team:Blizzard

#31184 Remove auto-generated TODO comments in `com.ibm.ws.transport.http` - netty-transport-http branch
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
Labels: in:Transport, team:Sirius

#31195 library path config for JDBC
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
  dev/com.ibm.ws.jdbc_fat_driver/fat/src/com/ibm/ws/jdbc/fat/driver/JDBCDriverManagerTest.java
  dev/com.ibm.ws.jdbc_fat_driver/publish/servers/com.ibm.ws.jdbc.fat.driver/server.xml
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/folder/driver/FolderDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/folder/driver/FolderJDBCHandler.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/fatdriver/src/jdbc/fat/folder/driver/pool/FolderPoolDataSource.java
  dev/com.ibm.ws.jdbc_fat_driver/test-applications/jdbcapp/src/jdbc/fat/driver/web/JDBCDriverManagerServlet.java
  dev/com.ibm.ws.jdbc_fat_postgresql/publish/servers/postgresql-test-server/server.xml
Labels: team:Zombie Apocalypse

#31182 Remove auto-generated todo comments in `com.ibm.ws.sipcontainer`
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/annotation/SipAnnotationUtil.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/annotation/SipXmlNameSpace.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/annotation/WebXmlNameSpace.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/failover/repository/SessionRepository.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/failover/repository/StandAloneSASRepoMgr.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/failover/repository/StandAloneSSAttrRepoMgr.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/parser/SipAppDesc.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/protocol/SipProtocolLayer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/ProxyTimer.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/SipBranchRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/proxy/StatefullProxy.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/IncomingSipServletRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/OutgoingSipServletRequest.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/OutgoingSipServletResponse.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/SipSessionSeqLog.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/servlets/WASXSipApplicationSessionImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/tu/TransactionUserImpl.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/DummySipServletRequestResponse.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/HttpDestroyedEvent.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/SipModuleStateListener.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/WasPropertiesReader.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/extension/SipServletConfig.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/filters/ApplState.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/was/message/SipMessage.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/security/auth/ThreadLocalStorage.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/context/ResponseContext.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/netty/GenericChain.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/sip/netty/SipConnLink.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/sip/netty/SipInboundChannelFactoryWs.java
Labels: CLA Signed, team:Sirius

#31192 Fix test defect related to testMultipleModuleWarsAllRunAsWithDB
  dev/com.ibm.ws.security.javaeesec_fat/test-applications/multipleModule.ear/resources/META-INF/permissions.xml
Labels: noproductcode

#30981 Invalid zjaas.conf file is breaking our SPNEGO Bucket
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/files/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.client_fat.spnego/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.spnego.op/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/files/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.oidc.server_fat.spnego/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat.endpoint.clientregistration/resources/security/kerberos/zjaas.conf
  dev/com.ibm.ws.security.spnego_fat/publish/files/resources/security/kerberos/zjaas.conf
  dev/io.openliberty.jcache.internal_fat.hazelcast/publish/servers/io.openliberty.jcache.internal.fat.spnego.auth.cache.1/resources/security/kerberos/zjaas.conf
  dev/io.openliberty.jcache.internal_fat.infinispan/publish/servers/io.openliberty.jcache.internal.fat.spnego.auth.cache.1/resources/security/kerberos/zjaas.conf
Labels: noproductcode

#31179 Validation Key FAT Tests
  dev/com.ibm.ws.security.token.ltpa/src/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImpl.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAConfigurationImplTest.java
  dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAKeyCreateTaskTest.java
  dev/com.ibm.ws.security.token.ltpa_fat/build.gradle
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/FATSuite.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAValidationKeyTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternate/validation9.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation9.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/server1FIPS.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/server1nonFIPS.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/server2FIPS.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/server2nonFIPS.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.validationKeyTestServer1/bootstrap.properties
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.validationKeyTestServer1/server.xml
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.validationKeyTestServer2/bootstrap.properties
  dev/com.ibm.ws.security.token.ltpa_fat/publish/servers/com.ibm.ws.security.token.ltpa.fat.validationKeyTestServer2/server.xml
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/LTPA.java
Labels: CLA Signed, team:Core Security

#31219 Update javadoc and method names in EL 6.0 FAT
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/fat/src/io/openliberty/org/apache/jasper/expressionLanguage60/fat/tests/EL60BeanELResolverBeanSupportFullTest.java
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat/test-applications/EL60ArrayLengthTest.war/src/io/openliberty/el60/fat/arraylengthtest/servlets/EL60ArrayLengthTestServlet.java
Labels: in:Web Components, noproductcode, team:Sirius, jakartaEE11

#31120 Move JSP EL tests to a new server
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/FATSuite.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPExpressionLanguageTests.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPSkipMetaInfTests.java
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPTests.java
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/expressionLanguageServer/bootstrap.properties
  dev/com.ibm.ws.jsp.2.3_fat/publish/servers/expressionLanguageServer/server.xml
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31183 Remove auto-generated TODO comments in `com.ibm.ws.transport.http`
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpRequestImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInputStreamEE7.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpOutputStreamEE7.java
Labels: in:Transport, CLA Signed, team:Sirius

#31186 Improve diagnostics when first connection attempt to DB tranlog fails
  dev/com.ibm.rls.jdbc/src/com/ibm/ws/recoverylog/custom/jdbc/impl/SQLNonTransactionalDataSource.java
Labels: CLA Signed

#31189 Add MP Config visibility tests
  dev/com.ibm.ws.microprofile.config.1.1_fat/bnd.bnd
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/suite/FATSuite.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/VisibilityTest.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/visibility/earlib/EarLibBean.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/visibility/earlib/EarLibDependentBean.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/visibility/earlib/VisibilityTestConstants.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/visibility/ejbjar/VisibilityTestEjb.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/visibility/war/VisibilityTestServlet.java
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/VisibilityServer/bootstrap.properties
  dev/com.ibm.ws.microprofile.config.1.1_fat/publish/servers/VisibilityServer/server.xml
  dev/com.ibm.ws.microprofile.config.1.1_fat/test-applications/testAppUtils.jar/src/com/ibm/ws/microprofile/appConfig/test/utils/TestUtils.java
Labels: noproductcode

#31208 Aggressive test
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
  dev/com.ibm.ws.transaction.cloud_fat.base/test-applications/transaction/src/servlets/Base2PCCloudServlet.java
Labels: noproductcode

#31222 disable agent test on zos
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent129Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/Agent250Test.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigMultiAppTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentConfigTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/AgentTest.java
Labels: noproductcode

#31221 remove experimental keywords
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Businesses.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/CreditCards.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse

#31214 combination of java:global and qualifiers not allowed
  dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ConcurrencyResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ContextServiceResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedScheduledExecutorResourceFactoryBuilder.java
  dev/io.openliberty.concurrent.internal/src/io/openliberty/concurrent/internal/processor/ManagedThreadFactoryResourceFactoryBuilder.java
Labels: team:Zombie Apocalypse, ID reviewed

#31215 Remove FeatureRequiresMinimumJavaLevel and update launch.xml
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/src/componenttest/annotation/FeatureRequiresMinimumJavaLevel.java
  dev/fattest.simplicity/src/componenttest/custom/junit/runner/JavaLevelFilter.java
Labels: noproductcode, team:Performance

#31238 Do instrumentation within javaCompile
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: noproductcode

#31237 feat: add websphere automation internal repository
  dev/fattest.simplicity/src/componenttest/containers/registry/InternalRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/substitution/LibertyMirrorSubstitutor.java
  dev/fattest.simplicity/test/componenttest/containers/registry/ArtifactoryRegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/registry/InternalRegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/LibertyMirrorSubstitutorTest.java
Labels: team:Zombie Apocalypse, noproductcode

#31233 fix: SSL tests timing out using Keytool binary
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/CloudantTest.java
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/CloudantTestOutboundSSL.java
  dev/com.ibm.ws.cloudant_fat/fat/src/com/ibm/ws/cloudant/fat/FATSuite.java
  dev/com.ibm.ws.jdbc_fat_postgresql/fat/src/com/ibm/ws/jdbc/fat/postgresql/PostgreSQLSSLTest.java
  dev/com.ibm.ws.transaction.db_fat/fat/src/com/ibm/ws/transaction/test/SSLRecoveryTest.java
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/TxTestContainerSuite.java
  dev/fattest.simplicity/src/componenttest/containers/KeystoreBuilder.java
  dev/fattest.simplicity/test/componenttest/containers/KeystoreBuilderTest.java
  dev/fattest.simplicity/test/componenttest/containers/test.crt
  dev/fattest.simplicity/test/componenttest/containers/test.p12
Labels: team:Zombie Apocalypse

#31216 fix: dbrotation setup for checkpoint tests
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: team:Zombie Apocalypse, noproductcode

#31169 Add tcpOptions portOpenRetries FAT
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/TcpOptions.java
  dev/io.openliberty.netty.internal.impl/src/io/openliberty/netty/internal/tcp/TCPUtils.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/PortOpenRetriesTests.java
  dev/io.openliberty.transport.http_fat/publish/servers/PortOpenRetries1/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/PortOpenRetries1/server.xml
  dev/io.openliberty.transport.http_fat/publish/servers/PortOpenRetries2/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/PortOpenRetries2/server.xml
Labels: in:Transport, CLA Signed, team:Sirius

#31187 Turning off the testcases to prevent build failures due to docker image - Defect 303550
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/FATSuite.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoBasicTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoConfigUpdateTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoDefaultSSLTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLInvalidTrustTest.java
  dev/com.ibm.ws.mongo_fat/fat/src/com/ibm/ws/mongo/fat/MongoSSLTest.java
Labels: noproductcode

#31190 Add deadline to feature template for design approval request
  .github/ISSUE_TEMPLATE/03_feature.md
Labels: noproductcode

#31193 Update ASM to 9.8 (Java 25)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
  dev/com.ibm.ws.org.objectweb.asm/src/io/openliberty/asm/ASMHelper.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
Labels: team:Zombie Apocalypse, java 25

#31279 Netty: Remove commented code in `getSSLContext()`
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/dispatcher/internal/channel/HttpDispatcherLink.java
Labels: in:Transport, team:Sirius

#31168 Issue #31167: Support ejblocal: subcontext lookup
  dev/com.ibm.websphere.appserver.features/visibility/protected/com.ibm.websphere.appserver.containerServices-1.0.feature
  dev/com.ibm.websphere.appserver.spi.containerServices/bnd.bnd
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/EJBLocalNamingHelper.java
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/naming/package-info.java
  dev/com.ibm.ws.ejbcontainer.bindings_fat/test-applications/EJB3DefBndWeb.war/src/com/ibm/ws/ejbcontainer/bindings/defbnd/web/DefaultBindingsServlet.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBLocalNamingHelperImpl.java
  dev/com.ibm.ws.jndi.ejb/src/com/ibm/ws/jndi/ejb/EJBLocalURLContext.java
Labels: team:Zombie Apocalypse, in:EJB Container, CLA Signed, release bug

#31272 handle empty value for http proxy env variables
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallKernelMap.java
Labels: CLA Signed

#31288 Removed an unnecessary character in the XML file
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/server2FIPS.xml
Labels: noproductcode

#31270 Grpc-ltpa-check
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreServicesSecurityTests.java
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#31264 Create More WebSocket CheckPoint Tests
  dev/io.openliberty.checkpoint_fat_wsoc/.classpath
  dev/io.openliberty.checkpoint_fat_wsoc/.project
  dev/io.openliberty.checkpoint_fat_wsoc/.settings/bndtools.core.prefs
  dev/io.openliberty.checkpoint_fat_wsoc/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.checkpoint_fat_wsoc/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.checkpoint_fat_wsoc/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.checkpoint_fat_wsoc/bnd.bnd
  dev/io.openliberty.checkpoint_fat_wsoc/build.gradle
  dev/io.openliberty.checkpoint_fat_wsoc/cognitiveMetadata.yml
  dev/io.openliberty.checkpoint_fat_wsoc/fat/src/io/openliberty/checkpoint/fat/BasicTest.java
  dev/io.openliberty.checkpoint_fat_wsoc/fat/src/io/openliberty/checkpoint/fat/FATSuite.java
  dev/io.openliberty.checkpoint_fat_wsoc/publish/servers/basicWsocServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_wsoc/publish/servers/basicWsocServer/server.xml
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/resources/WEB-INF/web.xml
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/BinaryStreamDecoder.java
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/ByteArrayTest.java
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/CustomString.java
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/DefaultsServerEP.java
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/EchoServerEP.java
  dev/io.openliberty.checkpoint_fat_wsoc/test-applications/basic.war/src/io/openliberty/wsoc/basic/UpgradeServlet.java
Labels: in:Web Components, noproductcode, team:Sirius

#31290 Update kernel feature logic for wmq versionless features.
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/FeatureResolverBaseline.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/util/RepoXML.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessJavaEEToMicroProfileTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessServletToMicroProfileTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/VersionlessTest.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/util/PlatformConstants.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/fat/src/com/ibm/ws/feature/tests/util/RepositoryUtil.java
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/Servlet6_1toHealth/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/Servlet6_1toHealth/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/Servlet6_1toMetrics/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/Servlet6_1toMetrics/server.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee11toMP/bootstrap.properties
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/servers/ee11toMP/server.xml
Labels: CLA Signed, team:Performance

#30896 Enhancing the ignoreWriteAfterCommit property
  dev/com.ibm.ws.jsp.2.3_fat/bnd.bnd
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPChannelTest.java
  dev/com.ibm.ws.jsp.2.3_fat/test-applications/WriteAfterRedirect.war/src/com/ibm/ws/jsp23/fat/writeafterredirect/servlets/SlowResponseServlet.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutputStreamImpl.java
Labels: CLA Signed

#31313 test bucket for java:global scenarios
  dev/io.openliberty.data.internal_fat_global/.classpath
  dev/io.openliberty.data.internal_fat_global/.project
  dev/io.openliberty.data.internal_fat_global/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_global/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_global/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_global/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_global/bnd.bnd
  dev/io.openliberty.data.internal_fat_global/build.gradle
  dev/io.openliberty.data.internal_fat_global/cognitiveMetadata.yml
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/DataJavaGlobalTest.java
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/FATSuite.java
  dev/io.openliberty.data.internal_fat_global/publish/servers/io.openliberty.data.internal.fat.global/bootstrap.properties
  dev/io.openliberty.data.internal_fat_global/publish/servers/io.openliberty.data.internal.fat.global/server.xml
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/DataGlobalRestApp.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/DataGlobalRestResource.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/Reminder.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/Reminders.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31291 Added TCP portOpenRetries to MpHealth31 SlowAppHealthCheckTests to resolve port binding issues
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckFastTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/SlowAppStartupHealthCheck/server.xml
  dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/SlowAppStartupHealthCheckFast/server.xml
Labels: noproductcode, CLA Signed

#31318 Add minimum Java levels for MP 7.1 features.
  dev/build.featureStart.base/resources/com/ibm/ws/test/featurestart/features/feature-levels.properties
Labels: noproductcode, CLA Signed, team:Performance

#31319 Add microProfile-7.1 to tested features list
  dev/io.openliberty.microprofile.internal_fat/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance

#31305 Add tcpOptions soReuseAddr FAT
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/SoLingerTests.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/SoReuseAddrTests.java
  dev/io.openliberty.transport.http_fat/publish/servers/SoReuseAddr/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/SoReuseAddr/server.xml
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#31242 Translatable message when invalid keyword used for collection attribute
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Condition.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/PageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voter.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
Labels: team:Zombie Apocalypse, ID reviewed, L2 Reviewed

#31248 Netty: Remove TODO comment that is no longer needed
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundServiceContextImpl.java
Labels: in:Transport, team:Sirius

#31157 Add Spring test for integration with transaction
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/internal/SpringBootRuntimeContainer.java
  dev/com.ibm.ws.springboot.fat20.transactions.app/.classpath
  dev/com.ibm.ws.springboot.fat20.transactions.app/.gitignore
  dev/com.ibm.ws.springboot.fat20.transactions.app/.project
  dev/com.ibm.ws.springboot.fat20.transactions.app/.settings/bndtools.core.prefs
  dev/com.ibm.ws.springboot.fat20.transactions.app/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.springboot.fat20.transactions.app/bnd.bnd
  dev/com.ibm.ws.springboot.fat20.transactions.app/build.gradle
  dev/com.ibm.ws.springboot.fat20.transactions.app/springboot.gradle
  dev/com.ibm.ws.springboot.fat20.transactions.app/src/main/java/com/ibm/ws/springboot/support/version20/test/transaction/app/AppRunner.java
  dev/com.ibm.ws.springboot.fat20.transactions.app/src/main/java/com/ibm/ws/springboot/support/version20/test/transaction/app/BookingService.java
  dev/com.ibm.ws.springboot.fat20.transactions.app/src/main/java/com/ibm/ws/springboot/support/version20/test/transaction/app/ManagingTransactionsApplication.java
  dev/com.ibm.ws.springboot.fat20.transactions.app/src/main/java/com/ibm/ws/springboot/support/version20/test/transaction/app/WebContext.java
  dev/com.ibm.ws.springboot.fat20.transactions.app/src/main/resources/application.properties
  dev/com.ibm.ws.springboot.fat20_fat/.classpath
  dev/com.ibm.ws.springboot.fat20_fat/bnd.bnd
  dev/com.ibm.ws.springboot.fat20_fat/build.gradle
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppAbstractTests.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests20.java
  dev/com.ibm.ws.springboot.fat20_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests20War.java
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/resources/META-INF/permissions.xml
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/resources/WEB-INF/beans.xml
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/src/ejbapp1/EJBEvent.java
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/src/ejbapp1/LocalEJBServlet.java
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/src/ejbapp1/LocalInterface.java
  dev/com.ibm.ws.springboot.fat20_fat/test-applications/ejbapp1/src/ejbapp1/TestObserver.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/Application.java
  dev/io.openliberty.springboot.fat30.transactions.app/.classpath
  dev/io.openliberty.springboot.fat30.transactions.app/.gitignore
  dev/io.openliberty.springboot.fat30.transactions.app/.project
  dev/io.openliberty.springboot.fat30.transactions.app/.settings/bndtools.core.prefs
  dev/io.openliberty.springboot.fat30.transactions.app/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.springboot.fat30.transactions.app/bnd.bnd
  dev/io.openliberty.springboot.fat30.transactions.app/build.gradle
  dev/io.openliberty.springboot.fat30.transactions.app/springboot.gradle
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/java/io/openliberty/springboot/support/version30/test/transaction/app/AppRunner.java
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/java/io/openliberty/springboot/support/version30/test/transaction/app/BookingService.java
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/java/io/openliberty/springboot/support/version30/test/transaction/app/ManagingTransactionsApplication.java
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/java/io/openliberty/springboot/support/version30/test/transaction/app/WebContext.java
  dev/io.openliberty.springboot.fat30.transactions.app/src/main/resources/application.properties
  dev/io.openliberty.springboot.fat30_fat/.classpath
  dev/io.openliberty.springboot.fat30_fat/bnd.bnd
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppAbstractTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests30War.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/UnsupportedConfigWarningTest30.java
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/resources/META-INF/permissions.xml
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/resources/WEB-INF/beans.xml
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/src/ejbapp1/EJBEvent.java
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/src/ejbapp1/LocalEJBServlet.java
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/src/ejbapp1/LocalInterface.java
  dev/io.openliberty.springboot.fat30_fat/test-applications/ejbapp1/src/ejbapp1/TestObserver.java
Labels: CLA Signed

#31317 Access telemetry log trace
  dev/com.ibm.ws.logging/src/com/ibm/ws/logging/collector/CollectorConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/source/AccessLogSource.java
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/rest/TelemetryServletFilter.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/MpTelemetryLogFieldConstants.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/MpTelemetryLogMappingUtils.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryAccessTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TestUtils.java
  dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/rest/AbstractTelemetryServletFilter.java
Labels: CLA Signed

#31334 test of repository using datasource from different app
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/DataJavaGlobalTest.java
  dev/io.openliberty.data.internal_fat_global/publish/servers/io.openliberty.data.internal.fat.global/server.xml
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/webapp/DataGlobalWebAppServlet.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/webapp/Dictionary.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/webapp/Word.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31194 doubling app startup timeout on windows
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/audit/BasicAuthAuditAUTHZTest.java
Labels: noproductcode

#31331 Correct comment for 1 thread
  dev/com.ibm.ws.jsp.2.3_fat/fat/src/com/ibm/ws/jsp23/fat/tests/JSPPrepareJSPThreadCountDefaultValueTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31330 Remove resource filter that is not necessary
  dev/io.openliberty.pages.4.0.internal.factories/.project
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#31306 Add ssl options to netty ssl
  dev/io.openliberty.netty.internal.tls.impl/src/io/openliberty/netty/internal/tls/impl/NettyTlsProviderImpl.java
Labels: in:Transport, team:Sirius

#31335 Add test for deadlock in Data with Startup EJB in war file
  dev/io.openliberty.data.internal_fat/bnd.bnd
  dev/io.openliberty.data.internal_fat/publish/servers/io.openliberty.data.internal.fat/server.xml
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestEJB.java
Labels: noproductcode, CLA Signed

#31338 Add jakarta.faces.annotation to version transformations
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee10plus.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee11.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions-ee9and10.properties
  dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
Labels: CLA Signed, team:Sirius

#31366 Fix spnego FAT clock skew error
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/CommonTest.java
Labels: noproductcode, CLA Signed, team:Core Security

#31363 Fix up several problems from recently updated code
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/.classpath
  dev/com.ibm.ws.jpa.tests.beanvalidation_3.2_fat.common/bnd.bnd
  dev/com.ibm.ws.logstash.collector_fat/publish/servers/ContainerEnvServer/bootstrap.properties
  dev/io.openliberty.cdi.4.1.internal_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.checkpoint_fat_mp/.classpath
  dev/io.openliberty.checkpoint_fat_mp/bnd.bnd
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/LocalConnectorTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/jmx/LocalConnector.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/jmx/package-info.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/CheckpointSPITestConfig.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/FATSuite.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPFaultToleranceTimeoutTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPHealthTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPHealthTestFileBased.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPJWTTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPMetricsTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPOpenTracingJaegerTraceTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPTelemetryJaxRsIntegrationTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPTelemetryTest.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/OpenAPIConfigTest.java
  dev/io.openliberty.checkpoint_fat_wsoc/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/cognitiveMetadata.yml
  dev/io.openliberty.springboot.fat30.transactions.app/.classpath
  dev/io.openliberty.springboot.fat30.transactions.app/.settings/org.eclipse.jdt.core.prefs
Labels: noproductcode, CLA Signed, team:Performance

#31340 Fix 301503
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/BasicAuthTest.java
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/JCacheSpnegoAuthenticationCacheTest.java
Labels: noproductcode, CLA Signed

#30741 Port MYFACES-4709
  dev/com.ibm.ws.jsf.2.3_fat.2/.classpath
  dev/com.ibm.ws.jsf.2.3_fat.2/bnd.bnd
  dev/com.ibm.ws.jsf.2.3_fat.2/fat/src/com/ibm/ws/jsf23/fat/FATSuite.java
  dev/com.ibm.ws.jsf.2.3_fat.2/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23BugFixes.java
  dev/com.ibm.ws.jsf.2.3_fat.2/publish/servers/jsf23BugFixServer/.gitignore
  dev/com.ibm.ws.jsf.2.3_fat.2/publish/servers/jsf23BugFixServer/bootstrap.properties
  dev/com.ibm.ws.jsf.2.3_fat.2/publish/servers/jsf23BugFixServer/server.xml
  dev/com.ibm.ws.jsf.2.3_fat.2/test-applications/MYFACES-4709.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.jsf.2.3_fat.2/test-applications/MYFACES-4709.war/resources/index.xhtml
  dev/com.ibm.ws.jsf.2.3_fat.2/test-applications/MYFACES-4709.war/src/com/ibm/ws/jsf23/fat/myfaces4709/SimpleBean.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/ee/MyFacesContainerInitializer.java
  dev/io.openliberty.faces.4.0.internal/src/io/openliberty/faces40/internal/ee/WASMyFacesContainerInitializer.java
  dev/io.openliberty.faces.internal/src/com/ibm/ws/jsf/ee/WASMyFacesContainerInitializer.java
  dev/io.openliberty.org.apache.myfaces.3.0/src/org/apache/myfaces/ee/MyFacesContainerInitializer.java
  dev/io.openliberty.org.apache.myfaces.4.0/src/org/apache/myfaces/webapp/MyFacesContainerInitializer.java
  dev/io.openliberty.org.apache.myfaces.4.1/src/org/apache/myfaces/webapp/MyFacesContainerInitializer.java
Labels: in:Web Components, CLA Signed, team:Sirius

#31337 Revert Overlay.
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/DB2Platform.java
Labels: in:JPA, team:Blizzard, CLA Signed

#31376 Disable OAuth/OIDC FATs that use Mongo
  dev/com.ibm.ws.security.fat.common.backchannelLogout/fat/src/com/ibm/ws/security/backchannelLogout/fat/CommonTests/BasicBCLTests.java
  dev/com.ibm.ws.security.oauth_fat/fat/src/com/ibm/ws/security/oauth20/fat/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.oauth/fat/src/com/ibm/ws/security/openidconnect/server/fat/oauth/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/oidc/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat.spnego/fat/src/com/ibm/ws/security/openidconnect/server/fat/spnego/FATSuite.java
Labels: noproductcode, CLA Signed, team:Security SSO

#31388 Move default tcpOptions tests to their own class/server
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/FATSuite.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/MaxOpenConnectionsTest.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/PortOpenRetriesTests.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/SoLingerTests.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/SoReuseAddrTests.java
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/TcpOptionsDefaultTests.java
  dev/io.openliberty.transport.http_fat/publish/servers/TcpOptionsDefaults/bootstrap.properties
  dev/io.openliberty.transport.http_fat/publish/servers/TcpOptionsDefaults/server.xml
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#31384 Update maxConcurrentStreams description default to 100
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
Labels: in:Transport, team:Sirius

#31370 Update to MyFaces 2.3.11 with MYFACES-4721 (autocomplete update)
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/bnd.bnd
  dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-minimal-modern.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-minimal.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/javax.faces/jsf-uncompressed-full.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.util/_Lang.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_AjaxRequest.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_AjaxUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/internal-resources/org.apache.myfaces.core.impl.xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/javax.faces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/javax.faces/jsf.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/_util/_Lang.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_AjaxRequest.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_AjaxUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/META-INF/resources/myfaces/_impl/xhrCore/_PartialSubmitUtils.js
  dev/com.ibm.websphere.javaee.jsf.2.3/src/META-INF/resources/myfaces/jsf-experimental.js
  dev/com.ibm.ws.org.apache.myfaces.2.3/bnd.bnd
  dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/application/ApplicationFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/FacesConfigurator.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/config/RuntimeConfig.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/context/servlet/FacesContextImplBase.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/lifecycle/LifecycleFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/renderkit/RenderKitFactoryImpl.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/renderkit/html/HtmlResponseStateManager.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/shared/renderkit/html/CommonPropertyUtils.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/util/Purgeable.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/FaceletViewDeclarationLanguage.java
  dev/com.ibm.ws.org.apache.myfaces.2.3/src/org/apache/myfaces/view/facelets/ViewPoolProcessor.java
Labels: in:Web Components, CLA Signed, team:Sirius

#31394 temporal types DayOfWeek and MonthDay
  dev/io.openliberty.data.internal_fat_global/fat/src/test/jakarta/data/global/DataJavaGlobalTest.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/DataGlobalRestResource.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/Reminder.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/Reminders.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31362 Test websockets as Spring Boot WAR and WEB WAR
  dev/io.openliberty.springboot.fat30.websocket.app/build.gradle
  dev/io.openliberty.springboot.fat30.websocket.app/src/main/java/com/ibm/ws/springboot/fat30/websocket/app/TestApplication.java
  dev/io.openliberty.springboot.fat30_fat/build.gradle
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/WebSocketAbstractTests.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/WebSocketSpringBootAppTests30.java
  dev/io.openliberty.springboot.fat30_fat/fat/src/com/ibm/ws/springboot/support/fat/WebSocketWebAppTests30.java
Labels: CLA Signed

#31315 MP Health - local/file based health checks. Introduce the _create interval_.
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/MPHealthElement.java
  dev/io.openliberty.checkpoint_fat_mp/fat/src/io/openliberty/checkpoint/fat/mp/MPHealthTestFileBased.java
  dev/io.openliberty.checkpoint_fat_mp/publish/servers/checkpointMPHealthFileBased/server.xml
  dev/io.openliberty.microprofile.health.4.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthCheck40ServiceImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/impl/HealthCheck40CDIBeanInvokerImpl.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/FATSuite.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/MPConfigDefaultValuesTest.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/fat/src/io/openliberty/microprofile/health/file/healthcheck/fat/SimpleFileBasedHealthCheckTest.java
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/DefaultAllUpServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/DefaultReadinessUpServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/DefaultStartupUpServer/server.xml
  dev/io.openliberty.microprofile.health.file.healthcheck.internal_fat/publish/servers/HealthServer/server.xml
  dev/io.openliberty.microprofile.health.internal.common/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.microprofile.health.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.health.internal.common/resources/io/openliberty/microprofile/health/resources/Health.nlsprops
  dev/io.openliberty.microprofile.health.internal.common/src/io/openliberty/microprofile/health/internal/common/HealthCheckConstants.java
Labels: ID reviewed, CLA Signed, L2 Reviewed

#31411 Enable tests of the fix for #29443
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#31379 Create uploadfat task
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode

#31422 Switch test code to use a ConcurrentHashMap for thread safety
  dev/com.ibm.ws.javaee.ddmodel_fat/test-bundles/ddmodel_fat_bundle/src/com/ibm/ws/javaee/ddmodel/fat/ContainerHelperComponent.java
Labels: noproductcode, team:Performance

#31372 Cryptocache
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/test/com/ibm/ws/crypto/ltpakeyutil/LTPACryptoTest.java
Labels: CLA Signed

#31418 Add CWWKS9113E to the server's shutdown messages
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAValidationKeyTests.java
Labels: noproductcode, CLA Signed

#31240 feat: add support for websphere automation testing
  dev/fattest.simplicity/src/componenttest/containers/registry/InternalRegistry.java
Labels: team:Zombie Apocalypse, noproductcode
