Repository OpenLiberty/open-liberty, pull requests merged in 2025-02, with the labels that each got.

#30695 Remove scarf from SwaggerUI dependencies
  dev/com.ibm.ws.openapi.ui/swagger-ui/package-lock.json
  dev/com.ibm.ws.openapi.ui/swagger-ui/package.json
Labels: noproductcode, CLA Signed

#30693 tests for insert and save of null record entity
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/PollingLocation.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
Labels: team:Zombie Apocalypse, CLA Signed

#30704 JAX-WS: JAXB Skip test for Java 8
  dev/com.ibm.ws.jaxb_fat/fat/src/com/ibm/ws/jaxb/fat/LibertyJAXBSpecTest.java
Labels: in:Web Services, noproductcode, CLA Signed, team:Bobcats

#30684 fix: DatabaseContainerUtil error on IBMi
  dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
  dev/fattest.simplicity/test/componenttest/topology/database/container/libraryServer.xml
Labels: team:Zombie Apocalypse, noproductcode, test bug, CLA Signed, ibmi

#30658 Wait for SSL start
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSFApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/NoAppTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/RestApplicationTest.java
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ServletApplicationTest.java
Labels: noproductcode, CLA Signed

#30672 Test checkpoint/restore with AES decryption for SSL
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SSLTest.java
Labels: noproductcode, CLA Signed

#30616 Refactor test code, more succinct boolean resolution
  dev/io.openliberty.http.monitor/src/io/openliberty/http/monitor/HttpServerStatsMonitor.java
Labels: CLA Signed

#30716 Fix log checking in OpenAPI merge config test
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/MergeConfigServerXMLTest.java
Labels: noproductcode, CLA Signed

#30721 error or exception during scheduled async method
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncAppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncTestServlet.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/AsyncInterceptor.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/ScheduledAsyncMethod.java
Labels: team:Zombie Apocalypse, CLA Signed

#30713 #29659 AES-256 passwordEncryption remove BETA guards
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat.federated/jvm.options
  dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat/jvm.options
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SSLTest.java
  dev/io.openliberty.checkpoint_fat/publish/servers/checkpointPasswordUtilities/jvm.options
Labels: CLA Signed, team:Core Security

#30668 adding block so windows doesn't run retrieveUninstallFileList twice
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
Labels: CLA Signed

#30710 Remove ssl feature from OpenAPITestServer
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
  dev/io.openliberty.microprofile.openapi.2.0.internal_fat/publish/servers/OpenAPITestServer/server.xml
Labels: noproductcode, CLA Signed

#30671 Run core CDI 4.1 TCK in build
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.classpath
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.project
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.cdi.4.1.internal_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.cdi.4.1.internal_fat_tck/bnd.bnd
  dev/io.openliberty.cdi.4.1.internal_fat_tck/build.gradle
  dev/io.openliberty.cdi.4.1.internal_fat_tck/fat.bnd
  dev/io.openliberty.cdi.4.1.internal_fat_tck/fat/src/io/openliberty/cdi41/internal/fat/tck/CDI41TckTest.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/fat/src/io/openliberty/cdi41/internal/fat/tck/FATSuite.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/porting-package.bnd
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/features/io.openliberty.cdi.tck.porting-package-4.1.mf
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/servers/FATServer/bootstrap.properties
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/servers/FATServer/jvm.options
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/servers/FATServer/server.xml
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/.gitignore
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/src/test/java/io/openliberty/cdi41/test/ArquillianLoadableExtension.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/src/test/resources/META-INF/cdi-tck.properties
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/src/test/resources/arquillian.xml
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/tck-suite-lite.xml
  dev/io.openliberty.cdi.4.1.internal_fat_tck/publish/tckRunner/tck-suite.xml
  dev/io.openliberty.cdi.4.1.internal_fat_tck/test-bundles/io.openliberty.cdi.tck.porting.package/src/io/openliberty/cdi/portingpackage/BeansImpl.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/test-bundles/io.openliberty.cdi.tck.porting.package/src/io/openliberty/cdi/portingpackage/ContextsImpl.java
  dev/io.openliberty.cdi.4.1.internal_fat_tck/test-bundles/io.openliberty.cdi.tck.porting.package/src/io/openliberty/cdi/portingpackage/package-info.java
Labels: CLA Signed

#30729 Update JACC tests to repeat with the right features
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.bindings/server.xml
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/configs/pureAnn.mergebindings.server.org.xml
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/configs/pureAnn.mergeconflict.xml
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.mergebindings/server.xml
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/configs/pureAnn.mergebindings.server.org.xml
  dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat/server.xml
  dev/com.ibm.ws.webcontainer.security.jacc.1.5_fat/fat/src/com/ibm/ws/webcontainer/security/jacc15/fat/audit/BasicAuthAuditAUTHZTest.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, team:Performance

#30726 automatic scheduled async methods
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncAppScopedBean.java
  dev/com.ibm.ws.concurrent_fat_schedasync/test-applications/SchedAsyncWeb/src/test/concurrency/schedasync/web/SchedAsyncTestServlet.java
Labels: team:Zombie Apocalypse, noproductcode

#30735 Updated regex for toString changes in Java 23
  dev/com.ibm.ws.security.acme_fat/fat/src/com/ibm/ws/security/acme/fat/AcmeCaRestHandlerTest.java
Labels: noproductcode, CLA Signed, team:Performance, Java 23, Java 24

#30647 refactor: support artifactory and internal registries
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
  dev/fattest.simplicity/bnd.bnd
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryMirrorSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/ArtifactoryRegistrySubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/ImageBuilder.java
  dev/fattest.simplicity/src/componenttest/containers/ImageHelper.java
  dev/fattest.simplicity/src/componenttest/containers/registry/ArtifactoryRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/registry/InternalRegistry.java
  dev/fattest.simplicity/src/componenttest/containers/registry/Registry.java
  dev/fattest.simplicity/src/componenttest/containers/substitution/ImageBuilderSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/substitution/LibertyImageNameSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/substitution/LibertyMirrorSubstitutor.java
  dev/fattest.simplicity/src/componenttest/containers/substitution/LibertyRegistrySubstitutor.java
  dev/fattest.simplicity/test/componenttest/containers/ArtifactoryImageNameSubstitutorTest.java
  dev/fattest.simplicity/test/componenttest/containers/ImageHelperTest.java
  dev/fattest.simplicity/test/componenttest/containers/registry/ArtifactoryRegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/registry/InternalRegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/registry/RegistryTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/ImageBuilderSubstitutorTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/LibertyImageNameSubstitorTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/LibertyMirrorSubstitutorTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/LibertyRegistrySubsititorTest.java
  dev/fattest.simplicity/test/componenttest/containers/substitution/MockedInstances.java
  dev/wlp-gradle/subprojects/fat.gradle
Labels: team:Zombie Apocalypse, CLA Signed

#30736 Updates to make things compile cleanly in eclipse
  dev/com.ibm.ws.messaging.comms.server/bnd.bnd
  dev/com.ibm.ws.sipcontainer/bnd.bnd
Labels: CLA Signed, team:Performance

#30675 Repair NullPointer exception thrown in AESKeyManager.java
  dev/com.ibm.ws.crypto.passwordutil/bnd.bnd
  dev/com.ibm.ws.crypto.passwordutil/resources/com/ibm/ws/crypto/util/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/AESKeyManager.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
Labels: ID reviewed, team:Core Security, L2 Reviewed

#30720 Stop building MP6 zip
  dev/build.image/build.gradle
  dev/build.image/profiles/microProfile6/features.xml
Labels: CLA Signed, team:Performance

#30730 clear anno cache on application metadata destroyed event
  dev/com.ibm.ws.anno/bnd.bnd
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/interfaces/TargetCache_FactoryLiberty.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/interfaces/package-info.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/internal/TargetCacheImpl_DataApps.java
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/internal/TargetCacheImpl_Factory.java
  dev/com.ibm.ws.container.service/bnd.bnd
  dev/com.ibm.ws.container.service/src/com/ibm/ws/container/service/metadata/internal/AnnotationCacheReleaseService.java
Labels: CLA Signed

#30637 Add support for path to library
  dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/library.properties
  dev/com.ibm.ws.classloading/resources/OSGI-INF/metatype/library.xml
  dev/com.ibm.ws.classloading/resources/com/ibm/ws/classloading/internal/resources/ClassLoadingServiceMessages.nlsprops
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/LibraryGeneration.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/SharedLibraryConstants.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/SharedLibraryFactory.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/SharedLibraryImpl.java
  dev/com.ibm.ws.classloading_classpath_fat/.classpath
  dev/com.ibm.ws.classloading_classpath_fat/bnd.bnd
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/fat/FATSuite.java
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/fat/LibraryPathTest.java
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/util/TestUtils.java
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPathTest/bootstrap.properties
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPathTest/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPathTest/server.xml
  dev/com.ibm.ws.classloading_classpath_fat/test-applications/testLibFileSet/src/io/openliberty/classloading/lib/path/test/app/LibPathTestServlet.java
Labels: noproductcode, ID reviewed, CLA Signed

#30685 Use org.eclipse.osgi 3.23.0.v20250201-1235 from integration build
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/cnf/oss_ibm.maven
  dev/org.eclipse.osgi/.classpath
  dev/org.eclipse.osgi/bnd.bnd
  dev/org.eclipse.osgi/bnd.overrides
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/container/KeyBasedLockStore.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/EquinoxClassLoader.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/loader/ModuleClassLoader.java
  dev/org.eclipse.osgi/src/org/eclipse/osgi/internal/url/URLStreamHandlerProxy.java
Labels: CLA Signed

#30754 fix: docker image builder for pipelines
  dev/fattest.simplicity/src/componenttest/containers/substitution/LibertyImageNameSubstitutor.java
  dev/io.openliberty.org.testcontainers/build.gradle
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/db2-krb5/12.1.0.0/Dockerfile
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/CustomImages.java
  dev/io.openliberty.org.testcontainers/src/io/openliberty/org/testcontainers/generate/Dockerfile.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30756 properly obtain interceptor binding annotation
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/ext/ConcurrentCDIExtension.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/TestBean.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/interceptor/AsyncInterceptor.java
Labels: team:Zombie Apocalypse, CLA Signed

#30743 Skip telemetry integration tests repeated in tck
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3MultiPropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/B3PropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTraceBaggagePropagationTestServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/transports/W3CTracePropagationTestServlet.java
Labels: noproductcode, CLA Signed

#30765 Update product and bundle version for release 25.0.0.3
  dev/cnf/resources/bnd/liberty-release.props
Labels: CLA Signed

#30755 Update package lock files to reflect exact version
  dev/com.ibm.ws.ui.tool.explore/package-lock.json
  dev/com.ibm.ws.ui.tool.explore/package.json
  dev/com.ibm.ws.ui.tool.javaBatch/package-lock.json
  dev/com.ibm.ws.ui.tool.javaBatch/package.json
  dev/com.ibm.ws.ui.tool.serverConfig/package-lock.json
  dev/com.ibm.ws.ui.tool.serverConfig/package.json
  dev/com.ibm.ws.ui/package-lock.json
  dev/com.ibm.ws.ui/package.json
Labels: noproductcode, CLA Signed

#30760 changing Jakarta Validation 3.1 feature and bundle to use the 3.1.1 v…
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.validation-3.1.feature
  dev/io.openliberty.jakarta/validation.3.1.bnd
Labels: CLA Signed

#30763 Update jnosql version to 1.1.4
  dev/io.openliberty.data.internal_fat_nosql/build.gradle
Labels: noproductcode, CLA Signed

#30768 Add Java 24 specific FAT
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java24Test.java
  dev/io.openliberty.java.internal_fat/publish/servers/java24-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java24-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java24-server/server.xml
  dev/io.openliberty.java.internal_fat/src-reference/java24/io/openliberty/java/internal/TestApp.java
  dev/io.openliberty.java.internal_fat/src-reference/java24/io/openliberty/java/internal/TestService.java
  dev/io.openliberty.java.internal_fat/src-reference/java24/io/openliberty/java/internal/package-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java24/module-info.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, Java 24

#30734 Improve handling of UnknownHostException in JMX client
  dev/com.ibm.ws.jmx.connector.client.rest/src/com/ibm/ws/jmx/connector/client/rest/internal/RESTMBeanServerConnection.java
Labels: CLA Signed

#30745 Recreate issue 30501
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Prime.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/RomanNumeral.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, CLA Signed

#30770 test case for inherited interceptor binding
  dev/com.ibm.ws.concurrent_fat_cdi/bnd.bnd
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/ConcurrentCDIServlet.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/MyAsync.java
  dev/com.ibm.ws.concurrent_fat_cdi/test-applications/concurrentCDIWeb/src/concurrent/cdi/web/TestBean.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30705 Fixes #30598 - Update Directory Browsing for Servlet 6.0 and later
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/servlet/DirectoryBrowsingServlet.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/.classpath
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/bnd.bnd
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/FATSuite.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/fat/src/io/openliberty/webcontainer/servlet60/fat/tests/Servlet60GetRealPathDirectoryBrowsingTest.java
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_getRealPathDirectoryBrowsing/bootstrap.properties
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/publish/servers/servlet60_getRealPathDirectoryBrowsing/server.xml
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/GetRealPathDirectoryBrowsing.war/resources/FirstFolder/firstText.txt
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/GetRealPathDirectoryBrowsing.war/resources/SecondFolder/secondText.txt
  dev/io.openliberty.webcontainer.servlet.6.0.internal_fat/test-applications/GetRealPathDirectoryBrowsing.war/resources/WEB-INF/ibm-web-ext.xml
Labels: in:Web Components, CLA Signed, team:Sirius

#30784 Correct testXMLValidation[Good/Bad]Case FAT
  dev/com.ibm.ws.jsf.2.2_fat.2/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java
Labels: in:Web Components, noproductcode, CLA Signed, team:Sirius

#30744 ltpa and audit crypto updates for fips 140-3
  dev/build.sharedResources/usrShared/resources/security/ltpaFIPS.keys
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyFileUtility.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAKeyFileUtilityImpl.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAPrivateKey.java
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPAPublicKey.java
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_cs.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_de.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_es.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_fr.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_hu.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_it.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_ja.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_ko.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_pl.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_pt_BR.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_ro.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_ru.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_zh.nlsprops
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages_zh_TW.nlsprops
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
  dev/com.ibm.ws.security.audit.reader/src/com/ibm/ws/security/audit/reader/tasks/AuditLogReader.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditCrypto.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditEncryptionImpl.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditSigningImpl.java
  dev/com.ibm.ws.security.fat.common/publish/shared/securityKeys/ltpaFIPS.keys
  dev/com.ibm.ws.security.token.ltpa/test-resources/test data/servers/com.ibm.ws.security.token.ltpa_test/resources/security/ltpaFIPS.keys
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/FATTest.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/ltpa.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation1.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation2.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation3.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation4.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation5.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation6.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation7.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/alternateFIPS/validation8.keys
  dev/com.ibm.ws.security.token.ltpa_fat/publish/files/corruptedFIPS/ltpa.keys
Labels: ID review not needed, CLA Signed

#30631 fix ltpa fat failures when fips is enabled
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
Labels: noproductcode, CLA Signed

#30788 better logging for shared libs
  dev/com.ibm.ws.kernel.metatype.helper/src/com/ibm/wsspi/config/internal/FilesetImpl.java
Labels: CLA Signed

#30706 Changes to deliver EclipseLink 5.0.0-B06
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
Labels: in:JPA, team:Blizzard, CLA Signed

#30746 Fully read heartbeat stream in RESTMBeanServerConnection
  dev/com.ibm.ws.jmx.connector.client.rest/src/com/ibm/ws/jmx/connector/client/rest/internal/RESTMBeanServerConnection.java
Labels: CLA Signed

#30759 Update Weld to 6.0.0.Final
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.org.jboss.weld6/build.gradle
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#30737 Use ServiceCaller for ArtifactContainerFactory
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ContainerClassLoader.java
Labels: CLA Signed

#30769 Update hashing algorithms when FIPs 140-3 is enabled
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/HashedData.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordHashGenerator.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/BaseHashedDataTest.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/HashedDataSHA1Test.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/HashedDataSHA512Test.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/HashedDataTest.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/PasswordHashGeneratorTest.java
Labels: CLA Signed, team:Core Security

#30792 transactional interceptor on repository interface
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/Util.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/provider/PUnitEMBuilder.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/service/DBStoreEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/PersonRepo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Persons.java
Labels: team:Zombie Apocalypse

#30803 Update SymbolicNameTest to not fetch from maven
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/SymbolicNameTest.java
Labels: team:Performance

#30804 Update SymbolicNameTest again to be more accurate
  dev/com.ibm.websphere.appserver.features/test/src/com/ibm/ws/feature/tests/SymbolicNameTest.java
Labels: team:Performance

#30794 Added new messages for FIPS
  dev/com.ibm.ws.kernel.service/resources/com/ibm/ws/kernel/pseudo/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
Labels: ID reviewed

#30800 @Version attribute of type LocalDateTime
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/County.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Model.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Models.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30805 Update Gzip jaxws test to not fail sometimes
  dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/GzipInterceptorsTest.java
Labels: noproductcode, CLA Signed, team:Performance, Java 24

#30782 Test CDI and EJB injection with appClientSupport for InstantOn
  dev/io.openliberty.checkpoint_fat_appClientSupport/fat/src/io/openliberty/checkpoint/fat/appclientsupport/AppClientSupportTest.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppClient.jar/src/io/openliberty/checkpoint/fat/appclientsupport/InjectionClientMain.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/resources/META-INF/beans.xml
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/resources/META-INF/ejb-jar.xml
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/SimpleCDIInjectionBean.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/SimpleEJBInjectionBean.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/SimpleGlobalEJBInjectionBean.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/view/SimpleCDIInjection.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/view/SimpleEJBInjectionBeanRemote.java
  dev/io.openliberty.checkpoint_fat_appClientSupport/test-applications/InjectionAppEJB.jar/src/io/openliberty/checkpoint/fat/appclientsupport/view/SimpleGlobalEJBInjectionBeanRemote.java
Labels: noproductcode, CLA Signed

#30299 Enable the J2EE Management feature to use the Checkpoint Rule
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/fat/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/tests/EJBJ2EEManagementTest.java
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/bootstrap.properties
  dev/fattest.simplicity/src/componenttest/rules/repeater/CheckpointRule.java
Labels: noproductcode, CLA Signed

#30790 Update Audit encryption algorithms and remove DESede support
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
  dev/com.ibm.ws.security.audit.reader/src/com/ibm/ws/security/audit/reader/tasks/AuditLogReader.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditCrypto.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditEncryptionImpl.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditKeyEncryptor.java
  dev/com.ibm.ws.security.audit.source/src/com/ibm/ws/security/audit/encryption/AuditSigningImpl.java
Labels: team:Core Security

#30786 Db2 jcc
  dev/com.ibm.ws.jdbc_fat/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/build.gradle
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.jdbc.fat.db2/server.xml
  dev/io.openliberty.checkpoint_fat_persistence/build.gradle
  dev/io.openliberty.checkpoint_fat_persistence/publish/servers/io.openliberty.checkpoint.jdbc.fat.db2/server.xml
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, CLA Signed

#30797 Remove beta guard for library path configuration
  dev/com.ibm.ws.classloading/resources/OSGI-INF/metatype/library.xml
  dev/com.ibm.ws.classloading/src/com/ibm/ws/library/internal/LibraryGeneration.java
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPathTest/jvm.options
Labels: CLA Signed

#30798 add FIPS 140-3 exception message for SHA1 password hashes
  dev/com.ibm.ws.crypto.passwordutil/resources/com/ibm/ws/crypto/util/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
Labels: ID reviewed, CLA Signed, team:Core Security

#30764 Updated java dump generation time in Hung RequestTiming FAT
  dev/com.ibm.ws.request.timing.hung_fat/fat/src/com/ibm/ws/request/timing/hung/fat/HungRequestTiming.java
Labels: noproductcode, CLA Signed

#30815 Switch from getProjectDir() to name for getting Bnd project
  dev/wlp-gradle/subprojects/fat.gradle
Labels: noproductcode, team:Performance

#30816 Fix EJB FAT metadata
  dev/com.ibm.ws.cloudant_fat/cognitiveMetadata.yml
  dev/com.ibm.ws.couchdb_fat/cognitiveMetadata.yml
  dev/com.ibm.ws.injection_fat/cognitiveMetadata.yml
  dev/io.openliberty.injection.jakarta_fat/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.jsonb.3.0_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.jsonb.internal_fat/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.jsonp.2.1_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.validation.v31_fat/cognitiveMetadata.yml
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug

#30819 Overlay created for Issue Fix : 28813
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/DerbyPlatform.java
Labels: in:JPA, team:Blizzard, CLA Signed

#30801 Netty: Don't use chunked transfer-encoding for HTTP 1.0
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/inbound/NettyTCPWriteRequestContext.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/inbound/HttpDispatcherHandler.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/outbound/HeaderHandler.java
Labels: in:Transport, team:Sirius

#30781 Addressing ByteBuf memory leak in upgrade handler
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/netty/upgrade/NettyServletUpgradeHandler.java
Labels: team:Sirius

#30817 countBy/existsBy error path testing for results
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataErrPathsTest.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/DataErrPathsTestServlet.java
  dev/io.openliberty.data.internal_fat_errorpaths/test-applications/DataErrPathsTestApp/src/test/jakarta/data/errpaths/web/Voters.java
Labels: team:Zombie Apocalypse, CLA Signed

#30825 Data functional acceptance test bucket TODOs
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Primes.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Rating.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Thing.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Things.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Rebate.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30823 fix ltpa cache cleanup
  dev/com.ibm.ws.crypto.ltpakeyutil/src/com/ibm/ws/crypto/ltpakeyutil/LTPACrypto.java
  dev/com.ibm.ws.crypto.ltpakeyutil/test/com/ibm/ws/crypto/ltpakeyutil/LTPACryptoTest.java
Labels: CLA Signed

#30826 Use the right name for the test war
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPathTest/server.xml
Labels: noproductcode, CLA Signed

#30811 mpHealth-4.0 file-based health checks
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/.classpath
  dev/io.openliberty.microprofile.health.4.0.internal/.project
  dev/io.openliberty.microprofile.health.4.0.internal/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.health.4.0.internal/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.health.4.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal/original.bnd
  dev/io.openliberty.microprofile.health.4.0.internal/resources/META-INF/services/org.eclipse.microprofile.health.spi.HealthCheckResponseProvider
  dev/io.openliberty.microprofile.health.4.0.internal/resources/WEB-INF/ibm-web-ext.xml
  dev/io.openliberty.microprofile.health.4.0.internal/resources/WEB-INF/web.xml
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/AppTracker40Impl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/FileHealthCheckBuilder.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthCheck40Service.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthCheck40ServiceImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthFileUtils.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/package-info.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/servlet/HealthCheckLivenessServlet.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/servlet/HealthCheckReadinessServlet.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/servlet/HealthCheckServlet.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/servlet/HealthCheckStartupServlet.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/servlet/package-info.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/HealthCheck40CDIBeanInvoker.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/HealthCheck40Executor.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/impl/HealthCheck40CDIBeanInvokerImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/impl/HealthCheck40ExecutorImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/impl/package-info.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/services/package-info.java
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/spi/impl/HealthCheck40ResponseProviderImpl.java
  dev/io.openliberty.microprofile.health.4.0.internal/test/src/io/openliberty/microprofile/health40/test/HealthCheck40ResponseTest.java
  dev/io.openliberty.microprofile.health.4.0.internal/transformed.bnd
  dev/io.openliberty.microprofile.health.internal.common/bnd.bnd
  dev/io.openliberty.microprofile.health.internal.common/resources/OSGI-INF/l10n/metatype.properties
  dev/io.openliberty.microprofile.health.internal.common/resources/OSGI-INF/metatype/metatype.xml
  dev/io.openliberty.microprofile.health.internal.common/src/io/openliberty/microprofile/health/internal/common/HealthCheckConstants.java
Labels: ID reviewed, CLA Signed

#30835 Remove Test library from scan
  dev/build.depScanner/src/io/openliberty/depScanner/BestMatch.java
Labels: noproductcode, CLA Signed

#30836 avoid logging customer data on bean validation path
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/CursoredPageImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/validation/EntityValidatorImpl.java
  dev/io.openliberty.data.internal_fat_validation/fat/src/test/jakarta/data/validation/DataValidationTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#30821 add CWWKS1864W for older aes and hash passwords
  dev/com.ibm.ws.crypto.passwordutil/resources/com/ibm/ws/crypto/util/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/AESKeyManager.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.jca_fat_bvt/fat/src/test/client/jca/JCABVTTest.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
  dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTestFederated.java
  dev/com.ibm.ws.security.registry.basic_fat/publish/files/defaultHashBasicRegistry.xml
  dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/SSLTest.java
Labels: ID reviewed, CLA Signed, team:Core Security, L2 Reviewed

#30806 Test injection of ELAwareBeanManager
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.cdi.4.1.internal_fat/fat/src/io/openliberty/cdi41/internal/fat/el/app/ELTestServlet.java
  dev/io.openliberty.org.jboss.weld6/build.gradle
  dev/io.openliberty.org.jboss.weld6/check-me-in-if-i-change.bnd
Labels: CLA Signed

#30829 Test CDI Managed Bean bindings
  dev/com.ibm.ws.cdi.jee_fat/build.gradle
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/FATSuite.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/binding/ManagedBeanBindingTest.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/binding/app/BindingTestCDIBean.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/binding/app/ManagedBeanBindingTestServlet.java
  dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/binding/app/ibm-managed-bean-bnd.xml
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12BindingServer/.gitignore
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12BindingServer/bootstrap.properties
  dev/com.ibm.ws.cdi.jee_fat/publish/servers/cdi12BindingServer/server.xml
Labels: noproductcode, CLA Signed

#30780 Updated trace gRPC message to work for case where the headers have not yet been set
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2HttpInboundLinkWrap.java
Labels: CLA Signed, team:Sirius

#30841 Enable tests now that #28813 (EclipseLink DateTimeParseException) is fixed
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Model.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Models.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30833 Added Audit logs to OTLP test for MP Telemetry 2.0
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/bnd.bnd
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/files/auditSourceServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/publish/servers/TelemetryLogsServer/jvm.options
Labels: noproductcode, CLA Signed

#30691 Improve Windows performance during uninstall
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/UninstallDirector.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/adaptor/ESAAdaptor.java
Labels: CLA Signed

#30834 Fixes for Db2 JCC 12 driver
  dev/com.ibm.ws.jdbc_fat_db2/publish/servers/com.ibm.ws.sqlj.fat/server.xml
  dev/com.ibm.ws.jdbc_fat_krb5/test-applications/krb5-db2-app/src/jdbc/krb5/db2/web/DB2KerberosTestServlet.java
Labels: noproductcode, CLA Signed

#30851 Fix FAT failures when there is a race condition for doLast method call
  dev/com.ibm.ws.security.acme_fat/build.gradle
  dev/com.ibm.ws.security.authentication.filter_fat/build.gradle
  dev/com.ibm.ws.security.spnego_fat.1/build.gradle
  dev/com.ibm.ws.security.spnego_fat.2/build.gradle
  dev/com.ibm.ws.security.spnego_fat/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.2/build.gradle
  dev/com.ibm.ws.security.wim.adapter.ldap_fat/build.gradle
Labels: noproductcode, CLA Signed, team:Core Security

#30807 Enable InstantOn beta for wssecurity-1.1
  dev/com.ibm.websphere.appserver.features/visibility/public/wsSecurity-1.1/com.ibm.websphere.appserver.wsSecurity-1.1.feature
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/files/features/wsseccbh-1.0.mf
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/files/features/wsseccbh-2.0.mf
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/servers/com.ibm.ws.wssecurity_fat.sample/bootstrap.properties
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/servers/com.ibm.ws.wssecurity_fat.sample/jvm.options
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/servers/com.ibm.ws.wssecurity_fat/bootstrap.properties
  dev/com.ibm.ws.wssecurity_fat.wsscxf.1/publish/servers/com.ibm.ws.wssecurity_fat/jvm.options
  dev/io.openliberty.checkpoint_fat_xmlws/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/LibertyCXFPositivePropertiesTestServer/bootstrap.properties
  dev/io.openliberty.checkpoint_fat_xmlws/publish/servers/LibertyCXFPositivePropertiesTestServer/jvm.options
Labels: CLA Signed

#30771 Netty: Ensure PushBuilder headers are added
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpRequestMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/message/NettyRequestMessage.java
Labels: in:Transport, team:Sirius

#30732 Allow HTTP transport to ignore writes after message is committed
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpChannelConfig.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpConfigConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/inbound/HttpInboundLink.java
Labels: ID Required, ID reviewed, CLA Signed, team:Sirius

#30848 Updating the SSLHandshakeIOCallback to track the SSL handshake errors
  dev/com.ibm.ws.channel.ssl/src/com/ibm/ws/channel/ssl/internal/SSLHandshakeIOCallback.java
Labels: CLA Signed

#30868 corrected Find annotation
  dev/io.openliberty.data.1.0.internal/src/io/openliberty/data/internal/v1_0/Data_1_0.java
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/DataExtension.java
  dev/io.openliberty.data.internal/src/io/openliberty/data/internal/version/DataVersionCompatibility.java
  dev/io.openliberty.jakarta.data.1.1/src/jakarta/data/repository/Find.java
Labels: team:Zombie Apocalypse, CLA Signed

#30832 Enable J2EEManagement as Beta
  dev/com.ibm.websphere.appserver.features/visibility/public/j2eeManagement-1.1/com.ibm.websphere.appserver.j2eeManagement-1.1.feature
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/jvm.options
Labels: CLA Signed

#30870 Update file-based health checks' `/health` directory to be placed under the `server.output.dir` over the `server.config.dir` property.
  dev/io.openliberty.microprofile.health.4.0.internal/src/io/openliberty/microprofile/health40/internal/HealthFileUtils.java
Labels: CLA Signed

#30837 JAX-WS: IllegalArgumentException fix when special characters are used for namespace with combination of monitor-1.0 feature
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/.classpath
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/bnd.bnd
  dev/com.ibm.ws.org.apache.cxf.cxf.rt.management.3.2/src/org/apache/cxf/management/interceptor/ResponseTimeMessageOutInterceptor.java
  dev/io.openliberty.jaxws_fat/.classpath
  dev/io.openliberty.jaxws_fat/bnd.bnd
  dev/io.openliberty.jaxws_fat/fat/src/com/ibm/ws/jaxws22/fat/FATSuite.java
  dev/io.openliberty.jaxws_fat/fat/src/com/ibm/ws/jaxws22/fat/SpecialCharactersTest.java
  dev/io.openliberty.jaxws_fat/publish/servers/com.ibm.ws.jaxws22.specialcharacters_fat/bootstrap.properties
  dev/io.openliberty.jaxws_fat/publish/servers/com.ibm.ws.jaxws22.specialcharacters_fat/server.xml
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/resources/WEB-INF/wsdl/WebServiceWithSpecialCharacters.wsdl
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____$__or/ObjectFactory.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____$__or/SC.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____$__or/SCResponse.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____$__or/package-info.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____/__or/Soap12WebServiceWithSpecialCharactersSoapProxy.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____/__or/Soap12WebServiceWithSpecialCharactersSoapSoapBindingImpl.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____/__or/WebServiceWithSpecialCharacters.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/____/__or/WebServiceWithSpecialCharactersPortType.java
  dev/io.openliberty.jaxws_fat/test-applications/specialcharacters/src/com/ibm/ws/jaxws/special/characters/servlet/SpecialCharacterTestServlet.java
Labels: in:Web Services, CLA Signed, team:Bobcats

#30762 Update Expression Language 6.0 to 11.0.3
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#30838 mpHealth-4.0 backport to EE7 and EE8
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee-10.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee-11.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee-7.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee-8.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee-9.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee.10.0.mp-6.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.mpHealth.4.0.ee.10.0.mp-6.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.org.eclipse.microprofile.health.javax-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mpHealth-4.0/io.openliberty.mpHealth-4.0.feature
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/platform_expected.xml
  dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/platform_expected_WL.xml
  dev/io.openliberty.microprofile.health.3.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30HttpResponseBuilder.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
  dev/io.openliberty.microprofile.health.3.1.internal_fat/build.gradle
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/DefaultOverallStartupStatusUpAppStartupFastTest.java
  dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckFastTest.java
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.classpath
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.project
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/build.gradle
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/fat/src/io/openliberty/microprofile/health40/tck/FATSuite.java
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/fat/src/io/openliberty/microprofile/health40/tck/Health40JavaEETCKLauncher.java
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/servers/Health40JavaxTCKServer/bootstrap.properties
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/servers/Health40JavaxTCKServer/jvm.options
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/servers/Health40JavaxTCKServer/server.xml
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/.gitignore
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/pom.xml
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/health40/test/ArquillianLoadableExtension.java
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/health40/test/URIProviderProducer.java
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/src/test/resources/arquillian.xml
  dev/io.openliberty.microprofile.health.4.0.internal.javax_fat_tck/publish/tckRunner/tck/tck-suite.xml
  dev/io.openliberty.microprofile.health.4.0.internal/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/bnd.bnd
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/build.gradle
  dev/io.openliberty.microprofile.health.4.0.internal_fat_tck/fat/src/io/openliberty/microprofile/health40/tck/Health40TCKLauncher.java
  dev/io.openliberty.microprofile.health.internal_fat.common/.classpath
  dev/io.openliberty.microprofile.health.internal_fat.common/.project
  dev/io.openliberty.microprofile.health.internal_fat.common/.settings/bndtools.core.prefs
  dev/io.openliberty.microprofile.health.internal_fat.common/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.microprofile.health.internal_fat.common/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.microprofile.health.internal_fat.common/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.microprofile.health.internal_fat.common/bnd.bnd
  dev/io.openliberty.microprofile.health.internal_fat.common/src/io/openliberty/microprofile/health/internal_fat/shared/HealthActions.java
  dev/io.openliberty.microprofile.health.internal_fat.common/src/io/openliberty/microprofile/health/internal_fat/shared/package-info.java
  dev/io.openliberty.org.eclipse.microprofile.health.javax/.classpath
  dev/io.openliberty.org.eclipse.microprofile.health.javax/.project
  dev/io.openliberty.org.eclipse.microprofile.health.javax/.settings/bndtools.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.health.javax/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.org.eclipse.microprofile.health.javax/bnd.bnd
  dev/io.openliberty.org.eclipse.microprofile.health.javax/health.4.0.javax.bnd
  dev/io.openliberty.org.eclipse.microprofile.health.javax/resources/rules/mpHealth-javax-renames.properties
Labels: CLA Signed

#30881 Fixing intermittent FAT failure
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryAccessTest.java
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/files/accessServer.xml
  dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_2_fat/publish/servers/TelemetryAccess/server.xml
Labels: noproductcode

#30875 include QueryInfo init failures in introspector output
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/RepositoryImpl.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/RepositoryProducer.java
  dev/io.openliberty.data.internal_fat_errorpaths/fat/src/test/jakarta/data/errpaths/DataIntrospectorTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#30887 fix: millis precision timestamp testing
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, test bug

#30877 Telemetry 2.0: Allow user to disable resource providers
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/FATSuite.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryDisabledProvidersTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/telemetry/DisabledProvidersServlet.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10DisabledProviders/bootstrap.properties
  dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/publish/servers/Telemetry10DisabledProviders/server.xml
  dev/io.openliberty.microprofile.telemetry.2.0.internal/src/io/openliberty/microprofile/telemetry20/internal/info/OpenTelemetryInfoFactoryImpl.java
Labels: CLA Signed

#30882 Fix grpc intermittent error code
  dev/com.ibm.ws.grpc_fat/fat/src/com/ibm/ws/fat/grpc/StoreProducerServletClientTests.java
Labels: in:Transport, in:Web Components, noproductcode, CLA Signed, team:Sirius

#30888 Add test case to show problem with application replace after PR #30730 was merged
  dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/targets/cache/internal/TargetCacheImpl_DataApps.java
  dev/com.ibm.ws.anno_fat/bnd.bnd
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/FATSuite.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/caching/AppReplaceTest.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/ejbs/one/TestReplaceEJB.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/ejbs/two/TestReplaceEJB.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/servlets/one/TestReplaceServlet.java
  dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/servlets/two/TestReplaceServlet.java
  dev/com.ibm.ws.anno_fat/publish/servers/appReplaceTestServer/bootstrap.properties
  dev/com.ibm.ws.anno_fat/publish/servers/appReplaceTestServer/server.xml
Labels: CLA Signed, team:Performance

#30866 Updates for Jakarta Authorization 3.0 implementation
  dev/com.ibm.ws.security.authorization.jacc.ejb/src/com/ibm/ws/security/authorization/jacc/ejb/impl/EJBJaccServiceImpl.java
  dev/com.ibm.ws.security.authorization.jacc.ejb/test/com/ibm/ws/security/authorization/jacc/ejb/impl/EJBJaccServiceImplTest.java
  dev/com.ibm.ws.security.authorization.jacc.web/src/com/ibm/ws/security/authorization/jacc/web/impl/WebJaccServiceImpl.java
  dev/com.ibm.ws.security.authorization.jacc.web/test/com/ibm/ws/security/authorization/jacc/web/impl/WebJaccServiceImplTest.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/PolicyConfigurationManager.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/PolicyConfigurationManagerImpl.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/PolicyContextUtil.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/PolicyProxy.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/common/ProviderServiceProxy.java
  dev/com.ibm.ws.security.authorization.jacc/src/com/ibm/ws/security/authorization/jacc/internal/JaccServiceImpl.java
  dev/com.ibm.ws.security.authorization.jacc/src/io/openliberty/security/authorization/jacc/internal/proxy/ProviderServiceProxyImpl.java
  dev/com.ibm.ws.security.authorization.jacc/test/com/ibm/ws/security/authorization/jacc/internal/JaccServiceImplTest.java
  dev/com.ibm.ws.security.javaeesec.cdi/src/com/ibm/ws/security/javaeesec/cdi/extensions/SecurityContextImpl.java
  dev/com.ibm.ws.security/bnd.bnd
  dev/com.ibm.ws.security/src/com/ibm/ws/security/context/SubjectManager.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/bnd.bnd
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/com/ibm/wsspi/security/authorization/jacc/ProviderService.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/JakartaPolicyFactoryProxyImpl.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/PolicyFactoryImpl.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/PrincipalMapperImpl.java
  dev/io.openliberty.security.authorization.internal.jacc.3.0/src/io/openliberty/security/authorization/jacc/internal/proxy/ProviderServiceProxyImpl.java
  dev/io.openliberty.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/provider/PolicyFactoryImpl.java
  dev/io.openliberty.security.authorization.jacc.testprovider/src/com/ibm/ws/security/authorization/jacc/service/ProviderServiceImpl.java
Labels: CLA Signed, team:Performance

#30880 Test of LOWER(ID(o)) in a Query
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#30889 fix string out of bounds error message
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheApp.java
Labels: noproductcode, CLA Signed
