Repository OpenLiberty/open-liberty, pull requests merged in 2025-08, with the labels that each got.

#32171 Remove MyFaces from FIPS 140-3 custom profiles
  dev/com.ibm.ws.jsf.2.2_fat.2/semeruFips140_3CustomProfile.properties
  dev/com.ibm.ws.jsf.2.2_fat/semeruFips140_3CustomProfile.properties
  dev/com.ibm.ws.jsf.2.3_fat/semeruFips140_3CustomProfile.properties
Labels: noproductcode, FIPS140-3

#32317 More Robust Parsing of MCP Tool Request Parameters
  dev/io.openliberty.mcp.internal/bnd.bnd
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpServlet.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/McpRequest.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/McpToolCallParams.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/McpToolCallRequest.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/parsers/McpRequestParser.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/parsers/McpRequestSubParser.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/requests/parsers/McpToolCallRequestParser.java
  dev/io.openliberty.mcp.internal/test/io/openliberty/mcp/internal/test/MessageParsingTest.java
Labels: CLA Signed

#32321 Update copyright years
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/HttpResponseMessageImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/outbound/HttpOutboundServiceContextImpl.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpBaseMessage.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpConstants.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpRequestMessage.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpResponseMessage.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/channel/HttpServiceContext.java
  dev/com.ibm.ws.transport.http/src/com/ibm/wsspi/http/ee7/HttpInputStreamEE7.java
Labels: in:Transport, team:Sirius

#32338 Netty fix API after update to legacy Request Context classes
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/inbound/NettyTCPReadRequestContext.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/inbound/NettyTCPWriteRequestContext.java
Labels: in:Transport, team:Sirius

#31904 Updates to not include more in autoFVT.zip files than necessary SPNEGO
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
  dev/com.ibm.ws.security.oidc.server_fat.spnego/build.gradle
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/Krb5Helper.java
  dev/com.ibm.ws.security.spnego_fat.1/build.gradle
  dev/com.ibm.ws.security.spnego_fat.2/build.gradle
  dev/com.ibm.ws.security.spnego_fat/build.gradle
Labels: noproductcode, CLA Signed

#32323 Issue #32118 : Fix DuplicateHomeNameException on app restart
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.project
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.settings/bndtools.core.prefs
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.settings/org.eclipse.core.resources.prefs
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/build.gradle
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/cognitiveMetadata.yml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/fat/src/com/ibm/ws/ejbcontainer/singleton/startup/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/fat/src/com/ibm/ws/ejbcontainer/singleton/startup/fat/tests/RestartStartupSingletonTest.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/RestartStartupSingletonServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/RestartStartupSingletonServer/server.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.jar.fail/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.jar.fail/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.jar/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.war.fail/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.war.fail/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources.war/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/src/test/ejbcontainer/restart/singleton/ear/jar/RestartSimpleBindingSingletonEarJarBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/src/test/ejbcontainer/restart/singleton/ear/jar/RestartStartupSingletonEarJarBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonApp.ear/src/test/ejbcontainer/restart/singleton/ear/war/RestartStartupSingletonEarWarBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/resources.fail/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/resources.fail/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/resources.fail/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/resources/META-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonEjb.jar/src/test/ejbcontainer/restart/singleton/jar/RestartStartupSingletonJarBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonIntf.jar/src/test/ejbcontainer/restart/singleton/shared/RestartStartupSingletonLocal.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonIntf.jar/src/test/ejbcontainer/restart/singleton/shared/RestartStartupSingletonRemote.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/resources.fail/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/resources.fail/WEB-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/resources.fail/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/resources/META-INF/permissions.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/resources/WEB-INF/ibm-ejb-jar-bnd.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/src/test/ejbcontainer/restart/singleton/web/RestartSimpleBindingSingletonWarBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/src/test/ejbcontainer/restart/singleton/web/RestartStartupSingletonServlet.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/RestartStartupSingletonWeb.war/src/test/ejbcontainer/restart/singleton/web/RestartStartupSingletonWarBean.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/EJBRuntimeImpl.java
  dev/com.ibm.ws.ejbcontainer/src/com/ibm/ws/ejbcontainer/osgi/internal/naming/EJBLocalNamingHelperImpl.java
Labels: team:Zombie Apocalypse, in:EJB Container, CLA Signed

#32322 Netty beta copyright cleanup jul 31
  dev/com.ibm.ws.transport.http.compression_fat/publish/files/compressionConfig/compression-server.xml
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat.2/fat/src/com/ibm/ws/fat/wc/tests/WCSameSiteCookieAttributeTests.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCServletPathForDefaultMappingFalse.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCTrailersTest.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/listeners/ReadListenerGetTrailers.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/servlets/ServletGetTrailers.java
  dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/TrailersTest.war/src/trailers/servlets/ServletSetTrailers.java
  dev/com.ibm.ws.wsoc/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/WsocReadCallback.java
  dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/outbound/HttpRequestorWsoc10FactoryImpl.java
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.1/publish/files/serversettings/java2Permissions.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.2/publish/files/serversettings/java2Permissions.xml
  dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.5/publish/files/serversettings/java2Permissions.xml
  dev/io.openliberty.wsoc.2.1.internal/src/io/openliberty/wsoc/httprequestor/HttpRequestorWsoc21FactoryImpl.java
Labels: in:Transport, team:Sirius

#32343 Increase allowed timer delay in EJB FAT for Mac OSX
  dev/com.ibm.ws.ejbcontainer.timer.np.config_fat/test-applications/NpTimerConfigRetryWeb.war/src/com/ibm/ws/ejbcontainer/timer/np/config/retry/web/NpTimerConfigRetryServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug

#32330 Netty wc server http unit
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
Labels: in:Transport, noproductcode, CLA Signed, team:Sirius

#32347 Renew lease on test server faster
  dev/com.ibm.ws.transaction.cloud_fat.base/publish/1servers/com.ibm.ws.transaction_ANYDBCLOUD001/server.xml
Labels: noproductcode, CLA Signed

#32348 Update spnego fat kdc container to use randomized port
  dev/com.ibm.ws.security.spnego.fat.common/fat/src/com/ibm/ws/security/spnego/fat/config/Krb5Helper.java
  dev/com.ibm.ws.security.spnego_fat/fat/src/com/ibm/ws/security/spnego/fat/KerberosContainer.java
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/spnego-kdc-server/1.0.0.1/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/spnego-kdc-server/1.0.0.1/docker-entrypoint.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/spnego-kdc-server/1.0.0.1/supervisord.conf
Labels: noproductcode, CLA Signed, team:Core Security

#32349 Have both microProfile-7.0 and 7.1 in webprofile and jakarta 11 zips
  dev/build.image/build.gradle
  dev/build.image/profiles/jakartaee11/features.xml
  dev/build.image/profiles/webProfile11/features.xml
Labels: team:Performance

#32345 Remove gsa.server from pipeline definitions
  .ci-orchestrator/compile.properties
  .ci-orchestrator/compilePersonalRTC.properties
Labels: noproductcode, CLA Signed

#32363 Small cleanup from recent updates
  dev/io.openliberty.microprofile.openapi.internal.common/bnd.bnd
  dev/io.openliberty.org.jctools/.classpath
Labels: team:Performance

#32312 Added in a SHA512 reference for Artifact Downloader
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/InstallUtils.java
Labels: CLA Signed

#32212 Remote FAT
  dev/com.ibm.ws.transaction.fat.util/resources/ourbuckets.txt
  dev/io.openliberty.org.testcontainers/cache/projects
  dev/io.openliberty.transaction.remote_fat/.classpath
  dev/io.openliberty.transaction.remote_fat/.project
  dev/io.openliberty.transaction.remote_fat/.settings/bndtools.core.prefs
  dev/io.openliberty.transaction.remote_fat/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.transaction.remote_fat/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.transaction.remote_fat/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.transaction.remote_fat/bnd.bnd
  dev/io.openliberty.transaction.remote_fat/build.gradle
  dev/io.openliberty.transaction.remote_fat/cognitiveMetadata.yml
  dev/io.openliberty.transaction.remote_fat/fat/src/suite/FATSuite.java
  dev/io.openliberty.transaction.remote_fat/fat/src/tests/EJBTest.java
  dev/io.openliberty.transaction.remote_fat/fat/src/tests/LocalEJBTest.java
  dev/io.openliberty.transaction.remote_fat/fat/src/tests/RemoteEJBTest.java
  dev/io.openliberty.transaction.remote_fat/publish/servers/RemoteEJBClient/bootstrap.properties
  dev/io.openliberty.transaction.remote_fat/publish/servers/RemoteEJBClient/server.xml
  dev/io.openliberty.transaction.remote_fat/publish/servers/RemoteEJBServer/bootstrap.properties
  dev/io.openliberty.transaction.remote_fat/publish/servers/RemoteEJBServer/server.xml
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/client/EJBClient.java
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/ejb/TestBean.java
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/localClient/LocalEJBClient.java
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/remoteClient/RemoteEJBClient.java
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/shared/TestBeanRemote.java
  dev/io.openliberty.transaction.remote_fat/test-applications/remoteEJB/src/shared/Util.java
Labels: noproductcode, CLA Signed

#32368 Use jpackcore to process java dump files on newer Semeru versions
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32388 add comments for using SHA512 message digest algorithm - com.ibm.ws.ui
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/ToolDataAPI.java
  dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
  dev/com.ibm.ws.ui_rest_fat/fat/src/com/ibm/ws/ui/fat/rest/v1/TooldataAPIv1Test.java
Labels: FIPS140-3

#32370 Add EJB test for blockWorkUntilAppStartedWaitTime
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/.classpath
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/bnd.bnd
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/fat/src/com/ibm/ws/ejbcontainer/singleton/startup/fat/FATSuite.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/fat/src/com/ibm/ws/ejbcontainer/singleton/startup/fat/tests/PropertyBlockWorkDefaultTest.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/fat/src/com/ibm/ws/ejbcontainer/singleton/startup/fat/tests/PropertyBlockWorkDisabledTest.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDefaultServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDefaultServer/jvm.options
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDefaultServer/server.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDisabledServer/bootstrap.properties
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDisabledServer/jvm.options
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/publish/servers/PropertyBlockWorkDisabledServer/server.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyIntf.jar/src/singleton/property/shared/BasicSingleton2.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyIntf.jar/src/singleton/property/shared/StartupHelperSingleton.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyIntf.jar/src/singleton/property/shared/TestData.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyNoStartupBean.jar/src/singleton/property/nostartup/ejb/NoStartupHelperSingletonBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyNoStartupBean.jar/src/singleton/property/nostartup/ejb/NoStartupSingletonBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyNoStartupWeb.war/resources/WEB-INF/web.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyNoStartupWeb.war/src/singleton/property/nostartup/web/NoStartupWebSingletonBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyNoStartupWeb.war/src/singleton/property/nostartup/web/TestEJBServletContextListener.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/src/singleton/property/startup/ejb/StartupHelperSingletonBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/src/singleton/property/startup/ejb/StartupSingletonBean.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyTest.war/src/singleton/property/web/AllowWorkNoStartupServlet.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyTest.war/src/singleton/property/web/AllowWorkStartupServlet.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyTest.war/src/singleton/property/web/BlockWorkNoStartupServlet.java
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyTest.war/src/singleton/property/web/BlockWorkStartupServlet.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test debt, CLA Signed

#32391 Copyright correction
  dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/SimpleSSLMultipleServersDefaultLibertySSLConfigTest.java
Labels: in:JAX-RS, noproductcode, CLA Signed

#32405 Handshake error message is required even if tracing is not enabled
  dev/io.openliberty.netty.internal.tls.impl/src/io/openliberty/netty/internal/tls/impl/handler/LibertySslHandler.java
Labels: in:Transport, team:Sirius

#32385 Added a fips check for the wssecurity's older algorithms
  dev/com.ibm.ws.wssecurity.3.4.1/src/com/ibm/ws/wssecurity/signature/SignatureAlgorithms.java
Labels: CLA Signed

#32389 remove unneeded waits in servlet FAT
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat.2/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/AsyncWriteListenerHttpUnit.java
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
Labels: in:Transport, team:Sirius

#32429 Remove commented code in NettyChain
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/NettyChain.java
Labels: in:Transport, team:Sirius

#32436 Cleanup unused handler
  dev/com.ibm.ws.transport.http/src/io/openliberty/http/netty/timeout/TimeoutEventHandler.java
  dev/com.ibm.ws.transport.http/src/io/openliberty/http/netty/timeout/exception/UnknownTimeoutException.java
Labels: in:Transport, team:Sirius

#32398 Add Java 25 specific FAT
  dev/cnf/oss_ibm.maven
  dev/io.openliberty.java.internal_fat/build.gradle
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/FATSuite.java
  dev/io.openliberty.java.internal_fat/fat/src/io/openliberty/java/internal/fat/Java25Test.java
  dev/io.openliberty.java.internal_fat/publish/servers/java25-server/bootstrap.properties
  dev/io.openliberty.java.internal_fat/publish/servers/java25-server/jvm.options
  dev/io.openliberty.java.internal_fat/publish/servers/java25-server/server.xml
  dev/io.openliberty.java.internal_fat/src-reference/java25/io/openliberty/java/internal/TestApp.java
  dev/io.openliberty.java.internal_fat/src-reference/java25/io/openliberty/java/internal/TestService.java
  dev/io.openliberty.java.internal_fat/src-reference/java25/io/openliberty/java/internal/package-info.java
  dev/io.openliberty.java.internal_fat/src-reference/java25/module-info.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, java 25

#32366 Use date-time cache for HTTP access logging
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogCurrentTime.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogStartTime.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/internal/HttpDateFormatImpl.java
Labels: team:Performance, performance

#32325 Inconsistent parent last delegation
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ClassLoaderRef.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/LibertyLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ParentLastClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ShadowClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ThreadContextClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ThreadContextClassLoaderForBundles.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/UnifiedClassLoader.java
  dev/com.ibm.ws.classloading_classpath_fat/test-applications/testParentLibraryInconsistent.war/src/io/openliberty/classloading/parent/library/inconsistent/test/app/ParentLibraryInconsistentTestServlet.java
Labels: CLA Signed

#32414 Clean up servlet 31 fat build gradle to remove apache.commons.lang3
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat.2/build.gradle
  dev/com.ibm.ws.webcontainer.servlet.3.1_fat/build.gradle
Labels: noproductcode

#32442 Scheduled Asynchronous Method on a Repository
  dev/io.openliberty.data.internal_fat/bnd.bnd
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Participants.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32341 Detect missing java:comp/env and allow DefaultDataSource
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal_fat_datastore/fat/src/test/jakarta/data/datastore/DataStoreTest.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/DataStoreTestEJB.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/EJBModuleDefaultDSEntity.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/EJBModuleDefaultDSRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreTestApp].module[DataStoreTestEJB.jar].databaseStore[java.comp.DefaultDataSource]_JakartaData.ddl
Labels: team:Zombie Apocalypse, ID reviewed, CLA Signed, L2 Reviewed

#32454 Remove unused codeline
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/netty/cookie/CookieTests.java
Labels: in:Transport, team:Sirius

#32435 Update ldap krb5 container ports to be dynamic
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/bnd.bnd
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/CommonBindTest.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/KerberosContainer.java
  dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/krb5/LdapContainer.java
  dev/io.openliberty.org.testcontainers/cache/externals
  dev/io.openliberty.org.testcontainers/cache/images
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-kdc-server/1.0.0.1/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-kdc-server/1.0.0.1/docker-entrypoint.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-kdc-server/1.0.0.1/supervisord.conf
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/Dockerfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/config_files/admin.keyfile
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/config_files/full_example_com.ldif
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/config_files/kerberos.openldap.ldif
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/config_files/ldap.conf
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/config_files/slapd.ldif
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/docker-entrypoint.sh
  dev/io.openliberty.org.testcontainers/resources/openliberty/testcontainers/ldap-server/3.18/supervisord.conf
Labels: noproductcode, CLA Signed, team:Core Security

#32434 Update jdbc loadfromapp FAT to work in Java 25+
  dev/com.ibm.ws.jdbc_fat_loadfromapp/fat/src/com/ibm/ws/jdbc/fat/loadfromapp/JDBCLoadFromAppTest.java
  dev/com.ibm.ws.jdbc_fat_loadfromapp/publish/servers/com.ibm.ws.jdbc.fat.loadfromapp/jvm.options
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed, java 25

#32426 java.lang.StringBuffer.append failed because session is null
  dev/com.ibm.ws.session.cache_fat/test-applications/sessionCacheApp/src/session/cache/web/SessionCacheTestServlet.java
Labels: noproductcode, CLA Signed

#32452 Add permissions for getProtectionDomian
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPrecedenceAfterAppTest/server.xml
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/libPrecedenceBeforeAppTest/server.xml
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastLibraryInconsistentTest/server.xml
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/patchLibWarTest/server.xml
Labels: noproductcode, CLA Signed

#32404 Update check Bearer in Authorization header
  dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/http/AuthUtils.java
  dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/http/AuthUtilsTest.java
  dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticator.java
  dev/com.ibm.ws.security.openidconnect.client/test/com/ibm/ws/security/openidconnect/client/internal/AccessTokenAuthenticatorTest.java
Labels: CLA Signed

#32467 Experimental comparison package was removed and no longer exists
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.1/io.openliberty.data-1.1.feature
Labels: team:Zombie Apocalypse, CLA Signed

#32379 Added a comment for using older algorithms
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java
Labels: CLA Signed

#32443 Limit connection queue
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/HttpPipelineInitializer.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/http2/LibertyNettyALPNHandler.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/inbound/LibertyHttpRequestHandler.java
  dev/com.ibm.ws.transport.http/test/com/ibm/ws/netty/pipelining/HttpRequestPipeliningTests.java
Labels: in:Transport, team:Sirius

#32473 Update MpTelemetry JaegerQueryClient to retry before throwing exception
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/jaeger/JaegerQueryClient.java
Labels: noproductcode

#32461 Stop servers simultaneously
  dev/com.ibm.ws.transaction.fat.util/src/com/ibm/ws/transaction/fat/util/FATUtils.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.8.ee10/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.8/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.8/fat/src/tests/DBRerouteRecoveryTest.java
  dev/com.ibm.ws.wsat.recovery_fat.multi.9/fat/src/tests/ReroutePeerRecoveryTest.java
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: noproductcode, CLA Signed

#32501 DataSourceDefinition on Repository in an EJB Module
  dev/io.openliberty.data.internal_fat_datastore/publish/servers/io.openliberty.data.internal.fat.datastore/server.xml
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/DataEJBAppBean.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreEJBApp/src/test/jakarta/data/datastore/ejbapp/EJBAppDSDRepo.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/web/DataStoreTestServlet.java
  dev/io.openliberty.data.internal_fat_datastore/test-resources/ddl/application[DataStoreEJBApp].databaseStore[java.app.jdbc.DataSourceDef]_JakartaData.ddl
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32518 Initialize cloud FATs the modern way
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.6/fat/src/suite/FATSuite.java
Labels: noproductcode

#32481 add supported OS check for apacheDSAndKDC in jcache SPNEGO tests
  dev/io.openliberty.jcache.internal_fat.hazelcast/fat/src/io/openliberty/jcache/internal/fat/testresource/KdcResource.java
Labels: noproductcode, CLA Signed, team:Core Security

#32531 Increase transaction timeout in EJB FAT
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/resources/META-INF/ejb-jar.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/resources/META-INF/ibm-ejb-jar-ext.xml
  dev/com.ibm.ws.ejbcontainer.singleton.startup_fat/test-applications/SingletonPropertyStartupBean.jar/src/singleton/property/startup/ejb/StartupSingletonBean.java
Labels: team:Zombie Apocalypse, in:EJB Container, noproductcode, test bug, CLA Signed

#32255 split ibm jdk and semeru fips 140-3 checks
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
  dev/com.ibm.ws.kernel.service/test/com/ibm/ws/common/crypto/CryptoUtilsTest.java
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: CLA Signed, FIPS140-3

#32493 disable unstable infinispan tests
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheOneServerTest.java
  dev/com.ibm.ws.session.cache_fat_infinispan/fat/src/com/ibm/ws/session/cache/fat/infinispan/SessionCacheTimeoutTest.java
Labels: noproductcode, CLA Signed

#32556 Overlay Netty 4.1.124.final
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/http2/LibertyUpgradeCodec.java
  dev/io.openliberty.io.netty/src/io/netty/handler/codec/http/HttpDecoderConfig.java
  dev/io.openliberty.io.netty/src/io/netty/handler/codec/http2/AbstractHttp2ConnectionHandlerBuilder.java
  dev/io.openliberty.io.netty/src/io/netty/handler/codec/http2/Http2ConnectionHandler.java
  dev/io.openliberty.io.netty/src/io/netty/handler/codec/http2/HttpToHttp2ConnectionHandlerBuilder.java
Labels: in:Transport, team:Sirius

#31975 Update JWT metatype to allow usage of ECDH-ES algorithm
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/short_ES256private-key-pkcs#8.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/short_ES256private-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/publish/shared/securityKeys/short_ES256public-key.pem
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/utils/JwtKeyTools.java
  dev/com.ibm.ws.security.fat.common.jwt/src/com/ibm/ws/security/fat/common/jwt/utils/JwtTokenBuilderUtils.java
  dev/com.ibm.ws.security.fat.common/publish/shared/securityKeys/ec_key.p12
  dev/com.ibm.ws.security.fat.common/publish/shared/securityKeys/ec_trust.p12
  dev/com.ibm.ws.security.jwt/bnd.bnd
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.jwt/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/BuilderImpl.java
  dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JweHelper.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwkEndpointValidationUrlTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderAPIConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/fat/src/com/ibm/ws/security/jwt/fat/builder/JwtBuilderApiBasicTests.java
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/goodSSLSettings.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientBasicConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/publish/shared/config/jwtBuilderClientConfigTestsConfig.xml
  dev/com.ibm.ws.security.jwt_fat.builder/semeruFips140_3CustomProfile.properties
  dev/com.ibm.ws.security.jwt_fat.consumer/fat/src/com/ibm/ws/security/jwt/fat/consumer/JwtConsumerApiConfigTests.java
  dev/com.ibm.ws.security.jwt_fat.consumer/publish/servers/com.ibm.ws.security.jwt_fat.consumer/configs/server_configTests.xml
  dev/com.ibm.ws.security.jwt_fat.consumer/semeruFips140_3CustomProfile.properties
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientConsumeUserinfoTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientEncryptionTests.java
  dev/com.ibm.ws.security.oidc.client_fat.2/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcPropagationConsumeUserinfoTests.java
  dev/com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest/fat/src/com/ibm/ws/security/openidconnect/server/fat/jaxrs/config/noOP/NoOPEncryptionRSServerTests.java
  dev/com.ibm.ws.security.social_fat/fat/src/com/ibm/ws/security/social/fat/commonTests/Social_EncryptionTests.java
Labels: ID reviewed, L2 ReviewNotRequired, FIPS140-3

#32579 Fix criu probe check for Java 24+
  dev/fattest.simplicity/src/componenttest/topology/impl/JavaInfo.java
Labels: noproductcode, CLA Signed

#32471 adding polling in checkForRolledLogsAtTime
  dev/io.openliberty.transport.http_fat/fat/src/io/openliberty/transport/http_fat/AccessLogRolloverTest.java
Labels: noproductcode

#32581 Explicitly set (lower non default) timeout for open telemetry exporter
  dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/FATSuite.java
Labels: noproductcode, CLA Signed

#32586 Set maximum java level for OpenAPI proxy support tests
  dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ProxySupportTest.java
Labels: noproductcode

#30011 Decrease minimum jwk rotation time
  dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKProvider.java
  dev/com.ibm.ws.security.common.jsonwebkey/test/com/ibm/ws/security/common/jwk/impl/JWKProviderTest.java
  dev/com.ibm.ws.security.oidc.server_fat.oidc/fat/src/com/ibm/ws/security/openidconnect/server/fat/oidc/FATSuite.java
  dev/com.ibm.ws.security.oidc.server_fat/fat/src/com/ibm/ws/security/openidconnect/server/fat/BasicTests/OIDC/OIDCJWKRotationTest.java
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/provider_OAuthConfigSample_jwkRotationTime_0m.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/files/serversettings/provider_OAuthConfigSample_jwkRotationTime_1m.xml
  dev/com.ibm.ws.security.oidc.server_fat/publish/servers/com.ibm.ws.security.openidconnect.server-1.0_fat/configs/server_jwkRotationTime.xml
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
  dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/metatype/metatype.xml
Labels: CLA Needed, ID reviewed, CLA Signed, L2 ReviewNotRequired

#32598 Remove the experimental updateBy pattern
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestServlet.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Houses.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Packages.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/Vehicles.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/DataExperimentalServlet.java
  dev/io.openliberty.data.internal_fat_exp/test-applications/DataExperimentalWeb/src/test/jakarta/data/experimental/web/Reservations.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Counties.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/Creatures.java
  dev/io.openliberty.data.internal_fat_validation/test-applications/DataValidationTestApp/src/test/jakarta/data/validation/web/DataValidationTestServlet.java
Labels: team:Zombie Apocalypse, CLA Signed

#32543 create unittest 'test' forlder to com.ibm.ws.ui
  dev/com.ibm.ws.ui/.classpath
  dev/com.ibm.ws.ui/bnd.bnd
  dev/com.ibm.ws.ui/build.gradle
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/FilterTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/RequestNLSTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceDebuggerTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceDebuggerWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceProviderTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceProviderWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceProvider_ErrorTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceProvider_ErrorWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/persistence/FilePersistenceProvider_SynchronousTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/APIRootTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/AdminCenterRouterTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/CommonJSONRESTHandlerTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/CommonJSONRESTHandlerWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/exceptions/BadRequestExceptionTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/exceptions/MethodNotSupportedExceptionTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/exceptions/NoSuchResourceExceptionTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/exceptions/RESTExceptionTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/CatalogAPITest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/CatalogAPIWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/ToolDataAPITest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/ToolDataAPIWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/ToolboxAPITest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/ToolboxAPIWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/V1RootTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/utils/FeatureUtilsTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/utils/URLUtilsTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/rest/v1/utils/UtilsRootTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/BookmarkTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/BookmarkWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/CatalogTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/CatalogWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/FeatureToolTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/FeatureToolWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/MessageTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/MessageWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/POJOLoaderServiceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/POJOLoaderServiceWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/PlainTextLoaderServiceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/PlainTextLoaderServiceWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/ToolEntryTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/ToolEntryWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/ToolboxTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/pojo/ToolboxWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/utils/ContextAwarePrintStreamFilter.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/utils/LogRule.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/utils/URLUtilityImplTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/utils/URLUtilityImplWithTraceTest.java
  dev/com.ibm.ws.ui/test/com/ibm/ws/ui/internal/v1/utils/UtilsTest.java
  dev/com.ibm.ws.ui/test/test/common/JSONablePOJOTestCase.java
Labels: CLA Signed, FIPS140-3

#32615 Fix spelling of because
  dev/com.ibm.ws.http2.client/src/com/ibm/ws/http2/test/Http2Client.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsConnectionImpl.java
  dev/com.ibm.ws.messaging.jms.2.0/src/com/ibm/ws/sib/api/jms/impl/JmsJMSContextImpl.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/gd/GuaranteedTargetStream.java
  dev/com.ibm.ws.messaging.runtime/src/com/ibm/ws/sib/processor/impl/CustomProperties.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2StreamProcessor.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java
  dev/com.ibm.ws.wsbytebuffer/src/com/ibm/ws/bytebuffer/internal/WsByteBufferImpl.java
  dev/fattest.simplicity/src/com/ibm/ws/fat/util/browser/WebResponse.java
Labels: in:Web Components, team:Sirius

#32623 Reduce defaultDeliveryDelay value
  dev/com.ibm.ws.messaging.open_jms20deliverydelay_fat/test-applications/DeliveryDelay/src/deliverydelay/web/DeliveryDelayServlet.java
Labels: noproductcode, CLA Signed

#32632 update jdk semeru vendor name
  dev/fattest.simplicity/src/componenttest/rules/SkipJavaSemeruWithFipsEnabled.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyClient.java
  dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java
Labels: noproductcode, CLA Signed

#32644 Fix inconsistent parent delegation
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/LibertyLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ParentLastClassLoader.java
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/ShadowClassLoader.java
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/fat/FATSuite.java
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/fat/ParentLastInconsistentLibraryTests.java
  dev/com.ibm.ws.classloading_classpath_fat/fat/src/io/openliberty/classloading/classpath/fat/ParentLastInconsistentResourceAdaptorTests.java
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastResourceAdaptorInconsistentTest/bootstrap.properties
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastResourceAdaptorInconsistentTest/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastResourceAdaptorInconsistentTest/server.xml
Labels: CLA Signed

#32679 Add missing source directory to .classpath
  dev/io.openliberty.io.netty/.classpath
Labels: noproductcode, team:Performance

#32641 Override virtual=true on ManagedScheduledExecutor
  dev/com.ibm.ws.concurrent/resources/com/ibm/ws/concurrent/resources/CWWKCMessages.nlsprops
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent_fat_no_vt/fat/src/test/concurrent/no/vt/ConcurrentVirtualThreadsDisabledTest.java
  dev/com.ibm.ws.concurrent_fat_no_vt/publish/servers/com.ibm.ws.concurrent.fat.no.vt/server.xml
  dev/com.ibm.ws.concurrent_fat_no_vt/test-applications/ConcurrentNoVTWeb/src/test/concurrent/no/vt/web/ConcurrentVTDisabledServlet.java
  dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
  dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/PolicyExecutorImpl.java
Labels: team:Zombie Apocalypse, noproductcode, ID reviewed, CLA Signed

#32496 Remove workaround of retrying lookups and add debug
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/cdi/FutureEMBuilder.java
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/DataTestEJB.java
  dev/io.openliberty.data.internal_fat_datastore/test-applications/DataStoreTestApp/src/test/jakarta/data/datastore/ejb/StartupSingletonEJB.java
  dev/io.openliberty.data.internal_fat_global/test-applications/DataGlobalRestApp/src/test/jakarta/data/global/rest/DataGlobalRestApp.java
Labels: team:Zombie Apocalypse, CLA Signed

#32684 Update fats to indicate they require Java 11
  dev/com.ibm.ws.transaction.cloud_fat.db2.6/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.derby.6/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.oracle.6/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.6/bnd.bnd
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.6/bnd.bnd
Labels: noproductcode, CLA Signed, team:Performance
