Repository OpenLiberty/open-liberty, pull requests merged in 2025-10, with the labels that each got.

#33000 Modify test AsyncInvokerTestServlet as part of 295046
  dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/bookstore/src/com/ibm/ws/jaxrs20/fat/bookstore/AsyncInvokerTestServlet.java
Labels: in:JAX-RS, noproductcode

#32932 Fix for RTC 306195
  dev/com.ibm.ws.security.token.ltpa_fat/fat/src/com/ibm/ws/security/token/ltpa/fat/LTPAKeyRotationTests.java
Labels: noproductcode

#33016 Count query generation, discovery of the entity identification variable, and parentheses insertion
  dev/io.openliberty.data.internal.persistence/resources/io/openliberty/data/internal/persistence/resources/CWWKDMessages.nlsprops
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryEdit.java
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/QueryInfo.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/Data_1_1_Servlet.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/Fractions.java
Labels: team:Zombie Apocalypse, ID review not needed, CLA Signed

#33037 Entity cleanup and test enablement for #30351
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
Labels: noproductcode, in:JPA, team:Blizzard, CLA Signed

#32537 Add Fips option for CLI commands
  dev/build.image/build.gradle
  dev/build.image/publish/wlp/security/FIPS140-3-Liberty.properties
  dev/build.sharedResources/usrShared/resources/security/semeruFips140_3CustomProfile.properties
  dev/cnf/resources/bin/tool
  dev/cnf/resources/bin/tool.bat
  dev/com.ibm.ws.appclient.boot.ws-client/publish/bin/client
  dev/com.ibm.ws.appclient.boot.ws-client/publish/bin/client.bat
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
  dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat
Labels: CLA Signed, FIPS140-3

#33015 Updates for noship / beta features with IBM APIs
  dev/.gitignore
  dev/com.ibm.websphere.appserver.features/visibility/public/appAuthorization-3.0/io.openliberty.appAuthorization-3.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.1/io.openliberty.data-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/mcpServer-1.0/io.openliberty.mcpServer-1.0.feature
  dev/io.openliberty.data/.classpath
  dev/io.openliberty.data/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data/bnd.bnd
  dev/io.openliberty.data/src/io/openliberty/data/repository/Count.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/Exists.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Add.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Assign.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Divide.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/Multiply.java
  dev/io.openliberty.data/src/io/openliberty/data/repository/update/SubtractFrom.java
  dev/io.openliberty.jacc.3.0/bnd.bnd
  dev/io.openliberty.jakarta.concurrency.3.2_fat_tck/.classpath
  dev/io.openliberty.jakarta.concurrency.3.2_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.classpath
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.mcp/bnd.bnd
  dev/wlp-gradle/subprojects/tasks.gradle
Labels: CLA Signed, team:Performance

#32290 Defect-303179-timeout-fix
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: in:JAX-RS, noproductcode, CLA Signed

#33046 Data 1.1 initial beta
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.data-1.1.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/data-1.1/io.openliberty.data-1.1.feature
Labels: team:Zombie Apocalypse, CLA Signed

#33044 detect and apply override of virtual thread creation
  dev/com.ibm.ws.concurrent/src/com/ibm/ws/concurrent/internal/ManagedThreadFactoryService.java
  dev/com.ibm.ws.concurrent_fat_no_vt/fat/src/test/concurrent/no/vt/ConcurrentVirtualThreadsDisabledTest.java
Labels: team:Zombie Apocalypse, CLA Signed

#32985 Fix netty websocket close
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/inbound/NettyTCPReadRequestContext.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/inbound/NettyTCPWriteRequestContext.java
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/netty/upgrade/NettyServletUpgradeHandler.java
Labels: in:Transport, CLA Signed, team:Sirius

#33051 Revert "Defect-303179-timeout-fix"
  dev/com.ibm.ws.jaxrs.2.x_fat_clientProps/test-applications/cxfClientPropsApp/src/jaxrs2x/cxfClientProps/CxfClientPropsTestServlet.java
Labels: noproductcode

#33056 Gradle updates
  dev/com.ibm.ws.install.featureUtility_fat/build.gradle
  dev/com.ibm.ws.java11_fat/build.gradle
  dev/io.openliberty.java.internal_fat/build.gradle
Labels: noproductcode, team:Performance

#33038 Remove constants and use StartPhase enum
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/ProvisionerConstants.java
  dev/com.ibm.ws.kernel.feature.core/src/com/ibm/ws/kernel/feature/internal/subsystem/FeatureResourceImpl.java
  dev/com.ibm.ws.kernel.feature_fat/test-bundles/test.startphase.condition/src/test/startphase/condition/AbstractTestStartPhaseCondition.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/wsspi/kernel/service/condition/StartPhaseCondition.java
  dev/io.openliberty.threading.virtual.internal/src/io/openliberty/threading/virtual/internal/VirtualThreadOperations.java
Labels: CLA Signed

#32948 Netty OKD Social Fix
  dev/com.ibm.ws.security.oauth.oidc_fat.common/src/com/ibm/ws/security/oauth_oidc/fat/commonTest/CommonTestTools.java
  dev/com.ibm.ws.security.social_fat.okdServiceLogin/fat/src/com/ibm/ws/security/social/fat/okdServiceLogin/commonTests/OKDServiceLogin_GenericTests.java
Labels: noproductcode, CLA Signed

#33059 Update ASM to 9.9
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/com.ibm.ws.org.objectweb.asm/bnd.bnd
  dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
  dev/com.ibm.ws.org.objectweb.asm/src/io/openliberty/asm/ASMHelper.java
  dev/com.ibm.ws.ras.instrument_test/test/com/ibm/ws/ras/RasTransformTest.java
Labels: team:Zombie Apocalypse, java 26

#33063 Updating liberty arquillian to 2.1.3 in Jakarata Validation TCK
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/ValidationTckLauncher.java
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/publish/tckRunner/tck/pom.xml
Labels: noproductcode

#32654 OL changes for Bring Your Own AES
  dev/com.ibm.ws.config/bnd.bnd
  dev/com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/variables/AbstractLibertyVariable.java
  dev/com.ibm.ws.crypto.passwordutil/bnd.bnd
  dev/com.ibm.ws.crypto.passwordutil/resources/com/ibm/ws/crypto/util/internal/resources/Messages.nlsprops
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/AESKeyManager.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/AesConfigFileParser.java
  dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/ws/crypto/util/PasswordCipherUtil.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
  dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/ws/crypto/util/AESKeyManagerTest.java
  dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/archive/FilteredDirEntryConfig.java
  dev/com.ibm.ws.kernel.service/src/com/ibm/ws/common/crypto/CryptoUtils.java
  dev/com.ibm.ws.logging.core/src/com/ibm/wsspi/logging/SensitiveIntrospector.java
  dev/com.ibm.ws.security.utility/bnd.bnd
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityMessages.nlsprops
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/SecurityUtility.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/BaseCommandTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/ConfigureFIPSTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateLTPAKeysTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/EncodeTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/GenerateAesKeyTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/HelpTask.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/BaseCommandTaskTest.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/CreateLTPAKeysTaskTest.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/EncodeTaskTest.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/tasks/GenerateAesKeyTest.java
Labels: ID reviewed, CLA Signed, L2 Reviewed
