Repository OpenLiberty/open-liberty, pull requests merged in 2025-09, with the labels that each got.

#32701 virtual=true is not allowed in server.xml for Java SE 17
  dev/com.ibm.ws.concurrent_fat_no_vt/fat/src/test/concurrent/no/vt/ConcurrentVirtualThreadsDisabledTest.java
  dev/com.ibm.ws.concurrent_fat_no_vt/test-applications/ConcurrentNoVTWeb/src/test/concurrent/no/vt/web/ConcurrentVTDisabledServlet.java
Labels: team:Zombie Apocalypse, noproductcode

#32703 Use Java EE name application name for applicationStopped
  dev/io.openliberty.data.internal.persistence/src/io/openliberty/data/internal/persistence/DataProvider.java
Labels: bug, team:Zombie Apocalypse

#32702 Tolerate Exception FFDC output just for serviceability
  dev/com.ibm.ws.transaction.cloud_fat.base/fat/src/tests/CloudFATServletClient.java
Labels: noproductcode

#32712 Do not include local.sharedLib for Open Liberty FAT classpath
  dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
Labels: noproductcode, CLA Signed, team:Performance

#32711 Updates after EclipseLink beta 10
  dev/io.openliberty.data.internal_fat/test-applications/DataTestApp/src/test/jakarta/data/web/RomanNumeral.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32727 Revert "Revert "Initialize cloud FATs the modern way""
  dev/com.ibm.ws.transaction.cloud_fat.db2.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.db2.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.derby.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.oracle.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.postgresql.6/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.0/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.1/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.2/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.3/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.4/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.5/fat/src/suite/FATSuite.java
  dev/com.ibm.ws.transaction.cloud_fat.sqlserver.6/fat/src/suite/FATSuite.java
Labels: noproductcode

#32676 Update Expression Language 6.0 to 11.0.10
  dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
  dev/cnf/oss_dependencies.maven
  dev/io.openliberty.jakarta.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.jakarta.expressionLanguage.6.0/build.gradle
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/bnd.bnd
  dev/io.openliberty.org.apache.jasper.expressionLanguage.6.0/build.gradle
Labels: in:Web Components, CLA Signed, team:Sirius, jakartaEE11

#32746 Create test bucket for possible beta
  dev/io.openliberty.data.internal_fat_1_1/.classpath
  dev/io.openliberty.data.internal_fat_1_1/.project
  dev/io.openliberty.data.internal_fat_1_1/.settings/bndtools.core.prefs
  dev/io.openliberty.data.internal_fat_1_1/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.data.internal_fat_1_1/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.data.internal_fat_1_1/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.data.internal_fat_1_1/bnd.bnd
  dev/io.openliberty.data.internal_fat_1_1/build.gradle
  dev/io.openliberty.data.internal_fat_1_1/fat/src/test/jakarta/data/v1_1/Data_1_1_Test.java
  dev/io.openliberty.data.internal_fat_1_1/fat/src/test/jakarta/data/v1_1/FATSuite.java
  dev/io.openliberty.data.internal_fat_1_1/publish/servers/io.openliberty.data.internal.fat.1.1/bootstrap.properties
  dev/io.openliberty.data.internal_fat_1_1/publish/servers/io.openliberty.data.internal.fat.1.1/server.xml
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/Data_1_1_Servlet.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/Fraction.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/Fractions.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/_Fraction.java
  dev/io.openliberty.data.internal_fat_1_1/test-applications/Data_1_1_App/src/test/jakarta/data/v1_1/web/_Fraction_Digits.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32771 Update TCKRunner
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
Labels: noproductcode, CLA Signed

#32784 Fixes #32782 - remove unusable SAML SHA128 signatureMethodAlgorithm
  dev/com.ibm.ws.security.saml.websso.2.0/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/rs/RsSamlConfigImpl.java
Labels: team:Security SSO, FIPS140-3

#32785 Retry featureUtility with verbose flag
  dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
Labels: noproductcode

#32742 Add GenAI assistance code check job
  .ci-orchestrator/pb.yml
Labels: noproductcode, CLA Signed

#32682 POST request with Long Content-Length is not supported in beta.
  dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/netty/pipeline/inbound/LibertyHttpObjectAggregator.java
Labels: in:Transport, team:Sirius

#32786 Add xml-apis to the list of required libs
  dev/com.ibm.ws.security.oidc.client_fat.spnego/build.gradle
Labels: noproductcode, team:Performance

#32510 io.openliberty.mpRestClient.4.0_fat - step 1, 2, 3
  dev/io.openliberty.mpRestClient.4.0_fat/bnd.bnd
  dev/io.openliberty.mpRestClient.4.0_fat/cognitiveMetadata.yml
  dev/io.openliberty.mpRestClient.4.0_fat/fat/src/io/openliberty/mpRestClient/fat/FATSuite.java
  dev/io.openliberty.mpRestClient.4.0_fat/fat/src/io/openliberty/mpRestClient/fat/MultipartTest.java
  dev/io.openliberty.mpRestClient.4.0_fat/fat/src/io/openliberty/mpRestClient/fat/PrototypeTest.java
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.multipartLocal/bootstrap.properties
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.multipartLocal/server.xml
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.multipartRemote/bootstrap.properties
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.multipartRemote/server.xml
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.prototypeLocal/bootstrap.properties
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.prototypeLocal/server.xml
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.prototypeRemote/bootstrap.properties
  dev/io.openliberty.mpRestClient.4.0_fat/publish/servers/io.openliberty.mpRestClient.fat.prototypeRemote/server.xml
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipart/src/io/openliberty/mpRestClient/fat/multipart/MultipartApplication.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipart/src/io/openliberty/mpRestClient/fat/multipart/MultipartResource.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/resources/multipart/test-file1.txt
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/resources/multipart/test-file2.txt
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/src/io/openliberty/mpRestClient/fat/multipartClient/FileManagerClient.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/src/io/openliberty/mpRestClient/fat/multipartClient/MultipartClientTestServlet.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/src/resources/multipart/test-file1.txt
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/multipartClientApp/src/resources/multipart/test-file2.txt
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/prototype/src/io/openliberty/mpRestClient/fat/prototype/PrototypeApplication.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/prototype/src/io/openliberty/mpRestClient/fat/prototype/PrototypeResource.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/prototypeClientApp/src/io/openliberty/mpRestClient/fat/prototypeClient/BasicClientTestServlet.java
  dev/io.openliberty.mpRestClient.4.0_fat/test-applications/prototypeClientApp/src/io/openliberty/mpRestClient/fat/prototypeClient/BasicServiceClient.java
Labels: in:JAX-RS, noproductcode

#32685 Increase app undeploy timeout in io.openliberty.jakarta.validation.3.1_fat_tck
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/ValidationTckLauncher.java
Labels: noproductcode, CLA Signed

#32805 Updates from recent merges
  dev/com.ibm.ws.jpa.container.v32_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.mcp.internal/bnd.bnd
  dev/io.openliberty.mcp.internal_fat/cognitiveMetadata.yml
  dev/io.openliberty.mcp/bnd.bnd
Labels: CLA Signed, team:Performance

#32845 Merge changes from MCP feature branch
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpCdiExtension.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpProtocolVersion.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpServlet.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpTransport.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/SpecialArgumentType.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/ToolMetadata.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/responses/McpInitializeResult.java
  dev/io.openliberty.mcp.internal/test/io/openliberty/mcp/internal/test/MCPServerToolsListTest.java
  dev/io.openliberty.mcp.internal/test/io/openliberty/mcp/internal/test/MessageParsingTest.java
  dev/io.openliberty.mcp.internal/test/io/openliberty/mcp/internal/test/ToolMetadataTestUtility.java
  dev/io.openliberty.mcp.internal_fat/build.gradle
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/FATSuite.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/lifecycle/tests/BeanLifecycleTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/protocol/ProtocolVersionTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/CancellationTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/DeploymentProblemTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/ExpectedAppFailureValidator.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/ToolErrorHandlingTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/ToolTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/basicToolApp/BasicTools.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/businessExceptionApp/CustomBusinessException.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/businessExceptionApp/ToolErrorHandlingTools.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/businessExceptionApp/UnwrappedBusinessException.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/deploymentErrorApps/DuplicateSpecialArgsErrorTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/deploymentErrorApps/DuplicateToolErrorTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/deploymentErrorApps/DuplicateToolErrorTest2.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/deploymentErrorApps/InvalidSpecialArgsErrorTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/deploymentErrorApps/ToolArgValidationTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/utils/HttpTestUtils.java
Labels: CLA Signed

#32821 fix: avoid NPE in ConcurrencyExtension
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ConcurrencyExtension.java
  dev/io.openliberty.concurrent.internal.cdi/src/io/openliberty/concurrent/internal/cdi/ManagedThreadFactoryBean.java
Labels: team:Zombie Apocalypse, CLA Signed

#32811 Remove beta guards for overrideLibrary references
  dev/com.ibm.ws.app.manager.module/src/com/ibm/ws/app/manager/module/internal/DeployedAppInfoBase.java
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/visTestServer/jvm.options
  dev/com.ibm.ws.cdi.visibility_fat/publish/servers/visTestServerAddWarCPToEar/jvm.options
  dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/classloader.properties
  dev/com.ibm.ws.classloading/resources/OSGI-INF/metatype/classloader.xml
  dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/overrideLibWarTest/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastLibraryInconsistentTest/jvm.options
  dev/com.ibm.ws.classloading_classpath_fat/publish/servers/parentLastResourceAdaptorInconsistentTest/jvm.options
  dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/DataSourceResourceFactoryBuilder.java
  dev/com.ibm.ws.jdbc_fat/publish/servers/com.ibm.ws.jdbc.fat/jvm.options
  dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/SharedLibClassesContainerInfoAdapter.java
Labels: ID reviewed

#32790 PH68082: Decrement the handle count that was incremented during getConnection
  dev/com.ibm.ws.jca.cm/src/com/ibm/ejs/j2c/ConnectionManager.java
Labels: CLA Signed

#32880 Update Persistence 3.2 CDI code and TCK to be Java 17
  dev/com.ibm.ws.jpa.container.v32.cdi/.classpath
  dev/com.ibm.ws.jpa.container.v32.cdi/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.container.v32.cdi/bnd.bnd
  dev/com.ibm.ws.jpa.container.v32_fat_tck/.classpath
  dev/com.ibm.ws.jpa.container.v32_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/com.ibm.ws.jpa.container.v32_fat_tck/bnd.bnd
Labels: CLA Signed, team:Performance

#32877 feat: allow test servlets to have a minimum java level
  dev/com.ibm.ws.concurrent_fat_cdi/fat/src/com/ibm/ws/concurrent/cdi/fat/ConcurrentCDITest.java
  dev/fattest.simplicity/src/componenttest/annotation/TestServlet.java
  dev/fattest.simplicity/src/componenttest/annotation/processor/TestServletProcessor.java
  dev/fattest.simplicity/test/componenttest/annotation/processor/TestServletProcessorTests.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32887 Like and NotLike constraints will always supply escape character
  dev/io.openliberty.data.1.1.internal/src/io/openliberty/data/internal/v1_1/Data_1_1.java
  dev/io.openliberty.jakarta.data.1.1/src/jakarta/data/constraint/Like.java
  dev/io.openliberty.jakarta.data.1.1/src/jakarta/data/constraint/LikeRecord.java
  dev/io.openliberty.jakarta.data.1.1/src/jakarta/data/constraint/NotLike.java
  dev/io.openliberty.jakarta.data.1.1/src/jakarta/data/constraint/NotLikeRecord.java
Labels: team:Zombie Apocalypse

#32884 add annotation to skip on ZOS
  dev/com.ibm.ws.jpa.container.v32_fat_tck/fat/src/io/openliberty/jpaContainer/v32/tck/JPAContainerV32Launcher.java
Labels: noproductcode

#32868 fix: skip db2 and sqlserver for testExtractDate
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/bnd.bnd
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/models/Showtime.java
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
  dev/io.openliberty.data.internal_fat_jpa/bnd.bnd
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode

#32765 Fixes intermittent FAT timeouts for `testAttributeAdded` under the EE 11 + MicroProfile 7.1 repeat.
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinOtelCollectorTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/tests/ZipkinTest.java
  dev/io.openliberty.microprofile.telemetry.1.0.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/internal/utils/TestConstants.java
Labels: noproductcode

#32855 Fix SHA512 MessageDigest not available
  dev/com.ibm.ws.install/src/com/ibm/ws/install/InstallException.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
  dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
Labels: regression, release bug

#32722 update saml for 400 request header too large
  dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
  dev/com.ibm.ws.security.saml.websso.2.0/test/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfoTest.java
Labels: CLA Signed, release bug

#32922 Skipping Jakarta Validation TCK run in windows
  dev/io.openliberty.jakarta.validation.3.1_fat_tck/fat/src/io/openliberty/jakarta/validation/tck/ValidationTckLauncher.java
Labels: noproductcode, CLA Signed

#32942 Set ebcShortlist to jenkins-child.yml and increase timeout to 1d
  .ci-orchestrator/steps/determineFATsNeeded.yml
Labels: noproductcode, CLA Signed

#32901 Fix spelling errors in wsspi webcontainer package
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/extension/ExtensionFactory.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/metadata/WebComponentMetaData.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/metadata/WebModuleMetaData.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/servlet/GenericServletWrapper.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/BufferedServletOutputStream.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/BufferedWriter.java
  dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/RequestUtils.java
Labels: in:Web Components, team:Sirius

#32933 reproduction of 29460 with EntityManager
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/Segments.java
Labels: team:Zombie Apocalypse, noproductcode

#32949 Enable Spring-4.0 Transactions WAR Tests
  dev/io.openliberty.springboot.fat40.transactions.app/build.gradle
  dev/io.openliberty.springboot.fat40_fat/build.gradle
  dev/io.openliberty.springboot.fat40_fat/fat/src/com/ibm/ws/springboot/support/fat/FATSuite.java
  dev/io.openliberty.springboot.fat40_fat/fat/src/com/ibm/ws/springboot/support/fat/JTAAppTests40War.java
Labels: noproductcode

#32941 Remove io.openliberty.io.netty.ssl from sipServlet-1.1 feature
  dev/com.ibm.websphere.appserver.features/visibility/public/sipServlet-1.1/com.ibm.websphere.appserver.sipServlet-1.1.feature
Labels: in:Transport, CLA Signed, team:Sirius

#32951 Implements EXTRACT(DATE FROM X) clause in DB2 through overlay
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
  dev/io.openliberty.persistence.3.2.thirdparty/bnd.bnd
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/DB2Platform.java
Labels: in:JPA, team:Blizzard

#32958 Tests for EXTRACT function with different field type identifiers
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartapersistence/src/io/openliberty/jpa/persistence/tests/web/JakartaPersistenceServlet.java
Labels: noproductcode, in:JPA, team:Blizzard

#32904 Spring Boot 4.0 feature beta edition
  dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.springBoot40ServerSupport.servlet61-1.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.springBootHandler-4.0.feature
  dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-4.0/io.openliberty.springBoot-4.0.feature
  dev/io.openliberty.springboot.fat40_fat/publish/servers/SpringBootTests/jvm.options
Labels: CLA Signed

#32899 Ensure DomainResolverImpl Picks Up Netty
  dev/com.ibm.ws.sipcontainer/resources/OSGI-INF/metatype/metatype.xml
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolverUdpTransport.java
  dev/com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/container/resolver/DomainResolverImpl.java
Labels: in:Transport, team:Sirius

#32961 feat: Create TCK runner for Data 1.1
  dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKRunner.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.classpath
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.gitignore
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.project
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.settings/bndtools.core.prefs
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.settings/org.eclipse.core.resources.prefs
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.settings/org.eclipse.jdt.core.prefs
  dev/io.openliberty.jakarta.data.1.1_fat_tck/.settings/org.eclipse.jdt.ui.prefs
  dev/io.openliberty.jakarta.data.1.1_fat_tck/README.md
  dev/io.openliberty.jakarta.data.1.1_fat_tck/bnd.bnd
  dev/io.openliberty.jakarta.data.1.1_fat_tck/build.gradle
  dev/io.openliberty.jakarta.data.1.1_fat_tck/cognitiveMetadata.yml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataCoreTckLauncher.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataFullTckLauncher.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataStandaloneTckLauncher.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/fat/src/io/openliberty/jakarta/data/tck/DataWebTckLauncher.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/fat/src/io/openliberty/jakarta/data/tck/FATSuite.java
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/defaultServer/.gitkeep
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core.nosql/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core.nosql/jvm.options
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core.nosql/server.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core/jvm.options
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.core/server.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.full/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.full/jvm.options
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.full/server.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.web/bootstrap.properties
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.web/jvm.options
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/servers/io.openliberty.jakarta.data.1.1.web/server.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/tckRunner/platform/pom.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/tckRunner/platform/src/test/resources/arquillian.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/tckRunner/platform/verification.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/tckRunner/pom.xml
  dev/io.openliberty.jakarta.data.1.1_fat_tck/publish/tckRunner/standalone/pom.xml
  dev/io.openliberty.org.testcontainers/cache/projects
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32987 Updates EclipseLink to support EXTRACT(TIME FROM X) in DB2
  dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartapersistence/src/io/openliberty/jpa/persistence/tests/web/JakartaPersistenceServlet.java
  dev/io.openliberty.persistence.3.2.thirdparty/src/org/eclipse/persistence/platform/database/DB2Platform.java
Labels: in:JPA, team:Blizzard, CLA Signed

#32979 GenAI code check also needed in 'Open Liberty Delivery Requirements Verification' pipeline
  .ci-orchestrator/checks.yml
Labels: CLA Signed

#32977 fix: reenable ExtractDate test in Data
  dev/io.openliberty.data.internal_fat_jpa/test-applications/DataJPATestApp/src/test/jakarta/data/jpa/web/DataJPATestServlet.java
Labels: team:Zombie Apocalypse, noproductcode, CLA Signed

#32989 Allow a trailing slash on the MCP endpoint
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpForwardFilter.java
  dev/io.openliberty.mcp.internal/src/io/openliberty/mcp/internal/McpServletInitializer.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/FATSuite.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/tool/McpUrlPathTest.java
  dev/io.openliberty.mcp.internal_fat/fat/src/io/openliberty/mcp/internal/fat/utils/McpClient.java
Labels: CLA Signed

#32320 create new configureFIPS task for securityUtility
  dev/com.ibm.ws.security.utility.securityutil/bnd.bnd
  dev/com.ibm.ws.security.utility/bnd.bnd
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityMessages.nlsprops
  dev/com.ibm.ws.security.utility/resources/com/ibm/ws/security/utility/resources/UtilityOptions.nlsprops
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/IFileUtility.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/SecurityUtility.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/ConfigureFIPSTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/tasks/HelpTask.java
  dev/com.ibm.ws.security.utility/src/com/ibm/ws/security/utility/utils/FileUtility.java
  dev/com.ibm.ws.security.utility/test/com/ibm/ws/security/utility/utils/FileUtilityTest.java
Labels: ID reviewed, CLA Signed, FIPS140-3
